using System.Collections.Concurrent;
using System.Data.Common;
using System.Globalization;
using March7thHoney.Configuration;
using March7thHoney.Database.Account;
using March7thHoney.Database.Generated;
using March7thHoney.Database.Quests;
using March7thHoney.Internationalization;
using March7thHoney.Util;
using Microsoft.Data.Sqlite;
using MySqlConnector;

namespace March7thHoney.Database;

/// <summary>
///     In-memory entity cache backed by per-entity stores generated by DatabaseStoreGenerator. All data is loaded
///     into <see cref="UidInstanceMap" /> at startup and flushed periodically. Dispatch is by concrete type through
///     the generated registry — no reflection, no SqlSugar (NativeAOT safe).
/// </summary>
public class DatabaseHelper
{
    public static Logger logger = new("Database");
    public static DatabaseHelper? Instance;
    public static readonly ConcurrentDictionary<int, List<BaseDatabaseDataHelper>> UidInstanceMap = [];
    private static readonly HashSet<int> DirtyUids = [];
    private static readonly object DirtyLock = new();
    public static long LastSaveTick = DateTime.UtcNow.Ticks;
    public static Thread? SaveThread;
    public static bool LoadAccount;
    public static bool LoadAllData;

    private static bool _mysql;
    private static string _connString = "";

    public DatabaseHelper()
    {
        Instance = this;
    }

    private static DbConnection Open()
    {
        DbConnection conn = _mysql ? new MySqlConnection(_connString) : new SqliteConnection(_connString);
        conn.Open();
        return conn;
    }

    public void Initialize()
    {
        logger.Info(I18NManager.Translate("Server.ServerInfo.LoadingItem", I18NManager.Translate("Word.Database")));
        var config = ConfigManager.Config;
        switch (config.Database.DatabaseType)
        {
            case "sqlite":
                SQLitePCL.Batteries_V2.Init();
                var f = new FileInfo(config.Path.DatabasePath + "/" + config.Database.DatabaseName);
                if (!f.Exists && f.Directory is { Exists: false }) f.Directory.Create();
                _mysql = false;
                _connString = $"Data Source={f.FullName}";
                break;
            case "mysql":
                _mysql = true;
                var db = config.Database;
                EnsureMySqlDatabase(db);
                _connString =
                    $"Server={db.MySqlHost};Port={db.MySqlPort};Database={db.MySqlDatabase};Uid={db.MySqlUser};Pwd={db.MySqlPassword};";
                break;
            default:
                logger.Error("Unsupported database type");
                return;
        }

        using var conn = Open();
        foreach (var store in EntityStores.Map.Values) store.EnsureTable(conn);

        // Load account data first so the dispatch server can start accepting logins.
        LoadType(conn, typeof(AccountData));
        foreach (var account in GetAllInstanceFromMap<AccountData>() ?? []) account.SyncPermissionsWithRole();
        LoadAccount = true;

        foreach (var type in EntityStores.Map.Keys)
        {
            if (type == typeof(AccountData)) continue;
            LoadType(conn, type);
        }

        WarmupFormatters();

        LastSaveTick = DateTime.UtcNow.Ticks;
        SaveThread = new Thread(() =>
        {
            // Sleep yields a GC safepoint; a tight loop here spins safepoint-free under NativeAOT and deadlocks GC.
            while (true)
            {
                CalcSaveDatabase();
                Thread.Sleep(1000);
            }
        });
        SaveThread.Start();

        LoadAllData = true;
    }

    // Pre-resolve MemoryPack formatters bottom-up at startup; the first populated serialization otherwise does deep re-entrant resolution that crashes under NativeAOT.
    private static void WarmupFormatters()
    {
        try
        {
            var enh = new Avatar.EnhanceInfo(0);
            enh.SkillTree[1] = 1;
            MemoryPack.MemoryPackSerializer.Serialize(enh);
            var item = new Inventory.ItemData();
            item.SubAffixes.Add(new Inventory.ItemSubAffix { Id = 1, Count = 1, Step = 1 });
            MemoryPack.MemoryPackSerializer.Serialize(item);
            MemoryPack.MemoryPackSerializer.Serialize(new List<Inventory.ItemData> { item });
            var path = new Avatar.PathInfo(1) { EquipData = item };
            path.EnhanceInfos[0] = enh;
            path.Relic[1] = 1;
            MemoryPack.MemoryPackSerializer.Serialize(path);
            var fa = new Avatar.FormalAvatarInfo { BaseAvatarId = 1, AvatarId = 1 };
            fa.PathInfos[1] = path;
            MemoryPack.MemoryPackSerializer.Serialize(fa);
            MemoryPack.MemoryPackSerializer.Serialize(new List<Avatar.FormalAvatarInfo> { fa });
            var sp = new Avatar.SpecialAvatarInfo { BaseAvatarId = 1, AvatarId = 1, SpecialAvatarId = 1 };
            sp.PathInfos[1] = path;
            MemoryPack.MemoryPackSerializer.Serialize(new List<Avatar.SpecialAvatarInfo> { sp });
            var old = new Avatar.OldAvatarInfo { AvatarId = 1 };
            old.PathInfoes[1] = path;
            old.SkillTree[1] = 1;
            old.SkillTreeExtra[1] = new Dictionary<int, int> { { 1, 1 } };
            MemoryPack.MemoryPackSerializer.Serialize(new List<Avatar.OldAvatarInfo> { old });
            var li = new Lineup.LineupInfo { BaseAvatars = [new Lineup.LineupAvatarInfo { BaseAvatarId = 1 }] };
            MemoryPack.MemoryPackSerializer.Serialize(li);
            MemoryPack.MemoryPackSerializer.Serialize(new Dictionary<int, Lineup.LineupInfo> { { 0, li } });
        }
        catch (Exception e)
        {
            logger.Error("WarmupFormatters failed", e);
        }
    }

    private static void EnsureMySqlDatabase(DatabaseConfig db)
    {
        using var conn = new MySqlConnection(
            $"Server={db.MySqlHost};Port={db.MySqlPort};Uid={db.MySqlUser};Pwd={db.MySqlPassword};");
        conn.Open();
        using var cmd = conn.CreateCommand();
        cmd.CommandText = $"CREATE DATABASE IF NOT EXISTS `{db.MySqlDatabase}`";
        cmd.ExecuteNonQuery();
    }

    private static void LoadType(DbConnection conn, Type type)
    {
        if (!EntityStores.Map.TryGetValue(type, out var store)) return;
        foreach (var inst in store.LoadAll(conn))
        {
            var list = UidInstanceMap.GetOrAdd(inst.Uid, static _ => []);
            lock (list) list.Add(inst);
        }
    }

    public T? GetInstance<T>(int uid) where T : class
    {
        var list = UidInstanceMap.GetOrAdd(uid, static _ => []);
        lock (list) return list.OfType<T>().FirstOrDefault();
    }

    public T GetInstanceOrCreateNew<T>(int uid) where T : BaseDatabaseDataHelper, new()
    {
        var instance = GetInstance<T>(uid);
        if (instance != null) return instance;

        instance = new T { Uid = uid };
        SaveInstance(instance);
        return instance;
    }

    public static List<T>? GetAllInstance<T>() where T : class
    {
        return GetAllInstanceFromMap<T>();
    }

    public static List<T>? GetAllInstanceFromMap<T>() where T : class
    {
        var result = new List<T>();
        foreach (var list in UidInstanceMap.Values)
            lock (list)
                result.AddRange(list.OfType<T>());
        return result;
    }

    public static void SaveInstance<T>(T instance) where T : BaseDatabaseDataHelper
    {
        if (EntityStores.Map.TryGetValue(instance.GetType(), out var store))
        {
            using var conn = Open();
            store.Insert(conn, instance);
        }

        var list = UidInstanceMap.GetOrAdd(instance.Uid, static _ => []);
        lock (list) list.Add(instance);
    }

    public static void SaveDatabaseType<T>(T instance) where T : BaseDatabaseDataHelper
    {
        try
        {
            if (!EntityStores.Map.TryGetValue(instance.GetType(), out var store)) return;
            using var conn = Open();
            store.Update(conn, instance);
        }
        catch (Exception e)
        {
            logger.Error("An error occurred while saving the database", e);
        }
    }

    /// <summary>
    ///     Flag a uid's in-memory data as needing a flush. Thread-safe — game threads call this concurrently with the
    ///     save thread's drain. Replaces the old unsynchronized <c>ToSaveUidList.Add</c>; the backing set dedups, so the
    ///     prior <c>SafeAdd</c> / <c>Contains</c> guards are no longer needed.
    /// </summary>
    public static void MarkDirty(int uid)
    {
        lock (DirtyLock) DirtyUids.Add(uid);
    }

    /// <summary>Drop a uid's dirty flag after it has been flushed or its data deleted.</summary>
    public static void ClearDirty(int uid)
    {
        lock (DirtyLock) DirtyUids.Remove(uid);
    }

    /// <summary>
    ///     Atomically take and clear the current dirty set. MarkDirty calls that race a flush land in the freshly
    ///     emptied set and survive to the next cycle, instead of being lost by a blanket Clear().
    /// </summary>
    private static int[] DrainDirty()
    {
        lock (DirtyLock)
        {
            if (DirtyUids.Count == 0) return [];
            var snapshot = new int[DirtyUids.Count];
            DirtyUids.CopyTo(snapshot);
            DirtyUids.Clear();
            return snapshot;
        }
    }

    public void CalcSaveDatabase()
    {
        if (LastSaveTick + TimeSpan.TicksPerMinute * 5 > DateTime.UtcNow.Ticks) return;
        SaveDatabase();
    }

    public void SaveDatabase()
    {
        // Drained up front so concurrent MarkDirty calls during the flush are kept for the next cycle.
        var uids = DrainDirty();

        DbConnection? conn = null;
        try
        {
            conn = Open();
            var prev = DateTime.Now;
            Exec(conn, "BEGIN");

            foreach (var uid in uids)
                if (UidInstanceMap.TryGetValue(uid, out var value))
                    lock (value)
                        foreach (var inst in value)
                            if (EntityStores.Map.TryGetValue(inst.GetType(), out var store))
                                store.Update(conn, inst);

            Exec(conn, "COMMIT");

            var t = (DateTime.Now - prev).TotalSeconds;
            logger.Info(I18NManager.Translate("Server.ServerInfo.SaveDatabase",
                Math.Round(t, 2).ToString(CultureInfo.InvariantCulture)));
        }
        catch (Exception e)
        {
            logger.Error("An error occurred while saving the database", e);
            // Roll back so the pooled connection isn't returned mid-transaction.
            if (conn != null)
                try { Exec(conn, "ROLLBACK"); }
                catch { /* no active transaction */ }
            // Re-flag the failed batch so it retries next cycle (matches the old "only clear on success" behaviour).
            foreach (var uid in uids) MarkDirty(uid);
        }
        finally
        {
            conn?.Dispose();
        }

        LastSaveTick = DateTime.UtcNow.Ticks;
    }

    private static void Exec(DbConnection conn, string sql)
    {
        using var cmd = conn.CreateCommand();
        cmd.CommandText = sql;
        cmd.ExecuteNonQuery();
    }

    public void SaveUidData(int uid)
    {
        try
        {
            if (!UidInstanceMap.TryGetValue(uid, out var value)) return;
            using var conn = Open();
            lock (value)
                foreach (var inst in value)
                    if (EntityStores.Map.TryGetValue(inst.GetType(), out var store))
                        store.Update(conn, inst);

            ClearDirty(uid);
        }
        catch (Exception e)
        {
            logger.Error($"An error occurred while saving gameplay data for uid {uid}", e);
        }
    }

    public void DeleteUidGameplayData(int uid)
    {
        if (!UidInstanceMap.TryGetValue(uid, out var value)) return;
        using var conn = Open();
        lock (value)
        {
            foreach (var inst in value.Where(i => i is not AccountData).ToList())
                if (EntityStores.Map.TryGetValue(inst.GetType(), out var store))
                    store.Delete(conn, uid);

            value.RemoveAll(instance => instance is not AccountData);
        }

        ClearDirty(uid);
    }

    public void DeleteInstance<T>(T instance) where T : BaseDatabaseDataHelper
    {
        if (EntityStores.Map.TryGetValue(instance.GetType(), out var store))
        {
            using var conn = Open();
            store.Delete(conn, instance.Uid);
        }

        if (UidInstanceMap.TryGetValue(instance.Uid, out var value))
            lock (value) value.Remove(instance);
        ClearDirty(instance.Uid);
    }

    public void DeleteUidData(int uid)
    {
        if (!UidInstanceMap.TryGetValue(uid, out var value)) return;

        using (var conn = Open())
        {
            lock (value)
                foreach (var inst in value.ToList())
                    if (EntityStores.Map.TryGetValue(inst.GetType(), out var store))
                        store.Delete(conn, uid);
        }

        UidInstanceMap.TryRemove(uid, out _);
        ClearDirty(uid);
    }

    public void UpgradeDatabase()
    {
        logger.Info("Upgrading database...");
        foreach (var instance in GetAllInstance<MissionData>() ?? []) instance.MoveFromOld();
    }
}
