syntax = "proto3";

// MergeFrom: 0x1B9C8B50
// WriteTo: 0x1B9C4E90
// obf: EBIPBHFLPHL
message GateServer {
    string lua_url = 3;
    bool IHDIGMMDNLI = 11;
    bool forbid_recharge = 1986;
    bool close_redeem_code = 903;
    string ban_appeal_url = 658;
    bool enable_upload_battle_log = 69;
    string login_white_msg = 790;
    string grid_fight_game_ref_color_header_key = 1340;
    bool enable_save_replay_file = 487;
    string PMHDHPMDDLK = 468;
    string asset_bundle_url = 15;
    string rogue_tourn_build_ref_api_req_color_header_value = 1061;
    string JCPEEKKJIPM = 2;
    string IAGFFDBPGBA = 989;
    string player_return_questionnaire_b_url = 1936;
    string anniv3rd_live_recorded = 1743;
    string web_tool_url = 982;
    bool watermark_enable = 48;
    bool JLDIBCBGPIP = 1568;
    string online_replay_upload_url = 939;
    string online_replay_download_url = 1162;
    string grid_fight_game_ref_cdn_url = 551;
    uint32 retcode = 14;
    string hot_point_url = 784;
    string i_fix_patch_revision = 1657;
    string MJIENPDBNFB = 2044;
    uint32 asb_relogin_type = 12;
    bool mtp_switch = 1045;
    string official_community_url = 523;
    string JCJOEPOJBAM = 501;
    string PGKFOKJKGOF = 796;
    uint32 rogue_tourn_notice_pic_type = 346;
    string JCOFKFAKMDC = 494;
    string temporary_maintenance_url = 1206;
    string asb_relogin_desc = 4;
    string anniv3rd_overseas = 106;
    string grid_fight_game_ref_h_5_url = 1852;
    string redeem_code_url = 266;
    string cloud_game_url = 1917;
    bool event_tracking_open = 1515;
    string operation_feedback_url = 159;
    string asset_bundle_url_android = 1774;
    string player_return_questionnaire_a_url = 1458;
    string rogue_tourn_build_ref_static_data_url_prefix = 1468;
    string BCIOOBNPHGL = 5;
    string predownload_update_url = 1553;
    string anniv3rd_live_inprogress = 1316;
    bool enable_design_data_bundle_version_update = 7;
    string FCOILMFFMJA = 1647;
    bool network_diagnostic = 2047;
    string grid_fight_game_ref_color_header_value = 946;
    string community_activity_url = 1976;
    string anniv3rd_book = 360;
    string anniv2nd_callback = 543;
    string rogue_magic_h_5_url = 310;
    string anniv2nd_concert = 1596;
    int64 stop_begin_time = 9;
    uint32 port = 6;
    string custom_service_url = 1744;
    string anniv3rd_live_mainpage = 363;
    string stop_desc = 13;
    bool ftc_switch = 148;
    string AEJGMLPNMOM = 1301;
    bool ios_exam = 1021;
    string KPNOAPMIOKJ = 297;
    string anniv2nd_book = 546;
    repeated string MPCMHGLIPNO = 1908;
    bool use_tcp = 1871;
    bool EJEADIFDKBD = 241;
    uint32 cdn_ipv_6_enable = 1605;
    bool android_middle_package_enable = 726;
    string anniv2nd_os = 1288;
    string ifix_url = 2038;
    string region_name = 1;
    int64 stop_end_time = 8;
    string game_start_customer_service_url = 540;
    string server_description = 1991;
    string rogue_tourn_build_ref_h_5_url = 768;
    string grid_fight_intro_h_5_url = 743;
    string anniv3rd_fes = 441;
    string MDANNHDNILP = 1439;
    uint32 rogue_tourn_notice_id = 335;
    uint32 design_data_relogin_type = 10;
    string rogue_tourn_h_5_url = 1838;
    string rogue_tourn_build_ref_api_req_color_header_key = 268;
    string design_data_relogin_desc = 371;
    string anniv3rd_callback = 699;
}
