using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace March7thHoney.SourceGen;

/// <summary>
///     Scans every <c>[CommandInfo]</c> command class and emits a static registry containing, per command:
///     a reconstructed <c>CommandInfoAttribute</c>, a fresh instance, and a strongly-typed dispatch table of
///     <c>[CommandMethod]</c>/<c>[CommandDefault]</c> invokers (compiled delegates, no reflection). Replaces the
///     reflection-based discovery and <c>MethodInfo.Invoke</c> path in <c>CommandManager</c>.
/// </summary>
[Generator]
public sealed class CommandRegistryGenerator : IIncrementalGenerator
{
    private const string CommandInfoAttribute = "March7thHoney.Command.CommandInfoAttribute";
    private const string CommandMethodAttribute = "March7thHoney.Command.CommandMethodAttribute";
    private const string CommandDefaultAttribute = "March7thHoney.Command.CommandDefaultAttribute";

    private const string ICommand = "global::March7thHoney.Command.ICommand";
    private const string CommandArg = "global::March7thHoney.Command.Command.CommandArg";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commands = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax cls && cls.AttributeLists.Count > 0 &&
                                    !cls.Modifiers.Any(m => m.ValueText == "abstract"),
                static (ctx, _) =>
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol symbol)
                        return null;
                    var info = symbol.GetAttributes()
                        .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == CommandInfoAttribute);
                    return info == null ? null : Extract(symbol, info);
                })
            .Where(static x => x != null)
            .Select(static (x, _) => x!)
            .Collect();

        context.RegisterSourceOutput(commands, static (spc, items) =>
        {
            if (items.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace March7thHoney.Command.Command;");
            sb.AppendLine();
            sb.AppendLine("internal static class GeneratedCommandRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    public static GeneratedCommand[] Build()");
            sb.AppendLine("    {");
            sb.AppendLine("        return new GeneratedCommand[]");
            sb.AppendLine("        {");
            foreach (var cmd in items)
            {
                sb.AppendLine("            new GeneratedCommand(");
                sb.AppendLine($"                new global::March7thHoney.Command.CommandInfoAttribute({cmd.InfoArgs}),");
                sb.AppendLine($"                new {cmd.TypeFqn}(),");
                if (cmd.Methods.Count == 0)
                {
                    sb.AppendLine("                global::System.Array.Empty<GeneratedCommandMethod>(),");
                }
                else
                {
                    sb.AppendLine("                new GeneratedCommandMethod[]");
                    sb.AppendLine("                {");
                    foreach (var m in cmd.Methods)
                    {
                        sb.AppendLine("                    new GeneratedCommandMethod(");
                        sb.AppendLine($"                        {SymbolDisplay.FormatLiteral(m.Name, true)},");
                        sb.AppendLine(
                            $"                        new global::March7thHoney.Command.CommandMethodAttribute({m.ConditionLiteral}).Conditions,");
                        sb.AppendLine($"                        {Invoker(cmd.TypeFqn, m)}),");
                    }

                    sb.AppendLine("                },");
                }

                if (cmd.Default == null)
                {
                    sb.AppendLine("                null),");
                }
                else
                {
                    sb.AppendLine("                new GeneratedCommandMethod(");
                    sb.AppendLine($"                    {SymbolDisplay.FormatLiteral(cmd.Default.Name, true)},");
                    sb.AppendLine(
                        "                    new global::System.Collections.Generic.List<global::March7thHoney.Command.CommandCondition>(),");
                    sb.AppendLine($"                    {Invoker(cmd.TypeFqn, cmd.Default)})),");
                }
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedCommandRegistry.g.cs", sb.ToString());
        });
    }

    private static string Invoker(string typeFqn, MethodEntry m)
    {
        var call = $"(({typeFqn})c).{m.Name}(a)";
        return m.ReturnsVoid
            ? $"static ({ICommand} c, {CommandArg} a) => {{ {call}; return null; }}"
            : $"static ({ICommand} c, {CommandArg} a) => {call}";
    }

    private static CommandEntry Extract(INamedTypeSymbol symbol, AttributeData info)
    {
        var typeFqn = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var infoArgs = BuildInfoArgs(info);

        var methods = new List<MethodEntry>();
        MethodEntry? defaultMethod = null;

        foreach (var member in symbol.GetMembers().OfType<IMethodSymbol>())
        {
            foreach (var attr in member.GetAttributes())
            {
                var name = attr.AttributeClass?.ToDisplayString();
                if (name == CommandMethodAttribute)
                {
                    // Only the string-condition constructor is supported.
                    if (attr.ConstructorArguments.Length == 1 &&
                        attr.ConstructorArguments[0].Value is string condition)
                        methods.Add(new MethodEntry(member.Name, member.ReturnsVoid,
                            SymbolDisplay.FormatLiteral(condition, true)));
                }
                else if (name == CommandDefaultAttribute)
                {
                    defaultMethod = new MethodEntry(member.Name, member.ReturnsVoid, "");
                }
            }
        }

        return new CommandEntry(typeFqn, infoArgs, methods, defaultMethod);
    }

    private static string BuildInfoArgs(AttributeData info)
    {
        string name = "", description = "", usage = "", keyword = "", permission = "";
        string[] alias = System.Array.Empty<string>();

        var ctor = info.AttributeConstructor;
        if (ctor != null)
            for (var i = 0; i < ctor.Parameters.Length && i < info.ConstructorArguments.Length; i++)
            {
                var arg = info.ConstructorArguments[i];
                switch (ctor.Parameters[i].Name)
                {
                    case "name": name = arg.Value as string ?? ""; break;
                    case "description": description = arg.Value as string ?? ""; break;
                    case "usage": usage = arg.Value as string ?? ""; break;
                    case "keyword": keyword = arg.Value as string ?? ""; break;
                    case "permission": permission = arg.Value as string ?? ""; break;
                    case "alias":
                        alias = arg.Values.Select(v => v.Value as string ?? "").ToArray();
                        break;
                }
            }

        foreach (var named in info.NamedArguments)
            switch (named.Key)
            {
                case "Name": name = named.Value.Value as string ?? name; break;
                case "Description": description = named.Value.Value as string ?? description; break;
                case "Usage": usage = named.Value.Value as string ?? usage; break;
                case "Keyword": keyword = named.Value.Value as string ?? keyword; break;
                case "Permission": permission = named.Value.Value as string ?? permission; break;
            }

        var aliasExpr = alias.Length == 0
            ? "global::System.Array.Empty<string>()"
            : "new string[]{" + string.Join(", ", alias.Select(a => SymbolDisplay.FormatLiteral(a, true))) + "}";

        return string.Join(", ",
            SymbolDisplay.FormatLiteral(name, true),
            SymbolDisplay.FormatLiteral(description, true),
            SymbolDisplay.FormatLiteral(usage, true),
            aliasExpr,
            SymbolDisplay.FormatLiteral(keyword, true),
            SymbolDisplay.FormatLiteral(permission, true));
    }

    private sealed class MethodEntry(string name, bool returnsVoid, string conditionLiteral)
    {
        public string Name { get; } = name;
        public bool ReturnsVoid { get; } = returnsVoid;
        public string ConditionLiteral { get; } = conditionLiteral;
    }

    private sealed class CommandEntry(string typeFqn, string infoArgs, List<MethodEntry> methods, MethodEntry? @default)
    {
        public string TypeFqn { get; } = typeFqn;
        public string InfoArgs { get; } = infoArgs;
        public List<MethodEntry> Methods { get; } = methods;
        public MethodEntry? Default { get; } = @default;
    }
}
