using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace March7thHoney.SourceGen;

/// <summary>
///     Scans every class annotated with <c>[Opcode(cmdId)]</c> and emits a static registry that maps the
///     command id to a freshly constructed handler instance. Replaces the reflection-based discovery in
///     <c>HandlerManager.Init</c> so packet dispatch is NativeAOT-safe (no Assembly.GetTypes / Activator).
/// </summary>
[Generator]
public sealed class HandlerRegistryGenerator : IIncrementalGenerator
{
    private const string OpcodeAttribute = "March7thHoney.GameServer.Server.Packet.Opcode";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider.ForAttributeWithMetadataName(
                OpcodeAttribute,
                static (node, _) => node is ClassDeclarationSyntax { } cls &&
                                    !cls.Modifiers.Any(m => m.ValueText == "abstract"),
                static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var attr = ctx.Attributes[0];
                    var cmdId = attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int v
                        ? v
                        : 0;
                    var fqn = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    return (cmdId, fqn);
                })
            .Collect();

        context.RegisterSourceOutput(handlers, static (spc, items) =>
        {
            if (items.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace March7thHoney.GameServer.Server.Packet;");
            sb.AppendLine();
            sb.AppendLine("internal static class GeneratedHandlerRegistry");
            sb.AppendLine("{");
            sb.AppendLine(
                "    public static global::System.Collections.Generic.Dictionary<int, Handler> Build()");
            sb.AppendLine("    {");
            sb.AppendLine(
                $"        var d = new global::System.Collections.Generic.Dictionary<int, Handler>({items.Length});");
            foreach (var (cmdId, fqn) in items.OrderBy(x => x.cmdId))
                sb.AppendLine($"        d[{cmdId}] = new {fqn}();");
            sb.AppendLine("        return d;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedHandlerRegistry.g.cs", sb.ToString());
        });
    }
}
