using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace March7thHoney.SourceGen;

/// <summary>
///     Scans classes annotated with <c>[MissionFinishAction(...)]</c> / <c>[MissionFinishType(...)]</c> and emits a
///     static registry that populates <c>MissionManager.ActionHandlers</c> / <c>FinishTypeHandlers</c> directly.
///     Replaces the reflection-based discovery in <c>ServerUtils.InitializeHandlers</c> (Assembly.GetTypes /
///     Activator.CreateInstance) so mission-handler registration is NativeAOT-safe.
/// </summary>
[Generator]
public sealed class MissionHandlerRegistryGenerator : IIncrementalGenerator
{
    private const string ActionAttribute =
        "March7thHoney.GameServer.Game.Mission.FinishAction.MissionFinishActionAttribute";

    private const string TypeAttribute =
        "March7thHoney.GameServer.Game.Mission.FinishType.MissionFinishTypeAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var actions = Collect(context, ActionAttribute);
        var types = Collect(context, TypeAttribute);

        var combined = actions.Combine(types);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var (actionHandlers, typeHandlers) = pair;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace March7thHoney.GameServer.Game.Mission;");
            sb.AppendLine();
            sb.AppendLine("internal static class GeneratedMissionHandlers");
            sb.AppendLine("{");
            sb.AppendLine("    public static void Register()");
            sb.AppendLine("    {");
            foreach (var (enumFqn, value, handlerFqn) in actionHandlers.OrderBy(x => x.value))
                sb.AppendLine(
                    $"        MissionManager.ActionHandlers[(global::{enumFqn}){value}] = new global::{handlerFqn}();");
            foreach (var (enumFqn, value, handlerFqn) in typeHandlers.OrderBy(x => x.value))
                sb.AppendLine(
                    $"        MissionManager.FinishTypeHandlers[(global::{enumFqn}){value}] = new global::{handlerFqn}();");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedMissionHandlers.g.cs", sb.ToString());
        });
    }

    private static IncrementalValueProvider<System.Collections.Immutable.ImmutableArray<(string enumFqn, long value,
        string handlerFqn)>> Collect(IncrementalGeneratorInitializationContext context, string attributeName)
    {
        return context.SyntaxProvider.ForAttributeWithMetadataName(
                attributeName,
                static (node, _) => node is ClassDeclarationSyntax cls &&
                                    !cls.Modifiers.Any(m => m.ValueText == "abstract"),
                static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var attr = ctx.Attributes[0];
                    var arg = attr.ConstructorArguments.Length > 0 ? attr.ConstructorArguments[0] : default;
                    var enumFqn = arg.Type?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                        .Replace("global::", "") ?? "";
                    var value = arg.Value is { } v ? System.Convert.ToInt64(v) : 0L;
                    var handlerFqn = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                        .Replace("global::", "");
                    return (enumFqn, value, handlerFqn);
                })
            .Collect();
    }
}
