// Generated by ts-to-zod
import { z } from "zod";

export const aSConfigMazeSchema = z.object({
  buff_1: z.array(z.number()),
  buff_2: z.array(z.number()),
  maze_buff: z.number(),
});

export const pFConfigMazeSchema = z.object({
  buff: z.array(z.number()),
  maze_buff: z.number(),
});

export const mOCConfigMazeSchema = z.object({
  maze_buff: z.number(),
});

export const avatarConfigMazeSchema = z.object({
  maze_buff: z.array(z.number()),
});

export const configMazeSchema = z.object({
  Avatar: z.record(avatarConfigMazeSchema),
  MOC: z.record(mOCConfigMazeSchema),
  AS: z.record(aSConfigMazeSchema),
  PF: z.record(pFConfigMazeSchema),
});
