// Generated by ts-to-zod
import { z } from "zod";

export const eventBasicRawSchema = z.object({
  param: z.array(z.number()).optional(),
  en: z.string(),
  id: z.string(),
  begin: z.string(),
  end: z.string(),
  live_begin: z.string(),
  live_end: z.string(),
  kr: z.string(),
  cn: z.string(),
  jp: z.string(),
});
