// Generated by ts-to-zod
import { z } from "zod";

export const filterAvatarTypeSchema = z.object({
  name: z.string(),
  path: z.array(z.string()),
  element: z.array(z.string()),
  rarity: z.array(z.string()),
  locale: z.string(),
});

export const filterLightconeTypeSchema = z.object({
  path: z.array(z.string()),
  rarity: z.array(z.string()),
  locale: z.string(),
  name: z.string(),
});

export const filterRelicTypeSchema = z.object({
  locale: z.string(),
  name: z.string(),
});

export const filterMonsterTypeSchema = z.object({
  name: z.string(),
  id: z.string(),
  rarity: z.array(z.string()),
  locale: z.string(),
  weak: z.array(z.string()),
});
