// Generated by ts-to-zod
import { z } from "zod";

export const lightConeBasicRawSchema = z.object({
  rank: z.string(),
  baseType: z.string(),
  en: z.string(),
  desc: z.string(),
  kr: z.string(),
  cn: z.string(),
  jp: z.string(),
});
