// Generated by ts-to-zod
import { z } from "zod";

export const monsterBasicRawSchema = z.object({
  rank: z.string(),
  camp: z.string().nullable(),
  icon: z.string(),
  child: z.array(z.number()),
  weak: z.array(z.string()),
  en: z.string(),
  desc: z.string(),
  kr: z.string(),
  cn: z.string(),
  jp: z.string(),
});
