// Generated by ts-to-zod
import { z } from "zod";

export const partDataSchema = z.object({
  Name: z.string(),
  Desc: z.string(),
  Story: z.string(),
});

export const requireBonusSchema = z.object({
  Desc: z.string(),
  ParamList: z.array(z.number()),
});

export const relicDetailSchema = z.object({
  Name: z.string(),
  Icon: z.string(),
  Parts: z.record(partDataSchema),
  RequireNum: z.record(requireBonusSchema),
});
