syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AiPamAskSettlementScNotify {
    MDGIOENHBEJ EIADGIMDNMO = 10;
}

message AiPamMotionScNotify {
    repeated string BLCCBDPODFM = 5;
}

message AiPamResponseFeedbackCommentCsReq {
    uint32 OLLBLNAGMPC = 9;
    string IMNOJNCGGNI = 4;
}

message AiPamResponseFeedbackCommentScRsp {
    uint32 retcode = 9;
}

message AiPamResponseFeedbackCsReq {
    bool NMMJBGFDNAI = 8;
    FKNKNLGMACL role = 1;
    bool IAJAOMAKAHA = 2;
}

message AiPamResponseFeedbackScRsp {
    FKNKNLGMACL role = 5;
    bool NMMJBGFDNAI = 14;
    uint32 retcode = 4;
    bool IAJAOMAKAHA = 3;
}

message AiPamSendMsgCsReq {
    bool GFIJJLNOOOM = 5;
    bool LOODCBCFNMJ = 10;
    MessageChatData content = 9;
    bool CLDBFBNOLNP = 8;
    FKNKNLGMACL role = 3;
}

message AiPamSendMsgScRsp {
    uint32 retcode = 5;
    FKNKNLGMACL role = 4;
}

message BALHBDBHHON {
    GOECDMPJMCM OAMKPPGDDIM = 1;
}

enum CmdAiPamType {
    CmdAiPamType_CmdAiTypeNone = 0;
    CmdAiPamType_GetAiPamNextQuestionCsReq = 9522;
    CmdAiPamType_GetAiPamChatInfoCsReq = 9538;
    CmdAiPamType_ReturnAiPamFunctionCallDataScRsp = 9541;
    CmdAiPamType_GetAiPamChatHistoryCsReq = 9524;
    CmdAiPamType_AiPamResponseFeedbackCommentScRsp = 9501;
    CmdAiPamType_GetAiPamChatHistoryScRsp = 9508;
    CmdAiPamType_UpdateAiPamSettingsScRsp = 9518;
    CmdAiPamType_UpdateAiPamAvatarCultivationStateCsReq = 9504;
    CmdAiPamType_TriggerAiPamSpeakCsReq = 9507;
    CmdAiPamType_TriggerAiPamSpeakScRsp = 9514;
    CmdAiPamType_AiPamResponseFeedbackCsReq = 9517;
    CmdAiPamType_ReturnAiPamFunctionCallDataCsReq = 9547;
    CmdAiPamType_AiPamMotionScNotify = 9525;
    CmdAiPamType_AiPamAskSettlementScNotify = 9510;
    CmdAiPamType_UpdateAiPamAvatarCultivationStateScRsp = 9535;
    CmdAiPamType_AiPamResponseFeedbackCommentCsReq = 9512;
    CmdAiPamType_GetAiPamChatInfoScRsp = 9521;
    CmdAiPamType_AiPamResponseFeedbackScRsp = 9519;
    CmdAiPamType_GetAiPamNextQuestionScRsp = 9532;
    CmdAiPamType_AiPamSendMsgCsReq = 9536;
    CmdAiPamType_AiPamSendMsgScRsp = 9529;
    CmdAiPamType_RecvAiPamChatEventScNotify = 9544;
    CmdAiPamType_UpdateAiPamSettingsCsReq = 9542;
}

message DEHDGGEDJHI {
    ChatMessageData stop_desc = 1;
}

message DOPJFJCLIAH {
    bool LJOEMLOJDDP = 1;
    bool JLNEBLAKKOB = 2;
}

message FAIFDBLLGKK {
    KDNCOBMFFEB event_type = 1;
    string ACFENKABBKK = 2;
    uint32 JKIHICLOPKM = 3;
    FKNKNLGMACL role = 4;
    DEHDGGEDJHI stop_desc = 11;
    DOPJFJCLIAH LMJCPMFPHLK = 12;
    BALHBDBHHON FHDMHKOMEFO = 13;
    IAGGIFBOFDF FIFCCCJOLNE = 14;
}

enum FKNKNLGMACL {
    FKNKNLGMACL_NLCDGIPGFDJ = 0;
    FKNKNLGMACL_LMBIMAOBGPO = 1;
    FKNKNLGMACL_NPDOGNAPCEE = 2;
}

enum GOECDMPJMCM {
    GOECDMPJMCM_NLCDGIPGFDJ = 0;
    GOECDMPJMCM_IKKJHNHKFOG = 1;
    GOECDMPJMCM_FFBIEEHPKND = 2;
    GOECDMPJMCM_JFNMPEJEIOH = 3;
}

message GetAiPamChatHistoryCsReq {
    uint32 target_side = 8;
}

message GetAiPamChatHistoryScRsp {
    uint32 retcode = 1;
    repeated ChatMessageData JPCMGNGNONJ = 6;
    uint32 target_side = 12;
}

message GetAiPamChatInfoCsReq {
}

message GetAiPamChatInfoScRsp {
    bool AGANFJKBFMA = 10;
    bool OKCIPPLKGCD = 14;
    bool LOCNGFLCENG = 8;
    string ACFENKABBKK = 15;
    repeated FAIFDBLLGKK BJLHDBPPILI = 7;
    uint32 retcode = 9;
    uint32 JKIHICLOPKM = 4;
}

message GetAiPamNextQuestionCsReq {
    FKNKNLGMACL role = 8;
}

message GetAiPamNextQuestionScRsp {
    repeated NEKAOLPJKEE KDOHKGKBFCH = 8;
    uint32 retcode = 11;
    FKNKNLGMACL role = 6;
}

message IAGGIFBOFDF {
}

enum KDNCOBMFFEB {
    KDNCOBMFFEB_NLCDGIPGFDJ = 0;
    KDNCOBMFFEB_BDOEMDGHHEP = 1;
    KDNCOBMFFEB_stop_desc = 2;
    KDNCOBMFFEB_LMJCPMFPHLK = 3;
    KDNCOBMFFEB_FHDMHKOMEFO = 4;
    KDNCOBMFFEB_FCKIHKAIIIJ = 5;
}

message KKNGAGGAJKC {
    string EDMBJCBKBIM = 1;
    string OIBPLFNJOEM = 2;
    string DMHFFKNLILH = 3;
}

message MDGIOENHBEJ {
    string title = 1;
    string OAPACMJOIKC = 2;
    uint32 ENHLKLFLCKG = 3;
    KKNGAGGAJKC tag = 4;
}

message NEKAOLPJKEE {
    string POLADDGLAEH = 1;
}

message RecvAiPamChatEventScNotify {
    FAIFDBLLGKK OOOACLEFDGM = 11;
}

message TriggerAiPamSpeakCsReq {
    uint32 JMPPMNAONHM = 15;
    FKNKNLGMACL role = 1;
}

message TriggerAiPamSpeakScRsp {
    uint32 retcode = 8;
    FKNKNLGMACL role = 15;
    uint32 JMPPMNAONHM = 1;
}

message UpdateAiPamSettingsCsReq {
    bool LOCNGFLCENG = 14;
}

message UpdateAiPamSettingsScRsp {
    uint32 retcode = 1;
    bool LOCNGFLCENG = 11;
}
