syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdAdventureType {
    CmdAdventureType_None = 0;
    CmdAdventureType_CocoonSweepCsReq = 1373;
    CmdAdventureType_FarmElementSweepScRsp = 1365;
    CmdAdventureType_QuickStartCocoonStageScRsp = 1391;
    CmdAdventureType_QuickStartFarmElementCsReq = 1398;
    CmdAdventureType_FarmElementSweepCsReq = 1372;
    CmdAdventureType_QuickStartCocoonStageCsReq = 1356;
    CmdAdventureType_GetFarmStageGachaInfoCsReq = 1379;
    CmdAdventureType_CocoonSweepScRsp = 1399;
    CmdAdventureType_QuickStartFarmElementScRsp = 1326;
    CmdAdventureType_GetFarmStageGachaInfoScRsp = 1339;
}

message CocoonSweepCsReq {
    uint32 cocoon_id = 4;
    uint32 world_level = 15;
}

message CocoonSweepScRsp {
    uint32 NCEFJFOHGBI = 7;
    ItemList multiple_drop_data = 9;
    uint32 retcode = 14;
    ItemList drop_data = 2;
    uint32 cocoon_id = 5;
}

message FarmElementSweepCsReq {
    uint32 world_level = 1;
    uint32 PAOFHFLFFHD = 9;
}

message FarmElementSweepScRsp {
    uint32 retcode = 13;
    ItemList multiple_drop_data = 8;
    uint32 PAOFHFLFFHD = 5;
}

message FarmStageGachaInfo {
    int64 end_time = 5;
    uint32 gacha_id = 3;
    int64 begin_time = 2;
}

message GetFarmStageGachaInfoCsReq {
    repeated uint32 farm_stage_gacha_id_list = 4;
}

message GetFarmStageGachaInfoScRsp {
    repeated FarmStageGachaInfo farm_stage_gacha_info_list = 8;
    uint32 retcode = 4;
}

message QuickStartCocoonStageCsReq {
    uint32 world_level = 7;
    uint32 HECCOBFBJFI = 10;
    NAJKNJLJPEP CBJCKEIGGNL = 14;
    uint32 wave = 9;
    uint32 cocoon_id = 15;
}

message QuickStartCocoonStageScRsp {
    uint32 wave = 10;
    SceneBattleInfo battle_info = 8;
    uint32 cocoon_id = 7;
    uint32 retcode = 4;
}

message QuickStartFarmElementCsReq {
    uint32 HECCOBFBJFI = 8;
    uint32 world_level = 7;
    uint32 PAOFHFLFFHD = 13;
}

message QuickStartFarmElementScRsp {
    uint32 world_level = 1;
    uint32 PAOFHFLFFHD = 8;
    SceneBattleInfo battle_info = 14;
    uint32 retcode = 12;
}
