syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AddAvatarScNotify {
    ItemList reward = 9;
    bool is_new = 15;
    uint32 base_avatar_id = 4;
    AddAvatarSrcState src = 5;
}

enum AddAvatarSrcState {
    ADD_AVATAR_SRC_NONE = 0;
    ADD_AVATAR_SRC_GACHA = 1;
    ADD_AVATAR_SRC_ROGUE = 2;
    ADD_AVATAR_SRC_DELIVERY = 3;
}

message AddMultiPathAvatarScNotify {
    GCALLOJPPIJ ALKDBJEGAGG = 3;
    ItemList reward = 6;
    uint32 avatar_id = 14;
    repeated NKDNFDCFNCP HJMDNLBNPNA = 12;
    bool is_new = 7;
}

message AvatarExpUpCsReq {
    uint32 base_avatar_id = 7;
    ItemCostData item_cost = 13;
}

message AvatarExpUpScRsp {
    uint32 retcode = 4;
    repeated PileItem return_item_list = 7;
}

message AvatarPathChangedNotify {
    MultiPathAvatarType cur_multi_path_avatar_type = 10;
    uint32 base_avatar_id = 7;
}

message AvatarSpecialSkilltreeUnlockScNotify {
    uint32 point_id = 6;
    uint32 avatar_id = 14;
}

enum CFMDKNCDDAL {
    CFMDKNCDDAL_NADPFMGBHDJ = 0;
    CFMDKNCDDAL_GGGLNCBOICD = 1;
}

enum CmdAvatarType {
    CmdAvatarType_None = 0;
    CmdAvatarType_DressAvatarCsReq = 373;
    CmdAvatarType_AvatarExpUpScRsp = 339;
    CmdAvatarType_UnlockSkilltreeScRsp = 391;
    CmdAvatarType_TakeOffAvatarSkinScRsp = 357;
    CmdAvatarType_DelAvatarScNotify = 347;
    CmdAvatarType_AvatarSpecialSkilltreeUnlockScNotify = 369;
    CmdAvatarType_TakePromotionRewardCsReq = 315;
    CmdAvatarType_DressRelicAvatarCsReq = 362;
    CmdAvatarType_UnlockSkilltreeCsReq = 356;
    CmdAvatarType_RankUpAvatarScRsp = 304;
    CmdAvatarType_GetPreAvatarActivityListScRsp = 383;
    CmdAvatarType_AddAvatarScNotify = 380;
    CmdAvatarType_TakeOffAvatarSkinCsReq = 338;
    CmdAvatarType_GetPreAvatarActivityListCsReq = 340;
    CmdAvatarType_UnlockAvatarPathScRsp = 370;
    CmdAvatarType_TakeOffRelicCsReq = 348;
    CmdAvatarType_UnlockAvatarPathCsReq = 389;
    CmdAvatarType_SetGrowthTargetAvatarCsReq = 314;
    CmdAvatarType_AddMultiPathAvatarScNotify = 324;
    CmdAvatarType_PromoteAvatarCsReq = 398;
    CmdAvatarType_GetAvatarDataCsReq = 334;
    CmdAvatarType_SetMultipleAvatarPathsCsReq = 311;
    CmdAvatarType_TakeOffEquipmentCsReq = 372;
    CmdAvatarType_AvatarQuickUpCsReq = 335;
    CmdAvatarType_SetGrowthTargetAvatarScRsp = 305;
    CmdAvatarType_GetPreAvatarGrowthInfoScRsp = 301;
    CmdAvatarType_TakePromotionRewardScRsp = 364;
    CmdAvatarType_GetAvatarDataScRsp = 382;
    CmdAvatarType_SetMultipleAvatarPathsScRsp = 387;
    CmdAvatarType_RankUpAvatarCsReq = 371;
    CmdAvatarType_SetAvatarEnhancedIdCsReq = 321;
    CmdAvatarType_DressAvatarScRsp = 399;
    CmdAvatarType_AvatarQuickUpScRsp = 378;
    CmdAvatarType_MarkAvatarCsReq = 366;
    CmdAvatarType_SetAvatarPathScRsp = 330;
    CmdAvatarType_TakeOffEquipmentScRsp = 365;
    CmdAvatarType_UnlockAvatarSkinScNotify = 346;
    CmdAvatarType_DressAvatarSkinScRsp = 341;
    CmdAvatarType_MarkAvatarScRsp = 309;
    CmdAvatarType_GetPreAvatarGrowthInfoCsReq = 344;
    CmdAvatarType_SetAvatarPathCsReq = 302;
    CmdAvatarType_SetPlayerOutfitCsReq = 355;
    CmdAvatarType_SetPlayerOutfitScRsp = 375;
    CmdAvatarType_TakeOffRelicScRsp = 388;
    CmdAvatarType_SetAvatarEnhancedIdScRsp = 343;
    CmdAvatarType_GrowthTargetAvatarChangedScNotify = 323;
    CmdAvatarType_AvatarExpUpCsReq = 379;
    CmdAvatarType_DressRelicAvatarScRsp = 349;
    CmdAvatarType_PromoteAvatarScRsp = 326;
    CmdAvatarType_AvatarPathChangedNotify = 360;
    CmdAvatarType_DressAvatarSkinCsReq = 381;
}

message DressAvatarCsReq {
    uint32 equipment_unique_id = 8;
    uint32 avatar_id = 7;
}

message DressAvatarSkinCsReq {
    uint32 avatar_id = 2;
    uint32 skin_id = 15;
}

message DressRelicAvatarCsReq {
    uint32 avatar_id = 12;
    repeated DressRelicParam switch_list = 14;
}

message DressRelicAvatarScRsp {
    uint32 PLDKENJLKME = 13;
    IBKDHOIDKJA CPKHFLBNJPA = 7;
    uint32 DONGOAMFBOG = 2;
}

message DressRelicParam {
    uint32 relic_type = 7;
    uint32 relic_unique_id = 9;
}

enum GCALLOJPPIJ {
    GCALLOJPPIJ_NLCDGIPGFDJ = 0;
    GCALLOJPPIJ_BDEFGIPPKNM = 1;
    GCALLOJPPIJ_BPBFOIJKCJA = 2;
}

message GetAvatarDataCsReq {
    repeated uint32 NOEPBNMJFGL = 9;
    bool is_get_all = 5;
}

message GetAvatarDataScRsp {
    repeated uint32 skin_list = 15;
    repeated CFMDKNCDDAL PILOAFIMCGK = 7;
    CJLCPMDGIBO DHKFCDAGHDM = 11;
    repeated AvatarPathData avatar_path_data_info_list = 2;
    repeated uint32 basic_type_id_list = 9;
    repeated Avatar avatar_list = 4;
    uint32 retcode = 3;
    repeated KVP JBFBEOLOHJN = 14;
    bool is_get_all = 12;
    uint32 JFAADMONJNF = 6;
}

message GetPreAvatarActivityListCsReq {
}

message GetPreAvatarActivityListScRsp {
    repeated uint32 DDMEHPDHPLM = 9;
    uint32 retcode = 6;
}

message GetPreAvatarGrowthInfoCsReq {
}

message GetPreAvatarGrowthInfoScRsp {
    repeated PreAvatarGrowthMaterialData JLMMCNIMPOA = 8;
    uint32 retcode = 12;
}

enum GrowthTargetState {
    GrowthTargetState_MMBDGPMCJKH = 0;
    GrowthTargetState_PDHPKPOCOHM = 1;
    GrowthTargetState_CMBMDMBHFEC = 2;
    GrowthTargetState_DALNOIDGBGI = 3;
    GrowthTargetState_JEAOCLOOAMJ = 4;
    GrowthTargetState_FCKJLEGDJHJ = 5;
}

message MarkAvatarCsReq {
    bool is_marked = 11;
    uint32 avatar_id = 8;
}

message MarkAvatarScRsp {
    uint32 avatar_id = 14;
    uint32 retcode = 10;
    bool is_marked = 3;
}

message PreAvatarGrowthMaterialData {
    uint32 IEGOLHHOANB = 9;
    uint32 DKEBMGFMCBH = 3;
    uint32 DLGCGJCKLCB = 5;
    uint32 JHLPBJCAIIF = 10;
    uint32 BJFJHEJGFPM = 14;
    string avatar_icon = 1144;
    uint32 FDIJAFBCILL = 13;
    string NOCPIJJBKCB = 310;
    uint32 type = 1340;
    uint32 panel_id = 1140;
    uint32 PGJKALFDFMA = 1;
    uint32 CAHBPNLNKCC = 15;
    uint32 OIFPBOCOALL = 12;
    uint32 IICANCHNIBB = 7;
    string NDJGLMCPFHK = 1874;
    uint32 LNHKCMAPMLM = 6;
    uint32 PELFCMAHJGA = 8;
    string LACBKOCCFHL = 124;
    uint32 JPGOACKIFFC = 2;
    uint32 JOBMEJMFELF = 11;
    uint32 PPDAGPPKEJD = 1605;
    uint32 BFEPBBLIOGP = 4;
}

message PromoteAvatarCsReq {
    repeated ItemCost item_list = 10;
    uint32 base_avatar_id = 9;
}

message RankUpAvatarCsReq {
    uint32 avatar_id = 6;
    ItemCostData cost_data = 15;
    uint32 rank = 3;
}

message SetAvatarEnhancedIdCsReq {
    uint32 enhanced_id = 8;
    uint32 avatar_id = 12;
}

message SetAvatarEnhancedIdScRsp {
    uint32 growth_avatar_id = 4;
    uint32 retcode = 6;
    uint32 unk_enhanced_id = 11;
}

message SetAvatarPathCsReq {
    MultiPathAvatarType avatar_id = 13;
}

message SetAvatarPathScRsp {
    uint32 retcode = 14;
    MultiPathAvatarType avatar_id = 2;
}

message SetGrowthTargetAvatarCsReq {
    repeated CFMDKNCDDAL FLINDJJJFLB = 5;
    uint32 FCACACLEJNM = 6;
    GrowthTargetState source = 8;
    uint32 avatar_id = 7;
}

message SetGrowthTargetAvatarScRsp {
    uint32 growth_avatar_id = 1;
    repeated CFMDKNCDDAL FLINDJJJFLB = 14;
    uint32 JFAADMONJNF = 13;
    uint32 retcode = 3;
}

message SetMultipleAvatarPathsCsReq {
    repeated MultiPathAvatarType avatar_id_list = 8;
}

message SetPlayerOutfitCsReq {
    CJLCPMDGIBO DHKFCDAGHDM = 12;
}

message SetPlayerOutfitScRsp {
    uint32 retcode = 9;
}

message TakeOffAvatarSkinCsReq {
    uint32 avatar_id = 11;
}

message TakeOffEquipmentCsReq {
    uint32 avatar_id = 4;
}

message TakeOffRelicCsReq {
    repeated uint32 relic_type_list = 6;
    uint32 avatar_id = 12;
}

message TakePromotionRewardCsReq {
    uint32 promotion = 11;
    uint32 base_avatar_id = 3;
}

message TakePromotionRewardScRsp {
    ItemList reward_list = 15;
    uint32 retcode = 14;
}

message UnlockAvatarPathCsReq {
    MultiPathAvatarType avatar_id = 7;
}

message UnlockAvatarPathScRsp {
    repeated uint32 basic_type_id_list = 3;
    uint32 retcode = 5;
    ItemList reward = 11;
    MultiPathAvatarType avatar_id = 15;
}

message UnlockAvatarSkinScNotify {
    uint32 skin_id = 6;
}
