syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ActiveActivityData {
    uint32 panel_id = 10;
    uint32 id = 13;
    uint32 DBIFEEDMAOF = 7;
    uint32 FODLNKPNION = 9;
    uint32 CDMIKICANEP = 6;
    repeated uint32 taken_star_rewards = 4;
}

message ActiveActivityDataChangeScNotify {
    ActiveActivityData ANFFLNDCGLG = 1;
}

enum CmdActiveType {
    CmdActiveType_None = 0;
    CmdActiveType_GetActiveActivityDataCsReq = 9555;
    CmdActiveType_TakeActiveActivityRewardScRsp = 9563;
    CmdActiveType_ActiveActivityDataChangeScNotify = 9559;
    CmdActiveType_GetActiveActivityDataScRsp = 9565;
    CmdActiveType_TakeActiveActivityRewardCsReq = 9570;
}

message GetActiveActivityDataCsReq {
}

message GetActiveActivityDataScRsp {
    uint32 retcode = 11;
    repeated ActiveActivityData HCLGPDFBDNP = 2;
}

message TakeActiveActivityRewardCsReq {
    uint32 id = 13;
}

message TakeActiveActivityRewardScRsp {
    ActiveActivityData ANFFLNDCGLG = 3;
    uint32 retcode = 6;
    ItemList reward = 9;
}
