syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AetherDivideFinishChallengeScNotify {
    uint32 challenge_id = 1;
}

message AetherDivideLineupScNotify {
    OCCAABPFBLF lineup = 3;
}

message AetherDivideRefreshEndlessCsReq {
}

message AetherDivideRefreshEndlessScNotify {
    uint32 JAOAHONIBJI = 5;
}

message AetherDivideRefreshEndlessScRsp {
    uint32 retcode = 3;
    uint32 JAOAHONIBJI = 14;
}

message AetherDivideSkillItemScNotify {
    uint32 num = 10;
    uint32 item_id = 7;
}

message AetherDivideSpiritExpUpCsReq {
    uint32 NCAOMBHCGNA = 14;
    uint32 FHAEENDPAAG = 9;
    uint32 APGDJGPGGMO = 10;
}

message AetherDivideSpiritExpUpScRsp {
    GHBICGMEFPL IAGNGEGKDOL = 12;
    uint32 retcode = 5;
}

message AetherDivideSpiritInfoScNotify {
    repeated GHBICGMEFPL FGBAPJKDFOC = 8;
}

message AetherDivideTainerInfoScNotify {
    uint32 FOCACJHLKDB = 3;
}

message AetherDivideTakeChallengeRewardCsReq {
    uint32 group_id = 12;
}

message AetherDivideTakeChallengeRewardScRsp {
    ItemList reward = 14;
    uint32 group_id = 5;
    uint32 retcode = 13;
}

enum CmdAetherDivideType {
    CmdAetherDivideType_None = 0;
    CmdAetherDivideType_StartAetherDivideChallengeBattleCsReq = 4832;
    CmdAetherDivideType_StartAetherDivideSceneBattleScRsp = 4822;
    CmdAetherDivideType_EnterAetherDivideSceneScRsp = 4829;
    CmdAetherDivideType_ClearAetherDividePassiveSkillScRsp = 4842;
    CmdAetherDivideType_GetAetherDivideInfoScRsp = 4817;
    CmdAetherDivideType_EquipAetherDividePassiveSkillCsReq = 4801;
    CmdAetherDivideType_StartAetherDivideStageBattleCsReq = 4804;
    CmdAetherDivideType_AetherDivideTainerInfoScNotify = 4833;
    CmdAetherDivideType_SetAetherDivideLineUpCsReq = 4819;
    CmdAetherDivideType_AetherDivideRefreshEndlessScNotify = 4843;
    CmdAetherDivideType_AetherDivideFinishChallengeScNotify = 4846;
    CmdAetherDivideType_EnterAetherDivideSceneCsReq = 4836;
    CmdAetherDivideType_SwitchAetherDivideLineUpSlotCsReq = 4818;
    CmdAetherDivideType_AetherDivideSpiritInfoScNotify = 4810;
    CmdAetherDivideType_LeaveAetherDivideSceneScRsp = 4824;
    CmdAetherDivideType_AetherDivideSpiritExpUpCsReq = 4847;
    CmdAetherDivideType_AetherDivideLineupScNotify = 4823;
    CmdAetherDivideType_AetherDivideTakeChallengeRewardScRsp = 4848;
    CmdAetherDivideType_AetherDivideTakeChallengeRewardCsReq = 4806;
    CmdAetherDivideType_StartAetherDivideStageBattleScRsp = 4835;
    CmdAetherDivideType_AetherDivideSpiritExpUpScRsp = 4841;
    CmdAetherDivideType_GetAetherDivideInfoCsReq = 4821;
    CmdAetherDivideType_LeaveAetherDivideSceneCsReq = 4844;
    CmdAetherDivideType_SwitchAetherDivideLineUpSlotScRsp = 4825;
    CmdAetherDivideType_GetAetherDivideChallengeInfoScRsp = 4830;
    CmdAetherDivideType_EquipAetherDividePassiveSkillScRsp = 4807;
    CmdAetherDivideType_StartAetherDivideChallengeBattleScRsp = 4837;
    CmdAetherDivideType_AetherDivideRefreshEndlessCsReq = 4827;
    CmdAetherDivideType_AetherDivideSkillItemScNotify = 4828;
    CmdAetherDivideType_AetherDivideRefreshEndlessScRsp = 4840;
    CmdAetherDivideType_GetAetherDivideChallengeInfoCsReq = 4849;
    CmdAetherDivideType_StartAetherDivideSceneBattleCsReq = 4808;
    CmdAetherDivideType_SetAetherDivideLineUpScRsp = 4812;
    CmdAetherDivideType_ClearAetherDividePassiveSkillCsReq = 4814;
}

message DMGDLEHEDFB {
    uint32 item_id = 7;
    uint32 JMMCEJOKMMG = 11;
    uint32 num = 3;
}

message EquipSkillCoreCsReq {
    uint32 slot = 10;
    uint32 item_id = 15;
    uint32 APGDJGPGGMO = 8;
}

message GHBICGMEFPL {
    SpBarInfo sp_bar = 15;
    uint32 APGDJGPGGMO = 3;
    uint32 exp = 10;
    uint32 EKKHLMEKJMK = 12;
    repeated POPJNEHGMIH LICLEEICAOE = 7;
    uint32 promotion = 11;
}

message GetAetherDivideChallengeInfoCsReq {
}

message GetAetherDivideChallengeInfoScRsp {
    repeated uint32 OHJHICLJABM = 13;
    repeated uint32 NADKCDEOIHJ = 6;
    uint32 retcode = 5;
    uint32 DIGFECBHCPP = 2;
}

message GetAetherDivideInfoCsReq {
}

message GetAetherDivideInfoScRsp {
    repeated GHBICGMEFPL CCHDKJMFNEP = 14;
    uint32 BDNOLFBJBGJ = 4;
    uint32 JAOAHONIBJI = 12;
    repeated OCCAABPFBLF lineup_list = 1;
    repeated DMGDLEHEDFB skill_list = 7;
    uint32 retcode = 6;
    uint32 FOCACJHLKDB = 3;
    uint32 NCMLHPAALEP = 5;
}

message LeaveAetherDivideSceneCsReq {
}

message LeaveAetherDivideSceneScRsp {
    uint32 retcode = 11;
}

message OCCAABPFBLF {
    uint32 slot = 6;
    repeated uint32 AJHCCDONNEK = 13;
}

message POPJNEHGMIH {
    uint32 slot = 1;
    uint32 item_id = 12;
}

message SetAetherDivideLineUpCsReq {
    OCCAABPFBLF lineup = 14;
}

message SetAetherDivideLineUpScRsp {
    OCCAABPFBLF lineup = 11;
    uint32 retcode = 12;
}

message StartAetherDivideChallengeBattleCsReq {
    uint32 FDKFIOLMPHA = 4;
    uint32 challenge_id = 6;
}

message StartAetherDivideChallengeBattleScRsp {
    AetherDivideBattleInfo battle_info = 9;
    uint32 retcode = 14;
}

message StartAetherDivideSceneBattleCsReq {
    uint32 skill_index = 13;
    repeated AssistMonsterEntityInfo assist_monster_entity_info = 11;
    uint32 cast_entity_id = 5;
    repeated uint32 assist_monster_entity_id_list = 1;
    uint32 attacked_by_entity_id = 8;
}

message StartAetherDivideSceneBattleScRsp {
    uint32 cast_entity_id = 9;
    uint32 retcode = 10;
    AetherDivideBattleInfo battle_info = 13;
}

message StartAetherDivideStageBattleCsReq {
    uint32 event_id = 11;
}

message StartAetherDivideStageBattleScRsp {
    AetherDivideBattleInfo battle_info = 3;
    uint32 retcode = 1;
}

message SwitchAetherDivideLineUpSlotCsReq {
    uint32 FDKFIOLMPHA = 5;
}

message SwitchAetherDivideLineUpSlotScRsp {
    uint32 retcode = 9;
    uint32 FDKFIOLMPHA = 8;
}

message TakeOffSkillCoreCsReq {
    uint32 slot = 15;
    uint32 APGDJGPGGMO = 4;
}
