syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BOMPFHOMMBH {
    uint32 item_id = 6;
    uint32 num = 10;
    uint32 target = 15;
}

enum CmdActivityRewardStatType {
    CmdActivityRewardStatType_CmdActivityRewardStatNone = 0;
    CmdActivityRewardStatType_GetActivityRewardCountDataCsReq = 9116;
    CmdActivityRewardStatType_GetActivityHotDataScRsp = 9120;
    CmdActivityRewardStatType_GetActivityHotDataCsReq = 9115;
    CmdActivityRewardStatType_GetActivityRewardCountDataScRsp = 9112;
    CmdActivityRewardStatType_GetAllActivityRewardCountDataScRsp = 9119;
    CmdActivityRewardStatType_GetAllActivityRewardCountDataCsReq = 9117;
}

message EFGIHHJGCFA {
    repeated BOMPFHOMMBH PGMDGPEKDGB = 3;
    uint32 panel_id = 15;
}

message GetActivityHotDataCsReq {
}

message GetActivityHotDataScRsp {
    repeated EFGIHHJGCFA content_package_list = 2;
    uint32 retcode = 8;
}

message GetActivityRewardCountDataCsReq {
    repeated uint32 DDMEHPDHPLM = 5;
}

message GetActivityRewardCountDataScRsp {
    uint32 retcode = 13;
    repeated EFGIHHJGCFA content_package_list = 1;
}

message GetAllActivityRewardCountDataCsReq {
}

message GetAllActivityRewardCountDataScRsp {
    repeated EFGIHHJGCFA content_package_list = 14;
    uint32 retcode = 12;
}
