syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";
import "CmdB51RacingType.proto";

message B51RacingChallengeEndMatchCsReq {
    uint32 match_id = 9;
    B51RacingMatchStats stats = 1;
    uint32 rank = 11;
    HPICFNLLMCO result_type = 13;
    uint32 track_id = 14;
    uint32 finish_time_ms = 15;
    uint32 random_seed = 8;
}

message B51RacingChallengeEndMatchScRsp {
    uint32 score = 14;
    uint32 match_id = 9;
    uint32 track_id = 15;
    uint32 retcode = 4;
}

message B51RacingChallengeStartMatchCsReq {
    uint32 driver_id = 5;
    uint32 track_id = 9;
    uint32 match_id = 11;
}

message B51RacingChallengeStartMatchScRsp {
    uint32 random_seed = 5;
    uint32 driver_id = 10;
    uint32 retcode = 12;
}

message B51RacingChallengeUpdateCarCsReq {
    repeated uint32 equipped_part_id_list = 10;
    B51RacingCarLivery livery = 3;
    uint32 cycle_id = 12;
}

message B51RacingChallengeUpdateCarScRsp {
    uint32 retcode = 4;
    B51RacingChallengeCarData car = 8;
}

enum CmdB51RacingExtType {
    CmdB51RacingExtType_None = 0;
    CmdB51RacingExtType_B51RacingChallengeEndMatchScRsp = 10112;
    CmdB51RacingExtType_B51RacingChallengeUpdateCarCsReq = 10105;
    CmdB51RacingExtType_B51RacingChallengeStartMatchCsReq = 10120;
    CmdB51RacingExtType_B51RacingChallengeStartMatchScRsp = 10113;
    CmdB51RacingExtType_B51RacingChallengeUpdateCarScRsp = 10115;
    CmdB51RacingExtType_B51RacingChallengeEndMatchCsReq = 10109;
}
