syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BenefitData {
    uint32 JALHKMEOOPN = 4;
    uint32 status = 5;
    uint32 level = 3;
    OPGKKPEDKCL config = 8;
}

enum CmdBenefitActivityType {
    CmdBenefitActivityType_None = 0;
    CmdBenefitActivityType_TakeBenefitActivityRewardCsReq = 4894;
    CmdBenefitActivityType_TakeBenefitActivityRewardScRsp = 4874;
    CmdBenefitActivityType_JoinBenefitActivityScRsp = 4872;
    CmdBenefitActivityType_GetBenefitActivityInfoScRsp = 4879;
    CmdBenefitActivityType_GetBenefitActivityInfoCsReq = 4886;
    CmdBenefitActivityType_JoinBenefitActivityCsReq = 4858;
}

message GetBenefitActivityInfoCsReq {
}

message GetBenefitActivityInfoScRsp {
    bool GHHLLCEMAOP = 6;
    uint32 retcode = 1;
    repeated BenefitData HNFFFDEGOEB = 15;
}

message ICGOLPHCKIL {
    ItemList item_list = 11;
    uint32 level = 6;
}

message JoinBenefitActivityCsReq {
    uint32 JALHKMEOOPN = 12;
}

message JoinBenefitActivityScRsp {
    uint32 retcode = 14;
    uint32 JALHKMEOOPN = 4;
}

message LuckyKoiInfoList {
    uint32 head_icon = 2;
    string LHAPDMPPOMP = 9;
    string ELBEDNGJKDD = 1;
}

message OIEAMBAGHBK {
    bool OOFKOIMLCPA = 13;
    ItemList item_list = 12;
    uint32 JALHKMEOOPN = 9;
}

message OKKEJHPLMLA {
    bool OOFKOIMLCPA = 5;
    uint32 JALHKMEOOPN = 3;
}

message OPGKKPEDKCL {
    repeated LuckyKoiInfoList JEMFDEEFPFM = 14;
    uint64 begin_time = 8;
    uint64 end_time = 15;
    uint64 EGGJMKCABEF = 10;
    uint32 MACLJJCIDEJ = 3;
    repeated ICGOLPHCKIL EGGJFCELHNK = 7;
}

message TakeBenefitActivityRewardCsReq {
    repeated OKKEJHPLMLA switch_list = 14;
    bool LJEGPIJGMLG = 3;
}

message TakeBenefitActivityRewardScRsp {
    ItemList JJOKIIKIHNL = 13;
    repeated OIEAMBAGHBK switch_list = 11;
    uint32 retcode = 2;
}
