syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AKLDICEFCIL {
    AvatarType avatar_type = 8;
    uint32 avatar_id = 5;
}

message BoxingClubChallengeUpdateScNotify {
    CIEEKOEECHB OCDLPDDMCLP = 2;
}

message BoxingClubRewardScNotify {
    uint32 EAFICCLCLLA = 9;
    uint32 challenge_id = 13;
    bool is_win = 3;
    ItemList reward = 10;
}

message CIEEKOEECHB {
    bool MLOGJKEOCPP = 2;
    repeated uint32 avatar_list = 12;
    uint32 challenge_id = 8;
    repeated uint32 EJEFDFEFOMH = 5;
    uint32 LFFBKJBJJDD = 14;
    uint32 stage_index = 13;
    uint32 EAFICCLCLLA = 15;
    uint32 IFHHFBIJOFC = 7;
    repeated FLLJIHLMKDI OOJOMKDMBBM = 1;
    uint32 HODLKBMKMCF = 3;
}

message ChooseBoxingClubResonanceCsReq {
    uint32 challenge_id = 15;
    uint32 HODLKBMKMCF = 6;
}

message ChooseBoxingClubResonanceScRsp {
    CIEEKOEECHB OCDLPDDMCLP = 2;
    uint32 retcode = 10;
}

message ChooseBoxingClubStageOptionalBuffCsReq {
    uint32 challenge_id = 14;
    uint32 MFKAOHKPIPE = 4;
}

message ChooseBoxingClubStageOptionalBuffScRsp {
    CIEEKOEECHB OCDLPDDMCLP = 13;
    uint32 retcode = 1;
}

enum CmdBoxingClubType {
    CmdBoxingClubType_None = 0;
    CmdBoxingClubType_StartBoxingClubBattleCsReq = 4256;
    CmdBoxingClubType_BoxingClubRewardScNotify = 4273;
    CmdBoxingClubType_StartBoxingClubBattleScRsp = 4291;
    CmdBoxingClubType_GetBoxingClubInfoCsReq = 4234;
    CmdBoxingClubType_ChooseBoxingClubResonanceCsReq = 4272;
    CmdBoxingClubType_ChooseBoxingClubStageOptionalBuffScRsp = 4262;
    CmdBoxingClubType_ChooseBoxingClubStageOptionalBuffCsReq = 4204;
    CmdBoxingClubType_MatchBoxingClubOpponentCsReq = 4279;
    CmdBoxingClubType_GiveUpBoxingClubChallengeCsReq = 4298;
    CmdBoxingClubType_GiveUpBoxingClubChallengeScRsp = 4226;
    CmdBoxingClubType_ChooseBoxingClubResonanceScRsp = 4265;
    CmdBoxingClubType_GetBoxingClubInfoScRsp = 4282;
    CmdBoxingClubType_SetBoxingClubResonanceLineupScRsp = 4271;
    CmdBoxingClubType_BoxingClubChallengeUpdateScNotify = 4299;
    CmdBoxingClubType_MatchBoxingClubOpponentScRsp = 4239;
    CmdBoxingClubType_SetBoxingClubResonanceLineupCsReq = 4280;
}

message FLLJIHLMKDI {
    uint32 avatar_id = 1;
    AvatarType avatar_type = 6;
}

message GetBoxingClubInfoCsReq {
}

message GetBoxingClubInfoScRsp {
    repeated CIEEKOEECHB challenge_list = 7;
    uint32 retcode = 13;
}

message GiveUpBoxingClubChallengeCsReq {
    bool KEAAGAIAHLA = 13;
    uint32 challenge_id = 11;
}

message GiveUpBoxingClubChallengeScRsp {
    uint32 retcode = 13;
    CIEEKOEECHB OCDLPDDMCLP = 7;
}

message MatchBoxingClubOpponentCsReq {
    repeated AKLDICEFCIL OOJOMKDMBBM = 6;
    repeated uint32 avatar_list = 8;
    uint32 challenge_id = 2;
}

message MatchBoxingClubOpponentScRsp {
    CIEEKOEECHB OCDLPDDMCLP = 13;
    uint32 retcode = 8;
}

message StartBoxingClubBattleCsReq {
    uint32 challenge_id = 5;
}

message StartBoxingClubBattleScRsp {
    uint32 challenge_id = 12;
    SceneBattleInfo battle_info = 7;
    uint32 retcode = 13;
}
