syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ABDOKOFEHMH {
    int32 BCJLNFOMEAG = 1;
}

message ABFLKIBIFDM {
    uint32 JEOFBDLFCOL = 1;
    double HIFNHNLNDPN = 2;
    double JGFKNDMDHHP = 3;
    uint32 wave = 4;
    uint32 IBNLKOLLPJH = 5;
    double AEPMEGILLOJ = 6;
    double MINCPOKEPDP = 7;
}

message ADHGIJPHLEB {
    uint32 trait_id = 1;
    repeated OBIMHNFFLEM MFJCLCJNAFO = 2;
    double damage = 3;
    double KINKMHEAANP = 4;
}

message AFGMNFFBBIG {
    uint32 BKPDKFLDLDD = 1;
    uint32 monster_id = 2;
    repeated GHCDMMNHNHO OFHCHNKEFMD = 3;
    uint32 delay = 4;
    repeated GANDCEDCLDL JNFCFEIAABH = 5;
}

message AttackDamageProperty {
    string attack_type = 1;
    double damage = 2;
}

message AvatarBattleInfo {
    AvatarType avatar_type = 1;
    uint32 id = 2;
    uint32 avatar_level = 3;
    uint32 avatar_rank = 4;
    uint32 avatar_promotion = 5;
    AvatarProperty avatar_status = 6;
    repeated AvatarSkillTree avatar_skill = 7;
    repeated EquipmentProperty avatar_equipment = 8;
    uint32 total_turns = 9;
    double total_damage = 10;
    double total_heal = 11;
    double total_damage_taken = 12;
    double total_hp_recover = 13;
    double total_sp_cost = 14;
    uint32 stage_id = 15;
    uint32 stage_type = 16;
    double total_break_damage = 17;
    repeated AttackDamageProperty attack_type_damage = 18;
    repeated AttackDamageProperty attack_type_break_damage = 19;
    repeated AttackDamageProperty attack_type_max_damage = 20;
    repeated SkillUseProperty skill_times = 21;
    double delay_cumulate = 22;
    uint32 total_sp_add = 23;
    repeated SpAddSource sp_add_source = 24;
    uint32 total_bp_cost = 25;
    uint32 die_times = 26;
    uint32 revive_times = 27;
    uint32 break_times = 28;
    uint32 extra_turns = 29;
    double total_shield = 30;
    double total_shield_taken = 31;
    double total_shield_damage = 32;
    AvatarProperty initial_status = 33;
    repeated BattleRelic relics = 34;
    uint32 assist_uid = 35;
    repeated AttackDamageProperty NOGHNMCDDAI = 36;
    double DEICGFKIMMO = 37;
    double GPLELDEIEKO = 38;
    double CNEMKKIBFEA = 39;
    double EEOGKOKOPNB = 40;
    repeated EPNAONKOHBO ALJIJBKEFDD = 41;
    uint32 CNLEPLAEEHF = 42;
    uint32 JDHDJFCKBGD = 43;
    double DIALJMAHFBO = 44;
    double LAOEEGEELDK = 45;
    double LFLKOGDPLKD = 46;
    double EBMFCBKHIEH = 47;
    double DBLABFODNMJ = 48;
    uint32 FJNKOPMOLDE = 49;
    uint32 FLKCFJBCIOM = 50;
    uint32 PNJDPNHNBDA = 51;
    double NEDCAKEMHLF = 52;
    uint32 NBCDOMJBAFM = 53;
    uint32 PECMOGDLCDC = 54;
    uint32 enhanced_id = 55;
    uint32 MEBKILMPMGA = 56;
    CFDHDBNIHPL FDMEEDEJCCP = 57;
    ABDOKOFEHMH GEHEJPPCBLK = 58;
    uint32 OKMHKBOJBOB = 59;
}

message AvatarProperty {
    double max_hp = 1;
    double attack = 2;
    double defence = 3;
    double speed = 4;
    double left_hp = 5;
    double left_sp = 6;
    double max_sp = 7;
}

message BJOFJDKIOPG {
    uint32 OEBAIDCOPLC = 1;
    uint32 IBHKMLKHKJB = 2;
    uint32 JBFEPAFJNCL = 3;
    repeated LGOKJFKMCBE EGHJFEIMHBB = 4;
}

message BMKIIODBMJF {
    uint32 wave = 1;
    double PCKECKCNHCE = 2;
    double EOKEFIAOFPN = 3;
    uint32 HEKPNDDKKMM = 4;
    uint32 INOIOGNMBMM = 5;
    uint32 status = 6;
    uint32 PKDANDJFAON = 7;
    uint32 HHOPLLPEKKE = 8;
}

message BattleAvatarGlobalBuffInfo {
    uint32 avatar_id = 1;
    uint32 maze_buff_id = 2;
    uint32 DLMBCCCPCKJ = 3;
}

message BattleAvatarServantInfo {
    uint32 avatar_id = 1;
    uint32 KAAHKLDJPJE = 2;
    uint32 total_turns = 3;
    double DBJOLLGOGOL = 4;
    repeated SkillUseProperty skill_times = 5;
    double total_damage = 6;
    double total_break_damage = 7;
    repeated AttackDamageProperty attack_type_damage = 8;
    repeated AttackDamageProperty attack_type_break_damage = 9;
    repeated AttackDamageProperty attack_type_max_damage = 10;
    double total_damage_taken = 11;
    double total_heal = 12;
    double total_hp_recover = 13;
    double total_shield = 14;
    double total_shield_taken = 15;
    double total_shield_damage = 16;
    uint32 break_times = 17;
    uint32 NFELHIGFIOM = 18;
    uint32 CNLEPLAEEHF = 19;
    uint32 JDHDJFCKBGD = 20;
    double DIALJMAHFBO = 21;
    uint32 entity_id = 22;
    uint32 MEBKILMPMGA = 23;
    double GPLELDEIEKO = 24;
}

enum BattleEndReason {
    BATTLE_END_REASON_NONE = 0;
    BATTLE_END_REASON_ALL_DIE = 1;
    BATTLE_END_REASON_TURN_LIMIT = 2;
}

message BattleReplayScNotify {
    bytes NOJCNDGGLBC = 3;
    uint32 battle_id = 5;
    uint32 stage_id = 15;
}

enum BattleStaticticEventType {
    BATTLE_STATICTIC_EVENT_NONE = 0;
    BATTLE_STATICTIC_EVENT_TREASURE_DUNGEON_ADD_EXPLORE = 1;
    BATTLE_STATICTIC_EVENT_TREASURE_DUNGEON_OPEN_GRID = 2;
    BATTLE_STATICTIC_EVENT_TREASURE_DUNGEON_PICKUP_ITEM = 3;
    BATTLE_STATICTIC_EVENT_TREASURE_DUNGEON_USE_BUFF = 4;
    BATTLE_STATICTIC_EVENT_TELEVISION_ACTIVITY_UPDATE_MAZE_BUFF_LAYER = 5;
    BATTLE_STATICTIC_EVENT_ROGUE_TOURN_TITAN_EXTRA_COIN = 6;
    BATTLE_STATICTIC_EVENT_ROGUE_TOURN_TITAN_EXTRA_COIN_TIMES = 7;
}

message BattleStatistics {
    uint32 total_battle_turns = 1;
    uint32 total_auto_turns = 2;
    repeated uint32 avatar_id_list = 3;
    uint32 ultra_cnt = 4;
    double total_delay_cumulate = 5;
    double cost_time = 6;
    repeated AvatarBattleInfo battle_avatar_list = 7;
    repeated MonsterBattleInfo monster_list = 8;
    uint32 round_cnt = 9;
    uint32 cocoon_dead_wave = 10;
    uint32 avatar_battle_turns = 11;
    uint32 monster_battle_turns = 12;
    map<string, float> custom_values = 13;
    uint32 challenge_score = 14;
    repeated BattleEventBattleInfo BDCHEJKPOAF = 16;
    BattleEndReason end_reason = 19;
    repeated HDKEPPDIDIH OKFALMGFHMA = 21;
    repeated int32 AKFFKEMDPLG = 22;
    repeated AFGMNFFBBIG ENPBMPKGLOM = 23;
    repeated StatisticEvent EIPBMOMKJDO = 26;
    repeated CDMPJODLBEE ECFFMBFGPOJ = 27;
    map<uint32, BattleTargetList> battle_target_info = 28;
    repeated MKICACCMBOF LGKAKIEEOMG = 29;
    BattleGridFightSpecialBattleInfo battle_evolve_build_data = 30;
    OJEANLINGCJ DOAFGHLAICM = 31;
    bool ADGBAKBCOKF = 32;
    repeated BMKIIODBMJF DCMAHKHAFEH = 33;
    repeated NHPAECJCOCG AIOKGNBLMDI = 34;
    uint32 NPFDEJPPPLI = 35;
    EANJJJPKIPJ DBKFEPMIMFF = 36;
    GBJMLKNLEPD MHPDKEDHELL = 37;
    BJOFJDKIOPG BCCIIEGCFAA = 38;
    OHDHNDMJFAP IAGKLJEKAOL = 39;
    FMEKABDGCEC OFMIGBJPKMH = 40;
    uint32 IEOGEFBLNEL = 41;
    repeated BattleAvatarGlobalBuffInfo MHLCFDEGOGN = 42;
    MGMJOPHJCNL APAGMJNECCN = 43;
    repeated uint32 GBLEKIOCFMA = 44;
    repeated uint32 MEBKILMPMGA = 45;
    KNBMAPNNDJL KFPEKBCKKPM = 46;
    CKOKAGGLKHG ILNNGPJAEGH = 47;
    FAHGFCIJHFK MFOJKJGKDGD = 48;
}

message CDMPJODLBEE {
    AABGIFAEEEK type = 1;
    uint32 id = 2;
    SpBarInfo sp_bar = 3;
}

message CFDHDBNIHPL {
    double GNHLKBINIEF = 1;
    repeated uint32 NGIJFAEONCK = 2;
}

message CJAFIJAFIPN {
    uint32 EOKOPAFFMII = 1;
    uint32 monster_id = 2;
}

message CKCDIAAFICJ {
    uint32 BKPDKFLDLDD = 1;
    double IFMOHNAAAMC = 2;
    uint32 MMPHFLDBEKB = 3;
    uint32 break_times = 4;
}

message CKOKAGGLKHG {
    uint32 HFLPDCJDIAC = 1;
    repeated NLAPCKJBJNB avatar_list = 2;
    double FBNBPPHOGLI = 3;
}

message CMIKEILGNGK {
    uint32 GCAHKLNGFCK = 1;
    uint32 level = 2;
    double total_damage = 3;
}

message CPNCAPLOIHI {
    uint32 role_id = 1;
    double damage = 2;
    double KINKMHEAANP = 5;
    map<uint32, double> ICECCHMAGNO = 6;
    uint32 CAKAOJGILMG = 7;
    uint32 OKMHKBOJBOB = 8;
}

enum CmdBattleType {
    CmdBattleType_None = 0;
    CmdBattleType_PvebattleResultScRsp = 182;
    CmdBattleType_GetCurBattleInfoScRsp = 191;
    CmdBattleType_GetCurBattleInfoCsReq = 156;
    CmdBattleType_BattleReplayScNotify = 104;
    CmdBattleType_QuitBattleScNotify = 173;
    CmdBattleType_SyncClientResVersionCsReq = 198;
    CmdBattleType_QuitBattleScRsp = 139;
    CmdBattleType_PvebattleResultCsReq = 134;
    CmdBattleType_QuitBattleCsReq = 179;
    CmdBattleType_RebattleByClientCsNotify = 171;
    CmdBattleType_SyncClientResVersionScRsp = 126;
}

message DFDPLINPMJF {
    uint32 INGDHDPEGOK = 1;
    uint32 IGPNFJDACIE = 2;
    repeated CMIKEILGNGK KGIELMEOPEH = 3;
}

message EANJJJPKIPJ {
    DFDPLINPMJF EBIJFLILKFP = 1;
    NKKADHADOLO GEOOCJBAKFI = 2;
}

message EPNAONKOHBO {
    string ability_name = 1;
    uint32 count = 2;
    double total_damage = 3;
}

message EquipmentProperty {
    uint32 id = 1;
    uint32 rank = 2;
    uint32 promotion = 3;
    uint32 level = 4;
}

message FAHGFCIJHFK {
    uint32 round_cnt = 1;
    uint32 FHPMEIECKLG = 2;
    uint32 HOIOBLJHJHJ = 3;
    uint32 total_bp_cost = 4;
    double total_damage = 5;
    double total_damage_taken = 6;
    double total_hp_recover = 7;
    double total_shield_taken = 8;
    repeated PMPCIBGILIE INBNCAKGDPJ = 9;
}

message FHKKPNDLLLO {
    uint32 portal_buff_id = 1;
}

message FIMBJCONBAE {
    uint32 DAEKFCNBCFC = 1;
    uint32 AMKBLKMNKFE = 2;
    uint32 MOLFOOGCBKE = 3;
    repeated uint32 CDJABFHCNFF = 4;
    repeated FMNPJNPAMOA CMAOCGLKFAE = 5;
    uint32 ACGIEKABIFK = 6;
    uint32 DAEBGDENDNN = 7;
}

message FMEKABDGCEC {
    NEJMJMJAMMA GIOJALJAIIF = 1;
    repeated NIFPICHIDLJ message_datas = 2;
}

message FMNPJNPAMOA {
    uint32 avatar_id = 1;
    uint32 JAEGABGPEDI = 2;
}

message GANDCEDCLDL {
    uint32 KAAHKLDJPJE = 1;
    uint32 FHPMEIECKLG = 2;
    uint32 entity_id = 3;
}

message GBJMLKNLEPD {
    HPHJPOIBGLC LNJMOALDPJD = 1;
    JIONEELJGCC BNMBHFMHGLH = 2;
    JGOFJDOCOMK KIABIIOENOK = 3;
    GECCJHDOCKH FIIGOHIOINP = 4;
}

message GECCJHDOCKH {
    uint32 DLGPBFDGEGJ = 1;
    uint32 BJLGFCKBPPJ = 2;
}

message GHCDMMNHNHO {
    uint32 avatar_id = 1;
    int32 GCABCJKCAOE = 2;
    uint32 enhanced_id = 3;
}

message GetCurBattleInfoCsReq {
}

message GetCurBattleInfoScRsp {
    SceneBattleInfo battle_info = 7;
    AetherDivideBattleInfo HIDIEJALFIE = 8;
    uint32 KDJGDHKJAGE = 6;
    uint32 retcode = 1;
    BattleEndStatus last_end_status = 12;
}

enum HDFAPKLGEFM {
    HDFAPKLGEFM_LCOKOJCGKHP = 0;
    HDFAPKLGEFM_NMDOPKBENEA = 1;
}

message HDKEPPDIDIH {
    uint32 avatar_id = 1;
    repeated uint32 EJDDMNAODEN = 2;
    uint32 source = 3;
    double damage = 4;
    repeated uint32 JNDBCDAIIDD = 5;
    int32 AFPKBFAPOAH = 6;
    double OELDAKBOPJA = 7;
    uint32 CNGEOGOMPOP = 8;
    uint32 wave = 9;
    uint32 enhanced_id = 10;
}

message HFFAFBIGNKP {
    uint32 monster_id = 1;
    uint32 IBNLKOLLPJH = 2;
    uint32 HEKPNDDKKMM = 3;
    uint32 INOIOGNMBMM = 4;
}

message HFKKKFJHPHJ {
    uint32 augment_id = 1;
    double damage = 3;
    double KINKMHEAANP = 4;
}

message HNDAOBACJOA {
    string phase = 1;
    float MINGOICONIF = 2;
    float EEFMGKOFOBH = 3;
    uint32 DLHCMNIACBO = 4;
    uint32 JMCFEEHBDDH = 5;
    uint32 ENCAECIICBP = 6;
    uint32 GOEEJIAAEKB = 7;
    uint32 HDGBKHPHKMO = 8;
    repeated uint32 DJOFHLGLDGB = 9;
    repeated uint32 NCDMFFBBBDP = 10;
}

message HPHJPOIBGLC {
    repeated HFFAFBIGNKP CDFPLJDJDEP = 1;
    repeated ABFLKIBIFDM EGHJFEIMHBB = 2;
    repeated JPKJNNKMIGJ DKOCKKCPGDK = 3;
}

message IGMOKOENLDK {
    double max_hp = 1;
    double attack = 2;
    double defence = 3;
    double OFMLLDLAOCC = 4;
    double speed = 5;
    double left_hp = 6;
    double GENCOBDFKLA = 7;
}

message JGOFJDOCOMK {
    uint32 progress = 1;
}

message JIONEELJGCC {
    FIMBJCONBAE IPDCLDBKIBI = 1;
}

message JPAIOFMJEPM {
    uint32 BBHBAKJCGLC = 1;
}

message JPHFANMNHJP {
    JPAIOFMJEPM FECDNCFJGFK = 1;
}

message JPKJNNKMIGJ {
    uint32 GDLJHBLJODK = 1;
    uint32 DFBHOJANGCF = 2;
    double CJKMCOMGJCL = 3;
    uint32 wave = 4;
    uint32 IBNLKOLLPJH = 5;
}

message KNBMAPNNDJL {
    int32 OLLPHBPPEHG = 1;
    int32 NONACGPCEKE = 2;
    int32 BCJLNFOMEAG = 3;
}

enum KPOIEOPCEJL {
    KPOIEOPCEJL_PJAAADFOKKC = 0;
    KPOIEOPCEJL_LMGJEFFHBHF = 1;
    KPOIEOPCEJL_JBGODLOEOPF = 2;
    KPOIEOPCEJL_DOGMHOAOJFD = 3;
}

message LFLENBDPNJN {
    uint32 PBFMLGOCOPF = 1;
    repeated CJAFIJAFIPN kill_monster_list = 2;
}

message LGOKJFKMCBE {
    uint32 KJGDBFEFHPJ = 1;
    double HIFNHNLNDPN = 2;
    double JGFKNDMDHHP = 3;
    uint32 IBOPDGOFDOD = 4;
    uint32 NBKOOPBPNPL = 5;
    uint32 GMJGPDKJAEE = 6;
    uint32 HKAENABCBHL = 7;
    double AEPMEGILLOJ = 8;
    uint32 BJGOOFNOGMJ = 9;
    uint32 OLPDBDEDCOG = 10;
    double MINCPOKEPDP = 11;
    uint32 OEBAIDCOPLC = 12;
    uint32 IBHKMLKHKJB = 13;
}

message MGMJOPHJCNL {
    uint32 HFLPDCJDIAC = 1;
    uint32 NBPFMFMKJHI = 2;
    repeated ADHGIJPHLEB MFOOECCEOBO = 3;
    repeated HFKKKFJHPHJ LLOFONJOGCE = 4;
    repeated BCCONKJHDJL ODMCMPIDJNH = 5;
    repeated LFLENBDPNJN NELAKLKIDDK = 6;
    repeated CPNCAPLOIHI DOGMMGLBJIJ = 8;
    uint32 OAHFCPPIMLF = 9;
    repeated FHKKPNDLLLO JHBJNKCJINO = 10;
    double NDKJJIFIFNJ = 11;
    double FLFEAJFNPAP = 12;
    double COCOMFHNEHF = 13;
    uint32 FKMINAMFFAN = 14;
    repeated JPHFANMNHJP OPJPKFEFPKA = 15;
    map<string, uint32> POCKGKDFLKK = 16;
}

message MKICACCMBOF {
    uint32 DMKHKEMIKKH = 1;
    uint32 CIHMKAEKGFL = 2;
}

message MonsterBattleInfo {
    uint32 entity_id = 1;
    uint32 monster_id = 2;
    uint32 PKFMOFPMBBJ = 3;
    uint32 NCKAICABJIK = 4;
    IGMOKOENLDK CIHAPGPNCMI = 5;
    uint32 total_turns = 6;
    double total_damage = 7;
    double total_heal = 8;
    double total_damage_taken = 9;
    double total_hp_recover = 11;
    uint32 stage_id = 12;
    uint32 KPMIIFGAMFA = 14;
    repeated AttackDamageProperty attack_type_damage = 15;
    repeated SkillUseProperty skill_times = 16;
    uint32 stage_type = 17;
    double MBDMCJLFJOO = 18;
    double delay_cumulate = 19;
    KPOIEOPCEJL death_source = 20;
    uint32 wave = 21;
    int32 JFDOMCHHBIF = 22;
    uint32 phase = 23;
    uint32 max_phase = 24;
    HDFAPKLGEFM GCAEPLJHCFE = 25;
    repeated AOFMDLLDIHG skill_info = 26;
    uint32 CBMLFOBDNCO = 27;
    repeated CKCDIAAFICJ AKGJOPBLPNE = 28;
    double NCDGNNJABJJ = 29;
    double IBENGEOJFOJ = 30;
    NLNEBDEEONP AHKJLOJDNIC = 31;
    bool BNGNPNPOGOO = 32;
}

message NEJMJMJAMMA {
    uint32 NCDBCLLAHPP = 1;
    uint32 JJDEEHAMHGF = 2;
    uint32 GCNMKIHOFGG = 3;
}

message NHPAECJCOCG {
    string key = 1;
    double value = 2;
}

message NKKADHADOLO {
    OKLPMDCIEIG FMNIHGEJKED = 1;
}

message NLAPCKJBJNB {
    uint32 avatar_id = 1;
    map<uint32, double> DMLCLKHGEFE = 2;
}

enum NLNEBDEEONP {
    NLNEBDEEONP_HHDDIFHGNHD = 0;
    NLNEBDEEONP_LDANCJMPNMB = 1;
}

message OBIMHNFFLEM {
    uint32 effect_id = 1;
    repeated uint32 switch_list = 2;
    map<uint32, GridFightDropInfo> trait_effect_level_reward = 5;
}

message OHDHNDMJFAP {
    repeated BattleAvatarServantInfo GFOAHHHNBJC = 1;
    uint32 GNMMFALALLD = 2;
    uint32 BOBELCJDDOA = 3;
}

message OJEANLINGCJ {
    uint32 EAAAEJLJDDE = 1;
    uint32 NCJOBKNJFPN = 2;
    uint32 OEBAIDCOPLC = 3;
    uint32 PLJCEFDPCIO = 4;
    uint32 IBHKMLKHKJB = 5;
    uint32 KOBJCPABKAA = 6;
    repeated uint32 boss_info = 7;
    repeated HNDAOBACJOA GDFAMBOOFJO = 8;
}

message OKLPMDCIEIG {
    uint32 IPLNNHLGDJK = 1;
    uint32 JOHMBBFODBB = 2;
    double ADNKLLMHLCJ = 3;
    double GADGHAGGBNO = 4;
}

message PMPCIBGILIE {
    uint32 avatar_id = 1;
    double damage = 2;
    uint32 OKMHKBOJBOB = 3;
}

message PVEBattleResultScRsp {
    string DPHOLBABAOL = 5;
    BattleEndStatus end_status = 9;
    string DIMHPKFPPKA = 10;
    uint32 AKDGBBDFDHA = 3;
    uint32 EAHGEKNLHPN = 14;
    repeated BattleAvatar battle_avatar_list = 4;
    ItemList drop_data = 11;
    bool OPDKJBHLOJM = 1534;
    LMDPKOELKFL ABEMLCJBIEF = 1470;
    uint32 battle_id = 15;
    ItemList item_list_unk1 = 1698;
    uint32 event_id = 12;
    uint32 LEMGICCOKBK = 1;
    uint32 stage_id = 2;
    ItemList item_list_unk2 = 13;
    bool check_identical = 8;
    uint32 retcode = 6;
    ItemList multiple_drop_data = 7;
}

message QuitBattleCsReq {
    BattleStatistics stt = 9;
    RebattleType NKDAAAGPCDB = 11;
}

message QuitBattleScNotify {
}

message RebattleByClientCsNotify {
    BattleStatistics stt = 8;
    RebattleType NKDAAAGPCDB = 2;
}

message SkillUseProperty {
    uint32 skill_id = 1;
    string skill_type = 2;
    uint32 skill_level = 3;
    uint32 skill_use_count = 4;
    double HLJOEGHJNLA = 5;
    double CIDJHAOBNMF = 6;
    double CFFFAPJGGCB = 7;
    uint32 GGDBMJGBDMA = 8;
    uint32 BJGNKIPLNBA = 9;
}

message SpAddSource {
    string source = 1;
    uint32 sp_add = 2;
}

message StatisticEvent {
    BattleStaticticEventType type = 1;
    uint32 LMMDHGCIHBL = 2;
    uint32 param = 3;
}

message SyncClientResVersionCsReq {
    uint32 client_res_version = 12;
}

message SyncClientResVersionScRsp {
    uint32 retcode = 7;
    uint32 client_res_version = 9;
}
