syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message ANKFJAABBFK {
    uint32 group_id = 9;
    uint32 JALHKMEOOPN = 3;
}

enum CmdBenefitV2ActivityType {
    CmdBenefitV2ActivityType_None = 0;
    CmdBenefitV2ActivityType_GetBenefitV2ActivityDataScRsp = 9830;
    CmdBenefitV2ActivityType_GetBenefitV2ActivityDataCsReq = 9825;
    CmdBenefitV2ActivityType_BenefitV2TakeRewardScRsp = 9822;
    CmdBenefitV2ActivityType_BenefitV2DrawScRsp = 9829;
    CmdBenefitV2ActivityType_BenefitV2DrawCsReq = 9827;
    CmdBenefitV2ActivityType_BenefitV2TakeRewardCsReq = 9826;
}

message FMDGFHPOAIO {
    uint32 group_id = 14;
    uint32 JALHKMEOOPN = 5;
}

message ILFJIIDEEBI {
}
