syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ChooseDeliveryCsReq {
    uint32 IHFNFDKLFIC = 10;
    uint32 group_id = 3;
}

message ChooseDeliveryGetDataCsReq {
}

message ChooseDeliveryGetDataScRsp {
    repeated uint32 PCOJLMKPAEL = 15;
    uint32 retcode = 12;
}

message ChooseDeliveryScRsp {
    uint32 group_id = 4;
    uint32 retcode = 3;
    repeated ItemList DJOBNPIAEJP = 11;
    uint32 IHFNFDKLFIC = 15;
}

enum CmdChooseDeliveryType {
    CmdChooseDeliveryType_None = 0;
    CmdChooseDeliveryType_ChooseDeliveryScRsp = 9493;
    CmdChooseDeliveryType_ChooseDeliveryGetDataCsReq = 9485;
    CmdChooseDeliveryType_ChooseDeliveryGetDataScRsp = 9495;
    CmdChooseDeliveryType_ChooseDeliveryCsReq = 9500;
}
