syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CakeRaceCoinScoreChangeScNotify {
    uint32 item_value = 14;
    uint32 score_id = 11;
    uint32 JNBEGEOPGFJ = 10;
}

message CakeRaceFinishFieldRewardScNotify {
    uint32 LOPNADHJKBF = 10;
    ItemList reward = 1;
}

message CakeRaceGetDailyLikeCsReq {
}

message CakeRaceGetDailyLikeScRsp {
    repeated uint32 LPBBJFFNACA = 5;
    uint32 retcode = 11;
}

message CakeRaceGetDataCsReq {
}

message CakeRaceGetDataScRsp {
    uint32 score_id = 11;
    uint32 item_value = 2;
    uint32 retcode = 3;
    repeated uint32 EAHKHGPPLEA = 10;
    repeated uint32 LAJJHAAKGAF = 12;
    uint32 JNBEGEOPGFJ = 5;
}

message CakeRaceGetFriendRankingInfoListCsReq {
}

message CakeRaceGetFriendRankingInfoListScRsp {
    repeated uint32 LPBBJFFNACA = 7;
    uint32 retcode = 15;
    repeated JBHLNAHOJOH MLPHLIHFGKG = 2;
}

message CakeRaceGetHandbookCsReq {
}

message CakeRaceGetHandbookScRsp {
    repeated GKCNOIGHOPM AOBBDDKFBMD = 3;
    uint32 retcode = 4;
}

message CakeRaceLikeFriendRankingInfoCsReq {
    uint32 teleport_id = 2;
}

message CakeRaceLikeFriendRankingInfoScRsp {
    uint32 retcode = 2;
    uint32 teleport_id = 9;
    repeated uint32 LPBBJFFNACA = 12;
    ItemList reward_list = 10;
}

message CakeRaceLoanCsReq {
}

message CakeRaceLoanScRsp {
    uint32 AKEABJGIKLI = 12;
    ItemList item_list = 13;
    uint32 retcode = 2;
}

message CakeRaceStartPveCsReq {
    uint32 LOPNADHJKBF = 10;
}

message CakeRaceStartPveScRsp {
    uint32 LOPNADHJKBF = 4;
    uint32 retcode = 9;
}

message CakeRaceUpdatePveCsReq {
    uint32 LOPNADHJKBF = 9;
    uint32 OPNGHDENCAB = 13;
    ICDBHMEPNDB BOEJNBKDJLM = 12;
    uint32 BCFPLAPCFPL = 4;
    bool MAGPAGCHOHP = 5;
    EMJCPFCMOMK KMOLBEGKLNI = 2;
    bool PIKEOHHECCA = 14;
}

message CakeRaceUpdatePveScRsp {
    uint32 retcode = 11;
}

enum CmdCakeRaceType {
    CmdCakeRaceType_None = 0;
    CmdCakeRaceType_CakeRaceGetDataScRsp = 9150;
    CmdCakeRaceType_CakeRaceLoanCsReq = 9134;
    CmdCakeRaceType_CakeRaceStartPveScRsp = 9129;
    CmdCakeRaceType_CakeRaceLikeFriendRankingInfoScRsp = 9145;
    CmdCakeRaceType_CakeRaceGetDailyLikeCsReq = 9123;
    CmdCakeRaceType_CakeRaceStartPveCsReq = 9124;
    CmdCakeRaceType_CakeRaceGetHandbookScRsp = 9141;
    CmdCakeRaceType_CakeRaceUpdatePveCsReq = 9130;
    CmdCakeRaceType_CakeRaceGetFriendRankingInfoListCsReq = 9147;
    CmdCakeRaceType_CakeRaceGetDailyLikeScRsp = 9136;
    CmdCakeRaceType_CakeRaceCoinScoreChangeScNotify = 9127;
    CmdCakeRaceType_CakeRaceFinishPveScRsp = 9149;
    CmdCakeRaceType_CakeRaceLoanScRsp = 9139;
    CmdCakeRaceType_CakeRaceFinishFieldRewardScNotify = 9148;
    CmdCakeRaceType_CakeRaceGetFriendRankingInfoListScRsp = 9142;
    CmdCakeRaceType_CakeRaceFinishPveCsReq = 9138;
    CmdCakeRaceType_CakeRaceGetHandbookCsReq = 9144;
    CmdCakeRaceType_CakeRaceUpdatePveScRsp = 9135;
    CmdCakeRaceType_CakeRaceLikeFriendRankingInfoCsReq = 9133;
    CmdCakeRaceType_CakeRaceGetDataCsReq = 9146;
}

message EMJCPFCMOMK {
    repeated uint32 CPIKEIGHMGB = 13;
}

message GKCNOIGHOPM {
    uint32 LHHJFMMCBAF = 15;
    uint32 MBNBCPEAALJ = 11;
    uint32 CBNKDHIHECO = 7;
}

message ICDBHMEPNDB {
    uint32 JLAHNBIMKPD = 6;
    uint32 LHHJFMMCBAF = 13;
}

message JBHLNAHOJOH {
    uint32 uid = 6;
    uint32 JNBEGEOPGFJ = 8;
    uint32 FOGJIBONACG = 10;
}

message PIBEHFDDAAJ {
    bool DHLLPOBKLIO = 12;
    uint32 score_id = 2;
}
