syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ABCHBKBKCDF {
    uint32 avatar_id = 4;
    uint32 skin_id = 7;
}

message ChallengePeak {
    repeated ChallengePeakBuild peak_build_list = 4;
    repeated uint32 finished_target_list = 8;
    uint32 cycles_used = 13;
    uint32 peak_id = 2;
    repeated uint32 peak_avatar_id_list = 11;
    bool has_passed = 10;
}

message ChallengePeakBoss {
    ChallengePeakBossClearance easy_mode = 4;
    bool hard_mode_has_passed = 3;
    uint32 BFBHCKEJDIG = 12;
    repeated uint32 finished_target_list = 13;
    ChallengePeakBossClearance hard_mode = 14;
}

message ChallengePeakBossClearance {
    repeated uint32 peak_avatar_id_list = 4;
    uint32 buff_id = 9;
    repeated uint32 LAMPCACOCHP = 11;
    repeated ABCHBKBKCDF EBNNJAEPBGD = 1;
    uint32 DJFGDMIDEHJ = 12;
    bool has_passed = 13;
    uint32 NHOJDHPGBBO = 5;
    uint32 best_cycle_count = 3;
}

message ChallengePeakBuild {
    repeated EquipRelic relic_list = 10;
    uint32 skin_id = 8;
    uint32 avatar_id = 5;
    uint32 equipment_unique_id = 4;
}

message ChallengePeakGroup {
    uint32 count_of_peaks = 9;
    JFBFFIAOPCC PAPDCCKPEPK = 8;
    repeated ChallengePeak peaks = 6;
    uint32 obtained_stars = 1;
    repeated uint32 taken_star_rewards = 7;
    uint32 peak_group_id = 5;
    WaitConfirmData wait_confirm_data = 10;
    bool disable_hard_mode = 14;
    ChallengePeakBoss peak_boss = 2;
}

message ChallengePeakGroupDataUpdateScNotify {
    ChallengePeakGroup challenge_peak_group = 9;
}

message ChallengePeakLineup {
    repeated uint32 peak_avatar_id_list = 4;
    uint32 peak_id = 9;
}

message ChallengePeakRewardGroup {
    ItemList reward = 11;
    uint32 reward_id = 7;
}

message ChallengePeakSettleScNotify {
    bool is_wait_confirm = 9;
    uint32 turn_left = 1;
    bool is_first_pass = 10;
    uint32 peak_id = 11;
    bool is_unlock_easy_boss = 3;
    bool hard_mode_has_passed = 8;
    bool is_boss_target_better = 4;
    bool is_win = 7;
    repeated ChallengePeakRewardGroup peak_reward_group_list = 5;
    uint32 cycles_used = 15;
    repeated uint32 finished_target_list = 13;
}

enum CmdChallengePeakType {
    CmdChallengePeakType_None = 0;
    CmdChallengePeakType_GetChallengePeakDataScRsp = 8929;
    CmdChallengePeakType_GetCurChallengePeakCsReq = 8921;
    CmdChallengePeakType_GetChallengePeakDataCsReq = 8936;
    CmdChallengePeakType_ReStartChallengePeakScRsp = 8907;
    CmdChallengePeakType_LeaveChallengePeakScRsp = 8922;
    CmdChallengePeakType_TakeChallengePeakRewardCsReq = 8920;
    CmdChallengePeakType_TakeChallengePeakRewardScRsp = 8938;
    CmdChallengePeakType_ConfirmChallengePeakSettleScRsp = 8941;
    CmdChallengePeakType_SetChallengePeakBossHardModeScRsp = 8912;
    CmdChallengePeakType_ConfirmChallengePeakSettleCsReq = 8947;
    CmdChallengePeakType_LeaveChallengePeakCsReq = 8908;
    CmdChallengePeakType_ChallengePeakGroupDataUpdateScNotify = 8937;
    CmdChallengePeakType_StartChallengePeakScRsp = 8924;
    CmdChallengePeakType_SetChallengePeakMobLineupAvatarCsReq = 8918;
    CmdChallengePeakType_GetCurChallengePeakScRsp = 8917;
    CmdChallengePeakType_SetChallengePeakMobLineupAvatarScRsp = 8925;
    CmdChallengePeakType_StartChallengePeakCsReq = 8944;
    CmdChallengePeakType_ChallengePeakSettleScNotify = 8932;
    CmdChallengePeakType_ReStartChallengePeakCsReq = 8901;
    CmdChallengePeakType_SetChallengePeakBossHardModeCsReq = 8919;
}

message ConfirmChallengePeakSettleCsReq {
    uint32 peak_id = 7;
    bool IOBCIMIPEOM = 2;
}

message ConfirmChallengePeakSettleScRsp {
    bool IOBCIMIPEOM = 13;
    uint32 peak_id = 15;
    uint32 retcode = 5;
}

message GetChallengePeakDataCsReq {
}

message GetChallengePeakDataScRsp {
    uint32 current_peak_group_id = 12;
    uint32 retcode = 10;
    repeated ChallengePeakGroup challenge_peak_groups = 13;
}

message GetCurChallengePeakCsReq {
}

message GetCurChallengePeakScRsp {
    uint32 boss_buff_id = 6;
    uint32 retcode = 4;
    uint32 peak_id = 2;
    bool has_passed = 13;
}

message JFBFFIAOPCC {
    repeated MEKPDDBLCGK peaks = 1;
}

message LeaveChallengePeakCsReq {
}

message MEKPDDBLCGK {
    repeated uint32 finished_target_list = 12;
    repeated ABCHBKBKCDF peak_avatar_id_list = 6;
    uint32 cycles_used = 5;
    uint32 peak_id = 7;
}

message ReStartChallengePeakCsReq {
}

message ReStartChallengePeakScRsp {
    uint32 retcode = 15;
}

message SetChallengePeakBossHardModeCsReq {
    bool is_hard_mode = 11;
    uint32 peak_group_id = 3;
}

message SetChallengePeakBossHardModeScRsp {
    uint32 retcode = 5;
    bool is_hard_mode = 1;
    uint32 peak_group_id = 3;
}

message SetChallengePeakMobLineupAvatarCsReq {
    uint32 peak_group_id = 7;
    repeated ChallengePeakLineup lineup_list = 12;
}

message StartChallengePeakCsReq {
    repeated uint32 peak_avatar_id_list = 2;
    uint32 peak_id = 8;
    uint32 boss_buff_id = 14;
}

message StartChallengePeakScRsp {
    uint32 retcode = 1;
}

message TakeChallengePeakRewardCsReq {
    repeated uint32 normal_reward_id_list = 11;
    uint32 peak_group_id = 12;
}

message TakeChallengePeakRewardScRsp {
    uint32 retcode = 7;
    repeated ChallengePeakRewardGroup peak_reward_group_list = 10;
    uint32 peak_group_id = 8;
}

message WaitConfirmData {
    uint32 cycles_used = 1;
    bool is_wait_confirm = 2;
    repeated uint32 finished_target_list = 8;
    uint32 peak_id = 6;
}
