syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AALCHOPCBEM {
    CABCPFKAOPP JOOEEKMDAEO = 12;
}

message AFDJNEOHCLB {
    uint32 progress = 12;
    JLPEICPFLMC source = 3;
    uint32 OCJCOOLMCGD = 13;
}

message AJNJDDFGFJL {
    uint32 BFCNALJDHMP = 12;
    uint32 level = 4;
    uint64 IEPAPOPIFHH = 7;
    uint32 max_level = 8;
}

message AKHEOAIPAPA {
    double OJMOBAEEMAP = 12;
    GLBAOKOHKCF GOKKLNBMLCA = 7;
    uint32 unique_id = 5;
    JLPEICPFLMC source = 8;
    double CPLFBOBLFMC = 15;
}

enum BCAMANFJINC {
    BCAMANFJINC_NLCDGIPGFDJ = 0;
    BCAMANFJINC_MLIGAFABJDP = 1;
    BCAMANFJINC_BLLCMLBDLPC = 2;
    BCAMANFJINC_MEBGACKEOOG = 3;
    BCAMANFJINC_GHPKFACFMML = 4;
    BCAMANFJINC_JHJCNLLMPKH = 5;
    BCAMANFJINC_LOFJAGLLHHG = 6;
    BCAMANFJINC_HEIHBJEEGPB = 7;
    BCAMANFJINC_NJPMBLBIBOD = 8;
    BCAMANFJINC_GIFGLDBDELN = 9;
    BCAMANFJINC_NGECENKOPLK = 10;
    BCAMANFJINC_EMGMFOBLAFN = 11;
    BCAMANFJINC_LIJMDJDFIIC = 12;
    BCAMANFJINC_JHGMHCJOKNA = 13;
    BCAMANFJINC_KPCEJLILHMO = 14;
    BCAMANFJINC_AEHHIPFDNFJ = 15;
    BCAMANFJINC_KHBEOADDIFM = 16;
    BCAMANFJINC_action = 17;
    BCAMANFJINC_DACEMIDFHOG = 18;
    BCAMANFJINC_OIKFFLEHFCN = 19;
    BCAMANFJINC_KEJCJJHDKJB = 20;
    BCAMANFJINC_EIIJCLPCFLM = 21;
    BCAMANFJINC_NKJFKBBDDEO = 22;
}

message BDOEDOEBFAJ {
    uint32 GCBDADCOBAE = 11;
    uint32 stage_id = 8;
    repeated AFDJNEOHCLB IFJIHNBDNGN = 5;
    KFOOLGFCNDN ILOODGHPOBM = 3;
    repeated uint32 MGJENMKKIBJ = 2;
    BNHBDMIDFCL FMIGOKIDKJL = 15;
    uint32 item_value = 9;
    repeated uint64 FNJCMFOFCNC = 246;
    repeated uint32 OKHDNEOLLNF = 6;
    uint32 cur_wave = 12;
    repeated DFFLMEMFPLM IEDKELDFHLP = 10;
    uint32 hp = 7;
    repeated PHHFOGFKDBC MEMGHBHGGPN = 4;
    MBLJIEELMKN GHICOBOPHOL = 1385;
    repeated HGCIPBFBNKO LDCJONHGDAN = 1;
    uint32 max_hp = 684;
    repeated LEGNLMENMJK entity_list = 14;
    uint32 NKDDBPGDAEE = 13;
}

message BFGNNODONFI {
}

message BNHBDMIDFCL {
    uint32 unique_id = 1;
    JAAJAPNFMGO DOKPHNPNCPN = 1386;
}

message CABCPFKAOPP {
    uint32 OEKIFIKBMFI = 13;
    repeated uint32 NFPADEPIKML = 2;
    uint32 KDIDDHIDNCG = 11;
    repeated uint32 GCDGGBLOJIC = 14;
}

enum CNEEMBBNNBO {
    CNEEMBBNNBO_NLCDGIPGFDJ = 0;
    CNEEMBBNNBO_EHNIPLNEEDI = 1;
    CNEEMBBNNBO_FAODKNDLNPF = 2;
    CNEEMBBNNBO_INCLHHDFCEL = 3;
}

message ChenLingBuyShopItemScRsp {
    uint32 PLDKENJLKME = 3;
}

message ChenLingFinishPrepareScRsp {
    uint32 PLDKENJLKME = 1;
}

message ChenLingFinishShopScRsp {
    uint32 PLDKENJLKME = 2;
}

message ChenLingGetDataCsReq {
}

message ChenLingGetDataScRsp {
    uint32 retcode = 1;
    FDDNKPJEMJE DJOLGKGKCHE = 7;
    repeated uint32 IMNNAENHBMA = 5;
    BDOEDOEBFAJ KFAIGIIPLOF = 9;
    uint32 GDHOLMIBAEA = 13;
}

message ChenLingMoveEntityScRsp {
    uint32 PLDKENJLKME = 9;
}

message ChenLingQuitStageCsReq {
    uint32 GDIMKFNECOK = 11;
}

message ChenLingQuitStageScRsp {
    DFEGGFFOMKI BFLLJJBHLDF = 8;
    uint32 retcode = 6;
}

message ChenLingRefreshCardScRsp {
    uint32 PLDKENJLKME = 8;
}

message ChenLingRefreshPolicyScRsp {
    uint32 PLDKENJLKME = 1;
}

message ChenLingRefreshShopScRsp {
    uint32 PLDKENJLKME = 5;
}

message ChenLingSelectCardScRsp {
    uint32 PLDKENJLKME = 2;
}

message ChenLingSelectPolicyScRsp {
    uint32 PLDKENJLKME = 6;
}

message ChenLingSellHandCardScRsp {
    uint32 PLDKENJLKME = 11;
}

message ChenLingStartStageCsReq {
    uint32 NKDDBPGDAEE = 14;
    uint32 stage_id = 15;
}

message ChenLingStartStageScRsp {
    BDOEDOEBFAJ AHCGJNDKBCA = 3;
    uint32 retcode = 2;
}

message ChenLingSyncChangeScNotify {
    repeated IOELPDDJGFJ DGNGMJMPFGK = 6;
}

message ChenLingUnlockGridScRsp {
    uint32 PLDKENJLKME = 13;
}

message ChenLingUseHandCardScRsp {
    uint32 PLDKENJLKME = 13;
}

enum CmdChenLingBattleType {
    CmdChenLingBattleType_None = 0;
    CmdChenLingBattleType_ChenLingSellHandCardScRsp = 9587;
    CmdChenLingBattleType_ChenLingMoveEntityCsReq = 9576;
    CmdChenLingBattleType_ChenLingBuyShopItemScRsp = 9616;
    CmdChenLingBattleType_ChenLingSellHandCardCsReq = 9591;
    CmdChenLingBattleType_ChenLingRefreshPolicyScRsp = 9595;
    CmdChenLingBattleType_ChenLingRefreshCardScRsp = 9612;
    CmdChenLingBattleType_ChenLingUseHandCardCsReq = 9590;
    CmdChenLingBattleType_ChenLingSelectPolicyCsReq = 9580;
    CmdChenLingBattleType_ChenLingBuyShopItemCsReq = 9600;
    CmdChenLingBattleType_ChenLingRefreshPolicyCsReq = 9588;
    CmdChenLingBattleType_ChenLingClientStatusChangeCsNotify = 9596;
    CmdChenLingBattleType_ChenLingUnlockGridScRsp = 9607;
    CmdChenLingBattleType_ChenLingStartStageScRsp = 9594;
    CmdChenLingBattleType_ChenLingFinishShopScRsp = 9597;
    CmdChenLingBattleType_ChenLingRefreshCardCsReq = 9584;
    CmdChenLingBattleType_ChenLingFinishPrepareScRsp = 9582;
    CmdChenLingBattleType_ChenLingSyncChangeScNotify = 9583;
    CmdChenLingBattleType_ChenLingRefreshShopCsReq = 9574;
    CmdChenLingBattleType_ChenLingUnlockGridCsReq = 9602;
    CmdChenLingBattleType_ChenLingQuitStageCsReq = 9578;
    CmdChenLingBattleType_ChenLingRefreshShopScRsp = 9605;
    CmdChenLingBattleType_ChenLingUseHandCardScRsp = 9608;
    CmdChenLingBattleType_ChenLingClientStartBattleCsNotify = 9620;
    CmdChenLingBattleType_ChenLingQuitStageScRsp = 9592;
    CmdChenLingBattleType_ChenLingFinishPrepareCsReq = 9589;
    CmdChenLingBattleType_ChenLingHandlePendingActionScRsp = 9613;
    CmdChenLingBattleType_ChenLingHandlePendingActionCsReq = 9610;
    CmdChenLingBattleType_ChenLingFinishShopCsReq = 9593;
    CmdChenLingBattleType_ChenLingStartStageCsReq = 9614;
    CmdChenLingBattleType_ChenLingSelectPolicyScRsp = 9619;
    CmdChenLingBattleType_ChenLingFinishBattleCsReq = 9571;
    CmdChenLingBattleType_ChenLingSelectCardScRsp = 9611;
    CmdChenLingBattleType_ChenLingActivatePrivilegeCsReq = 9603;
    CmdChenLingBattleType_ChenLingMoveEntityScRsp = 9618;
    CmdChenLingBattleType_ChenLingSelectCardCsReq = 9617;
    CmdChenLingBattleType_ChenLingGetDataScRsp = 9599;
    CmdChenLingBattleType_ChenLingGetDataCsReq = 9606;
    CmdChenLingBattleType_ChenLingActivatePrivilegeScRsp = 9598;
    CmdChenLingBattleType_ChenLingFinishBattleScRsp = 9577;
}

message DFEGGFFOMKI {
    uint32 wave = 15;
    uint32 max_hp = 11;
    CNEEMBBNNBO reason = 14;
    uint32 cur_hp = 9;
    uint32 stage_id = 7;
    repeated OGGELMMFPKP PPCKLBHFCCA = 5;
}

message DFFLMEMFPLM {
    PFPPACPMFDJ DJNOLLDHPHJ = 8;
    uint32 BFCNALJDHMP = 2;
}

message DIONONBIIKN {
    uint32 GDIMKFNECOK = 14;
}

message EJDPLLIJDNK {
    uint64 CHFNDAGCEBK = 3;
}

message EJKNEDLPMIB {
    uint32 BFCNALJDHMP = 9;
    GACKCPEPDAF GHPKFACFMML = 15;
}

message EOKKHLOIBIM {
    DFFLMEMFPLM GEOMBJDBHDD = 2;
    DFFLMEMFPLM HEHIOCEPEAE = 11;
}

message FCNMJGGDEFO {
    PFPPACPMFDJ GAJFFBBMMEN = 15;
    uint32 FGIHKKKOGJD = 11;
}

message FDDNKPJEMJE {
    uint32 stage_id = 13;
    bool is_unlock = 9;
}

message FIBKOLLMPMM {
}

message FJJPDJAEJHC {
    repeated uint32 MKOKLLKALDE = 10;
}

message GACKCPEPDAF {
    uint32 level = 10;
    uint64 MLMFNEBLNHP = 14;
    uint32 max_level = 3;
    uint32 config_id = 7;
}

message GBCKAGHDPEB {
}

message GDDLBMCHIED {
    repeated uint32 MKOKLLKALDE = 11;
    uint32 KDIDDHIDNCG = 10;
}

message GEEPIPMBGJD {
    repeated uint32 GCDGGBLOJIC = 6;
    repeated uint32 NFPADEPIKML = 1;
    uint32 KDIDDHIDNCG = 7;
    uint32 OEKIFIKBMFI = 2;
    CABCPFKAOPP JOOEEKMDAEO = 3;
}

message GICMOLJPLGF {
    repeated PHHFOGFKDBC MEMGHBHGGPN = 3;
}

message GKNOCNDPAJA {
    uint32 level = 9;
    uint32 max_level = 14;
    uint64 IEPAPOPIFHH = 12;
}

enum GLBAOKOHKCF {
    GLBAOKOHKCF_NLCDGIPGFDJ = 0;
    GLBAOKOHKCF_COJOIFPPCIJ = 2;
    GLBAOKOHKCF_hp = 3;
    GLBAOKOHKCF_OGGGLOEIOMM = 4;
    GLBAOKOHKCF_CCPLGNNIOCO = 5;
    GLBAOKOHKCF_DGOMNKGLABB = 6;
    GLBAOKOHKCF_PAIEELDAADP = 7;
}

message HGCIPBFBNKO {
    uint32 config_id = 6;
    JLPEICPFLMC source = 3;
    uint64 unique_id = 12;
    JLIFGIMBMBD AENBOONOFLC = 2;
}

message HKKBGLINEOM {
    PFPPACPMFDJ GAJFFBBMMEN = 15;
    uint32 BFCNALJDHMP = 1;
}

message HPKOOPBFEAH {
}

message IIEKKGNJJMC {
    bool DBODGPBOIHC = 3;
    uint32 BFCNALJDHMP = 4;
    uint64 KNDHHAJMBGB = 1;
}

message IOELPDDJGFJ {
    GICMOLJPLGF PJDHBMOIPPO = 2;
    LCKBHJBKHNH CCHBNLOBPGE = 14;
    uint32 cur_hp = 11;
    uint32 rogue_money = 8;
    LEGNLMENMJK AGHANKEAODD = 10;
    uint32 MGKMLJHMNMO = 1;
    AJNJDDFGFJL GDFFAICHLDJ = 13;
    IIEKKGNJJMC BECPNBEFHGC = 7;
    EJKNEDLPMIB PBNOFEFIDFI = 15;
    NEEAHLMKAAB IAOIFAADLLC = 5;
    DFFLMEMFPLM HOEGFMPDBHH = 4;
    FJJPDJAEJHC HLHBOGKHEEO = 9;
    HGCIPBFBNKO ANHDPPOAOGL = 484;
    uint64 ELMMNHBECNI = 95;
    FDDNKPJEMJE DJOLGKGKCHE = 1504;
    uint32 GCBDADCOBAE = 1507;
    uint32 FOJHBIMCLGC = 513;
    NGHEPMFILPE CNCKEHMNJGD = 411;
    KHGFCNNCOGA BJPEEGIFAEA = 752;
    AFDJNEOHCLB OFCPKKMEFKE = 1096;
    LGFBMEACHPI NAPDGGDENBM = 1641;
    BNHBDMIDFCL FMIGOKIDKJL = 991;
    uint32 PMFBIGLPJJA = 1066;
    EJDPLLIJDNK ONAJPGNNLEN = 1719;
    uint32 GDHOLMIBAEA = 1063;
    EOKKHLOIBIM KNANINELANC = 1318;
    KHLAFMBONNK BEOAPFIBDLB = 253;
    JKLKCKNBHCI ADEJOKOIBHC = 166;
    BFGNNODONFI PJMJAPKJINA = 1082;
    MBLJIEELMKN GHICOBOPHOL = 1933;
    JLPEICPFLMC source = 1680;
}

message IOPAIDKIGAJ {
    PFPPACPMFDJ DJNOLLDHPHJ = 8;
}

message JAAJAPNFMGO {
    repeated uint32 GCDGGBLOJIC = 8;
}

message JJLPGBIAADJ {
    uint32 AAIDCOJPLCI = 3;
}

message JKLKCKNBHCI {
}

message JLIFGIMBMBD {
    uint32 HMLBJFJIPCE = 8;
    uint32 BIOFDPICHLC = 4;
    uint32 KKCKMCDGCGK = 11;
}

message JLPEICPFLMC {
    BCAMANFJINC source_type = 10;
    uint64 BNEFLBPCPOI = 9;
    uint32 BFCNALJDHMP = 13;
    uint32 HPDFGFBLDOG = 8;
    uint32 GCPPLLLHBBJ = 1;
    uint32 DJODEIMGKGK = 4;
    uint32 PBHFMIIIPBD = 6;
    uint64 CHFNDAGCEBK = 1458;
    uint32 LEEMKAMANJN = 1262;
    uint32 NKDDBPGDAEE = 1348;
    uint32 EFEENOFADFC = 1245;
    PFPPACPMFDJ DJNOLLDHPHJ = 1549;
}

message KFOOLGFCNDN {
    AALCHOPCBEM EFBPPPNPBKH = 9;
    FIBKOLLMPMM IFCFIPGIIME = 7;
    LJBOELCMGFK OCIHLGBPALK = 4;
    GDDLBMCHIED NNLBNIJJPAH = 5;
    GEEPIPMBGJD DJBMEHBKNDF = 1;
    MLJEJCFJPLE BAMNOFCJMPP = 14;
}

message KHGFCNNCOGA {
    repeated uint32 PJANEJJKOKA = 14;
    uint32 BFCNALJDHMP = 8;
}

message KHLAFMBONNK {
}

message KHMGHGPLPHF {
}

message KNKCNKJOKPA {
    uint32 GPDEFEBDMNM = 5;
}

message LCKBHJBKHNH {
    KFOOLGFCNDN ILOODGHPOBM = 1;
    uint32 cur_wave = 13;
}

message LDNFIICMCHA {
    uint64 KNDHHAJMBGB = 14;
    uint64 IEPAPOPIFHH = 12;
    uint32 max_level = 5;
    repeated GACKCPEPDAF KAJOFKIEKNH = 2;
    uint32 level = 3;
    bool DBODGPBOIHC = 7;
    repeated AKHEOAIPAPA DIILKEEGLOJ = 15;
}

message LEGNLMENMJK {
    uint32 unique_id = 10;
    uint32 card_id = 4;
    LDNFIICMCHA MLIGAFABJDP = 12;
    GKNOCNDPAJA BLLCMLBDLPC = 1;
}

message LGFBMEACHPI {
    repeated uint32 MGJENMKKIBJ = 14;
}

message LJBOELCMGFK {
    repeated uint32 GCDGGBLOJIC = 1;
    uint32 KDIDDHIDNCG = 4;
}

message LKFKOHLGMOJ {
    uint32 NCHPDFCFFCK = 12;
}

message MBLJIEELMKN {
    repeated KVP OCIJDDBLGMH = 3;
}

message MEJECBOGNNN {
    uint32 FGIHKKKOGJD = 7;
}

message MLJEJCFJPLE {
}

message NEEAHLMKAAB {
    uint32 max_level = 13;
    uint32 level = 11;
    uint32 BFCNALJDHMP = 8;
    uint64 IEPAPOPIFHH = 15;
}

message NFAHEHELGEC {
}

message NGHEPMFILPE {
    uint32 BFCNALJDHMP = 5;
    AKHEOAIPAPA GOBMEEHNFDC = 2;
}

message NJJNLJAPMMK {
    uint32 BCJDCONICKP = 2;
}

message OGGELMMFPKP {
    double damage = 7;
    uint32 config_id = 15;
}

message PFPPACPMFDJ {
    int32 x = 12;
    int32 y = 1;
}

message PHHFOGFKDBC {
    uint32 card_id = 2;
    uint32 unique_id = 9;
}

message PIIJEIADMFP {
    bool PBJJAHKLNAA = 8;
}

message PLMPGLKCGBJ {
}
