syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AIGEDICFHCE {
    bool is_win = 9;
    uint32 IMGLLIBJAPC = 12;
}

message AJNKADCOKOL {
    uint32 IMGLLIBJAPC = 9;
    bool is_win = 14;
}

message CAMLFNCBFHI {
    repeated uint32 avatar_id_list = 3;
}

message CNOAGGFCDAL {
}

message ClockParkBuffList {
    repeated FAMLGHGHIOD buff_list = 10;
}

message ClockParkFinishScriptScNotify {
    GIPBHLBFDAH NLEOMLNOKCC = 1;
}

message ClockParkGetInfoCsReq {
}

message ClockParkGetInfoScRsp {
    uint32 progress = 7;
    repeated DEGFFGKMFJJ DCGDHFJLHCN = 9;
    uint32 LNKAKGOCAOF = 11;
    uint32 CDGICHDIIHH = 1;
    repeated uint32 HPEKLHNPDAJ = 2;
    uint32 retcode = 4;
}

message ClockParkGetOngoingScriptInfoCsReq {
}

message ClockParkGetOngoingScriptInfoScRsp {
    LOBFOKCKPKB JOFJEIFLGBP = 12;
    MDDIKNGBPPL HGDLJDAFHLI = 4;
    repeated uint32 FKNBOIIMFLD = 10;
    uint32 INDJEOAJJEN = 14;
    uint32 DCAHJELNJNP = 15;
    uint32 retcode = 6;
    string IMJFLCKFJGF = 5;
    uint32 script_id = 2;
    uint32 GIGAEFCKIAK = 9;
    uint32 NGBJMEHDKHN = 11;
    uint32 JIPPMKBDJJC = 3;
    ClockParkBuffList HABJHGPFGEB = 1;
}

message ClockParkHandleWaitOperationCsReq {
    uint32 JGPHDBDHKKO = 11;
    uint32 script_id = 7;
    NKOCCGLHOML IKNEKEJEGLM = 5;
    KJAIAGDNPGC JFAJEBGKPEH = 1;
    AIGEDICFHCE DIKEDLHGDJJ = 6;
    CAMLFNCBFHI KBOGLMPLNAI = 9;
    IGJLLHMJKPC EJLKEGLKGDN = 10;
    AJNKADCOKOL ACIOPOIJNEF = 15;
    MOEMKBLCKKO MLHNHAFPLKD = 13;
    uint32 GIGAEFCKIAK = 2;
}

message ClockParkHandleWaitOperationScRsp {
    ClockParkPlayStatus LNPGHCLDOKG = 1;
    uint32 IGBHCBNKEBO = 12;
    SceneBattleInfo battle_info = 3;
    uint32 JGPHDBDHKKO = 11;
    uint32 retcode = 10;
    uint32 DMNECEKOLAJ = 9;
}

enum ClockParkPlayStatus {
    ClockParkPlayStatus_ClockParkPlayNone = 0;
    ClockParkPlayStatus_ClockParkPlayNormalDeath = 1;
    ClockParkPlayStatus_ClockParkPlayNormalPass = 2;
    ClockParkPlayStatus_ClockParkPlayFinishScript = 5;
}

message ClockParkStartScriptCsReq {
    repeated uint32 BDGMNPIJDDL = 13;
    uint32 script_id = 6;
}

message ClockParkStartScriptScRsp {
    uint32 script_id = 3;
    uint32 retcode = 8;
}

message ClockParkUnlockTalentCsReq {
    uint32 CKHCLKOALKE = 8;
}

message ClockParkUnlockTalentScRsp {
    uint32 retcode = 5;
    uint32 CKHCLKOALKE = 6;
}

enum CmdClockParkType {
    CmdClockParkType_None = 0;
    CmdClockParkType_ClockParkUseBuffCsReq = 7218;
    CmdClockParkType_ClockParkStartScriptScRsp = 7237;
    CmdClockParkType_ClockParkFinishScriptScNotify = 7204;
    CmdClockParkType_ClockParkGetOngoingScriptInfoScRsp = 7238;
    CmdClockParkType_ClockParkHandleWaitOperationScRsp = 7217;
    CmdClockParkType_ClockParkBattleEndScNotify = 7214;
    CmdClockParkType_ClockParkQuitScriptScRsp = 7212;
    CmdClockParkType_ClockParkUnlockTalentScRsp = 7222;
    CmdClockParkType_ClockParkGetOngoingScriptInfoCsReq = 7220;
    CmdClockParkType_ClockParkUseBuffScRsp = 7225;
    CmdClockParkType_ClockParkGetInfoScRsp = 7229;
    CmdClockParkType_ClockParkHandleWaitOperationCsReq = 7221;
    CmdClockParkType_ClockParkUnlockTalentCsReq = 7208;
    CmdClockParkType_ClockParkGetInfoCsReq = 7236;
    CmdClockParkType_ClockParkStartScriptCsReq = 7232;
    CmdClockParkType_ClockParkQuitScriptCsReq = 7219;
}

message DEGFFGKMFJJ {
    repeated uint32 CFJOGMJIHOE = 9;
    uint32 script_id = 10;
}

message FAMLGHGHIOD {
    uint32 NOJLMNMPKDP = 13;
    uint64 unique_id = 7;
    uint32 buff_id = 10;
}

message FFDLJDAGEML {
    IIMHLPBEDDH CENIOBBIJMF = 14;
}

message FOFGKMONJHJ {
    bool OEKKAJJEGAK = 6;
}

message GEDICCGGDGI {
    bool MHICFGAPPNB = 15;
    uint32 script_id = 8;
}

message GIPBHLBFDAH {
    bool DMNEACGEHEC = 9;
    uint32 progress = 14;
    uint32 DCAHJELNJNP = 1;
    uint32 NGBJMEHDKHN = 4;
    uint32 script_id = 3;
    bool HGPKMHFPMBJ = 13;
    ItemList reward = 12;
}

message IEFICANECDH {
    IIMHLPBEDDH CENIOBBIJMF = 7;
    uint32 NDNHCFBFPMH = 13;
    uint32 gacha_random = 11;
}

message IGJLLHMJKPC {
    uint32 gacha_random = 15;
    bool IMKGOKGKDPH = 14;
}

message IIMHLPBEDDH {
    repeated NIJHCCNMEGA LONFKFCFDND = 11;
    repeated uint32 KCNEKEGGAGG = 9;
}

message KJAIAGDNPGC {
    IIMHLPBEDDH CENIOBBIJMF = 9;
}

message KOCBHDOKFNF {
    IIMHLPBEDDH CENIOBBIJMF = 11;
}

message LOBFOKCKPKB {
    int32 AKKLILNJCPL = 8;
    int32 PNOIJPDMCPG = 6;
    int32 JEKOHIHJFMK = 11;
}

message MDDIKNGBPPL {
    uint32 JGPHDBDHKKO = 13;
    CNOAGGFCDAL ICPMABKBLCD = 11;
    PEGDBKDLJDJ FDNLIPKGBLM = 5;
    NIKCDPGKKLF ABIPNABIDPE = 10;
    KOCBHDOKFNF BPMEBJHDOFC = 7;
    IEFICANECDH HGHBDACDJKP = 15;
    FFDLJDAGEML DLNGPBMGMKM = 3;
    FOFGKMONJHJ BELJJJLLCBK = 8;
    bool ALFNNIIMBLM = 4;
}

message MOEMKBLCKKO {
}

message NIJHCCNMEGA {
    uint32 card_id = 1;
    repeated uint32 KCNEKEGGAGG = 8;
    uint32 NPCBECNBIJK = 4;
}

message NIKCDPGKKLF {
    IIMHLPBEDDH CENIOBBIJMF = 12;
}

message NKOCCGLHOML {
}

message PEGDBKDLJDJ {
    IIMHLPBEDDH CENIOBBIJMF = 7;
}

message PGHBOPEOBHA {
    uint32 script_id = 4;
    uint64 unique_id = 5;
    uint32 JGPHDBDHKKO = 11;
}
