syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message Challenge {
    uint32 score_two = 4;
    uint32 challenge_id = 7;
    uint32 taken_reward = 10;
    uint32 score_id = 14;
    ChallengeStageInfo stage_info = 8;
    bool HGPKMHFPMBJ = 3;
    uint32 record_id = 13;
    uint32 star = 2;
}

message ChallengeBossBuffInfo {
    uint32 buff_one = 11;
    uint32 buff_two = 8;
}

message ChallengeBossBuffList {
    repeated uint32 buff_list = 6;
    uint32 challenge_boss_const = 8;
}

message ChallengeBossInfo {
    repeated AvatarIdentifier avatar_lineup_first = 7;
    ChallengeBossSingleNodeInfo second_node = 6;
    ChallengeBossSingleNodeInfo first_node = 2;
    repeated AvatarIdentifier avatar_lineup_second = 1;
    map<uint32, ChallengeBossEquipmentInfo> challenge_avatar_equipment_map = 8;
    bool unk1 = 12;
    map<uint32, ChallengeBossAvatarRelicInfo> challenge_avatar_relic_map = 11;
}

message ChallengeBossPhaseSettleNotify {
    repeated BattleTarget battle_target_list = 14;
    uint32 star = 13;
    uint32 score_two = 7;
    bool is_second_half = 1;
    uint32 challenge_id = 3;
    bool AGAEPDNHPJC = 5;
    bool is_reward = 15;
    bool is_win = 9;
    uint32 challenge_score = 4;
    uint32 page_type = 2;
    uint32 phase = 6;
}

message ChallengeBossSingleNodeInfo {
    uint32 max_score = 10;
    bool is_win = 14;
    uint32 buff_id = 3;
    bool MBHCJPONJOM = 13;
}

message ChallengeBuffInfo {
    ChallengeStoryBuffInfo story_info = 1;
    ChallengeBossBuffInfo boss_info = 14;
}

message ChallengeCurBuffInfo {
    ChallengeStoryBuffList cur_story_buffs = 9;
    ChallengeBossBuffList cur_boss_buffs = 5;
}

message ChallengeGroup {
    uint64 taken_stars_count_reward = 3;
    uint32 group_id = 2;
}

message ChallengeHistoryMaxLevel {
    uint32 reward_display_type = 2;
    uint32 level = 15;
    bool HNHCFJJNJCE = 12;
}

message ChallengeLineupNotify {
    ExtraLineupType extra_lineup_type = 9;
}

message ChallengeSettleNotify {
    repeated uint32 KDIDCCOOJJC = 9;
    ChallengeHistoryMaxLevel max_level = 12;
    uint32 challenge_score = 5;
    CurChallenge cur_challenge = 15;
    uint32 star = 10;
    uint32 challenge_id = 7;
    ItemList reward = 1;
    uint32 score_two = 13;
    bool is_win = 14;
}

message ChallengeStageInfo {
    ChallengeBossInfo boss_info = 12;
}

enum ChallengeStatus {
    CHALLENGE_UNKNOWN = 0;
    CHALLENGE_DOING = 1;
    CHALLENGE_FINISH = 2;
    CHALLENGE_FAILED = 3;
}

message ChallengeStoryBuffInfo {
    uint32 buff_two = 7;
    uint32 buff_one = 1;
}

message ChallengeStoryBuffList {
    repeated uint32 buff_list = 7;
}

enum CmdChallengeType {
    CmdChallengeType_None = 0;
    CmdChallengeType_StartPartialChallengeCsReq = 1788;
    CmdChallengeType_GetCurChallengeScRsp = 1772;
    CmdChallengeType_LeaveChallengeScRsp = 1791;
    CmdChallengeType_RestartChallengePhaseScRsp = 1741;
    CmdChallengeType_GetChallengeScRsp = 1782;
    CmdChallengeType_StartChallengeCsReq = 1779;
    CmdChallengeType_LeaveChallengeCsReq = 1756;
    CmdChallengeType_GetChallengeGroupStatisticsScRsp = 1748;
    CmdChallengeType_TakeChallengeRewardCsReq = 1704;
    CmdChallengeType_EnterChallengeNextPhaseCsReq = 1738;
    CmdChallengeType_ChallengeBossPhaseSettleNotify = 1746;
    CmdChallengeType_RestartChallengePhaseCsReq = 1781;
    CmdChallengeType_ChallengeSettleNotify = 1798;
    CmdChallengeType_GetChallengeGroupStatisticsCsReq = 1749;
    CmdChallengeType_TakeChallengeRewardScRsp = 1762;
    CmdChallengeType_EnterChallengeNextPhaseScRsp = 1757;
    CmdChallengeType_GetChallengeCsReq = 1734;
    CmdChallengeType_GetCurChallengeCsReq = 1799;
    CmdChallengeType_StartPartialChallengeScRsp = 1715;
    CmdChallengeType_StartChallengeScRsp = 1739;
    CmdChallengeType_ChallengeLineupNotify = 1765;
}

message CurChallenge {
    uint32 challenge_id = 11;
    uint32 dead_avatar_num = 15;
    ChallengeStatus status = 9;
    uint32 score_two = 12;
    ExtraLineupType extra_lineup_type = 14;
    ChallengeCurBuffInfo stage_info = 10;
    repeated KillMonster kill_monster_list = 7;
    uint32 round_count = 1;
    uint32 score_id = 6;
}

message EnterChallengeNextPhaseCsReq {
}

message EnterChallengeNextPhaseScRsp {
    uint32 retcode = 13;
    SceneInfo scene = 1;
}

message FMDAAIKLAJA {
    uint32 group_id = 1;
    bool JFKMNBHOBCL = 2;
    bool EGLLMGLLHDL = 3;
}

message GetChallengeCsReq {
}

message GetChallengeGroupStatisticsCsReq {
    uint32 group_id = 11;
}

message GetChallengeGroupStatisticsScRsp {
    uint32 group_id = 3;
    uint32 retcode = 15;
    ChallengeStatistics challenge_default = 13;
    ChallengeStoryStatistics challenge_story = 9;
    ChallengeBossStatistics challenge_boss = 8;
    PlayerChallengeTierceRecord MEGBIPBAFBP = 1299;
}

message GetChallengeScRsp {
    uint32 retcode = 3;
    repeated ChallengeHistoryMaxLevel max_level_list = 7;
    repeated ChallengeGroup challenge_group_list = 2;
    repeated Challenge challenge_list = 1;
    repeated FMDAAIKLAJA KKIAFPFKLGE = 14;
}

message GetCurChallengeCsReq {
}

message GetCurChallengeScRsp {
    CurChallenge cur_challenge = 2;
    repeated LineupInfo lineup_list = 11;
    uint32 retcode = 4;
}

message KillMonster {
    uint32 kill_num = 13;
    uint32 monster_id = 10;
}

message LeaveChallengeCsReq {
}

message LeaveChallengeScRsp {
    uint32 retcode = 7;
}

message RestartChallengePhaseCsReq {
}

message RestartChallengePhaseScRsp {
    uint32 retcode = 6;
    SceneInfo scene = 7;
}

message StartChallengeCsReq {
    ChallengeBuffInfo stage_info = 14;
    repeated AvatarIdentifier avatar_lineup_first = 13;
    repeated uint32 second_lineup = 3;
    repeated uint32 first_lineup = 7;
    uint32 challenge_id = 9;
    repeated AvatarIdentifier avatar_lineup_second = 11;
}

message StartChallengeScRsp {
    CurChallenge cur_challenge = 13;
    uint32 retcode = 2;
    SceneInfo scene = 7;
    repeated LineupInfo lineup_list = 14;
    ChallengeStageInfo stage_info = 12;
}

message StartPartialChallengeCsReq {
    uint32 buff_id = 13;
    uint32 challenge_id = 15;
    bool is_first_half = 9;
}

message StartPartialChallengeScRsp {
    LineupInfo lineup = 6;
    SceneInfo scene = 7;
    uint32 retcode = 14;
    CurChallenge cur_challenge = 2;
}

message TakeChallengeRewardCsReq {
    uint32 group_id = 2;
}

message TakeChallengeRewardScRsp {
    uint32 retcode = 4;
    ItemList OAKNHADPLJD = 8;
    repeated TakenChallengeRewardInfo taken_reward_list = 12;
    uint32 group_id = 15;
}

message TakenChallengeRewardInfo {
    ItemList reward = 15;
    uint32 star_count = 7;
}
