syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AEMAPGKPPJA {
    uint32 JPPAGGPJOMO = 13;
    LMNCBIDKHLF OLJCAJMFJPO = 9;
    FJKGDHKKDFF FDEEBBFMBLB = 6;
    repeated uint32 OPAEGCBNACJ = 1;
    int32 FJCIKNAKJOG = 11;
}

enum AIMCAMJABNA {
    AIMCAMJABNA_NLCDGIPGFDJ = 0;
    AIMCAMJABNA_ILIIOLJMKME = 1;
}

message BKJCADFCHAB {
    uint32 HONCDMKPBEG = 6;
}

message CGMCMAKMJDK {
    uint32 HLALFNEDFED = 14;
    uint32 CFGEJHAOKED = 12;
    uint32 PDKOHKKMKLF = 10;
    bool is_unlock = 4;
    ChessRogueBoardCellStatus EJEDLGNLOHB = 1;
    uint32 room_id = 8;
    uint32 JMPMDGJLIPF = 7;
    ChessRogueCellSpecialType KFEMJMKMGIJ = 11;
    uint32 id = 5;
    MCDONFNGMJE stage_info = 2;
    bool LDDHLGINDIJ = 9;
}

message CHHBLFHDFEK {
    uint32 BMGCCEONICH = 2;
    uint32 KPDLMKFLJAI = 15;
}

enum ChessRogueBoardCellStatus {
    ChessRogueBoardCellStatus_Idle = 0;
    ChessRogueBoardCellStatus_Selected = 1;
    ChessRogueBoardCellStatus_Processing = 2;
    ChessRogueBoardCellStatus_Finish = 3;
}

enum ChessRogueCellSpecialType {
    ChessRogueCellSpecialType_None = 0;
    ChessRogueCellSpecialType_Locked = 1;
    ChessRogueCellSpecialType_Replicate = 2;
    ChessRogueCellSpecialType_Protected = 3;
    ChessRogueCellSpecialType_Seed = 4;
    ChessRogueCellSpecialType_Stamp = 5;
}

message ChessRogueCellUpdateNotify {
    RogueModifierSourceType CFAOFCGJBMA = 3;
    AIMCAMJABNA reason = 12;
    repeated CGMCMAKMJDK CPPCIGMJALM = 8;
    uint32 AIHCKNAMPBP = 7;
}

message ChessRogueCheatRollCsReq {
    uint32 MMNMIFAAHOF = 12;
    uint32 AMPFBGKHJBF = 7;
}

message ChessRogueCheatRollScRsp {
    KFACLOGFNJF POHEPEEFBOA = 15;
    uint32 retcode = 4;
}

message ChessRogueConfirmRollCsReq {
}

message ChessRogueConfirmRollScRsp {
    uint32 retcode = 3;
    KFACLOGFNJF POHEPEEFBOA = 7;
}

enum ChessRogueDiceStatus {
    ChessRogueDiceStatus_ChessRogueDiceIdle = 0;
    ChessRogueDiceStatus_ChessRogueDiceRolled = 1;
    ChessRogueDiceStatus_ChessRogueDiceConfirmed = 2;
    ChessRogueDiceStatus_ChessRogueDiceGiveup = 3;
}

enum ChessRogueDiceType {
    ChessRogueDiceType_ChessRogueDiceFixed = 0;
    ChessRogueDiceType_ChessRogueDiceEditable = 1;
}

message ChessRogueEnterCellCsReq {
    uint32 LOFMJHJOELO = 7;
    uint32 IHAOMLEPHOM = 15;
}

message ChessRogueEnterCellScRsp {
    uint32 retcode = 13;
    MANINNKMFHG stage_info = 3;
    DJEKEGMEHLK info = 10;
}

message ChessRogueEnterCsReq {
    uint32 id = 9;
}

message ChessRogueEnterNextLayerCsReq {
}

message ChessRogueEnterNextLayerScRsp {
    DJEKEGMEHLK rogue_game_info = 6;
    uint32 retcode = 14;
    MANINNKMFHG stage_info = 7;
    OFGJFLCBBJP HPHKDGJHIJL = 1;
}

message ChessRogueEnterScRsp {
    uint32 id = 11;
    DJEKEGMEHLK info = 12;
    uint32 retcode = 15;
    MANINNKMFHG stage_info = 10;
}

message ChessRogueGiveUpCsReq {
}

message ChessRogueGiveUpScRsp {
    HIMJKAMHLMJ IHNENEGKEPO = 10;
    AEMAPGKPPJA AEFMMOHKCHJ = 15;
    OGHPKFMNNHL MINFCKLKLNJ = 6;
    uint32 retcode = 14;
    MANINNKMFHG stage_info = 11;
    PPAGCEGGCAK LFLCDNGALME = 4;
}

message ChessRogueLeaveCsReq {
}

message ChessRogueLeaveScRsp {
    AEMAPGKPPJA AEFMMOHKCHJ = 3;
    PPAGCEGGCAK LFLCDNGALME = 7;
    HIMJKAMHLMJ IHNENEGKEPO = 13;
    uint32 retcode = 10;
    MANINNKMFHG stage_info = 2;
}

message ChessRogueNousDiceSurfaceUnlockNotify {
    uint32 HBKEEBKFBFI = 11;
}

message ChessRogueNousDiceUpdateNotify {
    MOOKMKEKMKC DDHKAGCLBLH = 7;
}

message ChessRogueNousEditDiceScRsp {
    HGCIAPKELAF IOCCACNJIGD = 1;
    uint32 retcode = 4;
}

message ChessRogueNousEnableRogueTalentCsReq {
    uint32 CKHCLKOALKE = 9;
}

message ChessRogueNousEnableRogueTalentScRsp {
    FDBDLBAPDBE JCOBJAMPOAL = 7;
    uint32 FPCCPKAOGKG = 1;
    uint32 retcode = 5;
}

message ChessRogueNousGetRogueTalentInfoCsReq {
}

message ChessRogueNousGetRogueTalentInfoScRsp {
    FDBDLBAPDBE JCOBJAMPOAL = 10;
    uint32 retcode = 15;
    uint32 FPCCPKAOGKG = 1;
}

message ChessRogueQueryCsReq {
}

message ChessRogueQueryScRsp {
    uint32 retcode = 9;
    DJEKEGMEHLK info = 1;
    HIMJKAMHLMJ IHNENEGKEPO = 15;
    OGHPKFMNNHL MINFCKLKLNJ = 2;
    PPAGCEGGCAK LFLCDNGALME = 13;
}

message ChessRogueQuestFinishNotify {
    uint32 PEGKFPIKPKP = 9;
}

message ChessRogueQuitCsReq {
}

message ChessRogueQuitScRsp {
    uint32 retcode = 12;
    OGHPKFMNNHL MINFCKLKLNJ = 2;
    MANINNKMFHG stage_info = 5;
    LKPCDHCKHKP OEIBHLMDJKA = 11;
    PPAGCEGGCAK LFLCDNGALME = 15;
    HIMJKAMHLMJ IHNENEGKEPO = 10;
    AEMAPGKPPJA AEFMMOHKCHJ = 4;
}

message ChessRogueReRollDiceCsReq {
    uint32 MMNMIFAAHOF = 4;
}

message ChessRogueReRollDiceScRsp {
    uint32 retcode = 4;
    KFACLOGFNJF POHEPEEFBOA = 2;
}

message ChessRogueRollDiceCsReq {
    uint32 MMNMIFAAHOF = 1;
}

message ChessRogueRollDiceScRsp {
    uint32 retcode = 13;
    KFACLOGFNJF POHEPEEFBOA = 3;
}

message ChessRogueSelectCellCsReq {
    uint32 IHAOMLEPHOM = 4;
}

message ChessRogueSelectCellScRsp {
    NAPFNBJDIOO EEGHDAJOHJO = 14;
    uint32 retcode = 1;
}

message ChessRogueSkipTeachingLevelCsReq {
}

message ChessRogueSkipTeachingLevelScRsp {
    ItemList PDJCAHBPKLK = 12;
    uint32 retcode = 8;
}

message ChessRogueStartCsReq {
    uint32 id = 8;
    repeated uint32 unfinished_story_line_id_list = 4;
    repeated uint32 JKPIPNMGGOA = 2;
    uint32 PDFAHEKNHNJ = 14;
    uint32 AFEMBLFCCCH = 3;
    repeated uint32 NOEPBNMJFGL = 6;
    repeated uint32 OCEGEKKFLAL = 5;
}

message ChessRogueStartScRsp {
    OFGJFLCBBJP HPHKDGJHIJL = 2;
    uint32 retcode = 12;
    DJEKEGMEHLK info = 4;
    MANINNKMFHG stage_info = 3;
}

message ChessRogueUpdateActionPointScNotify {
    int32 EABEFBDOJEO = 9;
}

message ChessRogueUpdateAeonModifierValueScNotify {
    uint32 AFEMBLFCCCH = 12;
    int32 FJCIKNAKJOG = 6;
}

message ChessRogueUpdateAllowedSelectCellScNotify {
    repeated uint32 AADAFLKEJGD = 15;
    uint32 AIHCKNAMPBP = 5;
}

message ChessRogueUpdateDiceInfoScNotify {
    KFACLOGFNJF POHEPEEFBOA = 5;
}

message ChessRogueUpdateDicePassiveAccumulateValueScNotify {
    int32 CGPHGIBCNOH = 15;
}

message ChessRogueUpdateLevelBaseInfoScNotify {
    GDHLDNFLOOF GKDCPNLOLNF = 5;
    IOJJCDAPLAJ reason = 11;
}

message ChessRogueUpdateMoneyInfoScNotify {
    AGEOGDOGDMM DHEKLJDBNNP = 3;
}

message ChessRogueUpdateReviveInfoScNotify {
    GAJDPEBBFMG MFEODNJNGDP = 15;
}

message ChessRogueUpdateUnlockLevelScNotify {
    repeated uint32 HKCDKHJCNDC = 12;
}

enum CmdChessRogueType {
    CmdChessRogueType_None = 0;
    CmdChessRogueType_ChessRogueSelectCellScRsp = 5467;
    CmdChessRogueType_ChessRogueConfirmRollCsReq = 5492;
    CmdChessRogueType_ChessRogueUpdateDiceInfoScNotify = 5403;
    CmdChessRogueType_ChessRogueGiveUpScRsp = 5509;
    CmdChessRogueType_ChessRogueUpdateUnlockLevelScNotify = 5417;
    CmdChessRogueType_SelectChessRogueSubStoryScRsp = 5581;
    CmdChessRogueType_EnhanceChessRogueBuffScRsp = 5476;
    CmdChessRogueType_GetChessRogueNousStoryInfoCsReq = 5465;
    CmdChessRogueType_ChessRogueLeaveScRsp = 5483;
    CmdChessRogueType_ChessRogueCellUpdateNotify = 5496;
    CmdChessRogueType_ChessRogueReviveAvatarScRsp = 5520;
    CmdChessRogueType_ChessRogueNousGetRogueTalentInfoCsReq = 5445;
    CmdChessRogueType_ChessRogueConfirmRollScRsp = 5600;
    CmdChessRogueType_SyncChessRogueMainStoryFinishScNotify = 5558;
    CmdChessRogueType_ChessRoguePickAvatarCsReq = 5423;
    CmdChessRogueType_ChessRogueCheatRollScRsp = 5460;
    CmdChessRogueType_ChessRogueRollDiceCsReq = 5437;
    CmdChessRogueType_ChessRogueSkipTeachingLevelScRsp = 5536;
    CmdChessRogueType_ChessRogueQueryCsReq = 5456;
    CmdChessRogueType_SyncChessRogueNousValueScNotify = 5538;
    CmdChessRogueType_ChessRogueLeaveCsReq = 5573;
    CmdChessRogueType_ChessRogueQuitCsReq = 5523;
    CmdChessRogueType_ChessRogueGiveUpCsReq = 5545;
    CmdChessRogueType_ChessRogueQuestFinishNotify = 5497;
    CmdChessRogueType_ChessRogueUpdateAllowedSelectCellScNotify = 5401;
    CmdChessRogueType_ChessRoguePickAvatarScRsp = 5576;
    CmdChessRogueType_ChessRogueEnterScRsp = 5591;
    CmdChessRogueType_ChessRogueUpdateDicePassiveAccumulateValueScNotify = 5410;
    CmdChessRogueType_GetChessRogueNousStoryInfoScRsp = 5477;
    CmdChessRogueType_ChessRogueReRollDiceCsReq = 5562;
    CmdChessRogueType_EnterChessRogueAeonRoomCsReq = 5430;
    CmdChessRogueType_EnhanceChessRogueBuffCsReq = 5566;
    CmdChessRogueType_ChessRogueEnterNextLayerScRsp = 5588;
    CmdChessRogueType_ChessRogueUpdateActionPointScNotify = 5551;
    CmdChessRogueType_EnterChessRogueAeonRoomScRsp = 5425;
    CmdChessRogueType_ChessRogueSelectCellCsReq = 5416;
    CmdChessRogueType_ChessRogueStartScRsp = 5404;
    CmdChessRogueType_ChessRogueCheatRollCsReq = 5513;
    CmdChessRogueType_ChessRogueEnterCsReq = 5448;
    CmdChessRogueType_ChessRogueNousEditDiceScRsp = 5586;
    CmdChessRogueType_ChessRogueChangeyAeonDimensionNotify = 5570;
    CmdChessRogueType_GetChessRogueStoryAeonTalkInfoScRsp = 5518;
    CmdChessRogueType_ChessRogueQuitScRsp = 5422;
    CmdChessRogueType_FinishChessRogueSubStoryScRsp = 5402;
    CmdChessRogueType_ChessRogueNousDiceUpdateNotify = 5441;
    CmdChessRogueType_ChessRogueQueryScRsp = 5432;
    CmdChessRogueType_GetChessRogueBuffEnhanceInfoScRsp = 5428;
    CmdChessRogueType_GetChessRogueStoryInfoCsReq = 5469;
    CmdChessRogueType_ChessRogueUpdateAeonModifierValueScNotify = 5526;
    CmdChessRogueType_ChessRogueEnterCellCsReq = 5535;
    CmdChessRogueType_ChessRogueReRollDiceScRsp = 5455;
    CmdChessRogueType_ChessRogueNousEditDiceCsReq = 5564;
    CmdChessRogueType_SyncChessRogueNousMainStoryScNotify = 5510;
    CmdChessRogueType_GetChessRogueStoryAeonTalkInfoCsReq = 5589;
    CmdChessRogueType_ChessRogueRollDiceScRsp = 5450;
    CmdChessRogueType_ChessRogueEnterCellScRsp = 5418;
    CmdChessRogueType_ChessRogueNousEnableRogueTalentCsReq = 5563;
    CmdChessRogueType_ChessRogueNousEnableRogueTalentScRsp = 5457;
    CmdChessRogueType_ChessRogueEnterNextLayerCsReq = 5511;
    CmdChessRogueType_ChessRogueStartCsReq = 5439;
    CmdChessRogueType_FinishChessRogueSubStoryCsReq = 5569;
    CmdChessRogueType_ChessRogueReviveAvatarCsReq = 5574;
    CmdChessRogueType_ChessRogueUpdateReviveInfoScNotify = 5583;
    CmdChessRogueType_ChessRogueSkipTeachingLevelCsReq = 5444;
    CmdChessRogueType_SyncChessRogueNousSubStoryScNotify = 5462;
    CmdChessRogueType_SelectChessRogueSubStoryCsReq = 5579;
    CmdChessRogueType_GetChessRogueStoryInfoScRsp = 5541;
    CmdChessRogueType_ChessRogueNousGetRogueTalentInfoScRsp = 5499;
    CmdChessRogueType_ChessRogueUpdateMoneyInfoScNotify = 5429;
    CmdChessRogueType_GetChessRogueBuffEnhanceInfoCsReq = 5412;
    CmdChessRogueType_ChessRogueNousDiceSurfaceUnlockNotify = 5478;
    CmdChessRogueType_ChessRogueLayerAccountInfoNotify = 5494;
    CmdChessRogueType_ChessRogueUpdateLevelBaseInfoScNotify = 5452;
}

message DDAFEPBGOHK {
    FDBDLBAPDBE GMILDFJFOGD = 4;
    uint32 FPCCPKAOGKG = 15;
}

message DECHJACNLGP {
    uint32 BJBALPKFELE = 6;
    uint32 monster_id = 9;
}

message DFKMNLIJMFB {
    uint32 POFBAHEECGB = 10;
    bool is_selected = 13;
    repeated DECHJACNLGP GEJNMNBLFLG = 14;
}

message DJEKEGMEHLK {
    KCHPLCFMGLF EIOHFJMFOKF = 9;
    INHBMHCJJCN FMIGOKIDKJL = 7;
    AEMAPGKPPJA AEFMMOHKCHJ = 6;
    MOIOKCDLNHE AFHEGGDHAOC = 14;
    DLCNDCKCIPC story_info = 13;
    NHLBNBBDHMI DNPCCFFFBHN = 2;
    NEGNNJGLFJP EIIHJJEBKOE = 1301;
    EPDDOMFGIMK AJPMADHMGML = 8;
    EGLAPJGFKPN HABJHGPFGEB = 12;
    AGEOGDOGDMM DHEKLJDBNNP = 1;
    LKPCDHCKHKP OEIBHLMDJKA = 11;
    KFACLOGFNJF POHEPEEFBOA = 5;
    uint32 DLOJFEEHLIJ = 15;
}

message DLCNDCKCIPC {
    repeated uint32 AAFIFEGKACO = 11;
    uint32 JGCCIMMEDIJ = 4;
    uint32 HGKBJIAAFPC = 2;
    bool HIFMFMBCODL = 15;
}

message DMGODFDFPEI {
    uint32 AFEMBLFCCCH = 11;
    uint32 MNMJCNOLIII = 5;
}

enum DPBCJGCPMLE {
    DPBCJGCPMLE_PMJGFDCJKML = 0;
    DPBCJGCPMLE_BPGDELOMEKH = 1;
    DPBCJGCPMLE_DNOMGJBOGAD = 2;
    DPBCJGCPMLE_PEIIMIHPEMG = 3;
    DPBCJGCPMLE_KILLHJLIFJD = 4;
    DPBCJGCPMLE_MFDBGOABEKJ = 5;
}

message DPELLHBJGML {
    uint32 EPOHKNLFEAB = 7;
    repeated uint32 AADAFLKEJGD = 3;
    repeated GKDJBPJOGPO AGIJECGIBGJ = 13;
    EJHDHGGMILA BAGNPGNGLOJ = 12;
    IKCONCOKNAN ONKBPKPOHEC = 8;
    uint32 AAKGDLDFIIE = 1;
}

message EHKDAJFLIEI {
    uint32 HHFKOOJBOBF = 13;
    uint32 JAAIADKFPCL = 2;
}

message EJHDHGGMILA {
    LMNCBIDKHLF OLJCAJMFJPO = 8;
    uint32 LGPJLJAMJFJ = 6;
}

message EPDDOMFGIMK {
    int32 OPKEHOLONMJ = 12;
}

message EPHFHKDJKMD {
    uint32 APHIOEALOGI = 15;
    uint32 JGCCIMMEDIJ = 7;
}

message EditChessRogueNousBranchSurfaceCsReq {
    uint32 KKPOIMOFOGM = 3;
    uint32 AINHNOCEBJG = 4;
}

message EnterChessRogueAeonRoomCsReq {
}

message EnterChessRogueAeonRoomScRsp {
    MANINNKMFHG stage_info = 14;
    uint32 retcode = 4;
}

enum FILMJJMEBJA {
    FILMJJMEBJA_NLCDGIPGFDJ = 0;
    FILMJJMEBJA_BFADFAELKLJ = 1;
    FILMJJMEBJA_CIHFGJDCHIA = 2;
    FILMJJMEBJA_GMCLFNKAHIM = 3;
}

message FJKGDHKKDFF {
    repeated DMGODFDFPEI JHBFEGDPLJN = 3;
}

message FOAGKOAJEMD {
}

message FinishChessRogueSubStoryCsReq {
    uint32 HONCDMKPBEG = 13;
}

message FinishChessRogueSubStoryScRsp {
    uint32 HONCDMKPBEG = 6;
    uint32 KPDLMKFLJAI = 13;
    uint32 retcode = 8;
}

message GAJDPEBBFMG {
    ItemCostData LNIEFKBMIPD = 4;
}

enum GDHLDNFLOOF {
    GDHLDNFLOOF_ADHGHGEFMLG = 0;
    GDHLDNFLOOF_BHOGGJNMHPK = 1;
    GDHLDNFLOOF_HDMDBOMJDDI = 2;
    GDHLDNFLOOF_IGDHFMCJMIL = 3;
    GDHLDNFLOOF_EMJFLBCFONO = 4;
    GDHLDNFLOOF_EHMMIFPLLHM = 5;
}

message GKDJBPJOGPO {
    uint32 IHAOMLEPHOM = 8;
}

message GetChessRogueNousStoryInfoCsReq {
}

message GetChessRogueNousStoryInfoScRsp {
    repeated PJBODOPJFGA FNKLMMACCMJ = 11;
    uint32 retcode = 6;
    repeated BKJCADFCHAB POABJDELNGH = 1;
}

message GetChessRogueStoryAeonTalkInfoCsReq {
    uint32 OEANPIHCHHF = 2;
}

message GetChessRogueStoryAeonTalkInfoScRsp {
    uint32 OEANPIHCHHF = 8;
    uint32 retcode = 14;
    map<uint32, uint32> LDPAJKIEPIP = 9;
}

message GetChessRogueStoryInfoCsReq {
}

message GetChessRogueStoryInfoScRsp {
    repeated EPHFHKDJKMD POABJDELNGH = 6;
    uint32 retcode = 9;
    repeated CHHBLFHDFEK FNKLMMACCMJ = 7;
}

message HGCIAPKELAF {
    uint32 MABFMAFCEOA = 11;
    repeated EditChessRogueNousBranchSurfaceCsReq LFLFEKEAOCL = 14;
    uint32 AHNGMINODKG = 5;
    uint32 PDFAHEKNHNJ = 6;
}

message HIMJKAMHLMJ {
    FJKGDHKKDFF FDEEBBFMBLB = 2;
    LPCINMGGCNI EIIHJJEBKOE = 8;
    repeated uint32 FEBKOJODAAM = 3;
    DDAFEPBGOHK JCOBJAMPOAL = 14;
    repeated uint32 HKCDKHJCNDC = 1;
    MOOKMKEKMKC IOCCACNJIGD = 13;
}

message IFFEHFHAKCB {
    uint32 avatar_id = 8;
}

message IKCONCOKNAN {
    uint32 ABOHPPHHPEI = 10;
    uint32 width = 12;
    uint32 GHKDAJNDBBA = 11;
    uint32 height = 14;
    repeated CGMCMAKMJDK CPPCIGMJALM = 2;
}

message IOHKFHBGICD {
    ItemList item_list = 7;
}

enum IOJJCDAPLAJ {
    IOJJCDAPLAJ_OLBIJIJCONK = 0;
    IOJJCDAPLAJ_HCFMGBEFBGD = 1;
}

message JECIOGKPHFN {
    repeated uint32 JJHFHLAHLGP = 13;
}

message JKLCLLAFHOC {
    DFKMNLIJMFB MGACFLNJLCK = 7;
    JECIOGKPHFN MKMLKGOOAMK = 13;
}

message KCHPLCFMGLF {
    GAJDPEBBFMG MFEODNJNGDP = 7;
    repeated IFFEHFHAKCB JOLEGACINNK = 11;
}

message KFACLOGFNJF {
    bool BGDHHJLICFA = 10;
    bool IHCAMLMFAOH = 1354;
    uint32 DGLIOIEKGNP = 12;
    uint32 BMLMHPPLDDE = 11;
    repeated uint32 BDGMPDLBDGN = 162;
    uint32 EFDMLFGILKK = 5;
    uint32 FLADMNIKGEI = 14;
    int32 CMDDPMHCALK = 467;
    uint32 ONCIOGBKPPI = 15;
    ChessRogueDiceStatus OACDALINONI = 3;
    ChessRogueDiceType CEBDDDJMJIJ = 1;
    HGCIAPKELAF GMDKBGODBCB = 975;
    BMCNDLNONMO OBLADGDFCCN = 1974;
    uint32 JDLKMDFFMGP = 13;
    LMNCBIDKHLF BOPGHOPCFHF = 402;
    uint32 DGHEPBKLKDP = 9;
}

message LKPCDHCKHKP {
    uint32 MDAIAMFJNHM = 12;
    int32 EABEFBDOJEO = 10;
    uint32 id = 5;
    uint32 MLLDCLNMIOG = 15;
    uint32 GKDCPNLOLNF = 7;
    DPELLHBJGML board = 1;
}

message LMNCBIDKHLF {
    repeated BMCNDLNONMO HDLGLFGKONC = 11;
}

message LPCINMGGCNI {
    repeated uint32 KHCANAKMBDJ = 9;
}

message MANINNKMFHG {
    SceneInfo scene = 2;
    LineupInfo lineup = 7;
}

message MCDONFNGMJE {
    DFKMNLIJMFB MGACFLNJLCK = 15;
    JECIOGKPHFN MKMLKGOOAMK = 7;
    JKLCLLAFHOC LPAAMNFFAIB = 3;
}

message MOIOKCDLNHE {
    repeated uint32 GBLLJKFOIDK = 10;
    repeated uint32 IDCJMPMJHGC = 1;
    bool LKDOGPNPGPF = 15;
    bool HIFMFMBCODL = 2;
    uint32 HONCDMKPBEG = 4;
    repeated uint32 EKNOAJJDPMM = 7;
    uint32 KPDLMKFLJAI = 3;
}

message MOOKMKEKMKC {
    repeated uint32 ADLKMLFOFPF = 5;
    repeated HGCIAPKELAF BILCGENIGJM = 14;
    map<uint32, bool> PEGDMOMCFAD = 1;
}

message NAPFNBJDIOO {
    IOHKFHBGICD reward_item = 10;
    EHKDAJFLIEI MCGGEAAHBPD = 14;
}

message NEGNNJGLFJP {
    repeated uint32 KEHKLHMEABI = 15;
}

message OFGJFLCBBJP {
    repeated CGMCMAKMJDK CPPCIGMJALM = 5;
    uint32 EIMFLPNFPGM = 12;
}

message OGHPKFMNNHL {
    repeated uint32 AFGFOBPLFIL = 8;
    ItemList DAKEDPKJMLB = 3;
    uint32 HLOCCOOMBGG = 12;
    uint32 MMIDEAMEANB = 7;
    bool is_finish = 4;
    LineupInfo BJDLGBBPFCK = 11;
    uint32 KPDLMKFLJAI = 6;
    APNCCNFJBKO HABJHGPFGEB = 2;
    DPBCJGCPMLE HCPBMIEGDON = 13;
    uint32 OBBGJAFECBE = 14;
    uint32 ADMADHCDHJE = 9;
    uint32 INNAPIIHJFK = 1259;
    GMIJHCONFIH DNPCCFFFBHN = 5;
    uint32 DLOJFEEHLIJ = 923;
    uint32 difficulty = 1;
    uint32 OEGLLHMMBEM = 46;
    uint32 OLMLOEHHFCG = 784;
    MOIOKCDLNHE AFHEGGDHAOC = 1098;
    uint32 score_id = 778;
}

message PBILBBMINBI {
    uint32 IJAOJBIBDEN = 7;
}

message PJBODOPJFGA {
    FILMJJMEBJA status = 2;
    uint32 KPDLMKFLJAI = 1;
}

message PPAGCEGGCAK {
    MOOKMKEKMKC IOCCACNJIGD = 9;
    LPCINMGGCNI EIIHJJEBKOE = 5;
    repeated uint32 HKCDKHJCNDC = 4;
    DDAFEPBGOHK JCOBJAMPOAL = 14;
    FJKGDHKKDFF FDEEBBFMBLB = 2;
    repeated uint32 FEBKOJODAAM = 15;
}

message SelectChessRogueSubStoryCsReq {
    uint32 HONCDMKPBEG = 1;
    uint32 rogue_dialogue_event_id = 2;
}

message SelectChessRogueSubStoryScRsp {
    uint32 retcode = 7;
    uint32 rogue_dialogue_event_id = 14;
}

message SyncChessRogueMainStoryFinishScNotify {
    uint32 KPDLMKFLJAI = 3;
}

message SyncChessRogueNousMainStoryScNotify {
    repeated PJBODOPJFGA FNKLMMACCMJ = 1;
}

message SyncChessRogueNousSubStoryScNotify {
    uint32 HONCDMKPBEG = 14;
}

message SyncChessRogueNousValueScNotify {
    EPDDOMFGIMK AJPMADHMGML = 8;
}
