syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BBDLCOJKGMI {
    GLLDHGHJLOA PHLAMKCLLKP = 10;
}

enum BDEJGKKACMA {
    BDEJGKKACMA_NLCDGIPGFDJ = 0;
    BDEJGKKACMA_hp = 1;
    BDEJGKKACMA_COJOIFPPCIJ = 2;
}

message CJHOCMLPMJD {
    repeated uint32 AJFJLCKPNAM = 5;
}

message ChimeraDuelChangeLineupCsReq {
    uint32 ALJOJIDAAPC = 6;
    uint32 GIECFFNDLEB = 14;
    repeated uint32 AJFJLCKPNAM = 12;
}

message ChimeraDuelChangeLineupScRsp {
    repeated uint32 AJFJLCKPNAM = 2;
    uint32 retcode = 9;
}

message ChimeraDuelEndGameScRsp {
    uint32 retcode = 8;
    EBPBMFBFEJA CECFDNCDBEI = 6;
}

message ChimeraDuelEndRoundBattleStageCsReq {
    uint32 MILMHPODLBB = 14;
    DIIKFKNEHHG NONPIMDDJNN = 11;
    IDGMALDABBE stt = 12;
}

message ChimeraDuelEndRoundBattleStageScRsp {
    uint32 retcode = 14;
    DIIKFKNEHHG NONPIMDDJNN = 3;
    LCEDDGELBMJ CFDIKLBINHK = 893;
    EBPBMFBFEJA CECFDNCDBEI = 572;
}

message ChimeraDuelEndRoundShopStageCsReq {
}

message ChimeraDuelEndRoundShopStageScRsp {
    LCEDDGELBMJ CFDIKLBINHK = 12;
    uint32 retcode = 15;
}

message ChimeraDuelFinishMasterChallengeScRsp {
    uint32 IPINHNFCIOE = 6;
    uint32 retcode = 11;
}

message ChimeraDuelGetDataCsReq {
}

message ChimeraDuelGetDataScRsp {
    uint32 retcode = 3;
    LCEDDGELBMJ CFDIKLBINHK = 2;
    PCBOLEAFMDN COFPFIDNONN = 13;
}

message ChimeraDuelGetFriendListCsReq {
}

message ChimeraDuelGetFriendListScRsp {
    uint32 retcode = 13;
    repeated MPPHIOJNKGB friend_list = 8;
}

message ChimeraDuelPlayerRankData {
    uint32 score_id = 10;
    uint32 rank = 3;
}

message ChimeraDuelSaveFriendPvpLineupCsReq {
    uint32 slot = 13;
}

message ChimeraDuelSaveFriendPvpLineupScRsp {
    uint32 retcode = 10;
    uint32 slot = 7;
    PNCNGIAMLCA lineup = 1;
}

message ChimeraDuelSelectGameScRsp {
    uint32 FGLEKNDHMKN = 14;
    uint32 retcode = 8;
}

message ChimeraDuelSellChimeraCsReq {
    uint32 NDJGKJMPPHJ = 4;
    repeated uint32 AJFJLCKPNAM = 3;
}

message ChimeraDuelSellChimeraScRsp {
    uint32 retcode = 4;
    uint32 NDJGKJMPPHJ = 9;
    repeated uint32 AJFJLCKPNAM = 2;
}

message ChimeraDuelSetFriendDefendLineupCsReq {
    uint32 slot = 9;
}

message ChimeraDuelSetFriendDefendLineupScRsp {
    uint32 slot = 8;
    uint32 retcode = 13;
}

message ChimeraDuelShopBuyChimeraCsReq {
    uint32 KODOOHHPIKN = 5;
    repeated uint32 FMMICIHEOCM = 2;
    uint32 GCKFOOIEHHA = 10;
}

message ChimeraDuelShopBuyChimeraScRsp {
    uint32 retcode = 3;
}

message ChimeraDuelShopBuyItemCsReq {
    uint32 AGBAIFPNKII = 6;
    uint32 JHINLPCKMPK = 12;
}

message ChimeraDuelShopBuyItemScRsp {
    uint32 retcode = 1;
}

message ChimeraDuelShopLockCsReq {
    bool is_locked = 6;
    uint32 NDJGKJMPPHJ = 11;
    uint32 AGBAIFPNKII = 10;
}

message ChimeraDuelShopLockScRsp {
    uint32 retcode = 2;
    bool is_locked = 14;
    uint32 NDJGKJMPPHJ = 10;
    uint32 AGBAIFPNKII = 3;
}

message ChimeraDuelShopRefreshCsReq {
}

message ChimeraDuelShopRefreshScRsp {
    uint32 retcode = 6;
}

message ChimeraDuelStartGameCsReq {
    uint32 IPINHNFCIOE = 15;
}

message ChimeraDuelStartGameScRsp {
    LCEDDGELBMJ CFDIKLBINHK = 4;
    uint32 retcode = 8;
}

message ChimeraDuelSyncChangeScNotify {
    repeated LGEDKNLBCAN DGNGMJMPFGK = 4;
}

message ChimeraDuelUnlockMasterCsReq {
    uint32 IPINHNFCIOE = 15;
}

message ChimeraDuelUnlockMasterScRsp {
    uint32 retcode = 5;
    uint32 IPINHNFCIOE = 10;
}

enum CmdChimeraDuelType {
    CmdChimeraDuelType_None = 0;
    CmdChimeraDuelType_ChimeraDuelStartGameScRsp = 9247;
    CmdChimeraDuelType_ChimeraDuelSetFriendDefendLineupCsReq = 9233;
    CmdChimeraDuelType_ChimeraDuelSaveFriendPvpLineupCsReq = 9238;
    CmdChimeraDuelType_ChimeraDuelEndGameCsReq = 9229;
    CmdChimeraDuelType_ChimeraDuelSetFriendDefendLineupScRsp = 9237;
    CmdChimeraDuelType_ChimeraDuelChangeLineupCsReq = 9251;
    CmdChimeraDuelType_ChimeraDuelUnlockMasterCsReq = 9218;
    CmdChimeraDuelType_ChimeraDuelSelectGameScRsp = 9243;
    CmdChimeraDuelType_ChimeraDuelEndRoundBattleStageScRsp = 9227;
    CmdChimeraDuelType_ChimeraDuelUnlockMasterScRsp = 9232;
    CmdChimeraDuelType_ChimeraDuelSyncChangeScNotify = 9257;
    CmdChimeraDuelType_ChimeraDuelShopLockScRsp = 9235;
    CmdChimeraDuelType_ChimeraDuelShopBuyItemCsReq = 9224;
    CmdChimeraDuelType_ChimeraDuelShopBuyItemScRsp = 9252;
    CmdChimeraDuelType_ChimeraDuelSelectGameCsReq = 9256;
    CmdChimeraDuelType_ChimeraDuelSaveFriendPvpLineupScRsp = 9223;
    CmdChimeraDuelType_ChimeraDuelChangeLineupScRsp = 9220;
    CmdChimeraDuelType_ChimeraDuelSellChimeraCsReq = 9259;
    CmdChimeraDuelType_ChimeraDuelEndRoundShopStageCsReq = 9230;
    CmdChimeraDuelType_ChimeraDuelFinishMasterChallengeScRsp = 9258;
    CmdChimeraDuelType_ChimeraDuelGetFriendListCsReq = 9250;
    CmdChimeraDuelType_ChimeraDuelFinishMasterChallengeCsReq = 9216;
    CmdChimeraDuelType_ChimeraDuelSellChimeraScRsp = 9240;
    CmdChimeraDuelType_ChimeraDuelShopRefreshCsReq = 9214;
    CmdChimeraDuelType_ChimeraDuelShopBuyChimeraCsReq = 9211;
    CmdChimeraDuelType_ChimeraDuelEndGameScRsp = 9222;
    CmdChimeraDuelType_ChimeraDuelGetDataScRsp = 9239;
    CmdChimeraDuelType_ChimeraDuelGetFriendListScRsp = 9253;
    CmdChimeraDuelType_ChimeraDuelShopBuyChimeraScRsp = 9217;
    CmdChimeraDuelType_ChimeraDuelEndRoundShopStageScRsp = 9248;
    CmdChimeraDuelType_ChimeraDuelStartGameCsReq = 9242;
    CmdChimeraDuelType_ChimeraDuelShopRefreshScRsp = 9245;
    CmdChimeraDuelType_ChimeraDuelShopLockCsReq = 9228;
    CmdChimeraDuelType_ChimeraDuelEndRoundBattleStageCsReq = 9231;
    CmdChimeraDuelType_ChimeraDuelGetDataCsReq = 9246;
}

enum DIIKFKNEHHG {
    DIIKFKNEHHG_NLCDGIPGFDJ = 0;
    DIIKFKNEHHG_EHNIPLNEEDI = 1;
    DIIKFKNEHHG_FAODKNDLNPF = 2;
    DIIKFKNEHHG_EEOOMIBEMNH = 3;
}

message DMOJMNKOILL {
    uint32 item_id = 6;
    bool IFIGFODOPBB = 8;
    uint32 AGBAIFPNKII = 13;
    bool is_locked = 15;
}

message EBPBMFBFEJA {
    bool ENFKEAEGPBJ = 9;
    ChimeraDuelPlayerRankData AAIMONALOPD = 15;
    LCEDDGELBMJ CFDIKLBINHK = 6;
    uint32 FGLEKNDHMKN = 14;
}

message FJJHCDGNDPD {
    repeated uint32 ACCKECIHCGJ = 2;
    repeated uint32 JJOJFFAOEDI = 6;
}

message FLOPNJFNAOG {
    POACIACEJJN JOOEEKMDAEO = 3;
    bool NBHLDBBBPPA = 10;
}

message GIEPFAIPADI {
    repeated uint32 FMMICIHEOCM = 3;
}

message GLLDHGHJLOA {
    uint32 KIMKENNLHEH = 8;
    uint32 uid = 12;
    repeated NHDGNBKBNDB BCGOAIPKGIK = 2;
    uint32 rank = 13;
    repeated uint32 AJFJLCKPNAM = 4;
    uint32 head_icon = 6;
    uint32 IPINHNFCIOE = 11;
    uint32 hp = 10;
    string nickname = 7;
}

message HNAOOMKGFCB {
    uint32 LLMHAEAPGON = 14;
    uint32 BHCCDFFBAAM = 8;
    PDHFFPOJNJG source_type = 3;
}

message IDGMALDABBE {
    NDLBFFKAGBN NMPGPDMHKAM = 1;
    repeated KELKOMPBONA EECAHBHNDHC = 13;
    repeated KELKOMPBONA IIFPJKNCLGF = 6;
    uint32 total_damage = 5;
    uint32 cost_time = 14;
}

message JJKOHCPBGAL {
    uint32 FLIEDGKFNOL = 5;
    GIEPFAIPADI LHEOBNDKGHD = 6;
    HNAOOMKGFCB source = 14;
    BDEJGKKACMA LLCOEPJFGPE = 1518;
    uint32 BNCCMEGJONF = 87;
    FJJHCDGNDPD IAECKEDODEF = 1351;
}

message JJNHIKIGKJC {
    uint32 item_id = 10;
    uint32 unique_id = 4;
}

message KELKOMPBONA {
    uint32 DKHCOHKFKFA = 5;
    int32 atk = 7;
    uint32 grid_fight_equipment_id = 3;
    int32 hp = 8;
    uint32 unique_id = 15;
    uint32 exp = 9;
    uint32 index = 14;
    uint32 level = 4;
    uint32 MBNBFBNKLGH = 2;
    KPEPGHLKNFG status = 1;
    uint32 FGECDDFBFOJ = 6;
    uint32 DIECMLHJCFE = 10;
    uint32 EBMJGPMHDMK = 11;
}

message KGHDDIBDABP {
    uint32 FGECDDFBFOJ = 6;
    uint32 grid_fight_equipment_id = 4;
    bool is_locked = 15;
    uint32 NDJGKJMPPHJ = 13;
    uint32 IPAOBKONIFL = 14;
}

enum KPEPGHLKNFG {
    KPEPGHLKNFG_LCNJHOKLMPN = 0;
    KPEPGHLKNFG_JJBEPKLOLCP = 1;
    KPEPGHLKNFG_DOGMHOAOJFD = 2;
}

message LCEDDGELBMJ {
    repeated NHDGNBKBNDB BCGOAIPKGIK = 3;
    uint32 IDNHBBMLNJK = 2;
    uint32 JGPHDBDHKKO = 9;
    uint32 KIMKENNLHEH = 5;
    repeated uint32 HGKDHJHKFBP = 11;
    uint32 BAJHKGJPFED = 14;
    uint32 NMPABPJHGPE = 7;
    uint32 IPINHNFCIOE = 4;
    uint32 hp = 13;
    POACIACEJJN HKFFIGBBFAE = 1424;
    BBDLCOJKGMI PJCKOBNPFCB = 538;
}

message LGEDKNLBCAN {
    JJKOHCPBGAL ALPKKNKAFBG = 2;
    uint32 PBCGHKNGBFC = 12;
    NHDGNBKBNDB PFOBPLCGGGI = 8;
    uint32 KBPJKIEBBON = 3;
    FLOPNJFNAOG KJHMPBOIGGE = 4;
    CJHOCMLPMJD FICFIOENBEN = 9;
    uint32 GCKFOOIEHHA = 7;
    uint32 HFOKEKMCOBP = 14;
    uint32 CIFFLEBCFGK = 1;
    MAFDLBFIJMB BHPPAPONGOE = 13;
    uint32 NGBAKCIGBMN = 15;
}

message MAFDLBFIJMB {
    PNCNGIAMLCA lineup = 5;
    uint32 slot = 7;
}

message MPPHIOJNKGB {
    PNCNGIAMLCA lineup = 10;
    uint32 score_id = 8;
    uint32 uid = 15;
}

message NDLBFFKAGBN {
    uint32 total_auto_turns = 7;
    uint32 ODIBDCLGKBE = 9;
    uint32 BPHNEOLCKAD = 5;
    uint32 total_turns = 11;
    uint32 LPLLIICLCHB = 4;
    uint32 MHDBNNKHBBL = 12;
}

message NHDGNBKBNDB {
    uint32 LLEOGLLHCLK = 2;
    JJNHIKIGKJC equip = 13;
    uint32 exp = 10;
    int32 GIFJODBPLPJ = 3;
    uint32 FGECDDFBFOJ = 1;
    uint32 unique_id = 12;
    int32 OEEIPJDNMOK = 15;
}

message PCBOLEAFMDN {
    uint32 CIFFLEBCFGK = 3;
    uint32 DEFHFAGLMLC = 6;
    repeated uint32 FOLMLBOLGEM = 9;
    ChimeraDuelPlayerRankData AAIMONALOPD = 14;
    uint32 FGLEKNDHMKN = 15;
    repeated uint32 HAKLMIAENCF = 7;
    repeated MAFDLBFIJMB GNJGPFDKLBH = 11;
    uint32 NGBAKCIGBMN = 12;
    repeated uint32 PGGOOINMOLF = 13;
}

enum PDHFFPOJNJG {
    PDHFFPOJNJG_NLCDGIPGFDJ = 0;
    PDHFFPOJNJG_GIKNCJMJLFE = 1;
    PDHFFPOJNJG_PAGPNOKLNOM = 2;
    PDHFFPOJNJG_LPIINKCPJPO = 3;
    PDHFFPOJNJG_DIMIFCJPHME = 4;
    PDHFFPOJNJG_AJGOEJHKOKE = 5;
}

message PNCNGIAMLCA {
    repeated uint32 AJFJLCKPNAM = 1;
    repeated NHDGNBKBNDB BCGOAIPKGIK = 12;
    uint32 IPINHNFCIOE = 8;
}

message POACIACEJJN {
    repeated KGHDDIBDABP DKCMMMPNEME = 1;
    repeated DMOJMNKOILL LCJFDCHINHL = 3;
}
