syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message AABJNONNLML {
    uint32 index = 5;
    repeated uint32 FKGLNIAHGOA = 1;
    uint32 KDIDDHIDNCG = 8;
    uint32 HADIHNKDBAD = 7;
}

message BGAIEEIKOKK {
    uint32 total_score = 12;
    uint32 star_num = 4;
    uint32 level_id = 11;
    bool has_passed = 3;
}

message ChenLingFesBusinessDayEndCsReq {
    uint32 fever = 268;
    repeated AABJNONNLML FBNBEMECJIJ = 1;
    uint32 HPHHKJHGMPJ = 5;
    repeated PGIEBMKMECE MBFLDKEDBHN = 2;
    uint32 business_day = 11;
    uint32 COJGECEMCFN = 12;
    uint32 play_time = 102;
    double happy_progress = 8;
    uint32 EJEOGKPEIBF = 10;
    repeated NPNAEPOKPNE GOKMDCOJPHC = 7;
    uint32 DBODBBOMJAD = 9;
    repeated LECPPIEIENH BAOPBDDEBKP = 4;
    repeated HDLMAPACKNH PJGODPMGMEO = 14;
    uint32 fever_cnt_today = 1445;
    repeated EDHOBLLOBNP HDNGJJILDCE = 6;
    repeated PGEDFOBAEBC MNLCAOLGEMM = 15;
    uint32 OCLLAPEHDDH = 3;
    uint32 business_time = 496;
}

message ChenLingFesBusinessDayEndScRsp {
    string FGGCAOAPGPA = 3;
    uint32 business_day = 10;
    DMHADFNOIGP EHIHHFMGNHH = 13;
    MOJFFDOILBN GAAHAOGLNPJ = 1;
    uint32 FGKPIDLKALL = 12;
    uint32 retcode = 11;
}

message ChenLingFesLevelEndCsReq {
    uint32 level_id = 6;
}

message ChenLingFesLevelEndScRsp {
    uint32 level_id = 13;
    DMHADFNOIGP level_data = 3;
    uint32 retcode = 8;
}

message ChenLingFesLevelLeaveCsReq {
    uint32 level_id = 1;
}

message ChenLingFesLevelLeaveScRsp {
    uint32 retcode = 12;
    uint32 level_id = 7;
}

message ChenLingFesLevelResumeCsReq {
    uint32 level_id = 3;
}

message ChenLingFesLevelResumeScRsp {
    uint32 FGKPIDLKALL = 2;
    uint32 level_id = 4;
    uint32 retcode = 11;
}

message ChenLingFesLevelStartCsReq {
    uint32 level_id = 15;
}

message ChenLingFesLevelStartScRsp {
    uint32 level_id = 5;
    uint32 retcode = 10;
    uint32 FGKPIDLKALL = 14;
    string FGGCAOAPGPA = 6;
    string NLMEEEKBPKO = 11;
}

message ChenLingFesRaidKickedNotify {
    uint32 raid_id = 9;
}

enum CmdChenLingFesType {
    CmdChenLingFesType_None = 0;
    CmdChenLingFesType_ChenLingFesRaidKickedNotify = 9919;
    CmdChenLingFesType_ChenLingFesLevelResumeCsReq = 9932;
    CmdChenLingFesType_ChenLingFesLevelLeaveCsReq = 9908;
    CmdChenLingFesType_ChenLingFesBusinessDayEndScRsp = 9917;
    CmdChenLingFesType_ChenLingFesLevelStartCsReq = 9944;
    CmdChenLingFesType_ChenLingFesLevelLeaveScRsp = 9922;
    CmdChenLingFesType_ChenLingFesLevelResumeScRsp = 9937;
    CmdChenLingFesType_GetChenLingFesDataScRsp = 9929;
    CmdChenLingFesType_ChenLingFesLevelEndScRsp = 9938;
    CmdChenLingFesType_ChenLingFesLevelStartScRsp = 9924;
    CmdChenLingFesType_ChenLingFesLevelEndCsReq = 9920;
    CmdChenLingFesType_ChenLingFesBusinessDayEndCsReq = 9921;
    CmdChenLingFesType_GetChenLingFesDataCsReq = 9936;
}

message DMHADFNOIGP {
    bool is_success = 5;
    repeated MOJFFDOILBN JOJJKJFHMBI = 2;
}

message EDHOBLLOBNP {
    uint32 index = 2;
    repeated uint32 NELBBCIGIGF = 10;
    repeated uint32 OBGMKBIOMKB = 4;
    uint32 JJPMDBCPJBA = 9;
}

message GetChenLingFesDataCsReq {
}

message GetChenLingFesDataScRsp {
    repeated BGAIEEIKOKK PNDPCELOGHG = 5;
    OFGLEOIIJBD LAEDNIBCNKF = 14;
    uint32 retcode = 1;
}

message HDLMAPACKNH {
    uint32 DIDBBOCNHBJ = 5;
    uint32 GOCFOJJIAHL = 11;
}

message LECPPIEIENH {
    uint32 index = 9;
    repeated uint32 FKGLNIAHGOA = 3;
    uint32 JJPMDBCPJBA = 7;
    uint32 KDIDDHIDNCG = 13;
}

message MOJFFDOILBN {
    repeated uint32 MNOOFEPDHOO = 9;
    repeated uint32 EMPIEBNCANN = 3;
    uint32 star_num = 11;
    uint32 score_id = 12;
    uint32 phase_index = 4;
}

message NPNAEPOKPNE {
    repeated float LIAMHNFAPNL = 12;
    OPOCANGAEHJ coord = 9;
}

message OFGLEOIIJBD {
    repeated NPNAEPOKPNE GOKMDCOJPHC = 10;
    uint32 FGKPIDLKALL = 2;
    uint32 fever = 6;
    string FGGCAOAPGPA = 3;
    repeated MOJFFDOILBN JOJJKJFHMBI = 4;
    repeated uint32 FJDJCHFDIFL = 14;
    uint32 HGIICMLANJJ = 15;
    uint32 level_id = 9;
    repeated PGIEBMKMECE MBFLDKEDBHN = 13;
    uint32 PLCPOONCFDG = 7;
    string NLMEEEKBPKO = 1;
    uint32 PGOFHKLBPKC = 5;
    uint32 HHINBDNIFBE = 12;
    uint32 business_day = 11;
}

message OPOCANGAEHJ {
    uint32 x = 4;
    uint32 y = 6;
}

message PGEDFOBAEBC {
    uint32 PLFMKDOCPLP = 7;
    uint32 FCFLEFOKLFD = 5;
    uint32 OMFGAABELHE = 11;
}

message PGIEBMKMECE {
    uint32 score_id = 14;
    uint32 direction = 4;
    OPOCANGAEHJ IBLECIJAGBK = 6;
    uint32 OMFGAABELHE = 7;
    repeated float CDMKBCHLPAB = 10;
}
