syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message COCHLLCNDJF {
    repeated EDKJELMPONH CDGNAJDAGKE = 3;
}

message ChimeraDoFinalRoundCsReq {
    repeated uint32 PKKGGLIGKKN = 9;
    HFBJNFJHKPO stt = 11;
    GCFGCHAMNOL lineup = 7;
    bool CJEILDIOIOE = 1;
    repeated DEJGMBKPHEC FJLPLIGMPHB = 12;
    uint32 NMPCJAOIOHJ = 4;
}

message ChimeraDoFinalRoundScRsp {
    uint32 ENMLPFBMPNI = 13;
    uint32 finish_work_cnt = 10;
    bool CJEILDIOIOE = 2;
    repeated ONNMLLIEENI CMBJOLCGMAI = 15;
    repeated GADFFIFFNHM DKMKPFDNEBL = 1;
    uint32 NMPCJAOIOHJ = 3;
    uint32 index = 9;
    uint32 HCENDLKKHOC = 7;
    uint32 retcode = 4;
    uint32 GGPKMPBBENP = 8;
}

message ChimeraFinishEndlessRoundCsReq {
    uint32 NMPCJAOIOHJ = 10;
    bool CJEILDIOIOE = 3;
    GCFGCHAMNOL lineup = 11;
    HFBJNFJHKPO stt = 2;
    repeated DEJGMBKPHEC FJLPLIGMPHB = 1;
    repeated uint32 PKKGGLIGKKN = 4;
}

message ChimeraFinishEndlessRoundScRsp {
    uint32 IOMEILDMBNE = 13;
    uint32 NMPCJAOIOHJ = 6;
    repeated GADFFIFFNHM DKMKPFDNEBL = 12;
    uint32 EBDOCKLLKMI = 8;
    uint32 PIGPKIDNMDH = 4;
    uint32 retcode = 7;
    bool CJEILDIOIOE = 9;
    uint32 MMFKMEGECOI = 1;
}

message ChimeraGetDataCsReq {
}

message ChimeraQuitEndlessCsReq {
}

message ChimeraQuitEndlessScRsp {
    uint32 retcode = 6;
}

message ChimeraStartEndlessCsReq {
}

message ChimeraStartEndlessScRsp {
    uint32 retcode = 13;
}

enum CmdChimeraType {
    CmdChimeraType_None = 0;
    CmdChimeraType_ChimeraFinishRoundCsReq = 8169;
    CmdChimeraType_ChimeraFinishEndlessRoundCsReq = 8167;
    CmdChimeraType_ChimeraRoundWorkStartScRsp = 8162;
    CmdChimeraType_ChimeraDoFinalRoundScRsp = 8164;
    CmdChimeraType_ChimeraSetLineupCsReq = 8180;
    CmdChimeraType_ChimeraStartEndlessCsReq = 8171;
    CmdChimeraType_ChimeraQuitEndlessCsReq = 8178;
    CmdChimeraType_ChimeraGetDataScRsp = 8175;
    CmdChimeraType_ChimeraSetLineupScRsp = 8173;
    CmdChimeraType_ChimeraDoFinalRoundCsReq = 8179;
    CmdChimeraType_ChimeraFinishRoundScRsp = 8172;
    CmdChimeraType_ChimeraGetDataCsReq = 8165;
    CmdChimeraType_ChimeraStartEndlessScRsp = 8174;
    CmdChimeraType_ChimeraQuitEndlessScRsp = 8176;
    CmdChimeraType_ChimeraFinishEndlessRoundScRsp = 8170;
    CmdChimeraType_ChimeraRoundWorkStartCsReq = 8163;
}

message DEJGMBKPHEC {
    uint32 DKHCOHKFKFA = 14;
    int32 attack = 9;
    int32 hp = 7;
    uint32 MBNBFBNKLGH = 8;
    uint32 EBMJGPMHDMK = 3;
    uint32 DIECMLHJCFE = 13;
    uint32 FGECDDFBFOJ = 12;
    uint32 index = 4;
}

message EDKJELMPONH {
    uint32 progress = 10;
    uint32 HEFFPONLEGO = 5;
}

message GADFFIFFNHM {
    uint32 id = 4;
    int32 hp = 12;
    COCHLLCNDJF CDGNAJDAGKE = 3;
    repeated uint32 IIELAJFFDPB = 15;
    bool AMHAJDNFBGC = 2;
    int32 atk = 5;
}

message GCFGCHAMNOL {
    uint32 CMEKNAJONPH = 13;
    repeated uint32 PGFFGKDOPGM = 9;
}

message HFBJNFJHKPO {
    uint32 cost_time = 14;
    uint32 total_turns = 13;
    uint32 total_auto_turns = 11;
    uint32 BPHNEOLCKAD = 2;
    uint32 total_damage = 9;
    uint32 LPLLIICLCHB = 6;
}

message ONNMLLIEENI {
    uint32 IDBDBICPBBG = 13;
    uint32 finish_work_cnt = 15;
}
