syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdDiceCombatType {
    CmdDiceCombatType_None = 0;
    CmdDiceCombatType_DiceCombatGetSystemDataCsReq = 9295;
    CmdDiceCombatType_DiceCombatGetSystemDataScRsp = 9279;
    CmdDiceCombatType_DiceCombatGetShopDataScRsp = 9266;
    CmdDiceCombatType_DiceCombatFinishPvpScNotify = 9300;
    CmdDiceCombatType_DiceCombatV2FinishPveStageScRsp = 9283;
    CmdDiceCombatType_DiceCombatV2FinishPveStageCsReq = 9278;
    CmdDiceCombatType_DiceCombatAddItemScNotify = 9282;
    CmdDiceCombatType_DiceCombatRollDiceCsReq = 9289;
    CmdDiceCombatType_DiceCombatRollDiceScRsp = 9270;
    CmdDiceCombatType_DiceCombatFinishPveStageCsReq = 9277;
    CmdDiceCombatType_DiceCombatV2FinishPvpScNotify = 9286;
    CmdDiceCombatType_DiceCombatUpgradeAvatarCsReq = 9288;
    CmdDiceCombatType_DiceCombatUpgradeAvatarScRsp = 9267;
    CmdDiceCombatType_DiceCombatFinishPveStageScRsp = 9281;
    CmdDiceCombatType_DiceCombatBuyShopGoodCsReq = 9293;
    CmdDiceCombatType_DiceCombatBuyShopGoodScRsp = 9299;
    CmdDiceCombatType_DiceCombatModifyAvatarDiceScRsp = 9298;
    CmdDiceCombatType_DiceCombatModifyAvatarDiceCsReq = 9297;
    CmdDiceCombatType_DiceCombatGetShopDataCsReq = 9264;
}

message DiceCombatBuyShopGoodCsReq {
    uint32 GCPGNLPODDK = 3;
    uint32 PMFNLNMINAP = 5;
}

message DiceCombatFinishPveStageCsReq {
    bool GDNKJDNMILL = 1;
    bool EKJIPCEFPOG = 12;
    uint32 ODKEBLADOMK = 2;
    uint32 IBJNBJNDPIK = 4;
}

message DiceCombatModifyAvatarDiceCsReq {
    uint32 KHIPHMCDNOM = 10;
    uint32 KOEOEHIMOEI = 2;
}

message DiceCombatUpgradeAvatarCsReq {
    uint32 KOEOEHIMOEI = 14;
}

message HHKPBPHJOMO {
}

message JFGGPGHOANG {
}
