syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdDrinkMakerType {
    CmdDrinkMakerType_None = 0;
    CmdDrinkMakerType_DrinkMakerCheersMakeDrinkCsReq = 6983;
    CmdDrinkMakerType_MakeDrinkCsReq = 7000;
    CmdDrinkMakerType_EndDrinkMakerSequenceScRsp = 6992;
    CmdDrinkMakerType_MakeMissionDrinkScRsp = 6994;
    CmdDrinkMakerType_DrinkMakerCheersEnterNextGroupScRsp = 6997;
    CmdDrinkMakerType_DrinkMakerCheersMakeDrinkScRsp = 6982;
    CmdDrinkMakerType_DrinkMakerCheersGetDataScRsp = 6984;
    CmdDrinkMakerType_DrinkMakerUpdateTipsNotify = 6996;
    CmdDrinkMakerType_GetDrinkMakerDataCsReq = 6985;
    CmdDrinkMakerType_DrinkMakerCheersGetDataCsReq = 6999;
    CmdDrinkMakerType_DrinkMakerDayEndScNotify = 6987;
    CmdDrinkMakerType_DrinkMakerChallengeCsReq = 6990;
    CmdDrinkMakerType_DrinkMakerChallengeScRsp = 6998;
    CmdDrinkMakerType_MakeMissionDrinkCsReq = 6991;
    CmdDrinkMakerType_DrinkMakerCheersEnterNextGroupCsReq = 6981;
    CmdDrinkMakerType_MakeDrinkScRsp = 6993;
    CmdDrinkMakerType_GetDrinkMakerDataScRsp = 6995;
    CmdDrinkMakerType_EndDrinkMakerSequenceCsReq = 6989;
}

message DFJPGILAAON {
    uint32 DALCMIELFDD = 9;
    uint32 HCCKHLMLENE = 1;
    uint32 KMADACHJHJC = 4;
    uint32 PDHDOHAIJKD = 8;
    repeated uint32 ECIOKDDBEPN = 7;
}

message DrinkMakerChallengeCsReq {
    uint32 challenge_id = 9;
    DFJPGILAAON AGCBLNPHFCI = 14;
}

message DrinkMakerChallengeScRsp {
    uint32 challenge_id = 4;
    ItemList reward = 9;
    uint32 retcode = 13;
    bool KGKEJAKKLDP = 10;
}

message DrinkMakerCheersEnterNextGroupCsReq {
}

message DrinkMakerCheersEnterNextGroupScRsp {
    uint32 OLKJPIIKCKP = 3;
    uint32 retcode = 6;
}

message DrinkMakerCheersGetDataCsReq {
}

message DrinkMakerCheersGetDataScRsp {
    repeated LEFIDLICEMH NHFMCMGHADE = 8;
    uint32 retcode = 5;
    uint32 OLKJPIIKCKP = 2;
    uint32 LFNJKNCGNEE = 3;
}

message DrinkMakerCheersMakeDrinkCsReq {
    uint32 MJJMPMCCNJH = 2;
    bool PCPIHPDOIGI = 12;
    DFJPGILAAON AGCBLNPHFCI = 15;
    uint32 group_id = 5;
}

message DrinkMakerCheersMakeDrinkScRsp {
    LEFIDLICEMH GKBFMPCFFOE = 3;
    uint32 retcode = 7;
}

message DrinkMakerUpdateTipsNotify {
    uint32 FHPKJONKHAC = 1;
}

message EndDrinkMakerSequenceCsReq {
}

message EndDrinkMakerSequenceScRsp {
    uint32 FHPKJONKHAC = 13;
    ItemList reward = 9;
    uint32 BFHGACCOGJD = 14;
    uint32 exp = 6;
    uint32 retcode = 10;
    KKIACMJGIKN guest = 4;
    repeated NACEGIAMJMG ADNJJHNMAAJ = 5;
    uint32 level = 3;
}

message GetDrinkMakerDataCsReq {
}

message GetDrinkMakerDataScRsp {
    uint32 day = 10;
    uint32 EMIAIOMOLPO = 8;
    uint32 retcode = 5;
    uint32 FGBELHJAKCC = 4;
    uint32 level = 7;
    uint32 FHPKJONKHAC = 2;
    repeated KKIACMJGIKN ONFNEDNFOLL = 13;
    uint32 exp = 6;
    DFJPGILAAON LMOGDPMLKFH = 15;
    repeated uint32 CJKAGEDKAFL = 9;
}

message KKIACMJGIKN {
    repeated uint32 OBJOLNOJIKC = 15;
    uint32 JOIKIENJNJI = 1;
    uint32 OHPIDOOJDHJ = 2;
}

message LEFIDLICEMH {
    uint32 MJJMPMCCNJH = 12;
    bool MHNDLPIDJIE = 14;
    repeated uint32 LNCKEHDMHLD = 7;
    DFJPGILAAON AGCBLNPHFCI = 13;
}

message MakeDrinkCsReq {
    uint32 FGBELHJAKCC = 3;
    DFJPGILAAON AGCBLNPHFCI = 5;
}

message MakeDrinkScRsp {
    uint32 LEJDBHMPBBG = 6;
    uint32 retcode = 8;
    bool KGKEJAKKLDP = 1;
}

message MakeMissionDrinkCsReq {
    uint32 CJGGHHCILMD = 2;
    bool is_save = 1;
    DFJPGILAAON AGCBLNPHFCI = 4;
}

message MakeMissionDrinkScRsp {
    DFJPGILAAON LMOGDPMLKFH = 11;
    bool is_save = 12;
    bool KGKEJAKKLDP = 6;
    uint32 retcode = 4;
}

message NACEGIAMJMG {
    uint32 CJGGHHCILMD = 15;
    bool KGKEJAKKLDP = 14;
}
