syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AcceptMultipleExpeditionCsReq {
    repeated ExpeditionInfo expedition = 9;
}

message AcceptMultipleExpeditionScRsp {
    uint32 retcode = 9;
    repeated ItemList DJOBNPIAEJP = 7;
    repeated ExpeditionInfo accept_multi_expedition = 3;
    int64 BJMGDBCHEAN = 12;
}

enum CmdExpeditionType {
    CmdExpeditionType_None = 0;
    CmdExpeditionType_AcceptMultipleExpeditionCsReq = 2507;
    CmdExpeditionType_AcceptMultipleExpeditionScRsp = 2514;
    CmdExpeditionType_GetExpeditionDataCsReq = 2536;
    CmdExpeditionType_TakeMultipleExpeditionRewardScRsp = 2518;
    CmdExpeditionType_GetExpeditionDataScRsp = 2529;
    CmdExpeditionType_ExpeditionDataChangeScNotify = 2520;
    CmdExpeditionType_TakeMultipleExpeditionRewardCsReq = 2542;
}

message ExpeditionInfo {
    uint32 id = 4;
}

message GetExpeditionDataCsReq {
}

message GetExpeditionDataScRsp {
    uint32 total_expedition_count = 13;
    repeated uint32 CAALNNFJIAH = 9;
    repeated ExpeditionInfo expedition_info = 5;
    uint32 retcode = 14;
    int64 BJMGDBCHEAN = 3;
}

message TakeMultipleExpeditionRewardCsReq {
}

message TakeMultipleExpeditionRewardScRsp {
    uint32 retcode = 3;
    repeated uint32 NPCMKBNJABA = 5;
    int64 BJMGDBCHEAN = 4;
    repeated ItemList DJOBNPIAEJP = 14;
}
