syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message ChangeEraFlipperDataCsReq {
    KKFMGCNDHGH data = 5;
}

message ChangeEraFlipperDataScRsp {
    uint32 retcode = 10;
    KKFMGCNDHGH data = 9;
}

enum CmdEraFlipperType {
    CmdEraFlipperType_None = 0;
    CmdEraFlipperType_ResetEraFlipperDataCsReq = 6571;
    CmdEraFlipperType_EnterEraFlipperRegionCsReq = 6564;
    CmdEraFlipperType_ResetEraFlipperDataScRsp = 6562;
    CmdEraFlipperType_EraFlipperDataChangeScNotify = 6565;
    CmdEraFlipperType_GetEraFlipperDataCsReq = 6559;
    CmdEraFlipperType_GetEraFlipperDataScRsp = 6568;
    CmdEraFlipperType_ChangeEraFlipperDataScRsp = 6574;
    CmdEraFlipperType_ChangeEraFlipperDataCsReq = 6561;
    CmdEraFlipperType_EnterEraFlipperRegionScRsp = 6553;
}

message EnterEraFlipperDataCsReq {
    uint32 state = 6;
    uint32 region_id = 9;
}

message GetEraFlipperDataCsReq {
}

message GetEraFlipperDataScRsp {
    uint32 retcode = 15;
    KKFMGCNDHGH data = 3;
}

message HKLDDAAECLN {
    uint32 region_id = 1;
    uint32 state = 9;
}

message KKFMGCNDHGH {
    repeated HKLDDAAECLN DMDKAOOLABF = 2;
}

message ResetEraFlipperDataCsReq {
    bool CJEILDIOIOE = 8;
}

message ResetEraFlipperDataScRsp {
    KKFMGCNDHGH data = 9;
    uint32 retcode = 10;
    bool CJEILDIOIOE = 15;
}
