syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ACAKOLCGDLL {
    uint32 KKCKMCDGCGK = 8;
    repeated NOHPJFOGFLM NMJIOGGNLEO = 1;
    uint32 NPGFNBPFMKI = 9;
    uint32 MDIIJKBHBBI = 10;
    bool GPPHKPEHKIM = 11;
}

message AGFGGFBNOJC {
    uint32 AMMPOLONOBC = 6;
    uint32 level = 11;
}

message ALEEDHCDIAL {
}

message BAEDIBFGLDE {
    LABMFHEEPBI AJFHKPNGPDB = 9;
    repeated FHCIIMGMIML DLCGPENPMNK = 7;
    repeated GHFEKEGEFAC JJHMEHGELNO = 4;
}

message BMJDDOLALFI {
    uint32 ENBEGMDIFKN = 5;
    uint32 count = 9;
}

message CEKMLMOCLHF {
    ItemList KKDJMIMHNAE = 1;
    uint32 LOPNADHJKBF = 14;
    uint32 IHAOMLEPHOM = 12;
    map<uint32, ItemList> JOCFFLKPNOL = 4;
}

message CLBNCPOFNPB {
    uint32 AOOLKNMJLNI = 4;
    uint32 GELLJOJMEFP = 2;
    uint32 MCGHFJCBBMK = 12;
}

enum CmdElfRestaurantType {
    CmdElfRestaurantType_None = 0;
    CmdElfRestaurantType_SettleElfRestaurantPlayScRsp = 2591;
    CmdElfRestaurantType_ElfRestaurantSetFarmManagerScRsp = 2557;
    CmdElfRestaurantType_ElfRestaurantTakeVillagerRewardCsReq = 2583;
    CmdElfRestaurantType_ElfRestaurantFinishTradeOrderCsReq = 2580;
    CmdElfRestaurantType_EnterElfRestaurantNextDayScRsp = 2574;
    CmdElfRestaurantType_ElfRestaurantBuyShopItemCsReq = 2560;
    CmdElfRestaurantType_ElfRestaurantUpgradeEmployeeLevelScRsp = 2592;
    CmdElfRestaurantType_ElfRestaurantUpgradeRecipeLevelScRsp = 2585;
    CmdElfRestaurantType_ElfRestaurantHarvestCropCsReq = 2571;
    CmdElfRestaurantType_ElfRestaurantRecycleSeedCsReq = 2569;
    CmdElfRestaurantType_ElfRestaurantFinishTradeOrderScRsp = 2596;
    CmdElfRestaurantType_ElfRestaurantUpgradeFacilityLevelCsReq = 2568;
    CmdElfRestaurantType_ElfRestaurantPlantSeedScRsp = 2588;
    CmdElfRestaurantType_ElfRestaurantUpgradeEmployeeLevelCsReq = 2564;
    CmdElfRestaurantType_SetElfRestaurantPlayRecipeScRsp = 2573;
    CmdElfRestaurantType_GetElfRestaurantDataScRsp = 2579;
    CmdElfRestaurantType_SetElfRestaurantPlayRecipeCsReq = 2563;
    CmdElfRestaurantType_ElfRestaurantUpgradeFacilityLevelScRsp = 2575;
    CmdElfRestaurantType_ElfRestaurantBuyFieldCsReq = 2582;
    CmdElfRestaurantType_ElfRestaurantClientStatusCsReq = 2577;
    CmdElfRestaurantType_EnterElfRestaurantNextDayCsReq = 2594;
    CmdElfRestaurantType_ElfRestaurantClientStatusScRsp = 2590;
    CmdElfRestaurantType_GetElfRestaurantDataCsReq = 2586;
    CmdElfRestaurantType_ElfRestaurantSetFarmManagerCsReq = 2551;
    CmdElfRestaurantType_ElfRestaurantBuyFieldScRsp = 2587;
    CmdElfRestaurantType_ElfRestaurantDataChangeNotify = 2572;
    CmdElfRestaurantType_SettleElfRestaurantPlayCsReq = 2597;
    CmdElfRestaurantType_ElfRestaurantRecycleSeedScRsp = 2562;
    CmdElfRestaurantType_ElfRestaurantPlantSeedCsReq = 2570;
    CmdElfRestaurantType_ElfRestaurantHarvestCropScRsp = 2567;
    CmdElfRestaurantType_ElfRestaurantBuyShopItemScRsp = 2599;
    CmdElfRestaurantType_ElfRestaurantUpgradeRecipeLevelCsReq = 2554;
    CmdElfRestaurantType_ElfRestaurantTakeVillagerRewardScRsp = 2578;
}

message ECGKEKKAHGN {
    uint32 IHAOMLEPHOM = 4;
    ItemList FEANLLOCFBA = 10;
    uint32 LOPNADHJKBF = 6;
}

message EEAGACLNDFN {
    uint32 LOPNADHJKBF = 14;
}

message ElfRestaurantBuyFieldScRsp {
    uint32 PLDKENJLKME = 3;
    repeated CEKMLMOCLHF LKAJMFONLEE = 7;
}

message ElfRestaurantBuyShopItemCsReq {
    uint32 ICNCMMEEJKM = 3;
    uint32 ICAILDEHHBN = 1;
}

message ElfRestaurantDataChangeNotify {
    repeated HGMJFBCFJFN DGNGMJMPFGK = 8;
}

message ElfRestaurantFinishTradeOrderCsReq {
    uint32 BFADNHJAJBJ = 15;
}

message ElfRestaurantFinishTradeOrderScRsp {
    ItemCostData FKMFHAAJMMF = 9;
    uint32 BFADNHJAJBJ = 4;
    uint32 retcode = 6;
    ItemList GLAPKNMCIBI = 11;
}

message ElfRestaurantHarvestCropCsReq {
    repeated KPLHHLEGGCD FMCGHNLBIKP = 15;
}

message ElfRestaurantPlantSeedCsReq {
    repeated KPLHHLEGGCD FMCGHNLBIKP = 5;
    uint32 BLNHCIBKJOM = 7;
}

message ElfRestaurantPlantSeedScRsp {
    repeated NKEGPAOCGCJ FPEBFLJMEJL = 7;
    uint32 retcode = 4;
}

message ElfRestaurantRecycleSeedCsReq {
    repeated KPLHHLEGGCD FMCGHNLBIKP = 6;
}

message ElfRestaurantRecycleSeedScRsp {
    repeated ECGKEKKAHGN HDAMNMCDHLH = 10;
    uint32 retcode = 12;
}

message ElfRestaurantTakeVillagerRewardCsReq {
}

message ElfRestaurantTakeVillagerRewardScRsp {
    uint32 retcode = 5;
    repeated PLOHACFCDKF DJOBNPIAEJP = 7;
}

message EnterElfRestaurantNextDayScRsp {
    uint32 BMKIHDODJPN = 1;
    ItemList KNMAPBKCDHE = 11;
    ItemCostData FGDMAHNNGPI = 2;
    uint32 PLDKENJLKME = 8;
}

message FHCIIMGMIML {
    uint32 level = 10;
    uint32 AOOLKNMJLNI = 5;
}

message GHFEKEGEFAC {
    uint32 level = 13;
    uint32 OMFGAABELHE = 10;
}

message GetElfRestaurantDataCsReq {
}

message GetElfRestaurantDataScRsp {
    ICABANFEIHJ AHCEIMGNBNM = 14;
    IILBDJMKELG MILCHKIIEJE = 11;
    ACAKOLCGDLL IBHKOKEEMOI = 2;
    uint32 retcode = 7;
    OMPLEKGNLBC FFKCMKJFFCM = 4;
    BAEDIBFGLDE OENLJGEBCGA = 5;
}

message HCBCPFNMMMI {
    uint32 IGOOJKMPMDC = 14;
    uint32 OMFGAABELHE = 15;
}

message HCGNKJHKJMM {
    uint32 AOOLKNMJLNI = 2;
    uint32 IGOOJKMPMDC = 6;
}

message HGMJFBCFJFN {
    ACAKOLCGDLL JNBFIBDKLGB = 6;
    OBDBODNJACD LEMCGNHLOOI = 4;
    AGFGGFBNOJC NEFHJPJALGO = 7;
    uint32 EDGOIFOOBMH = 2;
    GHFEKEGEFAC HINKDPMAICB = 5;
    FHCIIMGMIML MOCNALBMLLI = 9;
    MOOGIHHBHFG MFAJAPGACPA = 10;
    uint32 FDLGKNFIPMG = 11;
    LGFLGGDMAGD HMGKHCNMDDJ = 15;
    uint32 KMHMAKDFKLB = 13;
    bool PCKLCAEDJPC = 1;
    LABMFHEEPBI HGPMMEHONLD = 12;
}

message ICABANFEIHJ {
    repeated MOOGIHHBHFG LCJFDCHINHL = 10;
    repeated LGFLGGDMAGD NILEKCAGIMK = 4;
}

message IILBDJMKELG {
    repeated AGFGGFBNOJC FGJHNNPOGGF = 8;
}

message KPLHHLEGGCD {
    uint32 IHAOMLEPHOM = 15;
    uint32 LOPNADHJKBF = 2;
}

message LABMFHEEPBI {
    uint32 DFELFGNJGDP = 4;
    repeated BMJDDOLALFI ELJEBPIOKDD = 13;
    repeated uint32 JEENJPHNBLI = 2;
    uint64 FEKHNEKHAAK = 1;
    repeated uint32 FFEILKDLABH = 9;
    repeated CLBNCPOFNPB FGJIAMOOIIG = 14;
    uint32 JFBOMKNCNIE = 8;
}

message LGFLGGDMAGD {
    uint32 BEIJKGPGFFE = 6;
    uint32 BFADNHJAJBJ = 10;
}

message MFIJFCEAKHA {
    bool is_active = 12;
}

message MOOGIHHBHFG {
    uint32 BEIJKGPGFFE = 3;
    uint32 ICNCMMEEJKM = 7;
    uint32 LMGFEGDNCHP = 2;
}

message NKEGPAOCGCJ {
    uint32 LOPNADHJKBF = 4;
    uint32 IHAOMLEPHOM = 8;
    ItemCostData FKMFHAAJMMF = 5;
}

message NOHPJFOGFLM {
    uint32 JJIJBJDKNAE = 13;
    uint32 progress = 6;
}

message OBDBODNJACD {
    uint32 BLNHCIBKJOM = 2;
    uint32 LOPNADHJKBF = 10;
    bool MEBMAMHHGMD = 15;
    bool JFAPNIECBKO = 11;
    uint32 IHAOMLEPHOM = 5;
    uint32 LIHAHPDCIKL = 9;
}

message OCKGMNGKIEE {
    uint32 IGOOJKMPMDC = 1;
    uint32 AMMPOLONOBC = 4;
}

message OMPLEKGNLBC {
    bool PCKLCAEDJPC = 5;
    repeated uint32 KPMKNBNOAFP = 7;
    repeated OBDBODNJACD FMCGHNLBIKP = 11;
}

message PLOHACFCDKF {
    uint32 MMMADINMHFB = 1;
    uint32 progress = 3;
    uint32 OCJKDCPANJM = 13;
    ItemList reward_list = 6;
}
