syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AFANKKDMIHC {
    KAOPGJBGEBF MGMPDHKJFIM = 11;
}

message AFKJKLJJLKN {
    uint32 PJLEJKEOFII = 11;
}

message AGPKFBLGDIH {
    repeated ActiveTraitSourceList KBGAPHFIPJF = 4;
    uint32 trait_id = 12;
}

message AHOMAAHPCIG {
    repeated uint32 DAPJMJMGCFC = 5;
    repeated uint32 EKJDLEFFGHD = 15;
}

message ANJBJLDMDFN {
    uint32 unique_id = 4;
}

message ANNFOAGBJBP {
    repeated MJLJMCCGNEE BLFMGKPNPGG = 11;
}

message ActiveTraitSourceList {
    FJKMGCKMNNA source = 15;
    uint32 cnt = 10;
}

message BDJEGABKNHN {
    repeated uint32 PPHEKHLLFHC = 5;
    map<uint32, uint32> ICAOKNPHKGN = 2;
}

message BFBCEOICLAB {
    repeated KAOPGJBGEBF LNNGKPAJKLP = 6;
    ENJDEFHFKPI IEMEKMDDIOI = 7;
    KCLHMJHIDOB LMLDELGBJOO = 15;
    JIMNPPNNHEL EFLLPHLDBPC = 10;
    uint32 area_id = 3;
    uint32 difficulty = 12;
    ANNFOAGBJBP CMCBGGKLBCF = 409;
    EMFDLPNOGOH status = 13;
    IBGFKJMMICI GODPEHNPPCO = 1144;
    NBBHDPCPHNN MHALEIHFKLG = 4;
    uint32 GBMBGHAPDMG = 9;
    PJFDAOKIKOJ CCOPDLOKAAE = 14;
    JFKAOMCJIKK FMIGOKIDKJL = 2;
    repeated KLMNGOJKEIN FELMAMPGMAE = 8;
}

message BGNIMFMFKLH {
    map<uint32, double> OPEMKBPFFDN = 8;
    FJKMGCKMNNA source = 5;
}

message CLNABFMHFFH {
    bool BKFONKNLCHP = 9;
    uint32 avatar_id = 6;
}

enum CmdFateType {
    CmdFateType_None = 0;
    CmdFateType_FateTakeExpRewardCsReq = 5999;
    CmdFateType_FateSettleScRsp = 5991;
    CmdFateType_FateShopLockGoodsScRsp = 5957;
    CmdFateType_FateShopLockGoodsCsReq = 5951;
    CmdFateType_FateQueryCsReq = 5986;
    CmdFateType_FateSettleScNotify = 5960;
    CmdFateType_FateShopBuyGoodsCsReq = 5970;
    CmdFateType_FateQueryScRsp = 5979;
    CmdFateType_FateTakeExpRewardScRsp = 5980;
    CmdFateType_FateStartScRsp = 5974;
    CmdFateType_FateSyncActionResultScNotify = 5954;
    CmdFateType_FateSyncPendingActionScNotify = 5985;
    CmdFateType_FateShopSellBuffCsReq = 5971;
    CmdFateType_FateStartCsReq = 5994;
    CmdFateType_FateShopRefreshGoodsCsReq = 5969;
    CmdFateType_FateShopLeaveScRsp = 5992;
    CmdFateType_FateBattleStartScRsp = 5972;
    CmdFateType_FateChangeLineupScRsp = 5987;
    CmdFateType_FateHandlePendingActionScRsp = 5975;
    CmdFateType_FateShopBuyGoodsScRsp = 5988;
    CmdFateType_FateSettleCsReq = 5997;
    CmdFateType_FateChangeLineupCsReq = 5982;
    CmdFateType_FateBattleStartCsReq = 5958;
    CmdFateType_FateHandlePendingActionCsReq = 5968;
    CmdFateType_FateShopSellBuffScRsp = 5967;
    CmdFateType_FateShopLeaveCsReq = 5964;
    CmdFateType_FateShopRefreshGoodsScRsp = 5962;
}

message DACCNAFGHFJ {
    KCLHMJHIDOB AKGJOPBLPNE = 14;
}

message DAFHOKGICNG {
    repeated uint32 PDABDEJBPEL = 3;
}

message DBKNLPMGFFH {
    uint32 gold = 9;
}

message DDLHODCINBI {
    DACCNAFGHFJ EKKABKCCLGJ = 11;
    MMPPKFJEOGK BJEDONKMCFE = 6;
    OPPNDJOCBEA GAEFNAJACEH = 12;
    FLIPLAHLMKM JGKDIFDIMKN = 9;
    DBKNLPMGFFH MFFLKLAJBDF = 10;
    JFLOHLLMOJK HENLCGACIOK = 1;
    DOBHOCKGHBI PLFLNBLMMHI = 14;
    MAFJLIIKIIF NKPAELIHJAD = 13;
    ANJBJLDMDFN MLPFDMIILBD = 5;
    AFANKKDMIHC GIGFDPNIMGD = 2;
    LMOPAFOIJNF JGNMFHFCIFN = 15;
    KAJLLLAAKOG OKDKHJFHJND = 3;
    AHOMAAHPCIG CCOHJLKNFON = 8;
    KGJGEEEKNNC MILPEAKHKEL = 4;
    LHJBIHJBNHI PLDLCJPGCIB = 175;
    BDJEGABKNHN FEINKBBJNHP = 1364;
    ELEMFBMOMMM HNFLLMLLNFI = 625;
    HACIGDEEMCJ CCEGFKEBEMI = 783;
    PANAGPMIIIH GGGLMGKKFFM = 105;
    KGOBMEOAEBL JKHGEJCJOEB = 701;
    PIKIDDEEDII CMHLMLEGNGM = 375;
}

message DOBHOCKGHBI {
    uint32 JIMBJHLMHLO = 10;
}

message EJCCCIGMHOM {
    repeated uint32 GMGOHBLFMAN = 9;
    GCECAGOELDP BDIBPIMAPOC = 5;
    repeated uint32 NKHIIMHCLCD = 11;
    HIJCLODMBPO GJFKKFFJDAH = 10;
}

message ELEMFBMOMMM {
    BGNIMFMFKLH ECMBBBAPAJC = 8;
}

enum EMFDLPNOGOH {
    EMFDLPNOGOH_NLCDGIPGFDJ = 0;
    EMFDLPNOGOH_NGPHFLBNHKB = 1;
    EMFDLPNOGOH_KBAENNGPMPH = 2;
    EMFDLPNOGOH_GKHJMGPHDBK = 3;
    EMFDLPNOGOH_CHGJLDDJJAH = 4;
    EMFDLPNOGOH_FBKMDMLBNII = 5;
    EMFDLPNOGOH_MADBILBKOAO = 6;
}

message ENJDEFHFKPI {
    repeated uint32 BAHMHMDOMPB = 1;
}

message FGEMJLFIHHL {
}

message FJKMGCKMNNA {
    uint32 BNEFLBPCPOI = 13;
    MOHNIMLCODA source_type = 11;
}

message FLIPLAHLMKM {
    repeated MJLJMCCGNEE BLFMGKPNPGG = 1;
}

message FateBattleStartCsReq {
}

message FateBattleStartScRsp {
    SceneBattleInfo battle_info = 11;
    uint32 retcode = 3;
}

message FateBuffData {
    uint32 buff_id = 1;
    uint32 cnt = 8;
}

message FateChangeLineupCsReq {
    repeated KPNHGDGLICN avatar_list = 12;
}

message FateChangeLineupScRsp {
    uint32 retcode = 8;
}

message FateHandlePendingActionCsReq {
    uint32 queue_position = 13;
    AFKJKLJJLKN HNPBCGILAJP = 12;
    GHAJMKCEEPJ NPBKAADBHHC = 10;
}

message FateHandlePendingActionScRsp {
    uint32 retcode = 5;
}

enum FateMasterStatusType {
    FateMasterStatusType_None = 0;
    FateMasterStatusType_Alive = 1;
    FateMasterStatusType_Dead = 2;
    FateMasterStatusType_Banned = 3;
}

message FateQueryCsReq {
}

message FateQueryScRsp {
    BFBCEOICLAB OEIBHLMDJKA = 1;
    uint32 retcode = 2;
    EJCCCIGMHOM LFLCDNGALME = 10;
}

message FateSettleScNotify {
    uint32 score_id = 4;
    HJFCEEBAGMF LNBBPPKLBFA = 5;
    ItemList reward = 2;
}

message FateShopBuyGoodsCsReq {
    uint32 COCLMANMAAI = 4;
}

message FateShopBuyGoodsScRsp {
    uint32 retcode = 1;
    uint32 COCLMANMAAI = 13;
}

message FateShopLeaveCsReq {
}

message FateShopLeaveScRsp {
    uint32 retcode = 10;
}

message FateShopLockGoodsCsReq {
    bool is_locked = 1;
}

message FateShopLockGoodsScRsp {
    bool is_locked = 9;
    uint32 retcode = 15;
}

message FateShopRefreshGoodsCsReq {
}

message FateShopRefreshGoodsScRsp {
    bool PNMNPFGCFBJ = 8;
    repeated JDAIOFEPGCC OGDKJPDFFAI = 5;
    uint32 retcode = 14;
}

message FateShopSellBuffCsReq {
    uint32 JDIFHPAFPID = 2;
    uint32 PCJOBDNLEAI = 10;
    bool PMCPIECGEHH = 12;
}

message FateShopSellBuffScRsp {
    uint32 JDIFHPAFPID = 6;
    bool PMCPIECGEHH = 1;
    uint32 PCJOBDNLEAI = 13;
    uint32 retcode = 7;
}

message FateStartCsReq {
    repeated KPNHGDGLICN avatar_list = 11;
    uint32 difficulty = 4;
    uint32 area_id = 2;
}

message FateStartScRsp {
    BFBCEOICLAB OEIBHLMDJKA = 15;
    uint32 retcode = 9;
}

message FateSyncActionResultScNotify {
    repeated DDLHODCINBI CLGGKLNPLCK = 5;
}

message FateSyncPendingActionScNotify {
    JFKAOMCJIKK FMIGOKIDKJL = 12;
}

message FateTakeExpRewardCsReq {
}

message FateTakeExpRewardScRsp {
    uint32 retcode = 11;
    ItemList reward = 10;
    repeated uint32 HPJMJEAJKAC = 15;
    repeated uint32 HKEFKHJOEPJ = 2;
}

message GCECAGOELDP {
    repeated uint32 CFIKMGKPOFH = 12;
    repeated uint32 NPDOKAJOOKD = 11;
    uint32 exp = 6;
}

message GHAJMKCEEPJ {
    bool MLKBOBIEAPL = 7;
    uint32 NOILILELKFB = 8;
}

message GKJEMHKOMJC {
    repeated JOGCCINEHFJ CFFCNEDGCJJ = 14;
    int32 hp = 10;
    int32 max_hp = 11;
    FateMasterStatusType status = 3;
    uint32 avatar_id = 1;
    uint32 rank = 13;
}

message HACIGDEEMCJ {
    FJKMGCKMNNA JDFKEJDDGFC = 2;
}

message HDHLHNEACHP {
    uint32 level = 11;
    uint32 id = 7;
    AvatarType avatar_type = 15;
    bool is_upgraded = 13;
}

message HIJCLODMBPO {
    repeated HJFCEEBAGMF BJJDJFJMGDI = 12;
    HJHMNDBJPND OAFLJGCKIAJ = 4;
    map<uint32, HJHMNDBJPND> BDJECEJAKIJ = 15;
    HJHMNDBJPND PIDFDPIDJMN = 14;
}

message HJFCEEBAGMF {
    uint32 OKOICDENGFK = 15;
    uint32 BKPDKFLDLDD = 12;
    repeated HDHLHNEACHP avatar_list = 7;
    map<uint32, uint32> DHBPGMPMPOL = 773;
    uint32 level_id = 2;
    map<uint32, uint32> LANHCGFHCDB = 9;
    uint32 difficulty = 5;
    uint32 IDNHBBMLNJK = 8;
    repeated uint32 LNNGKPAJKLP = 14;
    map<uint32, uint32> DBIFAJIBGAC = 6;
    repeated uint32 FELMAMPGMAE = 1;
}

message HJHMNDBJPND {
    repeated uint32 DKJEDBHLOPP = 2;
    map<uint32, uint32> LJDLJKCMIIC = 11;
    uint32 KAENLKDNOMF = 15;
    uint32 total_count = 7;
}

message IBGFKJMMICI {
    repeated BGNIMFMFKLH OPOIDPJFFPK = 15;
}

message IMIHIMCHHIP {
    uint32 OIDJFIFJDHL = 7;
    uint32 item_value = 3;
}

message JCMKKEKMHNC {
    repeated KMLOMKCMGHD LGFJPBJOBPC = 9;
}

message JDAIOFEPGCC {
    uint32 cnt = 1;
    uint32 buff_id = 15;
    bool GDOBLPPEGKD = 4;
    uint32 KDKPDJNMMCM = 9;
}

message JFKAOMCJIKK {
    uint32 queue_position = 6;
    KFAIFLHPEIE GJDKHBPHNCG = 9;
}

message JFLOHLLMOJK {
    uint32 MNCBFLEFJCK = 2;
    uint32 KCBLNMMHOKG = 7;
}

message JIMNPPNNHEL {
    repeated IMIHIMCHHIP AALLBBCJGIA = 10;
    uint32 item_value = 14;
    bool ONDCOEBNAPJ = 8;
    bool PNMNPFGCFBJ = 12;
    uint32 KCBLNMMHOKG = 15;
    uint32 MNCBFLEFJCK = 11;
    repeated JDAIOFEPGCC OGDKJPDFFAI = 2;
}

message JOGCCINEHFJ {
    repeated uint32 monster_list = 9;
    bool FNIAOAOBKBA = 12;
    uint32 affix_id = 8;
    uint32 unique_id = 4;
    bool DIHFBELJFIA = 5;
}

message KAJLLLAAKOG {
    repeated uint32 CJBINCOKFPO = 12;
    repeated AGPKFBLGDIH BFNINELCBCN = 2;
}

message KAOPGJBGEBF {
    int32 value = 12;
    uint32 unique_id = 9;
    uint32 DAMIHCPPJAB = 3;
}

message KCLHMJHIDOB {
    uint32 BKPDKFLDLDD = 5;
    uint32 IDNHBBMLNJK = 14;
}

message KFAIFLHPEIE {
    DAFHOKGICNG HNPBCGILAJP = 9;
    JCMKKEKMHNC NPBKAADBHHC = 11;
}

message KGJGEEEKNNC {
    JIMNPPNNHEL EFLLPHLDBPC = 1;
}

message KGOBMEOAEBL {
    bool ONDCOEBNAPJ = 1;
}

message KLMNGOJKEIN {
    uint32 MELNKMALHJO = 13;
    uint32 unique_id = 1;
}

message KMLOMKCMGHD {
    uint32 DAMIHCPPJAB = 3;
    uint32 JCNDBKGBLLJ = 8;
}

message LEGBKMIIJOA {
    uint32 GCIFCLINGFN = 4;
    bool MEHPJMPDNNA = 7;
    double FJDFOPNAFPP = 13;
    bool JMCMPFPDEHG = 8;
    uint32 JGLNALONLDO = 9;
    uint32 DIIDBKIJEAF = 12;
    uint32 ECPMGBGLLNN = 11;
    uint32 avatar_id = 10;
}

message LHJBIHJBNHI {
    GKJEMHKOMJC GJPGBBHCAFC = 14;
}

message LMOPAFOIJNF {
    repeated uint32 PDKAMAGEFEK = 7;
    repeated FateBuffData FCKIOLPLANI = 12;
}

message MAFJLIIKIIF {
    KLMNGOJKEIN MAIBAOAOGID = 5;
}

message MJLJMCCGNEE {
    CLNABFMHFFH KPEHHGEKNHA = 6;
    CLNABFMHFFH LJEAFPOHNCD = 9;
}

message MMPPKFJEOGK {
    EMFDLPNOGOH EGBFNFCEPHD = 12;
}

message NBBHDPCPHNN {
    repeated FateBuffData buff_list = 12;
    repeated uint32 NGOMJIFBBBP = 13;
    map<uint32, uint32> buff_amplification_map = 7;
    uint32 JIMBJHLMHLO = 15;
    repeated uint32 MHLNGFBOIDP = 2;
    repeated AGPKFBLGDIH ICCMJHJLPCD = 4;
}

message OPPNDJOCBEA {
    uint32 LKPNNOGPJOI = 7;
    repeated LEGBKMIIJOA MIKKAEJNLAL = 11;
    uint32 JJDEEHAMHGF = 6;
    uint32 GCNMKIHOFGG = 13;
    repeated GKJEMHKOMJC OCAMBKNKKGO = 4;
    uint32 NCDBCLLAHPP = 3;
    repeated uint32 EAOCKLDEOGH = 10;
    bool NEEDLFJJFPL = 14;
}

message PANAGPMIIIH {
    repeated uint32 NGOMJIFBBBP = 8;
}

message PIKIDDEEDII {
    repeated uint32 BAHMHMDOMPB = 11;
}

message PJFDAOKIKOJ {
    repeated GKJEMHKOMJC OCAMBKNKKGO = 13;
}
