syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum BGLIMCBGLAJ {
    BGLIMCBGLAJ_PICLIGEAJFN = 0;
    BGLIMCBGLAJ_OGPNODHENKN = 1;
    BGLIMCBGLAJ_JPDBDLEEHGK = 2;
    BGLIMCBGLAJ_BMHMMIMOAIJ = 3;
    BGLIMCBGLAJ_DCGAPNGCCEH = 4;
}

enum CmdFightFestType {
    CmdFightFestType_None = 0;
    CmdFightFestType_GetFightFestDataCsReq = 7286;
    CmdFightFestType_FightFestUpdateCoinNotify = 7287;
    CmdFightFestType_FightFestScoreUpdateNotify = 7258;
    CmdFightFestType_FightFestUpdateChallengeRecordNotify = 7282;
    CmdFightFestType_StartFightFestScRsp = 7274;
    CmdFightFestType_StartFightFestCsReq = 7294;
    CmdFightFestType_GetFightFestDataScRsp = 7279;
    CmdFightFestType_FightFestUnlockSkillNotify = 7272;
}

message EPCNGNEEMBI {
    uint32 id = 9;
    AvatarType avatar_type = 7;
}

message FightFestScoreUpdateNotify {
    uint32 score_id = 3;
    uint32 JODNMFEFPFD = 7;
}

enum FightFestType {
    FightFestType_None = 0;
    FightFestType_Main = 1;
    FightFestType_Score = 2;
    FightFestType_Challenge = 3;
    FightFestType_Teach = 4;
}

message FightFestUnlockSkillNotify {
    uint32 AMAGKDCBFGL = 5;
}

message FightFestUpdateChallengeRecordNotify {
    BGLIMCBGLAJ rank = 11;
    uint32 DJFGDMIDEHJ = 14;
    uint32 turn_left = 12;
    BGLIMCBGLAJ HMBBBNKAILD = 15;
    uint32 challenge_id = 7;
}

message FightFestUpdateCoinNotify {
    uint32 item_value = 10;
}

message GetFightFestDataCsReq {
}

message GetFightFestDataScRsp {
    uint32 score_id = 8;
    repeated LPJOINCGBBP challenge_list = 11;
    repeated uint32 GILJLEOAOMA = 10;
    uint32 retcode = 15;
    uint32 item_value = 7;
}

message LPJOINCGBBP {
    BGLIMCBGLAJ OINGNAJMFNL = 4;
    uint32 challenge_id = 12;
    uint32 DJFGDMIDEHJ = 2;
}

message StartFightFestCsReq {
    uint32 event_id = 5;
    repeated uint32 GILJLEOAOMA = 12;
    repeated EPCNGNEEMBI avatar_list = 4;
    FightFestType type = 6;
    uint32 id = 11;
}

message StartFightFestScRsp {
    FightFestType type = 15;
    uint32 event_id = 8;
    uint32 retcode = 4;
    uint32 id = 12;
    SceneBattleInfo battle_info = 13;
}
