syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdFightMatch3Type {
    CmdFightMatch3Type_CmdFightMathc3TypeNone = 0;
    CmdFightMatch3Type_FightMatch3SoloAnimEndScRsp = 30148;
    CmdFightMatch3Type_FightMatch3SoloAnimEndCsReq = 30149;
    CmdFightMatch3Type_FightMatch3SoloPreTurnEndScRsp = 30141;
    CmdFightMatch3Type_FightMatch3SwapScRsp = 30198;
    CmdFightMatch3Type_FightMatch3SoloSwapNotify = 30115;
    CmdFightMatch3Type_FightMatch3SoloPreTurnEndCsReq = 30181;
    CmdFightMatch3Type_FightMatch3SoloDataScRsp = 30162;
    CmdFightMatch3Type_FightMatch3RoyaleDataUpdateNotify = 30146;
    CmdFightMatch3Type_FightMatch3ChatCsReq = 30173;
    CmdFightMatch3Type_FightMatch3SoloUseItemNotify = 30164;
    CmdFightMatch3Type_FightMatch3ChatScRsp = 30199;
    CmdFightMatch3Type_FightMatch3RoyaleRankUpdateNotify = 30166;
    CmdFightMatch3Type_FightMatch3SoloDataCsReq = 30104;
    CmdFightMatch3Type_FightMatch3ForceUpdateNotify = 30165;
    CmdFightMatch3Type_FightMatch3SoloDataUpdateNotify = 30188;
    CmdFightMatch3Type_FightMatch3SwapCsReq = 30191;
    CmdFightMatch3Type_FightMatch3TurnStartScNotify = 30139;
    CmdFightMatch3Type_FightMatch3StartCountDownScNotify = 30179;
    CmdFightMatch3Type_FightMatch3DataCsReq = 30134;
    CmdFightMatch3Type_FightMatch3RoyaleDataScRsp = 30157;
    CmdFightMatch3Type_FightMatch3UseItemScRsp = 30171;
    CmdFightMatch3Type_FightMatch3UseItemCsReq = 30180;
    CmdFightMatch3Type_FightMatch3DataScRsp = 30182;
    CmdFightMatch3Type_FightMatch3TurnEndScNotify = 30156;
    CmdFightMatch3Type_FightMatch3ChatScNotify = 30172;
    CmdFightMatch3Type_FightMatch3OpponentDataScNotify = 30126;
    CmdFightMatch3Type_FightMatch3RoyaleDataCsReq = 30138;
}
