syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdFightType {
    CmdFightType_None = 0;
    CmdFightType_FightSessionStopScNotify = 30098;
    CmdFightType_FightGeneralCsReq = 30026;
    CmdFightType_FightGeneralScRsp = 30073;
    CmdFightType_FightHeartBeatScRsp = 30091;
    CmdFightType_FightHeartBeatCsReq = 30056;
    CmdFightType_FightEnterCsReq = 30034;
    CmdFightType_FightEnterScRsp = 30082;
    CmdFightType_FightGeneralScNotify = 30099;
    CmdFightType_FightLeaveScNotify = 30079;
}

message OEAMNAAJJHI {
    uint64 client_time_ms = 12;
}
