syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdFateRinType {
    CmdFateRinType_None = 0;
    CmdFateRinType_FateRinSetCurrentDeckScRsp = 9883;
    CmdFateRinType_FateRinModifyDeckCsReq = 9899;
    CmdFateRinType_FateRinHouguUnlockScNotify = 9888;
    CmdFateRinType_FateRinGetDataCsReq = 9895;
    CmdFateRinType_FateRinTraceHouguMapFightScRsp = 9900;
    CmdFateRinType_FateRinLevelUpScNotify = 9867;
    CmdFateRinType_FateRinStartHouguMapFightScRsp = 9864;
    CmdFateRinType_FateRinStartChallengeFightCsReq = 9866;
    CmdFateRinType_FateRinModifyDeckScRsp = 9897;
    CmdFateRinType_FateRinGetDataScRsp = 9879;
    CmdFateRinType_FateRinSetCurrentDeckCsReq = 9878;
    CmdFateRinType_FateRinFinishChallengeFightScNotify = 9886;
    CmdFateRinType_FateRinDeckUnlockScNotify = 9898;
    CmdFateRinType_FateRinStartStoryFightCsReq = 9882;
    CmdFateRinType_FateRinStartHouguMapFightCsReq = 9870;
    CmdFateRinType_FateRinStartStoryFightScRsp = 9889;
    CmdFateRinType_FateRinFinishHouguMapFightScNotify = 9877;
    CmdFateRinType_FateRinStartChallengeFightScRsp = 9893;
    CmdFateRinType_FateRinTraceHouguMapFightCsReq = 9881;
}

message DIEODGPPEDC {
}

message FateRinStartChallengeFightScRsp {
    SceneBattleInfo battle_info = 1;
    uint32 retcode = 10;
}

message FateRinStartHouguMapFightCsReq {
    bool JBIFGIHHMNO = 1;
    uint32 CCOOCEEAKFI = 8;
}

message FateRinStartHouguMapFightScRsp {
    SceneBattleInfo battle_info = 15;
    uint32 retcode = 2;
}

message FateRinStartStoryFightCsReq {
    uint32 CCOOCEEAKFI = 13;
}

message FateRinStartStoryFightScRsp {
    uint32 retcode = 7;
    SceneBattleInfo battle_info = 6;
}

message GHCLLIAGDEP {
    uint32 NKDDBPGDAEE = 2;
}

message OCOEKDNDEGJ {
    uint32 PPMJKDBNHCA = 12;
}
