syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AddBlacklistCsReq {
    uint32 uid = 3;
}

message AddBlacklistScRsp {
    uint32 retcode = 14;
    PlayerSimpleInfo black_info = 1;
}

message ApplyFriendCsReq {
    FriendApplySource source = 12;
    uint32 uid = 1;
}

message ApplyFriendScRsp {
    uint32 uid = 11;
    uint32 retcode = 13;
}

message BGPIHMLLNGM {
    NMFEHEHPGAB HJFHOEAAGGC = 9;
    FKCNEPIJJAO BFGELCKJJPN = 15;
    OIMLMDHOHAP MHAIBAMJGIM = 2;
    GLILLENEIJK ENDLJENKBMF = 4;
}

message BMKNANGPDGH {
    repeated ONKDAPOKGAC avatar_list = 14;
    uint32 EMOHLJHPOPC = 8;
    uint32 passed_level = 7;
    uint32 ALGOCKMHFHH = 4;
}

enum BattleRecordType {
    BattleRecordType_BattleRecordNone = 0;
    BattleRecordType_BattleRecordChallenge = 1;
    BattleRecordType_BattleRecordRogue = 2;
}

message CFNEMEIDMID {
    uint32 HOLPMKOHACH = 2;
    uint32 area_id = 3;
}

message CJNDCNIJBEI {
    repeated ONKDAPOKGAC avatar_list = 10;
    repeated uint32 finished_target_list = 6;
}

message ChallengePeakBossFriendLineupRecommendation {
    bool hard_mode_has_passed = 14;
    repeated uint32 finished_target_list = 12;
    repeated ONKDAPOKGAC avatar_list = 7;
    bool is_hard_mode = 13;
    uint32 buff_id = 9;
}

enum CmdFriendType {
    CmdFriendType_None = 0;
    CmdFriendType_GetFriendBattleRecordDetailScRsp = 2919;
    CmdFriendType_GetFriendAssistListCsReq = 2987;
    CmdFriendType_GetFriendRecommendLineupScRsp = 2928;
    CmdFriendType_GetFriendRecommendLineupDetailScRsp = 2925;
    CmdFriendType_GetAssistHistoryCsReq = 2908;
    CmdFriendType_GetFriendRecommendLineupCsReq = 2963;
    CmdFriendType_GetPlayerDetailInfoCsReq = 2979;
    CmdFriendType_SetFriendRemarkNameScRsp = 2981;
    CmdFriendType_SetFriendMarkScRsp = 2911;
    CmdFriendType_GetAssistListCsReq = 2924;
    CmdFriendType_GetFriendRecommendLineupDetailCsReq = 2985;
    CmdFriendType_GetFriendDevelopmentInfoScRsp = 2974;
    CmdFriendType_ReportPlayerCsReq = 2941;
    CmdFriendType_TakeAssistRewardCsReq = 2943;
    CmdFriendType_SetAssistScRsp = 2923;
    CmdFriendType_GetFriendListInfoCsReq = 2934;
    CmdFriendType_TakeAssistRewardScRsp = 2940;
    CmdFriendType_DeleteFriendScRsp = 2971;
    CmdFriendType_GetPlatformPlayerInfoScRsp = 2975;
    CmdFriendType_ReportPlayerScRsp = 2938;
    CmdFriendType_HandleFriendCsReq = 2999;
    CmdFriendType_SetFriendMarkCsReq = 2970;
    CmdFriendType_GetPlatformPlayerInfoCsReq = 2955;
    CmdFriendType_GetFriendRecommendListInfoScRsp = 2915;
    CmdFriendType_SyncHandleFriendScNotify = 2965;
    CmdFriendType_SetForbidOtherApplyFriendScRsp = 2989;
    CmdFriendType_SearchPlayerCsReq = 2966;
    CmdFriendType_SyncAddBlacklistScNotify = 2948;
    CmdFriendType_GetAssistListScRsp = 2914;
    CmdFriendType_CurAssistChangedNotify = 2983;
    CmdFriendType_DeleteBlacklistCsReq = 2957;
    CmdFriendType_GetAssistHistoryScRsp = 2958;
    CmdFriendType_GetFriendBattleRecordDetailCsReq = 2968;
    CmdFriendType_ApplyFriendScRsp = 2926;
    CmdFriendType_GetCurAssistScRsp = 2901;
    CmdFriendType_GetFriendLoginInfoCsReq = 2902;
    CmdFriendType_SyncApplyFriendScNotify = 2973;
    CmdFriendType_GetFriendApplyListInfoCsReq = 2956;
    CmdFriendType_GetCurAssistCsReq = 2944;
    CmdFriendType_DeleteBlacklistScRsp = 2946;
    CmdFriendType_GetFriendLoginInfoScRsp = 2930;
    CmdFriendType_GetPlayerDetailInfoScRsp = 2939;
    CmdFriendType_GetFriendListInfoScRsp = 2982;
    CmdFriendType_GetFriendAssistListScRsp = 2969;
    CmdFriendType_GetFriendRecommendListInfoCsReq = 2988;
    CmdFriendType_SetFriendRemarkNameCsReq = 2964;
    CmdFriendType_AddBlacklistScRsp = 2949;
    CmdFriendType_HandleFriendScRsp = 2972;
    CmdFriendType_GetFriendDevelopmentInfoCsReq = 2933;
    CmdFriendType_AddBlacklistCsReq = 2962;
    CmdFriendType_SetAssistCsReq = 2905;
    CmdFriendType_DeleteFriendCsReq = 2980;
    CmdFriendType_SearchPlayerScRsp = 2909;
    CmdFriendType_GetFriendApplyListInfoScRsp = 2991;
    CmdFriendType_SetForbidOtherApplyFriendCsReq = 2960;
    CmdFriendType_SyncDeleteFriendScNotify = 2904;
    CmdFriendType_ApplyFriendCsReq = 2998;
    CmdFriendType_NewAssistHistoryNotify = 2921;
}

message CurAssistChangedNotify {
    PlayerAssistInfo ODHMGPNECFO = 15;
}

message DBFHOCOBPMK {
    PlayerChallengePeakRecordBossData CDFFIGJLGMM = 3;
    repeated PlayerChallengePeakRecordMobData HDCHFBKDCEB = 5;
    uint32 group_id = 6;
}

message DeleteBlacklistCsReq {
    uint32 uid = 12;
}

message DeleteBlacklistScRsp {
    uint32 uid = 4;
    uint32 retcode = 10;
}

message DeleteFriendCsReq {
    uint32 LMHDOMCMGNL = 1;
    uint32 uid = 11;
}

message DeleteFriendScRsp {
    uint32 uid = 2;
    uint32 retcode = 13;
}

enum DevelopmentType {
    DevelopmentType_DevelopmentNone = 0;
    DevelopmentType_DevelopmentRogueCosmos = 1;
    DevelopmentType_DevelopmentRogueChess = 2;
    DevelopmentType_DevelopmentRogueChessNous = 3;
    DevelopmentType_DevelopmentMemoryChallenge = 4;
    DevelopmentType_DevelopmentStoryChallenge = 5;
    DevelopmentType_DevelopmentUnlockAvatar = 6;
    DevelopmentType_DevelopmentUnlockEquipment = 7;
    DevelopmentType_DevelopmentActivityStart = 8;
    DevelopmentType_DevelopmentActivityEnd = 9;
    DevelopmentType_DevelopmentBossChallenge = 10;
    DevelopmentType_DevelopmentRogueTourn = 11;
    DevelopmentType_DevelopmentRogueTournWeek = 12;
    DevelopmentType_DevelopmentRogueMagic = 13;
    DevelopmentType_DevelopmentChallengePeak = 14;
    DevelopmentType_DevelopmentRogueTournDivision = 15;
    DevelopmentType_DevelopmentGridFightDivision = 16;
    DevelopmentType_DevelopmentGridFightGameplay = 17;
    DevelopmentType_DevelopmentGridFightGameplayOcMode = 18;
}

message DisplayAvatarDetailInfo {
    repeated AvatarSkillTree skilltree_list = 7;
    uint32 enhanced_id = 4;
    uint32 avatar_id = 5;
    uint32 pos = 2;
    repeated DisplayRelicInfo relic_list = 12;
    uint32 avatar_type = 11;
    uint32 rank = 15;
    DisplayEquipmentInfo equipment = 9;
    uint32 level = 1;
    uint32 dressed_skin_id = 3;
    uint32 promotion = 10;
    uint32 exp = 8;
}

message DisplayEquipmentInfo {
    uint32 level = 13;
    uint32 promotion = 4;
    uint32 tid = 2;
    uint32 rank = 8;
    uint32 exp = 7;
}

message DisplayRelicInfo {
    uint32 tid = 9;
    uint32 type = 5;
    uint32 exp = 13;
    repeated RelicAffix sub_affix_list = 15;
    uint32 main_affix_id = 4;
    uint32 level = 7;
}

message EDEGAHHANMF {
    uint32 OPENPJJLADD = 14;
    uint32 LCDDMLIMAGA = 9;
    uint32 IGENPDKHDMC = 10;
    uint32 PLKAGMLBCDG = 15;
    uint32 MBHJNPEILCL = 1;
}

message EJAKBKOEEPC {
    JMOCDMHFEJG BHDKLAJPMBJ = 8;
}

message FKCNEPIJJAO {
    uint32 area_id = 2;
    uint32 DCOKLHPBAJO = 10;
    uint32 FEFLAJIODHB = 7;
    uint32 JNCCOGCHNMB = 4;
}

message FPDCINMDJCE {
    PlayerSimpleInfo player_info = 13;
    string remark_name = 2;
    FriendChallengeLineup NHMOPCHJEHN = 5;
    CJNDCNIJBEI BNAFKMMLGFE = 7;
    MJMGDLJAJCM LMHIOKFMDNE = 11;
    ChallengePeakBossFriendLineupRecommendation KCNAHJCMNJI = 1;
    OJJJDPNOKHG NHKCFOALAPD = 8;
    OFFMDBMMNFM KPPDEMBPEDO = 784;
}

message FriendApplyInfo {
    int64 apply_time = 3;
    PlayerSimpleInfo player_info = 2;
}

enum FriendApplySource {
    FriendApplySource_None = 0;
    FriendApplySource_Search = 1;
    FriendApplySource_Recommend = 2;
    FriendApplySource_Assist = 3;
    FriendApplySource_RecommendAssist = 4;
    FriendApplySource_PsnFriend = 5;
    FriendApplySource_AssistReward = 6;
    FriendApplySource_SocialPlay = 7;
    FriendApplySource_Roaming = 8;
    FriendApplySource_DiceCombatV2 = 9;
    FriendApplySource_RecentVisitor = 10;
}

message FriendChallengeClearanceInfo {
    PlayerChallengeTierceRecord MEGBIPBAFBP = 7;
    uint32 LMPPDGOFOMF = 13;
    ChallengeStatistics challenge_default = 149;
    ChallengeStoryStatistics challenge_story = 1122;
    ChallengeBossStatistics challenge_boss = 1429;
    uint32 group_id = 8;
}

message FriendChallengeLineup {
    uint32 buff_two = 4;
    PlayerSimpleInfo player_info = 5;
    string remark_name = 11;
    repeated ChallengeLineupList lineup_list = 6;
    uint32 score_id = 3;
    uint32 EEJCPNAEKLJ = 9;
    uint32 buff_one = 2;
}

message FriendGridFightRecord {
    uint32 division_id = 6;
}

message FriendRecommendInfo {
    bool JINLAHLMDLN = 1;
    PlayerSimpleInfo player_info = 10;
}

message FriendSimpleInfo {
    PAEFDELFKJK MBOIHJLIJDG = 11;
    bool is_marked = 10;
    PlayerSimpleInfo player_info = 12;
    PlayingState playing_state = 14;
    string remark_name = 8;
    int64 create_time = 4;
}

message GLILLENEIJK {
    uint32 GNIFODGCPAA = 3;
    uint32 FFFNGBKHOEA = 9;
}

message GetAssistHistoryCsReq {
}

message GetAssistHistoryScRsp {
    uint32 EFONJLMDFIH = 8;
    uint32 retcode = 5;
    uint32 LLIPLPNDIMC = 2;
    uint32 OFEKHCHHOFD = 12;
}

message GetAssistListCsReq {
    bool LKBAENBKJCE = 1;
    bool DDNKHDIKAEL = 14;
}

message GetAssistListScRsp {
    uint32 retcode = 3;
    repeated PlayerAssistInfo assist_list = 8;
}

message GetCurAssistCsReq {
}

message GetCurAssistScRsp {
    uint32 retcode = 10;
    PlayerAssistInfo ODHMGPNECFO = 12;
}

message GetFriendApplyListInfoCsReq {
}

message GetFriendApplyListInfoScRsp {
    uint32 retcode = 7;
    repeated FriendApplyInfo receive_apply_list = 15;
    repeated uint32 send_apply_list = 10;
}

message GetFriendAssistListCsReq {
    bool DDNKHDIKAEL = 15;
    repeated uint32 EEJGCFBJKAK = 8;
    repeated uint32 HHFPJHMEIJK = 1;
    uint32 target_side = 13;
    PIDAHABFLBL HFOLAOIKOLB = 9;
}

message GetFriendAssistListScRsp {
    repeated PlayerAssistInfo assist_list = 6;
    uint32 target_side = 7;
    uint32 retcode = 1;
}

message GetFriendBattleRecordDetailCsReq {
    uint32 uid = 4;
}

message GetFriendBattleRecordDetailScRsp {
    BGPIHMLLNGM HCIEFEHCENO = 14;
    uint32 uid = 2;
    uint32 retcode = 1;
    HBJDMDKKMFI BAMDEHAICDA = 15;
    repeated FriendChallengeClearanceInfo EPNLMHPCDKL = 10;
    repeated DBFHOCOBPMK LGIBJLFBFCG = 3;
}

message GetFriendDevelopmentInfoCsReq {
    uint32 uid = 8;
}

message GetFriendDevelopmentInfoScRsp {
    uint32 uid = 11;
    repeated NJMOBNILIHI EMBPENNEIJH = 10;
    uint32 retcode = 4;
}

message GetFriendListInfoCsReq {
}

message GetFriendListInfoScRsp {
    repeated PlayerSimpleInfo black_list = 5;
    repeated FriendSimpleInfo friend_list = 13;
    uint32 retcode = 12;
}

message GetFriendLoginInfoCsReq {
}

message GetFriendLoginInfoScRsp {
    repeated uint32 PCNLLMKOCEI = 13;
    bool show_red_dot_flag = 14;
    bool is_allow_other_apply = 4;
    uint32 retcode = 2;
    repeated uint32 NJJMDGKLLKP = 7;
}

message GetFriendRecommendLineupCsReq {
    JFNJKAPPNOF type = 7;
    uint32 key = 15;
}

message GetFriendRecommendLineupDetailCsReq {
    uint32 uid = 11;
    JFNJKAPPNOF type = 7;
    uint32 key = 5;
}

message GetFriendRecommendLineupDetailScRsp {
    JFNJKAPPNOF type = 3;
    uint32 retcode = 11;
    uint32 uid = 2;
    repeated DisplayAvatarDetailInfo KNHHAJDNGJG = 14;
    uint32 key = 4;
}

message GetFriendRecommendLineupScRsp {
    uint32 key = 14;
    repeated FPDCINMDJCE MGKCKHIIICL = 4;
    JFNJKAPPNOF type = 5;
    uint32 retcode = 1;
    bool ALDBIIIGLOM = 10;
}

message GetFriendRecommendListInfoCsReq {
    bool DDNKHDIKAEL = 11;
}

message GetFriendRecommendListInfoScRsp {
    repeated FriendRecommendInfo friend_recommend_list = 4;
    uint32 retcode = 8;
}

message GetPlatformPlayerInfoCsReq {
    repeated string EPIBJAMIJFI = 6;
    PlatformType platform = 13;
}

message GetPlatformPlayerInfoScRsp {
    repeated PlayerSimpleInfo friend_recommend_list = 1;
    uint32 retcode = 15;
}

message GetPlayerDetailInfoCsReq {
    uint32 uid = 5;
}

message GetPlayerDetailInfoScRsp {
    uint32 retcode = 4;
    PlayerDetailInfo detail_info = 7;
}

message HBJDMDKKMFI {
    uint32 division_id = 1;
}

message HHJANNIGCKM {
    repeated uint32 finished_target_list = 13;
    bool EGLLMGLLHDL = 15;
}

message HandleFriendCsReq {
    bool is_accept = 1;
    uint32 uid = 14;
}

message HandleFriendScRsp {
    FriendSimpleInfo friend_info = 6;
    bool is_accept = 3;
    uint32 uid = 14;
    uint32 retcode = 15;
}

message ICMGDJBDFEA {
    HHJANNIGCKM NCKJLAEJNDP = 9;
    uint32 max_level = 8;
    uint32 LMPPDGOFOMF = 12;
    uint32 group_id = 14;
    uint32 FBOGDAHNDKA = 5;
}

message IENCCMEAIAJ {
    uint32 GNIFODGCPAA = 10;
}

message JBKJGBMMKFI {
    uint32 peak_id = 9;
}

enum JFNJKAPPNOF {
    JFNJKAPPNOF_NLCDGIPGFDJ = 0;
    JFNJKAPPNOF_OCDLPDDMCLP = 1;
    JFNJKAPPNOF_JHOEBNNMKHB = 2;
    JFNJKAPPNOF_KMDNDLKKDLH = 3;
    JFNJKAPPNOF_DJKDPGDLLFM = 4;
    JFNJKAPPNOF_IGDNEOELFKC = 5;
    JFNJKAPPNOF_HCBNCEDBABL = 6;
}

message JMOCDMHFEJG {
    PIBFIDOEPAP KGBHIKKLJMK = 15;
}

message KAODLPJMEFE {
    PlatformType platform = 6;
    string remark_name = 8;
    uint32 level = 9;
    uint32 uid = 14;
    uint32 MIDBIPHKLJO = 3;
    uint32 DCOFPHDKNIJ = 1;
    HeadFrameInfo head_frame_info = 12;
    string nickname = 5;
    uint32 head_icon = 11;
    string DJONELMIFEE = 13;
}

message KGBAFBEMICB {
    uint32 AACGBEBGDPE = 1;
    bool MNDCIBFEJOP = 11;
}

message KHFEGOFPHHC {
    uint32 area_id = 11;
}

message LJJIEAPLOOI {
    uint32 division_id = 11;
}

message MJMGDLJAJCM {
    repeated OKFKPPNGCOD DNIGKDKIPPJ = 5;
}

message MOOGABJBJAG {
    uint32 challenge_id = 1;
}

message NJMOBNILIHI {
    DevelopmentType NELHEHHFCCM = 2;
    int64 time = 6;
    KHFEGOFPHHC DCODKLADIJM = 1929;
    MOOGABJBJAG ELJOEBBHDPB = 1889;
    uint32 avatar_id = 459;
    uint32 KAJCFPKEGBP = 814;
    CFNEMEIDMID IIBJEGJMOKJ = 1010;
    uint32 panel_id = 259;
    JBKJGBMMKFI AGKKAFEFGOB = 717;
    IENCCMEAIAJ IMILIFMDLBI = 790;
    LJJIEAPLOOI BNNDODHIKCE = 1163;
    KGBAFBEMICB DHKCMBFCALH = 1379;
}

message NMFEHEHPGAB {
    uint32 MGCACGFLKEK = 7;
    uint32 area_id = 5;
    uint32 MBDKAJBEPPF = 15;
}

message NewAssistHistoryNotify {
    uint32 OFEKHCHHOFD = 9;
}

message OFFMDBMMNFM {
    repeated BMKNANGPDGH lineup_list = 11;
}

message OHKDPNBGPOA {
    bool IOJEAOCOBBF = 15;
    bool DCJECFMMIBC = 4;
    bool MAKOLELFLFH = 2;
    bool PFBHGAHAFMD = 7;
    bool GNFDDPEMMFN = 13;
}

message OIMLMDHOHAP {
    uint32 APANPLBMONN = 5;
    uint32 KPHJDOPBMEN = 1;
    uint32 IELFOBFPDPA = 4;
    uint32 area_id = 12;
}

message OJJJDPNOKHG {
    repeated ChallengeLineupList lineup_list = 4;
    repeated uint32 AOLIEDBCNBN = 15;
    repeated uint32 finished_target_list = 12;
}

message OKFKPPNGCOD {
    repeated uint32 finished_target_list = 2;
    uint32 peak_id = 13;
    repeated ONKDAPOKGAC avatar_list = 5;
}

message ONKDAPOKGAC {
    AvatarType avatar_type = 1;
    uint32 id = 2;
    uint32 level = 3;
    uint32 index = 4;
    uint32 skin_id = 5;
}

message PAEFDELFKJK {
    ICMGDJBDFEA AMLDHBMIGEN = 13;
    BattleRecordType display_type = 4;
    FriendGridFightRecord BAMDEHAICDA = 6;
    EJAKBKOEEPC KBLKLGDCOMF = 14;
}

message PIBFIDOEPAP {
    uint32 FFFNGBKHOEA = 12;
    uint32 GNIFODGCPAA = 13;
}

enum PIDAHABFLBL {
    PIDAHABFLBL_ONGOHDOKEIE = 0;
    PIDAHABFLBL_FJBENKPGBPP = 1;
    PIDAHABFLBL_IBNPGEDFIMO = 2;
}

message PlayerAssistInfo {
    DisplayAvatarDetailInfo assist_avatar = 8;
    PlayerSimpleInfo player_info = 1;
}

message PlayerChallengePeakRecordBossData {
    uint32 buff_id = 13;
    repeated uint32 MCJNLLBBDHN = 9;
    uint32 best_cycle_count = 6;
    bool CFLDOMPACKI = 15;
    uint32 DJFGDMIDEHJ = 8;
    bool HAMDKIHGKGO = 1;
    ChallengeLineupList lineup = 4;
    uint32 peak_id = 11;
}

message PlayerChallengePeakRecordMobData {
    uint32 peak_id = 10;
    repeated uint32 MCJNLLBBDHN = 15;
    uint32 cycles_used = 5;
    ChallengeLineupList lineup = 12;
}

message PlayerDetailInfo {
    uint32 KINOEHKMFML = 634;
    PlayerRecordInfo record_info = 7;
    OHKDPNBGPOA BOKLABGLEFL = 864;
    repeated DisplayAvatarDetailInfo assist_avatar_list = 48;
    string nickname = 6;
    uint32 world_level = 10;
    CJLCPMDGIBO DHKFCDAGHDM = 1550;
    uint32 gender = 1399;
    uint32 level = 11;
    uint32 HCGMAGDFAAO = 15;
    string IJKOMIKFKEK = 2;
    uint32 head_icon = 13;
    bool HIEAPDNNNEI = 12;
    string signature = 8;
    HeadFrameInfo head_frame_info = 994;
    PlatformType platform = 9;
    bool is_banned = 1;
    repeated DisplayAvatarDetailInfo display_avatar_list = 5;
    uint32 uid = 3;
    OIIPJFDNPAH AIHNDIAFGPM = 1369;
    uint32 GEJFMBBHNLN = 14;
    string DJONELMIFEE = 4;
}

message PlayerRecordInfo {
    uint32 PPFDDFAHLED = 8;
    EDEGAHHANMF EOGGPDHKKBJ = 6;
    uint32 MIMECEAFDNK = 13;
    uint32 JJKIKOBAJLF = 11;
    uint32 DIOIIFAHAKK = 4;
    uint32 MHOIJFEBAPA = 15;
    uint32 NECKJBHEKHE = 12;
    uint32 ALGEOLGNFBL = 7;
    uint32 KCBINJNIBNO = 3;
}

enum PlayingState {
    PlayingState_None = 0;
    PlayingState_PlayingRogueCosmos = 1;
    PlayingState_PlayingRogueChess = 2;
    PlayingState_PlayingRogueChessNous = 3;
    PlayingState_PlayingChallengeMemory = 4;
    PlayingState_PlayingChallengeStory = 5;
    PlayingState_PlayingChallengeBoss = 6;
    PlayingState_PlayingRogueTourn = 7;
    PlayingState_PlayingRogueMagic = 8;
    PlayingState_PlayingChallengePeak = 9;
    PlayingState_PlayingGridFight = 10;
}

message ReportPlayerCsReq {
    string IMNOJNCGGNI = 6;
    uint32 uid = 10;
    uint32 OLLBLNAGMPC = 14;
}

message ReportPlayerScRsp {
    uint32 retcode = 12;
}

message SearchPlayerCsReq {
    bool DDNKHDIKAEL = 3;
    repeated uint32 uid_list = 11;
}

message SearchPlayerScRsp {
    repeated PlayerSimpleInfo simple_info_list = 6;
    uint32 retcode = 7;
    repeated uint32 result_uid_list = 14;
}

message SetAssistCsReq {
    uint32 avatar_id = 4;
    uint32 uid = 11;
}

message SetAssistScRsp {
    uint32 retcode = 15;
    uint32 avatar_id = 10;
    uint32 uid = 5;
}

message SetForbidOtherApplyFriendCsReq {
    bool PBNJDHFCHHC = 11;
}

message SetForbidOtherApplyFriendScRsp {
    bool PBNJDHFCHHC = 4;
    uint32 retcode = 11;
}

message SetFriendMarkCsReq {
    uint32 reason = 2;
    uint32 uid = 14;
    bool BIJJOJNJHDO = 7;
}

message SetFriendMarkScRsp {
    bool BIJJOJNJHDO = 9;
    uint32 uid = 14;
    uint32 retcode = 5;
}

message SetFriendRemarkNameCsReq {
    string remark_name = 1;
    uint32 reason = 12;
    uint32 uid = 14;
}

message SetFriendRemarkNameScRsp {
    string remark_name = 13;
    uint32 retcode = 11;
    uint32 uid = 8;
}

message SyncAddBlacklistScNotify {
    uint32 uid = 12;
}

message SyncApplyFriendScNotify {
    FriendApplyInfo friend_apply_info = 11;
}

message SyncDeleteFriendScNotify {
    uint32 uid = 8;
}

message SyncHandleFriendScNotify {
    bool is_accept = 3;
    uint32 uid = 15;
    FriendSimpleInfo friend_info = 10;
}

message TakeAssistRewardCsReq {
}

message TakeAssistRewardScRsp {
    uint32 retcode = 4;
    ItemList reward = 14;
    repeated KAODLPJMEFE OILHLECGBCH = 2;
}
