syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdFeverTimeActivityType {
    CmdFeverTimeActivityType_None = 0;
    CmdFeverTimeActivityType_GetFeverTimeActivityDataCsReq = 7159;
    CmdFeverTimeActivityType_EnterFeverTimeActivityStageScRsp = 7160;
    CmdFeverTimeActivityType_FeverTimeActivityBattleEndScNotify = 7157;
    CmdFeverTimeActivityType_GetFeverTimeActivityDataScRsp = 7156;
    CmdFeverTimeActivityType_EnterFeverTimeActivityStageCsReq = 7155;
}

message EnterFeverTimeActivityStageCsReq {
    uint32 MFLAIMHFABP = 15;
    repeated KPNHGDGLICN avatar_list = 6;
    uint32 id = 12;
    uint32 CJHDABDKGHP = 1;
}

message EnterFeverTimeActivityStageScRsp {
    uint32 retcode = 2;
    uint32 id = 3;
    SceneBattleInfo battle_info = 6;
}

message FeverTimeActivityBattleEndScNotify {
    FeverTimeBattleRank LDDHCPLNKKA = 12;
    uint32 turn_left = 14;
    uint32 id = 4;
    uint32 FAJDFFHODIP = 1;
}

enum FeverTimeBattleRank {
    FeverTimeBattleRank_C = 0;
    FeverTimeBattleRank_B = 1;
    FeverTimeBattleRank_A = 2;
    FeverTimeBattleRank_S = 3;
    FeverTimeBattleRank_Ss = 4;
}

message GetFeverTimeActivityDataCsReq {
}

message GetFeverTimeActivityDataScRsp {
    repeated JBMJOIPJPLH GNDEFEAEDNJ = 2;
    uint32 retcode = 14;
}

message JBMJOIPJPLH {
    FeverTimeBattleRank OINGNAJMFNL = 2;
    uint32 DJFGDMIDEHJ = 9;
    uint32 OFBEDJIAEOA = 13;
}
