syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CDABDPPPHBN {
    uint32 ALALEBDJGHA = 11;
    uint32 CJPDGBPLFIG = 3;
    repeated uint32 LINOMGEDMHC = 13;
    uint32 group_id = 5;
}

enum CmdFightActivityType {
    CmdFightActivityType_None = 0;
    CmdFightActivityType_EnterFightActivityStageScRsp = 3656;
    CmdFightActivityType_EnterFightActivityStageCsReq = 3639;
    CmdFightActivityType_TakeFightActivityRewardScRsp = 3698;
    CmdFightActivityType_FightActivityDataChangeScNotify = 3679;
    CmdFightActivityType_TakeFightActivityRewardCsReq = 3691;
    CmdFightActivityType_GetFightActivityDataScRsp = 3682;
    CmdFightActivityType_GetFightActivityDataCsReq = 3634;
}

message DOIBLFFDHDG {
    AvatarType avatar_type = 5;
    uint32 avatar_id = 15;
}

message EnterFightActivityStageCsReq {
    repeated uint32 avatar_list = 15;
    repeated DOIBLFFDHDG MACCJKCGGII = 7;
    repeated uint32 item_list = 5;
    uint32 DBKHHCGGKNN = 1;
    uint32 group_id = 6;
}

message EnterFightActivityStageScRsp {
    SceneBattleInfo battle_info = 6;
    uint32 group_id = 3;
    uint32 retcode = 14;
    uint32 DBKHHCGGKNN = 8;
}

message FightActivityDataChangeScNotify {
    map<uint32, uint32> EDGPAOJEENN = 4;
    repeated CDABDPPPHBN FALBALFNOFF = 11;
}

message GetFightActivityDataCsReq {
}

message GetFightActivityDataScRsp {
    uint32 world_level = 3;
    map<uint32, uint32> EDGPAOJEENN = 1;
    repeated CDABDPPPHBN FALBALFNOFF = 8;
    uint32 retcode = 14;
    bool CFDBDGEFJJN = 5;
}

message TakeFightActivityRewardScRsp {
    uint32 DBKHHCGGKNN = 2;
    uint32 retcode = 3;
    uint32 group_id = 7;
    ItemList reward = 11;
}
