syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdFiveDimType {
    CmdFiveDimType_None = 0;
    CmdFiveDimType_GetFiveDimMoneyScRsp = 2263;
    CmdFiveDimType_GetFiveDimMoneyDataCsReq = 2266;
    CmdFiveDimType_FiveDimGameTransferScRsp = 2254;
    CmdFiveDimType_GetFiveDimGameDataScRsp = 2268;
    CmdFiveDimType_FiveDimJumpEnergyChangeScNotify = 2260;
    CmdFiveDimType_GetFiveDimMoneyDataScRsp = 2275;
    CmdFiveDimType_FiveDimGameDataUpdateScNotify = 2257;
    CmdFiveDimType_GetFiveDimGameDataCsReq = 2259;
    CmdFiveDimType_UpdateFiveDimGameDataScRsp = 2253;
    CmdFiveDimType_UpdateFiveDimGameDataCsReq = 2264;
    CmdFiveDimType_FiveDimGameTransferCsReq = 2265;
    CmdFiveDimType_EnterFiveDimGameScRsp = 2274;
    CmdFiveDimType_FiveDimMoneyChangeScNotify = 2269;
    CmdFiveDimType_EnterFiveDimGameCsReq = 2261;
    CmdFiveDimType_LeaveFiveDimGameScRsp = 2262;
    CmdFiveDimType_LeaveFiveDimGameCsReq = 2271;
    CmdFiveDimType_GetFiveDimMoneyCsReq = 2272;
}

message EnterFiveDimGameCsReq {
    AHCLMAGAHPN PPJFMBIGIGB = 8;
    MotionInfo HKGDHOPGCKF = 13;
    BLPHONLBNBO OEIBHLMDJKA = 10;
}

message EnterFiveDimGameScRsp {
    uint32 retcode = 14;
}

message FiveDimGameDataUpdateScNotify {
    uint32 client_pos_version = 9;
    DGHPIDMDOJM CFDIKLBINHK = 3;
    bool HBJLJJAJHOI = 1;
}

message FiveDimGameTransferCsReq {
    AHCLMAGAHPN PPJFMBIGIGB = 1;
    uint32 COGDLBMPPNM = 14;
    KFDEPBCLENF KEHGFMAMEPD = 8;
    BLPHONLBNBO OEIBHLMDJKA = 10;
}

message FiveDimGameTransferScRsp {
    uint32 retcode = 10;
}

message FiveDimJumpEnergyChangeScNotify {
    uint32 CPFCMKLCMFG = 4;
}

message FiveDimMoneyChangeScNotify {
    uint32 KFBJGFJHGEK = 14;
    uint32 OEPCCMAPFFH = 4;
}

message GetFiveDimGameDataScRsp {
    uint32 CPFCMKLCMFG = 14;
    repeated uint32 KEGAOHGOALD = 8;
    uint32 retcode = 13;
    DGHPIDMDOJM CFDIKLBINHK = 6;
}

message GetFiveDimMoneyDataScRsp {
    uint32 OEPCCMAPFFH = 13;
    uint32 retcode = 2;
    uint32 KFBJGFJHGEK = 12;
}

message GetFiveDimMoneyScRsp {
    uint32 GJHKPIGEIIO = 4;
    uint32 JIDCDLCBKHG = 5;
    uint32 retcode = 7;
}

enum KFDEPBCLENF {
    KFDEPBCLENF_NLCDGIPGFDJ = 0;
    KFDEPBCLENF_KALJCABDJLC = 1;
    KFDEPBCLENF_HJJDLPHHFPA = 2;
}

message LeaveFiveDimGameCsReq {
    uint32 PJLKEHONHED = 13;
    KFDEPBCLENF KEHGFMAMEPD = 10;
    MotionInfo HKGDHOPGCKF = 4;
    uint32 COGDLBMPPNM = 2;
}

message LeaveFiveDimGameScRsp {
    uint32 retcode = 9;
    uint32 client_pos_version = 5;
}

message UpdateFiveDimGameDataCsReq {
    uint32 GABODFDMPMM = 5;
    AHCLMAGAHPN PPJFMBIGIGB = 14;
}

message UpdateFiveDimGameDataScRsp {
    uint32 retcode = 10;
}
