syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdFantasticStoryActivityType {
    CmdFantasticStoryActivityType_None = 0;
    CmdFantasticStoryActivityType_FinishChapterScNotify = 4979;
    CmdFantasticStoryActivityType_GetFantasticStoryActivityDataCsReq = 4934;
    CmdFantasticStoryActivityType_EnterFantasticStoryActivityStageScRsp = 4956;
    CmdFantasticStoryActivityType_FantasticStoryActivityBattleEndScNotify = 4991;
    CmdFantasticStoryActivityType_GetFantasticStoryActivityDataScRsp = 4982;
    CmdFantasticStoryActivityType_EnterFantasticStoryActivityStageCsReq = 4939;
}

message EnterFantasticStoryActivityStageCsReq {
    repeated PKCIPJBKAFO avatar_list = 10;
    uint32 battle_id = 15;
    uint32 OFHBPNGDEGO = 8;
    repeated uint32 buff_list = 13;
}

message EnterFantasticStoryActivityStageScRsp {
    uint32 retcode = 11;
    uint32 OFHBPNGDEGO = 1;
    SceneBattleInfo battle_info = 9;
    uint32 battle_id = 3;
}

message FGGCEKHFPLH {
    repeated PKCIPJBKAFO avatar_list = 3;
    repeated uint32 buff_list = 6;
}

message FantasticStoryActivityBattleEndScNotify {
    uint32 battle_id = 3;
    uint32 FHBNGHINHOG = 8;
    uint32 OFHBPNGDEGO = 15;
}

message GCFDJCPFOGG {
    repeated uint32 FIBFIKOBDPG = 2;
    repeated uint32 HPLNHIFHBMA = 10;
    uint32 OFHBPNGDEGO = 1;
    map<uint32, uint32> DLBOJCCDCFI = 13;
    map<uint32, FGGCEKHFPLH> DALPAKHCKLI = 9;
    repeated uint32 JJOBBOHHOMG = 11;
    repeated uint32 DJJKDGEFOIP = 6;
}

message GetFantasticStoryActivityDataCsReq {
    uint32 OFHBPNGDEGO = 12;
}

message GetFantasticStoryActivityDataScRsp {
    uint32 retcode = 10;
    GCFDJCPFOGG ONIEMLICONB = 4;
}

message PKCIPJBKAFO {
    uint32 avatar_id = 13;
    AvatarType avatar_type = 3;
}
