syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AAGHPDHCOOI {
    uint32 LKMEMKLGIIK = 7;
}

message AAMEAOBEGKA {
    uint32 unique_id = 3;
}

message ABPLALCHNFA {
    GridFightUpdateSrcType grid_update_src = 12;
    repeated GridFightSyncData JKPJFKCBIEM = 2;
    repeated uint32 OOEOCGLLHFO = 3;
}

message ACCMEOICEOD {
    repeated JKPOIHGIFFG GKJIDBEGBJP = 6;
}

enum ACOKICDKFCI {
    ACOKICDKFCI_LHLEHMPKDPB = 0;
    ACOKICDKFCI_LKKKMLMOMDI = 1;
    ACOKICDKFCI_KJLFGHAFPFP = 2;
    ACOKICDKFCI_FJDHALMPDAO = 3;
    ACOKICDKFCI_MJMCGPFLDIM = 4;
}

message AFCBKJEFKPG {
    GridFightDropInfo CLHLMNAPLNC = 6;
    IBBDHFAEFNH status = 3;
    uint32 progress = 4;
    BGMLEJCOFPK CCDGGDMHMLF = 8;
    bool MHBFIGLMLFG = 1;
    repeated uint32 CBACAMKJFMI = 7;
    uint32 id = 12;
}

message AFPJPEABFKH {
    uint32 EAKBFELDDBF = 2;
}

message AGGDDAJLAEB {
    double IDONFFOACIL = 14;
    uint32 INLHPJMOOMO = 10;
}

message AGOBLKJFJDL {
    uint32 OOPFNFIGPKB = 3;
    uint32 NFBJINKLLLK = 6;
}

message AHKDPCIIELA {
    uint32 role_star = 9;
    uint32 LOGHLGKIFEN = 5;
    uint32 monster_id = 12;
    uint32 IMDKLKONINF = 8;
}

message AJDFPFHBFJM {
}

message AKHEHAMBLEB {
    int64 KAHFEFACFIE = 6;
    int64 start_time = 11;
}

message AMFIFNOCDOF {
    uint32 MDNAGANGNKK = 7;
}

enum BBFEFIPJMEB {
    BBFEFIPJMEB_OHDJNICJKLK = 0;
    BBFEFIPJMEB_NCBOLDFDGNL = 1;
    BBFEFIPJMEB_EKGPCJLBINA = 2;
}

message BDDDLOFNCHN {
    uint32 MDNAGANGNKK = 15;
}

message BEBIJAKFNLO {
    uint32 PEBCBLBLMPH = 12;
}

enum BGMLEJCOFPK {
    BGMLEJCOFPK_NLCDGIPGFDJ = 0;
    BGMLEJCOFPK_ENPLACDLJGA = 1;
    BGMLEJCOFPK_DACEMIDFHOG = 2;
}

message BJALEHOMFKH {
    uint32 effect_id = 5;
    repeated uint32 OLPPMEAMFFO = 3;
    uint32 trait_id = 8;
}

message BJFLPMNPFFK {
    uint32 MDNAGANGNKK = 8;
}

message BJIGOFOAEPL {
}

message BKIKOGNAECK {
    uint32 DNMFNFCLOOM = 6;
    uint32 PEBCBLBLMPH = 2;
}

message BOPHDCKJMMN {
    uint32 weight = 5;
    uint32 CKKDAEMFDPA = 7;
}

message BPENENIMEFE {
    GridFightDropInfo GHBBCIIPHKJ = 9;
    bool IJJDEHIPOEL = 10;
    uint32 quest_id = 14;
}

message CBEHKFHNNAI {
}

message CCGJDDBKIDE {
    uint32 IMJBFLJPMJB = 12;
    BBFEFIPJMEB type = 11;
}

message CCKPBIKOIBB {
    uint32 LKMEMKLGIIK = 7;
}

message CEHDAMJJFOE {
    uint32 JNJBMFJHBHD = 5;
    uint32 MDNAGANGNKK = 10;
    uint32 ENNOJCBAJEN = 15;
}

message CFFDCICDAKK {
    repeated BPENENIMEFE EKBOGBMPAPJ = 1;
}

message CFHEKNFNMIP {
    bool is_locked = 3;
}

message CFIDOJGKBHB {
}

message CJPOMFIDLOA {
    uint32 augment_id = 13;
}

message CKIKMLCGLFK {
    uint32 FGCLPKIDGFK = 4;
}

message CKPOBLIFMGN {
    GridFightTalentInfo MHFHLBHFIBC = 3;
}

message CLFABOEKMJI {
    repeated uint32 MIOAPAGNAMC = 11;
}

message CNBHPJFFLEF {
    repeated uint32 OJNEFBJHCCK = 10;
    bool is_effect = 14;
}

message CheckTextCsReq {
    string OHNAIHACIKH = 1;
}

enum CmdGridFightType {
    CmdGridFightType_None = 0;
    CmdGridFightType_GridFightRecycleRoleScRsp = 8517;
    CmdGridFightType_GridFightQueryGamePlayDataScRsp = 8486;
    CmdGridFightType_GridFightUpdateGameRefCsReq = 8561;
    CmdGridFightType_GridFightSetMonsterHpRatioCsReq = 8450;
    CmdGridFightType_GridFightPreCheckFormationTextCsReq = 8661;
    CmdGridFightType_GridFightBuyGoodsScRsp = 8458;
    CmdGridFightType_GridFightGetArchiveScRsp = 8631;
    CmdGridFightType_GridFightEnablePermanentTalentCsReq = 8796;
    CmdGridFightType_GridFightEnablePermanentTalentScRsp = 8690;
    CmdGridFightType_GridFightResetPermanentTalentCsReq = 8444;
    CmdGridFightType_GridFightBuyGoodsCsReq = 8768;
    CmdGridFightType_GridFightTraitUpdateCsReq = 8402;
    CmdGridFightType_GridFightUpdatePosScRsp = 8765;
    CmdGridFightType_GridFightUseConsumableScRsp = 8453;
    CmdGridFightType_GridFightUseForgeCsReq = 8641;
    CmdGridFightType_GridFightBuyExpCsReq = 8625;
    CmdGridFightType_GridFightUpdatePosCsReq = 8692;
    CmdGridFightType_GridFightUpdateEquipTrackProrityScRsp = 8629;
    CmdGridFightType_GridFightApplyFormationCsReq = 8624;
    CmdGridFightType_GridFightUpdateGameRefScRsp = 8478;
    CmdGridFightType_GridFightLockShopScRsp = 8737;
    CmdGridFightType_GridFightBackToPrepareCsReq = 8738;
    CmdGridFightType_GridFightEquipCraftCsReq = 8773;
    CmdGridFightType_GridFightUpdateEquipTrackScRsp = 8565;
    CmdGridFightType_GridFightUseForgeScRsp = 8546;
    CmdGridFightType_GridFightFinishTutorialScRsp = 8791;
    CmdGridFightType_GridFightUseOrbNotify = 8529;
    CmdGridFightType_GridFightUpdateFormationScRsp = 8525;
    CmdGridFightType_GridFightTraitUpdateScRsp = 8714;
    CmdGridFightType_GridFightEquipDressCsReq = 8504;
    CmdGridFightType_GridFightLockShopCsReq = 8696;
    CmdGridFightType_GridFightRecycleRoleCsReq = 8656;
    CmdGridFightType_GridFightSyncVirtualItemScNotify = 8748;
    CmdGridFightType_GridFightStartGamePlayScRsp = 8474;
    CmdGridFightType_GridFightPreCheckFormationTextScRsp = 8590;
    CmdGridFightType_GridFightDeleteFormationCsReq = 8479;
    CmdGridFightType_GridFightEnterBattleStageScRsp = 8647;
    CmdGridFightType_GridFightHandlePendingActionScRsp = 8584;
    CmdGridFightType_GridFightUpdateEquipTrackProrityCsReq = 8800;
    CmdGridFightType_GridFightBackToPrepareScRsp = 8512;
    CmdGridFightType_GridFightSettleNotify = 8664;
    CmdGridFightType_GridFightQuitSettleCsReq = 8798;
    CmdGridFightType_GridFightResumeGamePlayCsReq = 8626;
    CmdGridFightType_GridFightUseOrbScRsp = 8430;
    CmdGridFightType_GridFightRefreshShopScRsp = 8447;
    CmdGridFightType_GridFightGetFormationCsReq = 8583;
    CmdGridFightType_GridFightEnterBattleStageCsReq = 8651;
    CmdGridFightType_GridFightGetShopRandomRuleCsReq = 8677;
    CmdGridFightType_GridFightUpdateEliteBranchSelectScRsp = 8469;
    CmdGridFightType_GridFightEndBattleStageNotify = 8606;
    CmdGridFightType_GridFightGetDataScRsp = 8440;
    CmdGridFightType_GridFightRoleLuckChanceScRsp = 8577;
    CmdGridFightType_GridFightEquipDressScRsp = 8613;
    CmdGridFightType_GridFightUpdateEliteBranchSelectCsReq = 8681;
    CmdGridFightType_GridFightGetFormationScRsp = 8618;
    CmdGridFightType_GridFightEquipCraftScRsp = 8790;
    CmdGridFightType_GridFightUseOrbCsReq = 8638;
    CmdGridFightType_GridFightBuyExpScRsp = 8775;
    CmdGridFightType_GridFightRefreshShopCsReq = 8730;
    CmdGridFightType_GridFightFinishTutorialCsReq = 8499;
    CmdGridFightType_GridFightTakeWeeklyRewardScRsp = 8666;
    CmdGridFightType_GridFightFavoriteArchiveCsReq = 8756;
    CmdGridFightType_GridFightFavoriteArchiveScRsp = 8569;
    CmdGridFightType_GridFightSeasonHandBookNotify = 8746;
    CmdGridFightType_GridFightSetMonsterHpRatioScRsp = 8456;
    CmdGridFightType_GridFightEnableSeasonTalentScRsp = 8558;
    CmdGridFightType_GridFightUpdateFormationCsReq = 8711;
    CmdGridFightType_GridFightHandlePendingActionCsReq = 8482;
    CmdGridFightType_GridFightSummonProjectionCsReq = 8548;
    CmdGridFightType_GridFightGetDataCsReq = 8704;
    CmdGridFightType_GridFightResetPermanentTalentScRsp = 8718;
    CmdGridFightType_GridFightDeleteFormationScRsp = 8573;
    CmdGridFightType_GridFightQuitSettleScRsp = 8472;
    CmdGridFightType_GridFightGetShopRandomRuleScRsp = 8575;
    CmdGridFightType_GridFightRoleLuckChanceCsReq = 8519;
    CmdGridFightType_GridFightResetSeasonTalentCsReq = 8457;
    CmdGridFightType_GridFightSyncUpdateResultScNotify = 8452;
    CmdGridFightType_GridFightGetArchiveCsReq = 8471;
    CmdGridFightType_GridFightSummonProjectionScRsp = 8559;
    CmdGridFightType_GridFightDestroyExceedWeeklyRewardCsReq = 8780;
    CmdGridFightType_GridFightUpdateTraitTrackScRsp = 8493;
    CmdGridFightType_GridFightQuitLeaveGamePlayScRsp = 8682;
    CmdGridFightType_GridFightResumeGamePlayScRsp = 8653;
    CmdGridFightType_GridFightQuitLeaveGamePlayCsReq = 8581;
    CmdGridFightType_GridFightUpdateTraitTrackCsReq = 8591;
    CmdGridFightType_GridFightUpdateEquipTrackCsReq = 8429;
    CmdGridFightType_GridFightTakeWeeklyRewardCsReq = 8462;
    CmdGridFightType_GridFightApplyFormationScRsp = 8436;
    CmdGridFightType_GridFightSyncKeepWinNumScNotify = 8607;
    CmdGridFightType_GridFightUseConsumableCsReq = 8513;
    CmdGridFightType_GridFightStartGamePlayCsReq = 8466;
    CmdGridFightType_GridFightEnableSeasonTalentCsReq = 8528;
    CmdGridFightType_GridFightDestroyExceedWeeklyRewardScRsp = 8688;
    CmdGridFightType_GridFightQueryGamePlayDataCsReq = 8745;
    CmdGridFightType_GridFightResetSeasonTalentScRsp = 8541;
    CmdGridFightType_GridFightWeeklyExtraSeasonExpNotify = 8445;
}

message DBFGKBNAKNH {
    uint32 KHHFIEPDHHD = 13;
}

message DFMGEJCCBPD {
}

message DGILDLDMGEI {
}

message DPHPAKFLNOD {
}

message EJEFKJGAKOO {
    uint32 trait_id = 2;
    uint32 effect_id = 4;
    uint32 MENFBEDCBHB = 15;
}

message ELGLKEAPLGM {
    uint32 grid_fight_equipment_id = 8;
}

message ELJOHIOHPMJ {
    uint32 IJMKBOBGHBD = 15;
}

message ELPPDAHKLBE {
}

message EPLJJNHCJIF {
}

message FADHEIGJENF {
    map<string, uint32> HJMAEDKCONE = 8;
}

message FAFBDGCEAHD {
    uint32 trait_id = 9;
    uint32 AFKKLDMAEDJ = 15;
}

message FBDLJKEBPHM {
    uint32 MDNAGANGNKK = 3;
    uint32 role_id = 7;
    map<uint32, uint32> JPIHLKGCBPC = 5;
}

message FBFBMMAAFCP {
    uint32 NBPFMFMKJHI = 4;
    uint32 EMFCEMPHOPI = 8;
}

message FCABIGNMAPL {
    uint32 CKKDAEMFDPA = 7;
}

message FHBHIHJAOPB {
    uint32 DMLFGGDECDN = 15;
    uint32 ODDKKGOJHFO = 13;
    uint32 DCAHJELNJNP = 2;
}

message FIIJNPBFJBG {
    map<string, uint32> POCKGKDFLKK = 5;
    uint32 IFLJPNDPDOA = 7;
}

message FKILNIGOKBF {
    uint32 role_id = 13;
}

message FKJMGFOPHHN {
    repeated FLFHACPLDJE CKJAKKNOHEK = 15;
    uint32 LCLPEJHEAID = 4;
}

message FLFHACPLDJE {
    PGECGKEKFNC BDPIMPJOJBK = 3;
    uint32 gold = 13;
}

message FMJDDIHBELC {
    uint32 PPKKHHNEOHB = 5;
    uint32 grid_fight_lineup_hp = 12;
}

message FNNFHNKHIDD {
    uint32 PFIKCNFBGHE = 12;
}

message FPHPFJLAJDK {
    uint32 pos = 13;
    uint32 LKMEMKLGIIK = 2;
    uint32 unique_id = 11;
}

message FavourArchiveCsReq {
    uint32 BAAGDILLLME = 9;
    bool IECKKCHJMLP = 2;
}

message GANGPHPGFCL {
    GridFightDamageSttInfo NKBIDLBLONC = 10;
    repeated GridFightSectionRecordInfo FNJNKKMNKIM = 7;
}

message GBJHJGCOJBC {
    uint32 MDNAGANGNKK = 2;
}

message GEEMFDBDMDH {
    NFPLDMFCLHA LHIAODNJIIC = 10;
    uint32 PBMAHOJBAGG = 15;
    NFPLDMFCLHA EDCLIPCEHAO = 2;
}

message GEIBJKJDOHO {
    uint32 trait_id = 3;
    repeated uint32 FJBFGEIGMHF = 8;
    uint32 effect_id = 12;
}

message GFOMAIAIDFA {
    uint32 IEOGEFBLNEL = 5;
}

message GHMLCIMANAM {
    repeated uint32 GEJEJNNMGGP = 10;
    uint32 HDCJFJNBNBA = 2;
    ACOKICDKFCI BGEAMGMALCL = 13;
}

message GILMFECEBFE {
    uint32 EOPHMLBEPGK = 12;
    uint32 PEBCBLBLMPH = 15;
}

message GIOLAAKLDED {
    uint32 augment_id = 1;
}

message GKLDOELMEIN {
    uint32 unique_id = 13;
}

message GLIFOLCEMIN {
    uint32 KEJGCDOGEDD = 2;
    uint32 PIFOEGCGKLC = 3;
}

message GLPCEKMKLGG {
    repeated uint32 grid_fight_avatar_list = 6;
}

message GMBMNFLMKPI {
    GridFightLockType LMICDNNABNM = 13;
    GridFightLockReason IBCPAKJAPFF = 12;
}

message GOCIGPCDKDJ {
    uint32 AACGBEBGDPE = 8;
    uint32 FDGKBOIEHBD = 5;
    uint32 EMOHLJHPOPC = 11;
    uint32 DCAHJELNJNP = 15;
    uint32 PAGPKOKMDBK = 7;
    uint32 LKCJAPIGEND = 14;
    uint32 section_id = 13;
    repeated uint32 FMEOHKHGMJM = 10;
}

message GPCFHMLMDHC {
    uint32 unique_id = 11;
}

message GridFightArchiveData {
    bool IECKKCHJMLP = 1;
    int64 OBNEAIPKGKL = 15;
    uint32 PMBNKEFCICH = 5;
    OEDHMAHDECC BFLLJJBHLDF = 2;
    uint32 BAAGDILLLME = 6;
    uint32 GEGMHOMNBDG = 7;
    uint32 LJNGPCKPJLF = 13;
}

message GridFightAugmentActionInfo {
    repeated GridFightPendingAugmentInfo CEBFFDFMKGK = 2;
}

message GridFightBackToPrepareCsReq {
}

message GridFightConsumableInfo {
    uint32 round_cnt = 10;
    uint32 group_id = 8;
    uint32 item_id = 15;
    uint32 num = 7;
}

message GridFightConsumableTargetInfo {
    BDDDLOFNCHN AALCFBOGFKP = 1364;
    HPJKBFKAKJH IMILGHELNBJ = 1789;
    BEBIJAKFNLO KMCBBKIHBKF = 1486;
    GBJHJGCOJBC AEOIKFNKAAP = 1498;
    AMFIFNOCDOF HLKKCAFGCIJ = 1540;
}

message GridFightConsumableUpdateInfo {
    uint32 round_cnt = 7;
    uint32 group_id = 15;
    uint32 num = 5;
    uint32 item_id = 9;
    int32 HFNNNGHBHGG = 10;
}

message GridFightCurrentInfo {
    GridFightGameData CAAGABEPPPE = 4;
    bool is_overlock = 6;
    uint32 division_id = 13;
    uint32 LJNGPCKPJLF = 8;
    repeated GridFightGameInfo NAGDJGMMCBE = 12;
    uint32 unique_id = 1;
    GridFightPendingAction FMIGOKIDKJL = 5;
    CLFABOEKMJI JLDDDLDNFEF = 14;
}

message GridFightCurrentTask {
    uint32 NLIDEKJOFMG = 10;
    uint32 progress = 5;
}

message GridFightDamageSttInfo {
    repeated KINJHHBJNJP APABPAFGCIA = 11;
    repeated PLFKMENCDMM EEGPILJDLBG = 12;
    repeated NFIDNDFHJGN JFCHLABGFJO = 7;
}

message GridFightEncounterInfo {
    uint32 IFIIOIIKJHO = 14;
    repeated PNAKHANCNGK monster_wave_list = 2;
    GridFightDropInfo BOAMLLHPNEC = 5;
    uint32 EPPHOFDAEMI = 13;
    uint32 CJADMFDOBAI = 4;
}

message GridFightEndBattleStageNotify {
    repeated GridFightHpModifyInfo HMKOKACNHJH = 2012;
    uint32 OAHFCPPIMLF = 1658;
    uint32 DMNILJEGICO = 12;
    bool CBHJKFNCDAD = 1;
    uint32 section_id = 7;
    uint32 CLFNPMGHMFC = 1629;
    uint32 ODJEBDNBLLC = 1659;
    uint32 OCCOHKIMGCN = 1709;
    uint32 OGLOCDMNNIM = 5;
    GEEMFDBDMDH AEOCOGHMEBG = 1858;
    uint32 DCAHJELNJNP = 13;
    uint32 JPKHBELGHCG = 10;
    GridFightDamageSttInfo NKBIDLBLONC = 6;
    uint32 EMOHLJHPOPC = 9;
    uint32 PAGPKOKMDBK = 157;
    map<uint32, GridFightDropInfo> AFFFCONCDMG = 2;
    uint32 HFLPDCJDIAC = 11;
    uint32 LKCJAPIGEND = 1173;
}

message GridFightEnterBattleStageCsReq {
}

message GridFightEnterBattleStageScRsp {
    SceneBattleInfo battle_info = 10;
    uint32 retcode = 7;
}

message GridFightEquipDressScRsp {
    uint32 PLDKENJLKME = 13;
}

enum GridFightEquipDressSource {
    GridFightEquipDressSource_KGridFightEquipDressSourceNone = 0;
    GridFightEquipDressSource_KGridFightEquipDressSourceManual = 1;
    GridFightEquipDressSource_KGridFightEquipDressSourceTrack = 2;
}

enum GridFightEquipTrackSource {
    GridFightEquipTrackSource_KGridFightEquipTrackSourceNone = 0;
    GridFightEquipTrackSource_KGridFightEquipTrackSourceRecommend = 1;
    GridFightEquipTrackSource_KGridFightEquipTrackSourceGuide = 2;
    GridFightEquipTrackSource_KGridFightEquipTrackSourceTraitEffect = 3;
}

message GridFightEquipmentInfo {
    uint32 unique_id = 11;
    uint32 grid_fight_equipment_id = 12;
    uint32 source = 3;
    map<uint32, uint32> convert_property_to_fixpoint = 15;
    bool IODIJBEHEGF = 14;
}

message GridFightForgeRoleActionInfo {
    repeated PGECGKEKFNC CKJAKKNOHEK = 5;
    uint32 LCLPEJHEAID = 6;
}

message GridFightGameAugmentAdd {
    GridGameAugmentInfo MCPIKEHDMND = 8;
}

message GridFightGameAugmentSync {
    repeated GridGameAugmentInfo sync_augment_info = 11;
}

message GridFightGameAugmentUpdate {
    GridGameAugmentInfo MCPIKEHDMND = 2;
}

message GridFightGameBasicInfo {
    string GBGOBPOOPGO = 1666;
    uint32 grid_fight_lineup_hp = 1;
    uint32 DNCOOFMDDAM = 14;
    string ANIBGAAIAHF = 1370;
    uint32 KNFOCCPOJEA = 5;
    uint32 NDAINFLOLPJ = 4;
    repeated RoleTrackEquipmentInfo MIIDIMOCPEB = 11;
    GridFightSyncCurrentTaskInfo BHJFJEEGGMC = 1692;
    uint32 PPKKHHNEOHB = 13;
    uint32 GDAKCOICIDA = 8;
    repeated uint32 ONHDKLIMLNM = 9;
    uint32 AFFCFLFIFPH = 15;
    uint32 MICEOJBAKGN = 12;
    uint32 EHNJDIDABHD = 7;
    repeated uint32 JCMCCGHFIAN = 2038;
    uint32 BEPMODICONA = 10;
    uint32 grid_fight_cur_level_exp = 6;
    uint32 JLOCMDIDPCI = 2;
    GMBMNFLMKPI GAJGBBFELEL = 1472;
    repeated uint32 FMEOHKHGMJM = 957;
    uint32 gold = 3;
}

message GridFightGameData {
    repeated GridFightGameItemInfo KLCKAOJAMNH = 8;
}

message GridFightGameInfo {
    GridFightGameBasicInfo FAOCFBOFCJP = 15;
    GridFightGameItemsInfo GCKLIONKMJC = 8;
    GridFightGameShopInfo EBHDIOGALIE = 12;
    GridFightLevelInfo KLCPAAHDPJF = 9;
    GridFightGameOrbInfo DBAGKJNPDOL = 13;
    GridFightGameAugmentSync LLDBOIANGDN = 5;
    GridFightGameTraitInfo OAHOAPCIDMK = 2;
    GridFightGameTeamInfo EJIPINIKNCK = 3;
    FIIJNPBFJBG KFBIEANENKJ = 7;
    MCNFDKKKABH CKLNMDAMJCB = 11;
}

message GridFightGameItemInfo {
    MJEICIEGAHF GBEAGMEAEPB = 8;
    uint32 unique_id = 5;
    LFOCLBEMIEM HAGAEFMEHBA = 1368;
    AKHEHAMBLEB FHKFMFKNMCH = 961;
    ONLFOIONDAF CHHEGLGPCCH = 1339;
    FBFBMMAAFCP IJAFFOCBKJI = 1638;
    KPKDJDEIKBM PDMOLEDAFIF = 1929;
    IPGCHDECCNB FCPGFBADIAL = 272;
    LHMLIGPHOKP LJBBFDMAEOH = 2026;
    HHNBCLPNDFI LFBGLMMDMCD = 512;
    FHBHIHJAOPB GLGPBLLICAG = 83;
    ELPPDAHKLBE DNLGBJLPDCE = 922;
    JEIEGMECGEN GNMCJEFJOKP = 1169;
    CNBHPJFFLEF PDHEDGGOPGL = 1395;
    HDOLIECDHAO BBGLCDJPLMF = 1004;
    OPJALEIKFAC EJEEHDPBHLI = 755;
    BJIGOFOAEPL EKLIOPIEKII = 698;
    FAFBDGCEAHD FKBIGANCEPD = 682;
    PIKKAEBHIKF NPHCPBDKLCH = 25;
    AGGDDAJLAEB CLFNPNNIFGE = 1227;
    FBDLJKEBPHM AOGFFCECKPK = 862;
    OHBLOLLNHIC CMBMNLHAECG = 786;
    ILDEFHMIDKP LBFBINFMGNF = 1538;
    FCABIGNMAPL FLELIBAJPEC = 453;
    GILMFECEBFE PNMLHBJOABC = 1315;
    DBFGKBNAKNH FBOLADPFLFL = 1496;
    KBEKJKNCMCL KPHBBLHOPHF = 1644;
    HCIFBGJCPDM OAJOEEODJAO = 859;
    HPMNCENLCAB KHNNNFBIAMA = 1150;
    KLIHJCNOEJP AMGAJDKLHFO = 1973;
    GFOMAIAIDFA PDADFOGABLJ = 626;
    PPBJJJMJOBN IBNBALOPKMM = 1965;
    IEOMGIBLHJB INDGPPMDFND = 1216;
    IEMINJAFCPM PKPFNHIKHON = 577;
    KPMOCBIIMHH NIOCABOLGLO = 781;
    CEHDAMJJFOE PGCBFHOPLEP = 48;
    BKIKOGNAECK KEHCIIEOLMD = 1962;
    HEHOBDGMMJM INHGPDPNILL = 751;
    GHMLCIMANAM BKAFGJDFMLF = 208;
    PIFMLFKCOOG GBHONNJKEHL = 610;
}

message GridFightGameItemSyncInfo {
    repeated GridFightEquipmentInfo grid_fight_equipment_list = 2;
    repeated GridFightConsumableUpdateInfo PFMDKHIDDLB = 9;
}

message GridFightGameItemsInfo {
    repeated GridFightEquipmentInfo grid_fight_equipment_list = 8;
    repeated GridFightConsumableInfo IPMKOMEHBMP = 12;
}

message GridFightGameOrbInfo {
    repeated PFBCBNMKFAK ODCMJGHEOMG = 1;
    repeated IBPDPCOGDEP MDKGCIKOMLI = 7;
}

message GridFightGamePortalBuffInfo {
    uint32 portal_buff_id = 14;
}

message GridFightGameShopInfo {
    repeated GridFightShopGoodsInfo OGDKJPDFFAI = 3;
    MONJNCPINKN ABBNGCPECAI = 4;
    repeated uint32 DLDJEOPKNMB = 1;
    uint32 NFGMOPCCPIC = 2;
    bool ABGEKPJHHIA = 6;
    uint32 OPDCMCFOFAA = 11;
}

message GridFightGameTeamInfo {
    repeated FPHPFJLAJDK KCOMPKMJCMC = 12;
    repeated GridGameRoleInfo grid_game_role_list = 13;
    repeated uint32 PLEIPHJGFIE = 5;
    repeated GridGameNpcInfo grid_game_npc_list = 9;
    repeated GridGameForgeItemInfo PMEOPPDAMLM = 2;
}

message GridFightGameTraitInfo {
    repeated IGKKILFFNJK DAOOOBLJOLB = 4;
    repeated GridGameTraitInfo grid_fight_trait_info = 1;
}

message GridFightGetArchiveCsReq {
    MLJIILDNDPL type = 11;
}

message GridFightGetArchiveScRsp {
    MLJIILDNDPL type = 11;
    uint32 retcode = 10;
    repeated GridFightArchiveData MCGGPONOCKC = 1;
}

message GridFightGetDataCsReq {
}

message GridFightGetDataScRsp {
    uint32 retcode = 5;
    GridFightCurrentInfo DHFOFLFCLAH = 15;
    GridFightSystemInfo LFLCDNGALME = 9;
}

message GridFightHandBookAugmentInfo {
    repeated uint32 JICIBCFDHIH = 1;
    repeated uint32 DDIFKADGIBO = 3;
}

message GridFightHandBookEquipInfo {
    repeated uint32 grid_fight_item_list = 1;
}

message GridFightHandBookInfo {
    GridFightHandBookMonsterInfo NIOAIKLPACM = 10;
    GridFightHandBookRoleInfo DNEGDNEBJMB = 6;
    GridFightHandBookAugmentInfo JLFANEOAHOC = 14;
    GridFightHandBookPortalInfo EJHDGLHCNLH = 13;
    GridFightHandBookEquipInfo PJBIPMKACOF = 4;
}

message GridFightHandBookMonsterInfo {
    repeated uint32 HEKMEJLMGFF = 7;
}

message GridFightHandBookPortalInfo {
    repeated uint32 NPHOIMEEDHM = 15;
    repeated uint32 DJJBKIGBGJA = 6;
}

message GridFightHandBookRoleInfo {
    repeated uint32 grid_fight_avatar_list = 13;
}

message GridFightHandlePendingActionCsReq {
    uint32 queue_position = 5;
    LAPOAFHDNCM MFFCPLBNHCF = 1822;
    EPLJJNHCJIF DCPHLHNLNKF = 1715;
    CJPOMFIDLOA IBCHMBNIPLK = 1849;
    GIOLAAKLDED DAJDBBEPMMA = 1475;
    GKLDOELMEIN PKHJLKNGCGH = 1295;
    OHAINOHGKCM BAKAKODKECM = 1323;
    NIDJPBLNDLH JLPOPEAJHMF = 1755;
    NNFPCAPDENH KEBDKGKEJDD = 1298;
    AJDFPFHBFJM NNDGEJFLGGF = 624;
    NEMAKFJPGDF LGNPHHBGKFH = 328;
    HMNMJKCHABE FIKAGBAEOAP = 835;
    DFMGEJCCBPD IACBCOBMGJB = 430;
    PDKGKIDCBKA HOKCPPPLJIO = 1395;
    DGILDLDMGEI EMMPHLKJAJN = 1586;
    PCCGPNAFMHP HHNPEHMBDKD = 1348;
    LFONAPFHAOB HHNHGJMOGDD = 394;
    FNNFHNKHIDD CFDIPFKBFJB = 1768;
    IDOJADMFGKF NFBJINKLLLK = 1319;
    EJEFKJGAKOO LAJGNNBOLDG = 1353;
    FKILNIGOKBF LFIDNOAECMN = 281;
    KCCPHHGCPMP IOHJGOENAPF = 162;
}

message GridFightHandlePendingActionScRsp {
    uint32 retcode = 15;
    uint32 queue_position = 9;
}

message GridFightHpModifyInfo {
    int32 ODJEBDNBLLC = 15;
    uint32 IOAOHNDEJNB = 7;
    uint32 EOBOFDOGDDM = 14;
    int32 BMMADDOCJOG = 11;
    GridFightUpdateGlobalHpReason reason = 5;
}

message GridFightLayerInfo {
    MDJBBILMHLC MPOBBIPMNNJ = 1388;
    bool LLOEBDLMLJO = 1;
}

message GridFightLevelInfo {
    GridFightLayerInfo IMPNAHBCADN = 6;
    uint32 EMOHLJHPOPC = 11;
    ACCMEOICEOD LHEBNOLNJHE = 4;
    uint32 DCAHJELNJNP = 8;
    uint32 section_id = 12;
    KGMCLFHAJNJ boss_info = 13;
    repeated GridFightGamePortalBuffInfo grid_fight_portal_buff_list = 1;
    repeated LHNCMINFONJ HEKMEJLMGFF = 2;
    repeated LAAMIAJFOMC CFFCNEDGCJJ = 15;
    GANGPHPGFCL COEBCNGCNOO = 14;
}

message GridFightLevelSyncInfo {
    uint32 DCAHJELNJNP = 15;
    GridFightLayerInfo IMPNAHBCADN = 5;
    uint32 section_id = 2;
}

enum GridFightLockReason {
    GridFightLockReason_NEELHDGILED = 0;
    GridFightLockReason_IDODGIKBBAE = 1;
    GridFightLockReason_NJJGBCMLNLI = 2;
    GridFightLockReason_AEINKINPAFL = 3;
}

enum GridFightLockType {
    GridFightLockType_EAJGHKNNJBB = 0;
    GridFightLockType_FHOHPFBDNOH = 6;
    GridFightLockType_GBDNJLPBNPO = 7;
    GridFightLockType_DAOBNJOGBBF = 8;
}

message GridFightOrbSyncInfo {
    uint32 LDBNOMPCOKK = 7;
    uint32 unique_id = 6;
}

message GridFightPendingAction {
    uint32 queue_position = 7;
    GridFightPortalBuffActionInfo MFFCPLBNHCF = 1918;
    GridFightAugmentActionInfo IBCHMBNIPLK = 2045;
    NGNKIIOHBAI PKHJLKNGCGH = 93;
    HNPHLAHJPOB BAKAKODKECM = 1886;
    LEGPFIAPLOO JLPOPEAJHMF = 1936;
    DPHPAKFLNOD NNDGEJFLGGF = 715;
    HJPDALHDJHC LGNPHHBGKFH = 1109;
    IAKEDFLIOFD FIKAGBAEOAP = 572;
    MHJIOJNNPDM HOKCPPPLJIO = 2018;
    GridFightRecommendEquipmentActionInfo HHNPEHMBDKD = 1657;
    GridFightForgeRoleActionInfo HHNHGJMOGDD = 1133;
    FKJMGFOPHHN CFDIPFKBFJB = 1540;
    GEIBJKJDOHO LAJGNNBOLDG = 1499;
    BJALEHOMFKH LFIDNOAECMN = 1097;
    CFFDCICDAKK IOHJGOENAPF = 1784;
}

message GridFightPendingAugmentInfo {
    uint32 KKIOBDHKPPK = 3;
    uint32 augment_id = 2;
    uint32 FEGDEOEHLFD = 12;
}

message GridFightPlayerLevelSyncInfo {
    uint32 level = 6;
    uint32 exp = 5;
    uint32 HFMKLAPEKFA = 7;
}

message GridFightPortalBuffActionInfo {
    uint32 DAEMEBCKHIK = 8;
    uint32 PLPJNCDKMAD = 6;
    uint32 GMLNOOHJCHM = 4;
    repeated uint32 NPHOIMEEDHM = 7;
}

message GridFightRecommendEquipmentActionInfo {
    repeated uint32 KBECJMLLCEJ = 3;
}

message GridFightRecycleRoleCsReq {
    uint32 unique_id = 13;
}

message GridFightRecycleRoleScRsp {
    uint32 retcode = 8;
}

message GridFightSeasonHandBookNotify {
    GridFightHandBookRoleInfo KBHGCCENEEC = 1068;
    GridFightHandBookEquipInfo LNLDBNIGODI = 124;
    GridFightHandBookAugmentInfo ODEJBBALEOA = 822;
    GridFightHandBookPortalInfo HLHCCONOKCL = 1135;
    GridFightHandBookMonsterInfo BNFHPKCIFCC = 1204;
}

message GridFightSectionRecordInfo {
    uint32 DCAHJELNJNP = 12;
    uint32 section_id = 5;
    uint32 node_type = 1;
    KEEPBBDICFN GFCEGEPFCDB = 1574;
}

message GridFightSettleNotify {
    uint32 KEJGCDOGEDD = 14;
    uint32 MNNKKEPCPPL = 1355;
    uint32 EDHKHJAPMKA = 12;
    OEDHMAHDECC BFLLJJBHLDF = 314;
    uint32 CDANKDNACJP = 2;
    uint32 CGKNDIJMOCJ = 1269;
    uint32 GEBGGMAGDJB = 5;
    uint32 FLHOPMMEGAI = 15;
    uint32 NMCKJPEMACM = 11;
}

enum GridFightSettleReason {
    GridFightSettleReason_AIBAFPBKDJI = 0;
    GridFightSettleReason_NOCIJDINKPJ = 1;
    GridFightSettleReason_HIGMFLKHGNJ = 2;
    GridFightSettleReason_JOJPGBCECLN = 3;
    GridFightSettleReason_NBPPJEDAIFN = 4;
}

message GridFightShopGoodsInfo {
    bool LHGIFDNPIDE = 5;
    uint32 KDKPDJNMMCM = 13;
    NJBGFHDPFNO BDPIMPJOJBK = 2036;
    ELJOHIOHPMJ LLIBLKCJEMI = 1091;
    CCKPBIKOIBB INBCCAIFHNL = 304;
}

message GridFightShopSyncInfo {
    uint32 OPDCMCFOFAA = 15;
    uint32 NFGMOPCCPIC = 14;
    repeated GridFightShopGoodsInfo OGDKJPDFFAI = 4;
    bool ABGEKPJHHIA = 2;
    MONJNCPINKN ABBNGCPECAI = 11;
}

message GridFightStaticGameInfo {
    GLIFOLCEMIN exp = 3;
    uint32 GDAKCOICIDA = 13;
    GridFightHandBookInfo NLENPEPIHAC = 1;
    uint32 division_id = 4;
    uint32 ADFEKPNIFOJ = 11;
    uint32 GEBGGMAGDJB = 6;
    uint32 GEGMHOMNBDG = 2;
    GridFightTalentInfo MHFHLBHFIBC = 12;
}

message GridFightSupplyRoleInfo {
    uint32 role_id = 3;
    repeated uint32 grid_fight_item_list = 4;
}

message GridFightSyncCurrentTaskInfo {
    GridFightCurrentTask ONPCDAELHGP = 10;
    repeated uint32 CAMMIIJDEKP = 14;
}

message GridFightSyncData {
    GridGameRoleInfo PIDDDHKPDDM = 919;
    GridGameRoleInfo CFOCDALNCBP = 1257;
    uint32 HFCBOIOAECK = 144;
    GridFightGameItemSyncInfo LMOLELDIKMA = 847;
    GridFightGameItemSyncInfo DDBKEOPKPFI = 1243;
    GridFightGameItemSyncInfo PENGEDECBNF = 688;
    uint32 item_value = 320;
    GridFightPlayerLevelSyncInfo PLPHEIBLPDL = 202;
    FMJDDIHBELC grid_fight_lineup_hp = 1283;
    uint32 BPCFDPNHIEL = 1234;
    GridFightShopSyncInfo MOFNIOJHBBL = 1938;
    GridFightPendingAction FMIGOKIDKJL = 587;
    MOENFCDKGMJ HPIIGHOELBH = 880;
    GridFightLevelSyncInfo OOICHLAMNIG = 1727;
    GridFightOrbSyncInfo AFILIPBHMOO = 640;
    GridFightSectionRecordInfo DMHMICHJBCB = 690;
    GridFightGameAugmentUpdate LEADDFOJFKD = 244;
    uint32 MDDKJGPJOAF = 665;
    uint32 PMFBIGLPJJA = 112;
    uint32 KNFOCCPOJEA = 1917;
    uint32 BEPMODICONA = 269;
    GridFightTraitSyncInfo HKHJJCMKKJE = 392;
    GridFightTraitTrackSyncInfo HGNDMOODNKF = 532;
    uint32 GDAKCOICIDA = 979;
    uint32 MICEOJBAKGN = 896;
    uint32 JLOCMDIDPCI = 761;
    uint32 DNCOOFMDDAM = 1617;
    GridFightDamageSttInfo NKBIDLBLONC = 1394;
    KEPIEGKPFIJ FGODNPLCECH = 1127;
    GridGameNpcInfo EJMDHDJCGDI = 129;
    GridGameNpcInfo DHLEOLKNAMI = 659;
    uint32 NJCEFEJBEOP = 267;
    GridGameForgeItemInfo OLCKALFILKK = 229;
    GridGameForgeItemInfo FEKCPKAPHHO = 1576;
    uint32 OACCGHIHLBA = 399;
    GridFightGameAugmentAdd EIKHFBCKIFA = 1524;
    MDKHMNKAECP BMGFDIKDOBE = 1604;
    GridFightGameItemInfo GOOCHGKBIPN = 92;
    uint32 GOHHJLAPMBB = 1253;
    uint32 DGEOHFLHAHI = 302;
    JPGKBLDLADF LDKDJAEJMPA = 910;
    GMBMNFLMKPI JOMFJHOCHJP = 140;
    uint32 KALKCJFFJIK = 946;
    FPHPFJLAJDK GOJINGMMAIL = 1750;
    FPHPFJLAJDK CPCJGHCGLIJ = 1850;
    uint32 DEKGKLGIDGI = 835;
    PFBCBNMKFAK AHMMHGHNHMI = 1560;
    uint32 OOAGJADOJNB = 1638;
    uint32 CDKJHJNFDIH = 813;
    uint32 LDPPDHGNCHL = 252;
    FADHEIGJENF HJMAEDKCONE = 395;
    GLPCEKMKLGG PPJFPNMIFHL = 32;
    uint32 LOGJNAICJPA = 1796;
    LAAMIAJFOMC MHFOELCFJGK = 1475;
    HOGJECBMFHD BKDDCFHELNB = 1186;
    HJCAJKHNCDH CKNDFNACIPO = 787;
}

message GridFightSyncUpdateResultScNotify {
    repeated ABPLALCHNFA GCPNIHHBGGD = 14;
}

message GridFightSystemInfo {
    CKPOBLIFMGN PKELAIPIHMF = 10;
    GridFightStaticGameInfo HFPEJIDDDJG = 1;
}

message GridFightTalentInfo {
    repeated uint32 BDGMNPIJDDL = 10;
}

message GridFightTraitEffectInfo {
    uint32 effect_id = 10;
    uint32 trait_core_role = 608;
    NBPEJFHIKJL avatar_core_info = 183;
    uint32 ECEMNCJBFOP = 1655;
    GridFightTraitElationEffectUpdate JLCLHAKNMLL = 1765;
    BJFLPMNPFFK MPHGIPCONLF = 1871;
    HJCFNEPJKDM KJFIOEPKOBM = 1694;
    LDMNIHIFDFG KOEPOCADLDI = 1166;
}

message GridFightTraitElationEffectUpdate {
    repeated FHCEIOHLADG POJGKJENENA = 7;
    uint32 DNNCAGJIOAP = 11;
    map<uint32, uint32> BANBECDCDHG = 8;
}

message GridFightTraitSyncInfo {
    uint32 trait_id = 5;
    bool is_recover = 8;
    GridFightTraitEffectInfo ENPLACDLJGA = 13;
}

message GridFightTraitTrackSyncInfo {
    bool GHJLDDEDJLI = 3;
    repeated uint32 ONHDKLIMLNM = 15;
}

message GridFightTraitUpdateCsReq {
    uint32 effect_id = 11;
    uint32 trait_id = 9;
    GPCFHMLMDHC FFBEPFLBHPL = 649;
    AFPJPEABFKH JLCLHAKNMLL = 773;
    MHKNPBJDFIC LFIDNOAECMN = 532;
}

message GridFightTraitUpdateScRsp {
    uint32 retcode = 6;
}

message GridFightUpdateEquipTrackCsReq {
    GridFightEquipTrackSource source = 7;
    repeated HLHHLIGPNOM DKEIDONNDCJ = 8;
}

enum GridFightUpdateGlobalHpReason {
    GridFightUpdateGlobalHpReason_KUpdateGlobalHpNone = 0;
    GridFightUpdateGlobalHpReason_KSubGlobalHpBaseCost = 1;
    GridFightUpdateGlobalHpReason_KSubGlobalHpExtraCost = 2;
    GridFightUpdateGlobalHpReason_KSubGlobalHpThresholdCost = 3;
    GridFightUpdateGlobalHpReason_KSubGlobalHpEffectCost = 4;
    GridFightUpdateGlobalHpReason_KSubGlobalHpAugment = 5;
    GridFightUpdateGlobalHpReason_KSubGlobalHpPrayQuest = 6;
    GridFightUpdateGlobalHpReason_KSubGlobalHpEquip = 7;
    GridFightUpdateGlobalHpReason_KAddGlobalHpTalent = 101;
    GridFightUpdateGlobalHpReason_KAddGlobalHpAugment = 102;
    GridFightUpdateGlobalHpReason_KAddGlobalHpFinalBattleTurn = 103;
    GridFightUpdateGlobalHpReason_KSetGlobalHpRevive = 201;
}

message GridFightUpdatePosCsReq {
    repeated MHEGMHKHAAD AAKDHMHCMLP = 15;
}

message GridFightUpdatePosScRsp {
    repeated MHEGMHKHAAD AAKDHMHCMLP = 5;
    uint32 retcode = 3;
}

enum GridFightUpdateSrcType {
    GridFightUpdateSrcType_KGridFightSrcNone = 0;
    GridFightUpdateSrcType_KGridFightSrcUseOrb = 1;
    GridFightUpdateSrcType_KGridFightSrcInitialSupplySelect = 2;
    GridFightUpdateSrcType_KGridFightSrcSelectPortalBuff = 3;
    GridFightUpdateSrcType_KGridFightSrcSelectAugment = 4;
    GridFightUpdateSrcType_KGridFightSrcTraitEffectUpdate = 5;
    GridFightUpdateSrcType_KGridFightSrcEnterNode = 6;
    GridFightUpdateSrcType_KGridFightSrcManualRefreshGoods = 7;
    GridFightUpdateSrcType_KGridFightSrcBuyGoods = 8;
    GridFightUpdateSrcType_KGridFightSrcMergeRole = 9;
    GridFightUpdateSrcType_KGridFightSrcAugment = 10;
    GridFightUpdateSrcType_KGridFightSrcPortalBuff = 11;
    GridFightUpdateSrcType_KGridFightSrcTalent = 12;
    GridFightUpdateSrcType_KGridFightSrcCraftEquip = 13;
    GridFightUpdateSrcType_KGridFightSrcDressEquip = 14;
    GridFightUpdateSrcType_KGridFightSrcAffix = 15;
    GridFightUpdateSrcType_KGridFightSrcUseForge = 16;
    GridFightUpdateSrcType_KGridFightSrcSelectSupply = 17;
    GridFightUpdateSrcType_KGridFightSrcBattleEnd = 18;
    GridFightUpdateSrcType_KGridFightSrcEliteBranchBattleBonus = 19;
    GridFightUpdateSrcType_KGridFightSrcCopyRole = 20;
    GridFightUpdateSrcType_KGridFightSrcDivision = 21;
    GridFightUpdateSrcType_KGridFightSrcSpecialGoods = 22;
    GridFightUpdateSrcType_KGridFightSrcEquipModifier = 23;
    GridFightUpdateSrcType_KGridFightSrcPreInitialSupplySelect = 24;
    GridFightUpdateSrcType_KGridFightSrcRecycleRole = 25;
    GridFightUpdateSrcType_KGridFightSrcUseConsumable = 26;
    GridFightUpdateSrcType_KGridFightSrcAddCrown = 27;
    GridFightUpdateSrcType_KGridFightSrcBuyExp = 28;
    GridFightUpdateSrcType_KGridFightSrcTraitEffectSelectEnhance = 29;
    GridFightUpdateSrcType_KGridFightSrcTutorial = 30;
    GridFightUpdateSrcType_KGridFightSrcActivityModule = 31;
    GridFightUpdateSrcType_KGridFightSrcPresent = 32;
    GridFightUpdateSrcType_KGridFightSrcSpecialCraftEquip = 33;
    GridFightUpdateSrcType_KGridFightSrcPrayQuest = 34;
    GridFightUpdateSrcType_KGridFightSrcPrayQuestAccept = 35;
    GridFightUpdateSrcType_KGridFightSrcPrayQuestFinish = 36;
}

message GridGameAugmentInfo {
    uint32 augment_id = 15;
    bool NEKJGIDPCAI = 6;
    bool AEKOKMPIFLN = 4;
}

message GridGameForgeItemInfo {
    uint32 unique_id = 1;
    uint32 LCLPEJHEAID = 12;
    repeated MBPDIPLJMKN CKJAKKNOHEK = 3;
    uint32 pos = 15;
}

message GridGameNpcInfo {
    uint32 pos = 4;
    uint32 id = 13;
    uint32 unique_id = 1;
    repeated uint32 PNJIPHJJONG = 9;
}

message GridGameRoleInfo {
    uint32 pos = 14;
    map<uint32, uint32> convert_property_to_fixpoint = 13;
    map<string, uint32> grid_fight_value_init_component = 15;
    uint32 unique_id = 5;
    uint32 role_star = 8;
    uint32 id = 4;
    repeated uint32 PNJIPHJJONG = 12;
}

message GridGameTraitInfo {
    uint32 CGIEODOGAIE = 11;
    uint32 layer = 4;
    repeated uint32 OLPPMEAMFFO = 1;
    repeated GridFightTraitEffectInfo trait_effect_list = 5;
    uint32 trait_id = 12;
    uint32 AFKKLDMAEDJ = 3;
}

message HCIFBGJCPDM {
}

message HDOLIECDHAO {
}

message HEHOBDGMMJM {
    uint32 trait_id = 6;
    repeated uint32 grid_fight_avatar_list = 12;
}

message HHNBCLPNDFI {
    repeated uint32 DIKFEBAJMEK = 4;
}

message HJCAJKHNCDH {
    AFCBKJEFKPG AIGPJLHBNEH = 4;
    AFCBKJEFKPG JNIOBAPDKLN = 2;
    uint32 MLAGBPIANKG = 5;
}

message HJCFNEPJKDM {
    repeated uint32 JMLAMKFMKON = 4;
}

message HJPDALHDJHC {
}

message HKOAOCKBBJA {
    uint32 dice_slot_id = 5;
}

message HLHHLIGPNOM {
    uint32 priority = 14;
    GridFightEquipTrackSource source = 15;
    repeated uint32 MCJMHBIECMN = 9;
    uint32 BGFFICLCKHE = 3;
    bool BJDOINAHDLN = 6;
    repeated uint32 grid_fight_item_list = 10;
}

message HMNMJKCHABE {
    repeated uint32 LOAFKKAFBOK = 10;
}

message HNPHLAHJPOB {
    uint32 PLPJNCDKMAD = 9;
    uint32 DAEMEBCKHIK = 6;
}

message HOGJECBMFHD {
    repeated IGKKILFFNJK DAOOOBLJOLB = 8;
}

message HPJKBFKAKJH {
    uint32 PEBCBLBLMPH = 15;
    uint32 MDNAGANGNKK = 1;
}

message HPMNCENLCAB {
    uint32 role_id = 2;
}

message IAABDBBJHOL {
    uint32 division_id = 5;
    bool is_overlock = 3;
    uint32 LJNGPCKPJLF = 9;
}

message IAKEDFLIOFD {
    uint32 IONLFBNMOFP = 8;
    uint32 JJPMDBCPJBA = 6;
    uint32 PLPJNCDKMAD = 9;
    uint32 DAEMEBCKHIK = 11;
    repeated GridFightSupplyRoleInfo MFBAKLCBPCJ = 2;
}

enum IBBDHFAEFNH {
    IBBDHFAEFNH_NLCDGIPGFDJ = 0;
    IBBDHFAEFNH_BMOOGBNPEAA = 1;
    IBBDHFAEFNH_CIHFGJDCHIA = 2;
    IBBDHFAEFNH_PJPFIHFAHGO = 3;
}

message IBPDPCOGDEP {
    uint32 LDBNOMPCOKK = 10;
    uint32 unique_id = 3;
}

message IDOJADMFGKF {
    uint32 ratio = 1;
}

message IEMINJAFCPM {
    repeated IFPAJBFOHLN ICDHAPACGEH = 2;
}

message IEOMGIBLHJB {
    uint32 NFFHCBDFABA = 14;
    uint32 IIJHFJFPIHK = 6;
}

message IFPAJBFOHLN {
    uint32 DCAHJELNJNP = 7;
    uint32 section_id = 8;
    uint32 role_id = 13;
}

message IGKKILFFNJK {
    repeated uint32 LEOCEFMKAEM = 2;
    uint32 BLAEAAFANBM = 15;
}

message ILCPGLAAADL {
}

message ILDEFHMIDKP {
    uint32 CKKDAEMFDPA = 14;
}

message IPGCHDECCNB {
    uint32 node_type = 5;
    uint32 CLBEEGLKMIM = 14;
    uint32 PIJBIFAIFOA = 13;
}

enum JDCAPBNPOOK {
    JDCAPBNPOOK_NLCDGIPGFDJ = 0;
    JDCAPBNPOOK_ENPLACDLJGA = 1;
    JDCAPBNPOOK_NMEEOHMGPKD = 2;
    JDCAPBNPOOK_OMKPENOHLII = 4;
    JDCAPBNPOOK_AOIGFLELHHH = 5;
    JDCAPBNPOOK_MCPIKEHDMND = 101;
    JDCAPBNPOOK_LDPMDPAGCHM = 102;
    JDCAPBNPOOK_EGCGFGDILBC = 103;
    JDCAPBNPOOK_HAEHIHOCLJD = 104;
    JDCAPBNPOOK_HCJBIBFBHKM = 105;
    JDCAPBNPOOK_MLOMHPFOMLO = 106;
    JDCAPBNPOOK_EDJGIJIILKE = 107;
    JDCAPBNPOOK_GGMPEGMEHPD = 108;
    JDCAPBNPOOK_FIFGENNKDBE = 109;
    JDCAPBNPOOK_ONPNOPLOAGH = 110;
    JDCAPBNPOOK_MDBHGMDBJGK = 111;
    JDCAPBNPOOK_DICKKDIAEND = 112;
    JDCAPBNPOOK_LKPOOOLNAJC = 113;
}

message JEIEGMECGEN {
    map<uint32, uint32> NADGHDJCHPI = 15;
}

message JKPOIHGIFFG {
    uint32 DCAHJELNJNP = 10;
    uint32 section_id = 1;
}

message JPGKBLDLADF {
    uint32 AOKPCNJJBAO = 10;
    GridFightCurrentTask KBBOAJPMNCN = 5;
    uint32 CEPEHNEOIOH = 13;
}

message KBEKJKNCMCL {
    repeated uint32 CAOADMAKKPM = 9;
}

message KCCPHHGCPMP {
    uint32 JLLFIDAMBCN = 8;
}

message KEEPBBDICFN {
    uint32 PDIAOLDMBLL = 3;
    uint32 LOGHLGKIFEN = 8;
}

message KEPIEGKPFIJ {
    uint32 MOADBALHMFD = 4;
}

message KGMCLFHAJNJ {
    repeated AHKDPCIIELA NCGHKPEMPDP = 1;
}

message KINJHHBJNJP {
    double damage = 15;
    uint32 trait_id = 8;
    uint32 layer = 12;
}

message KLIHJCNOEJP {
    uint32 IGOHOJEJIGP = 14;
    uint32 EEELJEKNNOG = 9;
    uint32 LLJLCCDDLNI = 8;
    uint32 NFBJINKLLLK = 12;
    repeated uint32 JPDCDKLEIBD = 10;
}

message KOIAMDKEFKH {
    GridFightEquipDressSource CPFCNOAJCGK = 6;
    uint32 MDNAGANGNKK = 13;
    uint32 PEBCBLBLMPH = 8;
}

message KPKDJDEIKBM {
    uint32 CJCOMKHDAGM = 3;
}

message KPMOCBIIMHH {
    uint32 role_id = 15;
    uint32 IEOGEFBLNEL = 6;
    uint32 MDNAGANGNKK = 10;
}

message LAAMIAJFOMC {
    bool PNJCLPNFIGA = 6;
    uint32 affix_id = 2;
}

message LAPOAFHDNCM {
    uint32 JCAPCNLJGFC = 6;
}

message LDMNIHIFDFG {
    uint32 BPJKHDNBPOE = 4;
}

message LEGPFIAPLOO {
    bool NKDEGMKKHPB = 6;
    uint32 trait_id = 1;
    repeated uint32 LAJLGHPLAAA = 15;
    repeated uint32 EGJDILDEAKP = 14;
    uint32 effect_id = 10;
}

message LFEFLIMJOGO {
}

message LFOCLBEMIEM {
    uint32 DCAHJELNJNP = 6;
    uint32 node_type = 11;
    uint32 ELPODIAAGEK = 4;
    uint32 section_id = 2;
}

message LFONAPFHAOB {
    uint32 PFIKCNFBGHE = 14;
}

message LHMLIGPHOKP {
    repeated uint32 DIKFEBAJMEK = 8;
}

message LHNCMINFONJ {
    uint32 LOGHLGKIFEN = 14;
}

message LKDMCPDHEGM {
}

message MBPDIPLJMKN {
    ELGLKEAPLGM GGMPEGMEHPD = 6;
}

message MCDBJHOCGHI {
    uint32 trait_id = 7;
    bool BJDOINAHDLN = 12;
}

message MCNFDKKKABH {
    repeated uint32 BHOBPPBBNIL = 7;
    repeated AFCBKJEFKPG IBBKKFGEEPH = 1;
}

message MDJBBILMHLC {
    repeated GridFightEncounterInfo BPDABHGFBFO = 1;
    uint32 LNDKCPBJDKH = 14;
    uint32 MOADBALHMFD = 9;
}

message MDKHMNKAECP {
    repeated RoleTrackEquipmentInfo MIIDIMOCPEB = 12;
}

message MHEGMHKHAAD {
    uint32 unique_id = 14;
    uint32 pos = 15;
}

message MHJIOJNNPDM {
    repeated uint32 KBECJMLLCEJ = 14;
}

message MHKNPBJDFIC {
    uint32 role_id = 10;
}

message MJEICIEGAHF {
    repeated uint32 OOEOCGLLHFO = 9;
    JDCAPBNPOOK JMNJLFACCLM = 2;
}

enum MLJIILDNDPL {
    MLJIILDNDPL_LAHJFEFDOBC = 0;
    MLJIILDNDPL_NJOBADDLBGK = 1;
    MLJIILDNDPL_FAGECPGMPEH = 2;
}

message MOENFCDKGMJ {
    uint32 portal_buff_id = 5;
}

message MOIONLDJGJI {
    uint32 item_id = 7;
    uint32 group_id = 8;
    GridFightConsumableTargetInfo param = 3;
}

message MONJNCPINKN {
    repeated BOPHDCKJMMN FIJPICNPKIG = 2;
}

message NBPEJFHIKJL {
    repeated uint32 OLPPMEAMFFO = 12;
}

message NDAMFDIDKGB {
    uint32 MOADBALHMFD = 6;
}

message NEMAKFJPGDF {
}

message NFIDNDFHJGN {
    uint32 augment_id = 8;
    double damage = 12;
    double KINKMHEAANP = 3;
}

message NFPLDMFCLHA {
    uint32 KDBMPKJKAKI = 8;
    uint32 level = 9;
    uint32 exp = 6;
}

message NGNKIIOHBAI {
    repeated uint32 OLPPMEAMFFO = 14;
    uint32 trait_id = 13;
    uint32 effect_id = 10;
}

message NIDJPBLNDLH {
    uint32 HAFOKMHCGFM = 14;
}

message NJBGFHDPFNO {
    uint32 role_id = 8;
    uint32 role_star = 7;
}

message NNFPCAPDENH {
}

message NOGLDANAKDO {
    uint32 FGCLPKIDGFK = 12;
}

message OCFPHHCOIHI {
}

message OCOONGAKCMI {
}

message OEBKLEPMMKE {
    uint32 unique_id = 14;
    uint32 PFIKCNFBGHE = 7;
}

message OEDHMAHDECC {
    GLPCEKMKLGG PPJFPNMIFHL = 1747;
    uint32 AKEGLJLCFPH = 515;
    repeated GridGameTraitInfo grid_fight_trait_info = 7;
    repeated KINJHHBJNJP APABPAFGCIA = 168;
    uint32 MBMJNEDIFFC = 84;
    bool is_overlock = 156;
    repeated GridGameAugmentInfo sync_augment_info = 5;
    repeated uint32 MHLBIBGKIOB = 374;
    KGMCLFHAJNJ boss_info = 59;
    repeated GridGameRoleInfo grid_game_role_list = 826;
    GOCIGPCDKDJ basic = 9;
    repeated FPHPFJLAJDK KCOMPKMJCMC = 1157;
    repeated uint32 HGAGKFEKBDA = 339;
    GridFightSettleReason reason = 2031;
    repeated NFIDNDFHJGN JFCHLABGFJO = 462;
    CLFABOEKMJI JLDDDLDNFEF = 482;
    repeated GridGameNpcInfo grid_game_npc_list = 1137;
    repeated GridFightEquipmentInfo grid_fight_equipment_list = 2014;
    repeated GridFightGamePortalBuffInfo OAIGAGABCMK = 8;
    repeated LAAMIAJFOMC CFFCNEDGCJJ = 1828;
    uint32 LLJJCOOKANH = 12;
    repeated PLFKMENCDMM EEGPILJDLBG = 4;
    bool DBODGPBOIHC = 1477;
}

message OHAINOHGKCM {
    uint32 MOADBALHMFD = 11;
}

message OHBLOLLNHIC {
    uint32 trait_id = 12;
    bool ANDIPJEDGMG = 10;
    uint32 HOHDOFKJJDJ = 1;
    uint32 role_id = 4;
}

message ONLFOIONDAF {
    uint32 JJNGGKPAKME = 7;
    uint32 interval = 10;
    bool JMCJKPPKAIF = 15;
    uint32 PNFOOPNCDCH = 8;
    int64 start_time = 5;
}

message OPJALEIKFAC {
}

message PAJHFEKAPMN {
    uint32 EGAPEGCKDFJ = 4;
}

message PCCGPNAFMHP {
    uint32 BCIGPPFMLJB = 9;
}

message PDKGKIDCBKA {
    uint32 BCIGPPFMLJB = 4;
}

message PFBCBNMKFAK {
    uint32 CMEHHMEEKPO = 6;
    uint32 DOJDFBENBEC = 2;
    uint32 unique_id = 13;
}

message PGECGKEKFNC {
    uint32 role_id = 11;
    uint32 LPFGIGJDLFM = 3;
}

message PHGFFOEJEBM {
    string EGCPAOEAGLF = 2;
    string PEOODHOAJMP = 15;
}

message PIFMLFKCOOG {
    uint32 MJGCDMOFALP = 2;
}

message PIKKAEBHIKF {
    uint32 PGEBCGLDNMN = 9;
}

message PLFKMENCDMM {
    bool DIGNECHKINI = 5;
    double total_damage = 10;
    bool OGIBPMBELKC = 1;
    uint32 role_star = 9;
    repeated uint32 grid_fight_equipment_list = 8;
    uint32 role_id = 2;
}

message PNAKHANCNGK {
    repeated AHKDPCIIELA PBLBBDBDLEK = 4;
    uint32 OCPEPEMNNEK = 9;
}

message PPBJJJMJOBN {
    uint32 BINKJCPGOAB = 8;
    uint32 BLAEAAFANBM = 4;
}

message RoleTrackEquipmentInfo {
    uint32 BGFFICLCKHE = 5;
    repeated uint32 MCJMHBIECMN = 13;
    GridFightEquipTrackSource source = 14;
    uint32 priority = 8;
    repeated uint32 grid_fight_item_list = 7;
}
