syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";
import "Orphans.proto";

enum CmdGachaType {
    CmdGachaType_None = 0;
    CmdGachaType_GetGachaCeilingCsReq = 1956;
    CmdGachaType_SetGachaDecideItemScRsp = 1999;
    CmdGachaType_ExchangeGachaCeilingScRsp = 1926;
    CmdGachaType_DoGachaScRsp = 1939;
    CmdGachaType_DoGachaCsReq = 1979;
    CmdGachaType_SetGachaDecideItemCsReq = 1973;
    CmdGachaType_GetGachaInfoScRsp = 1982;
    CmdGachaType_GetGachaCeilingScRsp = 1991;
    CmdGachaType_GetGachaInfoCsReq = 1934;
    CmdGachaType_ExchangeGachaCeilingCsReq = 1998;
    CmdGachaType_GachaDecideItemChangeScNotify = 1972;
}

message DoGachaCsReq {
    uint32 gacha_num = 3;
    uint32 simulate_magic = 7;
    uint32 gacha_random = 14;
    uint32 gacha_id = 8;
}

message DoGachaScRsp {
    uint32 gacha_id = 1;
    uint32 retcode = 4;
    repeated GachaItem gacha_item_list = 11;
    uint32 gacha_num = 15;
}

message EBNKDHCIJPH {
    uint32 KBOGFJANBPD = 11;
    uint32 ANPNFPJDPKP = 2;
    uint32 avatar_id = 12;
}

message ExchangeGachaCeilingCsReq {
    uint32 gacha_type = 4;
    uint32 avatar_id = 3;
}

message ExchangeGachaCeilingScRsp {
    GachaCeiling gacha_ceiling = 5;
    uint32 gacha_type = 10;
    uint32 retcode = 14;
    uint32 avatar_id = 8;
    ItemList transfer_item_list = 7;
}

message GachaCeiling {
    bool is_claimed = 4;
    repeated GachaCeilingAvatar avatar_list = 11;
    uint32 ceiling_num = 8;
}

message GachaCeilingAvatar {
    uint32 repeated_cnt = 7;
    uint32 avatar_id = 4;
}

message GachaInfo {
    int64 begin_time = 6;
    repeated uint32 item_detail_list = 3;
    int64 end_time = 10;
    uint32 GLLJFPENLHD = 8;
    string history_url = 7;
    repeated uint32 prize_item_list = 11;
    uint32 gacha_id = 4;
    string detail_url = 5;
    uint32 NHBBHEMPJJM = 14;
    uint32 MMELNCHIDNC = 2;
    GachaCeiling gacha_ceiling = 12;
    repeated uint32 ONIHOMCELJK = 15;
}

message GetGachaCeilingCsReq {
    uint32 gacha_type = 8;
}

message GetGachaCeilingScRsp {
    GachaCeiling gacha_ceiling = 1;
    uint32 retcode = 7;
    uint32 gacha_type = 14;
}

message GetGachaInfoCsReq {
}

message GetGachaInfoScRsp {
    uint32 retcode = 10;
    repeated GachaInfo gacha_info_list = 7;
    repeated NEIMLKNMDBM AKMDBPNEHDE = 14;
    uint32 gacha_random = 4;
    uint32 OGMPKDHKPAJ = 8;
    uint32 KKKNJDBNJPM = 5;
    uint32 GPNLDDLBOLM = 2;
}

message IGGFCPNDMPN {
    LJGKDEKCHPJ AONEJBHFKMO = 2;
    uint32 BKJFBHANFLC = 4;
}

message LJGKDEKCHPJ {
    uint32 MMONAECCLHN = 8;
    uint32 avatar_id = 9;
    uint32 MGBCAPIIKLM = 3;
}

message NEIMLKNMDBM {
    uint32 GFANBHAEKOK = 8;
    repeated uint32 OJNEFBJHCCK = 2;
    repeated uint32 EJGNMCAMELA = 11;
    uint32 MMELNCHIDNC = 1;
}

message SetGachaDecideItemCsReq {
    uint32 gacha_id = 10;
    uint32 GFANBHAEKOK = 7;
    repeated uint32 OJNEFBJHCCK = 6;
}

message SetGachaDecideItemScRsp {
    uint32 retcode = 9;
    NEIMLKNMDBM NBLOJLDLBEB = 15;
}
