syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AFEDHCKDDFA {
    bool AAGAFBJHOKK = 3;
    NAOCMAOJECF type = 9;
    uint32 id = 10;
}

message ANHJKLLEKKB {
    int32 value = 13;
    uint32 type = 5;
}

message BNJAIHINJIK {
    GEFEDOAOKNO IPDLBJHAJOO = 2;
    uint32 OBGKOOAPCEM = 4;
    uint32 ODPELJAIPHL = 14;
    HINIJKGDDBI FBECMPGLPKK = 10;
    PJOHABIOPPI GMMPIDODKKD = 7;
    uint32 GNAHDKMEDEP = 6;
}

enum CmdHipplenType {
    CmdHipplenType_None = 0;
    CmdHipplenType_GetHipplenInheritScRsp = 9024;
    CmdHipplenType_SetHipplenOutfitCsReq = 9019;
    CmdHipplenType_HipplenCycleResultScNotify = 9038;
    CmdHipplenType_TakeHipplenEndingRewardCsReq = 9042;
    CmdHipplenType_SettleHipplenWorkCsReq = 9032;
    CmdHipplenType_SettleHipplenWorkScRsp = 9037;
    CmdHipplenType_SetHipplenOutfitScRsp = 9012;
    CmdHipplenType_GetHipplenDataCsReq = 9036;
    CmdHipplenType_HipplenAgendaResultScNotify = 9020;
    CmdHipplenType_HipplenChangeScNotify = 9025;
    CmdHipplenType_OpenHipplenCycleCsReq = 9021;
    CmdHipplenType_SetHipplenAgendaScRsp = 9022;
    CmdHipplenType_OpenHipplenCycleScRsp = 9017;
    CmdHipplenType_GetHipplenDataScRsp = 9029;
    CmdHipplenType_GetHipplenInheritCsReq = 9044;
    CmdHipplenType_TakeHipplenEndingRewardScRsp = 9018;
    CmdHipplenType_HipplenTraitUnlockScNotify = 9014;
    CmdHipplenType_SetHipplenAgendaCsReq = 9008;
}

message DMLACLLDCCE {
    uint32 GNAHDKMEDEP = 12;
    int32 CBPGJAFAHFC = 2;
    uint32 MNCFOGJECMF = 3;
    uint32 AJAFEEAOBLC = 9;
}

message DPGGADJHCBG {
    uint32 IMIBAAPJGEJ = 13;
}

message ELOFLNEAHPD {
    repeated uint32 grid_fight_trait_info = 3;
    repeated ENIDJAFECBD BPFJDLHFEKG = 9;
}

message ENIDJAFECBD {
    bool is_taken_reward = 9;
    uint32 BKFICFMMGIN = 13;
}

message FCOBIMJMLIF {
    uint32 value = 6;
    uint32 type = 11;
}

message FEDNIHCAHGP {
    repeated uint32 GEMHKFCFCCC = 3;
    repeated uint32 FCOKODHGEKO = 8;
}

message GCNJGJMPLHM {
}

message GEFEDOAOKNO {
    repeated FCOBIMJMLIF MONKDLNMMBK = 9;
}

message GetHipplenDataCsReq {
}

message GetHipplenDataScRsp {
    uint32 JFLAEGMBMAK = 1;
    ELOFLNEAHPD ACOLLHOFKGL = 10;
    bool HPKECDINMCE = 11;
    BNJAIHINJIK HIGHKDBJNIM = 15;
    FEDNIHCAHGP KJDEEJNBLHK = 4;
    uint32 retcode = 9;
}

message GetHipplenInheritCsReq {
}

message GetHipplenInheritScRsp {
    repeated uint32 grid_fight_trait_info = 11;
    uint32 retcode = 5;
}

message HBMGNLFKMMK {
    uint32 MNCFOGJECMF = 6;
}

message HGDHJFGCEJF {
    DPGGADJHCBG MDFCELGPPHM = 1;
    NOPCFDDLPNN HNLMBGIBEBN = 15;
}

message HINIJKGDDBI {
    repeated uint32 grid_fight_trait_info = 7;
}

message HipplenAgendaResultScNotify {
    GEFEDOAOKNO JMKHOIMEFFM = 1;
    repeated uint32 GPDEDJIHMGB = 15;
    bool CPFFAGAHJMH = 14;
    LKFFMLJMGOB FEJPEALIKHE = 11;
    BNJAIHINJIK HIGHKDBJNIM = 9;
    repeated AFEDHCKDDFA NEMFNENACNB = 12;
    repeated uint32 grid_fight_trait_info = 5;
}

message HipplenChangeScNotify {
    repeated HGDHJFGCEJF DGNGMJMPFGK = 11;
}

message HipplenCycleResultScNotify {
    repeated JHBOOCGAKCM IHLCDDOMPKD = 1;
    repeated uint32 grid_fight_trait_info = 12;
    GEFEDOAOKNO GNBKDCHLDGL = 14;
    repeated uint32 FCOKODHGEKO = 4;
    repeated JHBOOCGAKCM FJFJMOGILBM = 2;
    uint32 JFLAEGMBMAK = 7;
    uint32 BKFICFMMGIN = 11;
}

message HipplenTraitUnlockScNotify {
    repeated uint32 grid_fight_trait_info = 6;
}

message JHBOOCGAKCM {
    uint32 LDMHLKGILOD = 2;
    uint32 FFKDFODDBDN = 10;
}

message LKFFMLJMGOB {
    int32 CBPGJAFAHFC = 7;
    uint32 AJAFEEAOBLC = 10;
    uint32 MNCFOGJECMF = 15;
}

message LODMLDKMPPL {
    uint32 id = 12;
}

enum NAOCMAOJECF {
    NAOCMAOJECF_NLCDGIPGFDJ = 0;
    NAOCMAOJECF_CNMBIADBFNG = 1;
    NAOCMAOJECF_ENCBGPOIFCM = 2;
    NAOCMAOJECF_ECKIMBNDOME = 3;
    NAOCMAOJECF_LONKNKFDPII = 4;
    NAOCMAOJECF_MLLNOGKNHNL = 5;
}

message NOPCFDDLPNN {
    uint32 BKFICFMMGIN = 8;
}

message OHHHCKCFPIG {
    repeated uint32 DPOKBJGLKNN = 10;
}

message OpenHipplenCycleCsReq {
    uint32 trait_id = 15;
}

message OpenHipplenCycleScRsp {
    BNJAIHINJIK HIGHKDBJNIM = 7;
    uint32 retcode = 14;
    uint32 JFLAEGMBMAK = 12;
}

message PJOHABIOPPI {
    uint32 MBHJONMGDOO = 7;
    uint32 DOHNBOCBOGJ = 4;
    AFEDHCKDDFA LAJOGEKPHOP = 5;
    repeated uint32 OGDLPFOJMHI = 13;
    repeated AFEDHCKDDFA NEMFNENACNB = 15;
    uint32 JEEELNEHDCD = 12;
}

message SetHipplenAgendaScRsp {
    repeated AFEDHCKDDFA NEMFNENACNB = 1;
    uint32 retcode = 5;
}

message SetHipplenOutfitCsReq {
    uint32 IMIBAAPJGEJ = 12;
}

message SetHipplenOutfitScRsp {
    repeated uint32 GEMHKFCFCCC = 5;
    uint32 retcode = 13;
}

message SettleHipplenWorkCsReq {
    HBMGNLFKMMK HBGCOIAGDIG = 11;
    LODMLDKMPPL ENCBGPOIFCM = 3;
    OHHHCKCFPIG ECKIMBNDOME = 2;
    GCNJGJMPLHM MLLNOGKNHNL = 9;
}

message SettleHipplenWorkScRsp {
    uint32 retcode = 10;
    GEFEDOAOKNO IPDLBJHAJOO = 13;
    repeated ANHJKLLEKKB BNIFMIPPIMA = 3;
    DMLACLLDCCE HBGCOIAGDIG = 8;
    LKFFMLJMGOB LONKNKFDPII = 6;
    repeated AFEDHCKDDFA NEMFNENACNB = 4;
}

message TakeHipplenEndingRewardCsReq {
    uint32 BKFICFMMGIN = 4;
}

message TakeHipplenEndingRewardScRsp {
    ItemList reward_list = 13;
    uint32 retcode = 8;
    uint32 BKFICFMMGIN = 15;
}
