syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message ANAJELDHDBH {
    double damage = 1;
    uint32 key = 9;
}

message APKJENOJIFD {
}

message BABFMGPNOIG {
    uint32 KJJJPMAPFOH = 11;
    uint32 chapter_index = 7;
}

message BBABPMLDJMM {
}

message BIJEDLPINKH {
}

message BIKNPJPLDAO {
    repeated ANAJELDHDBH HFHJGBHHBKM = 13;
    repeated ANAJELDHDBH FNHDDAMNKCG = 4;
    uint32 OBKCFGAJLJJ = 3;
    uint32 MBOBGNPLLOO = 14;
    double total_damage = 11;
}

message BKDANKLCAHC {
}

enum CmdIdleLiveType {
    CmdIdleLiveType_None = 0;
    CmdIdleLiveType_IdleLiveReplaceTeamScRsp = 9412;
    CmdIdleLiveType_IdleLiveGetPendingEquipScRsp = 9365;
    CmdIdleLiveType_IdleLiveGetStatisticsScRsp = 9359;
    CmdIdleLiveType_IdleLiveFinishNodeEventScRsp = 9449;
    CmdIdleLiveType_IdleLiveFinishQuestionScRsp = 9424;
    CmdIdleLiveType_IdleLiveTakeQuestEquipCsReq = 9397;
    CmdIdleLiveType_IdleLiveDressSpecialEquipCsReq = 9391;
    CmdIdleLiveType_IdleLiveTakeContentRewardCsReq = 9393;
    CmdIdleLiveType_IdleLiveTakeAssistRewardCsReq = 9361;
    CmdIdleLiveType_IdleLiveStartNodeScRsp = 9389;
    CmdIdleLiveType_IdleLiveUpdateCustomInfoScRsp = 9369;
    CmdIdleLiveType_IdleLiveCollectIncomeCsReq = 9399;
    CmdIdleLiveType_IdleLiveStartDungeonCsReq = 9433;
    CmdIdleLiveType_IdleLiveFinishNodeBattleCsReq = 9448;
    CmdIdleLiveType_IdleLiveGetFriendDungeonInfoCsReq = 9413;
    CmdIdleLiveType_IdleLiveSyncChangeScNotify = 9374;
    CmdIdleLiveType_IdleLiveTakeTaskRewardCsReq = 9364;
    CmdIdleLiveType_IdleLiveDoGachaScRsp = 9358;
    CmdIdleLiveType_IdleLiveTechTreeChangeNodeStateScRsp = 9394;
    CmdIdleLiveType_IdleLiveGetDataCsReq = 9384;
    CmdIdleLiveType_IdleLiveEndDungeonCsReq = 9425;
    CmdIdleLiveType_IdleLiveHandlePendingEquipCsReq = 9407;
    CmdIdleLiveType_IdleLiveUpgradeTeamSlotScRsp = 9370;
    CmdIdleLiveType_IdleLiveUpgradeTeamSlotCsReq = 9428;
    CmdIdleLiveType_IdleLiveTechTreeChangeNodeStateCsReq = 9373;
    CmdIdleLiveType_IdleLiveStartNodeBattleScRsp = 9441;
    CmdIdleLiveType_IdleLiveReplaceTeamCsReq = 9354;
    CmdIdleLiveType_IdleLiveTakeTaskRewardScRsp = 9355;
    CmdIdleLiveType_IdleLiveStartDungeonScRsp = 9405;
    CmdIdleLiveType_IdleLiveNewAssistRewardScNotify = 9419;
    CmdIdleLiveType_IdleLiveStartNodeCsReq = 9429;
    CmdIdleLiveType_IdleLiveHandlePendingEquipScRsp = 9396;
    CmdIdleLiveType_IdleLiveGetFriendDungeonInfoScRsp = 9378;
    CmdIdleLiveType_IdleLiveFinishChapterFinalActCsReq = 9422;
    CmdIdleLiveType_IdleLiveOpenChestCsReq = 9414;
    CmdIdleLiveType_IdleLiveCollectIncomeScRsp = 9398;
    CmdIdleLiveType_IdleLiveFinishNodeEventCsReq = 9423;
    CmdIdleLiveType_IdleLiveFinishNodeBattleScRsp = 9376;
    CmdIdleLiveType_IdleLiveStartNodeBattleCsReq = 9406;
    CmdIdleLiveType_IdleLiveDoGachaCsReq = 9351;
    CmdIdleLiveType_IdleLiveOpenChestScRsp = 9431;
    CmdIdleLiveType_IdleLiveTakeQuestEquipScRsp = 9385;
    CmdIdleLiveType_IdleLiveGetPendingEquipCsReq = 9438;
    CmdIdleLiveType_IdleLiveGetDataScRsp = 9432;
    CmdIdleLiveType_IdleLiveTakeContentRewardScRsp = 9390;
    CmdIdleLiveType_IdleLiveTakeAssistRewardScRsp = 9437;
    CmdIdleLiveType_IdleLiveDressSpecialEquipScRsp = 9388;
    CmdIdleLiveType_IdleLiveFinishQuestionCsReq = 9383;
    CmdIdleLiveType_IdleLiveFinishChapterFinalActScRsp = 9415;
    CmdIdleLiveType_IdleLiveGetStatisticsCsReq = 9416;
    CmdIdleLiveType_IdleLiveEndDungeonScRsp = 9352;
    CmdIdleLiveType_IdleLiveUpdateCustomInfoCsReq = 9418;
}

message DDNJIHCBDDE {
}

message DMEPOENPEIF {
    uint32 PJODECIGFOI = 6;
}

message EAILAPHKBNO {
    bool PGOIJMGMDEO = 6;
}

message FOMCONFODHH {
    JDGNMIDMACL GBJEALNCMJC = 7;
    BIKNPJPLDAO HNMLBLGGOLB = 11;
}

message FinishQuestionCsReq {
    uint32 CJAINJMLDFC = 15;
    uint32 PDICFEGEPNM = 7;
    uint32 JMBGMIPLLJI = 5;
    bool DJNDDEBIMGA = 2;
}

message GAIANGFBBPG {
    uint32 LOFNHPHCCIL = 9;
    bool ECBJLAKHOCF = 5;
}

message HGDEGLENMPM {
}

message HMPGPHLEJKF {
}

message IABBGPLBLML {
    uint32 JGFLMODLDCD = 3;
}

enum JDGNMIDMACL {
    JDGNMIDMACL_GAIFBJCKGPA = 0;
    JDGNMIDMACL_KGPGDEMEAND = 1;
    JDGNMIDMACL_BPKLGJOBOMA = 2;
    JDGNMIDMACL_IAAOAHFDFLC = 3;
}

message KKGJPMCFDON {
    uint32 gacha_count = 14;
}

enum LPPKGHJGOCC {
    LPPKGHJGOCC_NLCDGIPGFDJ = 0;
    LPPKGHJGOCC_CAJPAGKBBML = 1;
    LPPKGHJGOCC_JOKPPELAFOI = 2;
}

enum OEDABANAJEK {
    OEDABANAJEK_NLCDGIPGFDJ = 0;
    OEDABANAJEK_BPNMABIFCAC = 1;
    OEDABANAJEK_OHLJJBCALBF = 2;
}

message PDMEKAGOCND {
}

message TakeContentCsReq {
    uint32 content_id = 15;
    LPPKGHJGOCC content_type = 7;
}

message TakeQuestEquipCsCsReq {
    bool DKPCAIGPHNO = 6;
    uint32 quest_id = 13;
}

message TechTreeChangeNodeStateCsCsReq {
    OEDABANAJEK op_type = 1;
    uint32 CDMFHNGEFCN = 11;
}

message UpdateCustomInfoCsReq {
    string title = 12;
    uint32 AJIMPLLIFIE = 14;
}

message UpgradeTeamSlotCsCsReq {
    uint32 JIGOOAEFDPP = 12;
    uint32 level = 6;
}
