syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AMPMJPCFLND {
    TurnFoodSwitch KLAJGAKAFCP = 15;
    bool is_open = 13;
}

message AddRelicFilterPlanCsReq {
    string name = 3;
    bool is_marked = 2;
    KJDLIPEIAAK icon = 9;
    uint32 GFEENEDNJGF = 6;
    BNAILMNNGIF settings = 8;
}

message AddRelicFilterPlanScRsp {
    GABKFNAJIDD relic_plan = 8;
    uint32 retcode = 1;
}

message BKGPJOBNMKJ {
    uint64 expire_time = 3;
    uint32 tid = 1;
    uint32 num = 7;
}

message BNAILMNNGIF {
    uint32 AGPFHDNOBEN = 1;
    repeated uint32 DCFGIEJAILL = 2;
    repeated uint32 KLKADPNPNHI = 3;
    repeated uint32 NBINKKOFKED = 4;
    repeated uint32 PLJEJGCEKGL = 5;
    repeated uint32 HBLKPAJPPEC = 6;
    bool IHABNJLBNBL = 7;
    uint32 MNNLNOJNPBP = 8;
    repeated uint32 BOPGCJOMKGE = 9;
    repeated uint32 CLNIFBCKJPE = 10;
    repeated uint32 MPBDKLFAPCH = 11;
}

message BatchRankUpEquipmentCsReq {
    repeated FBNBEIKABGE switch_list = 11;
}

message CancelMarkItemNotify {
    uint32 item_id = 15;
}

enum CmdItemType {
    CmdItemType_None = 0;
    CmdItemType_UseItemScRsp = 526;
    CmdItemType_DestroyItemScRsp = 523;
    CmdItemType_GetRecyleTimeCsReq = 566;
    CmdItemType_ComposeItemCsReq = 580;
    CmdItemType_DeleteRelicFilterPlanScRsp = 568;
    CmdItemType_MarkItemCsReq = 508;
    CmdItemType_RankUpEquipmentScRsp = 599;
    CmdItemType_GetRelicFilterPlanScRsp = 587;
    CmdItemType_ComposeLimitNumUpdateNotify = 514;
    CmdItemType_MarkRelicFilterPlanScRsp = 533;
    CmdItemType_BatchRankUpEquipmentScRsp = 592;
    CmdItemType_UseItemCsReq = 598;
    CmdItemType_LockEquipmentScRsp = 591;
    CmdItemType_LockRelicCsReq = 549;
    CmdItemType_ExpUpEquipmentCsReq = 572;
    CmdItemType_RelicReforgeScRsp = 528;
    CmdItemType_GetRelicFilterPlanCsReq = 511;
    CmdItemType_SetTurnFoodSwitchCsReq = 540;
    CmdItemType_MarkItemScRsp = 558;
    CmdItemType_AddRelicFilterPlanCsReq = 569;
    CmdItemType_ExpUpEquipmentScRsp = 565;
    CmdItemType_ExpUpRelicScRsp = 562;
    CmdItemType_GetMarkItemListCsReq = 544;
    CmdItemType_RelicReforgeCsReq = 563;
    CmdItemType_DiscardRelicCsReq = 575;
    CmdItemType_LockEquipmentCsReq = 556;
    CmdItemType_GetBagCsReq = 534;
    CmdItemType_ModifyRelicFilterPlanCsReq = 535;
    CmdItemType_ComposeSelectedRelicCsReq = 538;
    CmdItemType_AddRelicFilterPlanScRsp = 547;
    CmdItemType_GetBagScRsp = 582;
    CmdItemType_LockRelicScRsp = 548;
    CmdItemType_RankUpEquipmentCsReq = 573;
    CmdItemType_RechargeSuccNotify = 564;
    CmdItemType_RelicFilterPlanClearNameScNotify = 574;
    CmdItemType_CancelMarkItemNotify = 521;
    CmdItemType_PromoteEquipmentScRsp = 539;
    CmdItemType_ExchangeHcoinCsReq = 581;
    CmdItemType_ComposeLimitNumCompleteNotify = 524;
    CmdItemType_GetRecyleTimeScRsp = 509;
    CmdItemType_ModifyRelicFilterPlanScRsp = 578;
    CmdItemType_RelicReforgeConfirmCsReq = 585;
    CmdItemType_DiscardRelicScRsp = 502;
    CmdItemType_ExpUpRelicCsReq = 504;
    CmdItemType_SetTurnFoodSwitchScRsp = 583;
    CmdItemType_ComposeSelectedRelicScRsp = 557;
    CmdItemType_SellItemScRsp = 515;
    CmdItemType_GeneralVirtualItemDataNotify = 555;
    CmdItemType_EquipmentQuickUpCsReq = 586;
    CmdItemType_SellItemCsReq = 588;
    CmdItemType_ExchangeHcoinScRsp = 541;
    CmdItemType_MarkRelicFilterPlanCsReq = 519;
    CmdItemType_DeleteRelicFilterPlanCsReq = 520;
    CmdItemType_AddEquipmentScNotify = 546;
    CmdItemType_EquipmentQuickUpScRsp = 596;
    CmdItemType_BatchRankUpEquipmentCsReq = 516;
    CmdItemType_PromoteEquipmentCsReq = 579;
    CmdItemType_SyncTurnFoodNotify = 543;
    CmdItemType_ComposeItemScRsp = 571;
    CmdItemType_RelicReforgeConfirmScRsp = 525;
    CmdItemType_DestroyItemCsReq = 505;
    CmdItemType_GetMarkItemListScRsp = 501;
}

message ComposeItemCsReq {
    ItemCostData compose_item_list = 7;
    uint32 count = 5;
    ItemCostData convert_item_list = 3;
    uint32 compose_id = 4;
}

message ComposeItemScRsp {
    uint32 count = 1;
    uint32 retcode = 4;
    uint32 compose_id = 15;
    ItemList return_item_list = 3;
}

message ComposeSelectedRelicCsReq {
    ItemCostData wr_item_list = 6;
    uint32 count = 9;
    ItemCostData compose_item_list = 14;
    uint32 compose_relic_id = 2;
    uint32 main_affix_id = 12;
    uint32 compose_id = 3;
    repeated uint32 sub_affix_id_list = 8;
}

message ComposeSelectedRelicScRsp {
    uint32 compose_id = 13;
    uint32 retcode = 5;
    ItemList return_item_list = 11;
}

message DestroyItemCsReq {
    uint32 item_count = 4;
    uint32 item_id = 6;
    uint32 ADOIMNBAGKC = 12;
}

message DestroyItemScRsp {
    uint32 ADOIMNBAGKC = 4;
    uint32 retcode = 7;
}

message DiscardRelicCsReq {
    uint64 KDGCPMGOPPJ = 11;
    repeated uint32 relic_ids = 2;
    bool DKPCAIGPHNO = 3;
    RelicDiscardType IFEEJKMACHF = 5;
}

message DiscardRelicScRsp {
    repeated uint32 relic_ids = 7;
    bool DKPCAIGPHNO = 6;
    uint32 retcode = 3;
    RelicDiscardType IFEEJKMACHF = 9;
}

message EquipmentQuickUpCsReq {
    uint32 equipment_unique_id = 6;
    ItemCostData BOBOKJBAMNB = 13;
    uint32 IGOOJKMPMDC = 5;
    ItemCostData IDGEEENIMMK = 10;
    uint32 KLMIBJIKIBB = 4;
}

message ExchangeHcoinCsReq {
    uint32 num = 8;
}

message ExchangeHcoinScRsp {
    uint32 num = 5;
    uint32 retcode = 7;
}

message ExpUpEquipmentCsReq {
    ItemCostData cost_data = 11;
    uint32 equipment_unique_id = 3;
}

message ExpUpEquipmentScRsp {
    repeated PileItem return_item_list = 14;
    uint32 retcode = 3;
}

message ExpUpRelicCsReq {
    ItemCostData cost_data = 10;
    uint32 relic_unique_id = 1;
}

message ExpUpRelicScRsp {
    uint32 retcode = 10;
    repeated PileItem return_item_list = 13;
}

message FBNBEIKABGE {
    uint32 equipment_unique_id = 3;
    ItemCostData cost_data = 5;
}

message GABKFNAJIDD {
    string name = 6;
    BNAILMNNGIF settings = 12;
    uint32 NPHAJEKCBKF = 10;
    int64 BNCALAMGIOC = 5;
    bool is_marked = 11;
    KJDLIPEIAAK icon = 7;
    uint32 GFEENEDNJGF = 14;
}

message GeneralVirtualItemDataNotify {
    repeated PileItem FCNBHBHMFMC = 10;
    bool EBLPGLFJNEL = 7;
}

message GetBagCsReq {
}

message GetBagScRsp {
    repeated OCKCHBDFGNL FFEGBHJLBNH = 14;
    repeated WaitDelResource wait_del_resource_list = 11;
    repeated TurnFoodSwitch EOJBFLHBNMB = 15;
    repeated uint32 CAMEGAGKPGL = 5;
    repeated uint32 HGGGFLABDLB = 3;
    repeated BKGPJOBNMKJ NAJFMIIFIEC = 10;
    repeated Material material_list = 12;
    repeated BKGPJOBNMKJ CNDODPICGHI = 7;
    repeated Equipment equipment_list = 13;
    repeated uint32 KOFNOJCMEFA = 9;
    repeated Relic relic_list = 8;
    repeated PileItem PLBLHEKEIJO = 4;
    repeated NLLLAAEJOBP update_platform_bound_gifts_list = 1650;
    uint32 retcode = 1;
}

message GetMarkItemListCsReq {
}

message GetMarkItemListScRsp {
    repeated uint32 PEPKCBILIFO = 8;
    uint32 retcode = 11;
}

message GetRecyleTimeScRsp {
    repeated BKGPJOBNMKJ NAJFMIIFIEC = 9;
    uint32 retcode = 11;
}

message GetRelicFilterPlanCsReq {
}

message GetRelicFilterPlanScRsp {
    uint32 retcode = 2;
    repeated GABKFNAJIDD JCKBEEKBPHF = 6;
}

message KJDLIPEIAAK {
    bool IFONLBKJGFE = 14;
    uint32 OLELCDKLPDK = 9;
}

message LockEquipmentCsReq {
    bool is_locked = 11;
    repeated uint32 LDBMBPBGFHK = 4;
}

message LockEquipmentScRsp {
    uint32 retcode = 13;
}

message LockRelicCsReq {
    repeated uint32 relic_ids = 10;
    bool NPPKABBJCMI = 6;
    bool is_locked = 9;
}

message LockRelicScRsp {
    uint32 retcode = 12;
}

message MarkItemCsReq {
    uint32 item_id = 13;
    bool ABDJKPCGDHO = 10;
}

message MarkItemScRsp {
    uint32 retcode = 8;
    uint32 item_id = 4;
    bool ABDJKPCGDHO = 15;
}

message MarkRelicFilterPlanCsReq {
    bool NPPKABBJCMI = 8;
    bool BIJJOJNJHDO = 1;
    repeated uint32 GGIGDJPFBBP = 9;
}

message MarkRelicFilterPlanScRsp {
    repeated uint32 GGIGDJPFBBP = 2;
    uint32 retcode = 3;
    bool NPPKABBJCMI = 8;
    bool BIJJOJNJHDO = 9;
}

message ModifyRelicFilterPlanCsReq {
    uint32 NPHAJEKCBKF = 8;
    string name = 1;
    KJDLIPEIAAK MJPKBIGCFOM = 10;
    BNAILMNNGIF LJKNDCIOOCG = 2;
}

message ModifyRelicFilterPlanScRsp {
    uint32 retcode = 3;
    uint32 NPHAJEKCBKF = 10;
    int64 BNCALAMGIOC = 4;
    string name = 12;
    KJDLIPEIAAK MJPKBIGCFOM = 9;
    BNAILMNNGIF LJKNDCIOOCG = 7;
}

message OCKCHBDFGNL {
    uint64 time = 13;
    repeated NKDNFDCFNCP HJMDNLBNPNA = 6;
}

message PromoteEquipmentCsReq {
    uint32 equipment_unique_id = 11;
    ItemCostData cost_data = 12;
}

message PromoteEquipmentScRsp {
    repeated PileItem DFABHHAPAEA = 3;
    uint32 PLDKENJLKME = 12;
}

message RankUpEquipmentCsReq {
    uint32 equipment_unique_id = 9;
    ItemCostData cost_data = 8;
}

message RankUpEquipmentScRsp {
    uint32 retcode = 4;
}

message RechargeSuccNotify {
    string product_id = 11;
    ItemList item_list = 9;
    string price_tier = 3;
    uint64 month_card_out_date_time = 15;
}

enum RelicDiscardType {
    RelicDiscardType_Single = 0;
    RelicDiscardType_Batch = 1;
    RelicDiscardType_Smart = 2;
}

message RelicReforgeConfirmCsReq {
    bool is_cancel = 14;
    uint32 relic_unique_id = 11;
}

message RelicReforgeCsReq {
    uint32 reforge_block_sub_affix_id = 6;
    uint32 relic_unique_id = 14;
}

message SellItemCsReq {
    bool HNLKAEBKKBL = 15;
    ItemCostData cost_data = 9;
}

message SellItemScRsp {
    uint32 retcode = 8;
    ItemList return_item_list = 6;
}

message SyncTurnFoodNotify {
    repeated TurnFoodSwitch EOJBFLHBNMB = 13;
    repeated uint32 CAMEGAGKPGL = 7;
}

enum TurnFoodSwitch {
    TurnFoodSwitch_None = 0;
    TurnFoodSwitch_Attack = 1;
    TurnFoodSwitch_Define = 2;
}

message UseItemCsReq {
    bool DGEKFCHEAPO = 10;
    uint32 use_item_id = 7;
    uint32 optional_reward_id = 9;
    uint32 use_item_count = 8;
    uint32 base_avatar_id = 11;
    AvatarType KANPPCMBJHG = 1;
}

message UseItemScRsp {
    ItemList return_data = 8;
    uint32 formula_id = 1;
    uint32 use_item_count = 12;
    uint32 retcode = 10;
    uint64 month_card_out_date_time = 7;
    uint32 use_item_id = 2;
}
