syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdJukeboxType {
    CmdJukeboxType_None = 0;
    CmdJukeboxType_TrialBackGroundMusicScRsp = 3126;
    CmdJukeboxType_GetJukeboxDataScRsp = 3182;
    CmdJukeboxType_UnlockBackGroundMusicScRsp = 3191;
    CmdJukeboxType_TrialBackGroundMusicCsReq = 3198;
    CmdJukeboxType_PlayBackGroundMusicScRsp = 3139;
    CmdJukeboxType_PlayBackGroundMusicCsReq = 3179;
    CmdJukeboxType_UnlockBackGroundMusicCsReq = 3156;
    CmdJukeboxType_GetJukeboxDataCsReq = 3134;
}

message FKLMGEFILDI {
    uint32 JKFCKJNHLHI = 8;
}

message GetJukeboxDataCsReq {
}

message GetJukeboxDataScRsp {
    repeated LHHGCDLCJDA IOKAJIBHLMP = 14;
    uint32 retcode = 7;
    MNCBEDBDDHL GFFOBALDBPM = 6;
}

message LHHGCDLCJDA {
    bool BIMDKNLMICG = 6;
    uint32 group_id = 15;
    uint32 id = 8;
}

message PlayBackGroundMusicCsReq {
    MNCBEDBDDHL IKJNIKIGFLF = 7;
}

message PlayBackGroundMusicScRsp {
    MNCBEDBDDHL GFFOBALDBPM = 1;
    uint32 retcode = 12;
}

message UnlockBackGroundMusicScRsp {
    repeated LHHGCDLCJDA IOKAJIBHLMP = 13;
    uint32 retcode = 6;
    repeated uint32 BPFGBEBPEDP = 8;
}
