syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ANFMHBGNNEG {
    PJMGBLIFDFP room_ext_info = 13;
}

message CIGLIFFIIDC {
    LKFBIALLBDK NABJDHEPELK = 1;
    LobbyCharacterStatus status = 2;
}

enum CmdLobbyType {
    CmdLobbyType_None = 0;
    CmdLobbyType_LobbyQuitCsReq = 7362;
    CmdLobbyType_LobbyModifyRoomExtInfoCsReq = 7385;
    CmdLobbyType_LobbyModifyPlayerInfoScRsp = 7387;
    CmdLobbyType_LobbyStartFightCsReq = 7358;
    CmdLobbyType_LobbyInteractCsReq = 7368;
    CmdLobbyType_LobbyInteractScNotify = 7354;
    CmdLobbyType_LobbySyncInfoScNotify = 7371;
    CmdLobbyType_LobbyJoinCsReq = 7394;
    CmdLobbyType_LobbyInteractScRsp = 7375;
    CmdLobbyType_LobbyKickOutScRsp = 7388;
    CmdLobbyType_LobbyInviteCsReq = 7367;
    CmdLobbyType_LobbyInviteScRsp = 7369;
    CmdLobbyType_LobbyCreateScRsp = 7379;
    CmdLobbyType_LobbyStartFightScRsp = 7372;
    CmdLobbyType_LobbyGetInfoCsReq = 7364;
    CmdLobbyType_LobbyModifyPlayerInfoCsReq = 7382;
    CmdLobbyType_LobbyModifyRoomExtInfoScRsp = 7397;
    CmdLobbyType_LobbyGetInfoScRsp = 7392;
    CmdLobbyType_LobbyJoinScRsp = 7374;
    CmdLobbyType_LobbyKickOutCsReq = 7370;
    CmdLobbyType_LobbyQuitScRsp = 7351;
    CmdLobbyType_LobbyCreateCsReq = 7386;
}

message DACEFJFGLGM {
}

message GBAKEFGOLCB {
    uint32 stage_id = 1;
    uint32 CDNNHONKELJ = 2;
}

message HCLAEGGMCFK {
    uint32 LOPNADHJKBF = 1;
}

message HFAAFFDPBIL {
    uint32 stage_id = 1;
    TeamTowersGameType DLFHABGGHFF = 2;
    uint32 CDNNHONKELJ = 3;
}

enum HGMNDBFCBLL {
    HGMNDBFCBLL_NLCDGIPGFDJ = 0;
    HGMNDBFCBLL_CPJDKCDJFNA = 1;
    HGMNDBFCBLL_APBCEPNOCKG = 2;
}

enum LKFBIALLBDK {
    LKFBIALLBDK_EFAGELOKHAH = 0;
    LKFBIALLBDK_EFLAAFEKBLO = 1;
    LKFBIALLBDK_MHOEPNOAGDN = 2;
    LKFBIALLBDK_GLLICMOMCOA = 3;
}

message LMLNNHKJEIP {
    MOHAGOFLGAP basic_info = 1;
    CIGLIFFIIDC GBBCBJCACIN = 2;
    LobbyGameExtInfo stage_info = 3;
}

enum LobbyCharacterStatus {
    LobbyCharacterStatus_None = 0;
    LobbyCharacterStatus_Idle = 1;
    LobbyCharacterStatus_Operating = 2;
    LobbyCharacterStatus_Ready = 3;
    LobbyCharacterStatus_Fighting = 4;
    LobbyCharacterStatus_Watching = 5;
    LobbyCharacterStatus_Matching = 6;
    LobbyCharacterStatus_LobbyStartFight = 7;
}

message LobbyCreateCsReq {
    LobbyGameExtInfo JIDKDPPPDPF = 9;
    PJMGBLIFDFP room_ext_info = 11;
    FightGameMode GJNMHILINHC = 4;
    uint32 HDJFGMGAOOF = 6;
}

message LobbyCreateScRsp {
    FightGameMode GJNMHILINHC = 15;
    uint64 room_id = 2;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 12;
    uint32 retcode = 11;
    PJMGBLIFDFP room_ext_info = 3;
    uint32 HDJFGMGAOOF = 4;
}

message LobbyGetInfoCsReq {
}

message LobbyGetInfoScRsp {
    uint64 room_id = 4;
    uint32 HDJFGMGAOOF = 13;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 11;
    uint32 retcode = 15;
    PJMGBLIFDFP room_ext_info = 14;
    FightGameMode GJNMHILINHC = 6;
}

message LobbyInteractScNotify {
    uint32 CPOCELOLNHL = 7;
    LobbyInteractType DNBKKDBFFAJ = 3;
}

enum LobbyInteractType {
    LobbyInteractType_None = 0;
    LobbyInteractType_RemindPrepare = 1;
}

message LobbyInviteCsReq {
    repeated uint32 uid_list = 7;
}

message LobbyInviteScRsp {
    uint32 retcode = 14;
    repeated uint32 uid_list = 1;
}

message LobbyJoinCsReq {
    uint64 room_id = 15;
    string JKJCIPFMOHG = 9;
    LobbyGameExtInfo JIDKDPPPDPF = 14;
}

message LobbyJoinScRsp {
    FightGameMode GJNMHILINHC = 1;
    uint64 room_id = 14;
    uint32 HDJFGMGAOOF = 13;
    PJMGBLIFDFP room_ext_info = 4;
    uint32 retcode = 12;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 2;
}

message LobbyKickOutCsReq {
    uint32 uid = 9;
}

message LobbyModifyPlayerInfoCsReq {
    LobbyModifyType type = 14;
    uint32 GMGJFJCDGGN = 11;
    LobbyGameExtInfo JIDKDPPPDPF = 1;
}

message LobbyModifyPlayerInfoScRsp {
    uint32 retcode = 7;
}

enum LobbyModifyType {
    LobbyModifyType_None = 0;
    LobbyModifyType_Idle = 1;
    LobbyModifyType_Ready = 2;
    LobbyModifyType_Operating = 3;
    LobbyModifyType_CancelMatch = 4;
    LobbyModifyType_Match = 5;
    LobbyModifyType_QuitLobby = 6;
    LobbyModifyType_KickOut = 7;
    LobbyModifyType_TimeOut = 8;
    LobbyModifyType_JoinLobby = 9;
    LobbyModifyType_LobbyDismiss = 10;
    LobbyModifyType_MatchTimeOut = 11;
    LobbyModifyType_FightStart = 12;
    LobbyModifyType_Logout = 13;
    LobbyModifyType_FightEnd = 14;
    LobbyModifyType_FightRoomDestroyInInit = 15;
    LobbyModifyType_LobbyStartFight = 16;
    LobbyModifyType_LobbyStartFightTimeout = 17;
    LobbyModifyType_LobbyRoomExtInfo = 18;
}

message LobbyQuitCsReq {
}

message LobbyQuitScRsp {
    uint32 retcode = 14;
}

message LobbySyncInfoScNotify {
    repeated LMLNNHKJEIP DFLEOIGPLNM = 9;
    LobbyModifyType type = 3;
    uint32 uid = 1;
}

message MOHAGOFLGAP {
    uint32 uid = 1;
    uint32 level = 2;
    string nickname = 3;
    uint32 icon = 4;
    PlatformType platform = 5;
    string IJKOMIKFKEK = 6;
    string EBMNJMIKNPP = 7;
    uint64 version = 8;
    bool OCLBMMNNMFC = 9;
    uint32 MIDBIPHKLJO = 10;
}

message ONNHDODIIED {
    HGMNDBFCBLL DLFHABGGHFF = 1;
}

message OPKKJFEFEIL {
    uint32 teleport_id = 15;
    LobbyInteractType DNBKKDBFFAJ = 12;
}

message PJMGBLIFDFP {
    HCLAEGGMCFK lobby_grid_fight_info = 1001;
    ONNHDODIIED GOKJCFBPHCJ = 1002;
    GBAKEFGOLCB FNNOPJBPLPF = 1003;
    HFAAFFDPBIL MPNPIIHHFPN = 1004;
}
