syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BJGNOHEEIGD {
    uint32 HOGCJDDLGKJ = 6;
    uint32 AHAFPEFKDNO = 14;
    repeated uint32 DECFDGJJFGL = 15;
}

message BMDEEMIDNEL {
    repeated uint32 IHOMKIICBLP = 6;
    uint32 CEDDGAMLKJK = 7;
}

enum CmdLimaoNewsType {
    CmdLimaoNewsType_None = 0;
    CmdLimaoNewsType_LimaoNewsReportEmployeeCheckRefreshScRsp = 9167;
    CmdLimaoNewsType_LimaoNewsCompleteOfficeSurveyListScRsp = 9181;
    CmdLimaoNewsType_LimaoNewsFinishPlanPhaseScRsp = 9161;
    CmdLimaoNewsType_LimaoNewsUpvoteInterviewCsReq = 9153;
    CmdLimaoNewsType_LimaoNewsStartWorkScRsp = 9189;
    CmdLimaoNewsType_LimaoNewsSubmitPostScRsp = 9154;
    CmdLimaoNewsType_LimaoNewsTrackSurveyScRsp = 9205;
    CmdLimaoNewsType_LimaoNewsSubmitIssueScRsp = 9169;
    CmdLimaoNewsType_LimaoNewsFinishClientEventScRsp = 9194;
    CmdLimaoNewsType_LimaoNewsReportEmployeeCheckRefreshCsReq = 9151;
    CmdLimaoNewsType_LimaoNewsFinishEmployeeCheckCsReq = 9192;
    CmdLimaoNewsType_LimaoNewsFinishClientMessageCsReq = 9177;
    CmdLimaoNewsType_LimaoNewsTrackSurveyCsReq = 9207;
    CmdLimaoNewsType_LimaoNewsUpvotePostCsReq = 9165;
    CmdLimaoNewsType_LimaoNewsUpvotePostScRsp = 9159;
    CmdLimaoNewsType_LimaoNewsCompleteOfficeSurveyListCsReq = 9155;
    CmdLimaoNewsType_LimaoNewsSetMainPageFlagScRsp = 9176;
    CmdLimaoNewsType_LimaoNewsFinishClientEventCsReq = 9198;
    CmdLimaoNewsType_LimaoNewsFinishClientMessageScRsp = 9200;
    CmdLimaoNewsType_LimaoNewsFinishPlanPhaseCsReq = 9166;
    CmdLimaoNewsType_LimaoNewsGetDataScRsp = 9157;
    CmdLimaoNewsType_LimaoNewsSetMainPageFlagCsReq = 9208;
    CmdLimaoNewsType_LimaoNewsRefreshOfficeSurveyCsReq = 9175;
    CmdLimaoNewsType_LimaoNewsUpvoteInterviewScRsp = 9152;
    CmdLimaoNewsType_LimaoNewsSubmitIssueCsReq = 9197;
    CmdLimaoNewsType_LimaoNewsFinishClientReplyScRsp = 9156;
    CmdLimaoNewsType_LimaoNewsRefreshOfficeSurveyScRsp = 9173;
    CmdLimaoNewsType_LimaoNewsFinishEmployeeCheckScRsp = 9201;
    CmdLimaoNewsType_LimaoNewsSubmitPostCsReq = 9168;
    CmdLimaoNewsType_LimaoNewsStartWorkCsReq = 9184;
    CmdLimaoNewsType_LimaoNewsFinishClientReplyCsReq = 9203;
    CmdLimaoNewsType_LimaoNewsDataChangeScNotify = 9171;
    CmdLimaoNewsType_LimaoNewsGetDataCsReq = 9160;
}

message DGFHEGJKHFO {
    uint32 KPKJALDCMIK = 4;
}

message FNIDNGOGAFF {
    uint32 KPKJALDCMIK = 2;
    uint32 IIADKFFPKGP = 15;
}

message HBOOIEJHKOD {
    uint32 BOGIJENAEHJ = 4;
    uint32 CBGODLHCLPK = 11;
}

message HOALCJNIJJC {
    uint32 param = 7;
    uint32 event_id = 9;
}

message IBPHNIBGMPH {
    uint32 CBGODLHCLPK = 1;
}

message JABBBMCMKAI {
    uint32 IHIOGBMCFIE = 12;
    uint32 FIAOCDAJBLD = 8;
}

message JGHOCEGBDCC {
}

message JPIEAEJIDAO {
    repeated FNIDNGOGAFF LMLLNJBLPGC = 9;
}

message KELNHIOMCNF {
}

message KJAMNAOLOLL {
    uint32 MBBGFJGCHGE = 13;
    uint32 LJHGIFGINOL = 5;
}

message LDCEDOGDNDC {
    uint32 LJEDNBHJPDA = 14;
    uint32 HDGKLMKGNND = 5;
}

message LFGKIJMBKJG {
    uint32 CBGODLHCLPK = 9;
    bool KBLBFGANMPJ = 14;
}

message LGGGHFDBCFN {
    uint32 FDGJLMMEAOF = 11;
    uint32 progress = 13;
    uint32 KBDOBOODPAK = 14;
    bool has_passed = 9;
}

message NFBHBDICGOG {
}

message OCEAHPDAPFC {
    uint32 OCJCOOLMCGD = 13;
    PBLBAAMLNLH NOGCKIHEDCE = 6;
    uint32 HOCFMNJPCLI = 1;
    uint32 JGMJFHLIAIL = 5;
    KJAMNAOLOLL IAFPOEBBJIL = 15;
    LGGGHFDBCFN LDBGGNHLFAM = 8;
    JPIEAEJIDAO HDMEPMHHOLP = 7;
    uint32 JDGKFGONCJI = 12;
    uint32 CGEFHJIEKGF = 9;
    OEIHBAJCCAF EOKMIFNCLAB = 2;
    BMDEEMIDNEL ANLLBMHLFFC = 11;
    BJGNOHEEIGD NBCEHKBENPE = 14;
    PPPCGBKJDAB JEBEMFMEEPJ = 1261;
}

message OEIHBAJCCAF {
    uint32 JFFDHONHFOA = 13;
    bool GKFNOCPMJLC = 8;
    uint32 IHIOGBMCFIE = 10;
    uint32 ADHFOFCHBII = 14;
    uint32 CMOOAFMCMDC = 9;
    uint32 OABNIMBJJGP = 5;
    repeated uint32 IEBALCFJBCM = 11;
    uint32 FIAOCDAJBLD = 2;
}

message OFNBDEKJMON {
    uint32 LFPABLEIKKE = 14;
}

message PBLBAAMLNLH {
    uint32 LJHGIFGINOL = 3;
    uint32 CBGODLHCLPK = 8;
    bool is_unlocked = 5;
    bool KBLBFGANMPJ = 14;
    uint32 BMGBBEMHLIG = 9;
    bool BBMCAHOMEFN = 12;
    uint32 MDJMBGPLCDD = 15;
}

message PDPKFDOJOFK {
    uint32 CMOOAFMCMDC = 8;
    uint32 AJLEHODGIJD = 7;
}

message PLADCLDJGKK {
    bool KBLBFGANMPJ = 6;
    uint32 BEOHGAADKPH = 7;
}

message PNALNDONMCK {
    repeated OCEAHPDAPFC DGNGMJMPFGK = 15;
}

message PNOAIGFGNKE {
}

message PPPCGBKJDAB {
    repeated uint32 KDEAHPHDDHH = 10;
    uint32 OOKLDLHMOFM = 14;
    uint32 LJEDNBHJPDA = 12;
}
