syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ACIHMMBKMIM {
    AvatarType avatar_type = 14;
    uint32 avatar_id = 1;
}

enum CmdLocalLegendType {
    CmdLocalLegendType_None = 0;
    CmdLocalLegendType_GetLocalLegendDataScRsp = 6593;
    CmdLocalLegendType_LocalLegendBattleEndScNotify = 6596;
    CmdLocalLegendType_GetLocalLegendDataCsReq = 6584;
    CmdLocalLegendType_EnterLocalLegendLevelScRsp = 6599;
    CmdLocalLegendType_EnterLocalLegendLevelCsReq = 6586;
}

message EnterLocalLegendLevelCsReq {
    repeated ACIHMMBKMIM avatar_list = 2;
    uint32 group_id = 13;
    uint32 DBKHHCGGKNN = 11;
}

message EnterLocalLegendLevelScRsp {
    uint32 retcode = 1;
    SceneBattleInfo battle_info = 7;
    uint32 group_id = 4;
    uint32 DBKHHCGGKNN = 13;
}

message GetLocalLegendDataCsReq {
}

message GetLocalLegendDataScRsp {
    repeated JJEFLBCLBFN level_data_list = 3;
    uint32 retcode = 11;
}

message JJEFLBCLBFN {
    uint32 group_id = 9;
    uint32 DBKHHCGGKNN = 14;
    uint32 FFGFINDLMCF = 13;
}
