syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BMJHAHOLEGH {
    uint32 KFBIODICKGC = 9;
    uint32 NEKCONMFFFE = 7;
    uint32 panel_id = 13;
    uint32 total_count = 8;
}

enum CmdMultipleDropType {
    CmdMultipleDropType_None = 0;
    CmdMultipleDropType_GetMultipleDropInfoCsReq = 4634;
    CmdMultipleDropType_GetPlayerReturnMultiDropInfoScRsp = 4656;
    CmdMultipleDropType_MultipleDropInfoScNotify = 4679;
    CmdMultipleDropType_MultipleDropInfoNotify = 4691;
    CmdMultipleDropType_GetMultipleDropInfoScRsp = 4682;
    CmdMultipleDropType_GetPlayerReturnMultiDropInfoCsReq = 4639;
}

message GCLPBMPOHLI {
    uint32 panel_id = 13;
    uint32 FAOAGKPPNGN = 9;
    uint32 LFOHEBCNMDP = 4;
    uint32 JMGPFEGLCGG = 1;
}

message GetMultipleDropInfoCsReq {
}

message GetMultipleDropInfoScRsp {
    repeated NGLOBFBCGBB MOPAGKNEMOD = 6;
    repeated BMJHAHOLEGH FAFFFJGJHHC = 4;
    uint32 retcode = 7;
}

message GetPlayerReturnMultiDropInfoCsReq {
}

message GetPlayerReturnMultiDropInfoScRsp {
    GCLPBMPOHLI HDLIGGEMOKM = 6;
    uint32 retcode = 5;
    repeated BMJHAHOLEGH FAFFFJGJHHC = 9;
}

message MultipleDropInfoNotify {
    repeated BMJHAHOLEGH FAFFFJGJHHC = 4;
    repeated NGLOBFBCGBB MOPAGKNEMOD = 6;
    repeated GCLPBMPOHLI JGALOGDBCKI = 2;
}

message MultipleDropInfoScNotify {
    repeated NGLOBFBCGBB MOPAGKNEMOD = 7;
}

message NGLOBFBCGBB {
    uint32 CLLFACKFNBO = 12;
    uint32 id = 2;
}
