syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ChargerInfo {
    uint32 group_id = 8;
    uint32 instance_id = 5;
}

enum CmdMapRotationType {
    CmdMapRotationType_None = 0;
    CmdMapRotationType_ResetMapRotationRegionCsReq = 6880;
    CmdMapRotationType_EnterMapRotationRegionScRsp = 6882;
    CmdMapRotationType_InteractChargerScRsp = 6839;
    CmdMapRotationType_InteractChargerCsReq = 6879;
    CmdMapRotationType_LeaveMapRotationRegionScRsp = 6899;
    CmdMapRotationType_DeployRotaterScRsp = 6891;
    CmdMapRotationType_RemoveRotaterCsReq = 6848;
    CmdMapRotationType_DeployRotaterCsReq = 6856;
    CmdMapRotationType_RotateMapCsReq = 6898;
    CmdMapRotationType_UpdateRotaterScNotify = 6815;
    CmdMapRotationType_LeaveMapRotationRegionCsReq = 6873;
    CmdMapRotationType_UpdateEnergyScNotify = 6862;
    CmdMapRotationType_GetMapRotationDataCsReq = 6872;
    CmdMapRotationType_UpdateMapRotationDataScNotify = 6849;
    CmdMapRotationType_RemoveRotaterScRsp = 6888;
    CmdMapRotationType_RotateMapScRsp = 6826;
    CmdMapRotationType_ResetMapRotationRegionScRsp = 6871;
    CmdMapRotationType_EnterMapRotationRegionCsReq = 6834;
    CmdMapRotationType_GetMapRotationDataScRsp = 6865;
}

message EnterMapRotationRegionCsReq {
    uint32 JPPMEKJGJFD = 13;
    MotionInfo motion = 6;
    uint32 region_id = 3;
}

message EnterMapRotationRegionScRsp {
    RotaterEnergyInfo energy_info = 3;
    MotionInfo motion = 9;
    uint32 region_id = 2;
    uint32 retcode = 11;
    uint32 JPPMEKJGJFD = 4;
    uint32 client_pos_version = 5;
}

message GetMapRotationDataCsReq {
}

message GetMapRotationDataScRsp {
    uint32 retcode = 2;
    repeated RotaterData CEDGGDFMILP = 1;
    uint32 JPPMEKJGJFD = 10;
    RotateMapInfo COOOMDKGODF = 13;
    bool BHABAIFPOOA = 7;
    RotaterEnergyInfo energy_info = 6;
    repeated NJMDFFHEAJJ EGAGKNADAHJ = 3;
    int32 region_id = 14;
}

message InteractChargerCsReq {
    ChargerInfo charger_info = 5;
}

message InteractChargerScRsp {
    uint32 retcode = 2;
    RotaterEnergyInfo energy_info = 7;
    NJMDFFHEAJJ charger_info = 14;
}

message LeaveMapRotationRegionCsReq {
    MotionInfo motion = 12;
}

message LeaveMapRotationRegionScRsp {
    MotionInfo motion = 2;
    uint32 client_pos_version = 7;
    uint32 retcode = 9;
}

message RemoveRotaterScRsp {
    RotaterEnergyInfo energy_info = 6;
    uint32 retcode = 14;
    RotaterData rotater_data = 5;
}

message ResetMapRotationRegionCsReq {
    RotateMapInfo COOOMDKGODF = 12;
    MotionInfo motion = 11;
}

message ResetMapRotationRegionScRsp {
    uint32 retcode = 12;
    MotionInfo motion = 1;
    uint32 client_pos_version = 11;
}

message RotateMapCsReq {
    uint32 instance_id = 10;
    MotionInfo motion = 9;
    RotateMapInfo COOOMDKGODF = 7;
    uint32 group_id = 13;
}

message RotateMapScRsp {
    uint32 retcode = 8;
    MotionInfo motion = 3;
    uint32 client_pos_version = 10;
}

message UpdateEnergyScNotify {
    RotaterEnergyInfo energy_info = 12;
}

message UpdateMapRotationDataScNotify {
    uint32 JPPMEKJGJFD = 9;
    bool BHABAIFPOOA = 7;
    RotateMapInfo COOOMDKGODF = 13;
    RotaterEnergyInfo energy_info = 8;
    repeated RotaterData CEDGGDFMILP = 6;
    repeated NJMDFFHEAJJ EGAGKNADAHJ = 12;
    int32 region_id = 1;
}
