syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CancelMatchCsReq {
}

message CancelMatchScRsp {
    uint32 retcode = 3;
}

enum CmdMatchType {
    CmdMatchType_None = 0;
    CmdMatchType_StartMatchCsReq = 7336;
    CmdMatchType_CancelMatchCsReq = 7344;
    CmdMatchType_StartMatchScRsp = 7329;
    CmdMatchType_GetCrossInfoCsReq = 7322;
    CmdMatchType_GetCrossInfoScRsp = 7332;
    CmdMatchType_CancelMatchScRsp = 7324;
}

message GetCrossInfoCsReq {
}

message GetCrossInfoScRsp {
    uint64 FGNFDGAKKAP = 6;
    FightGameMode GJNMHILINHC = 8;
    uint64 room_id = 4;
    uint32 retcode = 12;
}

message StartMatchCsReq {
    LobbyGameExtInfo JIDKDPPPDPF = 10;
    FightGameMode GJNMHILINHC = 9;
}

message StartMatchScRsp {
    uint32 retcode = 9;
}
