syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ADNCPPCPLLH {
    repeated uint32 MJMJOMDLOHI = 15;
    uint32 event_id = 2;
    uint32 GKKNMDDNOJF = 5;
    uint32 HAFOKMHCGFM = 14;
}

message AHMFKPIAHCO {
    uint32 KCLCDFGGPBK = 3;
    uint32 KJBILOOCBPB = 4;
    uint32 DAEKKPOJAJG = 13;
    uint32 ADADGDPCPDN = 5;
}

enum BAKAELIMIJI {
    BAKAELIMIJI_NLCDGIPGFDJ = 0;
    BAKAELIMIJI_HEIHBJEEGPB = 1;
    BAKAELIMIJI_BOGGAFJJPGC = 2;
    BAKAELIMIJI_HCEBKFDJGIO = 3;
    BAKAELIMIJI_CBKLDCBEKCH = 4;
    BAKAELIMIJI_LGGEBOCPPDA = 5;
    BAKAELIMIJI_BBDHKAKKBEA = 6;
    BAKAELIMIJI_BFPGGHFAHCA = 7;
    BAKAELIMIJI_PPINCGHOOBH = 8;
    BAKAELIMIJI_JCECCHOJPFK = 9;
    BAKAELIMIJI_JBLEFHFOHGO = 10;
}

message BANELIGFLCO {
    uint32 MFKHDANPCIC = 8;
    uint32 level = 13;
    uint32 CBILPMICEKC = 2;
}

message BCDIFIIDPIA {
    repeated KFGILGDFEKE BEMBGMOIAON = 13;
}

message CCMCKOKEJNI {
    repeated uint32 HNDAGKPKGHI = 7;
}

message CCOHBABCHAI {
    uint32 NJFKOEBEGGB = 10;
    bool EEDEGBHEKGD = 7;
}

enum CmdMonopolyType {
    CmdMonopolyType_None = 0;
    CmdMonopolyType_MonopolyGameGachaScRsp = 7001;
    CmdMonopolyType_MonopolyReRollRandomCsReq = 7049;
    CmdMonopolyType_MonopolyClickMbtiReportCsReq = 7095;
    CmdMonopolyType_MonopolyGameGachaCsReq = 7044;
    CmdMonopolyType_GetMonopolyFriendRankingListCsReq = 7047;
    CmdMonopolyType_MonopolyGetRafflePoolInfoScRsp = 7052;
    CmdMonopolyType_MonopolyTakeRaffleTicketRewardScRsp = 7054;
    CmdMonopolyType_MonopolyGuessChooseCsReq = 7083;
    CmdMonopolyType_MonopolyRollDiceCsReq = 7091;
    CmdMonopolyType_MonopolyMoveScRsp = 7073;
    CmdMonopolyType_GetMbtiReportCsReq = 7019;
    CmdMonopolyType_MonopolyLikeScNotify = 7068;
    CmdMonopolyType_MonopolyAcceptQuizScRsp = 7043;
    CmdMonopolyType_MonopolyDailySettleScNotify = 7069;
    CmdMonopolyType_MonopolyGetDailyInitItemCsReq = 7031;
    CmdMonopolyType_GetMonopolyMbtiReportRewardScRsp = 7045;
    CmdMonopolyType_MonopolyCheatDiceScRsp = 7009;
    CmdMonopolyType_MonopolyActionResultScNotify = 7079;
    CmdMonopolyType_MonopolyGetDailyInitItemScRsp = 7051;
    CmdMonopolyType_MonopolyAcceptQuizCsReq = 7021;
    CmdMonopolyType_GetMonopolyInfoCsReq = 7034;
    CmdMonopolyType_MonopolyConfirmRandomScRsp = 7015;
    CmdMonopolyType_MonopolyGetRafflePoolInfoCsReq = 7007;
    CmdMonopolyType_MonopolySelectOptionCsReq = 7099;
    CmdMonopolyType_MonopolyGuessDrawScNotify = 7030;
    CmdMonopolyType_MonopolySttUpdateScNotify = 7018;
    CmdMonopolyType_MonopolyTakePhaseRewardScRsp = 7042;
    CmdMonopolyType_GetSocialEventServerCacheCsReq = 7085;
    CmdMonopolyType_MonopolyLikeScRsp = 7020;
    CmdMonopolyType_MonopolyGameRaiseRatioCsReq = 7014;
    CmdMonopolyType_DeleteSocialEventServerCacheCsReq = 7016;
    CmdMonopolyType_MonopolyScrachRaffleTicketScRsp = 7076;
    CmdMonopolyType_MonopolyGetRegionProgressScRsp = 7036;
    CmdMonopolyType_GetMonopolyInfoScRsp = 7082;
    CmdMonopolyType_MonopolyLikeCsReq = 7078;
    CmdMonopolyType_MonopolyReRollRandomScRsp = 7048;
    CmdMonopolyType_MonopolyClickCellCsReq = 7093;
    CmdMonopolyType_MonopolyGuessChooseScRsp = 7055;
    CmdMonopolyType_MonopolyGameBingoFlipCardCsReq = 7008;
    CmdMonopolyType_MonopolyGiveUpCurContentCsReq = 7057;
    CmdMonopolyType_MonopolyEventSelectFriendScRsp = 7063;
    CmdMonopolyType_DeleteSocialEventServerCacheScRsp = 7092;
    CmdMonopolyType_MonopolyQuizDurationChangeScNotify = 7060;
    CmdMonopolyType_GetMonopolyFriendRankingListScRsp = 7035;
    CmdMonopolyType_MonopolyGetRaffleTicketScRsp = 7094;
    CmdMonopolyType_MonopolyGetRaffleTicketCsReq = 7096;
    CmdMonopolyType_MonopolySocialEventEffectScNotify = 7028;
    CmdMonopolyType_MonopolyGuessBuyInformationCsReq = 7075;
    CmdMonopolyType_MonopolyEventLoadUpdateScNotify = 7084;
    CmdMonopolyType_MonopolyRollDiceScRsp = 7098;
    CmdMonopolyType_MonopolyTakeRaffleTicketRewardCsReq = 7027;
    CmdMonopolyType_GetMonopolyDailyReportCsReq = 7053;
    CmdMonopolyType_MonopolyClickCellScRsp = 7012;
    CmdMonopolyType_MonopolyClickMbtiReportScRsp = 7010;
    CmdMonopolyType_MonopolyEventSelectFriendCsReq = 7074;
    CmdMonopolyType_MonopolyContentUpdateScNotify = 7024;
    CmdMonopolyType_MonopolyGameSettleScNotify = 7023;
    CmdMonopolyType_MonopolyUpgradeAssetCsReq = 7041;
    CmdMonopolyType_MonopolyConditionUpdateScNotify = 7097;
    CmdMonopolyType_MonopolyRollRandomCsReq = 7004;
    CmdMonopolyType_MonopolyBuyGoodsScRsp = 7081;
    CmdMonopolyType_DailyFirstEnterMonopolyActivityScRsp = 7071;
    CmdMonopolyType_MonopolyConfirmRandomCsReq = 7088;
    CmdMonopolyType_MonopolyUpgradeAssetScRsp = 7038;
    CmdMonopolyType_MonopolyGiveUpCurContentScRsp = 7046;
    CmdMonopolyType_MonopolyGameRaiseRatioScRsp = 7005;
    CmdMonopolyType_GetMonopolyMbtiReportRewardCsReq = 7050;
    CmdMonopolyType_MonopolyCheatDiceCsReq = 7066;
    CmdMonopolyType_MonopolyGameBingoFlipCardScRsp = 7058;
    CmdMonopolyType_GetMonopolyDailyReportScRsp = 7100;
    CmdMonopolyType_DailyFirstEnterMonopolyActivityCsReq = 7080;
    CmdMonopolyType_MonopolyScrachRaffleTicketCsReq = 7059;
    CmdMonopolyType_MonopolyGameCreateScNotify = 7040;
    CmdMonopolyType_MonopolySelectOptionScRsp = 7072;
    CmdMonopolyType_MonopolyCellUpdateNotify = 7039;
    CmdMonopolyType_MonopolyBuyGoodsCsReq = 7064;
    CmdMonopolyType_GetSocialEventServerCacheScRsp = 7025;
    CmdMonopolyType_MonopolyGetRegionProgressCsReq = 7013;
    CmdMonopolyType_MonopolyRollRandomScRsp = 7062;
    CmdMonopolyType_MonopolyTakePhaseRewardCsReq = 7037;
    CmdMonopolyType_MonopolyMoveCsReq = 7026;
    CmdMonopolyType_GetMbtiReportScRsp = 7033;
    CmdMonopolyType_MonopolyGuessBuyInformationScRsp = 7002;
}

message DBPHHPGNMKC {
    repeated BANELIGFLCO NPENGFBHFJN = 5;
}

message DCAJAKJAJNL {
    uint32 shop_id = 12;
}

message DCMHLOEGFBM {
    uint32 LCFDOPINEBO = 2;
    ItemList item_list = 8;
    uint32 HABHOAMCGLH = 13;
}

message DDHIEONLIIL {
    uint64 HEMOHFJJMJG = 4;
    bool is_taken_reward = 15;
    bool DDKGKOFAGMH = 9;
}

message DFKABDLJMJO {
    repeated NEMIDPFEJFL PHKBDAHIPEE = 7;
    uint32 KBLJEGIPINF = 5;
}

message DKHCBKNGOMF {
    uint32 MKNLPJMBHDK = 4;
}

message DailyFirstEnterMonopolyActivityCsReq {
}

message DailyFirstEnterMonopolyActivityScRsp {
    uint32 retcode = 15;
    int64 DJMLHBFEMBE = 1;
    NJHAGKGHKJJ OLAONLGLAJO = 4;
    bool GLEJFCIOMKC = 3;
    uint32 ICPAPCAJFKK = 2;
}

message EDGEHPFOKBH {
    uint32 ACPKAOIIEHJ = 13;
    uint32 cnt = 5;
}

message EIDFCGLODFB {
    uint32 map_id = 11;
    NADDHEILBBN PIJJDFCBMPG = 1;
    uint32 IHAOMLEPHOM = 9;
    bool BPKMKFLDCAI = 5;
}

message EOHAFICJPIP {
    uint32 CPOCELOLNHL = 5;
    uint32 id = 8;
    uint32 NLGNNDIFGGF = 10;
    uint32 add_coin = 2;
}

message FIOENGOHOOJ {
    NEMIDPFEJFL MEGBFFOAFGL = 14;
}

message FOOFAIFPOOI {
    repeated GLMGJFEEJHD BGJBAGJAJDL = 10;
    CCOHBABCHAI IBLHLCMNMAJ = 3;
    GLMGJFEEJHD JELODDPELKJ = 8;
}

message GALCNKIAHNN {
    uint32 NLGNNDIFGGF = 10;
    uint32 add_coin = 1;
}

message GLMGJFEEJHD {
    uint32 ratio = 5;
    uint32 BAJHKGJPFED = 14;
    uint32 config_id = 7;
    KDPGIMOOLON AGLMEDOBMAL = 13;
    JGKNADEDNHB LOCHFJEECKL = 15;
    LOEBAOEFMDC COKLIDDAEOH = 9;
}

message GNNGLBEGIKB {
    uint32 GCLADEKCJCG = 4;
    uint32 DPGJKAHLINH = 15;
    uint32 buff_id = 14;
}

message GOLHAKEGKCL {
    uint32 HFNNNGHBHGG = 1;
    uint32 item_id = 5;
    uint32 DCPDNBALDOA = 13;
}

message GPPKIMDCPBM {
    GOLHAKEGKCL FIPDBFMPEKH = 15;
    GOLHAKEGKCL AHMEECFKBDJ = 3;
    BANELIGFLCO CBKLDCBEKCH = 11;
    BANELIGFLCO HMOBMBALLJE = 7;
    GNNGLBEGIKB IFOOEPKGGAG = 10;
    GNNGLBEGIKB CMPNCFCJCNE = 1;
    NEAEMNNKKEF DOMHNBMJGHF = 5;
    NEAEMNNKKEF HKAGPIMFPAG = 9;
    CCOHBABCHAI GAJGLONDGMP = 4;
    AHMFKPIAHCO IJBAMMMBIOA = 2;
    GNNGLBEGIKB EBCGEBEPOJJ = 8;
    NEAEMNNKKEF CKBEEBALAEG = 14;
    NOKANMFKNMM LDIGCPKPNBC = 6;
}

message GetMbtiReportCsReq {
}

message GetMbtiReportScRsp {
    int32 KHMNANHKINB = 10;
    bool is_taken_reward = 1;
    repeated EDGEHPFOKBH BLINEMKKEOG = 4;
    int32 CJBLDKJDLOJ = 7;
    repeated HKNBLADLAAE DMCKDIGKHLB = 13;
    uint32 progress = 5;
    bool JMFNGFKBIFL = 15;
    uint32 retcode = 3;
}

message GetMonopolyDailyReportScRsp {
    NJHAGKGHKJJ OLAONLGLAJO = 10;
    uint32 retcode = 3;
}

message GetMonopolyFriendRankingListCsReq {
    uint32 DEJILEKOCFL = 15;
    uint32 MOKDJLMAKCE = 5;
    uint32 AJLMKACOOAG = 7;
    uint32 AODKNNMBGAD = 10;
    uint32 LJCHENNEOPL = 3;
}

message GetMonopolyFriendRankingListScRsp {
    GetMonopolyFriendRankingListCsReq PONAOKBNIAM = 5;
    uint32 retcode = 8;
    repeated GetMonopolyFriendRankingListCsReq BEDHEKAGAPE = 10;
}

message GetMonopolyInfoCsReq {
}

message GetMonopolyInfoScRsp {
    uint32 retcode = 15;
    BCDIFIIDPIA MALPPHCEOGB = 9;
    CCMCKOKEJNI CICLCCFLALE = 8;
    OCDBIMIBNCD stt = 5;
    HDDLALFAMKO GKMKAEEDCHP = 4;
    FOOFAIFPOOI PNJBEPAAEOF = 2;
    INGKNDHECNF HABJHGPFGEB = 14;
    repeated uint32 CANEJDOMAFA = 11;
    PDNABFBLEPG OCHNMGMDHME = 3;
    ILMFJKCGBCK COOOMDKGODF = 13;
    DBPHHPGNMKC KKKMHNAPFCP = 6;
    FIOENGOHOOJ MOMEIFPICLE = 10;
    NJHAGKGHKJJ OLAONLGLAJO = 1;
}

message GetMonopolyMbtiReportRewardScRsp {
    uint32 retcode = 3;
    ItemList reward_list = 4;
}

message GetSocialEventServerCacheCsReq {
}

message GetSocialEventServerCacheScRsp {
    repeated EOHAFICJPIP OKPHCFLPLGH = 13;
    uint32 retcode = 4;
}

message HDDLALFAMKO {
    repeated uint32 LPBBJFFNACA = 3;
    LAEHICCBBFN KDJACPBDHAE = 8;
}

message HIHEHNIAGPF {
    uint32 FBDENECLHIH = 5;
    uint32 progress = 14;
}

message HKNBLADLAAE {
    uint32 MIPKOFFGPFA = 11;
    uint32 HAFOKMHCGFM = 2;
    uint32 event_id = 12;
}

message IAFJANHGCLL {
}

message ILMFJKCGBCK {
    repeated EIDFCGLODFB EGDNFKHLKKE = 14;
    repeated EIDFCGLODFB DGBEOGGJLOO = 12;
    uint32 COKKNEKDJAJ = 9;
    uint32 LJCCANLCGHI = 6;
    EIDFCGLODFB GOPFOJLIFKN = 11;
}

message INGKNDHECNF {
    repeated GNNGLBEGIKB buff_list = 3;
}

message JGKNADEDNHB {
    uint32 KPGNEABOECG = 3;
    repeated uint32 HDAKGBMLKKI = 9;
    uint32 AHAPDFNPICG = 6;
    repeated NNDKLIBALLC OLGHCHMMMIA = 15;
    uint32 KOMEOMHBCEC = 1;
    uint32 GHKNBIOFLGA = 2;
}

message JPEGNCJDBOM {
    uint32 AFHMLGFILFN = 1;
    uint32 BLLLEIGDMOI = 13;
    uint32 AHAPDFNPICG = 2;
}

message KDPGIMOOLON {
    uint32 PEDFLGGDHDP = 15;
    repeated uint32 KNJMPBHKHCJ = 6;
    repeated uint32 JKOOLMNHPHI = 9;
    repeated uint32 PGMHMPEHPHP = 7;
    bool BDEFAFFDBCC = 10;
}

message KFGILGDFEKE {
    repeated HIHEHNIAGPF AMFDDGGEABC = 9;
    uint32 FNFEKIPGKHJ = 8;
    uint32 NBNCEEGGGFF = 6;
    uint32 pool_id = 11;
    uint32 GCPABINOPNJ = 12;
    repeated HIHEHNIAGPF BADCFEEJKIC = 10;
    string DPIOJAJLOLD = 95;
    string DANMGAEPGML = 1575;
    repeated DDHIEONLIIL JBKMDKKBFFA = 7;
    repeated HIHEHNIAGPF MHNLHEIMBLH = 2;
    repeated HIHEHNIAGPF IOFPLHOGBOD = 15;
    string MGKCFIFICCF = 1018;
    bool BODENACHCHF = 5;
    uint32 IJFPHJAPBCO = 1;
    uint32 FDOPJGFNMMA = 3;
}

enum LAEHICCBBFN {
    LAEHICCBBFN_NLCDGIPGFDJ = 0;
    LAEHICCBBFN_HHKFKGKFNJI = 1;
}

message LNCHJBMIMAF {
    uint32 event_id = 6;
}

message LOEBAOEFMDC {
    uint32 HABHOAMCGLH = 15;
    bool FNFJOCEGFBI = 14;
    uint32 HCFJIJHLJDM = 2;
}

message MonopolyAcceptQuizCsReq {
    repeated NNDKLIBALLC OLGHCHMMMIA = 8;
}

message MonopolyAcceptQuizScRsp {
    uint32 retcode = 1;
    JGKNADEDNHB LOCHFJEECKL = 12;
}

message MonopolyActionResult {
    uint32 trigger_cell_id = 4;
    BAKAELIMIJI source_type = 11;
    uint32 click_cell_id = 12;
    uint32 click_map_id = 8;
    GPPKIMDCPBM detail = 9;
    uint32 effect_type = 2;
    uint32 trigger_map_id = 1;
}

message MonopolyActionResultScNotify {
    repeated MonopolyActionResult BKGPGINCHJI = 9;
}

message MonopolyBuyGoodsCsReq {
    uint32 goods_id = 11;
    uint32 shop_id = 10;
}

message MonopolyBuyGoodsScRsp {
    uint32 goods_id = 8;
    uint32 retcode = 1;
    uint32 shop_id = 7;
}

message MonopolyCellUpdateNotify {
    EIDFCGLODFB GOPFOJLIFKN = 10;
}

message MonopolyCheatDiceCsReq {
    uint32 LAGNINIKEAE = 3;
}

message MonopolyCheatDiceScRsp {
    uint32 retcode = 14;
    uint32 LAGNINIKEAE = 9;
}

message MonopolyClickCellCsReq {
    uint32 IHAOMLEPHOM = 8;
    uint32 map_id = 7;
}

message MonopolyClickCellScRsp {
    uint32 IHAOMLEPHOM = 4;
    uint32 retcode = 1;
    uint32 map_id = 9;
}

message MonopolyConditionUpdateScNotify {
    CCMCKOKEJNI CICLCCFLALE = 13;
}

message MonopolyConfirmRandomCsReq {
    uint32 event_id = 7;
}

message MonopolyConfirmRandomScRsp {
    uint32 retcode = 2;
    NEMIDPFEJFL MOMEIFPICLE = 12;
}

message MonopolyContentUpdateScNotify {
    NEMIDPFEJFL MEGBFFOAFGL = 7;
}

message MonopolyDailySettleScNotify {
    uint32 ICPAPCAJFKK = 1;
    NJHAGKGHKJJ OLAONLGLAJO = 14;
}

message MonopolyEventLoadUpdateScNotify {
    repeated EIDFCGLODFB DGBEOGGJLOO = 2;
    repeated EIDFCGLODFB EGDNFKHLKKE = 11;
}

message MonopolyEventSelectFriendCsReq {
    bool DHLLPOBKLIO = 4;
    uint32 LPDFMJPFGJH = 3;
}

message MonopolyEventSelectFriendScRsp {
    uint32 add_coin = 10;
    uint32 retcode = 12;
    uint32 NLGNNDIFGGF = 1;
}

message MonopolyGameBingoFlipCardCsReq {
    uint32 LKFIGBGPEJB = 5;
}

message MonopolyGameBingoFlipCardScRsp {
    uint32 retcode = 8;
    uint32 total_score = 5;
    repeated uint32 KNJMPBHKHCJ = 9;
    bool BDEFAFFDBCC = 4;
}

message MonopolyGameGachaCsReq {
}

message MonopolyGameGachaScRsp {
    uint32 retcode = 1;
    repeated uint32 CLGGKLNPLCK = 12;
}

message MonopolyGameRaiseRatioCsReq {
    uint32 LCEHCAOINBN = 9;
}

message MonopolyGameSettleScNotify {
    GLMGJFEEJHD AJGOEJHKOKE = 8;
    ItemList NGADCEHJHBE = 11;
    ItemList item_list = 2;
}

message MonopolyGetDailyInitItemScRsp {
    uint32 MKEDABICJPH = 5;
    uint32 retcode = 12;
    int64 DJMLHBFEMBE = 3;
    uint32 AJDOFHNCOLP = 10;
    uint32 FOFGDAJJPEM = 9;
    uint32 AEDFGDEAOBD = 6;
    uint32 PKLPCBACEMA = 11;
}

message MonopolyGetRafflePoolInfoCsReq {
}

message MonopolyGetRafflePoolInfoScRsp {
    uint32 retcode = 4;
    BCDIFIIDPIA MALPPHCEOGB = 14;
}

message MonopolyGetRaffleTicketCsReq {
    uint32 pool_id = 7;
}

message MonopolyGetRaffleTicketScRsp {
    uint32 retcode = 15;
    repeated DDHIEONLIIL HDLPEKIMAJB = 5;
    uint32 pool_id = 12;
}

message MonopolyGetRegionProgressCsReq {
}

message MonopolyGetRegionProgressScRsp {
    uint32 CNGMMDKCBND = 1;
    uint32 HEIHPAPJHID = 4;
    uint32 retcode = 5;
}

message MonopolyGiveUpCurContentCsReq {
    uint32 content_id = 2;
}

message MonopolyGiveUpCurContentScRsp {
    uint32 retcode = 7;
}

message MonopolyGuessChooseCsReq {
    uint32 HCFJIJHLJDM = 8;
}

message MonopolyGuessChooseScRsp {
    uint32 HCFJIJHLJDM = 12;
    uint32 retcode = 11;
}

message MonopolyGuessDrawScNotify {
    repeated DCMHLOEGFBM KHLFDHANJCO = 9;
}

message MonopolyLikeCsReq {
    uint32 teleport_id = 14;
}

message MonopolyLikeScNotify {
    uint32 DOHOMJBJLLG = 8;
    repeated uint32 LPBBJFFNACA = 1;
}

message MonopolyLikeScRsp {
    ItemList reward_list = 5;
    uint32 retcode = 6;
    uint32 teleport_id = 4;
}

message MonopolyMoveCsReq {
    uint32 AHNGICEEADK = 14;
    uint32 CPFGHPCBFOF = 4;
}

message MonopolyMoveScRsp {
    repeated EIDFCGLODFB AJGMLOIONPK = 1;
    uint32 retcode = 15;
    ILMFJKCGBCK COOOMDKGODF = 5;
}

message MonopolyQuizDurationChangeScNotify {
    repeated JPEGNCJDBOM DGNGMJMPFGK = 9;
}

message MonopolyReRollRandomCsReq {
    uint32 event_id = 1;
}

message MonopolyReRollRandomScRsp {
    uint32 retcode = 5;
    NEMIDPFEJFL MOMEIFPICLE = 11;
}

message MonopolyRollDiceCsReq {
}

message MonopolyRollDiceScRsp {
    uint32 retcode = 11;
    uint32 roll_result = 12;
}

message MonopolyRollRandomCsReq {
    uint32 event_id = 12;
}

message MonopolyRollRandomScRsp {
    NEMIDPFEJFL MOMEIFPICLE = 7;
    uint32 event_id = 8;
    uint32 retcode = 15;
}

message MonopolyScrachRaffleTicketCsReq {
    uint32 pool_id = 1;
    uint64 BBPGHFJOADI = 7;
}

message MonopolyScrachRaffleTicketScRsp {
    uint32 pool_id = 1;
    uint32 retcode = 9;
    uint64 BBPGHFJOADI = 6;
}

message MonopolySelectOptionCsReq {
    uint32 event_id = 7;
    uint32 HAFOKMHCGFM = 6;
}

message MonopolySelectOptionScRsp {
    repeated HKNBLADLAAE DMCKDIGKHLB = 10;
    uint32 HAFOKMHCGFM = 3;
    uint32 retcode = 7;
    NEMIDPFEJFL MOMEIFPICLE = 6;
    uint32 event_id = 11;
}

message MonopolySocialEventEffectScNotify {
    repeated EOHAFICJPIP OKPHCFLPLGH = 1;
}

message MonopolySttUpdateScNotify {
    OCDBIMIBNCD stt = 4;
}

message MonopolyTakePhaseRewardCsReq {
    repeated uint32 IICEKEPFMJO = 11;
}

message MonopolyTakePhaseRewardScRsp {
    ItemList reward_list = 4;
    repeated uint32 IICEKEPFMJO = 9;
    uint32 retcode = 3;
}

message MonopolyTakeRaffleTicketRewardCsReq {
    uint64 BBPGHFJOADI = 6;
    uint32 pool_id = 1;
}

message MonopolyTakeRaffleTicketRewardScRsp {
    uint32 retcode = 6;
    uint32 BBPGHFJOADI = 10;
    ItemList reward_list = 2;
    uint32 pool_id = 14;
}

message MonopolyUpgradeAssetCsReq {
    uint32 AGMNNNMDIPG = 11;
}

enum NADDHEILBBN {
    NADDHEILBBN_BPOCOHFIAOH = 0;
    NADDHEILBBN_HOPAGBFPBGP = 1;
    NADDHEILBBN_MDJCIKAGEKH = 2;
    NADDHEILBBN_CIHFGJDCHIA = 3;
}

message NCPJGBCCGGI {
    uint32 CBILPMICEKC = 8;
}

message NEAEMNNKKEF {
    uint32 BGKDJKCFEKD = 12;
    uint32 DDFFJEBLCAN = 4;
}

message NEMIDPFEJFL {
    uint32 GCLADEKCJCG = 12;
    NIFKIMAANFJ NHONHFPBEBG = 8;
    LNCHJBMIMAF MPBPBBLAHNM = 14;
    ADNCPPCPLLH ONCBJHBKBLB = 6;
    NCPJGBCCGGI CEFDDDAIMMD = 1;
    DCAJAKJAJNL MOFNIOJHBBL = 10;
    DKHCBKNGOMF AJGOEJHKOKE = 2;
    GALCNKIAHNN ENFIEFPPCIC = 11;
    OFPGDJJKGKJ BJHKLNNKPPB = 4;
    DFKABDLJMJO HCLAEGDLOBD = 13;
}

message NIFKIMAANFJ {
    uint32 event_id = 13;
}

message NJHAGKGHKJJ {
    uint32 HNENMGMGONM = 1;
    uint32 PKHIADLBDDP = 11;
    uint32 JDMNGBJDLBN = 13;
    uint32 KDFDFBHKCNG = 3;
    bool DKJBKELKKFO = 4;
    uint32 IFDIIODCFLC = 14;
    uint32 DBPJBMMGAHH = 5;
    uint32 OECIPJIPKEG = 8;
    uint32 EEKPBPFPNIK = 15;
}

message NNDKLIBALLC {
    uint32 JJKPBPLAGAN = 8;
    uint32 KPMHGGHLOHB = 9;
}

message NOKANMFKNMM {
    uint32 PJFPLAFEHKK = 3;
}

message OCDBIMIBNCD {
    repeated uint32 POHBLAMKNJH = 11;
    repeated uint32 LEIJJGDJECI = 4;
}

message OFPGDJJKGKJ {
    uint32 event_id = 1;
    uint32 JMBGMIPLLJI = 12;
    repeated uint32 MJMJOMDLOHI = 14;
    uint32 IJJFAPBJMOD = 2;
    uint32 GKKNMDDNOJF = 13;
}

message PDNABFBLEPG {
    bool GNIHCOPOLJB = 8;
    uint32 ALMKIPNHAFM = 9;
    uint32 item_value = 14;
    uint32 MGJFFPIAOMI = 3;
    bool BLBFMKKBELI = 6;
    uint32 KEEOBECJNIP = 11;
}
