syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdMarbleType {
    CmdMarbleType_None = 0;
    CmdMarbleType_MarbleLevelFinishCsReq = 8290;
    CmdMarbleType_MarblePvpDataUpdateScNotify = 8284;
    CmdMarbleType_MarbleShopBuyCsReq = 8279;
    CmdMarbleType_MarbleGetDataScRsp = 8285;
    CmdMarbleType_MarbleShopBuyScRsp = 8282;
    CmdMarbleType_MarbleLevelFinishScRsp = 8283;
    CmdMarbleType_MarbleUnlockSealScNotify = 8281;
    CmdMarbleType_MarbleUpdateShownSealCsReq = 8277;
    CmdMarbleType_MarbleGetDataCsReq = 8275;
    CmdMarbleType_MarbleUpdateShownSealScRsp = 8280;
}

message MarbleGetDataCsReq {
}

message MarbleGetDataScRsp {
    repeated uint32 IKGIIIJLLBL = 2;
    repeated uint32 KJJCIMANKOA = 9;
    int32 score_id = 3;
    repeated uint32 LHDIMCDHCEO = 13;
    uint32 retcode = 10;
}

message MarblePvpDataUpdateScNotify {
    int32 score_id = 7;
}

message MarbleShopBuyCsReq {
    repeated uint32 EGCLLKDHIAE = 5;
}

message MarbleShopBuyScRsp {
    repeated uint32 EGCLLKDHIAE = 15;
    uint32 retcode = 10;
}

message MarbleUnlockSealScNotify {
    repeated uint32 EGCLLKDHIAE = 3;
}

message MarbleUpdateShownSealCsReq {
    repeated uint32 GFADCIHMDNN = 9;
}

message MarbleUpdateShownSealScRsp {
    repeated uint32 GFADCIHMDNN = 6;
    uint32 retcode = 10;
}
