syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BAEFMEJJIBI {
    uint32 CEAMLKCMMGD = 4;
    GBAEPOLFFMG pos = 6;
}

message BuyNpcStuffCsReq {
    uint32 CEAMLKCMMGD = 12;
}

message BuyNpcStuffScRsp {
    uint32 CEAMLKCMMGD = 5;
    uint32 retcode = 12;
}

message CDNPKGOKEPK {
    uint32 ELAENEOBAJD = 1;
    repeated uint32 MNBMDLBDCBB = 2;
    repeated FFEEHEBBLCI PMIFFBHOOOO = 11;
}

message CHMJIHDLDEB {
    uint32 PIACMPBJOIK = 8;
}

enum CmdMuseumType {
    CmdMuseumType_None = 0;
    CmdMuseumType_MuseumTargetRewardNotify = 4366;
    CmdMuseumType_MuseumRandomEventQueryCsReq = 4315;
    CmdMuseumType_UpgradeAreaStatCsReq = 4304;
    CmdMuseumType_RemoveStuffFromAreaScRsp = 4326;
    CmdMuseumType_GetMuseumInfoCsReq = 4334;
    CmdMuseumType_GetStuffScNotify = 4373;
    CmdMuseumType_MuseumTakeCollectRewardCsReq = 4309;
    CmdMuseumType_UpgradeAreaCsReq = 4380;
    CmdMuseumType_SetStuffToAreaCsReq = 4356;
    CmdMuseumType_FinishCurTurnScRsp = 4365;
    CmdMuseumType_UpgradeAreaStatScRsp = 4362;
    CmdMuseumType_MuseumRandomEventQueryScRsp = 4364;
    CmdMuseumType_MuseumRandomEventStartScNotify = 4388;
    CmdMuseumType_MuseumTakeCollectRewardScRsp = 4324;
    CmdMuseumType_GetMuseumInfoScRsp = 4382;
    CmdMuseumType_BuyNpcStuffCsReq = 4379;
    CmdMuseumType_MuseumFundsChangedScNotify = 4348;
    CmdMuseumType_MuseumRandomEventSelectScRsp = 4341;
    CmdMuseumType_UpgradeAreaScRsp = 4371;
    CmdMuseumType_MuseumTargetStartNotify = 4357;
    CmdMuseumType_BuyNpcStuffScRsp = 4339;
    CmdMuseumType_FinishCurTurnCsReq = 4372;
    CmdMuseumType_RemoveStuffFromAreaCsReq = 4398;
    CmdMuseumType_MuseumTargetMissionFinishNotify = 4346;
    CmdMuseumType_MuseumInfoChangedScNotify = 4349;
    CmdMuseumType_SetStuffToAreaScRsp = 4391;
    CmdMuseumType_MuseumRandomEventSelectCsReq = 4381;
    CmdMuseumType_GetExhibitScNotify = 4399;
}

message FCCDKHNGIPH {
    uint32 area_id = 4;
    uint32 level = 7;
    uint32 MLDLNLGBMHN = 13;
    uint32 FJPJFHPNKBH = 14;
    repeated BAEFMEJJIBI DHIOHIOPCGP = 15;
    uint32 PELHCNILCBP = 1;
}

message FEHHKDIIENA {
    uint32 CEAMLKCMMGD = 10;
    uint32 PIKEPJNDJPE = 11;
}

message FFEEHEBBLCI {
    repeated uint32 DAHOMKDLEGI = 2;
    MuseumRandomEventState state = 6;
    uint32 OMILGFHKGBC = 5;
    uint32 event_id = 12;
    uint32 JGPIOFGPBGE = 10;
    uint32 JJBKGGDAGIM = 13;
    uint32 PKDANDJFAON = 9;
}

message FGFJNANBJJI {
    uint32 CLLLEMMKDMB = 15;
    bool is_finish = 2;
}

message FinishCurTurnCsReq {
    uint32 IDFANGELPEE = 13;
}

message FinishCurTurnScRsp {
    uint32 retcode = 15;
}

enum GBAEPOLFFMG {
    GBAEPOLFFMG_NLCDGIPGFDJ = 0;
    GBAEPOLFFMG_FBLHLHCGMKO = 1;
    GBAEPOLFFMG_GNEIJHBGCHG = 2;
    GBAEPOLFFMG_JNKMJKBDGPL = 3;
}

message GetMuseumInfoCsReq {
}

message GetMuseumInfoScRsp {
    CDNPKGOKEPK PKJCHLDHKBL = 2;
    repeated FCCDKHNGIPH area_list = 9;
    uint32 cur_fund = 5;
    uint32 NEHFEBHDGIK = 14;
    repeated FEHHKDIIENA DHIOHIOPCGP = 6;
    repeated uint32 ONJEOMGPGLJ = 11;
    uint32 ONCBJHBKBLB = 3;
    uint32 exp = 10;
    KPCNNOGGIDO target = 15;
    uint32 level = 1;
    uint32 EKGPINKBLED = 4;
    repeated uint32 BILNKFBKOBC = 7;
    uint32 KAADGPOLIEN = 8;
    uint32 retcode = 12;
}

message KPCNNOGGIDO {
    repeated FGFJNANBJJI CBEFDHFFNLN = 3;
    uint32 CLPAAFFFBKK = 14;
    uint32 MGLEKDEAJBB = 9;
    uint32 KFGLDLFBFFB = 6;
    uint32 MLBMDLBKEEM = 10;
    uint32 MJOKDHMJBEH = 8;
}

message MuseumRandomEventQueryCsReq {
}

message MuseumRandomEventQueryScRsp {
    CDNPKGOKEPK info = 9;
    uint32 retcode = 13;
}

message MuseumRandomEventSelectCsReq {
    uint32 JGPIOFGPBGE = 15;
    uint32 event_id = 8;
}

message MuseumRandomEventSelectScRsp {
    uint32 retcode = 2;
    uint32 JGPIOFGPBGE = 14;
    uint32 event_id = 13;
}

enum MuseumRandomEventState {
    MuseumRandomEventState_None = 0;
    MuseumRandomEventState_Start = 1;
    MuseumRandomEventState_Processing = 2;
    MuseumRandomEventState_Finish = 3;
}

message RemoveStuffFromAreaCsReq {
    uint32 CEAMLKCMMGD = 5;
}

message RemoveStuffFromAreaScRsp {
    uint32 retcode = 8;
    uint32 CEAMLKCMMGD = 3;
}

message SetStuffToAreaCsReq {
    uint32 PIKEPJNDJPE = 8;
    GBAEPOLFFMG pos = 4;
    uint32 CEAMLKCMMGD = 11;
}

message SetStuffToAreaScRsp {
    uint32 PIKEPJNDJPE = 8;
    uint32 retcode = 7;
    uint32 CEAMLKCMMGD = 15;
    GBAEPOLFFMG pos = 6;
}

enum StatType {
    StatType_None = 0;
    StatType_Art = 1;
    StatType_Culture = 2;
    StatType_Popular = 3;
}

message UpgradeAreaCsReq {
    uint32 area_id = 13;
    uint32 level = 2;
}

message UpgradeAreaScRsp {
    uint32 area_id = 7;
    uint32 level = 8;
    uint32 retcode = 14;
}

message UpgradeAreaStatCsReq {
    StatType GNBKDCHLDGL = 13;
    uint32 level = 6;
    uint32 area_id = 1;
}

message UpgradeAreaStatScRsp {
    uint32 level = 15;
    uint32 area_id = 2;
    StatType GNBKDCHLDGL = 7;
    uint32 retcode = 10;
}
