syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ALNGMGOJDOA {
    repeated MLHLIMIJHDD DBINCLPHEFN = 14;
    map<uint32, uint32> GMONIMLFKFC = 5;
    map<uint32, uint32> AEOMEFEMBJI = 7;
    repeated HPIEHAMDJAP MJNNNJPDKDI = 6;
}

enum CmdMatchThreeModuleType {
    CmdMatchThreeModuleType_None = 0;
    CmdMatchThreeModuleType_MatchThreeLevelEndScRsp = 7424;
    CmdMatchThreeModuleType_MatchThreeV2BattleItemLevelUpCsReq = 7438;
    CmdMatchThreeModuleType_MatchThreeSetBirdPosCsReq = 7422;
    CmdMatchThreeModuleType_MatchThreeV2BattleItemLevelUpScRsp = 7421;
    CmdMatchThreeModuleType_MatchThreeV2PvpFinishScNotify = 7414;
    CmdMatchThreeModuleType_MatchThreeV2SetBirdPosCsReq = 7412;
    CmdMatchThreeModuleType_MatchThreeV2GetDataCsReq = 7437;
    CmdMatchThreeModuleType_MatchThreeSyncDataScNotify = 7408;
    CmdMatchThreeModuleType_MatchThreeRoyaleFinishScNotify = 7442;
    CmdMatchThreeModuleType_MatchThreeGetDataScRsp = 7429;
    CmdMatchThreeModuleType_MatchThreeSetBirdPosScRsp = 7432;
    CmdMatchThreeModuleType_MatchThreeGetDataCsReq = 7436;
    CmdMatchThreeModuleType_MatchThreeV2SetBirdPosScRsp = 7401;
    CmdMatchThreeModuleType_MatchThreeV2ScNotify = 7407;
    CmdMatchThreeModuleType_MatchThreeLevelEndCsReq = 7444;
    CmdMatchThreeModuleType_MatchThreeV2LevelEndScRsp = 7419;
    CmdMatchThreeModuleType_MatchThreeV2LevelEndCsReq = 7417;
    CmdMatchThreeModuleType_MatchThreeV2GetDataScRsp = 7420;
}

message HDKJPKPEJFO {
    uint32 level_id = 13;
    repeated uint32 GKCABEGBOCG = 12;
}

message HPIEHAMDJAP {
    uint32 KKHPKMAHDMK = 12;
    uint32 level_id = 3;
}

message JKEBEAKOHJJ {
    uint32 EECIJBLGLNG = 14;
    repeated KVP GOBIPJPDBFG = 8;
    repeated HDKJPKPEJFO NKHIIMHCLCD = 4;
    uint32 JNAOKJKFLHL = 2;
    repeated KVP BFCMLMLIHHM = 13;
    repeated KVP KIOIBLGKFCJ = 9;
    repeated KPCHPLEJCKC DBINCLPHEFN = 5;
}

message JPDGPEOBBNJ {
}

message KPCHPLEJCKC {
    uint32 pos = 1;
    uint32 count = 7;
    uint32 LALGADHLMCB = 13;
    uint32 HBONKLEOEEI = 5;
}

message LAJGLHCCNED {
    uint32 BMANBMAOLLD = 1;
    uint32 CKDCNKNMEAI = 2;
    uint32 EKPKADNENAG = 3;
    uint32 FIIPIFLPEDB = 4;
    uint32 MPNGHAGHAIM = 5;
    uint32 DNDAOOCDNGC = 6;
    uint32 GMNONMGKBFI = 7;
    uint32 CJHGLLNBLJH = 8;
    uint32 ONLANGHDIPJ = 9;
    uint32 CPHOGFPNKLC = 10;
    uint32 JOBFJAPJDBA = 11;
    uint32 PIPOCNHBHAC = 12;
    uint32 HFOPGJFDIHM = 13;
    uint32 CGHLEEAOJGO = 14;
}

message MLHLIMIJHDD {
    uint32 count = 1;
    uint32 pos = 9;
    uint32 LALGADHLMCB = 5;
    uint32 HBONKLEOEEI = 14;
}

message MatchThreeLevelEndCsReq {
    uint32 HBONKLEOEEI = 5;
    map<uint32, uint32> GMONIMLFKFC = 15;
    string uuid = 8;
    uint32 KKHPKMAHDMK = 1;
    uint32 level_id = 4;
    uint32 LALGADHLMCB = 6;
}

message MatchThreeLevelEndScRsp {
    uint32 retcode = 11;
    uint32 level_id = 10;
    uint32 KKHPKMAHDMK = 7;
}

message MatchThreeSyncDataScNotify {
    ALNGMGOJDOA GJFKKFFJDAH = 15;
}

message MatchThreeV2BattleItemLevelUpCsReq {
    uint32 IGOOJKMPMDC = 8;
    uint32 FMEHKPKHGJA = 3;
}

message MatchThreeV2BattleItemLevelUpScRsp {
    uint32 IGOOJKMPMDC = 6;
    uint32 retcode = 9;
    uint32 FMEHKPKHGJA = 1;
}

message MatchThreeV2LevelEndCsReq {
    uint32 JGIFDFLDBPB = 15;
    uint32 GFBAHEODFNA = 5;
    string uuid = 2;
    repeated KVP MONKDLNMMBK = 6;
    repeated uint32 EEDLBJGGLKD = 1;
    uint32 level_id = 13;
    uint32 EOHGLCJAMKN = 14;
    uint32 HBONKLEOEEI = 10;
}

message MatchThreeV2LevelEndScRsp {
    HDKJPKPEJFO OEIBHLMDJKA = 1;
    ItemList DBDIGIEPMBB = 5;
    uint32 level_id = 14;
    KPCHPLEJCKC IEGCHPIHPJN = 8;
    uint32 AFLCNNAJAGB = 3;
    uint32 JNAOKJKFLHL = 11;
    repeated ItemList DOBNEFKPMPB = 10;
    uint32 retcode = 4;
}

message MatchThreeV2PvpFinishScNotify {
    uint32 OJNGBIBGHBL = 5;
    NPPEMMILLCO reason = 1;
    LAJGLHCCNED JDFPKAMFHAP = 2;
    JKEBEAKOHJJ BJBJLBIOPKA = 12;
    FightGameMode game_mode = 13;
    uint32 BCAKPNCHIIJ = 11;
}

message MatchThreeV2ScNotify {
    JKEBEAKOHJJ BJBJLBIOPKA = 15;
}

message MatchThreeV2SetBirdPosCsReq {
    uint32 pos = 12;
    uint32 HBONKLEOEEI = 13;
}

message MatchThreeV2SetBirdPosScRsp {
    uint32 HBONKLEOEEI = 12;
    uint32 LIDGCJIKIEG = 9;
    uint32 retcode = 11;
    uint32 pos = 3;
}

enum NPPEMMILLCO {
    NPPEMMILLCO_HGLIFJGHADE = 0;
    NPPEMMILLCO_OPCKNBHNBOA = 1;
    NPPEMMILLCO_CEABDBJPIOF = 2;
    NPPEMMILLCO_HONKPOMPEOO = 3;
    NPPEMMILLCO_HOFPNHIBDKL = 4;
    NPPEMMILLCO_EHNIPLNEEDI = 5;
    NPPEMMILLCO_FAODKNDLNPF = 6;
    NPPEMMILLCO_JCNBPNHEBBH = 7;
}

message PBDKDFCOAPB {
}

message POGMMMGBNCH {
    uint32 HBONKLEOEEI = 9;
    uint32 pos = 2;
}
