syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdMessageType {
    CmdMessageType_None = 0;
    CmdMessageType_GetNpcStatusScRsp = 2739;
    CmdMessageType_FinishItemIdScRsp = 2791;
    CmdMessageType_GetNpcMessageGroupCsReq = 2734;
    CmdMessageType_GetNpcStatusCsReq = 2779;
    CmdMessageType_GetNpcMessageGroupScRsp = 2782;
    CmdMessageType_FinishItemIdCsReq = 2756;
    CmdMessageType_FinishPerformSectionIdScRsp = 2799;
    CmdMessageType_FinishSectionIdScRsp = 2726;
    CmdMessageType_GetMissionMessageInfoCsReq = 2772;
    CmdMessageType_FinishMultiPerformSectionIdScRsp = 2771;
    CmdMessageType_FinishMultiPerformSectionIdCsReq = 2780;
    CmdMessageType_GetMissionMessageInfoScRsp = 2765;
    CmdMessageType_FinishSectionIdCsReq = 2798;
    CmdMessageType_FinishPerformSectionIdCsReq = 2773;
}

message EJFBKAEEDJK {
}

message FPDBFGBJOFD {
    uint32 MGPGDLIJKLM = 8;
    repeated MessageItem DPPAFBAHEFH = 2;
}

message FinishItemIdCsReq {
    uint32 text_id = 14;
    uint32 item_id = 11;
}

message FinishItemIdScRsp {
    uint32 retcode = 10;
    uint32 item_id = 6;
    uint32 text_id = 12;
}

message FinishMultiPerformSectionIdScRsp {
    uint32 PLDKENJLKME = 10;
    repeated LGMDACIPFHL JCALNIODLLN = 3;
}

message FinishPerformSectionIdCsReq {
    FPDBFGBJOFD HBMLBLAJKKL = 3;
}

message FinishPerformSectionIdScRsp {
    uint32 retcode = 2;
    LGMDACIPFHL MIINDKFMBBM = 11;
}

message FinishSectionIdCsReq {
    uint32 section_id = 12;
}

message FinishSectionIdScRsp {
    uint32 section_id = 12;
    ItemList reward = 1;
    uint32 retcode = 4;
}

message GetNpcMessageGroupCsReq {
    repeated uint32 contact_id_list = 14;
}

message GetNpcMessageGroupScRsp {
    repeated MessageGroup message_group_list = 15;
    uint32 retcode = 8;
}

message GetNpcStatusCsReq {
}

message GetNpcStatusScRsp {
    uint32 retcode = 9;
    repeated NpcStatus npc_status_list = 5;
}

message LGMDACIPFHL {
    uint32 MGPGDLIJKLM = 2;
    ItemList EBMIJAAKMMH = 4;
    repeated MessageItem DPPAFBAHEFH = 3;
}

message MessageGroup {
    uint32 id = 8;
    MessageGroupStatus status = 9;
    uint32 message_section_id = 7;
    int64 refresh_time = 1;
    repeated MessageSection message_section_list = 6;
}

message MessageItem {
    uint32 text_id = 10;
    uint32 item_id = 5;
}

message MessageSection {
    repeated uint32 message_item_list = 4;
    uint32 frozen_item_id = 6;
    uint32 id = 13;
    repeated MessageItem item_list = 1;
    MessageSectionStatus status = 5;
}

message NpcStatus {
    bool is_finish = 3;
    uint32 npc_id = 4;
}
