syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AMKBFMCOIHK {
    CGOGDJKALMH source_type = 13;
    DifficultyAdjustmentType ANJMFPKJHOH = 2;
    uint32 id = 9;
}

message BCBHFBPADEE {
    uint32 JNOPBGBACOO = 15;
    uint32 MGGNKENIPFC = 3;
}

message BKAHEDAHNHL {
    uint32 gold = 13;
    uint32 NBFJHDJBLCF = 3;
}

message BPAGBAALHMP {
    uint32 BLMAEGGMCHJ = 15;
    uint32 level = 8;
    bool is_perfect = 11;
    uint32 EGKNHHFDJHM = 3;
}

enum CGOGDJKALMH {
    CGOGDJKALMH_FHFJLAIAGEH = 0;
    CGOGDJKALMH_FMDDNENDJOJ = 1;
    CGOGDJKALMH_JIBJFDIJCNM = 2;
}

message CancelDirectDeliveryNoticeCsReq {
    uint32 HFHHKGFNGFC = 11;
}

message CancelDirectDeliveryNoticeScRsp {
    uint32 HFHHKGFNGFC = 1;
    uint32 retcode = 10;
}

enum CmdMiscModuleType {
    CmdMiscModuleType_None = 0;
    CmdMiscModuleType_GetUnreleasedBlockInfoCsReq = 4155;
    CmdMiscModuleType_TakePictureCsReq = 4156;
    CmdMiscModuleType_CycleScoreRewardDestroyExceedRewardScRsp = 4111;
    CmdMiscModuleType_GetSwitchMascotDataScRsp = 4140;
    CmdMiscModuleType_CancelDirectDeliveryNoticeCsReq = 4158;
    CmdMiscModuleType_CycleScoreRewardGetDataScRsp = 4130;
    CmdMiscModuleType_SubmitOrigamiItemCsReq = 4104;
    CmdMiscModuleType_CycleScoreRewardUpdateInfoScNotify = 4187;
    CmdMiscModuleType_GetShareDataScRsp = 4139;
    CmdMiscModuleType_UpdateMovieRacingDataCsReq = 4141;
    CmdMiscModuleType_MazeKillDirectScRsp = 4101;
    CmdMiscModuleType_SecurityReportScRsp = 4165;
    CmdMiscModuleType_DifficultyAdjustmentGetDataScRsp = 4114;
    CmdMiscModuleType_CycleScoreRewardTakeRewardCsReq = 4160;
    CmdMiscModuleType_TakePictureScRsp = 4191;
    CmdMiscModuleType_TriggerVoiceScRsp = 4171;
    CmdMiscModuleType_UpdateGunPlayDataScRsp = 4109;
    CmdMiscModuleType_CancelCacheNotifyCsReq = 4173;
    CmdMiscModuleType_CancelDirectDeliveryNoticeScRsp = 4121;
    CmdMiscModuleType_CancelCacheNotifyScRsp = 4199;
    CmdMiscModuleType_SwitchMascotUpdateScNotify = 4183;
    CmdMiscModuleType_GetMovieRacingDataScRsp = 4181;
    CmdMiscModuleType_CycleScoreRewardGetDataCsReq = 4102;
    CmdMiscModuleType_GetMovieRacingDataCsReq = 4164;
    CmdMiscModuleType_GetOrigamiPropInfoScRsp = 4148;
    CmdMiscModuleType_GetShareDataCsReq = 4179;
    CmdMiscModuleType_GetUnreleasedBlockInfoScRsp = 4175;
    CmdMiscModuleType_GetGunPlayDataCsReq = 4157;
    CmdMiscModuleType_DifficultyAdjustmentUpdateDataScRsp = 4123;
    CmdMiscModuleType_UpdateMovieRacingDataScRsp = 4138;
    CmdMiscModuleType_ShareScRsp = 4182;
    CmdMiscModuleType_DifficultyAdjustmentUpdateDataCsReq = 4105;
    CmdMiscModuleType_SecurityReportCsReq = 4172;
    CmdMiscModuleType_GetGunPlayDataScRsp = 4146;
    CmdMiscModuleType_TriggerVoiceCsReq = 4180;
    CmdMiscModuleType_DirectDeliveryScNotify = 4108;
    CmdMiscModuleType_GetOrigamiPropInfoCsReq = 4149;
    CmdMiscModuleType_CycleScoreRewardDestroyExceedRewardCsReq = 4170;
    CmdMiscModuleType_MazeKillDirectCsReq = 4144;
    CmdMiscModuleType_CycleScoreRewardTakeRewardScRsp = 4189;
    CmdMiscModuleType_UpdateGunPlayDataCsReq = 4166;
    CmdMiscModuleType_GetSwitchMascotDataCsReq = 4143;
    CmdMiscModuleType_ShareCsReq = 4134;
    CmdMiscModuleType_SubmitOrigamiItemScRsp = 4162;
    CmdMiscModuleType_DifficultyAdjustmentGetDataCsReq = 4124;
}

message DDOOEDOKEPF {
    GAAMBBFPCHB NFEDANFBIBE = 12;
    uint32 retcode = 4;
}

message DifficultyAdjustmentGetDataCsReq {
}

message DifficultyAdjustmentGetDataScRsp {
    uint32 retcode = 6;
    repeated AMKBFMCOIHK content_package_list = 10;
}

enum DifficultyAdjustmentType {
    DifficultyAdjustmentType_DifficultyAjustmentTypeDefault = 0;
    DifficultyAdjustmentType_DifficultyAjustmentTypeEasy = 1;
}

message DifficultyAdjustmentUpdateDataCsReq {
    AMKBFMCOIHK data = 5;
}

message DifficultyAdjustmentUpdateDataScRsp {
    AMKBFMCOIHK data = 2;
    repeated AMKBFMCOIHK content_package_list = 15;
    uint32 retcode = 11;
}

message DirectDeliveryScNotify {
    repeated ItemList DJOBNPIAEJP = 10;
    uint32 HFHHKGFNGFC = 8;
}

message EABIMAPLLLL {
    GAAMBBFPCHB NFEDANFBIBE = 7;
}

enum FDJADOEAOLE {
    FDJADOEAOLE_OIDDFJEFIPF = 0;
    FDJADOEAOLE_AHGEIJFIGKE = 1;
    FDJADOEAOLE_PKHPJIKJMDO = 2;
    FDJADOEAOLE_HFGBOOLJDNA = 3;
    FDJADOEAOLE_ENDLJOAKNPI = 4;
    FDJADOEAOLE_KLMEOKHGFCF = 5;
}

message FECGDOJFDIM {
    uint32 retcode = 7;
    ItemList reward = 2;
    repeated uint32 NGKOFMBBGNL = 15;
    GAAMBBFPCHB NFEDANFBIBE = 13;
}

message FPBDJBIFJHA {
}

message GAAMBBFPCHB {
    uint32 PMJGAJGIFOA = 11;
    int64 end_time = 15;
    repeated uint32 OPLNKCOLCKJ = 7;
    int64 start_time = 5;
}

message GetGunPlayDataCsReq {
}

message GetGunPlayDataScRsp {
    repeated BPAGBAALHMP OHOLABHLCKL = 9;
    uint32 retcode = 13;
}

message GetMovieRacingDataCsReq {
}

message GetMovieRacingDataScRsp {
    repeated HDAHFLMBAAB HNIAEGMMPKD = 6;
    uint32 retcode = 11;
}

message GetShareDataCsReq {
}

message GetShareDataScRsp {
    uint32 retcode = 14;
    repeated BCBHFBPADEE MNCJMIOONPE = 3;
}

message GetSwitchMascotDataCsReq {
    uint32 NBFJHDJBLCF = 3;
}

message GetSwitchMascotDataScRsp {
    uint32 NBFJHDJBLCF = 12;
    repeated BKAHEDAHNHL JNOEHPJJPOF = 4;
    uint32 retcode = 7;
}

message HDAHFLMBAAB {
    uint32 HFENOFPKNPJ = 3;
    MovieRacingType type = 1;
    uint32 EGKNHHFDJHM = 8;
    uint32 level = 2;
}

message JDAALEACPKL {
    uint32 KPKEBLOEFCP = 3;
}

message JOIGBKBEGOB {
}

message LIOGDHEFOGD {
}

message MazeKillDirectCsReq {
    uint32 FABPLNCIGPK = 9;
    FDJADOEAOLE source_type = 1;
    repeated uint32 entity_list = 7;
}

message MazeKillDirectScRsp {
    uint32 retcode = 15;
    repeated uint32 entity_list = 8;
}

enum MovieRacingType {
    MovieRacingType_MovieRacingOverTake = 0;
    MovieRacingType_MovieRacingOverTakeEndless = 1;
    MovieRacingType_MovieRacingShooting = 2;
    MovieRacingType_MovieRacingShootingEndless = 3;
}

message ShareCsReq {
    uint32 MGGNKENIPFC = 2;
}

message ShareScRsp {
    BCBHFBPADEE NMOKJJMNICM = 13;
    ItemList reward = 7;
    uint32 retcode = 9;
}

message SwitchMascotUpdateScNotify {
    repeated BKAHEDAHNHL JNOEHPJJPOF = 12;
    bool EBLPGLFJNEL = 13;
}

message UpdateGunPlayDataCsReq {
    uint32 group_id = 4;
    BPAGBAALHMP AOPPLPDBEHK = 10;
    uint32 GIJOPFIAMIA = 13;
    uint64 uuid = 2;
}

message UpdateGunPlayDataScRsp {
    uint32 retcode = 14;
    BPAGBAALHMP AOPPLPDBEHK = 13;
}

message UpdateMovieRacingDataCsReq {
    HDAHFLMBAAB LJEPIAIDJFC = 5;
}

message UpdateMovieRacingDataScRsp {
    HDAHFLMBAAB LJEPIAIDJFC = 9;
    uint32 retcode = 5;
}
