syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdMultiplayerType {
    CmdMultiplayerType_None = 0;
    CmdMultiplayerType_MultiplayerGetFightGateScRsp = 1039;
    CmdMultiplayerType_MultiplayerFightGiveUpCsReq = 1056;
    CmdMultiplayerType_MultiplayerFightGameStateCsReq = 1034;
    CmdMultiplayerType_MultiplayerMatch3FinishScNotify = 1073;
    CmdMultiplayerType_MultiplayerFightGameStartScNotify = 1098;
    CmdMultiplayerType_MultiplayerGetMatchPlayFriendRankingInfoScRsp = 1071;
    CmdMultiplayerType_MultiplayerFightGiveUpScRsp = 1091;
    CmdMultiplayerType_MultiplayerMatchPlayDataChangeScNotify = 1065;
    CmdMultiplayerType_MultiplayerGetMatchPlayDataCsReq = 1099;
    CmdMultiplayerType_MultiplayerFightGameFinishScNotify = 1026;
    CmdMultiplayerType_MultiplayerGetMatchPlayFriendRankingInfoCsReq = 1080;
    CmdMultiplayerType_MultiplayerFightGameStateScRsp = 1082;
    CmdMultiplayerType_MultiplayerGetFightGateCsReq = 1079;
    CmdMultiplayerType_MultiplayerMatchPlayFriendRankingInfoChangeScNotify = 1004;
    CmdMultiplayerType_MultiplayerGetMatchPlayDataScRsp = 1072;
}

message ECOAKLBOLDA {
    uint32 EECIJBLGLNG = 12;
    uint32 CBFFGFBEFMF = 8;
}

message GetMatchPlayDataRsp {
    repeated PNEGDOHOLDN JBMEEGGOLKN = 14;
    uint32 retcode = 9;
}

message IHGLPGLPDFF {
}

message IMNPPGALEHP {
}

message JCNLJNELKEO {
    uint32 EECIJBLGLNG = 6;
}

message JJIJAMHKNGO {
    uint32 CJPDGBPLFIG = 15;
    bool GLEJFCIOMKC = 14;
    uint32 EECIJBLGLNG = 1;
}

message MatchPlayDataChangeNtf {
    PNEGDOHOLDN KMCDHFGJFNJ = 6;
}

message NLOPJLCMLEN {
}

message OOAHBHODMHG {
    uint32 count = 12;
    uint32 HBONKLEOEEI = 9;
    uint32 LALGADHLMCB = 3;
}

message PJLEILDLONN {
    repeated OOAHBHODMHG DBINCLPHEFN = 3;
    uint32 EECIJBLGLNG = 6;
}

message PNEGDOHOLDN {
    uint32 panel_id = 14;
    FightGameMode GJNMHILINHC = 13;
    PJLEILDLONN ODLONPLECJB = 15;
    ECOAKLBOLDA OCGCLKAHGBK = 3;
    JCNLJNELKEO ICNFMLIAAKE = 6;
    JJIJAMHKNGO GMDCKAOEGNF = 1;
}
