syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdPhoneType {
    CmdPhoneType_None = 0;
    CmdPhoneType_SelectPhoneCaseCsReq = 5173;
    CmdPhoneType_SelectPhoneCaseScRsp = 5199;
    CmdPhoneType_UnlockPhoneCaseScNotify = 5172;
    CmdPhoneType_UnlockPhoneThemeScNotify = 5126;
    CmdPhoneType_UnlockChatBubbleScNotify = 5156;
    CmdPhoneType_GetPhoneDataScRsp = 5182;
    CmdPhoneType_SelectChatBubbleCsReq = 5179;
    CmdPhoneType_SelectPhoneThemeCsReq = 5191;
    CmdPhoneType_GetPhoneDataCsReq = 5134;
    CmdPhoneType_SelectPhoneThemeScRsp = 5198;
    CmdPhoneType_SelectChatBubbleScRsp = 5139;
}

message GetPhoneDataCsReq {
}

message GetPhoneDataScRsp {
    uint32 retcode = 1;
    repeated uint32 owned_phone_cases = 5;
    uint32 cur_phone_theme = 4;
    repeated uint32 owned_phone_themes = 8;
    uint32 cur_phone_case = 15;
    uint32 cur_chat_bubble = 2;
    repeated uint32 owned_chat_bubbles = 14;
}

message SelectChatBubbleCsReq {
    uint32 bubble_id = 4;
}

message SelectChatBubbleScRsp {
    uint32 retcode = 4;
    uint32 cur_chat_bubble = 1;
    uint32 NGJMMMBJFHD = 3;
}

message SelectPhoneCaseCsReq {
    uint32 phone_case_id = 13;
}

message SelectPhoneCaseScRsp {
    uint32 cur_phone_case = 2;
    uint32 retcode = 5;
    uint32 NAMPHKPIOBA = 14;
}

message SelectPhoneThemeCsReq {
    uint32 theme_id = 6;
}

message SelectPhoneThemeScRsp {
    uint32 NNOHELHPJOM = 4;
    uint32 cur_phone_theme = 12;
    uint32 retcode = 9;
}

message UnlockChatBubbleScNotify {
    uint32 bubble_id = 4;
}

message UnlockPhoneCaseScNotify {
    uint32 phone_case_id = 13;
}

message UnlockPhoneThemeScNotify {
    uint32 theme_id = 3;
}
