syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdPlayerReturnType {
    CmdPlayerReturnType_None = 0;
    CmdPlayerReturnType_PlayerReturnPointChangeScNotify = 4539;
    CmdPlayerReturnType_PlayerReturnTakePointRewardScRsp = 4591;
    CmdPlayerReturnType_PlayerReturnTakeCustomRelicScRsp = 4562;
    CmdPlayerReturnType_PlayerReturnStartScNotify = 4534;
    CmdPlayerReturnType_PlayerReturnTakeExtraHcoinScNotify = 4571;
    CmdPlayerReturnType_TakeReturnExtraHcoinRewardScRsp = 4515;
    CmdPlayerReturnType_PlayerReturnForceFinishScNotify = 4572;
    CmdPlayerReturnType_PlayerReturnTakeRelicScRsp = 4580;
    CmdPlayerReturnType_PlayerReturnChangeAssistGroupScRsp = 4541;
    CmdPlayerReturnType_PlayerReturnTakeRewardCsReq = 4598;
    CmdPlayerReturnType_PlayerReturnChangeAssistGroupCsReq = 4581;
    CmdPlayerReturnType_PlayerReturnTakePointRewardCsReq = 4556;
    CmdPlayerReturnType_PlayerReturnTakeRewardScRsp = 4526;
    CmdPlayerReturnType_PlayerReturnSignCsReq = 4582;
    CmdPlayerReturnType_TakeReturnExtraHcoinRewardCsReq = 4588;
    CmdPlayerReturnType_PlayerReturnTakeCustomRelicCsReq = 4504;
    CmdPlayerReturnType_PlayerReturnTakeRelicCsReq = 4565;
    CmdPlayerReturnType_PlayerReturnExtraHcoinProgressScNotify = 4564;
    CmdPlayerReturnType_PlayerReturnInfoQueryCsReq = 4573;
    CmdPlayerReturnType_PlayerReturnSignScRsp = 4579;
    CmdPlayerReturnType_PlayerReturnInfoQueryScRsp = 4599;
}

message KEHOGIENDKC {
    uint32 DACCGMCONBP = 14;
    uint32 AIBJEFAPGMN = 15;
    MMLAPDEBFJM authkey_ver = 2;
}

enum MMLAPDEBFJM {
    MMLAPDEBFJM_NLCDGIPGFDJ = 0;
    MMLAPDEBFJM_reward = 1;
    MMLAPDEBFJM_IEIKAPNDPCI = 2;
}

message PlayerReturnExtraHcoinProgressScNotify {
    uint32 HBPKGODMJNK = 15;
}

message PlayerReturnForceFinishScNotify {
    IBKDHOIDKJA NAJPHJOFGBB = 4;
}

message PlayerReturnInfoQueryCsReq {
}

message PlayerReturnPointChangeScNotify {
    uint32 MNMJCNOLIII = 5;
}

message PlayerReturnSignCsReq {
    repeated KEHOGIENDKC AALGEFBLHEA = 14;
}

message PlayerReturnSignScRsp {
    repeated KEHOGIENDKC AALGEFBLHEA = 15;
    uint32 retcode = 7;
    repeated ItemList GPFMEDKPEAJ = 4;
}

message PlayerReturnTakeCustomRelicCsReq {
    uint32 avatar_id = 5;
}

message PlayerReturnTakeCustomRelicScRsp {
    repeated Relic relic_list = 8;
    uint32 avatar_id = 15;
    uint32 retcode = 13;
}

message PlayerReturnTakeExtraHcoinScNotify {
    bool EAJKAIKEHOL = 10;
    uint32 LHGKNPENJDO = 14;
    uint32 ONAEMDLNJDA = 3;
}

message PlayerReturnTakePointRewardCsReq {
    uint32 DACCGMCONBP = 11;
    uint32 GMKKBFHOMCM = 13;
}

message PlayerReturnTakePointRewardScRsp {
    uint32 GMKKBFHOMCM = 1;
    uint32 DACCGMCONBP = 15;
    uint32 retcode = 13;
    ItemList JNJPKNPCMIB = 8;
}

message PlayerReturnTakeRelicCsReq {
    uint32 avatar_id = 10;
}

message PlayerReturnTakeRelicScRsp {
    uint32 retcode = 4;
    ItemList item_list = 6;
    uint32 avatar_id = 12;
}

message PlayerReturnTakeRewardCsReq {
}

message PlayerReturnTakeRewardScRsp {
    uint32 retcode = 11;
    ItemList GPFMEDKPEAJ = 6;
}

message TakeReturnExtraHcoinRewardCsReq {
}

message TakeReturnExtraHcoinRewardScRsp {
    ItemList reward = 7;
    uint32 CFCNIPLEKON = 1;
    uint32 retcode = 11;
}
