syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AAIMICLLCKE {
    NCFKHDIKCNI NNJCNEMGEAJ = 9;
    uint32 JKAGCGKCHJG = 3;
}

message AIMNHEHKIMI {
    uint32 DJMPADMMPAN = 10;
    uint32 OAEFICOLFIG = 7;
    NCFKHDIKCNI BAGMMONIIGK = 11;
    uint32 AFOHLIOKLAA = 15;
    uint32 HMHEDCCLDGB = 4;
}

message BAGAOALHAJI {
    repeated EKEOBMOKEFD skill_list = 11;
}

message BEJOPEHPABO {
    NCFKHDIKCNI DCPDNBALDOA = 2;
    NCFKHDIKCNI HMCIEDENFMK = 8;
    NCFKHDIKCNI HFNNNGHBHGG = 6;
    repeated uint32 LGBOJJFEGFI = 10;
}

message BLDIHADJKJF {
    uint32 JKAGCGKCHJG = 13;
    NCFKHDIKCNI NNJCNEMGEAJ = 4;
}

message BMGHLHHJEGE {
    uint32 event_type = 13;
    bool is_disappeared_once = 1;
}

message CANOCBHNHLJ {
    uint32 CNGMMDKCBND = 7;
}

message CHBCJNLOLMB {
    repeated KICPDGKGGHO LDCJONHGDAN = 2;
}

message CPHOIPHAPDJ {
    uint32 role_star = 1;
    uint32 PLEEMBMPICA = 9;
    uint32 level = 5;
    uint32 avatar_id = 6;
}

enum CmdPlanetFesType {
    CmdPlanetFesType_None = 0;
    CmdPlanetFesType_PlanetFesBonusEventInteractScRsp = 8231;
    CmdPlanetFesType_PlanetFesStartMiniGameScRsp = 8243;
    CmdPlanetFesType_PlanetFesCollectAllIncomeScRsp = 8219;
    CmdPlanetFesType_PlanetFesClientStatusScRsp = 8221;
    CmdPlanetFesType_PlanetFesDeliverPamCargoScRsp = 8210;
    CmdPlanetFesType_PlanetFesDealAvatarEventOptionItemScRsp = 8233;
    CmdPlanetFesType_PlanetFesClientStatusCsReq = 8238;
    CmdPlanetFesType_PlanetFesUpgradeSkillLevelScRsp = 8213;
    CmdPlanetFesType_PlanetFesTakeQuestRewardScRsp = 8218;
    CmdPlanetFesType_PlanetFesCollectIncomeScRsp = 8208;
    CmdPlanetFesType_PlanetFesFriendRankingInfoChangeScNotify = 8203;
    CmdPlanetFesType_PlanetFesDoGachaScRsp = 8201;
    CmdPlanetFesType_PlanetFesBonusEventInteractCsReq = 8205;
    CmdPlanetFesType_PlanetFesAvatarLevelUpCsReq = 8207;
    CmdPlanetFesType_PlanetFesDealAvatarEventOptionItemCsReq = 8246;
    CmdPlanetFesType_PlanetFesCollectIncomeCsReq = 8224;
    CmdPlanetFesType_PlanetFesUpgradeFesLevelCsReq = 8239;
    CmdPlanetFesType_PlanetFesBuyLandScRsp = 8220;
    CmdPlanetFesType_PlanetFesDeliverPamCargoCsReq = 8241;
    CmdPlanetFesType_PlanetFesUpgradeFesLevelScRsp = 8216;
    CmdPlanetFesType_PlanetFesSetCustomKeyValueCsReq = 8202;
    CmdPlanetFesType_PlanetFesDoGachaCsReq = 8212;
    CmdPlanetFesType_PlanetFesUseItemScRsp = 8248;
    CmdPlanetFesType_PlanetFesCollectAllIncomeCsReq = 8217;
    CmdPlanetFesType_PlanetFesStartMiniGameCsReq = 8240;
    CmdPlanetFesType_PlanetFesChooseAvatarEventOptionCsReq = 8249;
    CmdPlanetFesType_PlanetFesSetAvatarWorkCsReq = 8222;
    CmdPlanetFesType_PlanetFesUpgradeSkillLevelCsReq = 8228;
    CmdPlanetFesType_PlanetFesGameBingoFlipCsReq = 8226;
    CmdPlanetFesType_PlanetFesGetFriendRankingInfoListScRsp = 8209;
    CmdPlanetFesType_PlanetFesGetBusinessDayInfoCsReq = 8225;
    CmdPlanetFesType_PlanetFesBuyLandCsReq = 8237;
    CmdPlanetFesType_PlanetFesChooseAvatarEventOptionScRsp = 8230;
    CmdPlanetFesType_PlanetFesSetCustomKeyValueScRsp = 8234;
    CmdPlanetFesType_PlanetFesTakeQuestRewardCsReq = 8242;
    CmdPlanetFesType_PlanetFesGetBusinessDayInfoScRsp = 8204;
    CmdPlanetFesType_PlanetFesGameBingoFlipScRsp = 8250;
    CmdPlanetFesType_GetPlanetFesDataScRsp = 8229;
    CmdPlanetFesType_PlanetFesBusinessDayRefreshEventCsReq = 8235;
    CmdPlanetFesType_PlanetFesTakeRegionPhaseRewardCsReq = 8223;
    CmdPlanetFesType_PlanetFesGetFriendRankingInfoListCsReq = 8215;
    CmdPlanetFesType_PlanetFesTakeRegionPhaseRewardScRsp = 8227;
    CmdPlanetFesType_GetPlanetFesDataCsReq = 8236;
    CmdPlanetFesType_PlanetFesGetAvatarStatScRsp = 8245;
    CmdPlanetFesType_PlanetFesSetAvatarWorkScRsp = 8232;
    CmdPlanetFesType_PlanetFesSyncChangeScNotify = 8244;
    CmdPlanetFesType_PlanetFesBusinessDayRefreshEventScRsp = 8247;
    CmdPlanetFesType_PlanetFesAvatarLevelUpScRsp = 8214;
    CmdPlanetFesType_PlanetFesGetAvatarStatCsReq = 8211;
    CmdPlanetFesType_PlanetFesUseItemCsReq = 8206;
}

message DAGGFIOGHGE {
    uint32 FNABEJNJBKN = 11;
    NCFKHDIKCNI GAMNCJJJPEN = 14;
    NCFKHDIKCNI EJPENDJNLIH = 4;
    int64 MGHNNENOOGB = 9;
}

message ECIDGEBFJHP {
    PLPDNKNJBAA BOLCNGAKAMG = 11;
}

message EKEOBMOKEFD {
    uint32 level = 8;
    uint32 skill_id = 7;
}

message EKPBGMKJGDL {
    IPMLDNLACFO HLBCFJLLKBL = 9;
    uint32 avatar_id = 11;
    uint32 MGBCAPIIKLM = 3;
    uint32 BEMDNEMABCC = 10;
}

message EPKGFJDJMHM {
    BEJOPEHPABO FKFPLMFLNPI = 2;
    BEJOPEHPABO HFCPPGPPMPB = 13;
    IHHONELJHJG LMOLELDIKMA = 12;
    IHHONELJHJG JCJLAAFLGHC = 10;
    DAGGFIOGHGE DLNEGFMNCPI = 14;
    DAGGFIOGHGE JLHJHFMMAPG = 7;
    CPHOIPHAPDJ LPGHOGLGEKH = 8;
    CPHOIPHAPDJ BFPNBEPPPLL = 11;
    KICPDGKGGHO KMKNPALADDC = 6;
    KICPDGKGGHO ELMMNHBECNI = 4;
    AAIMICLLCKE FBMJJGFJFMA = 5;
    JHACFFJIPHK NPNDMLGFEFI = 9;
    JHACFFJIPHK LIHDHBNHDKM = 15;
    PCONBOGEDFD MDFJJFCDLCK = 1;
    PlanetFesUnlockChange KONHPICIELO = 3;
    EKEOBMOKEFD LNPGIMBEMOE = 1472;
    IMHOJPDMOJI HGGBFCEFLKO = 1354;
    ECIDGEBFJHP ODOHJNABBAM = 281;
    PEMCOFDFCAC JDLEEFDFJGA = 446;
    MCCHABOPEFJ CGMBBDHDMEO = 1303;
    HGJHBCBIONE KGHOJJKNCBP = 1306;
    CANOCBHNHLJ BPKMBMPJAON = 1841;
    KICPDGKGGHO EOPILJCMLLA = 551;
    FLCJMPNDMMH KMCJFDEDEAA = 1035;
    GMODJEECPPJ DBDLIIPGEOE = 1246;
    IEDPDDJAAIH JOGCFKGJMJB = 1089;
    MAOINJAJOEC KJOAEEGIGDI = 667;
    DFEPHMALKDK OAHOCFKEMCM = 1265;
}

message FLCJMPNDMMH {
    uint32 HBMGKJAAPFI = 12;
    uint32 LAAAPJAIKAF = 6;
    repeated GLECNCOBKCJ FIHPPANOOFL = 8;
    uint32 NFCMAEIGKHK = 15;
    uint32 BPBADPAACOL = 4;
    NCFKHDIKCNI BFEOOJBNFBG = 2;
    uint32 MAGBFEHEOOI = 13;
    NCFKHDIKCNI FHGFEKEAJFF = 14;
    map<uint32, uint32> ODICAOCLJKO = 10;
    NCFKHDIKCNI FDGKBOIEHBD = 7;
}

message FPMMPGAOGCH {
    uint32 FNABEJNJBKN = 3;
}

message GHONFFLAMHB {
    uint32 IGOOJKMPMDC = 1;
}

enum GJJEOANEDDO {
    GJJEOANEDDO_NLCDGIPGFDJ = 0;
    GJJEOANEDDO_GHDEPAGOKBE = 1;
    GJJEOANEDDO_GGEKFBGIJID = 2;
}

message GLECNCOBKCJ {
    uint32 avatar_id = 4;
    uint32 LKBHAFLMOLA = 9;
    NCFKHDIKCNI NFDJOCBMLCI = 3;
    uint32 PKJHFPFOABL = 10;
}

message GNMCIEPEBPK {
    NCFKHDIKCNI item_value = 5;
    repeated FMKMEFMOJGJ item_list = 9;
    map<uint32, uint32> NDMLPIGABGE = 6;
}

message GOMIDGNOENH {
    uint32 FNABEJNJBKN = 6;
}

message GetPlanetFesDataCsReq {
    bool NFKMDPBNLEE = 11;
}

message GetPlanetFesDataScRsp {
    PPAIELAKIJD BBEKBJPHEJK = 10;
    CHBCJNLOLMB OPJLJOPBGOJ = 9;
    BAGAOALHAJI skill_info = 7;
    JMBNHAFHIHM IEKDOJDPMEB = 15;
    OBEHBNOCLMM LCPEDLCOMFE = 2;
    PLOFKJDKEPN FEOONKKLCHA = 6;
    KCMJJLJCHHP NJFGGOOMGCD = 8;
    BLDIHADJKJF OEIBHLMDJKA = 4;
    uint32 retcode = 13;
    KNECKDAOKOA OCHNMGMDHME = 14;
    PHCPOIHAPGP COGGJELNFCN = 1;
    repeated KVP custom_value_list = 3;
    NOLLHKIMDOC CCFGCCMEFCI = 12;
}

message HBONEFMPKKO {
    uint32 progress = 1;
    uint32 MMFGAJNCAOA = 6;
}

message HGJHBCBIONE {
    OJHHACMHFKA GLOAGDBEKDP = 6;
    GJJEOANEDDO GMKICMIMAAB = 4;
}

message IEDAMBICKBB {
    int64 KHCGOMAJDGL = 8;
}

message IHHONELJHJG {
    uint32 DCPDNBALDOA = 11;
    uint32 item_id = 12;
    uint32 HFNNNGHBHGG = 3;
}

message IKMLLJNNKJB {
    repeated AIMNHEHKIMI transfer_item_list = 15;
    repeated FMKMEFMOJGJ item_list = 3;
}

message IMHOJPDMOJI {
    uint32 HBJIJHHMEGO = 8;
}

message IPMLDNLACFO {
    AIMNHEHKIMI PIENFNCGFMB = 3;
    FMKMEFMOJGJ item = 8;
}

message JHACFFJIPHK {
    uint32 progress = 4;
    PlanetFesQuestState status = 7;
    uint32 quest_id = 1;
    uint32 DPCHGMMCKNN = 12;
    uint32 MCNLMNOKAFF = 13;
    NCFKHDIKCNI KNOCPAJCPJC = 8;
}

message JMBNHAFHIHM {
    repeated DAGGFIOGHGE GOIJOOCHJDP = 15;
}

message KCMJJLJCHHP {
    uint32 DDOIGECMKKA = 10;
    uint32 NEDCJCBPEJM = 4;
    bool has_passed = 1;
    bool CANDCMOCAFH = 8;
    int64 NACEMPJFKAH = 11;
    uint32 CINEILEIEJK = 14;
}

message KICPDGKGGHO {
    repeated IEDAMBICKBB KABJOHKOEFN = 1;
    uint64 unique_id = 9;
    OBEBKODGODB source = 15;
    uint32 config_id = 10;
}

message KNECKDAOKOA {
    NCFKHDIKCNI item_value = 13;
    NCFKHDIKCNI GJPLOMMEBGM = 2;
    repeated FMKMEFMOJGJ item_list = 15;
}

message LEJNBBLNNDM {
    OBEBKODGODB source = 7;
    EPKGFJDJMHM detail = 6;
}

message MAOINJAJOEC {
    NCFKHDIKCNI gold = 15;
    uint32 business_day = 10;
    uint32 LBICJMAMFGN = 12;
    uint32 PPOAGPGEAFH = 2;
    uint32 JKAGCGKCHJG = 1;
    uint32 uid = 5;
    uint32 EMJPFPHBKMG = 13;
}

message MCCHABOPEFJ {
    MOFKNBAKKDI GHKFKGMOHDO = 10;
}

message MOFKNBAKKDI {
    bool has_passed = 5;
    NCFKHDIKCNI FDGKBOIEHBD = 10;
    repeated OJHHACMHFKA CKACALMICBH = 4;
    int64 start_time = 11;
    uint32 business_day = 15;
    map<uint32, uint32> FLKNHFMNDCE = 7;
    bool CANDCMOCAFH = 2;
}

message MOOLKFODKIK {
}

message NDPJHJOAOJE {
    repeated uint32 EPBJNIFHBLE = 6;
    IKMLLJNNKJB HMMBBENHIFE = 7;
}

message NGHCOJCMJOK {
    repeated uint32 BNCOJCEGBPG = 4;
    repeated EKPBGMKJGDL HAINMHKIOMJ = 9;
    NCFKHDIKCNI OPOIDCHIMEK = 6;
    repeated IPMLDNLACFO FAJLFDNKFGJ = 2;
}

message NOLLHKIMDOC {
    int64 GLDGCHLDMJE = 6;
    repeated uint32 IJMHPOEPILG = 1;
    uint32 JOADLJIDGND = 12;
}

message OBEBKODGODB {
    uint32 BNEFLBPCPOI = 12;
    uint32 EPFHBGNGBBK = 14;
    uint32 EMPDMDNDLHE = 13;
}

message OBEHBNOCLMM {
    uint32 CNGMMDKCBND = 11;
    repeated uint32 HPMNIKJGBPD = 2;
}

message OHABCOEGDEH {
    NCFKHDIKCNI EJNBHKGOEKI = 8;
    bool CANDCMOCAFH = 1;
    uint32 NMLFCGHPGEL = 13;
    repeated GLECNCOBKCJ FIHPPANOOFL = 12;
    NCFKHDIKCNI FDGKBOIEHBD = 3;
    uint32 business_day = 5;
}

message OLENIPLHIPI {
    bool is_active = 15;
}

message PBAPKAGHGFB {
    repeated uint32 GOEJBENHBHE = 12;
}

message PCONBOGEDFD {
    uint32 PKCIADAEICG = 6;
    uint32 EDBPMKPHLDK = 10;
}

message PEMCOFDFCAC {
    NCFKHDIKCNI EFOJBKPJLIO = 4;
}

message PHCPOIHAPGP {
    repeated CPHOIPHAPDJ avatar_list = 15;
}

message PLOFKJDKEPN {
    repeated JHACFFJIPHK quest_list = 9;
    PCONBOGEDFD DFBGAOAJLIC = 12;
}

message PLPDNKNJBAA {
    MOFKNBAKKDI HOCBDMPEMDH = 2;
    repeated OHABCOEGDEH HBGPLDACACI = 15;
    repeated BMGHLHHJEGE ENDPGFBABBB = 9;
    repeated uint32 KCENCAAPMLK = 8;
    uint32 CINEILEIEJK = 12;
    uint32 NEDCJCBPEJM = 10;
}

message PPAIELAKIJD {
    repeated HBONEFMPKKO KFOFAKDPGJC = 14;
    repeated uint32 BJNOHKFONFP = 12;
}

message PlanetFesAvatarLevelUpCsReq {
    uint32 IGOOJKMPMDC = 4;
    uint32 avatar_id = 8;
}

message PlanetFesAvatarLevelUpScRsp {
    uint32 avatar_id = 4;
    uint32 retcode = 13;
    GNMCIEPEBPK reward = 9;
    uint32 KPGNEABOECG = 11;
    uint32 IGOOJKMPMDC = 3;
}

message PlanetFesBonusEventInteractCsReq {
    uint32 event_type = 10;
    uint32 JCBNLGDOMMF = 4;
}

message PlanetFesBonusEventInteractScRsp {
    OJHHACMHFKA GLOAGDBEKDP = 15;
    GNMCIEPEBPK reward = 9;
    uint32 event_type = 3;
    uint32 retcode = 14;
}

message PlanetFesBusinessDayRefreshEventCsReq {
    uint32 event_type = 3;
    uint32 business_day = 15;
    bool CEIONHPDNDP = 5;
}

message PlanetFesBusinessDayRefreshEventScRsp {
    uint32 retcode = 1;
    OJHHACMHFKA GLOAGDBEKDP = 13;
}

message PlanetFesChooseAvatarEventOptionCsReq {
    uint32 MABNCDEBPDK = 2;
}

message PlanetFesChooseAvatarEventOptionScRsp {
    GNMCIEPEBPK reward = 11;
    uint32 DNLAFCPNPOE = 4;
    uint32 IIBJDCKHAKE = 12;
    OJHHACMHFKA GLOAGDBEKDP = 5;
    uint32 HHGAHEBNAIL = 13;
    uint32 retcode = 9;
}

message PlanetFesDealAvatarEventOptionItemCsReq {
    uint32 HLLIBEEKFII = 12;
    bool MLKBOBIEAPL = 7;
}

message PlanetFesDealAvatarEventOptionItemScRsp {
    OJHHACMHFKA GLOAGDBEKDP = 7;
    uint32 DNLAFCPNPOE = 8;
    uint32 IIBJDCKHAKE = 14;
    uint32 retcode = 1;
    bool MLKBOBIEAPL = 6;
    GNMCIEPEBPK reward = 11;
}

message PlanetFesDeliverPamCargoCsReq {
    uint32 avatar_id = 3;
    uint32 JADCEPFHHDK = 10;
}

message PlanetFesDeliverPamCargoScRsp {
    uint32 avatar_id = 7;
    OJHHACMHFKA GLOAGDBEKDP = 15;
    GNMCIEPEBPK FFMILOLELNJ = 11;
    uint32 retcode = 2;
}

message PlanetFesDoGachaCsReq {
    uint32 simulate_magic = 2;
    uint32 gacha_id = 14;
    uint32 gacha_count = 11;
}

message PlanetFesDoGachaScRsp {
    uint32 retcode = 13;
    repeated FMKMEFMOJGJ LGPDNIGJEKP = 11;
    uint32 gacha_id = 7;
    NGHCOJCMJOK EHLPJELJJOO = 5;
    NDPJHJOAOJE FFBDKNIHNEL = 10;
}

message PlanetFesFriendRankingInfoChangeScNotify {
    repeated MAOINJAJOEC MLPHLIHFGKG = 12;
}

message PlanetFesGameBingoFlipCsReq {
    uint32 LKFIGBGPEJB = 9;
}

message PlanetFesGameBingoFlipScRsp {
    uint32 retcode = 8;
    uint32 LKFIGBGPEJB = 1;
    bool BDEFAFFDBCC = 13;
    GNMCIEPEBPK reward = 5;
}

message PlanetFesGetAvatarStatCsReq {
}

message PlanetFesGetAvatarStatScRsp {
    repeated GLECNCOBKCJ FIHPPANOOFL = 8;
    uint32 retcode = 4;
}

message PlanetFesGetBusinessDayInfoScRsp {
    int64 NACEMPJFKAH = 14;
    PLPDNKNJBAA BOLCNGAKAMG = 7;
    uint32 retcode = 11;
}

message PlanetFesGetFriendRankingInfoListCsReq {
}

message PlanetFesGetFriendRankingInfoListScRsp {
    uint32 retcode = 12;
    MAOINJAJOEC PONAOKBNIAM = 14;
}

enum PlanetFesQuestState {
    PlanetFesQuestState_PlanetFesQuestNone = 0;
    PlanetFesQuestState_PlanetFesQuestDoing = 1;
    PlanetFesQuestState_PlanetFesQuestFinish = 2;
    PlanetFesQuestState_PlanetFesQuestClose = 3;
}

message PlanetFesSetCustomKeyValueCsReq {
    uint32 key = 4;
    uint32 value = 3;
}

message PlanetFesSetCustomKeyValueScRsp {
    uint32 key = 4;
    uint32 retcode = 14;
    uint32 value = 15;
}

message PlanetFesSkillLevelUpCsReq {
    uint32 IGOOJKMPMDC = 14;
    uint32 skill_id = 5;
}

message PlanetFesStartMiniGameCsReq {
    uint32 ratio = 15;
    uint32 DLFHABGGHFF = 12;
}

message PlanetFesStartMiniGameScRsp {
    GNMCIEPEBPK reward = 14;
    uint32 retcode = 7;
    PGPHEKKPBLD CFDIKLBINHK = 12;
    PBAPKAGHGFB HMMBBENHIFE = 5;
}

message PlanetFesSyncChangeScNotify {
    repeated LEJNBBLNNDM DGNGMJMPFGK = 12;
}

message PlanetFesTakeQuestRewardCsReq {
    uint32 quest_id = 4;
}

message PlanetFesTakeQuestRewardScRsp {
    uint32 quest_id = 13;
    uint32 retcode = 8;
    IKMLLJNNKJB JMBFMMPAAAO = 9;
}

message PlanetFesTakeRegionPhaseRewardCsReq {
    uint32 BKPDKFLDLDD = 10;
}

message PlanetFesTakeRegionPhaseRewardScRsp {
    uint32 retcode = 8;
    uint32 BKPDKFLDLDD = 13;
    ItemList reward_list = 10;
}

message PlanetFesUnlockChange {
    bool has_passed = 13;
    HBONEFMPKKO BBEKBJPHEJK = 14;
}

message PlanetFesUseItemCsReq {
    uint32 JMOOBDBKFMD = 5;
    uint32 item_id = 10;
}

message PlanetFesUseItemScRsp {
    uint32 retcode = 7;
    GNMCIEPEBPK reward = 8;
}
