syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum ALGMICKCABI {
    ALGMICKCABI_FLANKPMJBMH = 0;
    ALGMICKCABI_LMHJFBBDLNH = 1;
}

message ANCNILJJBND {
}

message AnnounceData {
    uint32 config_id = 13;
    uint32 banner_frequency = 7;
    int64 end_time = 12;
    bool BBEBEKFGMAD = 9;
    string banner_text = 2;
    bool has_recommand = 10;
    int64 begin_time = 1;
    string emergency_text = 14;
}

message AntiAddictScNotify {
    string level = 7;
    uint32 msg_type = 3;
    string msg = 15;
}

message BlackInfo {
    int64 begin_time = 1;
    int64 end_time = 2;
    uint32 limit_level = 3;
    uint32 ban_type = 4;
}

message CMCJFJEBBCO {
    string LEMBPAGGMEM = 1;
    int32 BLNDDBDIDNJ = 2;
    int32 HDMMKJIKCOJ = 3;
    int32 LMMHAGLDACM = 4;
    int32 MBPELIOJBDG = 5;
}

message ClientDownloadData {
    uint32 version = 1;
    int64 time = 2;
    bytes data = 3;
    uint32 channel_id = 4;
}

message ClientDownloadDataScNotify {
    ClientDownloadData download_data = 4;
}

message ClientObjDownloadData {
    bytes sc_info = 1;
    ClientDownloadData client_obj_download_data = 2;
    repeated ClientDownloadData dyn_code = 3;
}

message ClientObjDownloadDataScNotify {
    ClientObjDownloadData data = 8;
}

message ClientObjUploadCsReq {
    ALGMICKCABI content_type = 12;
    uint32 EOHFCODKKMD = 5;
    bytes sc_data = 3;
}

message ClientObjUploadScRsp {
    ClientObjDownloadData data = 1;
    uint32 retcode = 10;
}

enum CmdPlayerType {
    CmdPlayerType_None = 0;
    CmdPlayerType_GetLevelRewardTakenListScRsp = 41;
    CmdPlayerType_GmTalkScNotify = 26;
    CmdPlayerType_GetVideoVersionKeyScRsp = 94;
    CmdPlayerType_StaminaInfoScNotify = 36;
    CmdPlayerType_ExchangeStaminaCsReq = 71;
    CmdPlayerType_PlayerHeartBeatCsReq = 19;
    CmdPlayerType_ReserveStaminaExchangeCsReq = 76;
    CmdPlayerType_GetLevelRewardTakenListCsReq = 81;
    CmdPlayerType_GmTalkCsReq = 99;
    CmdPlayerType_FeatureSwitchClosedScNotify = 63;
    CmdPlayerType_PlayerLoginFinishCsReq = 92;
    CmdPlayerType_GetLevelRewardCsReq = 38;
    CmdPlayerType_GetGameStateServiceConfigScRsp = 17;
    CmdPlayerType_UpdatePsnSettingsInfoScRsp = 50;
    CmdPlayerType_QueryProductInfoScRsp = 30;
    CmdPlayerType_AntiAddictScNotify = 88;
    CmdPlayerType_GetLevelRewardScRsp = 57;
    CmdPlayerType_UpdatePlayerSettingCsReq = 7;
    CmdPlayerType_GetSecretKeyInfoCsReq = 25;
    CmdPlayerType_UpdatePsnSettingsInfoCsReq = 18;
    CmdPlayerType_GetVideoVersionKeyCsReq = 96;
    CmdPlayerType_PlayerLoginFinishScRsp = 86;
    CmdPlayerType_SetLanguageCsReq = 9;
    CmdPlayerType_DailyRefreshNotify = 87;
    CmdPlayerType_PlayerForceSyncGameStateFinishCsReq = 6;
    CmdPlayerType_UpdateFeatureSwitchScNotify = 89;
    CmdPlayerType_GateServerScNotify = 74;
    CmdPlayerType_SetGenderScRsp = 40;
    CmdPlayerType_SetPlayerInfoScRsp = 55;
    CmdPlayerType_AceAntiCheaterCsReq = 35;
    CmdPlayerType_GetAuthkeyCsReq = 62;
    CmdPlayerType_SetLanguageScRsp = 24;
    CmdPlayerType_PlayerGetTokenCsReq = 56;
    CmdPlayerType_GetBasicInfoScRsp = 11;
    CmdPlayerType_PlayerKickOutScNotify = 73;
    CmdPlayerType_PlayerLogoutCsReq = 79;
    CmdPlayerType_GetGameStateServiceConfigCsReq = 29;
    CmdPlayerType_ExchangeStaminaScRsp = 4;
    CmdPlayerType_ClientObjDownloadDataScNotify = 37;
    CmdPlayerType_MonthCardRewardNotify = 20;
    CmdPlayerType_GetBasicInfoCsReq = 70;
    CmdPlayerType_SetNicknameScRsp = 64;
    CmdPlayerType_RegionStopScNotify = 48;
    CmdPlayerType_PlayerHeartBeatScRsp = 33;
    CmdPlayerType_ClientObjUploadCsReq = 42;
    CmdPlayerType_SetPlayerInfoCsReq = 83;
    CmdPlayerType_PlayerLogoutScRsp = 39;
    CmdPlayerType_GetAuthkeyScRsp = 49;
    CmdPlayerType_ServerAnnounceNotify = 14;
    CmdPlayerType_PlayerForceSyncGameStateFinishScRsp = 3;
    CmdPlayerType_SetRedPointStatusScNotify = 27;
    CmdPlayerType_RetcodeNotify = 68;
    CmdPlayerType_PlayerLoginCsReq = 34;
    CmdPlayerType_SetGameplayBirthdayCsReq = 69;
    CmdPlayerType_ClientDownloadDataScNotify = 60;
    CmdPlayerType_QueryProductInfoCsReq = 2;
    CmdPlayerType_UpdatePlayerSettingScRsp = 52;
    CmdPlayerType_ClientObjUploadScRsp = 84;
    CmdPlayerType_SetGameplayBirthdayScRsp = 47;
    CmdPlayerType_ReserveStaminaExchangeScRsp = 13;
    CmdPlayerType_PlayerLoginScRsp = 82;
    CmdPlayerType_SetNicknameCsReq = 15;
    CmdPlayerType_AceAntiCheaterScRsp = 78;
    CmdPlayerType_SetGenderCsReq = 43;
    CmdPlayerType_GetSecretKeyInfoScRsp = 16;
    CmdPlayerType_PlayerGetTokenScRsp = 91;
    CmdPlayerType_GmTalkScRsp = 72;
}

message DailyRefreshNotify {
    uint32 MDIIJKBHBBI = 1;
}

message EnterStageCsReq {
    string stop_desc = 4;
}

message ExchangeStaminaCsReq {
}

message ExchangeStaminaScRsp {
    repeated ItemCost item_cost_list = 9;
    uint32 retcode = 4;
    uint32 stamina_add = 3;
    uint32 exchange_times = 7;
    int64 last_recover_time = 5;
}

message FLMODPLLMNF {
    uint32 NMELIDCDKAK = 6;
    string GIFOENLDCHO = 8;
}

message FeatureSwitchClosedScNotify {
    FeatureSwitchType FMGLEBCIBHG = 14;
}

enum FeatureSwitchType {
    FeatureSwitchType_FeatureSwitchNone = 0;
    FeatureSwitchType_FeatureSwitchShop = 1;
    FeatureSwitchType_FeatureSwitchLineupName = 2;
    FeatureSwitchType_FeatureSwitchRechargeShop = 3;
    FeatureSwitchType_FeatureSwitchNickname = 4;
    FeatureSwitchType_FeatureSwitchSignature = 5;
    FeatureSwitchType_FeatureSwitchBattlepass = 6;
    FeatureSwitchType_FeatureSwitchPunkLord = 7;
    FeatureSwitchType_FeatureSwitchMonthcardDaily = 8;
    FeatureSwitchType_FeatureSwitchPictureShare = 9;
    FeatureSwitchType_FeatureSwitchRogue = 10;
    FeatureSwitchType_FeatureSwitchChallenge = 11;
    FeatureSwitchType_FeatureSwitchCocoon = 12;
    FeatureSwitchType_FeatureSwitchRaid = 13;
    FeatureSwitchType_FeatureSwitchMazePlaneEvent = 14;
    FeatureSwitchType_FeatureSwitchActivityPanel = 15;
    FeatureSwitchType_FeatureSwitchMailbox = 16;
    FeatureSwitchType_FeatureSwitchQuest = 17;
    FeatureSwitchType_FeatureSwitchGacha = 18;
    FeatureSwitchType_FeatureSwitchChat = 19;
    FeatureSwitchType_FeatureSwitchModifyFriendAlias = 20;
    FeatureSwitchType_FeatureSwitchUseItem = 21;
    FeatureSwitchType_FeatureSwitchActivitySchedule = 22;
    FeatureSwitchType_FeatureSwitchFarmElement = 23;
    FeatureSwitchType_FeatureSwitchAchievementLevel = 24;
    FeatureSwitchType_FeatureSwitchDailyActiveLevel = 25;
    FeatureSwitchType_FeatureSwitchPlayerReturn = 26;
    FeatureSwitchType_FeatureSwitchFirstSetNickname = 27;
    FeatureSwitchType_FeatureSwitchMainMissionReward = 28;
    FeatureSwitchType_FeatureSwitchSubMissionReward = 29;
    FeatureSwitchType_FeatureSwitchPamMission = 30;
    FeatureSwitchType_FeatureSwitchDestroyItem = 32;
    FeatureSwitchType_FeatureSwitchConsumeItemTurn = 33;
    FeatureSwitchType_FeatureSwitchRogueModifier = 34;
    FeatureSwitchType_FeatureSwitchChessRogue = 35;
    FeatureSwitchType_FeatureSwitchChessRogueBoard = 36;
    FeatureSwitchType_FeatureSwitchRollShop = 37;
    FeatureSwitchType_FeatureSwitchH5Return = 38;
    FeatureSwitchType_FeatureSwitchOffering = 39;
    FeatureSwitchType_FeatureSwitchServerRedPoint = 40;
    FeatureSwitchType_FeatureSwitchMonopolyOptionRatio = 41;
    FeatureSwitchType_FeatureSwitchMonopolyGetRaffleTicket = 42;
    FeatureSwitchType_FeatureSwitchMonopolyTakeRaffleReward = 43;
    FeatureSwitchType_FeatureSwitchChallengeRecommendLineup = 44;
    FeatureSwitchType_FeatureSwitchPsnMemberShipCheck = 45;
    FeatureSwitchType_FeatureSwitchPlayerBoardDevelopment = 46;
    FeatureSwitchType_FeatureSwitchPvp = 47;
    FeatureSwitchType_FeatureSwitchRogueMode = 48;
    FeatureSwitchType_FeatureSwitchRogueTournUgc = 49;
    FeatureSwitchType_FeatureSwitchRelicFilterPlanName = 50;
    FeatureSwitchType_FeatureSwitchMazeItemUseBuffDrop = 51;
    FeatureSwitchType_FeatureSwitchRedDot = 52;
    FeatureSwitchType_FeatureSwitchGameStateService = 53;
    FeatureSwitchType_FeatureSwitchBenefitIndex = 54;
    FeatureSwitchType_FeatureSwitchRogueTournBuildRef = 55;
    FeatureSwitchType_FeatureSwitchPreAvatarSetGrowthTarget = 56;
    FeatureSwitchType_FeatureSwitchImportRelicFilterPlan = 58;
    FeatureSwitchType_FeatureSwitchGachaDecideItem = 59;
    FeatureSwitchType_FeatureSwitchItemSync = 60;
    FeatureSwitchType_FeatureSwitchRechargeBenefit = 61;
    FeatureSwitchType_FeatureSwitchRechargeGift = 62;
    FeatureSwitchType_FeatureSwitchRogueTournBuildRefShareCode = 63;
    FeatureSwitchType_FeatureSwitchGachaAvatarToast = 64;
    FeatureSwitchType_FeatureSwitchRogueTournBuildRefShareCodeRename = 65;
    FeatureSwitchType_FeatureSwitchRelicSmartDiscard = 66;
    FeatureSwitchType_FeatureSwitchPlanetfesSocial = 67;
    FeatureSwitchType_FeatureSwitchRelicReforge = 68;
    FeatureSwitchType_FeatureSwitchRelicCompose = 69;
    FeatureSwitchType_FeatureSwitchRelicDecompose = 70;
    FeatureSwitchType_FeatureSwitchRogueTournCocoon = 71;
    FeatureSwitchType_FeatureSwitchItemCompose = 72;
    FeatureSwitchType_FeatureSwitchGrowMaterialAutoComplete = 73;
    FeatureSwitchType_FeatureSwitchSkipPerformance = 74;
    FeatureSwitchType_FeatureSwitchFate = 75;
    FeatureSwitchType_FeatureSwitchFateAvatarHandbook = 76;
    FeatureSwitchType_FeatureSwitchElfRestaurant = 77;
    FeatureSwitchType_FeatureSwitchBattleTimeoutLegal = 78;
    FeatureSwitchType_FeatureSwitchHipplen = 79;
    FeatureSwitchType_FeatureSwitchHipplenEffect = 80;
    FeatureSwitchType_FeatureSwitchReplayPerformance = 81;
    FeatureSwitchType_FeatureSwitchGridFightRef = 82;
    FeatureSwitchType_FeatureSwitchRelicBox = 83;
    FeatureSwitchType_FeatureSwitchGridFightStartGamePlay = 84;
    FeatureSwitchType_FeatureSwitchGridFightBanAugment = 85;
    FeatureSwitchType_FeatureSwitchGridFightBanPortalBuff = 86;
    FeatureSwitchType_FeatureSwitchBanGotoPage = 87;
    FeatureSwitchType_FeatureSwitchReportSensitiveWordCheck = 88;
    FeatureSwitchType_FeatureSwitchAvatarSkinId = 89;
    FeatureSwitchType_FeatureSwitchAiPam = 90;
    FeatureSwitchType_FeatureSwitchBattleCheckPass = 91;
    FeatureSwitchType_FeatureSwitchIdleLiveCustomTitle = 92;
    FeatureSwitchType_FeatureSwitchGridFightFormationName = 93;
    FeatureSwitchType_FeatureSwitchSocialPlay = 94;
    FeatureSwitchType_FeatureSwitchRelicPresetPlanName = 95;
    FeatureSwitchType_FeatureSwitchOutfitPreview = 96;
    FeatureSwitchType_FeatureSwitchRogueProcessorQueueCutting = 97;
    FeatureSwitchType_FeatureSwitchChooseDelivery = 98;
    FeatureSwitchType_FeatureSwitchUnlockContentPackage = 99;
    FeatureSwitchType_FeatureSwitchAcceleratePerformance = 102;
}

message GateServerScNotify {
    string OKLNPLEDKDE = 7;
}

enum Gender {
    Gender_None = 0;
    Gender_Man = 1;
    Gender_Woman = 2;
}

message GetAuthkeyCsReq {
    uint32 sign_type = 10;
    uint32 authkey_ver = 5;
    string auth_appid = 2;
}

message GetAuthkeyScRsp {
    uint32 retcode = 10;
    uint32 sign_type = 13;
    uint32 authkey_ver = 2;
    string auth_appid = 1;
    string authkey = 7;
}

message GetBasicInfoCsReq {
}

message GetBasicInfoScRsp {
    bool is_gender_set = 11;
    uint32 gender = 15;
    uint32 gameplay_birthday = 8;
    int64 next_recover_time = 13;
    PlayerSettingInfo player_setting_info = 9;
    int64 last_set_nickname_time = 7;
    uint32 cur_day = 5;
    uint32 week_cocoon_finished_count = 4;
    uint32 exchange_times = 2;
    uint32 retcode = 10;
}

message GetLevelRewardCsReq {
    uint32 interacted_prop_entity_id = 12;
    uint32 level = 6;
}

message GetLevelRewardScRsp {
    uint32 level = 4;
    ItemList reward = 3;
    uint32 retcode = 12;
}

message GetLevelRewardTakenListCsReq {
}

message GetLevelRewardTakenListScRsp {
    uint32 retcode = 3;
    repeated uint32 level_reward_taken_list = 10;
}

message GetSecretKeyInfoCsReq {
    bytes CILHEPFKKNI = 3;
}

message GetSecretKeyInfoScRsp {
    repeated SecretKeyInfo secret_info = 3;
    bytes secret_rsp = 7;
    uint32 retcode = 9;
}

message GetVideoVersionKeyCsReq {
}

message GetVideoVersionKeyScRsp {
    repeated VideoKeyInfo video_key_info_list = 11;
    repeated VideoKeyInfo activity_video_key_info_list = 6;
    uint32 retcode = 1;
}

message HBJLNKAFNAD {
    repeated uint32 switch_list = 1;
}

message HDOKNMGIDMB {
    FeatureSwitchType type = 1;
    repeated HBJLNKAFNAD BGNKLMIMBPI = 2;
    bool KPCPABKPAKL = 3;
}

message JKJMAKHANPB {
    string stop_desc = 4;
}

message LFCHHMGGMPC {
    uint32 EHNJDIDABHD = 7;
    uint32 show_type = 13;
    uint32 BMFJFFBPADD = 15;
    uint32 content_id = 14;
}

message LFKKOMBKJIP {
    string tag = 1;
    string value = 2;
}

enum LanguageType {
    LANGUAGE_NONE = 0;
    LANGUAGE_SC = 1;
    LANGUAGE_TC = 2;
    LANGUAGE_EN = 3;
    LANGUAGE_KR = 4;
    LANGUAGE_JP = 5;
    LANGUAGE_FR = 6;
    LANGUAGE_DE = 7;
    LANGUAGE_ES = 8;
    LANGUAGE_PT = 9;
    LANGUAGE_RU = 10;
    LANGUAGE_TH = 11;
    LANGUAGE_VI = 12;
    LANGUAGE_ID = 13;
}

message MEPHKJFAJPP {
    string NLONGNHNECG = 1;
    string BHNHGPCGKMA = 2;
    string CKACNADCDFP = 3;
    string EIDOKHKEOPP = 4;
    string HELMPDCKLEO = 5;
    string DFBLOBNLHCC = 6;
    string GLEEJNEJACP = 7;
}

message MonthCardRewardNotify {
    ItemList reward = 2;
}

message PNOLLIAKGDB {
    uint32 JHJKCJKDHIB = 7;
    bool MLPGDPGIFCJ = 2;
    bool BELKCBAGMFC = 9;
}

message PlayerGetTokenCsReq {
    uint32 channel_id = 7;
    uint32 uid = 8;
    uint32 account_ip_port = 15;
    string EKLOGGLELCG = 6;
    uint32 platform = 13;
    string account_uid = 9;
    uint32 sign_type = 10;
    string token = 1;
    uint32 account_ip = 2;
}

message PlayerGetTokenScRsp {
    BlackInfo black_info = 10;
    uint32 retcode = 1;
    string authkey = 4;
    uint64 secret_key_seed = 9;
    string stop_desc = 11;
    uint32 uid = 15;
}

message PlayerHeartBeatCsReq {
    LFKKOMBKJIP sc_data = 11;
    uint64 client_time_ms = 9;
    uint32 EOHFCODKKMD = 10;
}

message PlayerHeartBeatScRsp {
    uint64 client_time_ms = 13;
    ClientDownloadData download_data = 12;
    uint32 retcode = 9;
    uint64 server_time_ms = 8;
}

message PlayerLoginCsReq {
    string JKGAKDALFPE = 1186;
    string IJKOMIKFKEK = 1320;
    string NIBMFCFBHEP = 9;
    uint32 JMMHHFLEEPG = 15;
    CMCJFJEBBCO EONDGECNAIH = 1372;
    PlatformType platform = 10;
    string MGNLIGIKKPP = 2009;
    MEPHKJFAJPP HNPMEDIEJFC = 2032;
    string BJCIBNBGBMP = 13;
    uint64 login_random = 4;
    uint32 KPFGILOFIDI = 311;
    string LFLCDNGALME = 14;
    bool MENBLJOGJMH = 904;
    LanguageType HOFEMNAIIHB = 6;
    string BDGDPMALNIF = 2;
    string BAOGDOFPPLN = 1;
    bool ACJKHHBJKHE = 1279;
    string JHOKMNLHBMA = 12;
    string signature = 7;
    string IHMJHLLCLDE = 8;
    string IDIFIEPMLKA = 88;
    string GDMJPJCKBBE = 3;
    uint32 FKFFBEMEIEP = 1869;
    string LPBHJODECNE = 1570;
    uint32 client_res_version = 5;
    string LDCIBPHDAKI = 11;
    uint32 channel_id = 454;
    string DJONELMIFEE = 558;
}

message PlayerLoginFinishCsReq {
}

message PlayerLoginFinishScRsp {
    uint32 retcode = 11;
}

message PlayerLoginScRsp {
    uint64 login_random = 10;
    bool KDNPPNHLNOA = 12;
    uint32 stamina = 15;
    bool KCDAHNNCKPP = 8;
    string GIOAPOKHAOF = 2;
    int32 cur_timezone = 7;
    uint32 retcode = 3;
    PlayerBasicInfo basic_info = 9;
    string DKEPKHPOLHC = 14;
    uint64 server_timestamp_ms = 11;
}

message PlayerLogoutCsReq {
}

message PlayerSettingInfo {
    bool LNGHIJGFDKP = 1965;
    bool BOMGNMDOGLM = 12;
    bool MAKOLELFLFH = 2;
    bool PFBHGAHAFMD = 1;
    bool NJAKOMDMFJD = 11;
    bool BBEEBBIDJHE = 1023;
    bool IOJEAOCOBBF = 15;
    bool GOKFNGFFMOB = 1560;
    PNOLLIAKGDB OJPAODIHAJE = 6;
    bool GNFDDPEMMFN = 5;
    bool DCJECFMMIBC = 4;
    repeated KVP OKAHMFOINPM = 1809;
    JPGACKPLGCD CMFCOOEEECB = 727;
    bool AACOEHCFNDB = 7;
    bool HGPFFGKNPFB = 212;
    bool DGCNHMIHFJB = 8;
    bool FDHEPCKLCAM = 10;
}

message Product {
    string product_id = 3;
    bool double_reward = 2;
    int64 begin_time = 8;
    uint32 EMIHEDNKBCA = 5;
    uint32 CLDELMPNAPB = 4;
    int64 end_time = 10;
    uint32 ENCDABOOIKJ = 13;
    ProductGiftType gift_type = 9;
    string price_tier = 7;
}

enum ProductGiftType {
    ProductGiftType_ProductGiftNone = 0;
    ProductGiftType_ProductGiftCoin = 1;
    ProductGiftType_ProductGiftMonthCard = 2;
    ProductGiftType_ProductGiftBp68 = 3;
    ProductGiftType_ProductGiftBp128 = 4;
    ProductGiftType_ProductGiftBp68Upgrade128 = 5;
    ProductGiftType_ProductGiftPointCard = 6;
    ProductGiftType_ProductGiftPsPreOrder1 = 7;
    ProductGiftType_ProductGiftPsPreOrder2 = 8;
    ProductGiftType_ProductGiftGooglePoints100 = 9;
    ProductGiftType_ProductGiftGooglePoints150 = 10;
    ProductGiftType_ProductGiftPsPointCard030 = 11;
    ProductGiftType_ProductGiftPsPointCard050 = 12;
    ProductGiftType_ProductGiftPsPointCard100 = 13;
    ProductGiftType_ProductGiftPsnPlus = 14;
    ProductGiftType_ProductGiftSingle6 = 15;
    ProductGiftType_ProductGiftDailyLogin30 = 16;
    ProductGiftType_ProductGiftAppleGiftCard = 17;
    ProductGiftType_ProductGiftFtcUpGachaTicket1 = 18;
    ProductGiftType_ProductGiftFtcUpGachaTicket10 = 19;
    ProductGiftType_ProductGiftFtcNormalGachaTicket1 = 20;
    ProductGiftType_ProductGiftFtcNormalGachaTicket10 = 21;
    ProductGiftType_ProductGiftTicket10 = 22;
    ProductGiftType_ProductGiftPlayerHeadDecor = 23;
    ProductGiftType_ProductGiftReturnSign = 24;
    ProductGiftType_ProductGiftExtraValueTicket1 = 25;
}

message QueryProductInfoCsReq {
}

message QueryProductInfoScRsp {
    uint32 retcode = 15;
    uint64 month_card_out_date_time = 12;
    uint32 BFFHEKCGLMA = 4;
    uint32 BEBFNDIGKFK = 5;
    repeated Product product_list = 1;
}

message RegionStopScNotify {
    int64 stop_end_time = 7;
    int64 stop_begin_time = 8;
}

message ReserveStaminaExchangeCsReq {
    uint32 num = 10;
}

message ReserveStaminaExchangeScRsp {
    uint32 num = 13;
    uint32 retcode = 11;
}

message SecretKeyInfo {
    SecretKeyType type = 3;
    string secret_key = 6;
}

enum SecretKeyType {
    SECRET_KEY_NONE = 0;
    SECRET_KEY_SERVER_CHECK = 1;
    SECRET_KEY_VIDEO = 2;
    SECRET_KEY_BATTLE_TIME = 3;
}

message ServerAnnounceNotify {
    repeated AnnounceData announce_data_list = 11;
}

message SetGameplayBirthdayCsReq {
    uint32 birthday = 8;
}

message SetGameplayBirthdayScRsp {
    uint32 retcode = 9;
    uint32 birthday = 3;
}

message SetGenderCsReq {
    Gender gender = 13;
}

message SetGenderScRsp {
    MultiPathAvatarType cur_avatar_path = 7;
    uint32 retcode = 2;
}

message SetLanguageCsReq {
    LanguageType HOFEMNAIIHB = 5;
}

message SetLanguageScRsp {
    uint32 retcode = 9;
    LanguageType HOFEMNAIIHB = 10;
}

message SetNicknameCsReq {
    string nickname = 13;
    bool is_modify = 4;
}

message SetNicknameScRsp {
    bool is_modify = 7;
    uint32 retcode = 3;
    int64 set_time = 6;
}

message SetPlayerInfoCsReq {
    string nickname = 4;
    Gender gender = 15;
    bool is_modify = 9;
}

message SetPlayerInfoScRsp {
    int64 set_time = 15;
    uint32 retcode = 10;
    MultiPathAvatarType cur_avatar_path = 2;
    bool is_modify = 8;
}

message SetRedPointStatusScNotify {
    uint32 BMFJFFBPADD = 9;
    repeated LFCHHMGGMPC BKAKIJOACPO = 13;
    uint32 uid = 15;
    uint32 content_id = 4;
    uint32 show_type = 3;
}

message StaminaInfoScNotify {
    uint32 stamina = 14;
    uint32 reserve_stamina = 13;
    int64 EHJCPBJNEOO = 5;
    int64 next_recover_time = 9;
}

message UpdateFeatureSwitchScNotify {
    repeated HDOKNMGIDMB switch_info_list = 9;
}

message UpdatePlayerSetting {
    oneof BKAGLMFNKKA {
        bool AACOEHCFNDB = 9;
        bool DGCNHMIHFJB = 14;
        bool FDHEPCKLCAM = 13;
        bool DCJECFMMIBC = 11;
        bool IOJEAOCOBBF = 15;
        bool PFBHGAHAFMD = 3;
        bool GNFDDPEMMFN = 7;
        bool MAKOLELFLFH = 5;
        bool NJAKOMDMFJD = 12;
        PNOLLIAKGDB OJPAODIHAJE = 2;
        bool BOMGNMDOGLM = 1701;
        bool BBEEBBIDJHE = 85;
        bool HGPFFGKNPFB = 1503;
        bool LNGHIJGFDKP = 761;
        bool GOKFNGFFMOB = 654;
        JPGACKPLGCD CMFCOOEEECB = 1412;
        KVP EGLOIFDIDPK = 1077;
    }
}

message UpdatePlayerSettingCsReq {
    UpdatePlayerSetting player_setting = 12;
}

message UpdatePlayerSettingScRsp {
    UpdatePlayerSetting player_setting = 5;
    uint32 retcode = 11;
}

message VideoKeyInfo {
    uint64 AFBDJOIHOID = 1;
    uint64 IBDIMHPOPOJ = 12;
    uint32 id = 4;
    uint64 video_key = 11;
}
