syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message AcceptedPamMissionExpireCsReq {
    uint32 main_mission_id = 4;
}

message AcceptedPamMissionExpireScRsp {
    uint32 retcode = 4;
}

enum CmdPamMissionType {
    CmdPamMissionType_None = 0;
    CmdPamMissionType_SyncAcceptedPamMissionNotify = 4079;
    CmdPamMissionType_AcceptedPamMissionExpireCsReq = 4034;
    CmdPamMissionType_AcceptedPamMissionExpireScRsp = 4082;
}

message SyncAcceptedPamMissionNotify {
    uint32 main_mission_id = 11;
    uint64 expire_time = 9;
}
