syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AvatarSync {
    repeated Avatar avatar_list = 8;
    repeated AvatarPathData avatar_path_data_info_list = 14;
}

message BasicModuleSync {
    uint32 DLODAKOHFOP = 9;
    uint32 stamina = 6;
}

message CCHMHOONEGG {
    uint32 OCJLBKDCKHL = 8;
    uint32 num = 14;
}

enum CmdPlayerSyncType {
    CmdPlayerSyncType_CmdPlayerSyncNone = 0;
    CmdPlayerSyncType_PlayerSyncScNotify = 634;
}

message GroupStatus {
    int64 refresh_time = 15;
    MessageGroupStatus group_status = 5;
    uint32 group_id = 1;
}

message MJBANFPPEFH {
    uint32 id = 10;
    ONHKODAFEMH custom_value_list = 577;
}

message MissionSync {
    repeated Mission mission_list = 3;
    repeated MJBANFPPEFH NLPKLNDCMOC = 2;
    repeated uint32 finished_main_mission_id_list = 10;
    repeated uint32 LEBFLAKCJCM = 7;
    repeated uint32 DEPBONHELFD = 5;
    repeated uint32 OBCBLABECEA = 1;
}

message PFNHCOJOBKH {
    repeated uint32 LKAKMGKENOI = 1;
    repeated uint32 ABMLLCOKOLN = 12;
}

message PlayerBoardModuleSync {
    HeadFrameInfo head_frame_info = 10;
    repeated uint32 GHNJNFKJEDC = 14;
    bool MFFGEMKLNBF = 11;
    string signature = 6;
    repeated HeadIconData unlocked_head_icon_list = 15;
}

message PlayerSyncScNotify {
    BasicModuleSync JHJNMOFMPMO = 15;
    PlayerBoardModuleSync update_player_board_module_list = 981;
    CJLCPMDGIBO DHKFCDAGHDM = 1458;
    ItemList FHHGDACMJED = 326;
    repeated NLLLAAEJOBP update_platform_bound_gifts_list = 1618;
    repeated Material material_list = 4;
    repeated NKDNFDCFNCP NMBAFJGFOIH = 1855;
    repeated WaitDelResource wait_del_resource_list = 7;
    repeated CCHMHOONEGG JIEOHBBDJDA = 1118;
    PlayerBasicInfo basic_info = 12;
    repeated uint32 del_equipment_list = 9;
    SyncStatus sync_status = 283;
    repeated Material NAJFMIIFIEC = 1517;
    repeated Relic relic_list = 3;
    PFNHCOJOBKH update_pet_summon_items_list = 192;
    repeated Equipment equipment_list = 6;
    repeated uint32 del_relic_list = 14;
    AvatarSync avatar_sync = 5;
    MissionSync mission_sync = 8;
    repeated Quest quest_list = 1;
}

message SectionStatus {
    uint32 section_id = 2;
    MessageSectionStatus section_status = 14;
}

message SyncStatus {
    repeated GroupStatus message_group_status = 5;
    repeated uint32 BGPACBIJDCH = 15;
    repeated uint32 MDANGIEIMIF = 3;
    repeated SectionStatus section_status = 14;
}
