syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AEGGFGBNLPE {
    bool FOGGEJIIJCM = 9;
}

message AGBPBAOCCJF {
    bool is_win = 3;
}

message ALLFGCIALIJ {
    uint32 JNBIALMKFCL = 6;
    repeated EMHEOJNCGFH grid_fight_equipment_list = 3;
}

message AOPODAHBPFH {
    uint32 content_id = 8;
    uint32 content_type = 5;
}

message BMOIPALHBJN {
    uint32 AAIODNCLAIP = 8;
    uint32 shop_id = 13;
    uint32 JOMDKGINNEK = 2;
    repeated NJHFBDDHCEN OGDKJPDFFAI = 6;
}

message CCPCAIGEBCB {
    uint32 CCBIIDDBFGK = 12;
}

message CKICDPIJIMF {
    uint32 battle_id = 11;
}

enum CmdPixAirType {
    CmdPixAirType_None = 0;
    CmdPixAirType_PixAirBuyGoodsCsReq = 9777;
    CmdPixAirType_PixAirStartStageScRsp = 9778;
    CmdPixAirType_PixAirHandlePendingActionCsReq = 9808;
    CmdPixAirType_PixAirRefreshShopCsReq = 9812;
    CmdPixAirType_PixAirChangePosScRsp = 9789;
    CmdPixAirType_PixAirReenterStageCsReq = 9807;
    CmdPixAirType_PixAirEnableTalentCsReq = 9795;
    CmdPixAirType_PixAirUnlockPlaneCsReq = 9805;
    CmdPixAirType_PixAirHandlePendingActionScRsp = 9791;
    CmdPixAirType_PixAirGetDataCsReq = 9806;
    CmdPixAirType_PixAirChangePosCsReq = 9787;
    CmdPixAirType_PixAirSyncChangeScNotify = 9814;
    CmdPixAirType_PixAirSellEquipCsReq = 9782;
    CmdPixAirType_PixAirEnableTalentScRsp = 9774;
    CmdPixAirType_PixAirStartStageCsReq = 9794;
    CmdPixAirType_PixAirPauseStageScRsp = 9780;
    CmdPixAirType_PixAirSellEquipScRsp = 9771;
    CmdPixAirType_PixAirReenterStageScRsp = 9790;
    CmdPixAirType_PixAirQuitStageCsReq = 9792;
    CmdPixAirType_PixAirRefreshShopScRsp = 9788;
    CmdPixAirType_PixAirBuyGoodsScRsp = 9784;
    CmdPixAirType_PixAirQuitStageScRsp = 9802;
    CmdPixAirType_PixAirGetDataScRsp = 9799;
    CmdPixAirType_PixAirUnlockPlaneScRsp = 9817;
    CmdPixAirType_PixAirPauseStageCsReq = 9811;
}

message EIFBMCGPNMG {
    map<uint32, uint32> EOPNCAMILJF = 7;
}

message EMHEOJNCGFH {
    uint32 grid_fight_equipment_id = 4;
    uint32 level = 14;
}

message EPBFAAHFDNF {
    repeated MGCPEPBPMNG KFNMIEMBJGD = 14;
    uint32 event_id = 6;
}

message FFKHFDJFAGM {
    uint32 queue_position = 4;
    CKICDPIJIMF BACBKGJJOGA = 5;
    PKPHOOGGPOL IBIFHOIPAGE = 12;
    FJGMGGIGLPD MOFNIOJHBBL = 3;
    KAAJEKKIDIE IPKGIIJEPAJ = 13;
    ALLFGCIALIJ JFGIMDGOMBH = 10;
    EPBFAAHFDNF OOOACLEFDGM = 7;
    HIEACFOEMCE ADMICNGJLOI = 939;
    CCPCAIGEBCB AOEMGEFGIFG = 1452;
}

message FJGMGGIGLPD {
}

message GANGPOOHAKI {
    uint32 PEBCBLBLMPH = 6;
}

message GCINPDAAELN {
    repeated JPEBEDHMNLA grid_fight_equipment_list = 6;
}

message GDNDBHGJBLF {
    uint32 PEBCBLBLMPH = 11;
}

enum GJIGHKNMILJ {
    GJIGHKNMILJ_NCMIMMDPHFM = 0;
    GJIGHKNMILJ_PJFGLBEKECE = 1;
    GJIGHKNMILJ_INCLHHDFCEL = 2;
    GJIGHKNMILJ_BGDCOCGIONK = 3;
}

message HGNAHHFBMMN {
    FFKHFDJFAGM FMIGOKIDKJL = 4;
    string trans_no = 10;
    uint32 MFPOKNMFNGM = 13;
    uint32 PAEAKCCACOP = 14;
    uint32 GJLDDMIIILF = 9;
    uint32 AJHDCEGIGMC = 6;
    uint32 ALJNIHNLNMA = 11;
    IDJALKEGPLI basic = 12;
    BMOIPALHBJN NGNJHMEOHBD = 1;
    LHJDEOLKHKB JGEMNOLFNIE = 15;
    repeated KVP switch_list = 7;
    uint32 stage_id = 2;
}

message HIEACFOEMCE {
    uint32 HICEJEJNOLE = 7;
}

message HLDLJBFIMOO {
    uint32 HAFOKMHCGFM = 9;
}

message IDJALKEGPLI {
    repeated KVP DCJDCPMKEPN = 11;
    uint32 plane_id = 14;
}

message IIFHCHDPKIA {
    uint32 queue_position = 11;
    AGBPBAOCCJF DHJNFOKBPNC = 7;
    OHPMDJFALNH JEIODBPCKNB = 5;
    MOJCEJIPPGO MOFNIOJHBBL = 6;
    AEGGFGBNLPE IPKGIIJEPAJ = 12;
    LJGKOGKEDOA JFGIMDGOMBH = 10;
    HLDLJBFIMOO OOOACLEFDGM = 14;
    GANGPOOHAKI ADMICNGJLOI = 941;
    GDNDBHGJBLF AOEMGEFGIFG = 1366;
}

message ILBJGGEHAEK {
    uint32 unique_id = 3;
}

message IMAGFGIHLJC {
    uint32 CDMFHNGEFCN = 9;
    uint32 area_id = 7;
    uint32 AJHDCEGIGMC = 12;
}

enum JDHJMNAGIIA {
    JDHJMNAGIIA_CDCHHNPNPLN = 0;
    JDHJMNAGIIA_EECEDOKMPPI = 1;
    JDHJMNAGIIA_PGGEODDBMMK = 2;
    JDHJMNAGIIA_PJGPLEAPECI = 3;
    JDHJMNAGIIA_BFLLFGOJPCG = 4;
    JDHJMNAGIIA_JAOLOFNICGD = 5;
    JDHJMNAGIIA_KAPHNBBNHBP = 6;
    JDHJMNAGIIA_DAJDHGGFJGK = 7;
    JDHJMNAGIIA_KEDPGJCCLDC = 8;
    JDHJMNAGIIA_MDMMEAKJNOC = 9;
    JDHJMNAGIIA_CDKPJHAEMFE = 10;
    JDHJMNAGIIA_CCJKIBNAFPJ = 11;
    JDHJMNAGIIA_NIBDPFIMOFG = 12;
    JDHJMNAGIIA_KGJCNJPFCNO = 13;
    JDHJMNAGIIA_CPBNIGEIKJA = 14;
}

message JPEBEDHMNLA {
    uint32 pos = 7;
    uint32 level = 15;
    uint32 CCBIIDDBFGK = 13;
    uint32 grid_fight_equipment_id = 5;
    uint32 unique_id = 14;
}

message KAAJEKKIDIE {
    EMHEOJNCGFH equip = 15;
}

message KLBPBDLHKBG {
    JDHJMNAGIIA source_type = 3;
    uint32 BNEFLBPCPOI = 7;
    FFKHFDJFAGM FMIGOKIDKJL = 2;
    NBKKABHMMPP IANBCDJPDJF = 4;
    GCINPDAAELN EKEFDIEPHEE = 14;
    uint32 FKIAFJBMAPI = 1;
    IMAGFGIHLJC JKPINLKEOOK = 13;
    EIFBMCGPNMG DLOHBPGEMFF = 10;
    NNFFGHJKPJD KJHMPBOIGGE = 300;
    uint32 JOINHCDHNNL = 269;
    uint32 PMFBIGLPJJA = 1034;
    uint32 OEKKEIMGBNO = 1427;
}

message KNHFDINIJOL {
}

message LHJDEOLKHKB {
    uint32 slot_num = 6;
    repeated JPEBEDHMNLA MKJECBOMHPP = 8;
    repeated JPEBEDHMNLA DPPJILKLJAG = 3;
}

message LIFDLLPAAKF {
}

message LJGKOGKEDOA {
    uint32 OJEIHPEIJCO = 10;
}

message MGCPEPBPMNG {
    uint32 content_id = 9;
    uint32 HAFOKMHCGFM = 2;
}

message MOJCEJIPPGO {
}

message NAJFNKIEEDM {
    repeated uint32 BLHJIPBHHFO = 11;
}

message NBKKABHMMPP {
    uint32 HGBHCLHCGBB = 1117;
    ItemList reward = 7;
    uint32 NJPMPAAGCCD = 15;
    uint32 score_id = 10;
    uint32 GMLCJEOOCHJ = 2;
    uint32 OACBLHIIIEH = 743;
    uint32 ALOFCOLHAGA = 13;
    GJIGHKNMILJ reason = 5;
}

message NJHFBDDHCEN {
    uint32 grid_fight_equipment_id = 4;
    bool LHGIFDNPIDE = 12;
    uint32 level = 13;
}

message NMACHAFCGNI {
    uint32 MFPOKNMFNGM = 11;
    IDJALKEGPLI basic = 12;
    uint32 ALJNIHNLNMA = 15;
    uint32 stage_id = 2;
}

message NNFFGHJKPJD {
    uint32 AAIODNCLAIP = 14;
    repeated NJHFBDDHCEN OGDKJPDFFAI = 7;
    uint32 shop_id = 11;
    uint32 JOMDKGINNEK = 15;
}

message OHPMDJFALNH {
    uint32 content_id = 1;
}

message PKPHOOGGPOL {
    repeated AOPODAHBPFH message_datas = 14;
}

message PixAirBuyGoodsCsReq {
    uint32 FIEDIDHOLDJ = 10;
}

message PixAirGetDataCsReq {
}

message PixAirGetDataScRsp {
    NMACHAFCGNI IEIGEDABKAD = 3;
    uint32 retcode = 7;
    repeated uint32 OPOJIGCHGDO = 15;
    uint32 score_id = 12;
    NAJFNKIEEDM JCOBJAMPOAL = 2;
    repeated uint32 PGMIJBOGIKN = 4;
}

message PixAirReenterStageCsReq {
}

message PixAirReenterStageScRsp {
    HGNAHHFBMMN stage_info = 12;
    uint32 retcode = 8;
}

message PixAirRefreshShopCsReq {
}

message PixAirStartStageCsReq {
    bool EMMGHDLIPOH = 7;
    uint32 plane_id = 13;
    uint32 ALJNIHNLNMA = 10;
    uint32 stage_id = 14;
}

message PixAirStartStageScRsp {
    bool EMMGHDLIPOH = 15;
    HGNAHHFBMMN stage_info = 5;
    uint32 retcode = 10;
}

message PixAirSyncChangeScNotify {
    repeated KLBPBDLHKBG DGNGMJMPFGK = 6;
}

message PixAirUnlockPlaneCsReq {
    uint32 plane_id = 8;
}

message PixAirUnlockPlaneScRsp {
    uint32 plane_id = 6;
    uint32 retcode = 8;
}
