syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message ABEBEOKFKFF {
    uint32 cnt = 6;
    EJEGHJPAMPI type = 1;
}

message BADOONPCDLO {
    bool AJGOLAKNGPA = 6;
    uint32 level_id = 3;
    uint32 time = 8;
}

message BDEOLCNPBPP {
    uint32 id = 5;
    uint32 cnt = 10;
}

message COIMBCBMNIE {
    uint32 level_id = 11;
    repeated HANMCLKOCBO BEDHEKAGAPE = 10;
}

enum CmdParkourType {
    CmdParkourType_None = 0;
    CmdParkourType_ParkourGetRankingInfoCsReq = 8400;
    CmdParkourType_ParkourEndLevelScRsp = 8394;
    CmdParkourType_ParkourStartLevelScRsp = 8392;
    CmdParkourType_ParkourGetDataScRsp = 8395;
    CmdParkourType_ParkourGetDataCsReq = 8385;
    CmdParkourType_ParkourGetRankingInfoScRsp = 8393;
    CmdParkourType_ParkourEndLevelCsReq = 8391;
    CmdParkourType_ParkourStartLevelCsReq = 8389;
}

enum EJEGHJPAMPI {
    EJEGHJPAMPI_BACKHOLLHDC = 0;
    EJEGHJPAMPI_HAAFIJPEJOO = 1;
    EJEGHJPAMPI_FPPDHDLGACM = 2;
}

message HANMCLKOCBO {
    uint32 LJJGFIPLDLI = 11;
    uint32 time = 10;
    uint32 id = 5;
}

message IJJFBFPCBCI {
    uint32 IEOJFKHKBEP = 3;
    uint32 KBFHFLODGIA = 10;
    uint32 ICBKCJKHNBP = 6;
    uint32 BLEFGKAGDEN = 8;
}

enum OHFECKKADEK {
    OHFECKKADEK_NLCDGIPGFDJ = 0;
    OHFECKKADEK_CIHFGJDCHIA = 1;
    OHFECKKADEK_INCLHHDFCEL = 2;
}

message OIHEIIDJOLI {
    uint32 GCAFHJIAMIL = 14;
    uint32 NCMMFCJGDKA = 8;
    uint32 FPIDONGEKFO = 2;
    uint32 GOMFPKDIIKA = 15;
    uint32 GBOLMEOHEOB = 4;
    repeated BDEOLCNPBPP OECOCOPOOHO = 13;
    uint32 DHJEALPGPJK = 3;
    uint32 MGPMDJOMMOK = 1;
    uint32 GPHNIOGICJP = 6;
    uint32 BAPPKHBKOAG = 9;
    uint32 PLOEMBOCIGE = 12;
}

message ParkourEndLevelCsReq {
    OIHEIIDJOLI PKMAFFMMMAE = 15;
    repeated IJJFBFPCBCI FENPLCNDKBJ = 4;
    uint32 CEKKJHBNEOD = 1;
    uint32 time = 8;
    uint32 total_time = 13;
    repeated ABEBEOKFKFF IDLJKFOKBJD = 2;
    uint32 rank = 11;
    uint32 level_id = 3;
    OHFECKKADEK end_reason = 6;
    uint32 KMGMFCJIAPI = 7;
}

message ParkourEndLevelScRsp {
    uint32 level_id = 9;
    uint32 retcode = 14;
    BADOONPCDLO ENKCCEACJKL = 2;
    uint32 time = 10;
    OHFECKKADEK end_reason = 1;
    bool AJGOLAKNGPA = 3;
    bool ADJLGNBJAOC = 6;
}

message ParkourGetDataCsReq {
}

message ParkourGetDataScRsp {
    uint32 retcode = 14;
    repeated BADOONPCDLO CGIPFMLDPNA = 15;
}

message ParkourGetRankingInfoCsReq {
}

message ParkourGetRankingInfoScRsp {
    repeated COIMBCBMNIE JNMFKJHCOEG = 6;
    COIMBCBMNIE LGFNFABAAGA = 1;
    uint32 retcode = 7;
}

message ParkourStartLevelCsReq {
    uint32 level_id = 9;
    uint32 CEKKJHBNEOD = 8;
}

message ParkourStartLevelScRsp {
    uint32 level_id = 9;
    uint32 retcode = 5;
    uint32 CEKKJHBNEOD = 12;
}
