syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CDCCPHILOCC {
    uint32 uid = 1;
    uint32 monster_id = 2;
}

message CJDIAHDLCNJ {
    uint32 uid = 1;
    uint32 damage_hp = 2;
    bool is_final_hit = 3;
    uint32 over_kill_damage_hp = 4;
    string battle_replay_key = 5;
    repeated GOFFDNPBHIK avatar_list = 6;
    uint32 assist_score = 7;
    uint32 damage_score = 8;
    uint32 final_hit_score = 9;
}

enum CmdPunkLordType {
    CmdPunkLordType_None = 0;
    CmdPunkLordType_TakeKilledPunkLordMonsterScoreScRsp = 3214;
    CmdPunkLordType_PunkLordMonsterKilledNotify = 3209;
    CmdPunkLordType_GetPunkLordBattleRecordScRsp = 3244;
    CmdPunkLordType_GetKilledPunkLordMonsterDataCsReq = 3238;
    CmdPunkLordType_PunkLordBattleResultScNotify = 3241;
    CmdPunkLordType_PunkLordMonsterInfoScNotify = 3204;
    CmdPunkLordType_StartPunkLordRaidScRsp = 3239;
    CmdPunkLordType_SharePunkLordMonsterCsReq = 3256;
    CmdPunkLordType_TakePunkLordPointRewardCsReq = 3280;
    CmdPunkLordType_GetKilledPunkLordMonsterDataScRsp = 3257;
    CmdPunkLordType_SharePunkLordMonsterScRsp = 3291;
    CmdPunkLordType_GetPunkLordDataScRsp = 3249;
    CmdPunkLordType_PunkLordRaidTimeOutScNotify = 3288;
    CmdPunkLordType_SummonPunkLordMonsterScRsp = 3226;
    CmdPunkLordType_GetPunkLordMonsterDataScRsp = 3282;
    CmdPunkLordType_TakeKilledPunkLordMonsterScoreCsReq = 3224;
    CmdPunkLordType_StartPunkLordRaidCsReq = 3279;
    CmdPunkLordType_GetPunkLordMonsterDataCsReq = 3234;
    CmdPunkLordType_SummonPunkLordMonsterCsReq = 3298;
    CmdPunkLordType_GetPunkLordBattleRecordCsReq = 3223;
    CmdPunkLordType_TakePunkLordPointRewardScRsp = 3271;
    CmdPunkLordType_GetPunkLordDataCsReq = 3262;
    CmdPunkLordType_PunkLordDataChangeNotify = 3205;
}

message FGFGINEFBBK {
    int64 create_time = 11;
    uint32 config_id = 10;
    uint32 FJKDAFHKPGC = 3;
    uint32 monster_id = 9;
    bool APCMAIJPPEH = 8;
    uint32 world_level = 15;
}

message GMDHIALLILJ {
    repeated CJDIAHDLCNJ GAIKBNPIFLM = 1;
}

message GOFFDNPBHIK {
    uint32 avatar_id = 1;
    uint32 avatar_level = 2;
}

message GetKilledPunkLordMonsterDataCsReq {
}

message GetKilledPunkLordMonsterDataScRsp {
    repeated FGFGINEFBBK CPPDAIMLDGB = 7;
    uint32 retcode = 4;
    repeated CDCCPHILOCC BLLLCPONFBE = 9;
}

message GetPunkLordBattleRecordCsReq {
    CDCCPHILOCC KHOLBEGBFOM = 1;
}

message GetPunkLordBattleRecordScRsp {
    repeated TryDownLoadReplay HLCIMLHMEKI = 7;
    CDCCPHILOCC KHOLBEGBFOM = 13;
    repeated CJDIAHDLCNJ GAIKBNPIFLM = 14;
    uint32 retcode = 11;
}

message GetPunkLordDataCsReq {
}

message GetPunkLordDataScRsp {
    uint32 retcode = 15;
    uint32 KCBPBMOJOKJ = 10;
    uint32 GIIIFDGFJPG = 4;
    uint32 BPCOIOLGEMK = 1;
    uint32 LCAFKPGBDOL = 14;
    uint32 MGBHJPPJHEA = 11;
    repeated uint32 IEPPNGMCKJH = 8;
    int64 NEOGLPEGBHE = 9;
}

message GetPunkLordMonsterDataCsReq {
}

message GetPunkLordMonsterDataScRsp {
    repeated JEIAEAEGEBJ PBLBBDBDLEK = 9;
    uint32 retcode = 1;
}

message JEIAEAEGEBJ {
    PunkLordMonsterBasicInfo basic_info = 2;
    uint32 HDHIFJNJOBK = 1;
    GMDHIALLILJ FDJHMFAGEOA = 5;
    PunkLordAttackerStatus HCEENPENFGI = 4;
}

enum PAKHPLAHGBN {
    PAKHPLAHGBN_NLCDGIPGFDJ = 0;
    PAKHPLAHGBN_FIOLLIOEAJC = 1;
    PAKHPLAHGBN_CJMELLLIEDE = 2;
    PAKHPLAHGBN_COGCFDFAKON = 3;
}

enum PunkLordAttackerStatus {
    PunkLordAttackerStatus_None = 0;
    PunkLordAttackerStatus_Attacked = 1;
    PunkLordAttackerStatus_Attacking = 2;
    PunkLordAttackerStatus_AttackedAndAttacking = 3;
}

message PunkLordBattleResultScNotify {
    CJDIAHDLCNJ FDJHMFAGEOA = 8;
    PunkLordMonsterBasicInfo ONICJOAOEMA = 7;
    uint32 assist_score = 10;
    uint32 final_hit_score = 12;
    uint32 damage_score = 6;
}

message PunkLordDataChangeNotify {
    uint32 BPCOIOLGEMK = 2;
    uint32 MGBHJPPJHEA = 1;
    uint32 GIIIFDGFJPG = 13;
}

message PunkLordMonsterBasicInfo {
    uint32 uid = 1;
    uint32 monster_id = 2;
    uint32 config_id = 3;
    uint32 world_level = 4;
    int64 create_time = 5;
    uint32 left_hp = 6;
    uint32 attacker_num = 7;
    PunkLordShareType share_type = 8;
    bool APCMAIJPPEH = 9;
}

message PunkLordMonsterInfoScNotify {
    CJDIAHDLCNJ FDJHMFAGEOA = 11;
    PAKHPLAHGBN reason = 12;
    repeated uint32 FNMGMNABAJG = 10;
    PunkLordMonsterBasicInfo basic_info = 4;
}

message PunkLordMonsterKilledNotify {
    FGFGINEFBBK PEBMDFAGJAM = 11;
}

message PunkLordRaidTimeOutScNotify {
    PunkLordMonsterBasicInfo ONICJOAOEMA = 14;
}

enum PunkLordShareType {
    PunkLordShareType_None = 0;
    PunkLordShareType_Friend = 1;
    PunkLordShareType_All = 2;
}

message ReplayInfo {
    uint64 LMFBCHEHOLO = 1;
    PBIEFHKNAFA replay_type = 2;
    uint32 stage_id = 3;
    uint32 uid = 4;
    string nickname = 5;
    uint32 head_icon = 6;
    string replay_name = 7;
    uint64 create_time = 8;
    uint32 KLIFGJOILEE = 9;
    uint32 PBNIENNCNOP = 10;
}

message SharePunkLordMonsterCsReq {
    uint32 uid = 9;
    uint32 monster_id = 14;
    PunkLordShareType share_type = 2;
}

message SharePunkLordMonsterScRsp {
    uint32 retcode = 4;
    uint32 uid = 5;
    uint32 monster_id = 13;
    PunkLordShareType share_type = 7;
}

message StartPunkLordRaidCsReq {
    uint32 monster_id = 6;
    uint32 uid = 12;
    bool IDMPMEOCJIK = 7;
}

message StartPunkLordRaidScRsp {
    GEGLJDELBHA scene = 15;
    int64 PEAMKPJKIEL = 11;
    bool IDMPMEOCJIK = 13;
    uint32 retcode = 6;
    repeated uint32 FNMGMNABAJG = 4;
    JEIAEAEGEBJ ONICJOAOEMA = 9;
}

message SummonPunkLordMonsterCsReq {
}

message SummonPunkLordMonsterScRsp {
    uint32 retcode = 14;
    JEIAEAEGEBJ ONICJOAOEMA = 11;
}

message TakeKilledPunkLordMonsterScoreScRsp {
    uint32 retcode = 6;
    uint32 score_id = 11;
    repeated CDCCPHILOCC DFJFJNPCIPA = 10;
    bool LOMGNMFAPGE = 8;
}

message TakePunkLordPointRewardCsReq {
    bool LEFJBFMDEGK = 14;
    uint32 level = 6;
}

message TakePunkLordPointRewardScRsp {
    uint32 retcode = 15;
    uint32 level = 14;
    bool LEFJBFMDEGK = 4;
    ItemList reward = 10;
}

message TryDownLoadReplay {
    string battle_replay_key = 1;
    ReplayInfo replay_info = 2;
}
