syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdPlanetFesExtType {
    CmdPlanetFesExtType_None = 0;
    CmdPlanetFesExtType_PlanetFesChangeCardPieceApplyPermissionCsReq = 8298;
    CmdPlanetFesExtType_PlanetFesHandleCardPieceApplyScRsp = 8328;
    CmdPlanetFesExtType_PlanetFesGetExtraCardPieceInfoCsReq = 8326;
    CmdPlanetFesExtType_PlanetFesLargeBonusInteractScRsp = 8297;
    CmdPlanetFesExtType_PlanetFesEnterNextBusinessDayScRsp = 8332;
    CmdPlanetFesExtType_PlanetFesGiveCardPieceCsReq = 8309;
    CmdPlanetFesExtType_PlanetFesApplyCardPieceScRsp = 8327;
    CmdPlanetFesExtType_PlanetFesGetOfferedCardPieceScRsp = 8307;
    CmdPlanetFesExtType_PlanetFesHandleCardPieceApplyCsReq = 8310;
    CmdPlanetFesExtType_PlanetFesGetOfferedCardPieceCsReq = 8311;
    CmdPlanetFesExtType_PlanetFesChangeCardPieceApplyPermissionScRsp = 8312;
    CmdPlanetFesExtType_PlanetFesGetFriendCardPieceScRsp = 8314;
    CmdPlanetFesExtType_PlanetFesGetFriendCardPieceCsReq = 8334;
    CmdPlanetFesExtType_PlanetFesEnterNextBusinessDayCsReq = 8304;
    CmdPlanetFesExtType_PlanetFesGiveCardPieceScRsp = 8302;
    CmdPlanetFesExtType_PlanetFesApplyCardPieceCsReq = 8322;
    CmdPlanetFesExtType_PlanetFesLargeBonusInteractCsReq = 8291;
    CmdPlanetFesExtType_PlanetFesGetExtraCardPieceInfoScRsp = 8319;
}

message EPPIBFOLFKN {
    repeated uint32 MLPNIPENEBG = 2;
    uint32 uid = 11;
    repeated FMKMEFMOJGJ EOMINOCGLJF = 1;
    int64 OIKNNPOKKME = 5;
    repeated DFEPHMALKDK FDHMLGFKDIP = 12;
    repeated GMODJEECPPJ GMLEOJCLCFB = 10;
    uint32 HAAHAGAPDKC = 8;
    uint32 MLGAODMIHJH = 9;
}

message JJIBNOEGFLK {
}

message PlanetFesApplyCardPieceCsReq {
    uint32 teleport_id = 15;
    repeated uint32 OEEGPNOCFLP = 10;
}

message PlanetFesApplyCardPieceScRsp {
    uint32 retcode = 6;
    repeated uint32 OEEGPNOCFLP = 7;
    uint32 teleport_id = 8;
    uint32 BLGLDJHOMNO = 2;
    bool GOPCDFEIOEA = 3;
    int64 GLDGCHLDMJE = 4;
}

message PlanetFesChangeCardPieceApplyPermissionCsReq {
    uint32 HAAHAGAPDKC = 7;
}

message PlanetFesChangeCardPieceApplyPermissionScRsp {
    uint32 HAAHAGAPDKC = 1;
    uint32 retcode = 5;
}

message PlanetFesGetExtraCardPieceInfoCsReq {
}

message PlanetFesGetExtraCardPieceInfoScRsp {
    uint32 retcode = 9;
    EPPIBFOLFKN GIPNMPKNIFG = 3;
}

message PlanetFesGetFriendCardPieceCsReq {
}

message PlanetFesGetFriendCardPieceScRsp {
    uint32 retcode = 9;
    repeated EPPIBFOLFKN PEBGJJCNBMM = 3;
}

message PlanetFesGetOfferedCardPieceCsReq {
    uint64 CBMBOBNCKMO = 3;
    bool FOGGEJIIJCM = 8;
}

message PlanetFesGetOfferedCardPieceScRsp {
    repeated IEDPDDJAAIH CBPKFDJMGBH = 11;
    bool FOGGEJIIJCM = 12;
    uint32 retcode = 7;
    uint64 CBMBOBNCKMO = 13;
    int64 MAFLGLLOKBB = 2;
    repeated FMKMEFMOJGJ EOMINOCGLJF = 1;
}

message PlanetFesGiveCardPieceCsReq {
    uint32 teleport_id = 15;
    repeated uint32 JAKKDGHLJPH = 7;
}

message PlanetFesGiveCardPieceScRsp {
    uint64 CBMBOBNCKMO = 1;
    int64 JEAGHJHMCEN = 12;
    uint32 retcode = 4;
    repeated uint32 JAKKDGHLJPH = 13;
    uint32 teleport_id = 8;
}

message PlanetFesHandleCardPieceApplyCsReq {
    bool IKOBGOCEHFG = 13;
    uint32 BLGLDJHOMNO = 7;
    uint32 APIFFHBCDKK = 1;
    repeated uint32 JAKKDGHLJPH = 2;
}

message PlanetFesHandleCardPieceApplyScRsp {
    bool IKOBGOCEHFG = 15;
    uint32 retcode = 1;
    int64 JEAGHJHMCEN = 10;
    repeated uint32 JAKKDGHLJPH = 4;
    uint32 BLGLDJHOMNO = 3;
}

message PlanetFesLargeBonusInteractCsReq {
    uint32 DNBKKDBFFAJ = 14;
    uint32 MMKABABENKE = 11;
    uint32 IABOGPKEAGF = 6;
}

message PlanetFesLargeBonusInteractScRsp {
    uint32 DNBKKDBFFAJ = 5;
    OJHHACMHFKA GLOAGDBEKDP = 13;
    NCFKHDIKCNI CGKNMGLFKBN = 2;
    uint32 retcode = 9;
}
