syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BatchGetQuestDataScRsp {
    repeated Quest quest_list = 13;
    uint32 retcode = 8;
}

enum CmdQuestType {
    CmdQuestType_None = 0;
    CmdQuestType_TakeQuestRewardScRsp = 939;
    CmdQuestType_TakeQuestRewardCsReq = 979;
    CmdQuestType_FinishQuestCsReq = 999;
    CmdQuestType_QuestRecordScNotify = 973;
    CmdQuestType_TakeQuestOptionalRewardScRsp = 980;
    CmdQuestType_FinishQuestScRsp = 972;
    CmdQuestType_GetQuestDataScRsp = 982;
    CmdQuestType_GetQuestRecordCsReq = 998;
    CmdQuestType_BatchGetQuestDataCsReq = 904;
    CmdQuestType_GetQuestDataCsReq = 934;
    CmdQuestType_TakeQuestOptionalRewardCsReq = 965;
    CmdQuestType_BatchGetQuestDataScRsp = 962;
    CmdQuestType_GetQuestRecordScRsp = 926;
}

message ECLGDFGGOFH {
    uint32 progress = 15;
    uint32 MNLAMKJIAOC = 3;
}

message FinishQuestCsReq {
    uint32 group_id = 11;
    uint32 prop_id = 6;
    uint32 quest_id = 15;
}

message FinishQuestScRsp {
    uint32 retcode = 2;
}

message GetQuestDataCsReq {
}

message GetQuestDataScRsp {
    uint32 retcode = 9;
    repeated Quest quest_list = 8;
}

message GetQuestRecordCsReq {
}

message GetQuestRecordScRsp {
    uint32 retcode = 13;
    repeated ECLGDFGGOFH AOOFGCNFBPL = 12;
}

message QuestRecordScNotify {
    ECLGDFGGOFH HLMPJLDBPJP = 15;
}

message TakeQuestOptionalRewardCsReq {
    uint32 optional_reward_id = 14;
    uint32 quest_id = 3;
}

message TakeQuestOptionalRewardScRsp {
    uint32 retcode = 6;
    uint32 quest_id = 9;
    ItemList reward = 12;
}

message TakeQuestRewardCsReq {
    repeated uint32 succ_quest_id_list = 7;
}

message TakeQuestRewardScRsp {
    repeated uint32 succ_quest_id_list = 14;
    repeated uint32 quest_id_list = 7;
    ItemList reward = 9;
    uint32 retcode = 4;
}
