syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message CABBOOKAODO {
    uint32 avatar_id = 13;
    ONFLANPGHHL AEONNKANGCE = 3;
    repeated uint32 relic_ids = 6;
}

enum CmdRelicSmartWearType {
    CmdRelicSmartWearType_None = 0;
    CmdRelicSmartWearType_RelicSmartWearUpdatePlanScRsp = 8262;
    CmdRelicSmartWearType_RelicSmartWearUpdatePlanCsReq = 8259;
    CmdRelicSmartWearType_RelicSmartWearDeletePlanScRsp = 8264;
    CmdRelicSmartWearType_RelicSmartWearGetPinRelicScRsp = 8266;
    CmdRelicSmartWearType_RelicSmartWearAddPlanScRsp = 8263;
    CmdRelicSmartWearType_RelicSmartWearDeletePinRelicCsReq = 8267;
    CmdRelicSmartWearType_RelicSmartWearDeletePinRelicScRsp = 8258;
    CmdRelicSmartWearType_RelicSmartWearAddPlanCsReq = 8270;
    CmdRelicSmartWearType_RelicSmartWearUpdatePinRelicScRsp = 8251;
    CmdRelicSmartWearType_RelicSmartWearUpdatePinRelicCsReq = 8252;
    CmdRelicSmartWearType_RelicSmartWearDeletePlanCsReq = 8261;
    CmdRelicSmartWearType_RelicSmartWearUpdatePinRelicScNotify = 8269;
    CmdRelicSmartWearType_RelicSmartWearGetPlanCsReq = 8255;
    CmdRelicSmartWearType_RelicSmartWearGetPlanScRsp = 8265;
    CmdRelicSmartWearType_RelicSmartWearGetPinRelicCsReq = 8268;
}

enum KCKJILIMNFF {
    KCKJILIMNFF_NLCDGIPGFDJ = 0;
    KCKJILIMNFF_CFPGFAMANFD = 1;
    KCKJILIMNFF_HEHPPOFHLMI = 2;
    KCKJILIMNFF_EBDIOJPDJIH = 3;
}

message ONFLANPGHHL {
    repeated uint32 outside_relic_list = 3;
    repeated uint32 inside_relic_list = 4;
    KCKJILIMNFF ALAEIBDIGHM = 7;
}

message RelicSmartWearAddPlanCsReq {
    RelicSmartWearPlan relic_plan = 7;
}

message RelicSmartWearAddPlanScRsp {
    uint32 retcode = 9;
    RelicSmartWearPlan relic_plan = 12;
}

message RelicSmartWearDeletePinRelicCsReq {
    bool BEAJGCMPOED = 12;
    uint32 avatar_id = 4;
    repeated ONFLANPGHHL AIFAMIFGMCH = 2;
}

message RelicSmartWearDeletePinRelicScRsp {
    uint32 avatar_id = 13;
    repeated ONFLANPGHHL AIFAMIFGMCH = 14;
    uint32 retcode = 3;
}

message RelicSmartWearDeletePlanCsReq {
    uint32 unique_id = 8;
}

message RelicSmartWearDeletePlanScRsp {
    uint32 retcode = 2;
    uint32 unique_id = 9;
}

message RelicSmartWearGetPinRelicCsReq {
    uint32 avatar_id = 14;
}

message RelicSmartWearGetPinRelicScRsp {
    repeated CABBOOKAODO OJNCAOKPKIB = 4;
    uint32 avatar_id = 10;
    uint32 retcode = 7;
}

message RelicSmartWearGetPlanCsReq {
    uint32 avatar_id = 10;
}

message RelicSmartWearGetPlanScRsp {
    uint32 retcode = 11;
    uint32 avatar_id = 3;
    repeated RelicSmartWearPlan relic_plan_list = 8;
}

message RelicSmartWearPlan {
    repeated uint32 outside_relic_list = 10;
    uint32 unique_id = 15;
    uint32 avatar_id = 12;
    repeated uint32 inside_relic_list = 11;
}

message RelicSmartWearUpdatePinRelicCsReq {
    CABBOOKAODO DNNKBPBFPBK = 14;
}

message RelicSmartWearUpdatePinRelicScNotify {
    repeated CABBOOKAODO ANCHGOGNLFP = 13;
    uint32 relic_unique_id = 5;
    repeated CABBOOKAODO PLNCNCNIPKN = 6;
}

message RelicSmartWearUpdatePinRelicScRsp {
    uint32 retcode = 4;
    CABBOOKAODO DNNKBPBFPBK = 9;
}

message RelicSmartWearUpdatePlanCsReq {
    RelicSmartWearPlan relic_plan = 3;
}

message RelicSmartWearUpdatePlanScRsp {
    uint32 retcode = 8;
    RelicSmartWearPlan relic_plan = 14;
}
