syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BMMHJIFCGNO {
    uint32 KAJCFPKEGBP = 2;
    uint32 MIPKOFFGPFA = 7;
}

message BPFDFOJOEMI {
    uint32 LBDLAACOCCN = 2;
    uint32 percent = 9;
}

message BigDataAvatarRelicRecommend {
    repeated BPFDFOJOEMI rope_main_property_list = 14;
    repeated JBGPLPCCDBJ inner_set_list = 1;
    repeated BPFDFOJOEMI foot_main_property_list = 10;
    uint32 avatar_id = 15;
    repeated JBGPLPCCDBJ outer_set_list = 7;
    repeated BPFDFOJOEMI sphere_main_property_list = 2;
    repeated BPFDFOJOEMI body_main_property_list = 3;
}

message BigDataRecommendAvatarRelic {
    repeated BigDataAvatarRelicRecommend recomended_relic_info_list = 15;
}

message BigDataRecommendRelicAvatar {
    repeated RecomendedAvatarInfo recommended_avatar_info_list = 3;
}

enum BigDataRecommendType {
    BIG_DATA_RECOMMEND_TYPE_NONE = 0;
    BIG_DATA_RECOMMEND_TYPE_EQUIPMENT = 1;
    BIG_DATA_RECOMMEND_TYPE_RELIC_SUIT = 2;
    BIG_DATA_RECOMMEND_TYPE_RELIC_AVATAR = 3;
    BIG_DATA_RECOMMEND_TYPE_AVATAR_RELIC = 4;
    BIG_DATA_RECOMMEND_TYPE_LOCAL_LEGEND = 5;
    BIG_DATA_RECOMMEND_TYPE_CHALLENGE_PEAK_MOB = 6;
    BIG_DATA_RECOMMEND_TYPE_CHALLENGE_PEAK_BOSS = 7;
    BIG_DATA_RECOMMEND_TYPE_CHALLENGE = 8;
    BIG_DATA_RECOMMEND_TYPE_HMFFBIANKBF = 9;
    BIG_DATA_RECOMMEND_TYPE_IGDNEOELFKC = 10;
}

message CIOAOEGEIKH {
    repeated PEGJIHHIFOP DNIGKDKIPPJ = 1;
}

enum CmdRecommendType {
    CmdRecommendType_None = 0;
    CmdRecommendType_GetBigDataRecommendCsReq = 2432;
    CmdRecommendType_GetBigDataAllRecommendScRsp = 2438;
    CmdRecommendType_GetBigDataAllRecommendCsReq = 2420;
    CmdRecommendType_GetBigDataRecommendScRsp = 2437;
}

message DAMNNJKJOMM {
    repeated uint32 first_lineup = 1;
    repeated uint32 second_lineup = 2;
    uint32 DHMEBODOJMI = 3;
    uint32 DLCJLOIMKOJ = 4;
}

message EquipmentRecommend {
    repeated BMMHJIFCGNO equipment_list = 14;
}

message GFDJLBJPNMC {
    repeated JGPMBLAJJJG GBMBAHHDONN = 1;
}

message GHAJJBBEHBE {
    uint32 OAOPDHLDFIP = 15;
    uint32 BBGHAFGMMNM = 5;
    uint32 LMHDFOFNFII = 14;
}

message GNBBDMBNNDJ {
    repeated JOLHIMGJGBO lineup_list = 1;
}

message GetBigDataAllRecommendCsReq {
    BigDataRecommendType big_data_recommend_type = 7;
}

message GetBigDataAllRecommendScRsp {
    BigDataRecommendType big_data_recommend_type = 5;
    uint32 retcode = 3;
    BigDataRecommendRelicAvatar relic_avatar = 13;
    BigDataRecommendAvatarRelic avatar_relic = 12;
    GNBBDMBNNDJ KHCMLINMGEN = 7;
}

message GetBigDataRecommendCsReq {
    uint32 equip_avatar = 6;
    BigDataRecommendType big_data_recommend_type = 13;
}

message GetBigDataRecommendScRsp {
    uint32 equip_avatar = 3;
    bool has_recommand = 8;
    BigDataRecommendType big_data_recommend_type = 10;
    uint32 retcode = 13;
    EquipmentRecommend equipment_recommend = 5;
    RelicRecommend relic_recommend = 1;
    GNBBDMBNNDJ KHCMLINMGEN = 7;
}

message JBGPLPCCDBJ {
    uint32 percent = 5;
    uint32 NMFGIBMHNKI = 6;
    uint32 GBJPBAHGBPO = 3;
}

message JGPMBLAJJJG {
    repeated uint32 AEJPCFLOPAL = 1;
    uint32 buff_id = 2;
}

message JOLHIMGJGBO {
    OHLNNOMJPNH FJONKDKACAB = 1;
    CIOAOEGEIKH DKBBMJDNHNG = 2;
    JPKIDILKOAK BDNBIHLJNCK = 3;
    DAMNNJKJOMM HCAAHIGINOM = 4;
    KOBGMGHMCLF OEAKBCLIHGH = 5;
    GFDJLBJPNMC MIEJNLBBIDB = 6;
}

message JPKIDILKOAK {
    repeated uint32 AEJPCFLOPAL = 1;
    uint32 buff_id = 2;
}

message KOBGMGHMCLF {
    uint32 avatar_id = 1;
    repeated MCOFKOEJGGL BJKBFDJGFOG = 2;
    uint32 slot = 3;
    uint32 IDBDBICPBBG = 4;
}

message MCOFKOEJGGL {
    uint32 GPIOJJBAIJB = 1;
    repeated uint32 ADHEJNDAPIH = 2;
}

message OHLNNOMJPNH {
    repeated uint32 AEJPCFLOPAL = 1;
}

message PEGJIHHIFOP {
    repeated uint32 AEJPCFLOPAL = 1;
}

message RecomendedAvatarInfo {
    uint32 recommend_avatar_id = 5;
    repeated uint32 avatar_id_list = 11;
    uint32 relic_set_id = 10;
}

message RelicRecommend {
    repeated GHAJJBBEHBE GMCNPKAJMHC = 3;
}
