syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum BDFGBPHEPDI {
    BDFGBPHEPDI_PDKLDMNAJBO = 0;
    BDFGBPHEPDI_KCCEHPABIKB = 1;
    BDFGBPHEPDI_IEGNMOODDAK = 2;
}

message BEBNHPCBMPF {
    JBOAAPIDOIC NOAJIGHLIIC = 3;
    uint32 avatar_id = 11;
}

enum CmdRelicBoxType {
    CmdRelicBoxType_None = 0;
    CmdRelicBoxType_SetRelicBoxCustomScRsp = 8963;
    CmdRelicBoxType_GetRelicBoxDataScRsp = 8965;
    CmdRelicBoxType_OpenRelicBoxCsReq = 8957;
    CmdRelicBoxType_ReportRelicBoxActionCsReq = 8954;
    CmdRelicBoxType_OpenRelicBoxScRsp = 8960;
    CmdRelicBoxType_ConfirmRelicBoxCsReq = 8968;
    CmdRelicBoxType_SetRelicBoxTargetScRsp = 8962;
    CmdRelicBoxType_SetRelicBoxTargetCsReq = 8959;
    CmdRelicBoxType_ReportRelicBoxActionScRsp = 8953;
    CmdRelicBoxType_GetRelicBoxDataCsReq = 8955;
    CmdRelicBoxType_RelicBoxRegularScNotify = 8952;
    CmdRelicBoxType_SetRelicBoxCustomCsReq = 8970;
    CmdRelicBoxType_ConfirmRelicBoxScRsp = 8966;
}

message ConfirmRelicBoxCsReq {
    bool BBNIFADMHHO = 8;
}

message ConfirmRelicBoxScRsp {
    repeated uint32 OAJFAFIDKPI = 13;
    uint32 HMBNJLNBLIF = 10;
    bool BBNIFADMHHO = 9;
    uint32 retcode = 14;
}

message DPJCBHKGFOK {
    repeated Relic relics = 15;
}

message GetRelicBoxDataCsReq {
}

message GetRelicBoxDataScRsp {
    DPJCBHKGFOK AHNPPGMFOKN = 6;
    uint32 MFLMHFLMCPO = 9;
    uint32 retcode = 2;
    repeated BEBNHPCBMPF EBDIOJPDJIH = 14;
    repeated uint32 OAJFAFIDKPI = 11;
    BDFGBPHEPDI state = 15;
    HGABLJFOKDG target = 1;
    PNGBDDIBCDD NJFEFOFPKPF = 8;
}

message HGABLJFOKDG {
    uint32 avatar_id = 6;
    JFIIIHFBLPA HDHKAHJBFKD = 11;
    JBOAAPIDOIC NOAJIGHLIIC = 2;
}

message JBOAAPIDOIC {
    uint32 IPILHKHCLJH = 12;
    uint32 FLFOCHJFLOE = 15;
}

enum JFIIIHFBLPA {
    JFIIIHFBLPA_NEODNIFGDJC = 0;
    JFIIIHFBLPA_BPKKHFFJGGI = 1;
}

message OpenRelicBoxCsReq {
    HGABLJFOKDG target = 12;
}

message OpenRelicBoxScRsp {
    uint32 retcode = 3;
    PNGBDDIBCDD LCMADDIMION = 9;
    uint32 GNLAAIDFOJF = 8;
}

message PNGBDDIBCDD {
    uint32 level = 10;
    uint32 exp = 9;
    uint32 type = 11;
    uint32 tid = 1;
    repeated RelicAffix sub_affix_list = 5;
    uint32 main_affix_id = 2;
}

message RelicBoxRegularScNotify {
    DPJCBHKGFOK AHNPPGMFOKN = 14;
}

message ReportRelicBoxActionCsReq {
    uint32 KCGLKFKHPIC = 2;
}

message ReportRelicBoxActionScRsp {
    uint32 retcode = 13;
    BDFGBPHEPDI state = 14;
}

message SetRelicBoxCustomCsReq {
    repeated BEBNHPCBMPF JKKFJHKHFPL = 15;
    BEBNHPCBMPF EBDIOJPDJIH = 10;
}

message SetRelicBoxCustomScRsp {
    uint32 retcode = 3;
}

message SetRelicBoxTargetCsReq {
    HGABLJFOKDG target = 13;
}

message SetRelicBoxTargetScRsp {
    uint32 retcode = 12;
    HGABLJFOKDG target = 15;
}
