syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ACMKPNMKOKH {
    FKBOOENADFM detail = 1;
    uint32 queue_position = 12;
}

message ADIHAECHADG {
    uint32 KLNHFGLBBIM = 11;
}

message AGKONMPOJKP {
    repeated ELGOBKCNOHH MAJGMMCOCIG = 12;
}

message AHLALEEJOEG {
    repeated MGJDNGHDIKG LFCGPOKMJLC = 14;
}

message ALJJNBKGEOC {
    repeated uint32 EHKPMGBCPCG = 5;
}

message AOFKCKOIFCM {
    DNLKMHLAPHC LANFFLCLGAH = 8;
}

message BAHBCFDAIKG {
    repeated BBHHENEONHO HIILDALHIMD = 15;
}

message BAJDLLEFGHB {
    int32 LIAGGDDILGO = 12;
    uint32 JFIGNBBLCIM = 3;
    ItemCostData cost_data = 6;
}

message BBHHENEONHO {
    uint32 KGOPHALLLLI = 13;
    uint32 CFKKKPNKHEL = 15;
    bool IFIGFODOPBB = 6;
    ItemCostData cost_data = 8;
    ItemCostData IOJFGBDPPHI = 4;
}

message BCOEGNBGJFC {
    BAJDLLEFGHB NLJPONKBMFI = 9;
    BJBIFIMJDOL BBNEGKCNMBA = 4;
    BLICCEHIOLH PKPIEFOBHKH = 12;
    OMNMBANDCBA FKMADCAFJMC = 10;
    DCEPBLJKNNE PHLEDABHDML = 15;
    FBOFEOCHDMN DDLADFJMEEC = 2;
    BAHBCFDAIKG OJEANDPABHC = 8;
    GNFDPONFLJD CLLEJEPNBDH = 3;
    OJPMMKIJIFH DNHKNALBAMG = 5;
    EHELNMGMENO LBBCJHOPEPH = 7;
    LPODFEEGDOB KDFGAKDCMIK = 6;
    PGINHECHMPM HMCJFBBJNBF = 13;
    PGINHECHMPM KMFJJFOELCE = 14;
    PGINHECHMPM JDLALEHLNCJ = 1;
    PGINHECHMPM KLPJMFFONEE = 1206;
    bool KGOCMGGMAIC = 11;
}

message BIHACLHMAKO {
    uint32 AIAFEKGBFIF = 15;
}

message BJBIFIMJDOL {
    int32 LIAGGDDILGO = 4;
    ItemCostData cost_data = 1;
    uint32 JFIGNBBLCIM = 8;
}

message BLICCEHIOLH {
    uint32 max_num = 1;
    map<uint32, uint32> LBEIHAOKHAD = 4;
    uint32 cur_num = 14;
}

message BPHIKPCNBHM {
    uint32 maze_buff_id = 10;
}

message BPOKOPCGMAJ {
    int32 change_value = 2;
}

message BuyRogueShopBuffScRsp {
    uint32 retcode = 4;
    DAENHKENJHK HABJHGPFGEB = 6;
}

message BuyRogueShopFormulaScRsp {
    uint32 retcode = 1;
    GBHAHDBDOIE EAPCJKNGGCA = 13;
}

message BuyRogueShopMiracleCsReq {
    uint32 ABELECPLDAA = 6;
    uint32 interacted_prop_entity_id = 7;
}

message BuyRogueShopMiracleScRsp {
    AGKONMPOJKP DNPCCFFFBHN = 4;
    uint32 retcode = 3;
}

message CCKJAEDDDCL {
    KPIHDPGDMKB BMGOLFNGHGH = 2;
    AHLALEEJOEG BBEKBJPHEJK = 15;
    CDDEIPOBBCN MECOEFEJANE = 9;
    GANFMBPEJPF ABPOOCOOKCF = 6;
}

message CDDEIPOBBCN {
    repeated uint32 BHAGLNBNGBP = 7;
}

message CEDCDDPHBOG {
}

message CFJNAPDIMKM {
    repeated OMJGKNJKHCH EMLLEPOADED = 7;
}

message CIGDBCKOFBN {
    bool ALAJJMKOMML = 9;
    uint32 NPNMLPNBHDP = 10;
}

message CJAFLDKHDAF {
    HMAAICNBKCI value = 9;
}

message CKEOMFNPKPO {
    KOFMGCNIMIN miracle = 11;
}

message COKKOEBBEGM {
    uint32 HDGPBCJPNBE = 6;
}

enum CmdRogueCommonType {
    CmdRogueCommonType_None = 0;
    CmdRogueCommonType_GetRogueCommonDialogueDataCsReq = 5633;
    CmdRogueCommonType_PrepareRogueAdventureRoomCsReq = 5682;
    CmdRogueCommonType_SyncRogueHandbookDataUpdateScNotify = 5640;
    CmdRogueCommonType_RogueGetGambleInfoScRsp = 5700;
    CmdRogueCommonType_PrepareRogueAdventureRoomScRsp = 5679;
    CmdRogueCommonType_SyncRogueAdventureRoomInfoScNotify = 5634;
    CmdRogueCommonType_BuyRogueShopFormulaScRsp = 5617;
    CmdRogueCommonType_RogueWorkbenchHandleFuncScRsp = 5654;
    CmdRogueCommonType_RogueDoGambleScRsp = 5612;
    CmdRogueCommonType_FinishRogueCommonDialogueCsReq = 5685;
    CmdRogueCommonType_GetEnhanceCommonRogueBuffInfoScRsp = 5681;
    CmdRogueCommonType_RogueWorkbenchGetInfoScRsp = 5694;
    CmdRogueCommonType_RogueNpcDisappearScRsp = 5680;
    CmdRogueCommonType_RogueShopBeginBattleScRsp = 5603;
    CmdRogueCommonType_UpdateRogueAdventureRoomScoreCsReq = 5689;
    CmdRogueCommonType_SetRogueExhibitionCsReq = 5613;
    CmdRogueCommonType_UpdateRogueAdventureRoomScoreScRsp = 5670;
    CmdRogueCommonType_SetRogueExhibitionScRsp = 5636;
    CmdRogueCommonType_SyncRogueCommonPendingActionScNotify = 5660;
    CmdRogueCommonType_RogueNpcDisappearCsReq = 5665;
    CmdRogueCommonType_GetRogueShopMiracleInfoCsReq = 5639;
    CmdRogueCommonType_TakeRogueMiracleHandbookRewardScRsp = 5655;
    CmdRogueCommonType_HandleRogueCommonPendingActionCsReq = 5635;
    CmdRogueCommonType_GetRogueCommonDialogueDataScRsp = 5674;
    CmdRogueCommonType_RogueWorkbenchGetInfoCsReq = 5696;
    CmdRogueCommonType_SyncRogueCommonDialogueDataScNotify = 5616;
    CmdRogueCommonType_EnhanceCommonRogueBuffScRsp = 5638;
    CmdRogueCommonType_SyncRogueCommonVirtualItemInfoScNotify = 5611;
    CmdRogueCommonType_RogueWorkbenchHandleFuncCsReq = 5627;
    CmdRogueCommonType_StopRogueAdventureRoomScRsp = 5646;
    CmdRogueCommonType_EnhanceCommonRogueBuffCsReq = 5641;
    CmdRogueCommonType_SelectRogueCommonDialogueOptionCsReq = 5663;
    CmdRogueCommonType_StopRogueAdventureRoomCsReq = 5657;
    CmdRogueCommonType_HandleRogueCommonPendingActionScRsp = 5678;
    CmdRogueCommonType_BuyRogueShopBuffCsReq = 5699;
    CmdRogueCommonType_SyncRogueCommonDialogueOptionFinishScNotify = 5692;
    CmdRogueCommonType_BuyRogueShopMiracleScRsp = 5673;
    CmdRogueCommonType_GetRogueShopBuffInfoScRsp = 5698;
    CmdRogueCommonType_FinishRogueCommonDialogueScRsp = 5625;
    CmdRogueCommonType_TakeRogueEventHandbookRewardCsReq = 5675;
    CmdRogueCommonType_BuyRogueShopFormulaCsReq = 5629;
    CmdRogueCommonType_GetEnhanceCommonRogueBuffInfoCsReq = 5664;
    CmdRogueCommonType_SyncRogueCommonActionResultScNotify = 5630;
    CmdRogueCommonType_GetRogueAdventureRoomInfoCsReq = 5671;
    CmdRogueCommonType_BuyRogueShopMiracleCsReq = 5626;
    CmdRogueCommonType_RogueDoGambleCsReq = 5693;
    CmdRogueCommonType_SetRogueCollectionCsReq = 5659;
    CmdRogueCommonType_CommonRogueUpdateScNotify = 5619;
    CmdRogueCommonType_SelectRogueCommonDialogueOptionScRsp = 5628;
    CmdRogueCommonType_GetRogueHandbookDataScRsp = 5643;
    CmdRogueCommonType_RogueShopBeginBattleCsReq = 5606;
    CmdRogueCommonType_GetRogueShopMiracleInfoScRsp = 5656;
    CmdRogueCommonType_GetRogueHandbookDataCsReq = 5621;
    CmdRogueCommonType_GetRogueAdventureRoomInfoScRsp = 5604;
    CmdRogueCommonType_SetRogueCollectionScRsp = 5676;
    CmdRogueCommonType_CommonRogueQueryCsReq = 5620;
    CmdRogueCommonType_CommonRogueQueryScRsp = 5668;
    CmdRogueCommonType_GetRogueShopFormulaInfoCsReq = 5610;
    CmdRogueCommonType_TakeRogueMiracleHandbookRewardCsReq = 5683;
    CmdRogueCommonType_GetRogueShopBuffInfoCsReq = 5691;
    CmdRogueCommonType_BuyRogueShopBuffScRsp = 5672;
    CmdRogueCommonType_GetRogueShopFormulaInfoScRsp = 5661;
    CmdRogueCommonType_RogueGetGambleInfoCsReq = 5653;
    CmdRogueCommonType_TakeRogueEventHandbookRewardScRsp = 5602;
}

message CommonRogueQueryScRsp {
    repeated CCKJAEDDDCL LFLCDNGALME = 10;
    uint32 retcode = 8;
    uint32 GLGHEOPPCMH = 15;
}

message CommonRogueUpdateScNotify {
    KPIHDPGDMKB BMGOLFNGHGH = 4;
    AHLALEEJOEG BBEKBJPHEJK = 8;
    CDDEIPOBBCN MECOEFEJANE = 11;
}

message DAENHKENJHK {
    repeated KJEOBMBMNIN buff_list = 14;
}

message DCEPBLJKNNE {
    ItemCostData cost_data = 7;
    int32 LIAGGDDILGO = 3;
    uint32 JFIGNBBLCIM = 13;
}

message DGKLPPLJBNB {
    uint32 EFCAJENMLKA = 6;
    LBPLJCHEJOK status = 8;
    uint32 CNFGOHFPLGO = 4;
}

enum DICEONDKEFF {
    DICEONDKEFF_NLCDGIPGFDJ = 0;
    DICEONDKEFF_ICFONCMFNLG = 1;
    DICEONDKEFF_KDDIPFACJAJ = 2;
}

message DIKBPKAKENO {
    NKLAEHJPIMN status = 10;
    uint32 EFCAJENMLKA = 15;
}

message DOEJLDNIDED {
    uint32 DPGKMIIBPDB = 15;
}

message EDDEOKAIJAB {
    uint32 AMOABLICEDP = 7;
}

message EGMPACONNFP {
    uint32 GNCFHIKODKE = 7;
    uint32 NPBLEKPLPFA = 1;
    uint32 unique_id = 10;
}

message EHELNMGMENO {
    repeated NEFBECKCJIH MALDOMHPILM = 2;
}

message EJBEEKFJAHM {
    uint32 CFKKKPNKHEL = 13;
}

message ELGOBKCNOHH {
    ItemCostData KINNMAGDDJJ = 6;
    bool BELPGDAGFIH = 11;
    uint32 LJCEOGPOGBE = 2;
    ItemCostData cost_data = 10;
    bool GCIHGKCJOGB = 9;
}

message ELJDPDFMLPM {
    KPOFAPDKBJA ICKMKPJACAB = 4;
}

message EOIFLHMPBIF {
    uint64 GAHFPGCPAJA = 14;
    MMFOGJPOHGJ owner_type = 2;
}

message FBGIINJFCCD {
    LEJFIEPMMGG DKEENIMPLKD = 9;
}

message FBLONDAEJMC {
    PGMIABHEJNB CICDCBECKHP = 12;
}

message FBOFEOCHDMN {
    repeated LNPGBGDPIIK GJGFCCKEMFD = 14;
}

message FHAAGBGAHLO {
    uint32 CJGIOODIADG = 10;
}

message FKBOOENADFM {
    LPLHNOPDKHI PDFDENDALFD = 10;
    IDMHNMOLHKN HIMDHCBOFEH = 15;
    EOIFLHMPBIF NGEFAPOENBD = 6;
    GGCFMPIBGHA KBAMEDDAIIN = 12;
    KNOLJDOPBDG LIAODKPFBHA = 14;
}

message FKOGDINOBDF {
    GGGBAIAPDLO PCHGEGFBKLF = 14;
}

message FOINGKNPBLJ {
    uint32 KAHMGPGPOII = 13;
}

message GANFMBPEJPF {
    repeated NPAJHGDEIDJ DPIKOCFILGP = 7;
    repeated JMJEIBGACMD CEPDOBEIEFG = 1;
    repeated DGKLPPLJBNB PAKECMNPEJJ = 8;
    repeated DIKBPKAKENO JFHKJOGEOND = 10;
}

message GBHAHDBDOIE {
    repeated OMLMOJIGLEE KJFEFFGPNFF = 1;
}

message GBKILNHHGLB {
    repeated uint32 GMMAFIONFNF = 8;
}

message GGCFMPIBGHA {
    repeated AKMCODLAEKI GFKAFIFMHNF = 11;
}

message GNFDPONFLJD {
    ItemCostData cost_data = 8;
    uint32 JFIGNBBLCIM = 2;
    int32 LIAGGDDILGO = 13;
}

message GNGIHJIJGMD {
    DNLKMHLAPHC LANFFLCLGAH = 6;
}

message GNLBCCHFILK {
    BDJLHJDPEEK KDFKDNLNDHN = 1;
    bool BJDEBHMKJBC = 10;
}

message GetRogueCommonDialogueDataCsReq {
}

message GetRogueCommonDialogueDataScRsp {
    uint32 retcode = 6;
    repeated HFEOGNAMHCG dialogue_list = 14;
}

message GetRogueHandbookDataCsReq {
}

message GetRogueHandbookDataScRsp {
    uint32 retcode = 14;
    NHGJEIHKKHB HAMKPLCBEBG = 11;
}

message GetRogueShopBuffInfoScRsp {
    DAENHKENJHK HABJHGPFGEB = 12;
    int32 APMGPHFHENP = 10;
    int32 KCBOHFNFJEA = 2;
    uint32 retcode = 4;
    ItemCostData JOMDKGINNEK = 11;
}

message GetRogueShopFormulaInfoScRsp {
    GBHAHDBDOIE EAPCJKNGGCA = 13;
    uint32 retcode = 3;
    int32 APMGPHFHENP = 8;
    ItemCostData JOMDKGINNEK = 15;
    int32 KCBOHFNFJEA = 14;
}

message GetRogueShopMiracleInfoCsReq {
    uint32 interacted_prop_entity_id = 7;
    bool LJBCDJNNBJH = 14;
}

message GetRogueShopMiracleInfoScRsp {
    AGKONMPOJKP DNPCCFFFBHN = 11;
    ItemCostData JOMDKGINNEK = 6;
    uint32 retcode = 10;
}

message HCNEFGJCCMB {
    uint32 PEKGIDFPBNJ = 15;
}

message HEOBLDJAOPE {
    uint32 MJBKNMJHOGP = 13;
    uint32 OEANPIHCHHF = 8;
}

message HFEOGNAMHCG {
    uint32 AIAFEKGBFIF = 13;
    LEHBIBDGEHG owner = 1;
    repeated KDODFHMDAJI KFNMIEMBJGD = 15;
}

message HIMJNABCJMM {
    repeated EGMPACONNFP JKFNAKBGIBF = 11;
}

message HPIPKICGABB {
    AMKALFJHFJP AMIBPAGBMFP = 5;
}

message HandleRogueCommonPendingActionScRsp {
    uint32 retcode = 8;
    uint32 BFNEPPCNOOI = 3;
    uint32 queue_position = 4;
    FKOGDINOBDF JFHKDEIDMOG = 6;
    HPIPKICGABB COBNPFDHMEA = 2;
    OKFPPPBNJNH LDOFNPGNJJC = 12;
    ELJDPDFMLPM PKBOEKFFMKM = 5;
    OBNEOHHDAIP FPJABECNFNA = 14;
    KLEHEHAMKLC HGBKMEHOMHA = 795;
    FBLONDAEJMC FIPEBNNBAMA = 1317;
}

message IDMHNMOLHKN {
    repeated AKMCODLAEKI GFKAFIFMHNF = 10;
    uint64 GAHFPGCPAJA = 4;
    MMFOGJPOHGJ owner_type = 7;
}

message IKHMHNOIGAB {
    uint32 LJCEOGPOGBE = 2;
}

message IOMEMIEAPJO {
    KOFMGCNIMIN miracle = 13;
}

message IPKOBBJPKML {
    uint32 unique_id = 7;
}

message JFGGDMPDKNH {
    uint32 FGKPOBCOCKM = 3;
}

message JGCMGAMHDHM {
    uint32 PGGDEHKKINP = 2;
    uint32 HGKBJMGGPGL = 11;
}

message JJEMDNEIMOJ {
    LEJFIEPMMGG DKEENIMPLKD = 9;
}

message JLHJICBCHMO {
    uint32 BJIBCOHEGIJ = 15;
    KOFMGCNIMIN HLCPFLOPGBM = 5;
}

message JLJNNPIAKGH {
    uint32 round = 6;
    uint32 score_id = 8;
}

message JMJEIBGACMD {
    uint32 CNFGOHFPLGO = 6;
    uint32 ECPDJMMOGCI = 7;
    LBPLJCHEJOK status = 10;
}

message KDODFHMDAJI {
    bool is_selected = 9;
    uint32 arg_id = 4;
    KNMNEJCMHGE param = 15;
    bool is_valid = 1;
    uint32 HAFOKMHCGFM = 3;
    repeated MAEEIBPEOFN LDCJONHGDAN = 12;
}

message KJEOBMBMNIN {
    uint32 buff_id = 9;
    ItemCostData cost_data = 12;
    bool GCIHGKCJOGB = 7;
    bool BELPGDAGFIH = 4;
    ItemCostData KINNMAGDDJJ = 15;
    uint32 JBGENFIKGGF = 11;
}

message KLEHEHAMKLC {
    OHJJMCMJEHL KBEBGLAAEGM = 11;
}

message KNEJEHOOFGI {
    uint32 avatar_id = 7;
    AvatarType avatar_type = 8;
}

message KNMNEJCMHGE {
    int32 MNLINFEODPJ = 4;
    float GMPKBKLGDMA = 11;
}

message KNOLJDOPBDG {
    MMFOGJPOHGJ owner_type = 5;
    repeated AKMCODLAEKI GFKAFIFMHNF = 7;
    uint64 GAHFPGCPAJA = 12;
}

message KNPMLBOBKPI {
    uint32 LNAHJENGELA = 8;
}

message KPIHDPGDMKB {
    uint32 OCAGIAKNGPG = 8;
    uint32 NBBABABPEBE = 4;
    uint32 DGJPGMGPCCE = 1;
}

message LBBCNOOOCNE {
    DNLKMHLAPHC LANFFLCLGAH = 2;
}

enum LBPLJCHEJOK {
    LBPLJCHEJOK_NDDPEJHPLHG = 0;
    LBPLJCHEJOK_BMBGOIDDIJD = 1;
    LBPLJCHEJOK_KJDPEEAPJOO = 2;
}

message LEHBIBDGEHG {
    HEOBLDJAOPE MFAEGBJBJBE = 11;
    FOINGKNPBLJ MNKGPHFJDFM = 6;
    KNPMLBOBKPI DCFILENMPCC = 12;
    OEPAMDEPFLJ BDFKGFLFCFO = 7;
}

message LFBPMGGFCEO {
    repeated uint32 IPACFECEBFF = 14;
}

message LFLMJKLKBIL {
    uint32 PEKGIDFPBNJ = 3;
}

message LHKAOPAPJEK {
    FHEGNOPNICH JNKLNLKHGBB = 5;
    SceneInfo scene = 6;
    LineupInfo lineup = 3;
}

message LHKNCMFEPFK {
    uint32 FDEECOEDJEB = 12;
    KOFMGCNIMIN miracle = 14;
    uint32 EGJIEAAEEBD = 13;
}

message LLBKNIJDALM {
    uint32 GCAHKLNGFCK = 3;
}

message LNKEEAKFEHM {
}

message LNOPJJFKMDL {
    repeated uint32 PDAMBONNOND = 5;
}

message LNPGBGDPIIK {
    ItemCostData IOJFGBDPPHI = 13;
    bool IFIGFODOPBB = 6;
    ItemCostData cost_data = 9;
    OCBPJLLLJGO DDLADFJMEEC = 4;
}

enum LPCEBDCJBOI {
    LPCEBDCJBOI_IHENGPDPCHA = 0;
    LPCEBDCJBOI_HMKEPGCEMON = 1;
    LPCEBDCJBOI_GCMFFANJMHF = 2;
}

message LPLHNOPDKHI {
    repeated AKMCODLAEKI GFKAFIFMHNF = 6;
    uint64 GAHFPGCPAJA = 15;
    MMFOGJPOHGJ owner_type = 12;
}

message LPODFEEGDOB {
    uint32 CLNDMEODHJE = 8;
    uint32 DMGJDGJMCJL = 11;
}

message MAEEIBPEOFN {
    PIACCCGNOOF BACBKGJJOGA = 10;
    BPOKOPCGMAJ CNKCDGOJGJH = 11;
}

message MAOKMPOELCO {
    NHHMEPILLHL source = 15;
    PKHKEEKIODC detail = 12;
    uint32 queue_position = 5;
}

enum MGJDNGHDIKG {
    MGJDNGHDIKG_ANBKDJKHCBI = 0;
    MGJDNGHDIKG_DDJLLLNADIL = 1;
    MGJDNGHDIKG_NLCLCPPDLGM = 2;
    MGJDNGHDIKG_FDACPOINIEO = 3;
    MGJDNGHDIKG_BJDFGOACHGF = 4;
    MGJDNGHDIKG_ECLBIMKAKJC = 5;
}

enum MIGPNAOGHEP {
    MIGPNAOGHEP_DOOODKBGFCO = 0;
    MIGPNAOGHEP_COJLMFJMDKD = 1;
    MIGPNAOGHEP_AOKLIPHLBNN = 2;
}

message MIPGDFDCKLE {
    JFGGDMPDKNH NLJPONKBMFI = 10;
    COKKOEBBEGM BBNEGKCNMBA = 3;
    FHAAGBGAHLO PKPIEFOBHKH = 14;
    LNOPJJFKMDL FKMADCAFJMC = 8;
    MKFCLDMEMGN PHLEDABHDML = 12;
    DOEJLDNIDED DDLADFJMEEC = 9;
    ALJJNBKGEOC OJEANDPABHC = 11;
    LFBPMGGFCEO CLLEJEPNBDH = 15;
    EJBEEKFJAHM DNHKNALBAMG = 13;
    LLBKNIJDALM LBBCJHOPEPH = 2;
    NGOKMAABDJJ KDFGAKDCMIK = 1;
    ADIHAECHADG EBOFLGPCGNN = 7;
}

message MJEPCLPMKKI {
    uint32 HDHNKFPMPAO = 1;
}

message MKFCLDMEMGN {
    uint32 FALFBMDDFPA = 12;
}

message MKNALGLEBNA {
    LEJFIEPMMGG DKEENIMPLKD = 4;
}

message NBFAGOOJIOB {
    uint32 OMHHOADFMLI = 7;
}

message NEFBECKCJIH {
    uint32 GCAHKLNGFCK = 12;
    ItemCostData cost_data = 14;
}

message NEMJDLLBBGN {
    MMBBHFNJILI BLEBJLDOLII = 9;
    repeated uint32 LIIJNIKIGJD = 13;
}

message NGOKMAABDJJ {
    repeated uint32 GMMAFIONFNF = 6;
}

message NHGJEIHKKHB {
    repeated NMDKHGGGMBC JHEHAIBMNNF = 4;
    repeated NMHMGHEHHCM PMIFFBHOOOO = 15;
    repeated BPHIKPCNBHM buff_list = 13;
    repeated CIGDBCKOFBN MAJGMMCOCIG = 5;
}

enum NHHMEPILLHL {
    NHHMEPILLHL_NLCDGIPGFDJ = 0;
    NHHMEPILLHL_MIDKKNAGOFA = 1;
    NHHMEPILLHL_FJMCIHHIGIA = 2;
    NHHMEPILLHL_ANBKDJKHCBI = 3;
    NHHMEPILLHL_NCLBFAALLFJ = 4;
    NHHMEPILLHL_EPCDLHFFBLI = 5;
    NHHMEPILLHL_MOFNIOJHBBL = 6;
    NHHMEPILLHL_CLNGFDPINDB = 7;
    NHHMEPILLHL_BGDGIIOKHGF = 8;
    NHHMEPILLHL_MCGGEAAHBPD = 9;
    NHHMEPILLHL_FMPGGENBHID = 10;
    NHHMEPILLHL_EMALBALANLH = 11;
    NHHMEPILLHL_LFCDGLIEHAI = 12;
    NHHMEPILLHL_DOFDGKKLJDD = 13;
    NHHMEPILLHL_JOLNBCHMDNN = 14;
    NHHMEPILLHL_BGPLPIPENJN = 15;
    NHHMEPILLHL_NPAFMEBNFOB = 16;
    NHHMEPILLHL_IKCHCHPGFFJ = 17;
}

enum NKLAEHJPIMN {
    NKLAEHJPIMN_FGOFDMDBMAL = 0;
    NKLAEHJPIMN_GNGGGHLBNEH = 1;
    NKLAEHJPIMN_GIHACHNKFIE = 2;
}

message NKOBPBBONDJ {
    bool BJDEBHMKJBC = 14;
    BDJLHJDPEEK KDFKDNLNDHN = 6;
}

message NMDKHGGGMBC {
    uint32 AFEMBLFCCCH = 5;
    uint32 level = 8;
    uint32 exp = 7;
    uint32 max_level = 13;
    repeated uint32 HMIOHPIMLCE = 11;
}

message NMHMGHEHHCM {
    bool ALAJJMKOMML = 10;
    uint32 PNHGLNPDFEA = 12;
}

message NPAJHGDEIDJ {
    LPCEBDCJBOI status = 4;
    uint32 ECPDJMMOGCI = 3;
}

message NPCIGEBNOFG {
    uint32 num = 7;
    uint32 display_type = 2;
}

message OBNEOHHDAIP {
    JDFNPICGCGI IFPBFMOAJOP = 13;
}

message OECNJOAPCKO {
    uint32 FAGJACOFHGF = 4;
    uint32 KMIKBANMAFK = 15;
}

message OEPAMDEPFLJ {
    uint32 dialogue_id = 2;
}

message OEPIHJOHLKM {
    LHKAOPAPJEK IDCMACCPCBH = 15;
}

message OJPMMKIJIFH {
    map<uint32, ItemCostData> BHPELIMODBC = 8;
    ItemCostData PKAMBCBEKME = 3;
    uint32 JFIGNBBLCIM = 5;
    int32 LIAGGDDILGO = 12;
}

message OKBLBLPOENO {
    KOFMGCNIMIN miracle = 3;
}

message OKFPPPBNJNH {
    OFMCKLEMOMP FNEOOMHHGGB = 2;
}

message OMACAKFNAOA {
    repeated KVP IHFEBNBHDFM = 8;
}

message OMLMOJIGLEE {
    uint32 KAHMGPGPOII = 3;
    ItemCostData KINNMAGDDJJ = 6;
    bool BELPGDAGFIH = 4;
    bool GCIHGKCJOGB = 8;
    ItemCostData cost_data = 1;
}

message OMNMBANDCBA {
    uint32 JFIGNBBLCIM = 2;
    map<uint32, bool> PILABDDEKII = 4;
    int32 LIAGGDDILGO = 9;
    ItemCostData cost_data = 1;
}

message PGINHECHMPM {
}

message PIACCCGNOOF {
    uint32 battle_event_id = 9;
}

message PKHKEEKIODC {
    NPCIGEBNOFG DDCLCNPONOH = 3;
    NPCIGEBNOFG CONDGFPOFKD = 14;
    KJAMNOGFAMJ IFOOEPKGGAG = 1335;
    KJAMNOGFAMJ CMPNCFCJCNE = 1516;
    IOMEMIEAPJO GPJJMPCMAAA = 449;
    IKHMHNOIGAB LAEFENCCBBC = 21;
    LHKNCMFEPFK KDJBDMLDMHG = 1738;
    OKBLBLPOENO CBPINAOHEBD = 780;
    JLHJICBCHMO OMFLCEBLLMI = 978;
    CKEOMFNPKPO FLGGFGCIGNJ = 183;
    KNEJEHOOFGI ACIFEIPPILA = 868;
    JJEMDNEIMOJ MDGNDLLEFJE = 105;
    MKNALGLEBNA JOCLINGHBHE = 1665;
    PKOHBLEGMAO HPMJHOGCLGG = 1416;
    FBGIINJFCCD KMAMKBKNCPM = 836;
    CFJNAPDIMKM JEJCFJEDOLA = 146;
    CJAFLDKHDAF JEBLGELGBHM = 553;
    HCNEFGJCCMB GHMKDCKJILO = 1674;
    LFLMJKLKBIL CEICJPEMGHD = 68;
    GNGIHJIJGMD EBFCOMCMGLC = 1797;
    LBBCNOOOCNE JDCMEPIOMPN = 589;
    AOFKCKOIFCM KCGHLOHDMBM = 1871;
    MMBBHFNJILI JMJPONNLJEJ = 734;
    MMBBHFNJILI MCPKPJHBEAK = 1720;
    MMBBHFNJILI GDABGNBKFPA = 594;
    DNLKMHLAPHC APGPOGAKPAC = 1155;
    NEMJDLLBBGN JOLNBCHMDNN = 854;
    NBFAGOOJIOB KOHOCJAMJAN = 1209;
    NBFAGOOJIOB AEGMECDFNBE = 2004;
    NKOBPBBONDJ CIOLGFNLEBB = 2011;
    IPKOBBJPKML BIJODAGIKNF = 1481;
    GNLBCCHFILK MELCFMHKECA = 1739;
    EDDEOKAIJAB EMKIGHCFKCN = 528;
    PKOOFPOCNKB KAHKMDHFLOH = 1917;
    HIMJNABCJMM ALNEINEOJOJ = 103;
    PPHLEBFJIGM EGPLOEAAFGL = 1186;
    JGCMGAMHDHM JKLJBCBFNPL = 2001;
    OECNJOAPCKO MIDFLEHKPBF = 1763;
    OMACAKFNAOA NBEKLDCBJCH = 113;
    GBKILNHHGLB DFJCKBLAOBN = 555;
    OEPIHJOHLKM FLPDILMMCFK = 1287;
}

message PKOHBLEGMAO {
    LEJFIEPMMGG DKEENIMPLKD = 2;
}

message PKOOFPOCNKB {
    uint32 DBPAHBJPFLJ = 15;
    uint32 IFDIHFKKCLE = 7;
}

message PPHLEBFJIGM {
    uint32 style_level = 2;
    uint32 OIIJCLJHPPE = 1;
    uint32 AIIFGDGONIF = 6;
    uint32 style_exp = 12;
}

message RogueDoGambleCsReq {
    uint32 prop_entity_id = 6;
}

message RogueDoGambleScRsp {
    uint32 DOOECGPIMBD = 5;
    HKOEAOPNEAC KOBBMDFPNKA = 14;
    uint32 HNCCDEPDNEG = 12;
    uint32 retcode = 15;
}

message RogueGetGambleInfoCsReq {
    uint32 prop_entity_id = 7;
}

message RogueGetGambleInfoScRsp {
    HKOEAOPNEAC KOBBMDFPNKA = 14;
    uint32 retcode = 11;
}

message RogueShopBeginBattleCsReq {
    uint32 interacted_prop_entity_id = 10;
}

message RogueShopBeginBattleScRsp {
    uint32 retcode = 12;
    SceneBattleInfo AEPNEDJPAGK = 5;
}

message RogueWorkbenchGetInfoCsReq {
    uint32 prop_entity_id = 8;
}

message RogueWorkbenchGetInfoScRsp {
    map<uint32, BCOEGNBGJFC> NJAPFMHHPPA = 7;
    uint32 retcode = 15;
}

message RogueWorkbenchHandleFuncCsReq {
    MIPGDFDCKLE PELKPPHLMHE = 13;
    uint32 func_id = 6;
    uint32 prop_entity_id = 1;
}

message RogueWorkbenchHandleFuncScRsp {
    uint32 retcode = 4;
    uint32 func_id = 12;
    BCOEGNBGJFC JNPALDKNHKM = 3;
}

message SelectRogueCommonDialogueOptionCsReq {
    uint32 AIAFEKGBFIF = 7;
    uint32 HAFOKMHCGFM = 1;
}

message SelectRogueCommonDialogueOptionScRsp {
    repeated uint32 CGINGCNCPCO = 7;
    uint32 retcode = 13;
    uint32 AIAFEKGBFIF = 9;
    uint32 HAFOKMHCGFM = 14;
    HFEOGNAMHCG ONOLNGOHEMF = 11;
}

message SetRogueCollectionCsReq {
    repeated uint32 MFMPDDCGGMN = 8;
    repeated uint32 NPICFPDAPAF = 3;
    repeated MIGPNAOGHEP NEKJDKDAMKF = 6;
}

message SetRogueCollectionScRsp {
    repeated JMJEIBGACMD CEPDOBEIEFG = 3;
    repeated NPAJHGDEIDJ DPIKOCFILGP = 1;
    uint32 retcode = 4;
}

message SetRogueExhibitionCsReq {
    repeated uint32 HNCFLOKLJLA = 5;
    repeated uint32 DMIIBKINPNL = 6;
    repeated MIGPNAOGHEP ADGNFDJDCLG = 11;
}

message SetRogueExhibitionScRsp {
    repeated DGKLPPLJBNB PAKECMNPEJJ = 11;
    repeated DIKBPKAKENO JFHKJOGEOND = 8;
    uint32 retcode = 1;
}

message SyncRogueCommonActionResultScNotify {
    uint32 DLOJFEEHLIJ = 6;
    repeated ACMKPNMKOKH KCLBFINDGNA = 11;
    repeated MAOKMPOELCO CLGGKLNPLCK = 13;
    DICEONDKEFF display_type = 9;
}

message SyncRogueCommonDialogueDataScNotify {
    repeated HFEOGNAMHCG dialogue_list = 10;
}

message SyncRogueCommonDialogueOptionFinishScNotify {
    uint32 AIAFEKGBFIF = 12;
    uint32 HAFOKMHCGFM = 8;
    KDODFHMDAJI FJPGAOHGEBH = 1;
}

message SyncRogueCommonPendingActionScNotify {
    INHBMHCJJCN action = 1;
    uint32 DLOJFEEHLIJ = 10;
}

message SyncRogueHandbookDataUpdateScNotify {
    repeated ONMFMINNBEB LMDKIJFDLEO = 5;
    repeated NMHMGHEHHCM BOJGAEJNCFP = 1;
    repeated LGFOKKPICEH JEAGPFDBJDH = 6;
    repeated BPHIKPCNBHM IPNAAGCMNLB = 8;
    repeated CIGDBCKOFBN BFDFABHMCNE = 3;
}

message TakeRogueMiracleHandbookRewardScRsp {
    ItemList reward = 3;
    uint32 retcode = 8;
    repeated uint32 CNDLCGEFLCJ = 2;
}
