syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdRogueModifierType {
    CmdRogueModifierType_None = 0;
    CmdRogueModifierType_RogueModifierSelectCellScRsp = 5356;
    CmdRogueModifierType_RogueModifierDelNotify = 5373;
    CmdRogueModifierType_RogueModifierSelectCellCsReq = 5339;
    CmdRogueModifierType_RogueModifierStageStartNotify = 5399;
    CmdRogueModifierType_RogueModifierUpdateNotify = 5326;
    CmdRogueModifierType_RogueModifierAddNotify = 5379;
}

message RogueModifierAddNotify {
    BMCNDLNONMO modifier = 8;
}

message RogueModifierDelNotify {
    uint64 FCHLCANJIGL = 11;
}

message RogueModifierSelectCellCsReq {
    uint32 IHAOMLEPHOM = 5;
}

message RogueModifierSelectCellScRsp {
    ItemList NMJGHEACCMC = 11;
    uint32 retcode = 5;
}

message RogueModifierStageStartNotify {
    RogueModifierSourceType source_type = 5;
}

message RogueModifierUpdateNotify {
    BMCNDLNONMO modifier = 14;
}
