syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ABOFJEIMLLJ {
    uint32 buff_id = 13;
    uint32 level = 1;
}

message AEFFOCFJNBF {
    ItemCostData cost_data = 5;
    uint32 buff_id = 3;
}

message AGEHGBKOBEF {
    EDOIEMCFFCA LFLCDNGALME = 479;
    HNKAOFDGLIE CFDIKLBINHK = 939;
}

message ALBLEFHHJIC {
    uint32 id = 3;
    AvatarType avatar_type = 13;
    uint32 slot = 15;
    uint32 level = 6;
}

message CAJEBOPPMCJ {
    uint32 KNDHMNBIIDF = 3;
    bool ALAJJMKOMML = 6;
    RogueStatus NHDLEFAAPOB = 4;
    RogueAreaStatus area_status = 13;
    uint32 area_id = 2;
    uint32 map_id = 12;
}

message CDDIJCBEAHJ {
    repeated uint32 CEMOJMBHLDD = 13;
}

message CFMHEMGEANC {
    repeated ABOFJEIMLLJ CHCMEKAFKAF = 5;
}

message CGNNMPIKBBB {
    int64 begin_time = 13;
    uint32 LJNGPCKPJLF = 7;
    int64 end_time = 4;
}

message CIFCAIEDOLK {
    uint32 JPPAGGPJOMO = 3;
    uint32 unlock_aeon_enhance_num = 10;
}

enum CmdRogueType {
    CmdRogueType_None = 0;
    CmdRogueType_FinishAeonDialogueGroupScRsp = 1851;
    CmdRogueType_TakeRogueAeonLevelRewardScRsp = 1876;
    CmdRogueType_GetRogueBuffEnhanceInfoScRsp = 1838;
    CmdRogueType_GetRogueBuffEnhanceInfoCsReq = 1841;
    CmdRogueType_SyncRogueFinishScNotify = 1804;
    CmdRogueType_EnableRogueTalentCsReq = 1810;
    CmdRogueType_GetRogueInitialScoreCsReq = 1855;
    CmdRogueType_SyncRogueGetItemScNotify = 1854;
    CmdRogueType_SyncRogueMapRoomScNotify = 1802;
    CmdRogueType_QuitRogueScRsp = 1844;
    CmdRogueType_SyncRogueAreaUnlockScNotify = 1827;
    CmdRogueType_ReviveRogueAvatarCsReq = 1888;
    CmdRogueType_PickRogueAvatarScRsp = 1849;
    CmdRogueType_PickRogueAvatarCsReq = 1862;
    CmdRogueType_EnhanceRogueBuffScRsp = 1846;
    CmdRogueType_TakeRogueAeonLevelRewardCsReq = 1859;
    CmdRogueType_EnterRogueMapRoomCsReq = 1840;
    CmdRogueType_LeaveRogueScRsp = 1826;
    CmdRogueType_StartRogueCsReq = 1879;
    CmdRogueType_LeaveRogueCsReq = 1898;
    CmdRogueType_SyncRogueSeasonFinishScNotify = 1858;
    CmdRogueType_StartRogueScRsp = 1839;
    CmdRogueType_SyncRogueReviveInfoScNotify = 1805;
    CmdRogueType_SyncRogueStatusScNotify = 1877;
    CmdRogueType_EnableRogueTalentScRsp = 1861;
    CmdRogueType_GetRogueAeonInfoCsReq = 1893;
    CmdRogueType_SyncRogueAeonScNotify = 1894;
    CmdRogueType_GetRogueTalentInfoScRsp = 1895;
    CmdRogueType_SyncRogueVirtualItemInfoScNotify = 1867;
    CmdRogueType_ExchangeRogueRewardKeyCsReq = 1819;
    CmdRogueType_FinishAeonDialogueGroupCsReq = 1831;
    CmdRogueType_EnterRogueMapRoomScRsp = 1883;
    CmdRogueType_EnterRogueScRsp = 1891;
    CmdRogueType_GetRogueInfoScRsp = 1882;
    CmdRogueType_QuitRogueCsReq = 1823;
    CmdRogueType_GetRogueInitialScoreScRsp = 1875;
    CmdRogueType_OpenRogueChestCsReq = 1820;
    CmdRogueType_GetRogueTalentInfoCsReq = 1897;
    CmdRogueType_EnhanceRogueBuffCsReq = 1857;
    CmdRogueType_OpenRogueChestScRsp = 1868;
    CmdRogueType_SyncRogueExploreWinScNotify = 1808;
    CmdRogueType_GetRogueAeonInfoScRsp = 1812;
    CmdRogueType_GetRogueInfoCsReq = 1834;
    CmdRogueType_ExchangeRogueRewardKeyScRsp = 1833;
    CmdRogueType_EnterRogueCsReq = 1856;
    CmdRogueType_ReviveRogueAvatarScRsp = 1815;
}

message DNDMLICBKEF {
    uint32 map_id = 8;
    uint32 area_id = 5;
    uint32 ANHDBMOPGDC = 4;
    uint32 HPKMGKPPELC = 13;
    repeated PAIJCBOKIFO LLNICHDDIAN = 15;
}

message EDOIEMCFFCA {
    CGNNMPIKBBB HHFAAFOBKME = 5;
    MBCBDJNKFEB NIKDPODBIEF = 15;
    GFGHGCIMKGA AEFMMOHKCHJ = 12;
    GOIEJOCFKEE ACLKMFCDMED = 14;
}

message EFDAIBDBFEA {
    uint32 NPHAJEKCBKF = 8;
    uint32 LJCEOGPOGBE = 1;
    uint32 DGGCFDKJDPO = 2;
    uint32 total_count = 6;
}

message ENOBKLGCHOD {
    KCMFAIBMOHB MFEODNJNGDP = 2;
    repeated uint32 unfinished_story_line_id_list = 5;
    repeated uint32 NOEPBNMJFGL = 14;
}

message EnableRogueTalentCsReq {
    uint32 CKHCLKOALKE = 14;
}

message EnableRogueTalentScRsp {
    FDBDLBAPDBE JCOBJAMPOAL = 11;
    uint32 retcode = 15;
}

message EnhanceRogueBuffCsReq {
    uint32 IJAOJBIBDEN = 5;
}

message EnhanceRogueBuffScRsp {
    KJAMNOGFAMJ CNEFDJCKAPL = 9;
    bool KGKEJAKKLDP = 1;
    uint32 retcode = 5;
}

message EnterRogueCsReq {
    uint32 area_id = 15;
}

message EnterRogueMapRoomCsReq {
    uint32 room_id = 15;
    uint32 MAJKFIMPOOF = 13;
}

message EnterRogueMapRoomScRsp {
    LineupInfo lineup = 8;
    uint32 ANHDBMOPGDC = 11;
    SceneInfo scene = 6;
    FHEGNOPNICH JNKLNLKHGBB = 10;
    uint32 retcode = 12;
}

message EnterRogueScRsp {
    FHEGNOPNICH JNKLNLKHGBB = 4;
    SceneInfo scene = 15;
    uint32 retcode = 1;
    AGEHGBKOBEF rogue_game_info = 14;
    LineupInfo lineup = 7;
}

message ExchangeRogueRewardKeyCsReq {
    uint32 count = 3;
}

message ExchangeRogueRewardKeyScRsp {
    uint32 retcode = 7;
    uint32 count = 12;
}

message FLCPJJMHAGO {
    uint32 exp = 13;
    uint32 level = 11;
    uint32 AFEMBLFCCCH = 3;
    uint32 max_level = 8;
}

message FinishAeonDialogueGroupCsReq {
    uint32 AFEMBLFCCCH = 1;
}

message FinishAeonDialogueGroupScRsp {
    uint32 retcode = 11;
    ItemList reward = 1;
    FLCPJJMHAGO AEFMMOHKCHJ = 14;
}

message GAOBHBLFPEC {
    uint32 DBHOIDLKMAB = 2;
    uint32 OFHBBKOKANF = 5;
    uint32 GBIEAMKLONK = 7;
    uint32 LKHAIEIDAJL = 8;
}

message GFGHGCIMKGA {
    repeated uint32 OPAEGCBNACJ = 15;
    uint32 unlock_aeon_enhance_num = 7;
}

message GKHGFCBMLBL {
    uint32 MHPHDCFKMLF = 15;
    uint32 HEOMALBNJLL = 203;
    uint32 score_id = 7;
    ItemList LHPNJLBPACA = 6;
    uint32 GHCBFCIGIBF = 5;
    KCOEJJKGNIG record_info = 9;
    bool is_win = 4;
    uint32 GEBGGMAGDJB = 13;
    uint32 area_id = 1169;
    uint32 GMIIMAHLIJF = 14;
}

message GOIEJOCFKEE {
    repeated CAJEBOPPMCJ OJGOAOPLMLB = 10;
}

message GetRogueAeonInfoCsReq {
}

message GetRogueAeonInfoScRsp {
    uint32 retcode = 7;
    repeated FLCPJJMHAGO JHEHAIBMNNF = 5;
}

message GetRogueBuffEnhanceInfoCsReq {
}

message GetRogueBuffEnhanceInfoScRsp {
    HFGBCEKGFHK retcode = 3;
    uint32 PLDKENJLKME = 4;
}

message GetRogueInfoCsReq {
}

message GetRogueInfoScRsp {
    AGEHGBKOBEF rogue_game_info = 12;
    uint32 retcode = 11;
}

message GetRogueTalentInfoCsReq {
}

message GetRogueTalentInfoScRsp {
    FDBDLBAPDBE JCOBJAMPOAL = 6;
    uint32 retcode = 15;
}

message HFGBCEKGFHK {
    repeated AEFFOCFJNBF EMAGFIBLNCJ = 8;
}

message HIGAMEJNCJJ {
    uint32 AFEMBLFCCCH = 15;
    uint32 level = 8;
}

message HIKOBOMBMPB {
    OEDNNHAOHAB DNPCCFFFBHN = 12;
}

message HNKAOFDGLIE {
    INHBMHCJJCN FMIGOKIDKJL = 3;
    AGEOGDOGDMM DHEKLJDBNNP = 5;
    ENOBKLGCHOD EIOHFJMFOKF = 12;
    DNDMLICBKEF COOOMDKGODF = 2;
    RogueStatus status = 15;
    CDDIJCBEAHJ IELPCHGLFCA = 6;
    CFMHEMGEANC HABJHGPFGEB = 10;
    bool ILOFGCAFHAH = 14;
    HIKOBOMBMPB DNPCCFFFBHN = 9;
    CIFCAIEDOLK AEFMMOHKCHJ = 1;
}

message JIBBEEAIDIC {
    uint32 JPPAGGPJOMO = 5;
    repeated uint32 OPAEGCBNACJ = 11;
    uint32 unlock_aeon_enhance_num = 7;
}

message KCMFAIBMOHB {
    ItemCostData LNIEFKBMIPD = 4;
}

message KCOEJJKGNIG {
    repeated ALBLEFHHJIC avatar_list = 8;
    repeated ABOFJEIMLLJ buff_list = 5;
    repeated uint32 MAJGMMCOCIG = 15;
}

message LeaveRogueCsReq {
}

message LeaveRogueScRsp {
    SceneInfo scene = 12;
    LineupInfo lineup = 3;
    FHEGNOPNICH JNKLNLKHGBB = 5;
    uint32 retcode = 6;
}

message MBCBDJNKFEB {
    uint32 GEBGGMAGDJB = 7;
    uint32 CICAENDEDFE = 8;
    uint32 PDGBEJHNHHE = 5;
}

message OEDNNHAOHAB {
    repeated EFDAIBDBFEA MAJGMMCOCIG = 1;
}

message OpenRogueChestCsReq {
    bool FDEKKOKBDIC = 6;
    uint32 interacted_prop_entity_id = 3;
}

message OpenRogueChestScRsp {
    uint32 retcode = 12;
    ItemList drop_data = 8;
    LMDPKOELKFL ABEMLCJBIEF = 2;
    ItemList reward = 9;
}

message PAIJCBOKIFO {
    uint32 MAJKFIMPOOF = 12;
    RogueRoomStatus FCHHPCIDNGM = 4;
    RogueRoomStatus CAGDNHCOCKM = 15;
    uint32 PGACMFLCDID = 2;
    uint32 room_id = 9;
}

message PickRogueAvatarCsReq {
    uint32 prop_entity_id = 1;
    repeated uint32 NOEPBNMJFGL = 9;
}

message PickRogueAvatarScRsp {
    repeated uint32 DFPPCAJDBFK = 14;
    repeated uint32 NDFHHFGKMAI = 4;
    uint32 retcode = 7;
}

message QuitRogueCsReq {
    uint32 area_id = 7;
}

message QuitRogueScRsp {
    AGEHGBKOBEF rogue_game_info = 3;
    uint32 retcode = 10;
}

message ReviveRogueAvatarCsReq {
    uint32 interacted_prop_entity_id = 15;
    repeated uint32 NOEPBNMJFGL = 1;
}

message ReviveRogueAvatarScRsp {
    uint32 PLDKENJLKME = 15;
    KCMFAIBMOHB PHNAANFIFGB = 9;
}

enum RogueAreaStatus {
    RogueAreaStatus_Lock = 0;
    RogueAreaStatus_Unlock = 1;
    RogueAreaStatus_FirstPass = 2;
    RogueAreaStatus_Close = 3;
}

enum RogueRoomStatus {
    RogueRoomStatus_None = 0;
    RogueRoomStatus_Lock = 1;
    RogueRoomStatus_Unlock = 2;
    RogueRoomStatus_Play = 3;
    RogueRoomStatus_Finish = 4;
}

message StartRogueCsReq {
    uint32 AFEMBLFCCCH = 9;
    uint32 area_id = 8;
    repeated uint32 JKPIPNMGGOA = 7;
    repeated uint32 NOEPBNMJFGL = 10;
    repeated uint32 unfinished_story_line_id_list = 5;
}

message StartRogueScRsp {
    SceneInfo scene = 14;
    FHEGNOPNICH JNKLNLKHGBB = 1;
    AGEHGBKOBEF rogue_game_info = 12;
    LineupInfo lineup = 10;
    uint32 retcode = 5;
}

message SyncRogueAeonScNotify {
    JIBBEEAIDIC BGDGIIOKHGF = 9;
}

message SyncRogueAreaUnlockScNotify {
    uint32 area_id = 1;
}

message SyncRogueExploreWinScNotify {
    bool ILOFGCAFHAH = 13;
}

message SyncRogueFinishScNotify {
    GKHGFCBMLBL NLEOMLNOKCC = 15;
}

message SyncRogueGetItemScNotify {
    ItemList get_item_list = 9;
    ItemList IIDEAGLAMCC = 1;
}

message SyncRogueMapRoomScNotify {
    PAIJCBOKIFO HNEANMNJHDB = 15;
    uint32 map_id = 5;
}

message SyncRogueReviveInfoScNotify {
    KCMFAIBMOHB MFEODNJNGDP = 4;
}

message SyncRogueSeasonFinishScNotify {
    SceneInfo scene = 10;
    LineupInfo lineup = 8;
    GKHGFCBMLBL NLEOMLNOKCC = 14;
    bool FALJMPELHIO = 12;
}

message SyncRogueStatusScNotify {
    RogueStatus status = 11;
    bool AOBCKABCHGO = 4;
}

message SyncRogueVirtualItemInfoScNotify {
    GAOBHBLFPEC NIKDPODBIEF = 5;
}
