syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AJNOEKPLPCL {
    bool MJIPOJPBKNB = 5;
    uint32 IEOGEFBLNEL = 4;
    uint32 DNAPFBANFHJ = 14;
    uint32 FMCPHDJEIDC = 7;
    uint32 ICKJKIENKFI = 12;
    uint32 PKKDALHLCLA = 13;
    uint32 cur_layer = 11;
}

message BBCOLCHCEFP {
    repeated uint32 unfinished_story_line_id_list = 3;
    uint32 PJKMDLCCHHD = 9;
    APNCCNFJBKO JPKACKNNHCA = 15;
    RogueStatus status = 12;
    uint32 map_id = 5;
    GMIJHCONFIH HAJJBOFCFOO = 1;
    uint32 KNDHMNBIIDF = 11;
    repeated uint32 NOEPBNMJFGL = 2;
}

message CAEFBGAFKHD {
    AvatarType avatar_type = 11;
    uint32 avatar_id = 9;
}

enum CmdRogueEndlessType {
    CmdRogueEndlessType_CmdRogueEndlessNone = 0;
    CmdRogueEndlessType_EnterRogueEndlessActivityStageCsReq = 6007;
    CmdRogueEndlessType_GetRogueEndlessActivityDataScRsp = 6010;
    CmdRogueEndlessType_RogueEndlessActivityBattleEndScNotify = 6006;
    CmdRogueEndlessType_TakeRogueEndlessActivityAllBonusRewardCsReq = 6001;
    CmdRogueEndlessType_GetRogueEndlessActivityDataCsReq = 6005;
    CmdRogueEndlessType_EnterRogueEndlessActivityStageScRsp = 6009;
    CmdRogueEndlessType_TakeRogueEndlessActivityPointRewardScRsp = 6008;
    CmdRogueEndlessType_TakeRogueEndlessActivityPointRewardCsReq = 6002;
    CmdRogueEndlessType_TakeRogueEndlessActivityAllBonusRewardScRsp = 6004;
}

message EnterRogueEndlessActivityStageCsReq {
    uint32 MPMMCPMNLID = 4;
    repeated CAEFBGAFKHD avatar_list = 14;
}

message EnterRogueEndlessActivityStageScRsp {
    SceneBattleInfo battle_info = 6;
    uint32 retcode = 15;
}

message GetRogueEndlessActivityDataCsReq {
}

message GetRogueEndlessActivityDataScRsp {
    uint32 IAHEDAAPNEO = 9;
    uint32 CHIAFOOAIBK = 3;
    repeated uint32 IEPPNGMCKJH = 2;
    uint32 retcode = 7;
    repeated HGFJAHILCAA data = 12;
}

message HGFJAHILCAA {
    BBCOLCHCEFP BHHHNHMMDMH = 6;
    AJNOEKPLPCL PMKGMLELPPI = 14;
    uint32 area_id = 10;
}

message RogueEndlessActivityBattleEndScNotify {
    AJNOEKPLPCL PMKGMLELPPI = 12;
}

message TakeRogueEndlessActivityAllBonusRewardCsReq {
}

message TakeRogueEndlessActivityAllBonusRewardScRsp {
    uint32 CHIAFOOAIBK = 8;
    uint32 retcode = 9;
    ItemList reward = 15;
    repeated uint32 IEPPNGMCKJH = 2;
}

message TakeRogueEndlessActivityPointRewardCsReq {
    uint32 level = 6;
    bool LEFJBFMDEGK = 3;
}

message TakeRogueEndlessActivityPointRewardScRsp {
    uint32 retcode = 5;
    ItemList reward = 3;
    repeated uint32 IEPPNGMCKJH = 8;
    uint32 CHIAFOOAIBK = 13;
    uint32 level = 12;
}
