syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AAFBNNALHDK {
    repeated uint32 HHFPJHMEIJK = 8;
    uint32 avatar_id = 13;
    uint32 NPHAJEKCBKF = 9;
    uint32 BDJDAOGDBDD = 14;
    uint32 ALOPEGJPAKK = 12;
}

message AJCFOLGANFC {
    uint32 DEDCHHNCHFM = 5;
    uint32 style_exp = 14;
    uint32 style_level = 9;
    repeated JHECCCANFGP GJBOLJEJIEE = 11;
    repeated KVP IHFEBNBHDFM = 13;
    uint32 HGKBJMGGPGL = 10;
    uint32 PGGDEHKKINP = 8;
}

message AMOHFCEEBNK {
    FGGJCLDLMMI FCMGNLIODGI = 11;
}

message BJLNEBBMMOE {
    uint32 PDFJMFBHPFC = 8;
    uint32 NIOFIOOGKLD = 4;
    bool DOFNEAPHMKH = 14;
}

message CABKLLAKHKO {
    AJCFOLGANFC GMEPGCODKKE = 2;
}

message CFOIFHEBCJC {
    LPADDGPLIKK CCFGCCMEFCI = 3;
}

message CGBKKJENEOF {
    repeated uint32 BDBFENOAKOD = 2;
}

message CGNGOLJKBMP {
    HGGPKPPBGFP HHMLHKLKNDH = 2;
    EGLAPJGFKPN buff = 12;
    FKEDPCMLIFE item_value = 10;
    OHHKEOGOMCA LNCOKKIPAEP = 11;
    HIAHPMEAGFC BCNMBONFKPK = 4;
    DJODDECFHMC formula = 14;
    PHHLBGLNBHE MEEJDFNHBDI = 1;
    JEIKFFFGONB lineup = 6;
    CGBKKJENEOF BKIPDOFONLD = 3;
    NHLBNBBDHMI miracle = 13;
    ONPOFJPEBMJ level = 8;
}

message CJOCDGGCPCN {
    uint32 JDPFPDECPEH = 8;
    int64 end_time = 11;
    uint32 JNBIIJCAKKB = 1;
    bool KBNNOPHGGIN = 2;
}

message COOIDLLFFIJ {
    uint32 KNILAKJMEEP = 11;
    uint32 PGGDEHKKINP = 9;
}

enum CmdRogueTournType {
    CmdRogueTournType_None = 0;
    CmdRogueTournType_RogueTournGetSeasonTalentInfoScRsp = 6075;
    CmdRogueTournType_RogueTournHandBookNotify = 6091;
    CmdRogueTournType_RogueTournEnterLayerScRsp = 6050;
    CmdRogueTournType_RogueTournBattleFailSettleInfoScNotify = 6040;
    CmdRogueTournType_RogueTournLeaveRogueCocoonSceneCsReq = 6078;
    CmdRogueTournType_RogueTournConfirmSettleScRsp = 6026;
    CmdRogueTournType_RogueTournRenameBuildRefScRsp = 6084;
    CmdRogueTournType_RogueTournExpNotify = 6081;
    CmdRogueTournType_RogueTournUseSuperRewardKeyCsReq = 6028;
    CmdRogueTournType_RogueTournLeaveScRsp = 6019;
    CmdRogueTournType_RogueTournEnterRogueCocoonSceneCsReq = 6021;
    CmdRogueTournType_RogueTournEnterCsReq = 6069;
    CmdRogueTournType_RogueTournGetMiscRealTimeDataCsReq = 6088;
    CmdRogueTournType_RogueTournGetSettleInfoCsReq = 6035;
    CmdRogueTournType_RogueTournTakeExpRewardScRsp = 6094;
    CmdRogueTournType_RogueTournSaveBuildRefCsReq = 6066;
    CmdRogueTournType_RogueTournReviveAvatarCsReq = 6072;
    CmdRogueTournType_RogueTournTakeExpRewardCsReq = 6059;
    CmdRogueTournType_RogueTournStartScRsp = 6036;
    CmdRogueTournType_RogueTournLeaveRogueCocoonSceneScRsp = 6030;
    CmdRogueTournType_RogueTournGetSettleInfoScRsp = 6057;
    CmdRogueTournType_RogueTournWeekChallengeUpdateScNotify = 6080;
    CmdRogueTournType_RogueTournTriggerRoomSelectScRsp = 6063;
    CmdRogueTournType_RogueTournAreaUpdateScNotify = 6031;
    CmdRogueTournType_RogueTournEnterRoomCsReq = 6086;
    CmdRogueTournType_RogueTournGetArchiveRepositoryCsReq = 6089;
    CmdRogueTournType_RogueTournDeleteBuildRefCsReq = 6062;
    CmdRogueTournType_RogueTournStartCsReq = 6098;
    CmdRogueTournType_RogueTournLeaveCsReq = 6083;
    CmdRogueTournType_RogueTournGetArchiveRepositoryScRsp = 6024;
    CmdRogueTournType_RogueTournEnableSeasonTalentCsReq = 6046;
    CmdRogueTournType_RogueTournGetPermanentTalentInfoCsReq = 6048;
    CmdRogueTournType_RogueTournEnterScRsp = 6018;
    CmdRogueTournType_RogueTournSaveBuildRefScRsp = 6017;
    CmdRogueTournType_RogueTournResetPermanentTalentScRsp = 6034;
    CmdRogueTournType_RogueTournRenameArchiveCsReq = 6012;
    CmdRogueTournType_RogueTournEnablePermanentTalentScRsp = 6064;
    CmdRogueTournType_RogueTournGetMiscRealTimeDataScRsp = 6073;
    CmdRogueTournType_RogueTournApplyBuildRefCsReq = 6090;
    CmdRogueTournType_RogueTournReviveCostUpdateScNotify = 6096;
    CmdRogueTournType_RogueTournEnterRogueCocoonSceneScRsp = 6068;
    CmdRogueTournType_RogueTournEnterLayerCsReq = 6033;
    CmdRogueTournType_RogueTournLevelInfoUpdateScNotify = 6011;
    CmdRogueTournType_RogueTournDeleteArchiveScRsp = 6067;
    CmdRogueTournType_RogueTournGetAllArchiveScRsp = 6065;
    CmdRogueTournType_RogueTournResetPermanentTalentCsReq = 6044;
    CmdRogueTournType_RogueTournApplyBuildRefScRsp = 6093;
    CmdRogueTournType_RogueTournGetAllBuildRefScRsp = 6079;
    CmdRogueTournType_RogueTournTriggerRoomSelectCsReq = 6055;
    CmdRogueTournType_RogueTournConfirmSettleCsReq = 6025;
    CmdRogueTournType_RogueTournReviveAvatarScRsp = 6099;
    CmdRogueTournType_RogueTournUseSuperRewardKeyScRsp = 6060;
    CmdRogueTournType_RogueTournPersonaRoomCardZoneUpdateScNotify = 6022;
    CmdRogueTournType_RogueTournGetAllBuildRefCsReq = 6074;
    CmdRogueTournType_RogueTournGetCurRogueCocoonInfoScRsp = 6085;
    CmdRogueTournType_RogueTournReEnterRogueCocoonStageScRsp = 6070;
    CmdRogueTournType_RogueTournRenameBuildRefCsReq = 6052;
    CmdRogueTournType_RogueTournGetAllArchiveCsReq = 6015;
    CmdRogueTournType_RogueTournGetCurRogueCocoonInfoCsReq = 6038;
    CmdRogueTournType_RogueTournQueryCsReq = 6076;
    CmdRogueTournType_RogueTournDeleteArchiveCsReq = 6056;
    CmdRogueTournType_RogueTournEnterRoomScRsp = 6023;
    CmdRogueTournType_RogueTournEnablePermanentTalentCsReq = 6049;
    CmdRogueTournType_RogueTournGetPermanentTalentInfoScRsp = 6014;
    CmdRogueTournType_RogueTournSettleScRsp = 6053;
    CmdRogueTournType_RogueTournTitanUpdateTitanBlessProgressScNotify = 6029;
    CmdRogueTournType_RogueTournGetSeasonTalentInfoCsReq = 6058;
    CmdRogueTournType_RogueTournDeleteBuildRefScRsp = 6047;
    CmdRogueTournType_RogueTournQueryScRsp = 6092;
    CmdRogueTournType_RogueTournClearArchiveNameScNotify = 6037;
    CmdRogueTournType_RogueTournEnableSeasonTalentScRsp = 6054;
    CmdRogueTournType_RogueTournReEnterRogueCocoonStageCsReq = 6082;
    CmdRogueTournType_RogueTournSettleCsReq = 6045;
    CmdRogueTournType_RogueTournRenameArchiveScRsp = 6051;
}

message DCDMPLJNBJC {
    uint32 KABCGHCPEBG = 7;
    bool DOFNEAPHMKH = 13;
    uint32 NDGKLBDHJKB = 1;
    uint32 GEPHKCPLAJF = 6;
}

message DIFGGDIHDEG {
    int64 time = 1;
    uint32 NPHAJEKCBKF = 8;
    string name = 4;
    int64 BHNFGJOLLLB = 3;
    OOLJJHMLHBH MPOEFPFPEND = 15;
}

message DJODDECFHMC {
    repeated LEJFIEPMMGG KJFEFFGPNFF = 9;
    HMAAICNBKCI ENFIKCCMHAI = 15;
    repeated OMJGKNJKHCH EMLLEPOADED = 12;
}

message DKFJLHHDFKO {
    AvatarType avatar_type = 13;
    uint32 id = 6;
}

message DLEKOLHCNIE {
    bool is_unlock = 7;
    bool is_taken_reward = 11;
    uint32 area_id = 1;
    bool FJKHIFDJMDB = 14;
}

message DNCEOOPHIOK {
    uint32 LJCEOGPOGBE = 8;
}

message ECMNFOEDOJC {
    uint32 LJCEOGPOGBE = 15;
}

message ELHLCFBPAMO {
    uint32 composition_type = 7;
    repeated uint32 attribute_list = 14;
    uint32 level = 4;
}

message FAICNBKIELL {
    GKHFFKMFMEN JJLFKNPEPFP = 9;
    JGMDJIENFFH CPOLAHJPGFE = 12;
    BJLNEBBMMOE AOMHPLHONJA = 5;
    DCDMPLJNBJC AOGOHOCFFNE = 15;
    FBBOKKLGKGL BNLLEJPCIGD = 2;
    PFLOIHLLMEE PHGJIJELKDB = 6;
}

message FBBOKKLGKGL {
    uint32 LFCDPDDGFCB = 15;
    bool DOFNEAPHMKH = 13;
    uint32 DIFIEHPCDGO = 10;
}

message FGGJCLDLMMI {
    repeated uint32 OHKHMDEOCLA = 13;
    uint32 PLJPIPDFAHA = 15;
}

enum FKNGOGLNKIG {
    FKNGOGLNKIG_NLCDGIPGFDJ = 0;
    FKNGOGLNKIG_EHNIPLNEEDI = 1;
    FKNGOGLNKIG_PMKMEAAGKAP = 2;
    FKNGOGLNKIG_MNBAGHPEFBC = 3;
}

message GKHFFKMFMEN {
    bool DOFNEAPHMKH = 9;
    uint32 NIOFIOOGKLD = 11;
}

message HGGPKPPBGFP {
    uint32 OHPELHFNGCI = 7;
}

message HIAHPMEAGFC {
    bool JOOJIJFCHMK = 11;
}

message HMGGOEHMIJO {
    uint32 HHAEEEOADOJ = 13;
    uint32 FABMHMFNMDB = 2;
}

message HMOECPBNAOK {
    repeated uint32 IFFMIDABNEE = 5;
    repeated uint32 DMFAGJOOGJM = 14;
    repeated uint32 PINNDKIJHFG = 7;
    repeated uint32 JOAAOEDAPPJ = 1;
    repeated uint32 MMPPHJOONMI = 11;
    repeated uint32 DPEBCGBEJIG = 2;
    uint32 JKKIABLFCPE = 8;
}

enum IDCBNMFDICO {
    IDCBNMFDICO_NLCDGIPGFDJ = 0;
    IDCBNMFDICO_LOOAKNHDBLL = 1;
    IDCBNMFDICO_CIHFGJDCHIA = 2;
}

enum IIAOGEIADGA {
    IIAOGEIADGA_NLCDGIPGFDJ = 0;
    IIAOGEIADGA_JHHAJDKPLJH = 1;
    IIAOGEIADGA_LOOAKNHDBLL = 2;
    IIAOGEIADGA_CIHFGJDCHIA = 3;
}

message IJNFOHJGPBC {
    repeated ODNBCBEINNC JEHEILKKDEF = 2;
    uint32 MDAIAMFJNHM = 9;
    IDCBNMFDICO status = 13;
    uint32 JOJCPKNIJOH = 1;
    uint32 layer_index = 7;
}

message JGAMMPGMCNI {
    LineupInfo lineup = 8;
    SceneInfo scene = 3;
    FHEGNOPNICH JNKLNLKHGBB = 1;
}

message JGFPIJKOFCC {
    uint32 NPHAJEKCBKF = 7;
}

message JGJEICAELEB {
    uint32 exp = 7;
    repeated uint32 FKDNANDJLGK = 5;
}

message JGMDJIENFFH {
    uint32 GNIFODGCPAA = 3;
    uint32 JBKHIFHPGHM = 8;
}

message JHECCCANFGP {
    uint32 total_count = 3;
    uint32 GNCFHIKODKE = 4;
    uint32 unique_id = 11;
}

message KCDBGKJANIH {
    uint32 buff_id = 2;
}

message KGPIEEKIEME {
    uint32 OFNIDAECPCJ = 10;
    FDBDLBAPDBE JCOBJAMPOAL = 8;
}

message KIKEAJJLAMH {
    repeated MJMGOBMOPDL HLJOMIMOANL = 14;
    MDLPIFCHFPJ DPABCOHLPLH = 7;
    JGMDJIENFFH DLDCFHHFMID = 6;
    repeated DLEKOLHCNIE DANNIDIPFAL = 8;
    HMOECPBNAOK HAMKPLCBEBG = 11;
    CJOCDGGCPCN BFNHJIBDMOA = 13;
    KGPIEEKIEME HANICMMHJGI = 3;
    JGJEICAELEB DMFPCFCHHKE = 2;
    HMGGOEHMIJO HHFAAFOBKME = 9;
}

message KILGONODPIC {
    uint32 event_id = 1;
}

message LGCPLLJLHFF {
    uint32 item_value = 8;
    repeated KJAMNOGFAMJ buff_list = 15;
}

message LPADDGPLIKK {
    repeated uint32 NMMCOBBKKHA = 13;
    repeated BDJLHJDPEEK LONFKFCFDND = 12;
    uint32 MKJDMNAEAED = 8;
    uint32 AMOABLICEDP = 14;
    uint32 PJOAKLHHCNI = 7;
    repeated uint32 BIMFEAHDMIK = 2;
}

message MDLPIFCHFPJ {
    FDBDLBAPDBE JCOBJAMPOAL = 11;
    uint32 INJEKPLHPIF = 6;
}

message MJBODJKDPPD {
    uint32 KAHMGPGPOII = 12;
}

message MJMGOBMOPDL {
    uint32 NPHAJEKCBKF = 3;
    repeated DKFJLHHDFKO avatar_list = 2;
    PFLOIHLLMEE PHGJIJELKDB = 1;
    int64 end_time = 12;
    int64 time = 4;
    string name = 11;
    LGCPLLJLHFF data = 9;
    HMGGOEHMIJO HHFAAFOBKME = 10;
}

message NAMCKJLAFCN {
}

message NPOJNHKPKMN {
}

message ODNBCBEINNC {
    IIAOGEIADGA status = 6;
    uint32 EEPIDJJJMAH = 5;
    uint32 room_id = 15;
    uint32 LHLKJIDFLIN = 9;
    uint32 GHEHGIOAGDG = 10;
    ELHLCFBPAMO FIADMEPDAOG = 7;
}

message OHHKEOGOMCA {
    map<uint32, bool> PACLGPIDJGL = 7;
}

message ONPOFJPEBMJ {
    RogueTournLevelStatus status = 11;
    bool EJDMOENBHDP = 9;
    bool KENPENNAGLG = 13;
    uint32 BJHMFOAGMBF = 3;
    repeated IJNFOHJGPBC NNFFPJOLDHK = 1;
    FKNGOGLNKIG reason = 10;
    CFOIFHEBCJC FIADMEPDAOG = 2;
}

message OOLJJHMLHBH {
    uint32 FABMHMFNMDB = 14;
    repeated uint32 AKEMNAMGDOD = 8;
    repeated AAFBNNALHDK KOJMGCBLKKA = 13;
    repeated uint32 LBKFGKGNCCH = 6;
    repeated uint32 JHBEJKBCHEN = 7;
    uint32 HHAEEEOADOJ = 11;
    repeated uint32 MDHGBNCJNGB = 9;
}

message PFLOIHLLMEE {
    CBOLONJDHHL basic = 5;
    CGNGOLJKBMP AMEABNLMMGB = 3;
    NAMCKJLAFCN FBHCKMGOCJJ = 1670;
    AMOHFCEEBNK HAJEGKBFFAF = 1452;
    CABKLLAKHKO OPDEIFOCJEF = 1346;
}

message PHHLBGLNBHE {
    repeated uint32 KEHKLHMEABI = 11;
}

message RogueTournAreaUpdateScNotify {
    repeated DLEKOLHCNIE DANNIDIPFAL = 14;
}

message RogueTournBattleFailSettleInfoScNotify {
    FAICNBKIELL BFLLJJBHLDF = 3;
    JGAMMPGMCNI IDCMACCPCBH = 8;
}

message RogueTournClearArchiveNameScNotify {
    uint32 NPHAJEKCBKF = 12;
}

message RogueTournConfirmSettleCsReq {
    string name = 9;
    uint32 NPHAJEKCBKF = 4;
    uint32 area_id = 7;
}

message RogueTournConfirmSettleScRsp {
    ItemList AELJFOPMDJG = 14;
    JGAMMPGMCNI IDCMACCPCBH = 12;
    MJMGOBMOPDL BLPDBPHMCGA = 3;
    ItemList IIOMCJPCFML = 9;
    uint32 retcode = 4;
}

message RogueTournDeleteArchiveCsReq {
    uint32 NPHAJEKCBKF = 13;
}

message RogueTournDeleteArchiveScRsp {
    uint32 retcode = 2;
    uint32 NPHAJEKCBKF = 7;
}

message RogueTournDeleteBuildRefScRsp {
    repeated uint32 GGIGDJPFBBP = 6;
    uint32 retcode = 7;
}

message RogueTournEnablePermanentTalentCsReq {
    uint32 CKHCLKOALKE = 6;
}

message RogueTournEnablePermanentTalentScRsp {
    MDLPIFCHFPJ DPABCOHLPLH = 15;
    uint32 retcode = 12;
}

message RogueTournEnableSeasonTalentCsReq {
    uint32 CKHCLKOALKE = 15;
}

message RogueTournEnableSeasonTalentScRsp {
    uint32 retcode = 13;
    KGPIEEKIEME HANICMMHJGI = 2;
}

message RogueTournEnterCsReq {
}

message RogueTournEnterLayerCsReq {
    uint32 KHBLMAOPLLN = 3;
    uint32 BJHMFOAGMBF = 6;
}

message RogueTournEnterLayerScRsp {
    uint32 retcode = 7;
    JGAMMPGMCNI IDCMACCPCBH = 15;
}

message RogueTournEnterRogueCocoonSceneCsReq {
    repeated AvatarIdentifier avatar_list = 10;
    uint32 DCNNFJLABPL = 8;
    uint32 NBLMAGLGCGN = 2;
    uint32 difficulty = 6;
    uint32 HECCOBFBJFI = 12;
}

message RogueTournEnterRogueCocoonSceneScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 12;
    uint32 retcode = 5;
}

message RogueTournEnterRoomCsReq {
    uint32 KHBLMAOPLLN = 8;
    uint32 JOJCPKNIJOH = 14;
}

message RogueTournEnterRoomScRsp {
    uint32 retcode = 10;
    JGAMMPGMCNI IDCMACCPCBH = 5;
}

message RogueTournEnterScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 7;
    uint32 retcode = 11;
    PFLOIHLLMEE PHGJIJELKDB = 1;
}

message RogueTournExpNotify {
    uint32 exp = 12;
}

message RogueTournGetAllArchiveCsReq {
}

message RogueTournGetAllArchiveScRsp {
    repeated MJMGOBMOPDL MCGGPONOCKC = 4;
    uint32 retcode = 7;
}

message RogueTournGetAllBuildRefCsReq {
}

message RogueTournGetAllBuildRefScRsp {
    uint32 retcode = 9;
    repeated DIFGGDIHDEG GIOEPGJGMPD = 10;
}

message RogueTournGetArchiveRepositoryCsReq {
}

message RogueTournGetArchiveRepositoryScRsp {
    repeated uint32 BDNFDHJBAME = 14;
    repeated uint32 PBPIOEKJJPF = 5;
    uint32 retcode = 3;
}

message RogueTournGetCurRogueCocoonInfoCsReq {
}

message RogueTournGetCurRogueCocoonInfoScRsp {
    uint32 NBLMAGLGCGN = 12;
    uint32 retcode = 14;
    uint32 difficulty = 9;
    uint32 HECCOBFBJFI = 5;
    uint32 DCNNFJLABPL = 15;
}

message RogueTournGetMiscRealTimeDataCsReq {
}

message RogueTournGetMiscRealTimeDataScRsp {
    FBBOKKLGKGL BNLLEJPCIGD = 15;
    JGMDJIENFFH CPOLAHJPGFE = 9;
    DCDMPLJNBJC AOGOHOCFFNE = 10;
    BJLNEBBMMOE AOMHPLHONJA = 3;
    uint32 retcode = 11;
    GKHFFKMFMEN JJLFKNPEPFP = 12;
}

message RogueTournGetPermanentTalentInfoCsReq {
}

message RogueTournGetPermanentTalentInfoScRsp {
    uint32 retcode = 1;
    MDLPIFCHFPJ DPABCOHLPLH = 6;
}

message RogueTournGetSeasonTalentInfoCsReq {
}

message RogueTournGetSeasonTalentInfoScRsp {
    uint32 retcode = 12;
    KGPIEEKIEME HANICMMHJGI = 9;
}

message RogueTournGetSettleInfoCsReq {
    uint32 area_id = 10;
}

message RogueTournGetSettleInfoScRsp {
    uint32 retcode = 3;
    FAICNBKIELL BFLLJJBHLDF = 13;
}

message RogueTournHandBookNotify {
    ECMNFOEDOJC ODHGPLKCBBG = 4;
    DNCEOOPHIOK IOOACHNEHAH = 15;
    KCDBGKJANIH LFCDGLIEHAI = 10;
    KILGONODPIC OOOACLEFDGM = 14;
    MJBODJKDPPD ICNOEGEEPOF = 5;
    COOIDLLFFIJ CFNAKPADAEB = 1;
}

message RogueTournLeaveCsReq {
}

message RogueTournLeaveRogueCocoonSceneCsReq {
}

message RogueTournLeaveRogueCocoonSceneScRsp {
    uint32 retcode = 7;
    JGAMMPGMCNI IDCMACCPCBH = 6;
}

message RogueTournLeaveScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 10;
    uint32 retcode = 8;
}

message RogueTournLevelInfoUpdateScNotify {
    uint32 BJHMFOAGMBF = 10;
    FKNGOGLNKIG reason = 5;
    RogueTournLevelStatus status = 8;
    repeated IJNFOHJGPBC NNFFPJOLDHK = 14;
}

enum RogueTournLevelStatus {
    RogueTournLevelStatus_None = 0;
    RogueTournLevelStatus_Processing = 1;
    RogueTournLevelStatus_Finished = 2;
    RogueTournLevelStatus_Settled = 3;
}

message RogueTournPersonaRoomCardZoneUpdateScNotify {
    ODHJEDHKHOD NHNBJLLDOHO = 7;
}

message RogueTournQueryCsReq {
}

message RogueTournQueryScRsp {
    PFLOIHLLMEE PHGJIJELKDB = 6;
    uint32 retcode = 7;
    KIKEAJJLAMH LFLCDNGALME = 3;
}

message RogueTournReEnterRogueCocoonStageCsReq {
}

message RogueTournReEnterRogueCocoonStageScRsp {
    SceneBattleInfo battle_info = 1;
    uint32 retcode = 3;
}

message RogueTournRenameArchiveCsReq {
    uint32 NPHAJEKCBKF = 10;
    string name = 9;
}

message RogueTournRenameArchiveScRsp {
    uint32 NPHAJEKCBKF = 15;
    string name = 14;
    uint32 retcode = 9;
}

message RogueTournRenameBuildRefCsReq {
    string name = 7;
    uint32 NPHAJEKCBKF = 15;
}

message RogueTournRenameBuildRefScRsp {
    uint32 NPHAJEKCBKF = 13;
    string name = 7;
    uint32 retcode = 6;
}

message RogueTournResetPermanentTalentCsReq {
}

message RogueTournResetPermanentTalentScRsp {
    uint32 retcode = 1;
    MDLPIFCHFPJ DPABCOHLPLH = 8;
}

message RogueTournReviveAvatarCsReq {
    uint32 interacted_prop_entity_id = 8;
    repeated DKFJLHHDFKO avatar_list = 14;
}

message RogueTournReviveAvatarScRsp {
    uint32 retcode = 14;
    ItemCostData LNIEFKBMIPD = 4;
}

message RogueTournReviveCostUpdateScNotify {
    ItemCostData LNIEFKBMIPD = 3;
}

message RogueTournSaveBuildRefCsReq {
    string name = 13;
    uint32 NPHAJEKCBKF = 12;
    OOLJJHMLHBH MPOEFPFPEND = 9;
}

message RogueTournSaveBuildRefScRsp {
    string name = 15;
    uint32 retcode = 7;
    uint32 NPHAJEKCBKF = 4;
}

message RogueTournSettleCsReq {
}

message RogueTournSettleScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 1;
    uint32 retcode = 5;
    FAICNBKIELL BFLLJJBHLDF = 2;
}

message RogueTournStartCsReq {
    bool EJDMOENBHDP = 11;
    bool KENPENNAGLG = 5;
    repeated DKFJLHHDFKO avatar_list = 13;
    uint32 area_id = 3;
}

message RogueTournStartScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 4;
    uint32 retcode = 6;
    PFLOIHLLMEE PHGJIJELKDB = 9;
}

message RogueTournTakeExpRewardCsReq {
    uint32 FABMHMFNMDB = 12;
    repeated uint32 HBGAFAFFFAO = 14;
}

message RogueTournTakeExpRewardScRsp {
    uint32 retcode = 3;
    uint32 exp = 15;
    repeated uint32 FKDNANDJLGK = 8;
    ItemList reward = 9;
}

message RogueTournTitanUpdateTitanBlessProgressScNotify {
    uint32 PLJPIPDFAHA = 6;
}

message RogueTournUseSuperRewardKeyCsReq {
    uint32 cocoon_id = 10;
    uint32 count = 2;
    uint32 difficulty = 12;
}

message RogueTournUseSuperRewardKeyScRsp {
    ItemList drop_data = 8;
    LMDPKOELKFL ABEMLCJBIEF = 3;
    uint32 retcode = 15;
    ItemList reward = 5;
}

message RogueTournWeekChallengeUpdateScNotify {
    CJOCDGGCPCN BFNHJIBDMOA = 12;
}
