syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdRogueArcadeType {
    CmdRogueArcadeType_None = 0;
    CmdRogueArcadeType_RogueArcadeLeaveCsReq = 7692;
    CmdRogueArcadeType_RogueArcadeGetInfoCsReq = 7671;
    CmdRogueArcadeType_RogueArcadeRestartScRsp = 7670;
    CmdRogueArcadeType_RogueArcadeRestartCsReq = 7658;
    CmdRogueArcadeType_RogueArcadeGetInfoScRsp = 7657;
    CmdRogueArcadeType_RogueArcadeLeaveScRsp = 7672;
    CmdRogueArcadeType_RogueArcadeStartCsReq = 7694;
    CmdRogueArcadeType_RogueArcadeStartScRsp = 7675;
}

message GCPGBPNGOFF {
    FHEGNOPNICH JNKLNLKHGBB = 6;
    SceneInfo scene = 15;
    LineupInfo lineup = 2;
}

message RogueArcadeGetInfoCsReq {
}

message RogueArcadeGetInfoScRsp {
    uint32 retcode = 9;
    uint32 room_id = 3;
}

message RogueArcadeLeaveCsReq {
}

message RogueArcadeLeaveScRsp {
    GCPGBPNGOFF IDCMACCPCBH = 3;
    uint32 retcode = 4;
}

message RogueArcadeRestartCsReq {
}

message RogueArcadeRestartScRsp {
    uint32 retcode = 15;
    GCPGBPNGOFF IDCMACCPCBH = 13;
}

message RogueArcadeStartCsReq {
    uint32 room_id = 2;
    repeated uint32 NOEPBNMJFGL = 13;
}

message RogueArcadeStartScRsp {
    GCPGBPNGOFF IDCMACCPCBH = 7;
    uint32 room_id = 11;
    uint32 retcode = 14;
}
