syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BOPOBHGDIKN {
    uint32 OBLCIENDLED = 10;
}

enum CmdRaidCollectionType {
    CmdRaidCollectionType_None = 0;
    CmdRaidCollectionType_RaidCollectionEnterNextRaidScRsp = 6949;
    CmdRaidCollectionType_RaidCollectionDataCsReq = 6945;
    CmdRaidCollectionType_RaidCollectionEnterNextRaidCsReq = 6953;
    CmdRaidCollectionType_RaidCollectionDataScRsp = 6955;
}

message RaidCollectionDataCsReq {
}

message RaidCollectionDataScRsp {
    uint32 retcode = 1;
    repeated BOPOBHGDIKN challenge_list = 2;
}

message RaidCollectionEnterNextRaidCsReq {
    uint32 raid_id = 15;
    repeated uint32 avatar_list = 1;
    uint32 is_save = 5;
    uint32 world_level = 4;
}

message RaidCollectionEnterNextRaidScRsp {
    GEGLJDELBHA scene = 13;
    uint32 retcode = 8;
}
