syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdRedDotType {
    CmdRedDotType_None = 0;
    CmdRedDotType_GetAllRedDotDataScRsp = 5929;
    CmdRedDotType_UpdateRedDotDataCsReq = 5944;
    CmdRedDotType_GetSingleRedDotParamGroupScRsp = 5922;
    CmdRedDotType_GetSingleRedDotParamGroupCsReq = 5908;
    CmdRedDotType_UpdateRedDotDataScRsp = 5924;
    CmdRedDotType_GetAllRedDotDataCsReq = 5936;
}

message FHNAEJBKINH {
    repeated uint32 KCNPFIGHDAL = 8;
}

message GFOAMKNHBFE {
    map<uint32, FHNAEJBKINH> BANBCCBOEBJ = 8;
    uint32 FDEAKDCDGML = 10;
    uint32 panel_id = 1;
}

message GetAllRedDotDataCsReq {
}

message GetAllRedDotDataScRsp {
    repeated GFOAMKNHBFE KGONOBEAGAI = 3;
    uint32 retcode = 1;
}
