syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CILKBJMGNGL {
    repeated ONMFMINNBEB GJGFCCKEMFD = 1;
    repeated LGFOKKPICEH HIILDALHIMD = 9;
    GNPFDBACMIH story_info = 8;
    repeated uint32 OBBKBNDGOAI = 10;
    DFGAIOOGPPA IHJKLHGMKBI = 11;
    repeated NMOMMMGHMOA JJIEDDMALPE = 5;
    repeated IFCNLKPPPHK DANNIDIPFAL = 14;
}

enum CmdRogueMagicType {
    CmdRogueMagicType_CmdRogueMagicNone = 0;
    CmdRogueMagicType_RogueMagicBattleFailSettleInfoScNotify = 7748;
    CmdRogueMagicType_RogueMagicEnterLayerCsReq = 7772;
    CmdRogueMagicType_RogueMagicEnableTalentScRsp = 7758;
    CmdRogueMagicType_RogueMagicStartScRsp = 7782;
    CmdRogueMagicType_RogueMagicEnterCsReq = 7779;
    CmdRogueMagicType_RogueMagicScepterDressInUnitCsReq = 7757;
    CmdRogueMagicType_RogueMagicAreaUpdateScNotify = 7771;
    CmdRogueMagicType_RogueMagicEnterRoomScRsp = 7799;
    CmdRogueMagicType_RogueMagicScepterTakeOffUnitCsReq = 7766;
    CmdRogueMagicType_RogueMagicScepterDressInUnitScRsp = 7746;
    CmdRogueMagicType_RogueMagicLeaveCsReq = 7756;
    CmdRogueMagicType_RogueMagicEnterRoomCsReq = 7773;
    CmdRogueMagicType_RogueMagicEnterScRsp = 7739;
    CmdRogueMagicType_RogueMagicReviveAvatarScRsp = 7764;
    CmdRogueMagicType_RogueMagicLeaveScRsp = 7791;
    CmdRogueMagicType_RogueMagicGetMiscRealTimeDataScRsp = 7783;
    CmdRogueMagicType_RogueMagicSetAutoDressInMagicUnitCsReq = 7721;
    CmdRogueMagicType_RogueMagicQueryCsReq = 7781;
    CmdRogueMagicType_RogueMagicSettleCsReq = 7798;
    CmdRogueMagicType_RogueMagicSetAutoDressInMagicUnitScRsp = 7743;
    CmdRogueMagicType_RogueMagicStartCsReq = 7734;
    CmdRogueMagicType_RogueMagicAutoDressInMagicUnitChangeScNotify = 7730;
    CmdRogueMagicType_RogueMagicReviveAvatarCsReq = 7715;
    CmdRogueMagicType_RogueMagicAutoDressInUnitScRsp = 7775;
    CmdRogueMagicType_RogueMagicEnableTalentCsReq = 7708;
    CmdRogueMagicType_RogueMagicSettleScRsp = 7726;
    CmdRogueMagicType_RogueMagicQueryScRsp = 7741;
    CmdRogueMagicType_RogueMagicGetMiscRealTimeDataCsReq = 7740;
    CmdRogueMagicType_RogueMagicUnitComposeCsReq = 7724;
    CmdRogueMagicType_RogueMagicReviveCostUpdateScNotify = 7788;
    CmdRogueMagicType_RogueMagicEnterLayerScRsp = 7765;
    CmdRogueMagicType_RogueMagicLevelInfoUpdateScNotify = 7780;
    CmdRogueMagicType_RogueMagicStoryInfoUpdateScNotify = 7702;
    CmdRogueMagicType_RogueMagicUnitComposeScRsp = 7714;
    CmdRogueMagicType_RogueMagicAutoDressInUnitCsReq = 7755;
    CmdRogueMagicType_RogueMagicScepterTakeOffUnitScRsp = 7709;
}

message DFGAIOOGPPA {
    FDBDLBAPDBE JCOBJAMPOAL = 7;
    uint32 IMLHHAKIKCD = 10;
}

message EEILAINOLPO {
    FHEGNOPNICH JNKLNLKHGBB = 10;
    SceneInfo scene = 15;
    LineupInfo lineup = 9;
}

message EJHDAJAGFIJ {
    uint32 AEAHOGPJKEF = 14;
    bool DOFNEAPHMKH = 4;
}

message FKFOIDMNDFG {
    EJHDAJAGFIJ KDDGKLNGNEA = 2;
    NOAKCDKAAFB BNLLEJPCIGD = 5;
    GCBCKOKEAJH PHGJIJELKDB = 3;
}

message FODHGNLPBKH {
    uint32 EEPIDJJJMAH = 15;
    HOIFDJPBGLB status = 2;
    uint32 GHEHGIOAGDG = 9;
    uint32 room_id = 13;
}

message FPNDOBPMNED {
    repeated uint32 KEHKLHMEABI = 14;
}

message GCBCKOKEAJH {
    NHLBNBBDHMI miracle = 6;
    FPNDOBPMNED MEEJDFNHBDI = 2;
    JEIKFFFGONB lineup = 14;
    CBOLONJDHHL basic_info = 3;
    FKEDPCMLIFE item_value = 1;
    KDHAIFIOKDN level = 5;
    PLBAMNCLBHB DDLADFJMEEC = 13;
}

message GKMOAKPLBHO {
    uint32 LPOLPDBELON = 10;
    uint32 dice_slot_id = 13;
    uint32 GCAHKLNGFCK = 9;
}

message GNPFDBACMIH {
    repeated uint32 NOMDDGGIIBF = 5;
}

message GPEPGKCPBPB {
    uint32 MDAIAMFJNHM = 11;
    repeated FODHGNLPBKH JEHEILKKDEF = 9;
    uint32 JOJCPKNIJOH = 8;
    uint32 layer_index = 6;
    JGNAEPIJDNC status = 7;
}

message GPHMAJPGGEK {
    repeated OCBPJLLLJGO EBFHIDKDJOB = 6;
    repeated OKCCLEEPELM IHKCHDJEJGJ = 15;
}

enum HOIFDJPBGLB {
    HOIFDJPBGLB_NLCDGIPGFDJ = 0;
    HOIFDJPBGLB_JHHAJDKPLJH = 1;
    HOIFDJPBGLB_LOOAKNHDBLL = 2;
    HOIFDJPBGLB_CIHFGJDCHIA = 3;
}

message IFCNLKPPPHK {
    repeated uint32 PBJLMCGIBND = 3;
    bool is_taken_reward = 10;
    NJMOAGDJKFH record_info = 1;
    PGGMPDIMLAE COEBCNGCNOO = 11;
    bool is_unlock = 4;
    uint32 area_id = 12;
    bool FJKHIFDJMDB = 14;
}

enum JAMINGBJHBK {
    JAMINGBJHBK_NLCDGIPGFDJ = 0;
    JAMINGBJHBK_EHNIPLNEEDI = 1;
    JAMINGBJHBK_PMKMEAAGKAP = 2;
    JAMINGBJHBK_MNBAGHPEFBC = 3;
}

enum JGNAEPIJDNC {
    JGNAEPIJDNC_NLCDGIPGFDJ = 0;
    JGNAEPIJDNC_LOOAKNHDBLL = 1;
    JGNAEPIJDNC_CIHFGJDCHIA = 2;
}

message KDHAIFIOKDN {
    JAMINGBJHBK reason = 15;
    repeated GPEPGKCPBPB NNFFPJOLDHK = 14;
    uint32 JDPHADIIAPE = 9;
    uint32 BJHMFOAGMBF = 10;
    uint32 JJLEDNENPJK = 1;
    PFKHKAMBHBN status = 2;
}

message NJMOAGDJKFH {
    repeated uint32 avatar_id_list = 1789;
    repeated uint32 BGAFHIOEHFH = 784;
    uint32 NNNCEIGNIIA = 5;
    repeated DNLKMHLAPHC MALDOMHPILM = 1102;
    repeated MMBBHFNJILI HIILDALHIMD = 1964;
    uint32 EJJGHJMCFPH = 9;
    uint32 MEDAAELFEMN = 3;
    uint32 JJLEDNENPJK = 11;
    uint32 ADIFLCNAABJ = 15;
    uint32 NBMNPGKEIIH = 13;
    uint32 LKHAIEIDAJL = 8;
    uint32 MHPCIABALPI = 10;
    uint32 GEJEANJFCMI = 7;
}

message NMOMMMGHMOA {
    uint32 DFBDPEHAAMG = 14;
    bool is_unlock = 4;
}

message NOAKCDKAAFB {
    uint32 ADMJAHDJDDJ = 8;
    bool DOFNEAPHMKH = 15;
}

enum PFKHKAMBHBN {
    PFKHKAMBHBN_NLCDGIPGFDJ = 0;
    PFKHKAMBHBN_LOOAKNHDBLL = 1;
    PFKHKAMBHBN_CCKPNCIBDGP = 2;
    PFKHKAMBHBN_JKNPMIMBGML = 3;
}

message PGGMPDIMLAE {
    repeated uint32 ILNFEABHHCH = 873;
}

message PLBAMNCLBHB {
    uint32 NBMNPGKEIIH = 9;
    repeated DNLKMHLAPHC MALDOMHPILM = 3;
    repeated MMBBHFNJILI HIILDALHIMD = 15;
    bool HIKMFMJCNKP = 10;
}

message RogueMagicAreaUpdateScNotify {
    repeated IFCNLKPPPHK DANNIDIPFAL = 11;
}

message RogueMagicAutoDressInMagicUnitChangeScNotify {
    bool GBEMCAHPBKP = 7;
}

message RogueMagicBattleFailSettleInfoScNotify {
    EEILAINOLPO IDCMACCPCBH = 10;
    FKFOIDMNDFG BFLLJJBHLDF = 12;
}

message RogueMagicEnableTalentCsReq {
    uint32 CKHCLKOALKE = 13;
}

message RogueMagicEnableTalentScRsp {
    uint32 retcode = 9;
    DFGAIOOGPPA IHJKLHGMKBI = 14;
}

message RogueMagicEnterCsReq {
}

message RogueMagicEnterLayerCsReq {
    uint32 BJHMFOAGMBF = 4;
    uint32 KHBLMAOPLLN = 11;
}

message RogueMagicEnterLayerScRsp {
    EEILAINOLPO IDCMACCPCBH = 8;
    uint32 retcode = 2;
}

message RogueMagicEnterRoomCsReq {
    uint32 KHBLMAOPLLN = 4;
    uint32 JOJCPKNIJOH = 10;
}

message RogueMagicEnterRoomScRsp {
    EEILAINOLPO IDCMACCPCBH = 9;
    uint32 retcode = 2;
}

message RogueMagicEnterScRsp {
    uint32 retcode = 8;
    GCBCKOKEAJH PHGJIJELKDB = 9;
    EEILAINOLPO IDCMACCPCBH = 6;
}

message RogueMagicGetMiscRealTimeDataCsReq {
}

message RogueMagicGetMiscRealTimeDataScRsp {
    EJHDAJAGFIJ KDDGKLNGNEA = 13;
    uint32 retcode = 15;
    NOAKCDKAAFB BNLLEJPCIGD = 4;
}

message RogueMagicLeaveCsReq {
}

message RogueMagicLeaveScRsp {
    uint32 retcode = 5;
    EEILAINOLPO IDCMACCPCBH = 2;
}

message RogueMagicLevelInfoUpdateScNotify {
    uint32 BJHMFOAGMBF = 12;
    uint32 JJLEDNENPJK = 15;
    uint32 JDPHADIIAPE = 1;
    JAMINGBJHBK reason = 9;
    repeated GPEPGKCPBPB NNFFPJOLDHK = 5;
    PFKHKAMBHBN status = 14;
}

message RogueMagicQueryCsReq {
}

message RogueMagicQueryScRsp {
    CILKBJMGNGL LFLCDNGALME = 13;
    uint32 retcode = 5;
    GCBCKOKEAJH PHGJIJELKDB = 4;
}

message RogueMagicReviveAvatarCsReq {
    uint32 interacted_prop_entity_id = 7;
    repeated uint32 NOEPBNMJFGL = 6;
}

message RogueMagicReviveAvatarScRsp {
    ItemCostData LNIEFKBMIPD = 14;
    uint32 retcode = 8;
}

message RogueMagicReviveCostUpdateScNotify {
    ItemCostData LNIEFKBMIPD = 15;
}

message RogueMagicSetAutoDressInMagicUnitCsReq {
    bool GBEMCAHPBKP = 2;
}

message RogueMagicSetAutoDressInMagicUnitScRsp {
    uint32 retcode = 11;
    bool GBEMCAHPBKP = 4;
}

message RogueMagicSettleCsReq {
}

message RogueMagicSettleScRsp {
    ItemList IIOMCJPCFML = 10;
    EEILAINOLPO IDCMACCPCBH = 4;
    FKFOIDMNDFG BFLLJJBHLDF = 14;
    GPHMAJPGGEK IEHPMHOFBNJ = 6;
    uint32 retcode = 7;
}

message RogueMagicStartCsReq {
    uint32 area_id = 14;
    uint32 IEOFONJHFDJ = 11;
    repeated uint32 NOEPBNMJFGL = 3;
    repeated uint32 OCEGEKKFLAL = 15;
}

message RogueMagicStartScRsp {
    uint32 retcode = 1;
    EEILAINOLPO IDCMACCPCBH = 2;
    GCBCKOKEAJH PHGJIJELKDB = 12;
}

message RogueMagicStoryInfoUpdateScNotify {
    uint32 BNHAIKILAJK = 4;
}

message RogueMagicUnitComposeScRsp {
    uint32 retcode = 14;
}
