syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AKEKCKDIHLA {
    int32 new_value = 10;
    int32 old_value = 8;
    string property_name = 1;
}

message ActiveFarmElementCsReq {
    uint32 world_level = 10;
    uint32 HECCOBFBJFI = 14;
    uint32 entity_id = 6;
}

message ChangePropTimelineInfoCsReq {
    uint64 interact_id = 15;
    bool is_close_map = 12;
    PropTimelineInfo timeline_info = 14;
    uint32 prop_entity_id = 4;
    uint64 uuid = 1;
}

message ChangePropTimelineInfoScRsp {
    uint32 prop_entity_id = 7;
    uint32 retcode = 14;
}

message ChestInfo {
    uint32 opened_num = 1;
    uint32 exist_num = 12;
    ChestType chest_type = 6;
}

message ChestMonsterStat {
    uint32 PIJBPDPEODG = 2;
    uint32 type = 4;
    uint32 JBGIFBGMLMF = 9;
}

enum ChestType {
    MAP_INFO_CHEST_TYPE_NONE = 0;
    MAP_INFO_CHEST_TYPE_NORMAL = 101;
    MAP_INFO_CHEST_TYPE_CHALLENGE = 102;
    MAP_INFO_CHEST_TYPE_PUZZLE = 104;
}

enum CmdSceneType {
    CmdSceneType_None = 0;
    CmdSceneType_RefreshTriggerByClientCsReq = 1497;
    CmdSceneType_DeactivateFarmElementScRsp = 1430;
    CmdSceneType_ActivateFarmElementScRsp = 1489;
    CmdSceneType_RecoverAllLineupScRsp = 1401;
    CmdSceneType_SetGroupCustomSaveDataScRsp = 1474;
    CmdSceneType_InteractPropScRsp = 1439;
    CmdSceneType_StartCocoonStageScRsp = 1421;
    CmdSceneType_UpdateFloorSavedValueNotify = 1452;
    CmdSceneType_UpdateGroupPropertyCsReq = 1422;
    CmdSceneType_GroupStateChangeCsReq = 1453;
    CmdSceneType_DeactivateFarmElementCsReq = 1402;
    CmdSceneType_ReEnterLastElementStageCsReq = 1485;
    CmdSceneType_EnterSceneScRsp = 1496;
    CmdSceneType_SpringRefreshScRsp = 1488;
    CmdSceneType_EnteredSceneChangeScNotify = 1451;
    CmdSceneType_ChangePropTimelineInfoCsReq = 1473;
    CmdSceneType_SceneEntityTeleportScRsp = 1492;
    CmdSceneType_SceneEntityTeleportCsReq = 1416;
    CmdSceneType_SetClientPausedCsReq = 1483;
    CmdSceneType_ChestGroupPropertyRewardScNotify = 1424;
    CmdSceneType_GetUnlockTeleportScRsp = 1436;
    CmdSceneType_GetCurSceneInfoCsReq = 1498;
    CmdSceneType_SceneCastSkillCostMpScRsp = 1404;
    CmdSceneType_ChangePropTimelineInfoScRsp = 1499;
    CmdSceneType_SetTrainWorldIdScRsp = 1467;
    CmdSceneType_GameplayCounterCountDownScRsp = 1442;
    CmdSceneType_DeleteSummonUnitScRsp = 1429;
    CmdSceneType_SavePointsInfoNotify = 1408;
    CmdSceneType_LastSpringRefreshTimeNotify = 1415;
    CmdSceneType_SceneCastSkillCostMpCsReq = 1471;
    CmdSceneType_GameplayCounterRecoverCsReq = 1450;
    CmdSceneType_SpringRefreshCsReq = 1448;
    CmdSceneType_RefreshTriggerByClientScRsp = 1495;
    CmdSceneType_SceneCastSkillCsReq = 1456;
    CmdSceneType_OpenChestScNotify = 1407;
    CmdSceneType_SceneEntityMoveScRsp = 1482;
    CmdSceneType_DeleteSummonUnitCsReq = 1461;
    CmdSceneType_SceneEntityMoveCsReq = 1434;
    CmdSceneType_SceneGroupRefreshScNotify = 1418;
    CmdSceneType_SceneReviveAfterRebattleScRsp = 1446;
    CmdSceneType_RefreshTriggerByClientScNotify = 1410;
    CmdSceneType_EnterSceneByServerScNotify = 1494;
    CmdSceneType_SceneEntityMoveScNotify = 1472;
    CmdSceneType_RecoverAllLineupCsReq = 1444;
    CmdSceneType_EnterSceneCsReq = 1486;
    CmdSceneType_ScenePlaneEventScNotify = 1427;
    CmdSceneType_GetEnteredSceneScRsp = 1431;
    CmdSceneType_EnterSectionScRsp = 1409;
    CmdSceneType_GetEnteredSceneCsReq = 1412;
    CmdSceneType_SceneReviveAfterRebattleCsReq = 1457;
    CmdSceneType_ActivateFarmElementCsReq = 1460;
    CmdSceneType_SceneCastSkillMpUpdateScNotify = 1462;
    CmdSceneType_GameplayCounterRecoverScRsp = 1445;
    CmdSceneType_GetCurSceneInfoScRsp = 1426;
    CmdSceneType_GameplayCounterUpdateScNotify = 1484;
    CmdSceneType_SceneEnterStageCsReq = 1441;
    CmdSceneType_UpdateGroupPropertyScRsp = 1490;
    CmdSceneType_GroupStateChangeScRsp = 1500;
    CmdSceneType_GameplayCounterCountDownCsReq = 1437;
    CmdSceneType_TrainWorldIdChangeScNotify = 1406;
    CmdSceneType_SetClientPausedScRsp = 1455;
    CmdSceneType_ReturnLastTownScRsp = 1481;
    CmdSceneType_StartCocoonStageCsReq = 1458;
    CmdSceneType_SceneEnterStageScRsp = 1438;
    CmdSceneType_EnterSectionCsReq = 1466;
    CmdSceneType_GetUnlockTeleportCsReq = 1413;
    CmdSceneType_SetTrainWorldIdCsReq = 1403;
    CmdSceneType_SyncServerSceneChangeNotify = 1476;
    CmdSceneType_InteractPropCsReq = 1479;
    CmdSceneType_UnlockTeleportNotify = 1432;
    CmdSceneType_GetSceneMapInfoCsReq = 1454;
    CmdSceneType_SceneCastSkillScRsp = 1491;
    CmdSceneType_ReEnterLastElementStageScRsp = 1425;
    CmdSceneType_SceneUpdatePositionVersionNotify = 1465;
    CmdSceneType_ReturnLastTownCsReq = 1464;
    CmdSceneType_GetSceneMapInfoScRsp = 1459;
    CmdSceneType_SetGroupCustomSaveDataCsReq = 1433;
    CmdSceneType_SyncEntityBuffChangeListScNotify = 1480;
}

message CounterDownCsReq {
    uint32 DGGCFDKJDPO = 6;
    uint32 BIKALOGMMDA = 10;
}

message DeactivateFarmElementCsReq {
    uint32 entity_id = 15;
}

message DeactivateFarmElementScRsp {
    uint32 retcode = 5;
    uint32 entity_id = 10;
}

message DeleteSummonUnitCsReq {
    repeated uint32 entity_id_list = 11;
    uint64 interact_id = 5;
}

message DeleteSummonUnitScRsp {
    uint32 retcode = 14;
    repeated uint32 entity_id_list = 15;
}

message DynamicValues {
    float value = 15;
    string key = 9;
}

message EBADAHNBIIH {
    uint32 BIKALOGMMDA = 2;
    uint32 GPJBPKILOBM = 12;
}

message EnterSceneByServerScNotify {
    EnterSceneReason reason = 8;
    SceneInfo scene = 5;
    LineupInfo lineup = 15;
}

message EnterSceneCsReq {
    uint32 entry_id = 11;
    uint64 interact_id = 14;
    uint32 teleport_id = 5;
    bool is_close_map = 10;
    Vector IDABOKLJOLG = 8;
    bool FBPKOFOIOLC = 13;
    SceneIdentifier scene_identifier = 2;
}

enum EnterSceneReason {
    ENTER_SCENE_REASON_NONE = 0;
    ENTER_SCENE_REASON_CHALLENGE_TIMEOUT = 1;
    ENTER_SCENE_REASON_ROGUE_TIMEOUT = 2;
    ENTER_SCENE_REASON_CHANGE_STORYLINE = 3;
    ENTER_SCENE_REASON_DIMENSION_MERGE = 4;
}

message EnterSceneScRsp {
    bool is_close_map = 6;
    bool is_over_map = 10;
    uint32 retcode = 3;
    SceneIdentifier scene_identifier = 2;
}

message EnterSectionCsReq {
    uint64 interact_id = 14;
    uint32 section_id = 7;
}

message EnteredSceneChangeScNotify {
    repeated EnteredSceneInfo entered_scene_info_list = 5;
}

message EnteredSceneInfo {
    uint32 plane_id = 4;
    uint32 floor_id = 7;
}

message EntityBuffChangeInfo {
    SceneEntityBuffChangeType reason = 1;
    BuffInfo buff_change_info = 6;
    uint32 remove_buff_id = 4;
    uint32 entity_id = 9;
    uint32 cast_entity_id = 11;
}

message EntityMotion {
    uint32 map_layer = 10;
    bool FJOEOEDLNED = 13;
    MotionInfo motion = 5;
    uint32 entity_id = 3;
}

message FDGOBNJPKJG {
    uint32 PLNEOOCPFNI = 3;
}

message GetCurSceneInfoCsReq {
}

message GetCurSceneInfoScRsp {
    uint32 retcode = 15;
    SceneInfo scene = 2;
}

message GetEnteredSceneCsReq {
}

message GetEnteredSceneScRsp {
    uint32 retcode = 6;
    repeated EnteredSceneInfo entered_scene_info_list = 12;
}

message GetSceneMapInfoCsReq {
    repeated SceneIdentifier scene_identifiers = 15;
}

message GetSceneMapInfoScRsp {
    uint32 retcode = 15;
    repeated SceneMapInfo scene_map_info = 3;
}

message GetUnlockTeleportCsReq {
    repeated uint32 entry_id_list = 10;
}

message GetUnlockTeleportScRsp {
    repeated uint32 unlocked_teleport_list = 10;
    uint32 retcode = 1;
}

message GroupRefreshInfo {
    repeated SceneEntityRefreshInfo refresh_entity = 6;
    SceneGroupRefreshType refresh_type = 8;
    SceneEntityGroupInfo group_info = 7;
    uint32 state = 11;
    repeated AKEKCKDIHLA CDMKBCHLPAB = 2;
    uint32 group_id = 9;
}

message GroupStateChangeCsReq {
    GroupStateInfo group_state_info = 4;
    uint64 interact_id = 2;
}

message GroupStateChangeScRsp {
    uint32 retcode = 6;
    GroupStateInfo group_state_info = 1;
}

message GroupStateInfo {
    uint32 GMEHAMCHJBK = 10;
    uint32 group_id = 8;
    uint32 entry_id = 4;
    uint32 group_state = 15;
}

message HitMonsterBattleInfo {
    MonsterBattleType monster_battle_type = 8;
    uint32 target_monster_entity_id = 6;
}

message InteractPropCsReq {
    uint32 prop_entity_id = 11;
    uint32 interact_id2 = 12;
    uint64 interact_id = 14;
}

message InteractPropScRsp {
    uint32 prop_state = 3;
    uint32 prop_entity_id = 4;
    uint32 retcode = 2;
}

message MazeGroup {
    int64 modify_time = 2;
    bool is_need_refresh = 14;
    repeated uint32 destory_monster_config_id_list = 7;
    uint32 group_id = 11;
    map<string, int32> property_map = 6;
}

message MazePropState {
    uint32 state = 4;
    uint32 config_id = 10;
    PropExtraInfo extra_info = 13;
    uint32 group_id = 1;
}

enum MonsterBattleType {
    MONSTER_BATTLE_TYPE_NONE = 0;
    MONSTER_BATTLE_TYPE_TRIGGER_BATTLE = 1;
    MONSTER_BATTLE_TYPE_DIRECT_DIE_SIMULATE_BATTLE = 2;
    MONSTER_BATTLE_TYPE_DIRECT_DIE_SKIP_BATTLE = 3;
    MONSTER_BATTLE_TYPE_NO_BATTLE = 4;
}

message OpenChestScNotify {
    uint32 chest_id = 6;
}

message PDHBDPNPMPI {
}

message ReEnterLastElementStageCsReq {
    uint32 stage_id = 8;
}

message ReEnterLastElementStageScRsp {
    SceneBattleInfo battle_info = 8;
    uint32 stage_id = 10;
    uint32 retcode = 12;
}

message RefreshTriggerByClientCsReq {
    MotionInfo trigger_motion = 6;
    repeated uint32 trigger_target_id_list = 10;
    string trigger_name = 11;
    uint64 interact_id = 9;
    uint32 trigger_entity_id = 15;
}

message RefreshTriggerByClientScNotify {
    repeated uint32 trigger_target_id_list = 10;
    string trigger_name = 3;
    uint32 trigger_entity_id = 2;
}

message RefreshTriggerByClientScRsp {
    uint32 trigger_entity_id = 13;
    string trigger_name = 14;
    uint32 retcode = 10;
    bool refresh_trigger = 1;
}

message SavePointsInfoNotify {
    int64 refresh_time = 6;
    uint32 valid_times = 9;
}

message SceneCastSkillCostMpCsReq {
    uint32 skill_index = 7;
    uint32 attacked_by_entity_id = 13;
    uint32 cast_entity_id = 4;
}

message SceneCastSkillCostMpScRsp {
    uint32 retcode = 10;
    uint32 cast_entity_id = 13;
}

message SceneCastSkillCsReq {
    repeated uint32 hit_target_entity_id_list = 11;
    repeated uint32 assist_monster_entity_id_list = 8;
    repeated AssistMonsterEntityInfo assist_monster_entity_info = 6;
    MotionInfo target_motion = 14;
    string maze_ability_str = 5;
    uint32 KCFABNFPOPN = 10;
    uint32 skill_index = 15;
    uint32 attacked_by_entity_id = 1;
    repeated DynamicValues dynamic_values = 12;
    repeated SkillExtraTag skill_extra_tags = 4;
    uint32 cast_entity_id = 7;
}

message SceneCastSkillMpUpdateScNotify {
    uint32 cast_entity_id = 15;
    uint32 mp = 11;
}

message SceneCastSkillScRsp {
    uint32 retcode = 2;
    SceneBattleInfo battle_info = 11;
    uint32 cast_entity_id = 5;
    repeated HitMonsterBattleInfo monster_battle_info = 10;
}

message SceneCheckpoingRefreshCsReq {
    uint32 floor_id = 12;
    uint32 plane_id = 15;
    uint32 prop_entity_id = 2;
}

message SceneEnterStageCsReq {
    RebattleType NKDAAAGPCDB = 15;
    uint32 event_id = 12;
}

message SceneEnterStageScRsp {
    uint32 retcode = 9;
    SceneBattleInfo battle_info = 3;
}

enum SceneEntityBuffChangeType {
    SCENE_ENTITY_BUFF_CHANGE_TYPE_DEFAULT = 0;
    SCENE_ENTITY_BUFF_CHANGE_TYPE_ADD_MAZEBUFF = 1;
    SCENE_ENTITY_BUFF_CHANGE_TYPE_ADD_ADV_MODIFIER = 2;
}

message SceneEntityMoveCsReq {
    uint32 entry_id = 10;
    repeated EntityMotion entity_motion_list = 2;
    uint64 interact_id = 12;
}

message SceneEntityMoveScNotify {
    MotionInfo motion = 13;
    uint32 entity_id = 5;
    uint32 entry_id = 14;
    uint32 client_pos_version = 15;
}

message SceneEntityMoveScRsp {
    repeated EntityMotion entity_motion_list = 10;
    uint32 retcode = 4;
}

message SceneEntityRefreshInfo {
    SceneEntityInfo add_entity = 9;
    uint32 delete_entity = 13;
    uint32 BEEANADAHPL = 10;
}

message SceneEntityTeleportCsReq {
    EntityMotion entity_motion = 2;
    uint64 interact_id = 6;
    uint32 entry_id = 12;
}

message SceneEntityTeleportScRsp {
    uint32 retcode = 2;
    uint32 client_pos_version = 10;
    EntityMotion entity_motion = 14;
}

message SceneGroupRefreshScNotify {
    uint32 floor_id = 2;
    repeated GroupRefreshInfo group_refresh_list = 10;
    uint32 dimension_id = 12;
}

enum SceneGroupRefreshType {
    SCENE_GROUP_REFRESH_TYPE_NONE = 0;
    SCENE_GROUP_REFRESH_TYPE_LOADED = 1;
    SCENE_GROUP_REFRESH_TYPE_UNLOAD = 2;
    SCENE_GROUP_REFRESH_TYPE_AFIBFMAFNCC = 3;
}

message SceneMapInfo {
    repeated uint32 finished_chest_monster_id_list = 1317;
    repeated uint32 unlock_teleport_list = 13;
    uint32 retcode = 6;
    repeated MazePropState maze_prop_list = 10;
    SceneIdentifier scene_identifier = 1571;
    uint32 cur_map_entry_id = 14;
    MissionStatusBySceneInfo client_group_mission_info = 427;
    repeated uint32 lighten_section_list = 12;
    uint32 dimension_id = 3;
    repeated MazeGroup maze_group_list = 4;
    repeated ChestMonsterStat chest_monster_list = 7;
    repeated ChestInfo chest_list = 9;
    uint32 floor_id = 15;
    uint32 entry_id = 8;
    map<string, int32> floor_saved_value_map = 11;
    repeated uint32 opened_chest_id_list = 944;
}

message ScenePlaneEventScNotify {
    ItemList DMNKFILNCGB = 13;
    ItemList JENLPPHNECF = 3;
    ItemList get_item_list = 10;
    ItemList ECCIHPNDEHM = 7;
}

message SceneReviveAfterRebattleCsReq {
    RebattleType NKDAAAGPCDB = 12;
}

message SceneReviveAfterRebattleScRsp {
    uint32 retcode = 11;
}

message SetClientPausedCsReq {
    bool paused = 9;
}

message SetClientPausedScRsp {
    uint32 retcode = 10;
    bool paused = 6;
}

message SetGroupCustomSaveDataCsReq {
    uint32 entry_id = 9;
    uint64 interact_id = 14;
    string save_data = 10;
    uint32 group_id = 6;
}

message SetGroupCustomSaveDataScRsp {
    uint32 retcode = 5;
    uint32 group_id = 8;
    uint32 entry_id = 4;
}

message SetTrainWorldIdCsReq {
    uint32 CFDCEEMIOCO = 2;
    uint64 interact_id = 7;
}

message SetTrainWorldIdScRsp {
    uint32 retcode = 10;
    uint32 CFDCEEMIOCO = 7;
}

enum SkillExtraTag {
    SCENE_CAST_SKILL_NONE = 0;
    SCENE_CAST_SKILL_PROJECTILE_HIT = 1;
    SCENE_CAST_SKILL_PROJECTILE_LIFETIME_FINISH = 2;
}

message StartCocoonStageCsReq {
    uint32 world_level = 8;
    uint32 HECCOBFBJFI = 12;
    uint32 wave = 4;
    uint32 cocoon_id = 14;
    uint32 prop_entity_id = 11;
    NAJKNJLJPEP CBJCKEIGGNL = 3;
}

message StartCocoonStageScRsp {
    SceneBattleInfo battle_info = 2;
    uint32 challenge_cnt = 11;
    uint32 cocoon_id = 7;
    uint32 wave = 5;
    uint32 retcode = 9;
    uint32 prop_entity_id = 4;
}

message SyncEntityBuffChangeListScNotify {
    repeated EntityBuffChangeInfo entity_buff_change_list = 8;
}

message SyncServerSceneChangeNotify {
}

message TrainWorldIdChangeScNotify {
    uint32 CFDCEEMIOCO = 5;
}

message UnlockTeleportNotify {
    uint32 teleport_id = 4;
    uint32 entry_id = 14;
}

message UpdateFloorSavedValueNotify {
    uint32 plane_id = 6;
    uint32 floor_id = 7;
    uint32 dimension_id = 9;
    map<string, int32> saved_value = 3;
}

message UpdateGroupPropertyCsReq {
    uint32 floor_id = 2;
    uint32 group_id = 14;
    string property_name = 13;
    uint64 interact_id = 6;
    int32 OLBEPIBLDBD = 4;
    uint32 dimension_id = 10;
}

message UpdateGroupPropertyScRsp {
    int32 new_value = 4;
    string property_name = 10;
    uint32 retcode = 13;
    uint32 floor_id = 7;
    uint32 dimension_id = 5;
    uint32 group_id = 8;
    int32 old_value = 1;
}
