syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CGFMDMPCKDN {
    uint32 item_id = 13;
}

enum CmdSpaceZooType {
    CmdSpaceZooType_None = 0;
    CmdSpaceZooType_SpaceZooDeleteCatScRsp = 6799;
    CmdSpaceZooType_SpaceZooMutateScRsp = 6791;
    CmdSpaceZooType_SpaceZooCatUpdateNotify = 6772;
    CmdSpaceZooType_SpaceZooBornCsReq = 6779;
    CmdSpaceZooType_SpaceZooExchangeItemCsReq = 6765;
    CmdSpaceZooType_SpaceZooDataCsReq = 6734;
    CmdSpaceZooType_SpaceZooDeleteCatCsReq = 6773;
    CmdSpaceZooType_SpaceZooOpCatteryScRsp = 6726;
    CmdSpaceZooType_SpaceZooDataScRsp = 6782;
    CmdSpaceZooType_SpaceZooOpCatteryCsReq = 6798;
    CmdSpaceZooType_SpaceZooTakeScRsp = 6704;
    CmdSpaceZooType_SpaceZooExchangeItemScRsp = 6780;
    CmdSpaceZooType_SpaceZooTakeCsReq = 6771;
    CmdSpaceZooType_SpaceZooMutateCsReq = 6756;
    CmdSpaceZooType_SpaceZooBornScRsp = 6739;
}

message DBLILHCLPPL {
    uint32 BBMELNJBGAL = 13;
    bool PKKAJKHKBMN = 12;
    repeated uint32 DLPCPDGEADG = 5;
    uint32 unique_id = 4;
    repeated uint32 item_list = 11;
    uint32 DNNCAGJIOAP = 15;
}

message GFFFJCEHBEB {
    uint32 HFLPDCJDIAC = 15;
    uint32 BBMELNJBGAL = 3;
}

message SpaceZooBornScRsp {
    DBLILHCLPPL DLMJNMIPDCO = 1;
    repeated GFFFJCEHBEB JKMIFNJEBJO = 4;
    bool HCGHLFAKIKI = 12;
    uint32 retcode = 15;
}

message SpaceZooCatUpdateNotify {
    bool HCGHLFAKIKI = 14;
    bool FHHCNGAGFCJ = 2;
    repeated DBLILHCLPPL HMAIHHCBFKP = 12;
}

message SpaceZooDataCsReq {
}

message SpaceZooDataScRsp {
    uint32 OAIMAFOHLHC = 3;
    repeated uint32 FIBMJBJMCKK = 14;
    repeated uint32 ENGEBGICPPB = 2;
    repeated uint32 GLMMHALPEAG = 13;
    repeated GFFFJCEHBEB JAPFGEAIACA = 9;
    repeated uint32 JGCNAGNOFBP = 11;
    repeated DBLILHCLPPL NFIGGHNNJAP = 5;
    uint32 retcode = 1;
    repeated uint32 MDFEBNNOKLG = 15;
}

message SpaceZooDeleteCatScRsp {
    repeated uint32 ANHNMANNAEP = 6;
    uint32 retcode = 1;
}

message SpaceZooMutateScRsp {
    repeated GFFFJCEHBEB JKMIFNJEBJO = 3;
    uint32 retcode = 1;
    bool HCGHLFAKIKI = 5;
    DBLILHCLPPL KIIPGCDJPBO = 2;
}

message SpaceZooOpCatteryCsReq {
    uint32 OCKGDJCGKLH = 8;
    uint32 op_type = 2;
    uint32 FEPDLPHPHGI = 15;
}

message SpaceZooOpCatteryScRsp {
    uint32 retcode = 15;
    repeated uint32 MDFEBNNOKLG = 9;
}

message SpaceZooTakeCsReq {
    uint32 KIFKGLGCLEJ = 3;
}

message SpaceZooTakeScRsp {
    uint32 retcode = 4;
    uint32 KIFKGLGCLEJ = 15;
    ItemList reward = 9;
}
