syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AKFBNFPFKJJ {
}

message BCPMPHNADMN {
    repeated uint32 PGBJIJPACCE = 8;
    uint32 LMEDKDNNNKL = 3;
    uint32 GMANNHPPFPK = 12;
}

enum BHJOFLJGNKN {
    BHJOFLJGNKN_NLCDGIPGFDJ = 0;
    BHJOFLJGNKN_LENEGHPPELE = 1;
    BHJOFLJGNKN_LIDKLOCCDGI = 2;
    BHJOFLJGNKN_action = 3;
    BHJOFLJGNKN_OFPLODJBGMG = 4;
    BHJOFLJGNKN_DDGDJCKKHPH = 5;
    BHJOFLJGNKN_DDBIJDILDJL = 6;
    BHJOFLJGNKN_NCLBFAALLFJ = 7;
}

message BJKPJIBNPHC {
    uint32 DCPDNBALDOA = 14;
    EJCBOKGJFHE EGBFNFCEPHD = 4;
    uint32 HFNNNGHBHGG = 3;
}

message BLJHLKBNGEC {
}

enum CmdSwordTrainingType {
    CmdSwordTrainingType_None = 0;
    CmdSwordTrainingType_SwordTrainingResumeGameCsReq = 7465;
    CmdSwordTrainingType_GetSwordTrainingDataScRsp = 7494;
    CmdSwordTrainingType_SwordTrainingStoryConfirmScRsp = 7454;
    CmdSwordTrainingType_SwordTrainingStoryConfirmCsReq = 7475;
    CmdSwordTrainingType_SwordTrainingUnlockSyncScNotify = 7499;
    CmdSwordTrainingType_SwordTrainingResumeGameScRsp = 7459;
    CmdSwordTrainingType_SwordTrainingGiveUpGameScRsp = 7497;
    CmdSwordTrainingType_SwordTrainingSetSkillTraceCsReq = 7484;
    CmdSwordTrainingType_SwordTrainingLearnSkillScRsp = 7464;
    CmdSwordTrainingType_SwordTrainingStartGameCsReq = 7492;
    CmdSwordTrainingType_EnterSwordTrainingExamCsReq = 7462;
    CmdSwordTrainingType_SwordTrainingRestoreGameScRsp = 7490;
    CmdSwordTrainingType_SwordTrainingStartGameScRsp = 7468;
    CmdSwordTrainingType_GetSwordTrainingDataCsReq = 7479;
    CmdSwordTrainingType_SwordTrainingGiveUpGameCsReq = 7485;
    CmdSwordTrainingType_EnterSwordTrainingExamScRsp = 7451;
    CmdSwordTrainingType_SwordTrainingTurnActionScRsp = 7458;
    CmdSwordTrainingType_SwordTrainingGameSettleScNotify = 7460;
    CmdSwordTrainingType_SwordTrainingSelectEndingScRsp = 7478;
    CmdSwordTrainingType_SwordTrainingTurnActionCsReq = 7474;
    CmdSwordTrainingType_SwordTrainingSetSkillTraceScRsp = 7489;
    CmdSwordTrainingType_SwordTrainingLearnSkillCsReq = 7457;
    CmdSwordTrainingType_SwordTrainingMarkEndingViewedCsReq = 7466;
    CmdSwordTrainingType_SwordTrainingStoryBattleCsReq = 7455;
    CmdSwordTrainingType_SwordTrainingStoryBattleScRsp = 7481;
    CmdSwordTrainingType_SwordTrainingDialogueSelectOptionScRsp = 7470;
    CmdSwordTrainingType_SwordTrainingDialogueSelectOptionCsReq = 7487;
    CmdSwordTrainingType_SwordTrainingDailyPhaseConfirmCsReq = 7472;
    CmdSwordTrainingType_SwordTrainingSelectEndingCsReq = 7483;
    CmdSwordTrainingType_SwordTrainingRestoreGameCsReq = 7477;
    CmdSwordTrainingType_SwordTrainingExamResultConfirmScRsp = 7498;
    CmdSwordTrainingType_SwordTrainingActionTurnSettleScNotify = 7493;
    CmdSwordTrainingType_SwordTrainingGameSyncChangeScNotify = 7486;
    CmdSwordTrainingType_SwordTrainingExamResultConfirmCsReq = 7456;
    CmdSwordTrainingType_SwordTrainingDailyPhaseConfirmScRsp = 7482;
    CmdSwordTrainingType_SwordTrainingMarkEndingViewedScRsp = 7461;
}

message DAEDLFEEGIB {
    uint32 dialogue_id = 2;
}

message ECPHOKOPKBP {
    bool IJJEGKDGKCJ = 2;
    uint32 LNAHJENGELA = 11;
}

message EINKHFKDCCD {
    HFMLKIIOGBP CLKDEHDODBB = 7;
    HFKKEDPMKKF DOBHAEAGEDG = 8;
    uint32 IMGDMDDKHDL = 15;
    repeated uint32 MDBAEBENFBA = 13;
    LBBNBAEKGCJ GFAANLGDEOB = 14;
    NPGJDCIBFDD FMIGOKIDKJL = 11;
    HCHNKKNDJCN HCEAHMKBFFK = 3;
    BCPMPHNADMN skill_info = 2;
}

enum EJCBOKGJFHE {
    EJCBOKGJFHE_NLCDGIPGFDJ = 0;
    EJCBOKGJFHE_GLANPLEGMPG = 1;
    EJCBOKGJFHE_CIGHHAKHHMN = 2;
    EJCBOKGJFHE_GAMNPOMOAIG = 3;
    EJCBOKGJFHE_KIKADFCIPJO = 4;
    EJCBOKGJFHE_NKAACMGNNPK = 5;
}

message EnterSwordTrainingExamCsReq {
}

message EnterSwordTrainingExamScRsp {
    uint32 retcode = 8;
    SceneBattleInfo battle_info = 5;
}

message FBKIJNOFIAH {
    uint32 HFNNNGHBHGG = 8;
    uint32 DCPDNBALDOA = 1;
}

message FDANEJNFABF {
    uint32 progress = 3;
    uint32 id = 2;
}

message GELEHDAJMED {
    uint32 dialogue_id = 9;
}

message GFFDDJHNJPN {
    uint32 level = 15;
    uint32 queue_position = 9;
}

message GIHLNOIACIH {
    repeated uint32 MNIIFCOOOML = 8;
    repeated FDANEJNFABF KFOFAKDPGJC = 10;
}

message GIJKCHKMPJG {
    LJGKNFCFLLB detail = 9;
    BHJOFLJGNKN source = 4;
}

message GIJLACBOPEE {
    uint32 queue_position = 11;
    uint32 HJMEJNMAILK = 9;
    uint32 level = 10;
}

message GOCNLGIDBLM {
    uint32 JALHKMEOOPN = 8;
    uint32 AMNDNDNPLCA = 9;
}

message GetSwordTrainingDataCsReq {
}

message GetSwordTrainingDataScRsp {
    repeated uint32 IEPANMCFKJL = 5;
    uint32 retcode = 11;
    uint32 PABJCCKBGEB = 3;
    bool GPGIMFMGGKG = 4;
    GIHLNOIACIH BBEKBJPHEJK = 14;
    repeated uint32 JBJNHJNMPAP = 7;
    EINKHFKDCCD AJGOEJHKOKE = 2;
    repeated uint32 CICCAIENFGA = 13;
}

message HCHNKKNDJCN {
    uint32 mood = 14;
    uint32 KPJHKDOMEMJ = 10;
    repeated LBBGLAHFJKN status_list = 7;
}

message HFKKEDPMKKF {
    uint32 game_story_line_id = 7;
    repeated uint32 JBJNHJNMPAP = 15;
}

message HFMLKIIOGBP {
    repeated GFFDDJHNJPN BELEDENKGGI = 7;
}

message IEALCLFLDMP {
    SwordTrainingDailyPhaseType cur_phase = 8;
    repeated GOCNLGIDBLM COOMKNFDNLH = 2;
    repeated uint32 JAJNHOKCAHH = 13;
}

message IKGLCLFLAKO {
}

enum IPPKHOFKMHM {
    IPPKHOFKMHM_KLHMFENBDID = 0;
    IPPKHOFKMHM_JKGEFNAIMFK = 1;
    IPPKHOFKMHM_CJOADAMKIFC = 2;
    IPPKHOFKMHM_FBHDMJMLBIC = 3;
    IPPKHOFKMHM_OKCNPPPLAHM = 4;
    IPPKHOFKMHM_KPOMIPJOKND = 5;
}

message JADFEJKNOCO {
    uint32 LNAHJENGELA = 13;
    bool JBJIKKOCNLP = 11;
}

message KLNGFBHIADA {
    uint32 DGONPFLCOMO = 5;
}

message LBBGLAHFJKN {
    EJCBOKGJFHE EGBFNFCEPHD = 12;
    uint32 value = 14;
}

message LBBNBAEKGCJ {
    uint32 AFPHLNMGPHK = 933;
    IEALCLFLDMP NMIJKPKNPLE = 6;
    KLNGFBHIADA FKPDOHGKJJK = 12;
}

message LJGKNFCFLLB {
    BJKPJIBNPHC DEIMCENJPKP = 15;
    FBKIJNOFIAH FNONLFCKDIL = 13;
    FBKIJNOFIAH CIDOEGFPHEN = 2;
    GIJLACBOPEE HANCFMMMFNF = 4;
    MCECLBDBENF LMAGJOOLKII = 5;
    JADFEJKNOCO GOLOGIHJOPF = 3;
    DAEDLFEEGIB FOGBMALOAOK = 10;
    uint32 MIFOJPGIFDD = 14;
    uint32 KPJHKDOMEMJ = 517;
    ECPHOKOPKBP KJOAIOHFFMK = 1450;
    OKOJCBKENEJ GBNOIFNDPJB = 428;
    uint32 KGKJHCBMEFI = 556;
}

message MCECLBDBENF {
    uint32 IMGDMDDKHDL = 15;
    LBBNBAEKGCJ turn = 3;
}

message NPGJDCIBFDD {
    BLJHLKBNGEC NGOCELLBHCF = 12;
    PJKNNJGEEBJ KNDKCOGGEKL = 13;
    GELEHDAJMED NCLBFAALLFJ = 1;
    AKFBNFPFKJJ DOCGLPKMHDM = 11;
    JADFEJKNOCO KGPMPPHJHLD = 15;
    OKOJCBKENEJ OLHMHOOMGCK = 2;
    IKGLCLFLAKO MHLPJEDILFJ = 14;
    ECPHOKOPKBP GJNINFABDBN = 10;
}

message OKOJCBKENEJ {
}

message PJKNNJGEEBJ {
}

message SwordTrainingActionTurnSettleScNotify {
    uint32 GEAJILJKBIK = 10;
    repeated LBBGLAHFJKN BINKDPMJLFG = 13;
}

message SwordTrainingDailyPhaseConfirmCsReq {
    SwordTrainingDailyPhaseType GCBHFKKGPHC = 2;
}

message SwordTrainingDailyPhaseConfirmScRsp {
    uint32 retcode = 4;
    bool KPMJOKEFLJO = 1;
}

enum SwordTrainingDailyPhaseType {
    SwordTrainingDailyPhaseType_None = 0;
    SwordTrainingDailyPhaseType_Morning = 1;
    SwordTrainingDailyPhaseType_Noon = 2;
    SwordTrainingDailyPhaseType_Afternoon = 3;
    SwordTrainingDailyPhaseType_Evening = 4;
}

message SwordTrainingDialogueSelectOptionCsReq {
    uint32 HAFOKMHCGFM = 13;
}

message SwordTrainingDialogueSelectOptionScRsp {
    uint32 retcode = 2;
}

message SwordTrainingExamResultConfirmCsReq {
}

message SwordTrainingExamResultConfirmScRsp {
    uint32 retcode = 8;
}

message SwordTrainingGameSettleScNotify {
    uint32 LBNLIJBPKHI = 10;
    repeated uint32 KACAMGJNOOB = 14;
    ItemList reward = 7;
    uint32 turn = 3;
    repeated uint32 BHFHFONGHML = 6;
    uint32 game_story_line_id = 9;
    IPPKHOFKMHM reason = 4;
    uint32 CDBGPMABMGM = 2;
}

message SwordTrainingGameSyncChangeScNotify {
    repeated GIJKCHKMPJG DGNGMJMPFGK = 3;
}

message SwordTrainingGiveUpGameCsReq {
}

message SwordTrainingGiveUpGameScRsp {
    uint32 retcode = 15;
}

message SwordTrainingLearnSkillCsReq {
    uint32 skill_id = 12;
}

message SwordTrainingLearnSkillScRsp {
    uint32 skill_id = 8;
    uint32 retcode = 7;
}

message SwordTrainingMarkEndingViewedCsReq {
}

message SwordTrainingMarkEndingViewedScRsp {
    uint32 retcode = 15;
}

message SwordTrainingRestoreGameCsReq {
}

message SwordTrainingRestoreGameScRsp {
    uint32 retcode = 13;
    EINKHFKDCCD AJGOEJHKOKE = 9;
}

message SwordTrainingResumeGameCsReq {
    uint32 game_story_line_id = 13;
}

message SwordTrainingResumeGameScRsp {
    uint32 retcode = 8;
    EINKHFKDCCD AJGOEJHKOKE = 13;
}

message SwordTrainingSelectEndingCsReq {
    uint32 PFOLEGLCLFE = 9;
}

message SwordTrainingSelectEndingScRsp {
    uint32 retcode = 13;
    uint32 PFOLEGLCLFE = 2;
}

message SwordTrainingSetSkillTraceCsReq {
    uint32 skill_id = 11;
}

message SwordTrainingSetSkillTraceScRsp {
    uint32 skill_id = 7;
    uint32 retcode = 1;
}

message SwordTrainingStartGameCsReq {
    uint32 game_story_line_id = 6;
}

message SwordTrainingStartGameScRsp {
    EINKHFKDCCD AJGOEJHKOKE = 8;
    uint32 retcode = 3;
}

message SwordTrainingStoryBattleCsReq {
}

message SwordTrainingStoryBattleScRsp {
    uint32 retcode = 14;
    SceneBattleInfo battle_info = 4;
}

message SwordTrainingStoryConfirmCsReq {
    uint32 LNAHJENGELA = 4;
}

message SwordTrainingStoryConfirmScRsp {
    uint32 retcode = 6;
    uint32 LNAHJENGELA = 10;
}

message SwordTrainingTurnActionCsReq {
    repeated uint32 GJEPAKHPFCG = 2;
    repeated uint32 CCPADEMEHBA = 14;
}

message SwordTrainingTurnActionScRsp {
    repeated uint32 CCPADEMEHBA = 12;
    uint32 retcode = 8;
}

message SwordTrainingUnlockSyncScNotify {
    repeated uint32 MNIIFCOOOML = 5;
    repeated FDANEJNFABF KFOFAKDPGJC = 9;
}
