syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdStrongChallengeActivityType {
    CmdStrongChallengeActivityType_None = 0;
    CmdStrongChallengeActivityType_GetStrongChallengeActivityDataScRsp = 6682;
    CmdStrongChallengeActivityType_StrongChallengeActivityBattleEndScNotify = 6656;
    CmdStrongChallengeActivityType_EnterStrongChallengeActivityStageScRsp = 6639;
    CmdStrongChallengeActivityType_EnterStrongChallengeActivityStageCsReq = 6679;
    CmdStrongChallengeActivityType_GetStrongChallengeActivityDataCsReq = 6634;
}

message EnterStrongChallengeActivityStageCsReq {
    repeated uint32 buff_list = 1;
    uint32 stage_id = 14;
    repeated StrongChallengeAvatar avatar_list = 15;
}

message EnterStrongChallengeActivityStageScRsp {
    uint32 stage_id = 3;
    uint32 retcode = 10;
    SceneBattleInfo battle_info = 14;
}

message GetStrongChallengeActivityDataCsReq {
}

message StrongChallengeAvatar {
    AvatarType avatar_type = 14;
    uint32 avatar_id = 6;
}
