syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum ChangeStoryLineAction {
    ChangeStoryLineAction_None = 0;
    ChangeStoryLineAction_FinishAction = 1;
    ChangeStoryLineAction_Client = 2;
    ChangeStoryLineAction_CustomOP = 3;
    ChangeStoryLineAction_Raid = 4;
    ChangeStoryLineAction_HKFKAFPAJCO = 5;
}

message ChangeStoryLineFinishScNotify {
    uint32 cur_story_line_id = 12;
    ChangeStoryLineAction action = 15;
    bool HBFDGEPBLNP = 10;
    uint32 ONBMNAMBIGE = 9;
}

enum CmdStoryLineType {
    CmdStoryLineType_None = 0;
    CmdStoryLineType_StoryLineInfoScNotify = 6279;
    CmdStoryLineType_GetStoryLineInfoScRsp = 6282;
    CmdStoryLineType_GetStoryLineInfoCsReq = 6234;
    CmdStoryLineType_StoryLineTrialAvatarChangeScNotify = 6298;
    CmdStoryLineType_ChangeStoryLineFinishScNotify = 6291;
}

message GetStoryLineInfoCsReq {
}

message GetStoryLineInfoScRsp {
    uint32 retcode = 9;
    repeated uint32 trial_avatar_id_list = 3;
    repeated uint32 unfinished_story_line_id_list = 7;
    uint32 cur_story_line_id = 10;
}

message StoryLineInfoScNotify {
    repeated uint32 trial_avatar_id_list = 9;
    uint32 FDFLHKEDPGC = 10;
    repeated uint32 unfinished_story_line_id_list = 14;
    uint32 cur_story_line_id = 11;
}

message StoryLineTrialAvatarChangeScNotify {
    repeated uint32 EDBMIFNEHHH = 10;
    repeated uint32 ILIDIIGALKD = 6;
    bool OLPNMKAPDLP = 8;
}
