syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdStarFightType {
    CmdStarFightType_None = 0;
    CmdStarFightType_GetStarFightDataScRsp = 7170;
    CmdStarFightType_StarFightDataChangeNotify = 7166;
    CmdStarFightType_StartStarFightLevelScRsp = 7169;
    CmdStarFightType_GetStarFightDataCsReq = 7165;
    CmdStarFightType_StartStarFightLevelCsReq = 7167;
}

message EBGJAKBKPAN {
    AvatarType avatar_type = 8;
    uint32 avatar_id = 12;
}

message GetStarFightDataCsReq {
}

message GetStarFightDataScRsp {
    uint32 retcode = 2;
    repeated JFGCABMMKAB JJIDNKDKMLE = 15;
}

message JFGCABMMKAB {
    uint32 CEOEOEBOLNN = 7;
    uint32 group_id = 13;
    uint32 EBDDDCBKPAC = 1;
    bool NDBGPGODBPH = 4;
    uint32 KDNBADEGDNK = 10;
}

message StarFightDataChangeNotify {
    JFGCABMMKAB KDKKNFGPNAB = 2;
    uint32 group_id = 10;
}

message StartStarFightLevelCsReq {
    uint32 group_id = 6;
    uint32 DBKHHCGGKNN = 9;
    repeated EBGJAKBKPAN avatar_list = 12;
}

message StartStarFightLevelScRsp {
    SceneBattleInfo battle_info = 5;
    uint32 group_id = 4;
    uint32 retcode = 2;
    uint32 DBKHHCGGKNN = 10;
}
