syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdSwitchHandType {
    CmdSwitchHandType_None = 0;
    CmdSwitchHandType_SwitchHandResetGameCsReq = 8119;
    CmdSwitchHandType_SwitchHandResetHandPosScRsp = 8116;
    CmdSwitchHandType_SwitchHandStartCsReq = 8120;
    CmdSwitchHandType_SwitchHandFinishCsReq = 8109;
    CmdSwitchHandType_SwitchHandResetHandPosCsReq = 8118;
    CmdSwitchHandType_SwitchHandResetGameScRsp = 8104;
    CmdSwitchHandType_SwitchHandUpdateCsReq = 8111;
    CmdSwitchHandType_SwitchHandUpdateScRsp = 8114;
    CmdSwitchHandType_SwitchHandCoinUpdateScRsp = 8110;
    CmdSwitchHandType_SwitchHandDataCsReq = 8105;
    CmdSwitchHandType_SwitchHandFinishScRsp = 8112;
    CmdSwitchHandType_SwitchHandDataScRsp = 8115;
    CmdSwitchHandType_SwitchHandCoinUpdateCsReq = 8107;
    CmdSwitchHandType_SwitchHandStartScRsp = 8113;
}

message ENHOPAHGCMA {
    MotionInfo IFPFJIIFALA = 13;
    uint32 config_id = 3;
    bytes DNOBAJNIGAC = 7;
    uint32 EKHEAFBKDFP = 5;
    uint32 LNGJODEPCDN = 11;
}

message JAIOIENPGOD {
    uint32 LNGJODEPCDN = 13;
}

message SwitchHandDataCsReq {
    uint32 NOBLDDEFEKI = 3;
}

message SwitchHandFinishCsReq {
}

message SwitchHandFinishScRsp {
    ENHOPAHGCMA BDEDDAHODII = 6;
    uint32 retcode = 15;
}

message SwitchHandStartCsReq {
    uint32 config_id = 13;
}

message SwitchHandStartScRsp {
    uint32 retcode = 6;
    uint32 config_id = 5;
}
