syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdSummonActivityType {
    CmdSummonActivityType_None = 0;
    CmdSummonActivityType_EnterSummonActivityStageCsReq = 7567;
    CmdSummonActivityType_GetSummonActivityDataScRsp = 7570;
    CmdSummonActivityType_EnterSummonActivityStageScRsp = 7569;
    CmdSummonActivityType_SummonActivityBattleEndScNotify = 7566;
    CmdSummonActivityType_GetSummonActivityDataCsReq = 7565;
}

message EnterSummonActivityStageCsReq {
    repeated OOAJJMEGIFO avatar_list = 2;
    uint32 group_id = 5;
    OOAJJMEGIFO NLJCJIGLGHE = 9;
    uint32 DBKHHCGGKNN = 3;
}

message EnterSummonActivityStageScRsp {
    SceneBattleInfo battle_info = 3;
    uint32 group_id = 15;
    uint32 retcode = 13;
    uint32 DBKHHCGGKNN = 5;
}

message GetSummonActivityDataCsReq {
}

message GetSummonActivityDataScRsp {
    uint32 retcode = 3;
    repeated ILHFAFGOJAC IDLCLMMAIHP = 5;
}

message ILHFAFGOJAC {
    uint32 group_id = 1;
    uint32 DBKHHCGGKNN = 7;
    uint32 star = 15;
}

message OOAJJMEGIFO {
    uint32 avatar_id = 1;
    AvatarType avatar_type = 2;
}

message SummonActivityBattleEndScNotify {
    uint32 round = 15;
    uint32 DBKHHCGGKNN = 11;
    uint32 group_id = 9;
    uint32 star = 3;
}
