syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdTrackPhotoActivityType {
    CmdTrackPhotoActivityType_None = 0;
    CmdTrackPhotoActivityType_SettleTrackPhotoStageScRsp = 7559;
    CmdTrackPhotoActivityType_SettleTrackPhotoStageCsReq = 7557;
    CmdTrackPhotoActivityType_GetTrackPhotoActivityDataScRsp = 7560;
    CmdTrackPhotoActivityType_QuitTrackPhotoStageCsReq = 7558;
    CmdTrackPhotoActivityType_StartTrackPhotoStageScRsp = 7552;
    CmdTrackPhotoActivityType_GetTrackPhotoActivityDataCsReq = 7555;
    CmdTrackPhotoActivityType_StartTrackPhotoStageCsReq = 7556;
    CmdTrackPhotoActivityType_QuitTrackPhotoStageScRsp = 7551;
}

message EGIJMPCIJOG {
    uint32 stage_id = 11;
}

message GetTrackPhotoActivityDataCsReq {
}

message GetTrackPhotoActivityDataScRsp {
    repeated IFBJJJOBGHB PEDCKGNNPAJ = 4;
    uint32 retcode = 10;
}

message IFBJJJOBGHB {
    uint32 stage_id = 9;
    uint32 max_score = 12;
}

message PNICDFFMDDB {
    bool ADGCOJLMGAH = 3;
    uint32 entity_id = 11;
}

message SettleTrackPhotoStageCsReq {
    uint32 stage_id = 10;
    uint32 cost_time = 3;
    repeated PNICDFFMDDB PIGLHELGMIJ = 11;
}

message SettleTrackPhotoStageScRsp {
    uint32 score_id = 9;
    uint32 stage_id = 6;
    uint32 retcode = 1;
    repeated PNICDFFMDDB PIGLHELGMIJ = 2;
}

message StartTrackPhotoStageCsReq {
    bool LCPPNDPKHPH = 5;
    uint32 stage_id = 10;
}

message StartTrackPhotoStageScRsp {
    uint32 trans_no = 1;
    uint32 retcode = 9;
}
