syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BFAKMCIJFCB {
    repeated IIONNFELFEF PKMHMGAEAGO = 1;
    repeated HJACHMJFEAH PNHLAAMNGFE = 2;
    BOMHOLBACKF GLOGEMFDMJG = 3;
}

message BODEMOLDHAA {
    uint32 teleport_id = 8;
}

enum BOMHOLBACKF {
    BOMHOLBACKF_HGLIFJGHADE = 0;
    BOMHOLBACKF_PDJAJHELPKL = 1;
}

message CIEAALPHGFM {
}

enum CmdTrainCakeCatchType {
    CmdTrainCakeCatchType_None = 0;
    CmdTrainCakeCatchType_SocialPlayPreCheckEnterRoomScRsp = 9731;
    CmdTrainCakeCatchType_TrainCakeCatchDataScNotify = 9650;
    CmdTrainCakeCatchType_TrainCakeCatchCatGodInteractCsReq = 9622;
    CmdTrainCakeCatchType_TrainCakeCatchDiyScRsp = 9687;
    CmdTrainCakeCatchType_TrainCakeCatchGetDataCsReq = 9648;
    CmdTrainCakeCatchType_TrainCakeCatchOpenBoxScRsp = 9727;
    CmdTrainCakeCatchType_TrainCakeCatchSearchScRsp = 9660;
    CmdTrainCakeCatchType_SocialPlayGameplayOperationScNotify = 9763;
    CmdTrainCakeCatchType_SocialPlayPreCheckEnterRoomCsReq = 9717;
    CmdTrainCakeCatchType_TrainCakeCatchDiyCsReq = 9718;
    CmdTrainCakeCatchType_SocialPlayQueryRecentVisitorsScRsp = 9629;
    CmdTrainCakeCatchType_SocialPlayTalkCsReq = 9628;
    CmdTrainCakeCatchType_TrainCakeCatchOpenBoxCsReq = 9646;
    CmdTrainCakeCatchType_SocialPlayRoomPlayerMoveScNotify = 9764;
    CmdTrainCakeCatchType_TrainCakeCatchDiyLikeCsReq = 9666;
    CmdTrainCakeCatchType_SocialPlayRoomKickOutPlayerScRsp = 9680;
    CmdTrainCakeCatchType_SocialPlayRoomPlayerMoveCsReq = 9669;
    CmdTrainCakeCatchType_TrainCakeCatchDiyLikeScRsp = 9630;
    CmdTrainCakeCatchType_SocialPlayQueryRecentVisitorsCsReq = 9769;
    CmdTrainCakeCatchType_TrainCakeCatchSearchCsReq = 9737;
    CmdTrainCakeCatchType_SocialPlayRoomPlayerMoveScRsp = 9768;
    CmdTrainCakeCatchType_TrainCakeCatchCatGodInteractScRsp = 9688;
    CmdTrainCakeCatchType_SocialPlayRoomKickOutPlayerCsReq = 9625;
    CmdTrainCakeCatchType_SocialPlayTalkScRsp = 9682;
    CmdTrainCakeCatchType_SocialPlaySettingInfoScNotify = 9642;
    CmdTrainCakeCatchType_TrainCakeCatchGetDataScRsp = 9740;
}

message HHJLCGGEHPB {
    PlayerSimpleInfo CILGIDDHODG = 3;
    uint32 PLPPPCEPBDO = 13;
    int64 KFACPOBAAGM = 2;
}

message HJACHMJFEAH {
    uint32 PCPDHEIEJFO = 1;
    uint32 slot = 2;
}

message HMACEHDGGHB {
    repeated IKAHKMNCFDN BJPHDKEBOBK = 1;
    uint32 HBKEPFKDAMI = 2;
    int64 CMHKFNFKGOI = 3;
}

message IIONNFELFEF {
    uint32 dice_slot_id = 1;
    uint32 pose = 2;
    repeated uint32 DMIOBEKLDED = 3;
}

message IKAHKMNCFDN {
    uint32 PCPDHEIEJFO = 1;
    uint32 slot = 2;
}

message IKBDJLNEPBH {
    repeated PEEEEGAPCOK HFLOPHNBKGN = 1;
}

message JBJNJPAOCDA {
    JOLAHHGIFHA NJDCPMENIFG = 3;
    uint32 uid = 12;
    bool OJPDDAOJJKC = 4;
    int64 AIMNJIMDIKM = 11;
    PlayerSimpleInfo AJIPBLCIONL = 13;
    uint32 summoned_pet_id = 10;
}

message JGAMELLGLGE {
    JOLAHHGIFHA NJDCPMENIFG = 12;
}

message JOFHMCJPBCE {
    uint32 PCPDHEIEJFO = 14;
    uint32 count = 5;
}

message JOLAHHGIFHA {
    Vector pos = 1;
    Vector rot = 2;
    float ICNANKMDJIC = 3;
    Vector GHMKFMBDKNE = 4;
    float GHEMGLKGKLC = 5;
    uint32 FPHBEHJJBIA = 6;
    bool MGIOLDGHPMA = 7;
    int64 time_stamp = 8;
}

message JPAOIPLDKHB {
    repeated IKAHKMNCFDN BJPHDKEBOBK = 1;
    BFAKMCIJFCB NLJBJMDPBGN = 2;
    int64 DBIKJPDBMOE = 3;
    int64 CMHKFNFKGOI = 4;
    uint32 HBKEPFKDAMI = 5;
    uint32 GAEKEFEKCBD = 6;
}

message KKACLNNMMAM {
    repeated uint32 BPAOGJPLENJ = 9;
    bool JMAODNEONPF = 6;
}

enum MFPDAKOIOED {
    MFPDAKOIOED_KCOCMMIACMB = 0;
    MFPDAKOIOED_FLMPFOFPAGB = 1;
}

message MHNNEFBOPIE {
    uint32 op_uid = 1;
    repeated JOLAHHGIFHA JENKGODEIOM = 2;
}

message MIKGMGBHLEN {
    string message_text = 1;
    uint32 extra_id = 2;
}

message ONAADAJBLEB {
    int64 DBIKJPDBMOE = 5;
    uint32 ONOHPMDGNNH = 14;
}

message PBMDEBCGNMD {
    MNCBEDBDDHL IKJNIKIGFLF = 6;
    JPAOIPLDKHB PKHFMJDNKOE = 11;
    uint32 DLKOEIANIMK = 7;
}

message PEEEEGAPCOK {
    uint32 PLPPPCEPBDO = 1;
    uint32 op_uid = 2;
    uint32 OOCPKIGPEHP = 3;
    int64 CMIEOOODDIA = 4;
    string AALDPOAKJBK = 5;
}

message PJFIMFJPMCN {
    uint32 PCPDHEIEJFO = 8;
    repeated uint32 LPDFMJPFGJH = 11;
}

message POBLGKIGINE {
    repeated JBJNJPAOCDA player_info = 4;
    uint32 room_owner_uid = 15;
    PBMDEBCGNMD LNMGOFCOMED = 916;
}

message SocialPlayGameplayOperationScNotify {
    uint32 room_owner_uid = 9;
    uint32 op_uid = 12;
    uint32 LMGGGLECNEA = 1814;
    JBJNJPAOCDA GNLAECODENP = 877;
    POBLGKIGINE LMFMBJCNALJ = 458;
    uint32 HJHPHDACEHE = 1856;
    BFAKMCIJFCB OEMEKBOGNJH = 222;
    HMACEHDGGHB ONMNMLBANHK = 1531;
    MIKGMGBHLEN PHKCDLPHMPA = 1323;
    POBLGKIGINE LABNNEGJNHO = 1180;
    int64 DBIKJPDBMOE = 668;
    IKBDJLNEPBH IMPBCBPIFAG = 810;
    uint32 BJLCBAAKPDI = 861;
    uint32 DLKOEIANIMK = 1008;
}

message SocialPlayPreCheckEnterRoomCsReq {
    uint32 teleport_id = 13;
    uint32 entry_id = 5;
    MFPDAKOIOED GJNMHILINHC = 10;
}

message SocialPlayPreCheckEnterRoomScRsp {
    int64 CMHKFNFKGOI = 9;
    uint32 retcode = 7;
    PlayerSimpleInfo MCCEJINNADF = 2;
}

message SocialPlayQueryRecentVisitorsCsReq {
}

message SocialPlayQueryRecentVisitorsScRsp {
    repeated HHJLCGGEHPB recent_visitor_list = 3;
    uint32 retcode = 10;
}

message SocialPlayRoomPlayerMoveScNotify {
    uint32 op_uid = 7;
    MHNNEFBOPIE JENKGODEIOM = 11;
    uint32 room_owner_uid = 3;
}

message SocialPlaySettingInfoScNotify {
    JPGACKPLGCD BOHGFDFBLEN = 3;
}

message SocialPlayTalkCsReq {
    MIKGMGBHLEN PHKCDLPHMPA = 5;
}

message SocialPlayTalkScRsp {
    int64 end_time = 8;
    uint32 retcode = 5;
    MIKGMGBHLEN PHKCDLPHMPA = 6;
}

message TrainCakeCatchDataScNotify {
    repeated JOFHMCJPBCE NIELDCLPOLA = 7;
    repeated uint32 performance_id_list = 2;
}

message TrainCakeCatchDiyCsReq {
    BFAKMCIJFCB NLJBJMDPBGN = 5;
}

message TrainCakeCatchDiyLikeCsReq {
}

message TrainCakeCatchDiyLikeScRsp {
    repeated uint32 BPAOGJPLENJ = 3;
    uint32 retcode = 4;
}

message TrainCakeCatchDiyScRsp {
    BFAKMCIJFCB NLJBJMDPBGN = 9;
    uint32 retcode = 10;
}

message TrainCakeCatchGetDataCsReq {
}

message TrainCakeCatchGetDataScRsp {
    int64 CMHKFNFKGOI = 8;
    ONAADAJBLEB NAIFOMCLGLN = 2;
    KKACLNNMMAM JIELLGELABA = 5;
    repeated PJFIMFJPMCN CEMFBJPOLNP = 1;
    repeated JOFHMCJPBCE NIELDCLPOLA = 9;
    repeated IKAHKMNCFDN BJPHDKEBOBK = 12;
    bool OJPDDAOJJKC = 14;
    uint32 retcode = 11;
    repeated uint32 performance_id_list = 3;
    BFAKMCIJFCB NLJBJMDPBGN = 7;
    POBLGKIGINE DJMHHMMABJL = 15;
}

message TrainCakeCatchOpenBoxCsReq {
}

message TrainCakeCatchOpenBoxScRsp {
    uint32 retcode = 11;
    int64 CMHKFNFKGOI = 10;
    repeated IKAHKMNCFDN BJPHDKEBOBK = 14;
}

message TrainCakeCatchSearchCsReq {
    uint32 PCPDHEIEJFO = 3;
}

message TrainCakeCatchSearchScRsp {
    repeated PJFIMFJPMCN CEMFBJPOLNP = 15;
    uint32 PCPDHEIEJFO = 8;
    repeated uint32 GINENNKGDMG = 10;
    JOFHMCJPBCE NIELDCLPOLA = 13;
    uint32 retcode = 3;
}
