syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CBIKIIMGKHH {
    uint32 avatar_id = 10;
    AvatarType avatar_type = 2;
}

enum CmdTelevisionActivityType {
    CmdTelevisionActivityType_None = 0;
    CmdTelevisionActivityType_GetTelevisionActivityDataCsReq = 6965;
    CmdTelevisionActivityType_EnterTelevisionActivityStageScRsp = 6969;
    CmdTelevisionActivityType_TelevisionActivityBattleEndScNotify = 6972;
    CmdTelevisionActivityType_EnterTelevisionActivityStageCsReq = 6973;
    CmdTelevisionActivityType_GetTelevisionActivityDataScRsp = 6975;
}

message EnterTelevisionActivityStageCsReq {
    repeated CBIKIIMGKHH avatar_list = 10;
    repeated uint32 buff_list = 14;
    uint32 KKNGIFOJLGJ = 8;
}

message EnterTelevisionActivityStageScRsp {
    uint32 retcode = 15;
    uint32 KKNGIFOJLGJ = 1;
    SceneBattleInfo battle_info = 13;
}

message GetTelevisionActivityDataCsReq {
}

message GetTelevisionActivityDataScRsp {
    repeated PAAIMLDHJCI AKDFABDHHIO = 15;
    uint32 retcode = 4;
}

message PAAIMLDHJCI {
    uint32 max_score = 10;
    uint32 KKNGIFOJLGJ = 5;
    uint32 NELOAKJAABI = 14;
}

message TelevisionActivityBattleEndScNotify {
    uint32 total_score = 12;
    PAAIMLDHJCI GBHAIBBFPHJ = 14;
    uint32 turn_left = 4;
    uint32 round_score = 9;
    uint32 AAJFIPMBMHC = 3;
}
