syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdTreasureDungeonType {
    CmdTreasureDungeonType_None = 0;
    CmdTreasureDungeonType_FightTreasureDungeonMonsterCsReq = 4449;
    CmdTreasureDungeonType_EnterTreasureDungeonCsReq = 4480;
    CmdTreasureDungeonType_QuitTreasureDungeonScRsp = 4438;
    CmdTreasureDungeonType_InteractTreasureDungeonGridScRsp = 4415;
    CmdTreasureDungeonType_GetTreasureDungeonActivityDataCsReq = 4472;
    CmdTreasureDungeonType_UseTreasureDungeonItemScRsp = 4481;
    CmdTreasureDungeonType_InteractTreasureDungeonGridCsReq = 4488;
    CmdTreasureDungeonType_FightTreasureDungeonMonsterScRsp = 4448;
    CmdTreasureDungeonType_GetTreasureDungeonActivityDataScRsp = 4465;
    CmdTreasureDungeonType_TreasureDungeonDataScNotify = 4434;
    CmdTreasureDungeonType_UseTreasureDungeonItemCsReq = 4464;
    CmdTreasureDungeonType_EnterTreasureDungeonScRsp = 4471;
    CmdTreasureDungeonType_TreasureDungeonFinishScNotify = 4482;
    CmdTreasureDungeonType_OpenTreasureDungeonGridCsReq = 4404;
    CmdTreasureDungeonType_OpenTreasureDungeonGridScRsp = 4462;
    CmdTreasureDungeonType_QuitTreasureDungeonCsReq = 4441;
}

message DCMCLHJINBD {
    uint32 NKMNCCFFBAB = 14;
    uint32 attack_add = 9;
    uint32 MIAFMBHCMOG = 11;
    bool is_entered = 2;
    uint32 defence_add = 8;
    bool has_passed = 1;
    uint32 EICEKDBENKM = 10;
}

message ENGHACADBKI {
    uint32 EGKLFMCHLCO = 7;
    TreasureDungeonRecordType type = 2;
    uint32 FMIFPFAHFBL = 5;
    uint32 FFKDFODDBDN = 14;
    uint32 LDMHLKGILOD = 1;
}

message EnterTreasureDungeonCsReq {
    uint32 EICEKDBENKM = 9;
    repeated IOKGDDDHHPD avatar_list = 1;
}

message EnterTreasureDungeonScRsp {
    PPONNIHFJAP IMHNGDFGJJA = 1;
    uint32 retcode = 9;
}

message FFMOAGPPHGP {
    uint32 KHJKDLNAMIP = 4;
    uint32 hp = 11;
    uint32 avatar_type = 3;
    uint32 avatar_id = 1;
    SpBarInfo sp_bar = 8;
}

message FightTreasureDungeonMonsterCsReq {
    uint32 GDNEHLEOMOM = 11;
    repeated IOKGDDDHHPD avatar_list = 3;
    uint32 EICEKDBENKM = 1;
}

message FightTreasureDungeonMonsterScRsp {
    SceneBattleInfo battle_info = 4;
    uint32 retcode = 15;
}

message GetTreasureDungeonActivityDataCsReq {
}

message GetTreasureDungeonActivityDataScRsp {
    repeated DCMCLHJINBD NFEJLHOCFMC = 13;
    uint32 retcode = 6;
}

message IHBMPCIIGJD {
    bool is_locked = 8;
    bool DBMFBJCHNKN = 15;
    uint32 GDNEHLEOMOM = 1;
    uint32 OHCCEFIALGL = 11;
    repeated KMCCCOKIOFD buff_list = 117;
    bool BBBINMPJCGI = 7;
    bool can_interact = 14;
    uint32 EILBAOLILAM = 2;
}

message IOKGDDDHHPD {
    AvatarType avatar_type = 5;
    uint32 avatar_id = 10;
}

message InteractTreasureDungeonGridCsReq {
    uint32 GDNEHLEOMOM = 8;
    uint32 param = 3;
    uint32 EICEKDBENKM = 12;
}

message InteractTreasureDungeonGridScRsp {
    uint32 retcode = 6;
    PPONNIHFJAP IMHNGDFGJJA = 12;
}

message JDLIPNFGEID {
    uint32 avatar_id = 1;
    uint32 avatar_type = 3;
}

message JGNNOJEEBLP {
    uint32 MODPKCCOAJL = 6;
    uint32 buff_id = 8;
}

message KMCCCOKIOFD {
    uint32 FBNBPPHOGLI = 3;
    uint32 GDNEHLEOMOM = 6;
    uint32 buff_id = 5;
    uint32 EGKLFMCHLCO = 8;
    uint32 JBGENFIKGGF = 14;
}

message NPPFFMBNGBP {
    uint32 item_count = 11;
    uint32 item_id = 8;
}

message OMKAKFPOGDA {
    uint32 EICEKDBENKM = 6;
    bool KEAAGAIAHLA = 4;
}

message OpenTreasureDungeonGridCsReq {
    uint32 EICEKDBENKM = 11;
    uint32 GDNEHLEOMOM = 12;
}

message OpenTreasureDungeonGridScRsp {
    PPONNIHFJAP IMHNGDFGJJA = 6;
    uint32 retcode = 2;
}

message PPONNIHFJAP {
    uint32 map_id = 3;
    uint32 attack_add = 15;
    repeated JDLIPNFGEID FDOILGLIFIB = 1387;
    uint32 KJNKBKLCGHJ = 5;
    repeated FFMOAGPPHGP avatar_list = 1678;
    bool MNEIFMEDFGC = 1492;
    uint32 defence_add = 14;
    repeated JGNNOJEEBLP buff_list = 1511;
    uint32 MIAFMBHCMOG = 9;
    repeated IHBMPCIIGJD IEDKELDFHLP = 4;
    bool NBNPGEAMFJP = 1239;
    repeated FFMOAGPPHGP PBNEHHOBBFC = 1227;
    bool IGJCGAGHDPP = 1044;
    uint32 HCEGFNHMMOD = 1177;
    repeated ENGHACADBKI HFLOPHNBKGN = 13;
    repeated NPPFFMBNGBP item_list = 1078;
    uint32 DIPLENNGJII = 10;
    uint32 EICEKDBENKM = 6;
}

message TreasureDungeonDataScNotify {
    PPONNIHFJAP IMHNGDFGJJA = 4;
}

message TreasureDungeonFinishScNotify {
    uint32 EICEKDBENKM = 15;
    uint32 DJCNKLMCABG = 1;
    map<uint32, uint32> IMALNDJDDNO = 9;
    uint32 DEHGKCLNNAP = 5;
    uint32 MIAFMBHCMOG = 3;
    map<uint32, uint32> NLMHKDPJEFO = 12;
    bool is_win = 11;
}

enum TreasureDungeonRecordType {
    TreasureDungeonRecordType_TreasureDungeonRecordNone = 0;
    TreasureDungeonRecordType_TreasureDungeonRecordAddHp = 1;
    TreasureDungeonRecordType_TreasureDungeonRecordSubHp = 2;
    TreasureDungeonRecordType_TreasureDungeonRecordSubHpNoExplore = 3;
    TreasureDungeonRecordType_TreasureDungeonRecordAddAttack = 5;
    TreasureDungeonRecordType_TreasureDungeonRecordAddDefence = 6;
    TreasureDungeonRecordType_TreasureDungeonRecordAddExplore = 9;
    TreasureDungeonRecordType_TreasureDungeonRecordSubExplore = 10;
    TreasureDungeonRecordType_TreasureDungeonRecordAddExploreOverflow = 11;
    TreasureDungeonRecordType_TreasureDungeonRecordSummon = 15;
    TreasureDungeonRecordType_TreasureDungeonRecordKill = 16;
    TreasureDungeonRecordType_TreasureDungeonRecordAddTrialAvatar = 20;
    TreasureDungeonRecordType_TreasureDungeonRecordAddBuff = 24;
    TreasureDungeonRecordType_TreasureDungeonRecordUnlockDoor = 25;
    TreasureDungeonRecordType_TreasureDungeonRecordEnemyEnhance = 27;
    TreasureDungeonRecordType_TreasureDungeonRecordEnemyWeaken = 28;
    TreasureDungeonRecordType_TreasureDungeonRecordEnemyAuraRemove = 29;
    TreasureDungeonRecordType_TreasureDungeonRecordSpecialMonsterRun = 30;
    TreasureDungeonRecordType_TreasureDungeonRecordSpecialMonsterKill = 31;
    TreasureDungeonRecordType_TreasureDungeonRecordBattleBuffTriggerSuccess = 33;
    TreasureDungeonRecordType_TreasureDungeonRecordBattleBuffTriggerFail = 34;
    TreasureDungeonRecordType_TreasureDungeonRecordBattleBuffAddExplore = 35;
    TreasureDungeonRecordType_TreasureDungeonRecordBattleBuffOpenGrid = 36;
    TreasureDungeonRecordType_TreasureDungeonRecordBattleBuffAddItem = 37;
    TreasureDungeonRecordType_TreasureDungeonRecordAvatarDead = 40;
    TreasureDungeonRecordType_TreasureDungeonRecordTrialAvatarDead = 41;
    TreasureDungeonRecordType_TreasureDungeonRecordAllAvatarDead = 42;
    TreasureDungeonRecordType_TreasureDungeonRecordOpenItemChest = 43;
}

message UseTreasureDungeonItemCsReq {
    uint32 GDNEHLEOMOM = 13;
    uint32 item_id = 4;
    uint32 EICEKDBENKM = 5;
}

message UseTreasureDungeonItemScRsp {
    uint32 retcode = 3;
    PPONNIHFJAP IMHNGDFGJJA = 4;
}
