syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdTravelBrochureType {
    CmdTravelBrochureType_CmdTravelBrochureNone = 0;
    CmdTravelBrochureType_TravelBrochurePageUnlockScNotify = 6479;
    CmdTravelBrochureType_TravelBrochureSetPageDescStatusScRsp = 6448;
    CmdTravelBrochureType_TravelBrochureSetCustomValueScRsp = 6462;
    CmdTravelBrochureType_TravelBrochureGetDataScRsp = 6482;
    CmdTravelBrochureType_TravelBrochureRemovePasterCsReq = 6473;
    CmdTravelBrochureType_TravelBrochureUpdatePasterPosCsReq = 6472;
    CmdTravelBrochureType_TravelBrochurePageResetCsReq = 6488;
    CmdTravelBrochureType_TravelBrochureGetPasterScNotify = 6480;
    CmdTravelBrochureType_TravelBrochureUpdatePasterPosScRsp = 6465;
    CmdTravelBrochureType_TravelBrochureGetDataCsReq = 6434;
    CmdTravelBrochureType_TravelBrochureSelectMessageCsReq = 6456;
    CmdTravelBrochureType_TravelBrochurePageResetScRsp = 6415;
    CmdTravelBrochureType_TravelBrochureSetPageDescStatusCsReq = 6449;
    CmdTravelBrochureType_TravelBrochureRemovePasterScRsp = 6499;
    CmdTravelBrochureType_TravelBrochureApplyPasterListScRsp = 6481;
    CmdTravelBrochureType_TravelBrochureApplyPasterListCsReq = 6464;
    CmdTravelBrochureType_TravelBrochureSetCustomValueCsReq = 6404;
    CmdTravelBrochureType_TravelBrochureSelectMessageScRsp = 6491;
}

message DEDKIIFNECM {
    uint32 rotation = 1;
    uint32 EPLJKOLIPCI = 4;
    uint32 item_id = 7;
    int32 KNKFPENAPBF = 13;
    int32 APHMBADNMPH = 6;
}

message GNILAAACODB {
    uint32 item_id = 15;
    uint32 DCIJEFMACME = 14;
    uint64 unique_id = 1;
}

message HPGIGEEAGHL {
    uint32 value = 11;
}

message KJMKOJEHMII {
    OFLKOBJHFKH BEANBFLJELP = 13;
    repeated NGIOBCJINOG LFDLFDDEACA = 10;
    uint32 CFCICBNEOJB = 7;
    OLBNNJKCMAI PFOLIDBBHJN = 11;
    uint32 DCIJEFMACME = 12;
}

message NGIOBCJINOG {
    uint32 EPLJKOLIPCI = 10;
    uint32 item_id = 12;
    uint64 unique_id = 15;
    int32 APHMBADNMPH = 14;
    int32 KNKFPENAPBF = 1;
    uint32 rotation = 5;
}

enum OFLKOBJHFKH {
    OFLKOBJHFKH_CHDLPMPJLOJ = 0;
    OFLKOBJHFKH_IFEOKEGHLBL = 1;
    OFLKOBJHFKH_MDGOCIEKFJB = 2;
}

message OHMIEPPCKBJ {
    OFLKOBJHFKH DEBPJKJGCIE = 11;
    uint32 DCIJEFMACME = 7;
}

enum OLBNNJKCMAI {
    OLBNNJKCMAI_NJBGKCIGOJE = 0;
    OLBNNJKCMAI_GPNIFHBEHNB = 1;
    OLBNNJKCMAI_KCEHIDFLKLM = 2;
}

message TravelBrochureApplyPasterListCsReq {
    uint32 DCIJEFMACME = 13;
    repeated DEDKIIFNECM GMLEOJCLCFB = 14;
}

message TravelBrochureApplyPasterListScRsp {
    KJMKOJEHMII EDLLNJIEFBO = 6;
    uint32 retcode = 13;
}

message TravelBrochureGetDataCsReq {
}

message TravelBrochureGetDataScRsp {
    uint32 custom_value = 3;
    map<uint32, uint32> NNIDCBOKHFK = 14;
    map<uint32, KJMKOJEHMII> HJNJNFIBMEL = 9;
    uint32 retcode = 15;
}

message TravelBrochurePageResetCsReq {
    uint32 DCIJEFMACME = 4;
}

message TravelBrochurePageResetScRsp {
    uint32 retcode = 13;
    KJMKOJEHMII EDLLNJIEFBO = 6;
}

message TravelBrochurePageUnlockScNotify {
    uint32 DCIJEFMACME = 11;
}

message TravelBrochureSelectMessageCsReq {
    uint32 DCIJEFMACME = 12;
    uint32 CFCICBNEOJB = 5;
}

message TravelBrochureSelectMessageScRsp {
    ItemList reward = 8;
    uint32 retcode = 4;
    KJMKOJEHMII EDLLNJIEFBO = 1;
}
