syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdTextJoinType {
    CmdTextJoinType_None = 0;
    CmdTextJoinType_TextJoinBatchSaveCsReq = 3856;
    CmdTextJoinType_TextJoinQueryCsReq = 3879;
    CmdTextJoinType_TextJoinSaveScRsp = 3882;
    CmdTextJoinType_TextJoinSaveCsReq = 3834;
    CmdTextJoinType_TextJoinBatchSaveScRsp = 3891;
    CmdTextJoinType_TextJoinQueryScRsp = 3839;
}

message JCDNAGMDELF {
    uint32 PAIPJMKCCEH = 2;
    uint32 HPCIKHIBFHD = 15;
    string ANEGIMPIEHL = 1;
}

message TextJoinBatchSaveCsReq {
    repeated JCDNAGMDELF HPEDOFFJKKP = 3;
}

message TextJoinBatchSaveScRsp {
    repeated JCDNAGMDELF HPEDOFFJKKP = 11;
    uint32 retcode = 5;
}

message TextJoinQueryScRsp {
    uint32 retcode = 9;
    repeated JCDNAGMDELF HPEDOFFJKKP = 8;
}
