syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum ACKPCFFEMHB {
    ACKPCFFEMHB_NLCDGIPGFDJ = 0;
    ACKPCFFEMHB_GGEOGCBGEIH = 1;
    ACKPCFFEMHB_CNPNACJBHJG = 2;
}

enum CFCPOEDPPKB {
    CFCPOEDPPKB_ABECLEIGDEF = 0;
    CFCPOEDPPKB_CINLJPPIINL = 1;
    CFCPOEDPPKB_CHBNBPFIJPG = 2;
}

enum CmdTrainVisitorType {
    CmdTrainVisitorType_None = 0;
    CmdTrainVisitorType_GetTrainVisitorRegisterScRsp = 3726;
    CmdTrainVisitorType_GetTrainVisitorRegisterCsReq = 3798;
    CmdTrainVisitorType_TrainRefreshTimeNotify = 3756;
    CmdTrainVisitorType_ShowNewSupplementVisitorCsReq = 3772;
    CmdTrainVisitorType_GetTrainVisitorBehaviorCsReq = 3779;
    CmdTrainVisitorType_ShowNewSupplementVisitorScRsp = 3765;
    CmdTrainVisitorType_GetTrainVisitorBehaviorScRsp = 3739;
    CmdTrainVisitorType_TrainVisitorBehaviorFinishCsReq = 3734;
    CmdTrainVisitorType_TakeTrainVisitorUntakenBehaviorRewardCsReq = 3773;
    CmdTrainVisitorType_TrainVisitorBehaviorFinishScRsp = 3782;
    CmdTrainVisitorType_TakeTrainVisitorUntakenBehaviorRewardScRsp = 3799;
    CmdTrainVisitorType_TrainVisitorRewardSendNotify = 3791;
}

message FMIGHLPJAME {
    uint32 CNLGPDPICBH = 3;
}

message GetTrainVisitorRegisterCsReq {
    ACKPCFFEMHB type = 7;
}

message GetTrainVisitorRegisterScRsp {
    repeated MNKGDKAIELH NEDBIFJPBDJ = 7;
    uint32 retcode = 15;
    repeated uint32 BLKHPCPALDN = 12;
}

message MNKGDKAIELH {
    uint32 DOOACEHOPEE = 5;
    repeated uint32 HBGLEOAJJGE = 2;
    bool LHNHMFEKNDJ = 8;
    TrainVisitorStatus status = 3;
    uint32 IMHLMHKOPLD = 9;
}

message TrainRefreshTimeNotify {
    uint64 IAMKNFKCLCH = 9;
}

message TrainVisitorBehaviorFinishCsReq {
    uint32 DOOACEHOPEE = 11;
}

message TrainVisitorBehaviorFinishScRsp {
    uint32 retcode = 7;
    ItemList reward = 10;
    uint32 DOOACEHOPEE = 12;
}

message TrainVisitorRewardSendNotify {
    ItemList reward = 5;
    CFCPOEDPPKB type = 3;
    uint32 DOOACEHOPEE = 14;
}

enum TrainVisitorStatus {
    TrainVisitorStatus_None = 0;
    TrainVisitorStatus_Init = 1;
    TrainVisitorStatus_GetOn = 2;
    TrainVisitorStatus_GetOff = 3;
    TrainVisitorStatus_BeTrainMember = 4;
}
