syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AAAKPGJDCFJ {
    repeated LMKECAPDMAC skill_list = 4;
    uint32 EAFFACCBAAA = 3;
    uint32 OOCOFCBJOJD = 8;
    repeated uint32 HFJBMJHAHPE = 15;
    repeated KICEGHDKACP CFHOJCBDFPE = 11;
    uint32 DMAAMCIPPAM = 6;
}

message AHHMLENLDEF {
    CAIHACOKAJO KIOEJHHABKC = 3;
    repeated CPKCMMPFCGE LICJODMHBHA = 11;
    uint32 total_score = 15;
    BGPPDMIPDDH category = 6;
    repeated DKIGCLFPGFO COBENBOBPKD = 9;
    ECDINHEHKOJ KNMADMBFEDB = 7;
    repeated ELBILFGFDHA EEOEFLKFNIM = 13;
    uint32 CELHPMMLHGL = 12;
    uint32 score_id = 10;
    repeated BDGGEHGLFAC JHFBMEKEMMK = 14;
}

message AIOCPFLCNLB {
    repeated IDBCDHIOKEG FOOMIPJJKOG = 6;
    uint32 GKENFCLLLJC = 7;
    uint32 progress = 11;
    uint32 area_id = 14;
}

message AMDOMPIGBPG {
}

message AMEJEFBKPCH {
    repeated MDJAPHPOABA KFNMIEMBJGD = 1;
    LHLBGJLFFKK event_type = 15;
    uint32 event_id = 4;
}

message AreaStepInfo {
    uint32 GKENFCLLLJC = 13;
    repeated IDBCDHIOKEG BKKLGCLOBCD = 1;
}

message BAKFOMADBCJ {
    uint32 BKPFHFGIEPE = 14;
}

message BDGGEHGLFAC {
    TrainPartyMtSkillBriefType skill_type = 10;
    uint32 skill_id = 13;
    uint32 KLKAIFEDLNK = 8;
}

enum BGPPDMIPDDH {
    BGPPDMIPDDH_IIHEIDCFALE = 0;
    BGPPDMIPDDH_ODFNPPACBCI = 1;
    BGPPDMIPDDH_ABNPBGJGAHD = 2;
    BGPPDMIPDDH_HCFKOJHOLIK = 3;
    BGPPDMIPDDH_BCDLKDKDAFH = 4;
    BGPPDMIPDDH_GIOFBNENIJM = 5;
    BGPPDMIPDDH_MKMJJPHDOBH = 6;
    BGPPDMIPDDH_KOGGGJLBHEN = 7;
    BGPPDMIPDDH_NNPJFBFILEL = 8;
}

message BHBJLGFHLHM {
    uint32 LNLOHDJIFPK = 1;
    ECDINHEHKOJ KNMADMBFEDB = 6;
    IEDLKIGJLEM EMGMFOBLAFN = 9;
    bool DOFBGHGHDJA = 3;
}

message BHOPIKPAMPJ {
    uint32 area_id = 3;
    AreaDynamicInfo OOFPPPCEIDP = 13;
}

message CAIHACOKAJO {
    uint32 ODOBGIEGGEO = 8;
    ItemList ELMCGFMGILI = 9;
    repeated uint32 AEGPLACJFIO = 4;
}

message CBJGONHJAAC {
    repeated uint32 FOOMIPJJKOG = 11;
    uint32 area_id = 8;
}

message CEFEIJFPCKE {
    repeated uint32 switch_list = 11;
    uint32 MNLAMKJIAOC = 3;
}

message CKPNGMLENFA {
    repeated uint32 LKNGKJCFFBH = 9;
}

message CNFPBAJNIEL {
    uint32 area_id = 13;
    uint32 JBEEKBJMIIA = 1;
}

message CNLAOMCKFKD {
    uint32 param = 14;
    uint32 unique_id = 3;
    uint32 NDEBMEGNCKN = 6;
    uint32 GDNEHLEOMOM = 12;
}

message CPKCMMPFCGE {
    uint32 unique_id = 9;
    repeated BDGGEHGLFAC PBFNPODNDID = 15;
    uint32 DDAGDNNDCDI = 2;
}

enum CmdTrainPartyType {
    CmdTrainPartyType_None = 0;
    CmdTrainPartyType_TrainPartyUpdatePosEnvScRsp = 8023;
    CmdTrainPartyType_TrainPartyBuildRoomScNotify = 8021;
    CmdTrainPartyType_TrainPartyGamePlayStartScRsp = 8009;
    CmdTrainPartyType_TrainPartySetBadgeAutoFillCsReq = 8089;
    CmdTrainPartyType_TrainPartyGamePlaySettleNotify = 8024;
    CmdTrainPartyType_TrainPartyBuildingUpdateNotify = 8049;
    CmdTrainPartyType_TrainPartyTakeBuildLevelAwardScRsp = 8001;
    CmdTrainPartyType_TrainPartyAddBuildDynamicBuffScRsp = 8058;
    CmdTrainPartyType_TrainPartySettleNotify = 8098;
    CmdTrainPartyType_TrainPartyUpdatePosEnvCsReq = 8005;
    CmdTrainPartyType_TrainPartyBuildSelfDisplayAreaDiyScNotify = 8060;
    CmdTrainPartyType_TrainPartyTakeBuildLevelAwardCsReq = 8044;
    CmdTrainPartyType_TrainPartyGetDataCsReq = 8034;
    CmdTrainPartyType_TrainPartyUseCardCsReq = 8079;
    CmdTrainPartyType_TrainPartyBuildDiyCsReq = 8004;
    CmdTrainPartyType_TrainPartyBuildDiyScRsp = 8062;
    CmdTrainPartyType_TrainPartyGetDataScRsp = 8082;
    CmdTrainPartyType_TrainPartyBuildSelfDisplayAreaDiyCsReq = 8002;
    CmdTrainPartyType_TrainPartyHandlePendingActionScRsp = 8065;
    CmdTrainPartyType_TrainPartyHandlePendingActionCsReq = 8072;
    CmdTrainPartyType_TrainPartyUseCardScRsp = 8039;
    CmdTrainPartyType_TrainPartyBuildStartStepCsReq = 8080;
    CmdTrainPartyType_TrainPartyBuildStartStepScRsp = 8071;
    CmdTrainPartyType_TrainPartyAddBuildDynamicBuffCsReq = 8008;
    CmdTrainPartyType_TrainPartyMoveScNotify = 8056;
    CmdTrainPartyType_TrainPartyLeaveCsReq = 8064;
    CmdTrainPartyType_TrainPartyLeaveScRsp = 8081;
    CmdTrainPartyType_TrainPartyGamePlayStartCsReq = 8066;
    CmdTrainPartyType_TrainPartySyncUpdateScNotify = 8073;
    CmdTrainPartyType_TrainPartyEnterScRsp = 8015;
    CmdTrainPartyType_TrainPartyEnterCsReq = 8088;
    CmdTrainPartyType_TrainPartySetBadgeAutoFillScRsp = 8070;
    CmdTrainPartyType_TrainPartyBuildSelfDisplayAreaDiyScRsp = 8030;
}

message DJBJMHKMOMB {
    BGPPDMIPDDH JAPPKIFAHPH = 13;
    uint32 level = 2;
}

message DJKACFOFFAH {
    uint32 OENPDHNALLA = 8;
    repeated BDGGEHGLFAC CIKDPHGPIGK = 11;
    repeated ELBILFGFDHA EEOEFLKFNIM = 9;
    repeated DKIGCLFPGFO COBENBOBPKD = 1;
}

message DKIGCLFPGFO {
    uint32 num = 12;
    uint32 passenger_id = 6;
}

message DMFMMKJOCNJ {
    LMKECAPDMAC CBKINAFEDJC = 6;
}

message DOCMDCPJIEH {
    uint32 BHEJCEJHLIB = 6;
    uint32 star_num = 4;
}

message ECDINHEHKOJ {
    uint32 EBENOMJDOOF = 13;
    uint32 FJONJANIOIK = 11;
    uint32 GMBDHLCGOBI = 9;
    uint32 CGIGAAKLCKM = 4;
    uint32 GAIEFCFBNPA = 12;
    repeated uint32 BHKJIFAFHFN = 7;
}

message ELBILFGFDHA {
    uint32 unique_id = 6;
    uint32 GPIGNHPKFFB = 2;
    uint32 passenger_id = 9;
}

message EMEEKFKDPFD {
    repeated uint32 GHPFANGEMAN = 8;
}

message EPHKIEHONGB {
    PNLLCBKLBLE HEBCOOCAHOL = 15;
    uint32 IDBDBICPBBG = 3;
    AAAKPGJDCFJ NIMJPDMFBHN = 11;
    HOKCDEEABII LDAEAHOHMBB = 12;
    HJLECIIEKGI KAIDKOHAAGI = 14;
}

message FAHBCNPNBNC {
    uint32 NLJMJCGFFMD = 12;
}

message FFMMFBMOBEG {
    FAHBCNPNBNC CNGOKIKBGAJ = 364;
    PPLKBFMCGLD LLCOCEJHKLD = 1654;
    AIOCPFLCNLB MFNELHNLNGI = 1487;
    DOCMDCPJIEH FHBMGFFBOLP = 1311;
    NFNKNNFJILK FCKNCNDEKAE = 398;
    CNFPBAJNIEL NEFBGMNGKBN = 1401;
    IOJLDHECLIH BJMFDAFLNEC = 992;
    BAKFOMADBCJ LCNJLPDDFEE = 596;
    IGNNGONLFAJ FPMNNMMPOKL = 227;
    OIIPJFDNPAH ODGCBIDOGND = 1145;
}

message FHLHOEPCKAG {
}

message FLPMBEPBPGN {
    repeated LMKECAPDMAC skill_list = 4;
}

message GAGGCODGDLB {
    uint32 prop_id = 1;
    int64 time = 6;
}

message GMCPCKHHPOB {
    MKIIBIMNIGK src = 6;
    IEDLKIGJLEM EMGMFOBLAFN = 641;
    HBACEFIACOI BEEMEFMJEAA = 157;
    HPAGFCCNCHE BPNEOPLHEBK = 1994;
    MJMPOLBBFNA OEDJEOAECAC = 1800;
    MEDCHLCIOEI JPBBDGJBHKN = 870;
    DMFMMKJOCNJ CNLGPLJFMKA = 827;
    BHBJLGFHLHM BELKGEJFOIF = 528;
    FLPMBEPBPGN EFJKKFNNCGN = 672;
    MGOLOIGOAMB KEOOMCJAHMG = 1625;
    EMEEKFKDPFD HOHNMNGNCMG = 511;
}

message HBACEFIACOI {
    repeated LMAKFCIHCMA EBAIMMGLGFO = 12;
}

message HELJNONBKPH {
    uint32 EIKLMFPMJJD = 9;
    int64 expire_time = 11;
}

message HJLECIIEKGI {
    uint32 queue_position = 4;
    AMEJEFBKPCH KLONPDNKBJF = 1583;
    OGAFHKMJELA AKDJGIJMHPJ = 701;
    JEBGFIJPAPG LGBJDFHBIND = 1837;
}

message HLNFNACOFFF {
    repeated CEFEIJFPCKE DICAIJCHICB = 9;
    repeated KICEGHDKACP CFHOJCBDFPE = 13;
    uint32 KHFHCLBHAPD = 8;
}

message HOKCDEEABII {
    uint32 IDCJPIJHNCL = 1;
    ECDINHEHKOJ KNMADMBFEDB = 3;
    repeated CNLAOMCKFKD IEDKELDFHLP = 7;
    uint32 FJPEIFMFPAN = 15;
}

message HPAGFCCNCHE {
    HJLECIIEKGI FMIGOKIDKJL = 6;
}

message IAKFBFJCHFB {
    uint32 card_id = 3;
    uint32 unique_id = 5;
    uint32 EAFFACCBAAA = 13;
}

message IBNCBEPCAPF {
}

message IDBCDHIOKEG {
    JIIEHEBIBMO status = 2;
    uint32 DNLIGEOFPEL = 7;
}

message IEDLKIGJLEM {
    repeated IAKFBFJCHFB LONFKFCFDND = 9;
}

message IGNNGONLFAJ {
    repeated CBJGONHJAAC area_list = 8;
}

message IOJLDHECLIH {
    int64 time = 13;
    uint32 diy_dynamic_id = 5;
}

message JCPMKHCPCPN {
    uint32 GPIGNHPKFFB = 10;
    uint32 DMJGCIIBPJK = 9;
}

message JEBGFIJPAPG {
    repeated LMKECAPDMAC PBLDCDDFKIE = 13;
    uint32 JGHCFCGEIEO = 11;
}

enum JIIEHEBIBMO {
    JIIEHEBIBMO_CIJCGPBOFJP = 0;
    JIIEHEBIBMO_BHPKNHCHOJF = 1;
    JIIEHEBIBMO_HEIMDAGNDLO = 2;
    JIIEHEBIBMO_MJHBDAKIJDP = 3;
}

message KDBJBEJPGOO {
    repeated LMKECAPDMAC skill_list = 7;
}

message KICEGHDKACP {
    uint32 passenger_id = 5;
    JCPMKHCPCPN GNBKDCHLDGL = 15;
    uint32 FPKJONKIFLI = 3;
}

enum LHLBGJLFFKK {
    LHLBGJLFFKK_KGHKHLKDEBK = 0;
    LHLBGJLFFKK_AKGDAFFKANP = 1;
    LHLBGJLFFKK_KNJDGIMKJME = 2;
    LHLBGJLFFKK_DODHMJBMHAF = 3;
}

message LMAKFCIHCMA {
    uint32 passenger_id = 4;
    JCPMKHCPCPN GNBKDCHLDGL = 8;
}

message LMKECAPDMAC {
    uint32 skill_level = 4;
    uint32 max_level = 5;
    uint32 skill_id = 12;
}

message MDJAPHPOABA {
    bool is_selected = 4;
    uint32 HAFOKMHCGFM = 8;
}

message MDOIMCNFDLC {
    uint32 event_id = 1;
}

message MEDCHLCIOEI {
    repeated CNLAOMCKFKD IEDKELDFHLP = 10;
}

message MGOLOIGOAMB {
    TrainPartyPassenger IALIECEAFJB = 2;
}

message MJMPOLBBFNA {
    uint32 EAFFACCBAAA = 12;
}

enum MKIIBIMNIGK {
    MKIIBIMNIGK_EFBKDLIJKAG = 0;
    MKIIBIMNIGK_MGFHDNJAKKM = 1;
    MKIIBIMNIGK_NGAAHFBKMFM = 2;
    MKIIBIMNIGK_EBJCJAJDINC = 3;
    MKIIBIMNIGK_IDMGAGLJMLK = 4;
    MKIIBIMNIGK_IPFPPCLNIHO = 5;
}

message MOCNDOCEOJM {
    repeated uint32 LKNGKJCFFBH = 12;
}

message NFNKNNFJILK {
    uint32 IOJOIOHIEAB = 13;
}

message OGAFHKMJELA {
    uint32 total_score = 3;
    repeated DKIGCLFPGFO COBENBOBPKD = 4;
    repeated DJBJMHKMOMB JPOOHONHFJI = 15;
    uint32 OENPDHNALLA = 12;
    repeated ELBILFGFDHA EEOEFLKFNIM = 6;
    uint32 reach_point = 2;
    uint32 CELHPMMLHGL = 5;
    uint32 CLMFKHAJKLH = 7;
}

message OLBKADIKIGL {
    HLNFNACOFFF CBFPJAJAKGI = 7;
}

message PFAIANENDEE {
    uint32 BFPAFELCMGF = 11;
}

message PNLLCBKLBLE {
    bool DOFBGHGHDJA = 8;
    IEDLKIGJLEM LONFKFCFDND = 10;
    uint32 LNLOHDJIFPK = 4;
}

message PPLKBFMCGLD {
    repeated IDBCDHIOKEG FOOMIPJJKOG = 7;
    uint32 BPGBEEOHPLJ = 2;
}

message TrainPartyArea {
    repeated uint32 static_prop_id_list = 10;
    AreaStepInfo area_step_info = 2;
    uint32 progress = 12;
    repeated uint32 step_id_list = 9;
    repeated uint32 verify_step_id_list = 6;
    uint32 area_id = 7;
    repeated AreaDynamicInfo dynamic_info = 3;
}

message TrainPartyBuildDiyCsReq {
    uint32 diy_dynamic_id = 1;
    uint32 dice_slot_id = 3;
    uint32 area_id = 6;
}

message TrainPartyBuildDiyScRsp {
    uint32 area_id = 1;
    uint32 retcode = 10;
    repeated BHOPIKPAMPJ JKPJFKCBIEM = 4;
}

message TrainPartyBuildRoomScNotify {
    TrainPartyInfo CPMHKECPBOJ = 15;
}

message TrainPartyBuildSelfDisplayAreaDiyCsReq {
    OIIPJFDNPAH ACLKMFCDMED = 7;
}

message TrainPartyBuildSelfDisplayAreaDiyScNotify {
    TrainPartyInfo train_party_data = 7;
}

message TrainPartyBuildSelfDisplayAreaDiyScRsp {
    OIIPJFDNPAH ACLKMFCDMED = 1;
    uint32 retcode = 11;
}

message TrainPartyBuildStartStepCsReq {
    uint32 area_id = 14;
    uint32 GKENFCLLLJC = 11;
    uint32 DNLIGEOFPEL = 3;
    AreaDynamicInfo PFICNBHIHBA = 5;
}

message TrainPartyBuildStartStepScRsp {
    uint32 retcode = 13;
    uint32 cur_fund = 15;
}

message TrainPartyBuildingUpdateNotify {
    repeated FFMMFBMOBEG OOABOBHEKEH = 12;
}

message TrainPartyData {
    uint32 record_id = 11;
    bool LNMFDPFOKFF = 8;
    TrainPartyPassengerInfo passenger_info = 5;
    uint32 unlock_area_num = 3;
    EPHKIEHONGB HCJJPLKELGC = 7;
    TrainPartyInfo train_party_info = 9;
}

message TrainPartyGamePlaySettleNotify {
    TrainPartyPassengerInfo ENBJCMPCMLK = 3;
    repeated uint32 CEJPCMHEEMN = 14;
    uint32 record_id = 8;
    uint32 unlock_area_num = 1;
}

message TrainPartyGamePlayStartCsReq {
    uint32 IDBDBICPBBG = 7;
}

message TrainPartyGamePlayStartScRsp {
    EPHKIEHONGB FJKHJADDKLD = 7;
    uint32 retcode = 13;
}

message TrainPartyGetDataCsReq {
}

message TrainPartyGetDataScRsp {
    uint32 retcode = 11;
    TrainPartyData train_party_data = 1;
}

message TrainPartyHandlePendingActionCsReq {
    uint32 queue_position = 14;
    MDOIMCNFDLC KLONPDNKBJF = 1974;
    PFAIANENDEE LGBJDFHBIND = 2046;
    CKPNGMLENFA NELLGPKHIKE = 1213;
    MOCNDOCEOJM NMEFKABDHAN = 238;
}

message TrainPartyHandlePendingActionScRsp {
    HLNFNACOFFF CBFPJAJAKGI = 6;
    uint32 retcode = 13;
    bool HMNAOPOKLGE = 4;
    uint32 queue_position = 14;
    OLBKADIKIGL EEBFCLFOBPG = 1710;
    KDBJBEJPGOO OMLNCJEGJAC = 829;
    AHHMLENLDEF BHMJDNEOBNK = 1034;
    DJKACFOFFAH IGMEPOBLFFB = 997;
}

message TrainPartyInfo {
    uint32 cur_fund = 6;
    uint32 JJGKIPDGOGP = 3;
    uint32 star_num = 10;
    uint32 BHEJCEJHLIB = 4;
    OIIPJFDNPAH CMCNNJKJNPK = 13;
    uint32 BKPFHFGIEPE = 5;
    bool IEEAPCFKOJC = 14;
    repeated HELJNONBKPH FOOPKFCIHBA = 9;
    repeated GAGGCODGDLB MHABCMLHCGD = 8;
    repeated TrainPartyArea area_list = 11;
}

message TrainPartyLeaveScRsp {
    uint32 PLDKENJLKME = 12;
    EPHKIEHONGB LIADDJKCKFA = 6;
}

message TrainPartyMoveScNotify {
    repeated CNLAOMCKFKD JABPLBJAKKM = 13;
    uint32 DNGKGLFMGGE = 8;
}

enum TrainPartyMtSkillBriefType {
    TrainPartyMtSkillBriefType_KMtSkillNone = 0;
    TrainPartyMtSkillBriefType_KMtSkillModifyBase = 1;
    TrainPartyMtSkillBriefType_KMtSkillModifyRatio = 2;
    TrainPartyMtSkillBriefType_KMtSkillMultiplyRatio = 3;
    TrainPartyMtSkillBriefType_KMtSkillSelfDestroy = 4;
}

message TrainPartyPassenger {
    repeated uint32 GHPFANGEMAN = 6;
    uint32 record_id = 2;
    uint32 passenger_id = 9;
    bool JGDNJOFHCNC = 4;
}

message TrainPartyPassengerInfo {
    repeated uint32 GHPFANGEMAN = 15;
    repeated TrainPartyPassenger passenger_info_list = 1;
}

message TrainPartySetBadgeAutoFillCsReq {
    bool PELJACANAFH = 7;
}

message TrainPartySetBadgeAutoFillScRsp {
    uint32 retcode = 1;
    bool PELJACANAFH = 14;
}

message TrainPartySettleNotify {
    uint32 FGIHKKKOGJD = 13;
    HLNFNACOFFF CBFPJAJAKGI = 8;
}

message TrainPartySyncUpdateScNotify {
    repeated GMCPCKHHPOB JKPJFKCBIEM = 11;
}

message TrainPartyTakeBuildLevelAwardCsReq {
}

message TrainPartyTakeBuildLevelAwardScRsp {
    uint32 retcode = 5;
    uint32 FPHFHCGNNGM = 8;
    ItemList item_list = 14;
}

message TrainPartyUseCardCsReq {
    uint32 FGIHKKKOGJD = 3;
}

message TrainPartyUseCardScRsp {
    uint32 retcode = 7;
    uint32 FGIHKKKOGJD = 1;
}
