syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message AOMMAFEOBOA {
    uint32 id = 13;
    bool has_passed = 12;
}

enum CmdTarotBookType {
    CmdTarotBookType_None = 0;
    CmdTarotBookType_TarotBookGetDataCsReq = 8145;
    CmdTarotBookType_TarotBookSyncDataScNotify = 8144;
    CmdTarotBookType_TarotBookFinishStoryScRsp = 8154;
    CmdTarotBookType_TarotBookFinishInteractionCsReq = 8150;
    CmdTarotBookType_TarotBookUnlockStoryCsReq = 8149;
    CmdTarotBookType_TarotBookOpenPackScRsp = 8153;
    CmdTarotBookType_TarotBookModifyEnergyScNotify = 8147;
    CmdTarotBookType_TarotBookFinishInteractionScRsp = 8158;
    CmdTarotBookType_TarotBookGetDataScRsp = 8155;
    CmdTarotBookType_TarotBookUnlockInteractionScRsp = 8159;
    CmdTarotBookType_TarotBookMultiOpenPackAndUnlockStoryCsReq = 8143;
    CmdTarotBookType_TarotBookUnlockInteractionCsReq = 8156;
    CmdTarotBookType_TarotBookOpenPackCsReq = 8160;
    CmdTarotBookType_TarotBookUnlockStoryScRsp = 8152;
    CmdTarotBookType_TarotBookMultiOpenPackAndUnlockStoryScRsp = 8142;
    CmdTarotBookType_TarotBookFinishStoryCsReq = 8151;
}

message GMBGLBHEFDI {
    repeated uint32 HKFDNIFACFH = 2;
    repeated uint32 FPPJGGJCJIH = 8;
}

message LIONJNJEBBF {
    uint32 level = 11;
    uint32 id = 15;
}

message OHCFIOOIKND {
    repeated AOMMAFEOBOA ILKLAJBGKKI = 7;
    repeated LIONJNJEBBF LNFCBCDNFDL = 11;
}

message TarotBookFinishInteractionCsReq {
    uint32 INJAGFDOFEJ = 13;
}

message TarotBookFinishInteractionScRsp {
    uint32 INJAGFDOFEJ = 5;
    uint32 retcode = 4;
}

message TarotBookFinishStoryCsReq {
    uint32 LNAHJENGELA = 1;
}

message TarotBookFinishStoryScRsp {
    uint32 retcode = 5;
    uint32 LNAHJENGELA = 2;
    OHCFIOOIKND BBEMIGELGJC = 6;
}

message TarotBookGetDataCsReq {
}

message TarotBookGetDataScRsp {
    uint32 LOCEBOCJGEC = 2;
    uint32 retcode = 4;
    OHCFIOOIKND BBEMIGELGJC = 9;
    uint32 HBLKMBHGLNO = 13;
    uint32 energy_info = 15;
    map<uint32, uint32> IMNNLHCAKML = 14;
    map<uint32, uint32> IJOJMJOMELA = 6;
    GMBGLBHEFDI interaction = 7;
}

message TarotBookModifyEnergyScNotify {
    uint32 energy_info = 2;
    uint32 sub_mission_id = 14;
}

message TarotBookMultiOpenPackAndUnlockStoryCsReq {
}

message TarotBookMultiOpenPackAndUnlockStoryScRsp {
    uint32 LOCEBOCJGEC = 9;
    OHCFIOOIKND BBEMIGELGJC = 13;
    map<uint32, uint32> IJOJMJOMELA = 7;
    map<uint32, uint32> IMNNLHCAKML = 10;
    repeated uint32 LNOAAOAFJJE = 11;
    uint32 retcode = 4;
    uint32 energy_info = 12;
    uint32 HBLKMBHGLNO = 15;
}

message TarotBookOpenPackCsReq {
}

message TarotBookOpenPackScRsp {
    uint32 HBLKMBHGLNO = 14;
    uint32 energy_info = 5;
    uint32 LOCEBOCJGEC = 8;
    map<uint32, uint32> KMNLFHLINFB = 3;
    uint32 retcode = 15;
    map<uint32, uint32> NLAANGNGAIA = 4;
}

message TarotBookSyncDataScNotify {
    map<uint32, uint32> IMNNLHCAKML = 6;
    uint32 LOCEBOCJGEC = 3;
    OHCFIOOIKND BBEMIGELGJC = 5;
    uint32 energy_info = 8;
    map<uint32, uint32> IJOJMJOMELA = 2;
    uint32 HBLKMBHGLNO = 14;
}

message TarotBookUnlockInteractionScRsp {
    repeated uint32 CLNOMEFFHKG = 10;
    uint32 retcode = 2;
}

message TarotBookUnlockStoryScRsp {
    LIONJNJEBBF CLLIKPONHOC = 2;
    repeated uint32 BHFHFONGHML = 10;
    map<uint32, uint32> IJOJMJOMELA = 13;
    uint32 retcode = 3;
    map<uint32, uint32> IMNNLHCAKML = 7;
}
