syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdWolfBroType {
    CmdWolfBroType_None = 0;
    CmdWolfBroType_WolfBroGameUseBulletCsReq = 6517;
    CmdWolfBroType_WolfBroGameExplodeMonsterScRsp = 6518;
    CmdWolfBroType_QuitWolfBroGameScRsp = 6537;
    CmdWolfBroType_WolfBroGameUseBulletScRsp = 6519;
    CmdWolfBroType_StartWolfBroGameScRsp = 6529;
    CmdWolfBroType_WolfBroGamePickupBulletCsReq = 6512;
    CmdWolfBroType_StartWolfBroGameCsReq = 6536;
    CmdWolfBroType_QuitWolfBroGameCsReq = 6532;
    CmdWolfBroType_WolfBroGameExplodeMonsterCsReq = 6542;
    CmdWolfBroType_GetWolfBroGameDataScRsp = 6538;
    CmdWolfBroType_WolfBroGameActivateBulletCsReq = 6507;
    CmdWolfBroType_WolfBroGameDataChangeScNotify = 6521;
    CmdWolfBroType_ArchiveWolfBroGameCsReq = 6544;
    CmdWolfBroType_GetWolfBroGameDataCsReq = 6520;
    CmdWolfBroType_WolfBroGamePickupBulletScRsp = 6501;
    CmdWolfBroType_ArchiveWolfBroGameScRsp = 6524;
    CmdWolfBroType_RestoreWolfBroGameArchiveScRsp = 6522;
    CmdWolfBroType_RestoreWolfBroGameArchiveCsReq = 6508;
    CmdWolfBroType_WolfBroGameActivateBulletScRsp = 6514;
}

message DKJBGINLBPP {
    uint32 id = 8;
}

message LIKMPNFOKFF {
    uint32 id = 14;
}

message LJFEONHOKAG {
    uint32 id = 7;
}

message PHPEPPKFMJO {
    uint32 config_id = 7;
    uint32 group_id = 3;
}
