syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

// ========================= Adventure =========================

message NAJKNJLJPEP {
    uint32 LDPBPHBBFGF = 2;
    uint32 HFPLJFBOPEH = 8;
}

// ========================= AetherDivide =========================

message AetherDivideBattleInfo {
    repeated AetherAvatarInfo battle_avatar_list = 8;
    uint32 stage_id = 15;
    bool encrypt_result = 6;
    uint32 battle_id = 13;
    repeated SceneMonsterWave monster_wave_list = 10;
    repeated BattleBuff buff_list = 11;
    uint32 logic_random_seed = 9;
}

message AssistMonsterEntityInfo {
    repeated uint32 entity_id_list = 8;
}

message SpBarInfo {
    uint32 cur_sp = 1;
    uint32 max_sp = 2;
}

// ========================= AiPam =========================

message ChatMessageData {
    uint64 create_time = 4;
    repeated MessageChatData message_datas = 9;
    EKNABKLPEEL CKHPFFENOBE = 10;
    EKNABKLPEEL BKOALKHDLOB = 11;
}

message MessageChatData {
    MsgType message_type = 1;
    ChatData chat_data = 2;
}

// ========================= Avatar =========================

message AetherAvatarInfo {
    uint32 id = 1;
    uint32 index = 2;
    uint32 promotion = 3;
    repeated uint32 LICLEEICAOE = 4;
    AABGIFAEEEK AGBMHEMIAIH = 5;
    SpBarInfo sp_bar = 6;
}

message Avatar {
    uint64 first_met_time_stamp = 13;
    uint32 cur_multi_path_avatar_type = 9;
    uint32 level = 11;
    uint32 exp = 7;
    repeated uint32 has_taken_promotion_reward_list = 15;
    uint32 base_avatar_id = 10;
    uint32 promotion = 4;
    bool is_marked = 1;
    uint32 equipment_unique_id = 8;
}

message AvatarPathData {
    uint32 dressed_skin_id = 5;
    repeated AvatarPathSkillTree avatar_path_skill_tree = 11;
    uint32 unk_enhanced_id = 3;
    uint64 unlock_time = 15;
    uint32 avatar_id = 9;
    uint32 rank = 2;
    uint32 path_equipment_id = 14;
    repeated EquipRelic equip_relic_list = 13;
}

message AvatarPathSkillTree {
    uint32 point_id = 14;
    uint32 level = 3;
}

message CJLCPMDGIBO {
    repeated uint32 EAKOLIJOEPA = 1;
}

message IBKDHOIDKJA {
    uint32 HBPKGODMJNK = 641;
    repeated uint32 KMMNJBAEMAB = 7;
    bool OCPLGILCPPN = 858;
    uint32 CFCNIPLEKON = 1427;
    PJIMOBKFDNP status = 1;
    bool is_taken_reward = 13;
    repeated uint32 KCHPDJINNLH = 3;
    uint32 CLALLJOACNF = 1318;
    int64 finish_time = 8;
    uint32 world_level = 5;
    CEDCMIMKJHK BIHNCKPBBOA = 1019;
    uint32 MODFNPMCAAN = 9;
    uint32 MNMJCNOLIII = 12;
    bool HHFIEKHFNFP = 6;
    repeated PileItem NLMEEHNNOCP = 14;
    uint32 KAMECNCKNAB = 15;
    bool NFFOAHMFCMD = 1488;
    uint32 PDHOMKKMEME = 4;
    repeated uint32 ELKOPDBOMAD = 10;
    uint32 ACDPGFLDFHK = 1544;
    int64 start_time = 11;
}

message ItemCost {
    PileItem pile_item = 13;
    uint32 equipment_unique_id = 10;
    uint32 relic_unique_id = 6;
}

enum MultiPathAvatarType {
    MultiPathAvatarType_None = 0;
    MultiPathAvatarType_Mar7ThKnightType = 1001;
    MultiPathAvatarType_Mar7ThRogueType = 1224;
    MultiPathAvatarType_BoyWarriorType = 8001;
    MultiPathAvatarType_GirlWarriorType = 8002;
    MultiPathAvatarType_BoyKnightType = 8003;
    MultiPathAvatarType_GirlKnightType = 8004;
    MultiPathAvatarType_BoyShamanType = 8005;
    MultiPathAvatarType_GirlShamanType = 8006;
    MultiPathAvatarType_BoyMemoryType = 8007;
    MultiPathAvatarType_GirlMemoryType = 8008;
    MultiPathAvatarType_BoyElationType = 8009;
    MultiPathAvatarType_GirlElationType = 8010;
}

message NKDNFDCFNCP {
    PileItem FMOKFKBAEII = 4;
    repeated PileItem HJLENJODAMN = 11;
}

// ========================= B51Racing =========================

message HCAJDCFFEAE {
    uint32 IBEEKBHKHJI = 3;
    uint32 GPDJNNDEENJ = 14;
    bool KMJIGBPNFDK = 12;
    uint32 JIODKLHNMEO = 13;
    uint32 IFNGOALKHBJ = 1;
    uint32 AOIBFNMMLGH = 6;
    uint32 CFCJBCIJKAJ = 15;
    uint32 KFFNAJLFAII = 8;
}

enum HPICFNLLMCO {
    HPICFNLLMCO_NLCDGIPGFDJ = 0;
    HPICFNLLMCO_CIHFGJDCHIA = 1;
    HPICFNLLMCO_INCLHHDFCEL = 2;
    HPICFNLLMCO_EMMGHDLIPOH = 3;
}

// ========================= Battle =========================

enum AABGIFAEEEK {
    AABGIFAEEEK_OCAJFLCAMNA = 0;
    AABGIFAEEEK_AONENHHFNOD = 1;
    AABGIFAEEEK_AOIAAGNAFIO = 2;
}

message AOFMDLLDIHG {
    uint32 skill_id = 1;
    double delay = 2;
    repeated uint32 battle_target_list = 3;
    double damage = 4;
}

message AvatarSkillTree {
    uint32 point_id = 1;
    uint32 level = 2;
}

message BCCONKJHDJL {
    GridFightDropType FKKGLFOHGGA = 1;
    uint32 FNLMKJLKLFH = 2;
    uint32 num = 3;
    AOHKKFHDALO param = 5;
}

message BattleAvatar {
    AvatarType avatar_type = 1;
    uint32 id = 2;
    uint32 level = 3;
    uint32 rank = 4;
    uint32 index = 5;
    repeated AvatarSkillTree skilltree_list = 6;
    repeated BattleEquipment equipment_list = 7;
    uint32 hp = 8;
    uint32 promotion = 10;
    repeated BattleRelic relic_list = 11;
    uint32 world_level = 12;
    uint32 assist_uid = 13;
    AMEMKFNABGG ALNJENINBPN = 15;
    SpBarInfo sp_bar = 16;
    uint32 GDIMKFNECOK = 17;
    repeated AvatarSkillTree CHEFGGPEJKL = 18;
    uint32 enhanced_id = 19;
}

message BattleBuff {
    uint32 id = 1;
    uint32 level = 2;
    uint32 owner_index = 3;
    uint32 wave_flag = 4;
    repeated uint32 target_index_list = 5;
    map<string, float> dynamic_values = 6;
}

enum BattleEndStatus {
    BATTLE_END_NONE = 0;
    BATTLE_END_WIN = 1;
    BATTLE_END_LOSE = 2;
    BATTLE_END_QUIT = 3;
}

message BattleEquipment {
    uint32 id = 1;
    uint32 level = 2;
    uint32 promotion = 3;
    uint32 rank = 4;
}

message BattleEventBattleInfo {
    uint32 battle_event_id = 1;
    BattleEventProperty status = 2;
    repeated AOFMDLLDIHG skill_info = 3;
}

message BattleEventProperty {
    SpBarInfo sp_bar = 2;
}

message BattleGridFightEquipInfo {
    uint32 grid_fight_equipment_id = 2;
    map<uint32, uint32> convert_property_to_fixpoint = 4;
    uint32 unique_id = 5;
    map<uint32, double> OPEMKBPFFDN = 6;
    NKAFNCBDJAH PMAEBPKJCLL = 8;
}

message BattleGridFightSpecialBattleInfo {
    uint32 cur_level_id = 1;
    uint32 PFBDNGHMBII = 2;
    uint32 rogue_money = 3;
    repeated GFNAPELNFIC ICOPGAJFKHE = 4;
    repeated GFNAPELNFIC OMCLLCNKAHE = 5;
    repeated uint32 LLIFKMANADH = 6;
    EAENAFJCEFD HPHJGIEKMAA = 7;
    repeated uint32 FPONJJMJFAE = 8;
    uint32 grid_fight_cur_level_exp = 9;
    uint32 LJGPHGDDBKE = 11;
    repeated uint32 DCKIGAHCNMJ = 12;
    uint32 cur_wave = 14;
    repeated OEMOIGDNPNP LONFKFCFDND = 17;
    repeated HLFOOKANNDE HNJPIDFKNIK = 18;
    repeated uint32 BLLKCBJGAEB = 19;
    bool CHKBOLNIPMO = 20;
    uint32 GMBPGBIJGGE = 21;
    IDJIAGLCAPE INPNMBJNPPK = 22;
    uint32 NBKKKKKEMEH = 23;
    repeated uint32 PMLEEGOGPIF = 25;
    repeated PMNLJEJKLOD GMGPFAIONNG = 26;
    uint32 LJHKBJIBCGK = 27;
}

message BattleGridFightTraitCoreRoleInfo {
    uint32 role_id = 1;
    uint32 unique_id = 2;
}

message BattleGridFightTraitEffectInfo {
    uint32 effect_id = 1;
    BattleGridFightTraitCoreRoleInfo trait_core_role = 101;
    BattleGridFigntAvatarCoreRoleInfo avatar_core_info = 102;
    GridFightTraitEffectLevelInfo trait_effect_level_info = 103;
    KFMKBMJPEIC JLCLHAKNMLL = 104;
    CPMNHNHKLBK LFIDNOAECMN = 105;
}

message BattleGridFigntAvatarCoreRoleInfo {
    repeated uint32 grid_fight_avatar_list = 1;
    repeated uint32 LKNGKJCFFBH = 2;
}

message BattleRelic {
    uint32 id = 1;
    uint32 level = 2;
    uint32 main_affix_id = 3;
    repeated RelicAffix sub_affix_list = 4;
    uint32 unique_id = 5;
    uint32 set_id = 6;
    uint32 type = 7;
    uint32 rarity = 8;
}

message BattleRogueMagicInfo {
    IJLEFNJPFKP OOPCPMANCBO = 1;
    BLJEJFMKEII detail_info = 2;
}

message BattleTargetList {
    repeated BattleTarget battle_target_list = 1;
}

message LMDPKOELKFL {
    repeated uint32 relic_ids = 14;
    ItemList return_item_list = 6;
    bool ABFCDBOCMCF = 12;
}

message NIFPICHIDLJ {
    MOHNIMLCODA type = 1;
    uint32 config_id = 2;
    uint32 unique_id = 3;
    uint32 level = 4;
    repeated OEBBNFANHLK switch_list = 5;
}

enum RebattleType {
    REBATTLE_TYPE_NONE = 0;
    REBATTLE_TYPE_REBATTLE_MIDWAY = 1;
    REBATTLE_TYPE_REBATTLE_LOSE = 2;
    REBATTLE_TYPE_REBATTLE_MIDWAY_LINEUP = 3;
    REBATTLE_TYPE_REBATTLE_LOSE_LINEUP = 4;
    REBATTLE_TYPE_QUIT_MIDWAY = 5;
    REBATTLE_TYPE_QUIT_LOSE = 6;
}

// ========================= Challenge =========================

message AvatarIdentifier {
    uint32 assist_uid = 3;
    AvatarType avatar_type = 4;
    uint32 id = 7;
}

message BattleTarget {
    uint32 id = 1;
    uint32 progress = 2;
    uint32 total_progress = 3;
}

message ChallengeAvatarInfo {
    AvatarType avatar_type = 1;
    uint32 id = 2;
    uint32 level = 3;
    uint32 index = 4;
    uint32 skin_id = 5;
}

message ChallengeBossAvatarRelicInfo {
    map<uint32, ChallengeBossRelicInfo> avatar_relic_slot_map = 1;
}

message ChallengeBossEquipmentInfo {
    uint32 unique_id = 1;
    uint32 tid = 2;
    uint32 level = 3;
    uint32 promotion = 4;
    uint32 rank = 5;
}

message ChallengeBossRelicInfo {
    uint32 unique_id = 1;
    uint32 tid = 2;
    uint32 level = 3;
    uint32 main_affix_id = 4;
    repeated RelicAffix sub_affix_list = 5;
}

message ChallengeBossStatistics {
    uint32 record_id = 11;
    AANLJBLOOFO PPBHLLOJNEK = 14;
}

message ChallengeStatistics {
    ADKJKMKBFDC PPBHLLOJNEK = 7;
    uint32 record_id = 4;
}

message ChallengeStoryStatistics {
    uint32 record_id = 7;
    EIKPHEMHIOH PPBHLLOJNEK = 13;
}

message PlayerChallengeTierceRecord {
    bool EGLLMGLLHDL = 1;
    uint32 record_id = 2;
    repeated AIIGHJEIGHE GBMBAHHDONN = 3;
    uint32 used_cycle_count = 4;
    uint32 total_score = 5;
    repeated uint32 finished_target_list = 6;
}

// ========================= ChallengePeak =========================

message EquipRelic {
    uint32 relic_unique_id = 4;
    uint32 type = 10;
}

// ========================= Chat =========================

message ChatData {
    ECCKHOLLPPC NPBOINAPJJE = 101;
    NDDOMFBJMKE IBJBFODFIMN = 102;
    string message_text = 103;
    uint32 extra_id = 104;
    GCBHOIJLBFL IALHIFELMGE = 105;
    IDLACKBINMC ADBNPHDPPIH = 106;
    IGCHDHFMPBJ LPLCDCIFOOK = 107;
    PELDIEOMMDM NLHJFKGNAMB = 108;
    OPLFDAGPBEI BCLPAMNPHNP = 109;
    HCKADDLIGEB HJADNIAAMGJ = 110;
}

// ========================= ChessRogue =========================

message AGEOGDOGDMM {
    uint32 rogue_money = 9;
}

message APNCCNFJBKO {
    repeated KJAMNOGFAMJ buff_list = 3;
}

message BMCNDLNONMO {
    RogueModifierSourceType source_type = 12;
    KIJEFIIBBGG OOPCPMANCBO = 6;
    uint64 FCHLCANJIGL = 1;
    FGHIMGPGBNF NLGJFIGPENF = 13;
    AIBNHPAGDOL LEJPOHHGBMB = 3;
    HFJKOCDOAEH GGJOKFEOEBK = 14;
    AEBNHMHDMNP AOCJHEHCGFA = 15;
    EOLKILAIAKL DOLKNBFGCAD = 8;
}

message EGLAPJGFKPN {
    APNCCNFJBKO JPKACKNNHCA = 6;
}

message FDBDLBAPDBE {
    repeated OKPIPFKONMG BLHJIPBHHFO = 2;
}

message GMIJHCONFIH {
    repeated KOFMGCNIMIN MAJGMMCOCIG = 8;
}

message INHBMHCJJCN {
    uint32 queue_position = 2;
    DCFPEIMAMCN detail = 5;
}

message NHLBNBBDHMI {
    GMIJHCONFIH HAJJBOFCFOO = 1;
}

enum RogueModifierSourceType {
    RogueModifierSourceType_RogueModifierSourceNone = 0;
    RogueModifierSourceType_RogueModifierSourceDiceRoll = 1;
    RogueModifierSourceType_RogueModifierSourceAeon = 2;
    RogueModifierSourceType_RogueModifierSourceBoardEvent = 3;
    RogueModifierSourceType_RogueModifierSourceDialogEvent = 4;
    RogueModifierSourceType_RogueModifierSourceMiracle = 5;
    RogueModifierSourceType_RogueModifierSourceCellMark = 6;
    RogueModifierSourceType_RogueModifierSourceAeonTalent = 7;
    RogueModifierSourceType_RogueModifierSourceBossDecay = 8;
    RogueModifierSourceType_RogueModifierSourceDiceBranch = 9;
    RogueModifierSourceType_RogueModifierSourcePersonaStyle = 10;
}

// ========================= DiceCombat =========================

message DiceCombatAvatar {
    uint32 dice_avatar_id = 1;
    uint32 level = 2;
    repeated uint32 dice_id_list = 3;
    int64 unlock_time = 4;
}

// ========================= EvolveBuild =========================

message DKPHAFPGDLO {
    uint32 JGDOICIEMAH = 1;
    uint32 IOEAFFEEDFM = 2;
}

// ========================= Fate =========================

message KPNHGDGLICN {
    AvatarType avatar_type = 1;
    uint32 id = 2;
}

enum MOHNIMLCODA {
    MOHNIMLCODA_NLCDGIPGFDJ = 0;
    MOHNIMLCODA_DMJKCOJLFCL = 1;
    MOHNIMLCODA_ANEIGHKMJKB = 2;
    MOHNIMLCODA_MGMPDHKJFIM = 3;
    MOHNIMLCODA_MAIBAOAOGID = 4;
    MOHNIMLCODA_EGCGFGDILBC = 5;
    MOHNIMLCODA_KEEIBDBEJLH = 6;
    MOHNIMLCODA_level = 7;
    MOHNIMLCODA_DIMIFCJPHME = 8;
    MOHNIMLCODA_PEEDCBADBHJ = 9;
}

// ========================= FiveDim =========================

message AHCLMAGAHPN {
    MotionInfo motion = 2;
    uint32 entity_id = 4;
}

message BLPHONLBNBO {
    uint32 instance_id = 10;
    uint32 group_id = 9;
}

message DGHPIDMDOJM {
    uint32 GABODFDMPMM = 3;
    string uuid = 2;
    AHCLMAGAHPN PPJFMBIGIGB = 10;
    BLPHONLBNBO OEIBHLMDJKA = 12;
}

// ========================= Friend =========================

message ChallengeLineupList {
    repeated ChallengeAvatarInfo avatar_list = 1;
}

enum FriendOnlineStatus {
    FRIEND_ONLINE_STATUS_OFFLINE = 0;
    FRIEND_ONLINE_STATUS_ONLINE = 1;
}

message HeadFrameInfo {
    uint32 head_frame_item_id = 1;
    int64 head_frame_expire_time = 8;
}

enum PlatformType {
    EDITOR = 0;
    IOS = 1;
    ANDROID = 2;
    PC = 3;
    WEB = 4;
    WAP = 5;
    PS4 = 6;
    NINTENDO = 7;
    CLOUD_ANDROID = 8;
    CLOUD_PC = 9;
    CLOUD_IOS = 10;
    PS5 = 11;
    MAC = 12;
    CLOUD_MAC = 13;
    CLOUD_WEB_ANDROID = 20;
    CLOUD_WEB_IOS = 21;
    CLOUD_WEB_PC = 22;
    CLOUD_WEB_MAC = 23;
    CLOUD_WEB_TOUCH = 24;
    CLOUD_WEB_KEYBOARD = 25;
    CLOUD_DOUYIN_IOS = 27;
    CLOUD_DOUYIN_ANDROID = 28;
}

message PlayerSimpleInfo {
    uint32 level = 12;
    uint32 head_icon = 15;
    HeadFrameInfo head_frame_info = 1901;
    repeated AssistSimpleInfo assist_simple_info_list = 3;
    string nickname = 8;
    uint32 personal_card = 11;
    uint32 chat_bubble_id = 1;
    PlatformType platform = 14;
    int64 last_active_time = 6;
    int64 update_time = 1949;
    string platform_nick = 13;
    string platform_uuid = 4;
    bool is_banned = 5;
    uint32 gender = 1643;
    FriendOnlineStatus online_status = 10;
    uint32 uid = 2;
    string signature = 7;
    CJLCPMDGIBO player_outfit_data = 9;
}

message RelicAffix {
    uint32 affix_id = 1;
    uint32 cnt = 2;
    uint32 step = 3;
}

// ========================= GridFight =========================

message FHCEIOHLADG {
    uint32 pos = 1;
    uint32 LHHONKJPPDC = 2;
    uint32 KFGOKFKHOPB = 3;
    uint32 LLLOOKPGGGG = 4;
}

message GridFightAugmentInfo {
    uint32 augment_id = 1;
}

message GridFightDropInfo {
    repeated BCCONKJHDJL NMGIABHIJJB = 1;
}

enum GridFightDropType {
    GridFightDropType_None = 0;
    GridFightDropType_Coin = 1;
    GridFightDropType_Exp = 2;
    GridFightDropType_Refresh = 3;
    GridFightDropType_Role = 4;
    GridFightDropType_Item = 5;
    GridFightDropType_Orb = 6;
    GridFightDropType_RoleWithEquip = 7;
}

message GridFightInfo {
    repeated BattleAvatar OPHONCKPNMG = 1;
    uint32 battle_wave_id = 2;
    uint32 grid_fight_lineup_hp = 3;
    uint32 EHNJDIDABHD = 4;
    repeated GridFightTraitInfo grid_fight_trait_info = 7;
    repeated GridFightRoleInfo grid_game_role_list = 8;
    uint32 IFIIOIIKJHO = 9;
    repeated GridFightAugmentInfo sync_augment_info = 10;
    MIPDJDJLGPL IOCKDJCDMAH = 11;
    uint32 HHEPCDMBJFI = 12;
    uint32 LJNGPCKPJLF = 13;
    repeated GridFightPortalInfo grid_fight_portal_buff_list = 14;
    bool is_overlock = 15;
    uint32 AACGBEBGDPE = 16;
    repeated GridFightNPCInfo grid_game_npc_list = 17;
    repeated GridFightProjectionInfo KCOMPKMJCMC = 18;
    uint32 LODNFLMBIEH = 19;
    map<string, uint32> POCKGKDFLKK = 20;
    uint32 NFBJINKLLLK = 21;
    bool MEHFNAEMMFE = 22;
}

message GridFightNPCInfo {
    uint32 unique_id = 1;
    uint32 npc_id = 2;
    uint32 pos = 3;
    repeated BattleGridFightEquipInfo grid_fight_equipment_list = 4;
}

message GridFightPortalInfo {
    uint32 portal_buff_id = 1;
}

message GridFightProjectionInfo {
    uint32 unique_id = 1;
    uint32 LKMEMKLGIIK = 2;
    uint32 pos = 3;
}

message GridFightRoleInfo {
    uint32 role_id = 1;
    uint32 role_star = 2;
    uint32 pos = 3;
    repeated BattleGridFightEquipInfo CNIJIJMEPEF = 7;
    uint32 avatar_id = 8;
    map<uint32, uint32> convert_property_to_fixpoint = 10;
    uint32 unique_id = 11;
    JJHJCIAPADP DCEOLAAMGOO = 12;
}

message GridFightTraitEffectLevelInfo {
    uint32 trait_effect_level_exp = 1;
    map<uint32, GridFightDropInfo> trait_effect_level_reward = 2;
}

message GridFightTraitInfo {
    uint32 trait_id = 1;
    uint32 layer = 2;
    repeated BattleGridFightTraitEffectInfo trait_effect_list = 3;
    repeated MHFNFINKJKP KOJMGCBLKKA = 5;
    uint32 BPJKHDNBPOE = 6;
    uint32 AFKKLDMAEDJ = 7;
}

// ========================= Heliobus =========================

message GEGLJDELBHA {
    LineupInfo lineup = 9;
    uint32 world_level = 4;
    SceneInfo MOPHKIGKDIK = 5;
    uint32 raid_id = 1;
}

// ========================= Item =========================

message Equipment {
    uint32 rank = 11;
    uint32 level = 6;
    uint32 exp = 2;
    uint32 dress_avatar_id = 14;
    uint32 tid = 12;
    uint32 unique_id = 13;
    bool is_protected = 8;
    uint32 promotion = 3;
}

message Item {
    uint32 promotion = 2;
    uint32 unique_id = 4;
    uint32 main_affix_id = 8;
    uint32 num = 12;
    uint32 rank = 6;
    uint32 level = 3;
    uint32 item_id = 11;
}

message Material {
    uint32 num = 9;
    uint64 expire_time = 15;
    uint32 tid = 7;
}

message NLLLAAEJOBP {
    uint32 tid = 6;
    repeated uint32 DMNHPNAPGNB = 14;
}

message PileItem {
    uint32 item_num = 5;
    uint32 item_id = 13;
}

message Relic {
    bool is_protected = 7;
    uint32 main_affix_id = 5;
    repeated RelicAffix reforge_sub_affix_list = 6;
    bool is_discarded = 1;
    uint32 dress_avatar_id = 11;
    repeated RelicAffix sub_affix_list = 15;
    uint32 tid = 8;
    uint32 level = 4;
    uint32 unique_id = 14;
    uint32 reforge_block_sub_affix_id = 10;
    repeated RelicAffix preview_sub_affix_list = 2;
    uint32 exp = 9;
}

message WaitDelResource {
    uint32 tid = 15;
    uint32 num = 5;
}

// ========================= Jukebox =========================

message MNCBEDBDDHL {
    KHADHDLCNOI JKNLCEEDAHJ = 1;
    repeated AAKECCJELLI NNJCEINOEHH = 2;
    bool PGPNCNABHAM = 3;
}

// ========================= Lineup =========================

enum AvatarType {
    AvatarType_None = 0;
    AvatarType_AvatarTrialType = 1;
    AvatarType_AvatarLimitType = 2;
    AvatarType_AvatarFormalType = 3;
    AvatarType_AvatarAssistType = 4;
    AvatarType_AvatarAetherDivideType = 5;
    AvatarType_AvatarUpgradeAvailableType = 6;
    AvatarType_AvatarGridFightType = 7;
    AvatarType_AvatarFixedPathType = 8;
    AvatarType_AvatarReturnAssistType = 9;
}

enum ExtraLineupType {
    ExtraLineupType_LineupNone = 0;
    ExtraLineupType_LineupChallenge = 1;
    ExtraLineupType_LineupRogue = 2;
    ExtraLineupType_LineupChallenge2 = 3;
    ExtraLineupType_LineupChallenge3 = 4;
    ExtraLineupType_LineupRogueChallenge = 5;
    ExtraLineupType_LineupStageTrial = 6;
    ExtraLineupType_LineupRogueTrial = 7;
    ExtraLineupType_LineupActivity = 8;
    ExtraLineupType_LineupBoxingClub = 9;
    ExtraLineupType_LineupTreasureDungeon = 11;
    ExtraLineupType_LineupChessRogue = 12;
    ExtraLineupType_LineupHeliobus = 13;
    ExtraLineupType_LineupTournRogue = 14;
    ExtraLineupType_LineupRelicRogue = 15;
    ExtraLineupType_LineupArcadeRogue = 16;
    ExtraLineupType_LineupMagicRogue = 17;
    ExtraLineupType_LineupFate = 18;
    ExtraLineupType_LineupGridFight = 19;
}

message LineupAvatar {
    AvatarType avatar_type = 14;
    uint32 slot = 12;
    SpBarInfo sp_bar = 2;
    uint32 hp = 8;
    uint32 id = 5;
    uint32 satiety = 3;
}

// ========================= Lobby =========================

enum FightGameMode {
    FightGameMode_None = 0;
    FightGameMode_Match3 = 1;
    FightGameMode_Marble = 2;
    FightGameMode_Match3Solo = 3;
    FightGameMode_Match3Royale = 4;
    FightGameMode_MarbleMainsub = 5;
    FightGameMode_CakeRace = 6;
    FightGameMode_DiceCombat = 7;
    FightGameMode_DiceCombatV2 = 8;
    FightGameMode_TeamTowers = 9;
}

message LobbyGameExtInfo {
    repeated string MLAFBFEBNHB = 1;
    bool ELJECOAKNOF = 2;
    LobbyMarchInfo lobby_march_info = 1001;
    LobbyMarbleInfo lobby_marble_info = 1002;
    JMFPICAMLIG PHIBAOMGNOH = 1003;
    LobbyGridFightInfo lobby_grid_fight_info = 1004;
    IPIJFDIPNDE GOKJCFBPHCJ = 1005;
    PCBLIKPEEJA MPNPIIHHFPN = 1006;
}

message LobbyGridFightInfo {
    repeated uint32 LAJJHAAKGAF = 1;
    uint32 gold = 2;
    uint32 score_id = 3;
    string KEJLHDPBIPO = 4;
}

message LobbyMarbleInfo {
    uint32 GDBNHOJPKIE = 1;
    uint32 rank = 2;
    repeated uint32 CIPEHBBKFIH = 3;
    uint32 score_id = 4;
}

message LobbyMarchInfo {
    uint32 HBONKLEOEEI = 1;
    KBCHOKFHHIH AIKDCBMCLBI = 5;
}

enum TeamTowersGameType {
    TeamTowersGameType_None = 0;
    TeamTowersGameType_RandomStage = 1;
    TeamTowersGameType_Survival = 2;
    TeamTowersGameType_Race = 3;
    TeamTowersGameType_Endless = 4;
}

// ========================= MapRotation =========================

message MotionInfo {
    Vector pos = 10;
    Vector rot = 2;
}

message NJMDFFHEAJJ {
    uint32 LOPLGJAHIFF = 1;
    uint32 IEAPGPOMBIN = 5;
}

message RotateMapInfo {
    Vector4 MIACNFDGKCE = 1;
    Vector ELFDIEFKCMH = 14;
}

message RotaterData {
    float position = 10;
    uint32 group_id = 7;
    uint32 instance_id = 13;
}

message RotaterEnergyInfo {
    uint32 max_num = 11;
    uint32 cur_num = 7;
}

// ========================= MatchThreeModule =========================

message KVP {
    uint32 value = 5;
    uint32 key = 12;
}

// ========================= Message =========================

enum MessageGroupStatus {
    MessageGroupStatus_MessageGroupNone = 0;
    MessageGroupStatus_MessageGroupDoing = 1;
    MessageGroupStatus_MessageGroupFinish = 2;
    MessageGroupStatus_MessageGroupFrozen = 3;
}

enum MessageSectionStatus {
    MessageSectionStatus_MessageSectionNone = 0;
    MessageSectionStatus_MessageSectionDoing = 1;
    MessageSectionStatus_MessageSectionFinish = 2;
    MessageSectionStatus_MessageSectionFrozen = 3;
}

// ========================= Misc =========================

message AAKECCJELLI {
    uint32 id = 1;
    uint32 volume = 2;
}

message AANLJBLOOFO {
    repeated ChallengeLineupList lineup_list = 4;
    uint32 EEJCPNAEKLJ = 6;
    uint32 buff_one = 5;
    uint32 score_id = 1;
    uint32 level = 12;
    uint32 buff_two = 15;
}

enum ABBHAALIBAH {
    ABBHAALIBAH_IDIPGIPFJJE = 0;
    ABBHAALIBAH_IDJHPOCLFIH = 1;
    ABBHAALIBAH_BFEPJFDFICC = 2;
    ABBHAALIBAH_LNBMBNJICBI = 3;
    ABBHAALIBAH_PMEEHGMPNLK = 4;
}

message ABJGLPCOMMK {
    uint32 ENHJCNJFDFI = 1;
}

message ADKJKMKBFDC {
    uint32 level = 3;
    repeated ChallengeLineupList lineup_list = 5;
    uint32 round_count = 8;
    uint32 EEJCPNAEKLJ = 13;
}

message AEBNHMHDMNP {
    repeated uint32 DAMFHOOMJDK = 15;
    uint32 JFNJBOMPNML = 10;
    uint32 DECJPNGFFLC = 6;
    uint32 DJCDEFOCMCH = 13;
}

message AIBNHPAGDOL {
    bool GKEPPNOLNHF = 15;
    uint32 forbid_reason = 13;
}

message AIIGHJEIGHE {
    uint32 stage_index = 1;
    ChallengeLineupList lineup = 2;
    uint32 buff_id = 3;
}

message AMEMKFNABGG {
    bool GNLMBJCPING = 1;
    repeated uint32 ILOLFNPALJH = 2;
    uint32 PIKBPDAMGML = 3;
    uint32 ODHIDLBAPIG = 4;
}

message AOAOBPGFHLA {
    uint32 compose_relic_id = 1;
    uint32 relic_type = 2;
    JAONELJJAFK ELOGOFFIJBB = 3;
    repeated JAONELJJAFK sub_affix_list = 4;
}

message AOHKKFHDALO {
    uint32 role_star = 101;
    uint32 PIHGNNMBCEJ = 102;
}

message APKENKIDMGC {
    repeated DAAKGEDPPJJ GMGPFAIONNG = 7;
    uint32 PBJPEOEDEDF = 12;
}

message AssistSimpleInfo {
    uint32 avatar_id = 3;
    uint32 pos = 13;
    uint32 dressed_skin_id = 7;
    uint32 level = 12;
}

message BACHHBGNENA {
    uint32 DLFHABGGHFF = 10;
    PGPHEKKPBLD CFDIKLBINHK = 5;
    uint32 EDDBMFMEPJK = 15;
}

message BCGJJCCJBCG {
    uint32 HLLIBEEKFII = 6;
    uint32 HHGAHEBNAIL = 15;
    uint32 NJHAPBIALCN = 11;
    map<uint32, uint32> MIKLLOOAJFE = 2;
}

enum BEAIKEEANDP {
    BEAIKEEANDP_NLCDGIPGFDJ = 0;
    BEAIKEEANDP_NKDECDGECFL = 1;
    BEAIKEEANDP_LONKNKFDPII = 2;
}

message BELNLOJAFCM {
    DGHPIDMDOJM JHBAAHGLFCB = 3;
    uint32 MHFBCGMDDOO = 1;
    repeated uint32 HLLLIKPGOFG = 9;
}

message BGFLAKMOIGC {
    bool AMICPGOIHLL = 3;
    bool JJMKAHIBDBH = 10;
}

message BHPBJOMBCAD {
    repeated NEJPAGJBMDA IJKIBLJEGGE = 15;
    bool NOALGKCLDHF = 12;
    uint32 group_id = 9;
}

message BLJEJFMKEII {
    CJHPPLHFNAB FODLGHIFJGC = 1;
    FHOHCAIFHNA GLDHCIBNBAG = 2;
}

message BOFHHEBDEOD {
    uint32 GDBNHOJPKIE = 1;
}

message CBDMGEGELFM {
    int32 DPICNGBHFAC = 7;
    uint32 key = 9;
}

message CEDCMIMKJHK {
    bool is_open = 10;
    uint32 avatar_id = 3;
}

message CJHPPLHFNAB {
    EMLFDPFAPJP BJMJBLCMPAL = 1;
    repeated KCIEGDGJMBE AHBOCLNGFNM = 2;
}

message CLLBJDEJFNF {
    uint32 type = 14;
    uint32 id = 10;
    uint32 slot = 8;
}

message CMNLOKDOFEF {
    uint32 GDBNHOJPKIE = 1;
}

message CPMNHNHKLBK {
    uint32 role_id = 1;
}

message CustomSaveData {
    string save_data = 2;
    uint32 group_id = 10;
}

message DAAKGEDPPJJ {
    uint32 func_id = 10;
    bool is_valid = 6;
}

message DCFPEIMAMCN {
    GGGBAIAPDLO PCHGEGFBKLF = 1553;
    GCCIOBKOFJN JFNHDJIDJDA = 1297;
    IEJIOGIGFAI FEMFJIDBEAB = 1332;
    PKFNILLONDF GHBBKKABKBN = 1922;
    AMKALFJHFJP AMIBPAGBMFP = 853;
    LFKOLKFKOAP PAKPHFJOBAF = 1782;
    LBKIKIGLIMJ BJKEDGMKOLM = 345;
    MBPJGCJEGJB NGCJBBCOOCF = 1563;
    JJPDJPINDOA CNANEDFPNKJ = 565;
    DNGEEKCHHED CDFPGKGILAJ = 1678;
    NGEBIKIHIDD PMKJIMIIOGM = 1938;
    INKPGECIDNE JIPEPMDMCMB = 1280;
    OFMCKLEMOMP FNEOOMHHGGB = 1638;
    JIGLEHNAKNJ EMOJGAFOCML = 1862;
    PAGJKBPPOKL BMEMABNEFKK = 847;
    KBKLNECKDEN GOIFJFKIFFF = 719;
    NFNMMFBJBLC FJCHODNDIKA = 788;
    KPJBDOPFPDL FAENLPCFFEB = 1195;
    OFGGMBHCKPJ NLAMHGACGIO = 1160;
    OFGGMBHCKPJ JCBNIADPOGN = 1174;
    OFGGMBHCKPJ IJMIEMKJCHM = 1292;
    FDICOMLMBME PHGLAEOGJKM = 781;
    KPOFAPDKBJA MMHGAEBEIHD = 1650;
    JDFNPICGCGI IFPBFMOAJOP = 1036;
    NIHKHKONHPN KNKAPJOCNGM = 721;
    PGMIABHEJNB HDAHOBBJDIF = 1399;
    OHJJMCMJEHL KBEBGLAAEGM = 937;
    PBMGACMAMBE HBLHLFDHIGP = 1202;
}

message DCHCPKMFNNC {
    repeated uint32 avatar_id_list = 1;
}

message DINGDGLKHIP {
    BEAIKEEANDP HOKEFMONOPG = 7;
    uint32 avatar_id = 10;
}

message DJEECBNBGMN {
    uint32 HAFOKMHCGFM = 3;
}

enum DKOPGDPKJHB {
    DKOPGDPKJHB_CGBIKOCDABB = 0;
    DKOPGDPKJHB_ALJCHAAIPHG = 1;
    DKOPGDPKJHB_COEBIAOACFM = 2;
    DKOPGDPKJHB_FKOIKJFAIKF = 3;
    DKOPGDPKJHB_DIEMGOICHLO = 4;
    DKOPGDPKJHB_KHJHNEOFNLJ = 5;
    DKOPGDPKJHB_EFOHJENLODE = 6;
    DKOPGDPKJHB_HJHCDCHOKJG = 7;
    DKOPGDPKJHB_IHHCKDDFKJL = 8;
}

message DNGEEKCHHED {
    uint32 LGIPILAKIKB = 11;
    repeated uint32 BGAFHIOEHFH = 10;
}

message DPIFGEONFPI {
    repeated uint32 avatar_id_list = 1;
    uint32 ILBJLIENCLB = 2;
}

message EAENAFJCEFD {
    repeated uint32 MMGPKJOJIPM = 1;
    repeated uint32 FGPGOPOCAPN = 2;
}

message EBBJLHBAGCJ {
    uint32 ODPELJAIPHL = 1;
    repeated uint32 GLNPAOLFPDI = 2;
}

message EBBOJACNHEC {
    bool OEEDPJHLPHL = 15;
    uint32 GHEHGIOAGDG = 3;
    uint32 LHLKJIDFLIN = 7;
}

message ECCKHOLLPPC {
    uint64 ANBJMMOEGJE = 1;
    uint32 GJNMHILINHC = 2;
    uint32 JOJALEHLLEJ = 3;
    repeated uint32 AGNFHCLKGCF = 4;
}

message EDCFKACPFNB {
    uint32 CKGJIKJDHCJ = 1;
}

message EGAILAEBLIG {
    uint32 LJCEOGPOGBE = 2;
}

message EIKPHEMHIOH {
    repeated ChallengeLineupList lineup_list = 6;
    uint32 buff_one = 4;
    uint32 score_id = 13;
    uint32 buff_two = 12;
    uint32 EEJCPNAEKLJ = 14;
    uint32 level = 8;
}

message EJEFBHPAPND {
    repeated uint32 avatar_id_list = 1;
}

message EKNABKLPEEL {
    HCMEILLLKBD KPOBMNLKLOK = 1;
    uint32 role_id = 2;
}

message EMLFDPFAPJP {
    uint32 NAEAGNLBKAM = 1;
    uint32 MHPPIKLBNMD = 2;
}

message EOLKILAIAKL {
    bool PAPMELCOCEP = 5;
    repeated KVP KBMPMGHEKKA = 1;
}

message EPCNFDBKAEE {
    repeated uint32 avatar_id_list = 1;
}

message FDFGIHJBHEL {
    uint32 FMEHKPKHGJA = 1;
    uint32 PNGHFKLCNBE = 2;
}

message FDGKFJFICDN {
    uint32 OCPEPEMNNEK = 1;
    double delay = 2;
}

message FDICOMLMBME {
    uint32 AIAFEKGBFIF = 13;
}

message FEGKCMBHHJP {
    uint32 level = 1;
    uint32 FGFFLBHLKDF = 2;
}

message FGHIMGPGBNF {
    repeated uint32 OGOILMLPDEO = 3;
    bool is_selected = 13;
    uint32 FOHIFIMHENN = 7;
}

message FHBDPOJEEMJ {
    DJEECBNBGMN HHBPBGMNGPN = 8;
    EGAILAEBLIG ECCLOKPNFHP = 3;
    HLEBBGFAKAK HDFLCOIDCPE = 15;
}

message FHOHCAIFHNA {
    uint32 HILINOJPLGA = 1;
    double difficulty_ratio = 2;
    uint32 PGGDEHKKINP = 11;
    uint32 style_level = 12;
    uint32 style_exp = 13;
}

message GCBHOIJLBFL {
    DCHCPKMFNNC BNIGONFKICO = 1;
    EJEFBHPAPND JIOEBAFCAJE = 2;
    PFDBLPONOHE NBBFPHGLFNP = 3;
    GMMMIGPFIOH LNOMBCDABKJ = 4;
    DPIFGEONFPI BEGAIBBJHHD = 5;
    EPCNFDBKAEE GOIKMBNGGNP = 6;
    HFHFMPLAJCC CMHJJDDEHCP = 7;
    GDIBHDEKJCG OOKBDDEJHPB = 8;
    string BLDMFDKDJDM = 10;
}

message GCCIOBKOFJN {
    uint32 LGIPILAKIKB = 12;
    repeated KJAMNOGFAMJ JJDILEHLHDH = 11;
}

message GDIBHDEKJCG {
}

message GFNAPELNFIC {
    uint32 CLFBBAPEPML = 1;
    bool is_locked = 2;
    DKPHAFPGDLO JBNMAOFOFPE = 3;
}

message GILBMELHGCB {
    repeated uint32 JMMBAALIOJL = 10;
    uint32 stage_id = 11;
}

message GKFGIMIBBHF {
    bool finish = 11;
    uint32 progress = 2;
    uint32 MMFGAJNCAOA = 5;
}

message GLIBGKGGEJL {
    repeated uint32 PDABDEJBPEL = 1;
    uint32 NKDDBPGDAEE = 2;
}

message GMIMDEJMFCO {
    repeated LGEFLGJIGIJ GMALFEABLNG = 1;
    MGGBPKANFOA global_blackboard = 13;
}

message GMMMIGPFIOH {
    repeated uint32 avatar_id_list = 1;
}

message HCGDLIAMDLA {
    uint32 JJGMIGBBEOO = 14;
    uint32 JADCEPFHHDK = 3;
    uint32 avatar_id = 7;
}

message HCKADDLIGEB {
    string stop_desc = 1;
    uint32 HAAFJLKHCKF = 2;
}

enum HCMEILLLKBD {
    HCMEILLLKBD_NLCDGIPGFDJ = 0;
    HCMEILLLKBD_JDOAIPKBIPE = 1;
    HCMEILLLKBD_GGBMAANJNJC = 2;
}

message HFHFMPLAJCC {
    repeated uint32 avatar_id_list = 1;
}

message HFJKOCDOAEH {
    uint32 EKNHHGMJCPM = 9;
    uint32 OLPPACCCNGD = 6;
}

message HGNBPANECAL {
    uint32 entity_id = 9;
    repeated BuffInfo buff_list = 11;
}

message HIEKLHPINHL {
    uint32 OFBPKCNCGFG = 15;
    uint32 max_count = 8;
}

message HJDCJNOFBHH {
    uint32 LJCEOGPOGBE = 2;
}

message HJNPOBAMKKF {
    repeated AOAOBPGFHLA HGNKNFJPIKI = 1;
    repeated JAONELJJAFK CDMKBCHLPAB = 2;
    uint32 MNCFOGJECMF = 3;
}

message HLEBBGFAKAK {
    uint32 GNCFHIKODKE = 6;
}

message HLFAKEOBFAB {
    uint32 HJMACPMOINC = 8;
    uint32 PBMAHOJBAGG = 4;
    uint32 AFEMBLFCCCH = 13;
}

message HLFOOKANNDE {
    uint32 JGDOICIEMAH = 1;
    double damage = 2;
    double KADNIAEJACG = 3;
}

message HNEBODEBELG {
    uint32 role_star = 3;
    repeated BCCONKJHDJL IEBNOGOOEMO = 11;
}

message HOMMPJIOPGI {
    uint32 wave = 1;
    uint32 score_id = 2;
    uint32 GMKFBAMNDEA = 3;
    repeated DKPHAFPGDLO CBLOAJFJKKI = 4;
    float delay = 5;
}

enum IDDPBEAMDAO {
    IDDPBEAMDAO_IIOCEDFJPNH = 0;
    IDDPBEAMDAO_NBFHCJMNHAG = 1;
    IDDPBEAMDAO_DHHHKOJBKCJ = 2;
}

message IDJIAGLCAPE {
    uint32 IPCFGIEFBKH = 1;
    repeated HOMMPJIOPGI DCMAHKHAFEH = 2;
    repeated FDGKFJFICDN OJBMGEJCILM = 3;
}

message IDLACKBINMC {
    string title = 1;
    string JFCEOOODIBN = 2;
}

message IEJIOGIGFAI {
    repeated KJAMNOGFAMJ CGAEPNOCDIG = 2;
    uint32 LGIPILAKIKB = 7;
}

message IGCHDHFMPBJ {
    DKOPGDPKJHB type = 1;
    string stop_desc = 2;
    uint32 avatar_id = 3;
}

message IJLEFNJPFKP {
    uint32 rogue_mode = 1;
}

message INKPGECIDNE {
    repeated uint32 KPJPABDIOJB = 10;
}

message IPIJFDIPNDE {
    repeated DiceCombatAvatar avatar_list = 1;
    BOFHHEBDEOD BAEGDJILMBL = 2;
    CMNLOKDOFEF AEPFOJHNNFH = 3;
    uint32 EECIJBLGLNG = 4;
    uint32 EMHHCEMGBEM = 5;
    uint32 GMCAHOPDHLI = 6;
    bool KDFJPPOLFEB = 7;
}

message JAONELJJAFK {
    uint32 property_type = 1;
    float value = 2;
}

message JIGLEHNAKNJ {
    repeated uint32 KLLIJGIHFAP = 6;
    uint32 LGIPILAKIKB = 14;
}

message JJHJCIAPADP {
    ABJGLPCOMMK GLHDCCPOGHL = 101;
    NKAEOPAAJLG JBIFDJKPHIJ = 102;
}

message JJPDJPINDOA {
    repeated uint32 ANINMMMGLLL = 8;
    uint32 LGIPILAKIKB = 10;
}

message JMFPICAMLIG {
    KBCHOKFHHIH AIKDCBMCLBI = 1;
}

enum JNBOIFCNBCH {
    JNBOIFCNBCH_HGLIFJGHADE = 0;
    JNBOIFCNBCH_LCFJOOIAEHD = 1;
}

message KBCHOKFHHIH {
    uint32 GDBNHOJPKIE = 1;
    uint32 EAGEFHOHCOA = 2;
    uint32 EECIJBLGLNG = 3;
    uint32 OPHFDHGBLPJ = 4;
    repeated FDFGIHJBHEL MKIOMOINKOF = 5;
    uint32 IHEGLJHMKPP = 6;
    uint32 MFECHJLACLC = 7;
}

message KBKLNECKDEN {
    OKCCLEEPELM EPOCLANFIAC = 7;
    uint32 EIALMEADLGF = 2;
    uint32 LGIPILAKIKB = 12;
    uint32 NKGGAOJLCMD = 13;
    repeated OKCCLEEPELM AGKFAODICEA = 3;
}

message KCIEGDGJMBE {
    uint32 GCAHKLNGFCK = 1;
    repeated OJMPKMNINGK HIILDALHIMD = 2;
    uint32 level = 3;
    map<uint32, uint32> HCPNPDLJKGF = 4;
}

message KFMKBMJPEIC {
    uint32 DNNCAGJIOAP = 1;
    repeated uint32 IHCDDIPNJKO = 2;
    repeated BattleGridFightEquipInfo grid_fight_equipment_list = 3;
    map<uint32, uint32> BANBECDCDHG = 4;
    repeated FHCEIOHLADG POJGKJENENA = 5;
}

message KGLIOOODBPN {
    uint32 level = 4;
    repeated uint32 OEOMILPAFGI = 10;
    uint32 composition_type = 13;
}

message KHADHDLCNOI {
    uint32 id = 1;
    bool is_pause = 2;
}

message KIAICMELIMM {
    map<uint32, uint32> AOKECJBFMCN = 1;
    uint32 CDBGPMABMGM = 2;
    uint32 FGOHMOMLEBG = 3;
    uint32 enemy_hp_multiplier = 4;
}

message KIJEFIIBBGG {
    PHAOIGLGBMG content_type = 3;
    uint32 JAAIADKFPCL = 8;
    uint32 IKDHAMLPNPJ = 2;
}

message KOEIBOFDLCM {
    uint32 NFMHIOIFLCB = 14;
}

message KPJBDOPFPDL {
    OCBPJLLLJGO MAAGBKHLECB = 9;
}

message LBKIKIGLIMJ {
    uint32 LGIPILAKIKB = 8;
    repeated uint32 MJGBLEBKMDH = 13;
}

message LDKMOFFMGEL {
    uint32 type = 14;
    uint32 LPOLPDBELON = 5;
    uint32 slot = 13;
}

message LDOMEIGDIAK {
    uint32 NFMHIOIFLCB = 14;
}

message LFKOLKFKOAP {
    uint32 LGIPILAKIKB = 7;
    repeated uint32 CLEJHGMAFOD = 6;
}

message LGEFLGJIGIJ {
    MMFOGJPOHGJ owner_type = 1;
    repeated AKMCODLAEKI GFKAFIFMHNF = 3;
    uint64 GAHFPGCPAJA = 8;
}

message LMLNJFEMOAI {
    uint32 skill_id = 1;
    uint32 skill_level = 2;
}

message MBMAGILKFGP {
    repeated HCGDLIAMDLA LEBNOGAMCNE = 12;
}

message MBPJGCJEGJB {
    repeated uint32 LHMIIFKPPAG = 3;
    uint32 LGIPILAKIKB = 6;
}

message MGGBPKANFOA {
    repeated AKMCODLAEKI GFKAFIFMHNF = 12;
}

message MHFNFINKJKP {
    uint32 CHEEOEHDOBF = 1;
    IDDPBEAMDAO NKIENAICLGN = 2;
    uint32 NKJPCMPMGPM = 3;
    ABBHAALIBAH grid_update_src = 4;
}

message MHGAOLCDONK {
    uint32 NLMMKAEJEKH = 15;
    uint32 OPEEIFGGMIA = 4;
}

message MIPDJDJLGPL {
    uint32 EMOHLJHPOPC = 1;
    uint32 DCAHJELNJNP = 2;
    uint32 section_id = 3;
    uint32 node_type = 4;
}

message MNDMNDKLKIE {
    HNEBODEBELG EIGMKOJOEEI = 368;
}

enum MsgType {
    MsgType_None = 0;
    MsgType_CustomText = 1;
    MsgType_Emoji = 2;
    MsgType_Invite = 3;
    MsgType_PlanetFes = 4;
    MsgType_AiPamFunctionCall = 5;
    MsgType_UrlCitation = 6;
    MsgType_AiPamQuickFunction = 7;
    MsgType_AiPamLineupInterp = 8;
    MsgType_AiPamRelicInterp = 9;
    MsgType_AiPamPoke = 10;
}

message NBDKNCJGOMN {
    uint32 FOKPPMBIDID = 15;
    HKOEAOPNEAC KOBBMDFPNKA = 5;
}

message NCHGLFJCGIJ {
    repeated BMCNDLNONMO HDLGLFGKONC = 3;
}

message NDDHJBFEBHG {
    uint32 NFMHIOIFLCB = 15;
    uint32 OKNPKMABAHE = 3;
    uint32 CLMMHFFNKEH = 2;
}

message NDDOMFBJMKE {
    uint32 panel_id = 1;
    uint32 content_type = 2;
    uint64 HJFDAJAMFAC = 3;
}

message NEJPAGJBMDA {
    uint32 FGFFLBHLKDF = 11;
    bool OGNBANANFCC = 10;
    HJDCJNOFBHH AOLFPJFJPEO = 9;
    FEGKCMBHHJP NGALCDKBGBK = 5;
}

message NFNMMFBJBLC {
    repeated OCBPJLLLJGO INLDHMAIPMH = 5;
    uint32 LGIPILAKIKB = 1;
}

message NGEBIKIHIDD {
    repeated uint32 BGAFHIOEHFH = 5;
    uint32 LGIPILAKIKB = 6;
}

message NIHKHKONHPN {
    FHBDPOJEEMJ CPOHGLHEOLG = 10;
    repeated uint32 LEOPMIGFDLK = 1;
    uint32 LGIPILAKIKB = 6;
    repeated uint32 FNCIOCCACMD = 8;
}

enum NIMFANHLFNJ {
    NIMFANHLFNJ_FAAFEKOFGBL = 0;
    NIMFANHLFNJ_AMCJDDIPLJN = 1;
    NIMFANHLFNJ_BNNNGLNGCHL = 2;
    NIMFANHLFNJ_DIBHICHMJFE = 3;
    NIMFANHLFNJ_LKDDACHPOAM = 4;
}

message NKAEOPAAJLG {
    uint32 EAGPOCAGMCA = 1;
}

enum NKAFNCBDJAH {
    NKAFNCBDJAH_FFEDLLJAILE = 0;
    NKAFNCBDJAH_GPIALFOJHAC = 1;
    NKAFNCBDJAH_FDEMMIICBPB = 2;
}

message NMKNOLPFJDN {
    uint32 KOHGFNGKFPE = 2;
    repeated uint32 CKLIEKOIGOG = 11;
    uint32 JCKKPPELFHC = 15;
    repeated uint32 HGDNMKBNMBK = 13;
}

message NpcExtraInfo {
    NpcRogueGameInfo rogue_game_info = 11;
    PAGOHCJGOLC MBLFFIKGMOP = 15;
    MHGAOLCDONK DKPFHLBFFHI = 14;
}

message NpcMonsterExtraInfo {
    NpcMonsterRogueInfo rogue_game_info = 15;
}

message OEBBNFANHLK {
    uint32 JBPNBECLGKN = 1;
    double AALPICLABCO = 2;
}

message OEMOIGDNPNP {
    uint32 card_id = 1;
    double param = 2;
    bool is_enable = 3;
    repeated double switch_list = 4;
}

message OFGGMBHCKPJ {
    repeated MMBBHFNJILI AGKFAODICEA = 14;
    uint32 LGIPILAKIKB = 11;
}

message OJMPKMNINGK {
    uint32 CFKKKPNKHEL = 1;
    uint32 level = 2;
    bool is_locked = 3;
    uint32 dice_slot_id = 4;
    map<uint32, uint32> AAABHNMAENN = 5;
}

message OKPIPFKONMG {
    RogueTalentStatus status = 11;
    repeated GKFGIMIBBHF LDHIJAHNEGK = 1;
    uint32 CKHCLKOALKE = 7;
}

message ONNEJIPGHCK {
    uint32 chest_id = 14;
}

message OPLFDAGPBEI {
    uint32 avatar_id = 1;
    HJNPOBAMKKF FLFNBPLNNBL = 2;
    HJNPOBAMKKF LLMDKAHFIIJ = 3;
    string stop_desc = 4;
}

message PAGJKBPPOKL {
    OFMCKLEMOMP FNEOOMHHGGB = 1;
}

message PAGOHCJGOLC {
    uint32 DOOACEHOPEE = 4;
    bool is_meet = 1;
    uint32 PPFJGJNCOKI = 15;
}

message PBMGACMAMBE {
    uint32 IOJPOKCDFHM = 15;
    repeated KGLIOOODBPN JKFNAKBGIBF = 6;
}

message PCBLIKPEEJA {
    uint32 EECIJBLGLNG = 1;
    repeated LMLNJFEMOAI skill_list = 2;
    TeamTowersGameType DLFHABGGHFF = 3;
    uint32 stage_id = 4;
    bool JCKMMMNMLNG = 5;
}

message PELDIEOMMDM {
    repeated uint32 avatar_id_list = 1;
    string stop_desc = 2;
}

message PFDBLPONOHE {
    repeated uint32 avatar_id_list = 1;
    repeated PJCMNENIEHH GBKIBFJCPAL = 2;
    repeated uint32 POOEMJLCDHB = 3;
}

message PGLLFCMEFKG {
    uint32 GHEHGIOAGDG = 13;
    bool OEEDPJHLPHL = 14;
    uint32 LHLKJIDFLIN = 15;
}

enum PHAOIGLGBMG {
    PHAOIGLGBMG_OLJCMIBGNGL = 0;
    PHAOIGLGBMG_DLPKBBHKFBL = 1;
}

enum PJCMNENIEHH {
    PJCMNENIEHH_NLCDGIPGFDJ = 0;
    PJCMNENIEHH_KPILFMMNIGO = 1;
    PJCMNENIEHH_GGJPEMFEBLB = 2;
    PJCMNENIEHH_CIMNEOAKBJH = 3;
    PJCMNENIEHH_BOMDAIKIPLP = 4;
}

enum PJIMOBKFDNP {
    PJIMOBKFDNP_OPIIMBHECNJ = 0;
    PJIMOBKFDNP_FIKAGKIKFIJ = 1;
    PJIMOBKFDNP_NDBNMMJCAIC = 2;
}

message PKFNILLONDF {
    repeated KJAMNOGFAMJ LEOFNINDJDB = 5;
    uint32 LGIPILAKIKB = 6;
}

message PKPFAHEBJIO {
    repeated NIFPICHIDLJ message_datas = 1;
    map<uint32, uint32> FGGPANADLKM = 2;
    repeated EBBJLHBAGCJ FPMBJMDNPBM = 3;
    uint32 area_id = 4;
    uint32 difficulty = 5;
}

message PMNLJEJKLOD {
    NIMFANHLFNJ type = 1;
    uint32 count = 2;
}

message POFNNGOCEOK {
    uint32 EIKLMFPMJJD = 10;
    uint32 dice_slot_id = 7;
    int64 expire_time = 9;
}

message TeleportInfo {
    uint32 reason = 6;
    uint32 teleport_id = 5;
}

message Vector4 {
    float w = 5;
    float x = 10;
    float y = 6;
    float z = 7;
}

// ========================= Mission =========================

message MainMissionCustomValue {
    ONHKODAFEMH custom_value_list = 10;
    uint32 main_mission_id = 13;
}

message Mission {
    MissionStatus status = 7;
    uint32 progress = 4;
    uint32 id = 13;
}

message MissionCustomValue {
    uint32 custom_value = 2;
    uint32 index = 6;
    string BGDFHBAANLB = 4;
}

enum MissionStatus {
    MissionStatus_MissionNone = 0;
    MissionStatus_MissionDoing = 1;
    MissionStatus_MissionFinish = 2;
    MissionStatus_MissionPrepared = 3;
}

// ========================= Monopoly =========================

message ItemList {
    repeated Item item_list = 6;
}

// ========================= PlanetFes =========================

message DFEPHMALKDK {
    uint32 BLGLDJHOMNO = 4;
    repeated uint32 OEEGPNOCFLP = 9;
    int64 time = 14;
    uint32 APIFFHBCDKK = 1;
    uint32 source = 12;
}

message FMKMEFMOJGJ {
    uint32 item_count = 8;
    uint32 item_id = 9;
}

message GMODJEECPPJ {
    int64 apply_time = 6;
    repeated uint32 OEEGPNOCFLP = 9;
    uint32 BLGLDJHOMNO = 11;
    uint32 APIFFHBCDKK = 13;
}

message IEDPDDJAAIH {
    repeated uint32 OEEGPNOCFLP = 10;
    uint64 CBMBOBNCKMO = 7;
    int64 time = 1;
    uint32 HCJCIAGKHHL = 2;
    bool FOGGEJIIJCM = 15;
}

message NCFKHDIKCNI {
    repeated uint32 GFKAFIFMHNF = 9;
}

message OJHHACMHFKA {
    uint32 business_day = 8;
    bool HMEIPBNOMIG = 4;
    uint32 event_type = 12;
    uint32 BIOFDPICHLC = 9;
    bool BMHCDIPKKLE = 15;
    bool NLKMDIBKCIL = 13;
    int64 HPNLMPJJHCF = 11;
    MBMAGILKFGP BPABMONFKNB = 1;
    BCGJJCCJBCG DPNFIKGHFIH = 5;
    BACHHBGNENA NBAMDOAEHPJ = 14;
    LDOMEIGDIAK DIGJDCNCPOM = 2;
    NDDHJBFEBHG MBNBKOMMPFB = 3;
    KOEIBOFDLCM FBGJAACOEEI = 7;
}

message PGPHEKKPBLD {
    uint32 DLFHABGGHFF = 1;
    uint32 ratio = 11;
    NMKNOLPFJDN AGLMEDOBMAL = 8;
}

// ========================= Player =========================

message JPGACKPLGCD {
    bool KALACJBAPOA = 1;
    bool FOKJIPGMKAN = 2;
    bool IBLGOCFBOCO = 3;
}

message PlayerBasicInfo {
    string nickname = 1;
    uint32 level = 2;
    uint32 exp = 3;
    uint32 stamina = 4;
    uint32 mcoin = 5;
    uint32 hcoin = 6;
    uint32 scoin = 7;
    uint32 world_level = 8;
}

// ========================= PlayerBoard =========================

message HeadIconData {
    uint32 id = 11;
}

// ========================= PlayerSync =========================

message ONHKODAFEMH {
    repeated MissionCustomValue custom_value_list = 3;
}

// ========================= Quest =========================

message Quest {
    repeated uint32 MCPDELEIPIJ = 4;
    int64 finish_time = 12;
    uint32 progress = 11;
    uint32 id = 9;
    QuestStatus status = 15;
}

enum QuestStatus {
    QuestStatus_QuestNone = 0;
    QuestStatus_QuestDoing = 1;
    QuestStatus_QuestFinish = 2;
    QuestStatus_QuestClose = 3;
    QuestStatus_QuestDelete = 4;
}

// ========================= Replay =========================

enum PBIEFHKNAFA {
    PBIEFHKNAFA_NLCDGIPGFDJ = 0;
    PBIEFHKNAFA_KBBDECFFFAL = 1;
}

// ========================= Rogue =========================

message FHEGNOPNICH {
    uint32 JPPMEKJGJFD = 15;
    repeated RotaterData CEDGGDFMILP = 9;
    repeated NJMDFFHEAJJ EGAGKNADAHJ = 4;
    RotateMapInfo COOOMDKGODF = 10;
    RotaterEnergyInfo energy_info = 3;
    bool MJIPOJPBKNB = 2;
    int32 region_id = 1;
}

message KJAMNOGFAMJ {
    uint32 HAGDKKBAAKK = 1;
    uint32 buff_id = 3;
}

message LineupInfo {
    string name = 1;
    bool ABHONGJHICF = 6;
    uint32 leader_slot = 13;
    uint32 plane_id = 12;
    repeated LineupAvatar avatar_list = 7;
    repeated uint32 available_trial_avatar_i_ds = 8;
    repeated uint32 story_line_avatar_id_list = 2;
    uint32 mp = 15;
    uint32 index = 3;
    repeated uint32 locked_avatar_i_ds = 11;
    bool OPHLICGEPIC = 9;
    uint32 game_story_line_id = 4;
    uint32 max_mp = 5;
    ExtraLineupType extra_lineup_type = 10;
}

message NpcMonsterRogueInfo {
    uint32 IEDEBFCCKNL = 7;
    uint32 elite_group = 12;
    uint32 hard_level_group = 13;
    uint32 level = 4;
    uint32 rogue_monster_id = 15;
    JNBOIFCNBCH DPCNDADDCAJ = 9;
}

message NpcRogueGameInfo {
    uint32 AIAFEKGBFIF = 10;
    uint32 OEANPIHCHHF = 15;
    map<uint32, uint32> LDPAJKIEPIP = 5;
    bool FKKMLJNKHDH = 7;
    bool NLAFLKPLPFE = 1;
    uint32 MJBKNMJHOGP = 9;
    bool DJEPGKBMICM = 4;
}

message PropRogueInfo {
    uint32 MAJKFIMPOOF = 9;
    uint32 KKMEFDEFLBI = 10;
    uint32 room_id = 5;
    uint32 GECOCMLBBPE = 14;
}

enum RogueStatus {
    RogueStatus_None = 0;
    RogueStatus_Doing = 1;
    RogueStatus_Pending = 2;
    RogueStatus_Endless = 3;
    RogueStatus_Finish = 4;
}

enum RogueTalentStatus {
    RogueTalentStatus_Lock = 0;
    RogueTalentStatus_Unlock = 1;
    RogueTalentStatus_Enable = 2;
}

message SceneInfo {
    MissionStatusBySceneInfo scene_mission_info = 1917;
    SceneIdentifier scene_identifier = 1241;
    repeated HGNBPANECAL CPIKFGPCOCE = 8;
    repeated BuffInfo scene_buff_info_list = 4;
    repeated SceneEntityGroupInfo entity_group_list = 55;
    repeated CustomSaveData custom_data_list = 3;
    uint64 interact_id = 1935;
    uint32 leader_entity_id = 5;
    uint32 game_story_line_id = 1175;
    uint32 plane_id = 14;
    repeated uint32 opened_chests_list = 7;
    uint32 content_id = 1617;
    uint32 entry_id = 11;
    map<string, int32> floor_saved_data = 1562;
    uint32 game_mode_type = 9;
    repeated SceneEntityInfo entity_list = 2;
    uint32 floor_id = 15;
    map<uint32, HIEKLHPINHL> BIKBFGPFAAC = 12;
    uint32 dimension_id = 837;
    repeated uint32 lighten_section_list = 1224;
    BELNLOJAFCM FOJJGJPIMBL = 2041;
    uint32 client_pos_version = 1;
    uint32 world_id = 10;
}

// ========================= RogueCommon =========================

message AKMCODLAEKI {
    string key = 4;
    double value = 13;
}

message AMKALFJHFJP {
    uint32 LGIPILAKIKB = 11;
    repeated uint32 BPDDBKGDMDD = 1;
    uint32 FAHAMJFPMMI = 9;
    uint32 LIFJCJKNKNJ = 6;
}

message BDJLHJDPEEK {
    uint32 level = 7;
    uint32 composition_type = 12;
    uint32 unique_id = 8;
    repeated uint32 attribute_list = 1;
}

message DNLKMHLAPHC {
    repeated LDKMOFFMGEL LEDNAHCKMHK = 2;
    repeated OKCCLEEPELM AJFLAHGJELP = 12;
    map<uint32, uint32> HCPNPDLJKGF = 5;
    OCBPJLLLJGO OOPCPMANCBO = 8;
}

message GGGBAIAPDLO {
    RogueCommonBuffSelectSourceType source_type = 5;
    uint32 EGFOLKEPNCI = 14;
    uint32 PCGFIOKLIBE = 4;
    repeated KJAMNOGFAMJ LEOFNINDJDB = 2;
    ItemCostData DEHJDNIEKHB = 3;
    uint32 NOAMCDNNHMD = 10;
    uint32 EIALMEADLGF = 6;
    uint32 NKGGAOJLCMD = 8;
    repeated uint32 EBMEEKJGPPM = 1;
    bool can_roll = 15;
    uint32 FIMMFJCKCNK = 7;
}

message HKOEAOPNEAC {
    uint32 KMNDBEPFMGN = 6;
    uint32 GPNJGMEPMMD = 15;
    repeated BHPBJOMBCAD AJKOKAJABFG = 9;
    ItemCostData CANJGJIDKHK = 11;
    uint32 JAEDKHMMPIH = 3;
    uint32 DGGCFDKJDPO = 5;
    bool CEIIGJEOIAD = 10;
}

message HMAAICNBKCI {
    map<uint32, int32> DCLBHOHPGMB = 5;
}

message ItemCostData {
    repeated ItemCost item_list = 5;
}

message JDFNPICGCGI {
    bool KLGGHNILHIC = 12;
    uint32 LIFJCJKNKNJ = 10;
    repeated uint32 OIMCPHNONPF = 15;
    uint32 FAHAMJFPMMI = 6;
    repeated uint32 MLIDKPGKCIL = 9;
    map<uint32, uint32> KEGHPOHGPFF = 13;
    repeated uint32 GJFPEFCOBFJ = 7;
    repeated uint32 FNIPHPIEBNB = 3;
    ODHJEDHKHOD JBEBEKECKJN = 2;
    bool PLJNPPKFFCO = 14;
}

message KOFMGCNIMIN {
    uint32 DGGCFDKJDPO = 15;
    uint32 total_count = 2;
    uint32 LJCEOGPOGBE = 11;
}

message KPOFAPDKBJA {
    uint32 DAEMEBCKHIK = 5;
    uint32 PNNCEGEMAPP = 2;
    repeated uint32 PGACPPNAFFF = 9;
    uint32 LGIPILAKIKB = 6;
    uint32 FBJLLMGOPHO = 1;
}

message LEJFIEPMMGG {
    uint32 KAHMGPGPOII = 6;
    repeated CBDMGEGELFM IFJIHNBDNGN = 1;
    bool is_activated = 4;
}

message LGFOKKPICEH {
    uint32 KGOPHALLLLI = 14;
    uint32 CFKKKPNKHEL = 13;
}

message MMBBHFNJILI {
    OKCCLEEPELM OJEANDPABHC = 9;
    uint32 unique_id = 13;
}

enum MMFOGJPOHGJ {
    MMFOGJPOHGJ_NLCDGIPGFDJ = 0;
    MMFOGJPOHGJ_ANBKDJKHCBI = 1;
    MMFOGJPOHGJ_CFLNLFPNKPF = 2;
    MMFOGJPOHGJ_HHGAHPNPCJN = 3;
    MMFOGJPOHGJ_EELBIOJDKOH = 4;
    MMFOGJPOHGJ_CGBEHICONCC = 5;
}

message OCBPJLLLJGO {
    uint32 GCAHKLNGFCK = 6;
    uint32 level = 7;
}

message OFMCKLEMOMP {
    uint32 DENIIHGKNFM = 2;
    uint32 LGIPILAKIKB = 14;
    bool can_roll = 9;
    uint32 OJCEEICJBGI = 7;
    repeated uint32 ONECEAIJLAM = 6;
    ItemCostData GOOMJPLEIKL = 5;
}

message OHJJMCMJEHL {
    bool ODBKCIBGLLP = 14;
    uint32 MLJHCOGNJEL = 1;
    uint32 DAEMEBCKHIK = 11;
    uint32 NAENAEGAEAF = 9;
    repeated uint32 BLAHNLDHINC = 7;
}

message OMJGKNJKHCH {
    int32 NGIBKCODMAL = 12;
    uint32 IGNACLJKFGO = 14;
    int32 JOCCAPDMHGB = 2;
}

message ONMFMINNBEB {
    OCBPJLLLJGO DDLADFJMEEC = 3;
}

message PGMIABHEJNB {
    bool EAGILFBCKJH = 8;
    uint32 NBCECAHLGLM = 6;
    repeated uint32 ICCMIEHKDAO = 2;
    uint32 KJOFBAAHDCO = 15;
}

enum RogueCommonBuffSelectSourceType {
    RogueCommonBuffSelectSourceType_None = 0;
    RogueCommonBuffSelectSourceType_DiceRoll = 1;
    RogueCommonBuffSelectSourceType_Aeon = 2;
    RogueCommonBuffSelectSourceType_BoardEvent = 3;
    RogueCommonBuffSelectSourceType_LevelMechanism = 4;
}

// ========================= RogueMagic =========================

message CBOLONJDHHL {
    uint32 LJOBBEFACPG = 11;
    NCHGLFJCGIJ modifier = 14;
    string trans_no = 15;
    uint32 ICGCMEIBJLC = 13;
    INHBMHCJJCN FMIGOKIDKJL = 2;
    uint32 DLOJFEEHLIJ = 8;
    GMIMDEJMFCO blackboard = 5;
}

message FKEDPCMLIFE {
    map<uint32, uint32> HJANIOKJALB = 11;
}

message JEIKFFFGONB {
    ItemCostData LNIEFKBMIPD = 6;
    repeated DINGDGLKHIP BHBPKKKNABO = 11;
}

message OKCCLEEPELM {
    uint32 CFKKKPNKHEL = 6;
    uint32 level = 15;
}

// ========================= RogueTourn =========================

message ODHJEDHKHOD {
    repeated uint32 BIMFEAHDMIK = 4;
    repeated uint32 NMMCOBBKKHA = 15;
}

// ========================= Scene =========================

message BuffInfo {
    uint32 level = 9;
    uint32 count = 12;
    uint32 buff_summon_entity_id = 7;
    uint32 buff_id = 13;
    uint64 add_time_ms = 3;
    float life_time = 10;
    map<string, float> dynamic_values = 15;
    uint32 base_avatar_id = 8;
}

message MissionStatusBySceneInfo {
    repeated uint32 unfinished_main_mission_id_list = 11;
    repeated MainMissionCustomValue JLMGBADJBKN = 6;
    repeated Mission sub_mission_status_list = 14;
    repeated uint32 finished_main_mission_id_list = 2;
    repeated uint32 disabled_main_mission_id_list = 3;
}

message PropExtraInfo {
    PropRogueInfo rogue_game_info = 13;
    HLFAKEOBFAB AEFMMOHKCHJ = 1;
    BGFLAKMOIGC OGLJIOJBIEN = 11;
    EBBOJACNHEC ADNHHAELLNC = 7;
    APKENKIDMGC ACJPMKHJLDB = 8;
    NBDKNCJGOMN OEMHOKEMBKM = 3;
    ONNEJIPGHCK MFCPLGHHPNP = 6;
    PGLLFCMEFKG IDMAELPELLA = 10;
    PropTimelineInfo timeline_info = 4;
}

message PropTimelineInfo {
    bytes timeline_byte_value = 15;
    bool timeline_bool_value = 10;
}

message SceneActorInfo {
    uint32 base_avatar_id = 1;
    AvatarType avatar_type = 7;
    uint32 map_layer = 2;
    uint32 uid = 15;
}

message SceneBattleInfo {
    uint32 stage_id = 3;
    uint32 monster_wave_length = 9;
    uint32 logic_random_seed = 8;
    bool encrypt_result = 11;
    KIAICMELIMM battle_sword_training_data = 1425;
    GLIBGKGGEJL battle_fate_rin_data = 492;
    PKPFAHEBJIO battle_fate_data = 1594;
    repeated BattleBuff buff_list = 10;
    EDCFKACPFNB battle_action_event_id = 1578;
    map<uint32, BattleTargetList> battle_target_info = 145;
    repeated BattleAvatar battle_avatar_list = 14;
    BattleGridFightSpecialBattleInfo battle_evolve_build_data = 444;
    uint32 battle_id = 7;
    GridFightInfo battle_grid_fight_data = 1920;
    uint32 rounds_limit = 13;
    uint32 world_level = 4;
    repeated SceneMonsterWave monster_wave_list = 5;
    BattleRogueMagicInfo battle_rogue_magic_info = 254;
    repeated BattleEventBattleInfo battle_event = 745;
}

message SceneEntityGroupInfo {
    uint32 group_id = 1;
    uint32 state = 6;
    repeated SceneEntityInfo entity_list = 11;
    map<string, int32> BANBECDCDHG = 9;
}

message SceneEntityInfo {
    uint32 group_id = 1;
    uint32 inst_id = 4;
    MotionInfo motion = 7;
    uint32 entity_id = 8;
    SceneActorInfo actor = 2;
    SceneNpcMonsterInfo npc_monster = 12;
    SceneNpcInfo npc = 13;
    ScenePropInfo prop = 9;
    SceneSummonUnitInfo summon_unit = 6;
}

message SceneIdentifier {
    uint32 content_id = 9;
    uint32 game_story_line_id = 8;
    uint32 floor_id = 13;
    TeleportInfo teleport_info = 883;
}

message SceneMonster {
    uint32 max_hp = 8;
    uint32 monster_id = 11;
    MNDMNDKLKIE extra_info = 3;
    uint32 cur_hp = 7;
}

message SceneMonsterWave {
    uint32 battle_wave_id = 3;
    repeated SceneMonster monster_list = 13;
    uint32 battle_stage_id = 9;
    SceneMonsterWaveParam monster_param = 4;
    repeated ItemList NMGIABHIJJB = 12;
}

message SceneMonsterWaveParam {
    uint32 CPHIINKIDEB = 13;
    uint32 level = 2;
    uint32 elite_group = 8;
    uint32 hard_level_group = 1;
    uint32 IEDEBFCCKNL = 11;
}

message SceneNpcInfo {
    NpcExtraInfo extra_info = 3;
    uint32 npc_id = 7;
}

message SceneNpcMonsterInfo {
    bool NHKJKNJAGMF = 15;
    uint32 event_id = 2;
    uint32 monster_id = 6;
    GILBMELHGCB BMIJGBFJMCF = 9;
    bool NMPEOMMHMPP = 13;
    NpcMonsterExtraInfo extra_info = 3;
    uint32 world_level = 7;
}

message ScenePropInfo {
    PropExtraInfo extra_info = 11;
    uint32 life_time_ms = 3;
    uint32 prop_id = 8;
    repeated string trigger_name_list = 15;
    uint32 prop_state = 12;
    uint64 create_time_ms = 13;
}

message SceneSummonUnitInfo {
    uint32 summon_unit_id = 11;
    uint32 caster_entity_id = 8;
    uint64 create_time_ms = 13;
    uint32 attach_entity_id = 15;
    int32 life_time_ms = 6;
    repeated string trigger_name_list = 10;
}

message Vector {
    sint32 x = 1;
    sint32 y = 2;
    sint32 z = 3;
}

// ========================= TrainParty =========================

message AreaDynamicInfo {
    uint32 diy_dynamic_id = 11;
    uint32 dice_slot_id = 8;
}

message OIIPJFDNPAH {
    repeated AreaDynamicInfo GOEJIMNENDC = 12;
    repeated CLLBJDEJFNF OFOKOHGPEDO = 2;
    repeated POFNNGOCEOK POLMJFIKNHN = 6;
}
