syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdEvolveBuildType.proto";
import "Orphans.proto";

message GetEvolveBuildCoinNotify {
    uint32 item_value = 6;
    EDJKFOBBDJF HFPEJIDDDJG = 8;
}

message GetEvolveBuildFinishScNotify {
    uint32 exp = 6;
    uint32 item_value = 1;
    uint32 level_id = 3;
    uint32 wave = 15;
    bool NLMAFMCFHAL = 5;
    LDLCMMOPKNG OEIBHLMDJKA = 11;
    uint32 score_id = 14;
    IAPIIEJHLMP APKKKEIPJOG = 8;
}

message GetEvolveBuildGiveupScRsp {
    LDLCMMOPKNG OEIBHLMDJKA = 15;
    uint32 retcode = 11;
}

message GetEvolveBuildQueryInfoScRsp {
    repeated LDLCMMOPKNG JPDOIGJNGNP = 5;
    uint32 retcode = 14;
    CJJHNFICDIM CFDIKLBINHK = 2;
}

message GetEvolveBuildReRandomStageScRsp {
    uint32 retcode = 11;
    HLOADNFIOOO GMBPFFIABHJ = 13;
}

message GetEvolveBuildShopAbilityDownScRsp {
    uint32 level = 15;
    uint32 retcode = 3;
    uint32 JEKLOEPPJBK = 13;
}

message GetEvolveBuildShopAbilityResetScRsp {
    repeated GOMKGHJBNFM CEPCGLMFPBC = 15;
    EDJKFOBBDJF HFPEJIDDDJG = 11;
    uint32 retcode = 8;
    uint32 item_value = 9;
}

message GetEvolveBuildShopAbilityUpScRsp {
    uint32 retcode = 11;
    uint32 level = 5;
    uint32 JEKLOEPPJBK = 9;
}
