syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message JMAHAKPLAAD {
}

enum PlanetFesCardPieceApplyPermissionType {
    PlanetFesCardPieceApplyPermissionType_PlanetFesCardPieceApplyPermissionReview = 0;
    PlanetFesCardPieceApplyPermissionType_PlanetFesCardPieceApplyPermissionFree = 1;
    PlanetFesCardPieceApplyPermissionType_PlanetFesCardPiecePermissionBan = 2;
}

enum PlanetFesCustomKey {
    PlanetFesCustomKey_None = 0;
    PlanetFesCustomKey_UnlockInfiniteBusinessDayPerformance = 1;
    PlanetFesCustomKey_BusinessDayStartPerformanceLastSeenDay = 2;
    PlanetFesCustomKey_BusinessDayUnlockPerformanceLastSeenDay = 3;
    PlanetFesCustomKey_SummaryShow = 4;
}

message PlanetFesDemandCsReq {
    uint32 LANLJAPHOCL = 15;
    repeated uint32 ODLGJOLIOKD = 10;
}

message PlanetFesPresentCsReq {
    uint32 LANLJAPHOCL = 15;
    repeated uint32 IPJLIBPNKHG = 7;
}

message PlanetFesSkillLevelUpScRsp {
    FMKMEFMOJGJ item_cost = 1;
    uint32 skill_level = 5;
    uint32 retcode = 10;
    uint32 skill_id = 7;
}
