syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdChessRogueType.proto";
import "Common.proto";

message ChooseAvatarCsReq {
    uint32 KOEOEHIMOEI = 6;
}

message ChooseAvatarScRsp {
    uint32 retcode = 15;
    uint32 avatar_id = 3;
}

message CmdPickRogueAvatarScRsp {
    uint32 PLDKENJLKME = 1;
    repeated uint32 NDFHHFGKMAI = 3;
}

message CmdReviveRogueAvatarScRsp {
    uint32 PLDKENJLKME = 14;
    GAJDPEBBFMG PHNAANFIFGB = 3;
}

message DisplayAvatarData {
    uint32 avatar_id = 1;
    uint32 pos = 9;
}

message ModifyAvatarDiceRsp {
    DiceCombatAvatar avatar = 5;
    uint32 retcode = 8;
}

message UpgradeAvatarRsp {
    DiceCombatAvatar avatar = 15;
    uint32 retcode = 5;
}
