syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Orphans.proto";

message GridFightDestroyWeeklyRewardCsReq {
    repeated uint32 BHNEOLKFNAM = 2;
}

message GridFightGetOrbCsReq {
    bool JPNGMNGLHCI = 4;
    repeated uint32 NIBGJKIMFBH = 1;
}

message GridFightHandleElationTemplateCsReq {
    uint32 GEPLKKBDGGD = 5;
    LAPOAFHDNCM KHGHBGFGKIK = 1822;
    EPLJJNHCJIF MKIKLBENMFE = 1715;
    CJPOMFIDLOA HHCBEOEBBAI = 1849;
    GIOLAAKLDED IBNMLKPALFD = 1475;
    GKLDOELMEIN IBAHLKLDEDG = 1295;
    OHAINOHGKCM FKCNELEEPPF = 1323;
    NIDJPBLNDLH PBODJNNNBKH = 1755;
    NNFPCAPDENH FJHDGFCOKIH = 1298;
    AJDFPFHBFJM OABLFGBAAPC = 624;
    NEMAKFJPGDF PHCBFMINIMI = 328;
    HMNMJKCHABE BJDLOIDMPLO = 835;
    DFMGEJCCBPD INHAGJIAHDH = 430;
    PDKGKIDCBKA CADKKHGFMND = 1395;
    DGILDLDMGEI JPMOBEGPKDG = 1586;
    PCCGPNAFMHP AJODDDOOIEI = 1348;
    LFONAPFHAOB JDGENKHPIJO = 394;
    FNNFHNKHIDD LCBFFPJFOFE = 1768;
    IDOJADMFGKF PCCPNBOELHB = 1319;
    EJEFKJGAKOO MGCEJGNFOPN = 1353;
    FKILNIGOKBF LMMCPPALICA = 281;
    KCCPHHGCPMP FHFACNJGIPP = 162;
}

message GridFightPermanentTalentEnableScRsp {
    uint32 CKHCLKOALKE = 9;
    uint32 retcode = 1;
}

message GridFightPermanentTalentResetScRsp {
    uint32 retcode = 10;
}

message GridFightRoleShopBuyGoodsScRsp {
    repeated uint32 IEFKHAMBJKH = 7;
    uint32 PLDKENJLKME = 9;
}

message GridFightSeasonTalentEnableScRsp {
    uint32 retcode = 14;
    uint32 CKHCLKOALKE = 6;
}

message GridFightSeasonTalentResetScRsp {
    uint32 retcode = 5;
}

message GridFightSyncKeepWinCntNotify {
    uint32 EHBLJGIENPI = 10;
}

message GridFightSyncVirtualItemNotify {
    repeated CENBJOMMJGD item_list = 4;
}

message GridFightUpdateEquipTrackPriorityCsReq {
    repeated EPELDFBCCEK IDNLMNIDIAK = 10;
}

message GridFightUpdateTraitElationCsReq {
    uint32 BDHJLOLMAKK = 11;
    uint32 MJJGNBCFCOH = 9;
    GPCFHMLMDHC LEGMCEMDFCM = 649;
    AFPJPEABFKH INEBAKJIBGI = 773;
    MHKNPBJDFIC LMMCPPALICA = 532;
}

message GridFightWeeklyExtraSeasonExpScRsp {
    uint32 ACDOIGCBGEB = 1;
}
