syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdChallengeTierceType.proto";
import "Common.proto";

message ChallengeTierceMedal {
    uint32 group_id = 14;
}

message ChallengeTierceReward {
    ItemList reward = 9;
    uint32 HEJANCCDGAP = 5;
}

message ChallengeTierceStageClear {
    uint32 challenge_id = 8;
    repeated uint32 LICPEKHDJGK = 13;
}

message ChallengeTierceSyncAllStage {
    bool is_passed = 1483;
    repeated ChallengeTierceReward DJOBNPIAEJP = 8;
    uint32 challenge_id = 15;
    repeated ChallengeTierceStageData GBMBAHHDONN = 3;
    repeated uint32 finished_target_list = 1426;
    ChallengeTierceRecord EGEHLOPFELK = 11;
}

message ChallengeTierceSyncNotify {
    ChallengeTierceSyncSingleStage IANBCDJPDJF = 11;
    ChallengeTierceSyncAllStage DFNNKENBOEN = 4;
    ChallengeTierceStageClear IBFHHKHNEFL = 1;
    ChallengeTiercePendingStageSettle IIHFEDLHOPI = 2;
    ChallengeTierceMedal medal = 9;
}

message ChallengeTierceSyncSingleStage {
    bool is_passed = 995;
    ChallengeTierceStageData stage_data = 10;
    repeated uint32 finished_target_list = 773;
}

message RestartChallengeTierceScRsp {
    uint32 retcode = 10;
    SceneInfo scene = 14;
}

message StartChallengeTierceNextStageScRsp {
    ChallengeTierceChallengeInfo challenge_tierce_info = 7;
    SceneInfo scene = 12;
    uint32 retcode = 6;
}
