syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ALIMNHEENPP {
    uint32 role_star = 1;
    repeated BCCONKJHDJL IEBNOGOOEMO = 2;
}

enum BattleModuleType {
    BattleModuleType_BattleModuleMaze = 0;
    BattleModuleType_BattleModuleChallenge = 1;
    BattleModuleType_BattleModuleCocoon = 2;
    BattleModuleType_BattleModuleRogue = 3;
    BattleModuleType_BattleModuleChallengeActivity = 4;
    BattleModuleType_BattleModuleTrialLevel = 5;
    BattleModuleType_BattleModuleAetherDivide = 6;
}

message BattleMonster {
    uint32 monster_id = 1;
    uint32 cur_hp = 2;
    uint32 max_hp = 3;
    LJHDMKEBPDH extra_info = 4;
}

message BattleMonsterParam {
    uint32 hard_level_group = 1;
    uint32 level = 2;
    uint32 elite_group = 3;
    uint32 IEDEBFCCKNL = 4;
    uint32 CPHIINKIDEB = 5;
}

message BattleMonsterWave {
    repeated BattleMonster monster_list = 1;
    BattleMonsterParam monster_param = 2;
    uint32 battle_stage_id = 3;
    uint32 battle_wave_id = 4;
}

message BattleOp {
    uint32 turn_counter = 1;
    uint32 state = 2;
    uint32 action_entity_id = 3;
    uint32 target_entity_id = 4;
    uint32 op_type = 5;
    uint32 skill_index = 6;
    uint32 operation_counter = 7;
    string LOMLIPOLBKM = 8;
}

message DBCBMJKOBPJ {
    repeated BattleAvatar avatar_list = 1;
    repeated BattleMonsterWave monster_wave_list = 2;
    repeated BattleBuff buff_list = 3;
    uint32 world_level = 7;
    map<uint32, BattleTargetList> battle_target_info = 9;
    EDCFKACPFNB battle_action_event_id = 10;
    repeated BattleAvatar EEIPNLJNJAL = 11;
    BattleGridFightSpecialBattleInfo battle_evolve_build_data = 12;
    KIAICMELIMM battle_sword_training_data = 13;
    BattleRogueMagicInfo battle_rogue_magic_info = 14;
    PKPFAHEBJIO battle_fate_data = 15;
    GridFightInfo battle_grid_fight_data = 16;
    GLIBGKGGEJL battle_fate_rin_data = 17;
}

message EBPDNOOMHBD {
    repeated JIEAANCEIJP JJOGEHPDOKH = 1;
    string BDGLPMHPEKD = 2;
    string debug_extra_info = 3;
    repeated PAPJEPAJPCJ ADAILGDCPNH = 4;
    uint32 plane_id = 5;
    uint32 floor_id = 6;
    uint32 ABDBLDPCJCJ = 7;
    uint32 PBIGECFCHEN = 8;
    IBHHJPCIOIC COBOAEBCMCO = 9;
    uint32 IOHJEHHHPCL = 10;
}

message EICNFLHIHOI {
    bool GGOPPDKDPME = 1;
    uint32 OKHBCLCCLPL = 2;
    bool LGJMMJEFGNK = 3;
    string HAKCLAHLPFG = 4;
    bool IICCMNMEOFI = 5;
    bool DEBAOCJBBNB = 6;
    uint32 GCKHDGOBFOC = 7;
}

message HOLHBEOHEJD {
    uint32 interact_id = 1;
    repeated uint64 properties = 2;
}

message IBHHJPCIOIC {
    bool ECLAGOJMMBO = 1;
    map<string, MOHMAHDOBDO> JKMHAJHIKIK = 2;
    bytes AFMFNCGCNHI = 3;
}

message JIEAANCEIJP {
    uint32 turn_counter = 1;
    uint32 random_counter = 2;
    repeated HOLHBEOHEJD snapshot_list = 4;
    uint32 AMCPMEAOJJK = 6;
}

message LJHDMKEBPDH {
    ALIMNHEENPP EIGMKOJOEEI = 101;
}

message MOHMAHDOBDO {
    uint32 start_pos = 1;
    uint32 length = 2;
}

enum OIKBIPICGDN {
    OIKBIPICGDN_KNDKKGPEJAG = 0;
    OIKBIPICGDN_POGHAGEGKDN = 1;
    OIKBIPICGDN_FLMDIEEMOJK = 2;
    OIKBIPICGDN_ONAANCDBFJK = 3;
}

message OJHHHPLBIEJ {
    repeated AetherAvatarInfo avatar_list = 1;
    repeated BattleMonsterWave monster_wave_list = 2;
    repeated BattleBuff buff_list = 3;
}

message OKFLAHFIBCM {
    uint32 version = 1;
    uint32 logic_random_seed = 2;
    uint32 stage_id = 3;
    DBCBMJKOBPJ lineup = 4;
    repeated BattleOp op_list = 5;
    bytes turn_snapshot_hash = 6;
    uint32 FMOAAHKDGNP = 7;
    repeated uint32 DACGLGHGLIG = 8;
    bool NNGDLOHALCN = 9;
    OIKBIPICGDN MBHFMFEMPOM = 10;
    BattleModuleType JKCEIMCCBBA = 11;
    repeated BattleEventBattleInfo battle_event = 12;
    uint32 rounds_limit = 14;
    EICNFLHIHOI config = 15;
    bytes IJHANPILBAM = 16;
    uint32 NIBMFCFBHEP = 17;
    uint32 monster_wave_length = 18;
    OJHHHPLBIEJ APFNIHDLFIE = 19;
    EBPDNOOMHBD DDFABAGIHMD = 100;
}

message PAPJEPAJPCJ {
    int32 hash = 1;
    string value = 2;
}
