syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdPlanetFesType {
    CmdPlanetFesType_None = 0;
    CmdPlanetFesType_PlanetFesAvatarLevelUpScRsp = 8233;
    CmdPlanetFesType_PlanetFesGetFriendRankingInfoListScRsp = 8244;
    CmdPlanetFesType_PlanetFesTakeRegionPhaseRewardScRsp = 8227;
    CmdPlanetFesType_PlanetFesStartMiniGameScRsp = 8230;
    CmdPlanetFesType_PlanetFesGetAvatarStatCsReq = 8219;
    CmdPlanetFesType_PlanetFesBusinessDayRefreshEventCsReq = 8216;
    CmdPlanetFesType_PlanetFesSetAvatarWorkCsReq = 8222;
    CmdPlanetFesType_PlanetFesAvatarLevelUpCsReq = 8236;
    CmdPlanetFesType_PlanetFesTakeRegionPhaseRewardCsReq = 8228;
    CmdPlanetFesType_PlanetFesSetCustomKeyValueScRsp = 8250;
    CmdPlanetFesType_PlanetFesGetAvatarStatScRsp = 8245;
    CmdPlanetFesType_PlanetFesDeliverPamCargoCsReq = 8220;
    CmdPlanetFesType_PlanetFesAvatarLevelUpScRsp_8214 = 8214;
    CmdPlanetFesType_PlanetFesGetFriendRankingInfoListCsReq = 8201;
    CmdPlanetFesType_PlanetFesUseItemScRsp = 8226;
    CmdPlanetFesType_PlanetFesUseItemCsReq = 8241;
    CmdPlanetFesType_PlanetFesDoGachaCsReq = 8212;
    CmdPlanetFesType_GetPlanetFesDataScRsp = 8231;
    CmdPlanetFesType_PlanetFesStartMiniGameCsReq = 8239;
    CmdPlanetFesType_PlanetFesBonusEventInteractScRsp = 8234;
    CmdPlanetFesType_PlanetFesCollectAllIncomeCsReq = 8217;
    CmdPlanetFesType_PlanetFesChooseAvatarEventOptionCsReq = 8229;
    CmdPlanetFesType_PlanetFesDoGachaCsReq_8211 = 8211;
    CmdPlanetFesType_PlanetFesDeliverPamCargoScRsp = 8210;
    CmdPlanetFesType_PlanetFesUseItemCsReq_8206 = 8206;
    CmdPlanetFesType_PlanetFesSetCustomKeyValueCsReq = 8202;
    CmdPlanetFesType_PlanetFesTakeQuestRewardScRsp = 8225;
    CmdPlanetFesType_PlanetFesGetBusinessDayInfoScRsp = 8235;
    CmdPlanetFesType_PlanetFesStartMiniGameCsReq_8240 = 8240;
    CmdPlanetFesType_PlanetFesGetFriendRankingInfoListScRsp_8209 = 8209;
    CmdPlanetFesType_PlanetFesDoGachaScRsp = 8205;
    CmdPlanetFesType_PlanetFesBuyLandCsReq = 8237;
    CmdPlanetFesType_PlanetFesBusinessDayRefreshEventScRsp = 8213;
    CmdPlanetFesType_PlanetFesBusinessDayRefreshEventScRsp_8247 = 8247;
    CmdPlanetFesType_PlanetFesDealAvatarEventOptionItemCsReq = 8246;
    CmdPlanetFesType_PlanetFesFriendRankingInfoChangeScNotify = 8248;
    CmdPlanetFesType_PlanetFesSyncChangeScNotify = 8203;
    CmdPlanetFesType_PlanetFesDealAvatarEventOptionItemScRsp = 8223;
    CmdPlanetFesType_PlanetFesTakeQuestRewardCsReq = 8249;
    CmdPlanetFesType_PlanetFesChooseAvatarEventOptionScRsp = 8238;
    CmdPlanetFesType_PlanetFesSkillLevelUpScRsp = 8208;
    CmdPlanetFesType_GetPlanetFesDataCsReq = 8204;
    CmdPlanetFesType_PlanetFesTakeRegionPhaseRewardScRsp_8218 = 8218;
    CmdPlanetFesType_PlanetFesBonusEventInteractCsReq = 8221;
    CmdPlanetFesType_PlanetFesGameBingoFlipScRsp = 8224;
    CmdPlanetFesType_PlanetFesSkillLevelUpCsReq = 8242;
    CmdPlanetFesType_PlanetFesGameBingoFlipCsReq = 8232;
    CmdPlanetFesType_PlanetFesGetFriendRankingInfoListCsReq_8215 = 8215;
    CmdPlanetFesType_PlanetFesDealAvatarEventOptionItemCsReq_8243 = 8243;
    CmdPlanetFesType_PlanetFesDeliverPamCargoScRsp_8207 = 8207;
}
