name: build  # 👈 ชื่อ workflow ต้องเป็นตัวเล็ก เพื่อให้ nightly.link ใช้งานได้

on:
  push:
    branches:
      - 'SophonDownloader'
    paths-ignore:
      - '**/README.md'
      - '**/build.yml'
      - '**/.gitignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Sophon.Downloader.sln
        working-directory: Sophon.Downloader

      - name: Build (Publish)
        run: dotnet publish Sophon.Downloader.sln -c Release -o output
        working-directory: Sophon.Downloader

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sophon.Downloader
          path: Sophon.Downloader/output/
