name: Build

on:
  push:
    branches:
      - 'SophonDownloader'
    paths-ignore:
      - '**/README.md'
      - '**/build.yml'
      - '**/.gitignore'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Sophon.Downloader.sln
        working-directory: Sophon.Downloader

      - name: Build
        run: dotnet build Sophon.Downloader.sln -c Release --no-restore
        working-directory: Sophon.Downloader

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sophon.Downloader
          path: Sophon.Downloader/Core/bin/Release/*

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "Sophon.Downloader/Core/bin/Release/*" `
            -DestinationPath "Sophon.Downloader.zip" `
            -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_number }}"
          name: "Sophon.Downloader Build ${{ github.run_number }}"
          generate_release_notes: true
          files: Sophon.Downloader.zip
