name: Hoyo Game Monitor 13:30

on:
  schedule:
    - cron: "30 6 * * *" # รันทุกวันเวลา 13:30 (เวลาไทย)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -U discord.py

      - name: Run all miHoYo game monitors
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN_1 }}
        run: |
          python "HoyoGame/CN/Branches/原神 Branches.py"
          python "HoyoGame/CN/Branches/崩坏：因缘精灵 Branches.py"
          python "HoyoGame/CN/Branches/崩坏：星穹铁道 Branches.py"
          python "HoyoGame/CN/Branches/崩坏3 Branches.py"
          python "HoyoGame/CN/Branches/星布谷地 Branches.py"
          python "HoyoGame/CN/Branches/绝区零 Branches.py"
          python "HoyoGame/CN/Branches/星布谷地 Branches.py"

          python "HoyoGame/CN/Packages/原神.py"
          python "HoyoGame/CN/Packages/崩坏：因缘精灵.py"
          python "HoyoGame/CN/Packages/崩坏：星穹铁道.py"
          python "HoyoGame/CN/Packages/崩坏3.py"
          python "HoyoGame/CN/Packages/星布谷地.py"
          python "HoyoGame/CN/Packages/绝区零.py"
          python "HoyoGame/CN/Packages/星布谷地.py"

          python "HoyoGame/OS/Branches/Genshin Impact Branches.py"
          python "HoyoGame/OS/Branches/Honkai Impact3 Branches.py"
          python "HoyoGame/OS/Branches/Honkai Nexun Anima Branches.py"
          python "HoyoGame/OS/Branches/Honkai Star Rail Branches.py"
          python "HoyoGame/OS/Branches/Petit Planet Branches.py"
          python "HoyoGame/OS/Branches/Zenless Zone Zero Branches.py"

          python "HoyoGame/OS/Packages/Genshin Impact.py"
          python "HoyoGame/OS/Packages/Honkai Impact3.py"
          python "HoyoGame/OS/Packages/Honkai Nexun Anima.py"
          python "HoyoGame/OS/Packages/Honkai Star Rail.py"
          python "HoyoGame/OS/Packages/Petit Planet.py"
          python "HoyoGame/OS/Packages/Zenless Zone Zero.py"

      - name: Commit and Push logs
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          mkdir -p log/OSHoyo/Branches
          mkdir -p log/CNHoyo/Branches
          mkdir -p log/OSHoyo/Packages
          mkdir -p log/CNHoyo/Packages

          git add log/OSHoyo/Branches
          git add log/CNHoyo/Branches
          git add log/OSHoyo/Packages
          git add log/CNHoyo/Packages

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update logs [skip ci]"

          git push origin HEAD:Webhook
