name: Hoyo Game Monitor OS 05:00

on:
  schedule:
    - cron: "0 22 * * *" # รันทุกวันเวลา 05:00 (เวลาไทย)
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests


      - name: Run all game monitors
        run: |
            pip install -U pip
            pip install requests discord.py


      - name: Run all game monitors
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN_1 }}
        run: |

          python "HoyoGame/CN/Branches/原神 Branches.py"
          python "HoyoGame/CN/Branches/崩坏：因缘精灵 Branches.py"
          python "HoyoGame/CN/Branches/崩坏：星穹铁道 Branches.py"
          python "HoyoGame/CN/Branches/崩坏3 Branches.py"
          python "HoyoGame/CN/Branches/星布谷地 Branches.py"
          python "HoyoGame/CN/Branches/绝区零 Branches.py"

          python "HoyoGame/OS/Branches/Genshin Impact Branches.py"
          python "HoyoGame/OS/Branches/Honkai Impact3 Branches.py"
          python "HoyoGame/OS/Branches/Honkai Nexun Anima Branches.py"
          python "HoyoGame/OS/Branches/Honkai Star Rail Branches.py"
          python "HoyoGame/OS/Branches/Petit Planet Branches.py"
          python "HoyoGame/OS/Branches/Zenless Zone Zero Branches.py"

          python "HoyoGame/CN/Packages/原神.py"
          python "HoyoGame/CN/Packages/崩坏：因缘精灵.py"
          python "HoyoGame/CN/Packages/崩坏：星穹铁道.py"
          python "HoyoGame/CN/Packages/崩坏3.py"
          python "HoyoGame/CN/Packages/星布谷地.py"
          python "HoyoGame/CN/Packages/绝区零.py"

          python "HoyoGame/OS/Packages/Genshin Impact.py"
          python "HoyoGame/OS/Packages/Honkai Impact3.py"
          python "HoyoGame/OS/Packages/Honkai Nexun Anima.py"
          python "HoyoGame/OS/Packages/Honkai Star Rail.py"
          python "HoyoGame/OS/Packages/Petit Planet.py"
          python "HoyoGame/OS/Packages/Zenless Zone Zero.py"

      - name: Commit and Push logs
        env:
          PAT: ${{ secrets.PAT }} # ใส่ Personal Access Token ของคุณใน secrets
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          mkdir -p log/OSHoyo/log
          mkdir -p log/CNHoyo/log

          git add log/OSHoyo/log
          git add log/CNHoyo/log

          if ! git diff --cached --quiet; then
            git commit -m "Update logs [skip ci]"
            git push https://x-access-token:${PAT}@github.com/${{ github.repository }} HEAD:Webhook
          else
            echo "No changes to commit"
          fi
