name: Hoyo Game Monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # ให้ push กลับได้

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run all game monitors
        env:
          WEBHOOK1: ${{ secrets.WEBHOOK1 }}
          WEBHOOK2: ${{ secrets.WEBHOOK2 }}
          WEBHOOK3: ${{ secrets.WEBHOOK3 }}
          WEBHOOK4: ${{ secrets.WEBHOOK4 }}
        run: |
          mkdir -p /log
          python GI.py  >> log/GI.log 2>&1
          python HI3.py >> log/HI3.log 2>&1
          python HSR.py >> log/HSR.log 2>&1
          python ZZZ.py >> log/ZZZ.log 2>&1
          python HNA.py >> log/HNA.log 2>&1

      - name: Commit logs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Hoyo/log/*.log
          git commit -m "Update logs [skip ci]" || echo "No changes to commit"
          git push
