syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ActivityRaidPlacingGameScRsp {
    uint32 retcode = 15;
    oneof EFJLHNMJEED {
        uint32 GFHGCDEJFIE = 1;
        uint32 CAAHDGFMNNO = 5;
    }
}

message AlleyEventChangeNotify {
    uint32 KHANHNFACLN = 4;
    CEKIFBMPEFH OOOACLEFDGM = 15;
}

enum AlleyEventState {
    AJOCCOAIFIF_NAPMFFDMLEK = 0;
    AJOCCOAIFIF_EMJDKBJFFHF = 1;
    AJOCCOAIFIF_MOMHEEPILJO = 2;
    AJOCCOAIFIF_HDGPEEIJIJP = 3;
}

message AlleyFundsScNotify {
    uint32 cur_fund = 10;
}

message AlleyOrderChangedScNotify {
    KPBAIEMEFFH NGKPDFJBNMF = 15;
}

message AlleyPlacingGameCsReq {
    uint32 CAAHDGFMNNO = 4;
    uint32 BEAKGBHFLPJ = 7;
    uint32 JFALDHKOAOL = 8;
    uint32 IDILDCBMECI = 9;
    uint32 JJGKLHLMMNC = 10;
    AlleyPlacingShip GPOMFKNHCPB = 11;
    uint32 DPPOHBGCAGF = 12;
    uint32 cost_time = 13;
    uint32 BNPKLKIENIK = 14;
}

message AlleyPlacingGameScRsp {
    uint32 event_id = 3;
    uint32 LFMHGMJELEE = 4;
    uint32 JKBINMNFPKK = 5;
    uint32 CIBNBDLMEIC = 7;
    uint32 AJBEOCIEPKP = 9;
    uint32 BIJPMOBEIJC = 12;
    uint32 retcode = 13;
}

message AlleyPlacingShip {
    uint32 ship_id = 4;
    repeated CBBPDLPAIPL goods_list = 7;
}

message AlleyShipmentEventEffectsScNotify {
    PICDJHEPJLC JBFIFNPJNHA = 3;
}

message AlleyTakeEventRewardScRsp {
    ItemList reward = 2;
    uint32 retcode = 6;
}

message BOLCGIOGIBP {
    uint32 FMCPHDJEIDC = 4;
    uint32 map_id = 5;
    uint32 max_score = 6;
    uint32 AAMKNOOMEOO = 10;
    uint32 LLEPGPKGBGM = 12;
    uint32 EFBOOJGNKOH = 13;
    ItemList reward = 15;
}

message CBBPDLPAIPL {
    uint32 goods_id = 1;
    repeated GHMINCEANHG NJKDKIEBGHG = 9;
}

message CEKIFBMPEFH {
    uint32 event_id = 7;
    AlleyEventState state = 9;
    uint32 FHMBKAPPAGO = 14;
}

message CKJACADHCCC {
}

enum CmdAlleyType {
    CmdAlleyType_NLCDGIPGFDJ = 0;
    CmdAlleyType_GALIHKOCKCG = 4772;
    CmdAlleyType_AlleyOrderChangedScNotify = 4748;
    CmdAlleyType_AlleyShipmentEventEffectsScNotify = 4705;
    CmdAlleyType_MFPGIFEJJFB = 4784;
    CmdAlleyType_GetSaveLogisticsMapCsReq = 4741;
    CmdAlleyType_LogisticsDetonateStarSkiffCsReq = 4773;
    CmdAlleyType_HKIDPKBBOLM = 4786;
    CmdAlleyType_PrestigeLevelUpScRsp = 4765;
    CmdAlleyType_NKPAMGPIJGI = 4771;
    CmdAlleyType_ONFGKCPEBII = 4747;
    CmdAlleyType_LogisticsGameScRsp = 4758;
    CmdAlleyType_FABMCLAHAKE = 4769;
    CmdAlleyType_GetSaveLogisticsMapScRsp = 4710;
    CmdAlleyType_MLKIKMBONLC = 4742;
    CmdAlleyType_AEHPCEPEDBF = 4712;
    CmdAlleyType_GCHGEKDJMJM = 4780;
    CmdAlleyType_GHICLFBGFDL = 4711;
    CmdAlleyType_ActivityRaidPlacingResultCsReq = 4775;
    CmdAlleyType_ActivityRaidPlacingGameScRsp = 4744;
    CmdAlleyType_AlleyPlacingGameScRsp = 4738;
    CmdAlleyType_AlleyInitCsReq = 4725;
    CmdAlleyType_LogisticsScoreRewardSyncInfoScNotify = 4735;
    CmdAlleyType_LogisticsInfoScNotify = 4721;
    CmdAlleyType_DIMKKLNHPJA = 4713;
    CmdAlleyType_GetAlleyInfoScRsp = 4778;
    CmdAlleyType_AlleyPlacingGameCsReq = 4733;
    CmdAlleyType_AlleyEventChangeNotify = 4726;
    CmdAlleyType_AlleyTakeEventRewardScRsp = 4796;
    CmdAlleyType_AlleyFundsScNotify = 4730;
    CmdAlleyType_TakePrestigeRewardScRsp = 4740;
    CmdAlleyType_MONJHMOILDM = 4736;
    CmdAlleyType_ENAKMNLCNGN = 4734;
    CmdAlleyType_OOLAGMBOCDN = 4793;
}

message DPFGBJFOFCE {
    uint32 FNCLCJCBPLA = 10;
}

message GAAMMAACICO {
    repeated IODAFIBPAGM MDNBOBFGKFN = 11;
    uint32 retcode = 14;
}

message GDGEIAHNDAD {
    repeated uint32 IFOKHMFNNNF = 3;
    repeated JEEHGNIBIFE OELPOFLBMIE = 5;
    repeated BOLCGIOGIBP ALOOPKCJFEA = 8;
    repeated IODAFIBPAGM CFNKOBKJKNK = 9;
}

message GHMINCEANHG {
    uint32 LMKJLEOPKKL = 1;
    uint32 JAKMMNIEBGJ = 4;
}

message GIFADCJKKFE {
    uint32 event_id = 1;
}

message GetAlleyInfoScRsp {
    KPBAIEMEFFH HAMAOOBGMLO = 1;
    uint32 level = 2;
    uint32 cur_fund = 3;
    PICDJHEPJLC EEAACLBJODA = 4;
    repeated uint32 KENFKICLMGJ = 5;
    repeated CEKIFBMPEFH PMIFFBHOOOO = 6;
    repeated uint32 AMHAEPILIKF = 8;
    GDGEIAHNDAD NFJKAILEFAD = 9;
    uint32 retcode = 12;
    repeated uint32 LAANLLFBLDP = 14;
}

message GetSaveLogisticsMapCsReq {
}

message GetSaveLogisticsMapScRsp {
    uint32 retcode = 11;
    repeated IODAFIBPAGM CFNKOBKJKNK = 13;
}

message IODAFIBPAGM {
    uint32 cost_time = 6;
    uint32 map_id = 13;
    repeated JOMEGNGJKJK JNGNGMJCAAI = 14;
}

message JEEHGNIBIFE {
    uint32 APNAFLBGENA = 5;
    uint32 map_id = 10;
}

message JOMEGNGJKJK {
    repeated uint32 GADMAOCHBKN = 2;
    repeated uint32 BPCADEMEGNP = 3;
    repeated uint32 OGDKJPDFFAI = 4;
    uint32 shop_id = 5;
    uint32 EBNNNMFGHBJ = 10;
    uint32 CJHLDCAGKND = 11;
    uint32 ANHEOHPNKKC = 14;
}

message KPBAIEMEFFH {
    uint32 OCNLDDNIHOH = 1;
    repeated uint32 EPEELMJDJKP = 5;
    bool FPDGKFHFIEE = 7;
    uint32 EBOMMHDNBJL = 11;
    uint32 BCOAIDIFBBG = 12;
    repeated uint32 DNLGMDCMFGF = 13;
}

message LogisticsGameScRsp {
    uint32 retcode = 5;
    bool CNCJKGEDEII = 6;
    repeated BOLCGIOGIBP ALOOPKCJFEA = 7;
    uint32 event_id = 11;
}

message LogisticsInfoScNotify {
    GDGEIAHNDAD NFJKAILEFAD = 3;
}

message LogisticsScoreRewardSyncInfoScNotify {
    repeated BOLCGIOGIBP ALOOPKCJFEA = 5;
}

message MGMDNBOLBMO {
    uint32 MONFBLGFKGB = 2;
}

message NGOKHFLMLNJ {
    uint32 retcode = 12;
}

message PICDJHEPJLC {
    uint32 LEGCBILEEHK = 3;
    map<uint32, uint32> PCDFIOCMJFE = 13;
}

message PPJKEKEPFMF {
    uint32 retcode = 2;
    uint32 event_id = 4;
}

message PrestigeLevelUpScRsp {
    uint32 retcode = 1;
    uint32 level = 14;
}

message TakePrestigeRewardScRsp {
    uint32 level = 6;
    uint32 retcode = 7;
    ItemList reward = 15;
}
