syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdAdventureType {
    CmdAdventureType_NLCDGIPGFDJ = 0;
    CmdAdventureType_CENHFOIEDKK = 1388;
    CmdAdventureType_GetFarmStageGachaInfoCsReq = 1393;
    CmdAdventureType_GetFarmStageGachaInfoScRsp = 1358;
    CmdAdventureType_FarmElementSweepCsReq = 1371;
    CmdAdventureType_StartQuickCocoonStageRsp = 1381;
    CmdAdventureType_CocoonSweepScRsp = 1313;
    CmdAdventureType_StartQuickFarmElementRsp = 1347;
    CmdAdventureType_FarmElementSweepScRsp = 1340;
    CmdAdventureType_CocoonSweepCsReq = 1326;
    CmdAdventureType_BKFOKJHEHOM = 1386;
}

message CocoonSweepCsReq {
    uint32 world_level = 4;
    uint32 cocoon_id = 9;
}

message CocoonSweepScRsp {
    ItemList multiple_drop_data = 2;
    ItemList drop_data = 10;
    uint32 cocoon_id = 13;
    uint32 retcode = 14;
    uint32 NCEFJFOHGBI = 15;
}

message FarmElementSweepCsReq {
    uint32 PAOFHFLFFHD = 9;
    uint32 world_level = 11;
}

message FarmElementSweepScRsp {
    uint32 retcode = 2;
    ItemList multiple_drop_data = 3;
    uint32 PAOFHFLFFHD = 14;
}

message FarmStageGachaInfo {
    int64 end_time = 8;
    uint32 gacha_id = 13;
    int64 begin_time = 15;
}

message GetFarmStageGachaInfoCsReq {
    repeated uint32 farm_stage_gacha_id_list = 10;
}

message GetFarmStageGachaInfoScRsp {
    uint32 retcode = 5;
    repeated FarmStageGachaInfo farm_stage_gacha_info_list = 15;
}
