syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BOMPFHOMMBH {
    uint32 target = 2;
    uint32 num = 7;
    uint32 item_id = 15;
}

enum CmdActivityRewardStatType {
    CmdActivityRewardStatType_HBPEDDCOJDB = 0;
    CmdActivityRewardStatType_GetAllActivityRewardCountDataCsReq = 9113;
    CmdActivityRewardStatType_GetActivityRewardCountDataScRsp = 9116;
    CmdActivityRewardStatType_GetActivityRewardCountDataCsReq = 9114;
    CmdActivityRewardStatType_GetActivityHotDataCsReq = 9120;
    CmdActivityRewardStatType_GetAllActivityRewardCountDataScRsp = 9115;
    CmdActivityRewardStatType_GetActivityHotDataScRsp = 9111;
}

message EFGIHHJGCFA {
    uint32 panel_id = 2;
    repeated BOMPFHOMMBH PGMDGPEKDGB = 9;
}

message GetActivityHotDataCsReq {
}

message GetActivityHotDataScRsp {
    repeated EFGIHHJGCFA content_package_list = 2;
    uint32 retcode = 11;
}

message GetActivityRewardCountDataCsReq {
    repeated uint32 DDMEHPDHPLM = 1;
}

message GetActivityRewardCountDataScRsp {
    repeated EFGIHHJGCFA content_package_list = 3;
    uint32 retcode = 9;
}

message GetAllActivityRewardCountDataCsReq {
}

message GetAllActivityRewardCountDataScRsp {
    repeated EFGIHHJGCFA content_package_list = 9;
    uint32 retcode = 10;
}
