syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ActiveActivityData {
    uint32 id = 3;
    uint32 FODLNKPNION = 5;
    uint32 DBIFEEDMAOF = 8;
    uint32 panel_id = 9;
    repeated uint32 taken_star_rewards = 12;
    uint32 CDMIKICANEP = 15;
}

message ActiveActivityDataChangeScNotify {
    ActiveActivityData ANFFLNDCGLG = 14;
}

enum CmdActiveType {
    CmdActiveType_NLCDGIPGFDJ = 0;
    CmdActiveType_GetActiveActivityDataScRsp = 9558;
    CmdActiveType_ActivityActiveActivityDataCsReq = 9568;
    CmdActiveType_TakeActiveActivityRewardScRsp = 9562;
    CmdActiveType_ActivityActiveTakeRewardCsReq = 9553;
    CmdActiveType_ActiveActivityDataChangeScNotify = 9552;
}

message GetActiveActivityDataScRsp {
    repeated ActiveActivityData HCLGPDFBDNP = 6;
    uint32 retcode = 14;
}

message TakeActiveActivityRewardScRsp {
    uint32 retcode = 2;
    ActiveActivityData ANFFLNDCGLG = 9;
    ItemList reward = 14;
}
