syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CFGGOBEDJOK {
    uint32 JFAADMONJNF = 14;
    repeated CFMDKNCDDAL FLINDJJJFLB = 15;
}

enum CFMDKNCDDAL {
    CFMDKNCDDAL_NADPFMGBHDJ = 0;
    CFMDKNCDDAL_GGGLNCBOICD = 1;
}

enum CmdAvatarType {
    CmdAvatarType_NLCDGIPGFDJ = 0;
    CmdAvatarType_GetPreAvatarGrowthInfoScRsp = 363;
    CmdAvatarType_EGMEJPCBAPA = 313;
    CmdAvatarType_AOPAPAOGAEH = 347;
    CmdAvatarType_GetPreAvatarActivityListScRsp = 375;
    CmdAvatarType_EHEFLCGHFKI = 312;
    CmdAvatarType_PMOEBOIPGDH = 394;
    CmdAvatarType_CFBPNHBMCEO = 315;
    CmdAvatarType_HBDCBKODCHA = 349;
    CmdAvatarType_KIOLGLCCNAA = 384;
    CmdAvatarType_GetAvatarDataCsReq = 325;
    CmdAvatarType_MHHIHIHDEEP = 320;
    CmdAvatarType_KBDMBGGBGPG = 378;
    CmdAvatarType_GetPreAvatarGrowthInfoCsReq = 329;
    CmdAvatarType_OCFJIJANIGJ = 338;
    CmdAvatarType_GPKCBBPOFON = 344;
    CmdAvatarType_ONCCDOGNGGM = 386;
    CmdAvatarType_MJJHIOPHGJP = 353;
    CmdAvatarType_FNBMEOPOFIC = 310;
    CmdAvatarType_NEALCJHELAD = 339;
    CmdAvatarType_ICKMBJNMFAH = 358;
    CmdAvatarType_BKBHLOFEHOC = 342;
    CmdAvatarType_DOAFJPKMCEK = 373;
    CmdAvatarType_GHAONBDDELG = 372;
    CmdAvatarType_CKCCDCNLDOI = 365;
    CmdAvatarType_AFODJNHAKCJ = 393;
    CmdAvatarType_NBNJIHOHDDE = 336;
    CmdAvatarType_KELLLHMHFHL = 337;
    CmdAvatarType_DMGCCILGDCP = 330;
    CmdAvatarType_BBDLPCFBNMF = 343;
    CmdAvatarType_ODOEAMMDEPG = 371;
    CmdAvatarType_NPEJIBMLFMJ = 389;
    CmdAvatarType_FIGBLNAAMHE = 381;
    CmdAvatarType_JAAHMMDDCFH = 326;
    CmdAvatarType_DressRelicAvatarScRsp = 311;
    CmdAvatarType_FGKDLCDIOGL = 341;
    CmdAvatarType_BFIBBNOOEJD = 333;
    CmdAvatarType_EGKKKHOEKAC = 340;
    CmdAvatarType_MILFFHPMLMN = 351;
    CmdAvatarType_LBAECAAIMCF = 318;
    CmdAvatarType_CAOIEGEDBLL = 388;
    CmdAvatarType_ADGPJHGNCKD = 382;
    CmdAvatarType_FBHFDPACJBF = 305;
    CmdAvatarType_GetPreAvataActivityListCsReq = 335;
    CmdAvatarType_FHIBLOPGIOO = 321;
    CmdAvatarType_CPCFHPMOHDD = 352;
    CmdAvatarType_IMPBJAIAHFK = 304;
    CmdAvatarType_OHGIGFIELHJ = 345;
    CmdAvatarType_DPAAIBGLDOB = 314;
    CmdAvatarType_EGOBEKBKNJD = 380;
    CmdAvatarType_OAEFKHMADDF = 369;
    CmdAvatarType_INOAACIMADH = 348;
}

message DressRelicAvatarScRsp {
    uint32 avatar_id = 9;
    uint32 retcode = 13;
}

enum GCALLOJPPIJ {
    GCALLOJPPIJ_NLCDGIPGFDJ = 0;
    GCALLOJPPIJ_BDEFGIPPKNM = 1;
    GCALLOJPPIJ_BPBFOIJKCJA = 2;
}

message GetAvatarDataCsReq {
    bool is_get_all = 3;
    repeated uint32 NOEPBNMJFGL = 12;
}

message GetPreAvatarActivityListScRsp {
    repeated uint32 DDMEHPDHPLM = 3;
    uint32 retcode = 11;
}

message GetPreAvatarGrowthInfoCsReq {
}

message GetPreAvatarGrowthInfoScRsp {
    repeated PreAvatarGrowthMaterialData JLMMCNIMPOA = 6;
    uint32 retcode = 13;
}

message LENDBHPIOJK {
    uint32 avatar_id = 14;
}

message PMEMIDKDAFG {
    repeated PileItem return_item_list = 13;
    uint32 retcode = 14;
}

message PreAvatarGrowthMaterialData {
    uint32 FDIJAFBCILL = 1;
    uint32 JHLPBJCAIIF = 2;
    uint32 PELFCMAHJGA = 3;
    uint32 JOBMEJMFELF = 4;
    uint32 IICANCHNIBB = 5;
    uint32 LNHKCMAPMLM = 6;
    uint32 JPGOACKIFFC = 7;
    uint32 DKEBMGFMCBH = 8;
    uint32 BJFJHEJGFPM = 9;
    uint32 PGJKALFDFMA = 10;
    uint32 DLGCGJCKLCB = 11;
    uint32 CAHBPNLNKCC = 12;
    uint32 OIFPBOCOALL = 13;
    uint32 IEGOLHHOANB = 14;
    uint32 BFEPBBLIOGP = 15;
    uint32 PPDAGPPKEJD = 435;
    uint32 type = 499;
    string LACBKOCCFHL = 617;
    string avatar_icon = 1233;
    string NDJGLMCPFHK = 1281;
    string NOCPIJJBKCB = 1559;
    uint32 panel_id = 1620;
}
