syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ABMNFJJDDOE {
    uint32 ILBJLIENCLB = 1;
    repeated BJNCNELEOMO MPMNLICFHMC = 2;
}

message AiPamAskSettlementScNotify {
    MDGIOENHBEJ EIADGIMDNMO = 2;
}

message AiPamMotionScNotify {
    repeated string BLCCBDPODFM = 5;
}

message AiPamResponseFeedbackCommentCsReq {
    string IMNOJNCGGNI = 9;
    uint32 OLLBLNAGMPC = 12;
}

message AiPamResponseFeedbackCommentScRsp {
    uint32 retcode = 5;
}

message AiPamResponseFeedbackScRsp {
    bool NMMJBGFDNAI = 4;
    uint32 retcode = 7;
    FKNKNLGMACL role = 8;
    bool IAJAOMAKAHA = 12;
}

message AiPamSendMsgScRsp {
    FKNKNLGMACL role = 3;
    uint32 retcode = 9;
}

message BALHBDBHHON {
    GOECDMPJMCM OAMKPPGDDIM = 1;
}

message BJNCNELEOMO {
    uint32 item_id = 1;
    uint32 item_count = 2;
}

message BKHLGPCDLGL {
    uint32 retcode = 3;
}

enum CmdAiPamType {
    CmdAiPamType_JCDCNPPCNEO = 0;
    CmdAiPamType_AiPamAskSettlementScNotify = 9540;
    CmdAiPamType_AiPamResponseFeedbackCommentScRsp = 9533;
    CmdAiPamType_OIOAFEBBBEO = 9520;
    CmdAiPamType_AiPamResponseFeedbackCommentCsReq = 9529;
    CmdAiPamType_GGCFEOOGKPE = 9543;
    CmdAiPamType_AiPamMotionScNotify = 9515;
    CmdAiPamType_EFAJNIOONGI = 9508;
    CmdAiPamType_EDODALOPJCN = 9509;
    CmdAiPamType_GetAiPamNextQuestionScRsp = 9503;
    CmdAiPamType_TriggerAiPamSpeakScRsp = 9502;
    CmdAiPamType_GetAiPamChatHistoryCsReq = 9544;
    CmdAiPamType_JPCOGBHEADP = 9548;
    CmdAiPamType_PFFAMBOFBBJ = 9513;
    CmdAiPamType_GetAiPamChatInfoScRsp = 9524;
    CmdAiPamType_GetAiPamChatHistoryScRsp = 9519;
    CmdAiPamType_UpdateAiPamSettingsCsReq = 9514;
    CmdAiPamType_KGFDHFDLCFK = 9506;
    CmdAiPamType_UpdateAiPamSettingsScRsp = 9535;
    CmdAiPamType_AiPamResponseFeedbackScRsp = 9517;
    CmdAiPamType_RecvAiPamChatEventScNotify = 9537;
    CmdAiPamType_OIJHPHDNJFD = 9518;
    CmdAiPamType_AiPamSendMsgScRsp = 9523;
    CmdAiPamType_GetAiPamChatInfoCsReq = 9521;
}

message DEHDGGEDJHI {
    ChatMessageData stop_desc = 1;
}

message DNPDLODGAHA {
    uint32 avatar_id = 1;
    HJNPOBAMKKF FLFNBPLNNBL = 2;
    HJNPOBAMKKF LLMDKAHFIIJ = 3;
}

message DOPJFJCLIAH {
    bool LJOEMLOJDDP = 1;
    bool JLNEBLAKKOB = 2;
}

message DPKPGPPHHBM {
    uint32 avatar_id = 1;
    repeated PLHPNBIMIOK MDLGEIGFFEG = 2;
}

message EIICHLNCAKK {
    uint32 avatar_id = 1;
    repeated ABMNFJJDDOE CNIMHMAPDII = 2;
    uint32 HPJAAOPDIOL = 3;
    uint32 JFCLHPFCMHP = 4;
}

message FAIFDBLLGKK {
    KDNCOBMFFEB event_type = 1;
    string ACFENKABBKK = 2;
    uint32 JKIHICLOPKM = 3;
    FKNKNLGMACL role = 4;
    oneof FCIDKEAOIBG {
        DEHDGGEDJHI stop_desc = 11;
        DOPJFJCLIAH LMJCPMFPHLK = 12;
        BALHBDBHHON FHDMHKOMEFO = 13;
        IAGGIFBOFDF FIFCCCJOLNE = 14;
    }
}

enum FKNKNLGMACL {
    FKNKNLGMACL_NLCDGIPGFDJ = 0;
    FKNKNLGMACL_LMBIMAOBGPO = 1;
    FKNKNLGMACL_NPDOGNAPCEE = 2;
}

enum GOECDMPJMCM {
    GOECDMPJMCM_NLCDGIPGFDJ = 0;
    GOECDMPJMCM_IKKJHNHKFOG = 1;
    GOECDMPJMCM_FFBIEEHPKND = 2;
    GOECDMPJMCM_JFNMPEJEIOH = 3;
}

message GetAiPamChatHistoryCsReq {
    uint32 target_side = 11;
}

message GetAiPamChatHistoryScRsp {
    uint32 retcode = 2;
    uint32 target_side = 10;
    repeated ChatMessageData JPCMGNGNONJ = 14;
}

message GetAiPamChatInfoCsReq {
}

message GetAiPamChatInfoScRsp {
    repeated FAIFDBLLGKK BJLHDBPPILI = 2;
    bool AGANFJKBFMA = 5;
    uint32 retcode = 9;
    bool OKCIPPLKGCD = 10;
    bool LOCNGFLCENG = 11;
    string ACFENKABBKK = 12;
    uint32 JKIHICLOPKM = 14;
}

message GetAiPamNextQuestionScRsp {
    uint32 retcode = 4;
    repeated NEKAOLPJKEE KDOHKGKBFCH = 9;
    FKNKNLGMACL role = 12;
}

message HGGMNLNJPHG {
    uint32 retcode = 1;
}

message IAGGIFBOFDF {
}

message IJJKHFPLLIF {
    uint32 avatar_id = 1;
    repeated LJEMPEHADKJ HGAIDOLJKDL = 2;
    repeated LJEMPEHADKJ FLOKEJHHPPO = 3;
}

message IOFKKOEJFHI {
    PJCMNENIEHH game_mode = 1;
    repeated JOLHIMGJGBO lineup_list = 2;
}

message JFCPFBLKJAB {
    oneof PONFIKAJHFD {
        IJJKHFPLLIF lineup = 10;
        DNPDLODGAHA LCMADDIMION = 11;
        DPKPGPPHHBM PAGPNOKLNOM = 12;
        EIICHLNCAKK BEGAIBBJHHD = 13;
        IOFKKOEJFHI HCAAHIGINOM = 14;
    }
}

enum KDNCOBMFFEB {
    KDNCOBMFFEB_NLCDGIPGFDJ = 0;
    KDNCOBMFFEB_BDOEMDGHHEP = 1;
    KDNCOBMFFEB_stop_desc = 2;
    KDNCOBMFFEB_LMJCPMFPHLK = 3;
    KDNCOBMFFEB_FHDMHKOMEFO = 4;
    KDNCOBMFFEB_FCKIHKAIIIJ = 5;
}

message KKNGAGGAJKC {
    string EDMBJCBKBIM = 1;
    string OIBPLFNJOEM = 2;
    string DMHFFKNLILH = 3;
}

message LHNMDFOPMKN {
    string BLDMFDKDJDM = 1;
    JFCPFBLKJAB return_data = 2;
}

message LJEMPEHADKJ {
    repeated uint32 avatar_id_list = 1;
}

message MDGIOENHBEJ {
    string title = 1;
    string OAPACMJOIKC = 2;
    uint32 ENHLKLFLCKG = 3;
    KKNGAGGAJKC tag = 4;
}

message NEKAOLPJKEE {
    string POLADDGLAEH = 1;
}

message PLHPNBIMIOK {
    uint32 KAJCFPKEGBP = 1;
    uint32 JHFFAALHEAI = 2;
}

message RecvAiPamChatEventScNotify {
    FAIFDBLLGKK OOOACLEFDGM = 14;
}

message TriggerAiPamSpeakScRsp {
    uint32 JMPPMNAONHM = 2;
    uint32 retcode = 12;
    FKNKNLGMACL role = 13;
}

message UpdateAiPamSettingsCsReq {
    bool LOCNGFLCENG = 6;
}

message UpdateAiPamSettingsScRsp {
    uint32 retcode = 12;
    bool LOCNGFLCENG = 13;
}
