syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ActivityScheduleData {
    int64 begin_time = 3;
    uint32 panel_id = 8;
    int64 end_time = 12;
    uint32 activity_id = 13;
}

enum CmdActivityType {
    CmdActivityType_NLCDGIPGFDJ = 0;
    CmdActivityType_PLIDCPGKMNA = 2698;
    CmdActivityType_AnniversaryAvatarDeliverTakeRewardScRsp = 2683;
    CmdActivityType_CDELCNPAHDK = 2619;
    CmdActivityType_LeaveTrialActivityScRsp = 2655;
    CmdActivityType_SubmitMaterialSubmitActivityMaterialScRsp = 2645;
    CmdActivityType_AnniversaryAvatarDeliverTakeRewardCsReq = 2623;
    CmdActivityType_TakeLoginActivityRewardScRsp = 2658;
    CmdActivityType_LeaveTrialActivityCsReq = 2666;
    CmdActivityType_GetLoginActivityScRsp = 2678;
    CmdActivityType_DFILCMEDDCN = 2693;
    CmdActivityType_FGHJOMBPEKM = 2651;
    CmdActivityType_AnniversaryAvatarDeliverChooseAvatarScRsp = 2627;
    CmdActivityType_MaterialSubmissionModuleInitCsReq = 2611;
    CmdActivityType_OOIJABCIDNG = 2648;
    CmdActivityType_GetMaterialSubmitActivityDataScRsp = 2636;
    CmdActivityType_AnniversaryAvatarDeliverGetDataCsReq = 2606;
    CmdActivityType_TrialActivityNotify = 2616;
    CmdActivityType_AnniversaryAvatarDeliverChooseAvatarCsReq = 2657;
    CmdActivityType_GetLoginActivityCsReq = 2625;
    CmdActivityType_TakeMaterialSubmitActivityRewardScRsp = 2665;
    CmdActivityType_StartTrialActivityScRsp = 2662;
    CmdActivityType_GetActivityScheduleConfigCsReq = 2688;
    CmdActivityType_EnterTrialActivityStageScRsp = 2646;
    CmdActivityType_TrialActivityDataChangeScNotify = 2637;
    CmdActivityType_TakeTrialActivityRewardScRsp = 2628;
    CmdActivityType_GetTrialActivityDataScRsp = 2694;
    CmdActivityType_LEAEIODECFC = 2669;
    CmdActivityType_GetTrialActivityDataCsReq = 2682;
    CmdActivityType_AnniversaryAvatarDeliverGetDataScRsp = 2674;
    CmdActivityType_GetActivityScheduleConfigScRsp = 2681;
}

message EnterTrialActivityStageScRsp {
    SceneBattleInfo battle_info = 2;
    uint32 retcode = 6;
}

message GetActivityScheduleConfigCsReq {
}

message GetActivityScheduleConfigScRsp {
    repeated ActivityScheduleData schedule_data = 7;
    uint32 retcode = 8;
}

message GetLoginActivityCsReq {
}

message GetLoginActivityScRsp {
    repeated LoginActivityData login_activity_list = 11;
    uint32 retcode = 15;
}

message GetMaterialSubmitActivityDataScRsp {
    uint32 retcode = 1;
    repeated KPMAKCHCDMH JJNFLKKAOFI = 9;
}

message GetTrialActivityDataCsReq {
}

message GetTrialActivityDataScRsp {
    uint32 activity_stage_id = 1;
    repeated TrialActivityInfo trial_activity_info_list = 7;
    repeated PAALDKHKOLE OBOPMFBGBAE = 10;
    uint32 retcode = 15;
}

message KPMAKCHCDMH {
    bool BAONIPOKCPL = 5;
    uint32 panel_id = 6;
    uint32 LNOCOOCMNCI = 7;
    bool is_taken_reward = 10;
}

message LeaveTrialActivityCsReq {
    uint32 stage_id = 7;
}

message LeaveTrialActivityScRsp {
    uint32 stage_id = 7;
    uint32 retcode = 10;
}

message LoginActivityData {
    uint32 login_days = 3;
    uint32 panel_id = 7;
    repeated uint32 MOIAHCMHNEO = 13;
    uint32 id = 15;
}

message PAALDKHKOLE {
    uint32 enhanced_id = 4;
    uint32 avatar_id = 14;
}

message StartTrialActivityScRsp {
    uint32 stage_id = 9;
    uint32 retcode = 11;
}

message SubmitMaterialSubmitActivityMaterialScRsp {
    uint32 retcode = 2;
    KPMAKCHCDMH MEAEIKFLBPJ = 14;
}

message TakeLoginActivityRewardScRsp {
    ItemList reward = 1;
    uint32 panel_id = 6;
    uint32 retcode = 9;
    uint32 take_days = 12;
    uint32 id = 14;
}

message TakeMaterialSubmitActivityRewardScRsp {
    uint32 LNOCOOCMNCI = 1;
    ItemList reward = 7;
    uint32 retcode = 8;
}

message TakeTrialActivityRewardScRsp {
    uint32 retcode = 4;
    uint32 stage_id = 12;
    ItemList reward = 13;
}

message TrialActivityDataChangeScNotify {
    TrialActivityInfo trial_activity_info = 1;
    repeated PAALDKHKOLE OBOPMFBGBAE = 9;
}

message TrialActivityInfo {
    bool taken_reward = 1;
    uint32 stage_id = 12;
}
