syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdBattleCollegeType {
    CmdBattleCollegeType_NLCDGIPGFDJ = 0;
    CmdBattleCollegeType_BattleCollegeModuleInitCsReq = 5725;
    CmdBattleCollegeType_StartBattleCollegeScRsp = 5788;
    CmdBattleCollegeType_DLAEKJKFPJO = 5758;
    CmdBattleCollegeType_SyncBattleCollegeDataChangeScNotify = 5793;
    CmdBattleCollegeType_GetBattleCollegeDataScRsp = 5778;
}

message GetBattleCollegeDataScRsp {
    uint32 retcode = 6;
    uint32 MNMJCNOLIII = 9;
    repeated uint32 finished_college_id_list = 13;
}

message StartBattleCollegeScRsp {
    SceneBattleInfo battle_info = 3;
    uint32 retcode = 10;
    uint32 id = 11;
}

message SyncBattleCollegeDataChangeScNotify {
    repeated uint32 finished_college_id_list = 2;
    uint32 MNMJCNOLIII = 3;
    ItemList reward = 12;
}
