syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BattleReplayScNotify {
    bytes NOJCNDGGLBC = 1;
    uint32 stage_id = 3;
    uint32 battle_id = 9;
}

enum CmdBattleType {
    CmdBattleType_NLCDGIPGFDJ = 0;
    CmdBattleType_KGEMPCLBNPH = 193;
    CmdBattleType_LKMHOLIBOEJ = 138;
    CmdBattleType_BattleReplayScNotify = 139;
    CmdBattleType_QuitBattleScNotify = 126;
    CmdBattleType_CJGIDPPDCJB = 125;
    CmdBattleType_JFBOMFNODNL = 186;
    CmdBattleType_PVEBattleResultScRsp = 178;
    CmdBattleType_GetCurBattleInfoCsReq = 188;
    CmdBattleType_NPMINAPIGNJ = 158;
    CmdBattleType_GetCurBattleInfoScRsp = 181;
    CmdBattleType_OFJPHHNKJMG = 147;
}

message GetCurBattleInfoCsReq {
}

message GetCurBattleInfoScRsp {
    AetherDivideBattleInfo HIDIEJALFIE = 2;
    uint32 KDJGDHKJAGE = 7;
    BattleEndStatus last_end_status = 8;
    uint32 retcode = 10;
    SceneBattleInfo battle_info = 12;
}

message PVEBattleResultScRsp {
    uint32 retcode = 1;
    ItemList drop_data = 2;
    string DIMHPKFPPKA = 3;
    bool check_identical = 4;
    ItemList item_list_unk2 = 5;
    ItemList multiple_drop_data = 6;
    uint32 EAHGEKNLHPN = 7;
    uint32 event_id = 8;
    string DPHOLBABAOL = 9;
    uint32 AKDGBBDFDHA = 10;
    uint32 battle_id = 11;
    uint32 LEMGICCOKBK = 12;
    uint32 stage_id = 13;
    repeated BattleAvatar battle_avatar_list = 14;
    BattleEndStatus end_status = 15;
    bool OPDKJBHLOJM = 1253;
    ItemList item_list_unk1 = 1379;
    LMDPKOELKFL ABEMLCJBIEF = 1658;
}

message QuitBattleScNotify {
}
