syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BattlePassInfoNotify {
    uint64 OKPOHIHPOKI = 1;
    uint32 level = 2;
    uint32 POJDILFNJAH = 4;
    uint64 PDODOAOHMAC = 5;
    uint64 CHJKOFANIKA = 6;
    uint64 DAFMMPKFOEA = 7;
    uint64 NJDCMGOJOLE = 8;
    uint32 AECHNDNNMLF = 9;
    uint32 exp = 11;
    uint64 ICPCCGPEJMP = 12;
    uint64 AIMGGFNLIEK = 13;
    uint64 CBLNJDCICBC = 14;
    BpTierType DELEGHOCLMO = 15;
}

enum BpRewardType {
    FDKLOILAJHE_EIDKKGLPFGO = 0;
    FDKLOILAJHE_GBOMNKONCPL = 1;
    FDKLOILAJHE_CPGBMBBPKPG = 2;
    FDKLOILAJHE_ENKNEHACMFJ = 3;
    FDKLOILAJHE_CKPPJBAKGHL = 4;
}

enum BpTierType {
    FMGFKIKBHKN_NLCDGIPGFDJ = 0;
    FMGFKIKBHKN_LDCGNGDPGAM = 1;
    FMGFKIKBHKN_FENMGLMPMFF = 2;
    FMGFKIKBHKN_AJDEOPEJGEC = 3;
}

message BuyBpLevelCsReq {
    uint32 IGOOJKMPMDC = 12;
}

message BuyBpLevelScRsp {
    uint32 retcode = 4;
}

enum CmdBattlePassType {
    CmdBattlePassType_NLCDGIPGFDJ = 0;
    CmdBattlePassType_BuyBpLevelCsReq = 3081;
    CmdBattlePassType_TakeBpRewardScRsp = 3088;
    CmdBattlePassType_BattlePassTakeAllRewardScRsp = 3026;
    CmdBattlePassType_IHPLLMHHMAB = 3047;
    CmdBattlePassType_AGLKDJBDJIE = 3058;
    CmdBattlePassType_BattlePassInfoNotify = 3025;
    CmdBattlePassType_BuyBpLevelScRsp = 3086;
}

message TakeBpRewardScRsp {
    uint32 retcode = 2;
    ItemList reward = 10;
}
