syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BoxingClubChallengeUpdateScNotify {
    CIEEKOEECHB OCDLPDDMCLP = 2;
}

message BoxingClubRewardScNotify {
    ItemList reward = 1;
    uint32 challenge_id = 2;
    uint32 EAFICCLCLLA = 3;
    bool is_win = 4;
}

message CIEEKOEECHB {
    repeated uint32 avatar_list = 1;
    uint32 HODLKBMKMCF = 2;
    repeated FLLJIHLMKDI OOJOMKDMBBM = 5;
    bool MLOGJKEOCPP = 6;
    uint32 LFFBKJBJJDD = 7;
    uint32 stage_index = 8;
    repeated uint32 EJEFDFEFOMH = 9;
    uint32 challenge_id = 12;
    uint32 EAFICCLCLLA = 13;
    uint32 IFHHFBIJOFC = 15;
}

message ChooseBoxingClubResonanceCsReq {
    uint32 HODLKBMKMCF = 8;
    uint32 challenge_id = 13;
}

message ChooseBoxingClubResonanceScRsp {
    uint32 retcode = 2;
    CIEEKOEECHB OCDLPDDMCLP = 13;
}

message ChooseBoxingClubStageOptionalBuffScRsp {
    uint32 retcode = 4;
    CIEEKOEECHB OCDLPDDMCLP = 5;
}

enum CmdBoxingClubType {
    CmdBoxingClubType_NLCDGIPGFDJ = 0;
    CmdBoxingClubType_IIBDDINNJNE = 4233;
    CmdBoxingClubType_BoxingClubRewardScNotify = 4226;
    CmdBoxingClubType_GiveUpBoxingClubChallengeCsReq = 4286;
    CmdBoxingClubType_ChooseBoxingClubStageOptionalBuffScRsp = 4204;
    CmdBoxingClubType_ChooseBoxingClubResonanceScRsp = 4240;
    CmdBoxingClubType_ChooseBoxingClubResonanceCsReq = 4271;
    CmdBoxingClubType_ChooseBoxingClubResonanceOptionalBuffCsReq = 4239;
    CmdBoxingClubType_GiveUpBoxingClubChallengeScRsp = 4247;
    CmdBoxingClubType_StartBoxingClubBattleScRsp = 4281;
    CmdBoxingClubType_HLJDFNPEJGC = 4288;
    CmdBoxingClubType_SetBoxingClubResonanceScRsp = 4238;
    CmdBoxingClubType_BMGEGHLMKBO = 4293;
    CmdBoxingClubType_GetBoxingClubInfoScRsp = 4278;
    CmdBoxingClubType_BoxingClubChallengeUpdateScNotify = 4213;
    CmdBoxingClubType_GetChallengeDataCsReq = 4225;
    CmdBoxingClubType_MatchBoxingClubOpponentScRsp = 4258;
}

message FLLJIHLMKDI {
    AvatarType avatar_type = 7;
    uint32 avatar_id = 13;
}

message GetBoxingClubInfoScRsp {
    uint32 retcode = 12;
    repeated CIEEKOEECHB challenge_list = 14;
}

message GiveUpBoxingClubChallengeCsReq {
    uint32 challenge_id = 3;
    bool KEAAGAIAHLA = 5;
}

message GiveUpBoxingClubChallengeScRsp {
    uint32 retcode = 2;
    CIEEKOEECHB OCDLPDDMCLP = 14;
}

message MatchBoxingClubOpponentScRsp {
    uint32 retcode = 2;
    CIEEKOEECHB OCDLPDDMCLP = 10;
}

message SetBoxingClubResonanceScRsp {
    CIEEKOEECHB OCDLPDDMCLP = 2;
    uint32 retcode = 4;
}

message StartBoxingClubBattleScRsp {
    uint32 challenge_id = 3;
    SceneBattleInfo battle_info = 12;
    uint32 retcode = 14;
}
