syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BBDLCOJKGMI {
    GLLDHGHJLOA PHLAMKCLLKP = 15;
}

enum BDEJGKKACMA {
    BDEJGKKACMA_NLCDGIPGFDJ = 0;
    BDEJGKKACMA_hp = 1;
    BDEJGKKACMA_COJOIFPPCIJ = 2;
}

message CJHOCMLPMJD {
    repeated uint32 AJFJLCKPNAM = 8;
}

message ChimeraDuelChangeLineupScRsp {
    uint32 retcode = 2;
    repeated uint32 AJFJLCKPNAM = 5;
}

message ChimeraDuelEndGameScRsp {
    uint32 retcode = 7;
    EBPBMFBFEJA CECFDNCDBEI = 14;
}

message ChimeraDuelEndRoundBattleStageScRsp {
    uint32 retcode = 7;
    DIIKFKNEHHG NONPIMDDJNN = 12;
    oneof KKNBOACNCON {
        LCEDDGELBMJ CFDIKLBINHK = 1274;
        EBPBMFBFEJA CECFDNCDBEI = 1115;
    }
}

message ChimeraDuelEndRoundShopStageCsReq {
}

message ChimeraDuelEndRoundShopStageScRsp {
    uint32 retcode = 3;
    LCEDDGELBMJ CFDIKLBINHK = 4;
}

message ChimeraDuelFinishMasterChallengeCsReq {
    uint32 IPINHNFCIOE = 11;
}

message ChimeraDuelFinishMasterChallengeScRsp {
    uint32 IPINHNFCIOE = 3;
    uint32 retcode = 7;
}

message ChimeraDuelGetDataScRsp {
    uint32 retcode = 6;
    LCEDDGELBMJ CFDIKLBINHK = 11;
    PCBOLEAFMDN COFPFIDNONN = 15;
}

message ChimeraDuelGetFriendListCsReq {
}

message ChimeraDuelGetFriendListScRsp {
    repeated MPPHIOJNKGB friend_list = 5;
    uint32 retcode = 7;
}

message ChimeraDuelPlayerRankData {
    uint32 rank = 5;
    uint32 score_id = 12;
}

message ChimeraDuelSaveFriendPvpLineupCsReq {
    uint32 slot = 6;
}

message ChimeraDuelSaveFriendPvpLineupScRsp {
    uint32 retcode = 2;
    uint32 slot = 6;
    PNCNGIAMLCA lineup = 14;
}

message ChimeraDuelSelectGameCsReq {
    uint32 FGLEKNDHMKN = 1;
}

message ChimeraDuelSelectGameScRsp {
    uint32 FGLEKNDHMKN = 5;
    uint32 retcode = 7;
}

message ChimeraDuelSellChimeraScRsp {
    repeated uint32 AJFJLCKPNAM = 3;
    uint32 retcode = 5;
    uint32 NDJGKJMPPHJ = 13;
}

message ChimeraDuelSetFriendDefendLineupCsReq {
    uint32 slot = 6;
}

message ChimeraDuelSetFriendDefendLineupScRsp {
    uint32 slot = 3;
    uint32 retcode = 9;
}

message ChimeraDuelShopBuyChimeraCsReq {
    repeated uint32 FMMICIHEOCM = 6;
    uint32 KODOOHHPIKN = 8;
    uint32 GCKFOOIEHHA = 15;
}

message ChimeraDuelShopBuyChimeraScRsp {
    uint32 retcode = 5;
}

message ChimeraDuelShopBuyItemCsReq {
    uint32 AGBAIFPNKII = 11;
    uint32 JHINLPCKMPK = 14;
}

message ChimeraDuelShopBuyItemScRsp {
    uint32 retcode = 10;
}

message ChimeraDuelShopLockScRsp {
    bool is_locked = 1;
    uint32 retcode = 2;
    oneof KKNBOACNCON {
        uint32 NDJGKJMPPHJ = 4;
        uint32 AGBAIFPNKII = 3;
    }
}

message ChimeraDuelShopRefreshCsReq {
}

message ChimeraDuelShopRefreshScRsp {
    uint32 retcode = 11;
}

message ChimeraDuelStartGameCsReq {
    uint32 IPINHNFCIOE = 12;
}

message ChimeraDuelStartGameScRsp {
    uint32 retcode = 5;
    LCEDDGELBMJ CFDIKLBINHK = 8;
}

message ChimeraDuelSyncChangeScNotify {
    repeated LGEDKNLBCAN DGNGMJMPFGK = 15;
}

message ChimeraDuelUnlockMasterCsReq {
    uint32 IPINHNFCIOE = 1;
}

message ChimeraDuelUnlockMasterScRsp {
    uint32 retcode = 1;
    uint32 IPINHNFCIOE = 11;
}

enum CmdChimeraDuelType {
    CmdChimeraDuelType_NLCDGIPGFDJ = 0;
    CmdChimeraDuelType_ChimeraDuelShopBuyItemCsReq = 9212;
    CmdChimeraDuelType_ChimeraDuelStartGameScRsp = 9217;
    CmdChimeraDuelType_ChimeraDuelFinishMasterChallengeScRsp = 9222;
    CmdChimeraDuelType_ChimeraDuelShopLockItemCsReq = 9245;
    CmdChimeraDuelType_ChimeraDuelGetFriendListScRsp = 9215;
    CmdChimeraDuelType_ChimeraDuelSetFriendDefendLineupScRsp = 9246;
    CmdChimeraDuelType_ChimeraDuelSaveFriendPvpLineupScRsp = 9232;
    CmdChimeraDuelType_ChimeraDuelSellChimeraScRsp = 9255;
    CmdChimeraDuelType_ChimeraDuelEndRoundShopStageCsReq = 9220;
    CmdChimeraDuelType_ChimeraDuelEndGameScRsp = 9239;
    CmdChimeraDuelType_ChimeraDuelSetFriendDefendLineupCsReq = 9242;
    CmdChimeraDuelType_ChimeraDuelSyncChangeScNotify = 9228;
    CmdChimeraDuelType_ChimeraDuelShopRefreshScRsp = 9218;
    CmdChimeraDuelType_ChimeraDuelShopBuyChimeraCsReq = 9243;
    CmdChimeraDuelType_EKBHDFNBDEH = 9234;
    CmdChimeraDuelType_ChimeraDuelEndRoundShopStageScRsp = 9231;
    CmdChimeraDuelType_ChimeraDuelUnlockMasterScRsp = 9258;
    CmdChimeraDuelType_ChimeraDuelUnlockMasterCsReq = 9229;
    CmdChimeraDuelType_ChimeraDuelGetDataScRsp = 9233;
    CmdChimeraDuelType_BGGINGOKPDN = 9227;
    CmdChimeraDuelType_ChimeraDuelShopLockScRsp = 9225;
    CmdChimeraDuelType_ChimeraDuelGetFriendListCsReq = 9240;
    CmdChimeraDuelType_ChimeraDuelShopBuyItemScRsp = 9224;
    CmdChimeraDuelType_ChimeraDuelSaveFriendPvpLineupCsReq = 9252;
    CmdChimeraDuelType_ChimeraDuelSelectGameCsReq = 9249;
    CmdChimeraDuelType_TeamSellChimeraCsReq = 9236;
    CmdChimeraDuelType_ChimeraDuelEndRoundBattleStageScRsp = 9230;
    CmdChimeraDuelType_ChimeraDuelSelectGameScRsp = 9257;
    CmdChimeraDuelType_ChimeraDuelShopRefreshCsReq = 9223;
    CmdChimeraDuelType_ChimeraDuelShopBuyChimeraScRsp = 9216;
    CmdChimeraDuelType_FGJHLOALHJJ = 9253;
    CmdChimeraDuelType_ChimeraDuelStartGameCsReq = 9213;
    CmdChimeraDuelType_KBPJHMODAFK = 9219;
    CmdChimeraDuelType_ChimeraDuelFinishMasterChallengeCsReq = 9251;
    CmdChimeraDuelType_ChimeraDuelChangeLineupScRsp = 9250;
}

enum DIIKFKNEHHG {
    DIIKFKNEHHG_NLCDGIPGFDJ = 0;
    DIIKFKNEHHG_EHNIPLNEEDI = 1;
    DIIKFKNEHHG_FAODKNDLNPF = 2;
    DIIKFKNEHHG_EEOOMIBEMNH = 3;
}

message DMOJMNKOILL {
    bool is_locked = 6;
    uint32 item_id = 7;
    uint32 AGBAIFPNKII = 10;
    bool IFIGFODOPBB = 12;
}

message EBPBMFBFEJA {
    bool ENFKEAEGPBJ = 1;
    uint32 FGLEKNDHMKN = 5;
    LCEDDGELBMJ CFDIKLBINHK = 7;
    ChimeraDuelPlayerRankData AAIMONALOPD = 8;
}

message FJJHCDGNDPD {
    repeated uint32 JJOJFFAOEDI = 4;
    repeated uint32 ACCKECIHCGJ = 8;
}

message FLOPNJFNAOG {
    POACIACEJJN JOOEEKMDAEO = 6;
    bool NBHLDBBBPPA = 13;
}

message GIEPFAIPADI {
    repeated uint32 FMMICIHEOCM = 8;
}

message GLLDHGHJLOA {
    string nickname = 2;
    uint32 uid = 5;
    uint32 IPINHNFCIOE = 6;
    repeated NHDGNBKBNDB BCGOAIPKGIK = 7;
    repeated uint32 AJFJLCKPNAM = 8;
    uint32 hp = 10;
    uint32 KIMKENNLHEH = 11;
    uint32 head_icon = 12;
    uint32 rank = 13;
}

message HNAOOMKGFCB {
    PDHFFPOJNJG source_type = 1;
    uint32 LLMHAEAPGON = 7;
    uint32 BHCCDFFBAAM = 10;
}

message JJKOHCPBGAL {
    HNAOOMKGFCB source = 9;
    uint32 FLIEDGKFNOL = 11;
    GIEPFAIPADI LHEOBNDKGHD = 15;
    oneof BHNPKLCNDNG {
        BDEJGKKACMA LLCOEPJFGPE = 661;
        uint32 BNCCMEGJONF = 491;
        FJJHCDGNDPD IAECKEDODEF = 1931;
    }
}

message JJNHIKIGKJC {
    uint32 unique_id = 3;
    uint32 item_id = 6;
}

message KGHDDIBDABP {
    bool is_locked = 5;
    uint32 grid_fight_equipment_id = 9;
    uint32 IPAOBKONIFL = 13;
    uint32 NDJGKJMPPHJ = 14;
    uint32 FGECDDFBFOJ = 15;
}

message LCEDDGELBMJ {
    uint32 IPINHNFCIOE = 2;
    uint32 KIMKENNLHEH = 3;
    uint32 IDNHBBMLNJK = 6;
    uint32 NMPABPJHGPE = 7;
    uint32 JGPHDBDHKKO = 9;
    uint32 BAJHKGJPFED = 11;
    repeated NHDGNBKBNDB BCGOAIPKGIK = 13;
    uint32 hp = 14;
    repeated uint32 HGKDHJHKFBP = 15;
    oneof PAPIIIMEKDD {
        POACIACEJJN HKFFIGBBFAE = 982;
        BBDLCOJKGMI PJCKOBNPFCB = 1596;
    }
}

message LGEDKNLBCAN {
    oneof MMCGBGDJIPN {
        JJKOHCPBGAL ALPKKNKAFBG = 14;
        uint32 PBCGHKNGBFC = 13;
        NHDGNBKBNDB PFOBPLCGGGI = 12;
        uint32 KBPJKIEBBON = 10;
        FLOPNJFNAOG KJHMPBOIGGE = 7;
        CJHOCMLPMJD FICFIOENBEN = 11;
        uint32 GCKFOOIEHHA = 9;
        uint32 HFOKEKMCOBP = 2;
        uint32 CIFFLEBCFGK = 5;
        MAFDLBFIJMB BHPPAPONGOE = 8;
        uint32 NGBAKCIGBMN = 6;
    }
}

message MAFDLBFIJMB {
    PNCNGIAMLCA lineup = 4;
    uint32 slot = 10;
}

message MPPHIOJNKGB {
    PNCNGIAMLCA lineup = 5;
    uint32 uid = 6;
    uint32 score_id = 14;
}

message NHDGNBKBNDB {
    JJNHIKIGKJC equip = 1;
    int32 GIFJODBPLPJ = 4;
    uint32 unique_id = 5;
    uint32 FGECDDFBFOJ = 6;
    uint32 exp = 7;
    uint32 LLEOGLLHCLK = 10;
    int32 OEEIPJDNMOK = 12;
}

message PCBOLEAFMDN {
    repeated MAFDLBFIJMB GNJGPFDKLBH = 1;
    ChimeraDuelPlayerRankData AAIMONALOPD = 2;
    uint32 NGBAKCIGBMN = 3;
    repeated uint32 PGGOOINMOLF = 7;
    uint32 CIFFLEBCFGK = 8;
    repeated uint32 FOLMLBOLGEM = 9;
    repeated uint32 HAKLMIAENCF = 11;
    uint32 FGLEKNDHMKN = 12;
    uint32 DEFHFAGLMLC = 15;
}

enum PDHFFPOJNJG {
    PDHFFPOJNJG_NLCDGIPGFDJ = 0;
    PDHFFPOJNJG_GIKNCJMJLFE = 1;
    PDHFFPOJNJG_PAGPNOKLNOM = 2;
    PDHFFPOJNJG_LPIINKCPJPO = 3;
    PDHFFPOJNJG_DIMIFCJPHME = 4;
    PDHFFPOJNJG_AJGOEJHKOKE = 5;
}

message PNCNGIAMLCA {
    uint32 IPINHNFCIOE = 3;
    repeated uint32 AJFJLCKPNAM = 12;
    repeated NHDGNBKBNDB BCGOAIPKGIK = 15;
}

message POACIACEJJN {
    repeated KGHDDIBDABP DKCMMMPNEME = 1;
    repeated DMOJMNKOILL LCJFDCHINHL = 3;
}
