syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BCOHNDPHBGK {
    uint32 retcode = 3;
}

message CakeRaceCoinScoreChangeScNotify {
    uint32 score_id = 1;
    uint32 item_value = 9;
    uint32 JNBEGEOPGFJ = 14;
}

message CakeRaceFinishFieldRewardScNotify {
    ItemList reward = 2;
    uint32 LOPNADHJKBF = 8;
}

message CakeRaceGetDailyLikeCsReq {
}

message CakeRaceGetDailyLikeScRsp {
    repeated uint32 LPBBJFFNACA = 6;
    uint32 retcode = 7;
}

message CakeRaceGetDataCsReq {
}

message CakeRaceGetDataScRsp {
    repeated uint32 EAHKHGPPLEA = 2;
    uint32 score_id = 4;
    repeated uint32 LAJJHAAKGAF = 7;
    uint32 item_value = 11;
    uint32 JNBEGEOPGFJ = 13;
    uint32 retcode = 15;
}

message CakeRaceGetFriendRankingInfoListCsReq {
}

message CakeRaceGetFriendRankingInfoListScRsp {
    repeated uint32 LPBBJFFNACA = 3;
    repeated JBHLNAHOJOH MLPHLIHFGKG = 11;
    uint32 retcode = 15;
}

message CakeRaceGetHandbookCsReq {
}

message CakeRaceGetHandbookScRsp {
    uint32 retcode = 4;
    repeated GKCNOIGHOPM AOBBDDKFBMD = 15;
}

message CakeRaceLikeFriendRankingInfoCsReq {
    uint32 teleport_id = 5;
}

message CakeRaceLikeFriendRankingInfoScRsp {
    uint32 retcode = 2;
    ItemList reward_list = 9;
    uint32 teleport_id = 12;
    repeated uint32 LPBBJFFNACA = 13;
}

message CakeRaceLoanCsReq {
}

message CakeRaceLoanScRsp {
    uint32 retcode = 5;
    uint32 AKEABJGIKLI = 8;
    ItemList item_list = 11;
}

message CakeRaceStartPveCsReq {
    uint32 LOPNADHJKBF = 1;
}

message CakeRaceStartPveScRsp {
    uint32 retcode = 2;
    uint32 LOPNADHJKBF = 11;
}

message CakeRaceUpdatePveScRsp {
    uint32 retcode = 10;
}

enum CmdCakeRaceType {
    CmdCakeRaceType_NLCDGIPGFDJ = 0;
    CmdCakeRaceType_CakeRaceLoanScRsp = 9124;
    CmdCakeRaceType_CakeRaceGetHandbookCsReq = 9131;
    CmdCakeRaceType_CakeRaceUpdatePveScRsp = 9132;
    CmdCakeRaceType_CakeRaceGetDataCsReq = 9129;
    CmdCakeRaceType_CakeRaceGetHandbookScRsp = 9130;
    CmdCakeRaceType_CakeRaceLikeFriendRankingInfoScRsp = 9122;
    CmdCakeRaceType_CakeRaceStartPveScRsp = 9142;
    CmdCakeRaceType_CakeRaceGetDataScRsp = 9145;
    CmdCakeRaceType_CakeRaceGetFriendRankingInfoListScRsp = 9121;
    CmdCakeRaceType_NMJIDHAKDFK = 9135;
    CmdCakeRaceType_CakeRaceLikeFriendRankingInfoCsReq = 9150;
    CmdCakeRaceType_CakeRaceUseBattleItemPveCsReq = 9141;
    CmdCakeRaceType_CakeRaceLoanCsReq = 9138;
    CmdCakeRaceType_CakeRaceCoinScoreChangeScNotify = 9123;
    CmdCakeRaceType_CakeRaceFinishFieldRewardScNotify = 9147;
    CmdCakeRaceType_CakeRaceStartPveCsReq = 9125;
    CmdCakeRaceType_CakeRaceGetFriendRankingInfoListCsReq = 9128;
    CmdCakeRaceType_CakeRaceGetDailyLikeScRsp = 9139;
    CmdCakeRaceType_CakeRaceGetDailyLikeCsReq = 9137;
    CmdCakeRaceType_CakeRaceFinishPveCsReq = 9140;
}

message EMJCPFCMOMK {
    repeated uint32 CPIKEIGHMGB = 2;
}

message GKCNOIGHOPM {
    uint32 LHHJFMMCBAF = 3;
    uint32 MBNBCPEAALJ = 6;
    uint32 CBNKDHIHECO = 13;
}

message ICDBHMEPNDB {
    uint32 JLAHNBIMKPD = 3;
    uint32 LHHJFMMCBAF = 11;
}

message JBHLNAHOJOH {
    uint32 FOGJIBONACG = 7;
    uint32 uid = 10;
    uint32 JNBEGEOPGFJ = 14;
}

message PIBEHFDDAAJ {
    bool DHLLPOBKLIO = 10;
    uint32 score_id = 13;
}
