syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ABCHBKBKCDF {
    uint32 avatar_id = 1;
    uint32 skin_id = 6;
}

message ChallengePeak {
    uint32 peak_id = 2;
    repeated ChallengePeakBuild peak_build_list = 4;
    repeated uint32 peak_avatar_id_list = 5;
    uint32 cycles_used = 9;
    bool has_passed = 12;
    repeated uint32 finished_target_list = 15;
}

message ChallengePeakBoss {
    repeated uint32 finished_target_list = 4;
    uint32 BFBHCKEJDIG = 5;
    ChallengePeakBossClearance easy_mode = 8;
    ChallengePeakBossClearance hard_mode = 9;
    bool hard_mode_has_passed = 14;
}

message ChallengePeakBossClearance {
    uint32 best_cycle_count = 3;
    uint32 DJFGDMIDEHJ = 4;
    repeated ABCHBKBKCDF EBNNJAEPBGD = 6;
    repeated uint32 LAMPCACOCHP = 7;
    uint32 buff_id = 8;
    repeated uint32 peak_avatar_id_list = 9;
    bool has_passed = 11;
    uint32 NHOJDHPGBBO = 12;
}

message ChallengePeakBuild {
    repeated EquipRelic relic_list = 1;
    uint32 equipment_unique_id = 3;
    uint32 avatar_id = 7;
    uint32 skin_id = 9;
}

message ChallengePeakGroup {
    ChallengePeakBoss peak_boss = 1;
    uint32 peak_group_id = 2;
    uint32 obtained_stars = 3;
    bool disable_hard_mode = 5;
    JFBFFIAOPCC PAPDCCKPEPK = 8;
    WaitConfirmData wait_confirm_data = 9;
    repeated uint32 taken_star_rewards = 13;
    uint32 count_of_peaks = 14;
    repeated ChallengePeak peaks = 15;
}

message ChallengePeakGroupDataUpdateScNotify {
    ChallengePeakGroup challenge_peak_group = 1;
}

message ChallengePeakRewardGroup {
    uint32 reward_id = 10;
    ItemList reward = 14;
}

message ChallengePeakSettleScNotify {
    uint32 turn_left = 1;
    bool is_first_pass = 2;
    bool is_boss_target_better = 3;
    uint32 cycles_used = 6;
    bool is_unlock_easy_boss = 7;
    bool is_wait_confirm = 8;
    bool is_win = 9;
    repeated ChallengePeakRewardGroup peak_reward_group_list = 11;
    repeated uint32 finished_target_list = 12;
    uint32 peak_id = 13;
    bool hard_mode_has_passed = 15;
}

enum CmdChallengePeakType {
    CmdChallengePeakType_NLCDGIPGFDJ = 0;
    CmdChallengePeakType_PGAGCAMLDCB = 8910;
    CmdChallengePeakType_HIMPPADFCCO = 8943;
    CmdChallengePeakType_KAMEEPBPLJD = 8933;
    CmdChallengePeakType_ChallengePeakGroupDataUpdateScNotify = 8907;
    CmdChallengePeakType_GetChallengePeakDataCsReq = 8924;
    CmdChallengePeakType_ChallengePeakModuleInitCsReq = 8909;
    CmdChallengePeakType_GetChallengePeakDataScRsp = 8923;
    CmdChallengePeakType_AEGHKHLKDEF = 8948;
    CmdChallengePeakType_KALFCEDOGGO = 8935;
    CmdChallengePeakType_ReceiveResponseScRsp = 8944;
    CmdChallengePeakType_LCJOEDMEKDN = 8937;
    CmdChallengePeakType_TakeChallengePeakRewardScRsp = 8921;
    CmdChallengePeakType_ChallengePeakSettleScNotify = 8903;
    CmdChallengePeakType_LBAFAPCBFLD = 8919;
    CmdChallengePeakType_GDGEAGHJOJP = 8918;
    CmdChallengePeakType_ELLHHFBMILA = 8915;
    CmdChallengePeakType_OHDGEJLCAHA = 8906;
    CmdChallengePeakType_IGPMJGAHOPM = 8917;
    CmdChallengePeakType_GetCurChallengePeakScRsp = 8920;
    CmdChallengePeakType_SetChallengePeakBossHardModeScRsp = 8929;
}

message GetChallengePeakDataCsReq {
}

message GetChallengePeakDataScRsp {
    repeated ChallengePeakGroup challenge_peak_groups = 6;
    uint32 current_peak_group_id = 8;
    uint32 retcode = 12;
}

message GetCurChallengePeakScRsp {
    uint32 peak_id = 1;
    uint32 retcode = 2;
    bool has_passed = 5;
    uint32 boss_buff_id = 12;
}

message JFBFFIAOPCC {
    repeated MEKPDDBLCGK peaks = 2;
}

message MEKPDDBLCGK {
    uint32 cycles_used = 3;
    repeated uint32 finished_target_list = 6;
    repeated ABCHBKBKCDF peak_avatar_id_list = 11;
    uint32 peak_id = 14;
}

message SetChallengePeakBossHardModeScRsp {
    bool is_hard_mode = 2;
    uint32 retcode = 6;
    uint32 peak_group_id = 11;
}

message TakeChallengePeakRewardScRsp {
    uint32 retcode = 4;
    repeated ChallengePeakRewardGroup peak_reward_group_list = 8;
    uint32 peak_group_id = 11;
}

message WaitConfirmData {
    bool is_wait_confirm = 3;
    uint32 cycles_used = 7;
    repeated uint32 finished_target_list = 9;
    uint32 peak_id = 14;
}
