syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdChallengeTierceType {
    CmdChallengeTierceType_NLCDGIPGFDJ = 0;
    CmdChallengeTierceType_GKEEHHBEBCM = 8985;
    CmdChallengeTierceType_JDHLIGMPFLG = 8992;
    CmdChallengeTierceType_NMDDOIKKEKA = 8990;
    CmdChallengeTierceType_JKINFDKKKGG = 8974;
    CmdChallengeTierceType_CCDKLLGDLOM = 8991;
    CmdChallengeTierceType_LMFPFIKOJBD = 8980;
    CmdChallengeTierceType_GKCOKHMADPF = 8999;
    CmdChallengeTierceType_ENGOIEOPGMF = 8973;
    CmdChallengeTierceType_GAEELOILOCB = 8978;
    CmdChallengeTierceType_PMMCIBMKOLD = 8975;
    CmdChallengeTierceType_EIBCIGDELHA = 8971;
    CmdChallengeTierceType_BEFPNLIFBOE = 8979;
    CmdChallengeTierceType_ALLBIOLKCEK = 8988;
    CmdChallengeTierceType_BDHPJJHOOAC = 8981;
    CmdChallengeTierceType_DCANDNHNLCO = 8977;
    CmdChallengeTierceType_POJMHFPIFGM = 8995;
    CmdChallengeTierceType_GHHBEOGONIP = 8982;
}
