syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ChooseDeliveryGetDataCsReq {
}

message ChooseDeliveryGetDataScRsp {
    repeated uint32 PCOJLMKPAEL = 5;
    uint32 retcode = 10;
}

message ChooseDeliveryScRsp {
    uint32 IHFNFDKLFIC = 4;
    repeated ItemList DJOBNPIAEJP = 6;
    uint32 group_id = 10;
    uint32 retcode = 13;
}

enum CmdChooseDeliveryType {
    CmdChooseDeliveryType_NLCDGIPGFDJ = 0;
    CmdChooseDeliveryType_ChooseDeliveryGetDataScRsp = 9488;
    CmdChooseDeliveryType_ChooseDeliveryScRsp = 9492;
    CmdChooseDeliveryType_FFLBBFNFNNH = 9483;
    CmdChooseDeliveryType_ChooseDeliveryGetDataCsReq = 9498;
}
