syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BGAIEEIKOKK {
    uint32 total_score = 3;
    uint32 star_num = 11;
    bool has_passed = 13;
    uint32 level_id = 14;
}

message ChenLingFesBusinessDayEndScRsp {
    string FGGCAOAPGPA = 2;
    uint32 retcode = 4;
    uint32 FGKPIDLKALL = 6;
    uint32 business_day = 14;
    oneof FBLHECDEHEF {
        DMHADFNOIGP EHIHHFMGNHH = 1;
        MOJFFDOILBN GAAHAOGLNPJ = 15;
    }
}

message ChenLingFesLevelEndCsReq {
    uint32 level_id = 3;
}

message ChenLingFesLevelEndScRsp {
    uint32 level_id = 2;
    DMHADFNOIGP level_data = 6;
    uint32 retcode = 8;
}

message ChenLingFesLevelLeaveCsReq {
    uint32 level_id = 11;
}

message ChenLingFesLevelLeaveScRsp {
    uint32 level_id = 7;
    uint32 retcode = 13;
}

message ChenLingFesLevelResumeCsReq {
    uint32 level_id = 9;
}

message ChenLingFesLevelResumeScRsp {
    uint32 level_id = 4;
    uint32 retcode = 5;
    uint32 FGKPIDLKALL = 14;
}

message ChenLingFesLevelStartCsReq {
    uint32 level_id = 14;
}

message ChenLingFesLevelStartScRsp {
    uint32 FGKPIDLKALL = 2;
    string NLMEEEKBPKO = 5;
    string FGGCAOAPGPA = 9;
    uint32 retcode = 12;
    uint32 level_id = 13;
}

message ChenLingFesRaidKickedNotify {
    uint32 raid_id = 6;
}

enum CmdChenLingFesType {
    CmdChenLingFesType_NLCDGIPGFDJ = 0;
    CmdChenLingFesType_ChenLingFesLevelStartCsReq = 9937;
    CmdChenLingFesType_ChenLingFesLevelLeaveScRsp = 9948;
    CmdChenLingFesType_ChenLingFesRaidKickedNotify = 9917;
    CmdChenLingFesType_DGOFALCINAO = 9909;
    CmdChenLingFesType_ChenLingFesLevelStartScRsp = 9944;
    CmdChenLingFesType_AGGHGALCLOC = 9924;
    CmdChenLingFesType_ChenLingFesLevelResumeCsReq = 9903;
    CmdChenLingFesType_GetChenLingFesDataScRsp = 9923;
    CmdChenLingFesType_ChenLingFesLevelLeaveCsReq = 9919;
    CmdChenLingFesType_ChenLingFesLevelEndScRsp = 9921;
    CmdChenLingFesType_ChenLingFesLevelResumeScRsp = 9907;
    CmdChenLingFesType_ChenLingFesLevelEndCsReq = 9910;
    CmdChenLingFesType_ChenLingFesBusinessDayEndScRsp = 9920;
}

message DMHADFNOIGP {
    bool is_success = 12;
    repeated MOJFFDOILBN JOJJKJFHMBI = 14;
}

message GetChenLingFesDataScRsp {
    uint32 retcode = 8;
    repeated BGAIEEIKOKK PNDPCELOGHG = 13;
    OFGLEOIIJBD LAEDNIBCNKF = 15;
}

message MOJFFDOILBN {
    uint32 star_num = 1;
    repeated uint32 EMPIEBNCANN = 6;
    uint32 score_id = 8;
    uint32 phase_index = 11;
    repeated uint32 MNOOFEPDHOO = 14;
}

message NPNAEPOKPNE {
    OPOCANGAEHJ coord = 8;
    repeated float LIAMHNFAPNL = 10;
}

message OFGLEOIIJBD {
    uint32 FGKPIDLKALL = 2;
    repeated MOJFFDOILBN JOJJKJFHMBI = 3;
    uint32 fever = 4;
    string FGGCAOAPGPA = 5;
    uint32 HGIICMLANJJ = 6;
    uint32 HHINBDNIFBE = 7;
    repeated NPNAEPOKPNE GOKMDCOJPHC = 8;
    repeated PGIEBMKMECE MBFLDKEDBHN = 9;
    uint32 level_id = 10;
    uint32 PLCPOONCFDG = 11;
    string NLMEEEKBPKO = 12;
    uint32 business_day = 13;
    uint32 PGOFHKLBPKC = 14;
    repeated uint32 FJDJCHFDIFL = 15;
}

message OPOCANGAEHJ {
    uint32 y = 7;
    uint32 x = 12;
}

message PGIEBMKMECE {
    OPOCANGAEHJ IBLECIJAGBK = 1;
    uint32 OMFGAABELHE = 2;
    uint32 score_id = 3;
    uint32 direction = 10;
    repeated float CDMKBCHLPAB = 13;
}
