syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message COCHLLCNDJF {
    repeated EDKJELMPONH CDGNAJDAGKE = 6;
}

message ChimeraDoFinalRoundScRsp {
    repeated GADFFIFFNHM DKMKPFDNEBL = 1;
    uint32 index = 3;
    bool CJEILDIOIOE = 4;
    uint32 retcode = 6;
    uint32 ENMLPFBMPNI = 8;
    uint32 HCENDLKKHOC = 9;
    uint32 GGPKMPBBENP = 11;
    repeated ONNMLLIEENI CMBJOLCGMAI = 12;
    uint32 finish_work_cnt = 13;
    uint32 NMPCJAOIOHJ = 14;
}

message ChimeraFinishEndlessRoundScRsp {
    uint32 MMFKMEGECOI = 1;
    uint32 retcode = 2;
    uint32 PIGPKIDNMDH = 4;
    uint32 NMPCJAOIOHJ = 7;
    uint32 EBDOCKLLKMI = 8;
    uint32 IOMEILDMBNE = 9;
    bool CJEILDIOIOE = 12;
    repeated GADFFIFFNHM DKMKPFDNEBL = 13;
}

message ChimeraGetDataCsReq {
}

message ChimeraGetDataScRsp {
    uint32 finish_work_cnt = 1;
    uint32 HCENDLKKHOC = 2;
    repeated ONNMLLIEENI CMBJOLCGMAI = 3;
    uint32 IOMEILDMBNE = 4;
    uint32 PIGPKIDNMDH = 6;
    HDIOKENOFNJ HFPGDCJMNIK = 7;
    uint32 MMFKMEGECOI = 8;
    repeated uint32 ICBIMKIEOEP = 9;
    uint32 IMCGJPMBPPJ = 10;
    repeated GADFFIFFNHM JCOAGOJEAPB = 11;
    uint32 JIDBIMNMLJP = 12;
    uint32 retcode = 13;
    GCFGCHAMNOL lineup = 14;
    uint32 FBNEKMPIAKD = 15;
    uint32 ENMLPFBMPNI = 1180;
    uint32 NMPCJAOIOHJ = 1244;
    uint32 KCCACINBEEA = 1379;
    uint32 GGPKMPBBENP = 1587;
}

message ChimeraQuitEndlessCsReq {
}

message ChimeraQuitEndlessScRsp {
    uint32 retcode = 1;
}

enum ChimeraRoundWorkEndReason {
    POCJMDKMABI_KMOKDKCLMLD = 0;
    POCJMDKMABI_BKGPAKHJNKM = 1;
    POCJMDKMABI_LJEMJMCLGDH = 2;
    POCJMDKMABI_KLEKCFHLOGO = 3;
}

message ChimeraStartEndlessCsReq {
}

message ChimeraStartEndlessScRsp {
    uint32 retcode = 12;
}

enum CmdChimeraType {
    CmdChimeraType_NLCDGIPGFDJ = 0;
    CmdChimeraType_ChimeraGetDataCsReq = 8178;
    CmdChimeraType_NAGNHPDGFNG = 8180;
    CmdChimeraType_ChimeraFinishRoundScRsp = 8177;
    CmdChimeraType_ChimeraFinishEndlessRoundScRsp = 8175;
    CmdChimeraType_GBMFPFHNLBA = 8163;
    CmdChimeraType_ChimeraQuitEndlessCsReq = 8161;
    CmdChimeraType_ChimeraGetDataScRsp = 8168;
    CmdChimeraType_AOBDNGMLGMN = 8167;
    CmdChimeraType_IBPCLJPMLLG = 8174;
    CmdChimeraType_ChimeraDoFinalRoundScRsp = 8170;
    CmdChimeraType_CJIBJJGCBNO = 8172;
    CmdChimeraType_ChimeraStartEndlessCsReq = 8165;
    CmdChimeraType_ChimeraQuitEndlessScRsp = 8169;
    CmdChimeraType_BKALJDIIMOG = 8162;
    CmdChimeraType_ChimeraStartEndlessScRsp = 8164;
    CmdChimeraType_HLCGGBHIFLJ = 8171;
}

message EDKJELMPONH {
    uint32 progress = 2;
    uint32 HEFFPONLEGO = 12;
}

message GADFFIFFNHM {
    bool AMHAJDNFBGC = 5;
    int32 atk = 8;
    COCHLLCNDJF CDGNAJDAGKE = 9;
    int32 hp = 10;
    repeated uint32 IIELAJFFDPB = 12;
    uint32 id = 15;
}

message GCFGCHAMNOL {
    repeated uint32 PGFFGKDOPGM = 9;
    uint32 CMEKNAJONPH = 10;
}

enum HDIOKENOFNJ {
    HDIOKENOFNJ_EEGFMMCGCNH = 0;
    HDIOKENOFNJ_GOBLPKACBAE = 1;
    HDIOKENOFNJ_AHEJBANCCEK = 2;
    HDIOKENOFNJ_KBBPMFKGFCP = 3;
}

message LBMLOLGEHIM {
    uint32 retcode = 2;
}

message MFFFEOKDOAE {
    GCFGCHAMNOL lineup = 6;
    uint32 retcode = 15;
}

message NPDKAGOCOLG {
    repeated uint32 EACEBOMJKJH = 6;
}

message ONNMLLIEENI {
    uint32 finish_work_cnt = 3;
    uint32 IDBDBICPBBG = 4;
}
