syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AIGEDICFHCE {
    uint32 IMGLLIBJAPC = 7;
    bool is_win = 9;
}

message AJNKADCOKOL {
    uint32 IMGLLIBJAPC = 6;
    bool is_win = 12;
}

message CAMLFNCBFHI {
    repeated uint32 avatar_id_list = 6;
}

message CNOAGGFCDAL {
}

message ClockParkBuffList {
    repeated FAMLGHGHIOD buff_list = 4;
}

message ClockParkFinishScriptScNotify {
    GIPBHLBFDAH NLEOMLNOKCC = 9;
}

message ClockParkGetInfoScRsp {
    repeated DEGFFGKMFJJ DCGDHFJLHCN = 1;
    uint32 progress = 3;
    uint32 LNKAKGOCAOF = 4;
    uint32 CDGICHDIIHH = 6;
    repeated uint32 HPEKLHNPDAJ = 9;
    uint32 retcode = 14;
}

message ClockParkGetOngoingScriptInfoCsReq {
}

message ClockParkGetOngoingScriptInfoScRsp {
    repeated uint32 FKNBOIIMFLD = 1;
    ClockParkBuffList HABJHGPFGEB = 5;
    uint32 INDJEOAJJEN = 6;
    uint32 GIGAEFCKIAK = 7;
    MDDIKNGBPPL HGDLJDAFHLI = 8;
    uint32 script_id = 9;
    uint32 JIPPMKBDJJC = 10;
    uint32 retcode = 11;
    uint32 DCAHJELNJNP = 12;
    string IMJFLCKFJGF = 13;
    uint32 NGBJMEHDKHN = 14;
    LOBFOKCKPKB JOFJEIFLGBP = 15;
}

message ClockParkHandleWaitOperationScRsp {
    uint32 DMNECEKOLAJ = 2;
    uint32 IGBHCBNKEBO = 4;
    uint32 retcode = 6;
    uint32 JGPHDBDHKKO = 7;
    ClockParkPlayStatus LNPGHCLDOKG = 13;
    SceneBattleInfo battle_info = 14;
}

enum ClockParkPlayStatus {
    ACKNOAAIMPC_NFALPEDFKCL = 0;
    ACKNOAAIMPC_KHBHLGJPGPG = 1;
    ACKNOAAIMPC_MOBBEPFDCEM = 2;
    ACKNOAAIMPC_MNKEDGJLHLE = 5;
}

message ClockParkStartScriptCsReq {
    repeated uint32 BDGMNPIJDDL = 1;
    uint32 script_id = 4;
}

message ClockParkStartScriptScRsp {
    uint32 retcode = 7;
    uint32 script_id = 15;
}

message ClockParkUnlockTalentCsReq {
    uint32 CKHCLKOALKE = 13;
}

message ClockParkUnlockTalentScRsp {
    uint32 CKHCLKOALKE = 4;
    uint32 retcode = 11;
}

enum CmdClockParkType {
    CmdClockParkType_NLCDGIPGFDJ = 0;
    CmdClockParkType_ClockParkHandleWaitOperationScRsp = 7220;
    CmdClockParkType_ClockParkStartScriptCsReq = 7203;
    CmdClockParkType_ClockParkWaitSelectStartChapterIDCsReq = 7224;
    CmdClockParkType_ClockParkGetOngoingScriptInfoScRsp = 7221;
    CmdClockParkType_PEKHIMIDGHC = 7209;
    CmdClockParkType_ClockParkGetInfoScRsp = 7223;
    CmdClockParkType_ClockParkStartScriptScRsp = 7207;
    CmdClockParkType_ClockParkQuitScriptScRsp = 7229;
    CmdClockParkType_KBGOAJMIPEM = 7202;
    CmdClockParkType_ClockParkGetOngoingScriptInfoCsReq = 7210;
    CmdClockParkType_ANPBFBHIOHP = 7215;
    CmdClockParkType_ClockParkUnlockTalentCsReq = 7219;
    CmdClockParkType_ClockParkFinishScriptScNotify = 7213;
    CmdClockParkType_ClockParkQuitScriptCsReq = 7217;
    CmdClockParkType_ClockParkUseBuffCsReq = 7235;
    CmdClockParkType_ClockParkUnlockTalentScRsp = 7248;
}

message DEGFFGKMFJJ {
    repeated uint32 CFJOGMJIHOE = 9;
    uint32 script_id = 12;
}

message FAMLGHGHIOD {
    uint64 unique_id = 2;
    uint32 NOJLMNMPKDP = 7;
    uint32 buff_id = 14;
}

message FFDLJDAGEML {
    IIMHLPBEDDH CENIOBBIJMF = 13;
}

message FOFGKMONJHJ {
    bool OEKKAJJEGAK = 3;
}

message GEDICCGGDGI {
    uint32 script_id = 5;
    bool MHICFGAPPNB = 11;
}

message GIPBHLBFDAH {
    uint32 progress = 1;
    uint32 DCAHJELNJNP = 2;
    uint32 script_id = 3;
    uint32 NGBJMEHDKHN = 6;
    bool DMNEACGEHEC = 7;
    bool HGPKMHFPMBJ = 11;
    ItemList reward = 13;
}

message IEFICANECDH {
    uint32 NDNHCFBFPMH = 2;
    uint32 gacha_random = 6;
    IIMHLPBEDDH CENIOBBIJMF = 13;
}

message IFEGAHJADHG {
    uint32 retcode = 2;
}

message IGJLLHMJKPC {
    uint32 gacha_random = 5;
    bool IMKGOKGKDPH = 6;
}

message IIMHLPBEDDH {
    repeated uint32 KCNEKEGGAGG = 10;
    repeated NIJHCCNMEGA LONFKFCFDND = 11;
}

message KJAIAGDNPGC {
    IIMHLPBEDDH CENIOBBIJMF = 2;
}

message KOCBHDOKFNF {
    IIMHLPBEDDH CENIOBBIJMF = 10;
}

message LOBFOKCKPKB {
    int32 PNOIJPDMCPG = 10;
    int32 AKKLILNJCPL = 13;
    int32 JEKOHIHJFMK = 14;
}

message MDDIKNGBPPL {
    uint32 JGPHDBDHKKO = 5;
    oneof EEFKMMOBNOJ {
        CNOAGGFCDAL ICPMABKBLCD = 14;
        PEGDBKDLJDJ FDNLIPKGBLM = 3;
        NIKCDPGKKLF ABIPNABIDPE = 2;
        KOCBHDOKFNF BPMEBJHDOFC = 13;
        IEFICANECDH HGHBDACDJKP = 8;
        FFDLJDAGEML DLNGPBMGMKM = 9;
        FOFGKMONJHJ BELJJJLLCBK = 12;
        bool ALFNNIIMBLM = 1;
    }
}

message MOEMKBLCKKO {
}

message NIJHCCNMEGA {
    uint32 NPCBECNBIJK = 5;
    repeated uint32 KCNEKEGGAGG = 6;
    uint32 card_id = 8;
}

message NIKCDPGKKLF {
    IIMHLPBEDDH CENIOBBIJMF = 15;
}

message NKOCCGLHOML {
}

message OMPEMGHMDPM {
    uint32 retcode = 6;
    uint32 JGPHDBDHKKO = 7;
}

message ONNHCHDGBAB {
    uint32 JGPHDBDHKKO = 3;
    uint32 script_id = 5;
    uint32 retcode = 9;
    ClockParkBuffList HABJHGPFGEB = 13;
    oneof BAHFDOOAGPP {
        IIMHLPBEDDH CENIOBBIJMF = 1877;
        LOBFOKCKPKB JOFJEIFLGBP = 992;
    }
}

message PEGDBKDLJDJ {
    IIMHLPBEDDH CENIOBBIJMF = 12;
}

message PGHBOPEOBHA {
    uint32 script_id = 1;
    uint64 unique_id = 4;
    uint32 JGPHDBDHKKO = 13;
}
