syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AALCHOPCBEM {
    CABCPFKAOPP JOOEEKMDAEO = 3;
}

message AFDJNEOHCLB {
    uint32 OCJCOOLMCGD = 8;
    JLPEICPFLMC source = 9;
    uint32 progress = 15;
}

message AJNJDDFGFJL {
    uint32 max_level = 7;
    uint32 BFCNALJDHMP = 8;
    uint64 IEPAPOPIFHH = 11;
    uint32 level = 15;
}

message AKHEOAIPAPA {
    uint32 unique_id = 2;
    double OJMOBAEEMAP = 3;
    double CPLFBOBLFMC = 5;
    JLPEICPFLMC source = 8;
    GLBAOKOHKCF GOKKLNBMLCA = 10;
}

enum BCAMANFJINC {
    BCAMANFJINC_NLCDGIPGFDJ = 0;
    BCAMANFJINC_MLIGAFABJDP = 1;
    BCAMANFJINC_BLLCMLBDLPC = 2;
    BCAMANFJINC_MEBGACKEOOG = 3;
    BCAMANFJINC_GHPKFACFMML = 4;
    BCAMANFJINC_JHJCNLLMPKH = 5;
    BCAMANFJINC_LOFJAGLLHHG = 6;
    BCAMANFJINC_HEIHBJEEGPB = 7;
    BCAMANFJINC_NJPMBLBIBOD = 8;
    BCAMANFJINC_GIFGLDBDELN = 9;
    BCAMANFJINC_NGECENKOPLK = 10;
    BCAMANFJINC_EMGMFOBLAFN = 11;
    BCAMANFJINC_LIJMDJDFIIC = 12;
    BCAMANFJINC_JHGMHCJOKNA = 13;
    BCAMANFJINC_KPCEJLILHMO = 14;
    BCAMANFJINC_AEHHIPFDNFJ = 15;
    BCAMANFJINC_KHBEOADDIFM = 16;
    BCAMANFJINC_action = 17;
    BCAMANFJINC_DACEMIDFHOG = 18;
    BCAMANFJINC_OIKFFLEHFCN = 19;
    BCAMANFJINC_KEJCJJHDKJB = 20;
    BCAMANFJINC_EIIJCLPCFLM = 21;
    BCAMANFJINC_NKJFKBBDDEO = 22;
}

message BDOEDOEBFAJ {
    repeated AFDJNEOHCLB IFJIHNBDNGN = 1;
    repeated LEGNLMENMJK entity_list = 2;
    uint32 NKDDBPGDAEE = 3;
    repeated HGCIPBFBNKO LDCJONHGDAN = 4;
    repeated PHHFOGFKDBC MEMGHBHGGPN = 5;
    uint32 GCBDADCOBAE = 6;
    uint32 stage_id = 7;
    repeated DFFLMEMFPLM IEDKELDFHLP = 8;
    KFOOLGFCNDN ILOODGHPOBM = 9;
    uint32 item_value = 10;
    repeated uint32 MGJENMKKIBJ = 11;
    repeated uint32 OKHDNEOLLNF = 12;
    uint32 cur_wave = 13;
    uint32 hp = 14;
    BNHBDMIDFCL FMIGOKIDKJL = 15;
    repeated uint64 FNJCMFOFCNC = 264;
    uint32 max_hp = 539;
    MBLJIEELMKN GHICOBOPHOL = 1951;
}

message BEKKPBIKINI {
    uint32 retcode = 8;
}

message BFGNNODONFI {
}

message BNHBDMIDFCL {
    uint32 unique_id = 13;
    JAAJAPNFMGO DOKPHNPNCPN = 1053;
}

message CABCPFKAOPP {
    uint32 KDIDDHIDNCG = 1;
    repeated uint32 GCDGGBLOJIC = 8;
    repeated uint32 NFPADEPIKML = 10;
    uint32 OEKIFIKBMFI = 11;
}

enum CNEEMBBNNBO {
    CNEEMBBNNBO_NLCDGIPGFDJ = 0;
    CNEEMBBNNBO_EHNIPLNEEDI = 1;
    CNEEMBBNNBO_FAODKNDLNPF = 2;
    CNEEMBBNNBO_INCLHHDFCEL = 3;
}

message ChenLingActivatedPrivilegeCsReq {
    uint32 ADBGHKBGGJM = 11;
}

message ChenLingActivatedPrivilegeScRsp {
    uint32 ADBGHKBGGJM = 2;
    uint32 retcode = 5;
}

message ChenLingGetDataScRsp {
    FDDNKPJEMJE DJOLGKGKCHE = 5;
    BDOEDOEBFAJ KFAIGIIPLOF = 9;
    repeated uint32 IMNNAENHBMA = 11;
    uint32 retcode = 13;
    uint32 GDHOLMIBAEA = 14;
}

message ChenLingQuitStageCsReq {
    uint32 GDIMKFNECOK = 14;
}

message ChenLingQuitStageScRsp {
    DFEGGFFOMKI BFLLJJBHLDF = 3;
    uint32 retcode = 5;
}

message ChenLingStartStageCsReq {
    uint32 NKDDBPGDAEE = 3;
    uint32 stage_id = 13;
}

message ChenLingStartStageScRsp {
    uint32 retcode = 11;
    BDOEDOEBFAJ AHCGJNDKBCA = 13;
}

message ChenLingSyncChangeScNotify {
    repeated IOELPDDJGFJ DGNGMJMPFGK = 3;
}

enum CmdChenLingBattleType {
    CmdChenLingBattleType_NLCDGIPGFDJ = 0;
    CmdChenLingBattleType_ChenLingBuyShopItemScRsp = 9609;
    CmdChenLingBattleType_ChenLingPendingActionSelectCardScRsp = 9575;
    CmdChenLingBattleType_ChenLingRefreshShopScRsp = 9578;
    CmdChenLingBattleType_ChenLingFinishPrepareCsReq = 9587;
    CmdChenLingBattleType_ChenLingSelectPolicyCsReq = 9610;
    CmdChenLingBattleType_ChenLingQuitStageCsReq = 9589;
    CmdChenLingBattleType_ChenLingHandlePendingActionsCsReq = 9600;
    CmdChenLingBattleType_ChenLingFinishShopCsReq = 9602;
    CmdChenLingBattleType_ChenLingSyncChangeScNotify = 9592;
    CmdChenLingBattleType_ChenLingRefreshCardScRsp = 9584;
    CmdChenLingBattleType_ChenLingUseHandCardScRsp = 9591;
    CmdChenLingBattleType_JDIMPKBBDBJ = 9571;
    CmdChenLingBattleType_ChenLingSelectPolicyScRsp = 9596;
    CmdChenLingBattleType_ChenLingRefreshPolicyCsReq = 9605;
    CmdChenLingBattleType_ChenLingRefreshPolicyScRsp = 9585;
    CmdChenLingBattleType_ChenLingQuitStageScRsp = 9618;
    CmdChenLingBattleType_ChenLingMoveEntityCsReq = 9611;
    CmdChenLingBattleType_ChenLingUnlockGridCsReq = 9573;
    CmdChenLingBattleType_ChenLingFinishPrepareScRsp = 9599;
    CmdChenLingBattleType_ChenLingRefreshCardCsReq = 9572;
    CmdChenLingBattleType_ChenLingBuyShopItemCsReq = 9615;
    CmdChenLingBattleType_ChenLingRefreshShopCsReq = 9583;
    CmdChenLingBattleType_ChenLingStartStageCsReq = 9607;
    CmdChenLingBattleType_ChenLingSellHandCardCsReq = 9594;
    CmdChenLingBattleType_ChenLingActivatedPrivilegeScRsp = 9612;
    CmdChenLingBattleType_FinishBattleScRsp = 9576;
    CmdChenLingBattleType_ChenLingFinishBattleCsReq = 9603;
    CmdChenLingBattleType_ChenLingSelectCardScRsp = 9613;
    CmdChenLingBattleType_FBJDNKEOLPB = 9586;
    CmdChenLingBattleType_ChenLingUnlockGridScRsp = 9577;
    CmdChenLingBattleType_ChenLingStartStageScRsp = 9614;
    CmdChenLingBattleType_ChenLingSelectCardCsReq = 9588;
    CmdChenLingBattleType_ChenLingSellHandCardScRsp = 9590;
    CmdChenLingBattleType_ChenLingGetDataScRsp = 9593;
    CmdChenLingBattleType_ChenLingFinishShopScRsp = 9606;
    CmdChenLingBattleType_ChenLingUseHandCardCsReq = 9580;
    CmdChenLingBattleType_ChenLingMoveEntityScRsp = 9582;
    CmdChenLingBattleType_ChenLingBattleGetDataCsReq = 9579;
    CmdChenLingBattleType_ChenLingActivatedPrivilegeCsReq = 9617;
}

message DFEGGFFOMKI {
    uint32 wave = 1;
    uint32 cur_hp = 5;
    CNEEMBBNNBO reason = 6;
    repeated OGGELMMFPKP PPCKLBHFCCA = 7;
    uint32 stage_id = 8;
    uint32 max_hp = 13;
}

message DFFLMEMFPLM {
    uint32 BFCNALJDHMP = 12;
    PFPPACPMFDJ DJNOLLDHPHJ = 15;
}

message DIONONBIIKN {
    uint32 GDIMKFNECOK = 5;
}

message DLGCDMBGIEB {
    uint32 retcode = 10;
}

message EIFJNMDDNPF {
    uint32 retcode = 7;
}

message EJDPLLIJDNK {
    uint64 CHFNDAGCEBK = 3;
}

message EJKNEDLPMIB {
    uint32 BFCNALJDHMP = 7;
    GACKCPEPDAF GHPKFACFMML = 11;
}

message EOKKHLOIBIM {
    DFFLMEMFPLM HEHIOCEPEAE = 1;
    DFFLMEMFPLM GEOMBJDBHDD = 2;
}

message FAHNFMCOJCH {
    uint32 retcode = 10;
}

message FCNMJGGDEFO {
    PFPPACPMFDJ GAJFFBBMMEN = 2;
    uint32 FGIHKKKOGJD = 6;
}

message FDDNKPJEMJE {
    uint32 stage_id = 1;
    bool is_unlock = 6;
}

message FIBKOLLMPMM {
}

message FJJPDJAEJHC {
    repeated uint32 MKOKLLKALDE = 11;
}

message GACKCPEPDAF {
    uint64 MLMFNEBLNHP = 11;
    uint32 max_level = 12;
    uint32 level = 14;
    uint32 config_id = 15;
}

message GBCKAGHDPEB {
}

message GDDLBMCHIED {
    repeated uint32 MKOKLLKALDE = 9;
    uint32 KDIDDHIDNCG = 12;
}

message GEEPIPMBGJD {
    repeated uint32 GCDGGBLOJIC = 3;
    CABCPFKAOPP JOOEEKMDAEO = 5;
    repeated uint32 NFPADEPIKML = 7;
    uint32 KDIDDHIDNCG = 8;
    uint32 OEKIFIKBMFI = 12;
}

message GEPCOHMCAAJ {
    uint32 retcode = 3;
}

message GICMOLJPLGF {
    repeated PHHFOGFKDBC MEMGHBHGGPN = 3;
}

message GKNOCNDPAJA {
    uint64 IEPAPOPIFHH = 3;
    uint32 max_level = 7;
    uint32 level = 10;
}

enum GLBAOKOHKCF {
    GLBAOKOHKCF_NLCDGIPGFDJ = 0;
    GLBAOKOHKCF_COJOIFPPCIJ = 2;
    GLBAOKOHKCF_hp = 3;
    GLBAOKOHKCF_OGGGLOEIOMM = 4;
    GLBAOKOHKCF_CCPLGNNIOCO = 5;
    GLBAOKOHKCF_DGOMNKGLABB = 6;
    GLBAOKOHKCF_PAIEELDAADP = 7;
}

message GOKHEKCHLEL {
    uint32 retcode = 5;
    uint32 unique_id = 13;
}

message HFNMKEDPFJH {
    uint32 retcode = 1;
    uint32 add_coin = 3;
    bool DAOMHGBDEJH = 4;
    DFEGGFFOMKI BFLLJJBHLDF = 9;
    bool is_win = 10;
    uint32 cur_hp = 12;
    repeated OGGELMMFPKP PPCKLBHFCCA = 15;
}

message HGCIPBFBNKO {
    JLPEICPFLMC source = 5;
    uint64 unique_id = 7;
    uint32 config_id = 9;
    JLIFGIMBMBD AENBOONOFLC = 10;
}

message HKKBGLINEOM {
    uint32 BFCNALJDHMP = 4;
    PFPPACPMFDJ GAJFFBBMMEN = 11;
}

message HLCAKAJLKGO {
    uint32 retcode = 7;
}

message HPKOOPBFEAH {
}

message IIEKKGNJJMC {
    uint64 KNDHHAJMBGB = 3;
    uint32 BFCNALJDHMP = 8;
    bool DBODGPBOIHC = 13;
}

message IOELPDDJGFJ {
    JLPEICPFLMC source = 232;
    oneof MMCGBGDJIPN {
        GICMOLJPLGF PJDHBMOIPPO = 5;
        LCKBHJBKHNH CCHBNLOBPGE = 4;
        uint32 cur_hp = 2;
        uint32 rogue_money = 14;
        LEGNLMENMJK AGHANKEAODD = 9;
        uint32 MGKMLJHMNMO = 10;
        AJNJDDFGFJL GDFFAICHLDJ = 6;
        IIEKKGNJJMC BECPNBEFHGC = 13;
        EJKNEDLPMIB PBNOFEFIDFI = 1;
        NEEAHLMKAAB IAOIFAADLLC = 8;
        DFFLMEMFPLM HOEGFMPDBHH = 11;
        FJJPDJAEJHC HLHBOGKHEEO = 15;
        HGCIPBFBNKO ANHDPPOAOGL = 1364;
        uint64 ELMMNHBECNI = 1520;
        FDDNKPJEMJE DJOLGKGKCHE = 1722;
        uint32 GCBDADCOBAE = 1254;
        uint32 FOJHBIMCLGC = 691;
        NGHEPMFILPE CNCKEHMNJGD = 876;
        KHGFCNNCOGA BJPEEGIFAEA = 886;
        AFDJNEOHCLB OFCPKKMEFKE = 1229;
        LGFBMEACHPI NAPDGGDENBM = 1939;
        BNHBDMIDFCL FMIGOKIDKJL = 211;
        uint32 PMFBIGLPJJA = 1976;
        EJDPLLIJDNK ONAJPGNNLEN = 804;
        uint32 GDHOLMIBAEA = 1732;
        EOKKHLOIBIM KNANINELANC = 550;
        KHLAFMBONNK BEOAPFIBDLB = 860;
        JKLKCKNBHCI ADEJOKOIBHC = 548;
        BFGNNODONFI PJMJAPKJINA = 1279;
        MBLJIEELMKN GHICOBOPHOL = 68;
    }
}

message IOPAIDKIGAJ {
    PFPPACPMFDJ DJNOLLDHPHJ = 14;
}

message JAAJAPNFMGO {
    repeated uint32 GCDGGBLOJIC = 5;
}

message JJLPGBIAADJ {
    uint32 AAIDCOJPLCI = 11;
}

message JKLKCKNBHCI {
}

message JLIFGIMBMBD {
    uint32 KKCKMCDGCGK = 3;
    uint32 BIOFDPICHLC = 5;
    uint32 HMLBJFJIPCE = 12;
}

message JLPEICPFLMC {
    BCAMANFJINC source_type = 1;
    uint64 BNEFLBPCPOI = 6;
    oneof KLLMJCCOMNF {
        uint32 BFCNALJDHMP = 7;
        uint32 HPDFGFBLDOG = 9;
        uint32 GCPPLLLHBBJ = 13;
        uint32 DJODEIMGKGK = 8;
        uint32 PBHFMIIIPBD = 2;
        uint64 CHFNDAGCEBK = 1671;
        uint32 LEEMKAMANJN = 1075;
        uint32 NKDDBPGDAEE = 1219;
        uint32 EFEENOFADFC = 692;
        PFPPACPMFDJ DJNOLLDHPHJ = 158;
    }
}

message JMLOJKGMBMC {
    uint32 retcode = 9;
}

message KCEJNBLDAFE {
    uint32 retcode = 7;
}

message KFOOLGFCNDN {
    oneof CNHEJLOEFAA {
        AALCHOPCBEM EFBPPPNPBKH = 11;
        FIBKOLLMPMM IFCFIPGIIME = 6;
        LJBOELCMGFK OCIHLGBPALK = 15;
        GDDLBMCHIED NNLBNIJJPAH = 2;
        GEEPIPMBGJD DJBMEHBKNDF = 14;
        MLJEJCFJPLE BAMNOFCJMPP = 9;
    }
}

message KHGFCNNCOGA {
    uint32 BFCNALJDHMP = 1;
    repeated uint32 PJANEJJKOKA = 12;
}

message KHLAFMBONNK {
}

message KHMGHGPLPHF {
}

message KNKCNKJOKPA {
    uint32 GPDEFEBDMNM = 7;
}

message LAECPMJAIIK {
    uint32 retcode = 9;
}

message LCKBHJBKHNH {
    uint32 cur_wave = 4;
    KFOOLGFCNDN ILOODGHPOBM = 15;
}

message LDNFIICMCHA {
    uint32 max_level = 3;
    uint32 level = 6;
    bool DBODGPBOIHC = 7;
    uint64 IEPAPOPIFHH = 9;
    repeated AKHEOAIPAPA DIILKEEGLOJ = 12;
    repeated GACKCPEPDAF KAJOFKIEKNH = 13;
    uint64 KNDHHAJMBGB = 15;
}

message LEGNLMENMJK {
    uint32 unique_id = 6;
    uint32 card_id = 15;
    oneof NPFEGGMNBOC {
        LDNFIICMCHA MLIGAFABJDP = 7;
        GKNOCNDPAJA BLLCMLBDLPC = 11;
    }
}

message LFIONDMGCOP {
    uint32 AAIDCOJPLCI = 7;
}

message LGFBMEACHPI {
    repeated uint32 MGJENMKKIBJ = 3;
}

message LJBOELCMGFK {
    repeated uint32 GCDGGBLOJIC = 4;
    uint32 KDIDDHIDNCG = 6;
}

message LKFKOHLGMOJ {
    uint32 NCHPDFCFFCK = 1;
}

message MBLJIEELMKN {
    repeated KVP OCIJDDBLGMH = 4;
}

message MEJECBOGNNN {
    uint32 FGIHKKKOGJD = 2;
}

message MJEMCKGBIPN {
    uint32 retcode = 10;
}

message MLJEJCFJPLE {
}

message NEEAHLMKAAB {
    uint32 BFCNALJDHMP = 2;
    uint32 level = 8;
    uint32 max_level = 13;
    uint64 IEPAPOPIFHH = 14;
}

message NFAHEHELGEC {
}

message NGHEPMFILPE {
    uint32 BFCNALJDHMP = 10;
    AKHEOAIPAPA GOBMEEHNFDC = 14;
}

message OGGELMMFPKP {
    double damage = 5;
    uint32 config_id = 6;
}

message OMFFCGEINLF {
    uint32 retcode = 3;
}

message ONGCOFFLIAE {
    uint32 add_coin = 3;
    uint32 soldier_dead_cnt = 8;
    uint32 GDIMKFNECOK = 12;
    bool is_win = 13;
    repeated OGGELMMFPKP PPCKLBHFCCA = 14;
}

message PFELEGKDCBO {
    uint32 retcode = 12;
}

message PFPPACPMFDJ {
    int32 y = 5;
    int32 x = 11;
}

message PHHFOGFKDBC {
    uint32 unique_id = 7;
    uint32 card_id = 12;
}

message PICHIFNMBNO {
    uint32 unique_id = 10;
    LFIONDMGCOP GFGGBLEGKGJ = 143;
}

message PIIJEIADMFP {
    bool PBJJAHKLNAA = 9;
}

message PLMPGLKCGBJ {
}
