syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AEMAPGKPPJA {
    FJKGDHKKDFF FDEEBBFMBLB = 2;
    LMNCBIDKHLF OLJCAJMFJPO = 6;
    uint32 JPPAGGPJOMO = 9;
    repeated uint32 OPAEGCBNACJ = 11;
    int32 FJCIKNAKJOG = 15;
}

enum AIMCAMJABNA {
    AIMCAMJABNA_NLCDGIPGFDJ = 0;
    AIMCAMJABNA_ILIIOLJMKME = 1;
}

message BKJCADFCHAB {
    uint32 HONCDMKPBEG = 4;
}

message CGMCMAKMJDK {
    uint32 CFGEJHAOKED = 1;
    ChessRogueCellSpecialType KFEMJMKMGIJ = 2;
    uint32 JMPMDGJLIPF = 3;
    bool is_unlock = 5;
    uint32 id = 6;
    uint32 room_id = 7;
    MCDONFNGMJE stage_info = 8;
    uint32 PDKOHKKMKLF = 9;
    bool LDDHLGINDIJ = 10;
    uint32 HLALFNEDFED = 12;
    ChessRogueBoardCellStatus EJEDLGNLOHB = 15;
}

message CHHBLFHDFEK {
    uint32 KPDLMKFLJAI = 5;
    uint32 BMGCCEONICH = 9;
}

enum ChessRogueBoardCellStatus {
    GOBKHHAEIAF_BPOCOHFIAOH = 0;
    GOBKHHAEIAF_EAPFJHJHIFK = 1;
    GOBKHHAEIAF_LOOAKNHDBLL = 2;
    GOBKHHAEIAF_CIHFGJDCHIA = 3;
}

enum ChessRogueCellSpecialType {
    PHAHPIPPMDF_NLCDGIPGFDJ = 0;
    PHAHPIPPMDF_ABGEKPJHHIA = 1;
    PHAHPIPPMDF_EHDFEMMFHDG = 2;
    PHAHPIPPMDF_KCAIFKMKHFJ = 3;
    PHAHPIPPMDF_CMFNKDKKGGI = 4;
    PHAHPIPPMDF_MOPJKHEINAL = 5;
}

message ChessRogueCellUpdateNotify {
    uint32 AIHCKNAMPBP = 4;
    RogueModifierSourceType CFAOFCGJBMA = 7;
    AIMCAMJABNA reason = 10;
    repeated CGMCMAKMJDK CPPCIGMJALM = 15;
}

message ChessRogueChangeAeonDimensionNotify {
    DMGODFDFPEI info = 4;
}

message ChessRogueCheatRollCsReq {
    uint32 AMPFBGKHJBF = 6;
    uint32 MMNMIFAAHOF = 13;
}

message ChessRogueCheatRollScRsp {
    uint32 retcode = 13;
    KFACLOGFNJF POHEPEEFBOA = 14;
}

message ChessRogueConfirmRollCsReq {
}

message ChessRogueConfirmRollScRsp {
    uint32 retcode = 1;
    KFACLOGFNJF POHEPEEFBOA = 13;
}

enum ChessRogueDiceStatus {
    EEOMEIAMNMB_BBBFNMBDFDE = 0;
    EEOMEIAMNMB_BGDFCDGFAML = 1;
    EEOMEIAMNMB_IMFHIFIKKNK = 2;
    EEOMEIAMNMB_DMMCIMLIJOA = 3;
}

enum ChessRogueDiceType {
    HJCOLMNPKBK_IHHJBGPPACD = 0;
    HJCOLMNPKBK_BKCCOGNPPGH = 1;
}

message ChessRogueEnterCellCsReq {
    uint32 IHAOMLEPHOM = 5;
    uint32 LOFMJHJOELO = 15;
}

message ChessRogueEnterCellScRsp {
    uint32 retcode = 8;
    DJEKEGMEHLK info = 11;
    MANINNKMFHG stage_info = 15;
}

message ChessRogueEnterNextLayerCsReq {
}

message ChessRogueEnterNextLayerScRsp {
    uint32 retcode = 2;
    OFGJFLCBBJP HPHKDGJHIJL = 4;
    MANINNKMFHG stage_info = 6;
    DJEKEGMEHLK rogue_game_info = 10;
}

message ChessRogueEnterScRsp {
    DJEKEGMEHLK info = 3;
    MANINNKMFHG stage_info = 12;
    uint32 id = 14;
    uint32 retcode = 15;
}

message ChessRogueGiveUpScRsp {
    AEMAPGKPPJA AEFMMOHKCHJ = 1;
    OGHPKFMNNHL MINFCKLKLNJ = 2;
    uint32 retcode = 10;
    PPAGCEGGCAK LFLCDNGALME = 11;
    HIMJKAMHLMJ IHNENEGKEPO = 12;
    MANINNKMFHG stage_info = 14;
}

message ChessRogueLayerSettlement {
    uint32 difficulty = 9;
    OGHPKFMNNHL MINFCKLKLNJ = 14;
}

message ChessRogueLeaveCsReq {
}

message ChessRogueLeaveScRsp {
    HIMJKAMHLMJ IHNENEGKEPO = 4;
    PPAGCEGGCAK LFLCDNGALME = 5;
    AEMAPGKPPJA AEFMMOHKCHJ = 6;
    MANINNKMFHG stage_info = 8;
    uint32 retcode = 10;
}

message ChessRogueNousDiceSurfaceUnlockNotify {
    uint32 HBKEEBKFBFI = 1;
}

message ChessRogueNousDiceUpdateNotify {
    MOOKMKEKMKC DDHKAGCLBLH = 11;
}

message ChessRogueNousEditDiceScRsp {
    HGCIAPKELAF IOCCACNJIGD = 5;
    uint32 retcode = 12;
}

message ChessRogueNousEnableRogueTalentScRsp {
    FDBDLBAPDBE JCOBJAMPOAL = 5;
    uint32 retcode = 10;
    uint32 FPCCPKAOGKG = 13;
}

message ChessRogueNousGetRogueTalentInfoCsReq {
}

message ChessRogueNousGetRogueTalentInfoScRsp {
    uint32 FPCCPKAOGKG = 4;
    uint32 retcode = 6;
    FDBDLBAPDBE JCOBJAMPOAL = 14;
}

message ChessRogueQueryCsReq {
}

message ChessRogueQueryScRsp {
    DJEKEGMEHLK info = 1;
    uint32 retcode = 4;
    OGHPKFMNNHL MINFCKLKLNJ = 7;
    PPAGCEGGCAK LFLCDNGALME = 11;
    HIMJKAMHLMJ IHNENEGKEPO = 12;
}

message ChessRogueQuestFinishNotify {
    uint32 PEGKFPIKPKP = 2;
}

message ChessRogueQuitCsReq {
}

message ChessRogueQuitScRsp {
    LKPCDHCKHKP OEIBHLMDJKA = 3;
    AEMAPGKPPJA AEFMMOHKCHJ = 5;
    MANINNKMFHG stage_info = 9;
    HIMJKAMHLMJ IHNENEGKEPO = 10;
    uint32 retcode = 11;
    OGHPKFMNNHL MINFCKLKLNJ = 12;
    PPAGCEGGCAK LFLCDNGALME = 15;
}

message ChessRogueReRollDiceCsReq {
    uint32 MMNMIFAAHOF = 8;
}

message ChessRogueReRollDiceScRsp {
    uint32 retcode = 5;
    KFACLOGFNJF POHEPEEFBOA = 10;
}

message ChessRogueRollDiceCsReq {
    uint32 MMNMIFAAHOF = 14;
}

message ChessRogueRollDiceScRsp {
    KFACLOGFNJF POHEPEEFBOA = 2;
    uint32 retcode = 11;
}

message ChessRogueSelectCellCsReq {
    uint32 IHAOMLEPHOM = 2;
}

message ChessRogueSelectCellScRsp {
    uint32 retcode = 4;
    NAPFNBJDIOO EEGHDAJOHJO = 8;
}

message ChessRogueSkipTeachingLevelCsReq {
}

message ChessRogueSkipTeachingLevelScRsp {
    ItemList PDJCAHBPKLK = 7;
    uint32 retcode = 11;
}

message ChessRogueStartCsReq {
    repeated uint32 NOEPBNMJFGL = 1;
    repeated uint32 unfinished_story_line_id_list = 3;
    uint32 id = 4;
    repeated uint32 OCEGEKKFLAL = 5;
    uint32 PDFAHEKNHNJ = 9;
    repeated uint32 JKPIPNMGGOA = 12;
    uint32 AFEMBLFCCCH = 14;
}

message ChessRogueStartScRsp {
    MANINNKMFHG stage_info = 1;
    DJEKEGMEHLK info = 2;
    uint32 retcode = 6;
    OFGJFLCBBJP HPHKDGJHIJL = 11;
}

message ChessRogueUpdateActionPointScNotify {
    int32 EABEFBDOJEO = 5;
}

message ChessRogueUpdateAeonModifierValueScNotify {
    uint32 AFEMBLFCCCH = 3;
    int32 FJCIKNAKJOG = 11;
}

message ChessRogueUpdateAllowedSelectCellScNotify {
    repeated uint32 AADAFLKEJGD = 13;
    uint32 AIHCKNAMPBP = 14;
}

message ChessRogueUpdateDiceInfoScNotify {
    KFACLOGFNJF POHEPEEFBOA = 13;
}

message ChessRogueUpdateDicePassiveAccumulateValueScNotify {
    int32 CGPHGIBCNOH = 6;
}

message ChessRogueUpdateLevelBaseInfoScNotify {
    IOJJCDAPLAJ reason = 8;
    GDHLDNFLOOF GKDCPNLOLNF = 10;
}

message ChessRogueUpdateMoneyInfoScNotify {
    AGEOGDOGDMM DHEKLJDBNNP = 10;
}

message ChessRogueUpdateReviveInfoScNotify {
    GAJDPEBBFMG MFEODNJNGDP = 1;
}

message ChessRogueUpdateUnlockLevelScNotify {
    repeated uint32 HKCDKHJCNDC = 11;
}

enum CmdChessRogueType {
    CmdChessRogueType_NLCDGIPGFDJ = 0;
    CmdChessRogueType_FinishChessRogueSubStoryCsReq = 5544;
    CmdChessRogueType_ChessRogueEnterCellCsReq = 5486;
    CmdChessRogueType_GetChessRogueStoryInfoScRsp = 5548;
    CmdChessRogueType_EnterChessRogueAeonRoomScRsp = 5577;
    CmdChessRogueType_ChessRogueNousEditDiceScRsp = 5480;
    CmdChessRogueType_ChessRogueNousDiceUpdateNotify = 5455;
    CmdChessRogueType_ChessRogueEnterNextLayerCsReq = 5529;
    CmdChessRogueType_ChessRogueReviveRogueAvatarCsReq = 5543;
    CmdChessRogueType_ChessRogueUpdateReviveInfoScNotify = 5555;
    CmdChessRogueType_ChessRogueUpdateDiceInfoScNotify = 5460;
    CmdChessRogueType_ChessRogueUpdateUnlockLevelScNotify = 5496;
    CmdChessRogueType_ChessRogueUpdateAeonModifierValueScNotify = 5457;
    CmdChessRogueType_SelectChessRogueSubStoryScRsp = 5479;
    CmdChessRogueType_GetChessRogueStoryAeonTalkInfoScRsp = 5458;
    CmdChessRogueType_JKJFEHFCGLA = 5440;
    CmdChessRogueType_ChessRogueEnterScRsp = 5593;
    CmdChessRogueType_ChessRogueCheatRollCsReq = 5466;
    CmdChessRogueType_ChessRogueUpdateMoneyInfoScNotify = 5580;
    CmdChessRogueType_PPOCHBFMMHL = 5446;
    CmdChessRogueType_GiveUpChessRogueCsReq = 5441;
    CmdChessRogueType_ReEnterRogueCsReq = 5406;
    CmdChessRogueType_ChessRogueQuestFinishNotify = 5541;
    CmdChessRogueType_GetChessRogueStoryInfoCsReq = 5515;
    CmdChessRogueType_GetChessRogueStoryAeonTalkInfoCsReq = 5549;
    CmdChessRogueType_CmdGetRogueBuffEnhanceInfoScRsp = 5454;
    CmdChessRogueType_GetChessRogueNousStoryInfoScRsp = 5474;
    CmdChessRogueType_ChessRogueEnterCellScRsp = 5482;
    CmdChessRogueType_ChessRogueQueryCsReq = 5592;
    CmdChessRogueType_ChessRogueReviveRogueAvatarScRsp = 5550;
    CmdChessRogueType_ChessRogueLeaveScRsp = 5563;
    CmdChessRogueType_ChessRogueGiveUpScRsp = 5540;
    CmdChessRogueType_ChessRogueRollDiceScRsp = 5596;
    CmdChessRogueType_SyncChessRogueMainStoryFinishScNotify = 5469;
    CmdChessRogueType_ChessRogueUpdateLevelBaseInfoScNotify = 5437;
    CmdChessRogueType_ChessRogueRollDiceCsReq = 5501;
    CmdChessRogueType_ChessRogueStartCsReq = 5598;
    CmdChessRogueType_ChessRogueUpdateDicePassiveAccumulateValueScNotify = 5478;
    CmdChessRogueType_ChessRogueSkipTeachingLevelScRsp = 5445;
    CmdChessRogueType_ChessRogueNousDiceSurfaceUnlockNotify = 5408;
    CmdChessRogueType_ChessRogueCheatRollScRsp = 5410;
    CmdChessRogueType_ChessRogueQuitCsReq = 5434;
    CmdChessRogueType_ChessRogueLeaveCsReq = 5583;
    CmdChessRogueType_ChessRogueCellUpdateNotify = 5450;
    CmdChessRogueType_ChessRogueChangeAeonDimensionNotify = 5588;
    CmdChessRogueType_ChessRogueNousGetRogueTalentInfoScRsp = 5453;
    CmdChessRogueType_ChessRogueQuitScRsp = 5491;
    CmdChessRogueType_ChessRogueReRollDiceScRsp = 5417;
    CmdChessRogueType_SyncChessRogueNousMainStoryScNotify = 5421;
    CmdChessRogueType_ChessRogueNousEnableRogueTalentScRsp = 5586;
    CmdChessRogueType_AOACLOOJNLP = 5505;
    CmdChessRogueType_ChessRogueSelectCellCsReq = 5423;
    CmdChessRogueType_ChessRogueLayerSettlement = 5537;
    CmdChessRogueType_ChessRogueNousGetRogueTalentInfoCsReq = 5513;
    CmdChessRogueType_ChessRogueConfirmRollCsReq = 5573;
    CmdChessRogueType_GetChessRogueNousStoryInfoCsReq = 5545;
    CmdChessRogueType_ChessRogueQueryScRsp = 5524;
    CmdChessRogueType_ChessRogueReRollDiceCsReq = 5527;
    CmdChessRogueType_ChessRogueEnhanceRogueBuffCsReq = 5487;
    CmdChessRogueType_ChessRogueStartScRsp = 5495;
    CmdChessRogueType_ChessRogueConfirmRollScRsp = 5525;
    CmdChessRogueType_ChessRogueUpdateActionPointScNotify = 5590;
    CmdChessRogueType_EditChessRogueNousBranchSurfaceCsReq = 5546;
    CmdChessRogueType_ChessRoguePickRogueAvatarScRsp = 5494;
    CmdChessRogueType_ChessRoguePickRogueAvatarCsReq = 5488;
    CmdChessRogueType_SyncChessRogueNousValueScNotify = 5431;
    CmdChessRogueType_ChessRogueSkipTeachingLevelCsReq = 5483;
    CmdChessRogueType_ChessRogueEnterNextLayerScRsp = 5489;
    CmdChessRogueType_SyncChessRogueNousSubStoryScNotify = 5582;
    CmdChessRogueType_EnterChessRogueAeonRoomCsReq = 5463;
    CmdChessRogueType_ChessRogueUpdateAllowedSelectCellScNotify = 5520;
    CmdChessRogueType_ChessRogueSelectCellScRsp = 5522;
    CmdChessRogueType_FinishChessRogueSubStoryScRsp = 5516;
    CmdChessRogueType_ChessRogueEnhanceRogueBuffScRsp = 5514;
}

message DDAFEPBGOHK {
    FDBDLBAPDBE GMILDFJFOGD = 8;
    uint32 FPCCPKAOGKG = 13;
}

message DECHJACNLGP {
    uint32 monster_id = 1;
    uint32 BJBALPKFELE = 15;
}

message DFKMNLIJMFB {
    repeated DECHJACNLGP GEJNMNBLFLG = 7;
    uint32 POFBAHEECGB = 8;
    bool is_selected = 10;
}

message DJEKEGMEHLK {
    LKPCDHCKHKP OEIBHLMDJKA = 3;
    NHLBNBBDHMI DNPCCFFFBHN = 4;
    INHBMHCJJCN FMIGOKIDKJL = 5;
    MOIOKCDLNHE AFHEGGDHAOC = 6;
    DLCNDCKCIPC story_info = 7;
    uint32 DLOJFEEHLIJ = 8;
    KFACLOGFNJF POHEPEEFBOA = 9;
    EGLAPJGFKPN HABJHGPFGEB = 10;
    AEMAPGKPPJA AEFMMOHKCHJ = 11;
    KCHPLCFMGLF EIOHFJMFOKF = 12;
    AGEOGDOGDMM DHEKLJDBNNP = 14;
    EPDDOMFGIMK AJPMADHMGML = 15;
    NEGNNJGLFJP EIIHJJEBKOE = 1116;
}

message DLCNDCKCIPC {
    bool HIFMFMBCODL = 3;
    uint32 JGCCIMMEDIJ = 4;
    repeated uint32 AAFIFEGKACO = 7;
    uint32 HGKBJIAAFPC = 15;
}

message DMGODFDFPEI {
    uint32 AFEMBLFCCCH = 5;
    uint32 MNMJCNOLIII = 14;
}

enum DPBCJGCPMLE {
    DPBCJGCPMLE_PMJGFDCJKML = 0;
    DPBCJGCPMLE_BPGDELOMEKH = 1;
    DPBCJGCPMLE_DNOMGJBOGAD = 2;
    DPBCJGCPMLE_PEIIMIHPEMG = 3;
    DPBCJGCPMLE_KILLHJLIFJD = 4;
    DPBCJGCPMLE_MFDBGOABEKJ = 5;
}

message DPELLHBJGML {
    repeated GKDJBPJOGPO AGIJECGIBGJ = 1;
    EJHDHGGMILA BAGNPGNGLOJ = 3;
    IKCONCOKNAN ONKBPKPOHEC = 5;
    uint32 EPOHKNLFEAB = 6;
    uint32 AAKGDLDFIIE = 9;
    repeated uint32 AADAFLKEJGD = 12;
}

message EHKDAJFLIEI {
    uint32 JAAIADKFPCL = 11;
    uint32 HHFKOOJBOBF = 13;
}

message EJHDHGGMILA {
    LMNCBIDKHLF OLJCAJMFJPO = 1;
    uint32 LGPJLJAMJFJ = 15;
}

message EPDDOMFGIMK {
    int32 OPKEHOLONMJ = 1;
}

message EPHFHKDJKMD {
    uint32 APHIOEALOGI = 7;
    uint32 JGCCIMMEDIJ = 15;
}

message EnterChessRogueAeonRoomCsReq {
}

message EnterChessRogueAeonRoomScRsp {
    MANINNKMFHG stage_info = 6;
    uint32 retcode = 15;
}

enum FILMJJMEBJA {
    FILMJJMEBJA_NLCDGIPGFDJ = 0;
    FILMJJMEBJA_BFADFAELKLJ = 1;
    FILMJJMEBJA_CIHFGJDCHIA = 2;
    FILMJJMEBJA_GMCLFNKAHIM = 3;
}

message FJKGDHKKDFF {
    repeated DMGODFDFPEI JHBFEGDPLJN = 3;
}

message FinishChessRogueSubStoryCsReq {
    uint32 HONCDMKPBEG = 12;
}

message FinishChessRogueSubStoryScRsp {
    uint32 KPDLMKFLJAI = 10;
    uint32 retcode = 11;
    uint32 HONCDMKPBEG = 15;
}

message GAJDPEBBFMG {
    ItemCostData LNIEFKBMIPD = 11;
}

enum GDHLDNFLOOF {
    GDHLDNFLOOF_ADHGHGEFMLG = 0;
    GDHLDNFLOOF_BHOGGJNMHPK = 1;
    GDHLDNFLOOF_HDMDBOMJDDI = 2;
    GDHLDNFLOOF_IGDHFMCJMIL = 3;
    GDHLDNFLOOF_EMJFLBCFONO = 4;
    GDHLDNFLOOF_EHMMIFPLLHM = 5;
}

message GKDJBPJOGPO {
    uint32 IHAOMLEPHOM = 7;
}

message GetChessRogueNousStoryInfoCsReq {
}

message GetChessRogueNousStoryInfoScRsp {
    uint32 retcode = 3;
    repeated PJBODOPJFGA FNKLMMACCMJ = 5;
    repeated BKJCADFCHAB POABJDELNGH = 11;
}

message GetChessRogueStoryAeonTalkInfoCsReq {
    uint32 OEANPIHCHHF = 6;
}

message GetChessRogueStoryAeonTalkInfoScRsp {
    map<uint32, uint32> LDPAJKIEPIP = 4;
    uint32 OEANPIHCHHF = 9;
    uint32 retcode = 14;
}

message GetChessRogueStoryInfoCsReq {
}

message GetChessRogueStoryInfoScRsp {
    repeated CHHBLFHDFEK FNKLMMACCMJ = 1;
    repeated EPHFHKDJKMD POABJDELNGH = 5;
    uint32 retcode = 7;
}

message HGCIAPKELAF {
    uint32 PDFAHEKNHNJ = 2;
    uint32 AHNGMINODKG = 3;
    repeated OCGHBANLLOH LFLFEKEAOCL = 9;
    uint32 MABFMAFCEOA = 13;
}

message HIMJKAMHLMJ {
    repeated uint32 FEBKOJODAAM = 1;
    FJKGDHKKDFF FDEEBBFMBLB = 3;
    MOOKMKEKMKC IOCCACNJIGD = 10;
    LPCINMGGCNI EIIHJJEBKOE = 11;
    repeated uint32 HKCDKHJCNDC = 13;
    DDAFEPBGOHK JCOBJAMPOAL = 15;
}

message IFFEHFHAKCB {
    uint32 avatar_id = 11;
}

message IKCONCOKNAN {
    uint32 ABOHPPHHPEI = 3;
    uint32 GHKDAJNDBBA = 4;
    uint32 height = 5;
    repeated CGMCMAKMJDK CPPCIGMJALM = 13;
    uint32 width = 15;
}

message IOHKFHBGICD {
    ItemList item_list = 6;
}

enum IOJJCDAPLAJ {
    IOJJCDAPLAJ_OLBIJIJCONK = 0;
    IOJJCDAPLAJ_HCFMGBEFBGD = 1;
}

message JECIOGKPHFN {
    repeated uint32 JJHFHLAHLGP = 4;
}

message JKLCLLAFHOC {
    DFKMNLIJMFB MGACFLNJLCK = 2;
    JECIOGKPHFN MKMLKGOOAMK = 10;
}

message KCHPLCFMGLF {
    GAJDPEBBFMG MFEODNJNGDP = 3;
    repeated IFFEHFHAKCB JOLEGACINNK = 10;
}

message KFACLOGFNJF {
    ChessRogueDiceType CEBDDDJMJIJ = 1;
    uint32 DGLIOIEKGNP = 3;
    uint32 DGHEPBKLKDP = 4;
    ChessRogueDiceStatus OACDALINONI = 5;
    uint32 JDLKMDFFMGP = 6;
    bool BGDHHJLICFA = 9;
    uint32 FLADMNIKGEI = 10;
    uint32 BMLMHPPLDDE = 11;
    uint32 EFDMLFGILKK = 12;
    uint32 ONCIOGBKPPI = 13;
    repeated uint32 BDGMPDLBDGN = 813;
    int32 CMDDPMHCALK = 828;
    HGCIAPKELAF GMDKBGODBCB = 1346;
    BMCNDLNONMO OBLADGDFCCN = 1441;
    bool IHCAMLMFAOH = 1832;
    LMNCBIDKHLF BOPGHOPCFHF = 1971;
}

message LKPCDHCKHKP {
    uint32 id = 1;
    uint32 MDAIAMFJNHM = 4;
    uint32 GKDCPNLOLNF = 5;
    uint32 MLLDCLNMIOG = 7;
    int32 EABEFBDOJEO = 11;
    DPELLHBJGML board = 12;
}

message LMNCBIDKHLF {
    repeated BMCNDLNONMO HDLGLFGKONC = 8;
}

message LPCINMGGCNI {
    repeated uint32 KHCANAKMBDJ = 3;
}

message MANINNKMFHG {
    LineupInfo lineup = 2;
    SceneInfo scene = 10;
}

message MCDONFNGMJE {
    oneof CGIFMOFGECO {
        DFKMNLIJMFB MGACFLNJLCK = 9;
        JECIOGKPHFN MKMLKGOOAMK = 14;
        JKLCLLAFHOC LPAAMNFFAIB = 6;
    }
}

message MOIOKCDLNHE {
    repeated uint32 IDCJMPMJHGC = 3;
    repeated uint32 EKNOAJJDPMM = 5;
    bool HIFMFMBCODL = 7;
    bool LKDOGPNPGPF = 8;
    uint32 HONCDMKPBEG = 10;
    uint32 KPDLMKFLJAI = 12;
    repeated uint32 GBLLJKFOIDK = 13;
}

message MOOKMKEKMKC {
    map<uint32, bool> PEGDMOMCFAD = 1;
    repeated HGCIAPKELAF BILCGENIGJM = 5;
    repeated uint32 ADLKMLFOFPF = 6;
}

message NAPFNBJDIOO {
    EHKDAJFLIEI MCGGEAAHBPD = 9;
    IOHKFHBGICD reward_item = 12;
}

message NEGNNJGLFJP {
    repeated uint32 KEHKLHMEABI = 6;
}

message OCGHBANLLOH {
    uint32 AMPFBGKHJBF = 8;
    uint32 dice_slot_id = 11;
}

message OFGJFLCBBJP {
    repeated CGMCMAKMJDK CPPCIGMJALM = 14;
    uint32 EIMFLPNFPGM = 15;
}

message OGHPKFMNNHL {
    APNCCNFJBKO HABJHGPFGEB = 1;
    DPBCJGCPMLE HCPBMIEGDON = 2;
    GMIJHCONFIH DNPCCFFFBHN = 4;
    LineupInfo BJDLGBBPFCK = 5;
    uint32 MMIDEAMEANB = 6;
    uint32 difficulty = 7;
    bool is_finish = 8;
    uint32 KPDLMKFLJAI = 9;
    repeated uint32 AFGFOBPLFIL = 11;
    uint32 HLOCCOOMBGG = 12;
    uint32 OBBGJAFECBE = 13;
    uint32 ADMADHCDHJE = 14;
    ItemList DAKEDPKJMLB = 15;
    uint32 OLMLOEHHFCG = 543;
    uint32 DLOJFEEHLIJ = 711;
    uint32 INNAPIIHJFK = 714;
    uint32 OEGLLHMMBEM = 1036;
    MOIOKCDLNHE AFHEGGDHAOC = 1246;
    uint32 score_id = 1712;
}

message PJBODOPJFGA {
    FILMJJMEBJA status = 2;
    uint32 KPDLMKFLJAI = 7;
}

message PPAGCEGGCAK {
    repeated uint32 FEBKOJODAAM = 5;
    FJKGDHKKDFF FDEEBBFMBLB = 9;
    repeated uint32 HKCDKHJCNDC = 10;
    DDAFEPBGOHK JCOBJAMPOAL = 11;
    LPCINMGGCNI EIIHJJEBKOE = 14;
    MOOKMKEKMKC IOCCACNJIGD = 15;
}

message SelectChessRogueSubStoryScRsp {
    uint32 rogue_dialogue_event_id = 3;
    uint32 retcode = 8;
}

message SyncChessRogueMainStoryFinishScNotify {
    uint32 KPDLMKFLJAI = 2;
}

message SyncChessRogueNousMainStoryScNotify {
    repeated PJBODOPJFGA FNKLMMACCMJ = 10;
}

message SyncChessRogueNousSubStoryScNotify {
    uint32 HONCDMKPBEG = 14;
}

message SyncChessRogueNousValueScNotify {
    EPDDOMFGIMK AJPMADHMGML = 4;
}
