syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AddItemRsp {
    int64 unlock_time = 7;
    ItemList reward = 8;
    oneof FJIANHMABAB {
        uint32 avatar_id = 6;
        uint32 CLEKAKLPNBP = 2;
    }
}

message BLBHACNKKFC {
    uint32 EECIJBLGLNG = 1;
    int32 GALOHJONKCG = 6;
    bool is_win = 9;
    uint32 LEHIGGFKPMN = 11;
    bool is_friend = 12;
}

message BPNGPLHJHBE {
    uint32 retcode = 3;
}

message BuyShopGoodScRsp {
    uint32 retcode = 4;
    repeated NJEBDKOJNGA OPNFOBJOPCB = 11;
}

message CMKMOIGANHN {
    uint32 FPJMKDNDENK = 2;
    uint32 stage_id = 12;
}

enum CmdDiceCombatType {
    CmdDiceCombatType_NLCDGIPGFDJ = 0;
    CmdDiceCombatType_UpgradeAvatarRsp = 9293;
    CmdDiceCombatType_DiceCombatBuyShopGoodCsReq = 9284;
    CmdDiceCombatType_GetDiceCombatShopDataCsReq = 9281;
    CmdDiceCombatType_AGEOJALCOOC = 9279;
    CmdDiceCombatType_GetShopDataScRsp = 9265;
    CmdDiceCombatType_GetSystemDataRsp = 9270;
    CmdDiceCombatType_DiceCombatMainPageRollDiceCsReq = 9274;
    CmdDiceCombatType_GetDiceCombatSystemDataCsReq = 9296;
    CmdDiceCombatType_DiceCombatUpgradeAvatarCsReq = 9267;
    CmdDiceCombatType_AddItemRsp = 9297;
    CmdDiceCombatType_DiceCombatFinishPveStageCsReq = 9273;
    CmdDiceCombatType_NPANIDLBFNM = 9295;
    CmdDiceCombatType_BuyShopGoodScRsp = 9272;
    CmdDiceCombatType_FinishPveStageScRsp = 9269;
    CmdDiceCombatType_V2FinishPveStageScRsp = 9298;
    CmdDiceCombatType_JNPCPMEDCML = 9276;
    CmdDiceCombatType_V2FinishPveStageCsReq = 9278;
    CmdDiceCombatType_ModifyAvatarDiceRsp = 9290;
    CmdDiceCombatType_DiceCombatModifyAvatarDiceCsReq = 9283;
}

message DDKNIMHHNPA {
    repeated LPGJPLMHKFL JDGMEHCPGLL = 5;
    uint32 stage_id = 6;
    bool is_win = 10;
    repeated EHMEPOMCGNG LMPLLJFMFEC = 13;
    uint32 total_score = 15;
}

message DiceCombatBuyShopGoodCsReq {
    uint32 GCPGNLPODDK = 5;
    uint32 PMFNLNMINAP = 8;
}

message DiceCombatFinishPveStageCsReq {
    uint32 ODKEBLADOMK = 9;
    uint32 IBJNBJNDPIK = 10;
    bool EKJIPCEFPOG = 13;
    bool GDNKJDNMILL = 14;
}

message DiceCombatMainPageRollDiceCsReq {
}

message DiceCombatModifyAvatarDiceCsReq {
    uint32 KHIPHMCDNOM = 1;
    uint32 KOEOEHIMOEI = 3;
}

message DiceCombatUpgradeAvatarCsReq {
    uint32 KOEOEHIMOEI = 12;
}

message EHMEPOMCGNG {
    uint32 DBLJFJAAPAN = 1;
    repeated uint32 KBHCLLJLFHH = 2;
}

message FLDKOELBPGA {
    bool DOFNEAPHMKH = 1;
    ItemCostData cost = 3;
    uint32 item_id = 7;
    uint32 KDMNGCLJDOM = 15;
}

message FinishPveStageScRsp {
    uint32 MPDHNFNCIEA = 4;
    bool is_win = 5;
    uint32 retcode = 6;
    ItemList reward = 11;
}

message GetDiceCombatShopDataCsReq {
}

message GetDiceCombatSystemDataCsReq {
}

message GetShopDataScRsp {
    uint32 retcode = 1;
    repeated NJEBDKOJNGA OPNFOBJOPCB = 15;
}

message GetSystemDataRsp {
    repeated DiceCombatAvatar avatar_list = 2;
    repeated uint32 OHFIIBEIPJE = 6;
    uint32 retcode = 9;
    repeated PKENAGKIECB KCNEKEGGAGG = 11;
    PDEIEDGCOBA DGFNLDBFLAJ = 13;
}

message LPGJPLMHKFL {
    uint32 MDKFLGDEJCN = 1;
    repeated uint32 NJIFEDNDMFO = 2;
    uint32 DHJANOFGDNP = 3;
}

message ModifyAvatarDiceRsp {
    uint32 retcode = 4;
    DiceCombatAvatar avatar = 10;
}

message NJEBDKOJNGA {
    repeated FLDKOELBPGA CNFFGBMPCHD = 10;
    uint32 shop_id = 13;
}

message PDEIEDGCOBA {
    repeated uint32 GNNBMNHOIFG = 5;
    repeated CMKMOIGANHN LNPPFHHACPF = 12;
}

message PKENAGKIECB {
    uint32 CLEKAKLPNBP = 10;
    int64 unlock_time = 15;
}

message UpgradeAvatarRsp {
    DiceCombatAvatar avatar = 6;
    uint32 retcode = 15;
}

message V2FinishPveStageCsReq {
    uint32 AELAEGOOBMB = 4;
    uint32 MPDHNFNCIEA = 5;
    uint32 KGHBJELHOBA = 6;
    uint32 FGBIJPLPOBI = 8;
    bool is_win = 12;
    uint32 EOILKCCLEIF = 14;
    bool AINKFEINNAK = 15;
}

message V2FinishPveStageScRsp {
    uint32 retcode = 6;
    uint32 MPDHNFNCIEA = 9;
    bool is_win = 10;
    ItemList reward = 11;
}
