syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdDrinkMakerType {
    CmdDrinkMakerType_NLCDGIPGFDJ = 0;
    CmdDrinkMakerType_MakeChallengeDrinkCsReq = 6995;
    CmdDrinkMakerType_DrinkMakerCheersGetDataScRsp = 6990;
    CmdDrinkMakerType_MakeMissionDrinkScRsp = 6984;
    CmdDrinkMakerType_GetDrinkMakerDataScRsp = 6988;
    CmdDrinkMakerType_NGIDPGJIHCK = 7000;
    CmdDrinkMakerType_GetDrinkMakerDataCsReq = 6998;
    CmdDrinkMakerType_MakeDrinkCsReq = 6983;
    CmdDrinkMakerType_CAIJNLBLKKH = 6986;
    CmdDrinkMakerType_EndDrinkMakerSequenceScRsp = 6997;
    CmdDrinkMakerType_MakeGuideMissionDrinkCsReq = 6985;
    CmdDrinkMakerType_DrinkMakerCheersMakeDrinkScRsp = 6994;
    CmdDrinkMakerType_DrinkMakerUpdateTipsNotify = 6989;
    CmdDrinkMakerType_DrinkMakerCheersEnterNextGroupScRsp = 6999;
    CmdDrinkMakerType_EndDrinkMakerSequenceCsReq = 6982;
    CmdDrinkMakerType_DrinkMakerChallengeScRsp = 6981;
    CmdDrinkMakerType_MakeDrinkScRsp = 6992;
    CmdDrinkMakerType_LAEMBCJFOJI = 6987;
    CmdDrinkMakerType_GetDrinkMakerDayEndScNotify = 6991;
}

message DFJPGILAAON {
    repeated uint32 ECIOKDDBEPN = 4;
    uint32 PDHDOHAIJKD = 6;
    uint32 HCCKHLMLENE = 11;
    uint32 DALCMIELFDD = 12;
    uint32 KMADACHJHJC = 15;
}

message DrinkMakerChallengeScRsp {
    uint32 challenge_id = 9;
    bool KGKEJAKKLDP = 11;
    ItemList reward = 12;
    uint32 retcode = 15;
}

message DrinkMakerCheersEnterNextGroupScRsp {
    uint32 retcode = 1;
    uint32 OLKJPIIKCKP = 9;
}

message DrinkMakerCheersGetDataScRsp {
    uint32 LFNJKNCGNEE = 2;
    repeated LEFIDLICEMH NHFMCMGHADE = 4;
    uint32 retcode = 12;
    uint32 OLKJPIIKCKP = 15;
}

message DrinkMakerCheersMakeDrinkScRsp {
    uint32 retcode = 4;
    LEFIDLICEMH GKBFMPCFFOE = 8;
}

message DrinkMakerUpdateTipsNotify {
    uint32 FHPKJONKHAC = 13;
}

message EndDrinkMakerSequenceCsReq {
}

message EndDrinkMakerSequenceScRsp {
    repeated NACEGIAMJMG ADNJJHNMAAJ = 7;
    uint32 exp = 9;
    uint32 BFHGACCOGJD = 10;
    ItemList reward = 11;
    uint32 FHPKJONKHAC = 12;
    KKIACMJGIKN guest = 13;
    uint32 level = 14;
    uint32 retcode = 15;
}

message GetDrinkMakerDataCsReq {
}

message GetDrinkMakerDataScRsp {
    uint32 retcode = 1;
    uint32 EMIAIOMOLPO = 2;
    repeated uint32 CJKAGEDKAFL = 3;
    uint32 level = 4;
    uint32 FGBELHJAKCC = 6;
    repeated KKIACMJGIKN ONFNEDNFOLL = 7;
    DFJPGILAAON LMOGDPMLKFH = 8;
    uint32 FHPKJONKHAC = 11;
    uint32 day = 12;
    uint32 exp = 13;
}

message GetDrinkMakerDayEndScNotify {
    uint32 HBJIJHHMEGO = 10;
}

message KKIACMJGIKN {
    repeated uint32 OBJOLNOJIKC = 2;
    uint32 OHPIDOOJDHJ = 12;
    uint32 JOIKIENJNJI = 13;
}

message LEFIDLICEMH {
    DFJPGILAAON AGCBLNPHFCI = 1;
    uint32 MJJMPMCCNJH = 2;
    repeated uint32 LNCKEHDMHLD = 9;
    bool MHNDLPIDJIE = 13;
}

message MakeDrinkCsReq {
    uint32 FGBELHJAKCC = 7;
    DFJPGILAAON AGCBLNPHFCI = 13;
}

message MakeDrinkScRsp {
    bool KGKEJAKKLDP = 7;
    uint32 retcode = 12;
    uint32 LEJDBHMPBBG = 13;
}

message MakeMissionDrinkScRsp {
    uint32 retcode = 1;
    bool KGKEJAKKLDP = 7;
    DFJPGILAAON LMOGDPMLKFH = 11;
    bool is_save = 12;
}

message NACEGIAMJMG {
    uint32 CJGGHHCILMD = 1;
    bool KGKEJAKKLDP = 7;
}
