syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message ChangeEraFlipperDataCsReq {
    KKFMGCNDHGH data = 1;
}

enum CmdEraFlipperType {
    CmdEraFlipperType_NLCDGIPGFDJ = 0;
    CmdEraFlipperType_ChangeEraFlipperDataCsReq = 6562;
    CmdEraFlipperType_GKOKHIOBJDM = 6559;
    CmdEraFlipperType_DDFCEHMLIAL = 6571;
    CmdEraFlipperType_HBIJLNGMBIB = 6557;
    CmdEraFlipperType_DANCIMOJIJM = 6555;
    CmdEraFlipperType_DDHFJFAKPCB = 6565;
    CmdEraFlipperType_OPAIFJPGJKA = 6568;
    CmdEraFlipperType_EnterEraFlipperDataCsReq = 6569;
    CmdEraFlipperType_GetEraFlipperDataCsReq = 6558;
}

message DMICEOCOGAD {
    KKFMGCNDHGH data = 1;
    uint32 floor_id = 2;
}

message EnterEraFlipperDataCsReq {
    uint32 state = 5;
    uint32 region_id = 15;
}

message GetEraFlipperDataCsReq {
}

message HKLDDAAECLN {
    uint32 state = 8;
    uint32 region_id = 15;
}

message KKFMGCNDHGH {
    repeated HKLDDAAECLN DMDKAOOLABF = 14;
}
