syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ACNKOPCGKDD {
    uint32 max_score = 7;
    uint32 FAGLNMDFOME = 8;
    uint32 level_id = 14;
}

message CJJHNFICDIM {
    uint32 exp = 2;
    repeated HLOADNFIOOO JBOJBAGKIAE = 3;
    repeated ACNKOPCGKDD POFJCCBEBGA = 4;
    repeated LMMLGKHALLA HHFAAFOBKME = 5;
    repeated uint32 HNOCFELOAFJ = 8;
    uint32 item_value = 10;
    repeated uint32 BHAOHNCEAJM = 11;
}

enum CmdEvolveBuildType {
    CmdEvolveBuildType_MMNFGNKHNLL = 0;
    CmdEvolveBuildType_EvolveBuildStartLevelScRsp = 7144;
    CmdEvolveBuildType_GetEvolveBuildShopAbilityResetScRsp = 7118;
    CmdEvolveBuildType_EvolveBuildShopAbilityDownCsReq = 7114;
    CmdEvolveBuildType_EvolveBuildSkipTeachLevelCsReq = 7126;
    CmdEvolveBuildType_EvolveBuildReRandomStageCsReq = 7120;
    CmdEvolveBuildType_GetEvolveBuildCoinNotify = 7143;
    CmdEvolveBuildType_GetEvolveBuildQueryInfoScRsp = 7123;
    CmdEvolveBuildType_EvolveBuildGiveupCsReq = 7103;
    CmdEvolveBuildType_GetEvolveBuildGiveupScRsp = 7107;
    CmdEvolveBuildType_EvolveBuildShopAbilityUpCsReq = 7106;
    CmdEvolveBuildType_GetEvolveBuildShopAbilityUpScRsp = 7102;
    CmdEvolveBuildType_GetEvolveBuildShopAbilityDownScRsp = 7135;
    CmdEvolveBuildType_EvolveBuildSkipTeachLevelScRsp = 7145;
    CmdEvolveBuildType_EvolveBuildStartStageCsReq = 7119;
    CmdEvolveBuildType_GetEvolveBuildFinishScNotify = 7124;
    CmdEvolveBuildType_EvolveBuildStartStageScRsp = 7148;
    CmdEvolveBuildType_EvolveBuildQueryInfoCsReq = 7109;
    CmdEvolveBuildType_EvolveBuildStartLevelCsReq = 7137;
    CmdEvolveBuildType_GetEvolveBuildReRandomStageScRsp = 7117;
    CmdEvolveBuildType_EvolveBuildShopAbilityResetCsReq = 7108;
}

enum EDJKFOBBDJF {
    EDJKFOBBDJF_PCIHNGDCFAL = 0;
    EDJKFOBBDJF_CNLOJEFOHII = 1;
    EDJKFOBBDJF_IABFOPFPILL = 2;
}

message EHPLFHLNMIF {
    AvatarType avatar_type = 4;
    double damage = 7;
    uint32 avatar_id = 15;
}

message EvolveBuildSkipTeachLevelCsReq {
    uint32 level_id = 6;
}

message EvolveBuildSkipTeachLevelScRsp {
    uint32 level_id = 3;
    uint32 retcode = 7;
}

message EvolveBuildStartLevelCsReq {
    DKPHAFPGDLO NENJBDBJNFI = 2;
    uint32 level_id = 5;
    repeated EHPLFHLNMIF avatar_list = 7;
}

message EvolveBuildStartLevelScRsp {
    uint32 retcode = 11;
    LDLCMMOPKNG OEIBHLMDJKA = 15;
}

message EvolveBuildStartStageCsReq {
    uint32 level_id = 12;
}

message EvolveBuildStartStageScRsp {
    SceneBattleInfo AEPNEDJPAGK = 1;
    uint32 retcode = 3;
    LDLCMMOPKNG OEIBHLMDJKA = 13;
}

message GOMKGHJBNFM {
    uint32 level = 5;
    uint32 JEKLOEPPJBK = 9;
}

message GetEvolveBuildCoinNotify {
    uint32 item_value = 11;
    EDJKFOBBDJF HFPEJIDDDJG = 13;
}

message GetEvolveBuildFinishScNotify {
    LDLCMMOPKNG OEIBHLMDJKA = 2;
    uint32 wave = 3;
    uint32 level_id = 4;
    uint32 score_id = 5;
    uint32 item_value = 9;
    bool NLMAFMCFHAL = 10;
    uint32 exp = 13;
    IAPIIEJHLMP APKKKEIPJOG = 15;
}

message GetEvolveBuildGiveupScRsp {
    LDLCMMOPKNG OEIBHLMDJKA = 2;
    uint32 retcode = 8;
}

message GetEvolveBuildQueryInfoScRsp {
    repeated LDLCMMOPKNG JPDOIGJNGNP = 3;
    uint32 retcode = 6;
    CJJHNFICDIM CFDIKLBINHK = 9;
}

message GetEvolveBuildReRandomStageScRsp {
    uint32 retcode = 9;
    HLOADNFIOOO GMBPFFIABHJ = 15;
}

message GetEvolveBuildShopAbilityDownScRsp {
    uint32 JEKLOEPPJBK = 1;
    uint32 retcode = 12;
    uint32 level = 14;
}

message GetEvolveBuildShopAbilityResetScRsp {
    repeated GOMKGHJBNFM CEPCGLMFPBC = 7;
    EDJKFOBBDJF HFPEJIDDDJG = 11;
    uint32 retcode = 13;
    uint32 item_value = 14;
}

message GetEvolveBuildShopAbilityUpScRsp {
    uint32 JEKLOEPPJBK = 4;
    uint32 retcode = 12;
    uint32 level = 15;
}

message HLOADNFIOOO {
    repeated uint32 DCKIGAHCNMJ = 2;
    uint32 level_id = 6;
    bool FANPGKBLIOB = 11;
}

enum IAPIIEJHLMP {
    IAPIIEJHLMP_BFNCMBCKDHK = 0;
    IAPIIEJHLMP_GNDJPIHJCFF = 1;
    IAPIIEJHLMP_BNHFLKDCHOJ = 2;
    IAPIIEJHLMP_INHGFENMDFN = 3;
    IAPIIEJHLMP_HPDBIFBGHBD = 4;
}

message LDLCMMOPKNG {
    EDJKFOBBDJF HFPEJIDDDJG = 2;
    repeated EHPLFHLNMIF avatar_list = 3;
    uint32 DJHHPKMHPBC = 5;
    uint32 round_cnt = 6;
    repeated BattleTarget battle_target_list = 8;
    BattleGridFightSpecialBattleInfo battle_info = 11;
    repeated uint32 DCKIGAHCNMJ = 15;
}

message LMMLGKHALLA {
    uint32 item_value = 6;
    EDJKFOBBDJF HFPEJIDDDJG = 8;
    repeated GOMKGHJBNFM CEPCGLMFPBC = 15;
}
