syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ACAKOLCGDLL {
    uint32 MDIIJKBHBBI = 1;
    bool GPPHKPEHKIM = 8;
    uint32 NPGFNBPFMKI = 11;
    uint32 KKCKMCDGCGK = 12;
    repeated NOHPJFOGFLM NMJIOGGNLEO = 13;
}

message AGFGGFBNOJC {
    uint32 AMMPOLONOBC = 6;
    uint32 level = 11;
}

message ALEEDHCDIAL {
}

message BAEDIBFGLDE {
    LABMFHEEPBI AJFHKPNGPDB = 2;
    repeated GHFEKEGEFAC JJHMEHGELNO = 9;
    repeated FHCIIMGMIML DLCGPENPMNK = 10;
}

message BMJDDOLALFI {
    uint32 count = 1;
    uint32 ENBEGMDIFKN = 4;
}

message CEKMLMOCLHF {
    ItemList KKDJMIMHNAE = 6;
    map<uint32, ItemList> JOCFFLKPNOL = 9;
    uint32 LOPNADHJKBF = 10;
    uint32 IHAOMLEPHOM = 15;
}

message CLBNCPOFNPB {
    uint32 GELLJOJMEFP = 1;
    uint32 AOOLKNMJLNI = 7;
    uint32 MCGHFJCBBMK = 15;
}

enum CmdElfRestaurantType {
    CmdElfRestaurantType_NLCDGIPGFDJ = 0;
    CmdElfRestaurantType_EnterElfRestaurantNextDayCsReq = 2587;
    CmdElfRestaurantType_ElfRestaurantFinishTradeOrderScRsp = 2589;
    CmdElfRestaurantType_DNHPFOOEPLE = 2567;
    CmdElfRestaurantType_LCFDIHFAGHA = 2583;
    CmdElfRestaurantType_KGLPEMOFKEF = 2574;
    CmdElfRestaurantType_CGIKAANCBEP = 2559;
    CmdElfRestaurantType_SettleElfRestaurantPlayScRsp = 2593;
    CmdElfRestaurantType_HPKGGLPLHMD = 2556;
    CmdElfRestaurantType_ElfRestaurantClientStatusCsReq = 2586;
    CmdElfRestaurantType_ElfRestaurantBuyFieldScRsp = 2557;
    CmdElfRestaurantType_ElfRestaurantUpgradeFacilityLevelCsReq = 2585;
    CmdElfRestaurantType_OGCDAOELHCB = 2568;
    CmdElfRestaurantType_ElfRestaurantTakeVillagerRewardScRsp = 2592;
    CmdElfRestaurantType_EnterElfRestaurantNextDayScRsp = 2594;
    CmdElfRestaurantType_BPOKCCBFKGF = 2572;
    CmdElfRestaurantType_GetElfRestaurantDataScRsp = 2573;
    CmdElfRestaurantType_ElfRestaurantUpgradeFacilityLevelScRsp = 2565;
    CmdElfRestaurantType_ElfRestaurantFinishTradeOrderCsReq = 2595;
    CmdElfRestaurantType_AGLGOEMGMHL = 2558;
    CmdElfRestaurantType_ElfRestaurantDataChangeNotify = 2598;
    CmdElfRestaurantType_ElfRestaurantBuyShopItemCsReq = 2590;
    CmdElfRestaurantType_ElfRestaurantUpgradeEmployeeLevelScRsp = 2564;
    CmdElfRestaurantType_ElfRestaurantUpgradeRecipeLevelCsReq = 2563;
    CmdElfRestaurantType_ElfRestaurantPlantSeedScRsp = 2571;
    CmdElfRestaurantType_ElfRestaurantBuyFieldCsReq = 2553;
    CmdElfRestaurantType_ElfRestaurantRecycleSeedScRsp = 2579;
    CmdElfRestaurantType_ElfRestaurantTakeVillagerRewardCsReq = 2597;
    CmdElfRestaurantType_LEIKNDKAJLH = 2580;
    CmdElfRestaurantType_ElfRestaurantHarvestCropScRsp = 2570;
    CmdElfRestaurantType_ElfRestaurantUpgradeRecipeLevelScRsp = 2576;
    CmdElfRestaurantType_ElfRestaurantUpgradeEmployeeLevelCsReq = 2552;
    CmdElfRestaurantType_SetElfRestaurantPlayRecipeScRsp = 2582;
    CmdElfRestaurantType_ICEJBAGGOJP = 2560;
}

message ECGKEKKAHGN {
    uint32 LOPNADHJKBF = 5;
    uint32 IHAOMLEPHOM = 6;
    ItemList FEANLLOCFBA = 15;
}

message EEAGACLNDFN {
    uint32 LOPNADHJKBF = 10;
}

message ENDIDPAKMGF {
    uint32 retcode = 4;
}

message ElfRestaurantBuyShopItemCsReq {
    uint32 ICAILDEHHBN = 3;
    uint32 ICNCMMEEJKM = 14;
}

message ElfRestaurantDataChangeNotify {
    repeated HGMJFBCFJFN DGNGMJMPFGK = 13;
}

message ElfRestaurantFinishTradeOrderCsReq {
    uint32 BFADNHJAJBJ = 9;
}

message ElfRestaurantFinishTradeOrderScRsp {
    uint32 BFADNHJAJBJ = 4;
    ItemCostData FKMFHAAJMMF = 8;
    uint32 retcode = 12;
    ItemList GLAPKNMCIBI = 13;
}

message ElfRestaurantHarvestCropScRsp {
    uint32 retcode = 10;
    repeated CEKMLMOCLHF LGPOMBCJPKL = 13;
}

message ElfRestaurantPlantSeedScRsp {
    uint32 retcode = 6;
    repeated NKEGPAOCGCJ FPEBFLJMEJL = 9;
}

message ElfRestaurantRecycleSeedScRsp {
    repeated ECGKEKKAHGN HDAMNMCDHLH = 7;
    uint32 retcode = 13;
}

message ElfRestaurantTakeVillagerRewardCsReq {
}

message ElfRestaurantTakeVillagerRewardScRsp {
    uint32 retcode = 7;
    repeated PLOHACFCDKF DJOBNPIAEJP = 10;
}

message FCEEHNOJAAN {
    ItemCostData FKMFHAAJMMF = 5;
    uint32 retcode = 7;
}

message FHCIIMGMIML {
    uint32 AOOLKNMJLNI = 9;
    uint32 level = 15;
}

message GHFEKEGEFAC {
    uint32 level = 3;
    uint32 OMFGAABELHE = 10;
}

message GHNLNAAAOLG {
    uint32 retcode = 15;
}

message GOOJIJDPKIP {
    uint32 retcode = 2;
}

message GetElfRestaurantDataScRsp {
    uint32 retcode = 2;
    BAEDIBFGLDE OENLJGEBCGA = 4;
    OMPLEKGNLBC FFKCMKJFFCM = 5;
    ACAKOLCGDLL IBHKOKEEMOI = 8;
    IILBDJMKELG MILCHKIIEJE = 12;
    ICABANFEIHJ AHCEIMGNBNM = 13;
}

message HCBCPFNMMMI {
    uint32 OMFGAABELHE = 3;
    uint32 IGOOJKMPMDC = 5;
}

message HCGNKJHKJMM {
    uint32 AOOLKNMJLNI = 2;
    uint32 IGOOJKMPMDC = 6;
}

message HGMJFBCFJFN {
    oneof ENDDAHPBCKJ {
        ACAKOLCGDLL JNBFIBDKLGB = 4;
        OBDBODNJACD LEMCGNHLOOI = 10;
        AGFGGFBNOJC NEFHJPJALGO = 12;
        uint32 EDGOIFOOBMH = 7;
        GHFEKEGEFAC HINKDPMAICB = 5;
        FHCIIMGMIML MOCNALBMLLI = 9;
        MOOGIHHBHFG MFAJAPGACPA = 14;
        uint32 FDLGKNFIPMG = 8;
        LGFLGGDMAGD HMGKHCNMDDJ = 3;
        uint32 KMHMAKDFKLB = 15;
        bool PCKLCAEDJPC = 13;
        LABMFHEEPBI HGPMMEHONLD = 11;
    }
}

message ICABANFEIHJ {
    repeated MOOGIHHBHFG LCJFDCHINHL = 5;
    repeated LGFLGGDMAGD NILEKCAGIMK = 13;
}

message IILBDJMKELG {
    repeated AGFGGFBNOJC FGJHNNPOGGF = 9;
}

message IJBBCKPNPAF {
    uint32 retcode = 12;
}

message JFMKFJJCDKN {
    uint32 retcode = 5;
}

message LABMFHEEPBI {
    repeated BMJDDOLALFI ELJEBPIOKDD = 3;
    repeated CLBNCPOFNPB FGJIAMOOIIG = 4;
    repeated uint32 JEENJPHNBLI = 6;
    uint64 FEKHNEKHAAK = 7;
    repeated uint32 FFEILKDLABH = 9;
    uint32 DFELFGNJGDP = 13;
    uint32 JFBOMKNCNIE = 14;
}

message LGFLGGDMAGD {
    uint32 BEIJKGPGFFE = 6;
    uint32 BFADNHJAJBJ = 9;
}

message MFIJFCEAKHA {
    bool is_active = 7;
}

message MOOGIHHBHFG {
    uint32 LMGFEGDNCHP = 3;
    uint32 ICNCMMEEJKM = 6;
    uint32 BEIJKGPGFFE = 13;
}

message NJMHBEAAOOC {
    uint32 retcode = 11;
}

message NKEGPAOCGCJ {
    uint32 LOPNADHJKBF = 2;
    ItemCostData FKMFHAAJMMF = 7;
    uint32 IHAOMLEPHOM = 10;
}

message NOHPJFOGFLM {
    uint32 JJIJBJDKNAE = 5;
    uint32 progress = 7;
}

message OBDBODNJACD {
    uint32 LIHAHPDCIKL = 5;
    bool MEBMAMHHGMD = 7;
    bool JFAPNIECBKO = 8;
    uint32 LOPNADHJKBF = 9;
    uint32 BLNHCIBKJOM = 11;
    uint32 IHAOMLEPHOM = 14;
}

message OCKGMNGKIEE {
    uint32 AMMPOLONOBC = 4;
    uint32 IGOOJKMPMDC = 14;
}

message OMPLEKGNLBC {
    repeated OBDBODNJACD FMCGHNLBIKP = 1;
    bool PCKLCAEDJPC = 5;
    repeated uint32 KPMKNBNOAFP = 15;
}

message PLOHACFCDKF {
    ItemList reward_list = 1;
    uint32 progress = 8;
    uint32 OCJKDCPANJM = 9;
    uint32 MMMADINMHFB = 15;
}

message PNOENKFAKEK {
    uint32 retcode = 6;
    ItemCostData FKMFHAAJMMF = 7;
}
