syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdElationActivityType {
    CmdElationActivityType_NLCDGIPGFDJ = 0;
    CmdElationActivityType_ElationActivityBattleEndScNotify = 9104;
    CmdElationActivityType_EnterElationActivityStageCsReq = 9103;
    CmdElationActivityType_EnterElationActivityStageScRsp = 9105;
    CmdElationActivityType_GetActivityElationDataCsReq = 9110;
    CmdElationActivityType_GetElationActivityDataScRsp = 9101;
}

message ElationActivityAvatar {
    AvatarType avatar_type = 1;
    uint32 avatar_id = 12;
}

message ElationActivityBattleEndScNotify {
    uint32 JCFMCEPKEHA = 2;
    uint32 JIGFPIOBAHB = 4;
    uint32 level_id = 6;
    uint32 perfect_wave = 13;
    ElationActivityLevelData level_data = 15;
}

message ElationActivityLevelData {
    bool is_perfect = 5;
    uint32 level_id = 7;
    uint32 BOEINFJIILE = 10;
    uint32 CHPCJIBGKFK = 12;
    uint32 FFGFINDLMCF = 14;
}

message EnterElationActivityStageCsReq {
    repeated ElationActivityAvatar player_selected_avatar_list = 1;
    repeated ElationActivityAvatar fixed_avatar_list = 9;
    uint32 level_id = 12;
}

message EnterElationActivityStageScRsp {
    SceneBattleInfo battle_info = 1;
    uint32 retcode = 6;
    uint32 level_id = 7;
}

message GetElationActivityDataScRsp {
    uint32 retcode = 3;
    repeated ElationActivityLevelData level_data_list = 6;
}
