syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AcceptMultipleExpeditionScRsp {
    repeated ItemList DJOBNPIAEJP = 4;
    uint32 retcode = 10;
    repeated ExpeditionInfo accept_multi_expedition = 12;
    int64 BJMGDBCHEAN = 15;
}

enum CmdExpeditionType {
    CmdExpeditionType_NLCDGIPGFDJ = 0;
    CmdExpeditionType_OLCHGINAEIG = 2514;
    CmdExpeditionType_GetExpeditionDataCsReq = 2509;
    CmdExpeditionType_TakeMultipleExpeditionRewardScRsp = 2535;
    CmdExpeditionType_DFJDNLNFKLG = 2510;
    CmdExpeditionType_GetExpeditionDataScRsp = 2523;
    CmdExpeditionType_ECHFAEDEFLG = 2506;
    CmdExpeditionType_AcceptMultipleExpeditionScRsp = 2502;
}

message ExpeditionInfo {
    uint32 id = 6;
}

message GetExpeditionDataCsReq {
}

message GetExpeditionDataScRsp {
    uint32 retcode = 1;
    int64 BJMGDBCHEAN = 9;
    repeated ExpeditionInfo expedition_info = 11;
    repeated uint32 CAALNNFJIAH = 14;
    uint32 total_expedition_count = 15;
}

message HKCILGGEEFM {
    repeated ExpeditionInfo expedition_info = 1;
    repeated uint32 CAALNNFJIAH = 5;
    uint32 total_expedition_count = 9;
    int64 BJMGDBCHEAN = 13;
}

message TakeMultipleExpeditionRewardScRsp {
    uint32 retcode = 1;
    repeated ItemList DJOBNPIAEJP = 3;
    int64 BJMGDBCHEAN = 5;
    repeated uint32 NPCMKBNJABA = 10;
}
