syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message COMJKPOMILA {
    uint32 server_tick = 3;
    bytes LNBKFFIDEEJ = 6;
    uint64 server_time_ms = 10;
    uint32 OMFPICKPOCP = 12;
}

enum CmdFightType {
    CmdFightType_NLCDGIPGFDJ = 0;
    CmdFightType_OBLJAHGJMKL = 30081;
    CmdFightType_PNHBCILHNJC = 30078;
    CmdFightType_EHGEBECOEJO = 30088;
    CmdFightType_GeneralNotify = 30013;
    CmdFightType_MGKEDPLBGEM = 30047;
    CmdFightType_INICAJCFINI = 30025;
    CmdFightType_DGAFIEGABBG = 30093;
    CmdFightType_APKLPCMGJNL = 30026;
    CmdFightType_CCBKEMOFOBB = 30086;
}

message FEMJLEMCEFD {
    uint32 GCOPDPOLECJ = 7;
}

message ICKLANINJDB {
    uint32 OMFPICKPOCP = 3;
    bytes LNBKFFIDEEJ = 9;
    uint32 retcode = 11;
}

message IMKKKJFHEIO {
    uint64 server_time_ms = 1;
    uint64 client_time_ms = 9;
    uint32 retcode = 13;
}

message JEOILKKMKCN {
    uint32 retcode = 8;
    uint64 secret_key_seed = 9;
    uint32 MLKLBJJHGIO = 11;
    uint64 server_timestamp_ms = 14;
}

message OOCNBNHOICI {
    BFBHKJLJJBJ KAEDKFOMADJ = 11;
}
