syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdFeverTimeActivityType {
    CmdFeverTimeActivityType_NLCDGIPGFDJ = 0;
    CmdFeverTimeActivityType_EnterFeverTimeActivityStageScRsp = 7151;
    CmdFeverTimeActivityType_ActivityFeverTimeModuleInitCsReq = 7155;
    CmdFeverTimeActivityType_EnterFeverTimeActivityStageCsReq = 7160;
    CmdFeverTimeActivityType_FeverTimeActivityBattleEndScNotify = 7153;
    CmdFeverTimeActivityType_GetFeverTimeActivityDataScRsp = 7154;
}

message EnterFeverTimeActivityStageCsReq {
    repeated KPNHGDGLICN avatar_list = 2;
    uint32 id = 5;
    uint32 CJHDABDKGHP = 8;
    uint32 MFLAIMHFABP = 11;
}

message EnterFeverTimeActivityStageScRsp {
    uint32 retcode = 2;
    uint32 id = 7;
    SceneBattleInfo battle_info = 13;
}

message FeverTimeActivityBattleEndScNotify {
    uint32 id = 3;
    uint32 turn_left = 9;
    FeverTimeBattleRank LDDHCPLNKKA = 12;
    uint32 FAJDFFHODIP = 13;
}

enum FeverTimeBattleRank {
    NNNPOIJENJC_PICLIGEAJFN = 0;
    NNNPOIJENJC_OGPNODHENKN = 1;
    NNNPOIJENJC_JPDBDLEEHGK = 2;
    NNNPOIJENJC_BMHMMIMOAIJ = 3;
    NNNPOIJENJC_DCGAPNGCCEH = 4;
}

message GetFeverTimeActivityDataScRsp {
    uint32 retcode = 9;
    repeated JBMJOIPJPLH GNDEFEAEDNJ = 15;
}

message JBMJOIPJPLH {
    uint32 DJFGDMIDEHJ = 4;
    uint32 OFBEDJIAEOA = 8;
    FeverTimeBattleRank OINGNAJMFNL = 9;
}
