syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdFantasticStoryActivityType {
    CmdFantasticStoryActivityType_NLCDGIPGFDJ = 0;
    CmdFantasticStoryActivityType_GetFantasticStoryActivityDataScRsp = 4978;
    CmdFantasticStoryActivityType_EnterFantasticStoryActivityStageScRsp = 4988;
    CmdFantasticStoryActivityType_KFNLNJMBIEL = 4993;
    CmdFantasticStoryActivityType_EnterActivityFantasticStoryCsReq = 4958;
    CmdFantasticStoryActivityType_FantasticStoryActivityBattleEndScNotify = 4981;
    CmdFantasticStoryActivityType_GetFantasticStoryActivityDataCsReq = 4925;
}

message EPMJEKOHNME {
    GCFDJCPFOGG ONIEMLICONB = 8;
}

message EnterFantasticStoryActivityStageScRsp {
    SceneBattleInfo battle_info = 2;
    uint32 battle_id = 10;
    uint32 OFHBPNGDEGO = 11;
    uint32 retcode = 13;
}

message FGGCEKHFPLH {
    repeated uint32 buff_list = 6;
    repeated PKCIPJBKAFO avatar_list = 7;
}

message FantasticStoryActivityBattleEndScNotify {
    uint32 battle_id = 3;
    uint32 FHBNGHINHOG = 8;
    uint32 OFHBPNGDEGO = 10;
}

message GCFDJCPFOGG {
    repeated uint32 HPLNHIFHBMA = 2;
    uint32 OFHBPNGDEGO = 3;
    repeated uint32 DJJKDGEFOIP = 5;
    map<uint32, uint32> DLBOJCCDCFI = 6;
    repeated uint32 FIBFIKOBDPG = 10;
    map<uint32, FGGCEKHFPLH> DALPAKHCKLI = 11;
    repeated uint32 JJOBBOHHOMG = 15;
}

message GetFantasticStoryActivityDataCsReq {
    uint32 OFHBPNGDEGO = 14;
}

message GetFantasticStoryActivityDataScRsp {
    uint32 retcode = 2;
    GCFDJCPFOGG ONIEMLICONB = 4;
}

message PKCIPJBKAFO {
    AvatarType avatar_type = 8;
    uint32 avatar_id = 11;
}
