syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum ABLCCPHIOMI {
    ABLCCPHIOMI_KFIKMPOPBFD = 0;
    ABLCCPHIOMI_MCOJHEKMHIL = 1;
    ABLCCPHIOMI_GJGNJHPOFOL = 2;
    ABLCCPHIOMI_JONELAAFDEA = 3;
    ABLCCPHIOMI_DMBKGPBNBPO = 4;
    ABLCCPHIOMI_NGBOPLGBCNK = 5;
}

message AJOHOIGMCNN {
    IPGIJFNAFLC LLCPOHADBKB = 2;
    uint32 use_item_id = 7;
    uint32 retcode = 12;
}

enum AMDMKHKOHNF {
    AMDMKHKOHNF_CCLMEHJMPGC = 0;
    AMDMKHKOHNF_FDEAJLPGEOJ = 1;
    AMDMKHKOHNF_KNHNJMABEBB = 2;
    AMDMKHKOHNF_EGLAFFEKPHG = 3;
    AMDMKHKOHNF_LMBDFFBHDOK = 4;
    AMDMKHKOHNF_DPFACDOOILN = 5;
}

message BCMGFCDNAIE {
    uint32 retcode = 3;
}

message BHMEPBAGOFF {
    uint64 FIKHCEBOPMI = 1;
    int32 HIJJDGBOMDL = 3;
    repeated KLGJDILNNDH BFCGOELLNIP = 4;
    uint32 PBEPLKMNAKF = 5;
    uint32 NAOKGNGBHAO = 6;
    AMDMKHKOHNF cur_state = 10;
    IPGIJFNAFLC KNBGBCEBLDF = 12;
}

message BMBCNFKFABK {
    JECNOELJLKO data = 6;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 9;
    uint32 retcode = 12;
}

message CBDJAJAKCFF {
    uint32 retcode = 4;
}

enum CKGOFMFNIPP {
    CKGOFMFNIPP_HGBBGFBCCJJ = 0;
    CKGOFMFNIPP_MLJFKFACNND = 1;
    CKGOFMFNIPP_NNAMMGLFFCG = 2;
    CKGOFMFNIPP_OBLIOOOLFEE = 3;
    CKGOFMFNIPP_FAIALBOJMFN = 4;
    CKGOFMFNIPP_BMJKLMCDPLG = 5;
}

enum CmdFightMatch3Type {
    CmdFightMatch3Type_NHGDFLDLJLJ = 0;
    CmdFightMatch3Type_BEJKIFPOMME = 30158;
    CmdFightMatch3Type_AEMOIILIOIF = 30133;
    CmdFightMatch3Type_CFIDMGINPBI = 30181;
    CmdFightMatch3Type_MJOKFFEPILP = 30113;
    CmdFightMatch3Type_JMOMMLOOHDN = 30140;
    CmdFightMatch3Type_MJKIMBELELE = 30148;
    CmdFightMatch3Type_LAEHKICDGPJ = 30165;
    CmdFightMatch3Type_GNDGJMDGMMH = 30145;
    CmdFightMatch3Type_HBHIODOPENH = 30125;
    CmdFightMatch3Type_OHBILNLDEDC = 30180;
    CmdFightMatch3Type_JAMEPLPKJBB = 30139;
    CmdFightMatch3Type_EDHOJDAAGJL = 30126;
    CmdFightMatch3Type_FLJEDMOIGKA = 30169;
    CmdFightMatch3Type_ACKOCKCIPKK = 30147;
    CmdFightMatch3Type_JMACKKAMDEO = 30138;
    CmdFightMatch3Type_LNLLFEJNCGA = 30178;
    CmdFightMatch3Type_AFHJPABICCP = 30172;
    CmdFightMatch3Type_PMNOPHNLGJF = 30171;
    CmdFightMatch3Type_JGFBBLBJFJK = 30104;
    CmdFightMatch3Type_HPJLBKOHFCG = 30186;
    CmdFightMatch3Type_MOHONNNIKGF = 30142;
    CmdFightMatch3Type_ACLHDGALAIL = 30188;
    CmdFightMatch3Type_HKHFGEMOEMK = 30184;
    CmdFightMatch3Type_GBPLKHLHFDB = 30111;
    CmdFightMatch3Type_FCNHMPMPNPA = 30130;
    CmdFightMatch3Type_KKJGIAKPBCI = 30136;
    CmdFightMatch3Type_OKIKFPKCPEN = 30193;
}

message DFLIHGGNBDB {
    uint32 EDIGEANPBNL = 4;
    uint32 row = 15;
}

enum DIKCFAICOHB {
    DIKCFAICOHB_EJDLGGAGBEA = 0;
    DIKCFAICOHB_PINPGFJKDPH = 1;
    DIKCFAICOHB_EMPKDJGKDBI = 2;
    DIKCFAICOHB_AOIOAKGHGHG = 3;
    DIKCFAICOHB_ECEHHJJGFED = 4;
    DIKCFAICOHB_GHBHAPNLJEJ = 5;
}

message DLBGONGJBNC {
    uint32 FMEHKPKHGJA = 6;
    uint32 DGGCFDKJDPO = 9;
    uint32 ODFEDCPLNEM = 10;
    uint32 PNGHFKLCNBE = 12;
}

message DPDDOADGCMG {
    uint32 NAOKGNGBHAO = 2;
    repeated LPHCHEJEMPD BFCGOELLNIP = 3;
}

message EAGCPEPIOIO {
    JECNOELJLKO data = 9;
}

enum FDICBBEGKEO {
    FDICBBEGKEO_NLCDGIPGFDJ = 0;
    FDICBBEGKEO_EHNBEPDHBKC = 1;
    FDICBBEGKEO_CBLMHGEJLMP = 2;
    FDICBBEGKEO_NHEMIPGKGCJ = 3;
}

enum FNCFIHAFGGN {
    FNCFIHAFGGN_NLCDGIPGFDJ = 0;
    FNCFIHAFGGN_HBHCKEGINEN = 1;
    FNCFIHAFGGN_DDJCFCLNCIM = 2;
}

message FOJDKLCHCKG {
    int32 HIJJDGBOMDL = 1;
    IFFKDFPJECM cur_state = 4;
    repeated LPHCHEJEMPD BFCGOELLNIP = 8;
    IPGIJFNAFLC KNBGBCEBLDF = 10;
    uint32 NAOKGNGBHAO = 12;
    uint64 FIKHCEBOPMI = 14;
}

message GBFDMFJKOOP {
    NHHJAONHDDG state = 3;
    uint32 hp = 5;
    uint32 IFOCJCOCDBH = 11;
    uint32 score_id = 12;
    uint32 BPBMJBIDIIC = 13;
    repeated DLBGONGJBNC item_list = 15;
}

message GBMPOBJDAFF {
    FOJDKLCHCKG KHEFAHCPHBL = 4;
    DIKCFAICOHB reason = 14;
}

message GMGABLBKJMC {
    uint32 param = 13;
    FDICBBEGKEO buff_type = 14;
}

message GODEELLFLEN {
    JECNOELJLKO JMIOMLJDCNN = 3;
    JECNOELJLKO ENJMGOJPNOE = 12;
}

message IEOGEDFAELP {
    JECNOELJLKO EHIELLKLPCK = 3;
}

enum IFFKDFPJECM {
    IFFKDFPJECM_KFDDOBPEJMF = 0;
    IFFKDFPJECM_DOJNFGNKFGP = 1;
    IFFKDFPJECM_BBCFLEDLBBB = 2;
    IFFKDFPJECM_GOIMMOHGCIH = 3;
    IFFKDFPJECM_ADJOCBGIJHP = 4;
}

message IPGIJFNAFLC {
    repeated MNOOMFIAFPF op_list = 1;
    uint32 LIKMIMCFPKC = 2;
    uint32 FHEFKOGAMHK = 3;
    uint32 DJJODJAAIGA = 4;
    uint32 IGDOFKLAILH = 5;
    uint32 score_id = 6;
    repeated uint32 MNCPGDNOIAM = 7;
    uint32 cur_hp = 8;
    LAJGLHCCNED JDFPKAMFHAP = 9;
    repeated DLBGONGJBNC item_list = 10;
    NHHJAONHDDG LHNIIOHNIFL = 11;
    uint32 JJJBLAJDEDC = 13;
    uint32 energy_info = 14;
    repeated GMGABLBKJMC buff_list = 15;
}

message JBILGCPCJOD {
    uint32 OPHFDHGBLPJ = 1;
    bool BKFONKNLCHP = 3;
    NHHJAONHDDG state = 4;
    repeated DLBGONGJBNC item_list = 6;
    uint32 score_id = 8;
    uint32 IFOCJCOCDBH = 9;
    uint32 DHJANOFGDNP = 10;
    uint32 rank = 14;
    uint32 hp = 15;
}

message JECNOELJLKO {
    repeated uint32 LPOPKEGOLHB = 1;
    uint32 BPBMJBIDIIC = 3;
    int32 HIJJDGBOMDL = 5;
    uint64 FIKHCEBOPMI = 7;
    repeated JBILGCPCJOD BFCGOELLNIP = 8;
    PFPHJFEGDAA cur_state = 11;
    IPGIJFNAFLC KNBGBCEBLDF = 14;
}

message JFJDMGOMJOF {
    ABLCCPHIOMI JNIEIKOKBGK = 1;
    IPGIJFNAFLC KGOCFEINBIN = 12;
}

message KINFINGMICK {
    uint32 PIFNIJHPLJC = 4;
    uint32 OBJCJGPIHAD = 8;
}

message KLGJDILNNDH {
    NHHJAONHDDG LHNIIOHNIFL = 1;
    uint32 score_id = 2;
    bool OCLBMMNNMFC = 3;
    repeated DLBGONGJBNC item_list = 4;
    uint32 OPHFDHGBLPJ = 5;
    LAJGLHCCNED JDFPKAMFHAP = 6;
    uint32 FHEFKOGAMHK = 7;
    uint32 energy_info = 9;
    uint32 DHJANOFGDNP = 12;
    bool ANMLAPADELO = 13;
    uint32 IGDOFKLAILH = 15;
}

message LGEOFJJKFNF {
    CKGOFMFNIPP reason = 2;
    BHMEPBAGOFF data = 13;
}

message LLFIKHHPJEB {
    repeated LMLNNHKJEIP DFLEOIGPLNM = 4;
    BHMEPBAGOFF data = 7;
    uint32 retcode = 13;
}

message LNGLLJKNKHG {
    uint32 EAFFACCBAAA = 1;
    uint32 retcode = 8;
    IPGIJFNAFLC IHBOHKKCGCP = 11;
    bool BDCNNNNLLHJ = 14;
}

message LPHCHEJEMPD {
    NHHJAONHDDG state = 1;
    uint32 rank = 2;
    uint32 DHJANOFGDNP = 4;
    uint32 score_id = 7;
}

message MHLMFDBFCEC {
    uint32 PIFNIJHPLJC = 11;
    uint32 retcode = 15;
}

message MNOOMFIAFPF {
    FNCFIHAFGGN op_type = 2;
    uint32 MPKCANFHCHG = 8;
}

enum NHHJAONHDDG {
    NHHJAONHDDG_LCNJHOKLMPN = 0;
    NHHJAONHDDG_OFGBFHHIFAM = 1;
    NHHJAONHDDG_JJBEPKLOLCP = 2;
    NHHJAONHDDG_OPCKNBHNBOA = 3;
}

message NMOMCMJOFGG {
    JECNOELJLKO data = 3;
}

message OJLHCIDDFDF {
    IPGIJFNAFLC LLCPOHADBKB = 5;
    OKIPFIENKIF PBAPICNDIDN = 15;
}

message OKIPFIENKIF {
    DFLIHGGNBDB GGCMCDDGEIB = 2;
    repeated JFJDMGOMJOF DGKLOCJHKNH = 13;
    DFLIHGGNBDB OPMGDNNAEJF = 14;
    uint32 EAFFACCBAAA = 15;
}

message OPAOIBLFJOM {
    IPGIJFNAFLC LLCPOHADBKB = 1;
    PKBDAKMLDMC PBAPICNDIDN = 2;
}

enum PFPHJFEGDAA {
    PFPHJFEGDAA_HGFFCFFBGDB = 0;
    PFPHJFEGDAA_FOFLFMBMOMA = 1;
    PFPHJFEGDAA_DHHGMKAOALN = 2;
    PFPHJFEGDAA_CGKCEONNAGM = 3;
    PFPHJFEGDAA_MJLCFPEKNPA = 4;
    PFPHJFEGDAA_NAIHAJOLEID = 5;
}

message PKBDAKMLDMC {
    repeated DFLIHGGNBDB GNABNEDKPHH = 2;
    uint32 MMLNAMPFAKA = 5;
    uint32 use_item_id = 11;
    repeated JFJDMGOMJOF DGKLOCJHKNH = 13;
}

message PKBJOGHCFOA {
    FOJDKLCHCKG KHEFAHCPHBL = 5;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 14;
    uint32 retcode = 15;
}
