syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum BGLIMCBGLAJ {
    BGLIMCBGLAJ_PICLIGEAJFN = 0;
    BGLIMCBGLAJ_OGPNODHENKN = 1;
    BGLIMCBGLAJ_JPDBDLEEHGK = 2;
    BGLIMCBGLAJ_BMHMMIMOAIJ = 3;
    BGLIMCBGLAJ_DCGAPNGCCEH = 4;
}

enum CmdFightFestType {
    CmdFightFestType_NLCDGIPGFDJ = 0;
    CmdFightFestType_GetFightFestDataScRsp = 7273;
    CmdFightFestType_FightFestUpdateCoinNotify = 7257;
    CmdFightFestType_FightFestUpdateChallengeRecordNotify = 7253;
    CmdFightFestType_StartFightFestScRsp = 7294;
    CmdFightFestType_FightFestScoreUpdateNotify = 7269;
    CmdFightFestType_JNIBHGOJJMD = 7287;
    CmdFightFestType_FightFestUnlockSkillNotify = 7298;
    CmdFightFestType_FightFestInitCsReq = 7259;
}

message EPCNGNEEMBI {
    AvatarType avatar_type = 4;
    uint32 id = 14;
}

message FightFestScoreUpdateNotify {
    uint32 JODNMFEFPFD = 7;
    uint32 score_id = 11;
}

enum FightFestType {
    OGOJLBNJKCN_NLCDGIPGFDJ = 0;
    OGOJLBNJKCN_IBAADNINFCG = 1;
    OGOJLBNJKCN_score_id = 2;
    OGOJLBNJKCN_OCDLPDDMCLP = 3;
    OGOJLBNJKCN_HNGBFGALLBI = 4;
}

message FightFestUnlockSkillNotify {
    uint32 AMAGKDCBFGL = 11;
}

message FightFestUpdateChallengeRecordNotify {
    BGLIMCBGLAJ HMBBBNKAILD = 1;
    uint32 challenge_id = 4;
    BGLIMCBGLAJ rank = 10;
    uint32 DJFGDMIDEHJ = 13;
    uint32 turn_left = 15;
}

message FightFestUpdateCoinNotify {
    uint32 item_value = 3;
}

message GetFightFestDataScRsp {
    repeated uint32 GILJLEOAOMA = 6;
    uint32 score_id = 7;
    uint32 retcode = 8;
    repeated LPJOINCGBBP challenge_list = 10;
    uint32 item_value = 15;
}

message LPJOINCGBBP {
    uint32 DJFGDMIDEHJ = 1;
    BGLIMCBGLAJ OINGNAJMFNL = 4;
    uint32 challenge_id = 5;
}

message StartFightFestScRsp {
    uint32 id = 2;
    FightFestType type = 4;
    uint32 retcode = 7;
    SceneBattleInfo battle_info = 9;
    uint32 event_id = 15;
}
