syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AddBlacklistCsReq {
    uint32 uid = 3;
}

message AddBlacklistScRsp {
    PlayerSimpleInfo black_info = 3;
    uint32 retcode = 13;
}

message ApplyFriendCsReq {
    FriendApplySource source = 13;
    uint32 uid = 15;
}

message ApplyFriendScRsp {
    uint32 uid = 10;
    uint32 retcode = 14;
}

message BGPIHMLLNGM {
    NMFEHEHPGAB HJFHOEAAGGC = 1;
    OIMLMDHOHAP MHAIBAMJGIM = 9;
    FKCNEPIJJAO BFGELCKJJPN = 11;
    GLILLENEIJK ENDLJENKBMF = 12;
}

message BMKNANGPDGH {
    uint32 passed_level = 10;
    uint32 EMOHLJHPOPC = 12;
    repeated ONKDAPOKGAC avatar_list = 15;
}

enum BattleRecordType {
    BATTLE_RECORD_NONE = 0;
    BATTLE_RECORD_CHALLENGE = 1;
    BATTLE_RECORD_ROGUE = 2;
}

message CFNEMEIDMID {
    uint32 area_id = 2;
    uint32 HOLPMKOHACH = 9;
}

message CJNDCNIJBEI {
    repeated uint32 finished_target_list = 9;
    repeated ONKDAPOKGAC avatar_list = 15;
}

message ChallengePeakBossFriendLineupRecommendation {
    uint32 buff_id = 3;
    bool hard_mode_has_passed = 7;
    repeated ONKDAPOKGAC avatar_list = 9;
    bool is_hard_mode = 12;
    repeated uint32 finished_target_list = 15;
}

enum CmdFriendType {
    CmdFriendType_NLCDGIPGFDJ = 0;
    CmdFriendType_AKADDIDOLDF = 2966;
    CmdFriendType_GetAssistListCsReq = 2905;
    CmdFriendType_NewAssistHistoryNotify = 2973;
    CmdFriendType_DeleteBlacklistCsReq = 2972;
    CmdFriendType_GetFriendApplyListInfoScRsp = 2981;
    CmdFriendType_ApplyFriendScRsp = 2947;
    CmdFriendType_JNFFKMIDDEL = 2969;
    CmdFriendType_SetFriendMarkScRsp = 2914;
    CmdFriendType_GetFriendListInfoCsReq = 2925;
    CmdFriendType_GetFriendRecommendListInfoCsReq = 2948;
    CmdFriendType_PMJNLHJILGP = 2930;
    CmdFriendType_GetFriendBattleRecordDetailScRsp = 2928;
    CmdFriendType_HandleFriendCsReq = 2913;
    CmdFriendType_FEHDAKLPDBO = 2920;
    CmdFriendType_GetAssistHistoryCsReq = 2934;
    CmdFriendType_CurAssistChangedNotify = 2975;
    CmdFriendType_GetCurAssistCsReq = 2929;
    CmdFriendType_DeleteFriendCsReq = 2933;
    CmdFriendType_AddBlacklistCsReq = 2904;
    CmdFriendType_SyncDeleteFriendScNotify = 2939;
    CmdFriendType_SyncApplyFriendScNotify = 2926;
    CmdFriendType_BHNEEJDGEIA = 2953;
    CmdFriendType_GetFriendBattleRecordDetailCsReq = 2919;
    CmdFriendType_DeleteFriendScRsp = 2938;
    CmdFriendType_GetFriendRecommendLineupDetailScRsp = 2906;
    CmdFriendType_GetFriendDevelopmentInfoCsReq = 2998;
    CmdFriendType_GetCurAssistScRsp = 2963;
    CmdFriendType_JLHNNKPFGHI = 2984;
    CmdFriendType_SyncHandleFriendScNotify = 2940;
    CmdFriendType_SetAssistScRsp = 2943;
    CmdFriendType_SetFriendRemarkNameScRsp = 2965;
    CmdFriendType_ReportPlayerScRsp = 2942;
    CmdFriendType_AddBlacklistScRsp = 2911;
    CmdFriendType_GetFriendRecommendListInfoScRsp = 2945;
    CmdFriendType_SyncAddBlacklistScNotify = 2936;
    CmdFriendType_SetForbidOtherApplyFriendScRsp = 2952;
    CmdFriendType_GetAssistListScRsp = 2941;
    CmdFriendType_TakeAssistRewardScRsp = 2935;
    CmdFriendType_ApplyFriendCsReq = 2986;
    CmdFriendType_FNMNFKNAHIE = 2912;
    CmdFriendType_GetAssistHistoryScRsp = 2996;
    CmdFriendType_MJGEIGCCACO = 2910;
    CmdFriendType_GetPlatformPlayerInfoCsReq = 2944;
    CmdFriendType_GetPlayerDetailInfoCsReq = 2993;
    CmdFriendType_GetPlayerDetailInfoScRsp = 2958;
    CmdFriendType_BOBEBFMFNPE = 2915;
    CmdFriendType_GetFriendListInfoScRsp = 2978;
    CmdFriendType_GetFriendAssistListScRsp = 2982;
    CmdFriendType_GCPPDCPKNGL = 2916;
    CmdFriendType_GetFriendAssistListCsReq = 2989;
    CmdFriendType_GetFriendLoginInfoScRsp = 2918;
    CmdFriendType_DeleteBlacklistScRsp = 2980;
    CmdFriendType_GetFriendApplyListInfoCsReq = 2988;
    CmdFriendType_GetPlatformPlayerInfoScRsp = 2949;
    CmdFriendType_HandleFriendScRsp = 2971;
    CmdFriendType_GetFriendDevelopmentInfoScRsp = 2962;
    CmdFriendType_SearchPlayerScRsp = 2921;
    CmdFriendType_GetFriendRecommendLineupScRsp = 2955;
}

message CurAssistChangedNotify {
    PlayerAssistInfo ODHMGPNECFO = 4;
}

message DBFHOCOBPMK {
    repeated PlayerChallengePeakRecordMobData HDCHFBKDCEB = 8;
    PlayerChallengePeakRecordBossData CDFFIGJLGMM = 14;
    uint32 group_id = 15;
}

message DeleteBlacklistCsReq {
    uint32 uid = 14;
}

message DeleteBlacklistScRsp {
    uint32 retcode = 1;
    uint32 uid = 5;
}

message DeleteFriendCsReq {
    uint32 uid = 6;
    uint32 LMHDOMCMGNL = 9;
}

message DeleteFriendScRsp {
    uint32 uid = 2;
    uint32 retcode = 14;
}

enum DevelopmentType {
    KMJKPKLCPNM_BEEHIFFKOIH = 0;
    KMJKPKLCPNM_FJMKBHBKDNG = 1;
    KMJKPKLCPNM_OMMMLICONEG = 2;
    KMJKPKLCPNM_LMDJOBNEFFL = 3;
    KMJKPKLCPNM_CMAPLLHGPOF = 4;
    KMJKPKLCPNM_AOCOLEGAICP = 5;
    KMJKPKLCPNM_LODAGLNGOKA = 6;
    KMJKPKLCPNM_OCOKANBLFMA = 7;
    KMJKPKLCPNM_GPCJDNIHAGB = 8;
    KMJKPKLCPNM_LMAAEEHHJNC = 9;
    KMJKPKLCPNM_HEJAOMEJGKJ = 10;
    KMJKPKLCPNM_PHKEACMKMAA = 11;
    KMJKPKLCPNM_MPHKBCGINLC = 12;
    KMJKPKLCPNM_NPAIBBCODOH = 13;
    KMJKPKLCPNM_BIAIKCLDIFD = 14;
    KMJKPKLCPNM_FCIBLPLMEMI = 15;
    KMJKPKLCPNM_JAEMAKHBNHD = 16;
    KMJKPKLCPNM_LDPOJOODFEH = 17;
    KMJKPKLCPNM_ODDKNGFCBKO = 18;
}

message DisplayAvatarDetailInfo {
    uint32 enhanced_id = 1;
    uint32 rank = 2;
    uint32 pos = 3;
    uint32 dressed_skin_id = 5;
    repeated AvatarSkillTree skilltree_list = 6;
    uint32 exp = 7;
    DisplayEquipmentInfo equipment = 8;
    repeated DisplayRelicInfo relic_list = 9;
    uint32 avatar_type = 11;
    uint32 promotion = 12;
    uint32 avatar_id = 13;
    uint32 level = 14;
}

message DisplayEquipmentInfo {
    uint32 exp = 5;
    uint32 promotion = 9;
    uint32 level = 11;
    uint32 tid = 12;
    uint32 rank = 15;
}

message DisplayRelicInfo {
    uint32 exp = 3;
    repeated RelicAffix sub_affix_list = 4;
    uint32 level = 8;
    uint32 tid = 9;
    uint32 main_affix_id = 13;
    uint32 type = 14;
}

message EDEGAHHANMF {
    uint32 MBHJNPEILCL = 1;
    uint32 PLKAGMLBCDG = 2;
    uint32 OPENPJJLADD = 7;
    uint32 IGENPDKHDMC = 12;
    uint32 LCDDMLIMAGA = 15;
}

message EJAKBKOEEPC {
    JMOCDMHFEJG BHDKLAJPMBJ = 14;
}

message FKCNEPIJJAO {
    uint32 area_id = 3;
    uint32 FEFLAJIODHB = 9;
    uint32 DCOKLHPBAJO = 10;
    uint32 JNCCOGCHNMB = 11;
}

message FPDCINMDJCE {
    PlayerSimpleInfo player_info = 6;
    string remark_name = 7;
    oneof KJFEKHDEBIK {
        FriendChallengeLineup NHMOPCHJEHN = 11;
        CJNDCNIJBEI BNAFKMMLGFE = 12;
        MJMGDLJAJCM LMHIOKFMDNE = 2;
        ChallengePeakBossFriendLineupRecommendation KCNAHJCMNJI = 5;
        OJJJDPNOKHG NHKCFOALAPD = 15;
        OFFMDBMMNFM KPPDEMBPEDO = 1403;
    }
}

message FriendApplyInfo {
    int64 apply_time = 5;
    PlayerSimpleInfo player_info = 10;
}

enum FriendApplySource {
    HPEKGMDHFLO_NLCDGIPGFDJ = 0;
    HPEKGMDHFLO_GODCHGIMIAJ = 1;
    HPEKGMDHFLO_BLNBLLNHICH = 2;
    HPEKGMDHFLO_ODHMGPNECFO = 3;
    HPEKGMDHFLO_OBPHECNLKAP = 4;
    HPEKGMDHFLO_OKJJPJKLIOG = 5;
    HPEKGMDHFLO_OGCABAGJIIK = 6;
    HPEKGMDHFLO_CGMPJEGGEED = 7;
    HPEKGMDHFLO_JGFGNCLKIBO = 8;
    HPEKGMDHFLO_MKHLALNLOLA = 9;
    HPEKGMDHFLO_CILGIDDHODG = 10;
}

message FriendChallengeClearanceInfo {
    uint32 LMPPDGOFOMF = 4;
    PlayerChallengeTierceRecord MEGBIPBAFBP = 11;
    uint32 group_id = 14;
    oneof EDKOHAAMONH {
        ChallengeStatistics challenge_default = 1338;
        ChallengeStoryStatistics challenge_story = 651;
        ChallengeBossStatistics challenge_boss = 1920;
    }
}

message FriendChallengeLineup {
    PlayerSimpleInfo player_info = 2;
    repeated ChallengeLineupList lineup_list = 3;
    uint32 score_id = 6;
    uint32 buff_two = 9;
    string remark_name = 10;
    uint32 buff_one = 12;
    uint32 EEJCPNAEKLJ = 14;
}

message FriendGridFightRecord {
    uint32 division_id = 14;
}

message FriendRecommendInfo {
    bool JINLAHLMDLN = 1;
    PlayerSimpleInfo player_info = 10;
}

message FriendSimpleInfo {
    PlayingState playing_state = 1;
    string remark_name = 2;
    int64 create_time = 3;
    bool is_marked = 9;
    PAEFDELFKJK MBOIHJLIJDG = 10;
    PlayerSimpleInfo player_info = 14;
}

message GLILLENEIJK {
    uint32 GNIFODGCPAA = 8;
    uint32 FFFNGBKHOEA = 14;
}

message GetAssistHistoryCsReq {
}

message GetAssistHistoryScRsp {
    uint32 LLIPLPNDIMC = 3;
    uint32 OFEKHCHHOFD = 4;
    uint32 retcode = 12;
    uint32 EFONJLMDFIH = 15;
}

message GetAssistListCsReq {
    bool LKBAENBKJCE = 2;
    bool DDNKHDIKAEL = 12;
}

message GetAssistListScRsp {
    uint32 retcode = 3;
    repeated PlayerAssistInfo assist_list = 12;
}

message GetCurAssistCsReq {
}

message GetCurAssistScRsp {
    PlayerAssistInfo ODHMGPNECFO = 2;
    uint32 retcode = 8;
}

message GetFriendApplyListInfoCsReq {
}

message GetFriendApplyListInfoScRsp {
    repeated uint32 send_apply_list = 2;
    uint32 retcode = 6;
    repeated FriendApplyInfo receive_apply_list = 9;
}

message GetFriendAssistListCsReq {
    bool DDNKHDIKAEL = 1;
    repeated uint32 EEJGCFBJKAK = 5;
    repeated uint32 HHFPJHMEIJK = 6;
    PIDAHABFLBL HFOLAOIKOLB = 9;
    uint32 target_side = 10;
}

message GetFriendAssistListScRsp {
    uint32 target_side = 1;
    uint32 retcode = 2;
    repeated PlayerAssistInfo assist_list = 4;
}

message GetFriendBattleRecordDetailCsReq {
    uint32 uid = 8;
}

message GetFriendBattleRecordDetailScRsp {
    repeated FriendChallengeClearanceInfo EPNLMHPCDKL = 5;
    uint32 retcode = 9;
    BGPIHMLLNGM HCIEFEHCENO = 10;
    repeated DBFHOCOBPMK LGIBJLFBFCG = 11;
    uint32 uid = 12;
    HBJDMDKKMFI BAMDEHAICDA = 14;
}

message GetFriendDevelopmentInfoCsReq {
    uint32 uid = 2;
}

message GetFriendDevelopmentInfoScRsp {
    repeated NJMOBNILIHI EMBPENNEIJH = 2;
    uint32 uid = 7;
    uint32 retcode = 10;
}

message GetFriendListInfoCsReq {
}

message GetFriendListInfoScRsp {
    repeated PlayerSimpleInfo black_list = 2;
    uint32 retcode = 11;
    repeated FriendSimpleInfo friend_list = 15;
}

message GetFriendLoginInfoScRsp {
    bool show_red_dot_flag = 6;
    bool is_allow_other_apply = 8;
    uint32 retcode = 13;
}

message GetFriendRecommendLineupDetailScRsp {
    uint32 key = 2;
    uint32 retcode = 3;
    repeated DisplayAvatarDetailInfo KNHHAJDNGJG = 4;
    JFNJKAPPNOF type = 7;
    uint32 uid = 14;
}

message GetFriendRecommendLineupScRsp {
    uint32 key = 1;
    uint32 retcode = 6;
    repeated FPDCINMDJCE MGKCKHIIICL = 11;
    bool ALDBIIIGLOM = 14;
    JFNJKAPPNOF type = 15;
}

message GetFriendRecommendListInfoCsReq {
    bool DDNKHDIKAEL = 4;
}

message GetFriendRecommendListInfoScRsp {
    repeated FriendRecommendInfo friend_recommend_list = 4;
    uint32 retcode = 9;
}

message GetPlatformPlayerInfoCsReq {
    repeated string EPIBJAMIJFI = 10;
    PlatformType platform = 11;
}

message GetPlatformPlayerInfoScRsp {
    repeated PlayerSimpleInfo friend_recommend_list = 7;
    uint32 retcode = 9;
}

message GetPlayerDetailInfoCsReq {
    uint32 uid = 8;
}

message GetPlayerDetailInfoScRsp {
    PlayerDetailInfo detail_info = 1;
    uint32 retcode = 7;
}

message HBJDMDKKMFI {
    uint32 division_id = 10;
}

message HHJANNIGCKM {
    bool EGLLMGLLHDL = 5;
    repeated uint32 finished_target_list = 12;
}

message HandleFriendCsReq {
    bool is_accept = 4;
    uint32 uid = 6;
}

message HandleFriendScRsp {
    uint32 retcode = 2;
    bool is_accept = 3;
    uint32 uid = 8;
    FriendSimpleInfo friend_info = 12;
}

message ICMGDJBDFEA {
    uint32 LMPPDGOFOMF = 5;
    HHJANNIGCKM NCKJLAEJNDP = 6;
    uint32 group_id = 9;
    uint32 max_level = 11;
    uint32 FBOGDAHNDKA = 14;
}

message IENCCMEAIAJ {
    uint32 GNIFODGCPAA = 11;
}

message JBKJGBMMKFI {
    uint32 peak_id = 2;
}

enum JFNJKAPPNOF {
    JFNJKAPPNOF_NLCDGIPGFDJ = 0;
    JFNJKAPPNOF_OCDLPDDMCLP = 1;
    JFNJKAPPNOF_JHOEBNNMKHB = 2;
    JFNJKAPPNOF_KMDNDLKKDLH = 3;
    JFNJKAPPNOF_DJKDPGDLLFM = 4;
    JFNJKAPPNOF_IGDNEOELFKC = 5;
    JFNJKAPPNOF_HCBNCEDBABL = 6;
}

message JMOCDMHFEJG {
    PIBFIDOEPAP KGBHIKKLJMK = 10;
}

message KGBAFBEMICB {
    uint32 AACGBEBGDPE = 3;
    bool MNDCIBFEJOP = 5;
}

message KHFEGOFPHHC {
    uint32 area_id = 14;
}

message LJJIEAPLOOI {
    uint32 division_id = 4;
}

message MJMGDLJAJCM {
    repeated OKFKPPNGCOD DNIGKDKIPPJ = 7;
}

message MOOGABJBJAG {
    uint32 challenge_id = 7;
}

message NJMOBNILIHI {
    DevelopmentType NELHEHHFCCM = 3;
    int64 time = 10;
    oneof NNMAOMHPNBK {
        KHFEGOFPHHC DCODKLADIJM = 668;
        MOOGABJBJAG ELJOEBBHDPB = 1259;
        uint32 avatar_id = 712;
        uint32 KAJCFPKEGBP = 1411;
        CFNEMEIDMID IIBJEGJMOKJ = 1610;
        uint32 panel_id = 1857;
        JBKJGBMMKFI AGKKAFEFGOB = 1662;
        IENCCMEAIAJ IMILIFMDLBI = 1446;
        LJJIEAPLOOI BNNDODHIKCE = 1595;
        KGBAFBEMICB DHKCMBFCALH = 244;
    }
}

message NMFEHEHPGAB {
    uint32 MGCACGFLKEK = 3;
    uint32 area_id = 6;
    uint32 MBDKAJBEPPF = 10;
}

message NewAssistHistoryNotify {
    uint32 OFEKHCHHOFD = 9;
}

message OFFMDBMMNFM {
    repeated BMKNANGPDGH lineup_list = 9;
}

message OHKDPNBGPOA {
    bool MAKOLELFLFH = 2;
    bool DCJECFMMIBC = 3;
    bool GNFDDPEMMFN = 5;
    bool PFBHGAHAFMD = 8;
    bool IOJEAOCOBBF = 11;
}

message OIMLMDHOHAP {
    uint32 IELFOBFPDPA = 2;
    uint32 APANPLBMONN = 5;
    uint32 area_id = 9;
    uint32 KPHJDOPBMEN = 10;
}

message OJJJDPNOKHG {
    repeated uint32 finished_target_list = 4;
    repeated ChallengeLineupList lineup_list = 7;
    repeated uint32 AOLIEDBCNBN = 8;
}

message OKFKPPNGCOD {
    uint32 peak_id = 8;
    repeated ONKDAPOKGAC avatar_list = 9;
    repeated uint32 finished_target_list = 15;
}

message ONKDAPOKGAC {
    AvatarType avatar_type = 1;
    uint32 id = 2;
    uint32 level = 3;
    uint32 index = 4;
    uint32 skin_id = 5;
}

message PAEFDELFKJK {
    BattleRecordType display_type = 3;
    FriendGridFightRecord BAMDEHAICDA = 7;
    EJAKBKOEEPC KBLKLGDCOMF = 8;
    ICMGDJBDFEA AMLDHBMIGEN = 11;
}

message PIBFIDOEPAP {
    uint32 GNIFODGCPAA = 9;
    uint32 FFFNGBKHOEA = 14;
}

enum PIDAHABFLBL {
    PIDAHABFLBL_ONGOHDOKEIE = 0;
    PIDAHABFLBL_FJBENKPGBPP = 1;
    PIDAHABFLBL_IBNPGEDFIMO = 2;
}

message PlayerAssistInfo {
    PlayerSimpleInfo player_info = 10;
    DisplayAvatarDetailInfo assist_avatar = 12;
}

message PlayerChallengePeakRecordBossData {
    uint32 DJFGDMIDEHJ = 2;
    bool HAMDKIHGKGO = 5;
    repeated uint32 MCJNLLBBDHN = 7;
    uint32 peak_id = 9;
    uint32 buff_id = 10;
    uint32 best_cycle_count = 13;
    bool CFLDOMPACKI = 14;
    ChallengeLineupList lineup = 15;
}

message PlayerChallengePeakRecordMobData {
    uint32 cycles_used = 5;
    ChallengeLineupList lineup = 11;
    repeated uint32 MCJNLLBBDHN = 12;
    uint32 peak_id = 14;
}

message PlayerDetailInfo {
    bool is_banned = 1;
    string DJONELMIFEE = 2;
    uint32 head_icon = 3;
    string signature = 4;
    uint32 HCGMAGDFAAO = 5;
    string IJKOMIKFKEK = 6;
    uint32 uid = 7;
    bool HIEAPDNNNEI = 8;
    repeated DisplayAvatarDetailInfo display_avatar_list = 9;
    PlayerRecordInfo record_info = 10;
    uint32 world_level = 11;
    uint32 GEJFMBBHNLN = 12;
    PlatformType platform = 13;
    string nickname = 14;
    uint32 level = 15;
    uint32 gender = 230;
    uint32 KINOEHKMFML = 649;
    repeated DisplayAvatarDetailInfo assist_avatar_list = 880;
    CJLCPMDGIBO DHKFCDAGHDM = 1096;
    OIIPJFDNPAH AIHNDIAFGPM = 1159;
    OHKDPNBGPOA BOKLABGLEFL = 1414;
    HeadFrameInfo head_frame_info = 1703;
}

message PlayerRecordInfo {
    EDEGAHHANMF EOGGPDHKKBJ = 4;
    uint32 JJKIKOBAJLF = 5;
    uint32 MIMECEAFDNK = 7;
    uint32 PPFDDFAHLED = 8;
    uint32 DIOIIFAHAKK = 9;
    uint32 NECKJBHEKHE = 10;
    uint32 MHOIJFEBAPA = 11;
    uint32 KCBINJNIBNO = 14;
    uint32 ALGEOLGNFBL = 15;
}

enum PlayingState {
    PLAYING_STATE_NONE = 0;
    PLAYING_ROGUE_COSMOS = 1;
    PLAYING_ROGUE_CHESS = 2;
    PLAYING_ROGUE_CHESS_NOUS = 3;
    PLAYING_CHALLENGE_MEMORY = 4;
    PLAYING_CHALLENGE_STORY = 5;
    PLAYING_CHALLENGE_BOSS = 6;
    PLAYING_ROGUE_TOURN = 7;
    PLAYING_ROGUE_MAGIC = 8;
    PLAYING_CHALLENGE_PEAK = 9;
    DIHJILNECAD_OAILFPOOBMJ = 10;
}

message ReportPlayerScRsp {
    uint32 retcode = 15;
}

message SearchPlayerScRsp {
    repeated PlayerSimpleInfo simple_info_list = 2;
    repeated uint32 result_uid_list = 13;
    uint32 retcode = 14;
}

message SetAssistScRsp {
    uint32 retcode = 9;
    uint32 avatar_id = 11;
    uint32 uid = 15;
}

message SetForbidOtherApplyFriendScRsp {
    bool PBNJDHFCHHC = 4;
    uint32 retcode = 10;
}

message SetFriendMarkScRsp {
    bool BIJJOJNJHDO = 4;
    uint32 retcode = 6;
    uint32 uid = 15;
}

message SetFriendRemarkNameScRsp {
    uint32 retcode = 4;
    string remark_name = 8;
    uint32 uid = 12;
}

message SyncAddBlacklistScNotify {
    uint32 uid = 4;
}

message SyncApplyFriendScNotify {
    FriendApplyInfo friend_apply_info = 3;
}

message SyncDeleteFriendScNotify {
    uint32 uid = 15;
}

message SyncHandleFriendScNotify {
    bool is_accept = 2;
    FriendSimpleInfo friend_info = 6;
    uint32 uid = 13;
}

message TakeAssistRewardScRsp {
    repeated KAODLPJMEFE OILHLECGBCH = 2;
    uint32 retcode = 4;
    ItemList reward = 13;
}
