syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AFANKKDMIHC {
    KAOPGJBGEBF MGMPDHKJFIM = 12;
}

message AFKJKLJJLKN {
    uint32 PJLEJKEOFII = 1;
}

message AGPKFBLGDIH {
    repeated ActiveTraitSourceList KBGAPHFIPJF = 2;
    uint32 trait_id = 15;
}

message AHOMAAHPCIG {
    repeated uint32 DAPJMJMGCFC = 5;
    repeated uint32 EKJDLEFFGHD = 11;
}

message ANJBJLDMDFN {
    uint32 unique_id = 4;
}

message ANNFOAGBJBP {
    repeated MJLJMCCGNEE BLFMGKPNPGG = 3;
}

message ActiveTraitSourceList {
    uint32 cnt = 3;
    FJKMGCKMNNA source = 4;
}

message BDJEGABKNHN {
    map<uint32, uint32> ICAOKNPHKGN = 5;
    repeated uint32 PPHEKHLLFHC = 9;
}

message BFBCEOICLAB {
    ENJDEFHFKPI IEMEKMDDIOI = 1;
    repeated KAOPGJBGEBF LNNGKPAJKLP = 2;
    NBBHDPCPHNN MHALEIHFKLG = 3;
    uint32 difficulty = 5;
    repeated KLMNGOJKEIN FELMAMPGMAE = 7;
    uint32 area_id = 8;
    PJFDAOKIKOJ CCOPDLOKAAE = 9;
    EMFDLPNOGOH status = 10;
    JIMNPPNNHEL EFLLPHLDBPC = 11;
    JFKAOMCJIKK FMIGOKIDKJL = 12;
    KCLHMJHIDOB LMLDELGBJOO = 13;
    uint32 GBMBGHAPDMG = 15;
    ANNFOAGBJBP CMCBGGKLBCF = 706;
    IBGFKJMMICI GODPEHNPPCO = 978;
}

message BGNIMFMFKLH {
    FJKMGCKMNNA source = 13;
    map<uint32, double> OPEMKBPFFDN = 14;
}

message CLNABFMHFFH {
    uint32 avatar_id = 10;
    bool BKFONKNLCHP = 12;
}

enum CmdFateType {
    CmdFateType_NLCDGIPGFDJ = 0;
    CmdFateType_FateHandlePendingActionScRsp = 5965;
    CmdFateType_FKFCAKBEJFD = 5993;
    CmdFateType_FateBattleStartScRsp = 5998;
    CmdFateType_FateShopLeaveCsReq = 5952;
    CmdFateType_FateSyncPendingActionScNotify = 5958;
    CmdFateType_FateStartCsReq = 5987;
    CmdFateType_FateTakeExpRewardCsReq = 5976;
    CmdFateType_MJEDNEIFKDF = 5969;
    CmdFateType_FateShopBuyGoodsScRsp = 5971;
    CmdFateType_FateShopLockGoodsScRsp = 5956;
    CmdFateType_FateShopLeaveScRsp = 5964;
    CmdFateType_FateChangeLineupScRsp = 5957;
    CmdFateType_FateSyncActionResultScNotify = 5963;
    CmdFateType_FateShopRefreshGoodsCsReq = 5967;
    CmdFateType_FateShopBuyGoodsCsReq = 5960;
    CmdFateType_FateChangeLineupCsReq = 5953;
    CmdFateType_FateTakeExpRewardScRsp = 5995;
    CmdFateType_FateShopSellBuffCsReq = 5974;
    CmdFateType_FateStartScRsp = 5994;
    CmdFateType_FateSettleScNotify = 5990;
    CmdFateType_IIMFKFNANNC = 5968;
    CmdFateType_FateShopRefreshGoodsScRsp = 5979;
    CmdFateType_FateQueryScRsp = 5973;
    CmdFateType_FateShopSellBuffScRsp = 5970;
    CmdFateType_FateShopLockGoodsCsReq = 5983;
    CmdFateType_FateQueryCsReq = 5959;
    CmdFateType_FateReijuSelectRerollCsReq = 5985;
}

message DACCNAFGHFJ {
    KCLHMJHIDOB AKGJOPBLPNE = 6;
}

message DAFHOKGICNG {
    repeated uint32 PDABDEJBPEL = 8;
}

message DBKNLPMGFFH {
    uint32 gold = 13;
}

message DDLHODCINBI {
    oneof MMCGBGDJIPN {
        DACCNAFGHFJ EKKABKCCLGJ = 6;
        MMPPKFJEOGK BJEDONKMCFE = 13;
        OPPNDJOCBEA GAEFNAJACEH = 10;
        FLIPLAHLMKM JGKDIFDIMKN = 7;
        DBKNLPMGFFH MFFLKLAJBDF = 12;
        JFLOHLLMOJK HENLCGACIOK = 15;
        DOBHOCKGHBI PLFLNBLMMHI = 3;
        MAFJLIIKIIF NKPAELIHJAD = 5;
        ANJBJLDMDFN MLPFDMIILBD = 4;
        AFANKKDMIHC GIGFDPNIMGD = 9;
        LMOPAFOIJNF JGNMFHFCIFN = 1;
        KAJLLLAAKOG OKDKHJFHJND = 14;
        AHOMAAHPCIG CCOHJLKNFON = 2;
        KGJGEEEKNNC MILPEAKHKEL = 11;
        LHJBIHJBNHI PLDLCJPGCIB = 187;
        BDJEGABKNHN FEINKBBJNHP = 1436;
        ELEMFBMOMMM HNFLLMLLNFI = 1308;
        HACIGDEEMCJ CCEGFKEBEMI = 1111;
        PANAGPMIIIH GGGLMGKKFFM = 83;
        KGOBMEOAEBL JKHGEJCJOEB = 173;
        PIKIDDEEDII CMHLMLEGNGM = 1009;
    }
}

message DOBHOCKGHBI {
    uint32 JIMBJHLMHLO = 10;
}

message EJCCCIGMHOM {
    repeated uint32 NKHIIMHCLCD = 3;
    HIJCLODMBPO GJFKKFFJDAH = 4;
    repeated uint32 GMGOHBLFMAN = 5;
    GCECAGOELDP BDIBPIMAPOC = 12;
}

message ELEMFBMOMMM {
    BGNIMFMFKLH ECMBBBAPAJC = 14;
}

enum EMFDLPNOGOH {
    EMFDLPNOGOH_NLCDGIPGFDJ = 0;
    EMFDLPNOGOH_NGPHFLBNHKB = 1;
    EMFDLPNOGOH_KBAENNGPMPH = 2;
    EMFDLPNOGOH_GKHJMGPHDBK = 3;
    EMFDLPNOGOH_CHGJLDDJJAH = 4;
    EMFDLPNOGOH_FBKMDMLBNII = 5;
    EMFDLPNOGOH_MADBILBKOAO = 6;
}

message ENJDEFHFKPI {
    repeated uint32 BAHMHMDOMPB = 12;
}

message FGEMJLFIHHL {
}

message FJKMGCKMNNA {
    MOHNIMLCODA source_type = 1;
    uint32 BNEFLBPCPOI = 3;
}

message FLIPLAHLMKM {
    repeated MJLJMCCGNEE BLFMGKPNPGG = 12;
}

message FateBattleStartScRsp {
    SceneBattleInfo battle_info = 12;
    uint32 retcode = 14;
}

message FateBuffData {
    uint32 buff_id = 4;
    uint32 cnt = 6;
}

message FateChangeLineupCsReq {
    repeated KPNHGDGLICN avatar_list = 8;
}

message FateChangeLineupScRsp {
    uint32 retcode = 13;
}

message FateHandlePendingActionScRsp {
    uint32 retcode = 5;
}

enum FateMasterStatusType {
    KNGLNMKNGJD_NLCDGIPGFDJ = 0;
    KNGLNMKNGJD_LCNJHOKLMPN = 1;
    KNGLNMKNGJD_JJBEPKLOLCP = 2;
    KNGLNMKNGJD_PEBNPKOCADN = 3;
}

message FateQueryCsReq {
}

message FateQueryScRsp {
    uint32 retcode = 10;
    EJCCCIGMHOM LFLCDNGALME = 12;
    BFBCEOICLAB OEIBHLMDJKA = 15;
}

message FateSettleScNotify {
    HJFCEEBAGMF LNBBPPKLBFA = 1;
    ItemList reward = 7;
    uint32 score_id = 12;
}

message FateShopBuyGoodsCsReq {
    uint32 COCLMANMAAI = 2;
}

message FateShopBuyGoodsScRsp {
    uint32 retcode = 13;
    uint32 COCLMANMAAI = 14;
}

message FateShopLeaveCsReq {
}

message FateShopLeaveScRsp {
    uint32 retcode = 8;
}

message FateShopLockGoodsCsReq {
    bool is_locked = 11;
}

message FateShopLockGoodsScRsp {
    uint32 retcode = 12;
    bool is_locked = 13;
}

message FateShopRefreshGoodsCsReq {
}

message FateShopRefreshGoodsScRsp {
    uint32 retcode = 8;
    bool PNMNPFGCFBJ = 9;
    repeated JDAIOFEPGCC OGDKJPDFFAI = 15;
}

message FateShopSellBuffCsReq {
    uint32 JDIFHPAFPID = 8;
    uint32 PCJOBDNLEAI = 11;
    bool PMCPIECGEHH = 13;
}

message FateShopSellBuffScRsp {
    bool PMCPIECGEHH = 8;
    uint32 retcode = 9;
    uint32 JDIFHPAFPID = 11;
    uint32 PCJOBDNLEAI = 13;
}

message FateStartCsReq {
    uint32 area_id = 6;
    repeated KPNHGDGLICN avatar_list = 14;
    uint32 difficulty = 15;
}

message FateStartScRsp {
    uint32 retcode = 7;
    BFBCEOICLAB OEIBHLMDJKA = 11;
}

message FateSyncActionResultScNotify {
    repeated DDLHODCINBI CLGGKLNPLCK = 14;
}

message FateSyncPendingActionScNotify {
    JFKAOMCJIKK FMIGOKIDKJL = 6;
}

message FateTakeExpRewardCsReq {
}

message FateTakeExpRewardScRsp {
    ItemList reward = 6;
    repeated uint32 HPJMJEAJKAC = 7;
    uint32 retcode = 10;
    repeated uint32 HKEFKHJOEPJ = 12;
}

message GCECAGOELDP {
    uint32 exp = 1;
    repeated uint32 CFIKMGKPOFH = 10;
    repeated uint32 NPDOKAJOOKD = 14;
}

message GHAJMKCEEPJ {
    uint32 NOILILELKFB = 6;
    bool MLKBOBIEAPL = 13;
}

message GKJEMHKOMJC {
    uint32 rank = 5;
    int32 hp = 7;
    repeated JOGCCINEHFJ CFFCNEDGCJJ = 8;
    FateMasterStatusType status = 9;
    uint32 avatar_id = 11;
    int32 max_hp = 14;
}

message HACIGDEEMCJ {
    FJKMGCKMNNA JDFKEJDDGFC = 9;
}

message HDHLHNEACHP {
    uint32 id = 4;
    uint32 level = 6;
    AvatarType avatar_type = 10;
    bool is_upgraded = 15;
}

message HIJCLODMBPO {
    HJHMNDBJPND PIDFDPIDJMN = 2;
    HJHMNDBJPND OAFLJGCKIAJ = 11;
    map<uint32, HJHMNDBJPND> BDJECEJAKIJ = 12;
    repeated HJFCEEBAGMF BJJDJFJMGDI = 14;
}

message HJFCEEBAGMF {
    map<uint32, uint32> LANHCGFHCDB = 2;
    repeated HDHLHNEACHP avatar_list = 3;
    uint32 difficulty = 5;
    uint32 OKOICDENGFK = 7;
    map<uint32, uint32> DBIFAJIBGAC = 8;
    repeated uint32 LNNGKPAJKLP = 9;
    uint32 BKPDKFLDLDD = 11;
    uint32 IDNHBBMLNJK = 12;
    repeated uint32 FELMAMPGMAE = 13;
    uint32 level_id = 15;
    map<uint32, uint32> DHBPGMPMPOL = 302;
}

message HJHMNDBJPND {
    map<uint32, uint32> LJDLJKCMIIC = 2;
    uint32 total_count = 3;
    uint32 KAENLKDNOMF = 4;
    repeated uint32 DKJEDBHLOPP = 12;
}

message IBGFKJMMICI {
    repeated BGNIMFMFKLH OPOIDPJFFPK = 11;
}

message IMIHIMCHHIP {
    uint32 item_value = 8;
    uint32 OIDJFIFJDHL = 9;
}

message JCMKKEKMHNC {
    repeated KMLOMKCMGHD LGFJPBJOBPC = 3;
}

message JDAIOFEPGCC {
    bool GDOBLPPEGKD = 9;
    uint32 KDKPDJNMMCM = 10;
    uint32 cnt = 11;
    uint32 buff_id = 14;
}

message JFKAOMCJIKK {
    uint32 queue_position = 8;
    KFAIFLHPEIE GJDKHBPHNCG = 13;
}

message JFLOHLLMOJK {
    uint32 KCBLNMMHOKG = 1;
    uint32 MNCBFLEFJCK = 5;
}

message JIMNPPNNHEL {
    uint32 KCBLNMMHOKG = 1;
    bool ONDCOEBNAPJ = 3;
    uint32 item_value = 6;
    repeated IMIHIMCHHIP AALLBBCJGIA = 7;
    repeated JDAIOFEPGCC OGDKJPDFFAI = 9;
    uint32 MNCBFLEFJCK = 11;
    bool PNMNPFGCFBJ = 15;
}

message JOGCCINEHFJ {
    bool DIHFBELJFIA = 5;
    repeated uint32 monster_list = 7;
    uint32 unique_id = 10;
    uint32 affix_id = 11;
    bool FNIAOAOBKBA = 12;
}

message JOLGFGCFMAL {
    uint32 retcode = 12;
}

message KAJLLLAAKOG {
    repeated AGPKFBLGDIH BFNINELCBCN = 7;
    repeated uint32 CJBINCOKFPO = 8;
}

message KAOPGJBGEBF {
    uint32 unique_id = 6;
    int32 value = 12;
    uint32 DAMIHCPPJAB = 14;
}

message KCLHMJHIDOB {
    uint32 IDNHBBMLNJK = 7;
    uint32 BKPDKFLDLDD = 8;
}

message KFAIFLHPEIE {
    oneof MMCGBGDJIPN {
        DAFHOKGICNG HNPBCGILAJP = 7;
        JCMKKEKMHNC NPBKAADBHHC = 9;
    }
}

message KGJGEEEKNNC {
    JIMNPPNNHEL EFLLPHLDBPC = 9;
}

message KGOBMEOAEBL {
    bool ONDCOEBNAPJ = 5;
}

message KLMNGOJKEIN {
    uint32 unique_id = 6;
    uint32 MELNKMALHJO = 7;
}

message KMLOMKCMGHD {
    uint32 JCNDBKGBLLJ = 8;
    uint32 DAMIHCPPJAB = 11;
}

message LEGBKMIIJOA {
    uint32 DIIDBKIJEAF = 1;
    uint32 JGLNALONLDO = 5;
    uint32 GCIFCLINGFN = 7;
    uint32 avatar_id = 8;
    bool MEHPJMPDNNA = 9;
    double FJDFOPNAFPP = 10;
    bool JMCMPFPDEHG = 12;
    uint32 ECPMGBGLLNN = 15;
}

message LHJBIHJBNHI {
    GKJEMHKOMJC GJPGBBHCAFC = 10;
}

message LMOPAFOIJNF {
    repeated uint32 PDKAMAGEFEK = 9;
    repeated FateBuffData FCKIOLPLANI = 11;
}

message MAFJLIIKIIF {
    KLMNGOJKEIN MAIBAOAOGID = 9;
}

message MJLJMCCGNEE {
    CLNABFMHFFH KPEHHGEKNHA = 1;
    CLNABFMHFFH LJEAFPOHNCD = 15;
}

message MMPPKFJEOGK {
    EMFDLPNOGOH EGBFNFCEPHD = 15;
}

message NBBHDPCPHNN {
    map<uint32, uint32> buff_amplification_map = 2;
    repeated uint32 NGOMJIFBBBP = 5;
    repeated AGPKFBLGDIH ICCMJHJLPCD = 12;
    repeated FateBuffData buff_list = 13;
    repeated uint32 MHLNGFBOIDP = 14;
    uint32 JIMBJHLMHLO = 15;
}

message OPPNDJOCBEA {
    uint32 GCNMKIHOFGG = 1;
    repeated LEGBKMIIJOA MIKKAEJNLAL = 2;
    uint32 NCDBCLLAHPP = 3;
    uint32 LKPNNOGPJOI = 4;
    repeated uint32 EAOCKLDEOGH = 6;
    repeated GKJEMHKOMJC OCAMBKNKKGO = 8;
    bool NEEDLFJJFPL = 9;
    uint32 JJDEEHAMHGF = 14;
}

message PANAGPMIIIH {
    repeated uint32 NGOMJIFBBBP = 13;
}

message PIKIDDEEDII {
    repeated uint32 BAHMHMDOMPB = 2;
}

message PJFDAOKIKOJ {
    repeated GKJEMHKOMJC OCAMBKNKKGO = 9;
}
