syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdGachaType {
    CmdGachaType_NLCDGIPGFDJ = 0;
    CmdGachaType_DoGachaScRsp = 1958;
    CmdGachaType_GetGachaCeilingCsReq = 1988;
    CmdGachaType_ExchangeGachaCeilingScRsp = 1947;
    CmdGachaType_SetGachaDecideItemScRsp = 1913;
    CmdGachaType_GetGachaCeilingScRsp = 1981;
    CmdGachaType_GetGachaInfoCsReq = 1925;
    CmdGachaType_GetGachaInfoScRsp = 1978;
    CmdGachaType_LNEPKAIOAKB = 1926;
    CmdGachaType_ExchangeGachaCeilingCsReq = 1986;
    CmdGachaType_DoGachaCsReq = 1993;
    CmdGachaType_PDCIIFCCBEH = 1971;
}

message DoGachaCsReq {
    uint32 gacha_id = 4;
    uint32 simulate_magic = 5;
    uint32 gacha_random = 14;
    uint32 gacha_num = 15;
}

message DoGachaScRsp {
    repeated GachaItem gacha_item_list = 1;
    uint32 gacha_id = 2;
    uint32 NHBBHEMPJJM = 4;
    uint32 retcode = 5;
    uint32 LDBCKJIPDHF = 6;
    uint32 gacha_num = 10;
    uint32 ceiling_num = 13;
    uint32 GPNLDDLBOLM = 14;
    uint32 GLLJFPENLHD = 15;
}

message ExchangeGachaCeilingCsReq {
    uint32 avatar_id = 2;
    uint32 gacha_type = 8;
}

message ExchangeGachaCeilingScRsp {
    uint32 gacha_type = 1;
    GachaCeiling gacha_ceiling = 3;
    ItemList transfer_item_list = 5;
    uint32 avatar_id = 6;
    uint32 retcode = 9;
}

message GachaCeiling {
    repeated GachaCeilingAvatar avatar_list = 3;
    uint32 ceiling_num = 7;
    bool is_claimed = 11;
}

message GachaCeilingAvatar {
    uint32 repeated_cnt = 2;
    uint32 avatar_id = 12;
}

message GachaInfo {
    int64 begin_time = 1;
    uint32 MMELNCHIDNC = 2;
    repeated uint32 item_detail_list = 3;
    GachaCeiling gacha_ceiling = 4;
    string history_url = 5;
    uint32 NHBBHEMPJJM = 6;
    int64 end_time = 7;
    repeated uint32 ONIHOMCELJK = 9;
    uint32 GLLJFPENLHD = 12;
    uint32 gacha_id = 13;
    repeated uint32 prize_item_list = 14;
    string detail_url = 15;
}

message GachaItem {
    ItemList transfer_item_list = 1;
    ItemList token_item = 2;
    Item gacha_item = 3;
    bool is_new = 6;
}

message GetGachaCeilingCsReq {
    uint32 gacha_type = 7;
}

message GetGachaCeilingScRsp {
    uint32 retcode = 2;
    GachaCeiling gacha_ceiling = 5;
    uint32 gacha_type = 13;
}

message GetGachaInfoCsReq {
}

message GetGachaInfoScRsp {
    uint32 GPNLDDLBOLM = 1;
    uint32 OGMPKDHKPAJ = 3;
    uint32 retcode = 5;
    uint32 KKKNJDBNJPM = 9;
    repeated NEIMLKNMDBM AKMDBPNEHDE = 13;
    repeated GachaInfo gacha_info_list = 14;
    uint32 gacha_random = 15;
}

message NEIMLKNMDBM {
    uint32 GFANBHAEKOK = 10;
    repeated uint32 OJNEFBJHCCK = 12;
    uint32 MMELNCHIDNC = 13;
    repeated uint32 EJGNMCAMELA = 14;
}

message SetGachaDecideItemScRsp {
    NEIMLKNMDBM NBLOJLDLBEB = 4;
    uint32 retcode = 12;
}
