syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AAGHPDHCOOI {
    uint32 LKMEMKLGIIK = 9;
}

message AAMEAOBEGKA {
    uint32 unique_id = 1;
}

message ABCBKHAIEOG {
    uint32 retcode = 8;
}

message ABPLALCHNFA {
    repeated uint32 OOEOCGLLHFO = 6;
    repeated GridFightSyncData JKPJFKCBIEM = 7;
    GridFightUpdateSrcType grid_update_src = 13;
}

message ACCMEOICEOD {
    repeated JKPOIHGIFFG GKJIDBEGBJP = 2;
}

message AFCBKJEFKPG {
    BGMLEJCOFPK CCDGGDMHMLF = 3;
    uint32 progress = 5;
    uint32 id = 6;
    repeated uint32 CBACAMKJFMI = 10;
    GridFightDropInfo CLHLMNAPLNC = 12;
    IBBDHFAEFNH status = 14;
}

message AFPJPEABFKH {
    uint32 EAKBFELDDBF = 12;
}

message AGGDDAJLAEB {
    uint32 INLHPJMOOMO = 10;
    double IDONFFOACIL = 12;
}

message AGOBLKJFJDL {
    uint32 OOPFNFIGPKB = 10;
    uint32 NFBJINKLLLK = 15;
}

message AHKDPCIIELA {
    uint32 monster_id = 5;
    uint32 role_star = 9;
    uint32 IMDKLKONINF = 10;
    uint32 LOGHLGKIFEN = 15;
}

message AIDDODLHDLE {
    uint32 retcode = 10;
}

message AJDFPFHBFJM {
}

message AKHEHAMBLEB {
    int64 start_time = 11;
    int64 KAHFEFACFIE = 12;
}

message ALNFEBKHCFC {
    uint32 retcode = 5;
}

message AMFIFNOCDOF {
    uint32 MDNAGANGNKK = 11;
}

message BDDDLOFNCHN {
    uint32 MDNAGANGNKK = 11;
}

message BDNCOOANAEA {
    repeated uint32 EHDAKFEHPMF = 6;
    uint32 NNFECNICMOD = 9;
    uint32 JCNLCNFHHDG = 10;
    GridFightEquipCraftSource source = 13;
}

message BEBIJAKFNLO {
    uint32 PEBCBLBLMPH = 6;
}

enum BGMLEJCOFPK {
    BGMLEJCOFPK_NLCDGIPGFDJ = 0;
    BGMLEJCOFPK_ENPLACDLJGA = 1;
    BGMLEJCOFPK_DACEMIDFHOG = 2;
}

message BJALEHOMFKH {
    repeated uint32 OLPPMEAMFFO = 2;
    uint32 effect_id = 3;
    uint32 trait_id = 12;
}

message BJFLPMNPFFK {
    uint32 MDNAGANGNKK = 14;
}

message BJIGOFOAEPL {
}

message BKIKOGNAECK {
    uint32 PEBCBLBLMPH = 1;
    uint32 DNMFNFCLOOM = 3;
}

message BOPHDCKJMMN {
    uint32 weight = 2;
    uint32 CKKDAEMFDPA = 14;
}

message BPENENIMEFE {
    GridFightDropInfo GHBBCIIPHKJ = 8;
    uint32 quest_id = 10;
    bool IJJDEHIPOEL = 11;
}

message CBEEKLPIEMK {
    uint32 retcode = 3;
}

message CCGJDDBKIDE {
    message OAKDCENFILP {
        enum BBFEFIPJMEB {
            BBFEFIPJMEB_OHDJNICJKLK = 0;
            BBFEFIPJMEB_NCBOLDFDGNL = 1;
            BBFEFIPJMEB_EKGPCJLBINA = 2;
        }
    }
    uint32 IMJBFLJPMJB = 1;
    CCGJDDBKIDE.OAKDCENFILP.BBFEFIPJMEB type = 12;
}

message CCKPBIKOIBB {
    uint32 LKMEMKLGIIK = 12;
}

message CEGIAKADMHP {
    uint32 retcode = 8;
}

message CEHDAMJJFOE {
    uint32 MDNAGANGNKK = 5;
    uint32 ENNOJCBAJEN = 6;
    uint32 JNJBMFJHBHD = 12;
}

message CENBJOMMJGD {
    uint32 item_count = 1;
    uint32 item_type = 14;
}

message CFFDCICDAKK {
    repeated BPENENIMEFE EKBOGBMPAPJ = 2;
}

message CFHEKNFNMIP {
    bool is_locked = 8;
}

message CFIDOJGKBHB {
}

message CGBKKGNFMKL {
    uint32 retcode = 9;
}

message CJPOMFIDLOA {
    uint32 augment_id = 10;
}

message CKPOBLIFMGN {
    GridFightTalentInfo MHFHLBHFIBC = 11;
}

message CLFABOEKMJI {
    repeated uint32 MIOAPAGNAMC = 3;
}

message CNBHPJFFLEF {
    bool is_effect = 3;
    repeated uint32 OJNEFBJHCCK = 10;
}

message CNOAPAMNDOA {
    repeated NBNLDHBELLO LFJLNAHJNBE = 10;
    repeated LHCOHLJIAII KGOEHKJIONM = 12;
    uint32 retcode = 14;
}

message CheckTextRsp {
    uint32 retcode = 8;
}

enum CmdGridFightType {
    CmdGridFightType_NLCDGIPGFDJ = 0;
    CmdGridFightType_ILONCLKIMJM = 8742;
    CmdGridFightType_GridFightHandleElationTemplateCsReq = 8445;
    CmdGridFightType_MMKAOHDNDIC = 8577;
    CmdGridFightType_GridFightEquipDressScRsp = 8740;
    CmdGridFightType_AJAHEIHGNKD = 8465;
    CmdGridFightType_GridFightGetOrbCsReq = 8718;
    CmdGridFightType_GridFightUpdateGameRefCsReq = 8750;
    CmdGridFightType_UpdateGameFormationScRsp = 8696;
    CmdGridFightType_FavourArchiveScRsp = 8676;
    CmdGridFightType_GridFightSyncUpdateResultScNotify = 8602;
    CmdGridFightType_GridFightUpdateEquipTrackCsReq = 8689;
    CmdGridFightType_GridFightEquipDressCsReq = 8608;
    CmdGridFightType_GridFightFavourArchiveCsReq = 8652;
    CmdGridFightType_GridFightSeasonHandBookNotify = 8725;
    CmdGridFightType_GridFightUseConsumableCsReq = 8572;
    CmdGridFightType_GridFightGetArchiveCsReq = 8530;
    CmdGridFightType_HLHAJEGJMIA = 8601;
    CmdGridFightType_GridFightEndBattleStageNotify = 8459;
    CmdGridFightType_GridFightStartGamePlayCsReq = 8464;
    CmdGridFightType_JGHBFGEEKID = 8679;
    CmdGridFightType_MJHFMIJKHIP = 8716;
    CmdGridFightType_GridFightRecycleRoleCsReq = 8680;
    CmdGridFightType_GridFightPermanentTalentResetScRsp = 8423;
    CmdGridFightType_GridFightBuyGoodsCsReq = 8483;
    CmdGridFightType_GridFightGetDataScRsp = 8443;
    CmdGridFightType_HAACKDPGNPN = 8702;
    CmdGridFightType_GridFightUpdateEquipTrackScRsp = 8729;
    CmdGridFightType_HOIMGLAEEKN = 8661;
    CmdGridFightType_IBIOHPHMPBE = 8552;
    CmdGridFightType_GridFightEquipCraftScRsp = 8488;
    CmdGridFightType_GridFightDestroyWeeklyRewardCsReq = 8766;
    CmdGridFightType_IAHFACJKOFH = 8502;
    CmdGridFightType_OEDOOIOFOBB = 8664;
    CmdGridFightType_ENJEOMLGPHH = 8745;
    CmdGridFightType_GridFightTrackTraitCsReq = 8519;
    CmdGridFightType_GridFightUpdateEliteBranchSelectCsReq = 8581;
    CmdGridFightType_GridFightSeasonTalentResetScRsp = 8412;
    CmdGridFightType_GridFightSummonProjectionCsReq = 8498;
    CmdGridFightType_GridFightEquipCraftCsReq = 8570;
    CmdGridFightType_GridFightQuitLeaveGamePlayCsReq = 8794;
    CmdGridFightType_GridFightSyncVirtualItemNotify = 8710;
    CmdGridFightType_GridFightQuitSettleCsReq = 8650;
    CmdGridFightType_HBAOEGMHEBG = 8644;
    CmdGridFightType_MJFPIHEMGAJ = 8539;
    CmdGridFightType_GridFightUpdateEliteBranchSelectScRsp = 8723;
    CmdGridFightType_GridFightResumeGamePlayCsReq = 8763;
    CmdGridFightType_GridFightHandlePendingActionScRsp = 8798;
    CmdGridFightType_GridFightUpdatePosScRsp = 8631;
    CmdGridFightType_GridFightEnablePermanentTalentCsReq = 8435;
    CmdGridFightType_GridFightUseForgeCsReq = 8447;
    CmdGridFightType_GridFightUseConsumableScRsp = 8647;
    CmdGridFightType_LMFPABAMKKO = 8408;
    CmdGridFightType_HLBMFFCEHLA = 8699;
    CmdGridFightType_GridFightEnableSeasonTalentCsReq = 8441;
    CmdGridFightType_LHFCPEAOLCP = 8668;
    CmdGridFightType_GridFightLockShopCsReq = 8514;
    CmdGridFightType_GridFightSeasonTalentEnableScRsp = 8484;
    CmdGridFightType_GridFightResetSeasonTalentCsReq = 8700;
    CmdGridFightType_HFOGOFPDKEL = 8531;
    CmdGridFightType_KFKDGLGFLNE = 8693;
    CmdGridFightType_GridFightSettleNotify = 8698;
    CmdGridFightType_GridFightPermanentTalentEnableScRsp = 8717;
    CmdGridFightType_AGELGBFNAPE = 8422;
    CmdGridFightType_JECFGBFCEMB = 8504;
    CmdGridFightType_OOFHGFDNGIB = 8772;
    CmdGridFightType_GridFightEnterBattleStageCsReq = 8478;
    CmdGridFightType_GridFightTakeWeeklyRewardCsReq = 8651;
    CmdGridFightType_GridFightFinishTutorialCsReq = 8468;
    CmdGridFightType_GridFightUpdatePosCsReq = 8522;
    CmdGridFightType_BCGMNMNJCEF = 8413;
    CmdGridFightType_GetGameFormationScRsp = 8583;
    CmdGridFightType_GridFightBuyExpCsReq = 8682;
    CmdGridFightType_HPIMCHMAPGA = 8470;
    CmdGridFightType_CFPIOPPFGON = 8633;
    CmdGridFightType_GridFightRefreshShopCsReq = 8692;
    CmdGridFightType_MOODNCNAKJF = 8779;
    CmdGridFightType_MFGJGJDJNAE = 8697;
    CmdGridFightType_ICBHFOJFMOF = 8460;
    CmdGridFightType_GridFightUpdateTraitElationCsReq = 8620;
    CmdGridFightType_JOJPCNMJHII = 8595;
    CmdGridFightType_GridFightEnterBattleStageScRsp = 8695;
    CmdGridFightType_CheckTextRsp = 8591;
    CmdGridFightType_GridFightWeeklyExtraSeasonExpScRsp = 8658;
    CmdGridFightType_MNFBAKIOBDJ = 8516;
    CmdGridFightType_GridFightGetDataCsReq = 8578;
    CmdGridFightType_GridFightResetPermanentTalentCsReq = 8411;
    CmdGridFightType_GridFightTraitUpdateScRsp = 8554;
    CmdGridFightType_GridFightUpdateEquipTrackPriorityCsReq = 8584;
    CmdGridFightType_GridFightRoleShopBuyGoodsScRsp = 8492;
    CmdGridFightType_HMADFDJFJKN = 8776;
    CmdGridFightType_GridFightRecycleRoleScRsp = 8449;
    CmdGridFightType_MBDNJFEKFIG = 8592;
    CmdGridFightType_PACOMBKLOJF = 8757;
    CmdGridFightType_GridFightUseHackOptionCsReq = 8768;
    CmdGridFightType_GridFightBackToPrepareCsReq = 8748;
    CmdGridFightType_GridFightSyncKeepWinCntNotify = 8529;
}

message DBFGKBNAKNH {
    uint32 KHHFIEPDHHD = 15;
}

message DFMGEJCCBPD {
}

message DGILDLDMGEI {
}

message DHOCOJLJPPA {
    GridFightCurrentInfo DHFOFLFCLAH = 6;
    uint32 retcode = 13;
}

message DPHPAKFLNOD {
}

message EJEFKJGAKOO {
    uint32 effect_id = 2;
    uint32 MENFBEDCBHB = 11;
    uint32 trait_id = 12;
}

message ELGLKEAPLGM {
    uint32 grid_fight_equipment_id = 11;
}

message ELJOHIOHPMJ {
    uint32 IJMKBOBGHBD = 13;
}

message ELPPDAHKLBE {
}

message EMFJDODNGIF {
    uint32 retcode = 9;
}

message EPELDFBCCEK {
    uint32 BGFFICLCKHE = 5;
    uint32 priority = 15;
}

message EPLJJNHCJIF {
}

message FADHEIGJENF {
    map<string, uint32> HJMAEDKCONE = 1;
}

message FAFBDGCEAHD {
    uint32 trait_id = 2;
    uint32 AFKKLDMAEDJ = 7;
}

message FBDLJKEBPHM {
    uint32 role_id = 2;
    uint32 MDNAGANGNKK = 4;
    map<uint32, uint32> JPIHLKGCBPC = 10;
}

message FBFBMMAAFCP {
    uint32 NBPFMFMKJHI = 12;
    uint32 EMFCEMPHOPI = 15;
}

message FCABIGNMAPL {
    uint32 CKKDAEMFDPA = 14;
}

message FDJCIHMFOMC {
    uint32 retcode = 7;
    string EGCPAOEAGLF = 8;
    string PEOODHOAJMP = 10;
}

message FGMKGOIIFFL {
    uint32 retcode = 15;
}

message FHBHIHJAOPB {
    uint32 DCAHJELNJNP = 9;
    uint32 DMLFGGDECDN = 12;
    uint32 ODDKKGOJHFO = 14;
}

message FHNLBDMKPEM {
    uint32 retcode = 7;
}

message FIIJNPBFJBG {
    map<string, uint32> POCKGKDFLKK = 3;
    uint32 IFLJPNDPDOA = 10;
}

message FKILNIGOKBF {
    uint32 role_id = 10;
}

message FKJMGFOPHHN {
    repeated FLFHACPLDJE CKJAKKNOHEK = 2;
    uint32 LCLPEJHEAID = 3;
}

message FLFHACPLDJE {
    oneof OFJBCEDFLKL {
        PGECGKEKFNC BDPIMPJOJBK = 1;
        uint32 gold = 8;
    }
}

message FLHIDBDFFKG {
    uint32 retcode = 1;
}

message FMJDDIHBELC {
    uint32 grid_fight_lineup_hp = 5;
    uint32 PPKKHHNEOHB = 7;
}

message FNNFHNKHIDD {
    uint32 PFIKCNFBGHE = 5;
}

message FPHPFJLAJDK {
    uint32 unique_id = 1;
    uint32 LKMEMKLGIIK = 9;
    uint32 pos = 11;
}

message FavourArchiveScRsp {
    uint32 BAAGDILLLME = 2;
    uint32 retcode = 3;
    bool IECKKCHJMLP = 7;
}

message GAEKHIDCFHF {
    ItemList reward = 1;
    repeated uint32 NGKOFMBBGNL = 3;
    NDLNIKCCALK MGBNEAHCDMA = 4;
    uint32 retcode = 8;
}

message GANGPHPGFCL {
    repeated GridFightSectionRecordInfo FNJNKKMNKIM = 3;
    GridFightDamageSttInfo NKBIDLBLONC = 6;
}

message GBJHJGCOJBC {
    uint32 MDNAGANGNKK = 1;
}

message GDHFMHKFEAL {
    uint32 FKNNKCKLFMD = 6;
    GridFightDropInfo NMGIABHIJJB = 11;
}

message GEEMFDBDMDH {
    NFPLDMFCLHA LHIAODNJIIC = 5;
    uint32 PBMAHOJBAGG = 10;
    NFPLDMFCLHA EDCLIPCEHAO = 11;
}

message GEIBJKJDOHO {
    repeated uint32 FJBFGEIGMHF = 1;
    uint32 effect_id = 3;
    uint32 trait_id = 15;
}

message GFOMAIAIDFA {
    uint32 IEOGEFBLNEL = 13;
}

message GGAMIKNEDGE {
    uint32 retcode = 10;
}

message GILMFECEBFE {
    uint32 EOPHMLBEPGK = 1;
    uint32 PEBCBLBLMPH = 13;
}

message GIOLAAKLDED {
    uint32 augment_id = 15;
}

message GKLDOELMEIN {
    uint32 unique_id = 7;
}

message GLIFOLCEMIN {
    uint32 PIFOEGCGKLC = 11;
    uint32 KEJGCDOGEDD = 15;
}

message GLPCEKMKLGG {
    repeated uint32 grid_fight_avatar_list = 13;
}

message GMBMNFLMKPI {
    GridFightLockType LMICDNNABNM = 10;
    GridFightLockReason IBCPAKJAPFF = 12;
}

message GOCIGPCDKDJ {
    uint32 PAGPKOKMDBK = 2;
    uint32 EMOHLJHPOPC = 5;
    uint32 section_id = 6;
    uint32 LKCJAPIGEND = 8;
    uint32 FDGKBOIEHBD = 10;
    repeated uint32 FMEOHKHGMJM = 12;
    uint32 AACGBEBGDPE = 13;
    uint32 DCAHJELNJNP = 15;
}

message GPCFHMLMDHC {
    uint32 unique_id = 9;
}

message GetGameFormationScRsp {
    repeated HENDEHGPKMF FEBFMFMLHPO = 5;
    uint32 DACKJGDGMLN = 6;
    uint32 retcode = 12;
}

message GridFightAugmentActionInfo {
    repeated GridFightPendingAugmentInfo CEBFFDFMKGK = 2;
}

message GridFightBackToPrepareCsReq {
}

message GridFightConsumableInfo {
    uint32 item_id = 1;
    uint32 round_cnt = 2;
    uint32 num = 5;
    uint32 group_id = 9;
}

message GridFightConsumableTargetInfo {
    oneof NEBNJDMFELO {
        BDDDLOFNCHN AALCFBOGFKP = 1461;
        HPJKBFKAKJH IMILGHELNBJ = 1646;
        BEBIJAKFNLO KMCBBKIHBKF = 453;
        GBJHJGCOJBC AEOIKFNKAAP = 1600;
        AMFIFNOCDOF HLKKCAFGCIJ = 1794;
    }
}

message GridFightConsumableUpdateInfo {
    int32 HFNNNGHBHGG = 2;
    uint32 round_cnt = 7;
    uint32 item_id = 9;
    uint32 num = 10;
    uint32 group_id = 14;
}

message GridFightCurrentInfo {
    CLFABOEKMJI JLDDDLDNFEF = 2;
    uint32 LJNGPCKPJLF = 3;
    GridFightPendingAction FMIGOKIDKJL = 6;
    uint32 unique_id = 7;
    repeated GridFightGameInfo NAGDJGMMCBE = 8;
    bool is_overlock = 12;
    uint32 division_id = 14;
    GridFightGameData CAAGABEPPPE = 15;
}

message GridFightCurrentTask {
    uint32 progress = 2;
    uint32 NLIDEKJOFMG = 15;
}

message GridFightDamageSttInfo {
    repeated NFIDNDFHJGN JFCHLABGFJO = 3;
    repeated PLFKMENCDMM EEGPILJDLBG = 12;
    repeated KINJHHBJNJP APABPAFGCIA = 15;
}

message GridFightEncounterInfo {
    uint32 IFIIOIIKJHO = 1;
    repeated PNAKHANCNGK monster_wave_list = 6;
    uint32 EPPHOFDAEMI = 8;
    uint32 CJADMFDOBAI = 10;
    GridFightDropInfo BOAMLLHPNEC = 15;
}

message GridFightEndBattleStageNotify {
    uint32 DMNILJEGICO = 1;
    GridFightDamageSttInfo NKBIDLBLONC = 2;
    uint32 JPKHBELGHCG = 3;
    uint32 DCAHJELNJNP = 5;
    uint32 EMOHLJHPOPC = 6;
    uint32 HFLPDCJDIAC = 7;
    uint32 OGLOCDMNNIM = 8;
    map<uint32, GridFightDropInfo> AFFFCONCDMG = 9;
    bool CBHJKFNCDAD = 13;
    uint32 section_id = 15;
    uint32 CLFNPMGHMFC = 323;
    uint32 OAHFCPPIMLF = 471;
    uint32 ODJEBDNBLLC = 1105;
    uint32 OCCOHKIMGCN = 1115;
    GEEMFDBDMDH AEOCOGHMEBG = 1250;
    repeated GridFightHpModifyInfo HMKOKACNHJH = 1429;
    uint32 PAGPKOKMDBK = 1637;
    uint32 LKCJAPIGEND = 1987;
}

message GridFightEnterBattleStageCsReq {
}

message GridFightEnterBattleStageScRsp {
    uint32 retcode = 5;
    SceneBattleInfo battle_info = 10;
}

enum GridFightEquipCraftSource {
    ACNPGGHPDJB_GDDBKIPOJFK = 0;
    ACNPGGHPDJB_NAADGNAMIOK = 1;
    ACNPGGHPDJB_LEPMGCFIMGD = 2;
    ACNPGGHPDJB_KEKMKPPODEG = 3;
}

enum GridFightEquipDressSource {
    DMGOKGLBNJJ_IMLHGIMCJGG = 0;
    DMGOKGLBNJJ_GPAPBPFNKBI = 1;
    DMGOKGLBNJJ_PBKFJGEFCID = 2;
}

enum GridFightEquipTrackSource {
    IHMJHLGKLHP_FAHMBODELMP = 0;
    IHMJHLGKLHP_AIBFMLHADOG = 1;
    IHMJHLGKLHP_AJGKMJGKNNE = 2;
    IHMJHLGKLHP_GEMHFFFKHAP = 3;
}

message GridFightEquipmentInfo {
    uint32 grid_fight_equipment_id = 5;
    uint32 source = 8;
    uint32 unique_id = 11;
    map<uint32, uint32> convert_property_to_fixpoint = 14;
    bool IODIJBEHEGF = 15;
}

message GridFightForgeRoleActionInfo {
    uint32 LCLPEJHEAID = 11;
    repeated PGECGKEKFNC CKJAKKNOHEK = 13;
}

message GridFightGameAugmentAdd {
    GridGameAugmentInfo MCPIKEHDMND = 7;
}

message GridFightGameAugmentSync {
    repeated GridGameAugmentInfo sync_augment_info = 3;
}

message GridFightGameAugmentUpdate {
    GridGameAugmentInfo MCPIKEHDMND = 5;
}

message GridFightGameBasicInfo {
    repeated RoleTrackEquipmentInfo MIIDIMOCPEB = 1;
    uint32 grid_fight_lineup_hp = 2;
    uint32 gold = 3;
    uint32 JLOCMDIDPCI = 4;
    uint32 NDAINFLOLPJ = 5;
    uint32 PPKKHHNEOHB = 6;
    uint32 AFFCFLFIFPH = 7;
    uint32 GDAKCOICIDA = 8;
    uint32 EHNJDIDABHD = 9;
    uint32 MICEOJBAKGN = 10;
    uint32 grid_fight_cur_level_exp = 12;
    uint32 KNFOCCPOJEA = 13;
    repeated uint32 ONHDKLIMLNM = 14;
    uint32 BEPMODICONA = 15;
    GMBMNFLMKPI GAJGBBFELEL = 643;
    string ANIBGAAIAHF = 953;
    repeated uint32 JCMCCGHFIAN = 1509;
    repeated uint32 FMEOHKHGMJM = 1649;
    string GBGOBPOOPGO = 1889;
    GridFightSyncCurrentTaskInfo BHJFJEEGGMC = 2022;
}

message GridFightGameData {
    repeated GridFightGameItemInfo KLCKAOJAMNH = 9;
}

message GridFightGameInfo {
    oneof LEOIAOFBBFA {
        GridFightGameBasicInfo FAOCFBOFCJP = 15;
        GridFightGameItemsInfo GCKLIONKMJC = 11;
        GridFightGameShopInfo EBHDIOGALIE = 13;
        GridFightLevelInfo KLCPAAHDPJF = 14;
        GridFightGameOrbInfo DBAGKJNPDOL = 7;
        GridFightGameAugmentSync LLDBOIANGDN = 4;
        GridFightGameTraitInfo OAHOAPCIDMK = 10;
        GridFightGameTeamInfo EJIPINIKNCK = 5;
        FIIJNPBFJBG KFBIEANENKJ = 1;
        MCNFDKKKABH CKLNMDAMJCB = 8;
    }
}

message GridFightGameItemInfo {
    uint32 unique_id = 13;
    MJEICIEGAHF GBEAGMEAEPB = 15;
    oneof FMEKLFFDPGG {
        LFOCLBEMIEM HAGAEFMEHBA = 477;
        AKHEHAMBLEB FHKFMFKNMCH = 1784;
        ONLFOIONDAF CHHEGLGPCCH = 1577;
        FBFBMMAAFCP IJAFFOCBKJI = 140;
        KPKDJDEIKBM PDMOLEDAFIF = 1389;
        IPGCHDECCNB FCPGFBADIAL = 1293;
        LHMLIGPHOKP LJBBFDMAEOH = 1696;
        HHNBCLPNDFI LFBGLMMDMCD = 1626;
        FHBHIHJAOPB GLGPBLLICAG = 1438;
        ELPPDAHKLBE DNLGBJLPDCE = 1851;
        JEIEGMECGEN GNMCJEFJOKP = 1917;
        CNBHPJFFLEF PDHEDGGOPGL = 481;
        HDOLIECDHAO BBGLCDJPLMF = 556;
        OPJALEIKFAC EJEEHDPBHLI = 454;
        BJIGOFOAEPL EKLIOPIEKII = 1186;
        FAFBDGCEAHD FKBIGANCEPD = 1168;
        PIKKAEBHIKF NPHCPBDKLCH = 953;
        AGGDDAJLAEB CLFNPNNIFGE = 1539;
        FBDLJKEBPHM AOGFFCECKPK = 1607;
        OHBLOLLNHIC CMBMNLHAECG = 656;
        ILDEFHMIDKP LBFBINFMGNF = 107;
        FCABIGNMAPL FLELIBAJPEC = 219;
        GILMFECEBFE PNMLHBJOABC = 2005;
        DBFGKBNAKNH FBOLADPFLFL = 514;
        KBEKJKNCMCL KPHBBLHOPHF = 1245;
        HCIFBGJCPDM OAJOEEODJAO = 1440;
        HPMNCENLCAB KHNNNFBIAMA = 60;
        KLIHJCNOEJP AMGAJDKLHFO = 1015;
        GFOMAIAIDFA PDADFOGABLJ = 496;
        PPBJJJMJOBN IBNBALOPKMM = 1624;
        IEOMGIBLHJB INDGPPMDFND = 893;
        IEMINJAFCPM PKPFNHIKHON = 1022;
        KPMOCBIIMHH NIOCABOLGLO = 1410;
        CEHDAMJJFOE PGCBFHOPLEP = 732;
        BKIKOGNAECK KEHCIIEOLMD = 1818;
        HEHOBDGMMJM INHGPDPNILL = 1324;
    }
}

message GridFightGameItemSyncInfo {
    repeated GridFightConsumableUpdateInfo PFMDKHIDDLB = 4;
    repeated GridFightEquipmentInfo grid_fight_equipment_list = 8;
}

message GridFightGameItemsInfo {
    repeated GridFightEquipmentInfo grid_fight_equipment_list = 12;
    repeated GridFightConsumableInfo IPMKOMEHBMP = 14;
}

message GridFightGameOrbInfo {
    repeated PFBCBNMKFAK ODCMJGHEOMG = 2;
    repeated IBPDPCOGDEP MDKGCIKOMLI = 6;
}

message GridFightGamePortalBuffInfo {
    uint32 portal_buff_id = 15;
}

message GridFightGameShopInfo {
    uint32 OPDCMCFOFAA = 3;
    bool ABGEKPJHHIA = 5;
    repeated uint32 DLDJEOPKNMB = 10;
    MONJNCPINKN ABBNGCPECAI = 11;
    uint32 NFGMOPCCPIC = 12;
    repeated GridFightShopGoodsInfo OGDKJPDFFAI = 14;
}

message GridFightGameTeamInfo {
    repeated GridGameRoleInfo grid_game_role_list = 2;
    repeated FPHPFJLAJDK KCOMPKMJCMC = 3;
    repeated GridGameForgeItemInfo PMEOPPDAMLM = 6;
    repeated uint32 PLEIPHJGFIE = 13;
    repeated GridGameNpcInfo grid_game_npc_list = 14;
}

message GridFightGameTraitInfo {
    repeated GridGameTraitInfo grid_fight_trait_info = 2;
    repeated IGKKILFFNJK DAOOOBLJOLB = 11;
}

message GridFightGetArchiveCsReq {
    MLJIILDNDPL type = 14;
}

message GridFightGetDataCsReq {
}

message GridFightGetDataScRsp {
    uint32 retcode = 5;
    GridFightCurrentInfo DHFOFLFCLAH = 12;
    GridFightSystemInfo LFLCDNGALME = 15;
}

message GridFightHandBookAugmentInfo {
    repeated uint32 DDIFKADGIBO = 4;
    repeated uint32 JICIBCFDHIH = 7;
}

message GridFightHandBookEquipInfo {
    repeated uint32 grid_fight_item_list = 15;
}

message GridFightHandBookInfo {
    GridFightHandBookMonsterInfo NIOAIKLPACM = 6;
    GridFightHandBookEquipInfo PJBIPMKACOF = 9;
    GridFightHandBookAugmentInfo JLFANEOAHOC = 13;
    GridFightHandBookPortalInfo EJHDGLHCNLH = 14;
    GridFightHandBookRoleInfo DNEGDNEBJMB = 15;
}

message GridFightHandBookMonsterInfo {
    repeated uint32 HEKMEJLMGFF = 6;
}

message GridFightHandBookPortalInfo {
    repeated uint32 DJJBKIGBGJA = 1;
    repeated uint32 NPHOIMEEDHM = 7;
}

message GridFightHandBookRoleInfo {
    repeated uint32 grid_fight_avatar_list = 2;
}

message GridFightHandlePendingActionScRsp {
    uint32 retcode = 12;
    uint32 queue_position = 13;
}

message GridFightHpModifyInfo {
    uint32 IOAOHNDEJNB = 2;
    GridFightUpdateGlobalHpReason reason = 9;
    uint32 EOBOFDOGDDM = 10;
    int32 ODJEBDNBLLC = 11;
    int32 BMMADDOCJOG = 13;
}

message GridFightLayerInfo {
    bool LLOEBDLMLJO = 9;
    MDJBBILMHLC MPOBBIPMNNJ = 95;
}

message GridFightLevelInfo {
    GANGPHPGFCL COEBCNGCNOO = 2;
    ACCMEOICEOD LHEBNOLNJHE = 3;
    uint32 DCAHJELNJNP = 6;
    repeated LHNCMINFONJ HEKMEJLMGFF = 7;
    uint32 EMOHLJHPOPC = 8;
    GridFightLayerInfo IMPNAHBCADN = 9;
    KGMCLFHAJNJ boss_info = 10;
    repeated LAAMIAJFOMC CFFCNEDGCJJ = 11;
    uint32 section_id = 14;
    repeated GridFightGamePortalBuffInfo grid_fight_portal_buff_list = 15;
}

message GridFightLevelSyncInfo {
    uint32 DCAHJELNJNP = 2;
    uint32 section_id = 9;
    GridFightLayerInfo IMPNAHBCADN = 12;
}

enum GridFightLockReason {
    KMJNPEMPNMC_NEELHDGILED = 0;
    KMJNPEMPNMC_IDODGIKBBAE = 1;
    KMJNPEMPNMC_NJJGBCMLNLI = 2;
    KMJNPEMPNMC_AEINKINPAFL = 3;
}

enum GridFightLockType {
    GGNKDLAHAGH_EAJGHKNNJBB = 0;
    GGNKDLAHAGH_FHOHPFBDNOH = 6;
    GGNKDLAHAGH_GBDNJLPBNPO = 7;
    GGNKDLAHAGH_DAOBNJOGBBF = 8;
}

message GridFightOrbSyncInfo {
    uint32 unique_id = 6;
    uint32 LDBNOMPCOKK = 9;
}

message GridFightPendingAction {
    uint32 queue_position = 10;
    oneof FGLIODAJFML {
        GridFightPortalBuffActionInfo MFFCPLBNHCF = 339;
        GridFightAugmentActionInfo IBCHMBNIPLK = 1379;
        NGNKIIOHBAI PKHJLKNGCGH = 52;
        HNPHLAHJPOB BAKAKODKECM = 775;
        LEGPFIAPLOO JLPOPEAJHMF = 334;
        DPHPAKFLNOD NNDGEJFLGGF = 1071;
        HJPDALHDJHC LGNPHHBGKFH = 628;
        IAKEDFLIOFD FIKAGBAEOAP = 111;
        MHJIOJNNPDM HOKCPPPLJIO = 2033;
        GridFightRecommendEquipmentActionInfo HHNPEHMBDKD = 527;
        GridFightForgeRoleActionInfo HHNHGJMOGDD = 1479;
        FKJMGFOPHHN CFDIPFKBFJB = 139;
        GEIBJKJDOHO LAJGNNBOLDG = 1548;
        BJALEHOMFKH LFIDNOAECMN = 1986;
        CFFDCICDAKK IOHJGOENAPF = 1005;
    }
}

message GridFightPendingAugmentInfo {
    uint32 FEGDEOEHLFD = 3;
    uint32 KKIOBDHKPPK = 8;
    uint32 augment_id = 10;
}

message GridFightPermanentTalentEnableScRsp {
    uint32 CKHCLKOALKE = 8;
    uint32 retcode = 14;
}

message GridFightPermanentTalentResetScRsp {
    uint32 retcode = 4;
}

message GridFightPlayerLevelSyncInfo {
    uint32 HFMKLAPEKFA = 3;
    uint32 level = 8;
    uint32 exp = 14;
}

message GridFightPortalBuffActionInfo {
    repeated uint32 NPHOIMEEDHM = 4;
    uint32 PLPJNCDKMAD = 6;
    uint32 DAEMEBCKHIK = 7;
    uint32 GMLNOOHJCHM = 12;
}

message GridFightRecommendEquipmentActionInfo {
    repeated uint32 KBECJMLLCEJ = 10;
}

message GridFightRecycleRoleCsReq {
    uint32 unique_id = 12;
}

message GridFightRecycleRoleScRsp {
    uint32 retcode = 2;
}

message GridFightSeasonHandBookNotify {
    oneof KKNBOACNCON {
        GridFightHandBookRoleInfo KBHGCCENEEC = 518;
        GridFightHandBookEquipInfo LNLDBNIGODI = 1637;
        GridFightHandBookAugmentInfo ODEJBBALEOA = 537;
        GridFightHandBookPortalInfo HLHCCONOKCL = 1531;
        GridFightHandBookMonsterInfo BNFHPKCIFCC = 1069;
    }
}

message GridFightSeasonTalentEnableScRsp {
    uint32 retcode = 1;
    uint32 CKHCLKOALKE = 13;
}

message GridFightSeasonTalentResetScRsp {
    uint32 retcode = 14;
}

message GridFightSectionRecordInfo {
    uint32 DCAHJELNJNP = 5;
    uint32 node_type = 7;
    uint32 section_id = 11;
    KEEPBBDICFN GFCEGEPFCDB = 1758;
}

message GridFightSettleNotify {
    uint32 GEBGGMAGDJB = 5;
    uint32 KEJGCDOGEDD = 6;
    uint32 FLHOPMMEGAI = 10;
    uint32 NMCKJPEMACM = 13;
    uint32 EDHKHJAPMKA = 14;
    uint32 CDANKDNACJP = 15;
    OEDHMAHDECC BFLLJJBHLDF = 42;
    uint32 CGKNDIJMOCJ = 93;
    uint32 MNNKKEPCPPL = 457;
}

enum GridFightSettleReason {
    PEIJNEFOCHI_AIBAFPBKDJI = 0;
    PEIJNEFOCHI_NOCIJDINKPJ = 1;
    PEIJNEFOCHI_HIGMFLKHGNJ = 2;
    PEIJNEFOCHI_JOJPGBCECLN = 3;
    PEIJNEFOCHI_NBPPJEDAIFN = 4;
}

message GridFightShopGoodsInfo {
    bool LHGIFDNPIDE = 8;
    uint32 KDKPDJNMMCM = 12;
    oneof AELHFLGJMJN {
        NJBGFHDPFNO BDPIMPJOJBK = 1210;
        ELJOHIOHPMJ LLIBLKCJEMI = 409;
        CCKPBIKOIBB INBCCAIFHNL = 533;
    }
}

message GridFightShopSyncInfo {
    bool ABGEKPJHHIA = 1;
    uint32 OPDCMCFOFAA = 5;
    MONJNCPINKN ABBNGCPECAI = 6;
    uint32 NFGMOPCCPIC = 8;
    repeated GridFightShopGoodsInfo OGDKJPDFFAI = 9;
}

message GridFightStaticGameInfo {
    GLIFOLCEMIN exp = 2;
    uint32 ADFEKPNIFOJ = 3;
    uint32 GEBGGMAGDJB = 7;
    uint32 GEGMHOMNBDG = 8;
    uint32 GDAKCOICIDA = 9;
    GridFightTalentInfo MHFHLBHFIBC = 11;
    uint32 division_id = 13;
    GridFightHandBookInfo NLENPEPIHAC = 15;
}

message GridFightSupplyRoleInfo {
    uint32 role_id = 5;
    repeated uint32 grid_fight_item_list = 15;
}

message GridFightSyncCurrentTaskInfo {
    GridFightCurrentTask ONPCDAELHGP = 9;
    repeated uint32 CAMMIIJDEKP = 14;
}

message GridFightSyncData {
    oneof MNLCHEJKDHO {
        GridGameRoleInfo PIDDDHKPDDM = 1830;
        GridGameRoleInfo CFOCDALNCBP = 1071;
        uint32 HFCBOIOAECK = 1726;
        GridFightGameItemSyncInfo LMOLELDIKMA = 2016;
        GridFightGameItemSyncInfo DDBKEOPKPFI = 2004;
        GridFightGameItemSyncInfo PENGEDECBNF = 457;
        uint32 item_value = 542;
        GridFightPlayerLevelSyncInfo PLPHEIBLPDL = 873;
        FMJDDIHBELC grid_fight_lineup_hp = 1865;
        uint32 BPCFDPNHIEL = 450;
        GridFightShopSyncInfo MOFNIOJHBBL = 359;
        GridFightPendingAction FMIGOKIDKJL = 1938;
        MOENFCDKGMJ HPIIGHOELBH = 1114;
        GridFightLevelSyncInfo OOICHLAMNIG = 1061;
        GridFightOrbSyncInfo AFILIPBHMOO = 1769;
        GridFightSectionRecordInfo DMHMICHJBCB = 1253;
        GridFightGameAugmentUpdate LEADDFOJFKD = 1578;
        uint32 MDDKJGPJOAF = 294;
        uint32 PMFBIGLPJJA = 1073;
        uint32 KNFOCCPOJEA = 806;
        uint32 BEPMODICONA = 281;
        GridFightTraitSyncInfo HKHJJCMKKJE = 386;
        GridFightTraitTrackSyncInfo HGNDMOODNKF = 304;
        uint32 GDAKCOICIDA = 586;
        uint32 MICEOJBAKGN = 612;
        uint32 JLOCMDIDPCI = 1132;
        GridFightDamageSttInfo NKBIDLBLONC = 815;
        KEPIEGKPFIJ FGODNPLCECH = 1446;
        GridGameNpcInfo EJMDHDJCGDI = 666;
        GridGameNpcInfo DHLEOLKNAMI = 1226;
        uint32 NJCEFEJBEOP = 261;
        GridGameForgeItemInfo OLCKALFILKK = 1293;
        GridGameForgeItemInfo FEKCPKAPHHO = 917;
        uint32 OACCGHIHLBA = 1233;
        GridFightGameAugmentAdd EIKHFBCKIFA = 1463;
        MDKHMNKAECP BMGFDIKDOBE = 755;
        GridFightGameItemInfo GOOCHGKBIPN = 528;
        uint32 GOHHJLAPMBB = 1222;
        uint32 DGEOHFLHAHI = 130;
        JPGKBLDLADF LDKDJAEJMPA = 1993;
        GMBMNFLMKPI JOMFJHOCHJP = 1077;
        uint32 KALKCJFFJIK = 247;
        FPHPFJLAJDK GOJINGMMAIL = 1388;
        FPHPFJLAJDK CPCJGHCGLIJ = 68;
        uint32 DEKGKLGIDGI = 562;
        PFBCBNMKFAK AHMMHGHNHMI = 1681;
        uint32 OOAGJADOJNB = 165;
        uint32 CDKJHJNFDIH = 67;
        uint32 LDPPDHGNCHL = 911;
        FADHEIGJENF HJMAEDKCONE = 1633;
        GLPCEKMKLGG PPJFPNMIFHL = 1097;
        uint32 LOGJNAICJPA = 456;
        LAAMIAJFOMC MHFOELCFJGK = 235;
        HOGJECBMFHD BKDDCFHELNB = 1501;
        HJCAJKHNCDH CKNDFNACIPO = 1420;
    }
}

message GridFightSyncKeepWinCntNotify {
    uint32 EHBLJGIENPI = 14;
}

message GridFightSyncUpdateResultScNotify {
    repeated ABPLALCHNFA GCPNIHHBGGD = 6;
}

message GridFightSyncVirtualItemNotify {
    repeated CENBJOMMJGD item_list = 15;
}

message GridFightSystemInfo {
    GridFightStaticGameInfo HFPEJIDDDJG = 11;
    CKPOBLIFMGN PKELAIPIHMF = 12;
}

message GridFightTalentInfo {
    repeated uint32 BDGMNPIJDDL = 13;
}

message GridFightTraitEffectInfo {
    uint32 effect_id = 1;
    oneof NEBNJDMFELO {
        uint32 trait_core_role = 80;
        NBPEJFHIKJL avatar_core_info = 665;
        uint32 ECEMNCJBFOP = 812;
        GridFightTraitElationEffectUpdate JLCLHAKNMLL = 602;
        BJFLPMNPFFK MPHGIPCONLF = 1162;
        HJCFNEPJKDM KJFIOEPKOBM = 1515;
        LDMNIHIFDFG KOEPOCADLDI = 1626;
    }
}

message GridFightTraitElationEffectUpdate {
    repeated FHCEIOHLADG POJGKJENENA = 3;
    map<uint32, uint32> BANBECDCDHG = 12;
    uint32 DNNCAGJIOAP = 13;
}

message GridFightTraitSyncInfo {
    uint32 trait_id = 7;
    bool is_recover = 11;
    GridFightTraitEffectInfo ENPLACDLJGA = 15;
}

message GridFightTraitTrackSyncInfo {
    repeated uint32 ONHDKLIMLNM = 2;
    bool GHJLDDEDJLI = 12;
}

message GridFightTraitUpdateScRsp {
    uint32 retcode = 14;
}

message GridFightUpdateEquipTrackCsReq {
    repeated HLHHLIGPNOM DKEIDONNDCJ = 9;
    GridFightEquipTrackSource source = 14;
}

message GridFightUpdateEquipTrackScRsp {
    uint32 retcode = 15;
}

enum GridFightUpdateGlobalHpReason {
    DFIJIBKBEJL_IHNDJOLCKDI = 0;
    DFIJIBKBEJL_FDKCPHMMFCD = 1;
    DFIJIBKBEJL_IEGEHAKDEHA = 2;
    DFIJIBKBEJL_KEOPICGMGPI = 3;
    DFIJIBKBEJL_AAMHKFPCFPO = 4;
    DFIJIBKBEJL_LGCCNHOBMAP = 101;
    DFIJIBKBEJL_HBGPPEHGINP = 102;
    DFIJIBKBEJL_CJDPIHFECNJ = 103;
    DFIJIBKBEJL_AEKPBHCLJAN = 201;
}

message GridFightUpdatePosCsReq {
    repeated MHEGMHKHAAD AAKDHMHCMLP = 3;
}

message GridFightUpdatePosScRsp {
    uint32 retcode = 6;
    repeated MHEGMHKHAAD AAKDHMHCMLP = 11;
}

enum GridFightUpdateSrcType {
    JJDFGMMMCMI_CMOALMGLKIE = 0;
    JJDFGMMMCMI_DBIEKOMKBIN = 1;
    JJDFGMMMCMI_NFEGHCIANJO = 2;
    JJDFGMMMCMI_OIEEJKMJMDL = 3;
    JJDFGMMMCMI_EJLJOJFECPM = 4;
    JJDFGMMMCMI_GLFOHBCEGHA = 5;
    JJDFGMMMCMI_HLMCFKLKBPP = 6;
    JJDFGMMMCMI_JNCNKPHPFDH = 7;
    JJDFGMMMCMI_IEGCGBNPPHN = 8;
    JJDFGMMMCMI_NJBMBFFLNGM = 9;
    JJDFGMMMCMI_ANMFPKDFICD = 10;
    JJDFGMMMCMI_PNPMEHHEFPK = 11;
    JJDFGMMMCMI_NJPCDLLOHNO = 12;
    JJDFGMMMCMI_MAHELBOAHCG = 13;
    JJDFGMMMCMI_DOOKAAEOGPB = 14;
    JJDFGMMMCMI_LGHJPNHOGGA = 15;
    JJDFGMMMCMI_PKJFICDOGBH = 16;
    JJDFGMMMCMI_GLKAGBGLENM = 17;
    JJDFGMMMCMI_EABNJFBHKGG = 18;
    JJDFGMMMCMI_FDOIMKNLNLP = 19;
    JJDFGMMMCMI_NEDKALJPMLG = 20;
    JJDFGMMMCMI_LLENMLJBIDN = 21;
    JJDFGMMMCMI_MKNCMFALKPM = 22;
    JJDFGMMMCMI_KNEJNNEJNBC = 23;
    JJDFGMMMCMI_EGIKDCAEMNL = 24;
    JJDFGMMMCMI_JOMIDGFCHPH = 25;
    JJDFGMMMCMI_AFAFJHAHNEB = 26;
    JJDFGMMMCMI_OABPAPCNCKG = 27;
    JJDFGMMMCMI_IHEKGIGCGEC = 28;
    JJDFGMMMCMI_ECJPFOHNEDE = 29;
    JJDFGMMMCMI_IMDOPABAGGA = 30;
    JJDFGMMMCMI_EBMEIFGBJIM = 31;
    JJDFGMMMCMI_FFKPFGFJCEL = 32;
    JJDFGMMMCMI_NOKDKPGNPKK = 33;
    JJDFGMMMCMI_JNGKOHJPIHK = 34;
    JJDFGMMMCMI_DMJNOEIGDPA = 35;
    JJDFGMMMCMI_IOCFCLMNGDA = 36;
}

message GridFightWeeklyExtraSeasonExpScRsp {
    uint32 ACDOIGCBGEB = 5;
}

message GridGameAugmentInfo {
    bool NEKJGIDPCAI = 10;
    bool AEKOKMPIFLN = 13;
    uint32 augment_id = 15;
}

message GridGameForgeItemInfo {
    uint32 LCLPEJHEAID = 3;
    uint32 pos = 6;
    repeated MBPDIPLJMKN CKJAKKNOHEK = 7;
    uint32 unique_id = 13;
}

message GridGameNpcInfo {
    uint32 unique_id = 1;
    uint32 id = 3;
    uint32 pos = 4;
    repeated uint32 PNJIPHJJONG = 15;
}

message GridGameRoleInfo {
    uint32 role_star = 5;
    repeated uint32 PNJIPHJJONG = 8;
    uint32 unique_id = 9;
    map<string, uint32> grid_fight_value_init_component = 10;
    uint32 id = 12;
    map<uint32, uint32> convert_property_to_fixpoint = 14;
    uint32 pos = 15;
}

message GridGameTraitInfo {
    uint32 CGIEODOGAIE = 1;
    uint32 AFKKLDMAEDJ = 2;
    uint32 layer = 3;
    repeated uint32 OLPPMEAMFFO = 9;
    repeated GridFightTraitEffectInfo trait_effect_list = 11;
    uint32 trait_id = 14;
}

message HCIFBGJCPDM {
}

message HDOLIECDHAO {
}

message HEHOBDGMMJM {
    uint32 trait_id = 4;
    repeated uint32 grid_fight_avatar_list = 15;
}

message HENDEHGPKMF {
    uint32 dice_slot_id = 1;
    string name = 2;
    string KFPMJKCOJAJ = 4;
    bytes JLFIAFKGCOJ = 5;
    string MILBDIPBJGP = 6;
}

message HFNIHDLFMCJ {
    uint32 retcode = 9;
    NDLNIKCCALK MGBNEAHCDMA = 14;
}

message HHNBCLPNDFI {
    repeated uint32 DIKFEBAJMEK = 1;
}

message HJCAJKHNCDH {
    oneof MNLCHEJKDHO {
        AFCBKJEFKPG AIGPJLHBNEH = 9;
        AFCBKJEFKPG JNIOBAPDKLN = 3;
        uint32 MLAGBPIANKG = 1;
    }
}

message HJCFNEPJKDM {
    repeated uint32 JMLAMKFMKON = 8;
}

message HJPDALHDJHC {
}

message HKOAOCKBBJA {
    uint32 dice_slot_id = 4;
}

message HLHHLIGPNOM {
    repeated uint32 MCJMHBIECMN = 1;
    repeated uint32 grid_fight_item_list = 5;
    GridFightEquipTrackSource source = 6;
    bool BJDOINAHDLN = 9;
    uint32 priority = 10;
    uint32 BGFFICLCKHE = 15;
}

message HMBDOOHKIBC {
    uint32 retcode = 5;
}

message HMNMJKCHABE {
    repeated uint32 LOAFKKAFBOK = 3;
}

message HNPHLAHJPOB {
    uint32 DAEMEBCKHIK = 1;
    uint32 PLPJNCDKMAD = 5;
}

message HOGJECBMFHD {
    repeated IGKKILFFNJK DAOOOBLJOLB = 12;
}

message HPJKBFKAKJH {
    uint32 MDNAGANGNKK = 12;
    uint32 PEBCBLBLMPH = 13;
}

message HPMNCENLCAB {
    uint32 role_id = 5;
}

message IAABDBBJHOL {
    bool is_overlock = 1;
    uint32 LJNGPCKPJLF = 7;
    uint32 division_id = 14;
}

message IAKEDFLIOFD {
    uint32 PLPJNCDKMAD = 1;
    uint32 JJPMDBCPJBA = 4;
    uint32 DAEMEBCKHIK = 7;
    uint32 IONLFBNMOFP = 13;
    repeated GridFightSupplyRoleInfo MFBAKLCBPCJ = 14;
}

enum IBBDHFAEFNH {
    IBBDHFAEFNH_NLCDGIPGFDJ = 0;
    IBBDHFAEFNH_BMOOGBNPEAA = 1;
    IBBDHFAEFNH_CIHFGJDCHIA = 2;
    IBBDHFAEFNH_PJPFIHFAHGO = 3;
}

message IBPDPCOGDEP {
    uint32 unique_id = 3;
    uint32 LDBNOMPCOKK = 4;
}

message IDOJADMFGKF {
    uint32 ratio = 13;
}

message IEMINJAFCPM {
    repeated IFPAJBFOHLN ICDHAPACGEH = 14;
}

message IEOMGIBLHJB {
    uint32 NFFHCBDFABA = 1;
    uint32 IIJHFJFPIHK = 14;
}

message IFPAJBFOHLN {
    uint32 section_id = 4;
    uint32 DCAHJELNJNP = 11;
    uint32 role_id = 15;
}

message IGKKILFFNJK {
    uint32 BLAEAAFANBM = 1;
    repeated uint32 LEOCEFMKAEM = 8;
}

message IIFPPBCFBBC {
    uint32 retcode = 8;
}

message IKMOCJBMGOJ {
    bool is_get_all = 3;
    repeated uint32 CBMGDBJHLHO = 11;
}

message ILCPGLAAADL {
}

message ILDEFHMIDKP {
    uint32 CKKDAEMFDPA = 8;
}

message IPGCHDECCNB {
    uint32 node_type = 1;
    uint32 PIJBIFAIFOA = 11;
    uint32 CLBEEGLKMIM = 14;
}

message JBOOPAPNFDC {
    bool CIBONIOHELB = 5;
    repeated uint32 CGAFCMIAKLI = 12;
}

enum JDCAPBNPOOK {
    JDCAPBNPOOK_NLCDGIPGFDJ = 0;
    JDCAPBNPOOK_ENPLACDLJGA = 1;
    JDCAPBNPOOK_NMEEOHMGPKD = 2;
    JDCAPBNPOOK_OMKPENOHLII = 4;
    JDCAPBNPOOK_AOIGFLELHHH = 5;
    JDCAPBNPOOK_MCPIKEHDMND = 101;
    JDCAPBNPOOK_LDPMDPAGCHM = 102;
    JDCAPBNPOOK_EGCGFGDILBC = 103;
    JDCAPBNPOOK_HAEHIHOCLJD = 104;
    JDCAPBNPOOK_HCJBIBFBHKM = 105;
    JDCAPBNPOOK_MLOMHPFOMLO = 106;
    JDCAPBNPOOK_EDJGIJIILKE = 107;
    JDCAPBNPOOK_GGMPEGMEHPD = 108;
    JDCAPBNPOOK_FIFGENNKDBE = 109;
    JDCAPBNPOOK_ONPNOPLOAGH = 110;
    JDCAPBNPOOK_MDBHGMDBJGK = 111;
    JDCAPBNPOOK_DICKKDIAEND = 112;
    JDCAPBNPOOK_LKPOOOLNAJC = 113;
}

message JEIEGMECGEN {
    map<uint32, uint32> NADGHDJCHPI = 7;
}

message JIOMOCFOMOA {
    uint32 retcode = 5;
}

message JKGILKGILAI {
    uint32 DACKJGDGMLN = 6;
    uint32 retcode = 11;
}

message JKPOIHGIFFG {
    uint32 section_id = 4;
    uint32 DCAHJELNJNP = 6;
}

message JPGKBLDLADF {
    oneof MNLCHEJKDHO {
        uint32 AOKPCNJJBAO = 2;
        GridFightCurrentTask KBBOAJPMNCN = 3;
        uint32 CEPEHNEOIOH = 6;
    }
}

message KAHAOOJHJPK {
    uint32 retcode = 3;
}

message KBEKJKNCMCL {
    repeated uint32 CAOADMAKKPM = 9;
}

message KCCPHHGCPMP {
    uint32 JLLFIDAMBCN = 15;
}

message KEEPBBDICFN {
    uint32 PDIAOLDMBLL = 9;
    uint32 LOGHLGKIFEN = 11;
}

message KEPIEGKPFIJ {
    uint32 MOADBALHMFD = 11;
}

message KGMCLFHAJNJ {
    repeated AHKDPCIIELA NCGHKPEMPDP = 9;
}

message KINJHHBJNJP {
    uint32 trait_id = 7;
    uint32 layer = 9;
    double damage = 13;
}

message KLIHJCNOEJP {
    uint32 IGOHOJEJIGP = 6;
    uint32 NFBJINKLLLK = 9;
    repeated uint32 JPDCDKLEIBD = 11;
    uint32 EEELJEKNNOG = 12;
    uint32 LLJLCCDDLNI = 15;
}

message KOIAMDKEFKH {
    GridFightEquipDressSource CPFCNOAJCGK = 2;
    uint32 MDNAGANGNKK = 4;
    uint32 PEBCBLBLMPH = 14;
}

message KPKDJDEIKBM {
    uint32 CJCOMKHDAGM = 2;
}

message KPMOCBIIMHH {
    uint32 role_id = 4;
    uint32 IEOGEFBLNEL = 9;
    uint32 MDNAGANGNKK = 14;
}

message LAAMIAJFOMC {
    bool PNJCLPNFIGA = 5;
    uint32 affix_id = 11;
}

message LAPOAFHDNCM {
    uint32 JCAPCNLJGFC = 2;
}

message LCFAAGEJGBG {
    uint32 retcode = 12;
}

message LDBJKKCHNGJ {
    repeated uint32 JKCEBHFIENI = 10;
}

message LDMNIHIFDFG {
    uint32 BPJKHDNBPOE = 3;
}

message LDNPBALACDB {
    repeated uint32 GDCFLPLFJCI = 3;
}

message LEGPFIAPLOO {
    bool NKDEGMKKHPB = 4;
    uint32 effect_id = 5;
    uint32 trait_id = 6;
    repeated uint32 LAJLGHPLAAA = 10;
    repeated uint32 EGJDILDEAKP = 15;
}

message LFEFLIMJOGO {
}

message LFOCLBEMIEM {
    uint32 node_type = 2;
    uint32 DCAHJELNJNP = 11;
    uint32 section_id = 13;
    uint32 ELPODIAAGEK = 15;
}

message LFONAPFHAOB {
    uint32 PFIKCNFBGHE = 5;
}

message LHCOHLJIAII {
    uint32 num = 7;
    uint32 role_id = 13;
}

message LHMLIGPHOKP {
    repeated uint32 DIKFEBAJMEK = 9;
}

message LHNCMINFONJ {
    uint32 LOGHLGKIFEN = 3;
}

message LKDMCPDHEGM {
}

message LLPMAKIHAPL {
    uint32 retcode = 4;
}

message MBPDIPLJMKN {
    ELGLKEAPLGM GGMPEGMEHPD = 8;
}

message MCDBJHOCGHI {
    uint32 trait_id = 9;
    bool BJDOINAHDLN = 11;
}

message MCIPOMDGBCA {
    GridFightCurrentInfo DHFOFLFCLAH = 2;
    uint32 retcode = 4;
}

message MCNFDKKKABH {
    repeated uint32 BHOBPPBBNIL = 7;
    repeated AFCBKJEFKPG IBBKKFGEEPH = 14;
}

message MDJBBILMHLC {
    uint32 LNDKCPBJDKH = 3;
    uint32 MOADBALHMFD = 7;
    repeated GridFightEncounterInfo BPDABHGFBFO = 10;
}

message MDKHMNKAECP {
    repeated RoleTrackEquipmentInfo MIIDIMOCPEB = 6;
}

message MFLDDCIFAJN {
    uint32 retcode = 1;
}

message MHEGMHKHAAD {
    uint32 pos = 7;
    uint32 unique_id = 15;
}

message MHJIOJNNPDM {
    repeated uint32 KBECJMLLCEJ = 1;
}

message MHKNPBJDFIC {
    uint32 role_id = 9;
}

message MJEICIEGAHF {
    repeated uint32 OOEOCGLLHFO = 10;
    JDCAPBNPOOK JMNJLFACCLM = 12;
}

enum MLJIILDNDPL {
    MLJIILDNDPL_LAHJFEFDOBC = 0;
    MLJIILDNDPL_NJOBADDLBGK = 1;
    MLJIILDNDPL_FAGECPGMPEH = 2;
}

message MOENFCDKGMJ {
    uint32 portal_buff_id = 6;
}

message MOIONLDJGJI {
    GridFightConsumableTargetInfo param = 2;
    uint32 item_id = 10;
    uint32 group_id = 12;
}

message MONJNCPINKN {
    repeated BOPHDCKJMMN FIJPICNPKIG = 9;
}

message NBNLDHBELLO {
    uint32 role_id = 1;
    uint32 weight = 10;
}

message NBPEJFHIKJL {
    repeated uint32 OLPPMEAMFFO = 1;
}

message NDAMFDIDKGB {
    uint32 MOADBALHMFD = 11;
}

message NDLNIKCCALK {
    bool BPFFFCMMMCH = 1;
    uint32 EDHKHJAPMKA = 5;
    int64 end_time = 7;
    repeated uint32 OPLNKCOLCKJ = 12;
    int64 start_time = 14;
}

message NEMAKFJPGDF {
}

message NFIDNDFHJGN {
    double damage = 1;
    double KINKMHEAANP = 11;
    uint32 augment_id = 14;
}

message NFPLDMFCLHA {
    uint32 level = 1;
    uint32 KDBMPKJKAKI = 2;
    uint32 exp = 3;
}

message NGNKIIOHBAI {
    repeated uint32 OLPPMEAMFFO = 4;
    uint32 effect_id = 8;
    uint32 trait_id = 13;
}

message NIDJPBLNDLH {
    uint32 HAFOKMHCGFM = 10;
}

message NJBGFHDPFNO {
    uint32 role_star = 1;
    uint32 role_id = 7;
}

message NNFPCAPDENH {
}

message OEBKLEPMMKE {
    uint32 PFIKCNFBGHE = 5;
    uint32 unique_id = 12;
}

message OEDHMAHDECC {
    repeated GridGameTraitInfo grid_fight_trait_info = 3;
    uint32 LLJJCOOKANH = 6;
    repeated GridFightGamePortalBuffInfo OAIGAGABCMK = 7;
    repeated GridGameAugmentInfo sync_augment_info = 8;
    GOCIGPCDKDJ basic = 12;
    repeated PLFKMENCDMM EEGPILJDLBG = 13;
    repeated FPHPFJLAJDK KCOMPKMJCMC = 393;
    repeated GridGameRoleInfo grid_game_role_list = 636;
    repeated uint32 MHLBIBGKIOB = 682;
    repeated NFIDNDFHJGN JFCHLABGFJO = 738;
    repeated KINJHHBJNJP APABPAFGCIA = 762;
    uint32 MBMJNEDIFFC = 910;
    bool is_overlock = 1284;
    GLPCEKMKLGG PPJFPNMIFHL = 1290;
    bool DBODGPBOIHC = 1293;
    CLFABOEKMJI JLDDDLDNFEF = 1303;
    repeated uint32 HGAGKFEKBDA = 1311;
    repeated GridGameNpcInfo grid_game_npc_list = 1426;
    GridFightSettleReason reason = 1547;
    uint32 AKEGLJLCFPH = 1568;
    repeated LAAMIAJFOMC CFFCNEDGCJJ = 1846;
    KGMCLFHAJNJ boss_info = 1866;
    repeated GridFightEquipmentInfo grid_fight_equipment_list = 1972;
}

message OENNAOAFAMA {
    uint32 retcode = 5;
    uint32 JBDFEHDFKNO = 9;
    uint32 DACKJGDGMLN = 10;
}

message OHAINOHGKCM {
    uint32 MOADBALHMFD = 10;
}

message OHBLOLLNHIC {
    uint32 trait_id = 3;
    bool ANDIPJEDGMG = 11;
    uint32 HOHDOFKJJDJ = 12;
    uint32 role_id = 15;
}

message ONLFOIONDAF {
    uint32 JJNGGKPAKME = 3;
    uint32 interval = 4;
    uint32 PNFOOPNCDCH = 7;
    int64 start_time = 8;
    bool JMCJKPPKAIF = 12;
}

message OPJALEIKFAC {
}

message PAJHFEKAPMN {
    uint32 EGAPEGCKDFJ = 8;
}

message PCCGPNAFMHP {
    uint32 BCIGPPFMLJB = 12;
}

message PDKGKIDCBKA {
    uint32 BCIGPPFMLJB = 13;
}

message PFBCBNMKFAK {
    uint32 DOJDFBENBEC = 8;
    uint32 CMEHHMEEKPO = 14;
    uint32 unique_id = 15;
}

message PGECGKEKFNC {
    uint32 LPFGIGJDLFM = 1;
    uint32 role_id = 2;
}

message PHGFFOEJEBM {
    string EGCPAOEAGLF = 8;
    string PEOODHOAJMP = 9;
}

message PIKKAEBHIKF {
    uint32 PGEBCGLDNMN = 15;
}

message PLFKMENCDMM {
    uint32 role_star = 1;
    uint32 role_id = 2;
    bool DIGNECHKINI = 3;
    bool OGIBPMBELKC = 5;
    repeated uint32 grid_fight_equipment_list = 7;
    double total_damage = 10;
}

message PNAKHANCNGK {
    uint32 OCPEPEMNNEK = 8;
    repeated AHKDPCIIELA PBLBBDBDLEK = 15;
}

message PNHDGCBLPGD {
    uint32 retcode = 4;
}

message POIBJKBDLLI {
    repeated EPELDFBCCEK BFCMLCJMLOL = 15;
}

message PPBJJJMJOBN {
    uint32 BINKJCPGOAB = 7;
    uint32 BLAEAAFANBM = 11;
}

message RoleTrackEquipmentInfo {
    uint32 BGFFICLCKHE = 3;
    uint32 priority = 8;
    repeated uint32 MCJMHBIECMN = 9;
    GridFightEquipTrackSource source = 12;
    repeated uint32 grid_fight_item_list = 13;
}

message UpdateGameFormationScRsp {
    uint32 retcode = 2;
    HENDEHGPKMF EFBDADNLCGL = 4;
}
