syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AFEDHCKDDFA {
    uint32 id = 3;
    NAOCMAOJECF type = 12;
    bool AAGAFBJHOKK = 14;
}

message ANHJKLLEKKB {
    int32 value = 1;
    uint32 type = 2;
}

message BNJAIHINJIK {
    uint32 OBGKOOAPCEM = 1;
    GEFEDOAOKNO IPDLBJHAJOO = 4;
    HINIJKGDDBI FBECMPGLPKK = 5;
    uint32 ODPELJAIPHL = 6;
    PJOHABIOPPI GMMPIDODKKD = 12;
    uint32 GNAHDKMEDEP = 13;
}

enum CmdHipplenType {
    CmdHipplenType_NLCDGIPGFDJ = 0;
    CmdHipplenType_ELFNDPILMAA = 9024;
    CmdHipplenType_SettleHipplenWorkScRsp = 9007;
    CmdHipplenType_SetHipplenAgendaScRsp = 9048;
    CmdHipplenType_NMKDPKKOIND = 9017;
    CmdHipplenType_NJOOMIGMMPH = 9019;
    CmdHipplenType_TakeHipplenEndingRewardScRsp = 9035;
    CmdHipplenType_GetHipplenInheritScRsp = 9044;
    CmdHipplenType_JAFFDCKGMAA = 9037;
    CmdHipplenType_SetHipplenOutfitScRsp = 9029;
    CmdHipplenType_HipplenTraitUnlockScNotify = 9002;
    CmdHipplenType_HipplenCycleResultScNotify = 9021;
    CmdHipplenType_GetHipplenDataScRsp = 9023;
    CmdHipplenType_HipplenChangeScNotify = 9015;
    CmdHipplenType_KPABCGKCOCI = 9003;
    CmdHipplenType_OpenHipplenCycleScRsp = 9020;
    CmdHipplenType_ABCCLHIPMGG = 9014;
    CmdHipplenType_HipplenAgendaResultScNotify = 9010;
    CmdHipplenType_GAJEAKPBNFF = 9009;
}

message DMLACLLDCCE {
    uint32 GNAHDKMEDEP = 7;
    int32 CBPGJAFAHFC = 9;
    uint32 MNCFOGJECMF = 11;
    uint32 AJAFEEAOBLC = 15;
}

message DPGGADJHCBG {
    uint32 IMIBAAPJGEJ = 6;
}

message ELOFLNEAHPD {
    repeated ENIDJAFECBD BPFJDLHFEKG = 8;
    repeated uint32 grid_fight_trait_info = 10;
}

message ENIDJAFECBD {
    uint32 BKFICFMMGIN = 5;
    bool is_taken_reward = 11;
}

message FCOBIMJMLIF {
    uint32 type = 2;
    uint32 value = 15;
}

message FEDNIHCAHGP {
    repeated uint32 FCOKODHGEKO = 6;
    repeated uint32 GEMHKFCFCCC = 12;
}

message GCNJGJMPLHM {
}

message GEFEDOAOKNO {
    repeated FCOBIMJMLIF MONKDLNMMBK = 6;
}

message GetHipplenDataScRsp {
    FEDNIHCAHGP KJDEEJNBLHK = 1;
    uint32 JFLAEGMBMAK = 6;
    uint32 retcode = 8;
    BNJAIHINJIK HIGHKDBJNIM = 11;
    ELOFLNEAHPD ACOLLHOFKGL = 13;
    bool HPKECDINMCE = 15;
}

message GetHipplenInheritScRsp {
    uint32 retcode = 6;
    repeated uint32 grid_fight_trait_info = 11;
}

message HBMGNLFKMMK {
    uint32 MNCFOGJECMF = 5;
}

message HGDHJFGCEJF {
    oneof KKNBOACNCON {
        DPGGADJHCBG MDFCELGPPHM = 8;
        NOPCFDDLPNN HNLMBGIBEBN = 12;
    }
}

message HINIJKGDDBI {
    repeated uint32 grid_fight_trait_info = 4;
}

message HipplenAgendaResultScNotify {
    repeated uint32 grid_fight_trait_info = 2;
    BNJAIHINJIK HIGHKDBJNIM = 3;
    bool CPFFAGAHJMH = 5;
    GEFEDOAOKNO JMKHOIMEFFM = 6;
    repeated uint32 GPDEDJIHMGB = 10;
    repeated AFEDHCKDDFA NEMFNENACNB = 11;
    LKFFMLJMGOB FEJPEALIKHE = 15;
}

message HipplenChangeScNotify {
    repeated HGDHJFGCEJF DGNGMJMPFGK = 5;
}

message HipplenCycleResultScNotify {
    repeated JHBOOCGAKCM IHLCDDOMPKD = 1;
    uint32 JFLAEGMBMAK = 2;
    uint32 BKFICFMMGIN = 6;
    GEFEDOAOKNO GNBKDCHLDGL = 7;
    repeated JHBOOCGAKCM FJFJMOGILBM = 8;
    repeated uint32 FCOKODHGEKO = 13;
    repeated uint32 grid_fight_trait_info = 14;
}

message HipplenTraitUnlockScNotify {
    repeated uint32 grid_fight_trait_info = 3;
}

message JHBOOCGAKCM {
    uint32 LDMHLKGILOD = 7;
    uint32 FFKDFODDBDN = 14;
}

message LKFFMLJMGOB {
    uint32 MNCFOGJECMF = 2;
    uint32 AJAFEEAOBLC = 9;
    int32 CBPGJAFAHFC = 13;
}

message LODMLDKMPPL {
    uint32 id = 6;
}

enum NAOCMAOJECF {
    NAOCMAOJECF_NLCDGIPGFDJ = 0;
    NAOCMAOJECF_CNMBIADBFNG = 1;
    NAOCMAOJECF_ENCBGPOIFCM = 2;
    NAOCMAOJECF_ECKIMBNDOME = 3;
    NAOCMAOJECF_LONKNKFDPII = 4;
    NAOCMAOJECF_MLLNOGKNHNL = 5;
}

message NOPCFDDLPNN {
    uint32 BKFICFMMGIN = 15;
}

message OHHHCKCFPIG {
    repeated uint32 DPOKBJGLKNN = 1;
}

message OpenHipplenCycleScRsp {
    BNJAIHINJIK HIGHKDBJNIM = 1;
    uint32 JFLAEGMBMAK = 6;
    uint32 retcode = 10;
}

message PJOHABIOPPI {
    AFEDHCKDDFA LAJOGEKPHOP = 1;
    uint32 MBHJONMGDOO = 3;
    repeated AFEDHCKDDFA NEMFNENACNB = 7;
    repeated uint32 OGDLPFOJMHI = 9;
    uint32 DOHNBOCBOGJ = 13;
    uint32 JEEELNEHDCD = 15;
}

message SetHipplenAgendaScRsp {
    repeated AFEDHCKDDFA NEMFNENACNB = 10;
    uint32 retcode = 11;
}

message SetHipplenOutfitScRsp {
    repeated uint32 GEMHKFCFCCC = 1;
    uint32 retcode = 5;
}

message SettleHipplenWorkScRsp {
    repeated AFEDHCKDDFA NEMFNENACNB = 7;
    repeated ANHJKLLEKKB BNIFMIPPIMA = 8;
    GEFEDOAOKNO IPDLBJHAJOO = 11;
    uint32 retcode = 13;
    oneof MEJDDIPIEKK {
        DMLACLLDCCE HBGCOIAGDIG = 1;
        LKFFMLJMGOB LONKNKFDPII = 5;
    }
}

message TakeHipplenEndingRewardScRsp {
    uint32 BKFICFMMGIN = 1;
    uint32 retcode = 6;
    ItemList reward_list = 14;
}
