syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BGOMIHEFHPA {
    bool KGEJAOIMOBK = 2;
    uint32 CBGODLHCLPK = 3;
    repeated BLODLKIBCIE GEFLCFHPNJH = 6;
    uint32 MDAIPFLCNAJ = 7;
    uint32 HGBLLINAMLN = 11;
    uint32 DNNCAGJIOAP = 12;
    bool BNBCGFOBIPH = 13;
    uint32 GAIJNEMFDBP = 14;
}

message BLODLKIBCIE {
    repeated BLODLKIBCIE LEGEGIHKLFK = 2;
    uint32 BOGIJENAEHJ = 9;
    uint32 ELAENNLBEDD = 11;
}

enum CmdHeliobusType {
    CmdHeliobusType_NLCDGIPGFDJ = 0;
    CmdHeliobusType_HeliobusSnsCommentCsReq = 5826;
    CmdHeliobusType_HeliobusUpgradeLevelScRsp = 5838;
    CmdHeliobusType_HeliobusLineupUpdateScNotify = 5872;
    CmdHeliobusType_HeliobusSelectSkillScRsp = 5811;
    CmdHeliobusType_HeliobusSnsUpdateScNotify = 5871;
    CmdHeliobusType_HeliobusUpgradeLevelCsReq = 5833;
    CmdHeliobusType_HeliobusSnsPostCsReq = 5888;
    CmdHeliobusType_HeliobusActivityDataScRsp = 5878;
    CmdHeliobusType_HeliobusStartRaidCsReq = 5865;
    CmdHeliobusType_HeliobusInfoChangedScNotify = 5840;
    CmdHeliobusType_HeliobusSnsCommentScRsp = 5813;
    CmdHeliobusType_HeliobusSnsLikeCsReq = 5886;
    CmdHeliobusType_FPFHEFOLKBL = 5845;
    CmdHeliobusType_HeliobusSnsReadScRsp = 5858;
    CmdHeliobusType_HeliobusChallengeUpdateScNotify = 5842;
    CmdHeliobusType_HeliobusStartRaidScRsp = 5830;
    CmdHeliobusType_HeliobusActivityDataCsReq = 5825;
    CmdHeliobusType_HeliobusSnsReadCsReq = 5893;
    CmdHeliobusType_HeliobusSnsLikeScRsp = 5847;
    CmdHeliobusType_FLPCDJFJHHM = 5804;
    CmdHeliobusType_HeliobusEnterBattleScRsp = 5869;
    CmdHeliobusType_HeliobusUnlockSkillScNotify = 5839;
    CmdHeliobusType_HeliobusSnsPostScRsp = 5881;
}

message HeliobusActivityDataCsReq {
}

message HeliobusActivityDataScRsp {
    uint32 OMMNAFNIKPH = 2;
    uint32 level = 3;
    ONBLLGHELOB skill_info = 4;
    repeated HeliobusChallengeData challenge_list = 5;
    repeated BGOMIHEFHPA AAHPCIOOLHB = 6;
    uint32 phase = 7;
    uint32 retcode = 10;
    uint32 AFMLOAPAAPM = 12;
    uint32 IMGDMDDKHDL = 13;
    repeated HeliobusChallengeLineup DJKMBPEFCKL = 14;
}

message HeliobusChallengeData {
    uint32 challenge_id = 5;
    bool DBPNANBMGFE = 10;
    uint32 star = 12;
}

message HeliobusChallengeLineup {
    repeated uint32 avatar_id_list = 4;
    uint32 group_id = 8;
    uint32 skill_id = 9;
}

message HeliobusChallengeUpdateScNotify {
    HeliobusChallengeData OCDLPDDMCLP = 10;
}

message HeliobusEnterBattleScRsp {
    SceneBattleInfo battle_info = 2;
    uint32 event_id = 4;
    uint32 retcode = 10;
}

message HeliobusInfoChangedScNotify {
    uint32 IMGDMDDKHDL = 3;
    uint32 OMMNAFNIKPH = 4;
    repeated BGOMIHEFHPA KGKLBGOADCE = 12;
    uint32 phase = 13;
}

message HeliobusLineupUpdateScNotify {
    HeliobusChallengeLineup lineup = 11;
}

message HeliobusSelectSkillScRsp {
    uint32 skill_id = 2;
    uint32 retcode = 13;
}

message HeliobusSnsCommentCsReq {
    uint32 BOGIJENAEHJ = 1;
    uint32 CBGODLHCLPK = 4;
    uint32 JKGKPABHDCH = 5;
}

message HeliobusSnsCommentScRsp {
    uint32 retcode = 3;
    BGOMIHEFHPA AMFEFIDDMDA = 14;
}

message HeliobusSnsLikeCsReq {
    uint32 CBGODLHCLPK = 7;
}

message HeliobusSnsLikeScRsp {
    uint32 retcode = 6;
    uint32 CBGODLHCLPK = 11;
    bool KGEJAOIMOBK = 13;
}

message HeliobusSnsPostCsReq {
    uint32 MDAIPFLCNAJ = 5;
    uint32 CBGODLHCLPK = 10;
    uint32 DNNCAGJIOAP = 11;
}

message HeliobusSnsPostScRsp {
    uint32 retcode = 3;
    BGOMIHEFHPA AMFEFIDDMDA = 7;
}

message HeliobusSnsReadCsReq {
    uint32 CBGODLHCLPK = 7;
}

message HeliobusSnsReadScRsp {
    uint32 retcode = 3;
    uint32 CBGODLHCLPK = 11;
}

message HeliobusSnsUpdateScNotify {
    repeated BGOMIHEFHPA KGKLBGOADCE = 7;
}

message HeliobusStartRaidCsReq {
    uint32 skill_id = 1;
    bool is_save = 9;
    uint32 raid_id = 10;
    uint32 prop_entity_id = 12;
    uint32 DNOAEPDPHKK = 14;
    repeated uint32 avatar_list = 15;
}

message HeliobusStartRaidScRsp {
    uint32 retcode = 1;
    GEGLJDELBHA scene = 5;
}

message HeliobusUnlockSkillScNotify {
    uint32 skill_id = 1;
    uint32 ENGEPMPCJPC = 9;
}

message HeliobusUpgradeLevelCsReq {
}

message HeliobusUpgradeLevelScRsp {
    uint32 retcode = 1;
    uint32 level = 5;
}

message ONBLLGHELOB {
    repeated uint32 NGONANKBKMF = 1;
    uint32 ENGEPMPCJPC = 6;
}
