syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ChangeScriptEmotionCsReq {
    HeartDialEmotionType target_emotion_type = 3;
    uint32 BLKFCFGMMBD = 8;
    uint32 script_id = 15;
}

message ChangeScriptEmotionScRsp {
    HeartDialEmotionType emotion_type = 2;
    uint32 retcode = 3;
    uint32 script_id = 15;
}

enum CmdHeartdialType {
    CmdHeartdialType_NLCDGIPGFDJ = 0;
    CmdHeartdialType_KBBEFEENEMM = 6388;
    CmdHeartdialType_ChangeScriptEmotionScRsp = 6358;
    CmdHeartdialType_HeartDialScriptChangeScNotify = 6326;
    CmdHeartdialType_SubmitEmotionItemScRsp = 6381;
    CmdHeartdialType_GetHeartDialInfoCsReq = 6325;
    CmdHeartdialType_HeartDialTraceScriptCsReq = 6313;
    CmdHeartdialType_FinishEmotionDialoguePerformanceScRsp = 6347;
    CmdHeartdialType_HeartDialTraceScriptScRsp = 6371;
    CmdHeartdialType_ChangeScriptEmotionCsReq = 6393;
    CmdHeartdialType_FinishEmotionDialoguePerformanceCsReq = 6386;
    CmdHeartdialType_GetHeartDialInfoScRsp = 6378;
}

message EAJEMNNNEBM {
    uint32 LLIOEMOBFGD = 10;
    uint32 script_id = 12;
}

message FinishEmotionDialoguePerformanceCsReq {
    uint32 script_id = 2;
    uint32 BLKFCFGMMBD = 3;
    uint32 dialogue_id = 11;
}

message FinishEmotionDialoguePerformanceScRsp {
    uint32 retcode = 5;
    uint32 script_id = 7;
    ItemList reward_list = 8;
    uint32 dialogue_id = 12;
}

message GetHeartDialInfoCsReq {
}

message GetHeartDialInfoScRsp {
    repeated HeartDialScriptInfo script_info_list = 3;
    repeated HeartDialDialogueInfo dialogue_info_list = 4;
    HeartDialUnlockStatus unlock_status = 7;
    uint32 retcode = 9;
    repeated EAJEMNNNEBM EBLMNLBBFNL = 14;
}

message HeartDialDialogueInfo {
    bool GDPHOIMONLN = 12;
    uint32 dialogue_id = 14;
}

enum HeartDialEmotionType {
    HEART_DIAL_EMOTION_TYPE_PEACE = 0;
    HEART_DIAL_EMOTION_TYPE_ANGER = 1;
    HEART_DIAL_EMOTION_TYPE_HAPPY = 2;
    HEART_DIAL_EMOTION_TYPE_SAD = 3;
}

message HeartDialScriptChangeScNotify {
    repeated EAJEMNNNEBM EBLMNLBBFNL = 6;
    repeated HeartDialDialogueInfo changed_dialogue_info_list = 7;
    HeartDialUnlockStatus unlock_status = 12;
    repeated HeartDialScriptInfo changed_script_info_list = 15;
}

message HeartDialScriptInfo {
    uint32 script_id = 5;
    bool EEKCKFGHGEH = 11;
    HeartDialStepType step = 12;
    HeartDialEmotionType cur_emotion_type = 14;
    bool LHCOJIEBFFM = 15;
}

enum HeartDialStepType {
    HeartDialStepType_COEEJALELPF = 0;
    HeartDialStepType_BADPBGFJPNN = 1;
    HeartDialStepType_game_lock_info = 2;
    HeartDialStepType_CCJMKNNHKKE = 3;
    HeartDialStepType_BEJEBBNFGPM = 4;
    HeartDialStepType_NGNFOIHNLMJ = 5;
}

message HeartDialTraceScriptCsReq {
    EAJEMNNNEBM NDPMEMLJGCK = 6;
}

message HeartDialTraceScriptScRsp {
    EAJEMNNNEBM NDPMEMLJGCK = 3;
    uint32 retcode = 7;
}

enum HeartDialUnlockStatus {
    HEART_DIAL_UNLOCK_STATUS_LOCK = 0;
    HEART_DIAL_UNLOCK_STATUS_UNLOCK_SINGLE = 1;
    HEART_DIAL_UNLOCK_STATUS_UNLOCK_ALL = 2;
}

message SubmitEmotionItemScRsp {
    uint32 retcode = 4;
    uint32 script_id = 5;
}
