syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AMPMJPCFLND {
    TurnFoodSwitch KLAJGAKAFCP = 3;
    bool is_open = 12;
}

message AddEquipmentScRsp {
    uint32 KAJCFPKEGBP = 13;
}

message AddRelicFilterPlanCsReq {
    bool is_marked = 7;
    KJDLIPEIAAK icon = 9;
    string name = 11;
    BNAILMNNGIF settings = 12;
    uint32 GFEENEDNJGF = 15;
}

message AddRelicFilterPlanScRsp {
    uint32 retcode = 1;
    GABKFNAJIDD relic_plan = 8;
}

message BKGPJOBNMKJ {
    uint32 num = 5;
    uint32 tid = 8;
    uint64 expire_time = 14;
}

message BNAILMNNGIF {
    uint32 AGPFHDNOBEN = 1;
    repeated uint32 DCFGIEJAILL = 2;
    repeated uint32 KLKADPNPNHI = 3;
    repeated uint32 NBINKKOFKED = 4;
    repeated uint32 PLJEJGCEKGL = 5;
    repeated uint32 HBLKPAJPPEC = 6;
    bool IHABNJLBNBL = 7;
    uint32 MNNLNOJNPBP = 8;
    repeated uint32 BOPGCJOMKGE = 9;
    repeated uint32 CLNIFBCKJPE = 10;
    repeated uint32 MPBDKLFAPCH = 11;
}

message CancelMarkItemNotify {
    uint32 item_id = 8;
}

enum CmdItemType {
    CmdItemType_NLCDGIPGFDJ = 0;
    CmdItemType_GetRecyleTimeScRsp = 521;
    CmdItemType_LMGDHOHBDPF = 535;
    CmdItemType_OBCPFMLDLGB = 542;
    CmdItemType_GetBagCsReq = 525;
    CmdItemType_ComposeLimitNumCompleteScNotify = 505;
    CmdItemType_GetBagScRsp = 578;
    CmdItemType_GKJEAMCIEHI = 586;
    CmdItemType_DeleteRelicFilterPlanCsReq = 546;
    CmdItemType_GetRelicFilterPlanCsReq = 514;
    CmdItemType_ExpUpEquipmentCsReq = 571;
    CmdItemType_PPNGKFOEJGD = 574;
    CmdItemType_GetBigDataRecommendForLightConeCsReq = 566;
    CmdItemType_LockRelicCsReq = 511;
    CmdItemType_GetMarkItemListCsReq = 529;
    CmdItemType_LockEquipmentScRsp = 581;
    CmdItemType_MarkRelicFilterPlanCsReq = 528;
    CmdItemType_MFCMIAMBBEC = 506;
    CmdItemType_EquipmentQuickUpCsReq = 527;
    CmdItemType_RankUpEquipmentScRsp = 513;
    CmdItemType_IOOGNEIAKHD = 526;
    CmdItemType_LockRelicScRsp = 536;
    CmdItemType_GetRelicFilterPlanScRsp = 589;
    CmdItemType_ExchangeHcoinCsReq = 565;
    CmdItemType_DiscardRelicScRsp = 515;
    CmdItemType_ExpUpRelicCsReq = 539;
    CmdItemType_AddEquipmentScRsp = 580;
    CmdItemType_ExpUpEquipmentScRsp = 540;
    CmdItemType_RechargeSuccNotify = 569;
    CmdItemType_ComposeLimitNumUpdateScNotify = 541;
    CmdItemType_ComposeSelectedRelicScRsp = 572;
    CmdItemType_NHEPOMHDCNF = 516;
    CmdItemType_ExpUpRelicScRsp = 504;
    CmdItemType_ComposeItemCsReq = 533;
    CmdItemType_ModifyRelicFilterPlanScRsp = 551;
    CmdItemType_SetTurnFoodSwitchScRsp = 575;
    CmdItemType_MarkItemScRsp = 596;
    CmdItemType_GeneralVirtualItemDataNotify = 544;
    CmdItemType_GetRecycleTimeCsReq = 584;
    CmdItemType_MELJBPCLCLL = 519;
    CmdItemType_LBADMKELDFB = 562;
    CmdItemType_SellItemScRsp = 545;
    CmdItemType_PromoteEquipmentScRsp = 558;
    CmdItemType_ExchangeHcoinScRsp = 530;
    CmdItemType_LockEquipmentCsReq = 588;
    CmdItemType_DestroyItemScRsp = 543;
    CmdItemType_AAOJDKEKDAO = 593;
    CmdItemType_MAHFKODPCCB = 555;
    CmdItemType_GetMarkItemListScRsp = 563;
    CmdItemType_CancelMarkItemNotify = 573;
    CmdItemType_AddRelicFilterPlanScRsp = 594;
    CmdItemType_AddRelicFilterPlanCsReq = 582;
    CmdItemType_SellItemCsReq = 548;
    CmdItemType_UseItemScRsp = 547;
    CmdItemType_DiscardRelicCsReq = 549;
    CmdItemType_ComposeItemScRsp = 538;
    CmdItemType_POEGCEBFMAI = 557;
    CmdItemType_KDCMKMJGELA = 537;
    CmdItemType_MarkItemCsReq = 534;
    CmdItemType_EquipmentQuickUpScRsp = 523;
    CmdItemType_SyncTurnFoodNotify = 512;
    CmdItemType_MarkRelicFilterPlanScRsp = 598;
    CmdItemType_DestroyItemCsReq = 510;
}

message ComposeItemCsReq {
    ItemCostData compose_item_list = 3;
    ItemCostData convert_item_list = 13;
    uint32 count = 14;
    uint32 compose_id = 15;
}

message ComposeItemScRsp {
    uint32 count = 1;
    ItemList return_item_list = 3;
    uint32 compose_id = 12;
    uint32 retcode = 15;
}

message ComposeLimitNumCompleteScNotify {
    repeated DPGAHDIJJDL MGLCGPMNHBB = 3;
}

message ComposeLimitNumUpdateScNotify {
    DPGAHDIJJDL PLJFOAPFELP = 4;
}

message ComposeSelectedRelicScRsp {
    uint32 retcode = 5;
    ItemList return_item_list = 9;
    uint32 compose_id = 13;
}

message DPGAHDIJJDL {
    uint32 DJLNCCEIDNO = 5;
    uint32 KAHMGPGPOII = 7;
}

message DestroyItemCsReq {
    uint32 item_id = 1;
    uint32 ADOIMNBAGKC = 2;
    uint32 item_count = 15;
}

message DestroyItemScRsp {
    uint32 retcode = 2;
    uint32 ADOIMNBAGKC = 6;
}

message DiscardRelicCsReq {
    repeated uint32 relic_ids = 1;
    bool DKPCAIGPHNO = 6;
    RelicDiscardType IFEEJKMACHF = 8;
    uint64 KDGCPMGOPPJ = 13;
}

message DiscardRelicScRsp {
    RelicDiscardType IFEEJKMACHF = 3;
    repeated uint32 relic_ids = 5;
    uint32 retcode = 7;
    bool DKPCAIGPHNO = 14;
}

message EMLDLBKPEFD {
    repeated uint32 GGIGDJPFBBP = 5;
    bool NPPKABBJCMI = 14;
}

message EquipmentQuickUpCsReq {
    uint32 equipment_unique_id = 1;
    uint32 IGOOJKMPMDC = 3;
    ItemCostData IDGEEENIMMK = 4;
    ItemCostData BOBOKJBAMNB = 5;
    uint32 KLMIBJIKIBB = 12;
}

message EquipmentQuickUpScRsp {
    repeated PileItem return_item_list = 3;
    uint32 retcode = 6;
}

message ExchangeHcoinCsReq {
    uint32 num = 14;
}

message ExchangeHcoinScRsp {
    uint32 retcode = 3;
    uint32 num = 6;
}

message ExpUpEquipmentCsReq {
    ItemCostData cost_data = 1;
    uint32 equipment_unique_id = 10;
}

message ExpUpEquipmentScRsp {
    repeated PileItem return_item_list = 4;
    uint32 retcode = 14;
}

message ExpUpRelicCsReq {
    ItemCostData cost_data = 5;
    uint32 relic_unique_id = 13;
}

message ExpUpRelicScRsp {
    uint32 retcode = 10;
    repeated PileItem return_item_list = 13;
}

message GABKFNAJIDD {
    BNAILMNNGIF settings = 1;
    KJDLIPEIAAK icon = 2;
    uint32 NPHAJEKCBKF = 5;
    int64 BNCALAMGIOC = 6;
    string name = 10;
    bool is_marked = 11;
    uint32 GFEENEDNJGF = 12;
}

message GeneralVirtualItemDataNotify {
    bool EBLPGLFJNEL = 2;
    repeated PileItem FCNBHBHMFMC = 3;
}

message GetBagCsReq {
}

message GetBagScRsp {
    repeated WaitDelResource wait_del_resource_list = 1;
    repeated uint32 CAMEGAGKPGL = 2;
    repeated Relic relic_list = 3;
    repeated Equipment equipment_list = 4;
    repeated uint32 KOFNOJCMEFA = 5;
    repeated TurnFoodSwitch EOJBFLHBNMB = 6;
    repeated OCKCHBDFGNL FFEGBHJLBNH = 7;
    repeated PileItem PLBLHEKEIJO = 8;
    uint32 retcode = 10;
    repeated BKGPJOBNMKJ NAJFMIIFIEC = 11;
    repeated Material material_list = 13;
    repeated uint32 HGGGFLABDLB = 14;
    repeated BKGPJOBNMKJ CNDODPICGHI = 15;
    repeated NLLLAAEJOBP update_platform_bound_gifts_list = 206;
}

message GetMarkItemListCsReq {
}

message GetMarkItemListScRsp {
    repeated uint32 PEPKCBILIFO = 2;
    uint32 retcode = 13;
}

message GetRecyleTimeScRsp {
    repeated BKGPJOBNMKJ NAJFMIIFIEC = 6;
    uint32 retcode = 15;
}

message GetRelicFilterPlanCsReq {
}

message GetRelicFilterPlanScRsp {
    repeated GABKFNAJIDD JCKBEEKBPHF = 1;
    uint32 retcode = 5;
}

message KJDLIPEIAAK {
    uint32 OLELCDKLPDK = 3;
    bool IFONLBKJGFE = 15;
}

message LJKFPPDFHMH {
    TurnFoodSwitch KLAJGAKAFCP = 1;
    uint32 retcode = 2;
    bool is_open = 11;
}

message LockEquipmentCsReq {
    repeated uint32 LDBMBPBGFHK = 2;
    bool is_locked = 15;
}

message LockEquipmentScRsp {
    uint32 retcode = 1;
}

message LockRelicCsReq {
    bool NPPKABBJCMI = 12;
    bool is_locked = 13;
    repeated uint32 relic_ids = 15;
}

message LockRelicScRsp {
    uint32 retcode = 14;
}

message MGBKBIKLJDN {
    repeated uint32 GGIGDJPFBBP = 2;
    uint32 retcode = 13;
    bool NPPKABBJCMI = 14;
}

message MarkItemCsReq {
    bool ABDJKPCGDHO = 6;
    uint32 item_id = 13;
}

message MarkItemScRsp {
    uint32 retcode = 3;
    uint32 item_id = 4;
    bool ABDJKPCGDHO = 5;
}

message MarkRelicFilterPlanCsReq {
    repeated uint32 GGIGDJPFBBP = 5;
    bool NPPKABBJCMI = 13;
    bool BIJJOJNJHDO = 15;
}

message MarkRelicFilterPlanScRsp {
    uint32 retcode = 2;
    bool BIJJOJNJHDO = 7;
    bool NPPKABBJCMI = 10;
    repeated uint32 GGIGDJPFBBP = 11;
}

message ModifyRelicFilterPlanScRsp {
    int64 BNCALAMGIOC = 4;
    uint32 retcode = 10;
    uint32 NPHAJEKCBKF = 14;
    oneof KKNBOACNCON {
        string name = 7;
        KJDLIPEIAAK MJPKBIGCFOM = 1;
        BNAILMNNGIF LJKNDCIOOCG = 8;
    }
}

message OCKCHBDFGNL {
    uint64 time = 3;
    repeated NKDNFDCFNCP HJMDNLBNPNA = 11;
}

message PromoteEquipmentScRsp {
    uint32 retcode = 13;
}

message RankUpEquipmentScRsp {
    uint32 retcode = 2;
}

message RechargeSuccNotify {
    ItemList item_list = 1;
    string product_id = 3;
    uint64 month_card_out_date_time = 6;
    string price_tier = 11;
}

enum RelicDiscardType {
    PJHKIIDEOOG_ICFONCMFNLG = 0;
    PJHKIIDEOOG_AOBKJJHAHCN = 1;
    PJHKIIDEOOG_OHNJLMFECEN = 2;
}

message SellItemCsReq {
    ItemCostData cost_data = 11;
    bool HNLKAEBKKBL = 12;
}

message SellItemScRsp {
    ItemList return_item_list = 2;
    uint32 retcode = 12;
}

message SyncTurnFoodNotify {
    repeated uint32 CAMEGAGKPGL = 2;
    repeated TurnFoodSwitch EOJBFLHBNMB = 11;
}

enum TurnFoodSwitch {
    FHLEKKNDBBE_NLCDGIPGFDJ = 0;
    FHLEKKNDBBE_attack = 1;
    FHLEKKNDBBE_FJLOGNFECHI = 2;
}

message UseItemScRsp {
    uint32 use_item_id = 2;
    uint32 formula_id = 5;
    uint64 month_card_out_date_time = 10;
    ItemList return_data = 12;
    uint32 use_item_count = 14;
    uint32 retcode = 15;
}
