syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ANAJELDHDBH {
    uint32 key = 2;
    double damage = 14;
}

message AOJEODENHPL {
    uint32 event_id = 5;
    uint32 chapter_index = 7;
    uint32 IKKEJKOGBNO = 8;
    bool has_passed = 11;
    uint32 KJJJPMAPFOH = 13;
}

message APKJENOJIFD {
}

message BABFMGPNOIG {
    uint32 chapter_index = 3;
    uint32 KJJJPMAPFOH = 13;
}

message BBABPMLDJMM {
}

message BBIPCFPDEJN {
    CDABMABJFII reason = 2;
    uint64 GLANPLEGMPG = 12;
}

message BCIMOPDDKHH {
    repeated uint32 FEODDIKPAOA = 10;
    uint32 uid = 12;
}

message BIJEDLPINKH {
}

message BIKNPJPLDAO {
    repeated ANAJELDHDBH HFHJGBHHBKM = 6;
    repeated ANAJELDHDBH FNHDDAMNKCG = 8;
    uint32 MBOBGNPLLOO = 9;
    double total_damage = 12;
    uint32 OBKCFGAJLJJ = 14;
}

message CBNNMKNBLDI {
    uint32 level = 1;
    repeated CHAGFKJEIMI CDMKBCHLPAB = 4;
    uint32 rarity = 7;
    bool is_special = 10;
    uint32 grid_fight_equipment_id = 15;
}

enum CDABMABJFII {
    CDABMABJFII_NLCDGIPGFDJ = 0;
    CDABMABJFII_FEHEGGCOKJH = 2;
    CDABMABJFII_GGMPEGMEHPD = 4;
    CDABMABJFII_MGBCAPIIKLM = 5;
    CDABMABJFII_DILIGFNLNKE = 6;
    CDABMABJFII_BOJIEINFLFF = 7;
}

message CGBPOHBACGE {
    repeated KVP EIEOJFJAIBD = 3;
    uint64 battle_power = 7;
    repeated CGGPJFLLGID FKLPCAPONIA = 10;
    repeated PEPEHIDAKKK avatar_list = 15;
}

message CGGPJFLLGID {
    uint32 JIGOOAEFDPP = 8;
    uint32 level = 11;
}

message CHAGFKJEIMI {
    uint32 offset = 13;
    uint32 LBDLAACOCCN = 14;
}

enum CmdIdleLiveType {
    CmdIdleLiveType_NLCDGIPGFDJ = 0;
    CmdIdleLiveType_GetFriendNewAssistRewardScNotify = 9432;
    CmdIdleLiveType_IdleLiveFinishQuestionTimeoutCsReq = 9448;
    CmdIdleLiveType_ActivityIdleLiveGetDataScRsp = 9428;
    CmdIdleLiveType_KMHAFKKOGBL = 9439;
    CmdIdleLiveType_EBHAHJLGNIJ = 9397;
    CmdIdleLiveType_DressSpecialEquipScRsp = 9392;
    CmdIdleLiveType_IdleLiveUpgradeSlotCsReq = 9401;
    CmdIdleLiveType_IdleLiveHandlePendingEquipCsReq = 9422;
    CmdIdleLiveType_TakeQuestEquipCsRsp = 9387;
    CmdIdleLiveType_StartNodeBattleScRsp = 9431;
    CmdIdleLiveType_IdleLiveUpdateLiveRoomIconCsReq = 9369;
    CmdIdleLiveType_IdleLiveTakeContentRewardCsReq = 9362;
    CmdIdleLiveType_TakeContentScRsp = 9385;
    CmdIdleLiveType_EndDungeonScRsp = 9365;
    CmdIdleLiveType_IdleLiveReplaceTeamCsReq = 9389;
    CmdIdleLiveType_TechTreeChangeNodeStateCsRsp = 9379;
    CmdIdleLiveType_HMJDPMGHEIF = 9395;
    CmdIdleLiveType_IdleLiveDoGachaCsReq = 9413;
    CmdIdleLiveType_IdleLiveEndDungeonCsReq = 9399;
    CmdIdleLiveType_GEEANICAGGJ = 9380;
    CmdIdleLiveType_IdleLiveTakeTaskRewardCsReq = 9391;
    CmdIdleLiveType_COHLLCMCAEB = 9363;
    CmdIdleLiveType_IdleLiveGetFriendDungeonInfoCsReq = 9416;
    CmdIdleLiveType_UpdateCustomInfoScRsp = 9378;
    CmdIdleLiveType_UpgradeTeamSlotCsRsp = 9396;
    CmdIdleLiveType_IdleLiveStartNodeBattleCsReq = 9438;
    CmdIdleLiveType_IdleLiveChangeTechTreeNodeCsReq = 9393;
    CmdIdleLiveType_FinishChapterFinalActScRsp = 9390;
    CmdIdleLiveType_IdleLiveFinishNodeBattleCsReq = 9436;
    CmdIdleLiveType_CHADKCADCJD = 9386;
    CmdIdleLiveType_IdleLiveStartDungeonCsReq = 9425;
    CmdIdleLiveType_IdleLiveTakeQuestEquipCsReq = 9444;
    CmdIdleLiveType_GetFriendDungeonInfoScRsp = 9405;
    CmdIdleLiveType_IdleLiveOpenChestCsReq = 9419;
    CmdIdleLiveType_JDMKGGCKPEL = 9384;
    CmdIdleLiveType_IdleLiveGetStatisticCsReq = 9434;
    CmdIdleLiveType_IdleLiveFinishNodeEventCsReq = 9376;
    CmdIdleLiveType_IdleLiveStartNodeCsReq = 9443;
    CmdIdleLiveType_IdleLiveFinishFinalActCsReq = 9421;
    CmdIdleLiveType_FinishQuestionRsp = 9412;
    CmdIdleLiveType_IdleLiveGetDataCsReq = 9375;
    CmdIdleLiveType_IdleLiveTakeAssistRewardCsReq = 9364;
    CmdIdleLiveType_IdleLiveGetPendingEquipCsReq = 9398;
    CmdIdleLiveType_HandlePendingEquipScRsp = 9430;
    CmdIdleLiveType_ReplaceTeamCsRsp = 9354;
    CmdIdleLiveType_IdleLiveCollectIncomeCsReq = 9361;
    CmdIdleLiveType_TakeTaskRewardScRsp = 9360;
    CmdIdleLiveType_BHEAODAONOG = 9371;
    CmdIdleLiveType_CAECBBBKIIE = 9408;
    CmdIdleLiveType_StartDungeonScRsp = 9394;
    CmdIdleLiveType_SyncChangeCsNotify = 9355;
    CmdIdleLiveType_FGPHAGJEBIG = 9415;
}

enum DBKAAJAEGNM {
    DBKAAJAEGNM_NLCDGIPGFDJ = 0;
    DBKAAJAEGNM_BMOOGBNPEAA = 1;
    DBKAAJAEGNM_CIHFGJDCHIA = 2;
    DBKAAJAEGNM_PDKLDMNAJBO = 3;
}

message DDNJIHCBDDE {
}

message DICEFIGKFCL {
    uint32 BEBLGGDLADJ = 4;
    uint32 BJFNMEJNKIK = 8;
    uint32 LLGKEIPDDMB = 9;
    uint32 HJDNNCOHPJH = 10;
    JBMDMFOCOAK GJLDDMIIILF = 14;
    repeated KJMHIDMOBMB KNEMNAEGKBF = 15;
}

message DMEPOENPEIF {
    uint32 PJODECIGFOI = 2;
}

message DressSpecialEquipScRsp {
    uint32 retcode = 7;
    repeated KVP COLOHMBFKIH = 12;
}

message EBNKDHCIJPH {
    uint32 avatar_id = 7;
    uint32 ANPNFPJDPKP = 10;
    uint32 KBOGFJANBPD = 14;
}

message EJJBHFOLCEA {
    uint32 NJKHFPICPLK = 3;
    uint32 DLILJLGKBEK = 7;
    uint32 OLAAFALFKIH = 12;
}

message EMCJBMOICJN {
    HANHLKIHCJH BOOIAMNBFND = 1;
    PIOJJEGMOOF FNBMIGIICEK = 2;
    uint32 retcode = 3;
    PFPHKOAFPCJ AIBHMDPILKE = 4;
    CGBPOHBACGE MKAGCFGNPGD = 5;
    EJJBHFOLCEA JJKKMGKNCJA = 8;
    JDDFIGPOKHC HKLNGMHFICM = 9;
    IIPIFJCOIFO GNPHKFCKNOP = 10;
    HIDCLKLDHLE HFBBOHBKBJE = 11;
    IGOGKCCOIIF PLFNNLOKBOO = 12;
    PCGMJHKDCOG OPHJAENGBGJ = 13;
    DICEFIGKFCL DNGNEKAMHMD = 15;
}

message EndDungeonScRsp {
    uint32 DHBKGOFBMIM = 2;
    ItemList reward = 6;
    uint32 retcode = 8;
    uint32 EICEKDBENKM = 12;
}

message FAJEJCBILIA {
    uint32 retcode = 11;
    repeated uint32 IKLJBAJBOPG = 12;
}

message FHLEBDMFCHL {
    uint32 content_id = 2;
    LPPKGHJGOCC content_type = 8;
}

message FHMNLHLADJO {
    uint32 AJIMPLLIFIE = 2;
    uint32 FKIIFFFJKJH = 14;
}

message FOMCONFODHH {
    BIKNPJPLDAO HNMLBLGGOLB = 3;
    JDGNMIDMACL GBJEALNCMJC = 10;
}

message FinishQuestionRsp {
    uint32 retcode = 2;
}

message GAIANGFBBPG {
    bool ECBJLAKHOCF = 5;
    uint32 LOFNHPHCCIL = 6;
}

message GetFriendDungeonInfoScRsp {
    repeated OCBPHIBFFAC IOOIIKICFHE = 12;
    uint32 retcode = 13;
}

message GetFriendNewAssistRewardScNotify {
    uint32 FANDKFADKKM = 12;
}

message HANHLKIHCJH {
    repeated uint32 AFACNNLLPMG = 8;
}

message HGPBONMLNAJ {
    uint32 progress = 1;
    uint32 IBEFDOMBEHM = 7;
    DBKAAJAEGNM status = 11;
}

message HIDCLKLDHLE {
    repeated KVP CAOFMHOMMHF = 1;
    JIEKJDGEGDN POLADDGLAEH = 2;
    repeated OOMNNODJGPH NNIAKOLKDFP = 3;
    repeated uint32 HHNNEGILEFB = 4;
}

message HandlePendingEquipScRsp {
    uint32 retcode = 2;
    bool DKPCAIGPHNO = 12;
    KLNNIAHJBCO LJMLJKPLKBN = 13;
}

message IABBGPLBLML {
    uint32 JGFLMODLDCD = 3;
}

message IGGFCPNDMPN {
    oneof BNJPPHJNKHF {
        LJGKDEKCHPJ AONEJBHFKMO = 10;
        uint32 BKJFBHANFLC = 2;
    }
}

message IGOGKCCOIIF {
    uint32 AJIMPLLIFIE = 2;
    uint32 FKIIFFFJKJH = 9;
    string title = 15;
}

message IIPIFJCOIFO {
    HGPBONMLNAJ PJJGPDNKMJH = 12;
}

message JBMDMFOCOAK {
    AOJEODENHPL LMMNDOFIMBN = 6;
    uint32 PGIEEGCGCDI = 8;
}

message JDDFIGPOKHC {
    repeated MGEAPNBMJKJ JHJEJKGFJMN = 1;
}

enum JDGNMIDMACL {
    JDGNMIDMACL_GAIFBJCKGPA = 0;
    JDGNMIDMACL_KGPGDEMEAND = 1;
    JDGNMIDMACL_BPKLGJOBOMA = 2;
    JDGNMIDMACL_IAAOAHFDFLC = 3;
}

message JIEKJDGEGDN {
    bool is_active = 3;
    uint32 PDICFEGEPNM = 4;
    uint32 CJAINJMLDFC = 11;
}

message JLCNOGIJGMH {
    ItemList BPIOEKHMAIC = 2;
    repeated KVP HPCKMFMNOBG = 3;
    uint64 JEAEFMHIIAC = 4;
    JDGNMIDMACL GBJEALNCMJC = 7;
    repeated KVP IOFKDDFNDGC = 10;
    uint32 retcode = 11;
    ItemList DHPPLPJOMNB = 12;
    ItemList reward = 13;
    repeated KVP IBLOFDAGDCE = 15;
}

message KAILIIEEBJM {
    oneof MMCGBGDJIPN {
        PEPEHIDAKKK NBDDJGJOIEH = 12;
        KJMHIDMOBMB BBBEGOLJKHJ = 15;
        uint32 IFDLLJHHOGL = 5;
        HGPBONMLNAJ PJJGPDNKMJH = 9;
        BBIPCFPDEJN KGMIIKKGJFH = 8;
        FHLEBDMFCHL LNGGONNOBHM = 11;
        uint32 NJKHFPICPLK = 14;
        uint32 OLAAFALFKIH = 10;
        uint32 DLILJLGKBEK = 6;
        uint32 FFFBADMIMLF = 13;
        KVP DGBFGDIMKND = 806;
        bool EIJHKECFBLA = 1166;
        JIEKJDGEGDN POLADDGLAEH = 196;
        uint32 NOAKIEIOKIB = 128;
        FHMNLHLADJO HAEIEPPAJFH = 203;
    }
}

message KJMHIDMOBMB {
    uint64 battle_power = 1;
    uint32 chapter_index = 4;
    uint32 captain_num = 5;
    uint32 OAJGKOOFNBL = 11;
    bool is_final_act_finished = 12;
    repeated uint32 IKLJBAJBOPG = 14;
}

message KKGJPMCFDON {
    uint32 gacha_count = 12;
}

message KLNNIAHJBCO {
    CBNNMKNBLDI equip = 2;
    uint32 PNIPCNLLKKD = 6;
    uint32 OJBJHGBEMJN = 15;
}

message LGNJPFPACGH {
    KLNNIAHJBCO LJMLJKPLKBN = 3;
    uint32 retcode = 8;
}

message LJGKDEKCHPJ {
    uint32 MMONAECCLHN = 7;
    uint32 avatar_id = 10;
    uint32 MGBCAPIIKLM = 11;
}

message LMACKMNOJBF {
    JBMDMFOCOAK GJLDDMIIILF = 7;
    uint32 retcode = 14;
}

enum LPPKGHJGOCC {
    LPPKGHJGOCC_NLCDGIPGFDJ = 0;
    LPPKGHJGOCC_CAJPAGKBBML = 1;
    LPPKGHJGOCC_JOKPPELAFOI = 2;
}

message MAAIAFILLFN {
    uint32 retcode = 1;
}

message MGEAPNBMJKJ {
    uint32 KNEJAEFBDED = 6;
    uint32 EICEKDBENKM = 11;
}

message MLBDIPICABB {
    uint32 retcode = 2;
    ItemList reward = 8;
}

message NDMGIMOOFBL {
    repeated KVP HPCKMFMNOBG = 1;
    repeated KVP IOFKDDFNDGC = 4;
    repeated KVP IBLOFDAGDCE = 7;
    uint32 retcode = 9;
    bool ECBJLAKHOCF = 10;
    ItemList reward = 15;
}

message NILCAHCBKAI {
    uint32 retcode = 2;
    repeated IGGFCPNDMPN PGHCLDFGPOA = 5;
    uint32 FOGCAJJOMMK = 6;
    repeated EBNKDHCIJPH APGBCDJHPGL = 14;
}

message NMEMDFOCMFO {
    repeated KVP IOFKDDFNDGC = 1;
    repeated KVP IBLOFDAGDCE = 3;
    repeated KVP HPCKMFMNOBG = 4;
    uint32 PJODECIGFOI = 5;
    uint32 retcode = 7;
}

message NOHKADAPKHE {
    repeated KAODLPJMEFE OILHLECGBCH = 7;
    ItemList reward = 9;
    uint32 retcode = 13;
}

message OCBPHIBFFAC {
    repeated KVP CJDOEPKKJGC = 5;
    uint32 FANDKFADKKM = 6;
    uint32 LNGEAIJIODK = 9;
    uint32 uid = 11;
}

enum OEDABANAJEK {
    OEDABANAJEK_NLCDGIPGFDJ = 0;
    OEDABANAJEK_BPNMABIFCAC = 1;
    OEDABANAJEK_OHLJJBCALBF = 2;
}

message OOMNNODJGPH {
    uint32 NNDNCAEGDFI = 2;
    bool CIHPIAGDHAO = 9;
}

message PCGMJHKDCOG {
    repeated KVP IHJJKABIEPC = 1;
    repeated CBNNMKNBLDI KIDBGNPHGBI = 6;
    repeated uint32 OILPEBPLDBG = 10;
    repeated CBNNMKNBLDI grid_fight_equipment_list = 14;
}

message PDMEKAGOCND {
}

message PEPEHIDAKKK {
    uint32 avatar_id = 2;
    uint32 PMFAHDMLOFK = 6;
}

message PFPHKOAFPCJ {
    uint32 FOGCAJJOMMK = 11;
}

message PIOJJEGMOOF {
    repeated uint32 GBACMOJJKIJ = 15;
}

message ReplaceTeamCsRsp {
    repeated KVP ENCINPIHHDF = 11;
    uint32 retcode = 12;
}

message StartDungeonScRsp {
    repeated BCIMOPDDKHH KMMBNFIFALA = 2;
    uint32 EICEKDBENKM = 3;
    uint32 retcode = 7;
    repeated KVP COLOHMBFKIH = 8;
    repeated KVP ENCINPIHHDF = 15;
}

message StartNodeBattleScRsp {
    uint32 retcode = 5;
    uint32 PGIEEGCGCDI = 11;
    repeated KVP ENCINPIHHDF = 13;
}

message TakeContentScRsp {
    ItemList reward = 4;
    uint32 retcode = 9;
    uint32 content_id = 12;
    LPPKGHJGOCC content_type = 14;
}

message TakeQuestEquipCsRsp {
    uint32 retcode = 1;
    bool DKPCAIGPHNO = 10;
    uint32 quest_id = 14;
}

message TakeTaskRewardScRsp {
    uint32 retcode = 12;
    ItemList reward = 15;
}

message TechTreeChangeNodeStateCsRsp {
    uint32 retcode = 2;
    uint32 CDMFHNGEFCN = 5;
    OEDABANAJEK op_type = 14;
}

message UpdateCustomInfoScRsp {
    uint32 retcode = 10;
    oneof MMCGBGDJIPN {
        string title = 5;
        uint32 AJIMPLLIFIE = 11;
    }
}

message UpgradeTeamSlotCsRsp {
    uint32 level = 3;
    uint32 retcode = 6;
    uint32 JIGOOAEFDPP = 12;
}
