syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdJukeboxType {
    CmdJukeboxType_NLCDGIPGFDJ = 0;
    CmdJukeboxType_JDOHJBCOMKN = 3186;
    CmdJukeboxType_AEOGKBPOCEF = 3193;
    CmdJukeboxType_CKILMDLNFAP = 3147;
    CmdJukeboxType_OJDLNPGPCJN = 3188;
    CmdJukeboxType_UnlockBackGroundMusicScRsp = 3181;
    CmdJukeboxType_JHFCHFCMBPE = 3125;
    CmdJukeboxType_GetJukeboxDataScRsp = 3178;
    CmdJukeboxType_TrialBackGroundMusicScRsp = 3158;
}

message EGDFPDHNOKO {
    uint32 JKFCKJNHLHI = 11;
    uint32 retcode = 13;
}

message FKLMGEFILDI {
    uint32 JKFCKJNHLHI = 15;
}

message GetJukeboxDataScRsp {
    MNCBEDBDDHL GFFOBALDBPM = 1;
    repeated LHHGCDLCJDA IOKAJIBHLMP = 4;
    uint32 retcode = 5;
}

message LHHGCDLCJDA {
    uint32 id = 4;
    uint32 group_id = 8;
    bool BIMDKNLMICG = 11;
}

message UnlockBackGroundMusicScRsp {
    repeated LHHGCDLCJDA IOKAJIBHLMP = 3;
    repeated uint32 BPFGBEBPEDP = 6;
    uint32 retcode = 12;
}
