syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AGDPIOAKFGB {
    uint32 retcode = 12;
    uint32 teleport_id = 13;
}

message ANFMHBGNNEG {
    PJMGBLIFDFP room_ext_info = 15;
}

enum CmdLobbyType {
    CmdLobbyType_NLCDGIPGFDJ = 0;
    CmdLobbyType_LobbyCreateScRsp = 7373;
    CmdLobbyType_PJJBGLIJHIJ = 7365;
    CmdLobbyType_LobbyKickOutCsReq = 7360;
    CmdLobbyType_LobbyModifyPlayerInfoCsReq = 7353;
    CmdLobbyType_KickOutRsp = 7371;
    CmdLobbyType_PMBEKLJENGI = 7369;
    CmdLobbyType_LobbyInviteCsReq = 7370;
    CmdLobbyType_LobbyJoinCsReq = 7387;
    CmdLobbyType_LobbyModifyPlayerInfoScRsp = 7357;
    CmdLobbyType_GFEEMPEJIMH = 7385;
    CmdLobbyType_LobbyQuitCsReq = 7379;
    CmdLobbyType_LobbyGetInfoScRsp = 7364;
    CmdLobbyType_LobbyGetInfoCsReq = 7352;
    CmdLobbyType_OJNIMDFCMAM = 7358;
    CmdLobbyType_LobbyQuitScRsp = 7383;
    CmdLobbyType_LobbyInteractScNotify = 7363;
    CmdLobbyType_LobbyJoinScRsp = 7394;
    CmdLobbyType_PPMLDMMDPCK = 7359;
    CmdLobbyType_NCACLCLAGPM = 7368;
    CmdLobbyType_LobbySyncInfoScNotify = 7374;
    CmdLobbyType_BOJKKDBEFNL = 7367;
    CmdLobbyType_ACOHEGOOIJA = 7398;
}

message DACEFJFGLGM {
}

message GBAKEFGOLCB {
    uint32 stage_id = 1;
    uint32 CDNNHONKELJ = 2;
}

message GJBGNMGGDLE {
    uint32 retcode = 14;
}

message HCLAEGGMCFK {
    uint32 LOPNADHJKBF = 1;
}

message HFAAFFDPBIL {
    uint32 stage_id = 1;
    TeamTowersGameType DLFHABGGHFF = 2;
    uint32 CDNNHONKELJ = 3;
}

message KIGJGMLAMGH {
    uint32 retcode = 12;
}

message LobbyCreateScRsp {
    uint64 room_id = 2;
    uint32 retcode = 5;
    uint32 HDJFGMGAOOF = 7;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 9;
    FightGameMode GJNMHILINHC = 13;
    PJMGBLIFDFP room_ext_info = 14;
}

message LobbyGetInfoCsReq {
}

message LobbyGetInfoScRsp {
    uint32 HDJFGMGAOOF = 1;
    uint32 retcode = 3;
    PJMGBLIFDFP room_ext_info = 4;
    FightGameMode GJNMHILINHC = 5;
    uint64 room_id = 7;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 9;
}

message LobbyInteractScNotify {
    LobbyInteractType DNBKKDBFFAJ = 1;
    uint32 CPOCELOLNHL = 8;
}

enum LobbyInteractType {
    ODPJEOGDIKF_NLCDGIPGFDJ = 0;
    ODPJEOGDIKF_DPMKFJKKKKA = 1;
}

message LobbyInviteCsReq {
    repeated uint32 uid_list = 1;
}

message LobbyJoinCsReq {
    LobbyGameExtInfo JIDKDPPPDPF = 5;
    string JKJCIPFMOHG = 10;
    uint64 room_id = 15;
}

message LobbyJoinScRsp {
    PJMGBLIFDFP room_ext_info = 4;
    uint32 HDJFGMGAOOF = 7;
    FightGameMode GJNMHILINHC = 8;
    uint32 retcode = 10;
    uint64 room_id = 12;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 15;
}

message LobbyKickOutCsReq {
    uint32 uid = 9;
}

message LobbyModifyPlayerInfoCsReq {
    LobbyModifyType type = 9;
    LobbyGameExtInfo JIDKDPPPDPF = 13;
    uint32 GMGJFJCDGGN = 15;
}

message LobbyModifyPlayerInfoScRsp {
    uint32 retcode = 2;
}

enum LobbyModifyType {
    CJHHGHKGAIL_NLCDGIPGFDJ = 0;
    CJHHGHKGAIL_BPOCOHFIAOH = 1;
    CJHHGHKGAIL_HMOGOHOFPFG = 2;
    CJHHGHKGAIL_NCIPEHOHDMG = 3;
    CJHHGHKGAIL_BHMEGEPHBIC = 4;
    CJHHGHKGAIL_EHINOPGCAEE = 5;
    CJHHGHKGAIL_PINPKNJDKLP = 6;
    CJHHGHKGAIL_OIINGMJAHFA = 7;
    CJHHGHKGAIL_ACEBEKCCMEG = 8;
    CJHHGHKGAIL_HIOFMONBFLO = 9;
    CJHHGHKGAIL_NDMLJELOPCM = 10;
    CJHHGHKGAIL_KOKIHLKEJOL = 11;
    CJHHGHKGAIL_CGDOBHJPMHI = 12;
    CJHHGHKGAIL_MNFOFJKGCHL = 13;
    CJHHGHKGAIL_MNPCJLJIKML = 14;
    CJHHGHKGAIL_HDOBALIFGCG = 15;
    CJHHGHKGAIL_HIGMNPCOONG = 16;
    CJHHGHKGAIL_KPKNEPLALOK = 17;
    CJHHGHKGAIL_NGIGCKJNPJC = 18;
}

message LobbyQuitCsReq {
}

message LobbyQuitScRsp {
    uint32 retcode = 4;
}

message LobbySyncInfoScNotify {
    uint32 uid = 3;
    LobbyModifyType type = 5;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 8;
}

message ONNHDODIIED {
    HGMNDBFCBLL DLFHABGGHFF = 1;
}

message OPKKJFEFEIL {
    uint32 teleport_id = 5;
    LobbyInteractType DNBKKDBFFAJ = 9;
}

message PJMGBLIFDFP {
    oneof CGIFMOFGECO {
        HCLAEGGMCFK lobby_grid_fight_info = 1001;
        ONNHDODIIED GOKJCFBPHCJ = 1002;
        GBAKEFGOLCB FNNOPJBPLPF = 1003;
        HFAAFFDPBIL MPNPIIHHFPN = 1004;
    }
}
