syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message ACGBGKFFAOL {
    uint32 retcode = 5;
}

message CPGFNBBIGLH {
    uint32 event_id = 5;
    uint32 param = 10;
    uint32 retcode = 13;
}

enum CmdLimaoNewsType {
    CmdLimaoNewsType_NLCDGIPGFDJ = 0;
    CmdLimaoNewsType_NMCEPGKIIJC = 9202;
    CmdLimaoNewsType_KEOPMNCGEAF = 9199;
    CmdLimaoNewsType_NOGFALFDIHF = 9210;
    CmdLimaoNewsType_AFIKAEMKEFL = 9194;
    CmdLimaoNewsType_JNLFKHPAPJO = 9184;
    CmdLimaoNewsType_CDCJOCAPMBO = 9191;
    CmdLimaoNewsType_KPDNDHNLDBN = 9190;
    CmdLimaoNewsType_MGKFNLIDIMN = 9197;
    CmdLimaoNewsType_POBOGNLNKCJ = 9209;
    CmdLimaoNewsType_NAGIGEBCKKC = 9182;
    CmdLimaoNewsType_OMLIMKCEKKI = 9189;
    CmdLimaoNewsType_CDMGNMFJBKI = 9200;
    CmdLimaoNewsType_OIIMHPFEBGF = 9195;
    CmdLimaoNewsType_FGEBELHDACI = 9188;
    CmdLimaoNewsType_JKLDNBFNOGA = 9192;
    CmdLimaoNewsType_JBOPMLMLMDF = 9201;
    CmdLimaoNewsType_KFIMAMJJEPE = 9205;
    CmdLimaoNewsType_JOGEHJJCHNM = 9207;
    CmdLimaoNewsType_IOBFPKHFFBE = 9183;
    CmdLimaoNewsType_FGBJJJHJFHG = 9181;
    CmdLimaoNewsType_FJKMBBBFDGO = 9198;
    CmdLimaoNewsType_ALJLHGANFEM = 9185;
    CmdLimaoNewsType_LimaoNewsDataChangeScNotify = 9187;
    CmdLimaoNewsType_DCICGFAEBPK = 9186;
    CmdLimaoNewsType_OKDICCOLPLG = 9204;
}

message DDAPICMFDAB {
    bool KBLBFGANMPJ = 3;
    uint32 retcode = 6;
    uint32 CBGODLHCLPK = 11;
}

message EPMONPAABKJ {
    uint32 BOGIJENAEHJ = 4;
    uint32 retcode = 6;
    uint32 CBGODLHCLPK = 8;
}

message FNIDNGOGAFF {
    uint32 IIADKFFPKGP = 4;
    uint32 KPKJALDCMIK = 7;
}

message GHBBMIJFIAD {
    uint32 KPKJALDCMIK = 6;
    uint32 retcode = 12;
}

message GHBKJLIHHGJ {
    uint32 NNDNCAEGDFI = 5;
    uint32 retcode = 7;
}

message HDDBFAIFCGK {
    uint32 LFPABLEIKKE = 6;
    repeated PJPMBOBAMIC EHFHDELPGLN = 13;
}

message JEGNOIJMBCA {
    uint32 retcode = 5;
}

message JKHGDJGBHCD {
    repeated PBLBAAMLNLH JLADELFEHNO = 2;
    repeated uint32 BIGCHMJEPKE = 5;
    uint32 retcode = 6;
    repeated HDDBFAIFCGK IDMHGCAIBNK = 7;
    repeated uint32 BEBLBBEEIGH = 8;
    repeated KJAMNAOLOLL LFEGDDMBLEE = 9;
    bool HIHOBEPGLEJ = 10;
    repeated uint32 KBMHPOBLMKH = 11;
    repeated FNIDNGOGAFF LBBGCNIJMJC = 12;
    uint32 JDGKFGONCJI = 13;
    repeated LGGGHFDBCFN JEFNJEJFPGK = 15;
}

message JPIEAEJIDAO {
    repeated FNIDNGOGAFF LMLLNJBLPGC = 10;
}

message KBAKBMGBNOL {
    uint32 BEOHGAADKPH = 2;
    uint32 retcode = 10;
    bool KBLBFGANMPJ = 13;
}

message KJAMNAOLOLL {
    uint32 MBBGFJGCHGE = 1;
    uint32 LJHGIFGINOL = 12;
}

message LGGGHFDBCFN {
    uint32 KBDOBOODPAK = 2;
    uint32 progress = 6;
    bool has_passed = 9;
    uint32 FDGJLMMEAOF = 13;
}

message LJCBIAEMLDN {
    uint32 retcode = 14;
}

message MAGMMMINOAJ {
    uint32 retcode = 1;
    PBLBAAMLNLH AMFEFIDDMDA = 11;
}

message OCEAHPDAPFC {
    oneof MMCGBGDJIPN {
        uint32 OCJCOOLMCGD = 15;
        PBLBAAMLNLH NOGCKIHEDCE = 3;
        uint32 HOCFMNJPCLI = 12;
        uint32 JGMJFHLIAIL = 11;
        KJAMNAOLOLL IAFPOEBBJIL = 7;
        LGGGHFDBCFN LDBGGNHLFAM = 10;
        JPIEAEJIDAO HDMEPMHHOLP = 14;
        uint32 JDGKFGONCJI = 5;
        uint32 CGEFHJIEKGF = 9;
    }
}

message OFDMHDODALP {
    uint32 retcode = 1;
    uint32 LFPABLEIKKE = 4;
}

message PBLBAAMLNLH {
    uint32 MDJMBGPLCDD = 1;
    uint32 LJHGIFGINOL = 4;
    bool is_unlocked = 6;
    bool BBMCAHOMEFN = 7;
    uint32 BMGBBEMHLIG = 10;
    uint32 CBGODLHCLPK = 12;
    bool KBLBFGANMPJ = 13;
}

message PJPMBOBAMIC {
    bool KBLBFGANMPJ = 9;
    uint32 BEOHGAADKPH = 12;
}

message PNALNDONMCK {
    repeated OCEAHPDAPFC DGNGMJMPFGK = 15;
}
