syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CNCFCDJAFOJ {
    repeated uint32 KLNEDJPADCA = 4;
}

message ChangeLineupLeaderCsReq {
    uint32 slot = 15;
}

message ChangeLineupLeaderScRsp {
    uint32 slot = 6;
    uint32 retcode = 11;
}

enum CmdLineupType {
    CmdLineupType_NLCDGIPGFDJ = 0;
    CmdLineupType_JoinLineupCsReq = 788;
    CmdLineupType_FANJALKAECH = 704;
    CmdLineupType_EIJDLMFMFGO = 736;
    CmdLineupType_BPDMAOANCKF = 726;
    CmdLineupType_ChangeLineupLeaderScRsp = 739;
    CmdLineupType_ExtraLineupDestroyNotify = 772;
    CmdLineupType_GetAllLineupDataCsReq = 745;
    CmdLineupType_SwapLineupScRsp = 713;
    CmdLineupType_GetCurLineupDataCsReq = 793;
    CmdLineupType_JHBHFAODNFG = 786;
    CmdLineupType_MMPOIAMJMPH = 721;
    CmdLineupType_GetLineupAvatarDataScRsp = 733;
    CmdLineupType_SyncLineupNotify = 771;
    CmdLineupType_LFOBDPHHBAI = 781;
    CmdLineupType_SwitchLineupIndexScRsp = 711;
    CmdLineupType_GetCurLineupDataScRsp = 758;
    CmdLineupType_KEHBLKLNKAP = 730;
    CmdLineupType_VirtualLineupTrialAvatarChangeScNotify = 780;
    CmdLineupType_VirtualLineupDestroyNotify = 765;
    CmdLineupType_GetAllLineupDataScRsp = 769;
    CmdLineupType_GetLineupAvatarDataCsReq = 740;
    CmdLineupType_QuitLineupScRsp = 747;
    CmdLineupType_ChangeLineupLeaderCsReq = 738;
    CmdLineupType_SetLineupNameScRsp = 748;
    CmdLineupType_SyncAllPresetLineupNotify = 784;
    CmdLineupType_JoinLineupScRsp = 742;
}

message ExtraLineupDestroyNotify {
    ExtraLineupType extra_lineup_type = 3;
}

message GetAllLineupDataCsReq {
}

message GetAllLineupDataScRsp {
    uint32 retcode = 3;
    uint32 cur_index = 5;
    repeated LineupInfo lineup_list = 7;
}

message GetCurLineupDataCsReq {
}

message GetCurLineupDataScRsp {
    LineupInfo lineup = 10;
    uint32 retcode = 15;
}

message GetLineupAvatarDataCsReq {
}

message GetLineupAvatarDataScRsp {
    uint32 retcode = 11;
    repeated LineupAvatarData avatar_data_list = 15;
}

message JoinLineupCsReq {
    ExtraLineupType extra_lineup_type = 1;
    uint32 slot = 5;
    uint32 base_avatar_id = 8;
    uint32 index = 10;
    uint32 plane_id = 12;
    AvatarType avatar_type = 13;
}

message JoinLineupScRsp {
    uint32 retcode = 9;
}

message LineupAvatarData {
    uint32 hp = 12;
    AvatarType avatar_type = 14;
    uint32 id = 15;
}

message QuitLineupScRsp {
    uint32 retcode = 1;
    bool MFBIPMACFCE = 15;
}

message SetLineupNameScRsp {
    uint32 retcode = 10;
    string name = 12;
    uint32 index = 13;
}

message SwapLineupScRsp {
    uint32 retcode = 12;
}

message SwitchLineupIndexScRsp {
    uint32 retcode = 2;
    uint32 index = 5;
}

message SyncAllPresetLineupNotify {
    repeated LineupInfo lineup_list = 10;
    uint32 cur_index = 13;
}

message SyncLineupNotify {
    LineupInfo lineup = 3;
    repeated SyncLineupReason reason_list = 7;
}

enum SyncLineupReason {
    SYNC_REASON_NONE = 0;
    SYNC_REASON_MP_ADD = 1;
    SYNC_REASON_MP_ADD_PROP_HIT = 2;
    SYNC_REASON_HP_ADD = 3;
    SYNC_REASON_HP_ADD_PROP_HIT = 4;
    SYNC_REASON_MP_MAX_CHANGED_PERMANENT = 5;
    SYNC_REASON_MP_MAX_CHANGED_BY_MODIFIER = 6;
}

message VirtualLineupDestroyNotify {
    uint32 plane_id = 1;
}

message VirtualLineupTrialAvatarChangeScNotify {
    bool OLPNMKAPDLP = 1;
    uint32 plane_id = 5;
    repeated uint32 EDBMIFNEHHH = 7;
    repeated uint32 ILIDIIGALKD = 12;
}
