syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ACIHMMBKMIM {
    uint32 avatar_id = 3;
    AvatarType avatar_type = 12;
}

enum CmdLocalLegendType {
    CmdLocalLegendType_NLCDGIPGFDJ = 0;
    CmdLocalLegendType_LPMAMNPJPCE = 6587;
    CmdLocalLegendType_LocalLegendDataChangeNotify = 6580;
    CmdLocalLegendType_EnterLocalLegendLevelScRsp = 6582;
    CmdLocalLegendType_GetLocalLegendDataScRsp = 6596;
    CmdLocalLegendType_GetLocalLegendDataCsReq = 6583;
}

message EnterLocalLegendLevelScRsp {
    uint32 retcode = 2;
    uint32 DBKHHCGGKNN = 3;
    SceneBattleInfo battle_info = 6;
    uint32 group_id = 15;
}

message GetLocalLegendDataCsReq {
}

message GetLocalLegendDataScRsp {
    uint32 retcode = 9;
    repeated JJEFLBCLBFN level_data_list = 13;
}

message JJEFLBCLBFN {
    uint32 group_id = 1;
    uint32 DBKHHCGGKNN = 9;
    uint32 FFGFINDLMCF = 11;
}

message LocalLegendDataChangeNotify {
    JJEFLBCLBFN level_data = 2;
}
