syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BAEFMEJJIBI {
    uint32 CEAMLKCMMGD = 6;
    GBAEPOLFFMG pos = 11;
}

message BuyNpcStuffCsReq {
    uint32 CEAMLKCMMGD = 7;
}

message BuyNpcStuffScRsp {
    uint32 retcode = 10;
    uint32 CEAMLKCMMGD = 14;
}

message CDNPKGOKEPK {
    repeated uint32 MNBMDLBDCBB = 1;
    uint32 ELAENEOBAJD = 2;
    repeated FFEEHEBBLCI PMIFFBHOOOO = 9;
}

enum CmdMuseumType {
    CmdMuseumType_NLCDGIPGFDJ = 0;
    CmdMuseumType_PGDBMGAFCCN = 4321;
    CmdMuseumType_MuseumRandomEventSelectScRsp = 4330;
    CmdMuseumType_GetMuseumInfoCsReq = 4325;
    CmdMuseumType_SetStuffToAreaScRsp = 4381;
    CmdMuseumType_SyncGetExhibitScNotify = 4313;
    CmdMuseumType_NKEHOBMLIID = 4339;
    CmdMuseumType_SyncMuseumRandomEventStartScNotify = 4348;
    CmdMuseumType_UpgradeAreaStatScRsp = 4304;
    CmdMuseumType_HAACGKDBCOH = 4388;
    CmdMuseumType_FinishCurTurnScRsp = 4340;
    CmdMuseumType_SyncMuseumTargetStartNotify = 4372;
    CmdMuseumType_SyncGetStuffScNotify = 4326;
    CmdMuseumType_TakeCollectRewardRsp = 4305;
    CmdMuseumType_GetMuseumInfoScRsp = 4378;
    CmdMuseumType_FinishCurTurnCsReq = 4371;
    CmdMuseumType_UpgradeAreaScRsp = 4338;
    CmdMuseumType_SyncMuseumFundsChangedScNotify = 4336;
    CmdMuseumType_RemoveStuffFromAreaScRsp = 4347;
    CmdMuseumType_BuyNpcStuffScRsp = 4358;
    CmdMuseumType_CEPFGCAKGKM = 4333;
    CmdMuseumType_BuyNpcStuffCsReq = 4393;
    CmdMuseumType_JAHIGLFGFNM = 4386;
    CmdMuseumType_SyncMuseumInfoChangedScNotify = 4311;
    CmdMuseumType_SyncMuseumTargetMissionFinishNotify = 4380;
    CmdMuseumType_MuseumRandomEventSelectCsReq = 4365;
    CmdMuseumType_SyncMuseumTargetRewardNotify = 4384;
    CmdMuseumType_MuseumRandomEventQueryCsReq = 4345;
    CmdMuseumType_MuseumRandomEventQueryScRsp = 4369;
}

message FCCDKHNGIPH {
    uint32 MLDLNLGBMHN = 1;
    uint32 area_id = 3;
    uint32 FJPJFHPNKBH = 4;
    uint32 PELHCNILCBP = 5;
    uint32 level = 13;
    repeated BAEFMEJJIBI DHIOHIOPCGP = 14;
}

message FEHHKDIIENA {
    uint32 CEAMLKCMMGD = 3;
    uint32 PIKEPJNDJPE = 4;
}

message FFEEHEBBLCI {
    uint32 PKDANDJFAON = 2;
    MuseumRandomEventState state = 3;
    uint32 OMILGFHKGBC = 5;
    uint32 JJBKGGDAGIM = 8;
    uint32 JGPIOFGPBGE = 9;
    repeated uint32 DAHOMKDLEGI = 12;
    uint32 event_id = 14;
}

message FGFJNANBJJI {
    uint32 CLLLEMMKDMB = 5;
    bool is_finish = 10;
}

message FinishCurTurnCsReq {
    uint32 IDFANGELPEE = 15;
}

message FinishCurTurnScRsp {
    uint32 retcode = 14;
}

enum GBAEPOLFFMG {
    GBAEPOLFFMG_NLCDGIPGFDJ = 0;
    GBAEPOLFFMG_FBLHLHCGMKO = 1;
    GBAEPOLFFMG_GNEIJHBGCHG = 2;
    GBAEPOLFFMG_JNKMJKBDGPL = 3;
}

message GetMuseumInfoCsReq {
}

message GetMuseumInfoScRsp {
    uint32 exp = 1;
    KPCNNOGGIDO target = 2;
    repeated uint32 BILNKFBKOBC = 3;
    uint32 cur_fund = 4;
    repeated uint32 ONJEOMGPGLJ = 5;
    uint32 NEHFEBHDGIK = 6;
    CDNPKGOKEPK PKJCHLDHKBL = 7;
    uint32 ONCBJHBKBLB = 8;
    uint32 KAADGPOLIEN = 9;
    uint32 EKGPINKBLED = 11;
    uint32 retcode = 12;
    uint32 level = 13;
    repeated FCCDKHNGIPH area_list = 14;
    repeated FEHHKDIIENA DHIOHIOPCGP = 15;
}

enum GetStuffType {
    FILBJDAJPAA_AADOIEIDPKC = 0;
    FILBJDAJPAA_KLEADAAONJI = 1;
    FILBJDAJPAA_JIJFOLELOHP = 2;
    FILBJDAJPAA_KCMIPOEAKOM = 3;
    FILBJDAJPAA_MFCAHCCMCHA = 4;
    FILBJDAJPAA_DCJDPBHNEEN = 5;
    FILBJDAJPAA_CBECLOHPGNJ = 6;
}

message KPCNNOGGIDO {
    uint32 KFGLDLFBFFB = 6;
    uint32 CLPAAFFFBKK = 7;
    uint32 MJOKDHMJBEH = 9;
    uint32 MGLEKDEAJBB = 10;
    uint32 MLBMDLBKEEM = 12;
    repeated FGFJNANBJJI CBEFDHFFNLN = 15;
}

message MuseumRandomEventQueryCsReq {
}

message MuseumRandomEventQueryScRsp {
    CDNPKGOKEPK info = 8;
    uint32 retcode = 12;
}

message MuseumRandomEventSelectCsReq {
    uint32 event_id = 13;
    uint32 JGPIOFGPBGE = 15;
}

message MuseumRandomEventSelectScRsp {
    uint32 event_id = 1;
    uint32 retcode = 9;
    uint32 JGPIOFGPBGE = 14;
}

enum MuseumRandomEventState {
    NLAEDPNBHBP_NLCDGIPGFDJ = 0;
    NLAEDPNBHBP_NPAFMEBNFOB = 1;
    NLAEDPNBHBP_LOOAKNHDBLL = 2;
    NLAEDPNBHBP_CIHFGJDCHIA = 3;
}

message RemoveStuffFromAreaScRsp {
    uint32 retcode = 5;
    uint32 CEAMLKCMMGD = 15;
}

message SetStuffToAreaScRsp {
    uint32 PIKEPJNDJPE = 5;
    uint32 retcode = 8;
    uint32 CEAMLKCMMGD = 12;
    GBAEPOLFFMG pos = 13;
}

enum StatType {
    GOPHGIHIDPP_NLCDGIPGFDJ = 0;
    GOPHGIHIDPP_INJOMKCIBPI = 1;
    GOPHGIHIDPP_GMKNIIHMCBO = 2;
    GOPHGIHIDPP_HNMLECBEGPB = 3;
}

message SyncGetExhibitScNotify {
    uint32 MMNBPCGIONF = 4;
}

message SyncGetStuffScNotify {
    GetStuffType BAPBMHCHCIC = 3;
    uint32 CEAMLKCMMGD = 4;
}

message SyncMuseumFundsChangedScNotify {
    uint32 cur_fund = 14;
}

message SyncMuseumInfoChangedScNotify {
    uint32 exp = 1;
    uint32 cur_fund = 2;
    KPCNNOGGIDO target = 3;
    uint32 EKGPINKBLED = 5;
    uint32 level = 6;
    uint32 KAADGPOLIEN = 7;
    repeated uint32 ONJEOMGPGLJ = 8;
    repeated FCCDKHNGIPH area_list = 9;
    repeated uint32 BILNKFBKOBC = 10;
    repeated FEHHKDIIENA DHIOHIOPCGP = 11;
    CDNPKGOKEPK PKJCHLDHKBL = 12;
    uint32 NEHFEBHDGIK = 13;
    uint32 ONCBJHBKBLB = 14;
}

message SyncMuseumRandomEventStartScNotify {
    FFEEHEBBLCI info = 7;
}

message SyncMuseumTargetMissionFinishNotify {
    bool MAOMPIDOMIJ = 1;
    repeated uint32 CLLLEMMKDMB = 9;
    uint32 KFGLDLFBFFB = 12;
}

message SyncMuseumTargetRewardNotify {
    uint32 KFGLDLFBFFB = 4;
    uint32 item_count = 6;
    uint32 item_id = 15;
}

message SyncMuseumTargetStartNotify {
    uint32 KFGLDLFBFFB = 1;
}

message TakeCollectRewardRsp {
    uint32 retcode = 3;
    uint32 item_id = 8;
    ItemList reward = 12;
}

message UpgradeAreaScRsp {
    uint32 retcode = 4;
    uint32 level = 6;
    uint32 area_id = 12;
}

message UpgradeAreaStatScRsp {
    StatType GNBKDCHLDGL = 1;
    uint32 retcode = 4;
    uint32 area_id = 10;
    uint32 level = 13;
}
