syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdMarbleType {
    CmdMarbleType_NLCDGIPGFDJ = 0;
    CmdMarbleType_DLJNJFOMAEG = 8288;
    CmdMarbleType_AGDKICBCICD = 8273;
    CmdMarbleType_CCJMIFLJFKC = 8281;
    CmdMarbleType_KHNPGEPLCLD = 8272;
    CmdMarbleType_MarbleShopBuyScRsp = 8287;
    CmdMarbleType_MarbleUpdateShownSealScRsp = 8285;
    CmdMarbleType_MarbleUnlockSealScNotify = 8275;
    CmdMarbleType_MarblePvpDataUpdateScNotify = 8274;
    CmdMarbleType_MarbleGetDataScRsp = 8278;
    CmdMarbleType_JHCDCIKNEEM = 8282;
}

message HAJKEPNEJED {
    uint32 GNAMNBDIEKG = 3;
    repeated uint32 EGCLLKDHIAE = 13;
}

message KBECKAMICJF {
    uint32 GNAMNBDIEKG = 5;
    uint32 retcode = 13;
}

message MarbleGetDataScRsp {
    repeated uint32 IKGIIIJLLBL = 3;
    int32 score_id = 8;
    repeated uint32 LHDIMCDHCEO = 11;
    uint32 retcode = 12;
    repeated uint32 KJJCIMANKOA = 15;
}

message MarblePvpDataUpdateScNotify {
    int32 score_id = 15;
}

message MarbleShopBuyScRsp {
    repeated uint32 EGCLLKDHIAE = 8;
    uint32 retcode = 13;
}

message MarbleUnlockSealScNotify {
    repeated uint32 EGCLLKDHIAE = 10;
}

message MarbleUpdateShownSealScRsp {
    repeated uint32 GFADCIHMDNN = 3;
    uint32 retcode = 10;
}
