syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdMapRotationType {
    CmdMapRotationType_NLCDGIPGFDJ = 0;
    CmdMapRotationType_BGKIMCFIDJP = 6838;
    CmdMapRotationType_IIDKFIGMHHE = 6886;
    CmdMapRotationType_OKNOECBLJHG = 6845;
    CmdMapRotationType_DONNNJLGABE = 6833;
    CmdMapRotationType_EGJJGMJHLHC = 6836;
    CmdMapRotationType_DeployRotatorCsReq = 6888;
    CmdMapRotationType_InteractChargerCsReq = 6893;
    CmdMapRotationType_GMPGIIIILIH = 6878;
    CmdMapRotationType_JBFMGCIDLKE = 6840;
    CmdMapRotationType_BLAKAIFHDMA = 6858;
    CmdMapRotationType_LeaveMapRotationRegionCsReq = 6826;
    CmdMapRotationType_CEOGMABPNGP = 6813;
    CmdMapRotationType_GEEJLMENDGC = 6847;
    CmdMapRotationType_EnterMapRotationRegionCsReq = 6825;
    CmdMapRotationType_GetMapRotationDataCsReq = 6871;
    CmdMapRotationType_FOKPNCMNKDJ = 6848;
    CmdMapRotationType_PMJCDLIOAON = 6881;
    CmdMapRotationType_EJELBNKLFDJ = 6804;
    CmdMapRotationType_OMBDFNNCLHC = 6811;
}

message DNNLHFKKNLM {
    repeated RotaterData CEDGGDFMILP = 4;
}

message DeployRotatorCsReq {
    RotaterData rotater_data = 4;
}

message EnterMapRotationRegionCsReq {
    MotionInfo motion = 3;
    uint32 region_id = 7;
    uint32 JPPMEKJGJFD = 11;
}

message GetMapRotationDataCsReq {
}

message InteractChargerCsReq {
    ChargerInfo charger_info = 5;
}

message LeaveMapRotationRegionCsReq {
    MotionInfo motion = 3;
}
