syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BMJHAHOLEGH {
    uint32 NEKCONMFFFE = 1;
    uint32 KFBIODICKGC = 4;
    uint32 panel_id = 10;
    uint32 total_count = 15;
}

enum CmdMultipleDropType {
    CmdMultipleDropType_NLCDGIPGFDJ = 0;
    CmdMultipleDropType_GetMultipleDropInfoCsReq = 4625;
    CmdMultipleDropType_GetPlayerReturnMultiDropInfoScRsp = 4688;
    CmdMultipleDropType_GetMultipleDropInfoScRsp = 4678;
    CmdMultipleDropType_MultipleDropInfoNotify = 4681;
    CmdMultipleDropType_GetPlayerReturnMultiDropInfoCsReq = 4658;
    CmdMultipleDropType_MultipleDropInfoScNotify = 4693;
}

message GCLPBMPOHLI {
    uint32 FAOAGKPPNGN = 2;
    uint32 JMGPFEGLCGG = 5;
    uint32 panel_id = 8;
    uint32 LFOHEBCNMDP = 11;
}

message GetMultipleDropInfoCsReq {
}

message GetMultipleDropInfoScRsp {
    repeated BMJHAHOLEGH FAFFFJGJHHC = 3;
    uint32 retcode = 10;
    repeated NGLOBFBCGBB MOPAGKNEMOD = 13;
}

message GetPlayerReturnMultiDropInfoCsReq {
}

message GetPlayerReturnMultiDropInfoScRsp {
    uint32 retcode = 2;
    repeated BMJHAHOLEGH FAFFFJGJHHC = 9;
    GCLPBMPOHLI HDLIGGEMOKM = 15;
}

message MultipleDropInfoNotify {
    repeated GCLPBMPOHLI JGALOGDBCKI = 7;
    repeated NGLOBFBCGBB MOPAGKNEMOD = 10;
    repeated BMJHAHOLEGH FAFFFJGJHHC = 13;
}

message MultipleDropInfoScNotify {
    repeated NGLOBFBCGBB MOPAGKNEMOD = 4;
}

message NGLOBFBCGBB {
    uint32 id = 4;
    uint32 CLLFACKFNBO = 11;
}
