syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ALCDAEIDEAM {
    uint32 retcode = 7;
    GAAMBBFPCHB NFEDANFBIBE = 9;
}

message AMKBFMCOIHK {
    CGOGDJKALMH source_type = 9;
    uint32 id = 11;
    DifficultyAdjustmentType ANJMFPKJHOH = 13;
}

message BCBHFBPADEE {
    uint32 JNOPBGBACOO = 4;
    uint32 MGGNKENIPFC = 12;
}

message BKAHEDAHNHL {
    uint32 NBFJHDJBLCF = 13;
    uint32 gold = 15;
}

message BLPLICDMFEL {
    uint32 floor_id = 10;
    repeated MJEIKNGOCJO PEPOGGNCGLD = 14;
}

message BMFLFFJIEFC {
    uint32 retcode = 6;
}

enum BMHIHBHECKD {
    BMHIHBHECKD_NLCDGIPGFDJ = 0;
    BMHIHBHECKD_AONEONHEHNA = 1;
    BMHIHBHECKD_NGCHDKKBACD = 2;
    BMHIHBHECKD_LHCCHLAIAIN = 3;
}

message BPAGBAALHMP {
    uint32 BLMAEGGMCHJ = 3;
    uint32 EGKNHHFDJHM = 10;
    uint32 level = 11;
    bool is_perfect = 14;
}

enum CGOGDJKALMH {
    CGOGDJKALMH_FHFJLAIAGEH = 0;
    CGOGDJKALMH_FMDDNENDJOJ = 1;
    CGOGDJKALMH_JIBJFDIJCNM = 2;
}

message CancelDirectDeliveryNoticeScRsp {
    uint32 retcode = 12;
    uint32 HFHHKGFNGFC = 13;
}

enum CmdMiscModuleType {
    CmdMiscModuleType_NLCDGIPGFDJ = 0;
    CmdMiscModuleType_CycleScoreRewardDestroyExceedRewardCsReq = 4120;
    CmdMiscModuleType_CycleScoreRewardTakeRewardCsReq = 4153;
    CmdMiscModuleType_CycleScoreRewardUpdateInfoScNotify = 4189;
    CmdMiscModuleType_ALEAPGIGDJO = 4130;
    CmdMiscModuleType_CycleScoreRewardRsp = 4118;
    CmdMiscModuleType_LFKEKJMBEJC = 4136;
    CmdMiscModuleType_GetSwitchMascotDataCsReq = 4112;
    CmdMiscModuleType_GetMovieRacingDataScRsp = 4165;
    CmdMiscModuleType_HCIANHKHHKB = 4133;
    CmdMiscModuleType_CycleScoreRewardGetDataCsReq = 4115;
    CmdMiscModuleType_UpdateGunPlayDataScRsp = 4121;
    CmdMiscModuleType_NLLHFDEHAKN = 4138;
    CmdMiscModuleType_FDKEJEECJIC = 4181;
    CmdMiscModuleType_ACELJOANJFJ = 4149;
    CmdMiscModuleType_GetWolfBroShootingDataCsReq = 4172;
    CmdMiscModuleType_GetMovieRacingDataCsReq = 4169;
    CmdMiscModuleType_GCKLEAKDNHB = 4125;
    CmdMiscModuleType_DPADOHAJJJB = 4104;
    CmdMiscModuleType_GetGunPlayDataScRsp = 4180;
    CmdMiscModuleType_GetShareDataCsReq = 4193;
    CmdMiscModuleType_DJFGNHCFMDL = 4188;
    CmdMiscModuleType_CNHFAPDGPPM = 4171;
    CmdMiscModuleType_StageEventDifficultyUpdateDataCsReq = 4110;
    CmdMiscModuleType_CycleScoreRewardTakeRewardScRsp = 4152;
    CmdMiscModuleType_EHMJKOEHEEE = 4113;
    CmdMiscModuleType_MazeKillDirectScRsp = 4163;
    CmdMiscModuleType_DifficultyAdjustmentGetDataScRsp = 4141;
    CmdMiscModuleType_ShareScRsp = 4178;
    CmdMiscModuleType_MazeKillDirectCsReq = 4129;
    CmdMiscModuleType_UpdateMovieRacingDataScRsp = 4142;
    CmdMiscModuleType_GIEFJMJFPDB = 4139;
    CmdMiscModuleType_GetSwitchMascotDataScRsp = 4135;
    CmdMiscModuleType_DifficultyAdjustmentUpdateDataScRsp = 4143;
    CmdMiscModuleType_GetUnreleasedBlockInfoCsReq = 4144;
    CmdMiscModuleType_DirectDeliveryScNotify = 4134;
    CmdMiscModuleType_CancelAutoConversionCacheCsReq = 4126;
    CmdMiscModuleType_DifficultyAdjustmentGetDataCsReq = 4105;
    CmdMiscModuleType_DMPDEBAHNHC = 4140;
    CmdMiscModuleType_CancelDirectDeliveryNoticeScRsp = 4173;
    CmdMiscModuleType_CycleScoreRewardDestroyExceedRewardScRsp = 4114;
    CmdMiscModuleType_FFHFBDONBPD = 4184;
    CmdMiscModuleType_SwitchMascotUpdateScNotify = 4175;
    CmdMiscModuleType_ELPKNAFKEOJ = 4196;
    CmdMiscModuleType_GetOrigamiPropInfoCsReq = 4111;
    CmdMiscModuleType_GetShareDataScRsp = 4158;
}

message DDOOEDOKEPF {
    GAAMBBFPCHB NFEDANFBIBE = 9;
    uint32 retcode = 11;
}

message DifficultyAdjustmentGetDataCsReq {
}

message DifficultyAdjustmentGetDataScRsp {
    repeated AMKBFMCOIHK content_package_list = 3;
    uint32 retcode = 10;
}

enum DifficultyAdjustmentType {
    JNECPMMFEKP_AANHCEGHCFA = 0;
    JNECPMMFEKP_AEDDONPLOFJ = 1;
}

message DifficultyAdjustmentUpdateDataScRsp {
    uint32 retcode = 2;
    repeated AMKBFMCOIHK content_package_list = 7;
    AMKBFMCOIHK data = 10;
}

message DirectDeliveryScNotify {
    uint32 HFHHKGFNGFC = 2;
    repeated ItemList DJOBNPIAEJP = 13;
}

message EABIMAPLLLL {
    GAAMBBFPCHB NFEDANFBIBE = 2;
}

message EHNLGMEGIJP {
    uint32 retcode = 2;
}

enum FDJADOEAOLE {
    FDJADOEAOLE_OIDDFJEFIPF = 0;
    FDJADOEAOLE_AHGEIJFIGKE = 1;
    FDJADOEAOLE_PKHPJIKJMDO = 2;
    FDJADOEAOLE_HFGBOOLJDNA = 3;
    FDJADOEAOLE_ENDLJOAKNPI = 4;
}

message FECGDOJFDIM {
    uint32 retcode = 1;
    repeated uint32 NGKOFMBBGNL = 6;
    GAAMBBFPCHB NFEDANFBIBE = 10;
    ItemList reward = 14;
}

message GAAMBBFPCHB {
    int64 end_time = 3;
    repeated uint32 OPLNKCOLCKJ = 6;
    int64 start_time = 7;
    uint32 PMJGAJGIFOA = 8;
}

message GFGEMCJLGPP {
    uint32 IFMCCMLCBGP = 8;
    repeated uint32 BGJAEJKJCFP = 10;
    uint32 content_id = 12;
}

message GetGunPlayDataScRsp {
    uint32 retcode = 2;
    repeated BPAGBAALHMP OHOLABHLCKL = 13;
}

message GetMovieRacingDataCsReq {
}

message GetMovieRacingDataScRsp {
    repeated HDAHFLMBAAB HNIAEGMMPKD = 5;
    uint32 retcode = 7;
}

message GetShareDataCsReq {
}

message GetShareDataScRsp {
    repeated BCBHFBPADEE MNCJMIOONPE = 3;
    uint32 retcode = 13;
}

message GetSwitchMascotDataCsReq {
    uint32 NBFJHDJBLCF = 13;
}

message GetSwitchMascotDataScRsp {
    repeated BKAHEDAHNHL JNOEHPJJPOF = 8;
    uint32 retcode = 10;
    uint32 NBFJHDJBLCF = 14;
}

message HDAHFLMBAAB {
    uint32 level = 3;
    uint32 HFENOFPKNPJ = 13;
    MovieRacingType type = 14;
    uint32 EGKNHHFDJHM = 15;
}

message IDENFKIJICM {
    uint32 retcode = 10;
}

message INKEEEKKNKF {
    uint32 retcode = 9;
}

message JDAALEACPKL {
    uint32 KPKEBLOEFCP = 3;
}

message JOIGBKBEGOB {
}

message LCBIEJNJDIF {
    repeated uint32 GDCFLPLFJCI = 8;
}

message LIOGDHEFOGD {
}

message MGFAALHCHEF {
    uint32 retcode = 3;
    repeated BLPLICDMFEL CGOJBLPJFAK = 8;
    uint32 IFMCCMLCBGP = 14;
    uint32 content_id = 15;
}

message MJEIKNGOCJO {
    uint32 state = 5;
    uint32 group_id = 6;
    uint32 config_id = 15;
}

message MNCFPNFGAOH {
    repeated OKJCHGLGBHP OKJNBIOKKIB = 5;
}

message MazeKillDirectCsReq {
    repeated uint32 entity_list = 12;
    FDJADOEAOLE source_type = 14;
    uint32 FABPLNCIGPK = 15;
}

message MazeKillDirectScRsp {
    repeated uint32 entity_list = 4;
    uint32 retcode = 12;
}

enum MovieRacingType {
    KKBNKEKDPFM_BIFLGLFOBBM = 0;
    KKBNKEKDPFM_DNKHLGPJNJO = 1;
    KKBNKEKDPFM_FPGEONEKIPD = 2;
    KKBNKEKDPFM_CGMLGHICNPN = 3;
}

message NIALCDGNNLC {
    uint32 retcode = 9;
    uint32 KPKEBLOEFCP = 10;
}

message OKJCHGLGBHP {
    uint32 type = 4;
    repeated uint32 JLNOCDGJDLI = 8;
    uint32 NADCIHPPPBC = 15;
}

message PICONFLHMCD {
    repeated uint32 JKCEBHFIENI = 7;
}

message PIMFFPGEPIO {
    repeated uint32 JALHKMEOOPN = 5;
    repeated string OKFMBDEECCH = 7;
    BMHIHBHECKD type = 8;
}

message ShareScRsp {
    uint32 retcode = 8;
    ItemList reward = 13;
    BCBHFBPADEE NMOKJJMNICM = 15;
}

message SwitchMascotUpdateScNotify {
    bool EBLPGLFJNEL = 11;
    repeated BKAHEDAHNHL JNOEHPJJPOF = 12;
}

message UpdateGunPlayDataScRsp {
    uint32 retcode = 11;
    BPAGBAALHMP AOPPLPDBEHK = 15;
}

message UpdateMovieRacingDataScRsp {
    uint32 retcode = 8;
    HDAHFLMBAAB LJEPIAIDJFC = 13;
}
