syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message APCDHOBPBHA {
    uint32 stage_id = 1;
}

message BCKBEMGGGIF {
    uint32 EECIJBLGLNG = 11;
}

message CEOJGIDJLOA {
    HGMNDBFCBLL DLFHABGGHFF = 1;
}

enum CmdMultiplayerType {
    CmdMultiplayerType_NLCDGIPGFDJ = 0;
    CmdMultiplayerType_BNAPHIHJLBL = 1026;
    CmdMultiplayerType_MultiplayerMatchPlayDataChangeScNotify = 1040;
    CmdMultiplayerType_FightGiveUpScRsp = 1081;
    CmdMultiplayerType_MGJGKJAODIO = 1058;
    CmdMultiplayerType_GetFriendRankingInfoRsp = 1038;
    CmdMultiplayerType_FightGameStateCsReq = 1025;
    CmdMultiplayerType_FightGiveUpCsReq = 1088;
    CmdMultiplayerType_IABBOIKMDLB = 1047;
    CmdMultiplayerType_FightGameStateScRsp = 1078;
    CmdMultiplayerType_FightGameStartScNotify = 1086;
    CmdMultiplayerType_GetMatchPlayDataCsReq = 1013;
    CmdMultiplayerType_JFACCEAOBDM = 1093;
    CmdMultiplayerType_SelfRankChangeNtf = 1039;
    CmdMultiplayerType_MultiplayerGetMatchPlayDataScRsp = 1071;
    CmdMultiplayerType_GetFriendRankingInfoCsReq = 1033;
}

message DGLBOFKGGLL {
    uint32 EECIJBLGLNG = 6;
}

message DLCJPINDIAC {
    uint32 PPOAGPGEAFH = 7;
    uint32 uid = 10;
    oneof KKNBOACNCON {
        DGLBOFKGGLL BJKBADEMEOE = 15;
        PLICOOFLBIB KCICNNFJEAC = 1;
        BCKBEMGGGIF LENBIENEFIB = 11;
        GKJHNGLHOBA ONNAKPKDLHO = 3;
    }
}

message ECOAKLBOLDA {
    uint32 CBFFGFBEFMF = 4;
    uint32 EECIJBLGLNG = 14;
}

message EDLENJAPMBJ {
    uint32 stage_id = 1;
    TeamTowersGameType DLFHABGGHFF = 2;
}

message FightGameStartScNotify {
    repeated LMLNNHKJEIP DFLEOIGPLNM = 1;
    BFBHKJLJJBJ KAEDKFOMADJ = 11;
}

message FightGameStateCsReq {
}

message FightGameStateScRsp {
    OFFMCODMKDL room_ext_info = 5;
    uint32 retcode = 9;
    BFBHKJLJJBJ KAEDKFOMADJ = 12;
    repeated LMLNNHKJEIP DFLEOIGPLNM = 13;
}

message GKJHNGLHOBA {
    uint32 CJPDGBPLFIG = 9;
    bool GLEJFCIOMKC = 10;
    uint32 EECIJBLGLNG = 11;
}

message GetFriendRankingInfoCsReq {
    FightGameMode GJNMHILINHC = 15;
}

message GetFriendRankingInfoRsp {
    uint32 retcode = 7;
    FightGameMode GJNMHILINHC = 11;
    repeated DLCJPINDIAC MLPHLIHFGKG = 13;
}

message GetMatchPlayDataCsReq {
    repeated FightGameMode LCCHAKBKAHL = 15;
}

message HFFCEACMEIG {
    BFBHKJLJJBJ KAEDKFOMADJ = 4;
}

message HPGIGMPBIBO {
    uint32 retcode = 4;
    string fight_token = 10;
    uint32 port = 12;
    string gate_server_address = 14;
    uint64 FGNFDGAKKAP = 15;
}

message IHGLPGLPDFF {
}

message JCNLJNELKEO {
    uint32 EECIJBLGLNG = 5;
}

message JJAGFPLDCAF {
    uint32 retcode = 9;
}

message JJIJAMHKNGO {
    bool GLEJFCIOMKC = 6;
    uint32 EECIJBLGLNG = 8;
    uint32 CJPDGBPLFIG = 9;
}

message NENHKMEFAEC {
    uint32 BCAKPNCHIIJ = 4;
    NPPEMMILLCO reason = 9;
}

message NFDHOCKEPGD {
    uint32 LOPNADHJKBF = 1;
}

message NLOPJLCMLEN {
}

message OFFMCODMKDL {
    oneof CGIFMOFGECO {
        NFDHOCKEPGD lobby_grid_fight_info = 1001;
        CEOJGIDJLOA GOKJCFBPHCJ = 1002;
        APCDHOBPBHA FNNOPJBPLPF = 1003;
        EDLENJAPMBJ MPNPIIHHFPN = 1004;
    }
}

message OOAHBHODMHG {
    uint32 count = 7;
    uint32 HBONKLEOEEI = 9;
    uint32 LALGADHLMCB = 12;
}

message PJLEILDLONN {
    uint32 EECIJBLGLNG = 10;
    repeated OOAHBHODMHG DBINCLPHEFN = 15;
}

message PLICOOFLBIB {
    uint32 EECIJBLGLNG = 9;
}

message PNEGDOHOLDN {
    uint32 panel_id = 13;
    FightGameMode GJNMHILINHC = 14;
    oneof AELHFLGJMJN {
        PJLEILDLONN ODLONPLECJB = 11;
        ECOAKLBOLDA OCGCLKAHGBK = 4;
        JCNLJNELKEO ICNFMLIAAKE = 6;
        JJIJAMHKNGO GMDCKAOEGNF = 3;
    }
}

message SelfRankChangeNtf {
    FightGameMode GJNMHILINHC = 11;
    repeated DLCJPINDIAC MLPHLIHFGKG = 14;
}
