syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ADNCPPCPLLH {
    repeated uint32 MJMJOMDLOHI = 5;
    uint32 GKKNMDDNOJF = 8;
    uint32 event_id = 9;
    uint32 HAFOKMHCGFM = 11;
}

message AHMFKPIAHCO {
    uint32 DAEKKPOJAJG = 2;
    uint32 KCLCDFGGPBK = 7;
    uint32 ADADGDPCPDN = 8;
    uint32 KJBILOOCBPB = 15;
}

enum BAKAELIMIJI {
    BAKAELIMIJI_NLCDGIPGFDJ = 0;
    BAKAELIMIJI_HEIHBJEEGPB = 1;
    BAKAELIMIJI_BOGGAFJJPGC = 2;
    BAKAELIMIJI_HCEBKFDJGIO = 3;
    BAKAELIMIJI_CBKLDCBEKCH = 4;
    BAKAELIMIJI_LGGEBOCPPDA = 5;
    BAKAELIMIJI_BBDHKAKKBEA = 6;
    BAKAELIMIJI_BFPGGHFAHCA = 7;
    BAKAELIMIJI_PPINCGHOOBH = 8;
    BAKAELIMIJI_JCECCHOJPFK = 9;
    BAKAELIMIJI_JBLEFHFOHGO = 10;
}

message BANELIGFLCO {
    uint32 CBILPMICEKC = 4;
    uint32 level = 10;
    uint32 MFKHDANPCIC = 12;
}

message BBEPMABCBGF {
    uint32 KDFDFBHKCNG = 1;
    uint32 HEIHPAPJHID = 6;
    uint32 DOHOMJBJLLG = 7;
    uint32 uid = 8;
    uint32 OECIPJIPKEG = 9;
}

message BCDIFIIDPIA {
    repeated KFGILGDFEKE BEMBGMOIAON = 12;
}

message CCMCKOKEJNI {
    repeated uint32 HNDAGKPKGHI = 12;
}

message CCOHBABCHAI {
    bool EEDEGBHEKGD = 7;
    uint32 NJFKOEBEGGB = 11;
}

enum CmdMonopolyType {
    CmdMonopolyType_NLCDGIPGFDJ = 0;
    CmdMonopolyType_MonopolyGameSettleScNotify = 7043;
    CmdMonopolyType_MonopolyConfirmRandomScRsp = 7045;
    CmdMonopolyType_GetMbtiReportRewardCsReq = 7059;
    CmdMonopolyType_MonopolyGetRafflePoolInfoScRsp = 7003;
    CmdMonopolyType_MonopolyAcceptQuizScRsp = 7012;
    CmdMonopolyType_GetMbtiReportScRsp = 7098;
    CmdMonopolyType_GetMbtiReportCsReq = 7028;
    CmdMonopolyType_MonopolyContentUpdateScNotify = 7005;
    CmdMonopolyType_GetDailyReportCsReq = 7079;
    CmdMonopolyType_MonopolyCheatDiceScRsp = 7021;
    CmdMonopolyType_MonopolyGuessChooseCsReq = 7075;
    CmdMonopolyType_DeleteSocialEventServerCacheCsReq = 7074;
    CmdMonopolyType_MonopolyLikeCsReq = 7051;
    CmdMonopolyType_MonopolySelectOptionCsReq = 7013;
    CmdMonopolyType_MonopolyCheatDiceCsReq = 7084;
    CmdMonopolyType_GetMonopolyFriendRankingListCsReq = 7094;
    CmdMonopolyType_MonopolyUpgradeAssetCsReq = 7030;
    CmdMonopolyType_MonopolyGetRaffleTicketScRsp = 7083;
    CmdMonopolyType_MonopolyActionResultScNotify = 7093;
    CmdMonopolyType_GetDailyInitItemCsReq = 7085;
    CmdMonopolyType_MCBBINJHOON = 7015;
    CmdMonopolyType_GetJackpotProgressCsReq = 7032;
    CmdMonopolyType_MonopolyReRollRandomCsReq = 7011;
    CmdMonopolyType_MonopolyGiveUpCurContentCsReq = 7072;
    CmdMonopolyType_MonopolyTakeRaffleTicketRewardCsReq = 7095;
    CmdMonopolyType_MonopolyClickCellCsReq = 7087;
    CmdMonopolyType_MonopolyGameBingoFlipCardScRsp = 7096;
    CmdMonopolyType_MonopolyScrachRaffleTicketCsReq = 7060;
    CmdMonopolyType_MonopolyScrachRaffleTicketScRsp = 7090;
    CmdMonopolyType_MonopolyLikeScRsp = 7046;
    CmdMonopolyType_MonopolySelectOptionScRsp = 7071;
    CmdMonopolyType_GetSocialEventServerCacheScRsp = 7006;
    CmdMonopolyType_MonopolySocialEventEffectScNotify = 7055;
    CmdMonopolyType_MonopolyEventLoadUpdateScNotify = 7068;
    CmdMonopolyType_MonopolyGameCreateScNotify = 7035;
    CmdMonopolyType_MonopolyConfirmRandomCsReq = 7048;
    CmdMonopolyType_LBHLKHEKIDN = 7042;
    CmdMonopolyType_MonopolyGameBingoFlipCardCsReq = 7034;
    CmdMonopolyType_ClickMbtiReportCsReq = 7002;
    CmdMonopolyType_MonopolyTakeRaffleTicketRewardScRsp = 7017;
    CmdMonopolyType_MonopolyAcceptQuizCsReq = 7073;
    CmdMonopolyType_MonopolyGuessChooseScRsp = 7044;
    CmdMonopolyType_MonopolyConditionUpdateScNotify = 7031;
    CmdMonopolyType_GetMonopolyMbtiReportRewardScRsp = 7009;
    CmdMonopolyType_TakeJackpotProgressRewardCsReq = 7001;
    CmdMonopolyType_MonopolyBuyGoodsCsReq = 7069;
    CmdMonopolyType_DailyFirstEnterMonopolyActivityScRsp = 7038;
    CmdMonopolyType_GetJackpotInfoCsReq = 7097;
    CmdMonopolyType_GetMonopolyInfoCsReq = 7025;
    CmdMonopolyType_MonopolyGetRaffleTicketCsReq = 7023;
    CmdMonopolyType_MonopolyMoveCsReq = 7047;
    CmdMonopolyType_DailyFirstEnterMonopolyActivityCsReq = 7033;
    CmdMonopolyType_GetMonopolyInfoScRsp = 7078;
    CmdMonopolyType_MonopolyEventSelectFriendScRsp = 7066;
    CmdMonopolyType_DeleteSocialEventServerCacheScRsp = 7057;
    CmdMonopolyType_MonopolyGuessBuyInformationScRsp = 7018;
    CmdMonopolyType_MonopolyRollRandomCsReq = 7039;
    CmdMonopolyType_MonopolyClickCellScRsp = 7024;
    CmdMonopolyType_GetMonopolyDailyReportScRsp = 7007;
    CmdMonopolyType_MonopolyCellUpdateNotify = 7058;
    CmdMonopolyType_MonopolyRollDiceCsReq = 7081;
    CmdMonopolyType_MonopolyRollDiceScRsp = 7086;
    CmdMonopolyType_GetMonopolyFriendRankingListScRsp = 7037;
    CmdMonopolyType_MonopolyLikeScNotify = 7019;
    CmdMonopolyType_MonopolyBuyGoodsScRsp = 7065;
    CmdMonopolyType_IKOKKJHKBML = 7010;
    CmdMonopolyType_MonopolyGiveUpCurContentScRsp = 7080;
    CmdMonopolyType_MonopolyGameGachaScRsp = 7063;
    CmdMonopolyType_MonopolyDailySettleScNotify = 7082;
    CmdMonopolyType_MonopolySttUpdateScNotify = 7091;
    CmdMonopolyType_ClickMbtiReportScRsp = 7100;
    CmdMonopolyType_MonopolyQuizDurationChangeScNotify = 7053;
    CmdMonopolyType_MonopolyGameRaiseRatioCsReq = 7041;
    CmdMonopolyType_MonopolyTakePhaseRewardScRsp = 7064;
    CmdMonopolyType_MonopolyGameGachaCsReq = 7029;
    CmdMonopolyType_MonopolyGuessBuyInformationCsReq = 7049;
    CmdMonopolyType_MonopolyUpgradeAssetScRsp = 7004;
    CmdMonopolyType_MonopolyMoveScRsp = 7026;
    CmdMonopolyType_CEHIPNEEEPN = 7062;
    CmdMonopolyType_MonopolyGetRegionProgressScRsp = 7070;
    CmdMonopolyType_GetSocialEventServerCacheCsReq = 7016;
    CmdMonopolyType_MonopolyGetDailyInitItemScRsp = 7077;
    CmdMonopolyType_MonopolyReRollRandomScRsp = 7036;
}

message DBPHHPGNMKC {
    repeated BANELIGFLCO NPENGFBHFJN = 3;
}

message DCAJAKJAJNL {
    uint32 shop_id = 7;
}

message DCMHLOEGFBM {
    uint32 LCFDOPINEBO = 2;
    ItemList item_list = 7;
    uint32 HABHOAMCGLH = 15;
}

message DDHIEONLIIL {
    bool is_taken_reward = 3;
    bool DDKGKOFAGMH = 8;
    uint64 HEMOHFJJMJG = 15;
}

message DFKABDLJMJO {
    repeated NEMIDPFEJFL PHKBDAHIPEE = 3;
    uint32 KBLJEGIPINF = 5;
}

message DKHCBKNGOMF {
    uint32 MKNLPJMBHDK = 11;
}

message DNBHKLFEMLG {
}

message DailyFirstEnterMonopolyActivityCsReq {
}

message DailyFirstEnterMonopolyActivityScRsp {
    uint32 ICPAPCAJFKK = 2;
    bool GLEJFCIOMKC = 4;
    int64 DJMLHBFEMBE = 7;
    uint32 retcode = 13;
    NJHAGKGHKJJ OLAONLGLAJO = 15;
}

message EDGEHPFOKBH {
    uint32 cnt = 9;
    uint32 ACPKAOIIEHJ = 10;
}

message EIDFCGLODFB {
    uint32 map_id = 2;
    bool BPKMKFLDCAI = 3;
    uint32 IHAOMLEPHOM = 13;
    NADDHEILBBN PIJJDFCBMPG = 15;
}

message EOHAFICJPIP {
    uint32 add_coin = 6;
    uint32 NLGNNDIFGGF = 9;
    uint32 CPOCELOLNHL = 14;
    uint32 id = 15;
}

message EPAIKOHMLDK {
    uint32 retcode = 6;
}

message FIOENGOHOOJ {
    NEMIDPFEJFL MEGBFFOAFGL = 6;
}

message FOOFAIFPOOI {
    repeated GLMGJFEEJHD BGJBAGJAJDL = 4;
    CCOHBABCHAI IBLHLCMNMAJ = 5;
    GLMGJFEEJHD JELODDPELKJ = 13;
}

message GALCNKIAHNN {
    uint32 NLGNNDIFGGF = 1;
    uint32 add_coin = 3;
}

message GDDEAKMJOAP {
    uint32 retcode = 4;
    repeated uint32 FHAIOBNLADG = 13;
}

message GLMGJFEEJHD {
    uint32 ratio = 6;
    uint32 config_id = 11;
    uint32 BAJHKGJPFED = 13;
    oneof JMPNIHHAMPH {
        KDPGIMOOLON AGLMEDOBMAL = 5;
        JGKNADEDNHB LOCHFJEECKL = 10;
        LOEBAOEFMDC COKLIDDAEOH = 7;
    }
}

message GNNGLBEGIKB {
    uint32 DPGJKAHLINH = 2;
    uint32 GCLADEKCJCG = 3;
    uint32 buff_id = 15;
}

message GOLHAKEGKCL {
    uint32 DCPDNBALDOA = 10;
    uint32 HFNNNGHBHGG = 11;
    uint32 item_id = 12;
}

message GPPKIMDCPBM {
    oneof IDLCKHEKCCB {
        GOLHAKEGKCL FIPDBFMPEKH = 9;
        GOLHAKEGKCL AHMEECFKBDJ = 3;
        BANELIGFLCO CBKLDCBEKCH = 1;
        BANELIGFLCO HMOBMBALLJE = 10;
        GNNGLBEGIKB IFOOEPKGGAG = 11;
        GNNGLBEGIKB CMPNCFCJCNE = 5;
        NEAEMNNKKEF DOMHNBMJGHF = 7;
        NEAEMNNKKEF HKAGPIMFPAG = 14;
        CCOHBABCHAI GAJGLONDGMP = 12;
        AHMFKPIAHCO IJBAMMMBIOA = 6;
        GNNGLBEGIKB EBCGEBEPOJJ = 8;
        NEAEMNNKKEF CKBEEBALAEG = 13;
        NOKANMFKNMM LDIGCPKPNBC = 4;
    }
}

message GetMbtiReportCsReq {
}

message GetMbtiReportScRsp {
    bool is_taken_reward = 1;
    repeated HKNBLADLAAE DMCKDIGKHLB = 3;
    bool JMFNGFKBIFL = 5;
    uint32 retcode = 6;
    int32 KHMNANHKINB = 7;
    int32 CJBLDKJDLOJ = 9;
    uint32 progress = 10;
    repeated EDGEHPFOKBH BLINEMKKEOG = 14;
}

message GetMonopolyDailyReportScRsp {
    uint32 retcode = 10;
    NJHAGKGHKJJ OLAONLGLAJO = 12;
}

message GetMonopolyFriendRankingListCsReq {
}

message GetMonopolyFriendRankingListScRsp {
    uint32 retcode = 3;
    repeated BBEPMABCBGF BEDHEKAGAPE = 6;
    BBEPMABCBGF PONAOKBNIAM = 14;
}

message GetMonopolyInfoCsReq {
}

message GetMonopolyInfoScRsp {
    FIOENGOHOOJ MOMEIFPICLE = 1;
    ILMFJKCGBCK COOOMDKGODF = 2;
    DBPHHPGNMKC KKKMHNAPFCP = 3;
    FOOFAIFPOOI PNJBEPAAEOF = 4;
    BCDIFIIDPIA MALPPHCEOGB = 5;
    NJHAGKGHKJJ OLAONLGLAJO = 6;
    uint32 retcode = 7;
    INGKNDHECNF HABJHGPFGEB = 9;
    OCDBIMIBNCD stt = 11;
    CCMCKOKEJNI CICLCCFLALE = 12;
    PDNABFBLEPG OCHNMGMDHME = 13;
    HDDLALFAMKO GKMKAEEDCHP = 14;
    repeated uint32 CANEJDOMAFA = 15;
}

message GetMonopolyMbtiReportRewardScRsp {
    ItemList reward_list = 2;
    uint32 retcode = 13;
}

message GetSocialEventServerCacheCsReq {
}

message GetSocialEventServerCacheScRsp {
    uint32 retcode = 5;
    repeated EOHAFICJPIP OKPHCFLPLGH = 12;
}

message HDDLALFAMKO {
    LAEHICCBBFN KDJACPBDHAE = 6;
    repeated uint32 LPBBJFFNACA = 15;
}

message HIHEHNIAGPF {
    uint32 FBDENECLHIH = 4;
    uint32 progress = 9;
}

message HKNBLADLAAE {
    uint32 MIPKOFFGPFA = 3;
    uint32 event_id = 12;
    uint32 HAFOKMHCGFM = 13;
}

message ILMFJKCGBCK {
    repeated EIDFCGLODFB DGBEOGGJLOO = 2;
    repeated EIDFCGLODFB EGDNFKHLKKE = 6;
    uint32 COKKNEKDJAJ = 8;
    EIDFCGLODFB GOPFOJLIFKN = 9;
    uint32 LJCCANLCGHI = 11;
}

message INGKNDHECNF {
    repeated GNNGLBEGIKB buff_list = 8;
}

message JGKNADEDNHB {
    uint32 KPGNEABOECG = 1;
    uint32 AHAPDFNPICG = 7;
    uint32 GHKNBIOFLGA = 10;
    repeated NNDKLIBALLC OLGHCHMMMIA = 11;
    uint32 KOMEOMHBCEC = 12;
    repeated uint32 HDAKGBMLKKI = 15;
}

message JHIDMEBBKPE {
    repeated uint32 CNILHHCDAKD = 14;
}

message JPEGNCJDBOM {
    uint32 AHAPDFNPICG = 5;
    uint32 AFHMLGFILFN = 7;
    uint32 BLLLEIGDMOI = 13;
}

message KDPGIMOOLON {
    repeated uint32 KNJMPBHKHCJ = 2;
    repeated uint32 PGMHMPEHPHP = 6;
    repeated uint32 JKOOLMNHPHI = 7;
    bool BDEFAFFDBCC = 9;
    uint32 PEDFLGGDHDP = 14;
}

message KFGILGDFEKE {
    uint32 GCPABINOPNJ = 1;
    repeated HIHEHNIAGPF IOFPLHOGBOD = 2;
    repeated DDHIEONLIIL JBKMDKKBFFA = 3;
    uint32 FNFEKIPGKHJ = 5;
    uint32 IJFPHJAPBCO = 6;
    repeated HIHEHNIAGPF MHNLHEIMBLH = 7;
    bool BODENACHCHF = 8;
    repeated HIHEHNIAGPF AMFDDGGEABC = 10;
    uint32 FDOPJGFNMMA = 11;
    repeated HIHEHNIAGPF BADCFEEJKIC = 12;
    uint32 pool_id = 13;
    uint32 NBNCEEGGGFF = 15;
    string MGKCFIFICCF = 157;
    string DANMGAEPGML = 1305;
    string DPIOJAJLOLD = 1683;
}

enum LAEHICCBBFN {
    LAEHICCBBFN_NLCDGIPGFDJ = 0;
    LAEHICCBBFN_HHKFKGKFNJI = 1;
}

message LNCHJBMIMAF {
    uint32 event_id = 14;
}

message LOEBAOEFMDC {
    uint32 HCFJIJHLJDM = 3;
    bool FNFJOCEGFBI = 7;
    uint32 HABHOAMCGLH = 15;
}

message MLBDFEOBKIJ {
    uint32 retcode = 7;
}

message MonopolyAcceptQuizCsReq {
    repeated NNDKLIBALLC OLGHCHMMMIA = 5;
}

message MonopolyAcceptQuizScRsp {
    uint32 retcode = 11;
    JGKNADEDNHB LOCHFJEECKL = 14;
}

message MonopolyActionResult {
    uint32 trigger_cell_id = 4;
    GPPKIMDCPBM detail = 6;
    uint32 click_map_id = 7;
    uint32 click_cell_id = 8;
    uint32 effect_type = 11;
    uint32 trigger_map_id = 13;
    BAKAELIMIJI source_type = 15;
}

message MonopolyActionResultScNotify {
    repeated MonopolyActionResult BKGPGINCHJI = 15;
}

message MonopolyBuyGoodsCsReq {
    uint32 shop_id = 12;
    uint32 goods_id = 14;
}

message MonopolyBuyGoodsScRsp {
    uint32 retcode = 5;
    uint32 goods_id = 13;
    uint32 shop_id = 15;
}

message MonopolyCellUpdateNotify {
    EIDFCGLODFB GOPFOJLIFKN = 6;
}

message MonopolyCheatDiceCsReq {
    uint32 LAGNINIKEAE = 15;
}

message MonopolyCheatDiceScRsp {
    uint32 retcode = 4;
    uint32 LAGNINIKEAE = 15;
}

message MonopolyClickCellCsReq {
    uint32 map_id = 1;
    uint32 IHAOMLEPHOM = 7;
}

message MonopolyClickCellScRsp {
    uint32 IHAOMLEPHOM = 1;
    uint32 map_id = 13;
    uint32 retcode = 14;
}

message MonopolyConditionUpdateScNotify {
    CCMCKOKEJNI CICLCCFLALE = 4;
}

message MonopolyConfirmRandomCsReq {
    uint32 event_id = 10;
}

message MonopolyConfirmRandomScRsp {
    NEMIDPFEJFL MOMEIFPICLE = 2;
    uint32 retcode = 10;
}

message MonopolyContentUpdateScNotify {
    NEMIDPFEJFL MEGBFFOAFGL = 7;
}

message MonopolyDailySettleScNotify {
    NJHAGKGHKJJ OLAONLGLAJO = 10;
    uint32 ICPAPCAJFKK = 11;
}

message MonopolyEventLoadUpdateScNotify {
    repeated EIDFCGLODFB DGBEOGGJLOO = 6;
    repeated EIDFCGLODFB EGDNFKHLKKE = 10;
}

message MonopolyEventSelectFriendScRsp {
    uint32 NLGNNDIFGGF = 2;
    uint32 add_coin = 5;
    uint32 retcode = 8;
}

message MonopolyGameBingoFlipCardCsReq {
    uint32 LKFIGBGPEJB = 5;
}

message MonopolyGameBingoFlipCardScRsp {
    uint32 retcode = 3;
    repeated uint32 KNJMPBHKHCJ = 5;
    bool BDEFAFFDBCC = 11;
    uint32 total_score = 14;
}

message MonopolyGameCreateScNotify {
    CCOHBABCHAI IBLHLCMNMAJ = 7;
    GLMGJFEEJHD AJGOEJHKOKE = 10;
}

message MonopolyGameGachaCsReq {
}

message MonopolyGameGachaScRsp {
    uint32 retcode = 2;
    repeated uint32 CLGGKLNPLCK = 15;
}

message MonopolyGameSettleScNotify {
    ItemList item_list = 9;
    ItemList NGADCEHJHBE = 14;
    GLMGJFEEJHD AJGOEJHKOKE = 15;
}

message MonopolyGetDailyInitItemScRsp {
    uint32 AEDFGDEAOBD = 1;
    int64 DJMLHBFEMBE = 2;
    uint32 FOFGDAJJPEM = 3;
    uint32 MKEDABICJPH = 4;
    uint32 PKLPCBACEMA = 11;
    uint32 retcode = 12;
    uint32 AJDOFHNCOLP = 15;
}

message MonopolyGetRafflePoolInfoScRsp {
    BCDIFIIDPIA MALPPHCEOGB = 3;
    uint32 retcode = 13;
}

message MonopolyGetRaffleTicketCsReq {
    uint32 pool_id = 2;
}

message MonopolyGetRaffleTicketScRsp {
    uint32 pool_id = 6;
    uint32 retcode = 9;
    repeated DDHIEONLIIL HDLPEKIMAJB = 12;
}

message MonopolyGetRegionProgressScRsp {
    uint32 CNGMMDKCBND = 2;
    uint32 retcode = 8;
    uint32 HEIHPAPJHID = 14;
}

message MonopolyGiveUpCurContentCsReq {
    uint32 content_id = 14;
}

message MonopolyGiveUpCurContentScRsp {
    uint32 retcode = 8;
}

message MonopolyGuessChooseCsReq {
    uint32 HCFJIJHLJDM = 13;
}

message MonopolyGuessChooseScRsp {
    uint32 retcode = 1;
    uint32 HCFJIJHLJDM = 10;
}

message MonopolyLikeCsReq {
    uint32 teleport_id = 3;
}

message MonopolyLikeScNotify {
    uint32 DOHOMJBJLLG = 2;
    repeated uint32 LPBBJFFNACA = 3;
}

message MonopolyLikeScRsp {
    uint32 teleport_id = 7;
    ItemList reward_list = 11;
    uint32 retcode = 15;
}

message MonopolyMoveCsReq {
    uint32 AHNGICEEADK = 6;
    uint32 CPFGHPCBFOF = 8;
}

message MonopolyMoveScRsp {
    repeated EIDFCGLODFB AJGMLOIONPK = 3;
    ILMFJKCGBCK COOOMDKGODF = 8;
    uint32 retcode = 9;
}

message MonopolyQuizDurationChangeScNotify {
    repeated JPEGNCJDBOM DGNGMJMPFGK = 1;
}

message MonopolyReRollRandomCsReq {
    uint32 event_id = 1;
}

message MonopolyReRollRandomScRsp {
    uint32 retcode = 2;
    NEMIDPFEJFL MOMEIFPICLE = 12;
}

message MonopolyRollDiceCsReq {
}

message MonopolyRollDiceScRsp {
    uint32 retcode = 1;
    uint32 roll_result = 12;
}

message MonopolyRollRandomCsReq {
    uint32 event_id = 11;
}

message MonopolyScrachRaffleTicketCsReq {
    uint32 pool_id = 5;
    uint64 BBPGHFJOADI = 13;
}

message MonopolyScrachRaffleTicketScRsp {
    uint64 BBPGHFJOADI = 8;
    uint32 pool_id = 10;
    uint32 retcode = 14;
}

message MonopolySelectOptionCsReq {
    uint32 HAFOKMHCGFM = 2;
    uint32 event_id = 12;
}

message MonopolySelectOptionScRsp {
    uint32 event_id = 5;
    uint32 HAFOKMHCGFM = 6;
    repeated HKNBLADLAAE DMCKDIGKHLB = 8;
    NEMIDPFEJFL MOMEIFPICLE = 13;
    uint32 retcode = 15;
}

message MonopolySocialEventEffectScNotify {
    repeated EOHAFICJPIP OKPHCFLPLGH = 12;
}

message MonopolySttUpdateScNotify {
    OCDBIMIBNCD stt = 8;
}

message MonopolyTakePhaseRewardScRsp {
    uint32 retcode = 8;
    repeated uint32 IICEKEPFMJO = 13;
    ItemList reward_list = 15;
}

message MonopolyTakeRaffleTicketRewardCsReq {
    uint32 pool_id = 3;
    uint64 BBPGHFJOADI = 9;
}

message MonopolyTakeRaffleTicketRewardScRsp {
    uint32 retcode = 5;
    uint32 pool_id = 6;
    uint32 BBPGHFJOADI = 7;
    ItemList reward_list = 9;
}

enum NADDHEILBBN {
    NADDHEILBBN_BPOCOHFIAOH = 0;
    NADDHEILBBN_HOPAGBFPBGP = 1;
    NADDHEILBBN_MDJCIKAGEKH = 2;
    NADDHEILBBN_CIHFGJDCHIA = 3;
}

message NCPJGBCCGGI {
    uint32 CBILPMICEKC = 2;
}

message NEAEMNNKKEF {
    uint32 DDFFJEBLCAN = 3;
    uint32 BGKDJKCFEKD = 7;
}

message NEMIDPFEJFL {
    uint32 GCLADEKCJCG = 13;
    oneof BMHHGPHPLJB {
        NIFKIMAANFJ NHONHFPBEBG = 12;
        LNCHJBMIMAF MPBPBBLAHNM = 14;
        ADNCPPCPLLH ONCBJHBKBLB = 6;
        NCPJGBCCGGI CEFDDDAIMMD = 2;
        DCAJAKJAJNL MOFNIOJHBBL = 5;
        DKHCBKNGOMF AJGOEJHKOKE = 10;
        GALCNKIAHNN ENFIEFPPCIC = 3;
        OFPGDJJKGKJ BJHKLNNKPPB = 1;
        DFKABDLJMJO HCLAEGDLOBD = 4;
    }
}

message NHKIADBINML {
    uint32 ratio = 4;
    uint32 retcode = 12;
}

message NIFKIMAANFJ {
    uint32 event_id = 9;
}

message NJHAGKGHKJJ {
    uint32 DBPJBMMGAHH = 1;
    bool DKJBKELKKFO = 2;
    uint32 IFDIIODCFLC = 3;
    uint32 KDFDFBHKCNG = 4;
    uint32 OECIPJIPKEG = 7;
    uint32 EEKPBPFPNIK = 9;
    uint32 JDMNGBJDLBN = 10;
    uint32 HNENMGMGONM = 11;
    uint32 PKHIADLBDDP = 12;
}

message NNDKLIBALLC {
    uint32 JJKPBPLAGAN = 13;
    uint32 KPMHGGHLOHB = 14;
}

message NOKANMFKNMM {
    uint32 PJFPLAFEHKK = 6;
}

message OCDBIMIBNCD {
    repeated uint32 LEIJJGDJECI = 10;
    repeated uint32 POHBLAMKNJH = 15;
}

message OFPGDJJKGKJ {
    uint32 IJJFAPBJMOD = 1;
    repeated uint32 MJMJOMDLOHI = 4;
    uint32 JMBGMIPLLJI = 6;
    uint32 GKKNMDDNOJF = 9;
    uint32 event_id = 11;
}

message OIDPMKIOJGK {
    uint32 CBILPMICEKC = 14;
}

message PDJFKFFPDKI {
    uint32 retcode = 14;
}

message PDNABFBLEPG {
    bool GNIHCOPOLJB = 1;
    uint32 MGJFFPIAOMI = 2;
    uint32 KEEOBECJNIP = 3;
    uint32 item_value = 5;
    uint32 ALMKIPNHAFM = 6;
    bool BLBFMKKBELI = 7;
}

message PILJIHGLHJA {
    uint32 ratio = 1;
}
