syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ALNGMGOJDOA {
    map<uint32, uint32> AEOMEFEMBJI = 7;
    repeated HPIEHAMDJAP MJNNNJPDKDI = 9;
    map<uint32, uint32> GMONIMLFKFC = 12;
    repeated MLHLIMIJHDD DBINCLPHEFN = 15;
}

enum CmdMatchThreeModuleType {
    CmdMatchThreeModuleType_NLCDGIPGFDJ = 0;
    CmdMatchThreeModuleType_PBCJMGFDJHF = 7429;
    CmdMatchThreeModuleType_LKHPOJKAGPC = 7420;
    CmdMatchThreeModuleType_MatchThreeSetBirdPosCsReq = 7448;
    CmdMatchThreeModuleType_MatchThreeV2GetDataScRsp = 7410;
    CmdMatchThreeModuleType_MatchThreeGetDataCsReq = 7409;
    CmdMatchThreeModuleType_MatchThreeV2ScNotify = 7406;
    CmdMatchThreeModuleType_LIIDFPAJNMP = 7414;
    CmdMatchThreeModuleType_MatchThreeV2BattleItemLevelUpScRsp = 7424;
    CmdMatchThreeModuleType_MatchThreeV2SetBirdPosScRsp = 7433;
    CmdMatchThreeModuleType_IDOCIKIILOL = 7407;
    CmdMatchThreeModuleType_MatchThreeV2BattleItemLevelUpCsReq = 7421;
    CmdMatchThreeModuleType_AFFBEPCCEAL = 7403;
    CmdMatchThreeModuleType_MatchThreeLevelEndCsReq = 7437;
    CmdMatchThreeModuleType_MatchThreeGetDataDataScRsp = 7423;
    CmdMatchThreeModuleType_MatchThreeV2LevelEndScRsp = 7417;
    CmdMatchThreeModuleType_MatchThreeSyncDataScNotify = 7419;
    CmdMatchThreeModuleType_MatchThreeV2PvpFinishScNotify = 7402;
    CmdMatchThreeModuleType_MatchThreeLevelEndScRsp = 7444;
}

message DHFGMHFEHEB {
    JKEBEAKOHJJ BJBJLBIOPKA = 13;
    uint32 retcode = 14;
}

message EEHLDBOEFGB {
    LAJGLHCCNED JDFPKAMFHAP = 4;
    uint32 BCAKPNCHIIJ = 5;
    int32 OJNGBIBGHBL = 7;
    NPPEMMILLCO reason = 11;
    FightGameMode game_mode = 12;
}

message HDAOEKOEDHO {
    uint32 pos = 6;
    uint32 retcode = 8;
    uint32 HBONKLEOEEI = 11;
}

message HDKJPKPEJFO {
    uint32 level_id = 4;
    repeated uint32 GKCABEGBOCG = 5;
}

message HPIEHAMDJAP {
    uint32 level_id = 8;
    uint32 KKHPKMAHDMK = 9;
}

message JKEBEAKOHJJ {
    repeated KVP GOBIPJPDBFG = 2;
    repeated KPCHPLEJCKC DBINCLPHEFN = 4;
    repeated KVP KIOIBLGKFCJ = 6;
    repeated HDKJPKPEJFO NKHIIMHCLCD = 8;
    uint32 EECIJBLGLNG = 10;
    repeated KVP BFCMLMLIHHM = 12;
    uint32 JNAOKJKFLHL = 15;
}

message KPCHPLEJCKC {
    uint32 LALGADHLMCB = 7;
    uint32 count = 11;
    uint32 pos = 14;
    uint32 HBONKLEOEEI = 15;
}

message MLHLIMIJHDD {
    uint32 pos = 2;
    uint32 count = 6;
    uint32 HBONKLEOEEI = 7;
    uint32 LALGADHLMCB = 9;
}

message MatchThreeGetDataDataScRsp {
    ALNGMGOJDOA GJFKKFFJDAH = 8;
    uint32 retcode = 14;
}

message MatchThreeLevelEndCsReq {
    map<uint32, uint32> GMONIMLFKFC = 2;
    uint32 KKHPKMAHDMK = 3;
    uint32 HBONKLEOEEI = 4;
    uint32 LALGADHLMCB = 5;
    string uuid = 7;
    uint32 level_id = 11;
}

message MatchThreeLevelEndScRsp {
    uint32 retcode = 3;
    uint32 level_id = 10;
    uint32 KKHPKMAHDMK = 14;
}

message MatchThreeSyncDataScNotify {
    ALNGMGOJDOA GJFKKFFJDAH = 6;
}

message MatchThreeV2BattleItemLevelUpCsReq {
    uint32 IGOOJKMPMDC = 8;
    uint32 FMEHKPKHGJA = 12;
}

message MatchThreeV2BattleItemLevelUpScRsp {
    uint32 FMEHKPKHGJA = 5;
    uint32 retcode = 8;
    uint32 IGOOJKMPMDC = 10;
}

message MatchThreeV2LevelEndScRsp {
    uint32 level_id = 1;
    ItemList DBDIGIEPMBB = 3;
    uint32 JNAOKJKFLHL = 4;
    repeated ItemList DOBNEFKPMPB = 5;
    HDKJPKPEJFO OEIBHLMDJKA = 6;
    KPCHPLEJCKC IEGCHPIHPJN = 7;
    uint32 AFLCNNAJAGB = 11;
    uint32 retcode = 13;
}

message MatchThreeV2PvpFinishScNotify {
    JKEBEAKOHJJ BJBJLBIOPKA = 2;
    LAJGLHCCNED JDFPKAMFHAP = 3;
    NPPEMMILLCO reason = 5;
    uint32 OJNGBIBGHBL = 11;
    FightGameMode game_mode = 13;
    uint32 BCAKPNCHIIJ = 14;
}

message MatchThreeV2ScNotify {
    JKEBEAKOHJJ BJBJLBIOPKA = 5;
}

message MatchThreeV2SetBirdPosScRsp {
    uint32 pos = 5;
    uint32 retcode = 6;
    uint32 HBONKLEOEEI = 10;
    uint32 LIDGCJIKIEG = 12;
}

message PBDKDFCOAPB {
}

message POGMMMGBNCH {
    uint32 HBONKLEOEEI = 8;
    uint32 pos = 14;
}
