syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CancelMatchCsReq {
}

message CancelMatchScRsp {
    uint32 retcode = 1;
}

enum CmdMatchType {
    CmdMatchType_NLCDGIPGFDJ = 0;
    CmdMatchType_StartMatchScRsp = 7323;
    CmdMatchType_GetCrossInfoScRsp = 7303;
    CmdMatchType_CancelMatchCsReq = 7337;
    CmdMatchType_GetCrossInfoCsReq = 7348;
    CmdMatchType_JFMFEFGAIBK = 7309;
    CmdMatchType_CancelMatchScRsp = 7344;
}

message GetCrossInfoCsReq {
}

message GetCrossInfoScRsp {
    uint64 FGNFDGAKKAP = 7;
    uint64 room_id = 9;
    uint32 retcode = 10;
    FightGameMode GJNMHILINHC = 15;
}

message StartMatchScRsp {
    uint32 retcode = 2;
}
