syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CDJKLJDMJHO {
    JBOBHIPHGPB game_data = 3;
    uint32 retcode = 11;
}

message ChenLingGameBoyGetFriendRankingInfoScRsp {
    bool EBAFPOLLJIA = 7;
    uint32 IJCJBDDGGJF = 10;
    repeated NBHDCJHGKCN BEDHEKAGAPE = 12;
    uint32 retcode = 13;
}

enum CmdMazePuzzleType {
    CmdMazePuzzleType_NLCDGIPGFDJ = 0;
    CmdMazePuzzleType_EIFJIFCFLBJ = 9071;
    CmdMazePuzzleType_LCKLCFFIFCC = 9065;
    CmdMazePuzzleType_NBOOGOBHMOE = 9085;
    CmdMazePuzzleType_GetChenLingGameBoyDataScRsp = 9073;
    CmdMazePuzzleType_FiveDimFluteDataChangeNotify = 9068;
    CmdMazePuzzleType_KNLOKAAIGOB = 9083;
    CmdMazePuzzleType_FinishChenLingGameBoyScRsp = 9094;
    CmdMazePuzzleType_JCPGIMAGBHN = 9069;
    CmdMazePuzzleType_MazeCrossFloorConditionChangeScNotify = 9093;
    CmdMazePuzzleType_ChenLingGameBoyChangeSettingsCsReq = 9053;
    CmdMazePuzzleType_IPNFOOJJGMC = 9063;
    CmdMazePuzzleType_LDPOIFPCEHB = 9052;
    CmdMazePuzzleType_ChenLingGameBoyGetFriendRankingInfoScRsp = 9098;
    CmdMazePuzzleType_BDKPNHPGCOI = 9057;
    CmdMazePuzzleType_CCOKCJODLJI = 9058;
    CmdMazePuzzleType_BDFOHFOJBKK = 9074;
    CmdMazePuzzleType_LMGELDDBLDH = 9070;
    CmdMazePuzzleType_FinishFiveDimMiniGameScRsp = 9056;
    CmdMazePuzzleType_GetFiveDimMiniGameDataScRsp = 9079;
    CmdMazePuzzleType_KGMEEFCMPCK = 9067;
    CmdMazePuzzleType_GetFiveDimFluteDataScRsp = 9064;
    CmdMazePuzzleType_JKEBLDNOJGO = 9087;
    CmdMazePuzzleType_DIELFHOLCGG = 9059;
    CmdMazePuzzleType_EEICODKONDH = 9060;
}

message EGJJHFIPCNB {
    uint32 retcode = 9;
    uint32 BAKMHAPCNCJ = 10;
}

message FinishChenLingGameBoyScRsp {
    ItemList reward = 5;
    repeated uint32 DDDGOAEEODC = 7;
    uint32 retcode = 8;
    uint32 IJCJBDDGGJF = 9;
    uint64 HLNODEFLOCF = 12;
    uint64 BEJCJJCLJHL = 15;
}

message FinishFiveDimMiniGameScRsp {
    uint32 BAJHKGJPFED = 1;
    float JAPBBDENKGM = 3;
    ItemList KAFIKBEFKDH = 5;
    uint32 score_id = 6;
    uint32 MGBDFKKMNOL = 7;
    uint32 AKCLEAJAEPA = 8;
    uint32 retcode = 10;
    uint32 gold = 11;
    ItemList DHBABIBHNOG = 12;
    bool ILAFNJNAFIM = 14;
    uint32 CHMBABEJKGE = 15;
}

message FiveDimFluteDataChangeNotify {
    repeated uint32 AOBGMMAIMHJ = 3;
    repeated uint32 NFOBNDJIEPL = 13;
}

message GetChenLingGameBoyDataScRsp {
    JBOBHIPHGPB game_data = 9;
    uint32 retcode = 15;
}

message GetFiveDimFluteDataScRsp {
    repeated uint32 AOBGMMAIMHJ = 1;
    repeated uint32 NFOBNDJIEPL = 8;
    uint32 retcode = 11;
}

message GetFiveDimMiniGameDataScRsp {
    repeated IKHLECEJHPO content_package_list = 8;
    uint32 retcode = 12;
}

message IKHLECEJHPO {
    uint32 OFNNJJNAHHH = 1;
    uint32 BAJHKGJPFED = 12;
}

message JBOBHIPHGPB {
    uint64 HLNODEFLOCF = 2;
    bool HIEMHCBHKEO = 5;
    bool OOMILCOFGPN = 9;
    uint32 IJCJBDDGGJF = 10;
    repeated uint32 CJKAGEDKAFL = 13;
}

message JHEHACPKKBL {
    JBOBHIPHGPB game_data = 1;
    uint32 retcode = 8;
}

message MazeCrossFloorConditionChangeScNotify {
    repeated uint32 HLLLIKPGOFG = 9;
}

message NBHDCJHGKCN {
    uint64 BEJCJJCLJHL = 3;
    uint32 IJCJBDDGGJF = 7;
    uint32 uid = 12;
}

message NCGFPOKHMBL {
    uint32 BAKMHAPCNCJ = 1;
    uint32 retcode = 12;
}

message ONAEGKCMPNN {
    uint32 retcode = 8;
    bool EBAFPOLLJIA = 11;
}
