syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CEDCMIMKJHK {
    uint32 avatar_id = 11;
    bool is_open = 12;
}

enum CmdPlayerReturnType {
    CmdPlayerReturnType_NLCDGIPGFDJ = 0;
    CmdPlayerReturnType_PlayerReturnExtraHcoinProgressScNotify = 4569;
    CmdPlayerReturnType_HIJOOLDBOGH = 4565;
    CmdPlayerReturnType_KLPKEBJGGNC = 4525;
    CmdPlayerReturnType_EHNPLBICNBA = 4526;
    CmdPlayerReturnType_PlayerReturnTakeCustomRelicCsReq = 4539;
    CmdPlayerReturnType_PlayerReturnForceFinishScNotify = 4571;
    CmdPlayerReturnType_PlayerReturnTakeExtraHcoinScNotify = 4538;
    CmdPlayerReturnType_PlayerReturnInfoQueryScRsp = 4513;
    CmdPlayerReturnType_TakeReturnExtraHcoinRewardScRsp = 4545;
    CmdPlayerReturnType_KLMJNOGPEFP = 4548;
    CmdPlayerReturnType_KDMHHNKIKNL = 4578;
    CmdPlayerReturnType_PIFENBGEGLG = 4530;
    CmdPlayerReturnType_PlayerReturnTakePointRewardScRsp = 4581;
    CmdPlayerReturnType_PlayerReturnPointChangeScNotify = 4558;
    CmdPlayerReturnType_PlayerReturnTakeRelicScRsp = 4533;
    CmdPlayerReturnType_PlayerReturnSignScRsp = 4593;
    CmdPlayerReturnType_FIOHCFAGLOK = 4540;
    CmdPlayerReturnType_PlayerReturnTakeCustomRelicScRsp = 4504;
    CmdPlayerReturnType_OGPKAHADKOE = 4588;
    CmdPlayerReturnType_PlayerReturnTakeRewardScRsp = 4547;
    CmdPlayerReturnType_NAEOOKHCMFP = 4586;
}

message FEIHGOEPANI {
    uint32 PKOKBHDLFNM = 3;
}

message IBKDHOIDKJA {
    uint32 KAMECNCKNAB = 1;
    repeated uint32 ELKOPDBOMAD = 2;
    repeated uint32 KMMNJBAEMAB = 3;
    int64 start_time = 4;
    uint32 MODFNPMCAAN = 5;
    bool HHFIEKHFNFP = 6;
    PJIMOBKFDNP status = 7;
    bool is_taken_reward = 8;
    int64 finish_time = 9;
    uint32 world_level = 10;
    uint32 MNMJCNOLIII = 11;
    repeated PileItem NLMEEHNNOCP = 12;
    repeated uint32 KCHPDJINNLH = 13;
    uint32 PDHOMKKMEME = 15;
    uint32 HBPKGODMJNK = 578;
    bool NFFOAHMFCMD = 622;
    uint32 CLALLJOACNF = 751;
    uint32 ACDPGFLDFHK = 862;
    uint32 CFCNIPLEKON = 1101;
    CEDCMIMKJHK BIHNCKPBBOA = 1617;
    bool OCPLGILCPPN = 1696;
}

message KEHOGIENDKC {
    uint32 DACCGMCONBP = 10;
    uint32 AIBJEFAPGMN = 12;
    MMLAPDEBFJM authkey_ver = 15;
}

message KFFEEDHEOOH {
    uint32 ACDPGFLDFHK = 7;
    uint32 retcode = 14;
}

enum MMLAPDEBFJM {
    MMLAPDEBFJM_NLCDGIPGFDJ = 0;
    MMLAPDEBFJM_reward = 1;
    MMLAPDEBFJM_IEIKAPNDPCI = 2;
}

enum PJIMOBKFDNP {
    PJIMOBKFDNP_OPIIMBHECNJ = 0;
    PJIMOBKFDNP_FIKAGKIKFIJ = 1;
    PJIMOBKFDNP_NDBNMMJCAIC = 2;
}

message PlayerReturnExtraHcoinProgressScNotify {
    uint32 HBPKGODMJNK = 10;
}

message PlayerReturnForceFinishScNotify {
    IBKDHOIDKJA NAJPHJOFGBB = 3;
}

message PlayerReturnInfoQueryScRsp {
    IBKDHOIDKJA NAJPHJOFGBB = 2;
    uint32 retcode = 5;
    uint32 HDGPODMDLBL = 15;
}

message PlayerReturnPointChangeScNotify {
    uint32 MNMJCNOLIII = 8;
}

message PlayerReturnSignScRsp {
    repeated KEHOGIENDKC AALGEFBLHEA = 1;
    uint32 retcode = 6;
    repeated ItemList GPFMEDKPEAJ = 13;
}

message PlayerReturnTakeCustomRelicCsReq {
    uint32 avatar_id = 6;
}

message PlayerReturnTakeCustomRelicScRsp {
    uint32 retcode = 6;
    repeated Relic relic_list = 9;
    uint32 avatar_id = 14;
}

message PlayerReturnTakeExtraHcoinScNotify {
    uint32 ONAEMDLNJDA = 3;
    uint32 LHGKNPENJDO = 5;
    bool EAJKAIKEHOL = 8;
}

message PlayerReturnTakePointRewardScRsp {
    ItemList JNJPKNPCMIB = 2;
    uint32 DACCGMCONBP = 4;
    uint32 retcode = 5;
    uint32 GMKKBFHOMCM = 11;
}

message PlayerReturnTakeRelicScRsp {
    ItemList item_list = 4;
    uint32 retcode = 5;
    uint32 avatar_id = 7;
}

message PlayerReturnTakeRewardScRsp {
    uint32 retcode = 4;
    ItemList GPFMEDKPEAJ = 9;
}

message TakeReturnExtraHcoinRewardScRsp {
    uint32 retcode = 10;
    ItemList reward = 13;
    uint32 CFCNIPLEKON = 15;
}
