syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AEGGFGBNLPE {
    bool FOGGEJIIJCM = 7;
}

message AGBPBAOCCJF {
    bool is_win = 7;
}

message ALLFGCIALIJ {
    uint32 JNBIALMKFCL = 4;
    repeated EMHEOJNCGFH grid_fight_equipment_list = 10;
}

message AOPODAHBPFH {
    uint32 content_id = 3;
    uint32 content_type = 14;
}

message BFHPBLANIKG {
    uint32 retcode = 9;
}

message BMOIPALHBJN {
    repeated NJHFBDDHCEN OGDKJPDFFAI = 4;
    uint32 JOMDKGINNEK = 8;
    uint32 shop_id = 11;
    uint32 AAIODNCLAIP = 12;
}

message CCPCAIGEBCB {
    uint32 CCBIIDDBFGK = 12;
}

message CKICDPIJIMF {
    uint32 battle_id = 2;
}

enum CmdPixAirType {
    CmdPixAirType_NLCDGIPGFDJ = 0;
    CmdPixAirType_PixAirReenterStageCsReq = 9777;
    CmdPixAirType_PixAirSellEquipScRsp = 9803;
    CmdPixAirType_PixAirRefreshShopCsReq = 9784;
    CmdPixAirType_PixAirBuyGoodsScRsp = 9772;
    CmdPixAirType_PixAirSwapEquipCsReq = 9790;
    CmdPixAirType_DJFANBNMAKN = 9785;
    CmdPixAirType_PAPOKNOAHMH = 9805;
    CmdPixAirType_PixAirHandlePendingActionScRsp = 9794;
    CmdPixAirType_PixAirGetDataCsReq = 9779;
    CmdPixAirType_PixAirSwapEquipScRsp = 9787;
    CmdPixAirType_PixAirSellEquipCsReq = 9799;
    CmdPixAirType_PixAirQuitStageCsReq = 9818;
    CmdPixAirType_PixAirRefreshShopScRsp = 9788;
    CmdPixAirType_PixAirSyncChangeScNotify = 9807;
    CmdPixAirType_IJOKHOEMJEM = 9810;
    CmdPixAirType_PixAirHandlePendingActionBattleCsReq = 9791;
    CmdPixAirType_PixAirBuyGoodsCsReq = 9776;
    CmdPixAirType_PixAirGetDataScRsp = 9793;
    CmdPixAirType_PixAirUnlockPlaneCsReq = 9778;
    CmdPixAirType_EFIGNDDPNJH = 9813;
    CmdPixAirType_INPBMNCLGNI = 9783;
    CmdPixAirType_PixAirStartStageScRsp = 9789;
    CmdPixAirType_PixAirStartStageCsReq = 9814;
    CmdPixAirType_PixAirReenterStageScRsp = 9780;
    CmdPixAirType_PixAirQuitStageScRsp = 9773;
}

message EIFBMCGPNMG {
    map<uint32, uint32> EOPNCAMILJF = 7;
}

message EKJMIJBIIHO {
    uint32 retcode = 11;
}

message EKMNFJIPCMI {
    uint32 retcode = 14;
}

message EMHEOJNCGFH {
    uint32 level = 4;
    uint32 grid_fight_equipment_id = 14;
}

message EPADPABCFGH {
    uint32 pos = 3;
    uint32 IAAHNOFKNGN = 4;
    uint32 unique_id = 5;
}

message EPBFAAHFDNF {
    repeated MGCPEPBPMNG KFNMIEMBJGD = 12;
    uint32 event_id = 15;
}

message FCIBLHJDPID {
    uint32 retcode = 4;
}

message FFKHFDJFAGM {
    uint32 queue_position = 12;
    oneof MMCGBGDJIPN {
        CKICDPIJIMF BACBKGJJOGA = 2;
        PKPHOOGGPOL IBIFHOIPAGE = 10;
        FJGMGGIGLPD MOFNIOJHBBL = 15;
        KAAJEKKIDIE IPKGIIJEPAJ = 14;
        ALLFGCIALIJ JFGIMDGOMBH = 9;
        EPBFAAHFDNF OOOACLEFDGM = 13;
        HIEACFOEMCE ADMICNGJLOI = 783;
        CCPCAIGEBCB AOEMGEFGIFG = 1021;
    }
}

message FJGMGGIGLPD {
}

message GANGPOOHAKI {
    uint32 PEBCBLBLMPH = 1;
}

message GCINPDAAELN {
    repeated JPEBEDHMNLA grid_fight_equipment_list = 9;
}

message GDNDBHGJBLF {
    uint32 PEBCBLBLMPH = 6;
}

enum GJIGHKNMILJ {
    GJIGHKNMILJ_NCMIMMDPHFM = 0;
    GJIGHKNMILJ_PJFGLBEKECE = 1;
    GJIGHKNMILJ_INCLHHDFCEL = 2;
    GJIGHKNMILJ_BGDCOCGIONK = 3;
}

message GNCJNHIOKDL {
    uint32 CKHCLKOALKE = 2;
    uint32 retcode = 8;
    oneof PGNIENCDODA {
        uint32 ECHFGJHHGOG = 1;
        uint32 NDEDLLMEFBJ = 9;
        KVP CJKEIMBCMEP = 3;
    }
}

message HENHAIFODIG {
    uint32 retcode = 5;
}

message HGNAHHFBMMN {
    LHJDEOLKHKB JGEMNOLFNIE = 1;
    IDJALKEGPLI basic = 2;
    uint32 AJHDCEGIGMC = 3;
    uint32 MFPOKNMFNGM = 4;
    uint32 GJLDDMIIILF = 5;
    uint32 stage_id = 6;
    repeated KVP switch_list = 7;
    string trans_no = 9;
    uint32 ALJNIHNLNMA = 10;
    FFKHFDJFAGM FMIGOKIDKJL = 11;
    BMOIPALHBJN NGNJHMEOHBD = 13;
    uint32 PAEAKCCACOP = 15;
}

message HIEACFOEMCE {
    uint32 HICEJEJNOLE = 7;
}

message HLDLJBFIMOO {
    uint32 HAFOKMHCGFM = 13;
}

message HPEKDMBCAEI {
    uint32 retcode = 15;
}

message IAOPGEAFECL {
}

message IDJALKEGPLI {
    repeated KVP DCJDCPMKEPN = 9;
    uint32 plane_id = 14;
}

message IIFHCHDPKIA {
    uint32 queue_position = 3;
    oneof MMCGBGDJIPN {
        AGBPBAOCCJF DHJNFOKBPNC = 4;
        OHPMDJFALNH JEIODBPCKNB = 8;
        MOJCEJIPPGO MOFNIOJHBBL = 13;
        AEGGFGBNLPE IPKGIIJEPAJ = 15;
        LJGKOGKEDOA JFGIMDGOMBH = 14;
        HLDLJBFIMOO OOOACLEFDGM = 11;
        GANGPOOHAKI ADMICNGJLOI = 508;
        GDNDBHGJBLF AOEMGEFGIFG = 713;
    }
}

message ILBJGGEHAEK {
    uint32 unique_id = 12;
}

message IMAGFGIHLJC {
    uint32 CDMFHNGEFCN = 4;
    uint32 AJHDCEGIGMC = 7;
    uint32 area_id = 8;
}

enum JDHJMNAGIIA {
    JDHJMNAGIIA_CDCHHNPNPLN = 0;
    JDHJMNAGIIA_EECEDOKMPPI = 1;
    JDHJMNAGIIA_PGGEODDBMMK = 2;
    JDHJMNAGIIA_PJGPLEAPECI = 3;
    JDHJMNAGIIA_BFLLFGOJPCG = 4;
    JDHJMNAGIIA_JAOLOFNICGD = 5;
    JDHJMNAGIIA_KAPHNBBNHBP = 6;
    JDHJMNAGIIA_DAJDHGGFJGK = 7;
    JDHJMNAGIIA_KEDPGJCCLDC = 8;
    JDHJMNAGIIA_MDMMEAKJNOC = 9;
    JDHJMNAGIIA_CDKPJHAEMFE = 10;
    JDHJMNAGIIA_CCJKIBNAFPJ = 11;
    JDHJMNAGIIA_NIBDPFIMOFG = 12;
    JDHJMNAGIIA_KGJCNJPFCNO = 13;
    JDHJMNAGIIA_CPBNIGEIKJA = 14;
}

message JPEBEDHMNLA {
    uint32 unique_id = 2;
    uint32 pos = 3;
    uint32 grid_fight_equipment_id = 8;
    uint32 CCBIIDDBFGK = 10;
    uint32 level = 13;
}

message KAAJEKKIDIE {
    EMHEOJNCGFH equip = 14;
}

message KLBPBDLHKBG {
    JDHJMNAGIIA source_type = 5;
    uint32 BNEFLBPCPOI = 10;
    oneof MMCGBGDJIPN {
        FFKHFDJFAGM FMIGOKIDKJL = 14;
        NBKKABHMMPP IANBCDJPDJF = 7;
        GCINPDAAELN EKEFDIEPHEE = 2;
        uint32 FKIAFJBMAPI = 9;
        IMAGFGIHLJC JKPINLKEOOK = 12;
        EIFBMCGPNMG DLOHBPGEMFF = 13;
        NNFFGHJKPJD KJHMPBOIGGE = 347;
        uint32 JOINHCDHNNL = 164;
        uint32 PMFBIGLPJJA = 730;
        uint32 OEKKEIMGBNO = 257;
    }
}

message LHJDEOLKHKB {
    repeated JPEBEDHMNLA DPPJILKLJAG = 3;
    repeated JPEBEDHMNLA MKJECBOMHPP = 8;
    uint32 slot_num = 10;
}

message LIFDLLPAAKF {
}

message LJGKOGKEDOA {
    uint32 OJEIHPEIJCO = 15;
}

message MGCPEPBPMNG {
    uint32 content_id = 10;
    uint32 HAFOKMHCGFM = 13;
}

message MOJCEJIPPGO {
}

message NAJFNKIEEDM {
    repeated uint32 BLHJIPBHHFO = 10;
}

message NBBINLLONGI {
    uint32 CDCIOPBFKGB = 4;
}

message NBKKABHMMPP {
    uint32 NJPMPAAGCCD = 1;
    uint32 score_id = 4;
    ItemList reward = 5;
    uint32 ALOFCOLHAGA = 6;
    uint32 GMLCJEOOCHJ = 7;
    GJIGHKNMILJ reason = 11;
    uint32 OACBLHIIIEH = 223;
    uint32 HGBHCLHCGBB = 555;
}

message NJHFBDDHCEN {
    bool LHGIFDNPIDE = 4;
    uint32 grid_fight_equipment_id = 5;
    uint32 level = 11;
}

message NMACHAFCGNI {
    uint32 ALJNIHNLNMA = 1;
    IDJALKEGPLI basic = 7;
    uint32 MFPOKNMFNGM = 8;
    uint32 stage_id = 10;
}

message NNFFGHJKPJD {
    uint32 JOMDKGINNEK = 2;
    uint32 shop_id = 7;
    uint32 AAIODNCLAIP = 14;
    repeated NJHFBDDHCEN OGDKJPDFFAI = 15;
}

message OHPMDJFALNH {
    uint32 content_id = 15;
}

message PKPHOOGGPOL {
    repeated AOPODAHBPFH message_datas = 5;
}

message PixAirGetDataCsReq {
}

message PixAirGetDataScRsp {
    NMACHAFCGNI IEIGEDABKAD = 1;
    repeated uint32 PGMIJBOGIKN = 5;
    uint32 score_id = 6;
    NAJFNKIEEDM JCOBJAMPOAL = 7;
    repeated uint32 OPOJIGCHGDO = 14;
    uint32 retcode = 15;
}

message PixAirReenterStageCsReq {
}

message PixAirReenterStageScRsp {
    uint32 retcode = 6;
    HGNAHHFBMMN stage_info = 14;
}

message PixAirStartStageCsReq {
    uint32 stage_id = 1;
    bool EMMGHDLIPOH = 6;
    uint32 ALJNIHNLNMA = 7;
    uint32 plane_id = 8;
}

message PixAirStartStageScRsp {
    uint32 retcode = 7;
    bool EMMGHDLIPOH = 9;
    HGNAHHFBMMN stage_info = 14;
}

message PixAirSwapEquipCsReq {
    repeated EPADPABCFGH MJLGNPMNMOP = 13;
}

message PixAirSwapEquipScRsp {
    uint32 retcode = 11;
    repeated EPADPABCFGH MJLGNPMNMOP = 15;
}

message PixAirSyncChangeScNotify {
    repeated KLBPBDLHKBG DGNGMJMPFGK = 8;
}

message PixAirUnlockPlaneCsReq {
    uint32 plane_id = 8;
}
