syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdPhoneType {
    CmdPhoneType_NLCDGIPGFDJ = 0;
    CmdPhoneType_LBBFEOIBHGK = 5181;
    CmdPhoneType_GetPhoneDataScRsp = 5178;
    CmdPhoneType_GetPhoneDataCsReq = 5125;
    CmdPhoneType_SelectPhoneCaseScRsp = 5113;
    CmdPhoneType_SelectPhoneThemeScRsp = 5186;
    CmdPhoneType_HAGCKNHKEOG = 5126;
    CmdPhoneType_HFCGJMALAFG = 5193;
    CmdPhoneType_UnlockChatBubbleScNotify = 5188;
    CmdPhoneType_UnlockPhoneCaseScNotify = 5171;
    CmdPhoneType_UnlockPhoneThemeScNotify = 5147;
    CmdPhoneType_SelectChatBubbleScRsp = 5158;
}

message GetPhoneDataCsReq {
}

message GetPhoneDataScRsp {
    repeated uint32 owned_phone_cases = 1;
    uint32 retcode = 2;
    uint32 cur_phone_theme = 3;
    repeated uint32 owned_phone_themes = 6;
    uint32 cur_phone_case = 10;
    uint32 cur_chat_bubble = 11;
    repeated uint32 owned_chat_bubbles = 14;
}

message SelectChatBubbleScRsp {
    uint32 retcode = 3;
    uint32 NGJMMMBJFHD = 4;
    uint32 cur_chat_bubble = 6;
}

message SelectPhoneCaseScRsp {
    uint32 retcode = 1;
    uint32 cur_phone_case = 9;
    uint32 NAMPHKPIOBA = 14;
}

message SelectPhoneThemeScRsp {
    uint32 retcode = 7;
    uint32 cur_phone_theme = 12;
    uint32 NNOHELHPJOM = 13;
}

message UnlockChatBubbleScNotify {
    uint32 bubble_id = 9;
}

message UnlockPhoneCaseScNotify {
    uint32 phone_case_id = 7;
}

message UnlockPhoneThemeScNotify {
    uint32 theme_id = 4;
}
