syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message Avatar {
    uint32 promotion = 1;
    uint32 cur_multi_path_avatar_type = 2;
    uint32 level = 6;
    bool is_marked = 8;
    uint32 base_avatar_id = 10;
    repeated uint32 has_taken_promotion_reward_list = 11;
    uint32 equipment_unique_id = 13;
    uint64 first_met_time_stamp = 14;
    uint32 exp = 15;
}

message AvatarPathData {
    uint32 path_equipment_id = 1;
    repeated EquipRelic equip_relic_list = 4;
    repeated AvatarPathSkillTree avatar_path_skill_tree = 6;
    uint32 avatar_id = 8;
    uint32 rank = 9;
    uint32 dressed_skin_id = 12;
    uint64 unlock_time = 13;
    uint32 unk_enhanced_id = 15;
}

message AvatarPathSkillTree {
    uint32 level = 1;
    uint32 point_id = 13;
}

message AvatarSync {
    repeated Avatar avatar_list = 6;
    repeated AvatarPathData avatar_path_data_info_list = 14;
}

message BasicModuleSync {
    uint32 stamina = 4;
    uint32 DLODAKOHFOP = 6;
}

message CCHMHOONEGG {
    uint32 num = 4;
    uint32 OCJLBKDCKHL = 5;
}

enum CmdPlayerSyncType {
    CmdPlayerSyncType_LIDGOKIFPOJ = 0;
    CmdPlayerSyncType_PlayerSyncScNotify = 625;
}

message GroupStatus {
    int64 refresh_time = 1;
    uint32 group_id = 5;
    MessageGroupStatus group_status = 15;
}

message MJBANFPPEFH {
    uint32 id = 8;
    ONHKODAFEMH custom_value_list = 547;
}

message MissionSync {
    repeated uint32 finished_main_mission_id_list = 1;
    repeated Mission mission_list = 4;
    repeated uint32 OBCBLABECEA = 7;
    repeated uint32 LEBFLAKCJCM = 10;
    repeated uint32 DEPBONHELFD = 11;
    repeated MJBANFPPEFH NLPKLNDCMOC = 14;
}

message PFNHCOJOBKH {
    repeated uint32 ABMLLCOKOLN = 4;
    repeated uint32 LKAKMGKENOI = 11;
}

message PlayerBoardModuleSync {
    repeated HeadIconData unlocked_head_icon_list = 5;
    bool MFFGEMKLNBF = 6;
    string signature = 7;
    HeadFrameInfo head_frame_info = 10;
    repeated uint32 GHNJNFKJEDC = 13;
}

message PlayerSyncScNotify {
    BasicModuleSync JHJNMOFMPMO = 2;
    repeated uint32 del_relic_list = 5;
    MissionSync mission_sync = 6;
    repeated WaitDelResource wait_del_resource_list = 7;
    repeated Relic relic_list = 8;
    AvatarSync avatar_sync = 9;
    repeated Quest quest_list = 10;
    PlayerBasicInfo basic_info = 11;
    repeated Equipment equipment_list = 12;
    repeated Material material_list = 14;
    repeated uint32 del_equipment_list = 15;
    repeated NKDNFDCFNCP NMBAFJGFOIH = 240;
    PlayerBoardModuleSync update_player_board_module_list = 325;
    repeated Material NAJFMIIFIEC = 525;
    repeated CCHMHOONEGG JIEOHBBDJDA = 608;
    repeated NLLLAAEJOBP update_platform_bound_gifts_list = 1086;
    ItemList FHHGDACMJED = 1130;
    SyncStatus sync_status = 1405;
    PFNHCOJOBKH update_pet_summon_items_list = 1452;
    CJLCPMDGIBO DHKFCDAGHDM = 1962;
}

message SectionStatus {
    uint32 section_id = 14;
    MessageSectionStatus section_status = 15;
}

message SyncStatus {
    repeated SectionStatus section_status = 5;
    repeated GroupStatus message_group_status = 10;
    repeated uint32 MDANGIEIMIF = 13;
    repeated uint32 BGPACBIJDCH = 14;
}
