syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdPamSkinType {
    CmdPamSkinType_NLCDGIPGFDJ = 0;
    CmdPamSkinType_UnlockPamSkinScNotify = 8122;
    CmdPamSkinType_NJMBOIMIKOD = 8123;
    CmdPamSkinType_GetPamSkinDataScRsp = 8128;
    CmdPamSkinType_SelectPamSkinScRsp = 8132;
    CmdPamSkinType_GetPamSkinDataCsReq = 8138;
}

message GetPamSkinDataCsReq {
}

message GetPamSkinDataScRsp {
    uint32 retcode = 3;
    repeated uint32 unlock_skin_list = 6;
    uint32 cur_skin = 8;
}

message SelectPamSkinScRsp {
    uint32 retcode = 2;
    uint32 set_skin = 3;
    uint32 cur_skin = 5;
}

message UnlockPamSkinScNotify {
    uint32 pam_skin = 3;
}
