syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AAIMICLLCKE {
    NCFKHDIKCNI NNJCNEMGEAJ = 10;
    uint32 JKAGCGKCHJG = 13;
}

message AIMNHEHKIMI {
    uint32 DJMPADMMPAN = 3;
    uint32 AFOHLIOKLAA = 8;
    uint32 OAEFICOLFIG = 10;
    NCFKHDIKCNI BAGMMONIIGK = 11;
    uint32 HMHEDCCLDGB = 15;
}

message BAGAOALHAJI {
    repeated EKEOBMOKEFD skill_list = 3;
}

message BEJOPEHPABO {
    NCFKHDIKCNI HFNNNGHBHGG = 6;
    NCFKHDIKCNI HMCIEDENFMK = 8;
    repeated uint32 LGBOJJFEGFI = 9;
    NCFKHDIKCNI DCPDNBALDOA = 14;
}

message BGNAMLHFLDB {
    uint32 retcode = 1;
}

message BLDIHADJKJF {
    NCFKHDIKCNI NNJCNEMGEAJ = 2;
    uint32 JKAGCGKCHJG = 5;
}

message BMGHLHHJEGE {
    uint32 event_type = 7;
    bool is_disappeared_once = 12;
}

message CANOCBHNHLJ {
    uint32 CNGMMDKCBND = 7;
}

message CHBCJNLOLMB {
    repeated KICPDGKGGHO LDCJONHGDAN = 12;
}

message CPHOIPHAPDJ {
    uint32 role_star = 6;
    uint32 PLEEMBMPICA = 9;
    uint32 level = 12;
    uint32 avatar_id = 13;
}

enum CmdPlanetFesType {
    CmdPlanetFesType_NLCDGIPGFDJ = 0;
    CmdPlanetFesType_KGOCELOKOIM = 8232;
    CmdPlanetFesType_MDGPHBEBHEE = 8248;
    CmdPlanetFesType_PlanetFesSkillLevelUpScRsp = 8222;
    CmdPlanetFesType_PlanetFesBuyLandScRsp = 8210;
    CmdPlanetFesType_PlanetFesClientStatusCsReq = 8221;
    CmdPlanetFesType_PlanetFesSetCustomKeyValueScRsp = 8211;
    CmdPlanetFesType_CNFLJMFDMAD = 8242;
    CmdPlanetFesType_PlanetFesGetFriendRankingInfoListScRsp = 8238;
    CmdPlanetFesType_PlanetFesFriendRankingInfoChangeScNotify = 8227;
    CmdPlanetFesType_PlanetFesBonusEventInteractCsReq = 8250;
    CmdPlanetFesType_PlanetFesCollectIncomeCsReq = 8244;
    CmdPlanetFesType_PlanetFesGetAvatarStatScRsp = 8225;
    CmdPlanetFesType_PlanetFesDeliverPamCargoCsReq = 8243;
    CmdPlanetFesType_JDFHIHGPNGG = 8249;
    CmdPlanetFesType_OLCODFNGEBI = 8224;
    CmdPlanetFesType_PlanetFesSetAvatarWorkScRsp = 8203;
    CmdPlanetFesType_PlanetFesGetAvatarStatCsReq = 8231;
    CmdPlanetFesType_GetPlanetFesDataScRsp = 8223;
    CmdPlanetFesType_GetPlanetFesDataCsReq = 8215;
    CmdPlanetFesType_PlanetFesTakeRegionPhaseRewardScRsp = 8236;
    CmdPlanetFesType_PlanetFesTakeQuestRewardScRsp = 8235;
    CmdPlanetFesType_PlanetFesAvatarLevelUpCsReq = 8206;
    CmdPlanetFesType_PlanetFesUseItemScRsp = 8212;
    CmdPlanetFesType_PlanetFesDoGachaScRsp = 8233;
    CmdPlanetFesType_MCAPKCNFHEB = 8214;
    CmdPlanetFesType_PlanetFesChooseAvatarEventOptionCsReq = 8226;
    CmdPlanetFesType_PlanetFesBusinessDayRefreshEventCsReq = 8208;
    CmdPlanetFesType_PlanetFesBingoGameFlipCardCsReq = 8216;
    CmdPlanetFesType_PlanetFesGameBingoFlipScRsp = 8201;
    CmdPlanetFesType_PlanetFesCollectAllIncomeCsReq = 8220;
    CmdPlanetFesType_IDFLFAMGKPK = 8246;
    CmdPlanetFesType_PlanetFesGetFriendRankingInfoListCsReq = 8234;
    CmdPlanetFesType_PlanetFesCollectAllIncomeScRsp = 8217;
    CmdPlanetFesType_PlanetFesGetBusinessDayInfoScRsp = 8213;
    CmdPlanetFesType_KKNGDKMKCDI = 8228;
    CmdPlanetFesType_PlanetFesCollectIncomeScRsp = 8219;
    CmdPlanetFesType_PlanetFesBuyLandCsReq = 8207;
    CmdPlanetFesType_PlanetFesSyncChangeScNotify = 8237;
    CmdPlanetFesType_PlanetFesStartMiniGameScRsp = 8205;
    CmdPlanetFesType_BKEBLIDOJFE = 8241;
    CmdPlanetFesType_PlanetFesChooseAvatarEventOptionScRsp = 8245;
    CmdPlanetFesType_PlanetFesDeliverPamCargoScRsp = 8240;
    CmdPlanetFesType_PlanetFesAvatarLevelUpScRsp = 8202;
    CmdPlanetFesType_MJCPDNPLBAF = 8230;
    CmdPlanetFesType_PlanetFesInitCsReq = 8209;
    CmdPlanetFesType_PlanetFesDealAvatarEventOptionItemScRsp = 8247;
    CmdPlanetFesType_PlanetFesDealAvatarEventOptionItemCsReq = 8239;
    CmdPlanetFesType_PlanetFesBonusEventInteractScRsp = 8204;
    CmdPlanetFesType_PlanetFesDoGachaCsReq = 8229;
    CmdPlanetFesType_PlanetFesBusinessDayRefreshEventScRsp = 8218;
}

message DAGGFIOGHGE {
    int64 MGHNNENOOGB = 1;
    NCFKHDIKCNI GAMNCJJJPEN = 6;
    uint32 FNABEJNJBKN = 9;
    NCFKHDIKCNI EJPENDJNLIH = 13;
}

message DHHFAMDCDPK {
    uint32 retcode = 1;
}

message ECIDGEBFJHP {
    PLPDNKNJBAA BOLCNGAKAMG = 10;
}

message ECJCIAPBFDJ {
    uint32 retcode = 11;
}

message EKEOBMOKEFD {
    uint32 level = 4;
    uint32 skill_id = 9;
}

message EKPBGMKJGDL {
    uint32 MGBCAPIIKLM = 4;
    IPMLDNLACFO HLBCFJLLKBL = 8;
    uint32 avatar_id = 9;
    uint32 BEMDNEMABCC = 14;
}

message EPKGFJDJMHM {
    oneof KKNBOACNCON {
        BEJOPEHPABO FKFPLMFLNPI = 5;
        BEJOPEHPABO HFCPPGPPMPB = 9;
        IHHONELJHJG LMOLELDIKMA = 4;
        IHHONELJHJG JCJLAAFLGHC = 3;
        DAGGFIOGHGE DLNEGFMNCPI = 10;
        DAGGFIOGHGE JLHJHFMMAPG = 8;
        CPHOIPHAPDJ LPGHOGLGEKH = 13;
        CPHOIPHAPDJ BFPNBEPPPLL = 1;
        KICPDGKGGHO KMKNPALADDC = 15;
        KICPDGKGGHO ELMMNHBECNI = 7;
        AAIMICLLCKE FBMJJGFJFMA = 2;
        JHACFFJIPHK NPNDMLGFEFI = 11;
        JHACFFJIPHK LIHDHBNHDKM = 14;
        PCONBOGEDFD MDFJJFCDLCK = 6;
        PlanetFesUnlockChange KONHPICIELO = 12;
        EKEOBMOKEFD LNPGIMBEMOE = 974;
        IMHOJPDMOJI HGGBFCEFLKO = 959;
        ECIDGEBFJHP ODOHJNABBAM = 981;
        PEMCOFDFCAC JDLEEFDFJGA = 801;
        MCCHABOPEFJ CGMBBDHDMEO = 1451;
        HGJHBCBIONE KGHOJJKNCBP = 1173;
        CANOCBHNHLJ BPKMBMPJAON = 373;
        KICPDGKGGHO EOPILJCMLLA = 139;
        FLCJMPNDMMH KMCJFDEDEAA = 1437;
        GMODJEECPPJ DBDLIIPGEOE = 1619;
        IEDPDDJAAIH JOGCFKGJMJB = 723;
        MAOINJAJOEC KJOAEEGIGDI = 899;
        DFEPHMALKDK OAHOCFKEMCM = 963;
    }
}

message FLCJMPNDMMH {
    uint32 HBMGKJAAPFI = 2;
    NCFKHDIKCNI BFEOOJBNFBG = 3;
    uint32 MAGBFEHEOOI = 4;
    repeated GLECNCOBKCJ FIHPPANOOFL = 6;
    uint32 NFCMAEIGKHK = 7;
    uint32 BPBADPAACOL = 10;
    uint32 LAAAPJAIKAF = 12;
    NCFKHDIKCNI FDGKBOIEHBD = 13;
    map<uint32, uint32> ODICAOCLJKO = 14;
    NCFKHDIKCNI FHGFEKEAJFF = 15;
}

message FPMMPGAOGCH {
    uint32 FNABEJNJBKN = 11;
}

message GHONFFLAMHB {
    uint32 IGOOJKMPMDC = 14;
}

enum GJJEOANEDDO {
    GJJEOANEDDO_NLCDGIPGFDJ = 0;
    GJJEOANEDDO_GHDEPAGOKBE = 1;
    GJJEOANEDDO_GGEKFBGIJID = 2;
}

message GLECNCOBKCJ {
    uint32 LKBHAFLMOLA = 4;
    uint32 PKJHFPFOABL = 6;
    uint32 avatar_id = 7;
    NCFKHDIKCNI NFDJOCBMLCI = 10;
}

message GNMCIEPEBPK {
    repeated FMKMEFMOJGJ item_list = 2;
    NCFKHDIKCNI item_value = 6;
    map<uint32, uint32> NDMLPIGABGE = 13;
}

message GOMIDGNOENH {
    uint32 FNABEJNJBKN = 9;
}

message GetPlanetFesDataCsReq {
}

message GetPlanetFesDataScRsp {
    PPAIELAKIJD BBEKBJPHEJK = 1;
    repeated KVP custom_value_list = 2;
    PLOFKJDKEPN FEOONKKLCHA = 3;
    PHCPOIHAPGP COGGJELNFCN = 5;
    OBEHBNOCLMM LCPEDLCOMFE = 6;
    NOLLHKIMDOC CCFGCCMEFCI = 8;
    KCMJJLJCHHP NJFGGOOMGCD = 9;
    CHBCJNLOLMB OPJLJOPBGOJ = 10;
    BLDIHADJKJF OEIBHLMDJKA = 11;
    BAGAOALHAJI skill_info = 12;
    JMBNHAFHIHM IEKDOJDPMEB = 13;
    uint32 retcode = 14;
    KNECKDAOKOA OCHNMGMDHME = 15;
}

message HBONEFMPKKO {
    uint32 MMFGAJNCAOA = 2;
    uint32 progress = 10;
}

message HGJHBCBIONE {
    GJJEOANEDDO GMKICMIMAAB = 3;
    OJHHACMHFKA GLOAGDBEKDP = 13;
}

message IEDAMBICKBB {
    int64 KHCGOMAJDGL = 9;
}

message IHHBDEJOCGI {
    uint32 retcode = 5;
}

message IHHONELJHJG {
    uint32 item_id = 1;
    uint32 DCPDNBALDOA = 5;
    uint32 HFNNNGHBHGG = 15;
}

message IKMLLJNNKJB {
    repeated FMKMEFMOJGJ item_list = 7;
    repeated AIMNHEHKIMI transfer_item_list = 9;
}

message IMHOJPDMOJI {
    uint32 HBJIJHHMEGO = 7;
}

message IPMLDNLACFO {
    FMKMEFMOJGJ item = 5;
    AIMNHEHKIMI PIENFNCGFMB = 12;
}

message JHACFFJIPHK {
    PlanetFesQuestState status = 5;
    uint32 progress = 7;
    uint32 DPCHGMMCKNN = 10;
    uint32 quest_id = 11;
    oneof JCPHPAHKPDD {
        uint32 MCNLMNOKAFF = 2;
        NCFKHDIKCNI KNOCPAJCPJC = 15;
    }
}

message JMBNHAFHIHM {
    repeated DAGGFIOGHGE GOIJOOCHJDP = 14;
}

message KCMJJLJCHHP {
    bool has_passed = 3;
    uint32 DDOIGECMKKA = 4;
    bool CANDCMOCAFH = 5;
    uint32 NEDCJCBPEJM = 6;
    uint32 CINEILEIEJK = 8;
    int64 NACEMPJFKAH = 13;
}

message KICPDGKGGHO {
    uint64 unique_id = 2;
    uint32 config_id = 8;
    repeated IEDAMBICKBB KABJOHKOEFN = 9;
    OBEBKODGODB source = 10;
}

message KNECKDAOKOA {
    NCFKHDIKCNI item_value = 3;
    NCFKHDIKCNI GJPLOMMEBGM = 8;
    repeated FMKMEFMOJGJ item_list = 15;
}

message LEJNBBLNNDM {
    OBEBKODGODB source = 6;
    EPKGFJDJMHM detail = 7;
}

message LOFFNNNIDMM {
    uint32 retcode = 4;
}

message MAOINJAJOEC {
    uint32 JKAGCGKCHJG = 1;
    NCFKHDIKCNI gold = 3;
    uint32 business_day = 6;
    uint32 LBICJMAMFGN = 7;
    uint32 EMJPFPHBKMG = 9;
    uint32 PPOAGPGEAFH = 10;
    uint32 uid = 13;
}

message MCCHABOPEFJ {
    MOFKNBAKKDI GHKFKGMOHDO = 2;
}

message MOFKNBAKKDI {
    repeated OJHHACMHFKA CKACALMICBH = 2;
    NCFKHDIKCNI FDGKBOIEHBD = 3;
    int64 start_time = 4;
    map<uint32, uint32> FLKNHFMNDCE = 5;
    uint32 business_day = 6;
    bool CANDCMOCAFH = 7;
    bool has_passed = 12;
}

message MOOLKFODKIK {
}

message NDPJHJOAOJE {
    IKMLLJNNKJB HMMBBENHIFE = 6;
    repeated uint32 EPBJNIFHBLE = 10;
}

message NGHCOJCMJOK {
    repeated EKPBGMKJGDL HAINMHKIOMJ = 8;
    repeated uint32 BNCOJCEGBPG = 9;
    NCFKHDIKCNI OPOIDCHIMEK = 12;
    repeated IPMLDNLACFO FAJLFDNKFGJ = 15;
}

message NLAGKOJKHCN {
    uint32 retcode = 4;
    NCFKHDIKCNI GALBOLNODBB = 11;
}

message NOLLHKIMDOC {
    int64 GLDGCHLDMJE = 1;
    uint32 JOADLJIDGND = 2;
    repeated uint32 IJMHPOEPILG = 3;
}

message OBEBKODGODB {
    uint32 EMPDMDNDLHE = 1;
    uint32 EPFHBGNGBBK = 3;
    uint32 BNEFLBPCPOI = 12;
}

message OBEHBNOCLMM {
    repeated uint32 HPMNIKJGBPD = 10;
    uint32 CNGMMDKCBND = 12;
}

message OHABCOEGDEH {
    uint32 business_day = 2;
    repeated GLECNCOBKCJ FIHPPANOOFL = 9;
    NCFKHDIKCNI FDGKBOIEHBD = 10;
    uint32 NMLFCGHPGEL = 11;
    NCFKHDIKCNI EJNBHKGOEKI = 12;
    bool CANDCMOCAFH = 13;
}

message OLENIPLHIPI {
    bool is_active = 4;
}

message PBAPKAGHGFB {
    repeated uint32 GOEJBENHBHE = 15;
}

message PCONBOGEDFD {
    uint32 PKCIADAEICG = 3;
    uint32 EDBPMKPHLDK = 15;
}

message PEMCOFDFCAC {
    NCFKHDIKCNI EFOJBKPJLIO = 15;
}

message PHCPOIHAPGP {
    repeated CPHOIPHAPDJ avatar_list = 7;
}

message PHFGDCMBDBA {
    uint32 avatar_id = 4;
    uint32 FNABEJNJBKN = 10;
}

message PLOFKJDKEPN {
    repeated JHACFFJIPHK quest_list = 7;
    PCONBOGEDFD DFBGAOAJLIC = 8;
}

message PLPDNKNJBAA {
    repeated OHABCOEGDEH HBGPLDACACI = 5;
    repeated uint32 KCENCAAPMLK = 11;
    uint32 NEDCJCBPEJM = 12;
    repeated BMGHLHHJEGE ENDPGFBABBB = 13;
    MOFKNBAKKDI HOCBDMPEMDH = 14;
    uint32 CINEILEIEJK = 15;
}

message POFDBDHOJNG {
    repeated PHFGDCMBDBA NEMFNENACNB = 14;
}

message PPAIELAKIJD {
    repeated uint32 BJNOHKFONFP = 1;
    repeated HBONEFMPKKO KFOFAKDPGJC = 14;
}

message PlanetFesAvatarLevelUpCsReq {
    uint32 IGOOJKMPMDC = 1;
    uint32 avatar_id = 9;
}

message PlanetFesAvatarLevelUpScRsp {
    uint32 retcode = 3;
    uint32 IGOOJKMPMDC = 4;
    GNMCIEPEBPK reward = 6;
    uint32 KPGNEABOECG = 9;
    uint32 avatar_id = 13;
}

message PlanetFesBonusEventInteractCsReq {
    uint32 JCBNLGDOMMF = 5;
    uint32 event_type = 10;
}

message PlanetFesBonusEventInteractScRsp {
    uint32 retcode = 8;
    uint32 event_type = 11;
    OJHHACMHFKA GLOAGDBEKDP = 13;
    GNMCIEPEBPK reward = 15;
}

message PlanetFesBusinessDayRefreshEventCsReq {
    bool CEIONHPDNDP = 5;
    uint32 event_type = 9;
    uint32 business_day = 12;
}

message PlanetFesBusinessDayRefreshEventScRsp {
    uint32 retcode = 8;
    OJHHACMHFKA GLOAGDBEKDP = 9;
}

message PlanetFesChooseAvatarEventOptionCsReq {
    uint32 MABNCDEBPDK = 7;
}

message PlanetFesChooseAvatarEventOptionScRsp {
    uint32 IIBJDCKHAKE = 2;
    uint32 HHGAHEBNAIL = 3;
    uint32 retcode = 6;
    OJHHACMHFKA GLOAGDBEKDP = 8;
    GNMCIEPEBPK reward = 10;
    uint32 DNLAFCPNPOE = 12;
}

message PlanetFesDealAvatarEventOptionItemCsReq {
    bool MLKBOBIEAPL = 6;
    uint32 HLLIBEEKFII = 13;
}

message PlanetFesDealAvatarEventOptionItemScRsp {
    bool MLKBOBIEAPL = 1;
    OJHHACMHFKA GLOAGDBEKDP = 2;
    uint32 IIBJDCKHAKE = 4;
    uint32 DNLAFCPNPOE = 9;
    uint32 retcode = 10;
    GNMCIEPEBPK reward = 14;
}

message PlanetFesDeliverPamCargoCsReq {
    uint32 avatar_id = 5;
    uint32 JADCEPFHHDK = 12;
}

message PlanetFesDeliverPamCargoScRsp {
    uint32 avatar_id = 2;
    uint32 retcode = 4;
    GNMCIEPEBPK FFMILOLELNJ = 6;
    OJHHACMHFKA GLOAGDBEKDP = 11;
}

message PlanetFesDoGachaCsReq {
    uint32 gacha_id = 1;
    uint32 gacha_count = 3;
    uint32 simulate_magic = 12;
}

message PlanetFesDoGachaScRsp {
    uint32 retcode = 1;
    uint32 gacha_id = 3;
    repeated FMKMEFMOJGJ LGPDNIGJEKP = 8;
    oneof BNJPPHJNKHF {
        NGHCOJCMJOK EHLPJELJJOO = 2;
        NDPJHJOAOJE FFBDKNIHNEL = 7;
    }
}

message PlanetFesFriendRankingInfoChangeScNotify {
    repeated MAOINJAJOEC MLPHLIHFGKG = 5;
}

message PlanetFesGameBingoFlipScRsp {
    GNMCIEPEBPK reward = 3;
    uint32 retcode = 8;
    bool BDEFAFFDBCC = 10;
    uint32 LKFIGBGPEJB = 14;
}

message PlanetFesGetAvatarStatCsReq {
}

message PlanetFesGetAvatarStatScRsp {
    repeated GLECNCOBKCJ FIHPPANOOFL = 2;
    uint32 retcode = 12;
}

message PlanetFesGetBusinessDayInfoScRsp {
    PLPDNKNJBAA BOLCNGAKAMG = 10;
    int64 NACEMPJFKAH = 14;
    uint32 retcode = 15;
}

message PlanetFesGetFriendRankingInfoListCsReq {
}

message PlanetFesGetFriendRankingInfoListScRsp {
    MAOINJAJOEC PONAOKBNIAM = 6;
    uint32 retcode = 7;
}

enum PlanetFesQuestState {
    CNLAEDCLICP_MDPJCGEMOLG = 0;
    CNLAEDCLICP_GBJIHFOIGHD = 1;
    CNLAEDCLICP_BILKPNLJBFA = 2;
    CNLAEDCLICP_CGIIKAHOIKL = 3;
}

message PlanetFesSetCustomKeyValueScRsp {
    uint32 retcode = 7;
    uint32 value = 10;
    uint32 key = 15;
}

message PlanetFesSkillLevelUpScRsp {
    FMKMEFMOJGJ item_cost = 2;
    uint32 skill_id = 4;
    uint32 skill_level = 8;
    uint32 retcode = 12;
}

message PlanetFesStartMiniGameScRsp {
    uint32 retcode = 3;
    GNMCIEPEBPK reward = 9;
    PGPHEKKPBLD CFDIKLBINHK = 10;
    PBAPKAGHGFB HMMBBENHIFE = 11;
}

message PlanetFesSyncChangeScNotify {
    repeated LEJNBBLNNDM DGNGMJMPFGK = 10;
}

message PlanetFesTakeQuestRewardScRsp {
    uint32 quest_id = 3;
    IKMLLJNNKJB JMBFMMPAAAO = 7;
    uint32 retcode = 9;
}

message PlanetFesTakeRegionPhaseRewardScRsp {
    uint32 BKPDKFLDLDD = 3;
    uint32 retcode = 8;
    ItemList reward_list = 9;
}

message PlanetFesUnlockChange {
    HBONEFMPKKO BBEKBJPHEJK = 5;
    bool has_passed = 15;
}

message PlanetFesUseItemScRsp {
    uint32 retcode = 1;
    GNMCIEPEBPK reward = 4;
}
