syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CDCCPHILOCC {
    uint32 uid = 1;
    uint32 monster_id = 2;
}

message CJDIAHDLCNJ {
    uint32 uid = 1;
    uint32 damage_hp = 2;
    bool is_final_hit = 3;
    uint32 over_kill_damage_hp = 4;
    string battle_replay_key = 5;
    repeated GOFFDNPBHIK avatar_list = 6;
    uint32 assist_score = 7;
    uint32 damage_score = 8;
    uint32 final_hit_score = 9;
}

enum CmdPunkLordType {
    CmdPunkLordType_NLCDGIPGFDJ = 0;
    CmdPunkLordType_PunkLordMonsterKilledNotify = 3221;
    CmdPunkLordType_PunkLordBattleResultScNotify = 3230;
    CmdPunkLordType_NFCLFNPJDBL = 3205;
    CmdPunkLordType_PunkLordDataChangeNotify = 3210;
    CmdPunkLordType_StartPunkLordRaidScRsp = 3258;
    CmdPunkLordType_SummonPunkLordMonsterScRsp = 3247;
    CmdPunkLordType_GetPunkLordMonsterDataScRsp = 3278;
    CmdPunkLordType_TakePunkLordPointRewardScRsp = 3238;
    CmdPunkLordType_GetKilledPunkLordMonsterDataCsReq = 3242;
    CmdPunkLordType_LDLNMHHFEKE = 3288;
    CmdPunkLordType_GetPunkLordBattleRecordScRsp = 3229;
    CmdPunkLordType_GetPunkLordMonsterDataCsReq = 3225;
    CmdPunkLordType_GetKilledPunkLordMonsterDataScRsp = 3272;
    CmdPunkLordType_SharePunkLordMonsterScRsp = 3281;
    CmdPunkLordType_GetPunkLordDataScRsp = 3211;
    CmdPunkLordType_GetPunkLordBattleRecordCsReq = 3243;
    CmdPunkLordType_PunkLordMonsterInfoScNotify = 3239;
    CmdPunkLordType_OHOCIGMPANB = 3286;
    CmdPunkLordType_BBPJCEBHDHM = 3293;
    CmdPunkLordType_TakeKilledPunkLordMonsterScoreScRsp = 3241;
    CmdPunkLordType_JOOJJAKOAKP = 3233;
    CmdPunkLordType_GetPunkLordDataCsReq = 3204;
    CmdPunkLordType_PunkLordRaidTimeOutScNotify = 3248;
}

message FGFGINEFBBK {
    uint32 FJKDAFHKPGC = 1;
    bool APCMAIJPPEH = 3;
    uint32 config_id = 4;
    int64 create_time = 5;
    uint32 world_level = 6;
    uint32 monster_id = 7;
}

message GMDHIALLILJ {
    repeated CJDIAHDLCNJ GAIKBNPIFLM = 1;
}

message GOFFDNPBHIK {
    uint32 avatar_id = 1;
    uint32 avatar_level = 2;
}

message GetKilledPunkLordMonsterDataCsReq {
}

message GetKilledPunkLordMonsterDataScRsp {
    repeated CDCCPHILOCC BLLLCPONFBE = 10;
    repeated FGFGINEFBBK CPPDAIMLDGB = 11;
    uint32 retcode = 15;
}

message GetPunkLordBattleRecordCsReq {
    CDCCPHILOCC KHOLBEGBFOM = 13;
}

message GetPunkLordBattleRecordScRsp {
    repeated TryDownLoadReplay HLCIMLHMEKI = 1;
    CDCCPHILOCC KHOLBEGBFOM = 7;
    uint32 retcode = 13;
    repeated CJDIAHDLCNJ GAIKBNPIFLM = 15;
}

message GetPunkLordDataCsReq {
}

message GetPunkLordDataScRsp {
    repeated uint32 IEPPNGMCKJH = 2;
    int64 NEOGLPEGBHE = 5;
    uint32 retcode = 8;
    uint32 BPCOIOLGEMK = 10;
    uint32 KCBPBMOJOKJ = 11;
    uint32 GIIIFDGFJPG = 12;
    uint32 MGBHJPPJHEA = 14;
    uint32 LCAFKPGBDOL = 15;
}

message GetPunkLordMonsterDataCsReq {
}

message GetPunkLordMonsterDataScRsp {
    uint32 retcode = 9;
    repeated JEIAEAEGEBJ PBLBBDBDLEK = 15;
}

message JEIAEAEGEBJ {
    PunkLordMonsterBasicInfo basic_info = 1;
    GMDHIALLILJ FDJHMFAGEOA = 4;
    uint32 HDHIFJNJOBK = 11;
    PunkLordAttackerStatus HCEENPENFGI = 13;
}

enum PAKHPLAHGBN {
    PAKHPLAHGBN_NLCDGIPGFDJ = 0;
    PAKHPLAHGBN_FIOLLIOEAJC = 1;
    PAKHPLAHGBN_CJMELLLIEDE = 2;
    PAKHPLAHGBN_COGCFDFAKON = 3;
}

enum PunkLordAttackerStatus {
    PFIPEIGDLLK_NLCDGIPGFDJ = 0;
    PFIPEIGDLLK_CCALGNCNFME = 1;
    PFIPEIGDLLK_MOKNDKJFLDH = 2;
    PFIPEIGDLLK_HKLDKMJMGAH = 3;
}

message PunkLordBattleResultScNotify {
    uint32 assist_score = 1;
    uint32 damage_score = 6;
    PunkLordMonsterBasicInfo ONICJOAOEMA = 10;
    CJDIAHDLCNJ FDJHMFAGEOA = 11;
    uint32 final_hit_score = 13;
}

message PunkLordDataChangeNotify {
    uint32 MGBHJPPJHEA = 3;
    uint32 BPCOIOLGEMK = 8;
    uint32 GIIIFDGFJPG = 10;
}

message PunkLordMonsterBasicInfo {
    uint32 uid = 1;
    uint32 monster_id = 2;
    uint32 config_id = 3;
    uint32 world_level = 4;
    int64 create_time = 5;
    uint32 left_hp = 6;
    uint32 attacker_num = 7;
    PunkLordShareType share_type = 8;
    bool APCMAIJPPEH = 9;
}

message PunkLordMonsterInfoScNotify {
    CJDIAHDLCNJ FDJHMFAGEOA = 3;
    PunkLordMonsterBasicInfo basic_info = 7;
    repeated uint32 FNMGMNABAJG = 13;
    PAKHPLAHGBN reason = 15;
}

message PunkLordMonsterKilledNotify {
    FGFGINEFBBK PEBMDFAGJAM = 15;
}

message PunkLordRaidTimeOutScNotify {
    PunkLordMonsterBasicInfo ONICJOAOEMA = 10;
}

enum PunkLordShareType {
    EOPODGPDKMO_NLCDGIPGFDJ = 0;
    EOPODGPDKMO_ENFIEFPPCIC = 1;
    EOPODGPDKMO_ACAOCKPIGPL = 2;
}

message ReplayInfo {
    uint64 LMFBCHEHOLO = 1;
    PBIEFHKNAFA replay_type = 2;
    uint32 stage_id = 3;
    uint32 uid = 4;
    string nickname = 5;
    uint32 head_icon = 6;
    string replay_name = 7;
    uint64 create_time = 8;
    uint32 KLIFGJOILEE = 9;
    uint32 PBNIENNCNOP = 10;
}

message SharePunkLordMonsterScRsp {
    PunkLordShareType share_type = 1;
    uint32 retcode = 6;
    uint32 uid = 7;
    uint32 monster_id = 15;
}

message StartPunkLordRaidScRsp {
    int64 PEAMKPJKIEL = 1;
    uint32 retcode = 5;
    JEIAEAEGEBJ ONICJOAOEMA = 6;
    bool IDMPMEOCJIK = 7;
    repeated uint32 FNMGMNABAJG = 11;
    GEGLJDELBHA scene = 13;
}

message SummonPunkLordMonsterScRsp {
    JEIAEAEGEBJ ONICJOAOEMA = 1;
    uint32 retcode = 6;
}

message TakeKilledPunkLordMonsterScoreScRsp {
    uint32 score_id = 1;
    bool LOMGNMFAPGE = 5;
    uint32 retcode = 13;
    repeated CDCCPHILOCC DFJFJNPCIPA = 15;
}

message TakePunkLordPointRewardScRsp {
    uint32 retcode = 2;
    uint32 level = 13;
    ItemList reward = 14;
    bool LEFJBFMDEGK = 15;
}

message TryDownLoadReplay {
    string battle_replay_key = 1;
    ReplayInfo replay_info = 2;
}
