syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdPetType {
    CmdPetType_NLCDGIPGFDJ = 0;
    CmdPetType_BCJECGLBFMD = 7612;
    CmdPetType_SummonPetScRsp = 7607;
    CmdPetType_GetPetDataScRsp = 7621;
    CmdPetType_GetPetDataCsReq = 7608;
    CmdPetType_BCKIBFHMGOF = 7619;
    CmdPetType_RecallPetScRsp = 7609;
    CmdPetType_KHHMEFCDMIF = 7605;
}

message GetPetDataCsReq {
}

message GetPetDataScRsp {
    repeated uint32 unlocked_pet_id = 3;
    uint32 cur_pet_id = 4;
    uint32 retcode = 5;
}

message RecallPetScRsp {
    uint32 retcode = 4;
    uint32 cur_pet_id = 8;
    uint32 select_pet_id = 14;
}

message SummonPetScRsp {
    uint32 cur_pet_id = 6;
    uint32 select_pet_id = 7;
    uint32 retcode = 15;
}
