syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message ABEBEOKFKFF {
    uint32 cnt = 3;
    EJEGHJPAMPI type = 12;
}

message BADOONPCDLO {
    bool AJGOLAKNGPA = 1;
    uint32 level_id = 8;
    uint32 time = 10;
}

message BDEOLCNPBPP {
    uint32 id = 8;
    uint32 cnt = 12;
}

message COIMBCBMNIE {
    repeated HANMCLKOCBO BEDHEKAGAPE = 2;
    uint32 level_id = 11;
}

enum CmdParkourType {
    CmdParkourType_NLCDGIPGFDJ = 0;
    CmdParkourType_ParkourEndLevelScRsp = 8384;
    CmdParkourType_ParkourStartLevelScRsp = 8397;
    CmdParkourType_ParkourGetDataScRsp = 8388;
    CmdParkourType_ActivityParkourInitCsReq = 8398;
    CmdParkourType_ParkourGetRankingInfoScRsp = 8392;
    CmdParkourType_GAJOJHCNNMO = 8382;
    CmdParkourType_GMODLOKAHLA = 8383;
    CmdParkourType_PGIBHKCAEAK = 8385;
}

enum EJEGHJPAMPI {
    EJEGHJPAMPI_BACKHOLLHDC = 0;
    EJEGHJPAMPI_HAAFIJPEJOO = 1;
    EJEGHJPAMPI_FPPDHDLGACM = 2;
}

message HANMCLKOCBO {
    uint32 time = 2;
    uint32 id = 7;
    uint32 LJJGFIPLDLI = 14;
}

message IJJFBFPCBCI {
    uint32 IEOJFKHKBEP = 2;
    uint32 KBFHFLODGIA = 3;
    uint32 ICBKCJKHNBP = 7;
    uint32 BLEFGKAGDEN = 13;
}

enum OHFECKKADEK {
    OHFECKKADEK_NLCDGIPGFDJ = 0;
    OHFECKKADEK_CIHFGJDCHIA = 1;
    OHFECKKADEK_INCLHHDFCEL = 2;
}

message OIHEIIDJOLI {
    repeated BDEOLCNPBPP OECOCOPOOHO = 1;
    uint32 FPIDONGEKFO = 2;
    uint32 MGPMDJOMMOK = 3;
    uint32 BAPPKHBKOAG = 4;
    uint32 NCMMFCJGDKA = 5;
    uint32 DHJEALPGPJK = 7;
    uint32 GCAFHJIAMIL = 8;
    uint32 GBOLMEOHEOB = 12;
    uint32 GOMFPKDIIKA = 13;
    uint32 PLOEMBOCIGE = 14;
    uint32 GPHNIOGICJP = 15;
}

message ParkourEndLevelScRsp {
    OHFECKKADEK end_reason = 1;
    bool ADJLGNBJAOC = 2;
    uint32 level_id = 4;
    uint32 time = 5;
    BADOONPCDLO ENKCCEACJKL = 6;
    uint32 retcode = 8;
    bool AJGOLAKNGPA = 10;
}

message ParkourGetDataScRsp {
    repeated BADOONPCDLO CGIPFMLDPNA = 8;
    uint32 retcode = 12;
}

message ParkourGetRankingInfoScRsp {
    COIMBCBMNIE LGFNFABAAGA = 1;
    repeated COIMBCBMNIE JNMFKJHCOEG = 5;
    uint32 retcode = 8;
}

message ParkourStartLevelScRsp {
    uint32 level_id = 2;
    uint32 CEKKJHBNEOD = 4;
    uint32 retcode = 10;
}
