syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AAHPJECONDN {
    uint32 retcode = 9;
}

enum CmdPlanetFesExtType {
    CmdPlanetFesExtType_NLCDGIPGFDJ = 0;
    CmdPlanetFesExtType_PlanetFesGetOfferedCardPieceScRsp = 8310;
    CmdPlanetFesExtType_PlanetFesHandleCardPieceApplyCsReq = 8300;
    CmdPlanetFesExtType_PlanetFesGiveCardPieceScRsp = 8319;
    CmdPlanetFesExtType_HEIDCFGIGFA = 8304;
    CmdPlanetFesExtType_PlanetFesGetExtraCardPieceInfoScRsp = 8313;
    CmdPlanetFesExtType_PlanetFesGetFriendCardPieceCsReq = 8327;
    CmdPlanetFesExtType_PlanetFesEnterNextBusinessDayCsReq = 8292;
    CmdPlanetFesExtType_PlanetFesLargeBonusInteractScRsp = 8296;
    CmdPlanetFesExtType_PlanetFesPresentCsReq = 8307;
    CmdPlanetFesExtType_PlanetFesApplyCardPieceScRsp = 8297;
    CmdPlanetFesExtType_PlanetFesDemandCsReq = 8293;
    CmdPlanetFesExtType_PlanetFesGetOfferedCardPieceCsReq = 8314;
    CmdPlanetFesExtType_PlanetFesChangeCardPieceApplyPermissionCsReq = 8309;
    CmdPlanetFesExtType_PlanetFesHandleCardPieceApplyScRsp = 8311;
    CmdPlanetFesExtType_PlanetFesChangeCardPieceApplyPermissionScRsp = 8338;
    CmdPlanetFesExtType_PlanetFesGetFriendCardPieceScRsp = 8334;
    CmdPlanetFesExtType_PlanetFesLargeBonusInteractCsReq = 8323;
    CmdPlanetFesExtType_PlanetFesGetExtraCardPieceInfoCsReq = 8299;
}

message EPPIBFOLFKN {
    int64 OIKNNPOKKME = 3;
    repeated FMKMEFMOJGJ EOMINOCGLJF = 5;
    uint32 HAAHAGAPDKC = 7;
    repeated DFEPHMALKDK FDHMLGFKDIP = 8;
    uint32 MLGAODMIHJH = 10;
    repeated GMODJEECPPJ GMLEOJCLCFB = 12;
    uint32 uid = 14;
    repeated uint32 MLPNIPENEBG = 15;
}

message JJIBNOEGFLK {
}

message PlanetFesApplyCardPieceScRsp {
    uint32 BLGLDJHOMNO = 4;
    int64 GLDGCHLDMJE = 6;
    uint32 retcode = 7;
    bool GOPCDFEIOEA = 10;
    repeated uint32 OEEGPNOCFLP = 14;
    uint32 teleport_id = 15;
}

message PlanetFesChangeCardPieceApplyPermissionCsReq {
    uint32 HAAHAGAPDKC = 9;
}

message PlanetFesChangeCardPieceApplyPermissionScRsp {
    uint32 retcode = 9;
    uint32 HAAHAGAPDKC = 15;
}

message PlanetFesGetExtraCardPieceInfoCsReq {
}

message PlanetFesGetExtraCardPieceInfoScRsp {
    uint32 retcode = 10;
    EPPIBFOLFKN GIPNMPKNIFG = 14;
}

message PlanetFesGetFriendCardPieceCsReq {
}

message PlanetFesGetFriendCardPieceScRsp {
    uint32 retcode = 1;
    repeated EPPIBFOLFKN PEBGJJCNBMM = 13;
}

message PlanetFesGetOfferedCardPieceCsReq {
    bool FOGGEJIIJCM = 4;
    uint64 CBMBOBNCKMO = 9;
}

message PlanetFesGetOfferedCardPieceScRsp {
    int64 MAFLGLLOKBB = 4;
    repeated IEDPDDJAAIH CBPKFDJMGBH = 5;
    bool FOGGEJIIJCM = 6;
    uint64 CBMBOBNCKMO = 11;
    repeated FMKMEFMOJGJ EOMINOCGLJF = 14;
    uint32 retcode = 15;
}

message PlanetFesGiveCardPieceScRsp {
    int64 JEAGHJHMCEN = 1;
    uint32 retcode = 8;
    uint32 teleport_id = 9;
    uint64 CBMBOBNCKMO = 10;
    repeated uint32 JAKKDGHLJPH = 11;
}

message PlanetFesHandleCardPieceApplyCsReq {
    uint32 BLGLDJHOMNO = 1;
    repeated uint32 JAKKDGHLJPH = 2;
    uint32 APIFFHBCDKK = 4;
    bool IKOBGOCEHFG = 12;
}

message PlanetFesHandleCardPieceApplyScRsp {
    bool IKOBGOCEHFG = 1;
    uint32 retcode = 4;
    repeated uint32 JAKKDGHLJPH = 6;
    int64 JEAGHJHMCEN = 11;
    uint32 BLGLDJHOMNO = 12;
}

message PlanetFesLargeBonusInteractCsReq {
    uint32 IABOGPKEAGF = 1;
    uint32 MMKABABENKE = 2;
    uint32 DNBKKDBFFAJ = 4;
}

message PlanetFesLargeBonusInteractScRsp {
    uint32 DNBKKDBFFAJ = 3;
    uint32 retcode = 4;
    NCFKHDIKCNI CGKNMGLFKBN = 12;
    OJHHACMHFKA GLOAGDBEKDP = 15;
}
