syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum ALGMICKCABI {
    ALGMICKCABI_FLANKPMJBMH = 0;
    ALGMICKCABI_LMHJFBBDLNH = 1;
}

message AnnounceData {
    uint32 config_id = 2;
    int64 begin_time = 3;
    bool has_recommand = 6;
    uint32 banner_frequency = 8;
    int64 end_time = 10;
    bool BBEBEKFGMAD = 11;
    string emergency_text = 12;
    string banner_text = 15;
}

message AntiAddictScNotify {
    uint32 msg_type = 8;
    string level = 11;
    string msg = 12;
}

message BlackInfo {
    int64 begin_time = 1;
    int64 end_time = 2;
    uint32 limit_level = 3;
    uint32 ban_type = 4;
}

message ClientDownloadData {
    uint32 version = 1;
    int64 time = 2;
    bytes data = 3;
    uint32 channel_id = 4;
}

message ClientObjDownloadData {
    bytes sc_info = 1;
    ClientDownloadData client_obj_download_data = 2;
    repeated ClientDownloadData dyn_code = 3;
}

message ClientObjDownloadDataScNotify {
    ClientObjDownloadData data = 11;
}

message ClientObjUploadCsReq {
    ALGMICKCABI content_type = 1;
    uint32 EOHFCODKKMD = 4;
    bytes sc_data = 14;
}

message ClientObjUploadScRsp {
    uint32 retcode = 2;
    ClientObjDownloadData data = 12;
}

enum CmdPlayerType {
    CmdPlayerType_NLCDGIPGFDJ = 0;
    CmdPlayerType_HDDNALCIJDE = 98;
    CmdPlayerType_ONNNLNCMMGJ = 58;
    CmdPlayerType_BCOPKPAPNAI = 88;
    CmdPlayerType_LLGMMAPJDLI = 56;
    CmdPlayerType_UpdateFeatureSwitchScNotify = 52;
    CmdPlayerType_GmTalkScNotify = 47;
    CmdPlayerType_SetPlayerInfoScRsp = 44;
    CmdPlayerType_GetBasicInfoScRsp = 14;
    CmdPlayerType_SetRedPointStatusScNotify = 95;
    CmdPlayerType_ABAKFMHMHPD = 67;
    CmdPlayerType_BFMIAMIHIED = 5;
    CmdPlayerType_COENAOLHFEL = 53;
    CmdPlayerType_GetLevelRewardScRsp = 72;
    CmdPlayerType_GetLevelRewardCsReq = 42;
    CmdPlayerType_GetLevelRewardGetListCsReq = 65;
    CmdPlayerType_IPDCEJGOFKI = 76;
    CmdPlayerType_AFKIMICKEDM = 4;
    CmdPlayerType_GetBasicInfoCsReq = 20;
    CmdPlayerType_QueryProductInfoScRsp = 18;
    CmdPlayerType_PlayerGetTokenScRsp = 81;
    CmdPlayerType_GetSecretKeyInfoScRsp = 74;
    CmdPlayerType_ExchangeStaminaCsReq = 38;
    CmdPlayerType_ExchangeStaminaScRsp = 39;
    CmdPlayerType_MonthCardRewardNotify = 46;
    CmdPlayerType_KCCMJKHJMAB = 90;
    CmdPlayerType_LoginAllPacketsCsReq = 57;
    CmdPlayerType_RegionStopScNotify = 36;
    CmdPlayerType_AntiAddictScNotify = 48;
    CmdPlayerType_PlayerLoginScRsp = 78;
    CmdPlayerType_MCFLGBJENJD = 59;
    CmdPlayerType_IBPHMNFDGCA = 71;
    CmdPlayerType_JBHLDLGENMB = 25;
    CmdPlayerType_LAKJLNGMLPC = 28;
    CmdPlayerType_KPALKJHKPED = 12;
    CmdPlayerType_CJOBOBANBOA = 93;
    CmdPlayerType_CEDFKEJBCCJ = 51;
    CmdPlayerType_SetNicknameScRsp = 69;
    CmdPlayerType_PlayerSqueezedScNotify = 26;
    CmdPlayerType_OPFIKLLIHBH = 15;
    CmdPlayerType_HONJDBCACEB = 82;
    CmdPlayerType_KGCPBEOGMOP = 21;
    CmdPlayerType_HLAAGBFPKPH = 91;
    CmdPlayerType_GetVideoVersionKeyCsReq = 23;
    CmdPlayerType_UpdatePlayerSettingScRsp = 3;
    CmdPlayerType_FeatureSwitchClosedScNotify = 66;
    CmdPlayerType_ServerAnnounceNotify = 41;
    CmdPlayerType_CAEEPLEGLCK = 75;
    CmdPlayerType_GetSecretKeyInfoCsReq = 6;
    CmdPlayerType_POACPAFBFKJ = 62;
    CmdPlayerType_MTPInformationCsReq = 37;
    CmdPlayerType_ClientObjUploadCsReq = 64;
    CmdPlayerType_ClientManagedSettingCsReq = 97;
    CmdPlayerType_EnterStageCsReq = 13;
    CmdPlayerType_GetVideoVersionKeyScRsp = 83;
    CmdPlayerType_ForceSyncGameStateFinishCSReq = 54;
    CmdPlayerType_GetAuthkeyScRsp = 11;
    CmdPlayerType_ReserveStaminaExchangeScRsp = 32;
    CmdPlayerType_StaminaInfoScNotify = 70;
    CmdPlayerType_SetGenderScRsp = 35;
    CmdPlayerType_SetGameplayBirthdayScRsp = 94;
    CmdPlayerType_ClientObjUploadScRsp = 68;
    CmdPlayerType_BLLKMJKMNIG = 19;
    CmdPlayerType_ClientObjDownloadDataScNotify = 1;
    CmdPlayerType_DailyRefreshNotify = 89;
    CmdPlayerType_GetLevelRewardTakenListScRsp = 30;
    CmdPlayerType_PlayerLoginFinishScRsp = 27;
    CmdPlayerType_FCNEJBELPDL = 45;
}

message DailyRefreshNotify {
    uint32 MDIIJKBHBBI = 10;
}

message EAFHBODFEKM {
    oneof GBGKEJPFEIL {
        bool CNMAFMEKADJ = 1829;
        GLNJKGOGKKL BDHBFFEOPFG = 378;
        GLNJKGOGKKL DLDGBIBHDKM = 279;
    }
}

message EnterStageCsReq {
    string stop_desc = 12;
}

message ExchangeStaminaCsReq {
}

message ExchangeStaminaScRsp {
    uint32 exchange_times = 2;
    uint32 retcode = 3;
    int64 last_recover_time = 6;
    uint32 stamina_add = 10;
    repeated ItemCost item_cost_list = 13;
}

message FLMODPLLMNF {
    string GIFOENLDCHO = 8;
    uint32 NMELIDCDKAK = 14;
}

message FeatureSwitchClosedScNotify {
    FeatureSwitchType FMGLEBCIBHG = 6;
}

enum FeatureSwitchType {
    BLOHGFCFEEL_OLLFDOONPPH = 0;
    BLOHGFCFEEL_CMPBOEFPAFF = 1;
    BLOHGFCFEEL_NPMMMJEABDA = 2;
    BLOHGFCFEEL_LDFMLGODBCI = 3;
    BLOHGFCFEEL_IMFCEBAFAOD = 4;
    BLOHGFCFEEL_PMJOGFFOGGA = 5;
    BLOHGFCFEEL_GMGNBIKFFJG = 6;
    BLOHGFCFEEL_NEHKLAFBDHN = 7;
    BLOHGFCFEEL_CJLCHBBLENG = 8;
    BLOHGFCFEEL_JNKNFAIIGMK = 9;
    BLOHGFCFEEL_GMKIADNCPNI = 10;
    BLOHGFCFEEL_MGICOLCGDAB = 11;
    BLOHGFCFEEL_NGPACINNIMD = 12;
    BLOHGFCFEEL_OAIEBHMHLEP = 13;
    BLOHGFCFEEL_FIPDOKKDAAC = 14;
    BLOHGFCFEEL_APHDKDPMEFF = 15;
    BLOHGFCFEEL_PIFHPBHFBOB = 16;
    BLOHGFCFEEL_EGGFIKODABA = 17;
    BLOHGFCFEEL_PHOKAODFGGN = 18;
    BLOHGFCFEEL_DDJKAMDEFOB = 19;
    BLOHGFCFEEL_BFNCHIOOEGI = 20;
    BLOHGFCFEEL_EAKICFJGJCG = 21;
    BLOHGFCFEEL_JLJGFFJBMAP = 22;
    BLOHGFCFEEL_DBMIBEJDGNK = 23;
    BLOHGFCFEEL_LIHGIPDAMEE = 24;
    BLOHGFCFEEL_PBMEFECMLBN = 25;
    BLOHGFCFEEL_NJIBBLDHBPA = 26;
    BLOHGFCFEEL_JNOJKPFDENE = 27;
    BLOHGFCFEEL_HHNGOAPLCAJ = 28;
    BLOHGFCFEEL_PJIADEFEOCE = 29;
    BLOHGFCFEEL_ELJKDENKLBB = 30;
    BLOHGFCFEEL_HPHLHNECBNC = 32;
    BLOHGFCFEEL_ODBDMOCCODH = 33;
    BLOHGFCFEEL_CACHILIJDAO = 34;
    BLOHGFCFEEL_AEILDNIMLHF = 35;
    BLOHGFCFEEL_PNLHBBLODFA = 36;
    BLOHGFCFEEL_FJBIEBHJGON = 37;
    BLOHGFCFEEL_AOJPPBMCIEJ = 38;
    BLOHGFCFEEL_MEEHJJDBMKP = 39;
    BLOHGFCFEEL_ODPBAGEBPGL = 40;
    BLOHGFCFEEL_MIJANGMGPKL = 41;
    BLOHGFCFEEL_CGHNMCHABLO = 42;
    BLOHGFCFEEL_FBKIFMKMLNO = 43;
    BLOHGFCFEEL_HLFPEFNLMLE = 44;
    BLOHGFCFEEL_BIFDPCPBGLN = 45;
    BLOHGFCFEEL_DCPIMKDCFLE = 46;
    BLOHGFCFEEL_KJDBBPEHCNO = 47;
    BLOHGFCFEEL_NIBGLJHFMNO = 48;
    BLOHGFCFEEL_HOPBLPLCJLO = 49;
    BLOHGFCFEEL_FOHOHLFLEEJ = 50;
    BLOHGFCFEEL_NAFKMFKGKPN = 51;
    BLOHGFCFEEL_OIAKLFCDFCK = 52;
    BLOHGFCFEEL_KFILNDOMNAA = 53;
    BLOHGFCFEEL_OBEDFFDLDKD = 54;
    BLOHGFCFEEL_FHJBILODKOO = 55;
    BLOHGFCFEEL_IBKCCGOBPLK = 56;
    BLOHGFCFEEL_MJHMECNJIFB = 58;
    BLOHGFCFEEL_GIFAIEODMBC = 59;
    BLOHGFCFEEL_GALJOECHLAA = 60;
    BLOHGFCFEEL_NHEFHKBDCMC = 61;
    BLOHGFCFEEL_CKNEFAPKNBD = 62;
    BLOHGFCFEEL_FJKMNDDEKOA = 63;
    BLOHGFCFEEL_FFNGHDIANMA = 64;
    BLOHGFCFEEL_KEEENOCCNND = 65;
    BLOHGFCFEEL_GPLCBDBKCPD = 66;
    BLOHGFCFEEL_KEFJFJDBPKG = 67;
    BLOHGFCFEEL_ACFLOIONODA = 68;
    BLOHGFCFEEL_OPGDDDOGGOE = 69;
    BLOHGFCFEEL_OMBHMDBLDEJ = 70;
    BLOHGFCFEEL_NCIHPLBABNC = 71;
    BLOHGFCFEEL_AKGLHLMIKMM = 72;
    BLOHGFCFEEL_BCLMECHBIKB = 73;
    BLOHGFCFEEL_GEBMCAOAIEJ = 74;
    BLOHGFCFEEL_EGGIGABAHPO = 75;
    BLOHGFCFEEL_KJMDGIIOPOO = 76;
    BLOHGFCFEEL_FCJAFAGBGLG = 77;
    BLOHGFCFEEL_KNGBCAFGALI = 78;
    BLOHGFCFEEL_HGGNFJCKBDA = 79;
    BLOHGFCFEEL_FANNNOPGFBB = 80;
    BLOHGFCFEEL_BFJNFBIJINB = 81;
    BLOHGFCFEEL_JGKMCBGFJLL = 82;
    BLOHGFCFEEL_AJBAFCAMEMH = 83;
    BLOHGFCFEEL_OCDKAOGLBPC = 84;
    BLOHGFCFEEL_NCHIOPJLMFE = 85;
    BLOHGFCFEEL_POEHEEKBHLH = 86;
    BLOHGFCFEEL_EBGFEKLFJDB = 87;
    BLOHGFCFEEL_JOJLKCIGHAJ = 88;
    BLOHGFCFEEL_IGBCOPCFPAI = 89;
    BLOHGFCFEEL_GAFEEBBCOEK = 90;
    BLOHGFCFEEL_COOFLDLKDFM = 91;
    BLOHGFCFEEL_KNMALPBJLJL = 92;
    BLOHGFCFEEL_IPDDHMBDLJI = 93;
    BLOHGFCFEEL_ANCKMNILOCG = 94;
    BLOHGFCFEEL_KACOHBEJFOD = 95;
    BLOHGFCFEEL_KGMKFOPKJPK = 96;
    BLOHGFCFEEL_HBMLKNFMGEN = 97;
    BLOHGFCFEEL_AFNFHMPAPFN = 98;
    BLOHGFCFEEL_MOMBNANDPNO = 99;
}

message ForceSyncGameStateFinishCSReq {
}

message GGIHCKPGACF {
    repeated string PKLFOJBALKK = 4;
    repeated string HBBIHGLHKDM = 6;
    repeated string EHMGEMMNPLA = 8;
    uint32 retcode = 9;
}

message GLNJKGOGKKL {
    repeated string ODAHKGONNHJ = 2;
}

enum Gender {
    GenderNone = 0;
    GenderMan = 1;
    GenderWoman = 2;
}

message GetAuthkeyScRsp {
    uint32 retcode = 5;
    uint32 authkey_ver = 6;
    uint32 sign_type = 8;
    string auth_appid = 9;
    string authkey = 15;
}

message GetBasicInfoCsReq {
}

message GetBasicInfoScRsp {
    uint32 exchange_times = 1;
    uint32 gameplay_birthday = 2;
    bool is_gender_set = 4;
    uint32 week_cocoon_finished_count = 5;
    uint32 gender = 7;
    int64 last_set_nickname_time = 9;
    uint32 retcode = 10;
    uint32 cur_day = 11;
    PlayerSettingInfo player_setting_info = 12;
    int64 next_recover_time = 13;
}

message GetLevelRewardCsReq {
    uint32 interacted_prop_entity_id = 3;
    uint32 level = 9;
}

message GetLevelRewardScRsp {
    uint32 level = 2;
    uint32 retcode = 5;
    ItemList reward = 12;
}

message GetLevelRewardTakenListScRsp {
    uint32 retcode = 13;
    repeated uint32 level_reward_taken_list = 14;
}

message GetSecretKeyInfoCsReq {
    bytes CILHEPFKKNI = 5;
}

message GetSecretKeyInfoScRsp {
    bytes secret_rsp = 4;
    repeated SecretKeyInfo secret_info = 5;
    uint32 retcode = 14;
}

message GetVideoVersionKeyCsReq {
}

message GetVideoVersionKeyScRsp {
    repeated VideoKeyInfo activity_video_key_info_list = 3;
    repeated VideoKeyInfo video_key_info_list = 10;
    uint32 retcode = 14;
}

message HBJLNKAFNAD {
    repeated uint32 switch_list = 1;
}

message HDOKNMGIDMB {
    FeatureSwitchType type = 1;
    repeated HBJLNKAFNAD BGNKLMIMBPI = 2;
    bool KPCPABKPAKL = 3;
}

message IAOCHINIPGK {
    repeated uint32 FLFBHONGDAD = 1;
    uint32 retcode = 11;
}

message IBCDDGKNICG {
    GLNJKGOGKKL black_list = 1;
    bool CNMAFMEKADJ = 2;
}

message IDAIHHGGPIJ {
    uint32 retcode = 15;
}

message JKJMAKHANPB {
    string stop_desc = 2;
}

message KEKFNKDLDOM {
    oneof JNLIJAABGFF {
        IBCDDGKNICG ICKNLCPNHCD = 1425;
        EAFHBODFEKM LOMPGELJCLM = 1509;
    }
}

message LFCHHMGGMPC {
    uint32 BMFJFFBPADD = 5;
    uint32 show_type = 7;
    uint32 EHNJDIDABHD = 8;
    uint32 content_id = 11;
}

message LFKKOMBKJIP {
    string tag = 1;
    string value = 2;
}

message MHMFPLEKOIL {
    uint32 retcode = 13;
}

message MonthCardRewardNotify {
    ItemList reward = 1;
}

message PNOLLIAKGDB {
    bool BELKCBAGMFC = 2;
    uint32 JHJKCJKDHIB = 4;
    bool MLPGDPGIFCJ = 5;
}

message PlayerGetTokenScRsp {
    string stop_desc = 3;
    uint32 retcode = 4;
    uint64 secret_key_seed = 8;
    BlackInfo black_info = 9;
    uint32 uid = 14;
    string authkey = 15;
}

message PlayerLoginFinishScRsp {
    uint32 retcode = 8;
}

message PlayerLoginScRsp {
    int32 cur_timezone = 1;
    string DKEPKHPOLHC = 3;
    string GIOAPOKHAOF = 4;
    uint32 stamina = 5;
    uint64 server_timestamp_ms = 6;
    PlayerBasicInfo basic_info = 8;
    uint64 login_random = 9;
    uint32 retcode = 11;
    bool KDNPPNHLNOA = 13;
    bool KCDAHNNCKPP = 14;
}

message PlayerSettingInfo {
    bool AACOEHCFNDB = 1;
    PNOLLIAKGDB OJPAODIHAJE = 2;
    bool DCJECFMMIBC = 3;
    bool DGCNHMIHFJB = 4;
    bool PFBHGAHAFMD = 5;
    bool GNFDDPEMMFN = 6;
    bool MAKOLELFLFH = 7;
    bool FDHEPCKLCAM = 8;
    bool IOJEAOCOBBF = 12;
    bool BOMGNMDOGLM = 14;
    bool NJAKOMDMFJD = 15;
    JPGACKPLGCD CMFCOOEEECB = 220;
    repeated KVP OKAHMFOINPM = 491;
    bool HGPFFGKNPFB = 524;
    bool GOKFNGFFMOB = 1458;
    bool BBEEBBIDJHE = 1685;
    bool LNGHIJGFDKP = 1773;
}

message PlayerSqueezedScNotify {
    enum KickType {
        KICK_SQUEEZED = 0;
        KICK_BLACK = 1;
        KICK_CHANGE_PWD = 2;
        KICK_LOGIN_WHITE_TIMEOUT = 3;
        KICK_ACE_ANTI_CHEATER = 4;
        KICK_BY_GM = 5;
    }
    BlackInfo black_info = 8;
    PlayerSqueezedScNotify.KickType kick_type = 9;
}

message Product {
    uint32 ENCDABOOIKJ = 1;
    int64 end_time = 2;
    uint32 CLDELMPNAPB = 3;
    string price_tier = 4;
    int64 begin_time = 5;
    string product_id = 7;
    bool double_reward = 8;
    ProductGiftType gift_type = 10;
    uint32 EMIHEDNKBCA = 15;
}

enum ProductGiftType {
    PRODUCT_GIFT_NONE = 0;
    PRODUCT_GIFT_COIN = 1;
    PRODUCT_GIFT_MONTH_CARD = 2;
    PRODUCT_GIFT_BP_68 = 3;
    PRODUCT_GIFT_BP_128 = 4;
    PRODUCT_GIFT_BP68_UPGRADE_128 = 5;
    PRODUCT_GIFT_POINT_CARD = 6;
    PRODUCT_GIFT_PS_PRE_ORDER_1 = 7;
    PRODUCT_GIFT_PS_PRE_ORDER_2 = 8;
    PRODUCT_GIFT_GOOGLE_POINTS_100 = 9;
    PRODUCT_GIFT_GOOGLE_POINTS_150 = 10;
    PRODUCT_GIFT_PS_POINT_CARD_030 = 11;
    PRODUCT_GIFT_PS_POINT_CARD_050 = 12;
    PRODUCT_GIFT_PS_POINT_CARD_100 = 13;
    PRODUCT_GIFT_PSN_PLUS = 14;
    PRODUCT_GIFT_SINGLE_6 = 15;
    PRODUCT_GIFT_DAILY_LOGIN_30 = 16;
    PRODUCT_GIFT_APPLE_GIFT_CARD = 17;
    PRODUCT_GIFT_FTC_UP_GACHA_TICKET_1 = 18;
    PRODUCT_GIFT_FTC_UP_GACHA_TICKET_10 = 19;
    PRODUCT_GIFT_FTC_NORMAL_GACHA_TICKET_1 = 20;
    PRODUCT_GIFT_FTC_NORMAL_GACHA_TICKET_10 = 21;
    PRODUCT_GIFT_TICKET_10 = 22;
    EJEBHIIKAJF_DBIADNGNFMD = 23;
    ProductGiftType_OOLBPMEJANG = 24;
    ProductGiftType_NKJADAFIFIK = 25;
}

message QueryProductInfoScRsp {
    repeated Product product_list = 4;
    uint32 BFFHEKCGLMA = 5;
    uint32 BEBFNDIGKFK = 6;
    uint64 month_card_out_date_time = 7;
    uint32 retcode = 14;
}

message RegionStopScNotify {
    int64 stop_end_time = 1;
    int64 stop_begin_time = 11;
}

message ReserveStaminaExchangeScRsp {
    uint32 retcode = 12;
    uint32 num = 14;
}

message SecretKeyInfo {
    SecretKeyType type = 3;
    string secret_key = 13;
}

enum SecretKeyType {
    SECRET_KEY_NONE = 0;
    SECRET_KEY_SERVER_CHECK = 1;
    SECRET_KEY_VIDEO = 2;
    SECRET_KEY_BATTLE_TIME = 3;
}

message ServerAnnounceNotify {
    repeated AnnounceData announce_data_list = 8;
}

message SetGameplayBirthdayScRsp {
    uint32 retcode = 7;
    uint32 birthday = 12;
}

message SetGenderScRsp {
    MultiPathAvatarType cur_avatar_path = 8;
    uint32 retcode = 12;
}

message SetNicknameScRsp {
    int64 set_time = 1;
    bool is_modify = 8;
    uint32 retcode = 15;
}

message SetPlayerInfoScRsp {
    uint32 retcode = 1;
    bool is_modify = 5;
    MultiPathAvatarType cur_avatar_path = 7;
    int64 set_time = 10;
}

message SetRedPointStatusScNotify {
    uint32 BMFJFFBPADD = 1;
    uint32 content_id = 6;
    uint32 show_type = 7;
    repeated LFCHHMGGMPC BKAKIJOACPO = 9;
    uint32 uid = 15;
}

message StaminaInfoScNotify {
    uint32 stamina = 4;
    uint32 reserve_stamina = 7;
    int64 next_recover_time = 10;
    int64 EHJCPBJNEOO = 15;
}

message UpdateFeatureSwitchScNotify {
    repeated HDOKNMGIDMB switch_info_list = 13;
}

message UpdatePlayerSetting {
    oneof BKAGLMFNKKA {
        bool AACOEHCFNDB = 9;
        bool DGCNHMIHFJB = 5;
        bool FDHEPCKLCAM = 7;
        bool DCJECFMMIBC = 12;
        bool IOJEAOCOBBF = 1;
        bool PFBHGAHAFMD = 4;
        bool GNFDDPEMMFN = 8;
        bool MAKOLELFLFH = 6;
        bool NJAKOMDMFJD = 2;
        PNOLLIAKGDB OJPAODIHAJE = 14;
        bool BOMGNMDOGLM = 56;
        bool BBEEBBIDJHE = 1951;
        bool HGPFFGKNPFB = 1477;
        bool LNGHIJGFDKP = 541;
        bool GOKFNGFFMOB = 1238;
        JPGACKPLGCD CMFCOOEEECB = 1738;
        KVP EGLOIFDIDPK = 1456;
    }
}

message UpdatePlayerSettingScRsp {
    UpdatePlayerSetting player_setting = 6;
    uint32 retcode = 13;
}

message VideoKeyInfo {
    uint64 IBDIMHPOPOJ = 1;
    uint32 id = 2;
    uint64 video_key = 11;
}
