syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdQuestType {
    CmdQuestType_NLCDGIPGFDJ = 0;
    CmdQuestType_TakeQuestOptionalRewardScRsp = 933;
    CmdQuestType_TakeQuestRewardScRsp = 958;
    CmdQuestType_IKABMLMGLHN = 940;
    CmdQuestType_GetQuestRecordScRsp = 947;
    CmdQuestType_FinishClientAchievementCsReq = 913;
    CmdQuestType_OJKCEKKDLEL = 939;
    CmdQuestType_PJEHEOLCFCF = 904;
    CmdQuestType_GetQuestRecordCsReq = 986;
    CmdQuestType_OIHECCNGJKO = 993;
    CmdQuestType_GetQuestDataCsReq = 925;
    CmdQuestType_GetQuestDataScRsp = 978;
    CmdQuestType_CFHHFHMGAGL = 971;
    CmdQuestType_QuestRecordScNotify = 926;
}

message ECLGDFGGOFH {
    uint32 MNLAMKJIAOC = 2;
    uint32 progress = 15;
}

message GetQuestDataCsReq {
}

message GetQuestDataScRsp {
    uint32 retcode = 3;
    repeated Quest quest_list = 13;
}

message GetQuestRecordCsReq {
}

message GetQuestRecordScRsp {
    repeated ECLGDFGGOFH AOOFGCNFBPL = 6;
    uint32 retcode = 10;
}

message QuestRecordScNotify {
    ECLGDFGGOFH HLMPJLDBPJP = 3;
}

message TakeQuestOptionalRewardScRsp {
    ItemList reward = 2;
    uint32 quest_id = 6;
    uint32 retcode = 13;
}

message TakeQuestRewardScRsp {
    repeated uint32 succ_quest_id_list = 5;
    ItemList reward = 9;
    uint32 retcode = 10;
    repeated uint32 quest_id_list = 13;
}
