syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ACMKPNMKOKH {
    uint32 queue_position = 1;
    FKBOOENADFM detail = 4;
}

message AEJLPCAIODP {
    uint32 BAOFIGFFMLN = 7;
}

message AGKONMPOJKP {
    repeated ELGOBKCNOHH MAJGMMCOCIG = 15;
}

message AHLALEEJOEG {
    repeated MGJDNGHDIKG LFCGPOKMJLC = 10;
}

message AHNLMMFHOME {
    MMBBHFNJILI ACCCINPPINC = 10;
}

message ALJJNBKGEOC {
    repeated uint32 EHKPMGBCPCG = 9;
}

message ALMGFDOPLGA {
    uint32 FGIHKKKOGJD = 7;
}

message ANMDOACPHMN {
    BDPHJAEBKAD POOGLPNNDAB = 1;
}

message AOFKCKOIFCM {
    DNLKMHLAPHC LANFFLCLGAH = 11;
}

message AOMOENMNCNB {
    uint32 OJPGDDFJCHB = 14;
}

message APOKGADPHDC {
}

message BAHBCFDAIKG {
    repeated BBHHENEONHO HIILDALHIMD = 11;
}

message BAJDLLEFGHB {
    ItemCostData cost_data = 2;
    uint32 JFIGNBBLCIM = 3;
    int32 LIAGGDDILGO = 14;
}

message BBHHENEONHO {
    uint32 KGOPHALLLLI = 2;
    bool IFIGFODOPBB = 3;
    uint32 CFKKKPNKHEL = 9;
    ItemCostData cost_data = 10;
    ItemCostData IOJFGBDPPHI = 12;
}

message BCOEGNBGJFC {
    oneof PKMEJECPMCH {
        BAJDLLEFGHB NLJPONKBMFI = 14;
        BJBIFIMJDOL BBNEGKCNMBA = 3;
        BLICCEHIOLH PKPIEFOBHKH = 9;
        OMNMBANDCBA FKMADCAFJMC = 11;
        DCEPBLJKNNE PHLEDABHDML = 1;
        FBOFEOCHDMN DDLADFJMEEC = 2;
        BAHBCFDAIKG OJEANDPABHC = 13;
        GNFDPONFLJD CLLEJEPNBDH = 7;
        OJPMMKIJIFH DNHKNALBAMG = 5;
        EHELNMGMENO LBBCJHOPEPH = 4;
        LPODFEEGDOB KDFGAKDCMIK = 12;
    }
}

message BDPHJAEBKAD {
    repeated RogueAdventureRoomGameplayWolfGunTarget battle_target_list = 5;
    uint32 NFGNOCBCKID = 15;
}

message BFAMBJHPNGE {
    uint32 GEGJGJKMELD = 1;
}

message BIHACLHMAKO {
    uint32 AIAFEKGBFIF = 9;
}

message BJBIFIMJDOL {
    ItemCostData cost_data = 8;
    int32 LIAGGDDILGO = 12;
    uint32 JFIGNBBLCIM = 15;
}

message BLICCEHIOLH {
    uint32 cur_num = 3;
    uint32 max_num = 4;
    map<uint32, uint32> LBEIHAOKHAD = 11;
}

message BOHAJCPBBJI {
}

message BPHIKPCNBHM {
    uint32 maze_buff_id = 9;
}

message BPLNKHGAILK {
    uint32 BAOFIGFFMLN = 12;
}

message BPOKOPCGMAJ {
    int32 change_value = 4;
}

message BuyRogueShopBuffScRsp {
    uint32 retcode = 1;
    DAENHKENJHK HABJHGPFGEB = 12;
}

message BuyRogueShopFormulaScRsp {
    GBHAHDBDOIE EAPCJKNGGCA = 6;
    uint32 retcode = 13;
}

message BuyRogueShopMiracleCsReq {
    repeated uint32 KOFNOJCMEFA = 7;
    uint32 interacted_prop_entity_id = 14;
}

message BuyRogueShopMiracleScRsp {
    uint32 retcode = 1;
    AGKONMPOJKP DNPCCFFFBHN = 12;
}

message CCKJAEDDDCL {
    oneof KKNBOACNCON {
        KPIHDPGDMKB BMGOLFNGHGH = 6;
        AHLALEEJOEG BBEKBJPHEJK = 14;
        CDDEIPOBBCN MECOEFEJANE = 5;
        GANFMBPEJPF ABPOOCOOKCF = 15;
    }
}

message CDDEIPOBBCN {
    repeated uint32 BHAGLNBNGBP = 6;
}

message CEDCDDPHBOG {
}

message CFJNAPDIMKM {
    repeated OMJGKNJKHCH EMLLEPOADED = 6;
}

message CHDPILMCJNP {
}

message CHEPPLBNOFF {
    uint32 OJPGDDFJCHB = 12;
}

message CIBMBDDOGBH {
    uint32 OOMKNHFIGAF = 11;
}

message CIGDBCKOFBN {
    uint32 NPNMLPNBHDP = 2;
    bool ALAJJMKOMML = 10;
}

message CJAFLDKHDAF {
    HMAAICNBKCI value = 13;
}

message CKEOMFNPKPO {
    KOFMGCNIMIN miracle = 15;
}

message CKPKIINILKA {
    uint32 retcode = 2;
    HHAGOFKBFAP DJMHHMMABJL = 12;
}

message CLMPCCGCADK {
    uint32 EOOLCIACHFJ = 15;
}

message COKKOEBBEGM {
    uint32 HDGPBCJPNBE = 5;
}

enum CmdRogueCommonType {
    CmdRogueCommonType_NLCDGIPGFDJ = 0;
    CmdRogueCommonType_GPJHECIHEGG = 5678;
    CmdRogueCommonType_OLEJGPFJPEI = 5660;
    CmdRogueCommonType_BuyRogueShopMiracleScRsp = 5626;
    CmdRogueCommonType_GetRogueShopMiracleInfoCsReq = 5658;
    CmdRogueCommonType_BuyRogueShopFormulaCsReq = 5667;
    CmdRogueCommonType_GetRogueShopMiracleInfoScRsp = 5688;
    CmdRogueCommonType_SyncRogueCommonDialogueOptionFinishScNotify = 5657;
    CmdRogueCommonType_FCHIJLIDKPK = 5620;
    CmdRogueCommonType_RogueWorkbenchHandleFuncScRsp = 5617;
    CmdRogueCommonType_CommonRogueVirtualItemInfoScNotify = 5614;
    CmdRogueCommonType_BPALBPHJNNP = 5623;
    CmdRogueCommonType_JJDADDOICGE = 5649;
    CmdRogueCommonType_SetRogueExhibitionScRsp = 5670;
    CmdRogueCommonType_RefreshRogueShopBuffCsReq = 5681;
    CmdRogueCommonType_RogueDoGambleScRsp = 5624;
    CmdRogueCommonType_RogueGetGambleInfoScRsp = 5607;
    CmdRogueCommonType_HandleRogueCommonPendingActionScRsp = 5651;
    CmdRogueCommonType_GetRogueShopBuffInfoScRsp = 5686;
    CmdRogueCommonType_CDCNMGIJEHJ = 5642;
    CmdRogueCommonType_FinishRogueCommonDialogueCsReq = 5616;
    CmdRogueCommonType_DNEFIPNCEHK = 5687;
    CmdRogueCommonType_CommonRogueQueryScRsp = 5619;
    CmdRogueCommonType_GIMIJDFDNGN = 5666;
    CmdRogueCommonType_GetRogueShopFormulaInfoScRsp = 5608;
    CmdRogueCommonType_LCBHOHJEJJB = 5695;
    CmdRogueCommonType_LJPHELEEEIM = 5625;
    CmdRogueCommonType_JDEGIBDGNKN = 5652;
    CmdRogueCommonType_SyncRogueCommonPendingActionScNotify = 5653;
    CmdRogueCommonType_BAECOJPJADA = 5672;
    CmdRogueCommonType_SetRogueCollectionScRsp = 5690;
    CmdRogueCommonType_GetRogueHandbookDataScRsp = 5612;
    CmdRogueCommonType_RogueWorkbenchGetInfoScRsp = 5683;
    CmdRogueCommonType_RogueMiracleSelectActionSelectCsReq = 5637;
    CmdRogueCommonType_SyncRogueHandbookDataUpdateScNotify = 5635;
    CmdRogueCommonType_TakeEventHandbookRewardScRsp = 5615;
    CmdRogueCommonType_BuyRogueShopBuffScRsp = 5671;
    CmdRogueCommonType_ENHIGLGFBJP = 5639;
    CmdRogueCommonType_CommonRogueUpdateScNotify = 5628;
    CmdRogueCommonType_SyncRogueCommonDialogueDataScNotify = 5674;
    CmdRogueCommonType_GetRogueCommonDialogueDataCsReq = 5698;
    CmdRogueCommonType_LJIGIJBBJHN = 5654;
    CmdRogueCommonType_RogueShopBeginBattleScRsp = 5656;
    CmdRogueCommonType_GKDNKDIHJDA = 5680;
    CmdRogueCommonType_HFKJDMNODNJ = 5679;
    CmdRogueCommonType_BuyRogueShopBuffCsReq = 5613;
    CmdRogueCommonType_GetRogueAdventureRoomInfoCsReq = 5638;
    CmdRogueCommonType_GetRogueHandbookDataCsReq = 5673;
    CmdRogueCommonType_RefreshRogueShopFormulaCsReq = 5700;
    CmdRogueCommonType_MNCPDJLJFIK = 5632;
    CmdRogueCommonType_ECGCIPCGADI = 5669;
    CmdRogueCommonType_TakeRogueMiracleHandbookRewardScRsp = 5644;
    CmdRogueCommonType_CMMJIMDDPND = 5693;
    CmdRogueCommonType_FPPOLDDIGFF = 5630;
    CmdRogueCommonType_INKGIMABIBD = 5646;
    CmdRogueCommonType_KHEBIGENECE = 5675;
    CmdRogueCommonType_SelectRogueCommonDialogueOptionScRsp = 5655;
    CmdRogueCommonType_SyncRogueCommonActionResultScNotify = 5618;
    CmdRogueCommonType_PGJMHOEBBFM = 5633;
    CmdRogueCommonType_HDNLKKBJCAA = 5640;
    CmdRogueCommonType_BuyRogueShopFormulaScRsp = 5676;
    CmdRogueCommonType_GetRogueCommonDialogueDataScRsp = 5662;
    CmdRogueCommonType_DNNECBLLKBO = 5665;
    CmdRogueCommonType_BuyRogueShopMiracleCsReq = 5647;
    CmdRogueCommonType_FinishRogueCommonDialogueScRsp = 5606;
}

message CommonRogueQueryScRsp {
    uint32 GLGHEOPPCMH = 2;
    uint32 retcode = 10;
    repeated CCKJAEDDDCL LFLCDNGALME = 15;
}

message CommonRogueUpdateScNotify {
    oneof NOKMOIHLGBN {
        KPIHDPGDMKB BMGOLFNGHGH = 6;
        AHLALEEJOEG BBEKBJPHEJK = 14;
        CDDEIPOBBCN MECOEFEJANE = 3;
    }
}

message CommonRogueVirtualItemInfoScNotify {
    repeated LKCDLJCKCJI DMCINCJLMND = 15;
}

message DAENHKENJHK {
    repeated KJEOBMBMNIN buff_list = 2;
}

message DCADHJHJMMD {
    HHAGOFKBFAP DJMHHMMABJL = 7;
    uint32 retcode = 11;
}

message DCEPBLJKNNE {
    int32 LIAGGDDILGO = 2;
    ItemCostData cost_data = 4;
    uint32 JFIGNBBLCIM = 15;
}

message DEMENEAAGAA {
}

message DGKLPPLJBNB {
    uint32 CNFGOHFPLGO = 1;
    uint32 EFCAJENMLKA = 10;
    LBPLJCHEJOK status = 11;
}

enum DICEONDKEFF {
    DICEONDKEFF_NLCDGIPGFDJ = 0;
    DICEONDKEFF_ICFONCMFNLG = 1;
    DICEONDKEFF_KDDIPFACJAJ = 2;
}

message DIKBPKAKENO {
    uint32 EFCAJENMLKA = 1;
    NKLAEHJPIMN status = 3;
}

message DOEJLDNIDED {
    uint32 DPGKMIIBPDB = 9;
}

message EBOLNPIMDAL {
    uint32 battle_event_id = 5;
    bool is_win = 10;
    map<uint32, uint32> NGJJMOIAJKO = 14;
}

message EDBOGEKADGP {
    uint32 KGEBFIOJFLC = 2;
    repeated uint32 EEDPLDBFMMM = 11;
}

message EDDEOKAIJAB {
    uint32 AMOABLICEDP = 2;
}

message EGMPACONNFP {
    uint32 NPBLEKPLPFA = 10;
    uint32 GNCFHIKODKE = 12;
    uint32 unique_id = 13;
}

message EHELNMGMENO {
    repeated NEFBECKCJIH MALDOMHPILM = 15;
}

message EJBEEKFJAHM {
    uint32 CFKKKPNKHEL = 2;
}

message EKIFAOJKOCL {
    oneof GBFHOGKMMEA {
        uint32 unique_id = 14;
        uint32 JAMNNBEPPKE = 13;
    }
}

message ELGOBKCNOHH {
    ItemCostData cost_data = 3;
    uint32 LJCEOGPOGBE = 5;
    bool BELPGDAGFIH = 8;
    ItemCostData KINNMAGDDJJ = 9;
    bool GCIHGKCJOGB = 15;
}

message ELJDPDFMLPM {
    KPOFAPDKBJA ICKMKPJACAB = 4;
}

message EOIFLHMPBIF {
    MMFOGJPOHGJ owner_type = 3;
    uint64 GAHFPGCPAJA = 11;
}

message FBGIINJFCCD {
    LEJFIEPMMGG DKEENIMPLKD = 8;
}

message FBOFEOCHDMN {
    repeated LNPGBGDPIIK GJGFCCKEMFD = 8;
}

message FEIJPEJBDDH {
    int32 count = 9;
}

message FENFEHCCOCA {
}

message FHAAGBGAHLO {
    uint32 CJGIOODIADG = 5;
}

message FKBOOENADFM {
    oneof MMCGBGDJIPN {
        LPLHNOPDKHI PDFDENDALFD = 12;
        IDMHNMOLHKN HIMDHCBOFEH = 3;
        EOIFLHMPBIF NGEFAPOENBD = 6;
        GGCFMPIBGHA KBAMEDDAIIN = 15;
        KNOLJDOPBDG LIAODKPFBHA = 8;
    }
}

message FKOGDINOBDF {
    GGGBAIAPDLO PCHGEGFBKLF = 1;
}

message FLCPMJGCHID {
    uint32 retcode = 8;
    HHAGOFKBFAP DJMHHMMABJL = 9;
}

message FOINGKNPBLJ {
    uint32 KAHMGPGPOII = 2;
}

message GANFMBPEJPF {
    repeated DIKBPKAKENO JFHKJOGEOND = 1;
    repeated JMJEIBGACMD CEPDOBEIEFG = 6;
    repeated DGKLPPLJBNB PAKECMNPEJJ = 9;
    repeated NPAJHGDEIDJ DPIKOCFILGP = 15;
}

message GBHAHDBDOIE {
    repeated OMLMOJIGLEE KJFEFFGPNFF = 15;
}

message GBKILNHHGLB {
    repeated uint32 GMMAFIONFNF = 13;
}

message GDIKLACNOEJ {
    OKCCLEEPELM ACCCINPPINC = 4;
}

message GGCFMPIBGHA {
    repeated AKMCODLAEKI GFKAFIFMHNF = 2;
}

message GJIHIMKICLG {
    uint32 MEOHDNHGPMF = 4;
}

message GKNPEGHPCMH {
    uint32 retcode = 15;
}

message GNFDPONFLJD {
    ItemCostData cost_data = 4;
    uint32 JFIGNBBLCIM = 9;
    int32 LIAGGDDILGO = 11;
}

message GNGIHJIJGMD {
    DNLKMHLAPHC LANFFLCLGAH = 12;
}

message GNLBCCHFILK {
    bool BJDEBHMKJBC = 7;
    BDJLHJDPEEK KDFKDNLNDHN = 13;
}

message GetRogueCommonDialogueDataCsReq {
}

message GetRogueCommonDialogueDataScRsp {
    repeated HFEOGNAMHCG dialogue_list = 11;
    uint32 retcode = 14;
}

message GetRogueHandbookDataCsReq {
}

message GetRogueHandbookDataScRsp {
    uint32 retcode = 9;
    NHGJEIHKKHB HAMKPLCBEBG = 12;
}

message GetRogueShopBuffInfoScRsp {
    DAENHKENJHK HABJHGPFGEB = 3;
    int32 KCBOHFNFJEA = 10;
    int32 APMGPHFHENP = 11;
    uint32 retcode = 12;
    ItemCostData JOMDKGINNEK = 15;
}

message GetRogueShopFormulaInfoScRsp {
    int32 APMGPHFHENP = 4;
    int32 KCBOHFNFJEA = 9;
    ItemCostData JOMDKGINNEK = 11;
    GBHAHDBDOIE EAPCJKNGGCA = 12;
    uint32 retcode = 14;
}

message GetRogueShopMiracleInfoCsReq {
    bool LJBCDJNNBJH = 2;
    uint32 interacted_prop_entity_id = 13;
}

message GetRogueShopMiracleInfoScRsp {
    ItemCostData JOMDKGINNEK = 2;
    uint32 retcode = 4;
    AGKONMPOJKP DNPCCFFFBHN = 5;
}

message HCNEFGJCCMB {
    uint32 PEKGIDFPBNJ = 6;
}

message HELGMBBOGMJ {
    uint32 JMNMFMHPCKD = 13;
}

message HEOBLDJAOPE {
    uint32 MJBKNMJHOGP = 1;
    uint32 OEANPIHCHHF = 14;
}

message HFEOGNAMHCG {
    uint32 AIAFEKGBFIF = 4;
    LEHBIBDGEHG owner = 10;
    repeated KDODFHMDAJI KFNMIEMBJGD = 12;
}

message HHAGOFKBFAP {
    uint32 IIMOONEHGLO = 2;
    uint32 score_id = 4;
    double NDLJIJINOBB = 7;
    ANMDOACPHMN IHNENEGKEPO = 8;
    uint32 MEFKKHAJACJ = 12;
    uint32 status = 13;
}

message HIMJNABCJMM {
    repeated EGMPACONNFP JKFNAKBGIBF = 8;
}

message HPIPKICGABB {
    AMKALFJHFJP AMIBPAGBMFP = 11;
}

message HandleRogueCommonPendingActionScRsp {
    uint32 queue_position = 2;
    uint32 BFNEPPCNOOI = 8;
    uint32 retcode = 13;
    oneof KKNBOACNCON {
        FKOGDINOBDF JFHKDEIDMOG = 7;
        HPIPKICGABB COBNPFDHMEA = 14;
        OKFPPPBNJNH LDOFNPGNJJC = 4;
        ELJDPDFMLPM PKBOEKFFMKM = 12;
        OBNEOHHDAIP FPJABECNFNA = 11;
        KLEHEHAMKLC HGBKMEHOMHA = 627;
    }
}

message IDMHNMOLHKN {
    repeated AKMCODLAEKI GFKAFIFMHNF = 4;
    uint64 GAHFPGCPAJA = 7;
    MMFOGJPOHGJ owner_type = 8;
}

message IGODPKFLDNE {
    uint32 JMNMFMHPCKD = 7;
}

message IHOFKNBNNLB {
    OCBPJLLLJGO NBKMDMGMOGK = 4;
    bool AJPLPEFCNAM = 5;
}

message IKHMHNOIGAB {
    uint32 LJCEOGPOGBE = 11;
}

message IOMEMIEAPJO {
    KOFMGCNIMIN miracle = 3;
}

message IPKOBBJPKML {
    uint32 unique_id = 15;
}

message JEKGAINCPNH {
    uint32 AHPLANFABJH = 4;
}

message JFGGDMPDKNH {
    uint32 FGKPOBCOCKM = 11;
}

message JGCMGAMHDHM {
    uint32 PGGDEHKKINP = 5;
}

message JHBEOHDMHDA {
    OCBPJLLLJGO PJJNMNJMKBG = 1;
    bool OKJJOMMGIGD = 14;
}

message JINFLJMPPHN {
    uint32 OJPGDDFJCHB = 3;
}

message JJEMDNEIMOJ {
    LEJFIEPMMGG DKEENIMPLKD = 14;
}

message JKLLLNDHJHI {
    uint32 PGDEHMAGGLF = 2;
}

message JLHJICBCHMO {
    KOFMGCNIMIN HLCPFLOPGBM = 2;
    uint32 BJIBCOHEGIJ = 15;
}

message JLJNNPIAKGH {
    uint32 score_id = 13;
    uint32 round = 15;
}

message JMJEIBGACMD {
    uint32 CNFGOHFPLGO = 3;
    uint32 ECPDJMMOGCI = 4;
    LBPLJCHEJOK status = 13;
}

message JMPNGBAILBG {
    uint32 LJCEOGPOGBE = 11;
}

message KDODFHMDAJI {
    uint32 HAFOKMHCGFM = 3;
    bool is_selected = 6;
    KNMNEJCMHGE param = 7;
    uint32 arg_id = 10;
    repeated MAEEIBPEOFN LDCJONHGDAN = 13;
    bool is_valid = 14;
}

message KIHMNMMJIDL {
    uint32 LJGNHKCBAIO = 6;
}

message KJEOBMBMNIN {
    bool BELPGDAGFIH = 2;
    ItemCostData KINNMAGDDJJ = 3;
    ItemCostData cost_data = 5;
    uint32 buff_id = 6;
    uint32 JBGENFIKGGF = 7;
    bool GCIHGKCJOGB = 8;
}

message KLEHEHAMKLC {
    OHJJMCMJEHL KBEBGLAAEGM = 9;
}

message KNEJEHOOFGI {
    AvatarType avatar_type = 1;
    uint32 avatar_id = 12;
}

message KNMNEJCMHGE {
    float GMPKBKLGDMA = 12;
    int32 MNLINFEODPJ = 14;
}

message KNOLJDOPBDG {
    uint64 GAHFPGCPAJA = 2;
    repeated AKMCODLAEKI GFKAFIFMHNF = 9;
    MMFOGJPOHGJ owner_type = 15;
}

message KNPMLBOBKPI {
    uint32 LNAHJENGELA = 3;
}

message KPDALNGIDAG {
    uint32 PBGBMGIIHHA = 4;
}

message KPIHDPGDMKB {
    uint32 OCAGIAKNGPG = 3;
    uint32 NBBABABPEBE = 4;
    uint32 DGJPGMGPCCE = 8;
}

message LBBCNOOOCNE {
    DNLKMHLAPHC LANFFLCLGAH = 6;
}

enum LBPLJCHEJOK {
    LBPLJCHEJOK_NDDPEJHPLHG = 0;
    LBPLJCHEJOK_BMBGOIDDIJD = 1;
    LBPLJCHEJOK_KJDPEEAPJOO = 2;
}

message LDFJBLDICPJ {
}

message LECIGPPCMAB {
    uint32 interacted_prop_entity_id = 7;
    repeated uint32 AOLIEDBCNBN = 13;
}

message LEHBIBDGEHG {
    oneof JGOLOIOMGFO {
        HEOBLDJAOPE MFAEGBJBJBE = 12;
        FOINGKNPBLJ MNKGPHFJDFM = 13;
        KNPMLBOBKPI DCFILENMPCC = 4;
        OEPAMDEPFLJ BDFKGFLFCFO = 1;
    }
}

message LFBPMGGFCEO {
    repeated uint32 IPACFECEBFF = 9;
}

message LFLMJKLKBIL {
    uint32 PEKGIDFPBNJ = 6;
}

message LHKAOPAPJEK {
    FHEGNOPNICH JNKLNLKHGBB = 2;
    LineupInfo lineup = 7;
    SceneInfo scene = 14;
}

message LHKNCMFEPFK {
    KOFMGCNIMIN miracle = 4;
    uint32 FDEECOEDJEB = 8;
    uint32 EGJIEAAEEBD = 9;
}

message LKCDLJCKCJI {
    uint32 KMNILIKJFHD = 9;
    uint32 item_type = 12;
}

message LLBKNIJDALM {
    uint32 GCAHKLNGFCK = 6;
}

message LNKEEAKFEHM {
}

message LNOPJJFKMDL {
    repeated uint32 PDAMBONNOND = 3;
}

message LNPGBGDPIIK {
    ItemCostData cost_data = 1;
    ItemCostData IOJFGBDPPHI = 2;
    bool IFIGFODOPBB = 12;
    OCBPJLLLJGO DDLADFJMEEC = 13;
}

enum LPCEBDCJBOI {
    LPCEBDCJBOI_IHENGPDPCHA = 0;
    LPCEBDCJBOI_HMKEPGCEMON = 1;
    LPCEBDCJBOI_GCMFFANJMHF = 2;
}

message LPDPAJGFBMM {
    uint32 retcode = 14;
}

message LPLHNOPDKHI {
    uint64 GAHFPGCPAJA = 6;
    repeated AKMCODLAEKI GFKAFIFMHNF = 12;
    MMFOGJPOHGJ owner_type = 13;
}

message LPODFEEGDOB {
    uint32 DMGJDGJMCJL = 5;
    uint32 CLNDMEODHJE = 15;
}

message MAEEIBPEOFN {
    oneof PGNIENCDODA {
        PIACCCGNOOF BACBKGJJOGA = 2;
        BPOKOPCGMAJ CNKCDGOJGJH = 14;
    }
}

message MAOKMPOELCO {
    NHHMEPILLHL source = 9;
    uint32 queue_position = 10;
    PKHKEEKIODC detail = 11;
}

message MCFEKKMFEHA {
}

message MCHIJNKKOAM {
    HHAGOFKBFAP DJMHHMMABJL = 7;
    uint32 retcode = 15;
}

enum MGJDNGHDIKG {
    MGJDNGHDIKG_ANBKDJKHCBI = 0;
    MGJDNGHDIKG_DDJLLLNADIL = 1;
    MGJDNGHDIKG_NLCLCPPDLGM = 2;
    MGJDNGHDIKG_FDACPOINIEO = 3;
    MGJDNGHDIKG_BJDFGOACHGF = 4;
    MGJDNGHDIKG_ECLBIMKAKJC = 5;
}

message MHLLNFJHMEK {
    uint32 AIAFEKGBFIF = 9;
}

message MIPGDFDCKLE {
    oneof MMCGBGDJIPN {
        JFGGDMPDKNH NLJPONKBMFI = 9;
        COKKOEBBEGM BBNEGKCNMBA = 5;
        FHAAGBGAHLO PKPIEFOBHKH = 4;
        LNOPJJFKMDL FKMADCAFJMC = 7;
        MKFCLDMEMGN PHLEDABHDML = 1;
        DOEJLDNIDED DDLADFJMEEC = 3;
        ALJJNBKGEOC OJEANDPABHC = 13;
        LFBPMGGFCEO CLLEJEPNBDH = 8;
        EJBEEKFJAHM DNHKNALBAMG = 10;
        LLBKNIJDALM LBBCJHOPEPH = 2;
        NGOKMAABDJJ KDFGAKDCMIK = 6;
    }
}

message MJEPCLPMKKI {
    uint32 HDHNKFPMPAO = 12;
}

message MKFCLDMEMGN {
    uint32 FALFBMDDFPA = 8;
}

message MKNALGLEBNA {
    LEJFIEPMMGG DKEENIMPLKD = 15;
}

message MNGNLOCLNOF {
}

message NBFAGOOJIOB {
    uint32 OMHHOADFMLI = 1;
}

message NEFBECKCJIH {
    uint32 GCAHKLNGFCK = 2;
    ItemCostData cost_data = 12;
}

message NEMJDLLBBGN {
    MMBBHFNJILI BLEBJLDOLII = 8;
    repeated uint32 LIIJNIKIGJD = 14;
}

message NGOKMAABDJJ {
    repeated uint32 GMMAFIONFNF = 14;
}

message NHGJEIHKKHB {
    repeated BPHIKPCNBHM buff_list = 9;
    repeated NMDKHGGGMBC JHEHAIBMNNF = 10;
    repeated CIGDBCKOFBN MAJGMMCOCIG = 14;
    repeated NMHMGHEHHCM PMIFFBHOOOO = 15;
}

enum NHHMEPILLHL {
    NHHMEPILLHL_NLCDGIPGFDJ = 0;
    NHHMEPILLHL_MIDKKNAGOFA = 1;
    NHHMEPILLHL_FJMCIHHIGIA = 2;
    NHHMEPILLHL_ANBKDJKHCBI = 3;
    NHHMEPILLHL_NCLBFAALLFJ = 4;
    NHHMEPILLHL_EPCDLHFFBLI = 5;
    NHHMEPILLHL_MOFNIOJHBBL = 6;
    NHHMEPILLHL_CLNGFDPINDB = 7;
    NHHMEPILLHL_BGDGIIOKHGF = 8;
    NHHMEPILLHL_MCGGEAAHBPD = 9;
    NHHMEPILLHL_FMPGGENBHID = 10;
    NHHMEPILLHL_EMALBALANLH = 11;
    NHHMEPILLHL_LFCDGLIEHAI = 12;
    NHHMEPILLHL_DOFDGKKLJDD = 13;
    NHHMEPILLHL_JOLNBCHMDNN = 14;
    NHHMEPILLHL_BGPLPIPENJN = 15;
    NHHMEPILLHL_NPAFMEBNFOB = 16;
    NHHMEPILLHL_IKCHCHPGFFJ = 17;
}

enum NKLAEHJPIMN {
    NKLAEHJPIMN_FGOFDMDBMAL = 0;
    NKLAEHJPIMN_GNGGGHLBNEH = 1;
    NKLAEHJPIMN_GIHACHNKFIE = 2;
}

message NKOBPBBONDJ {
    bool BJDEBHMKJBC = 2;
    BDJLHJDPEEK KDFKDNLNDHN = 11;
}

message NMDKHGGGMBC {
    repeated uint32 HMIOHPIMLCE = 6;
    uint32 exp = 9;
    uint32 level = 11;
    uint32 max_level = 12;
    uint32 AFEMBLFCCCH = 13;
}

message NMHMGHEHHCM {
    uint32 PNHGLNPDFEA = 3;
    bool ALAJJMKOMML = 10;
}

message NMMLEBEEJLB {
    uint32 NNNJECNENGA = 10;
}

message NPAJHGDEIDJ {
    uint32 ECPDJMMOGCI = 12;
    LPCEBDCJBOI status = 13;
}

message NPCIGEBNOFG {
    uint32 num = 8;
    uint32 display_type = 10;
}

message OBNEOHHDAIP {
    JDFNPICGCGI IFPBFMOAJOP = 12;
}

message OECNJOAPCKO {
    uint32 FAGJACOFHGF = 11;
    uint32 KMIKBANMAFK = 12;
}

message OEPAMDEPFLJ {
    uint32 dialogue_id = 12;
}

message OEPIHJOHLKM {
    LHKAOPAPJEK IDCMACCPCBH = 6;
}

message OGPOHFPHEOB {
    uint32 PMILABMFMMM = 9;
}

message OJPMMKIJIFH {
    map<uint32, ItemCostData> BHPELIMODBC = 4;
    ItemCostData PKAMBCBEKME = 6;
    int32 LIAGGDDILGO = 9;
    uint32 JFIGNBBLCIM = 14;
}

message OKBLBLPOENO {
    KOFMGCNIMIN miracle = 7;
}

message OKFPPPBNJNH {
    OFMCKLEMOMP FNEOOMHHGGB = 8;
}

message OMACAKFNAOA {
    repeated KVP IHFEBNBHDFM = 3;
}

message OMLMOJIGLEE {
    ItemCostData cost_data = 1;
    uint32 KAHMGPGPOII = 4;
    bool BELPGDAGFIH = 5;
    bool GCIHGKCJOGB = 11;
    ItemCostData KINNMAGDDJJ = 15;
}

message OMNMBANDCBA {
    int32 LIAGGDDILGO = 2;
    map<uint32, bool> PILABDDEKII = 3;
    ItemCostData cost_data = 10;
    uint32 JFIGNBBLCIM = 15;
}

message PIACCCGNOOF {
    uint32 battle_event_id = 1;
}

message PIBOMOCKACA {
    uint32 KDIDDHIDNCG = 4;
}

message PIJDFMAJMFD {
    uint32 JMNMFMHPCKD = 1;
}

message PJFPIPIPOJN {
    HHAGOFKBFAP DJMHHMMABJL = 4;
}

message PJMEDBOACGL {
    uint32 BAOFIGFFMLN = 6;
}

message PKHKEEKIODC {
    oneof KKNBOACNCON {
        NPCIGEBNOFG DDCLCNPONOH = 5;
        NPCIGEBNOFG CONDGFPOFKD = 14;
        KJAMNOGFAMJ IFOOEPKGGAG = 1986;
        KJAMNOGFAMJ CMPNCFCJCNE = 703;
        IOMEMIEAPJO GPJJMPCMAAA = 250;
        IKHMHNOIGAB LAEFENCCBBC = 1047;
        LHKNCMFEPFK KDJBDMLDMHG = 198;
        OKBLBLPOENO CBPINAOHEBD = 329;
        JLHJICBCHMO OMFLCEBLLMI = 1684;
        CKEOMFNPKPO FLGGFGCIGNJ = 1145;
        KNEJEHOOFGI ACIFEIPPILA = 1974;
        JJEMDNEIMOJ MDGNDLLEFJE = 986;
        MKNALGLEBNA JOCLINGHBHE = 1496;
        PKOHBLEGMAO HPMJHOGCLGG = 101;
        FBGIINJFCCD KMAMKBKNCPM = 1592;
        CFJNAPDIMKM JEJCFJEDOLA = 1007;
        CJAFLDKHDAF JEBLGELGBHM = 99;
        HCNEFGJCCMB GHMKDCKJILO = 137;
        LFLMJKLKBIL CEICJPEMGHD = 221;
        GNGIHJIJGMD EBFCOMCMGLC = 1284;
        LBBCNOOOCNE JDCMEPIOMPN = 663;
        AOFKCKOIFCM KCGHLOHDMBM = 1991;
        MMBBHFNJILI JMJPONNLJEJ = 449;
        MMBBHFNJILI MCPKPJHBEAK = 895;
        MMBBHFNJILI GDABGNBKFPA = 2015;
        DNLKMHLAPHC APGPOGAKPAC = 486;
        NEMJDLLBBGN JOLNBCHMDNN = 685;
        NBFAGOOJIOB KOHOCJAMJAN = 1026;
        NBFAGOOJIOB AEGMECDFNBE = 897;
        NKOBPBBONDJ CIOLGFNLEBB = 1082;
        IPKOBBJPKML BIJODAGIKNF = 246;
        GNLBCCHFILK MELCFMHKECA = 518;
        EDDEOKAIJAB EMKIGHCFKCN = 141;
        PKOOFPOCNKB KAHKMDHFLOH = 950;
        HIMJNABCJMM ALNEINEOJOJ = 903;
        PPHLEBFJIGM EGPLOEAAFGL = 1429;
        JGCMGAMHDHM JKLJBCBFNPL = 985;
        OECNJOAPCKO MIDFLEHKPBF = 945;
        OMACAKFNAOA NBEKLDCBJCH = 2011;
        GBKILNHHGLB DFJCKBLAOBN = 1617;
        OEPIHJOHLKM FLPDILMMCFK = 364;
    }
}

message PKOHBLEGMAO {
    LEJFIEPMMGG DKEENIMPLKD = 8;
}

message PKOOFPOCNKB {
    uint32 IFDIHFKKCLE = 4;
    uint32 DBPAHBJPFLJ = 14;
}

message PPHLEBFJIGM {
    uint32 OIIJCLJHPPE = 2;
    uint32 AIIFGDGONIF = 3;
    uint32 style_level = 4;
    uint32 style_exp = 10;
}

message RogueAdventureRoomGameplayWolfGunTarget {
    oneof target_impl {
        MNGNLOCLNOF target_none = 15;
        FEIJPEJBDDH target_coin = 12;
        JMPNGBAILBG target_miracle = 6;
        FENFEHCCOCA target_ruanmei = 5;
    }
}

message RogueDoGambleScRsp {
    uint32 retcode = 6;
    uint32 HNCCDEPDNEG = 10;
    uint32 DOOECGPIMBD = 12;
    HKOEAOPNEAC KOBBMDFPNKA = 14;
}

message RogueGetGambleInfoScRsp {
    HKOEAOPNEAC KOBBMDFPNKA = 2;
    uint32 retcode = 6;
}

message RogueShopBeginBattleScRsp {
    SceneBattleInfo AEPNEDJPAGK = 2;
    uint32 retcode = 13;
}

message RogueWorkbenchGetInfoScRsp {
    uint32 retcode = 7;
    map<uint32, BCOEGNBGJFC> NJAPFMHHPPA = 9;
}

message RogueWorkbenchHandleFuncScRsp {
    BCOEGNBGJFC JNPALDKNHKM = 8;
    uint32 func_id = 10;
    uint32 retcode = 15;
}

message SelectRogueCommonDialogueOptionScRsp {
    uint32 AIAFEKGBFIF = 5;
    uint32 retcode = 10;
    uint32 HAFOKMHCGFM = 12;
    repeated uint32 CGINGCNCPCO = 14;
    HFEOGNAMHCG ONOLNGOHEMF = 15;
}

message SetRogueCollectionScRsp {
    uint32 retcode = 2;
    repeated JMJEIBGACMD CEPDOBEIEFG = 6;
    repeated NPAJHGDEIDJ DPIKOCFILGP = 7;
}

message SetRogueExhibitionScRsp {
    uint32 retcode = 7;
    repeated DGKLPPLJBNB PAKECMNPEJJ = 9;
    repeated DIKBPKAKENO JFHKJOGEOND = 13;
}

message SyncRogueCommonActionResultScNotify {
    repeated MAOKMPOELCO CLGGKLNPLCK = 4;
    DICEONDKEFF display_type = 9;
    uint32 DLOJFEEHLIJ = 11;
    repeated ACMKPNMKOKH KCLBFINDGNA = 13;
}

message SyncRogueCommonDialogueDataScNotify {
    repeated HFEOGNAMHCG dialogue_list = 12;
}

message SyncRogueCommonDialogueOptionFinishScNotify {
    uint32 HAFOKMHCGFM = 2;
    KDODFHMDAJI FJPGAOHGEBH = 9;
    uint32 AIAFEKGBFIF = 14;
}

message SyncRogueCommonPendingActionScNotify {
    uint32 DLOJFEEHLIJ = 10;
    INHBMHCJJCN action = 15;
}

message SyncRogueHandbookDataUpdateScNotify {
    repeated BPHIKPCNBHM IPNAAGCMNLB = 7;
    repeated NMHMGHEHHCM BOJGAEJNCFP = 9;
    repeated LGFOKKPICEH JEAGPFDBJDH = 10;
    repeated CIGDBCKOFBN BFDFABHMCNE = 11;
    repeated ONMFMINNBEB LMDKIJFDLEO = 14;
}

message TakeEventHandbookRewardScRsp {
    ItemList reward = 6;
    uint32 retcode = 12;
    repeated uint32 DBGOOKPHLFD = 15;
}

message TakeRogueMiracleHandbookRewardScRsp {
    repeated uint32 CNDLCGEFLCJ = 7;
    ItemList reward = 9;
    uint32 retcode = 12;
}
