syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdRogueArcadeType {
    CmdRogueArcadeType_NLCDGIPGFDJ = 0;
    CmdRogueArcadeType_RogueArcadeLeaveScRsp = 7659;
    CmdRogueArcadeType_RogueArcadeRestartScRsp = 7664;
    CmdRogueArcadeType_RogueArcadeModuleInitCsReq = 7669;
    CmdRogueArcadeType_RogueArcadeGetInfoScRsp = 7690;
    CmdRogueArcadeType_PJDFLECDOAA = 7679;
    CmdRogueArcadeType_ENDFCJDJHEJ = 7656;
    CmdRogueArcadeType_GFECMCBCMDM = 7683;
    CmdRogueArcadeType_RogueArcadeStartScRsp = 7685;
}

message GCPGBPNGOFF {
    FHEGNOPNICH JNKLNLKHGBB = 8;
    LineupInfo lineup = 11;
    SceneInfo scene = 13;
}

message RogueArcadeGetInfoScRsp {
    uint32 retcode = 3;
    uint32 room_id = 15;
}

message RogueArcadeLeaveScRsp {
    GCPGBPNGOFF IDCMACCPCBH = 11;
    uint32 retcode = 15;
}

message RogueArcadeRestartScRsp {
    uint32 retcode = 8;
    GCPGBPNGOFF IDCMACCPCBH = 13;
}

message RogueArcadeStartScRsp {
    GCPGBPNGOFF IDCMACCPCBH = 4;
    uint32 room_id = 5;
    uint32 retcode = 7;
}
