syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum BDFGBPHEPDI {
    BDFGBPHEPDI_PDKLDMNAJBO = 0;
    BDFGBPHEPDI_KCCEHPABIKB = 1;
    BDFGBPHEPDI_IEGNMOODDAK = 2;
}

message BEBNHPCBMPF {
    JBOAAPIDOIC NOAJIGHLIIC = 3;
    uint32 avatar_id = 4;
}

enum CmdRelicBoxType {
    CmdRelicBoxType_NLCDGIPGFDJ = 0;
    CmdRelicBoxType_ANLKBPKEAGG = 8952;
    CmdRelicBoxType_ConfirmRelicBoxCsReq = 8951;
    CmdRelicBoxType_GetRelicBoxDataCsReq = 8968;
    CmdRelicBoxType_RelicBoxRegularScNotify = 8964;
    CmdRelicBoxType_GetRelicBoxDataScRsp = 8958;
    CmdRelicBoxType_OpenRelicBoxScRsp = 8965;
    CmdRelicBoxType_SetRelicBoxTargetScRsp = 8967;
    CmdRelicBoxType_SetRelicBoxCustomScRsp = 8962;
    CmdRelicBoxType_ReportRelicBoxActionScRsp = 8957;
    CmdRelicBoxType_NINAJABOKCG = 8953;
    CmdRelicBoxType_ConfirmRelicBoxScRsp = 8959;
    CmdRelicBoxType_OpenRelicBoxCsReq = 8961;
    CmdRelicBoxType_FGCLOPHMIAF = 8960;
}

message ConfirmRelicBoxCsReq {
    bool BBNIFADMHHO = 1;
}

message ConfirmRelicBoxScRsp {
    bool BBNIFADMHHO = 1;
    repeated uint32 OAJFAFIDKPI = 4;
    uint32 retcode = 8;
    uint32 HMBNJLNBLIF = 11;
}

message DPJCBHKGFOK {
    repeated Relic relics = 7;
}

message GetRelicBoxDataCsReq {
}

message GetRelicBoxDataScRsp {
    uint32 retcode = 1;
    DPJCBHKGFOK AHNPPGMFOKN = 2;
    BDFGBPHEPDI state = 3;
    PNGBDDIBCDD NJFEFOFPKPF = 7;
    HGABLJFOKDG target = 10;
    repeated uint32 OAJFAFIDKPI = 13;
    repeated BEBNHPCBMPF EBDIOJPDJIH = 14;
    uint32 MFLMHFLMCPO = 15;
}

message HGABLJFOKDG {
    uint32 avatar_id = 6;
    JFIIIHFBLPA HDHKAHJBFKD = 12;
    JBOAAPIDOIC NOAJIGHLIIC = 14;
}

message JBOAAPIDOIC {
    uint32 IPILHKHCLJH = 11;
    uint32 FLFOCHJFLOE = 13;
}

enum JFIIIHFBLPA {
    JFIIIHFBLPA_NEODNIFGDJC = 0;
    JFIIIHFBLPA_BPKKHFFJGGI = 1;
}

message OpenRelicBoxCsReq {
    HGABLJFOKDG target = 7;
}

message OpenRelicBoxScRsp {
    PNGBDDIBCDD LCMADDIMION = 4;
    uint32 retcode = 5;
    uint32 GNLAAIDFOJF = 12;
}

message PNGBDDIBCDD {
    uint32 type = 1;
    repeated RelicAffix sub_affix_list = 2;
    uint32 exp = 4;
    uint32 level = 11;
    uint32 tid = 12;
    uint32 main_affix_id = 15;
}

message RelicBoxRegularScNotify {
    DPJCBHKGFOK AHNPPGMFOKN = 14;
}

message ReportRelicBoxActionScRsp {
    uint32 retcode = 7;
    BDFGBPHEPDI state = 11;
}

message SetRelicBoxCustomScRsp {
    uint32 retcode = 3;
}

message SetRelicBoxTargetScRsp {
    uint32 retcode = 4;
    HGABLJFOKDG target = 9;
}
