syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message ABOFJEIMLLJ {
    uint32 buff_id = 12;
    uint32 level = 13;
}

message AEFFOCFJNBF {
    ItemCostData cost_data = 2;
    uint32 buff_id = 11;
}

message AGEHGBKOBEF {
    HNKAOFDGLIE CFDIKLBINHK = 448;
    EDOIEMCFFCA LFLCDNGALME = 960;
}

message AJAOJOEAGML {
    KCMFAIBMOHB MFEODNJNGDP = 10;
    uint32 retcode = 12;
}

message ALBLEFHHJIC {
    AvatarType avatar_type = 1;
    uint32 slot = 2;
    uint32 level = 6;
    uint32 id = 9;
}

message BHLEHMNFHPJ {
    repeated uint32 NOEPBNMJFGL = 7;
    uint32 retcode = 10;
    repeated uint32 unfinished_story_line_id_list = 15;
}

message CAJEBOPPMCJ {
    RogueStatus NHDLEFAAPOB = 1;
    uint32 KNDHMNBIIDF = 3;
    bool ALAJJMKOMML = 8;
    uint32 area_id = 12;
    uint32 map_id = 13;
    RogueAreaStatus area_status = 14;
}

message CDDIJCBEAHJ {
    repeated uint32 CEMOJMBHLDD = 3;
}

message CDOKCLHEDBO {
    uint32 retcode = 15;
}

message CFMHEMGEANC {
    repeated ABOFJEIMLLJ CHCMEKAFKAF = 15;
}

message CGMBIHBHLFK {
}

message CGNNMPIKBBB {
    uint32 LJNGPCKPJLF = 6;
    int64 begin_time = 8;
    int64 end_time = 11;
}

message CIFCAIEDOLK {
    uint32 unlock_aeon_enhance_num = 2;
    uint32 JPPAGGPJOMO = 6;
}

message CINMCBDCBMJ {
    uint32 maze_buff_id = 14;
}

enum CmdRogueType {
    CmdRogueType_NLCDGIPGFDJ = 0;
    CmdRogueType_GetRogueTalentInfoScRsp = 1802;
    CmdRogueType_OpenRogueChestScRsp = 1819;
    CmdRogueType_SyncRogueGetItemScNotify = 1817;
    CmdRogueType_EnterRogueCsReq = 1888;
    CmdRogueType_EnableRogueTalentScRsp = 1808;
    CmdRogueType_SimulatedRogueReviveRogueAvatarCsReq = 1848;
    CmdRogueType_SimulatedRoguePickRogueAvatarCsReq = 1804;
    CmdRogueType_GetRogueAeonInfoCsReq = 1887;
    CmdRogueType_IFNOKEFGLAH = 1900;
    CmdRogueType_GetRogueInfoCsReq = 1825;
    CmdRogueType_GetRogueTalentInfoCsReq = 1831;
    CmdRogueType_ELAMNACKPEG = 1893;
    CmdRogueType_ECHBHMHDIPJ = 1849;
    CmdRogueType_IIEJEHFKECM = 1830;
    CmdRogueType_QuitRogueScRsp = 1829;
    CmdRogueType_SyncRogueAeonScNotify = 1883;
    CmdRogueType_EnterRogueMapRoomScRsp = 1875;
    CmdRogueType_SyncRogueAreaUnlockScNotify = 1895;
    CmdRogueType_GetRogueAeonInfoScRsp = 1824;
    CmdRogueType_GetRogueInfoScRsp = 1878;
    CmdRogueType_GetRogueBuffEnhanceInfoScRsp = 1842;
    CmdRogueType_ExchangeRogueRewardKeyCsReq = 1828;
    CmdRogueType_OpenRogueChestCsReq = 1846;
    CmdRogueType_ExchangeRogueRewardKeyScRsp = 1898;
    CmdRogueType_FPPNFKKOJNF = 1843;
    CmdRogueType_SyncRogueStatusScNotify = 1899;
    CmdRogueType_HPJBLIFMOJB = 1844;
    CmdRogueType_SimulatedRogueEnhanceRogueBuffCsReq = 1872;
    CmdRogueType_StartRogueScRsp = 1858;
    CmdRogueType_FinishAeonDialogueGroupScRsp = 1877;
    CmdRogueType_EnterRogueScRsp = 1881;
    CmdRogueType_SyncRogueReviveInfoScNotify = 1810;
    CmdRogueType_SyncRogueVirtualItemInfoScNotify = 1822;
    CmdRogueType_LeaveRogueCsReq = 1886;
    CmdRogueType_EnterRogueMapRoomCsReq = 1835;
    CmdRogueType_RogueReviveRogueAvatarScRsp = 1845;
    CmdRogueType_SyncRogueMapRoomScNotify = 1815;
    CmdRogueType_LeaveRogueScRsp = 1847;
    CmdRogueType_SyncRogueFinishScNotify = 1839;
    CmdRogueType_FinishAeonDialogueGroupCsReq = 1885;
    CmdRogueType_NIGMIDIJOLB = 1890;
    CmdRogueType_SyncRogueSeasonFinishScNotify = 1896;
    CmdRogueType_RogueEnhanceRogueBuffScRsp = 1880;
    CmdRogueType_SyncRogueExploreWinScNotify = 1834;
    CmdRogueType_LKCBMMHDNCF = 1860;
    CmdRogueType_RoguePickRogueAvatarScRsp = 1811;
}

message DNDMLICBKEF {
    uint32 ANHDBMOPGDC = 7;
    uint32 HPKMGKPPELC = 11;
    repeated PAIJCBOKIFO LLNICHDDIAN = 12;
    uint32 area_id = 13;
    uint32 map_id = 15;
}

message EDOIEMCFFCA {
    MBCBDJNKFEB NIKDPODBIEF = 5;
    CGNNMPIKBBB HHFAAFOBKME = 6;
    GOIEJOCFKEE ACLKMFCDMED = 8;
    GFGHGCIMKGA AEFMMOHKCHJ = 14;
}

message EFDAIBDBFEA {
    uint32 DGGCFDKJDPO = 2;
    uint32 LJCEOGPOGBE = 4;
    uint32 NPHAJEKCBKF = 10;
    uint32 total_count = 11;
}

message EKFCDGNOAIN {
    repeated uint32 NOEPBNMJFGL = 4;
    repeated uint32 unfinished_story_line_id_list = 6;
    uint32 prop_entity_id = 7;
}

message ENOBKLGCHOD {
    repeated uint32 NOEPBNMJFGL = 5;
    repeated uint32 unfinished_story_line_id_list = 8;
    KCMFAIBMOHB MFEODNJNGDP = 9;
}

message EnableRogueTalentScRsp {
    uint32 retcode = 4;
    FDBDLBAPDBE JCOBJAMPOAL = 12;
}

message EnterRogueCsReq {
    uint32 area_id = 5;
}

message EnterRogueMapRoomCsReq {
    uint32 room_id = 2;
    uint32 MAJKFIMPOOF = 3;
}

message EnterRogueMapRoomScRsp {
    FHEGNOPNICH JNKLNLKHGBB = 9;
    LineupInfo lineup = 10;
    uint32 retcode = 11;
    SceneInfo scene = 12;
    uint32 ANHDBMOPGDC = 15;
}

message EnterRogueScRsp {
    LineupInfo lineup = 2;
    SceneInfo scene = 3;
    FHEGNOPNICH JNKLNLKHGBB = 7;
    uint32 retcode = 8;
    AGEHGBKOBEF rogue_game_info = 12;
}

message ExchangeRogueRewardKeyCsReq {
    uint32 count = 2;
}

message ExchangeRogueRewardKeyScRsp {
    uint32 count = 3;
    uint32 retcode = 8;
}

message FLCPJJMHAGO {
    uint32 max_level = 2;
    uint32 AFEMBLFCCCH = 4;
    uint32 level = 8;
    uint32 exp = 9;
}

message FinishAeonDialogueGroupCsReq {
    uint32 AFEMBLFCCCH = 5;
}

message FinishAeonDialogueGroupScRsp {
    uint32 retcode = 1;
    ItemList reward = 3;
    FLCPJJMHAGO AEFMMOHKCHJ = 15;
}

message GAOBHBLFPEC {
    uint32 OFHBBKOKANF = 5;
    uint32 GBIEAMKLONK = 6;
    uint32 DBHOIDLKMAB = 8;
    uint32 LKHAIEIDAJL = 10;
}

message GFGHGCIMKGA {
    repeated uint32 OPAEGCBNACJ = 10;
    uint32 unlock_aeon_enhance_num = 13;
}

message GKHGFCBMLBL {
    ItemList LHPNJLBPACA = 7;
    uint32 GEBGGMAGDJB = 9;
    bool is_win = 10;
    uint32 GHCBFCIGIBF = 11;
    uint32 score_id = 12;
    uint32 MHPHDCFKMLF = 13;
    uint32 GMIIMAHLIJF = 14;
    KCOEJJKGNIG record_info = 15;
    uint32 area_id = 29;
    uint32 HEOMALBNJLL = 1073;
}

message GOIEJOCFKEE {
    repeated CAJEBOPPMCJ OJGOAOPLMLB = 13;
}

message GetRogueAeonInfoCsReq {
}

message GetRogueAeonInfoScRsp {
    uint32 retcode = 10;
    repeated FLCPJJMHAGO JHEHAIBMNNF = 13;
}

message GetRogueBuffEnhanceInfoScRsp {
    uint32 retcode = 1;
    AACJBNFGABA ILMAMLBLIDL = 10;
}

message GetRogueInfoCsReq {
}

message GetRogueInfoScRsp {
    uint32 retcode = 2;
    AGEHGBKOBEF rogue_game_info = 6;
}

message GetRogueTalentInfoCsReq {
}

message GetRogueTalentInfoScRsp {
    uint32 retcode = 12;
    FDBDLBAPDBE JCOBJAMPOAL = 15;
}

message HFGBCEKGFHK {
    repeated AEFFOCFJNBF EMAGFIBLNCJ = 15;
}

message HIGAMEJNCJJ {
    uint32 AFEMBLFCCCH = 6;
    uint32 level = 12;
}

message HIKOBOMBMPB {
    OEDNNHAOHAB DNPCCFFFBHN = 12;
}

message HNKAOFDGLIE {
    DNDMLICBKEF COOOMDKGODF = 2;
    CDDIJCBEAHJ IELPCHGLFCA = 3;
    AGEOGDOGDMM DHEKLJDBNNP = 4;
    RogueStatus status = 5;
    HIKOBOMBMPB DNPCCFFFBHN = 6;
    INHBMHCJJCN FMIGOKIDKJL = 7;
    ENOBKLGCHOD EIOHFJMFOKF = 9;
    CIFCAIEDOLK AEFMMOHKCHJ = 12;
    CFMHEMGEANC HABJHGPFGEB = 13;
    bool ILOFGCAFHAH = 15;
}

message JIBBEEAIDIC {
    repeated uint32 OPAEGCBNACJ = 1;
    uint32 JPPAGGPJOMO = 5;
    uint32 unlock_aeon_enhance_num = 9;
}

message KCMFAIBMOHB {
    ItemCostData LNIEFKBMIPD = 14;
}

message KCOEJJKGNIG {
    repeated uint32 MAJGMMCOCIG = 1;
    repeated ALBLEFHHJIC avatar_list = 13;
    repeated ABOFJEIMLLJ buff_list = 14;
}

message KFJFHKLJKAK {
    uint32 retcode = 6;
    ItemList reward = 11;
    uint32 AFEMBLFCCCH = 12;
    uint32 level = 14;
}

message LeaveRogueCsReq {
}

message LeaveRogueScRsp {
    SceneInfo scene = 1;
    LineupInfo lineup = 7;
    FHEGNOPNICH JNKLNLKHGBB = 10;
    uint32 retcode = 11;
}

message MBCBDJNKFEB {
    uint32 GEBGGMAGDJB = 1;
    uint32 PDGBEJHNHHE = 10;
    uint32 CICAENDEDFE = 12;
}

message NAHANHPHGGF {
    ABOFJEIMLLJ CNEFDJCKAPL = 3;
    bool KGKEJAKKLDP = 5;
    uint32 retcode = 13;
}

message OEDNNHAOHAB {
    repeated EFDAIBDBFEA MAJGMMCOCIG = 5;
}

message OpenRogueChestCsReq {
    bool FDEKKOKBDIC = 1;
    uint32 interacted_prop_entity_id = 13;
}

message OpenRogueChestScRsp {
    ItemList drop_data = 2;
    uint32 retcode = 5;
    LMDPKOELKFL ABEMLCJBIEF = 11;
    ItemList reward = 13;
}

message PAIJCBOKIFO {
    uint32 room_id = 5;
    uint32 MAJKFIMPOOF = 10;
    RogueRoomStatus CAGDNHCOCKM = 13;
    RogueRoomStatus FCHHPCIDNGM = 14;
    uint32 PGACMFLCDID = 15;
}

message PDNOJMFCDDG {
    uint32 interacted_prop_entity_id = 1;
    repeated uint32 NOEPBNMJFGL = 15;
}

message QuitRogueScRsp {
    AGEHGBKOBEF rogue_game_info = 8;
    uint32 retcode = 11;
}

enum RogueAreaStatus {
    HNPHKCCICPM_GAJGBBFELEL = 0;
    HNPHKCCICPM_BFADFAELKLJ = 1;
    HNPHKCCICPM_MKHFMMCKAEI = 2;
    HNPHKCCICPM_PDKLDMNAJBO = 3;
}

enum RogueRoomStatus {
    KFNIFOJPFCB_NLCDGIPGFDJ = 0;
    KFNIFOJPFCB_GAJGBBFELEL = 1;
    KFNIFOJPFCB_BFADFAELKLJ = 2;
    KFNIFOJPFCB_JDAGFHEPMHF = 3;
    KFNIFOJPFCB_CIHFGJDCHIA = 4;
}

message StartRogueScRsp {
    AGEHGBKOBEF rogue_game_info = 3;
    LineupInfo lineup = 7;
    FHEGNOPNICH JNKLNLKHGBB = 8;
    uint32 retcode = 9;
    SceneInfo scene = 12;
}

message SyncRogueAeonScNotify {
    JIBBEEAIDIC BGDGIIOKHGF = 4;
}

message SyncRogueAreaUnlockScNotify {
    uint32 area_id = 4;
}

message SyncRogueExploreWinScNotify {
    bool ILOFGCAFHAH = 8;
}

message SyncRogueFinishScNotify {
    GKHGFCBMLBL NLEOMLNOKCC = 5;
}

message SyncRogueGetItemScNotify {
    ItemList get_item_list = 1;
    ItemList IIDEAGLAMCC = 8;
}

message SyncRogueMapRoomScNotify {
    uint32 map_id = 6;
    PAIJCBOKIFO HNEANMNJHDB = 11;
}

message SyncRogueReviveInfoScNotify {
    KCMFAIBMOHB MFEODNJNGDP = 11;
}

message SyncRogueSeasonFinishScNotify {
    bool FALJMPELHIO = 2;
    GKHGFCBMLBL NLEOMLNOKCC = 3;
    LineupInfo lineup = 14;
    SceneInfo scene = 15;
}

message SyncRogueStatusScNotify {
    bool AOBCKABCHGO = 7;
    RogueStatus status = 11;
}

message SyncRogueVirtualItemInfoScNotify {
    GAOBHBLFPEC NIKDPODBIEF = 11;
}
