syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BMMHJIFCGNO {
    uint32 MIPKOFFGPFA = 8;
    uint32 KAJCFPKEGBP = 14;
}

message BPFDFOJOEMI {
    uint32 percent = 2;
    uint32 LBDLAACOCCN = 6;
}

message BigDataAvatarRelicRecommend {
    repeated BPFDFOJOEMI sphere_main_property_list = 1;
    repeated BPFDFOJOEMI rope_main_property_list = 4;
    repeated BPFDFOJOEMI foot_main_property_list = 5;
    repeated BPFDFOJOEMI body_main_property_list = 6;
    uint32 avatar_id = 7;
    repeated JBGPLPCCDBJ inner_set_list = 10;
    repeated JBGPLPCCDBJ outer_set_list = 12;
}

message BigDataRecommendAvatarRelic {
    repeated BigDataAvatarRelicRecommend recomended_relic_info_list = 5;
}

message BigDataRecommendRelicAvatar {
    repeated RecomendedAvatarInfo recommended_avatar_info_list = 1;
}

enum BigDataRecommendType {
    BIG_DATA_RECOMMEND_TYPE_NONE = 0;
    BIG_DATA_RECOMMEND_TYPE_EQUIPMENT = 1;
    BIG_DATA_RECOMMEND_TYPE_RELIC_SUIT = 2;
    BIG_DATA_RECOMMEND_TYPE_RELIC_AVATAR = 3;
    BIG_DATA_RECOMMEND_TYPE_AVATAR_RELIC = 4;
    BIG_DATA_RECOMMEND_TYPE_LOCAL_LEGEND = 5;
    BIG_DATA_RECOMMEND_TYPE_CHALLENGE_PEAK_MOB = 6;
    BIG_DATA_RECOMMEND_TYPE_CHALLENGE_PEAK_BOSS = 7;
    BIG_DATA_RECOMMEND_TYPE_CHALLENGE = 8;
    BIG_DATA_RECOMMEND_TYPE_HMFFBIANKBF = 9;
    BIG_DATA_RECOMMEND_TYPE_IGDNEOELFKC = 10;
}

enum CmdRecommendType {
    CmdRecommendType_NLCDGIPGFDJ = 0;
    CmdRecommendType_GetBigDataRecommendCsReq = 2403;
    CmdRecommendType_GetBigDataRecommendScRsp = 2407;
    CmdRecommendType_BigDataAllRecommendCSReq = 2410;
    CmdRecommendType_GetBigDataAllRecommendScRsp = 2421;
}

message EquipmentRecommend {
    repeated BMMHJIFCGNO equipment_list = 2;
}

message GHAJJBBEHBE {
    uint32 LMHDFOFNFII = 3;
    uint32 BBGHAFGMMNM = 4;
    uint32 OAOPDHLDFIP = 11;
}

message GNBBDMBNNDJ {
    repeated JOLHIMGJGBO lineup_list = 1;
}

message GetBigDataAllRecommendScRsp {
    BigDataRecommendType big_data_recommend_type = 5;
    uint32 retcode = 9;
    oneof OODKOEILJCD {
        BigDataRecommendRelicAvatar relic_avatar = 1;
        BigDataRecommendAvatarRelic avatar_relic = 8;
        GNBBDMBNNDJ KHCMLINMGEN = 7;
    }
}

message GetBigDataRecommendCsReq {
    BigDataRecommendType big_data_recommend_type = 1;
    uint32 equip_avatar = 2;
}

message GetBigDataRecommendScRsp {
    uint32 equip_avatar = 2;
    bool has_recommand = 6;
    BigDataRecommendType big_data_recommend_type = 12;
    uint32 retcode = 14;
    oneof OODKOEILJCD {
        EquipmentRecommend equipment_recommend = 13;
        RelicRecommend relic_recommend = 11;
        GNBBDMBNNDJ KHCMLINMGEN = 4;
    }
}

message JBGPLPCCDBJ {
    uint32 NMFGIBMHNKI = 1;
    uint32 GBJPBAHGBPO = 4;
    uint32 percent = 8;
}

message RecomendedAvatarInfo {
    uint32 recommend_avatar_id = 9;
    repeated uint32 avatar_id_list = 11;
    uint32 relic_set_id = 12;
}

message RelicRecommend {
    repeated GHAJJBBEHBE GMCNPKAJMHC = 9;
}
