syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AAFBNNALHDK {
    uint32 NPHAJEKCBKF = 1;
    uint32 avatar_id = 2;
    repeated uint32 HHFPJHMEIJK = 4;
    uint32 BDJDAOGDBDD = 10;
    uint32 ALOPEGJPAKK = 12;
}

message AJCFOLGANFC {
    uint32 DEDCHHNCHFM = 1;
    uint32 style_level = 3;
    repeated KVP IHFEBNBHDFM = 5;
    uint32 PGGDEHKKINP = 9;
    repeated JHECCCANFGP GJBOLJEJIEE = 12;
    uint32 style_exp = 13;
}

message AMOHFCEEBNK {
    FGGJCLDLMMI FCMGNLIODGI = 12;
}

message BJLNEBBMMOE {
    uint32 NIOFIOOGKLD = 3;
    bool DOFNEAPHMKH = 7;
    uint32 PDFJMFBHPFC = 14;
}

message CABKLLAKHKO {
    AJCFOLGANFC GMEPGCODKKE = 7;
}

message CFOIFHEBCJC {
    LPADDGPLIKK CCFGCCMEFCI = 7;
}

message CGBKKJENEOF {
    repeated uint32 BDBFENOAKOD = 11;
}

message CGNGOLJKBMP {
    HGGPKPPBGFP HHMLHKLKNDH = 1;
    PHHLBGLNBHE MEEJDFNHBDI = 3;
    FKEDPCMLIFE item_value = 4;
    DJODDECFHMC formula = 5;
    OHHKEOGOMCA LNCOKKIPAEP = 6;
    EGLAPJGFKPN buff = 8;
    HIAHPMEAGFC BCNMBONFKPK = 9;
    ONPOFJPEBMJ level = 11;
    NHLBNBBDHMI miracle = 12;
    JEIKFFFGONB lineup = 13;
    CGBKKJENEOF BKIPDOFONLD = 15;
}

message CJOCDGGCPCN {
    int64 end_time = 6;
    bool KBNNOPHGGIN = 7;
    uint32 JNBIIJCAKKB = 9;
    uint32 JDPFPDECPEH = 13;
}

message COOIDLLFFIJ {
    oneof AJOABBCKHCK {
        uint32 KNILAKJMEEP = 13;
        uint32 PGGDEHKKINP = 2;
    }
}

enum CmdRogueTournType {
    CmdRogueTournType_NLCDGIPGFDJ = 0;
    CmdRogueTournType_GMMLDBBBMOB = 6014;
    CmdRogueTournType_RogueTournWeekChallengeUpdateScNotify = 6084;
    CmdRogueTournType_ADHCMDHNCIH = 6097;
    CmdRogueTournType_COBBOLLGLJM = 6061;
    CmdRogueTournType_OLJGECDPHDN = 6072;
    CmdRogueTournType_RogueTournGetCurRogueCocoonInfoScRsp = 6090;
    CmdRogueTournType_RogueTournRenameArchiveScRsp = 6057;
    CmdRogueTournType_EIDJIJPEDJG = 6085;
    CmdRogueTournType_FCPJLDACDJI = 6056;
    CmdRogueTournType_NLNBJLHDNAM = 6080;
    CmdRogueTournType_RogueTournReviveCostUpdateScNotify = 6039;
    CmdRogueTournType_RogueTournReEnterRogueCocoonStageScRsp = 6028;
    CmdRogueTournType_NFHEPPBLJEM = 6059;
    CmdRogueTournType_RogueTournGetSeasonTalentInfoScRsp = 6049;
    CmdRogueTournType_RogueTournAreaUpdateScNotify = 6040;
    CmdRogueTournType_RogueTournResetPermanentTalentScRsp = 6031;
    CmdRogueTournType_RogueTournLeaveScRsp = 6062;
    CmdRogueTournType_DMGHOODIDCH = 6089;
    CmdRogueTournType_RogueTournDeleteBuildRefScRsp = 6091;
    CmdRogueTournType_CHEEPPFGIEK = 6073;
    CmdRogueTournType_RogueTournEnablePermanentTalentScRsp = 6058;
    CmdRogueTournType_CCNBOGOEPMJ = 6078;
    CmdRogueTournType_PCBBKKGGIPI = 6015;
    CmdRogueTournType_RogueTournSettleScRsp = 6037;
    CmdRogueTournType_HODIGELBEPF = 6022;
    CmdRogueTournType_RogueTournStartScRsp = 6093;
    CmdRogueTournType_RogueTournGetAllBuildRefScRsp = 6096;
    CmdRogueTournType_RogueTournEnableSeasonTalentScRsp = 6038;
    CmdRogueTournType_RogueTournBattleFailSettleInfoScNotify = 6024;
    CmdRogueTournType_RogueTournGetArchiveRepositoryScRsp = 6026;
    CmdRogueTournType_DPGGHPHKBDA = 6054;
    CmdRogueTournType_RogueTournDeleteArchiveScRsp = 6081;
    CmdRogueTournType_NKHDFBHDOBG = 6046;
    CmdRogueTournType_GDLIGAPAHOD = 6023;
    CmdRogueTournType_RogueTournGetSettleInfoScRsp = 6047;
    CmdRogueTournType_OCKHDDBDGMJ = 6036;
    CmdRogueTournType_EMPBOGAJOPE = 6070;
    CmdRogueTournType_RogueTournEnterScRsp = 6043;
    CmdRogueTournType_KMLIBOEDGGE = 6069;
    CmdRogueTournType_FBPFEOJEGIL = 6025;
    CmdRogueTournType_RogueTournQueryScRsp = 6052;
    CmdRogueTournType_BNOGOAHABHN = 6042;
    CmdRogueTournType_RogueTournGetMiscRealTimeDataScRsp = 6063;
    CmdRogueTournType_RogueTournEnterLayerScRsp = 6082;
    CmdRogueTournType_HOOPLLFAEAB = 6092;
    CmdRogueTournType_GGLDPDGKKHL = 6033;
    CmdRogueTournType_EDJGBDBFLEK = 6074;
    CmdRogueTournType_RogueTournTitanUpdateTitanBlessProgressScNotify = 6076;
    CmdRogueTournType_RogueTournLeaveRogueCocoonSceneScRsp = 6053;
    CmdRogueTournType_RogueTournSaveBuildRefScRsp = 6027;
    CmdRogueTournType_RogueTournEnterRogueCocoonSceneScRsp = 6079;
    CmdRogueTournType_RogueTournGetCurRogueCocoonInfoCsReq = 6065;
    CmdRogueTournType_AJIOOMLGHOK = 6048;
    CmdRogueTournType_RogueTournHandBookNotify = 6055;
    CmdRogueTournType_RogueTournRenameBuildRefScRsp = 6098;
    CmdRogueTournType_RogueTournTakeExpRewardScRsp = 6075;
    CmdRogueTournType_RogueTournExpNotify = 6030;
    CmdRogueTournType_RogueTournReviveAvatarScRsp = 6095;
    CmdRogueTournType_RogueTournClearArchiveNameScNotify = 6016;
    CmdRogueTournType_LCFHIOEHDJN = 6068;
    CmdRogueTournType_DACKEJAPIPM = 6021;
    CmdRogueTournType_RogueTournConfirmSettleScRsp = 6029;
    CmdRogueTournType_OJBIPEEGMEC = 6013;
    CmdRogueTournType_RogueTournGetAllArchiveScRsp = 6045;
    CmdRogueTournType_NEKCFMGNGPB = 6094;
    CmdRogueTournType_HBICPILLFEO = 6051;
    CmdRogueTournType_RogueTournUseSuperRewardKeyScRsp = 6011;
    CmdRogueTournType_RogueTournEnterRoomScRsp = 6088;
    CmdRogueTournType_EDHLEDMDJHD = 6044;
    CmdRogueTournType_RogueTournGetPermanentTalentInfoScRsp = 6035;
    CmdRogueTournType_RogueTournReviveRogueAvatarCsReq = 6020;
    CmdRogueTournType_RogueTournPersonaRoomCardZoneUpdateScNotify = 6019;
    CmdRogueTournType_RogueTournLevelInfoUpdateScNotify = 6067;
    CmdRogueTournType_AFDKPOLPNOD = 6083;
}

message DCDMPLJNBJC {
    uint32 NDGKLBDHJKB = 3;
    bool DOFNEAPHMKH = 4;
    uint32 KABCGHCPEBG = 5;
    uint32 GEPHKCPLAJF = 10;
}

message DIFGGDIHDEG {
    OOLJJHMLHBH MPOEFPFPEND = 6;
    int64 BHNFGJOLLLB = 7;
    int64 time = 11;
    string name = 13;
    uint32 NPHAJEKCBKF = 15;
}

message DJODDECFHMC {
    HMAAICNBKCI ENFIKCCMHAI = 5;
    repeated LEJFIEPMMGG KJFEFFGPNFF = 8;
    repeated OMJGKNJKHCH EMLLEPOADED = 10;
}

message DKFJLHHDFKO {
    uint32 id = 9;
    AvatarType avatar_type = 14;
}

message DLEKOLHCNIE {
    bool FJKHIFDJMDB = 9;
    bool is_taken_reward = 10;
    bool is_unlock = 11;
    uint32 area_id = 15;
}

message DNCEOOPHIOK {
    uint32 LJCEOGPOGBE = 8;
}

message ECMNFOEDOJC {
    uint32 LJCEOGPOGBE = 4;
}

message ELHLCFBPAMO {
    repeated uint32 attribute_list = 2;
    uint32 composition_type = 9;
    uint32 level = 14;
}

message FAICNBKIELL {
    FBBOKKLGKGL BNLLEJPCIGD = 3;
    JGMDJIENFFH CPOLAHJPGFE = 7;
    GKHFFKMFMEN JJLFKNPEPFP = 9;
    DCDMPLJNBJC AOGOHOCFFNE = 12;
    PFLOIHLLMEE PHGJIJELKDB = 13;
    BJLNEBBMMOE AOMHPLHONJA = 15;
}

message FBBOKKLGKGL {
    uint32 LFCDPDDGFCB = 1;
    bool DOFNEAPHMKH = 2;
    uint32 DIFIEHPCDGO = 9;
}

message FGGJCLDLMMI {
    uint32 PLJPIPDFAHA = 7;
    repeated uint32 OHKHMDEOCLA = 13;
}

enum FKNGOGLNKIG {
    FKNGOGLNKIG_NLCDGIPGFDJ = 0;
    FKNGOGLNKIG_EHNIPLNEEDI = 1;
    FKNGOGLNKIG_PMKMEAAGKAP = 2;
    FKNGOGLNKIG_MNBAGHPEFBC = 3;
}

message GKHFFKMFMEN {
    bool DOFNEAPHMKH = 10;
    uint32 NIOFIOOGKLD = 12;
}

message HGGPKPPBGFP {
    uint32 OHPELHFNGCI = 1;
}

message HIAHPMEAGFC {
    bool JOOJIJFCHMK = 7;
}

message HMGGOEHMIJO {
    uint32 FABMHMFNMDB = 4;
    uint32 HHAEEEOADOJ = 9;
}

message HMOECPBNAOK {
    repeated uint32 MMPPHJOONMI = 1;
    repeated uint32 IFFMIDABNEE = 6;
    uint32 JKKIABLFCPE = 7;
    repeated uint32 PINNDKIJHFG = 9;
    repeated uint32 JOAAOEDAPPJ = 11;
    repeated uint32 DPEBCGBEJIG = 14;
    repeated uint32 DMFAGJOOGJM = 15;
}

enum IDCBNMFDICO {
    IDCBNMFDICO_NLCDGIPGFDJ = 0;
    IDCBNMFDICO_LOOAKNHDBLL = 1;
    IDCBNMFDICO_CIHFGJDCHIA = 2;
}

enum IIAOGEIADGA {
    IIAOGEIADGA_NLCDGIPGFDJ = 0;
    IIAOGEIADGA_JHHAJDKPLJH = 1;
    IIAOGEIADGA_LOOAKNHDBLL = 2;
    IIAOGEIADGA_CIHFGJDCHIA = 3;
}

message IJNFOHJGPBC {
    uint32 JOJCPKNIJOH = 3;
    repeated ODNBCBEINNC JEHEILKKDEF = 6;
    uint32 layer_index = 10;
    uint32 MDAIAMFJNHM = 11;
    IDCBNMFDICO status = 12;
}

message JGAMMPGMCNI {
    SceneInfo scene = 3;
    LineupInfo lineup = 13;
    FHEGNOPNICH JNKLNLKHGBB = 15;
}

message JGFPIJKOFCC {
    uint32 NPHAJEKCBKF = 15;
}

message JGJEICAELEB {
    repeated uint32 FKDNANDJLGK = 6;
    uint32 exp = 7;
}

message JGMDJIENFFH {
    uint32 GNIFODGCPAA = 7;
    uint32 JBKHIFHPGHM = 8;
}

message JHECCCANFGP {
    uint32 total_count = 2;
    uint32 unique_id = 6;
    uint32 GNCFHIKODKE = 13;
}

message KCDBGKJANIH {
    uint32 buff_id = 4;
}

message KGPIEEKIEME {
    FDBDLBAPDBE JCOBJAMPOAL = 6;
    uint32 OFNIDAECPCJ = 10;
}

message KIKEAJJLAMH {
    KGPIEEKIEME HANICMMHJGI = 1;
    repeated MJMGOBMOPDL HLJOMIMOANL = 2;
    JGMDJIENFFH DLDCFHHFMID = 3;
    CJOCDGGCPCN BFNHJIBDMOA = 5;
    HMGGOEHMIJO HHFAAFOBKME = 9;
    repeated DLEKOLHCNIE DANNIDIPFAL = 10;
    JGJEICAELEB DMFPCFCHHKE = 12;
    HMOECPBNAOK HAMKPLCBEBG = 13;
    MDLPIFCHFPJ DPABCOHLPLH = 14;
}

message KILGONODPIC {
    uint32 event_id = 9;
}

message LGCPLLJLHFF {
    uint32 item_value = 6;
    repeated KJAMNOGFAMJ buff_list = 8;
}

message LPADDGPLIKK {
    repeated uint32 NMMCOBBKKHA = 1;
    uint32 AMOABLICEDP = 4;
    uint32 MKJDMNAEAED = 5;
    uint32 PJOAKLHHCNI = 8;
    repeated uint32 BIMFEAHDMIK = 9;
    repeated BDJLHJDPEEK LONFKFCFDND = 14;
}

message MDLPIFCHFPJ {
    FDBDLBAPDBE JCOBJAMPOAL = 4;
    uint32 INJEKPLHPIF = 8;
}

message MJBODJKDPPD {
    uint32 KAHMGPGPOII = 6;
}

message MJMGOBMOPDL {
    repeated DKFJLHHDFKO avatar_list = 3;
    string name = 5;
    int64 time = 6;
    int64 end_time = 9;
    uint32 NPHAJEKCBKF = 11;
    LGCPLLJLHFF data = 12;
    PFLOIHLLMEE PHGJIJELKDB = 13;
    HMGGOEHMIJO HHFAAFOBKME = 14;
}

message MNILJCPCOFG {
    uint32 retcode = 2;
}

message NAMCKJLAFCN {
}

message NPOJNHKPKMN {
}

message ODNBCBEINNC {
    uint32 GHEHGIOAGDG = 2;
    uint32 LHLKJIDFLIN = 3;
    uint32 room_id = 7;
    IIAOGEIADGA status = 10;
    uint32 EEPIDJJJMAH = 12;
    ELHLCFBPAMO FIADMEPDAOG = 1;
}

message OHHKEOGOMCA {
    map<uint32, bool> PACLGPIDJGL = 3;
}

message ONPOFJPEBMJ {
    RogueTournLevelStatus status = 6;
    repeated IJNFOHJGPBC NNFFPJOLDHK = 7;
    uint32 BJHMFOAGMBF = 10;
    bool EJDMOENBHDP = 12;
    bool KENPENNAGLG = 13;
    FKNGOGLNKIG reason = 14;
    CFOIFHEBCJC FIADMEPDAOG = 8;
}

message OOLJJHMLHBH {
    repeated uint32 JHBEJKBCHEN = 1;
    repeated uint32 AKEMNAMGDOD = 4;
    repeated uint32 LBKFGKGNCCH = 7;
    uint32 HHAEEEOADOJ = 8;
    repeated AAFBNNALHDK KOJMGCBLKKA = 9;
    uint32 FABMHMFNMDB = 11;
    repeated uint32 MDHGBNCJNGB = 15;
}

message PALAOPCBAPC {
    uint32 NPHAJEKCBKF = 10;
    uint32 retcode = 13;
}

message PFLOIHLLMEE {
    CBOLONJDHHL basic = 3;
    CGNGOLJKBMP AMEABNLMMGB = 12;
    oneof KKNBOACNCON {
        NAMCKJLAFCN FBHCKMGOCJJ = 349;
        AMOHFCEEBNK HAJEGKBFFAF = 1144;
        CABKLLAKHKO OPDEIFOCJEF = 244;
    }
}

message PHHLBGLNBHE {
    repeated uint32 KEHKLHMEABI = 12;
}

message RogueTournAreaUpdateScNotify {
    repeated DLEKOLHCNIE DANNIDIPFAL = 7;
}

message RogueTournBattleFailSettleInfoScNotify {
    JGAMMPGMCNI IDCMACCPCBH = 8;
    FAICNBKIELL BFLLJJBHLDF = 13;
}

message RogueTournClearArchiveNameScNotify {
    uint32 NPHAJEKCBKF = 1;
}

message RogueTournConfirmSettleScRsp {
    ItemList IIOMCJPCFML = 1;
    JGAMMPGMCNI IDCMACCPCBH = 4;
    MJMGOBMOPDL BLPDBPHMCGA = 8;
    ItemList AELJFOPMDJG = 10;
    uint32 retcode = 15;
}

message RogueTournDeleteArchiveScRsp {
    uint32 NPHAJEKCBKF = 5;
    uint32 retcode = 7;
}

message RogueTournDeleteBuildRefScRsp {
    repeated uint32 GGIGDJPFBBP = 3;
    uint32 retcode = 7;
}

message RogueTournEnablePermanentTalentScRsp {
    uint32 retcode = 1;
    MDLPIFCHFPJ DPABCOHLPLH = 11;
}

message RogueTournEnableSeasonTalentScRsp {
    KGPIEEKIEME HANICMMHJGI = 4;
    uint32 retcode = 7;
}

message RogueTournEnterLayerScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 2;
    uint32 retcode = 10;
}

message RogueTournEnterRogueCocoonSceneScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 3;
    uint32 retcode = 6;
}

message RogueTournEnterRoomScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 7;
    uint32 retcode = 11;
}

message RogueTournEnterScRsp {
    uint32 retcode = 6;
    PFLOIHLLMEE PHGJIJELKDB = 10;
    JGAMMPGMCNI IDCMACCPCBH = 13;
}

message RogueTournExpNotify {
    uint32 exp = 6;
}

message RogueTournGetAllArchiveScRsp {
    uint32 retcode = 3;
    repeated MJMGOBMOPDL MCGGPONOCKC = 5;
}

message RogueTournGetAllBuildRefScRsp {
    repeated DIFGGDIHDEG GIOEPGJGMPD = 2;
    uint32 retcode = 15;
}

message RogueTournGetArchiveRepositoryScRsp {
    repeated uint32 BDNFDHJBAME = 3;
    repeated uint32 PBPIOEKJJPF = 9;
    uint32 retcode = 12;
}

message RogueTournGetCurRogueCocoonInfoCsReq {
}

message RogueTournGetCurRogueCocoonInfoScRsp {
    uint32 DCNNFJLABPL = 3;
    uint32 NBLMAGLGCGN = 4;
    uint32 retcode = 5;
    uint32 difficulty = 7;
    uint32 HECCOBFBJFI = 15;
}

message RogueTournGetMiscRealTimeDataScRsp {
    BJLNEBBMMOE AOMHPLHONJA = 3;
    JGMDJIENFFH CPOLAHJPGFE = 4;
    GKHFFKMFMEN JJLFKNPEPFP = 9;
    uint32 retcode = 11;
    FBBOKKLGKGL BNLLEJPCIGD = 13;
    DCDMPLJNBJC AOGOHOCFFNE = 14;
}

message RogueTournGetPermanentTalentInfoScRsp {
    uint32 retcode = 3;
    MDLPIFCHFPJ DPABCOHLPLH = 9;
}

message RogueTournGetSeasonTalentInfoScRsp {
    uint32 retcode = 13;
    KGPIEEKIEME HANICMMHJGI = 14;
}

message RogueTournGetSettleInfoScRsp {
    uint32 retcode = 5;
    FAICNBKIELL BFLLJJBHLDF = 9;
}

message RogueTournHandBookNotify {
    oneof KKNBOACNCON {
        ECMNFOEDOJC ODHGPLKCBBG = 6;
        DNCEOOPHIOK IOOACHNEHAH = 14;
        KCDBGKJANIH LFCDGLIEHAI = 11;
        KILGONODPIC OOOACLEFDGM = 12;
        MJBODJKDPPD ICNOEGEEPOF = 5;
        COOIDLLFFIJ CFNAKPADAEB = 3;
    }
}

message RogueTournLeaveRogueCocoonSceneScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 4;
    uint32 retcode = 9;
}

message RogueTournLeaveScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 1;
    uint32 retcode = 8;
}

message RogueTournLevelInfoUpdateScNotify {
    FKNGOGLNKIG reason = 2;
    repeated IJNFOHJGPBC NNFFPJOLDHK = 4;
    RogueTournLevelStatus status = 5;
    uint32 BJHMFOAGMBF = 10;
}

enum RogueTournLevelStatus {
    NHMPGNHBBLC_NLCDGIPGFDJ = 0;
    NHMPGNHBBLC_LOOAKNHDBLL = 1;
    NHMPGNHBBLC_CCKPNCIBDGP = 2;
    NHMPGNHBBLC_JKNPMIMBGML = 3;
}

message RogueTournPersonaRoomCardZoneUpdateScNotify {
    ODHJEDHKHOD NHNBJLLDOHO = 11;
}

message RogueTournQueryScRsp {
    uint32 retcode = 7;
    PFLOIHLLMEE PHGJIJELKDB = 11;
    KIKEAJJLAMH LFLCDNGALME = 12;
}

message RogueTournReEnterRogueCocoonStageScRsp {
    SceneBattleInfo battle_info = 2;
    uint32 retcode = 5;
}

message RogueTournRenameArchiveScRsp {
    string name = 11;
    uint32 NPHAJEKCBKF = 14;
    uint32 retcode = 15;
}

message RogueTournRenameBuildRefScRsp {
    uint32 retcode = 4;
    uint32 NPHAJEKCBKF = 9;
    string name = 15;
}

message RogueTournResetPermanentTalentScRsp {
    MDLPIFCHFPJ DPABCOHLPLH = 2;
    uint32 retcode = 5;
}

message RogueTournReviveAvatarScRsp {
    uint32 retcode = 5;
    ItemCostData LNIEFKBMIPD = 6;
}

message RogueTournReviveCostUpdateScNotify {
    ItemCostData LNIEFKBMIPD = 9;
}

message RogueTournSaveBuildRefScRsp {
    uint32 retcode = 2;
    uint32 NPHAJEKCBKF = 12;
    string name = 13;
}

message RogueTournSettleScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 2;
    uint32 retcode = 4;
    FAICNBKIELL BFLLJJBHLDF = 5;
}

message RogueTournStartScRsp {
    JGAMMPGMCNI IDCMACCPCBH = 5;
    PFLOIHLLMEE PHGJIJELKDB = 10;
    uint32 retcode = 13;
}

message RogueTournTakeExpRewardScRsp {
    uint32 retcode = 3;
    repeated uint32 FKDNANDJLGK = 5;
    uint32 exp = 6;
    ItemList reward = 15;
}

message RogueTournTitanUpdateTitanBlessProgressScNotify {
    uint32 PLJPIPDFAHA = 11;
}

message RogueTournUseSuperRewardKeyScRsp {
    uint32 retcode = 4;
    ItemList reward = 6;
    ItemList drop_data = 8;
    LMDPKOELKFL ABEMLCJBIEF = 9;
}

message RogueTournWeekChallengeUpdateScNotify {
    CJOCDGGCPCN BFNHJIBDMOA = 8;
}
