syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BCAJNMLLIED {
    uint32 panel_id = 2;
    repeated uint32 OLHODIFNABL = 3;
    uint32 progress = 7;
    uint32 id = 10;
}

enum CmdRechargeGiftType {
    CmdRechargeGiftType_NLCDGIPGFDJ = 0;
    CmdRechargeGiftType_GetRechargeBenefitInfoScRsp = 8377;
    CmdRechargeGiftType_DOIMOMMDEGJ = 8364;
    CmdRechargeGiftType_MFNAHHMMGNK = 8363;
    CmdRechargeGiftType_GLAMIHDHHCC = 8362;
    CmdRechargeGiftType_TakeRechargeGiftRewardScRsp = 8372;
    CmdRechargeGiftType_GetRechargeGiftInfoScRsp = 8368;
    CmdRechargeGiftType_GetRechargeGiftInfoCsReq = 8378;
    CmdRechargeGiftType_TakeRechargeBenefitRewardScRsp = 8371;
    CmdRechargeGiftType_SyncRechargeBenefitInfoScNotify = 8365;
}

message GetRechargeBenefitInfoScRsp {
    repeated BCAJNMLLIED OABBABNPPOO = 6;
    uint32 retcode = 8;
}

message GetRechargeGiftInfoCsReq {
}

message GetRechargeGiftInfoScRsp {
    repeated JBNGCJJDLHL OFIHOCCHNCN = 2;
    uint32 retcode = 11;
}

message IJHPILBBHDI {
    message BBIBCFCKPJH {
        enum EGCFNCBLHJC {
            EGCFNCBLHJC_EDHBOMMOKGM = 0;
            EGCFNCBLHJC_ACBHGLIBJBG = 1;
            EGCFNCBLHJC_LJLKNDIACEO = 2;
        }
    }
    IJHPILBBHDI.BBIBCFCKPJH.EGCFNCBLHJC status = 2;
    uint32 index = 11;
}

message JBNGCJJDLHL {
    uint32 gift_type = 2;
    int64 end_time = 3;
    int64 start_time = 5;
    repeated IJHPILBBHDI status_list = 8;
}

message SyncRechargeBenefitInfoScNotify {
    BCAJNMLLIED KLCGBJIEMPO = 7;
}

message TakeRechargeBenefitRewardScRsp {
    BCAJNMLLIED KLCGBJIEMPO = 10;
    uint32 retcode = 11;
    ItemList reward = 12;
}

message TakeRechargeGiftRewardScRsp {
    JBNGCJJDLHL KJBDNIIBGNE = 2;
    ItemList reward = 12;
    uint32 retcode = 15;
}
