syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdRollShopType {
    CmdRollShopType_NLCDGIPGFDJ = 0;
    CmdRollShopType_DoGachaInRollShopScRsp = 6912;
    CmdRollShopType_RollShopGachaCsReq = 6903;
    CmdRollShopType_FNHGIIEDMOL = 6902;
    CmdRollShopType_GetRollShopInfoScRsp = 6908;
    CmdRollShopType_TakeRollShopRewardScRsp = 6917;
    CmdRollShopType_GetRollShopInfoCsReq = 6918;
}

message DoGachaInRollShopScRsp {
    uint32 reward_display_type = 4;
    uint32 roll_shop_id = 5;
    ItemList reward = 6;
    uint32 LDBCKJIPDHF = 13;
    uint32 retcode = 14;
}

message GetRollShopInfoCsReq {
    uint32 roll_shop_id = 6;
}

message GetRollShopInfoScRsp {
    uint32 gacha_random = 2;
    uint32 retcode = 5;
    repeated uint32 shop_group_id_list = 9;
    uint32 roll_shop_id = 10;
}

message TakeRollShopRewardScRsp {
    ItemList reward = 1;
    uint32 group_type = 3;
    uint32 roll_shop_id = 5;
    uint32 retcode = 9;
}
