syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdRelicPresetType {
    CmdRelicPresetType_NLCDGIPGFDJ = 0;
    CmdRelicPresetType_CIGFPGNKCBO = 9845;
    CmdRelicPresetType_FPEMHEADJMF = 9844;
    CmdRelicPresetType_FJPOEECMLFM = 9843;
    CmdRelicPresetType_ALPFGCMPNAK = 9848;
    CmdRelicPresetType_BJGKLFMLMAF = 9855;
    CmdRelicPresetType_HOCGMBLBMBD = 9852;
    CmdRelicPresetType_PKLFCJBCOLE = 9851;
    CmdRelicPresetType_EMOAOEIMDDM = 9858;
    CmdRelicPresetType_ODHBCNILDOK = 9842;
    CmdRelicPresetType_CHMEMLHLCMA = 9857;
}

message EGGOCLKIAME {
    uint32 unique_id = 14;
}

message EJILGJGLKIO {
    PFCKBFLDHNI relic_plan = 6;
}

enum FDJKLJGDCID {
    FDJKLJGDCID_NLCDGIPGFDJ = 0;
    FDJKLJGDCID_DCGAPNGCCEH = 1;
    FDJKLJGDCID_BMHMMIMOAIJ = 2;
    FDJKLJGDCID_JPDBDLEEHGK = 3;
    FDJKLJGDCID_OGPNODHENKN = 4;
    FDJKLJGDCID_PICLIGEAJFN = 5;
    FDJKLJGDCID_FHCEFAOHJJJ = 6;
}

message HPPOINFLEPJ {
    FDJKLJGDCID LLJJCOOKANH = 1;
    repeated uint32 relic_ids = 4;
    RelicPresetPlanSourceType source_type = 12;
}

message PFCKBFLDHNI {
    uint32 avatar_id = 1;
    repeated uint32 relic_ids = 4;
    string name = 6;
    uint32 unique_id = 10;
    RelicPresetPlanSourceType source_type = 13;
}

enum RelicPresetPlanSourceType {
    HNBGMOIHOAN_NLCDGIPGFDJ = 0;
    HNBGMOIHOAN_BDNDDMBONNJ = 1;
    HNBGMOIHOAN_DLBLNAKKNKJ = 2;
    HNBGMOIHOAN_ODFAMIBHIGE = 3;
    HNBGMOIHOAN_LIKOPGNHBPP = 4;
    HNBGMOIHOAN_CPHMEHDCFBF = 5;
    HNBGMOIHOAN_platform = 6;
}
