syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message CABBOOKAODO {
    ONFLANPGHHL AEONNKANGCE = 3;
    repeated uint32 relic_ids = 10;
    uint32 avatar_id = 13;
}

enum CmdRelicSmartWearType {
    CmdRelicSmartWearType_NLCDGIPGFDJ = 0;
    CmdRelicSmartWearType_RelicSmartWearDeletePlanScRsp = 8254;
    CmdRelicSmartWearType_RelicSmartWearUpdatePinRelicScRsp = 8256;
    CmdRelicSmartWearType_RelicSmartWearGetPlanScRsp = 8258;
    CmdRelicSmartWearType_FOAGMJKPMPG = 8268;
    CmdRelicSmartWearType_CPKIJENBJIC = 8269;
    CmdRelicSmartWearType_GLNCPBGNDIG = 8251;
    CmdRelicSmartWearType_RelicSmartWearAddPlanScRsp = 8262;
    CmdRelicSmartWearType_RelicSmartWearGetPinRelicScRsp = 8259;
    CmdRelicSmartWearType_KAJELKNPMLF = 8255;
    CmdRelicSmartWearType_MMBGLIDPBIB = 8252;
    CmdRelicSmartWearType_RelicSmartWearDeletePinRelicScRsp = 8266;
    CmdRelicSmartWearType_RelicSmartWearUpdatePinRelicScNotify = 8270;
    CmdRelicSmartWearType_PGDKLOECDJF = 8264;
    CmdRelicSmartWearType_RelicSmartWearUpdatePlanScRsp = 8267;
    CmdRelicSmartWearType_GDCIJLJGNEB = 8253;
}

enum KCKJILIMNFF {
    KCKJILIMNFF_NLCDGIPGFDJ = 0;
    KCKJILIMNFF_CFPGFAMANFD = 1;
    KCKJILIMNFF_HEHPPOFHLMI = 2;
    KCKJILIMNFF_EBDIOJPDJIH = 3;
}

message ONFLANPGHHL {
    repeated uint32 inside_relic_list = 4;
    KCKJILIMNFF ALAEIBDIGHM = 13;
    repeated uint32 outside_relic_list = 15;
}

message RelicSmartWearAddPlanScRsp {
    uint32 retcode = 12;
    RelicSmartWearPlan relic_plan = 13;
}

message RelicSmartWearDeletePinRelicScRsp {
    repeated ONFLANPGHHL AIFAMIFGMCH = 5;
    uint32 avatar_id = 10;
    uint32 retcode = 14;
}

message RelicSmartWearDeletePlanScRsp {
    uint32 unique_id = 4;
    uint32 retcode = 10;
}

message RelicSmartWearGetPinRelicScRsp {
    repeated CABBOOKAODO OJNCAOKPKIB = 1;
    uint32 retcode = 5;
    uint32 avatar_id = 15;
}

message RelicSmartWearGetPlanScRsp {
    repeated RelicSmartWearPlan relic_plan_list = 6;
    uint32 avatar_id = 8;
    uint32 retcode = 12;
}

message RelicSmartWearPlan {
    uint32 unique_id = 4;
    repeated uint32 outside_relic_list = 5;
    uint32 avatar_id = 6;
    repeated uint32 inside_relic_list = 11;
}

message RelicSmartWearUpdatePinRelicScNotify {
    repeated CABBOOKAODO ANCHGOGNLFP = 3;
    repeated CABBOOKAODO PLNCNCNIPKN = 4;
    uint32 relic_unique_id = 10;
}

message RelicSmartWearUpdatePinRelicScRsp {
    uint32 retcode = 13;
    CABBOOKAODO DNNKBPBFPBK = 15;
}

message RelicSmartWearUpdatePlanScRsp {
    RelicSmartWearPlan relic_plan = 4;
    uint32 retcode = 13;
}
