syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdRogueModifierType {
    CmdRogueModifierType_NLCDGIPGFDJ = 0;
    CmdRogueModifierType_RogueModifierSelectCellScRsp = 5388;
    CmdRogueModifierType_EPPMKBDPDBM = 5358;
    CmdRogueModifierType_RogueModifierStageStartNotify = 5313;
    CmdRogueModifierType_RogueModifierAddNotify = 5393;
    CmdRogueModifierType_RogueModifierDelNotify = 5326;
    CmdRogueModifierType_RogueModifierUpdateNotify = 5347;
}

message RogueModifierAddNotify {
    BMCNDLNONMO modifier = 14;
}

message RogueModifierDelNotify {
    uint64 FCHLCANJIGL = 10;
}

message RogueModifierSelectCellScRsp {
    ItemList NMJGHEACCMC = 2;
    uint32 retcode = 10;
}

message RogueModifierStageStartNotify {
    RogueModifierSourceType source_type = 13;
}

message RogueModifierUpdateNotify {
    BMCNDLNONMO modifier = 6;
}
