syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdRedDotType {
    CmdRedDotType_NLCDGIPGFDJ = 0;
    CmdRedDotType_KABNELBBNKH = 5937;
    CmdRedDotType_EJDAHCIBGOF = 5919;
    CmdRedDotType_GetAllRedDotDataCsReq = 5909;
    CmdRedDotType_NFMGANEMPNE = 5944;
    CmdRedDotType_FKBAFCOEHGG = 5948;
    CmdRedDotType_DFFBHAGPBJE = 5923;
}

message EGELHCKMLNK {
    uint32 retcode = 9;
    uint32 FDEAKDCDGML = 10;
    uint32 group_id = 12;
    uint32 panel_id = 14;
}

message FHNAEJBKINH {
    repeated uint32 KCNPFIGHDAL = 12;
}

message GFOAMKNHBFE {
    map<uint32, FHNAEJBKINH> BANBCCBOEBJ = 2;
    uint32 FDEAKDCDGML = 10;
    uint32 panel_id = 14;
}

message GetAllRedDotDataCsReq {
}

message LLCOHLNBNGM {
    uint32 panel_id = 1;
    FHNAEJBKINH BKNKFNHIPAK = 2;
    uint32 group_id = 4;
    uint32 retcode = 8;
    uint32 FDEAKDCDGML = 14;
}
