syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CILKBJMGNGL {
    repeated ONMFMINNBEB GJGFCCKEMFD = 1;
    DFGAIOOGPPA IHJKLHGMKBI = 4;
    repeated uint32 OBBKBNDGOAI = 8;
    GNPFDBACMIH story_info = 9;
    repeated LGFOKKPICEH HIILDALHIMD = 11;
    repeated NMOMMMGHMOA JJIEDDMALPE = 14;
    repeated IFCNLKPPPHK DANNIDIPFAL = 15;
}

enum CmdRogueMagicType {
    CmdRogueMagicType_ELGPACEMCGP = 0;
    CmdRogueMagicType_RogueMagicEnterScRsp = 7758;
    CmdRogueMagicType_DNMLCNEJLCP = 7772;
    CmdRogueMagicType_CEMDCONHCGL = 7726;
    CmdRogueMagicType_RogueMagicReviveRogueAvatarCsReq = 7745;
    CmdRogueMagicType_OLMJEOHJDOE = 7749;
    CmdRogueMagicType_RogueMagicSetAutoDressInMagicUnitScRsp = 7712;
    CmdRogueMagicType_RogueMagicStoryInfoUpdateScNotify = 7715;
    CmdRogueMagicType_KJNOLKDPHHG = 7786;
    CmdRogueMagicType_RogueMagicSettleScRsp = 7747;
    CmdRogueMagicType_HNFPIDGENIB = 7735;
    CmdRogueMagicType_MEIBPJIJKAD = 7784;
    CmdRogueMagicType_HONOAMIJAEL = 7705;
    CmdRogueMagicType_RogueMagicUnitComposeScRsp = 7741;
    CmdRogueMagicType_RogueMagicStartScRsp = 7778;
    CmdRogueMagicType_RogueMagicReviveAvatarScRsp = 7769;
    CmdRogueMagicType_RogueMagicAutoDressInMagicUnitChangeScNotify = 7718;
    CmdRogueMagicType_RogueMagicAreaUpdateScNotify = 7738;
    CmdRogueMagicType_RogueMagicBattleFailSettleInfoScNotify = 7736;
    CmdRogueMagicType_RogueMagicEnterRoomScRsp = 7713;
    CmdRogueMagicType_RogueMagicLeaveScRsp = 7781;
    CmdRogueMagicType_DLGJNFNPIIM = 7744;
    CmdRogueMagicType_RogueMagicLevelInfoUpdateScNotify = 7733;
    CmdRogueMagicType_RogueMagicGetMiscRealTimeDataScRsp = 7775;
    CmdRogueMagicType_LEMAMDNLBBE = 7721;
    CmdRogueMagicType_AKELCLEGHFG = 7771;
    CmdRogueMagicType_RogueMagicQueryScRsp = 7730;
    CmdRogueMagicType_RogueMagicEnterLayerScRsp = 7740;
    CmdRogueMagicType_HIOELOOHHKA = 7780;
    CmdRogueMagicType_LJCCLPPDLHH = 7765;
    CmdRogueMagicType_AGJONFGMLNF = 7788;
    CmdRogueMagicType_LFABAIJILAP = 7725;
    CmdRogueMagicType_RogueMagicReviveCostUpdateScNotify = 7748;
    CmdRogueMagicType_RogueMagicEnableTalentScRsp = 7796;
    CmdRogueMagicType_OBJMAFEBKMO = 7734;
    CmdRogueMagicType_LHLOMIFDHIL = 7793;
    CmdRogueMagicType_JBCEMCLPDDP = 7773;
}

message DBOMCCEIFJO {
    uint32 retcode = 6;
}

message DFGAIOOGPPA {
    uint32 IMLHHAKIKCD = 2;
    FDBDLBAPDBE JCOBJAMPOAL = 13;
}

message EEILAINOLPO {
    SceneInfo scene = 5;
    LineupInfo lineup = 9;
    FHEGNOPNICH JNKLNLKHGBB = 13;
}

message EJHDAJAGFIJ {
    bool DOFNEAPHMKH = 5;
    uint32 AEAHOGPJKEF = 12;
}

message FKFOIDMNDFG {
    NOAKCDKAAFB BNLLEJPCIGD = 2;
    EJHDAJAGFIJ KDDGKLNGNEA = 6;
    GCBCKOKEAJH PHGJIJELKDB = 9;
}

message FODHGNLPBKH {
    uint32 EEPIDJJJMAH = 1;
    uint32 GHEHGIOAGDG = 7;
    uint32 room_id = 11;
    HOIFDJPBGLB status = 13;
}

message FPNDOBPMNED {
    repeated uint32 KEHKLHMEABI = 6;
}

message GCBCKOKEAJH {
    CBOLONJDHHL basic_info = 1;
    KDHAIFIOKDN level = 2;
    PLBAMNCLBHB DDLADFJMEEC = 5;
    NHLBNBBDHMI miracle = 7;
    JEIKFFFGONB lineup = 8;
    FKEDPCMLIFE item_value = 10;
    FPNDOBPMNED MEEJDFNHBDI = 11;
}

message GKMOAKPLBHO {
    uint32 LPOLPDBELON = 3;
    uint32 GCAHKLNGFCK = 5;
    uint32 dice_slot_id = 10;
}

message GNPFDBACMIH {
    repeated uint32 NOMDDGGIIBF = 15;
}

message GPEPGKCPBPB {
    repeated FODHGNLPBKH JEHEILKKDEF = 1;
    uint32 JOJCPKNIJOH = 5;
    uint32 MDAIAMFJNHM = 9;
    uint32 layer_index = 14;
    JGNAEPIJDNC status = 15;
}

message GPHMAJPGGEK {
    repeated OKCCLEEPELM IHKCHDJEJGJ = 2;
    repeated OCBPJLLLJGO EBFHIDKDJOB = 14;
}

message HBCOFDDCGOL {
    repeated uint32 JDJFHIMPIPK = 1;
    uint32 GCAHKLNGFCK = 6;
}

enum HOIFDJPBGLB {
    HOIFDJPBGLB_NLCDGIPGFDJ = 0;
    HOIFDJPBGLB_JHHAJDKPLJH = 1;
    HOIFDJPBGLB_LOOAKNHDBLL = 2;
    HOIFDJPBGLB_CIHFGJDCHIA = 3;
}

message IFCNLKPPPHK {
    repeated uint32 PBJLMCGIBND = 6;
    PGGMPDIMLAE COEBCNGCNOO = 7;
    NJMOAGDJKFH record_info = 8;
    uint32 area_id = 9;
    bool is_unlock = 10;
    bool is_taken_reward = 14;
    bool FJKHIFDJMDB = 15;
}

enum JAMINGBJHBK {
    JAMINGBJHBK_NLCDGIPGFDJ = 0;
    JAMINGBJHBK_EHNIPLNEEDI = 1;
    JAMINGBJHBK_PMKMEAAGKAP = 2;
    JAMINGBJHBK_MNBAGHPEFBC = 3;
}

enum JGNAEPIJDNC {
    JGNAEPIJDNC_NLCDGIPGFDJ = 0;
    JGNAEPIJDNC_LOOAKNHDBLL = 1;
    JGNAEPIJDNC_CIHFGJDCHIA = 2;
}

message KDHAIFIOKDN {
    uint32 JDPHADIIAPE = 2;
    uint32 JJLEDNENPJK = 3;
    PFKHKAMBHBN status = 6;
    JAMINGBJHBK reason = 9;
    repeated GPEPGKCPBPB NNFFPJOLDHK = 13;
    uint32 BJHMFOAGMBF = 15;
}

message NADKCPCFIPM {
    uint32 retcode = 11;
}

message NICAJBEJAHC {
    repeated uint32 JDJFHIMPIPK = 4;
}

message NJMOAGDJKFH {
    uint32 MHPCIABALPI = 3;
    uint32 JJLEDNENPJK = 5;
    uint32 ADIFLCNAABJ = 6;
    uint32 GEJEANJFCMI = 7;
    uint32 MEDAAELFEMN = 8;
    uint32 EJJGHJMCFPH = 11;
    uint32 NNNCEIGNIIA = 13;
    uint32 LKHAIEIDAJL = 14;
    uint32 NBMNPGKEIIH = 15;
    repeated uint32 avatar_id_list = 499;
    repeated MMBBHFNJILI HIILDALHIMD = 1214;
    repeated uint32 BGAFHIOEHFH = 1581;
    repeated DNLKMHLAPHC MALDOMHPILM = 1842;
}

message NMOMMMGHMOA {
    bool is_unlock = 4;
    uint32 DFBDPEHAAMG = 6;
}

message NOAKCDKAAFB {
    bool DOFNEAPHMKH = 10;
    uint32 ADMJAHDJDDJ = 12;
}

message OHONLLCHIFJ {
    uint32 retcode = 1;
}

enum PFKHKAMBHBN {
    PFKHKAMBHBN_NLCDGIPGFDJ = 0;
    PFKHKAMBHBN_LOOAKNHDBLL = 1;
    PFKHKAMBHBN_CCKPNCIBDGP = 2;
    PFKHKAMBHBN_JKNPMIMBGML = 3;
}

message PGGMPDIMLAE {
    repeated uint32 ILNFEABHHCH = 354;
}

message PLBAMNCLBHB {
    uint32 NBMNPGKEIIH = 2;
    bool HIKMFMJCNKP = 3;
    repeated MMBBHFNJILI HIILDALHIMD = 8;
    repeated DNLKMHLAPHC MALDOMHPILM = 9;
}

message RogueMagicAreaUpdateScNotify {
    repeated IFCNLKPPPHK DANNIDIPFAL = 4;
}

message RogueMagicAutoDressInMagicUnitChangeScNotify {
    bool GBEMCAHPBKP = 12;
}

message RogueMagicBattleFailSettleInfoScNotify {
    EEILAINOLPO IDCMACCPCBH = 13;
    FKFOIDMNDFG BFLLJJBHLDF = 15;
}

message RogueMagicEnableTalentScRsp {
    DFGAIOOGPPA IHJKLHGMKBI = 2;
    uint32 retcode = 8;
}

message RogueMagicEnterLayerScRsp {
    uint32 retcode = 6;
    EEILAINOLPO IDCMACCPCBH = 12;
}

message RogueMagicEnterRoomScRsp {
    uint32 retcode = 4;
    EEILAINOLPO IDCMACCPCBH = 11;
}

message RogueMagicEnterScRsp {
    EEILAINOLPO IDCMACCPCBH = 3;
    GCBCKOKEAJH PHGJIJELKDB = 6;
    uint32 retcode = 11;
}

message RogueMagicGetMiscRealTimeDataScRsp {
    uint32 retcode = 2;
    EJHDAJAGFIJ KDDGKLNGNEA = 3;
    NOAKCDKAAFB BNLLEJPCIGD = 8;
}

message RogueMagicLeaveScRsp {
    uint32 retcode = 2;
    EEILAINOLPO IDCMACCPCBH = 9;
}

message RogueMagicLevelInfoUpdateScNotify {
    PFKHKAMBHBN status = 1;
    uint32 JJLEDNENPJK = 3;
    uint32 BJHMFOAGMBF = 5;
    uint32 JDPHADIIAPE = 9;
    repeated GPEPGKCPBPB NNFFPJOLDHK = 11;
    JAMINGBJHBK reason = 15;
}

message RogueMagicQueryScRsp {
    uint32 retcode = 3;
    GCBCKOKEAJH PHGJIJELKDB = 6;
    CILKBJMGNGL LFLCDNGALME = 15;
}

message RogueMagicReviveAvatarScRsp {
    ItemCostData LNIEFKBMIPD = 12;
    uint32 retcode = 14;
}

message RogueMagicReviveCostUpdateScNotify {
    ItemCostData LNIEFKBMIPD = 1;
}

message RogueMagicSetAutoDressInMagicUnitScRsp {
    uint32 retcode = 4;
    bool GBEMCAHPBKP = 13;
}

message RogueMagicSettleScRsp {
    FKFOIDMNDFG BFLLJJBHLDF = 2;
    uint32 retcode = 7;
    ItemList IIOMCJPCFML = 10;
    GPHMAJPGGEK IEHPMHOFBNJ = 11;
    EEILAINOLPO IDCMACCPCBH = 12;
}

message RogueMagicStartScRsp {
    uint32 retcode = 1;
    GCBCKOKEAJH PHGJIJELKDB = 5;
    EEILAINOLPO IDCMACCPCBH = 14;
}

message RogueMagicStoryInfoUpdateScNotify {
    uint32 BNHAIKILAJK = 11;
}

message RogueMagicUnitComposeScRsp {
    uint32 retcode = 8;
}
