syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BOPOBHGDIKN {
    uint32 OBLCIENDLED = 8;
}

enum CmdRaidCollectionType {
    CmdRaidCollectionType_NLCDGIPGFDJ = 0;
    CmdRaidCollectionType_HIKIBFCIKBA = 6952;
    CmdRaidCollectionType_LNFHMGKBNEO = 6958;
    CmdRaidCollectionType_RaidCollectionDataScRsp = 6948;
    CmdRaidCollectionType_RaidCollectionEnterNextRaidScRsp = 6942;
}

message RaidCollectionDataScRsp {
    repeated BOPOBHGDIKN challenge_list = 2;
    uint32 retcode = 13;
}

message RaidCollectionEnterNextRaidScRsp {
    uint32 retcode = 8;
    GEGLJDELBHA scene = 12;
}
