syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdSummonActivityType {
    CmdSummonActivityType_NLCDGIPGFDJ = 0;
    CmdSummonActivityType_ActivitySummonModuleInitCsReq = 7570;
    CmdSummonActivityType_GetSummonActivityDataScRsp = 7561;
    CmdSummonActivityType_EnterSummonActivityStageCsReq = 7563;
    CmdSummonActivityType_EnterSummonActivityStageScRsp = 7565;
    CmdSummonActivityType_SummonActivityBattleEndScNotify = 7564;
}

message EnterSummonActivityStageCsReq {
    uint32 group_id = 7;
    uint32 DBKHHCGGKNN = 8;
    OOAJJMEGIFO NLJCJIGLGHE = 11;
    repeated OOAJJMEGIFO avatar_list = 14;
}

message EnterSummonActivityStageScRsp {
    SceneBattleInfo battle_info = 2;
    uint32 retcode = 12;
    uint32 DBKHHCGGKNN = 13;
    uint32 group_id = 15;
}

message GetSummonActivityDataScRsp {
    repeated ILHFAFGOJAC IDLCLMMAIHP = 11;
    uint32 retcode = 14;
}

message ILHFAFGOJAC {
    uint32 star = 2;
    uint32 DBKHHCGGKNN = 11;
    uint32 group_id = 15;
}

message OOAJJMEGIFO {
    uint32 avatar_id = 5;
    AvatarType avatar_type = 9;
}

message SummonActivityBattleEndScNotify {
    uint32 group_id = 1;
    uint32 round = 2;
    uint32 star = 5;
    uint32 DBKHHCGGKNN = 12;
}
