syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CBFOJHEPNHE {
    BattleEndStatus end_status = 3;
    uint32 damage_score = 4;
    uint32 stage_id = 5;
    uint32 score_id = 6;
    uint32 IMCJFGIPIFI = 7;
    uint32 BMAHOGKMPDJ = 9;
    uint32 max_score = 13;
    uint32 total_damage = 15;
}

message CEJMCEEBCOG {
    DKOPOIIBDGJ OCLJEAKLFBH = 4;
    uint32 retcode = 14;
}

enum CmdStrongChallengeActivityType {
    CmdStrongChallengeActivityType_NLCDGIPGFDJ = 0;
    CmdStrongChallengeActivityType_KPEJEKDMPDN = 6688;
    CmdStrongChallengeActivityType_EnterStrongChallengeActivityStageScRsp = 6658;
    CmdStrongChallengeActivityType_MNNOLKMBMCI = 6678;
    CmdStrongChallengeActivityType_EnterActivityStrongChallengeCsReq = 6693;
    CmdStrongChallengeActivityType_GetStrongChallengeActivityDataCsReq = 6625;
}

message DKOPOIIBDGJ {
    map<uint32, MKGHJJCPBLP> MBDBADFENPL = 15;
}

message EnterStrongChallengeActivityStageScRsp {
    uint32 retcode = 1;
    uint32 stage_id = 5;
    SceneBattleInfo battle_info = 12;
}

message FPMFICMFNGJ {
}

message MKGHJJCPBLP {
    uint32 panel_id = 2;
    uint32 CNBCDMMBCKI = 4;
    uint32 max_score = 5;
    uint32 stage_id = 6;
    NAFMBLMMAAG LMDGHCEHJCG = 13;
}

message NAFMBLMMAAG {
    repeated StrongChallengeAvatar avatar_list = 3;
    repeated uint32 buff_list = 9;
}

message StrongChallengeAvatar {
    uint32 avatar_id = 3;
    AvatarType avatar_type = 7;
}
