syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum ChangeStoryLineAction {
    ChangeStoryLineAction_None = 0;
    ChangeStoryLineAction_FinishAction = 1;
    ChangeStoryLineAction_Client = 2;
    ChangeStoryLineAction_CustomOP = 3;
    ChangeStoryLineAction_Raid = 4;
    ChangeStoryLineAction_HKFKAFPAJCO = 5;
}

message ChangeStoryLineFinishScNotify {
    uint32 ONBMNAMBIGE = 4;
    bool HBFDGEPBLNP = 6;
    ChangeStoryLineAction action = 10;
    uint32 cur_story_line_id = 12;
}

enum CmdStoryLineType {
    CmdStoryLineType_NLCDGIPGFDJ = 0;
    CmdStoryLineType_ChangeStoryLineFinishScNotify = 6281;
    CmdStoryLineType_StoryLineInfoScNotify = 6293;
    CmdStoryLineType_GetStoryLineInfoCsReq = 6225;
    CmdStoryLineType_StoryLineTrialAvatarChangeScNotify = 6286;
    CmdStoryLineType_GGCEHNECGME = 6278;
}

message GetStoryLineInfoCsReq {
}

message StoryLineInfoScNotify {
    repeated uint32 trial_avatar_id_list = 3;
    uint32 FDFLHKEDPGC = 4;
    repeated uint32 unfinished_story_line_id_list = 8;
    uint32 cur_story_line_id = 11;
}

message StoryLineTrialAvatarChangeScNotify {
    repeated uint32 EDBMIFNEHHH = 1;
    repeated uint32 ILIDIIGALKD = 2;
    bool OLPNMKAPDLP = 6;
}
