syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message BAEKEIDLDCI {
    uint32 retcode = 8;
    uint32 item_id = 11;
}

message CGFMDMPCKDN {
    uint32 item_id = 6;
}

enum CmdSpaceZooType {
    CmdSpaceZooType_NLCDGIPGFDJ = 0;
    CmdSpaceZooType_HFBJHFGODGB = 6793;
    CmdSpaceZooType_SpaceZooDeleteCatScRsp = 6713;
    CmdSpaceZooType_DPOBLEPFJDJ = 6740;
    CmdSpaceZooType_DPLPKPEFDCC = 6733;
    CmdSpaceZooType_SpaceZooBornScRsp = 6758;
    CmdSpaceZooType_SpaceZooDataScRsp = 6778;
    CmdSpaceZooType_SpaceZooOpCatteryScRsp = 6747;
    CmdSpaceZooType_SpaceZooModuleInitCsReq = 6725;
    CmdSpaceZooType_SpaceZooMutateScRsp = 6781;
    CmdSpaceZooType_SpaceZooCatUpdateNotify = 6771;
    CmdSpaceZooType_KCMOAOLIPGN = 6738;
    CmdSpaceZooType_AOJDJHDIFIP = 6788;
    CmdSpaceZooType_FMNIDGBDCDO = 6786;
    CmdSpaceZooType_GIMMMBGKIKL = 6726;
    CmdSpaceZooType_SpaceZooExchangeItemScRsp = 6739;
}

message DBLILHCLPPL {
    repeated uint32 item_list = 3;
    uint32 unique_id = 6;
    uint32 DNNCAGJIOAP = 7;
    bool PKKAJKHKBMN = 10;
    repeated uint32 DLPCPDGEADG = 11;
    uint32 BBMELNJBGAL = 12;
}

message GFFFJCEHBEB {
    uint32 BBMELNJBGAL = 7;
    uint32 HFLPDCJDIAC = 13;
}

message SpaceZooBornScRsp {
    bool HCGHLFAKIKI = 4;
    DBLILHCLPPL DLMJNMIPDCO = 6;
    uint32 retcode = 7;
    repeated GFFFJCEHBEB JKMIFNJEBJO = 12;
}

message SpaceZooCatUpdateNotify {
    bool HCGHLFAKIKI = 9;
    repeated DBLILHCLPPL HMAIHHCBFKP = 10;
    bool FHHCNGAGFCJ = 11;
}

message SpaceZooDataScRsp {
    repeated uint32 JGCNAGNOFBP = 1;
    repeated DBLILHCLPPL NFIGGHNNJAP = 2;
    repeated GFFFJCEHBEB JAPFGEAIACA = 3;
    uint32 retcode = 4;
    repeated uint32 GLMMHALPEAG = 5;
    repeated uint32 MDFEBNNOKLG = 8;
    repeated uint32 FIBMJBJMCKK = 10;
    uint32 OAIMAFOHLHC = 14;
    repeated uint32 ENGEBGICPPB = 15;
}

message SpaceZooDeleteCatScRsp {
    uint32 retcode = 9;
    repeated uint32 ANHNMANNAEP = 11;
}

message SpaceZooMutateScRsp {
    DBLILHCLPPL KIIPGCDJPBO = 9;
    repeated GFFFJCEHBEB JKMIFNJEBJO = 10;
    bool HCGHLFAKIKI = 13;
    uint32 retcode = 15;
}

message SpaceZooOpCatteryScRsp {
    repeated uint32 MDFEBNNOKLG = 5;
    uint32 retcode = 14;
}
