syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AKFBNFPFKJJ {
}

message BCPMPHNADMN {
    uint32 LMEDKDNNNKL = 1;
    repeated uint32 PGBJIJPACCE = 3;
    uint32 GMANNHPPFPK = 15;
}

enum BHJOFLJGNKN {
    BHJOFLJGNKN_NLCDGIPGFDJ = 0;
    BHJOFLJGNKN_LENEGHPPELE = 1;
    BHJOFLJGNKN_LIDKLOCCDGI = 2;
    BHJOFLJGNKN_action = 3;
    BHJOFLJGNKN_OFPLODJBGMG = 4;
    BHJOFLJGNKN_DDGDJCKKHPH = 5;
    BHJOFLJGNKN_DDBIJDILDJL = 6;
    BHJOFLJGNKN_NCLBFAALLFJ = 7;
}

message BJKPJIBNPHC {
    EJCBOKGJFHE EGBFNFCEPHD = 9;
    uint32 HFNNNGHBHGG = 11;
    uint32 DCPDNBALDOA = 15;
}

message BLJHLKBNGEC {
}

enum CmdSwordTrainingType {
    CmdSwordTrainingType_NLCDGIPGFDJ = 0;
    CmdSwordTrainingType_SwordTrainingActionTurnSettleScNotify = 7455;
    CmdSwordTrainingType_SwordTrainingLearnSkillCsReq = 7456;
    CmdSwordTrainingType_SwordTrainingResumeGameScRsp = 7488;
    CmdSwordTrainingType_AHAIINGGOGL = 7486;
    CmdSwordTrainingType_JOKIGIJPGPP = 7458;
    CmdSwordTrainingType_SwordTrainingRestoreGameScRsp = 7480;
    CmdSwordTrainingType_DDLCANIIOGE = 7494;
    CmdSwordTrainingType_SwordTrainingTurnActionScRsp = 7469;
    CmdSwordTrainingType_ELAJPNELHOB = 7484;
    CmdSwordTrainingType_MAOAAGMAEIL = 7497;
    CmdSwordTrainingType_SwordTrainingSelectEndingScRsp = 7492;
    CmdSwordTrainingType_SwordTrainingGameSettleScNotify = 7490;
    CmdSwordTrainingType_SwordTrainingDailyPhaseConfirmScRsp = 7453;
    CmdSwordTrainingType_SwordTrainingGiveUpGameScRsp = 7468;
    CmdSwordTrainingType_SwordTrainingStoryConfirmScRsp = 7463;
    CmdSwordTrainingType_SwordTrainingStoryBattleScRsp = 7454;
    CmdSwordTrainingType_SwordTrainingMarkEndingViewedScRsp = 7481;
    CmdSwordTrainingType_GIHEPFALJIM = 7500;
    CmdSwordTrainingType_SwordTrainingSetSkillTraceScRsp = 7499;
    CmdSwordTrainingType_SwordTrainingStartGameScRsp = 7485;
    CmdSwordTrainingType_SwordTrainingExamResultConfirmScRsp = 7462;
    CmdSwordTrainingType_SwordTrainingUnlockSyncScNotify = 7476;
    CmdSwordTrainingType_HHMNHFCDBON = 7479;
    CmdSwordTrainingType_NAPIPJGKKOH = 7457;
    CmdSwordTrainingType_SwordTrainingStoryConfirmCsReq = 7465;
    CmdSwordTrainingType_EnterSwordTrainingExamScRsp = 7483;
    CmdSwordTrainingType_GetSwordTrainingDataCsReq = 7473;
    CmdSwordTrainingType_HHLAMIEJMPI = 7496;
    CmdSwordTrainingType_SwordTrainingDialogueSelectOptionScRsp = 7460;
    CmdSwordTrainingType_SwordTrainingLearnSkillScRsp = 7452;
    CmdSwordTrainingType_GDJMKPJLCNP = 7498;
    CmdSwordTrainingType_SwordTrainingExamResultConfirmCsReq = 7491;
    CmdSwordTrainingType_SwordTrainingSetSkillTraceCsReq = 7461;
    CmdSwordTrainingType_GetSwordTrainingDataScRsp = 7487;
    CmdSwordTrainingType_SwordTrainingGameSyncChangeScNotify = 7459;
    CmdSwordTrainingType_PJFLGFBPJOD = 7464;
}

message DAEDLFEEGIB {
    uint32 dialogue_id = 12;
}

message ECPHOKOPKBP {
    bool IJJEGKDGKCJ = 7;
    uint32 LNAHJENGELA = 14;
}

message EINKHFKDCCD {
    BCPMPHNADMN skill_info = 1;
    LBBNBAEKGCJ GFAANLGDEOB = 4;
    HFMLKIIOGBP CLKDEHDODBB = 5;
    repeated uint32 MDBAEBENFBA = 6;
    NPGJDCIBFDD FMIGOKIDKJL = 7;
    uint32 IMGDMDDKHDL = 10;
    HCHNKKNDJCN HCEAHMKBFFK = 12;
    HFKKEDPMKKF DOBHAEAGEDG = 13;
}

enum EJCBOKGJFHE {
    EJCBOKGJFHE_NLCDGIPGFDJ = 0;
    EJCBOKGJFHE_GLANPLEGMPG = 1;
    EJCBOKGJFHE_CIGHHAKHHMN = 2;
    EJCBOKGJFHE_GAMNPOMOAIG = 3;
    EJCBOKGJFHE_KIKADFCIPJO = 4;
    EJCBOKGJFHE_NKAACMGNNPK = 5;
}

message EnterSwordTrainingExamScRsp {
    SceneBattleInfo battle_info = 5;
    uint32 retcode = 11;
}

message FBKIJNOFIAH {
    uint32 HFNNNGHBHGG = 1;
    uint32 DCPDNBALDOA = 15;
}

message FDANEJNFABF {
    uint32 progress = 12;
    uint32 id = 15;
}

message GELEHDAJMED {
    uint32 dialogue_id = 12;
}

message GFFDDJHNJPN {
    uint32 level = 1;
    uint32 queue_position = 5;
}

message GIHLNOIACIH {
    repeated FDANEJNFABF KFOFAKDPGJC = 5;
    repeated uint32 MNIIFCOOOML = 14;
}

message GIJKCHKMPJG {
    BHJOFLJGNKN source = 3;
    LJGKNFCFLLB detail = 12;
}

message GIJLACBOPEE {
    uint32 HJMEJNMAILK = 5;
    uint32 queue_position = 9;
    uint32 level = 12;
}

message GOCNLGIDBLM {
    uint32 AMNDNDNPLCA = 5;
    uint32 JALHKMEOOPN = 8;
}

message GetSwordTrainingDataCsReq {
}

message GetSwordTrainingDataScRsp {
    GIHLNOIACIH BBEKBJPHEJK = 1;
    repeated uint32 CICCAIENFGA = 2;
    EINKHFKDCCD AJGOEJHKOKE = 4;
    uint32 PABJCCKBGEB = 7;
    repeated uint32 JBJNHJNMPAP = 8;
    repeated uint32 IEPANMCFKJL = 10;
    uint32 retcode = 13;
    bool GPGIMFMGGKG = 15;
}

message HCHNKKNDJCN {
    uint32 KPJHKDOMEMJ = 8;
    repeated LBBGLAHFJKN status_list = 12;
    uint32 mood = 15;
}

message HFKKEDPMKKF {
    uint32 game_story_line_id = 13;
    repeated uint32 JBJNHJNMPAP = 14;
}

message HFMLKIIOGBP {
    repeated GFFDDJHNJPN BELEDENKGGI = 9;
}

message IEALCLFLDMP {
    repeated GOCNLGIDBLM COOMKNFDNLH = 4;
    repeated uint32 JAJNHOKCAHH = 6;
    SwordTrainingDailyPhaseType cur_phase = 12;
}

message IKGLCLFLAKO {
}

enum IPPKHOFKMHM {
    IPPKHOFKMHM_KLHMFENBDID = 0;
    IPPKHOFKMHM_JKGEFNAIMFK = 1;
    IPPKHOFKMHM_CJOADAMKIFC = 2;
    IPPKHOFKMHM_FBHDMJMLBIC = 3;
    IPPKHOFKMHM_OKCNPPPLAHM = 4;
    IPPKHOFKMHM_KPOMIPJOKND = 5;
}

message JADFEJKNOCO {
    bool JBJIKKOCNLP = 5;
    uint32 LNAHJENGELA = 14;
}

message KLNGFBHIADA {
    uint32 DGONPFLCOMO = 11;
}

message LBBGLAHFJKN {
    EJCBOKGJFHE EGBFNFCEPHD = 3;
    uint32 value = 15;
}

message LBBNBAEKGCJ {
    uint32 AFPHLNMGPHK = 686;
    oneof KKNBOACNCON {
        IEALCLFLDMP NMIJKPKNPLE = 5;
        KLNGFBHIADA FKPDOHGKJJK = 8;
    }
}

message LJGKNFCFLLB {
    oneof KKNBOACNCON {
        BJKPJIBNPHC DEIMCENJPKP = 6;
        FBKIJNOFIAH FNONLFCKDIL = 7;
        FBKIJNOFIAH CIDOEGFPHEN = 8;
        GIJLACBOPEE HANCFMMMFNF = 12;
        MCECLBDBENF LMAGJOOLKII = 10;
        JADFEJKNOCO GOLOGIHJOPF = 1;
        DAEDLFEEGIB FOGBMALOAOK = 15;
        uint32 MIFOJPGIFDD = 5;
        uint32 KPJHKDOMEMJ = 839;
        ECPHOKOPKBP KJOAIOHFFMK = 433;
        OKOJCBKENEJ GBNOIFNDPJB = 896;
        uint32 KGKJHCBMEFI = 1707;
    }
}

message MCECLBDBENF {
    LBBNBAEKGCJ turn = 4;
    uint32 IMGDMDDKHDL = 11;
}

message NPGJDCIBFDD {
    oneof KKNBOACNCON {
        BLJHLKBNGEC NGOCELLBHCF = 13;
        PJKNNJGEEBJ KNDKCOGGEKL = 1;
        GELEHDAJMED NCLBFAALLFJ = 4;
        AKFBNFPFKJJ DOCGLPKMHDM = 12;
        JADFEJKNOCO KGPMPPHJHLD = 6;
        OKOJCBKENEJ OLHMHOOMGCK = 7;
        IKGLCLFLAKO MHLPJEDILFJ = 11;
        ECPHOKOPKBP GJNINFABDBN = 8;
    }
}

message OKOJCBKENEJ {
}

message PJKNNJGEEBJ {
}

message SwordTrainingActionTurnSettleScNotify {
    repeated LBBGLAHFJKN BINKDPMJLFG = 2;
    uint32 GEAJILJKBIK = 12;
}

message SwordTrainingDailyPhaseConfirmScRsp {
    uint32 retcode = 10;
    bool KPMJOKEFLJO = 13;
}

enum SwordTrainingDailyPhaseType {
    GFEKOONGJBL_NLCDGIPGFDJ = 0;
    GFEKOONGJBL_JIMMOJHFOKE = 1;
    GFEKOONGJBL_JMCHLJLGPPD = 2;
    GFEKOONGJBL_OHDHBFKJIKL = 3;
    GFEKOONGJBL_NPJHPLIALIN = 4;
}

message SwordTrainingDialogueSelectOptionScRsp {
    uint32 retcode = 3;
}

message SwordTrainingExamResultConfirmCsReq {
}

message SwordTrainingExamResultConfirmScRsp {
    uint32 retcode = 2;
}

message SwordTrainingGameSettleScNotify {
    IPPKHOFKMHM reason = 3;
    ItemList reward = 5;
    uint32 game_story_line_id = 6;
    uint32 turn = 7;
    uint32 LBNLIJBPKHI = 8;
    repeated uint32 KACAMGJNOOB = 10;
    uint32 CDBGPMABMGM = 11;
    repeated uint32 BHFHFONGHML = 14;
}

message SwordTrainingGameSyncChangeScNotify {
    repeated GIJKCHKMPJG DGNGMJMPFGK = 11;
}

message SwordTrainingGiveUpGameScRsp {
    uint32 retcode = 7;
}

message SwordTrainingLearnSkillCsReq {
    uint32 skill_id = 11;
}

message SwordTrainingLearnSkillScRsp {
    uint32 skill_id = 7;
    uint32 retcode = 13;
}

message SwordTrainingMarkEndingViewedScRsp {
    uint32 retcode = 9;
}

message SwordTrainingRestoreGameScRsp {
    EINKHFKDCCD AJGOEJHKOKE = 7;
    uint32 retcode = 11;
}

message SwordTrainingResumeGameScRsp {
    EINKHFKDCCD AJGOEJHKOKE = 4;
    uint32 retcode = 9;
}

message SwordTrainingSelectEndingScRsp {
    uint32 PFOLEGLCLFE = 8;
    uint32 retcode = 13;
}

message SwordTrainingSetSkillTraceCsReq {
    uint32 skill_id = 10;
}

message SwordTrainingSetSkillTraceScRsp {
    uint32 skill_id = 6;
    uint32 retcode = 10;
}

message SwordTrainingStartGameScRsp {
    EINKHFKDCCD AJGOEJHKOKE = 4;
    uint32 retcode = 15;
}

message SwordTrainingStoryBattleScRsp {
    SceneBattleInfo battle_info = 3;
    uint32 retcode = 5;
}

message SwordTrainingStoryConfirmCsReq {
    uint32 LNAHJENGELA = 6;
}

message SwordTrainingStoryConfirmScRsp {
    uint32 LNAHJENGELA = 5;
    uint32 retcode = 6;
}

message SwordTrainingTurnActionScRsp {
    uint32 retcode = 4;
    repeated uint32 CCPADEMEHBA = 10;
}

message SwordTrainingUnlockSyncScNotify {
    repeated uint32 MNIIFCOOOML = 13;
    repeated FDANEJNFABF KFOFAKDPGJC = 15;
}
