syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BuyGoodsCsReq {
    uint32 goods_id = 1;
    uint32 goods_num = 4;
    repeated uint32 ALHBEKKLJKK = 6;
    uint32 shop_id = 8;
    uint32 interacted_prop_entity_id = 12;
    uint32 item_id = 14;
}

message BuyGoodsScRsp {
    uint32 goods_id = 2;
    ItemList return_item_list = 5;
    uint32 shop_id = 8;
    uint32 goods_buy_times = 10;
    uint32 retcode = 15;
}

message CityShopInfoScNotify {
    uint32 level = 1;
    uint32 shop_id = 2;
    uint64 taken_level_reward = 4;
    uint32 exp = 10;
}

enum CmdShopType {
    CmdShopType_NLCDGIPGFDJ = 0;
    CmdShopType_GetShopListScRsp = 1578;
    CmdShopType_CityShopInfoScNotify = 1586;
    CmdShopType_BuyGoodsCsReq = 1593;
    CmdShopType_OGOGLCKKCEK = 1581;
    CmdShopType_GetShopListCsReq = 1525;
    CmdShopType_BuyGoodsScRsp = 1558;
    CmdShopType_ADLEAFAAFKB = 1588;
}

message GetShopListCsReq {
    uint32 shop_type = 11;
}

message GetShopListScRsp {
    uint32 retcode = 4;
    repeated Shop shop_list = 5;
    uint32 shop_type = 6;
}

message Goods {
    int64 end_time = 1;
    uint32 goods_id = 6;
    uint32 buy_times = 7;
    uint32 item_id = 10;
    int64 begin_time = 15;
}

message Shop {
    uint32 city_level = 1;
    uint32 shop_id = 5;
    int64 end_time = 7;
    repeated Goods goods_list = 10;
    int64 begin_time = 13;
    uint32 city_exp = 14;
    uint64 city_taken_level_reward = 15;
}
