syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdSwitchHandType {
    CmdSwitchHandType_NLCDGIPGFDJ = 0;
    CmdSwitchHandType_GetSwitchHandResetGameScRsp = 8110;
    CmdSwitchHandType_SwitchHandResetGameCsReq = 8120;
    CmdSwitchHandType_GetSwitchHandDataScRsp = 8108;
    CmdSwitchHandType_SwitchHandFinishScRsp = 8117;
    CmdSwitchHandType_GFIKCCKEHJF = 8103;
    CmdSwitchHandType_SwitchHandDataCsReq = 8118;
    CmdSwitchHandType_GetSwitchHandUpdateScRsp = 8104;
    CmdSwitchHandType_GetSwitchHandResetHandPosScRsp = 8109;
    CmdSwitchHandType_EINMDLDJKNP = 8115;
    CmdSwitchHandType_SwitchHandStartScRsp = 8112;
    CmdSwitchHandType_NMFDIDGOONF = 8105;
    CmdSwitchHandType_SwitchHandFinishCsReq = 8102;
    CmdSwitchHandType_SwitchHandResetTransformCsReq = 8101;
    CmdSwitchHandType_BNGFJCFOFBH = 8111;
}

enum DDNJKAMIHHI {
    DDNJKAMIHHI_NLCDGIPGFDJ = 0;
    DDNJKAMIHHI_LJHJNDHCHJF = 1;
    DDNJKAMIHHI_HOKACNFCJAI = 2;
}

message ENHOPAHGCMA {
    uint32 config_id = 2;
    bytes DNOBAJNIGAC = 5;
    uint32 EKHEAFBKDFP = 6;
    uint32 LNGJODEPCDN = 11;
    MotionInfo IFPFJIIFALA = 12;
}

message GetSwitchHandDataScRsp {
    uint32 EBNGHIMCAPK = 1;
    repeated ENHOPAHGCMA BEADAHPGGAF = 9;
    uint32 MHKAPGBGFNO = 12;
    uint32 retcode = 15;
}

message GetSwitchHandResetGameScRsp {
    uint32 retcode = 9;
    ENHOPAHGCMA BEADAHPGGAF = 15;
}

message GetSwitchHandResetHandPosScRsp {
    uint32 retcode = 4;
    ENHOPAHGCMA BEADAHPGGAF = 10;
}

message GetSwitchHandUpdateScRsp {
    ENHOPAHGCMA BDEDDAHODII = 4;
    OENDLKLJHPF NCADGIPIALO = 11;
    uint32 retcode = 13;
}

message JAIOIENPGOD {
    uint32 LNGJODEPCDN = 7;
}

message OENDLKLJHPF {
    uint32 LKJHCMMPBDL = 1;
    uint32 IIIMCOINAOG = 4;
    DDNJKAMIHHI op_type = 6;
    uint32 group_id = 7;
}

message ONPMJJOCBMM {
    uint32 retcode = 10;
    uint32 LNGJODEPCDN = 11;
}

message SwitchHandFinishCsReq {
}

message SwitchHandFinishScRsp {
    ENHOPAHGCMA BDEDDAHODII = 11;
    uint32 retcode = 12;
}

message SwitchHandStartScRsp {
    uint32 retcode = 12;
    uint32 config_id = 14;
}
