syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum CmdStarFightType {
    CmdStarFightType_NLCDGIPGFDJ = 0;
    CmdStarFightType_GetStarFightDataScRsp = 7161;
    CmdStarFightType_StartStarFightLevelScRsp = 7165;
    CmdStarFightType_GetStarFightDataCsReq = 7170;
    CmdStarFightType_StarFightDataChangeNotify = 7164;
    CmdStarFightType_MEECLAKOPJD = 7163;
}

message EBGJAKBKPAN {
    AvatarType avatar_type = 1;
    uint32 avatar_id = 14;
}

message GetStarFightDataCsReq {
}

message GetStarFightDataScRsp {
    uint32 retcode = 7;
    repeated JFGCABMMKAB JJIDNKDKMLE = 8;
}

message JFGCABMMKAB {
    uint32 group_id = 1;
    bool NDBGPGODBPH = 4;
    uint32 EBDDDCBKPAC = 5;
    uint32 KDNBADEGDNK = 9;
    uint32 CEOEOEBOLNN = 15;
}

message StarFightDataChangeNotify {
    uint32 group_id = 11;
    JFGCABMMKAB KDKKNFGPNAB = 15;
}

message StartStarFightLevelScRsp {
    SceneBattleInfo battle_info = 3;
    uint32 retcode = 7;
    uint32 group_id = 13;
    uint32 DBKHHCGGKNN = 14;
}
