syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message AOMMAFEOBOA {
    uint32 id = 12;
    bool has_passed = 15;
}

enum CmdTarotBookType {
    CmdTarotBookType_NLCDGIPGFDJ = 0;
    CmdTarotBookType_TarotBookUnlockInteractionScRsp = 8160;
    CmdTarotBookType_TarotBookMultiOpenPackAndUnlockStoryScRsp = 8154;
    CmdTarotBookType_MFHFFDFPBGA = 8145;
    CmdTarotBookType_TarotBookModuleInitCsReq = 8158;
    CmdTarotBookType_EIDOKKFKCJE = 8149;
    CmdTarotBookType_JPMKFNJCFDA = 8143;
    CmdTarotBookType_TarotBookUnlockStoryScRsp = 8157;
    CmdTarotBookType_TarotBookOpenPackScRsp = 8152;
    CmdTarotBookType_OAIEAOHBPPL = 8147;
    CmdTarotBookType_CMECHEPAGCK = 8155;
    CmdTarotBookType_TarotBookSyncDataScNotify = 8150;
    CmdTarotBookType_TarotBookModifyEnergyScNotify = 8151;
    CmdTarotBookType_TarotBookGetDataScRsp = 8148;
    CmdTarotBookType_IDKNBAJLBAP = 8142;
    CmdTarotBookType_TarotBookFinishStoryScRsp = 8144;
    CmdTarotBookType_TarotBookFinishInteractionScRsp = 8141;
}

message GMBGLBHEFDI {
    repeated uint32 HKFDNIFACFH = 1;
    repeated uint32 FPPJGGJCJIH = 8;
}

message LIONJNJEBBF {
    uint32 id = 8;
    uint32 level = 13;
}

message OHCFIOOIKND {
    repeated AOMMAFEOBOA ILKLAJBGKKI = 4;
    repeated LIONJNJEBBF LNFCBCDNFDL = 9;
}

message TarotBookFinishInteractionScRsp {
    uint32 retcode = 4;
    uint32 INJAGFDOFEJ = 15;
}

message TarotBookFinishStoryScRsp {
    uint32 retcode = 2;
    OHCFIOOIKND BBEMIGELGJC = 4;
    uint32 LNAHJENGELA = 9;
}

message TarotBookGetDataScRsp {
    uint32 energy_info = 1;
    OHCFIOOIKND BBEMIGELGJC = 4;
    GMBGLBHEFDI interaction = 5;
    map<uint32, uint32> IMNNLHCAKML = 6;
    map<uint32, uint32> IJOJMJOMELA = 8;
    uint32 LOCEBOCJGEC = 9;
    uint32 HBLKMBHGLNO = 10;
    uint32 retcode = 14;
}

message TarotBookModifyEnergyScNotify {
    uint32 energy_info = 3;
    uint32 sub_mission_id = 8;
}

message TarotBookMultiOpenPackAndUnlockStoryScRsp {
    uint32 retcode = 1;
    uint32 HBLKMBHGLNO = 5;
    uint32 LOCEBOCJGEC = 6;
    uint32 energy_info = 10;
    OHCFIOOIKND BBEMIGELGJC = 11;
    map<uint32, uint32> IJOJMJOMELA = 12;
    repeated uint32 LNOAAOAFJJE = 13;
    map<uint32, uint32> IMNNLHCAKML = 15;
}

message TarotBookOpenPackScRsp {
    uint32 energy_info = 2;
    map<uint32, uint32> NLAANGNGAIA = 3;
    uint32 HBLKMBHGLNO = 6;
    uint32 retcode = 11;
    map<uint32, uint32> KMNLFHLINFB = 12;
    uint32 LOCEBOCJGEC = 15;
}

message TarotBookSyncDataScNotify {
    uint32 energy_info = 4;
    OHCFIOOIKND BBEMIGELGJC = 5;
    uint32 HBLKMBHGLNO = 8;
    uint32 LOCEBOCJGEC = 9;
    map<uint32, uint32> IMNNLHCAKML = 11;
    map<uint32, uint32> IJOJMJOMELA = 13;
}

message TarotBookUnlockInteractionScRsp {
    uint32 retcode = 8;
    repeated uint32 CLNOMEFFHKG = 15;
}

message TarotBookUnlockStoryScRsp {
    LIONJNJEBBF CLLIKPONHOC = 1;
    map<uint32, uint32> IJOJMJOMELA = 3;
    repeated uint32 BHFHFONGHML = 6;
    uint32 retcode = 9;
    map<uint32, uint32> IMNNLHCAKML = 12;
}
