syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message AJGLEIOGOID {
    repeated uint32 IKOKEPJGHAF = 3;
    uint32 stage_id = 7;
    uint32 IDIPBEPCIFG = 11;
    uint32 finish_time = 14;
}

message CLCOAJDPMJN {
    uint32 IDIPBEPCIFG = 1;
    repeated MBLAIDFENOE GEPKDDNJING = 2;
    uint32 finish_time = 5;
    repeated uint32 IKOKEPJGHAF = 7;
    uint32 stage_id = 8;
    bool is_win = 9;
    uint32 GEPHKCPLAJF = 10;
    uint32 retcode = 14;
}

enum CmdTeamTowersType {
    CmdTeamTowersType_NLCDGIPGFDJ = 0;
    CmdTeamTowersType_CLNPCBKKIHF = 9975;
    CmdTeamTowersType_PHIIDKGBFLO = 9957;
    CmdTeamTowersType_GHNJNKLLAAA = 9954;
    CmdTeamTowersType_MANKOBADGIF = 9959;
    CmdTeamTowersType_AHBAGOLHOKD = 9968;
}

message EABDMCJDJFA {
    uint32 level = 9;
    uint32 skill_id = 15;
}

enum GJCOFAFLAEI {
    GJCOFAFLAEI_NLCDGIPGFDJ = 0;
    GJCOFAFLAEI_NCMIMMDPHFM = 1;
    GJCOFAFLAEI_role_star = 2;
    GJCOFAFLAEI_MCMDKGEANNA = 3;
    GJCOFAFLAEI_LBGJHODBAEA = 4;
}

message GNNAEMBFINJ {
    KMAOBFIIMKF JCOBJAMPOAL = 6;
    repeated AJGLEIOGOID OHFIIBEIPJE = 7;
    uint32 retcode = 10;
    repeated EABDMCJDJFA LCOCDLIECKJ = 11;
    uint32 GEPHKCPLAJF = 13;
}

message ICLFACJDJHB {
    uint32 level = 1;
    uint32 skill_id = 8;
}

message KMAOBFIIMKF {
    repeated uint32 PICLHLCBIMP = 4;
    uint32 GEPHKCPLAJF = 11;
}

message MBLAIDFENOE {
    uint32 NCHBLJHJNID = 7;
    GJCOFAFLAEI source_type = 10;
    uint32 exp = 15;
}
