syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AAAKPGJDCFJ {
    repeated KICEGHDKACP CFHOJCBDFPE = 6;
    uint32 OOCOFCBJOJD = 7;
    uint32 DMAAMCIPPAM = 8;
    uint32 EAFFACCBAAA = 10;
    repeated uint32 HFJBMJHAHPE = 12;
    repeated LMKECAPDMAC skill_list = 15;
}

message AHHMLENLDEF {
    repeated ELBILFGFDHA EEOEFLKFNIM = 3;
    ECDINHEHKOJ KNMADMBFEDB = 4;
    BGPPDMIPDDH category = 6;
    repeated CPKCMMPFCGE LICJODMHBHA = 7;
    repeated DKIGCLFPGFO COBENBOBPKD = 8;
    CAIHACOKAJO KIOEJHHABKC = 9;
    repeated BDGGEHGLFAC JHFBMEKEMMK = 11;
    uint32 CELHPMMLHGL = 13;
    uint32 total_score = 14;
    uint32 score_id = 15;
}

message AIOCPFLCNLB {
    repeated IDBCDHIOKEG FOOMIPJJKOG = 1;
    uint32 progress = 2;
    uint32 area_id = 7;
    uint32 GKENFCLLLJC = 10;
}

message AMDOMPIGBPG {
}

message AMEJEFBKPCH {
    uint32 event_id = 4;
    repeated MDJAPHPOABA KFNMIEMBJGD = 12;
    LHLBGJLFFKK event_type = 13;
}

message AreaStepInfo {
    repeated IDBCDHIOKEG BKKLGCLOBCD = 8;
    uint32 GKENFCLLLJC = 9;
}

message BAKFOMADBCJ {
    uint32 BKPFHFGIEPE = 15;
}

message BDGGEHGLFAC {
    TrainPartyMtSkillBriefType skill_type = 6;
    uint32 KLKAIFEDLNK = 12;
    uint32 skill_id = 15;
}

enum BGPPDMIPDDH {
    BGPPDMIPDDH_IIHEIDCFALE = 0;
    BGPPDMIPDDH_ODFNPPACBCI = 1;
    BGPPDMIPDDH_ABNPBGJGAHD = 2;
    BGPPDMIPDDH_HCFKOJHOLIK = 3;
    BGPPDMIPDDH_BCDLKDKDAFH = 4;
    BGPPDMIPDDH_GIOFBNENIJM = 5;
    BGPPDMIPDDH_MKMJJPHDOBH = 6;
    BGPPDMIPDDH_KOGGGJLBHEN = 7;
    BGPPDMIPDDH_NNPJFBFILEL = 8;
}

message BHBJLGFHLHM {
    uint32 LNLOHDJIFPK = 2;
    bool DOFBGHGHDJA = 7;
    IEDLKIGJLEM EMGMFOBLAFN = 9;
    ECDINHEHKOJ KNMADMBFEDB = 10;
}

message BHOPIKPAMPJ {
    uint32 area_id = 7;
    AreaDynamicInfo OOFPPPCEIDP = 10;
}

message CAIHACOKAJO {
    repeated uint32 AEGPLACJFIO = 2;
    uint32 ODOBGIEGGEO = 5;
    ItemList ELMCGFMGILI = 6;
}

message CBJGONHJAAC {
    repeated uint32 FOOMIPJJKOG = 14;
    uint32 area_id = 15;
}

message CEFEIJFPCKE {
    repeated uint32 switch_list = 3;
    uint32 MNLAMKJIAOC = 9;
}

message CKPNGMLENFA {
    repeated uint32 LKNGKJCFFBH = 1;
}

message CNFPBAJNIEL {
    uint32 area_id = 5;
    uint32 JBEEKBJMIIA = 13;
}

message CNLAOMCKFKD {
    uint32 GDNEHLEOMOM = 2;
    uint32 param = 3;
    uint32 unique_id = 6;
    uint32 NDEBMEGNCKN = 9;
}

message CPKCMMPFCGE {
    repeated BDGGEHGLFAC PBFNPODNDID = 8;
    uint32 DDAGDNNDCDI = 10;
    uint32 unique_id = 11;
}

enum CmdTrainPartyType {
    CmdTrainPartyType_NLCDGIPGFDJ = 0;
    CmdTrainPartyType_TrainPartySyncUpdateScNotify = 8026;
    CmdTrainPartyType_NEHFOBDKJFB = 8071;
    CmdTrainPartyType_BuildingUpdateNotify = 8011;
    CmdTrainPartyType_TrainPartyEnterScRsp = 8045;
    CmdTrainPartyType_LLDOODNHAPO = 8052;
    CmdTrainPartyType_LOOFEOBBGEH = 8069;
    CmdTrainPartyType_TrainPartySetBadgeAutoFillScRsp = 8020;
    CmdTrainPartyType_TrainPartyGamePlayStartScRsp = 8021;
    CmdTrainPartyType_GEIFHOAPCIM = 8034;
    CmdTrainPartyType_GetTrainPartyDataCsReq = 8025;
    CmdTrainPartyType_TrainPartySettleNotify = 8086;
    CmdTrainPartyType_AGHNFFMFIOE = 8096;
    CmdTrainPartyType_TrainPartyHandlePendingActionScRsp = 8040;
    CmdTrainPartyType_TrainPartyTakeBuildLevelAwardScRsp = 8063;
    CmdTrainPartyType_TrainPartyGamePlaySettleNotify = 8005;
    CmdTrainPartyType_IHNEEIPCGCJ = 8048;
    CmdTrainPartyType_NPPMJELJPLP = 8015;
    CmdTrainPartyType_LJGOKPDBPMH = 8029;
    CmdTrainPartyType_EDBPKKFHMOH = 8093;
    CmdTrainPartyType_TrainPartyBuildDiyScRsp = 8004;
    CmdTrainPartyType_TrainPartyBuildSelfDisplayAreaDiyScRsp = 8018;
    CmdTrainPartyType_OBHINPCABDB = 8043;
    CmdTrainPartyType_JOIOOOFNBIC = 8084;
    CmdTrainPartyType_CDDGCNFBFMI = 8010;
    CmdTrainPartyType_TrainPartyBuildSelfDisplayAreaDiyScNotify = 8053;
    CmdTrainPartyType_TrainPartyGetDataScRsp = 8078;
    CmdTrainPartyType_TrainPartyBuildStartStepScRsp = 8038;
    CmdTrainPartyType_TrainPartyUseCardScRsp = 8058;
    CmdTrainPartyType_TrainPartyLeaveScRsp = 8065;
    CmdTrainPartyType_TrainPartyBuildRoomScNotify = 8073;
    CmdTrainPartyType_EOIGPFGGIOF = 8039;
    CmdTrainPartyType_MoveNotify = 8088;
    CmdTrainPartyType_EONAFDCGLLF = 8033;
}

message DBGHCHPONOH {
    uint32 retcode = 14;
}

message DJBJMHKMOMB {
    BGPPDMIPDDH JAPPKIFAHPH = 3;
    uint32 level = 4;
}

message DJKACFOFFAH {
    repeated ELBILFGFDHA EEOEFLKFNIM = 1;
    repeated DKIGCLFPGFO COBENBOBPKD = 7;
    uint32 OENPDHNALLA = 10;
    repeated BDGGEHGLFAC CIKDPHGPIGK = 15;
}

message DKIGCLFPGFO {
    uint32 num = 3;
    uint32 passenger_id = 8;
}

message DMFMMKJOCNJ {
    LMKECAPDMAC CBKINAFEDJC = 6;
}

message DNIAFCGKEOP {
    uint32 retcode = 8;
    uint32 buff_id = 10;
}

message DOCMDCPJIEH {
    uint32 star_num = 13;
    uint32 BHEJCEJHLIB = 14;
}

message ECDINHEHKOJ {
    uint32 GMBDHLCGOBI = 1;
    uint32 GAIEFCFBNPA = 7;
    uint32 EBENOMJDOOF = 8;
    repeated uint32 BHKJIFAFHFN = 9;
    uint32 FJONJANIOIK = 10;
    uint32 CGIGAAKLCKM = 11;
}

message ELBILFGFDHA {
    uint32 passenger_id = 4;
    uint32 GPIGNHPKFFB = 8;
    uint32 unique_id = 13;
}

message EMEEKFKDPFD {
    repeated uint32 GHPFANGEMAN = 12;
}

message EPHKIEHONGB {
    HJLECIIEKGI KAIDKOHAAGI = 5;
    uint32 IDBDBICPBBG = 7;
    AAAKPGJDCFJ NIMJPDMFBHN = 11;
    PNLLCBKLBLE HEBCOOCAHOL = 14;
    HOKCDEEABII LDAEAHOHMBB = 15;
}

message FAHBCNPNBNC {
    uint32 NLJMJCGFFMD = 11;
}

message FDDJJCFNFOJ {
    uint32 retcode = 14;
}

message FFMMFBMOBEG {
    oneof MNLCHEJKDHO {
        FAHBCNPNBNC CNGOKIKBGAJ = 1891;
        PPLKBFMCGLD LLCOCEJHKLD = 110;
        AIOCPFLCNLB MFNELHNLNGI = 684;
        DOCMDCPJIEH FHBMGFFBOLP = 725;
        NFNKNNFJILK FCKNCNDEKAE = 1269;
        CNFPBAJNIEL NEFBGMNGKBN = 1783;
        IOJLDHECLIH BJMFDAFLNEC = 231;
        BAKFOMADBCJ LCNJLPDDFEE = 1182;
        IGNNGONLFAJ FPMNNMMPOKL = 100;
        OIIPJFDNPAH ODGCBIDOGND = 1822;
    }
}

message FHLHOEPCKAG {
}

message FLPMBEPBPGN {
    repeated LMKECAPDMAC skill_list = 7;
}

message GAGGCODGDLB {
    uint32 prop_id = 3;
    int64 time = 13;
}

message GMCPCKHHPOB {
    MKIIBIMNIGK src = 4;
    oneof MNLCHEJKDHO {
        IEDLKIGJLEM EMGMFOBLAFN = 1049;
        HBACEFIACOI BEEMEFMJEAA = 1178;
        HPAGFCCNCHE BPNEOPLHEBK = 1432;
        MJMPOLBBFNA OEDJEOAECAC = 1139;
        MEDCHLCIOEI JPBBDGJBHKN = 1877;
        DMFMMKJOCNJ CNLGPLJFMKA = 146;
        BHBJLGFHLHM BELKGEJFOIF = 1321;
        FLPMBEPBPGN EFJKKFNNCGN = 609;
        MGOLOIGOAMB KEOOMCJAHMG = 1998;
        EMEEKFKDPFD HOHNMNGNCMG = 1852;
    }
}

message HBACEFIACOI {
    repeated LMAKFCIHCMA EBAIMMGLGFO = 11;
}

message HELJNONBKPH {
    int64 expire_time = 2;
    uint32 EIKLMFPMJJD = 8;
}

message HJLECIIEKGI {
    uint32 queue_position = 13;
    oneof FGLIODAJFML {
        AMEJEFBKPCH KLONPDNKBJF = 628;
        OGAFHKMJELA AKDJGIJMHPJ = 668;
        JEBGFIJPAPG LGBJDFHBIND = 1733;
    }
}

message HLNFNACOFFF {
    repeated CEFEIJFPCKE DICAIJCHICB = 2;
    uint32 KHFHCLBHAPD = 5;
    repeated KICEGHDKACP CFHOJCBDFPE = 6;
}

message HOKCDEEABII {
    ECDINHEHKOJ KNMADMBFEDB = 1;
    uint32 FJPEIFMFPAN = 4;
    uint32 IDCJPIJHNCL = 11;
    repeated CNLAOMCKFKD IEDKELDFHLP = 13;
}

message HPAGFCCNCHE {
    HJLECIIEKGI FMIGOKIDKJL = 15;
}

message IAKFBFJCHFB {
    uint32 EAFFACCBAAA = 8;
    uint32 unique_id = 11;
    uint32 card_id = 12;
}

message IBNCBEPCAPF {
}

message IDBCDHIOKEG {
    JIIEHEBIBMO status = 9;
    uint32 DNLIGEOFPEL = 11;
}

message IEDLKIGJLEM {
    repeated IAKFBFJCHFB LONFKFCFDND = 2;
}

message IGNNGONLFAJ {
    repeated CBJGONHJAAC area_list = 3;
}

message IOJLDHECLIH {
    uint32 diy_dynamic_id = 3;
    int64 time = 8;
}

message JCPMKHCPCPN {
    uint32 DMJGCIIBPJK = 5;
    uint32 GPIGNHPKFFB = 13;
}

message JEBGFIJPAPG {
    repeated LMKECAPDMAC PBLDCDDFKIE = 8;
    uint32 JGHCFCGEIEO = 12;
}

enum JIIEHEBIBMO {
    JIIEHEBIBMO_CIJCGPBOFJP = 0;
    JIIEHEBIBMO_BHPKNHCHOJF = 1;
    JIIEHEBIBMO_HEIMDAGNDLO = 2;
    JIIEHEBIBMO_MJHBDAKIJDP = 3;
}

message KDBJBEJPGOO {
    repeated LMKECAPDMAC skill_list = 15;
}

message KICEGHDKACP {
    uint32 FPKJONKIFLI = 7;
    JCPMKHCPCPN GNBKDCHLDGL = 12;
    uint32 passenger_id = 15;
}

enum LHLBGJLFFKK {
    LHLBGJLFFKK_KGHKHLKDEBK = 0;
    LHLBGJLFFKK_AKGDAFFKANP = 1;
    LHLBGJLFFKK_KNJDGIMKJME = 2;
    LHLBGJLFFKK_DODHMJBMHAF = 3;
}

message LMAKFCIHCMA {
    JCPMKHCPCPN GNBKDCHLDGL = 7;
    uint32 passenger_id = 13;
}

message LMKECAPDMAC {
    uint32 max_level = 6;
    uint32 skill_id = 9;
    uint32 skill_level = 13;
}

message MDJAPHPOABA {
    bool is_selected = 2;
    uint32 HAFOKMHCGFM = 3;
}

message MDOIMCNFDLC {
    uint32 event_id = 12;
}

message MEDCHLCIOEI {
    repeated CNLAOMCKFKD IEDKELDFHLP = 13;
}

message MGOLOIGOAMB {
    TrainPartyPassenger IALIECEAFJB = 5;
}

message MJMPOLBBFNA {
    uint32 EAFFACCBAAA = 1;
}

enum MKIIBIMNIGK {
    MKIIBIMNIGK_EFBKDLIJKAG = 0;
    MKIIBIMNIGK_MGFHDNJAKKM = 1;
    MKIIBIMNIGK_NGAAHFBKMFM = 2;
    MKIIBIMNIGK_EBJCJAJDINC = 3;
    MKIIBIMNIGK_IDMGAGLJMLK = 4;
    MKIIBIMNIGK_IPFPPCLNIHO = 5;
}

message MOCNDOCEOJM {
    repeated uint32 LKNGKJCFFBH = 14;
}

message NFNKNNFJILK {
    uint32 IOJOIOHIEAB = 2;
}

message OGAFHKMJELA {
    uint32 total_score = 2;
    uint32 reach_point = 7;
    uint32 CLMFKHAJKLH = 9;
    repeated DKIGCLFPGFO COBENBOBPKD = 10;
    uint32 CELHPMMLHGL = 11;
    uint32 OENPDHNALLA = 12;
    repeated DJBJMHKMOMB JPOOHONHFJI = 14;
    repeated ELBILFGFDHA EEOEFLKFNIM = 15;
}

message OLBKADIKIGL {
    HLNFNACOFFF CBFPJAJAKGI = 14;
}

message PFAIANENDEE {
    uint32 BFPAFELCMGF = 6;
}

message PNLLCBKLBLE {
    IEDLKIGJLEM LONFKFCFDND = 4;
    uint32 LNLOHDJIFPK = 8;
    bool DOFBGHGHDJA = 14;
}

message PPLKBFMCGLD {
    repeated IDBCDHIOKEG FOOMIPJJKOG = 6;
    uint32 BPGBEEOHPLJ = 7;
}

message TrainPartyArea {
    repeated AreaDynamicInfo dynamic_info = 1;
    AreaStepInfo area_step_info = 3;
    repeated uint32 verify_step_id_list = 8;
    uint32 progress = 11;
    uint32 area_id = 13;
    repeated uint32 step_id_list = 14;
    repeated uint32 static_prop_id_list = 15;
}

message TrainPartyBuildDiyScRsp {
    uint32 area_id = 5;
    uint32 retcode = 9;
    repeated BHOPIKPAMPJ JKPJFKCBIEM = 10;
}

message TrainPartyBuildRoomScNotify {
    TrainPartyInfo CPMHKECPBOJ = 9;
}

message TrainPartyBuildSelfDisplayAreaDiyScNotify {
    TrainPartyInfo train_party_data = 2;
}

message TrainPartyBuildSelfDisplayAreaDiyScRsp {
    OIIPJFDNPAH ACLKMFCDMED = 1;
    uint32 retcode = 4;
}

message TrainPartyBuildStartStepScRsp {
    uint32 cur_fund = 1;
    uint32 retcode = 4;
}

message TrainPartyData {
    TrainPartyInfo train_party_info = 6;
    EPHKIEHONGB HCJJPLKELGC = 7;
    uint32 record_id = 8;
    TrainPartyPassengerInfo passenger_info = 9;
    uint32 unlock_area_num = 11;
    bool LNMFDPFOKFF = 15;
}

message TrainPartyGamePlaySettleNotify {
    TrainPartyPassengerInfo ENBJCMPCMLK = 3;
    uint32 unlock_area_num = 6;
    repeated uint32 CEJPCMHEEMN = 10;
    uint32 record_id = 12;
}

message TrainPartyGamePlayStartScRsp {
    EPHKIEHONGB FJKHJADDKLD = 7;
    uint32 retcode = 13;
}

message TrainPartyGetDataScRsp {
    TrainPartyData train_party_data = 7;
    uint32 retcode = 9;
}

message TrainPartyHandlePendingActionScRsp {
    uint32 queue_position = 1;
    HLNFNACOFFF CBFPJAJAKGI = 7;
    uint32 retcode = 11;
    bool HMNAOPOKLGE = 14;
    oneof KILBFAAFDPD {
        OLBKADIKIGL EEBFCLFOBPG = 1482;
        KDBJBEJPGOO OMLNCJEGJAC = 1711;
        AHHMLENLDEF BHMJDNEOBNK = 744;
        DJKACFOFFAH IGMEPOBLFFB = 1305;
    }
}

message TrainPartyInfo {
    uint32 star_num = 1;
    repeated GAGGCODGDLB MHABCMLHCGD = 2;
    uint32 JJGKIPDGOGP = 4;
    uint32 BHEJCEJHLIB = 5;
    repeated TrainPartyArea area_list = 6;
    repeated HELJNONBKPH FOOPKFCIHBA = 7;
    uint32 BKPFHFGIEPE = 8;
    OIIPJFDNPAH CMCNNJKJNPK = 11;
    uint32 cur_fund = 14;
    bool IEEAPCFKOJC = 15;
}

enum TrainPartyMtSkillBriefType {
    ANMELOCBHGK_ODCHAJHNFDF = 0;
    ANMELOCBHGK_ENDBHCELNKL = 1;
    ANMELOCBHGK_AMFLHLKGLFL = 2;
    ANMELOCBHGK_ECPMEDNEOGE = 3;
    ANMELOCBHGK_NHLNOHDCPHH = 4;
}

message TrainPartyPassenger {
    uint32 record_id = 1;
    bool JGDNJOFHCNC = 2;
    uint32 passenger_id = 8;
    repeated uint32 GHPFANGEMAN = 12;
}

message TrainPartyPassengerInfo {
    repeated TrainPartyPassenger passenger_info_list = 12;
    repeated uint32 GHPFANGEMAN = 14;
}

message TrainPartySetBadgeAutoFillScRsp {
    bool PELJACANAFH = 2;
    uint32 retcode = 13;
}

message TrainPartySettleNotify {
    uint32 FGIHKKKOGJD = 6;
    HLNFNACOFFF CBFPJAJAKGI = 12;
}

message TrainPartySyncUpdateScNotify {
    repeated GMCPCKHHPOB JKPJFKCBIEM = 13;
}

message TrainPartyTakeBuildLevelAwardScRsp {
    uint32 retcode = 7;
    uint32 FPHFHCGNNGM = 8;
    ItemList item_list = 12;
}

message TrainPartyUseCardScRsp {
    uint32 retcode = 1;
    uint32 FGIHKKKOGJD = 5;
}
