syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AKGFMPCFOOK {
    KJMKOJEHMII EDLLNJIEFBO = 9;
    uint32 retcode = 14;
}

message BAHMABONKBP {
    uint32 EPLJKOLIPCI = 2;
    uint32 DCIJEFMACME = 4;
    uint64 unique_id = 7;
    int32 APHMBADNMPH = 8;
    uint32 item_id = 11;
    uint32 rotation = 14;
    int32 KNKFPENAPBF = 15;
}

enum CmdTravelBrochureType {
    CmdTravelBrochureType_NFDNDMDGICK = 0;
    CmdTravelBrochureType_TravelBrochurePageUnlockScNotify = 6493;
    CmdTravelBrochureType_TravelBrochurePageResetScRsp = 6445;
    CmdTravelBrochureType_OIIPPCADMJL = 6436;
    CmdTravelBrochureType_TravelBrochureRemovePasterScRsp = 6413;
    CmdTravelBrochureType_TravelBrochureSelectMessageScRsp = 6481;
    CmdTravelBrochureType_EPAJNBOJIDC = 6426;
    CmdTravelBrochureType_TravelBrochureApplyPasterListScRsp = 6465;
    CmdTravelBrochureType_MKAGOFKLIDL = 6488;
    CmdTravelBrochureType_TravelBrochureGetPasterScNotify = 6433;
    CmdTravelBrochureType_GFIPKGHIEFA = 6448;
    CmdTravelBrochureType_TravelBrochureGetDataScRsp = 6478;
    CmdTravelBrochureType_FDJFMFOABGH = 6471;
    CmdTravelBrochureType_EJAPHKDGPPF = 6469;
    CmdTravelBrochureType_KIAFALEPDON = 6425;
    CmdTravelBrochureType_BMCNHNBAMEG = 6404;
    CmdTravelBrochureType_MMKKFKILNHC = 6411;
    CmdTravelBrochureType_TravelBrochureUpdatePasterPosScRsp = 6440;
    CmdTravelBrochureType_NIBHBJGPMKG = 6439;
}

message DDHIIJAJIOO {
    uint32 num = 3;
}

message DEDKIIFNECM {
    uint32 item_id = 1;
    uint32 EPLJKOLIPCI = 3;
    uint32 rotation = 4;
    int32 KNKFPENAPBF = 11;
    int32 APHMBADNMPH = 12;
}

message FPGBALIKPDE {
    uint32 retcode = 4;
}

message GNILAAACODB {
    uint64 unique_id = 5;
    uint32 DCIJEFMACME = 11;
    uint32 item_id = 15;
}

message HPGIGEEAGHL {
    uint32 value = 6;
}

message IDNIEAKJMCF {
    uint32 retcode = 13;
    KJMKOJEHMII EDLLNJIEFBO = 14;
}

message KJMKOJEHMII {
    OFLKOBJHFKH BEANBFLJELP = 2;
    uint32 DCIJEFMACME = 4;
    repeated NGIOBCJINOG LFDLFDDEACA = 6;
    OLBNNJKCMAI PFOLIDBBHJN = 11;
    uint32 CFCICBNEOJB = 13;
}

message MLADIJBBLPN {
    uint32 retcode = 7;
}

message NGIOBCJINOG {
    int32 KNKFPENAPBF = 2;
    uint32 rotation = 3;
    int32 APHMBADNMPH = 4;
    uint32 EPLJKOLIPCI = 10;
    uint64 unique_id = 11;
    uint32 item_id = 15;
}

enum OFLKOBJHFKH {
    OFLKOBJHFKH_CHDLPMPJLOJ = 0;
    OFLKOBJHFKH_IFEOKEGHLBL = 1;
    OFLKOBJHFKH_MDGOCIEKFJB = 2;
}

message OHMIEPPCKBJ {
    uint32 DCIJEFMACME = 1;
    OFLKOBJHFKH DEBPJKJGCIE = 11;
}

enum OLBNNJKCMAI {
    OLBNNJKCMAI_NJBGKCIGOJE = 0;
    OLBNNJKCMAI_GPNIFHBEHNB = 1;
    OLBNNJKCMAI_KCEHIDFLKLM = 2;
}

message TravelBrochureApplyPasterListScRsp {
    uint32 retcode = 1;
    KJMKOJEHMII EDLLNJIEFBO = 15;
}

message TravelBrochureGetDataScRsp {
    uint32 custom_value = 4;
    map<uint32, uint32> NNIDCBOKHFK = 7;
    map<uint32, KJMKOJEHMII> HJNJNFIBMEL = 10;
    uint32 retcode = 12;
}

message TravelBrochurePageResetScRsp {
    KJMKOJEHMII EDLLNJIEFBO = 12;
    uint32 retcode = 14;
}

message TravelBrochurePageUnlockScNotify {
    uint32 DCIJEFMACME = 6;
}

message TravelBrochureSelectMessageScRsp {
    uint32 retcode = 3;
    KJMKOJEHMII EDLLNJIEFBO = 8;
    ItemList reward = 9;
}
