syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message CBIKIIMGKHH {
    uint32 avatar_id = 12;
    AvatarType avatar_type = 13;
}

enum CmdTelevisionActivityType {
    CmdTelevisionActivityType_NLCDGIPGFDJ = 0;
    CmdTelevisionActivityType_ActivityTelevisionModuleInitCsReq = 6978;
    CmdTelevisionActivityType_EnterTelevisionActivityStageCsReq = 6972;
    CmdTelevisionActivityType_EnterTelevisionActivityStageScRsp = 6962;
    CmdTelevisionActivityType_GetTelevisionActivityDataScRsp = 6968;
    CmdTelevisionActivityType_TelevisionActivityBattleEndScNotify = 6977;
}

message EnterTelevisionActivityStageCsReq {
    uint32 KKNGIFOJLGJ = 7;
    repeated uint32 buff_list = 10;
    repeated CBIKIIMGKHH avatar_list = 14;
}

message EnterTelevisionActivityStageScRsp {
    uint32 retcode = 3;
    uint32 KKNGIFOJLGJ = 7;
    SceneBattleInfo battle_info = 11;
}

message GetTelevisionActivityDataScRsp {
    repeated PAAIMLDHJCI AKDFABDHHIO = 6;
    uint32 retcode = 15;
}

message PAAIMLDHJCI {
    uint32 NELOAKJAABI = 4;
    uint32 max_score = 5;
    uint32 KKNGIFOJLGJ = 12;
}

message TelevisionActivityBattleEndScNotify {
    uint32 turn_left = 1;
    uint32 round_score = 3;
    uint32 AAJFIPMBMHC = 6;
    PAAIMLDHJCI GBHAIBBFPHJ = 8;
    uint32 total_score = 12;
}
