syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

enum ACKPCFFEMHB {
    ACKPCFFEMHB_NLCDGIPGFDJ = 0;
    ACKPCFFEMHB_GGEOGCBGEIH = 1;
    ACKPCFFEMHB_CNPNACJBHJG = 2;
}

enum CFCPOEDPPKB {
    CFCPOEDPPKB_ABECLEIGDEF = 0;
    CFCPOEDPPKB_CINLJPPIINL = 1;
    CFCPOEDPPKB_CHBNBPFIJPG = 2;
}

enum CmdTrainVisitorType {
    CmdTrainVisitorType_NLCDGIPGFDJ = 0;
    CmdTrainVisitorType_GGFOFBFAEIN = 3793;
    CmdTrainVisitorType_TrainRefreshTimeNotify = 3788;
    CmdTrainVisitorType_TrainVisitorBehaviorFinishScRsp = 3778;
    CmdTrainVisitorType_GJBHPGPAGKJ = 3740;
    CmdTrainVisitorType_AMDHGJKALDO = 3758;
    CmdTrainVisitorType_GetTrainVisitorRegisterCsReq = 3786;
    CmdTrainVisitorType_TrainVisitorRewardSendNotify = 3781;
    CmdTrainVisitorType_PJMKLBEMCBG = 3771;
    CmdTrainVisitorType_CCDCHACIAOE = 3725;
    CmdTrainVisitorType_GetTrainVisitorRegisterScRsp = 3747;
    CmdTrainVisitorType_NPDGBECOIIE = 3726;
    CmdTrainVisitorType_TakeTrainVisitorBehaviorRewardScRsp = 3713;
}

message DEFFFLGJAEM {
    uint32 DOOACEHOPEE = 6;
    bool is_meet = 7;
}

message EIDKOEHEAAA {
    repeated DEFFFLGJAEM LPOLKFNCEAB = 3;
    uint32 retcode = 11;
}

message GetTrainVisitorRegisterCsReq {
    ACKPCFFEMHB type = 6;
}

message GetTrainVisitorRegisterScRsp {
    uint32 retcode = 1;
    repeated uint32 BLKHPCPALDN = 6;
    repeated MNKGDKAIELH NEDBIFJPBDJ = 15;
}

message MNKGDKAIELH {
    repeated uint32 HBGLEOAJJGE = 2;
    uint32 DOOACEHOPEE = 5;
    TrainVisitorStatus status = 6;
    uint32 IMHLMHKOPLD = 8;
    bool LHNHMFEKNDJ = 13;
}

message OBICGCEFCCI {
    uint32 retcode = 5;
}

message TakeTrainVisitorBehaviorRewardScRsp {
    uint32 DOOACEHOPEE = 8;
    uint32 retcode = 12;
    repeated uint32 HBGLEOAJJGE = 14;
}

message TrainRefreshTimeNotify {
    uint64 IAMKNFKCLCH = 10;
}

message TrainVisitorBehaviorFinishScRsp {
    uint32 retcode = 3;
    ItemList reward = 9;
    uint32 DOOACEHOPEE = 12;
}

message TrainVisitorRewardSendNotify {
    CFCPOEDPPKB type = 7;
    uint32 DOOACEHOPEE = 8;
    ItemList reward = 10;
}

enum TrainVisitorStatus {
    LDMCCFPAPOL_NLCDGIPGFDJ = 0;
    LDMCCFPAPOL_KPJGDHLENIP = 1;
    LDMCCFPAPOL_PGAACLCKFFO = 2;
    LDMCCFPAPOL_FBAEFCEPHHI = 3;
    LDMCCFPAPOL_HKMJGGPKGIM = 4;
}
