syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BFAKMCIJFCB {
    repeated IIONNFELFEF PKMHMGAEAGO = 1;
    repeated HJACHMJFEAH PNHLAAMNGFE = 2;
    BOMHOLBACKF GLOGEMFDMJG = 3;
}

message BODEMOLDHAA {
    uint32 teleport_id = 11;
}

enum BOMHOLBACKF {
    BOMHOLBACKF_HGLIFJGHADE = 0;
    BOMHOLBACKF_PDJAJHELPKL = 1;
}

message BPJMEGHIEIN {
    ItemList reward = 5;
    uint32 ONOHPMDGNNH = 9;
    uint32 retcode = 12;
    bool JMAODNEONPF = 15;
}

enum CmdTrainCakeCatchType {
    CmdTrainCakeCatchType_NLCDGIPGFDJ = 0;
    CmdTrainCakeCatchType_OAFHNCOANPE = 9715;
    CmdTrainCakeCatchType_EHGILHHDKHF = 9740;
    CmdTrainCakeCatchType_BOIAJPMHPML = 9668;
    CmdTrainCakeCatchType_GCNJHGHPHDG = 9683;
    CmdTrainCakeCatchType_TrainCakeCatchOpenBoxScRsp = 9718;
    CmdTrainCakeCatchType_AFAKIKMICOF = 9767;
    CmdTrainCakeCatchType_APDHJHHIMOF = 9642;
    CmdTrainCakeCatchType_TrainCakeCatchDiyScRsp = 9658;
    CmdTrainCakeCatchType_PBPPLEDIMGH = 9753;
    CmdTrainCakeCatchType_AEFOHGJHOMB = 9713;
    CmdTrainCakeCatchType_SocialPlayTalkScRsp = 9628;
    CmdTrainCakeCatchType_NMEHFLHCOJI = 9747;
    CmdTrainCakeCatchType_PJPMBFIMNJB = 9653;
    CmdTrainCakeCatchType_SocialPlayQueryRecentVisitorsScRsp = 9725;
    CmdTrainCakeCatchType_TrainCakeCatchGetDataScRsp = 9686;
    CmdTrainCakeCatchType_TrainCakeCatchDiyLikeScRsp = 9659;
    CmdTrainCakeCatchType_BPOBPOPNPNL = 9666;
    CmdTrainCakeCatchType_CFAOJOLPOPG = 9661;
    CmdTrainCakeCatchType_SocialPlaySettingInfoScNotify = 9639;
    CmdTrainCakeCatchType_NJNHJOFFHHC = 9662;
    CmdTrainCakeCatchType_TrainCakeCatchDataScNotify = 9695;
    CmdTrainCakeCatchType_JLBBKGOMCDE = 9671;
    CmdTrainCakeCatchType_SocialPlayRoomPlayerMoveScNotify = 9644;
    CmdTrainCakeCatchType_SocialPlayPreCheckEnterRoomScRsp = 9699;
    CmdTrainCakeCatchType_TrainCakeCatchSearchScRsp = 9672;
    CmdTrainCakeCatchType_SocialPlayGameplayOperationScNotify = 9765;
}

message DJIHNCHDFED {
    uint32 retcode = 15;
}

message HHJLCGGEHPB {
    PlayerSimpleInfo CILGIDDHODG = 1;
    uint32 PLPPPCEPBDO = 4;
    int64 KFACPOBAAGM = 13;
}

message HJACHMJFEAH {
    uint32 PCPDHEIEJFO = 1;
    uint32 slot = 2;
}

message HMACEHDGGHB {
    repeated IKAHKMNCFDN BJPHDKEBOBK = 1;
    uint32 HBKEPFKDAMI = 2;
    int64 CMHKFNFKGOI = 3;
}

message IIONNFELFEF {
    uint32 dice_slot_id = 1;
    uint32 pose = 2;
    repeated uint32 DMIOBEKLDED = 3;
}

message IKAHKMNCFDN {
    uint32 PCPDHEIEJFO = 1;
    uint32 slot = 2;
}

message IKBDJLNEPBH {
    repeated PEEEEGAPCOK HFLOPHNBKGN = 1;
}

message JBJNJPAOCDA {
    uint32 summoned_pet_id = 1;
    JOLAHHGIFHA NJDCPMENIFG = 3;
    uint32 uid = 6;
    int64 AIMNJIMDIKM = 7;
    bool OJPDDAOJJKC = 8;
    PlayerSimpleInfo AJIPBLCIONL = 12;
}

message JGAMELLGLGE {
    JOLAHHGIFHA NJDCPMENIFG = 7;
}

message JKILAALMFIB {
    uint32 retcode = 3;
}

message JOFHMCJPBCE {
    uint32 count = 4;
    uint32 PCPDHEIEJFO = 12;
}

message JOLAHHGIFHA {
    Vector pos = 1;
    Vector rot = 2;
    float ICNANKMDJIC = 3;
    Vector GHMKFMBDKNE = 4;
    float GHEMGLKGKLC = 5;
    uint32 FPHBEHJJBIA = 6;
    bool MGIOLDGHPMA = 7;
    int64 time_stamp = 8;
}

message JPAOIPLDKHB {
    repeated IKAHKMNCFDN BJPHDKEBOBK = 1;
    BFAKMCIJFCB NLJBJMDPBGN = 2;
    int64 DBIKJPDBMOE = 3;
    int64 CMHKFNFKGOI = 4;
    uint32 HBKEPFKDAMI = 5;
    uint32 GAEKEFEKCBD = 6;
}

message KKACLNNMMAM {
    bool JMAODNEONPF = 3;
    repeated uint32 BPAOGJPLENJ = 14;
}

enum MFPDAKOIOED {
    MFPDAKOIOED_KCOCMMIACMB = 0;
    MFPDAKOIOED_FLMPFOFPAGB = 1;
}

message MHNNEFBOPIE {
    uint32 op_uid = 1;
    repeated JOLAHHGIFHA JENKGODEIOM = 2;
}

message MIKGMGBHLEN {
    oneof IBANGBLDNIG {
        string message_text = 1;
        uint32 extra_id = 2;
    }
}

message ONAADAJBLEB {
    int64 DBIKJPDBMOE = 7;
    uint32 ONOHPMDGNNH = 10;
}

message PBMDEBCGNMD {
    MNCBEDBDDHL IKJNIKIGFLF = 6;
    uint32 DLKOEIANIMK = 7;
    JPAOIPLDKHB PKHFMJDNKOE = 11;
}

message PEEEEGAPCOK {
    uint32 PLPPPCEPBDO = 1;
    uint32 op_uid = 2;
    uint32 OOCPKIGPEHP = 3;
    int64 CMIEOOODDIA = 4;
    string AALDPOAKJBK = 5;
}

message PJFIMFJPMCN {
    repeated uint32 LPDFMJPFGJH = 2;
    uint32 PCPDHEIEJFO = 7;
}

message POBLGKIGINE {
    uint32 room_owner_uid = 4;
    repeated JBJNJPAOCDA player_info = 9;
    PBMDEBCGNMD LNMGOFCOMED = 39;
}

message SocialPlayGameplayOperationScNotify {
    uint32 room_owner_uid = 7;
    uint32 op_uid = 15;
    oneof NBGBONGLJHM {
        uint32 LMGGGLECNEA = 914;
        JBJNJPAOCDA GNLAECODENP = 1883;
        POBLGKIGINE LMFMBJCNALJ = 1621;
        uint32 HJHPHDACEHE = 849;
        BFAKMCIJFCB OEMEKBOGNJH = 832;
        HMACEHDGGHB ONMNMLBANHK = 1786;
        MIKGMGBHLEN PHKCDLPHMPA = 1794;
        POBLGKIGINE LABNNEGJNHO = 1625;
        int64 DBIKJPDBMOE = 557;
        IKBDJLNEPBH IMPBCBPIFAG = 799;
        uint32 BJLCBAAKPDI = 1359;
        uint32 DLKOEIANIMK = 1834;
    }
}

message SocialPlayPreCheckEnterRoomScRsp {
    uint32 retcode = 8;
    int64 CMHKFNFKGOI = 15;
}

message SocialPlayQueryRecentVisitorsScRsp {
    repeated HHJLCGGEHPB recent_visitor_list = 4;
    uint32 retcode = 8;
}

message SocialPlayRoomPlayerMoveScNotify {
    MHNNEFBOPIE JENKGODEIOM = 5;
    uint32 op_uid = 8;
    uint32 room_owner_uid = 14;
}

message SocialPlaySettingInfoScNotify {
    JPGACKPLGCD BOHGFDFBLEN = 13;
}

message SocialPlayTalkScRsp {
    int64 end_time = 11;
    uint32 retcode = 13;
    MIKGMGBHLEN PHKCDLPHMPA = 15;
}

message TrainCakeCatchDataScNotify {
    repeated uint32 performance_id_list = 10;
    repeated JOFHMCJPBCE NIELDCLPOLA = 14;
}

message TrainCakeCatchDiyLikeScRsp {
    uint32 retcode = 4;
    repeated uint32 BPAOGJPLENJ = 8;
}

message TrainCakeCatchDiyScRsp {
    BFAKMCIJFCB NLJBJMDPBGN = 2;
    uint32 retcode = 14;
}

message TrainCakeCatchGetDataScRsp {
    uint32 retcode = 1;
    bool OJPDDAOJJKC = 2;
    repeated uint32 performance_id_list = 3;
    BFAKMCIJFCB NLJBJMDPBGN = 7;
    KKACLNNMMAM JIELLGELABA = 8;
    ONAADAJBLEB NAIFOMCLGLN = 9;
    repeated IKAHKMNCFDN BJPHDKEBOBK = 10;
    POBLGKIGINE DJMHHMMABJL = 11;
    repeated PJFIMFJPMCN CEMFBJPOLNP = 13;
    int64 CMHKFNFKGOI = 14;
    repeated JOFHMCJPBCE NIELDCLPOLA = 15;
}

message TrainCakeCatchOpenBoxScRsp {
    uint32 retcode = 3;
    int64 CMHKFNFKGOI = 4;
    repeated IKAHKMNCFDN BJPHDKEBOBK = 14;
}

message TrainCakeCatchSearchScRsp {
    repeated uint32 GINENNKGDMG = 3;
    uint32 PCPDHEIEJFO = 6;
    JOFHMCJPBCE NIELDCLPOLA = 7;
    uint32 retcode = 8;
    repeated PJFIMFJPMCN CEMFBJPOLNP = 10;
}
