syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdTrackPhotoActivityType {
    CmdTrackPhotoActivityType_NLCDGIPGFDJ = 0;
    CmdTrackPhotoActivityType_StartTrackPhotoStageScRsp = 7556;
    CmdTrackPhotoActivityType_GetTrackPhotoActivityDataCsReq = 7560;
    CmdTrackPhotoActivityType_SettleTrackPhotoStageScRsp = 7555;
    CmdTrackPhotoActivityType_GetTrackPhotoActivityDataScRsp = 7551;
    CmdTrackPhotoActivityType_NOHJMHABGPF = 7559;
    CmdTrackPhotoActivityType_KOHIOJDEEPP = 7554;
    CmdTrackPhotoActivityType_LPMCPJPLCGP = 7553;
    CmdTrackPhotoActivityType_OKGOCHLFHAK = 7552;
}

message EGIJMPCIJOG {
    uint32 stage_id = 9;
}

message GetTrackPhotoActivityDataCsReq {
}

message GetTrackPhotoActivityDataScRsp {
    repeated IFBJJJOBGHB PEDCKGNNPAJ = 6;
    uint32 retcode = 12;
}

message IFBJJJOBGHB {
    uint32 stage_id = 3;
    uint32 max_score = 14;
}

message IGKBMLELJDH {
    uint32 retcode = 5;
}

message PNICDFFMDDB {
    bool ADGCOJLMGAH = 8;
    uint32 entity_id = 12;
}

message SettleTrackPhotoStageScRsp {
    uint32 stage_id = 1;
    uint32 retcode = 6;
    uint32 score_id = 9;
    repeated PNICDFFMDDB PIGLHELGMIJ = 15;
}

message StartTrackPhotoStageScRsp {
    uint32 trans_no = 3;
    uint32 retcode = 10;
}
