syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdTextJoinType {
    CmdTextJoinType_NLCDGIPGFDJ = 0;
    CmdTextJoinType_HEENPFACDCA = 3888;
    CmdTextJoinType_JLAEJCGNFBK = 3893;
    CmdTextJoinType_CCMGEHOGJIM = 3878;
    CmdTextJoinType_IPONEPLMCBI = 3825;
    CmdTextJoinType_TextJoinQueryScRsp = 3858;
    CmdTextJoinType_TextJoinBatchSaveScRsp = 3881;
}

message JCDNAGMDELF {
    uint32 PAIPJMKCCEH = 1;
    uint32 HPCIKHIBFHD = 7;
    string ANEGIMPIEHL = 9;
}

message OGFBEAPMGJM {
    uint32 retcode = 3;
}

message TextJoinBatchSaveScRsp {
    repeated JCDNAGMDELF HPEDOFFJKKP = 2;
    uint32 retcode = 15;
}

message TextJoinQueryScRsp {
    repeated JCDNAGMDELF HPEDOFFJKKP = 2;
    uint32 retcode = 13;
}
