syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

enum CmdWaypointType {
    CmdWaypointType_NLCDGIPGFDJ = 0;
    CmdWaypointType_HCNHEDFNLJC = 478;
    CmdWaypointType_HBAPBPBKJLL = 481;
    CmdWaypointType_KNFMJKOGEGF = 425;
    CmdWaypointType_DDKCNBCOELM = 488;
}

message FDECDCEDPNM {
    uint32 BGMFEHBEABC = 3;
    repeated uint32 ICCCHCCDKND = 4;
    uint32 id = 9;
    bool is_new = 13;
}

message GAKJMHLEJMD {
    repeated HEGGPIEGBIN HCBJONGPJFD = 1;
}

message GMCAGPOHKJJ {
    uint32 retcode = 3;
    GAKJMHLEJMD KEDNGHIEOBB = 11;
}

message HEGGPIEGBIN {
    bool is_new = 2;
    uint32 FHNNGNBDGHO = 9;
    uint32 id = 12;
}

message MKEPKKAJONE {
    repeated FDECDCEDPNM LPBLEICPFPD = 1;
    uint32 retcode = 14;
}
