syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message AJDPPONBABG {
    Vector GGDCDJDBCCN = 1;
}

message BPPICAMLGNB {
    GGHOBPBFFOB game_data = 1;
    uint32 retcode = 6;
}

message CPKCMNJKPOE {
    uint32 retcode = 4;
    GGHOBPBFFOB game_data = 8;
}

enum CmdWolfBroType {
    CmdWolfBroType_NLCDGIPGFDJ = 0;
    CmdWolfBroType_DCDMEIGBHMD = 6537;
    CmdWolfBroType_NEOHOJBGGIC = 6507;
    CmdWolfBroType_FMECIELENAK = 6506;
    CmdWolfBroType_AEOJKFFBNME = 6524;
    CmdWolfBroType_BJEGLBIJMIM = 6509;
    CmdWolfBroType_HPHNFDIPEIE = 6520;
    CmdWolfBroType_LMLKFMGOLEI = 6529;
    CmdWolfBroType_MGMMPODDKBK = 6544;
    CmdWolfBroType_NCJOMMAINOC = 6514;
    CmdWolfBroType_EAFBKBGOHBO = 6548;
    CmdWolfBroType_ECKPMIBOCAM = 6503;
    CmdWolfBroType_NDODPFHIFND = 6502;
    CmdWolfBroType_IHFDKCPLIPE = 6521;
    CmdWolfBroType_INPEBLCNDMA = 6535;
    CmdWolfBroType_NBFIFCBOGNO = 6533;
    CmdWolfBroType_MPMBJANKEKM = 6510;
    CmdWolfBroType_JDKHJJNOOGL = 6517;
    CmdWolfBroType_NLOHHNGFENG = 6519;
    CmdWolfBroType_GJGEEPPBGCN = 6523;
}

message DEAHIAKBGMJ {
    GGHOBPBFFOB game_data = 9;
    uint32 retcode = 13;
}

message DKJBGINLBPP {
    uint32 id = 10;
}

message ENPJFKDKLOB {
    GGHOBPBFFOB game_data = 6;
    uint32 retcode = 12;
}

message GGHOBPBFFOB {
    repeated Vector PAOEJKABFEP = 1;
    bool is_bullet_activated = 5;
    KDFPANILFOH BBEMIGELGJC = 7;
    string uuid = 9;
    uint32 id = 10;
    uint32 CHCOPKAKBNO = 11;
}

message HFJCGEMMPKB {
    uint32 retcode = 11;
}

message HKPFPMJBNEP {
    uint32 retcode = 9;
}

message JOHDLJLGNHL {
    uint32 id = 1;
    MotionInfo motion = 5;
}

message KDFPANILFOH {
    repeated Vector PAOEJKABFEP = 6;
    bool is_bullet_activated = 9;
    MotionInfo motion = 13;
    uint32 CHCOPKAKBNO = 15;
}

message KDMANLNDIOA {
    GGHOBPBFFOB game_data = 1;
    uint32 retcode = 4;
}

message LIKMPNFOKFF {
    uint32 id = 13;
}

message LJEFFBCJJEM {
    GGHOBPBFFOB game_data = 11;
}

message LJFEONHOKAG {
    uint32 id = 8;
}

message MDDFDNHFCIL {
    uint32 retcode = 5;
    GGHOBPBFFOB game_data = 9;
}

message NHIGCJFJGPF {
    uint32 retcode = 10;
    GGHOBPBFFOB game_data = 15;
}

message NHLGEDLKOKI {
    MotionInfo motion = 3;
    uint32 id = 6;
    GroupStateInfo group_state_info = 9;
}

message PHPEPPKFMJO {
    uint32 group_id = 8;
    uint32 config_id = 14;
}
