syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

// ========================= AetherDivide =========================

message AetherDivideBattleInfo {
    repeated BattleBuff buff_list = 1;
    uint32 logic_random_seed = 2;
    uint32 stage_id = 9;
    uint32 battle_id = 10;
    repeated AetherAvatarInfo battle_avatar_list = 11;
    bool encrypt_result = 14;
    repeated SceneMonsterWave monster_wave_list = 15;
}

message SpBarInfo {
    uint32 cur_sp = 1;
    uint32 max_sp = 2;
}

// ========================= AiPam =========================

message ChatMessageData {
    uint64 create_time = 4;
    repeated MessageChatData message_datas = 9;
    EKNABKLPEEL CKHPFFENOBE = 10;
    EKNABKLPEEL BKOALKHDLOB = 11;
}

message HJNPOBAMKKF {
    repeated AOAOBPGFHLA HGNKNFJPIKI = 1;
    repeated JAONELJJAFK CDMKBCHLPAB = 2;
    uint32 MNCFOGJECMF = 3;
}

message JOLHIMGJGBO {
    oneof JBLDLHIGGKM {
        OHLNNOMJPNH FJONKDKACAB = 1;
        CIOAOEGEIKH DKBBMJDNHNG = 2;
        JPKIDILKOAK BDNBIHLJNCK = 3;
        DAMNNJKJOMM HCAAHIGINOM = 4;
        KOBGMGHMCLF OEAKBCLIHGH = 5;
        GFDJLBJPNMC MIEJNLBBIDB = 6;
    }
}

enum PJCMNENIEHH {
    PJCMNENIEHH_NLCDGIPGFDJ = 0;
    PJCMNENIEHH_KPILFMMNIGO = 1;
    PJCMNENIEHH_GGJPEMFEBLB = 2;
    PJCMNENIEHH_CIMNEOAKBJH = 3;
    PJCMNENIEHH_BOMDAIKIPLP = 4;
}

// ========================= Avatar =========================

message AetherAvatarInfo {
    uint32 id = 1;
    uint32 index = 2;
    uint32 promotion = 3;
    repeated uint32 LICLEEICAOE = 4;
    AABGIFAEEEK AGBMHEMIAIH = 5;
    SpBarInfo sp_bar = 6;
}

// ========================= Battle =========================

message BattleAvatar {
    AvatarType avatar_type = 1;
    uint32 id = 2;
    uint32 level = 3;
    uint32 rank = 4;
    uint32 index = 5;
    repeated AvatarSkillTree skilltree_list = 6;
    repeated BattleEquipment equipment_list = 7;
    uint32 hp = 8;
    uint32 promotion = 10;
    repeated BattleRelic relic_list = 11;
    uint32 world_level = 12;
    uint32 assist_uid = 13;
    AMEMKFNABGG ALNJENINBPN = 15;
    SpBarInfo sp_bar = 16;
    uint32 GDIMKFNECOK = 17;
    repeated AvatarSkillTree CHEFGGPEJKL = 18;
    uint32 enhanced_id = 19;
}

message BattleBuff {
    uint32 id = 1;
    uint32 level = 2;
    uint32 owner_index = 3;
    uint32 wave_flag = 4;
    repeated uint32 target_index_list = 5;
    map<string, float> dynamic_values = 6;
}

enum BattleEndStatus {
    BATTLE_END_NONE = 0;
    BATTLE_END_WIN = 1;
    BATTLE_END_LOSE = 2;
    BATTLE_END_QUIT = 3;
}

message BattleEquipment {
    uint32 id = 1;
    uint32 level = 2;
    uint32 promotion = 3;
    uint32 rank = 4;
}

message BattleEventBattleInfo {
    uint32 battle_event_id = 1;
    BattleEventProperty status = 2;
    repeated AOFMDLLDIHG skill_info = 3;
}

message BattleEventProperty {
    SpBarInfo sp_bar = 2;
}

message BattleGridFightEquipInfo {
    uint32 grid_fight_equipment_id = 2;
    map<uint32, uint32> convert_property_to_fixpoint = 4;
    uint32 unique_id = 5;
    map<uint32, double> OPEMKBPFFDN = 6;
    CACGKIJHEMG PFCBHCJIDKE = 7;
}

message BattleGridFightTraitCoreRoleInfo {
    uint32 role_id = 1;
    uint32 unique_id = 2;
}

message BattleGridFightTraitEffectInfo {
    uint32 effect_id = 1;
    oneof NEBNJDMFELO {
        BattleGridFightTraitCoreRoleInfo trait_core_role = 101;
        BattleGridFigntAvatarCoreRoleInfo avatar_core_info = 102;
        GridFightTraitEffectLevelInfo trait_effect_level_info = 103;
        KFMKBMJPEIC JLCLHAKNMLL = 104;
        CPMNHNHKLBK LFIDNOAECMN = 105;
    }
}

message BattleGridFigntAvatarCoreRoleInfo {
    repeated uint32 grid_fight_avatar_list = 1;
    repeated uint32 LKNGKJCFFBH = 2;
}

message BattleRelic {
    uint32 id = 1;
    uint32 level = 2;
    uint32 main_affix_id = 3;
    repeated RelicAffix sub_affix_list = 4;
    uint32 unique_id = 5;
    uint32 set_id = 6;
    uint32 type = 7;
    uint32 rarity = 8;
}

message BattleRogueMagicInfo {
    IJLEFNJPFKP OOPCPMANCBO = 1;
    BLJEJFMKEII detail_info = 2;
}

message BattleTargetList {
    repeated BattleTarget battle_target_list = 1;
}

message LMDPKOELKFL {
    bool ABFCDBOCMCF = 1;
    ItemList return_item_list = 5;
    repeated uint32 relic_ids = 14;
}

// ========================= Challenge =========================

message AvatarIdentifier {
    AvatarType avatar_type = 3;
    uint32 assist_uid = 7;
    uint32 id = 9;
}

message BattleTarget {
    uint32 id = 1;
    uint32 progress = 2;
    uint32 total_progress = 3;
}

message ChallengeAvatarInfo {
    AvatarType avatar_type = 1;
    uint32 id = 2;
    uint32 level = 3;
    uint32 index = 4;
    uint32 skin_id = 5;
}

message ChallengeBossStatistics {
    AANLJBLOOFO PPBHLLOJNEK = 1;
    uint32 record_id = 14;
}

message ChallengeStatistics {
    ADKJKMKBFDC PPBHLLOJNEK = 6;
    uint32 record_id = 10;
}

message ChallengeStoryStatistics {
    EIKPHEMHIOH PPBHLLOJNEK = 6;
    uint32 record_id = 7;
}

enum ExtraLineupType {
    LINEUP_NONE = 0;
    LINEUP_CHALLENGE = 1;
    LINEUP_ROGUE = 2;
    LINEUP_CHALLENGE_2 = 3;
    LINEUP_CHALLENGE_3 = 4;
    LINEUP_ROGUE_CHALLENGE = 5;
    LINEUP_STAGE_TRIAL = 6;
    LINEUP_ROGUE_TRIAL = 7;
    LINEUP_ACTIVITY = 8;
    LINEUP_BOXING_CLUB = 9;
    LINEUP_TREASURE_DUNGEON = 11;
    LINEUP_CHESS_ROGUE = 12;
    LINEUP_HELIOBUS = 13;
    LINEUP_TOURN_ROGUE = 14;
    LINEUP_RELIC_ROGUE = 15;
    LINEUP_ARCADE_ROGUE = 16;
    LINEUP_MAGIC_ROGUE = 17;
    LINEUP_FATE = 18;
    LINEUP_GRID_FIGHT = 19;
}

message PlayerChallengeTierceRecord {
    bool EGLLMGLLHDL = 1;
    uint32 record_id = 2;
    repeated AIIGHJEIGHE GBMBAHHDONN = 3;
    uint32 used_cycle_count = 4;
    uint32 total_score = 5;
    repeated uint32 finished_target_list = 6;
}

message RelicAffix {
    uint32 affix_id = 1;
    uint32 cnt = 2;
    uint32 step = 3;
}

// ========================= ChallengePeak =========================

message EquipRelic {
    uint32 relic_unique_id = 1;
    uint32 type = 12;
}

// ========================= Chat =========================

message ChatData {
    oneof extend_type {
        ECCKHOLLPPC NPBOINAPJJE = 101;
        NDDOMFBJMKE IBJBFODFIMN = 102;
        string message_text = 103;
        uint32 extra_id = 104;
        GCBHOIJLBFL IALHIFELMGE = 105;
        IDLACKBINMC ADBNPHDPPIH = 106;
        IGCHDHFMPBJ LPLCDCIFOOK = 107;
        PELDIEOMMDM NLHJFKGNAMB = 108;
        OPLFDAGPBEI BCLPAMNPHNP = 109;
        HCKADDLIGEB HJADNIAAMGJ = 110;
    }
}

// ========================= ChessRogue =========================

message AGEOGDOGDMM {
    uint32 rogue_money = 13;
}

message APNCCNFJBKO {
    repeated KJAMNOGFAMJ buff_list = 12;
}

message BMCNDLNONMO {
    uint64 FCHLCANJIGL = 8;
    KIJEFIIBBGG OOPCPMANCBO = 12;
    RogueModifierSourceType source_type = 14;
    oneof KKNBOACNCON {
        FGHIMGPGBNF NLGJFIGPENF = 11;
        AIBNHPAGDOL LEJPOHHGBMB = 15;
        HFJKOCDOAEH GGJOKFEOEBK = 1;
    }
}

message EGLAPJGFKPN {
    APNCCNFJBKO JPKACKNNHCA = 1;
}

message FDBDLBAPDBE {
    repeated OKPIPFKONMG BLHJIPBHHFO = 2;
}

message GMIJHCONFIH {
    repeated KOFMGCNIMIN MAJGMMCOCIG = 3;
}

message INHBMHCJJCN {
    uint32 queue_position = 2;
    DCFPEIMAMCN detail = 5;
}

message NHLBNBBDHMI {
    GMIJHCONFIH HAJJBOFCFOO = 14;
}

enum RogueModifierSourceType {
    AMEIKAGDIFC_PBGOAOGCPLA = 0;
    AMEIKAGDIFC_OLKBMGLCENL = 1;
    AMEIKAGDIFC_ALPFGINEKIL = 2;
    AMEIKAGDIFC_NNDCINJLBPI = 3;
    AMEIKAGDIFC_MAPKBMAHBKE = 4;
    AMEIKAGDIFC_DMGFEOBEAFD = 5;
    AMEIKAGDIFC_BCPOMCGMFFK = 6;
    AMEIKAGDIFC_LFAHFLJMFNK = 7;
    AMEIKAGDIFC_NOAMEMMFGKP = 8;
    AMEIKAGDIFC_HKOAHEKCJAE = 9;
    AMEIKAGDIFC_IHGDLAJAJMA = 10;
}

// ========================= DiceCombat =========================

message DiceCombatAvatar {
    uint32 dice_avatar_id = 1;
    uint32 level = 2;
    repeated uint32 dice_id_list = 3;
    int64 unlock_time = 4;
}

// ========================= EvolveBuild =========================

message BattleGridFightSpecialBattleInfo {
    uint32 cur_level_id = 1;
    uint32 PFBDNGHMBII = 2;
    uint32 rogue_money = 3;
    repeated GFNAPELNFIC ICOPGAJFKHE = 4;
    repeated GFNAPELNFIC OMCLLCNKAHE = 5;
    repeated uint32 LLIFKMANADH = 6;
    EAENAFJCEFD HPHJGIEKMAA = 7;
    repeated uint32 FPONJJMJFAE = 8;
    uint32 grid_fight_cur_level_exp = 9;
    uint32 LJGPHGDDBKE = 11;
    repeated uint32 DCKIGAHCNMJ = 12;
    uint32 cur_wave = 14;
    repeated OEMOIGDNPNP LONFKFCFDND = 17;
    repeated HLFOOKANNDE HNJPIDFKNIK = 18;
    repeated uint32 BLLKCBJGAEB = 19;
    bool CHKBOLNIPMO = 20;
    uint32 GMBPGBIJGGE = 21;
    IDJIAGLCAPE INPNMBJNPPK = 22;
    uint32 NBKKKKKEMEH = 23;
    repeated uint32 PMLEEGOGPIF = 25;
    repeated PMNLJEJKLOD GMGPFAIONNG = 26;
    uint32 LJHKBJIBCGK = 27;
}

message DKPHAFPGDLO {
    uint32 JGDOICIEMAH = 1;
    uint32 IOEAFFEEDFM = 2;
}

// ========================= Fate =========================

message KPNHGDGLICN {
    AvatarType avatar_type = 1;
    uint32 id = 2;
}

enum MOHNIMLCODA {
    MOHNIMLCODA_NLCDGIPGFDJ = 0;
    MOHNIMLCODA_DMJKCOJLFCL = 1;
    MOHNIMLCODA_ANEIGHKMJKB = 2;
    MOHNIMLCODA_MGMPDHKJFIM = 3;
    MOHNIMLCODA_MAIBAOAOGID = 4;
    MOHNIMLCODA_EGCGFGDILBC = 5;
    MOHNIMLCODA_KEEIBDBEJLH = 6;
    MOHNIMLCODA_level = 7;
    MOHNIMLCODA_DIMIFCJPHME = 8;
    MOHNIMLCODA_PEEDCBADBHJ = 9;
}

// ========================= FightMatch3 =========================

message LAJGLHCCNED {
    uint32 BMANBMAOLLD = 1;
    uint32 CKDCNKNMEAI = 2;
    uint32 EKPKADNENAG = 3;
    uint32 FIIPIFLPEDB = 4;
    uint32 MPNGHAGHAIM = 5;
    uint32 DNDAOOCDNGC = 6;
    uint32 GMNONMGKBFI = 7;
    uint32 CJHGLLNBLJH = 8;
    uint32 ONLANGHDIPJ = 9;
    uint32 CPHOGFPNKLC = 10;
    uint32 JOBFJAPJDBA = 11;
    uint32 PIPOCNHBHAC = 12;
    uint32 HFOPGJFDIHM = 13;
    uint32 CGHLEEAOJGO = 14;
}

// ========================= FiveDim =========================

message DGHPIDMDOJM {
    uint32 GABODFDMPMM = 2;
    AHCLMAGAHPN PPJFMBIGIGB = 4;
    BLPHONLBNBO OEIBHLMDJKA = 6;
    string uuid = 7;
}

// ========================= Friend =========================

message AvatarSkillTree {
    uint32 point_id = 1;
    uint32 level = 2;
}

message CJLCPMDGIBO {
    repeated uint32 EAKOLIJOEPA = 1;
}

message ChallengeLineupList {
    repeated ChallengeAvatarInfo avatar_list = 1;
}

enum FriendOnlineStatus {
    FRIEND_ONLINE_STATUS_OFFLINE = 0;
    FRIEND_ONLINE_STATUS_ONLINE = 1;
}

message HeadFrameInfo {
    uint32 head_frame_item_id = 10;
    int64 head_frame_expire_time = 15;
}

message KAODLPJMEFE {
    HeadFrameInfo head_frame_info = 2;
    uint32 uid = 3;
    string nickname = 4;
    string remark_name = 5;
    PlatformType platform = 6;
    uint32 level = 8;
    string DJONELMIFEE = 12;
    uint32 head_icon = 13;
    uint32 MIDBIPHKLJO = 14;
    uint32 DCOFPHDKNIJ = 15;
}

enum PlatformType {
    EDITOR = 0;
    IOS = 1;
    ANDROID = 2;
    PC = 3;
    WEB = 4;
    WAP = 5;
    PS4 = 6;
    NINTENDO = 7;
    CLOUD_ANDROID = 8;
    CLOUD_PC = 9;
    CLOUD_IOS = 10;
    PS5 = 11;
    MAC = 12;
    CLOUD_MAC = 13;
    CLOUD_WEB_ANDROID = 20;
    CLOUD_WEB_IOS = 21;
    CLOUD_WEB_PC = 22;
    CLOUD_WEB_MAC = 23;
    CLOUD_WEB_TOUCH = 24;
    CLOUD_WEB_KEYBOARD = 25;
    CLOUD_DOUYIN_IOS = 27;
    CLOUD_DOUYIN_ANDROID = 28;
}

message PlayerSimpleInfo {
    bool is_banned = 1;
    uint32 chat_bubble_id = 2;
    string signature = 3;
    string nickname = 4;
    uint32 head_icon = 5;
    uint32 personal_card = 6;
    CJLCPMDGIBO player_outfit_data = 7;
    uint32 level = 8;
    string platform_nick = 9;
    FriendOnlineStatus online_status = 10;
    repeated AssistSimpleInfo assist_simple_info_list = 11;
    uint32 uid = 12;
    string platform_uuid = 13;
    int64 last_active_time = 14;
    PlatformType platform = 15;
    uint32 gender = 48;
    HeadFrameInfo head_frame_info = 837;
    int64 update_time = 1034;
}

// ========================= Gacha =========================

message Item {
    uint32 promotion = 2;
    uint32 unique_id = 3;
    uint32 item_id = 5;
    uint32 main_affix_id = 6;
    uint32 num = 9;
    uint32 level = 11;
    uint32 rank = 13;
}

// ========================= GridFight =========================

message FHCEIOHLADG {
    uint32 pos = 1;
    uint32 LHHONKJPPDC = 2;
    uint32 KFGOKFKHOPB = 3;
    uint32 LLLOOKPGGGG = 4;
}

message GridFightAugmentInfo {
    uint32 augment_id = 1;
}

message GridFightDropInfo {
    repeated BCCONKJHDJL NMGIABHIJJB = 1;
}

enum GridFightDropType {
    MJJIFGINJAJ_NLCDGIPGFDJ = 0;
    MJJIFGINJAJ_item_value = 1;
    MJJIFGINJAJ_exp = 2;
    MJJIFGINJAJ_LJBCDJNNBJH = 3;
    MJJIFGINJAJ_BDPIMPJOJBK = 4;
    MJJIFGINJAJ_NLFCABFPJHD = 5;
    MJJIFGINJAJ_ANMDMBGNOHL = 6;
    MJJIFGINJAJ_JJDGKIIBHOP = 7;
}

message GridFightInfo {
    repeated BattleAvatar OPHONCKPNMG = 1;
    uint32 battle_wave_id = 2;
    uint32 grid_fight_lineup_hp = 3;
    uint32 EHNJDIDABHD = 4;
    repeated GridFightTraitInfo grid_fight_trait_info = 7;
    repeated GridFightRoleInfo grid_game_role_list = 8;
    uint32 IFIIOIIKJHO = 9;
    repeated GridFightAugmentInfo sync_augment_info = 10;
    MIPDJDJLGPL IOCKDJCDMAH = 11;
    uint32 HHEPCDMBJFI = 12;
    uint32 LJNGPCKPJLF = 13;
    repeated GridFightPortalInfo grid_fight_portal_buff_list = 14;
    bool is_overlock = 15;
    uint32 AACGBEBGDPE = 16;
    repeated GridFightNPCInfo grid_game_npc_list = 17;
    repeated GridFightProjectionInfo KCOMPKMJCMC = 18;
    uint32 LODNFLMBIEH = 19;
    map<string, uint32> POCKGKDFLKK = 20;
    uint32 NFBJINKLLLK = 21;
    bool MEHFNAEMMFE = 22;
}

message GridFightNPCInfo {
    uint32 unique_id = 1;
    uint32 npc_id = 2;
    uint32 pos = 3;
    repeated BattleGridFightEquipInfo grid_fight_equipment_list = 4;
}

message GridFightPortalInfo {
    uint32 portal_buff_id = 1;
}

message GridFightProjectionInfo {
    uint32 unique_id = 1;
    uint32 LKMEMKLGIIK = 2;
    uint32 pos = 3;
}

message GridFightRoleInfo {
    uint32 role_id = 1;
    uint32 role_star = 2;
    uint32 pos = 3;
    repeated BattleGridFightEquipInfo CNIJIJMEPEF = 7;
    uint32 avatar_id = 8;
    map<uint32, uint32> convert_property_to_fixpoint = 10;
    uint32 unique_id = 11;
    JJHJCIAPADP DCEOLAAMGOO = 12;
}

message GridFightTraitEffectLevelInfo {
    uint32 trait_effect_level_exp = 1;
    map<uint32, GridFightDropInfo> trait_effect_level_reward = 2;
}

message GridFightTraitInfo {
    uint32 trait_id = 1;
    uint32 layer = 2;
    repeated BattleGridFightTraitEffectInfo trait_effect_list = 3;
    repeated MHFNFINKJKP KOJMGCBLKKA = 5;
    uint32 BPJKHDNBPOE = 6;
    uint32 AFKKLDMAEDJ = 7;
}

// ========================= Heliobus =========================

message GEGLJDELBHA {
    uint32 world_level = 6;
    uint32 raid_id = 8;
    SceneInfo MOPHKIGKDIK = 12;
    LineupInfo lineup = 13;
}

// ========================= IdleLive =========================

message ItemList {
    repeated Item item_list = 2;
}

message KVP {
    uint32 value = 4;
    uint32 key = 12;
}

// ========================= Item =========================

message Equipment {
    bool is_protected = 3;
    uint32 tid = 4;
    uint32 dress_avatar_id = 7;
    uint32 rank = 8;
    uint32 exp = 9;
    uint32 promotion = 10;
    uint32 level = 12;
    uint32 unique_id = 13;
}

message Material {
    uint64 expire_time = 1;
    uint32 num = 5;
    uint32 tid = 11;
}

message NKDNFDCFNCP {
    PileItem FMOKFKBAEII = 5;
    repeated PileItem HJLENJODAMN = 10;
}

message NLLLAAEJOBP {
    uint32 tid = 11;
    repeated uint32 DMNHPNAPGNB = 13;
}

message PileItem {
    uint32 item_id = 2;
    uint32 item_num = 10;
}

message Relic {
    uint32 unique_id = 1;
    repeated RelicAffix sub_affix_list = 2;
    bool is_discarded = 3;
    repeated RelicAffix reforge_sub_affix_list = 4;
    uint32 main_affix_id = 6;
    uint32 level = 7;
    uint32 tid = 8;
    bool is_protected = 10;
    uint32 dress_avatar_id = 11;
    uint32 exp = 13;
    repeated RelicAffix preview_sub_affix_list = 14;
    uint32 reforge_block_sub_affix_id = 15;
}

message WaitDelResource {
    uint32 num = 3;
    uint32 tid = 14;
}

// ========================= Jukebox =========================

message MNCBEDBDDHL {
    KHADHDLCNOI JKNLCEEDAHJ = 1;
    repeated AAKECCJELLI NNJCEINOEHH = 2;
    bool PGPNCNABHAM = 3;
}

// ========================= Lineup =========================

enum AvatarType {
    AVATAR_TYPE_NONE = 0;
    AVATAR_TRIAL_TYPE = 1;
    AVATAR_LIMIT_TYPE = 2;
    AVATAR_FORMAL_TYPE = 3;
    AVATAR_ASSIST_TYPE = 4;
    AVATAR_AETHER_DIVIDE_TYPE = 5;
    AVATAR_UPGRADE_AVAILABLE_TYPE = 6;
    AVATAR_GRID_FIGHT_TYPE = 7;
    AVATAR_GLJDNDMIGIP = 8;
    AvatarType_GPMNKEOADPI = 9;
}

message LineupAvatar {
    uint32 id = 3;
    uint32 slot = 4;
    uint32 satiety = 10;
    AvatarType avatar_type = 13;
    uint32 hp = 14;
    SpBarInfo sp_bar = 15;
}

// ========================= Lobby =========================

enum HGMNDBFCBLL {
    HGMNDBFCBLL_NLCDGIPGFDJ = 0;
    HGMNDBFCBLL_CPJDKCDJFNA = 1;
    HGMNDBFCBLL_APBCEPNOCKG = 2;
}

message LMLNNHKJEIP {
    MOHAGOFLGAP basic_info = 1;
    CIGLIFFIIDC GBBCBJCACIN = 2;
    LobbyGameExtInfo stage_info = 3;
}

enum LobbyCharacterStatus {
    JPJAJPOGCJJ_NLCDGIPGFDJ = 0;
    JPJAJPOGCJJ_BPOCOHFIAOH = 1;
    JPJAJPOGCJJ_NCIPEHOHDMG = 2;
    JPJAJPOGCJJ_HMOGOHOFPFG = 3;
    JPJAJPOGCJJ_HNADONAFDDN = 4;
    JPJAJPOGCJJ_ANAIJLLOOHF = 5;
    JPJAJPOGCJJ_AILKHMPHLEP = 6;
    JPJAJPOGCJJ_HIGMNPCOONG = 7;
}

message LobbyGameExtInfo {
    repeated string MLAFBFEBNHB = 1;
    bool ELJECOAKNOF = 2;
    oneof APEMJMHJHKD {
        LobbyMarchInfo lobby_march_info = 1001;
        LobbyMarbleInfo lobby_marble_info = 1002;
        JMFPICAMLIG PHIBAOMGNOH = 1003;
        LobbyGridFightInfo lobby_grid_fight_info = 1004;
        IPIJFDIPNDE GOKJCFBPHCJ = 1005;
        PCBLIKPEEJA MPNPIIHHFPN = 1006;
    }
}

message LobbyGridFightInfo {
    repeated uint32 LAJJHAAKGAF = 1;
    uint32 gold = 2;
    uint32 score_id = 3;
    string KEJLHDPBIPO = 4;
}

message LobbyMarbleInfo {
    uint32 GDBNHOJPKIE = 1;
    uint32 rank = 2;
    repeated uint32 CIPEHBBKFIH = 3;
    uint32 score_id = 4;
}

message LobbyMarchInfo {
    uint32 HBONKLEOEEI = 1;
    KBCHOKFHHIH AIKDCBMCLBI = 5;
}

enum TeamTowersGameType {
    OCLACMHKMFO_NLCDGIPGFDJ = 0;
    OCLACMHKMFO_AJNDODBCPDB = 1;
    OCLACMHKMFO_GCNBGNABMKN = 2;
    OCLACMHKMFO_HOIHEMDINEH = 3;
    OCLACMHKMFO_CBFHENKAMKO = 4;
}

// ========================= MapRotation =========================

message ChargerInfo {
    uint32 group_id = 10;
    uint32 instance_id = 11;
}

message RotaterData {
    float position = 9;
    uint32 instance_id = 11;
    uint32 group_id = 15;
}

// ========================= MatchThreeModule =========================

enum NPPEMMILLCO {
    NPPEMMILLCO_HGLIFJGHADE = 0;
    NPPEMMILLCO_OPCKNBHNBOA = 1;
    NPPEMMILLCO_CEABDBJPIOF = 2;
    NPPEMMILLCO_HONKPOMPEOO = 3;
    NPPEMMILLCO_HOFPNHIBDKL = 4;
    NPPEMMILLCO_EHNIPLNEEDI = 5;
    NPPEMMILLCO_FAODKNDLNPF = 6;
    NPPEMMILLCO_JCNBPNHEBBH = 7;
}

// ========================= Message =========================

message MessageChatData {
    MsgType message_type = 1;
    ChatData chat_data = 2;
}

enum MessageGroupStatus {
    MESSAGE_GROUP_NONE = 0;
    MESSAGE_GROUP_DOING = 1;
    MESSAGE_GROUP_FINISH = 2;
    MESSAGE_GROUP_FROZEN = 3;
}

enum MessageSectionStatus {
    MESSAGE_SECTION_NONE = 0;
    MESSAGE_SECTION_DOING = 1;
    MESSAGE_SECTION_FINISH = 2;
    MESSAGE_SECTION_FROZEN = 3;
}

// ========================= Misc =========================

enum AABGIFAEEEK {
    AABGIFAEEEK_OCAJFLCAMNA = 0;
    AABGIFAEEEK_AONENHHFNOD = 1;
    AABGIFAEEEK_AOIAAGNAFIO = 2;
}

message AAKECCJELLI {
    uint32 id = 1;
    uint32 volume = 2;
}

message AANLJBLOOFO {
    uint32 buff_two = 1;
    uint32 EEJCPNAEKLJ = 6;
    uint32 level = 8;
    repeated ChallengeLineupList lineup_list = 9;
    uint32 buff_one = 11;
    uint32 score_id = 15;
}

enum ABBHAALIBAH {
    ABBHAALIBAH_IDIPGIPFJJE = 0;
    ABBHAALIBAH_IDJHPOCLFIH = 1;
    ABBHAALIBAH_BFEPJFDFICC = 2;
    ABBHAALIBAH_LNBMBNJICBI = 3;
    ABBHAALIBAH_PMEEHGMPNLK = 4;
}

message ABJGLPCOMMK {
    uint32 ENHJCNJFDFI = 1;
}

message ADKJKMKBFDC {
    uint32 EEJCPNAEKLJ = 1;
    uint32 round_count = 3;
    uint32 level = 13;
    repeated ChallengeLineupList lineup_list = 14;
}

message AHCLMAGAHPN {
    uint32 entity_id = 3;
    MotionInfo motion = 7;
}

message AIBNHPAGDOL {
    bool GKEPPNOLNHF = 4;
    uint32 forbid_reason = 5;
}

message AIIGHJEIGHE {
    uint32 stage_index = 1;
    ChallengeLineupList lineup = 2;
    uint32 buff_id = 3;
}

message AMEMKFNABGG {
    bool GNLMBJCPING = 1;
    repeated uint32 ILOLFNPALJH = 2;
    uint32 PIKBPDAMGML = 3;
    uint32 ODHIDLBAPIG = 4;
}

message AOAOBPGFHLA {
    uint32 compose_relic_id = 1;
    uint32 relic_type = 2;
    JAONELJJAFK ELOGOFFIJBB = 3;
    repeated JAONELJJAFK sub_affix_list = 4;
}

message AOFMDLLDIHG {
    uint32 skill_id = 1;
    double delay = 2;
    repeated uint32 battle_target_list = 3;
    double damage = 4;
}

message AOHKKFHDALO {
    oneof NEBNJDMFELO {
        uint32 role_star = 101;
        uint32 PIHGNNMBCEJ = 102;
    }
}

message APKENKIDMGC {
    uint32 PBJPEOEDEDF = 1;
    repeated DAAKGEDPPJJ GMGPFAIONNG = 14;
}

message AssistSimpleInfo {
    uint32 pos = 1;
    uint32 dressed_skin_id = 5;
    uint32 level = 6;
    uint32 avatar_id = 15;
}

message BACHHBGNENA {
    PGPHEKKPBLD CFDIKLBINHK = 4;
    uint32 EDDBMFMEPJK = 9;
    uint32 DLFHABGGHFF = 13;
}

message BCCONKJHDJL {
    GridFightDropType FKKGLFOHGGA = 1;
    uint32 FNLMKJLKLFH = 2;
    uint32 num = 3;
    AOHKKFHDALO param = 5;
}

message BCGJJCCJBCG {
    uint32 HHGAHEBNAIL = 1;
    uint32 NJHAPBIALCN = 4;
    map<uint32, uint32> MIKLLOOAJFE = 6;
    uint32 HLLIBEEKFII = 10;
}

enum BEAIKEEANDP {
    BEAIKEEANDP_NLCDGIPGFDJ = 0;
    BEAIKEEANDP_NKDECDGECFL = 1;
    BEAIKEEANDP_LONKNKFDPII = 2;
}

message BELNLOJAFCM {
    repeated uint32 HLLLIKPGOFG = 4;
    DGHPIDMDOJM JHBAAHGLFCB = 7;
}

message BGFLAKMOIGC {
    bool AMICPGOIHLL = 9;
    bool JJMKAHIBDBH = 14;
}

message BHPBJOMBCAD {
    repeated NEJPAGJBMDA IJKIBLJEGGE = 2;
    uint32 group_id = 4;
    bool NOALGKCLDHF = 13;
}

message BLJEJFMKEII {
    oneof MMCGBGDJIPN {
        CJHPPLHFNAB FODLGHIFJGC = 1;
        FHOHCAIFHNA GLDHCIBNBAG = 2;
    }
}

message BLPHONLBNBO {
    uint32 instance_id = 4;
    uint32 group_id = 12;
}

message BOFHHEBDEOD {
    uint32 GDBNHOJPKIE = 1;
}

message BPONKBLGNNL {
    ItemCostData cost_data = 2;
    uint32 buff_id = 3;
}

message BuffInfo {
    uint32 buff_id = 1;
    uint32 level = 4;
    uint32 base_avatar_id = 5;
    uint32 count = 6;
    uint32 buff_summon_entity_id = 8;
    map<string, float> dynamic_values = 10;
    uint64 add_time_ms = 12;
    float life_time = 13;
}

enum CACGKIJHEMG {
    CACGKIJHEMG_KFDEMFFJNKA = 0;
    CACGKIJHEMG_DGAPMMELBPE = 1;
    CACGKIJHEMG_MCBPEPHOOHK = 2;
    CACGKIJHEMG_CCCHHGEMJGM = 3;
    CACGKIJHEMG_HJGPMAMOABN = 4;
    CACGKIJHEMG_ONBLMIFEHKK = 5;
}

message CBDMGEGELFM {
    uint32 key = 2;
    int32 DPICNGBHFAC = 12;
}

message CIGLIFFIIDC {
    LKFBIALLBDK NABJDHEPELK = 1;
    LobbyCharacterStatus status = 2;
}

message CIOAOEGEIKH {
    repeated PEGJIHHIFOP DNIGKDKIPPJ = 1;
}

message CJHPPLHFNAB {
    EMLFDPFAPJP BJMJBLCMPAL = 1;
    repeated KCIEGDGJMBE AHBOCLNGFNM = 2;
}

message CLLBJDEJFNF {
    message OOIDNDCPEAF {
        enum DAHCIBCIIAD {
            DAHCIBCIIAD_MNEIHEIGLPO = 0;
            DAHCIBCIIAD_BPILLPJGGGB = 1;
            DAHCIBCIIAD_ANHFOPPEFAL = 2;
            DAHCIBCIIAD_LEEOOMLKANM = 3;
            DAHCIBCIIAD_HJOMKLAGMCM = 4;
        }
    }
    uint32 id = 2;
    uint32 type = 8;
    uint32 slot = 14;
}

message CMNLOKDOFEF {
    uint32 GDBNHOJPKIE = 1;
}

message CPMNHNHKLBK {
    uint32 role_id = 1;
}

message CustomSaveData {
    uint32 group_id = 2;
    string save_data = 5;
}

message DAAKGEDPPJJ {
    bool is_valid = 1;
    uint32 func_id = 14;
}

message DAMNNJKJOMM {
    repeated uint32 first_lineup = 1;
    repeated uint32 second_lineup = 2;
    uint32 DHMEBODOJMI = 3;
    uint32 DLCJLOIMKOJ = 4;
}

message DCFPEIMAMCN {
    oneof KKNBOACNCON {
        GGGBAIAPDLO PCHGEGFBKLF = 724;
        GCCIOBKOFJN JFNHDJIDJDA = 1500;
        IEJIOGIGFAI FEMFJIDBEAB = 2020;
        PKFNILLONDF GHBBKKABKBN = 1112;
        AMKALFJHFJP AMIBPAGBMFP = 491;
        LFKOLKFKOAP PAKPHFJOBAF = 1660;
        LBKIKIGLIMJ BJKEDGMKOLM = 1193;
        MBPJGCJEGJB NGCJBBCOOCF = 462;
        JJPDJPINDOA CNANEDFPNKJ = 756;
        DNGEEKCHHED CDFPGKGILAJ = 278;
        NGEBIKIHIDD PMKJIMIIOGM = 1576;
        INKPGECIDNE JIPEPMDMCMB = 578;
        OFMCKLEMOMP FNEOOMHHGGB = 633;
        JIGLEHNAKNJ EMOJGAFOCML = 1077;
        PAGJKBPPOKL BMEMABNEFKK = 1569;
        KBKLNECKDEN GOIFJFKIFFF = 576;
        NFNMMFBJBLC FJCHODNDIKA = 1927;
        KPJBDOPFPDL FAENLPCFFEB = 499;
        OFGGMBHCKPJ NLAMHGACGIO = 1290;
        OFGGMBHCKPJ JCBNIADPOGN = 1880;
        OFGGMBHCKPJ IJMIEMKJCHM = 471;
        FDICOMLMBME PHGLAEOGJKM = 2028;
        KPOFAPDKBJA MMHGAEBEIHD = 1107;
        JDFNPICGCGI IFPBFMOAJOP = 171;
        NIHKHKONHPN KNKAPJOCNGM = 566;
        PGMIABHEJNB HDAHOBBJDIF = 1003;
        OHJJMCMJEHL KBEBGLAAEGM = 167;
        PBMGACMAMBE HBLHLFDHIGP = 290;
    }
}

message DCHCPKMFNNC {
    repeated uint32 avatar_id_list = 1;
}

message DINGDGLKHIP {
    BEAIKEEANDP HOKEFMONOPG = 3;
    uint32 avatar_id = 9;
}

message DJEECBNBGMN {
    uint32 HAFOKMHCGFM = 1;
}

enum DKOPGDPKJHB {
    DKOPGDPKJHB_CGBIKOCDABB = 0;
    DKOPGDPKJHB_ALJCHAAIPHG = 1;
    DKOPGDPKJHB_COEBIAOACFM = 2;
    DKOPGDPKJHB_FKOIKJFAIKF = 3;
    DKOPGDPKJHB_DIEMGOICHLO = 4;
    DKOPGDPKJHB_KHJHNEOFNLJ = 5;
    DKOPGDPKJHB_EFOHJENLODE = 6;
    DKOPGDPKJHB_HJHCDCHOKJG = 7;
    DKOPGDPKJHB_IHHCKDDFKJL = 8;
}

message DNGEEKCHHED {
    repeated uint32 BGAFHIOEHFH = 7;
    uint32 LGIPILAKIKB = 15;
}

message DPIFGEONFPI {
    repeated uint32 avatar_id_list = 1;
    uint32 ILBJLIENCLB = 2;
}

message EAENAFJCEFD {
    repeated uint32 MMGPKJOJIPM = 1;
    repeated uint32 FGPGOPOCAPN = 2;
}

message EBBJLHBAGCJ {
    uint32 ODPELJAIPHL = 1;
    repeated uint32 GLNPAOLFPDI = 2;
}

message EBBOJACNHEC {
    bool OEEDPJHLPHL = 6;
    uint32 GHEHGIOAGDG = 9;
    uint32 LHLKJIDFLIN = 15;
}

message ECCKHOLLPPC {
    uint64 ANBJMMOEGJE = 1;
    uint32 GJNMHILINHC = 2;
    uint32 JOJALEHLLEJ = 3;
    repeated uint32 AGNFHCLKGCF = 4;
}

message EDCFKACPFNB {
    uint32 CKGJIKJDHCJ = 1;
}

message EGAILAEBLIG {
    uint32 LJCEOGPOGBE = 12;
}

message EIKPHEMHIOH {
    uint32 EEJCPNAEKLJ = 5;
    uint32 buff_one = 6;
    repeated ChallengeLineupList lineup_list = 9;
    uint32 score_id = 10;
    uint32 level = 11;
    uint32 buff_two = 15;
}

message EJEFBHPAPND {
    repeated uint32 avatar_id_list = 1;
}

message EKNABKLPEEL {
    HCMEILLLKBD KPOBMNLKLOK = 1;
    uint32 role_id = 2;
}

message EMLFDPFAPJP {
    uint32 NAEAGNLBKAM = 1;
    uint32 MHPPIKLBNMD = 2;
}

message EPCNFDBKAEE {
    repeated uint32 avatar_id_list = 1;
}

message FDFGIHJBHEL {
    uint32 FMEHKPKHGJA = 1;
    uint32 PNGHFKLCNBE = 2;
}

message FDGKFJFICDN {
    uint32 OCPEPEMNNEK = 1;
    double delay = 2;
}

message FDICOMLMBME {
    uint32 AIAFEKGBFIF = 11;
}

message FEGKCMBHHJP {
    uint32 level = 2;
    uint32 FGFFLBHLKDF = 7;
}

message FGHIMGPGBNF {
    uint32 FOHIFIMHENN = 4;
    bool is_selected = 7;
    repeated uint32 OGOILMLPDEO = 11;
}

message FHBDPOJEEMJ {
    oneof KOEFMOAPDGI {
        DJEECBNBGMN HHBPBGMNGPN = 13;
        EGAILAEBLIG ECCLOKPNFHP = 1;
        HLEBBGFAKAK HDFLCOIDCPE = 6;
    }
}

message FHOHCAIFHNA {
    uint32 HILINOJPLGA = 1;
    double difficulty_ratio = 2;
    uint32 PGGDEHKKINP = 11;
    uint32 style_level = 12;
    uint32 style_exp = 13;
}

message GCBHOIJLBFL {
    string BLDMFDKDJDM = 10;
    oneof BLOFAGPDOKJ {
        DCHCPKMFNNC BNIGONFKICO = 1;
        EJEFBHPAPND JIOEBAFCAJE = 2;
        PFDBLPONOHE NBBFPHGLFNP = 3;
        GMMMIGPFIOH LNOMBCDABKJ = 4;
        DPIFGEONFPI BEGAIBBJHHD = 5;
        EPCNFDBKAEE GOIKMBNGGNP = 6;
        HFHFMPLAJCC CMHJJDDEHCP = 7;
        GDIBHDEKJCG OOKBDDEJHPB = 8;
    }
}

message GCCIOBKOFJN {
    uint32 LGIPILAKIKB = 4;
    repeated KJAMNOGFAMJ JJDILEHLHDH = 10;
}

message GDIBHDEKJCG {
}

message GFDJLBJPNMC {
    repeated JGPMBLAJJJG GBMBAHHDONN = 1;
}

message GFNAPELNFIC {
    uint32 CLFBBAPEPML = 1;
    bool is_locked = 2;
    DKPHAFPGDLO JBNMAOFOFPE = 3;
}

message GILBMELHGCB {
    uint32 stage_id = 14;
    repeated uint32 JMMBAALIOJL = 15;
}

message GKFGIMIBBHF {
    uint32 progress = 2;
    uint32 MMFGAJNCAOA = 7;
    bool finish = 8;
}

message GLIBGKGGEJL {
    repeated uint32 PDABDEJBPEL = 1;
    uint32 NKDDBPGDAEE = 2;
}

message GMIMDEJMFCO {
    MGGBPKANFOA global_blackboard = 7;
    repeated LGEFLGJIGIJ GMALFEABLNG = 11;
}

message GMMMIGPFIOH {
    repeated uint32 avatar_id_list = 1;
}

message HCGDLIAMDLA {
    uint32 avatar_id = 10;
    uint32 JJGMIGBBEOO = 12;
    uint32 JADCEPFHHDK = 14;
}

message HCKADDLIGEB {
    string stop_desc = 1;
    uint32 HAAFJLKHCKF = 2;
}

enum HCMEILLLKBD {
    HCMEILLLKBD_NLCDGIPGFDJ = 0;
    HCMEILLLKBD_JDOAIPKBIPE = 1;
    HCMEILLLKBD_GGBMAANJNJC = 2;
}

message HFHFMPLAJCC {
    repeated uint32 avatar_id_list = 1;
}

message HFJKOCDOAEH {
    uint32 EKNHHGMJCPM = 4;
    uint32 OLPPACCCNGD = 8;
}

message HGNBPANECAL {
    repeated BuffInfo buff_list = 4;
    uint32 entity_id = 5;
}

message HIEKLHPINHL {
    uint32 max_count = 13;
    uint32 OFBPKCNCGFG = 15;
}

message HJDCJNOFBHH {
    uint32 LJCEOGPOGBE = 10;
}

message HLEBBGFAKAK {
    uint32 GNCFHIKODKE = 2;
}

message HLFAKEOBFAB {
    uint32 AFEMBLFCCCH = 3;
    uint32 HJMACPMOINC = 6;
    uint32 PBMAHOJBAGG = 9;
}

message HLFOOKANNDE {
    uint32 JGDOICIEMAH = 1;
    double damage = 2;
    double KADNIAEJACG = 3;
}

message HNEBODEBELG {
    repeated BCCONKJHDJL IEBNOGOOEMO = 5;
    uint32 role_star = 11;
}

message HOMMPJIOPGI {
    uint32 wave = 1;
    uint32 score_id = 2;
    uint32 GMKFBAMNDEA = 3;
    repeated DKPHAFPGDLO CBLOAJFJKKI = 4;
    float delay = 5;
}

enum IDDPBEAMDAO {
    IDDPBEAMDAO_IIOCEDFJPNH = 0;
    IDDPBEAMDAO_NBFHCJMNHAG = 1;
    IDDPBEAMDAO_DHHHKOJBKCJ = 2;
}

message IDJIAGLCAPE {
    uint32 IPCFGIEFBKH = 1;
    repeated HOMMPJIOPGI DCMAHKHAFEH = 2;
    repeated FDGKFJFICDN OJBMGEJCILM = 3;
}

message IDLACKBINMC {
    string title = 1;
    string JFCEOOODIBN = 2;
}

message IEJIOGIGFAI {
    uint32 LGIPILAKIKB = 6;
    repeated KJAMNOGFAMJ CGAEPNOCDIG = 15;
}

message IGCHDHFMPBJ {
    DKOPGDPKJHB type = 1;
    string stop_desc = 2;
    uint32 avatar_id = 3;
}

message IJLEFNJPFKP {
    uint32 rogue_mode = 1;
}

message INKPGECIDNE {
    repeated uint32 KPJPABDIOJB = 6;
}

message IPIJFDIPNDE {
    repeated DiceCombatAvatar avatar_list = 1;
    BOFHHEBDEOD BAEGDJILMBL = 2;
    CMNLOKDOFEF AEPFOJHNNFH = 3;
    uint32 EECIJBLGLNG = 4;
    uint32 EMHHCEMGBEM = 5;
    uint32 GMCAHOPDHLI = 6;
    bool KDFJPPOLFEB = 7;
}

message JAONELJJAFK {
    uint32 property_type = 1;
    float value = 2;
}

message JGPMBLAJJJG {
    repeated uint32 AEJPCFLOPAL = 1;
    uint32 buff_id = 2;
}

message JIGLEHNAKNJ {
    uint32 LGIPILAKIKB = 2;
    repeated uint32 KLLIJGIHFAP = 8;
}

message JJHJCIAPADP {
    ABJGLPCOMMK GLHDCCPOGHL = 101;
    NKAEOPAAJLG JBIFDJKPHIJ = 102;
    uint32 EAGPOCAGMCA = 1;
}

message JJPDJPINDOA {
    uint32 LGIPILAKIKB = 7;
    repeated uint32 ANINMMMGLLL = 13;
}

message JMFPICAMLIG {
    KBCHOKFHHIH AIKDCBMCLBI = 1;
}

enum JNBOIFCNBCH {
    JNBOIFCNBCH_HGLIFJGHADE = 0;
    JNBOIFCNBCH_LCFJOOIAEHD = 1;
}

message JPKIDILKOAK {
    repeated uint32 AEJPCFLOPAL = 1;
    uint32 buff_id = 2;
}

message KBCHOKFHHIH {
    uint32 GDBNHOJPKIE = 1;
    uint32 EAGEFHOHCOA = 2;
    uint32 EECIJBLGLNG = 3;
    uint32 OPHFDHGBLPJ = 4;
    repeated FDFGIHJBHEL MKIOMOINKOF = 5;
    uint32 IHEGLJHMKPP = 6;
    uint32 MFECHJLACLC = 7;
}

message KBKLNECKDEN {
    uint32 NKGGAOJLCMD = 1;
    repeated OKCCLEEPELM AGKFAODICEA = 4;
    OKCCLEEPELM EPOCLANFIAC = 5;
    uint32 EIALMEADLGF = 10;
    uint32 LGIPILAKIKB = 15;
}

message KCIEGDGJMBE {
    uint32 GCAHKLNGFCK = 1;
    repeated OJMPKMNINGK HIILDALHIMD = 2;
    uint32 level = 3;
    map<uint32, uint32> HCPNPDLJKGF = 4;
}

message KFMKBMJPEIC {
    uint32 DNNCAGJIOAP = 1;
    repeated uint32 IHCDDIPNJKO = 2;
    repeated BattleGridFightEquipInfo grid_fight_equipment_list = 3;
    map<uint32, uint32> BANBECDCDHG = 4;
    repeated FHCEIOHLADG POJGKJENENA = 5;
}

message KGLIOOODBPN {
    uint32 level = 2;
    uint32 composition_type = 5;
    repeated uint32 OEOMILPAFGI = 13;
}

message KHADHDLCNOI {
    uint32 id = 1;
    bool is_pause = 2;
}

message KIAICMELIMM {
    map<uint32, uint32> AOKECJBFMCN = 1;
    uint32 CDBGPMABMGM = 2;
    uint32 FGOHMOMLEBG = 3;
    uint32 enemy_hp_multiplier = 4;
}

message KIJEFIIBBGG {
    uint32 JAAIADKFPCL = 3;
    PHAOIGLGBMG content_type = 9;
    uint32 IKDHAMLPNPJ = 11;
}

message KOBGMGHMCLF {
    uint32 avatar_id = 1;
    repeated MCOFKOEJGGL BJKBFDJGFOG = 2;
    uint32 slot = 3;
    uint32 IDBDBICPBBG = 4;
}

message KOEIBOFDLCM {
    uint32 NFMHIOIFLCB = 12;
}

message KPJBDOPFPDL {
    OCBPJLLLJGO MAAGBKHLECB = 11;
}

message LBKIKIGLIMJ {
    uint32 LGIPILAKIKB = 11;
    repeated uint32 MJGBLEBKMDH = 12;
}

message LDKMOFFMGEL {
    uint32 type = 4;
    uint32 LPOLPDBELON = 10;
    uint32 slot = 11;
}

message LDOMEIGDIAK {
    uint32 NFMHIOIFLCB = 8;
}

message LFKOLKFKOAP {
    repeated uint32 CLEJHGMAFOD = 2;
    uint32 LGIPILAKIKB = 6;
}

message LGEFLGJIGIJ {
    uint64 GAHFPGCPAJA = 2;
    repeated AKMCODLAEKI GFKAFIFMHNF = 7;
    MMFOGJPOHGJ owner_type = 14;
}

enum LKFBIALLBDK {
    LKFBIALLBDK_EFAGELOKHAH = 0;
    LKFBIALLBDK_EFLAAFEKBLO = 1;
    LKFBIALLBDK_MHOEPNOAGDN = 2;
    LKFBIALLBDK_GLLICMOMCOA = 3;
}

message LMLNJFEMOAI {
    uint32 skill_id = 1;
    uint32 skill_level = 2;
}

message MBMAGILKFGP {
    repeated HCGDLIAMDLA LEBNOGAMCNE = 2;
}

message MBPJGCJEGJB {
    uint32 LGIPILAKIKB = 2;
    repeated uint32 LHMIIFKPPAG = 8;
}

message MCOFKOEJGGL {
    uint32 GPIOJJBAIJB = 1;
    repeated uint32 ADHEJNDAPIH = 2;
}

message MGGBPKANFOA {
    repeated AKMCODLAEKI GFKAFIFMHNF = 7;
}

message MHFNFINKJKP {
    uint32 CHEEOEHDOBF = 1;
    IDDPBEAMDAO NKIENAICLGN = 2;
    uint32 NKJPCMPMGPM = 3;
    ABBHAALIBAH grid_update_src = 4;
}

message MHGAOLCDONK {
    uint32 NLMMKAEJEKH = 2;
    uint32 OPEEIFGGMIA = 14;
}

message MIPDJDJLGPL {
    uint32 EMOHLJHPOPC = 1;
    uint32 DCAHJELNJNP = 2;
    uint32 section_id = 3;
    uint32 node_type = 4;
}

message MNDMNDKLKIE {
    HNEBODEBELG EIGMKOJOEEI = 1951;
}

message MOHAGOFLGAP {
    uint32 uid = 1;
    uint32 level = 2;
    string nickname = 3;
    uint32 icon = 4;
    PlatformType platform = 5;
    string IJKOMIKFKEK = 6;
    string EBMNJMIKNPP = 7;
    uint64 version = 8;
    bool OCLBMMNNMFC = 9;
    uint32 MIDBIPHKLJO = 10;
}

enum MsgType {
    MSG_TYPE_NONE = 0;
    MSG_TYPE_CUSTOM_TEXT = 1;
    MSG_TYPE_EMOJI = 2;
    MSG_TYPE_INVITE = 3;
    MSG_TYPE_PLANET_FES = 4;
    MSG_TYPE_ACIELMOLELB = 5;
    MSG_TYPE_BGDMLGDMDIF = 6;
    MSG_TYPE_MGLPLOPECGJ = 7;
    MSG_TYPE_PPGBFMOGAHC = 8;
    MSG_TYPE_BAEKHOHLLKJ = 9;
    MSG_TYPE_MJIEABMBEDP = 10;
}

message NAJKNJLJPEP {
    uint32 LDPBPHBBFGF = 4;
    uint32 HFPLJFBOPEH = 5;
}

message NBDKNCJGOMN {
    HKOEAOPNEAC KOBBMDFPNKA = 4;
    uint32 FOKPPMBIDID = 14;
}

message NCHGLFJCGIJ {
    repeated BMCNDLNONMO HDLGLFGKONC = 6;
}

message NDDHJBFEBHG {
    uint32 CLMMHFFNKEH = 4;
    uint32 NFMHIOIFLCB = 6;
    uint32 OKNPKMABAHE = 9;
}

message NDDOMFBJMKE {
    uint32 panel_id = 1;
    uint32 content_type = 2;
    uint64 HJFDAJAMFAC = 3;
}

message NEJPAGJBMDA {
    uint32 FGFFLBHLKDF = 6;
    bool OGNBANANFCC = 15;
    oneof MOKOADHEBBA {
        HJDCJNOFBHH AOLFPJFJPEO = 12;
        FEGKCMBHHJP NGALCDKBGBK = 9;
    }
}

message NFNMMFBJBLC {
    repeated OCBPJLLLJGO INLDHMAIPMH = 7;
    uint32 LGIPILAKIKB = 15;
}

message NGEBIKIHIDD {
    repeated uint32 BGAFHIOEHFH = 1;
    uint32 LGIPILAKIKB = 14;
}

message NIFPICHIDLJ {
    MOHNIMLCODA type = 1;
    uint32 config_id = 2;
    uint32 unique_id = 3;
    uint32 level = 4;
    repeated OEBBNFANHLK switch_list = 5;
}

message NIHKHKONHPN {
    FHBDPOJEEMJ CPOHGLHEOLG = 10;
    uint32 LGIPILAKIKB = 11;
    repeated uint32 FNCIOCCACMD = 13;
    repeated uint32 LEOPMIGFDLK = 15;
}

enum NIMFANHLFNJ {
    NIMFANHLFNJ_FAAFEKOFGBL = 0;
    NIMFANHLFNJ_AMCJDDIPLJN = 1;
    NIMFANHLFNJ_BNNNGLNGCHL = 2;
    NIMFANHLFNJ_DIBHICHMJFE = 3;
    NIMFANHLFNJ_LKDDACHPOAM = 4;
}

message NKAEOPAAJLG {
    uint32 EAGPOCAGMCA = 1;
}

message NMKNOLPFJDN {
    uint32 KOHGFNGKFPE = 2;
    repeated uint32 CKLIEKOIGOG = 9;
    uint32 JCKKPPELFHC = 14;
    repeated uint32 HGDNMKBNMBK = 15;
}

message NpcExtraInfo {
    oneof KKNBOACNCON {
        NpcRogueGameInfo rogue_game_info = 15;
        PAGOHCJGOLC MBLFFIKGMOP = 10;
        MHGAOLCDONK DKPFHLBFFHI = 8;
    }
}

message NpcMonsterExtraInfo {
    NpcMonsterRogueInfo rogue_game_info = 1;
}

message OEBBNFANHLK {
    uint32 JBPNBECLGKN = 1;
    double AALPICLABCO = 2;
}

message OEMOIGDNPNP {
    uint32 card_id = 1;
    double param = 2;
    bool is_enable = 3;
    repeated double switch_list = 4;
}

message OFGGMBHCKPJ {
    uint32 LGIPILAKIKB = 8;
    repeated MMBBHFNJILI AGKFAODICEA = 9;
}

message OHLNNOMJPNH {
    repeated uint32 AEJPCFLOPAL = 1;
}

message OJMPKMNINGK {
    uint32 CFKKKPNKHEL = 1;
    uint32 level = 2;
    bool is_locked = 3;
    uint32 dice_slot_id = 4;
    map<uint32, uint32> AAABHNMAENN = 5;
}

message OKPIPFKONMG {
    uint32 CKHCLKOALKE = 2;
    RogueTalentStatus status = 8;
    repeated GKFGIMIBBHF LDHIJAHNEGK = 10;
}

message ONNEJIPGHCK {
    uint32 chest_id = 9;
}

message OPLFDAGPBEI {
    uint32 avatar_id = 1;
    HJNPOBAMKKF FLFNBPLNNBL = 2;
    HJNPOBAMKKF LLMDKAHFIIJ = 3;
    string stop_desc = 4;
}

message PAGJKBPPOKL {
    OFMCKLEMOMP FNEOOMHHGGB = 4;
}

message PAGOHCJGOLC {
    uint32 PPFJGJNCOKI = 7;
    uint32 DOOACEHOPEE = 10;
    bool is_meet = 12;
}

message PBMGACMAMBE {
    uint32 IOJPOKCDFHM = 7;
    repeated KGLIOOODBPN JKFNAKBGIBF = 13;
}

message PCBLIKPEEJA {
    uint32 EECIJBLGLNG = 1;
    repeated LMLNJFEMOAI skill_list = 2;
    TeamTowersGameType DLFHABGGHFF = 3;
    uint32 stage_id = 4;
}

message PEGJIHHIFOP {
    repeated uint32 AEJPCFLOPAL = 1;
}

message PELDIEOMMDM {
    repeated uint32 avatar_id_list = 1;
    string stop_desc = 2;
}

message PFDBLPONOHE {
    repeated uint32 avatar_id_list = 1;
    repeated PJCMNENIEHH GBKIBFJCPAL = 2;
    repeated uint32 POOEMJLCDHB = 3;
}

message PGLLFCMEFKG {
    uint32 GHEHGIOAGDG = 3;
    bool OEEDPJHLPHL = 5;
    uint32 LHLKJIDFLIN = 10;
}

message PGMIABHEJNB {
    repeated uint32 ICCMIEHKDAO = 9;
}

enum PHAOIGLGBMG {
    PHAOIGLGBMG_OLJCMIBGNGL = 0;
    PHAOIGLGBMG_DLPKBBHKFBL = 1;
}

message PKFNILLONDF {
    uint32 LGIPILAKIKB = 3;
    repeated KJAMNOGFAMJ LEOFNINDJDB = 6;
}

message PKPFAHEBJIO {
    repeated NIFPICHIDLJ message_datas = 1;
    map<uint32, uint32> FGGPANADLKM = 2;
    repeated EBBJLHBAGCJ FPMBJMDNPBM = 3;
    uint32 area_id = 4;
    uint32 difficulty = 5;
}

message PMNLJEJKLOD {
    NIMFANHLFNJ type = 1;
    uint32 count = 2;
}

message POFNNGOCEOK {
    uint32 EIKLMFPMJJD = 2;
    uint32 dice_slot_id = 3;
    int64 expire_time = 10;
}

message PropTimelineInfo {
    bytes timeline_byte_value = 8;
    bool timeline_bool_value = 12;
}

message RotateMapInfo {
    Vector ELFDIEFKCMH = 2;
    Vector4 MIACNFDGKCE = 10;
}

message RotaterEnergyInfo {
    uint32 max_num = 1;
    uint32 cur_num = 13;
}

message TeleportInfo {
    uint32 teleport_id = 3;
    uint32 reason = 4;
}

message Vector4 {
    float z = 6;
    float w = 8;
    float x = 9;
    float y = 10;
}

// ========================= Mission =========================

message MainMissionCustomValue {
    ONHKODAFEMH custom_value_list = 2;
    uint32 main_mission_id = 4;
}

message Mission {
    MissionStatus status = 7;
    uint32 id = 12;
    uint32 progress = 14;
}

message MissionCustomValue {
    string BGDFHBAANLB = 2;
    uint32 index = 3;
    uint32 custom_value = 6;
}

enum MissionStatus {
    MISSION_NONE = 0;
    MISSION_DOING = 1;
    MISSION_FINISH = 2;
    MISSION_PREPARED = 3;
}

// ========================= Multiplayer =========================

message BFBHKJLJJBJ {
    uint64 NOPDGKNKEEH = 1;
    FightGameMode MFLEPLDCJBC = 2;
}

enum FightGameMode {
    FJPMJPEKLJL_NLCDGIPGFDJ = 0;
    FJPMJPEKLJL_EAMCPOPPHEN = 1;
    FJPMJPEKLJL_KPEKNPODEKJ = 2;
    FJPMJPEKLJL_NHAADPKOCMK = 3;
    FJPMJPEKLJL_GCMNKEJIMFI = 4;
    FJPMJPEKLJL_BBEAIOOHDBE = 5;
    FJPMJPEKLJL_BLBMAPAMFHE = 6;
    FJPMJPEKLJL_FBPGILKIGBE = 7;
    FJPMJPEKLJL_MKHLALNLOLA = 8;
    FJPMJPEKLJL_AAHDLLNEJEL = 9;
}

// ========================= PlanetFes =========================

message DFEPHMALKDK {
    uint32 APIFFHBCDKK = 2;
    uint32 BLGLDJHOMNO = 4;
    int64 time = 6;
    uint32 source = 13;
    repeated uint32 OEEGPNOCFLP = 15;
}

message FMKMEFMOJGJ {
    uint32 item_count = 1;
    uint32 item_id = 6;
}

message GMODJEECPPJ {
    repeated uint32 OEEGPNOCFLP = 2;
    int64 apply_time = 8;
    uint32 APIFFHBCDKK = 11;
    uint32 BLGLDJHOMNO = 15;
}

message IEDPDDJAAIH {
    bool FOGGEJIIJCM = 4;
    int64 time = 9;
    uint32 HCJCIAGKHHL = 12;
    repeated uint32 OEEGPNOCFLP = 13;
    uint64 CBMBOBNCKMO = 15;
}

message NCFKHDIKCNI {
    repeated uint32 GFKAFIFMHNF = 8;
}

message OJHHACMHFKA {
    uint32 BIOFDPICHLC = 2;
    uint32 business_day = 3;
    bool NLKMDIBKCIL = 7;
    bool BMHCDIPKKLE = 9;
    int64 HPNLMPJJHCF = 11;
    uint32 event_type = 14;
    bool HMEIPBNOMIG = 15;
    oneof MMCGBGDJIPN {
        MBMAGILKFGP BPABMONFKNB = 13;
        BCGJJCCJBCG DPNFIKGHFIH = 8;
        BACHHBGNENA NBAMDOAEHPJ = 4;
        LDOMEIGDIAK DIGJDCNCPOM = 1;
        NDDHJBFEBHG MBNBKOMMPFB = 5;
        KOEIBOFDLCM FBGJAACOEEI = 6;
    }
}

message PGPHEKKPBLD {
    uint32 ratio = 13;
    uint32 DLFHABGGHFF = 15;
    NMKNOLPFJDN AGLMEDOBMAL = 6;
}

// ========================= Player =========================

message ItemCost {
    oneof item {
        PileItem pile_item = 10;
        uint32 equipment_unique_id = 5;
        uint32 relic_unique_id = 9;
    }
}

message JPGACKPLGCD {
    bool KALACJBAPOA = 1;
    bool FOKJIPGMKAN = 2;
    bool IBLGOCFBOCO = 3;
}

enum MultiPathAvatarType {
    MultiPathAvatarTypeNone = 0;
    Mar_7thKnightType = 1001;
    Mar_7thRogueType = 1224;
    BoyWarriorType = 8001;
    GirlWarriorType = 8002;
    BoyKnightType = 8003;
    GirlKnightType = 8004;
    BoyShamanType = 8005;
    GirlShamanType = 8006;
    BoyMemoryType = 8007;
    GirlMemoryType = 8008;
    BoyElationType = 8009;
    GirlElationType = 8010;
}

message PlayerBasicInfo {
    string nickname = 1;
    uint32 level = 2;
    uint32 exp = 3;
    uint32 stamina = 4;
    uint32 mcoin = 5;
    uint32 hcoin = 6;
    uint32 scoin = 7;
    uint32 world_level = 8;
}

// ========================= PlayerBoard =========================

message HeadIconData {
    uint32 id = 9;
}

// ========================= PlayerSync =========================

message ONHKODAFEMH {
    repeated MissionCustomValue custom_value_list = 8;
}

message Quest {
    uint32 progress = 1;
    int64 finish_time = 2;
    uint32 id = 14;
    QuestStatus status = 15;
}

// ========================= PunkLord =========================

enum PBIEFHKNAFA {
    PBIEFHKNAFA_NLCDGIPGFDJ = 0;
    PBIEFHKNAFA_KBBDECFFFAL = 1;
}

// ========================= Quest =========================

enum QuestStatus {
    QUEST_NONE = 0;
    QUEST_DOING = 1;
    QUEST_FINISH = 2;
    QUEST_CLOSE = 3;
    QUEST_DELETE = 4;
}

// ========================= Rogue =========================

message AACJBNFGABA {
    repeated BPONKBLGNNL EMAGFIBLNCJ = 6;
}

message FHEGNOPNICH {
    bool MJIPOJPBKNB = 1;
    int32 region_id = 2;
    RotaterEnergyInfo energy_info = 6;
    repeated RotaterData CEDGGDFMILP = 9;
    uint32 JPPMEKJGJFD = 11;
    RotateMapInfo COOOMDKGODF = 14;
    repeated ChargerInfo EGAGKNADAHJ = 15;
}

message LineupInfo {
    repeated uint32 locked_avatar_i_ds = 1;
    repeated uint32 available_trial_avatar_i_ds = 2;
    uint32 mp = 3;
    uint32 game_story_line_id = 4;
    uint32 leader_slot = 5;
    bool ABHONGJHICF = 6;
    repeated LineupAvatar avatar_list = 7;
    uint32 plane_id = 8;
    repeated uint32 story_line_avatar_id_list = 9;
    uint32 index = 12;
    uint32 max_mp = 13;
    string name = 14;
    ExtraLineupType extra_lineup_type = 15;
}

message NpcMonsterRogueInfo {
    uint32 rogue_monster_id = 2;
    uint32 elite_group = 3;
    uint32 IEDEBFCCKNL = 4;
    uint32 hard_level_group = 8;
    JNBOIFCNBCH DPCNDADDCAJ = 11;
    uint32 level = 14;
}

message NpcRogueGameInfo {
    map<uint32, uint32> LDPAJKIEPIP = 1;
    bool DJEPGKBMICM = 2;
    uint32 AIAFEKGBFIF = 4;
    uint32 MJBKNMJHOGP = 7;
    uint32 OEANPIHCHHF = 11;
    bool FKKMLJNKHDH = 12;
    bool NLAFLKPLPFE = 14;
}

message PropRogueInfo {
    uint32 room_id = 5;
    uint32 GECOCMLBBPE = 6;
    uint32 MAJKFIMPOOF = 8;
    uint32 KKMEFDEFLBI = 13;
}

enum RogueStatus {
    NOGKOJCAFAE_NLCDGIPGFDJ = 0;
    NOGKOJCAFAE_BMOOGBNPEAA = 1;
    NOGKOJCAFAE_IGGJEJAHPIJ = 2;
    NOGKOJCAFAE_CBFHENKAMKO = 3;
    NOGKOJCAFAE_CIHFGJDCHIA = 4;
}

enum RogueTalentStatus {
    PONHNPLLKAB_GAJGBBFELEL = 0;
    PONHNPLLKAB_BFADFAELKLJ = 1;
    PONHNPLLKAB_has_recommand = 2;
}

message SceneInfo {
    uint32 plane_id = 1;
    uint32 floor_id = 2;
    uint32 world_id = 3;
    repeated uint32 opened_chests_list = 4;
    uint32 entry_id = 5;
    map<uint32, HIEKLHPINHL> BIKBFGPFAAC = 7;
    uint32 leader_entity_id = 8;
    repeated SceneEntityInfo entity_list = 9;
    uint32 client_pos_version = 10;
    repeated CustomSaveData custom_data_list = 11;
    repeated HGNBPANECAL CPIKFGPCOCE = 12;
    uint32 game_mode_type = 13;
    repeated BuffInfo scene_buff_info_list = 15;
    map<string, int32> floor_saved_data = 880;
    uint32 content_id = 966;
    repeated SceneEntityGroupInfo entity_group_list = 989;
    SceneIdentifier scene_identifier = 1107;
    uint32 dimension_id = 1243;
    uint32 game_story_line_id = 1396;
    uint64 interact_id = 1496;
    repeated uint32 lighten_section_list = 1604;
    MissionStatusBySceneInfo scene_mission_info = 1660;
    BELNLOJAFCM FOJJGJPIMBL = 1938;
}

// ========================= RogueCommon =========================

message AKMCODLAEKI {
    double value = 2;
    string key = 3;
}

message AMKALFJHFJP {
    uint32 LIFJCJKNKNJ = 1;
    repeated uint32 BPDDBKGDMDD = 3;
    uint32 FAHAMJFPMMI = 6;
    uint32 LGIPILAKIKB = 8;
}

message BDJLHJDPEEK {
    uint32 level = 2;
    uint32 composition_type = 5;
    repeated uint32 attribute_list = 11;
    uint32 unique_id = 14;
}

message DNLKMHLAPHC {
    OCBPJLLLJGO OOPCPMANCBO = 6;
    map<uint32, uint32> HCPNPDLJKGF = 9;
    repeated LDKMOFFMGEL LEDNAHCKMHK = 13;
    repeated OKCCLEEPELM AJFLAHGJELP = 14;
}

message GGGBAIAPDLO {
    repeated uint32 EBMEEKJGPPM = 2;
    uint32 NOAMCDNNHMD = 3;
    bool can_roll = 4;
    repeated KJAMNOGFAMJ LEOFNINDJDB = 6;
    RogueCommonBuffSelectSourceType source_type = 7;
    uint32 FIMMFJCKCNK = 8;
    uint32 NKGGAOJLCMD = 9;
    uint32 EGFOLKEPNCI = 10;
    uint32 EIALMEADLGF = 11;
    uint32 PCGFIOKLIBE = 14;
    ItemCostData DEHJDNIEKHB = 15;
}

message HKOEAOPNEAC {
    uint32 DGGCFDKJDPO = 2;
    uint32 GPNJGMEPMMD = 3;
    uint32 JAEDKHMMPIH = 10;
    repeated BHPBJOMBCAD AJKOKAJABFG = 12;
    ItemCostData CANJGJIDKHK = 13;
    bool CEIIGJEOIAD = 14;
    uint32 KMNDBEPFMGN = 15;
}

message HMAAICNBKCI {
    map<uint32, int32> DCLBHOHPGMB = 12;
}

message ItemCostData {
    repeated ItemCost item_list = 7;
}

message JDFNPICGCGI {
    map<uint32, uint32> KEGHPOHGPFF = 1;
    repeated uint32 MLIDKPGKCIL = 2;
    repeated uint32 GJFPEFCOBFJ = 3;
    uint32 LIFJCJKNKNJ = 5;
    ODHJEDHKHOD JBEBEKECKJN = 8;
    bool PLJNPPKFFCO = 11;
    repeated uint32 OIMCPHNONPF = 12;
    repeated uint32 FNIPHPIEBNB = 13;
    uint32 FAHAMJFPMMI = 14;
    bool KLGGHNILHIC = 15;
}

message KJAMNOGFAMJ {
    uint32 buff_id = 4;
    uint32 HAGDKKBAAKK = 12;
}

message KOFMGCNIMIN {
    uint32 DGGCFDKJDPO = 4;
    uint32 total_count = 10;
    uint32 LJCEOGPOGBE = 12;
}

message KPOFAPDKBJA {
    uint32 LGIPILAKIKB = 6;
    uint32 FBJLLMGOPHO = 9;
    uint32 PNNCEGEMAPP = 11;
    repeated uint32 PGACPPNAFFF = 13;
    uint32 DAEMEBCKHIK = 15;
}

message LEJFIEPMMGG {
    repeated CBDMGEGELFM IFJIHNBDNGN = 4;
    uint32 KAHMGPGPOII = 11;
    bool is_activated = 12;
}

message LGFOKKPICEH {
    uint32 KGOPHALLLLI = 7;
    uint32 CFKKKPNKHEL = 9;
}

message MMBBHFNJILI {
    uint32 unique_id = 6;
    OKCCLEEPELM OJEANDPABHC = 13;
}

enum MMFOGJPOHGJ {
    MMFOGJPOHGJ_NLCDGIPGFDJ = 0;
    MMFOGJPOHGJ_ANBKDJKHCBI = 1;
    MMFOGJPOHGJ_CFLNLFPNKPF = 2;
    MMFOGJPOHGJ_HHGAHPNPCJN = 3;
    MMFOGJPOHGJ_EELBIOJDKOH = 4;
    MMFOGJPOHGJ_CGBEHICONCC = 5;
}

message OCBPJLLLJGO {
    uint32 GCAHKLNGFCK = 3;
    uint32 level = 5;
}

message OFMCKLEMOMP {
    uint32 LGIPILAKIKB = 1;
    repeated uint32 ONECEAIJLAM = 3;
    uint32 OJCEEICJBGI = 5;
    uint32 DENIIHGKNFM = 8;
    ItemCostData GOOMJPLEIKL = 9;
    bool can_roll = 15;
}

message OHJJMCMJEHL {
    repeated uint32 BLAHNLDHINC = 5;
    uint32 DAEMEBCKHIK = 6;
    uint32 NAENAEGAEAF = 9;
    bool ODBKCIBGLLP = 10;
    uint32 MLJHCOGNJEL = 14;
}

message OKCCLEEPELM {
    uint32 level = 3;
    uint32 CFKKKPNKHEL = 9;
}

message OMJGKNJKHCH {
    int32 NGIBKCODMAL = 2;
    int32 JOCCAPDMHGB = 9;
    uint32 IGNACLJKFGO = 10;
}

message ONMFMINNBEB {
    OCBPJLLLJGO DDLADFJMEEC = 10;
}

enum RogueCommonBuffSelectSourceType {
    CLNECBOMHMN_NLCDGIPGFDJ = 0;
    CLNECBOMHMN_OHFGCMENFDH = 1;
    CLNECBOMHMN_BGDGIIOKHGF = 2;
    CLNECBOMHMN_MCGGEAAHBPD = 3;
    CLNECBOMHMN_EMALBALANLH = 4;
}

// ========================= RogueMagic =========================

message CBOLONJDHHL {
    uint32 ICGCMEIBJLC = 1;
    uint32 LJOBBEFACPG = 4;
    NCHGLFJCGIJ modifier = 7;
    GMIMDEJMFCO blackboard = 8;
    INHBMHCJJCN FMIGOKIDKJL = 10;
    uint32 DLOJFEEHLIJ = 12;
    string trans_no = 14;
}

message FKEDPCMLIFE {
    map<uint32, uint32> HJANIOKJALB = 2;
}

message JEIKFFFGONB {
    ItemCostData LNIEFKBMIPD = 13;
    repeated DINGDGLKHIP BHBPKKKNABO = 15;
}

// ========================= RogueTourn =========================

message ODHJEDHKHOD {
    repeated uint32 NMMCOBBKKHA = 3;
    repeated uint32 BIMFEAHDMIK = 14;
}

// ========================= Scene =========================

message GroupStateInfo {
    uint32 group_id = 2;
    uint32 GMEHAMCHJBK = 6;
    uint32 group_state = 11;
    uint32 entry_id = 13;
}

message MissionStatusBySceneInfo {
    repeated Mission sub_mission_status_list = 1;
    repeated uint32 disabled_main_mission_id_list = 2;
    repeated uint32 unfinished_main_mission_id_list = 4;
    repeated MainMissionCustomValue JLMGBADJBKN = 5;
    repeated uint32 finished_main_mission_id_list = 14;
}

message PropExtraInfo {
    PropTimelineInfo timeline_info = 11;
    oneof KKNBOACNCON {
        PropRogueInfo rogue_game_info = 14;
        HLFAKEOBFAB AEFMMOHKCHJ = 12;
        BGFLAKMOIGC OGLJIOJBIEN = 1;
        EBBOJACNHEC ADNHHAELLNC = 13;
        APKENKIDMGC ACJPMKHJLDB = 15;
        NBDKNCJGOMN OEMHOKEMBKM = 4;
        ONNEJIPGHCK MFCPLGHHPNP = 2;
        PGLLFCMEFKG IDMAELPELLA = 9;
    }
}

message SceneActorInfo {
    uint32 map_layer = 3;
    AvatarType avatar_type = 9;
    uint32 uid = 10;
    uint32 base_avatar_id = 12;
}

message SceneBattleInfo {
    uint32 stage_id = 1;
    repeated BattleBuff buff_list = 2;
    uint32 world_level = 4;
    uint32 logic_random_seed = 5;
    repeated BattleAvatar battle_avatar_list = 7;
    uint32 monster_wave_length = 9;
    repeated SceneMonsterWave monster_wave_list = 10;
    bool encrypt_result = 12;
    uint32 battle_id = 14;
    uint32 rounds_limit = 15;
    BattleGridFightSpecialBattleInfo battle_evolve_build_data = 188;
    GridFightInfo battle_grid_fight_data = 301;
    EDCFKACPFNB battle_action_event_id = 466;
    PKPFAHEBJIO battle_fate_data = 502;
    GLIBGKGGEJL battle_fate_rin_data = 1053;
    KIAICMELIMM battle_sword_training_data = 1427;
    repeated BattleEventBattleInfo battle_event = 1565;
    map<uint32, BattleTargetList> battle_target_info = 1712;
    BattleRogueMagicInfo battle_rogue_magic_info = 1939;
}

message SceneEntityGroupInfo {
    repeated SceneEntityInfo entity_list = 2;
    uint32 group_id = 9;
    map<string, int32> BANBECDCDHG = 12;
    uint32 state = 13;
}

message SceneEntityInfo {
    uint32 entity_id = 8;
    uint32 inst_id = 10;
    MotionInfo motion = 12;
    uint32 group_id = 15;
    oneof entity {
        SceneActorInfo actor = 13;
        SceneNpcMonsterInfo npc_monster = 14;
        SceneNpcInfo npc = 6;
        ScenePropInfo prop = 7;
        SceneSummonUnitInfo summon_unit = 1;
    }
}

message SceneIdentifier {
    uint32 floor_id = 1;
    uint32 content_id = 2;
    uint32 game_story_line_id = 11;
    TeleportInfo teleport_info = 1035;
}

message SceneMonster {
    uint32 max_hp = 2;
    uint32 cur_hp = 10;
    MNDMNDKLKIE extra_info = 11;
    uint32 monster_id = 12;
}

message SceneMonsterWave {
    repeated ItemList NMGIABHIJJB = 3;
    uint32 battle_wave_id = 8;
    uint32 battle_stage_id = 12;
    repeated SceneMonster monster_list = 13;
    SceneMonsterWaveParam monster_param = 15;
}

message SceneMonsterWaveParam {
    uint32 hard_level_group = 1;
    uint32 CPHIINKIDEB = 3;
    uint32 IEDEBFCCKNL = 8;
    uint32 level = 10;
    uint32 elite_group = 14;
}

message SceneNpcInfo {
    NpcExtraInfo extra_info = 6;
    uint32 npc_id = 8;
}

message SceneNpcMonsterInfo {
    NpcMonsterExtraInfo extra_info = 2;
    uint32 monster_id = 4;
    bool NHKJKNJAGMF = 6;
    uint32 world_level = 7;
    GILBMELHGCB BMIJGBFJMCF = 11;
    bool NMPEOMMHMPP = 12;
    uint32 event_id = 15;
}

message ScenePropInfo {
    uint32 prop_state = 1;
    repeated string trigger_name_list = 3;
    PropExtraInfo extra_info = 8;
    uint64 create_time_ms = 10;
    uint32 life_time_ms = 12;
    uint32 prop_id = 13;
}

message SceneSummonUnitInfo {
    uint32 caster_entity_id = 13;
    repeated string trigger_name_list = 4;
    uint32 attach_entity_id = 6;
    int32 life_time_ms = 7;
    uint64 create_time_ms = 11;
    uint32 summon_unit_id = 1;
}

// ========================= TrainParty =========================

message AreaDynamicInfo {
    uint32 diy_dynamic_id = 6;
    uint32 dice_slot_id = 13;
}

message OIIPJFDNPAH {
    repeated AreaDynamicInfo GOEJIMNENDC = 7;
    repeated POFNNGOCEOK POLMJFIKNHN = 9;
    repeated CLLBJDEJFNF OFOKOHGPEDO = 12;
}

// ========================= WolfBro =========================

message MotionInfo {
    Vector pos = 5;
    Vector rot = 12;
}

message Vector {
    sint32 x = 1;
    sint32 y = 2;
    sint32 z = 3;
}
