syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";
import "Orphans.proto";

message EnterFiveDimGameCsReq {
    BLPHONLBNBO OEIBHLMDJKA = 1;
    AHCLMAGAHPN PPJFMBIGIGB = 4;
    MotionInfo HKGDHOPGCKF = 14;
}

message FinishFiveDimMiniGameCsReq {
    uint32 CHMBABEJKGE = 1;
    uint32 AKCLEAJAEPA = 2;
    uint32 IPDDIKPHGPE = 4;
    uint32 BAJHKGJPFED = 5;
    uint32 gold = 7;
    uint32 MGBDFKKMNOL = 8;
    uint32 score_id = 9;
    string uuid = 10;
    float JAPBBDENKGM = 11;
    uint32 FKFGIGAPJNF = 13;
    uint32 OCFCOJMIMFD = 15;
}

message FiveDimGameTransferCsReq {
    KFDEPBCLENF KEHGFMAMEPD = 1;
    AHCLMAGAHPN PPJFMBIGIGB = 2;
    BLPHONLBNBO OEIBHLMDJKA = 3;
    uint32 COGDLBMPPNM = 14;
}

message GetFiveDimGameDataCsReq {
}

message GetFiveDimMiniGameDataCsReq {
    bool EBAFPOLLJIA = 13;
}

message LeaveFiveDimGameCsReq {
    uint32 PJLKEHONHED = 3;
    MotionInfo HKGDHOPGCKF = 5;
    KFDEPBCLENF KEHGFMAMEPD = 8;
    uint32 COGDLBMPPNM = 12;
}

message UpdateFiveDimGameDataCsReq {
    uint32 GABODFDMPMM = 1;
    AHCLMAGAHPN PPJFMBIGIGB = 7;
}
