syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message PlanetFesApplyCardPieceCsReq {
    uint32 teleport_id = 2;
    repeated uint32 OEEGPNOCFLP = 11;
}

enum PlanetFesCardPieceApplyPermissionType {
    BOKMDMEDAHN_OAPAHOMMCGO = 0;
    BOKMDMEDAHN_GOJLDPCAMHM = 1;
    BOKMDMEDAHN_MKAAHIPOJBJ = 2;
}

enum PlanetFesCustomKey {
    FEGJOAPIMCK_NLCDGIPGFDJ = 0;
    FEGJOAPIMCK_HHBCDDHGFEO = 1;
    FEGJOAPIMCK_DHHOGPFPJGL = 2;
    FEGJOAPIMCK_OANGMEDLOBL = 3;
    FEGJOAPIMCK_CFOLBLCAPFB = 4;
}

message PlanetFesGameBingoFlipCsReq {
    uint32 LKFIGBGPEJB = 11;
}

message PlanetFesGetBusinessDayInfoCsReq {
    bool EFILMAOHOBK = 4;
}

message PlanetFesGiveCardPieceCsReq {
    uint32 teleport_id = 8;
    repeated uint32 JAKKDGHLJPH = 14;
}

message PlanetFesSetCustomKeyValueCsReq {
    uint32 key = 6;
    uint32 value = 15;
}

message PlanetFesSkillLevelUpCsReq {
    uint32 IGOOJKMPMDC = 13;
    uint32 skill_id = 15;
}

message PlanetFesStartMiniGameCsReq {
    uint32 DLFHABGGHFF = 6;
    uint32 ratio = 11;
}

message PlanetFesTakeQuestRewardCsReq {
    uint32 quest_id = 11;
}

message PlanetFesTakeRegionPhaseRewardCsReq {
    uint32 BKPDKFLDLDD = 1;
}

message PlanetFesUseItemCsReq {
    uint32 JMOOBDBKFMD = 3;
    uint32 item_id = 14;
}
