syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdAlleyType.proto";

message ActivityRaidPlacingGameCsReq {
    AlleyPlacingShip GPOMFKNHCPB = 2;
    oneof EFJLHNMJEED {
        uint32 GFHGCDEJFIE = 4;
        uint32 CAAHDGFMNNO = 14;
    }
}

message CurTrialActivityScNotify {
    uint32 activity_stage_id = 8;
    TrialActivityStatus status = 9;
}

message EnterTrialActivityStageCsReq {
    uint32 stage_id = 12;
}

message GetActiveActivityDataCsReq {
}

message GetMaterialSubmitActivityDataCsReq {
}

message GetPreAvatarActivityListCsReq {
}

message StartTrialActivityCsReq {
    uint32 stage_id = 5;
}

message SubmitMaterialSubmitActivityMaterialCsReq {
    uint32 LNOCOOCMNCI = 10;
}

message TakeActiveActivityRewardCsReq {
    uint32 id = 13;
}

message TakeLoginActivityRewardCsReq {
    uint32 take_days = 1;
    uint32 id = 14;
}

message TakeMaterialSubmitActivityRewardCsReq {
    uint32 LNOCOOCMNCI = 5;
}

message TakeTrialActivityRewardCsReq {
    uint32 stage_id = 2;
}

enum TrialActivityStatus {
    TRIAL_ACTIVITY_STATUS_NONE = 0;
    TRIAL_ACTIVITY_STATUS_FINISH = 1;
}
