syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdGridFightType.proto";

message GridFightArchiveData {
    uint32 GEGMHOMNBDG = 7;
    int64 OBNEAIPKGKL = 9;
    bool IECKKCHJMLP = 10;
    OEDHMAHDECC BFLLJJBHLDF = 11;
    uint32 PMBNKEFCICH = 12;
    uint32 LJNGPCKPJLF = 14;
    uint32 BAAGDILLLME = 15;
}

message GridFightBackToPrepareScRsp {
    uint32 retcode = 3;
}

enum GridFightDropReason {
    JEHMCCGIOKG_LNPNFLDKKCK = 0;
    JEHMCCGIOKG_ELFIEMKALJO = 1;
    JEHMCCGIOKG_KJMKFEICCDA = 2;
}

message GridFightGetArchiveScRsp {
    MLJIILDNDPL type = 7;
    repeated GridFightArchiveData MCGGPONOCKC = 10;
    uint32 retcode = 11;
}

message GridFightHandlePendingActionCsReq {
    uint32 queue_position = 4;
    oneof FGLIODAJFML {
        LAPOAFHDNCM MFFCPLBNHCF = 2023;
        EPLJJNHCJIF DCPHLHNLNKF = 1901;
        CJPOMFIDLOA IBCHMBNIPLK = 1939;
        GIOLAAKLDED DAJDBBEPMMA = 656;
        GKLDOELMEIN PKHJLKNGCGH = 1607;
        OHAINOHGKCM BAKAKODKECM = 690;
        NIDJPBLNDLH JLPOPEAJHMF = 1162;
        NNFPCAPDENH KEBDKGKEJDD = 301;
        AJDFPFHBFJM NNDGEJFLGGF = 1142;
        NEMAKFJPGDF LGNPHHBGKFH = 497;
        HMNMJKCHABE FIKAGBAEOAP = 827;
        DFMGEJCCBPD IACBCOBMGJB = 349;
        PDKGKIDCBKA HOKCPPPLJIO = 374;
        DGILDLDMGEI EMMPHLKJAJN = 1304;
        PCCGPNAFMHP HHNPEHMBDKD = 1095;
        LFONAPFHAOB HHNHGJMOGDD = 885;
        FNNFHNKHIDD CFDIPFKBFJB = 210;
        IDOJADMFGKF NFBJINKLLLK = 1748;
        EJEFKJGAKOO LAJGNNBOLDG = 1884;
        FKILNIGOKBF LFIDNOAECMN = 1593;
        KCCPHHGCPMP IOHJGOENAPF = 1247;
    }
}

message GridFightPermanentTalentEnableCsReq {
    uint32 CKHCLKOALKE = 4;
}

message GridFightPermanentTalentResetCsReq {
}

message GridFightSeasonTalentEnableCsReq {
    uint32 CKHCLKOALKE = 1;
}

message GridFightSeasonTalentResetCsReq {
}

message GridFightTraitUpdateCsReq {
    uint32 effect_id = 8;
    uint32 trait_id = 12;
    oneof NEBNJDMFELO {
        GPCFHMLMDHC FFBEPFLBHPL = 897;
        AFPJPEABFKH JLCLHAKNMLL = 1879;
        MHKNPBJDFIC LFIDNOAECMN = 1854;
    }
}
