syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdEvolveBuildType.proto";

message GetEvolveBuildGiveupCsReq {
    uint32 level_id = 3;
}

message GetEvolveBuildQueryInfoCsReq {
}

message GetEvolveBuildReRandomStageCsReq {
    uint32 level_id = 9;
}

message GetEvolveBuildShopAbilityDownCsReq {
    uint32 level = 1;
    uint32 JEKLOEPPJBK = 7;
}

message GetEvolveBuildShopAbilityResetCsReq {
    EDJKFOBBDJF HFPEJIDDDJG = 15;
}

message GetEvolveBuildShopAbilityUpCsReq {
    uint32 JEKLOEPPJBK = 2;
    uint32 level = 5;
}
