syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message RogueMagicEnableTalentCsReq {
    uint32 CKHCLKOALKE = 10;
}

message RogueMagicEnterCsReq {
}

message RogueMagicEnterLayerCsReq {
    uint32 BJHMFOAGMBF = 10;
    uint32 KHBLMAOPLLN = 12;
}

message RogueMagicEnterRoomCsReq {
    uint32 JOJCPKNIJOH = 6;
    uint32 KHBLMAOPLLN = 9;
}

message RogueMagicGetMiscRealTimeDataCsReq {
}

message RogueMagicLeaveCsReq {
}

message RogueMagicQueryCsReq {
}

message RogueMagicReviveAvatarCsReq {
    uint32 interacted_prop_entity_id = 4;
    repeated uint32 NOEPBNMJFGL = 12;
}

message RogueMagicSetAutoDressInMagicUnitCsReq {
    bool GBEMCAHPBKP = 7;
}

message RogueMagicSettleCsReq {
}

message RogueMagicStartCsReq {
    repeated uint32 OCEGEKKFLAL = 5;
    repeated uint32 NOEPBNMJFGL = 12;
    uint32 area_id = 13;
    uint32 IEOFONJHFDJ = 14;
}

message RogueMagicUnitComposeCsReq {
    repeated uint32 JDJFHIMPIPK = 1;
}
