syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdEraFlipperType.proto";

message ChangeEraFlipperDataScRsp {
    uint32 retcode = 5;
    KKFMGCNDHGH data = 7;
}

message EnterEraFlipperDataScRsp {
    uint32 region_id = 6;
    uint32 retcode = 7;
}

message EraFlipperRegionDataSnapshot {
    uint32 region_id = 1;
    uint32 state = 2;
}

message EraFlipperSnapshot {
    repeated EraFlipperRegionDataSnapshot region_data_list = 1;
}

message GetEraFlipperDataScRsp {
    uint32 retcode = 1;
    KKFMGCNDHGH data = 11;
}

message ResetEraFlipperDataCsReq {
    bool CJEILDIOIOE = 1;
}

message ResetEraFlipperDataScRsp {
    uint32 retcode = 3;
    KKFMGCNDHGH data = 7;
    bool CJEILDIOIOE = 15;
}
