syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdMultiplayerType.proto";
import "Common.proto";
import "Orphans.proto";

message GetMatchPlayDataRsp {
    uint32 retcode = 9;
    repeated PNEGDOHOLDN JBMEEGGOLKN = 10;
}

message MatchBoxingClubOpponentCsReq {
    uint32 challenge_id = 4;
    repeated AKLDICEFCIL OOJOMKDMBBM = 5;
    repeated uint32 avatar_list = 11;
}

message MatchPlayDataChangeNtf {
    PNEGDOHOLDN KMCDHFGJFNJ = 5;
}

message MatchThreeGetDataDataCsReq {
}

enum MatchThreeStatisticsType {
    JHGPKBIJHDE_AKHAIBHBLFL = 0;
    JHGPKBIJHDE_IKGFLPIKBME = 1;
    JHGPKBIJHDE_FPBHKCHPDJD = 2;
    JHGPKBIJHDE_CGMJACLCLOI = 3;
    JHGPKBIJHDE_OEMMEEEJGJN = 4;
    JHGPKBIJHDE_GGCOALCKJLG = 5;
    JHGPKBIJHDE_DEDJLNBBFJD = 6;
    JHGPKBIJHDE_LCIJPPIJBKC = 7;
    JHGPKBIJHDE_EAKEHNFBDBN = 8;
    JHGPKBIJHDE_ALMCCADJLKA = 9;
    JHGPKBIJHDE_COLMJCGJDCC = 10;
    JHGPKBIJHDE_MDBAFCNEPJP = 11;
    JHGPKBIJHDE_OFOKPFFONKH = 12;
    JHGPKBIJHDE_DBNNDMDFHEK = 13;
}

message MatchThreeV2LevelEndCsReq {
    string uuid = 1;
    repeated KVP MONKDLNMMBK = 2;
    repeated uint32 EEDLBJGGLKD = 3;
    uint32 EOHGLCJAMKN = 8;
    uint32 HBONKLEOEEI = 10;
    uint32 JGIFDFLDBPB = 12;
    uint32 GFBAHEODFNA = 13;
    uint32 level_id = 15;
}

message MatchThreeV2SetBirdPosCsReq {
    uint32 HBONKLEOEEI = 5;
    uint32 pos = 14;
}

message StartMatchCsReq {
    FightGameMode GJNMHILINHC = 4;
    LobbyGameExtInfo JIDKDPPPDPF = 11;
}
