syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdRelicPresetType.proto";

message RelicPresetAddPlanCsReq {
    uint32 avatar_id = 4;
    string name = 5;
    RelicPresetPlanSourceType source_type = 8;
    repeated uint32 relic_ids = 13;
    FDJKLJGDCID LLJJCOOKANH = 14;
}

message RelicPresetAddPlanScRsp {
    PFCKBFLDHNI relic_plan = 2;
    uint32 retcode = 14;
}

message RelicPresetDeletePlanCsReq {
    uint32 unique_id = 9;
}

message RelicPresetDeletePlanScRsp {
    uint32 retcode = 4;
    uint32 unique_id = 6;
}

message RelicPresetGetPlanCsReq {
    uint32 avatar_id = 7;
}

message RelicPresetGetPlanScRsp {
    uint32 retcode = 1;
    uint32 avatar_id = 5;
    repeated PFCKBFLDHNI relic_plan_list = 8;
}

message RelicPresetUpdatePlanCsReq {
    uint32 unique_id = 15;
    oneof KKNBOACNCON {
        HPPOINFLEPJ relic_list = 12;
        string name = 13;
    }
}

message RelicPresetUpdatePlanScRsp {
    uint32 retcode = 3;
    uint32 unique_id = 6;
    oneof KKNBOACNCON {
        HPPOINFLEPJ relic_list = 15;
        string name = 9;
    }
}
