syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdHipplenType.proto";

message GetHipplenDataCsReq {
}

message GetHipplenInheritCsReq {
}

message OpenHipplenCycleCsReq {
    uint32 trait_id = 5;
}

message SetHipplenAgendaCsReq {
    repeated uint32 NEMFNENACNB = 11;
}

message SetHipplenOutfitCsReq {
    uint32 IMIBAAPJGEJ = 12;
}

message SettleHipplenWorkCsReq {
    oneof NEBNJDMFELO {
        HBMGNLFKMMK HBGCOIAGDIG = 10;
        LODMLDKMPPL ENCBGPOIFCM = 15;
        OHHHCKCFPIG ECKIMBNDOME = 12;
        GCNJGJMPLHM MLLNOGKNHNL = 9;
    }
}

message TakeHipplenEndingRewardCsReq {
    uint32 BKFICFMMGIN = 9;
}
