syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdRogueTournType.proto";
import "Common.proto";

message RogueTournConfirmSettleCsReq {
    string name = 6;
    uint32 NPHAJEKCBKF = 9;
    uint32 area_id = 11;
}

message RogueTournDeleteArchiveCsReq {
    uint32 NPHAJEKCBKF = 13;
}

message RogueTournDeleteBuildRefCsReq {
    repeated uint32 GGIGDJPFBBP = 1;
}

message RogueTournEnablePermanentTalentCsReq {
    uint32 CKHCLKOALKE = 6;
}

message RogueTournEnableSeasonTalentCsReq {
    uint32 CKHCLKOALKE = 6;
}

message RogueTournEnterCsReq {
}

message RogueTournEnterLayerCsReq {
    uint32 BJHMFOAGMBF = 5;
    uint32 KHBLMAOPLLN = 10;
}

message RogueTournEnterRogueCocoonSceneCsReq {
    uint32 DCNNFJLABPL = 2;
    uint32 NBLMAGLGCGN = 6;
    uint32 difficulty = 8;
    repeated AvatarIdentifier avatar_list = 10;
    uint32 HECCOBFBJFI = 12;
}

message RogueTournEnterRoomCsReq {
    uint32 KHBLMAOPLLN = 10;
    uint32 JOJCPKNIJOH = 14;
}

message RogueTournGetAllArchiveCsReq {
}

message RogueTournGetAllBuildRefCsReq {
}

message RogueTournGetArchiveRepositoryCsReq {
}

message RogueTournGetMiscRealTimeDataCsReq {
}

message RogueTournGetPermanentTalentInfoCsReq {
}

message RogueTournGetSeasonTalentInfoCsReq {
}

message RogueTournGetSettleInfoCsReq {
    uint32 area_id = 2;
}

message RogueTournLeaveCsReq {
}

message RogueTournLeaveRogueCocoonSceneCsReq {
}

message RogueTournQueryCsReq {
}

message RogueTournReEnterRogueCocoonStageCsReq {
}

message RogueTournRenameArchiveCsReq {
    string name = 3;
    uint32 NPHAJEKCBKF = 8;
}

message RogueTournRenameBuildRefCsReq {
    uint32 NPHAJEKCBKF = 1;
    string name = 7;
}

message RogueTournResetPermanentTalentCsReq {
}

message RogueTournReviveAvatarCsReq {
    uint32 interacted_prop_entity_id = 7;
    repeated DKFJLHHDFKO avatar_list = 10;
}

message RogueTournSaveBuildRefCsReq {
    OOLJJHMLHBH MPOEFPFPEND = 3;
    string name = 6;
    uint32 NPHAJEKCBKF = 15;
}

message RogueTournSettleCsReq {
}

message RogueTournStartCsReq {
    uint32 area_id = 1;
    bool EJDMOENBHDP = 5;
    bool KENPENNAGLG = 11;
    repeated DKFJLHHDFKO avatar_list = 13;
}

message RogueTournTakeExpRewardCsReq {
    uint32 FABMHMFNMDB = 11;
    repeated uint32 HBGAFAFFFAO = 14;
}

message RogueTournUseSuperRewardKeyCsReq {
    uint32 count = 3;
    uint32 difficulty = 5;
    uint32 cocoon_id = 13;
}
