syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdSwordTrainingType.proto";

message EnterSwordTrainingExamCsReq {
}

message SwordTrainingDailyPhaseConfirmCsReq {
    SwordTrainingDailyPhaseType GCBHFKKGPHC = 1;
}

message SwordTrainingDialogueSelectOptionCsReq {
    uint32 HAFOKMHCGFM = 12;
}

message SwordTrainingGiveUpGameCsReq {
}

message SwordTrainingMarkEndingViewedCsReq {
}

message SwordTrainingRestoreGameCsReq {
}

message SwordTrainingResumeGameCsReq {
    uint32 game_story_line_id = 5;
}

message SwordTrainingSelectEndingCsReq {
    uint32 PFOLEGLCLFE = 1;
}

message SwordTrainingStartGameCsReq {
    uint32 game_story_line_id = 1;
}

message SwordTrainingStoryBattleCsReq {
}

message SwordTrainingTurnActionCsReq {
    repeated uint32 GJEPAKHPFCG = 13;
    repeated uint32 CCPADEMEHBA = 14;
}
