syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdMonopolyType.proto";

message GetMonopolyDailyReportCsReq {
}

message GetMonopolyMbtiReportRewardCsReq {
}

message MonopolyEventSelectFriendCsReq {
    uint32 LPDFMJPFGJH = 5;
    bool DHLLPOBKLIO = 7;
}

message MonopolyGetDailyInitItemCsReq {
}

message MonopolyGetRafflePoolInfoCsReq {
}

message MonopolyGetRegionProgressCsReq {
}

message MonopolyGuessDrawScNotify {
    repeated DCMHLOEGFBM KHLFDHANJCO = 11;
}

message MonopolyRollRandomScRsp {
    NEMIDPFEJFL MOMEIFPICLE = 1;
    uint32 event_id = 11;
    uint32 retcode = 14;
}

message MonopolyTakePhaseRewardCsReq {
    repeated uint32 IICEKEPFMJO = 9;
}
