syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdTrainPartyType.proto";
import "Common.proto";

message TrainPartyBuildDiyCsReq {
    uint32 diy_dynamic_id = 2;
    uint32 dice_slot_id = 3;
    uint32 area_id = 6;
}

message TrainPartyBuildSelfDisplayAreaDiyCsReq {
    OIIPJFDNPAH ACLKMFCDMED = 11;
}

message TrainPartyBuildStartStepCsReq {
    uint32 DNLIGEOFPEL = 1;
    uint32 area_id = 2;
    uint32 GKENFCLLLJC = 3;
    AreaDynamicInfo PFICNBHIHBA = 15;
}

message TrainPartyBuildingUpdateNotify {
    repeated FFMMFBMOBEG OOABOBHEKEH = 15;
}

message TrainPartyGamePlayStartCsReq {
    uint32 IDBDBICPBBG = 10;
}

message TrainPartyGetDataCsReq {
}

message TrainPartyHandlePendingActionCsReq {
    uint32 queue_position = 6;
    oneof KILBFAAFDPD {
        MDOIMCNFDLC KLONPDNKBJF = 1533;
        PFAIANENDEE LGBJDFHBIND = 352;
        CKPNGMLENFA NELLGPKHIKE = 1642;
        MOCNDOCEOJM NMEFKABDHAN = 795;
    }
}

message TrainPartyMoveScNotify {
    repeated CNLAOMCKFKD JABPLBJAKKM = 6;
    uint32 DNGKGLFMGGE = 14;
}

message TrainPartySetBadgeAutoFillCsReq {
    bool PELJACANAFH = 6;
}

message TrainPartyTakeBuildLevelAwardCsReq {
}

message TrainPartyUseCardCsReq {
    uint32 FGIHKKKOGJD = 5;
}
