syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message BatchGetQuestDataCsReq {
    repeated uint32 quest_list = 2;
}

message BatchGetQuestDataScRsp {
    uint32 retcode = 3;
    repeated Quest quest_list = 10;
}

message FinishQuestCsReq {
    uint32 prop_id = 4;
    uint32 quest_id = 5;
    uint32 group_id = 14;
}

message FinishQuestScRsp {
    uint32 retcode = 2;
}

message FinishQuestionCsReq {
    uint32 CJAINJMLDFC = 8;
    uint32 PDICFEGEPNM = 11;
    bool DJNDDEBIMGA = 12;
    uint32 JMBGMIPLLJI = 13;
}

message TakeQuestEquipCsCsReq {
    bool DKPCAIGPHNO = 4;
    uint32 quest_id = 15;
}

message TakeQuestOptionalRewardCsReq {
    uint32 optional_reward_id = 4;
    uint32 quest_id = 8;
}

message TakeQuestRewardCsReq {
    repeated uint32 succ_quest_id_list = 2;
}
