syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdRogueCommonType.proto";
import "CmdRogueType.proto";
import "Common.proto";
import "Orphans.proto";

message AJNDMBCDEOL {
    HFGBCEKGFHK ILMAMLBLIDL = 1;
    uint32 retcode = 3;
}

message CommonRogueQueryCsReq {
    repeated uint32 query_list = 6;
}

message EnableRogueTalentCsReq {
    uint32 CKHCLKOALKE = 6;
}

message EnhanceRogueBuffCsReq {
    uint32 maze_buff_id = 13;
}

message EnhanceRogueBuffScRsp {
    KJAMNOGFAMJ CNEFDJCKAPL = 1;
    uint32 retcode = 10;
    bool KGKEJAKKLDP = 14;
}

message GetRogueBuffEnhanceInfoCsReq {
}

message GetRogueShopBuffInfoCsReq {
    bool LJBCDJNNBJH = 1;
    uint32 interacted_prop_entity_id = 15;
}

message GetRogueShopFormulaInfoCsReq {
    bool LJBCDJNNBJH = 3;
    uint32 interacted_prop_entity_id = 15;
}

message QuitRogueCsReq {
    uint32 area_id = 2;
}

message RogueDoGambleCsReq {
    uint32 prop_entity_id = 3;
}

message RogueGetGambleInfoCsReq {
    uint32 prop_entity_id = 15;
}

message RogueShopBeginBattleCsReq {
    uint32 interacted_prop_entity_id = 12;
}

message RogueWorkbenchGetInfoCsReq {
    uint32 prop_entity_id = 5;
}

message RogueWorkbenchHandleFuncCsReq {
    MIPGDFDCKLE PELKPPHLMHE = 4;
    uint32 prop_entity_id = 8;
    uint32 func_id = 9;
}

message SetRogueCollectionCsReq {
    repeated uint32 NPICFPDAPAF = 1;
    repeated uint32 MFMPDDCGGMN = 4;
    repeated MIGPNAOGHEP NEKJDKDAMKF = 8;
}

message SetRogueExhibitionCsReq {
    repeated MIGPNAOGHEP ADGNFDJDCLG = 3;
    repeated uint32 HNCFLOKLJLA = 9;
    repeated uint32 DMIIBKINPNL = 15;
}

message StartRogueCsReq {
    repeated uint32 unfinished_story_line_id_list = 1;
    repeated uint32 NOEPBNMJFGL = 2;
    uint32 AFEMBLFCCCH = 4;
    uint32 area_id = 13;
    repeated uint32 JKPIPNMGGOA = 14;
}

message TakeRogueMiracleHandbookRewardCsReq {
    repeated uint32 PHINEMJKBJK = 14;
}
