syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdRelicSmartWearType.proto";

message RelicSmartWearAddPlanCsReq {
    RelicSmartWearPlan relic_plan = 9;
}

message RelicSmartWearDeletePinRelicCsReq {
    bool BEAJGCMPOED = 7;
    repeated ONFLANPGHHL AIFAMIFGMCH = 8;
    uint32 avatar_id = 15;
}

message RelicSmartWearDeletePlanCsReq {
    uint32 unique_id = 12;
}

message RelicSmartWearGetPinRelicCsReq {
    uint32 avatar_id = 8;
}

message RelicSmartWearGetPlanCsReq {
    uint32 avatar_id = 15;
}

message RelicSmartWearUpdatePinRelicCsReq {
    CABBOOKAODO DNNKBPBFPBK = 14;
}

message RelicSmartWearUpdatePlanCsReq {
    RelicSmartWearPlan relic_plan = 3;
}
