syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

message ChallengePeakLineup {
    uint32 peak_id = 4;
    repeated uint32 peak_avatar_id_list = 10;
}

message ConfirmChallengePeakSettleCsReq {
    bool IOBCIMIPEOM = 1;
    uint32 peak_id = 13;
}

message ConfirmChallengePeakSettleScRsp {
    bool IOBCIMIPEOM = 5;
    uint32 peak_id = 8;
    uint32 retcode = 12;
}

message GetCurChallengePeakCsReq {
}

message LeaveChallengePeakCsReq {
}

message LeaveChallengePeakScRsp {
    uint32 retcode = 8;
}

message ReStartChallengePeakCsReq {
}

message ReStartChallengePeakScRsp {
    uint32 retcode = 15;
}

message SetChallengePeakBossHardModeCsReq {
    uint32 peak_group_id = 7;
    bool is_hard_mode = 11;
}

message SetChallengePeakMobLineupAvatarCsReq {
    repeated ChallengePeakLineup lineup_list = 1;
    uint32 peak_group_id = 12;
}

message SetChallengePeakMobLineupAvatarScRsp {
    uint32 retcode = 2;
}

message StartChallengePeakCsReq {
    repeated uint32 peak_avatar_id_list = 3;
    uint32 boss_buff_id = 4;
    uint32 peak_id = 7;
}

message StartChallengePeakScRsp {
    uint32 retcode = 1;
}

message TakeChallengePeakRewardCsReq {
    repeated uint32 normal_reward_id_list = 11;
    uint32 peak_group_id = 15;
}
