syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdChimeraDuelType.proto";
import "Orphans.proto";

message ChimeraDuelChangeLineupCsReq {
    uint32 ALJOJIDAAPC = 2;
    repeated uint32 AJFJLCKPNAM = 3;
    uint32 GIECFFNDLEB = 15;
}

message ChimeraDuelEndGameCsReq {
}

message ChimeraDuelEndRoundBattleStageCsReq {
    DIIKFKNEHHG NONPIMDDJNN = 4;
    IDGMALDABBE stt = 11;
    uint32 MILMHPODLBB = 12;
}

message ChimeraDuelGetDataCsReq {
}

message ChimeraDuelSellChimeraCsReq {
    uint32 NDJGKJMPPHJ = 2;
    repeated uint32 AJFJLCKPNAM = 12;
}

message ChimeraDuelShopLockCsReq {
    bool is_locked = 10;
    oneof KKNBOACNCON {
        uint32 NDJGKJMPPHJ = 9;
        uint32 AGBAIFPNKII = 1;
    }
}
