syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";
import "Orphans.proto";

message ChallengeTierceChallengeInfo {
    bool is_single_stage = 1;
    repeated LineupInfo lineup_list = 7;
    uint32 stage_index = 12;
    ChallengeTiercePendingStageSettle IIHFEDLHOPI = 13;
    uint32 challenge_id = 15;
}

message ChallengeTierceData {
    uint32 challenge_id = 3;
    repeated ChallengeTierceStageData result_list = 4;
    bool is_passed = 6;
    repeated uint32 finished_target_list = 7;
    repeated ChallengeTierceStageInfo stage_info_list = 8;
    ChallengeTierceRecord record = 13;
}

message ChallengeTierceMedal {
    uint32 MGLLKBNFKFG = 5;
}

message ChallengeTiercePendingStageSettle {
    uint32 OPNPMBJDKNB = 8;
    uint32 MMCPICGKOGD = 10;
    uint32 NEDGGMGMLGO = 15;
    uint32 BIEPFFBBJHG = 295;
    uint32 EKKLCBKNAED = 1420;
    uint32 DPDNPCBNENI = 1788;
}

message ChallengeTierceRecord {
    uint32 total_score = 14;
    uint32 used_cycle_count = 15;
}

message ChallengeTierceRecordInfo {
    repeated ChallengeTierceStageRecord result_list = 4;
    repeated uint32 finished_target_list = 5;
    uint32 challenge_id = 6;
    bool is_passed = 10;
}

message ChallengeTierceReward {
    uint32 HEJANCCDGAP = 9;
    ItemList reward = 15;
}

message ChallengeTierceStageClear {
    repeated uint32 LICPEKHDJGK = 4;
    uint32 challenge_id = 13;
}

message ChallengeTierceStageData {
    uint32 IBECKONIICF = 1;
    uint32 score_id = 3;
    repeated BattleTarget battle_target_list = 7;
    uint32 stage_index = 9;
    BattleEndStatus end_status = 10;
    uint32 INLLMKEDGLC = 13;
    GLLFJFJBIBC lineup = 14;
}

message ChallengeTierceStageInfo {
    repeated uint32 peak_avatar_id_list = 1;
    repeated AvatarIdentifier lineup = 5;
    uint32 buff_id = 8;
    uint32 stage_index = 14;
}

message ChallengeTierceStageLineupInfo {
    uint32 buff_id = 5;
    repeated AvatarIdentifier lineup = 9;
}

message ChallengeTierceStageRecord {
    uint32 stage_index = 1;
    uint32 score_id = 6;
    uint32 INLLMKEDGLC = 8;
    uint32 IBECKONIICF = 11;
}

message ChallengeTierceSyncAllStage {
    repeated ChallengeTierceStageData GBMBAHHDONN = 1;
    uint32 challenge_id = 9;
    repeated ChallengeTierceReward DJOBNPIAEJP = 12;
    ChallengeTierceRecord EGEHLOPFELK = 15;
    repeated uint32 finished_target_list = 167;
    bool is_passed = 504;
}

message ChallengeTierceSyncNotify {
    oneof MMCGBGDJIPN {
        ChallengeTierceSyncSingleStage IANBCDJPDJF = 1;
        ChallengeTierceSyncAllStage DFNNKENBOEN = 12;
        ChallengeTierceStageClear IBFHHKHNEFL = 4;
        ChallengeTiercePendingStageSettle IIHFEDLHOPI = 14;
        ChallengeTierceMedal HNHCFJJNJCE = 5;
    }
}

message ChallengeTierceSyncSingleStage {
    ChallengeTierceStageData stage_data = 11;
    bool is_passed = 206;
    repeated uint32 finished_target_list = 1591;
}

message ConfirmChallengeTierceStageSettleCsReq {
    bool IOBCIMIPEOM = 14;
}

message ConfirmChallengeTierceStageSettleScRsp {
    uint32 retcode = 2;
}

message GetChallengeTierceControllerCsReq {
}

message GetChallengeTierceControllerScRsp {
    uint32 retcode = 7;
    ChallengeTierceChallengeInfo challenge_tierce_info = 12;
    ChallengeTierceRecordInfo OHPGEHKFABM = 15;
}

message GetChallengeTierceDataCsReq {
}

message GetChallengeTierceDataScRsp {
    repeated ChallengeTierceData challenge_info_list = 10;
    uint32 retcode = 12;
}

message LeaveChallengeTierceCsReq {
}

message LeaveChallengeTierceScRsp {
    uint32 retcode = 13;
}

message RestartChallengeTierceCsReq {
}

message RestartChallengeTierceScRsp {
    SceneInfo scene = 1;
    uint32 retcode = 11;
}

message SetChallengeTierceLineupCsReq {
    uint32 challenge_id = 7;
    repeated ChallengeTierceStageLineupInfo stage_info_list = 12;
}

message SetChallengeTierceLineupScRsp {
    uint32 retcode = 12;
}

message StartChallengeTierceCsReq {
    uint32 stage_index = 1;
    uint32 challenge_id = 3;
    bool is_single_stage = 13;
    repeated ChallengeTierceStageLineupInfo stage_info_list = 14;
}

message StartChallengeTierceNextStageCsReq {
}

message StartChallengeTierceNextStageScRsp {
    ChallengeTierceChallengeInfo challenge_tierce_info = 8;
    SceneInfo scene = 10;
    uint32 retcode = 12;
}

message StartChallengeTierceScRsp {
    uint32 retcode = 4;
    SceneInfo scene = 7;
    ChallengeTierceChallengeInfo challenge_tierce_info = 12;
}
