syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message SpaceZooBornCsReq {
    repeated uint32 MOAOBPPHLDC = 1;
    uint32 OPMPEGKMBPC = 6;
}

message SpaceZooDataCsReq {
}

message SpaceZooDeleteCatCsReq {
    repeated uint32 GBIEAFKKAPI = 2;
}

message SpaceZooMutateCsReq {
    uint32 unique_id = 1;
    uint32 item_id = 3;
}

message SpaceZooOpCatteryCsReq {
    uint32 FEPDLPHPHGI = 11;
    uint32 op_type = 12;
    uint32 OCKGDJCGKLH = 15;
}

message SpaceZooTakeCsReq {
    uint32 KIFKGLGCLEJ = 6;
}

message SpaceZooTakeScRsp {
    ItemList reward = 3;
    uint32 retcode = 12;
    uint32 KIFKGLGCLEJ = 15;
}
