syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "Common.proto";

message LineupSlotData {
    uint32 id = 7;
    uint32 slot = 10;
    uint32 assist_uid = 12;
    AvatarType avatar_type = 13;
}

message QuitLineupCsReq {
    AvatarType avatar_type = 1;
    uint32 base_avatar_id = 6;
    uint32 plane_id = 8;
    uint32 index = 9;
    ExtraLineupType extra_lineup_type = 14;
}

message ReplaceLineupCsReq {
    bool PLIEODDEEHG = 1;
    uint32 leader_slot = 2;
    bool HIAMAJKDIOO = 9;
    uint32 game_story_line_id = 10;
    uint32 plane_id = 11;
    repeated LineupSlotData lineup_slot_list = 13;
    uint32 index = 14;
    ExtraLineupType extra_lineup_type = 15;
}

message ReplaceLineupScRsp {
    uint32 OMDLCGEMBLA = 4;
    uint32 retcode = 14;
}

message SetLineupNameCsReq {
    string name = 4;
    uint32 index = 11;
}

message SwapLineupCsReq {
    uint32 ENBIBCPPLDC = 1;
    uint32 index = 4;
    ExtraLineupType extra_lineup_type = 8;
    uint32 MPIEGFCNBEN = 10;
    uint32 plane_id = 13;
}

message SwitchLineupIndexCsReq {
    uint32 index = 1;
}
