syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdAetherDivideType.proto";
import "Orphans.proto";

message AetherDivideRefreshEndlessCsReq {
}

message SetAetherDivideLineUpCsReq {
    OCCAABPFBLF lineup = 13;
}

message StartAetherDivideChallengeBattleCsReq {
    uint32 FDKFIOLMPHA = 6;
    uint32 challenge_id = 15;
}

message StartAetherDivideSceneBattleCsReq {
    repeated AssistMonsterEntityInfo assist_monster_entity_info = 1;
    uint32 skill_index = 5;
    uint32 attacked_by_entity_id = 6;
    uint32 cast_entity_id = 7;
    repeated uint32 assist_monster_entity_id_list = 10;
}

message StartAetherDivideStageBattleCsReq {
    uint32 event_id = 12;
}

message SwitchAetherDivideLineUpSlotCsReq {
    uint32 FDKFIOLMPHA = 3;
}
