syntax = "proto3";

option csharp_namespace = "March7thHoney.Proto";

import "CmdChessRogueType.proto";

message ChessRogueEnterCsReq {
    uint32 id = 4;
}

message ChessRogueGiveUpCsReq {
}

enum ChessRogueNousDicePhase {
    PKCGJHNMLPK_NLCDGIPGFDJ = 0;
    PKCGJHNMLPK_HJBHKCJEEEE = 1;
    PKCGJHNMLPK_GAIALIOPEPC = 2;
}

message ChessRogueNousEditDiceCsReq {
    HGCIAPKELAF IOCCACNJIGD = 14;
}

message ChessRogueNousEnableRogueTalentCsReq {
    uint32 CKHCLKOALKE = 8;
}

message SelectChessRogueSubStoryCsReq {
    uint32 rogue_dialogue_event_id = 10;
    uint32 HONCDMKPBEG = 12;
}
